classdef HiveInventoryTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 parity tests for apps.borg.hive.

    methods (Test)
        function completeApiInventory(testCase)
            root = "kssolv.analysis.matgenlab.apps.borg.";
            classes = ["AbstractDrone", "VaspToComputedEntryDrone", ...
                "SimpleVaspToComputedEntryDrone", ...
                "GaussianToComputedEntryDrone"];
            for name = classes
                testCase.verifyNotEmpty(which(root + name));
            end
            verifyMembers(testCase, root + "AbstractDrone", ...
                ["assimilate", "get_valid_paths"]);
            verifyMembers(testCase, root + "VaspToComputedEntryDrone", ...
                ["assimilate", "get_valid_paths", "as_dict", "from_dict"]);
            verifyMembers(testCase, root + ...
                "SimpleVaspToComputedEntryDrone", ...
                ["assimilate", "as_dict", "from_dict"]);
            verifyMembers(testCase, root + ...
                "GaussianToComputedEntryDrone", ...
                ["assimilate", "get_valid_paths", "as_dict", "from_dict"]);
        end

        function vaspOfficialFixtureParity(testCase)
            oracle = loadOracle();
            fixtures = fixtureDirectory();
            drone = kssolv.analysis.matgenlab.apps.borg. ...
                VaspToComputedEntryDrone("data", {"efermi"});
            entry = drone.assimilate(fixtures);
            expected = oracle.entries.vasp;
            testCase.verifyClass(entry, ...
                "kssolv.analysis.matgenlab.core.ComputedEntry");
            testCase.verifyEqual(entry.reduced_formula, ...
                string(expected.formula));
            testCase.verifyEqual(entry.energy, expected.energy, ...
                AbsTol = 1e-10);
            testCase.verifyEqual(entry.data.efermi, ...
                expected.data.efermi, AbsTol = 1e-10);
            testCase.verifyEqual(entry.parameters.run_type, ...
                string(expected.parameters.run_type));
            testCase.verifyFalse(entry.parameters.is_hubbard);
            testCase.verifyEqual(entry.parameters.potcar_symbols, ...
                expected.parameters.potcar_symbols.');

            structureDrone = kssolv.analysis.matgenlab.apps.borg. ...
                VaspToComputedEntryDrone(true);
            structureEntry = structureDrone.assimilate(fixtures);
            testCase.verifyClass(structureEntry, ...
                "kssolv.analysis.matgenlab.core.ComputedStructureEntry");
            testCase.verifyEqual(structureEntry.energy, ...
                oracle.entries.vasp_structure.energy, AbsTol = 1e-10);
            testCase.verifyEqual(structureEntry.structure.num_sites, 1);
        end

        function vaspPathRules(testCase)
            fixtures = fixtureDirectory();
            drone = kssolv.analysis.matgenlab.apps.borg. ...
                VaspToComputedEntryDrone();
            paths = drone.get_valid_paths( ...
                {fixtures, {"+simple_vasp"}, ...
                {"vasprun.xml.xe.gz", "methane.log"}});
            testCase.verifyEqual(paths, fixtures);

            temporary = string(tempname);
            mkdir(temporary);
            cleanup = onCleanup(@()rmdir(temporary, "s"));
            mkdir(fullfile(temporary, "relax1"));
            mkdir(fullfile(temporary, "relax2"));
            testCase.verifyEqual(drone.get_valid_paths( ...
                {temporary, {"relax1", "relax2"}, {}}), temporary);
            testCase.verifyEmpty(drone.get_valid_paths( ...
                {fullfile(temporary, "relax1"), {}, {}}));
            clear cleanup
        end

        function vaspSerializationParity(testCase)
            oracle = loadOracle();
            drone = kssolv.analysis.matgenlab.apps.borg. ...
                VaspToComputedEntryDrone(true);
            value = drone.as_dict();
            expected = oracle.drone_dicts.vasp_structure;
            testCase.verifyEqual(value.x_module, ...
                string(expected.x_module));
            testCase.verifyEqual(value.x_class, ...
                string(expected.x_class));
            testCase.verifyEqual(sort(string(value.init_args.parameters)), ...
                sort(reshape(string(expected.init_args.parameters), 1, [])));
            restored = kssolv.analysis.matgenlab.apps.borg. ...
                VaspToComputedEntryDrone.from_dict(value);
            testCase.verifyTrue(restored.inc_structure);
            testCase.verifyEqual(sort(restored.parameters), ...
                sort(drone.parameters));
            testCase.verifyEqual(string(drone), ...
                string(oracle.strings.vasp));
        end

        function simpleVaspNativeParity(testCase)
            oracle = loadOracle();
            directory = fullfile(fixtureDirectory(), "+simple_vasp");
            drone = kssolv.analysis.matgenlab.apps.borg. ...
                SimpleVaspToComputedEntryDrone(true);
            entry = drone.assimilate(directory);
            expected = oracle.entries.simple_structure;
            testCase.verifyClass(entry, ...
                "kssolv.analysis.matgenlab.core.ComputedStructureEntry");
            testCase.verifyEqual(entry.reduced_formula, ...
                string(expected.formula));
            testCase.verifyEqual(entry.energy, expected.energy, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(entry.data.delta_volume, ...
                expected.data.delta_volume, AbsTol = 1e-14);
            testCase.verifyEqual(entry.structure.lattice.matrix, ...
                expected.lattice, AbsTol = 1e-14);
            testCase.verifyEqual(entry.structure.frac_coords, ...
                expected.frac_coords, AbsTol = 1e-14);
            testCase.verifyFalse(entry.parameters.is_hubbard);
            testCase.verifyEqual(numel(entry.parameters.potcar_spec), 1);
            testCase.verifyError(@()drone.assimilate(fixtureDirectory()), ...
                "KSSOLV:Matgenlab:Borg:MissingVaspFiles");

            restored = kssolv.analysis.matgenlab.apps.borg. ...
                SimpleVaspToComputedEntryDrone.from_dict(drone.as_dict());
            testCase.verifyTrue(restored.inc_structure);
            testCase.verifyEqual(string(drone), ...
                string(oracle.strings.simple));
        end

        function gaussianOfficialFixtureParity(testCase)
            oracle = loadOracle();
            filename = fullfile(fixtureDirectory(), "methane.log");
            drone = kssolv.analysis.matgenlab.apps.borg. ...
                GaussianToComputedEntryDrone( ...
                "data", {"corrections"});
            entry = drone.assimilate(filename);
            expected = oracle.entries.gaussian;
            testCase.verifyClass(entry, ...
                "kssolv.analysis.matgenlab.core.ComputedEntry");
            testCase.verifyEqual(entry.reduced_formula, ...
                string(expected.formula));
            testCase.verifyEqual(entry.energy, expected.energy, ...
                AbsTol = 1e-10);
            testCase.verifyEqual(entry.parameters.functional, ...
                string(expected.parameters.functional));
            testCase.verifyEqual(entry.parameters.basis_set, ...
                string(expected.parameters.basis_set));
            testCase.verifyEqual(entry.parameters.charge, ...
                expected.parameters.charge);
            testCase.verifyEqual(entry.parameters.spin_multiplicity, ...
                expected.parameters.spin_multiplicity);
            testCase.verifyTrue(isKey( ...
                entry.parameters.route_parameters, "opt"));
            testCase.verifyEqual(entry.data.stationary_type, ...
                string(expected.data.stationary_type));
            testCase.verifyTrue(entry.data.properly_terminated);

            structureDrone = kssolv.analysis.matgenlab.apps.borg. ...
                GaussianToComputedEntryDrone(true);
            structureEntry = structureDrone.assimilate(filename);
            expectedStructure = oracle.entries.gaussian_structure;
            testCase.verifyClass(structureEntry, ...
                "kssolv.analysis.matgenlab.core.ComputedStructureEntry");
            testCase.verifyEqual(structureEntry.structure.cart_coords, ...
                expectedStructure.cart_coords, AbsTol = 1e-9);
        end

        function gaussianPathsAndSerialization(testCase)
            oracle = loadOracle();
            drone = kssolv.analysis.matgenlab.apps.borg. ...
                GaussianToComputedEntryDrone( ...
                "file_extensions", {".log", ".out"});
            paths = drone.get_valid_paths( ...
                {"/tmp", {}, {"methane.log", "job.out", ...
                "notes.txt", "upper.LOG"}});
            [~, names, extensions] = arrayfun(@fileparts, paths, ...
                "UniformOutput", false);
            actual = string(names) + string(extensions);
            testCase.verifyEqual(actual, ...
                string(oracle.valid_paths.gaussian).');

            value = drone.as_dict();
            restored = kssolv.analysis.matgenlab.apps.borg. ...
                GaussianToComputedEntryDrone.from_dict(value);
            testCase.verifyEqual(restored.file_extensions, ...
                [".log", ".out"]);
            testCase.verifyEqual(sort(restored.parameters), ...
                sort(drone.parameters));
            testCase.verifyEqual(string(drone), ...
                string(oracle.strings.gaussian));
        end
    end
end

function verifyMembers(testCase, className, methodNames)
available = string(methods(char(className)));
for name = reshape(string(methodNames), 1, [])
    testCase.verifyTrue(any(available == name), ...
        "Missing method " + className + "." + name);
end
end

function directory = fixtureDirectory()
directory = string(fullfile(fileparts(mfilename("fullpath")), "+fixtures"));
end

function value = loadOracle()
root = string(fileparts(mfilename("fullpath")));
for index = 1:6
    root = string(fileparts(root));
end
filename = fullfile(root, "dev", "matgenlab", "oracles", ...
    "apps_borg_hive_2026.5.4.json");
value = jsondecode(fileread(filename));
end
