classdef FragmentCommands
    %FRAGMENTCOMMANDS Molecular fragment library editing commands.
    methods (Static)
        function ids = commandIds()
            ids = ["attach_fragment"; "save_user_fragment"];
        end
        function value = supports(commandId)
            value = any(kssolv.modeling.fragments.FragmentCommands. ...
                commandIds() == string(commandId));
        end
        function result = execute(model, commandId, parameters)
            import kssolv.modeling.ParameterUtils
            commandId = string(commandId);
            switch commandId
                case "attach_fragment"
                    indices = ParameterUtils.indices(parameters, ...
                        model.num_sites, []);
                    name = string(ParameterUtils.get(parameters, ...
                        "fragmentName", "Methyl"));
                    head = double(ParameterUtils.get(parameters, ...
                        "fragmentIndex", 1));
                    portId = string(ParameterUtils.get(parameters, ...
                        "portId", ""));
                    if isempty(indices)
                        error("KSSOLV:Modeling:FragmentSelection", ...
                            "Select the host atoms required by the fragment port.");
                    end
                    order = double(ParameterUtils.get(parameters, ...
                        "bondOrder", NaN));
                    storePath = string(ParameterUtils.get(parameters, ...
                        "storePath", ""));
                    [model, metadata] = kssolv.modeling.fragments. ...
                        FragmentLibrary.attach(model, name, indices, ...
                        fragmentIndex = head, bondOrder = order, ...
                        portId = portId, ...
                        storePath = storePath);
                    result = struct("model", model, "changed", true, ...
                        "message", "Fragment attached.", ...
                        "analysis", metadata);
                case "save_user_fragment"
                    name = string(ParameterUtils.get(parameters, ...
                        "fragmentName", "User Fragment"));
                    storePath = string(ParameterUtils.get(parameters, ...
                        "storePath", ""));
                    overwrite = ParameterUtils.logical(parameters, ...
                        "overwrite", false);
                    kssolv.modeling.fragments.FragmentLibrary.saveUser( ...
                        name, model, storePath = storePath, ...
                        overwrite = overwrite);
                    result = struct("model", model, "changed", false, ...
                        "message", "User fragment saved.");
                otherwise
                    error("KSSOLV:Modeling:FragmentCommand", ...
                        "Unsupported fragment command '%s'.", commandId);
            end
        end
    end
end
