classdef AboutDialog < controllib.ui.internal.dialog.AbstractDialog
    %ABOUTDIALOG 显示 KSSOLV Toolbox 的产品和版本信息。

    % 开发者：杨柳
    % 版权 2026 合肥瀚海量子科技有限公司

    properties (SetAccess = private)
        widgets = struct()
    end

    properties (Access = private)
        width = 570
        height = 206
    end

    methods
        function this = AboutDialog()
            import kssolv.ui.util.Localizer.message

            this.Title = message('KSSOLV:dialogs:AboutDialogTitle');
            this.CloseMode = 'hide';

            fig = this.getWidget();
            fig.CloseRequestFcn = @(~, ~) close(this);
        end
    end

    methods (Access = protected)
        function buildUI(this)
            import kssolv.ui.util.Localizer.message

            fig = this.getWidget();
            fig.Position(3:4) = [this.width this.height];

            layout = uigridlayout(fig, [6 1], ...
                'Scrollable', 'off', ...
                'RowHeight', {'fit', 'fit', 'fit', 'fit', 'fit', 'fit'}, ...
                'ColumnWidth', {'1x'}, ...
                'RowSpacing', 10, ...
                'Padding', [14 6 14 12]);

            titleLayout = uigridlayout(layout, [1 3], ...
                'RowHeight', {'fit'}, ...
                'ColumnWidth', {'1x', 'fit', '1x'}, ...
                'Padding', 0);
            titleLayout.Layout.Row = 1;
            productName = uilabel(titleLayout, ...
                'Text', [' ' char(KSSOLV_Toolbox.Name) ' '], ...
                'HorizontalAlignment', 'center', ...
                'FontSize', 30, ...
                'FontWeight', 'bold', ...
                'FontColor', [0.043 0.165 0.290]);
            productName.Layout.Column = 2;

            versionText = uilabel(layout, ...
                'Text', sprintf(message('KSSOLV:dialogs:AboutDialogVersion'), ...
                char(KSSOLV_Toolbox.Version), ...
                char(KSSOLV_Toolbox.ReleaseDate)), ...
                'HorizontalAlignment', 'center', ...
                'FontSize', 15, ...
                'FontWeight', 'bold');
            versionText.Layout.Row = 2;

            description = uilabel(layout, ...
                'Text', char(KSSOLV_Toolbox.Description), ...
                'HorizontalAlignment', 'center', ...
                'WordWrap', 'on', ...
                'FontSize', 13);
            description.Layout.Row = 3;

            schemaText = uilabel(layout, ...
                'Text', sprintf(message( ...
                'KSSOLV:dialogs:AboutDialogModelingSchema'), ...
                KSSOLV_Toolbox.ModelingSchemaVersion, ...
                char(KSSOLV_Toolbox.BuildChannel), char(version('-release'))), ...
                'HorizontalAlignment', 'center', ...
                'FontColor', [0.25 0.35 0.45]);
            schemaText.Layout.Row = 4;

            copyrightText = uilabel(layout, ...
                'Text', sprintf(message('KSSOLV:dialogs:AboutDialogCopyright'), ...
                char(KSSOLV_Toolbox.AuthorCompany)), ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'top', ...
                'WordWrap', 'on', ...
                'FontColor', [0.35 0.35 0.35]);
            copyrightText.Layout.Row = 5;

            buttonLayout = uigridlayout(layout, [1 3], ...
                'RowHeight', {'fit'}, ...
                'ColumnWidth', {'fit', '1x', 'fit'}, ...
                'Padding', 0);
            buttonLayout.Layout.Row = 6;

            repositoryButton = uibutton(buttonLayout, ...
                'Text', message('KSSOLV:dialogs:AboutDialogRepositoryButton'), ...
                'ButtonPushedFcn', @(~, ~) web(KSSOLV_Toolbox.CodeRepository));
            repositoryButton.Layout.Column = 1;

            closeButton = uibutton(buttonLayout, ...
                'Text', message('KSSOLV:dialogs:DialogCloseButton'), ...
                'ButtonPushedFcn', @(~, ~) close(this));
            closeButton.Layout.Column = 3;

            this.widgets.ProductName = productName;
            this.widgets.ModelingSchema = schemaText;
            this.widgets.RepositoryButton = repositoryButton;
            this.widgets.CloseButton = closeButton;
        end
    end
end
