classdef LammpsData < kssolv.analysis.matgenlab.util.MSONable
    %#ok<*ALIGN,*AGROW>
    %LAMMPSDATA Native MATLAB model/parser/writer for LAMMPS data files.
    properties
        box
        masses table
        atoms table
        velocities = []
        force_field = []
        topology = []
        atom_style = "full"
    end
    properties (Dependent)
        structure
    end
    methods
        function obj=LammpsData(box,masses,atoms,velocities,force_field,topology,atom_style)
            if nargin<4, velocities=[]; end
            if nargin<5, force_field=[]; end
            if nargin<6, topology=[]; end
            if nargin<7, atom_style="full"; end
            obj.box=box; obj.masses=masses; obj.atoms=atoms;
            obj.velocities=velocities; obj.force_field=force_field;
            obj.topology=topology; obj.atom_style=string(atom_style);
        end
        function s=get.structure(obj)
            types=obj.atoms.type; mass=obj.masses.mass;
            elems=kssolv.analysis.matgenlab.core.Element.all();
            emass=cellfun(@(e)double(e.atomic_mass),elems);
            labels=strings(height(obj.atoms),1);
            for k=1:height(obj.atoms)
                [~,j]=min(abs(emass-mass(types(k))));
                labels(k)=string(elems{j}.symbol);
            end
            coords=obj.atoms{:,{'x','y','z'}}-obj.box.bounds(:,1)';
            props=struct();
            if any(strcmp(obj.atoms.Properties.VariableNames,'q')), props.charge=obj.atoms.q; end
            if ~isempty(obj.velocities)
                velocityArray=table2array(obj.velocities);
                props.velocities=mat2cell(velocityArray,ones(size(velocityArray,1),1),3);
            end
            s=kssolv.analysis.matgenlab.core.Structure(obj.box.to_lattice(), ...
                cellstr(labels),coords,coords_are_cartesian=true,site_properties=props);
        end
        function text=get_str(obj,distance,velocity,charge,hybrid) %#ok<INUSD>
            if nargin<2, distance=6; end
            if nargin<3, velocity=8; end
            if nargin<4, charge=4; end
            countNames={'atoms'}; countValues=height(obj.atoms);
            topoNames={'Bonds','Angles','Dihedrals','Impropers'};
            for k=1:numel(topoNames)
                if isa(obj.topology,'containers.Map')&&isKey(obj.topology,topoNames{k})
                    countNames{end+1}=lower(topoNames{k});
                    countValues(end+1)=height(obj.topology(topoNames{k}));
                end
            end
            typeNames={'atom'}; typeValues=height(obj.masses);
            coeffNames={'Bond Coeffs','Angle Coeffs','Dihedral Coeffs','Improper Coeffs'};
            for k=1:numel(coeffNames)
                if isa(obj.force_field,'containers.Map')&&isKey(obj.force_field,coeffNames{k})
                    typeNames{end+1}=lower(extractBefore(coeffNames{k},' '));
                    typeValues(end+1)=height(obj.force_field(coeffNames{k}));
                end
            end
            vals=[countValues,typeValues];
            width=strlength(string(max(vals)));
            lines="Generated by pymatgen.io.lammps.data.LammpsData"+newline+newline;
            for k=1:numel(countNames), lines=lines+sprintf("%*d  %s\n",width,countValues(k),countNames{k}); end
            lines=lines+newline;
            for k=1:numel(typeNames), lines=lines+sprintf("%*d  %s types\n",width,typeValues(k),typeNames{k}); end
            lines=lines+newline+string(obj.box.get_str(distance))+newline+newline;
            order={'Masses','Pair Coeffs','PairIJ Coeffs','Bond Coeffs','Angle Coeffs', ...
                'Dihedral Coeffs','Improper Coeffs','BondBond Coeffs','BondAngle Coeffs', ...
                'MiddleBondTorsion Coeffs','EndBondTorsion Coeffs','AngleTorsion Coeffs', ...
                'AngleAngleTorsion Coeffs','BondBond13 Coeffs','AngleAngle Coeffs', ...
                'Atoms','Velocities','Bonds','Angles','Dihedrals','Impropers'};
            for k=1:numel(order)
                name=order{k}; tab=[];
                if strcmp(name,'Masses'), tab=obj.masses;
                elseif strcmp(name,'Atoms'), tab=obj.atoms;
                elseif strcmp(name,'Velocities'), tab=obj.velocities;
                elseif isa(obj.force_field,'containers.Map')&&isKey(obj.force_field,name), tab=obj.force_field(name);
                elseif isa(obj.topology,'containers.Map')&&isKey(obj.topology,name), tab=obj.topology(name);
                end
                if isempty(tab), continue; end
                lines=lines+name+newline+newline;
                includeId=~strcmp(name,'PairIJ Coeffs');
                lines=lines+obj.formatTable(tab,includeId,distance,velocity,charge)+newline;
            end
            text=char(lines);
        end
        function write_file(obj,filename,distance,velocity,charge)
            if nargin<3, distance=6; end
            if nargin<4, velocity=8; end
            if nargin<5, charge=4; end
            fid=fopen(filename,'w'); cleanup=onCleanup(@()fclose(fid));
            fwrite(fid,obj.get_str(distance,velocity,charge));
        end
        function [box,ff,topologies]=disassemble(obj,atom_labels,guess_element,ff_label)
            if nargin<3||isempty(guess_element), guess_element=true; end
            if nargin<4||isempty(ff_label), ff_label='ff_map'; end
            if nargin<2||isempty(atom_labels)
                atom_labels=cell(height(obj.masses),1);
                elems=kssolv.analysis.matgenlab.core.Element.all();
                emass=cellfun(@(e)double(e.atomic_mass),elems);
                for k=1:height(obj.masses)
                    if guess_element
                        [~,j]=min(abs(emass-obj.masses.mass(k))); base=string(elems{j}.symbol);
                    else, base="Q"; end
                    atom_labels{k}=char(base+string(k));
                end
            end
            nonbond=[]; topoCoeffs=struct();
            if isa(obj.force_field,'containers.Map')
                if isKey(obj.force_field,'Pair Coeffs'), nonbond=table2array(obj.force_field('Pair Coeffs'));
                elseif isKey(obj.force_field,'PairIJ Coeffs')
                    t=obj.force_field('PairIJ Coeffs'); nonbond=table2array(t(:,3:end)); end
                kinds={'Bond','Angle','Dihedral','Improper'};
                class2={{}, {'BondBond Coeffs','BondAngle Coeffs'}, ...
                    {'MiddleBondTorsion Coeffs','EndBondTorsion Coeffs','AngleTorsion Coeffs', ...
                    'AngleAngleTorsion Coeffs','BondBond13 Coeffs'}, {'AngleAngle Coeffs'}};
                for k=1:numel(kinds)
                    key=[kinds{k} ' Coeffs'];
                    if isKey(obj.force_field,key)
                        coeffTable=obj.force_field(key); vals=table2cell(coeffTable);
                        entries=cell(height(coeffTable),1);
                        for j=1:numel(entries)
                            coeffValues=vals(j,:);
                            if all(cellfun(@isnumeric,coeffValues)), coeffValues=cell2mat(coeffValues); end
                            entries{j}=struct('coeffs',coeffValues,'types',{{}});
                            for ci=1:numel(class2{k})
                                auxiliaryKey=class2{k}{ci};
                                if isKey(obj.force_field,auxiliaryKey)
                                    field=matlab.lang.makeValidName(auxiliaryKey);
                                    auxiliaryTable=obj.force_field(auxiliaryKey);
                                    entries{j}.(field)=table2array(auxiliaryTable(j,:));
                                end
                            end
                        end
                        topologyKey=[kinds{k} 's'];
                        if isa(obj.topology,'containers.Map')&&isKey(obj.topology,topologyKey)
                            topTable=obj.topology(topologyKey);
                            atomColumns=startsWith(topTable.Properties.VariableNames,'atom');
                            for row=1:height(topTable)
                                typeIndex=topTable.type(row);
                                ids=topTable{row,atomColumns};
                                tuple=atom_labels(obj.atoms.type(ids));
                                entries{typeIndex}.types{end+1}=tuple;
                            end
                        end
                        topoCoeffs.(matlab.lang.makeValidName(key))=entries;
                    end
                end
            end
            massInfo=[atom_labels,num2cell(obj.masses.mass)];
            ff=kssolv.analysis.matgenlab.io.lammps.ForceField(massInfo,nonbond,topoCoeffs);
            molIDs=ones(height(obj.atoms),1);
            if any(strcmp(obj.atoms.Properties.VariableNames,'molecule_ID')), molIDs=obj.atoms.molecule_ID; end
            ids=unique(molIDs,'stable'); topologies=cell(1,numel(ids));
            for j=1:numel(ids)
                rows=molIDs==ids(j); labels=atom_labels(obj.atoms.type(rows));
                coords=obj.atoms{rows,{'x','y','z'}};
                species=cell(size(labels));
                for si=1:numel(labels)
                    token=regexp(labels{si},'^[A-Z][a-z]?','match','once');
                    if isempty(token), token='H'; end
                    species{si}=token;
                end
                siteProperties=struct(); siteProperties.(char(ff_label))=labels;
                mol=kssolv.analysis.matgenlab.core.Molecule(species,coords,site_properties=siteProperties);
                charges=[]; if any(strcmp(obj.atoms.Properties.VariableNames,'q')), charges=obj.atoms.q(rows); end
                vel=[]; if ~isempty(obj.velocities), vel=table2array(obj.velocities(rows,:)); end
                tops=struct(); globalIds=find(rows);
                if ~isempty(obj.atoms.Properties.RowNames), globalIds=str2double(obj.atoms.Properties.RowNames(rows)); end
                if isa(obj.topology,'containers.Map')
                    topologyKeys=obj.topology.keys;
                    for tk=1:numel(topologyKeys)
                        topTable=obj.topology(topologyKeys{tk});
                        atomColumns=startsWith(topTable.Properties.VariableNames,'atom');
                        atomIds=topTable{:,atomColumns};
                        keep=all(ismember(atomIds,globalIds),2);
                        if any(keep)
                            [~,local]=ismember(atomIds(keep,:),globalIds);
                            tops.(topologyKeys{tk})=local-1;
                        end
                    end
                end
                topologies{j}=kssolv.analysis.matgenlab.io.lammps.Topology(mol, ...
                    ff_label=ff_label,charges=charges,velocities=vel,topologies=tops);
            end
            box=obj.box;
        end
        function obj=set_charge_atom(obj,charges)
            if isa(charges,'containers.Map'), keys=charges.keys;
                for k=1:numel(keys)
                    atomId=keys{k}; if ischar(atomId)||isstring(atomId), atomId=str2double(atomId); end
                    row=atomId;
                    if ~isempty(obj.atoms.Properties.RowNames)
                        row=find(str2double(obj.atoms.Properties.RowNames)==atomId,1);
                    end
                    obj.atoms.q(row)=charges(keys{k});
                end
            elseif isstruct(charges)
                names=fieldnames(charges);
                for k=1:numel(names), obj.atoms.q(str2double(erase(names{k},'x')))=charges.(names{k}); end
            end
        end
        function obj=set_charge_atom_type(obj,charges)
            if isa(charges,'containers.Map'), keys=charges.keys;
                for k=1:numel(keys)
                    atomType=keys{k};
                    if ischar(atomType)||isstring(atomType)
                        text=string(atomType); number=str2double(text);
                        if isnan(number)
                            mass=kssolv.analysis.matgenlab.core.Element(text).atomic_mass;
                            atomType=find(abs(obj.masses.mass-mass)<1e-5,1);
                        else, atomType=number; end
                    end
                    obj.atoms.q(obj.atoms.type==atomType)=charges(keys{k});
                end
            elseif isstruct(charges)
                names=fieldnames(charges);
                for k=1:numel(names)
                    text=string(erase(names{k},'x'));
                    atomType=str2double(text);
                    if isnan(atomType)
                        mass=kssolv.analysis.matgenlab.core.Element(text).atomic_mass;
                        atomType=find(abs(obj.masses.mass-mass)<1e-5,1);
                    end
                    obj.atoms.q(obj.atoms.type==atomType)=charges.(names{k});
                end
            end
        end
        function d=asDict(obj)
            d=struct('box',obj.box.as_dict(),'masses',obj.masses,'atoms',obj.atoms, ...
                'velocities',obj.velocities,'force_field',obj.force_field, ...
                'topology',obj.topology,'atom_style',obj.atom_style);
        end
    end
    methods (Static)
        function obj=from_file(filename,atom_style,sort_id)
            if nargin<2, atom_style="full"; end
            if nargin<3, sort_id=false; end
            text=kssolv.analysis.matgenlab.io.lammps.read_text(filename);
            lines=splitlines(string(text));
            titles={'Masses','Pair Coeffs','PairIJ Coeffs','Bond Coeffs','Angle Coeffs', ...
                'Dihedral Coeffs','Improper Coeffs','BondBond Coeffs','BondAngle Coeffs', ...
                'MiddleBondTorsion Coeffs','EndBondTorsion Coeffs','AngleTorsion Coeffs', ...
                'AngleAngleTorsion Coeffs','BondBond13 Coeffs','AngleAngle Coeffs', ...
                'Atoms','Velocities','Bonds','Angles','Dihedrals','Impropers'};
            marks=[]; markNames={};
            for k=1:numel(lines)
                base=strtrim(extractBefore(lines(k)+" #"," #"));
                j=find(strcmp(base,titles),1);
                if ~isempty(j), marks(end+1)=k; markNames{end+1}=titles{j}; end
            end
            header=lines(1:marks(1)-1); bounds=zeros(3,2); got=false(3,1); tilt=[];
            for k=1:numel(header)
                t=regexp(header(k),'^\s*([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+([xyz])lo\s+\3hi','tokens','once');
                if ~isempty(t), j=find('xyz'==t{3}); bounds(j,:)=[str2double(t{1}) str2double(t{2})]; got(j)=true; end
                t=regexp(header(k),'^\s*([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+xy xz yz','tokens','once');
                if ~isempty(t), tilt=cellfun(@str2double,t); end
            end
            if any(~got), bounds(~got,:)=repmat([-.5 .5],sum(~got),1); end
            box=kssolv.analysis.matgenlab.io.lammps.LammpsBox(bounds,tilt);
            sections=containers.Map('KeyType','char','ValueType','any');
            for q=1:numel(marks)
                last=numel(lines); if q<numel(marks), last=marks(q+1)-1; end
                body=lines(marks(q)+1:last); body=strtrim(body);
                body(body==""|startsWith(body,"#"))=[];
                clean=strings(0,1);
                for z=1:numel(body)
                    line=strtrim(extractBefore(body(z)+"#","#"));
                    if line~="", clean(end+1)=line; end
                end
                sections(markNames{q})=kssolv.analysis.matgenlab.io.lammps.LammpsData. ...
                    parseSection(markNames{q},clean,atom_style,sort_id);
            end
            masses=sections('Masses'); atoms=sections('Atoms'); velocities=[];
            if isKey(sections,'Velocities'), velocities=sections('Velocities'); end
            ff=containers.Map('KeyType','char','ValueType','any'); topo=containers.Map('KeyType','char','ValueType','any');
            ks=sections.keys;
            for k=1:numel(ks)
                if contains(ks{k},'Coeff'), ff(ks{k})=sections(ks{k});
                elseif ismember(ks{k},{'Bonds','Angles','Dihedrals','Impropers'}), topo(ks{k})=sections(ks{k}); end
            end
            if ff.Count==0, ff=[]; end
            if topo.Count==0, topo=[]; end
            obj=kssolv.analysis.matgenlab.io.lammps.LammpsData(box,masses,atoms,velocities,ff,topo,atom_style);
        end
        function obj=from_structure(structure,ff_elements,atom_style,is_sort)
            if nargin<2, ff_elements=[]; end
            if nargin<3, atom_style="charge"; end
            if nargin<4, is_sort=false; end
            [box,op]=kssolv.analysis.matgenlab.io.lammps.lattice_2_lmpbox(structure.lattice);
            labels=strings(structure.num_sites,1);
            for k=1:structure.num_sites, labels(k)=structure.sites{k}.species_string; end
            props=structure.site_properties; order=(1:structure.num_sites)';
            if is_sort, [labels,order]=sort(labels); end
            coords=structure.cart_coords(order,:);
            rotated=op.operate_multi(coords);
            elems=sort(unique([string(structure.symbol_set),string(ff_elements)])); mass=zeros(numel(elems),1);
            for k=1:numel(elems), mass(k)=kssolv.analysis.matgenlab.core.Element(elems(k)).atomic_mass; end
            masses=table(mass,'VariableNames',{'mass'}); masses.Properties.RowNames=cellstr(string(1:numel(elems)));
            [~,type]=ismember(labels,elems);
            q=zeros(numel(type),1);
            if isfield(props,'charge')
                values=props.charge; if iscell(values), values=cell2mat(values); end
                q=double(values(order)); q=q(:);
            end
            switch string(atom_style)
                case "atomic", atoms=table(type,rotated(:,1),rotated(:,2),rotated(:,3),'VariableNames',{'type','x','y','z'});
                case "charge", atoms=table(type,q,rotated(:,1),rotated(:,2),rotated(:,3),'VariableNames',{'type','q','x','y','z'});
                otherwise, atoms=table(ones(numel(type),1),type,q,rotated(:,1),rotated(:,2),rotated(:,3), ...
                        'VariableNames',{'molecule_ID','type','q','x','y','z'});
            end
            atoms.Properties.RowNames=cellstr(string(1:height(atoms)));
            velocities=[];
            if isfield(props,'velocities')
                values=props.velocities; if iscell(values), values=vertcat(values{:}); end
                values=double(values(order,:))*op.rotation_matrix.';
                velocities=array2table(values,'VariableNames',{'vx','vy','vz'});
                velocities.Properties.RowNames=atoms.Properties.RowNames;
            end
            obj=kssolv.analysis.matgenlab.io.lammps.LammpsData(box,masses,atoms,velocities,[],[],atom_style);
        end
        function obj=from_molecule(molecule,box_or_lattice,varargin)
            if isa(box_or_lattice,'kssolv.analysis.matgenlab.io.lammps.LammpsBox'), box=box_or_lattice;
            elseif isa(box_or_lattice,'kssolv.analysis.matgenlab.core.Lattice'), box=kssolv.analysis.matgenlab.io.lammps.lattice_2_lmpbox(box_or_lattice);
            else, box=kssolv.analysis.matgenlab.io.lammps.LammpsBox([zeros(3,1),double(box_or_lattice(:))]); end
            lattice=box.to_lattice(); s=kssolv.analysis.matgenlab.core.Structure(lattice, ...
                molecule.species,molecule.cart_coords,coords_are_cartesian=true, ...
                site_properties=molecule.site_properties);
            obj=kssolv.analysis.matgenlab.io.lammps.LammpsData.from_structure(s,varargin{:});
        end
        function obj=from_ff_and_topologies(box,ff,topologies,atom_style)
            if nargin<4, atom_style="full"; end
            coords=[]; labels=strings(0,1); mol=[]; charges=[]; velocities=[];
            topologyRows=containers.Map('KeyType','char','ValueType','any');
            atomShift=0; topologyNames={'Bonds','Angles','Dihedrals','Impropers'};
            for k=1:numel(topologies)
                if iscell(topologies), t=topologies{k}; else, t=topologies(k); end
                coords=[coords;t.sites.cart_coords];
                labels=[labels;string(t.type_by_sites(:))]; mol=[mol;repmat(k,numel(t.type_by_sites),1)];
                if isempty(t.charges), charges=[charges;zeros(numel(t.type_by_sites),1)]; else, charges=[charges;t.charges(:)]; end
                if ~isempty(t.velocities), velocities=[velocities;t.velocities]; end
                if isstruct(t.topologies)
                    for ti=1:numel(topologyNames)
                        key=topologyNames{ti};
                        if ~isfield(t.topologies,key), continue; end
                        atomIds=double(t.topologies.(key))+atomShift+1;
                        mapper=ff.maps(key); types=zeros(size(atomIds,1),1); keep=true(size(types));
                        for row=1:size(atomIds,1)
                            local=double(t.topologies.(key)(row,:))+1;
                            typeKey=char(join(string(t.type_by_sites(local)),'|'));
                            if isKey(mapper,typeKey), types(row)=mapper(typeKey); else, keep(row)=false; end
                        end
                        rows=[types(keep),atomIds(keep,:)];
                        if isKey(topologyRows,key), topologyRows(key)=[topologyRows(key);rows];
                        else, topologyRows(key)=rows; end
                    end
                end
                atomShift=atomShift+t.sites.num_sites;
            end
            type=zeros(numel(labels),1);
            map=ff.maps('Atoms'); for k=1:numel(labels), type(k)=map(char(labels(k))); end
            switch string(atom_style)
                case "atomic"
                    atoms=table(type,coords(:,1),coords(:,2),coords(:,3), ...
                        'VariableNames',{'type','x','y','z'});
                case "charge"
                    atoms=table(type,charges,coords(:,1),coords(:,2),coords(:,3), ...
                        'VariableNames',{'type','q','x','y','z'});
                otherwise
                    atoms=table(mol,type,charges,coords(:,1),coords(:,2),coords(:,3), ...
                        'VariableNames',{'molecule_ID','type','q','x','y','z'});
            end
            atoms.Properties.RowNames=cellstr(string(1:height(atoms)));
            vel=[]; if ~isempty(velocities), vel=array2table(velocities,'VariableNames',{'vx','vy','vz'}); vel.Properties.RowNames=atoms.Properties.RowNames; end
            topology=containers.Map('KeyType','char','ValueType','any');
            keys=topologyRows.keys;
            for k=1:numel(keys)
                arr=topologyRows(keys{k}); nAtoms=size(arr,2)-1;
                names=[{'type'},arrayfun(@(x)sprintf('atom%d',x),1:nAtoms,'UniformOutput',false)];
                tab=array2table(arr,'VariableNames',names); tab.Properties.RowNames=cellstr(string(1:height(tab)));
                topology(keys{k})=tab;
            end
            if topology.Count==0, topology=[]; end
            obj=kssolv.analysis.matgenlab.io.lammps.LammpsData(box,ff.masses,atoms,vel,ff.force_field,topology,atom_style);
        end
    end
    methods (Static,Access=private)
        function tab=parseSection(name,lines,atom_style,sort_id)
            rows=cell(numel(lines),1); maxc=0;
            for k=1:numel(lines), p=split(lines(k)); p(p=="")=[]; rows{k}=cellstr(p); maxc=max(maxc,numel(p)); end
            raw=cell(numel(lines),maxc);
            for k=1:numel(lines)
                for j=1:numel(rows{k})
                    n=str2double(rows{k}{j}); if ~isnan(n), raw{k,j}=n; else, raw{k,j}=rows{k}{j}; end
                end
            end
            switch name
                case 'Masses', names={'id','mass'};
                case 'Velocities', names={'id','vx','vy','vz'};
                case 'Bonds', names={'id','type','atom1','atom2'};
                case 'Angles', names={'id','type','atom1','atom2','atom3'};
                case {'Dihedrals','Impropers'}, names={'id','type','atom1','atom2','atom3','atom4'};
                case 'Atoms'
                    styles=struct('atomic',{{'type','x','y','z'}},'charge',{{'type','q','x','y','z'}}, ...
                        'molecular',{{'molecule_ID','type','x','y','z'}},'bond',{{'molecule_ID','type','x','y','z'}}, ...
                        'angle',{{'molecule_ID','type','x','y','z'}},'full',{{'molecule_ID','type','q','x','y','z'}});
                    names=[{'id'},styles.(char(atom_style))];
                    if maxc==numel(names)+3, names=[names {'nx','ny','nz'}]; end
                otherwise
                    if strcmp(name,'PairIJ Coeffs'), names=[{'id1','id2'},arrayfun(@(x)sprintf('coeff%d',x),1:maxc-2,'UniformOutput',false)];
                    else, names=[{'id'},arrayfun(@(x)sprintf('coeff%d',x),1:maxc-1,'UniformOutput',false)]; end
            end
            tab=cell2table(raw,'VariableNames',names);
            for j=1:width(tab)
                v=tab{:,j};
                if iscell(v)&&all(cellfun(@(x)isnumeric(x)||isempty(x),v))
                    numericColumn=nan(numel(v),1);
                    present=~cellfun(@isempty,v);
                    numericColumn(present)=cellfun(@double,v(present));
                    tab.(j)=numericColumn;
                end
            end
            if any(strcmp(names,'id'))
                ids=tab.id;
                if sort_id, [ids,order]=sort(ids); tab=tab(order,:); end
                tab.id=[]; tab.Properties.RowNames=cellstr(string(ids));
            elseif sort_id&&all(ismember({'id1','id2'},names)), tab=sortrows(tab,{'id1','id2'}); end
        end
    end
    methods (Access=private)
        function out=formatTable(~,tab,includeId,distance,velocity,charge)
            rows=strings(height(tab),1); names=tab.Properties.VariableNames;
            for i=1:height(tab)
                fields=strings(0,1);
                if includeId
                    if ~isempty(tab.Properties.RowNames), fields(end+1)=tab.Properties.RowNames{i}; else, fields(end+1)=string(i); end
                end
                for j=1:width(tab)
                    v=tab{i,j}; if iscell(v), v=v{1}; end
                    name=names{j};
                    if isnumeric(v)
                        if ismember(name,{'x','y','z'}), f="%."+distance+"f";
                        elseif ismember(name,{'vx','vy','vz'}), f="%."+velocity+"f";
                        elseif strcmp(name,'q'), f="%."+charge+"f";
                        elseif abs(v-round(v))<1e-12, f="%.0f"; else, f="%.9g"; end
                        fields(end+1)=sprintf(f,v);
                    else, fields(end+1)=string(v); end
                end
                rows(i)=join(fields," ");
            end
            out=join(rows,newline);
        end
    end
end
