classdef KPathSetyawanCurtarolo < ...
        kssolv.analysis.matgenlab.symmetry.kpath.KPathBase
    %KPATHSETYAWANCURTAROLO Setyawan-Curtarolo reciprocal paths.
    properties (SetAccess=private)
        conventional
        prim
        prim_rec
        name (1,1) string = ""
    end

    methods
        function obj=KPathSetyawanCurtarolo( ...
                structure,symprec,angleTolerance,atol)
            if nargin<2,symprec=0.01;end
            if nargin<3,angleTolerance=5;end
            if nargin<4,atol=1e-5;end
            obj@kssolv.analysis.matgenlab.symmetry.kpath.KPathBase( ...
                structure,symprec,angleTolerance,atol);
            analyzer=kssolv.analysis.matgenlab.symmetry.analyzer. ...
                SpacegroupAnalyzer(structure,symprec,angleTolerance);
            obj.prim=analyzer.get_primitive_standard_structure(false);
            obj.conventional= ...
                analyzer.get_conventional_standard_structure(false);
            obj.prim_rec=obj.prim.lattice.reciprocal_lattice;
            obj.rec_lattice=obj.prim_rec;
            latticeType=analyzer.get_lattice_type();
            symbol=analyzer.get_space_group_symbol();
            lengths=obj.conventional.lattice.lengths;
            if latticeType=="cubic"
                if contains(symbol,"P")
                    obj.kpath=obj.cubic();
                elseif contains(symbol,"F")
                    obj.kpath=obj.fcc();
                else
                    obj.kpath=obj.bcc();
                end
            elseif latticeType=="tetragonal"
                if contains(symbol,"P")
                    obj.kpath=obj.tet();
                elseif lengths(3)<lengths(1)
                    obj.kpath=obj.bctet1(lengths(3),lengths(1));
                else
                    obj.kpath=obj.bctet2(lengths(3),lengths(1));
                end
            elseif latticeType=="orthorhombic"
                a=lengths(1);b=lengths(2);c=lengths(3);
                if contains(symbol,"P")
                    obj.kpath=obj.orc();
                elseif contains(symbol,"F")
                    comparison=1/a^2-1/b^2-1/c^2;
                    if comparison>0
                        obj.kpath=obj.orcf1(a,b,c);
                    elseif comparison<0
                        obj.kpath=obj.orcf2(a,b,c);
                    else
                        obj.kpath=obj.orcf3(a,b,c);
                    end
                elseif contains(symbol,"I")
                    obj.kpath=obj.orci(a,b,c);
                else
                    obj.kpath=obj.orcc(a,b,c);
                end
            elseif latticeType=="hexagonal"
                obj.kpath=obj.hex();
            elseif latticeType=="rhombohedral"
                alpha=deg2rad(obj.prim.lattice.angles(1));
                if alpha<pi/2
                    obj.kpath=obj.rhl1(alpha);
                else
                    obj.kpath=obj.rhl2(alpha);
                end
            elseif latticeType=="monoclinic"
                a=lengths(1);b=lengths(2);c=lengths(3);
                alpha=deg2rad(obj.conventional.lattice.angles(1));
                if contains(symbol,"P")
                    obj.kpath=obj.mcl(b,c,alpha);
                else
                    gamma=obj.rec_lattice.angles(3);
                    comparison=b*cos(alpha)/c+ ...
                        b^2*sin(alpha)^2/a^2;
                    if gamma>90
                        obj.kpath=obj.mclc1(a,b,c,alpha);
                    elseif gamma==90
                        obj.kpath=obj.mclc2(a,b,c,alpha);
                    elseif comparison<1
                        obj.kpath=obj.mclc3(a,b,c,alpha);
                    elseif comparison>1
                        obj.kpath=obj.mclc5(a,b,c,alpha);
                    else
                        obj.kpath=obj.mclc4(a,b,c,alpha);
                    end
                end
            else
                reciprocalAngles=obj.rec_lattice.angles;
                if all(reciprocalAngles>90)
                    obj.kpath=obj.tria();
                else
                    obj.kpath=obj.trib();
                end
            end
        end

        function value=cubic(obj)
            obj.name="CUB";
            value=makePath({'\Gamma','X','R','M'}, ...
                [0,0,0;0,.5,0;.5,.5,.5;.5,.5,0], ...
                {{'\Gamma','X','M','\Gamma','R','X'},{'M','R'}});
        end

        function value=fcc(obj)
            obj.name="FCC";
            value=makePath({'\Gamma','K','L','U','W','X'}, ...
                [0,0,0;3/8,3/8,3/4;.5,.5,.5;5/8,1/4,5/8; ...
                .5,1/4,3/4;.5,0,.5], ...
                {{'\Gamma','X','W','K','\Gamma','L','U','W','L','K'}, ...
                {'U','X'}});
        end

        function value=bcc(obj)
            obj.name="BCC";
            value=makePath({'\Gamma','H','P','N'}, ...
                [0,0,0;.5,-.5,.5;.25,.25,.25;0,0,.5], ...
                {{'\Gamma','H','N','\Gamma','P','H'},{'P','N'}});
        end

        function value=tet(obj)
            obj.name="TET";
            value=makePath({'\Gamma','A','M','R','X','Z'}, ...
                [0,0,0;.5,.5,.5;.5,.5,0;0,.5,.5;0,.5,0;0,0,.5], ...
                {{'\Gamma','X','M','\Gamma','Z','R','A','Z'}, ...
                {'X','R'},{'M','A'}});
        end

        function value=bctet1(obj,c,a)
            obj.name="BCT1";eta=(1+c^2/a^2)/4;
            value=makePath({'\Gamma','M','N','P','X','Z','Z_1'}, ...
                [0,0,0;-.5,.5,.5;0,.5,0;.25,.25,.25;0,0,.5; ...
                eta,eta,-eta;-eta,1-eta,eta], ...
                {{'\Gamma','X','M','\Gamma','Z','P','N','Z_1','M'}, ...
                {'X','P'}});
        end

        function value=bctet2(obj,c,a)
            obj.name="BCT2";eta=(1+a^2/c^2)/4;zeta=a^2/(2*c^2);
            value=makePath( ...
                {'\Gamma','N','P','\Sigma','\Sigma_1','X','Y','Y_1','Z'}, ...
                [0,0,0;0,.5,0;.25,.25,.25;-eta,eta,eta; ...
                eta,1-eta,-eta;0,0,.5;-zeta,zeta,.5; ...
                .5,.5,-zeta;.5,.5,-.5], ...
                {{'\Gamma','X','Y','\Sigma','\Gamma','Z', ...
                '\Sigma_1','N','P','Y_1','Z'},{'X','P'}});
        end

        function value=orc(obj)
            obj.name="ORC";
            value=makePath({'\Gamma','R','S','T','U','X','Y','Z'}, ...
                [0,0,0;.5,.5,.5;.5,.5,0;0,.5,.5;.5,0,.5; ...
                .5,0,0;0,.5,0;0,0,.5], ...
                {{'\Gamma','X','S','Y','\Gamma','Z','U','R','T','Z'}, ...
                {'Y','T'},{'U','X'},{'S','R'}});
        end

        function value=orcf1(obj,a,b,c)
            obj.name="ORCF1";zeta=(1+a^2/b^2-a^2/c^2)/4; ...
                eta=(1+a^2/b^2+a^2/c^2)/4;
            value=makePath( ...
                {'\Gamma','A','A_1','L','T','X','X_1','Y','Z'}, ...
                [0,0,0;.5,.5+zeta,zeta;.5,.5-zeta,1-zeta; ...
                .5,.5,.5;1,.5,.5;0,eta,eta;1,1-eta,1-eta; ...
                .5,0,.5;.5,.5,0], ...
                {{'\Gamma','Y','T','Z','\Gamma','X','A_1','Y'}, ...
                {'T','X_1'},{'X','A','Z'},{'L','\Gamma'}});
        end

        function value=orcf2(obj,a,b,c)
            obj.name="ORCF2";phi=(1+c^2/b^2-c^2/a^2)/4; ...
                eta=(1+a^2/b^2-a^2/c^2)/4; ...
                delta=(1+b^2/a^2-b^2/c^2)/4;
            value=makePath( ...
                {'\Gamma','C','C_1','D','D_1','L','H','H_1','X','Y','Z'}, ...
                [0,0,0;.5,.5-eta,1-eta;.5,.5+eta,eta; ...
                .5-delta,.5,1-delta;.5+delta,.5,delta;.5,.5,.5; ...
                1-phi,.5-phi,.5;phi,.5+phi,.5;0,.5,.5; ...
                .5,0,.5;.5,.5,0], ...
                {{'\Gamma','Y','C','D','X','\Gamma','Z','D_1','H','C'}, ...
                {'C_1','Z'},{'X','H_1'},{'H','Y'},{'L','\Gamma'}});
        end

        function value=orcf3(obj,a,b,c)
            obj.name="ORCF3";zeta=(1+a^2/b^2-a^2/c^2)/4; ...
                eta=(1+a^2/b^2+a^2/c^2)/4;
            value=makePath( ...
                {'\Gamma','A','A_1','L','T','X','X_1','Y','Z'}, ...
                [0,0,0;.5,.5+zeta,zeta;.5,.5-zeta,1-zeta; ...
                .5,.5,.5;1,.5,.5;0,eta,eta;1,1-eta,1-eta; ...
                .5,0,.5;.5,.5,0], ...
                {{'\Gamma','Y','T','Z','\Gamma','X','A_1','Y'}, ...
                {'X','A','Z'},{'L','\Gamma'}});
        end

        function value=orci(obj,a,b,c)
            obj.name="ORCI";zeta=(1+a^2/c^2)/4; ...
                eta=(1+b^2/c^2)/4;delta=(b^2-a^2)/(4*c^2); ...
                mu=(a^2+b^2)/(4*c^2);
            value=makePath( ...
                {'\Gamma','L','L_1','L_2','R','S','T','W', ...
                'X','X_1','Y','Y_1','Z'}, ...
                [0,0,0;-mu,mu,.5-delta;mu,-mu,.5+delta; ...
                .5-delta,.5+delta,-mu;0,.5,0;.5,0,0;0,0,.5; ...
                .25,.25,.25;-zeta,zeta,zeta;zeta,1-zeta,-zeta; ...
                eta,-eta,eta;1-eta,eta,-eta;.5,.5,-.5], ...
                {{'\Gamma','X','L','T','W','R','X_1','Z', ...
                '\Gamma','Y','S','W'},{'L_1','Y'},{'Y_1','Z'}});
        end

        function value=orcc(obj,a,b,c) %#ok<INUSD>
            obj.name="ORCC";zeta=(1+a^2/b^2)/4;
            value=makePath( ...
                {'\Gamma','A','A_1','R','S','T','X','X_1','Y','Z'}, ...
                [0,0,0;zeta,zeta,.5;-zeta,1-zeta,.5;0,.5,.5; ...
                0,.5,0;-.5,.5,.5;zeta,zeta,0;-zeta,1-zeta,0; ...
                -.5,.5,0;0,0,.5], ...
                {{'\Gamma','X','S','R','A','Z','\Gamma','Y', ...
                'X_1','A_1','T','Y'},{'Z','T'}});
        end

        function value=hex(obj)
            obj.name="HEX";
            value=makePath({'\Gamma','A','H','K','L','M'}, ...
                [0,0,0;0,0,.5;1/3,1/3,.5;1/3,1/3,0; ...
                .5,0,.5;.5,0,0], ...
                {{'\Gamma','M','K','\Gamma','A','L','H','A'}, ...
                {'L','M'},{'K','H'}});
        end

        function value=rhl1(obj,alpha)
            obj.name="RHL1";eta=(1+4*cos(alpha))/(2+4*cos(alpha)); ...
                nu=3/4-eta/2;
            value=makePath( ...
                {'\Gamma','B','B_1','F','L','L_1','P','P_1','P_2','Q','X','Z'}, ...
                [0,0,0;eta,.5,1-eta;.5,1-eta,eta-1;.5,.5,0; ...
                .5,0,0;0,0,-.5;eta,nu,nu;1-nu,1-nu,1-eta; ...
                nu,nu,eta-1;1-nu,nu,0;nu,0,-nu;.5,.5,.5], ...
                {{'\Gamma','L','B_1'},{'B','Z','\Gamma','X'}, ...
                {'Q','F','P_1','Z'},{'L','P'}});
        end

        function value=rhl2(obj,alpha)
            obj.name="RHL2";eta=1/(2*tan(alpha/2)^2); ...
                nu=3/4-eta/2;
            value=makePath( ...
                {'\Gamma','F','L','P','P_1','Q','Q_1','Z'}, ...
                [0,0,0;.5,-.5,0;.5,0,0;1-nu,-nu,1-nu; ...
                nu,nu-1,nu-1;eta,eta,eta;1-eta,-eta,-eta; ...
                .5,-.5,.5], ...
                {{'\Gamma','P','Z','Q','\Gamma','F','P_1','Q_1','L','Z'}});
        end

        function value=mcl(obj,b,c,beta)
            obj.name="MCL";eta=(1-b*cos(beta)/c)/(2*sin(beta)^2); ...
                nu=.5-eta*c*cos(beta)/b;
            value=makePath( ...
                {'\Gamma','A','C','D','D_1','E','H','H_1','H_2', ...
                'M','M_1','M_2','X','Y','Y_1','Z'}, ...
                [0,0,0;.5,.5,0;0,.5,.5;.5,0,.5;.5,0,-.5; ...
                .5,.5,.5;0,eta,1-nu;0,1-eta,nu;0,eta,-nu; ...
                .5,eta,1-nu;.5,1-eta,nu;.5,eta,-nu; ...
                0,.5,0;0,0,.5;0,0,-.5;.5,0,0], ...
                {{'\Gamma','Y','H','C','E','M_1','A','X','H_1'}, ...
                {'M','D','Z'},{'Y','D'}});
        end

        function value=mclc1(obj,a,b,c,alpha)
            value=mclc12(obj,a,b,c,alpha,1);
        end
        function value=mclc2(obj,a,b,c,alpha)
            value=mclc12(obj,a,b,c,alpha,2);
        end
        function value=mclc3(obj,a,b,c,alpha)
            value=mclc34(obj,a,b,c,alpha,3);
        end
        function value=mclc4(obj,a,b,c,alpha)
            value=mclc34(obj,a,b,c,alpha,4);
        end

        function value=mclc5(obj,a,b,c,alpha)
            obj.name="MCLC5";
            zeta=(b^2/a^2+(1-b*cos(alpha)/c)/sin(alpha)^2)/4;
            eta=.5+2*zeta*c*cos(alpha)/b;
            mu=eta/2+b^2/(4*a^2)-b*c*cos(alpha)/(2*a^2);
            nu=2*mu-zeta;rho=1-zeta*a^2/b^2;
            omega=(4*nu-1-b^2*sin(alpha)^2/a^2)*c/ ...
                (2*b*cos(alpha));
            delta=zeta*c*cos(alpha)/b+omega/2-.25;
            value=makePath( ...
                {'\Gamma','F','F_1','F_2','H','H_1','H_2', ...
                'I','I_1','L','M','N','N_1','X','Y','Y_1','Y_2','Y_3','Z'}, ...
                [0,0,0;nu,nu,omega;1-nu,1-nu,1-omega; ...
                nu,nu-1,omega;zeta,zeta,eta;1-zeta,-zeta,1-eta; ...
                -zeta,-zeta,1-eta;rho,1-rho,.5;1-rho,rho-1,.5; ...
                .5,.5,.5;.5,0,.5;.5,0,0;0,-.5,0;.5,-.5,0; ...
                mu,mu,delta;1-mu,-mu,-delta;-mu,-mu,-delta; ...
                mu,mu-1,delta;0,0,.5], ...
                {{'\Gamma','Y','F','L','I'}, ...
                {'I_1','Z','H','F_1'}, ...
                {'H_1','Y_1','X','\Gamma','N'},{'M','\Gamma'}});
        end

        function value=tria(obj)
            obj.name="TRI1a";
            value=triclinicPath(false);
        end
        function value=trib(obj)
            obj.name="TRI1b";
            value=triclinicPath(true);
        end
    end

    methods (Access=private)
        function value=mclc12(obj,a,b,c,alpha,variant)
            obj.name="MCLC"+variant;
            zeta=(2-b*cos(alpha)/c)/(4*sin(alpha)^2);
            eta=.5+2*zeta*c*cos(alpha)/b;
            psi=.75-a^2/(4*b^2*sin(alpha)^2);
            phi=psi+(.75-psi)*b*cos(alpha)/c;
            names={'\Gamma','N','N_1','F','F_1','F_2','I','I_1', ...
                'L','M','X','X_1','X_2','Y','Y_1','Z'};
            coords=[0,0,0;.5,0,0;0,-.5,0;1-zeta,1-zeta,1-eta; ...
                zeta,zeta,eta;-zeta,-zeta,1-eta;phi,1-phi,.5; ...
                1-phi,phi-1,.5;.5,.5,.5;.5,0,.5; ...
                1-psi,psi-1,0;psi,1-psi,0;psi-1,-psi,0; ...
                .5,.5,0;-.5,-.5,0;0,0,.5];
            if variant==1
                paths={{'\Gamma','Y','F','L','I'}, ...
                    {'I_1','Z','F_1'},{'Y','X_1'}, ...
                    {'X','\Gamma','N'},{'M','\Gamma'}};
            else
                names{end+1}='F_3';
                coords(end+1,:)=[1-zeta,-zeta,1-eta];
                paths={{'\Gamma','Y','F','L','I'}, ...
                    {'I_1','Z','F_1'},{'N','\Gamma','M'}};
            end
            value=makePath(names,coords,paths);
        end

        function value=mclc34(obj,a,b,c,alpha,variant)
            obj.name="MCLC"+variant;
            mu=(1+b^2/a^2)/4;
            delta=b*c*cos(alpha)/(2*a^2);
            zeta=mu-.25+(1-b*cos(alpha)/c)/(4*sin(alpha)^2);
            eta=.5+2*zeta*c*cos(alpha)/b;
            phi=1+zeta-2*mu;psi=eta-2*delta;
            names={'\Gamma','F','F_1','F_2','H','H_1','H_2', ...
                'I','M','N','N_1','X','Y','Y_1','Y_2','Y_3','Z'};
            coords=[0,0,0;1-phi,1-phi,1-psi;phi,phi-1,psi; ...
                1-phi,-phi,1-psi;zeta,zeta,eta; ...
                1-zeta,-zeta,1-eta;-zeta,-zeta,1-eta; ...
                .5,-.5,.5;.5,0,.5;.5,0,0;0,-.5,0; ...
                .5,-.5,0;mu,mu,delta;1-mu,-mu,-delta; ...
                -mu,-mu,-delta;mu,mu-1,delta;0,0,.5];
            if variant==3
                paths={{'\Gamma','Y','F','H','Z','I','F_1'}, ...
                    {'H_1','Y_1','X','\Gamma','N'},{'M','\Gamma'}};
            else
                paths={{'\Gamma','Y','F','H','Z','I'}, ...
                    {'H_1','Y_1','X','\Gamma','N'},{'M','\Gamma'}};
            end
            value=makePath(names,coords,paths);
        end
    end
end

function value=makePath(names,coordinates,paths)
points=containers.Map("KeyType","char","ValueType","any");
for index=1:numel(names),points(names{index})=coordinates(index,:);end
value=struct("kpoints",points,"path",{paths});
end

function value=triclinicPath(second)
if ~second
    coordinates=[0,0,0;.5,.5,0;0,.5,.5;.5,0,.5; ...
        .5,.5,.5;.5,0,0;0,.5,0;0,0,.5];
else
    coordinates=[0,0,0;.5,-.5,0;0,0,.5;-.5,-.5,.5; ...
        0,-.5,.5;0,-.5,0;.5,0,0;-.5,0,.5];
end
value=makePath({'\Gamma','L','M','N','R','X','Y','Z'}, ...
    coordinates,{{'X','\Gamma','Y'},{'L','\Gamma','Z'}, ...
    {'N','\Gamma','M'},{'R','\Gamma'}});
end
