function openffMol = create_openff_mol(smile, geometry, chargeScaling, ...
        partialCharges, backupChargeMethod, backend)
%CREATE_OPENFF_MOL Create an OpenFF molecule from SMILES and optional geometry.
if nargin < 2, geometry = []; end
if nargin < 3 || isempty(chargeScaling), chargeScaling = 1; end
if nargin < 4, partialCharges = []; end
if nargin < 5 || strlength(string(backupChargeMethod)) == 0
    backupChargeMethod = "am1bcc";
end
if nargin < 6, backend = []; end
if ~isempty(backend) && ...
        kssolv.analysis.matgenlab.io.openff.internal. ...
        backend_has(backend, "create_openff_mol")
    openffMol = kssolv.analysis.matgenlab.io.openff.internal. ...
        call_backend(backend, "create_openff_mol", smile, geometry, ...
        chargeScaling, partialCharges, backupChargeMethod);
    return
end
if ischar(geometry) || (isstring(geometry) && isscalar(geometry))
    geometry = kssolv.analysis.matgenlab.core.Molecule. ...
        from_file(char(geometry));
end
if ~isempty(partialCharges)
    if isempty(geometry)
        error("KSSOLV:Matgenlab:OpenFF:GeometryRequired", ...
            "geometries must be set if partial_charges is set");
    end
    if numel(partialCharges) ~= geometry.num_sites
        error("KSSOLV:Matgenlab:OpenFF:ChargeLength", ...
            "partial charges must have same length & order as geometry");
    end
end
if ~isempty(backend)
    openffMol = kssolv.analysis.matgenlab.io.openff.internal. ...
        call_backend(backend, "from_smiles", smile, true);
else
    openffMol = kssolv.analysis.matgenlab.io.openff. ...
        OpenFFMolecule.from_smiles(smile, true);
end
[openffMol, atomMap] = kssolv.analysis.matgenlab.io.openff. ...
    add_conformer(openffMol, geometry, backend);
openffMol = kssolv.analysis.matgenlab.io.openff. ...
    assign_partial_charges(openffMol, atomMap, backupChargeMethod, ...
    partialCharges, backend);
if isa(openffMol, ...
        "kssolv.analysis.matgenlab.io.openff.OpenFFMolecule")
    openffMol.set_partial_charges( ...
        openffMol.partial_charges * double(chargeScaling));
elseif ~isempty(backend) && ...
        kssolv.analysis.matgenlab.io.openff.internal. ...
        backend_has(backend, "scale_partial_charges")
    openffMol = kssolv.analysis.matgenlab.io.openff.internal. ...
        call_backend(backend, "scale_partial_charges", openffMol, ...
        double(chargeScaling));
else
    error("KSSOLV:Matgenlab:OpenFF:BackendContract", ...
        "External OpenFF values require scale_partial_charges.");
end
end
