classdef Cp2kOutput < handle
%#ok<*INUSD,*NASGU,*CPROP,*AGROW,*STOUT,*MANU,*UNRCH>
 properties,filename string;dir string;filenames struct=struct();data struct=struct();input=[];initial_structure=[];lattice=[];final_structure=[];composition=[];efermi=[];vbm=[];cbm=[];band_gap=[];structures={};ionic_steps={};final_energy=[];end
 properties(Dependent),cp2k_version;completed;num_warnings;run_type;calculation_type;project_name;spin_polarized;charge;multiplicity;is_molecule;is_metal;is_hubbard;complete_dos;band_structure;end
 methods
  function obj=Cp2kOutput(filename,verbose,auto_load),if nargin<2,verbose=false;end;if nargin<3,auto_load=false;end;obj.filename=string(filename);obj.dir=string(fileparts(filename));obj.parse_files();obj.parse_cp2k_params();obj.parse_input();obj.parse_global_params();obj.parse_dft_params();if auto_load,obj.ran_successfully();obj.convergence();obj.parse_structures();obj.parse_energies();obj.parse_forces();obj.parse_stresses();obj.parse_ionic_steps();obj.parse_dos();obj.parse_bandstructure();obj.parse_timing();end,end
  function v=get.cp2k_version(o),v=o.data.cp2k_version;end
  function v=get.completed(o),v=isfield(o.data,"completed")&&o.data.completed;end
  function v=get.num_warnings(o),if isfield(o.data,"num_warnings"),v=o.data.num_warnings;else,v=0;end,end
  function v=get.run_type(o),v=o.data.global.Run_type;end
  function v=get.calculation_type(o),if o.is_hubbard,v="Unknown+U";else,v="Unknown";end,end
  function v=get.project_name(o),v=o.data.global.project_name;end
  function v=get.spin_polarized(o),v=isfield(o.data,"dft")&&o.data.dft.spin_polarized;end
  function v=get.charge(o),if ~isempty(o.input)&&o.input.check("FORCE_EVAL/DFT"),k=o.input.by_path("FORCE_EVAL/DFT").get("CHARGE",kssolv.analysis.matgenlab.io.cp2k.Keyword("",0));v=k.values{1};else,v=0;end,end
  function v=get.multiplicity(o),if ~isempty(o.input)&&o.input.check("FORCE_EVAL/DFT"),k=o.input.by_path("FORCE_EVAL/DFT").get("MULTIPLICITY",kssolv.analysis.matgenlab.io.cp2k.Keyword("",1));v=k.values{1};else,v=1;end,end
  function v=get.is_molecule(o),v=isfield(o.data,"poisson_periodicity")&&upper(string(o.data.poisson_periodicity))=="NONE";end
  function v=get.is_metal(o),v=isempty(o.band_gap)||o.band_gap<=0;end
  function v=get.is_hubbard(o),v=isfield(o.data,"plus_u")&&~isempty(o.data.plus_u);end
  function v=get.complete_dos(o),if isfield(o.data,"cdos"),v=o.data.cdos;elseif isfield(o.data,"complete_dos"),v=o.data.complete_dos;else,v=[];end,end
  function v=get.band_structure(o),if isfield(o.data,"band_structure"),v=o.data.band_structure;else,v=[];end,end
  function parse_files(o),patterns=struct("DOS","*.dos*","PDOS","*pdos*","band_structure","*BAND.bs*","trajectory","*pos*.xyz*","forces","*frc*.xyz*","stress","*stress*","cell","*.cell*","ener","*.ener*","hyperfine_tensor","*HYPERFINE*eprhyp*","g_tensor","*GTENSOR*data*","chi_tensor","*CHI*data*","nmr_shift","*SHIFT*data*","raman","*raman*data*");n=fieldnames(patterns);for i=1:numel(n),d=dir(fullfile(o.dir,patterns.(n{i})));o.filenames.(n{i})=string(fullfile({d.folder},{d.name}));end;o.filenames.LDOS=strings(0,1);end
  function v=parse_structures(o,varargin),if isempty(o.initial_structure),o.parse_initial_structure();end;o.structures={o.initial_structure};o.final_structure=o.initial_structure;v=o.structures;end
  function v=parse_initial_structure(o),text=fileread(o.filename);rows=regexp(text,'(?m)^\s*\d+\s+\d+\s+([A-Z][a-z]?)\s+\d+\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s+[-+\d.]+\s+[-+\d.]+\s*$','tokens');if isempty(rows),v=[];return,end;species=cellfun(@(x)x{1},rows,"UniformOutput",false);coords=zeros(numel(rows),3);for i=1:numel(rows),coords(i,:)=cellfun(@str2double,rows{i}(2:4));end;lat=o.parse_cell_params();if o.is_molecule,o.initial_structure=kssolv.analysis.matgenlab.core.Molecule(species,coords);else,o.initial_structure=kssolv.analysis.matgenlab.core.Structure(kssolv.analysis.matgenlab.core.Lattice(lat),species,coords,coords_are_cartesian=true);end;o.composition=o.initial_structure.composition;v=o.initial_structure;end
  function v=ran_successfully(o),text=fileread(o.filename);o.data.completed=contains(text,"PROGRAM ENDED AT");v=o.data.completed;end
  function v=convergence(o),text=fileread(o.filename);o.data.converged=contains(text,"SCF run converged");v=o.data.converged;end
  function v=parse_energies(o),text=fileread(o.filename);t=regexp(text,'ENERGY\| Total FORCE_EVAL.*?:\s*([-+\d.Ee]+)','tokens');v=cellfun(@(x)str2double(x{1})*27.211386245988,t);o.data.energy=v;if ~isempty(v),o.final_energy=v(end);end,end
  function v=parse_forces(o),text=fileread(o.filename);blocks=regexp(text,'ATOMIC FORCES in \[a\.u\.\][\s\S]*?SUM OF ATOMIC FORCES','match');v=cell(1,numel(blocks));for i=1:numel(blocks),rows=regexp(blocks{i},'(?m)^\s*\d+\s+\d+\s+\w+\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)','tokens');mat=zeros(numel(rows),3);for j=1:numel(rows),mat(j,:)=cellfun(@str2double,rows{j});end;v{i}=mat;end;o.data.forces=v;end
  function v=parse_stresses(o),text=fileread(o.filename);blocks=regexp(text,'STRESS\|\s+x\s+y\s+z[\s\S]*?(?=\n\s*\n)','match');v=cell(1,numel(blocks));for i=1:numel(blocks),rows=regexp(blocks{i},'(?m)STRESS\|\s+[xyz]\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)','tokens');mat=zeros(numel(rows),3);for j=1:numel(rows),mat(j,:)=cellfun(@str2double,rows{j});end;v{i}=mat;end;o.data.stress_tensor=v;end
  function v=parse_ionic_steps(o),if isempty(o.structures),o.parse_structures();end;if ~isfield(o.data,"energy"),o.parse_energies();end;if ~isfield(o.data,"forces"),o.parse_forces();end;if ~isfield(o.data,"stress_tensor"),o.parse_stresses();end;n=min(numel(o.structures),numel(o.data.energy));o.ionic_steps=cell(1,n);for i=1:n,force=[];stress=[];if i<=numel(o.data.forces),force=o.data.forces{i};end;if i<=numel(o.data.stress_tensor),stress=o.data.stress_tensor{i};end;o.ionic_steps{i}=struct("structure",o.structures{i},"E",o.data.energy(i),"forces",force,"stress_tensor",stress);end;v=o.ionic_steps;end
  function parse_cp2k_params(o),text=fileread(o.filename);t=regexp(text,'CP2K\| version string:\s+CP2K version\s+(\S+)','tokens','once');if isempty(t),o.data.cp2k_version="";else,o.data.cp2k_version=string(t{1});end;t=regexp(text,'number of warnings for this run is\s*:\s*(\d+)','tokens');o.data.num_warnings=cellfun(@(x)str2double(x{1}),t);end
  function v=parse_plus_u_params(o),text=fileread(o.filename);blocks=regexp(text,'(?ms)DFT\+U correction.*?(?=\n\s*\n)','match');v=cell(1,numel(blocks));for i=1:numel(blocks),l=regexp(blocks{i},'Angular momentum.*?(\d+)','tokens','once');u=regexp(blocks{i},'U_MINUS_J.*?([-+\d.]+)','tokens','once');v{i}=struct("L",scalarToken(l),"U_MINUS_J",scalarToken(u));end;o.data.plus_u=v;end
  function v=parse_input(o),files=dir(fullfile(o.dir,"*.inp"));if ~isempty(files),o.input=kssolv.analysis.matgenlab.io.cp2k.Cp2kInput.from_file(fullfile(files(1).folder,files(1).name));end;v=o.input;end
  function v=parse_global_params(o),text=fileread(o.filename);p=regexp(text,'GLOBAL\| Project name\s+(\S+)','tokens','once');r=regexp(text,'GLOBAL\| Run type\s+(\S+)','tokens','once');if isempty(p),p={""};end;if isempty(r),r={""};end;o.data.global=struct("project_name",string(p{1}),"Run_type",string(r{1}));v=o.data.global;end
  function v=parse_dft_params(o),text=fileread(o.filename);rows=regexp(text,'(?m)^\s*DFT\|\s+(.+?)\s{3,}(\S.*?)\s*$','tokens');v=struct("spin_polarized",contains(text,"spin-polarized")||contains(text," UKS"));for i=1:numel(rows),key=matlab.lang.makeValidName(strtrim(rows{i}{1}));v.(key)=kssolv.analysis.matgenlab.io.cp2k.postprocessor(strtrim(rows{i}{2}));end;p=regexp(text,'POISSON\| Periodicity\s+(\w+)','tokens','once');if ~isempty(p),o.data.poisson_periodicity=string(p{1});end;o.data.dft=v;end
  function v=parse_qs_params(o),text=fileread(o.filename);rows=regexp(text,'(?m)^\s*QS\|\s+(.+?):?\s{3,}(\S.*?)\s*$','tokens');v=struct();for i=1:numel(rows),v.(matlab.lang.makeValidName(strtrim(rows{i}{1})))=kssolv.analysis.matgenlab.io.cp2k.postprocessor(strtrim(rows{i}{2}));end;o.data.qs=v;end
  function v=parse_overlap_condition(o),text=fileread(o.filename);t=regexp(text,'\|A\|\*\|A\^-1\|.+=\s+([-+\d.Ee]+)','tokens','once');v=scalarToken(t);o.data.overlap_condition_number=v;end
  function v=parse_scf_params(o),text=fileread(o.filename);a=regexp(text,'max_scf:\s+(\d+)','tokens','once');b=regexp(text,'eps_scf:\s+([-+\d.Ee]+)','tokens','once');v=struct("max_scf",scalarToken(a),"eps_scf",scalarToken(b));o.data.scf=v;end
  function v=parse_cell_params(o),text=fileread(o.filename);rows=regexp(text,'(?m)CELL\| Vector [abc].*?:\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)','tokens');if numel(rows)>=3,v=zeros(3);for i=1:3,v(i,:)=cellfun(@str2double,rows{i});end;else,v=[];end;o.lattice=v;o.data.cell=v;end
  function v=parse_atomic_kind_info(o),text=fileread(o.filename);heads=regexp(text,'(?m)^\s*(\d+)\. Atomic kind:\s+(\S+)\s+Number of atoms:\s+(\d+)','tokens');v=struct();for i=1:numel(heads),name=matlab.lang.makeValidName(heads{i}{2});start=regexp(text,'(?m)^\s*'+string(heads{i}{1})+'\. Atomic kind:\s+'+regexptranslate("escape",string(heads{i}{2})),'start','once');tail=text(start:min(end,start+12000));basis=regexp(tail,'Orbital Basis Set\s+(\S+)','tokens','once');pot=regexp(tail,'Potential information for element.*\n\s+Potential name\s+(\S+)','tokens','once');if isempty(pot),pot={"NONE"};end;if isempty(basis),basis={""};end;v.(name)=struct("kind_number",str2double(heads{i}{1}),"number_of_atoms",str2double(heads{i}{3}),"orbital_basis_set",string(basis{1}),"pseudo_potential",string(pot{1}));end;o.data.atomic_kind_info=v;end
  function v=parse_total_numbers(o),text=fileread(o.filename);names=["atomic_kinds","atoms","shell_sets","shells","primitive_cartesian_functions","cartesian_basis_functions","spherical_basis_functions"];labels=["Atomic kinds","Atoms","Shell sets","Shells","Primitive Cartesian functions","Cartesian basis functions","Spherical basis functions"];v=struct();for i=1:numel(names),t=regexp(text,'- '+labels(i)+':\s+(\d+)','tokens','once');v.(char(names(i)))=scalarToken(t);end;o.data.total_numbers=v;end
  function v=parse_scf_opt(o),text=fileread(o.filename);blocks=regexp(text,'SCF WAVEFUNCTION OPTIMIZATION[\s\S]*?\*\*\* SCF run','match');v=cell(1,numel(blocks));for i=1:numel(blocks),rows=regexp(blocks{i},'(?m)^\s*(\d+)\s+(\S+)\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)','tokens');v{i}=rows;end;o.data.electronic_steps=v;end
  function v=parse_timing(o),text=fileread(o.filename);rows=regexp(text,'(?m)^\s*([A-Za-z]\w*)\s+(\d+)\s+(\d+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s*$','tokens');v=struct();for i=1:numel(rows),r=rows{i};v.(matlab.lang.makeValidName(r{1}))=struct("calls",str2double(r{2}),"asd",str2double(r{3}),"self_average",str2double(r{4}),"self_maximum",str2double(r{5}),"total_average",str2double(r{6}),"total_maximum",str2double(r{7}));end;o.data.timing=v;end
  function v=parse_opt_steps(o),text=fileread(o.filename);fields=["total_energy","real_energy_change","predicted_change_in_energy","scaling_factor","step_size","trust_radius","used_time"];labels=["Total Energy","Real energy change","Predicted change in energy","Scaling factor","Step size","Trust radius","Used time"];v=struct();for i=1:numel(fields),t=regexp(text,'(?m)^\s*'+regexptranslate("escape",labels(i))+'\s*=\s*([-+\d.Ee]+)','tokens');v.(char(fields(i)))=cellfun(@(x)str2double(x{1}),t);end;o.data.opt_steps=v;end
  function v=parse_mulliken(o),text=fileread(o.filename);blocks=regexp(text,'Mulliken Population Analysis[\s\S]*?# Total charge and spin[^\n]*','match');v=cell(1,numel(blocks));for i=1:numel(blocks),rows=regexp(blocks{i},'(?m)^\s*(\d+)\s+([A-Z][a-z]?)\s+(\d+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)','tokens');v{i}=populationRows(rows,true);end;o.data.mulliken=v;end
  function v=parse_hirshfeld(o),text=fileread(o.filename);blocks=regexp(text,'Hirshfeld Charges[\s\S]*?Total Charge[^\n]*','match');v=cell(1,numel(blocks));for i=1:numel(blocks),rows=regexp(blocks{i},'(?m)^\s*(\d+)\s+([A-Z][a-z]?)\s+(\d+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)','tokens');v{i}=populationRows(rows,false);end;o.data.hirshfeld=v;end
  function v=parse_mo_eigenvalues(o),text=fileread(o.filename);occ=regexp(text,'Eigenvalues of the occupied subspace spin\s+(\d+)\s*\n\s*-+\s*\n([\s\d.Ee+-]+?)\n\s*Fermi Energy \[eV\]\s*:\s*([-+\d.]+)','tokens');unocc=regexp(text,'Lowest eigenvalues of the unoccupied subspace spin\s+(\d+)\s*\n\s*-+\s*\n([\s\d.Ee+-]+?)(?=\n\s*(?:Lowest|PW_GRID|HOMO|Eigenvalues))','tokens');v=struct("occupied",struct(),"unoccupied",struct(),"efermi",struct());for i=1:numel(occ),key="spin_"+occ{i}{1};v.occupied.(key)=numbers(occ{i}{2})*27.211386245988;v.efermi.(key)=str2double(occ{i}{3});end;for i=1:numel(unocc),key="spin_"+unocc{i}{1};v.unoccupied.(key)=numbers(unocc{i}{2})*27.211386245988;end;o.data.eigenvalues=v;if isfield(v.occupied,"spin_1"),o.vbm=max(v.occupied.spin_1);end;if isfield(v.unoccupied,"spin_1"),o.cbm=min(v.unoccupied.spin_1);end;if ~isempty(o.vbm)&&~isempty(o.cbm),o.band_gap=o.cbm-o.vbm;end;end
  function v=parse_homo_lumo(o),text=fileread(o.filename);t=regexp(text,'HOMO.*-.*LUMO.*gap.*\s([-+\d.]+)','tokens');v=cellfun(@(x)str2double(x{1}),t);o.data.homo_lumo_gap=v;if ~isempty(v),o.band_gap=v(end);end,end
  function v=parse_dos(o,varargin),if isempty(o.filenames.DOS),v=[];else,v=kssolv.analysis.matgenlab.io.cp2k.parse_dos(o.filenames.DOS(1));o.data.tdos=v;end;if ~isempty(o.filenames.PDOS),p=kssolv.analysis.matgenlab.io.cp2k.parse_pdos(o.filenames.PDOS(1));o.data.pdos=p;end,end
  function v=parse_bandstructure(o,varargin),if isempty(o.filenames.band_structure),v=[];return,end;text=fileread(o.filenames.band_structure(1));rows=regexp(text,'(?m)^\s*\d+\s+([-+\d.]+)\s+([\d.]+)\s*$','tokens');e=cellfun(@(x)str2double(x{1}),rows);occ=cellfun(@(x)str2double(x{2}),rows);gap=min(e(occ==0))-max(e(occ>0));o.band_gap=gap;o.data.band_structure=kssolv.analysis.matgenlab.io.cp2k.Cp2kBandResult(gap);v=o.data.band_structure;end
  function v=parse_hyperfine(o,varargin),file=chooseFile(varargin,o.filenames.hyperfine_tensor);if strlength(file)==0,v=[];return,end;lines=splitlines(string(fileread(file)));mats={};for i=1:numel(lines)-2,if contains(lines(i),"A_ani"),rows=[numbers(lines(i-1));numbers(lines(i));numbers(lines(i+1))];mats{end+1}=rows(:,end-2:end);end,end;o.data.hyperfine_tensor={mats};v=mats;end
  function v=parse_gtensor(o,varargin),file=chooseFile(varargin,o.filenames.g_tensor);v=o.parseTensorFile(file,["gmatrix_zke","gmatrix_so","gmatrix_soo","gmatrix_total","gtensor_total","delta_g"]);end
  function v=parse_chi_tensor(o,varargin),file=chooseFile(varargin,o.filenames.chi_tensor);text=fileread(file);lines=splitlines(string(text));names=["chi_soft","chi_local","chi_total","chi_total_ppm_cgs"];heads=["CHI from SOFT","CHI from LOCAL","Total CHI in 10","Total CHI in ppm"];for i=1:4,idx=find(contains(lines,heads(i)),1);if isempty(idx)||idx+3>numel(lines),continue,end;mat=zeros(3);for j=1:3,vals=numbers(lines(idx+j));mat(j,:)=vals(end-2:end);end;o.data.(char(names(i)))={mat};end;pv=regexp(text,'PV1=\s*([-+\d.]+)\s+PV2=\s*([-+\d.]+)\s+PV3=\s*([-+\d.]+)','tokens','once');iso=regexp(text,'ISO=\s*([-+\d.]+)\s+ANISO=\s*([-+\d.]+)','tokens','once');if ~isempty(pv),for i=1:3,o.data.(char("PV"+i))={str2double(pv{i})};end,end;if ~isempty(iso),o.data.ISO={str2double(iso{1})};o.data.ANISO={str2double(iso{2})};end;if isfield(o.data,"chi_total"),v=o.data.chi_total{1};else,v=[];end,end
  function v=parse_nmr_shift(o),error("KSSOLV:Matgenlab:Cp2k:UnsupportedUpstream","NMR parsing is not implemented by the frozen pymatgen upstream.");v=[];end
  function v=parse_tddfpt(o),error("KSSOLV:Matgenlab:Cp2k:UnsupportedUpstream","TDDFPT parsing is not implemented by the frozen pymatgen upstream.");v=[];end
  function v=parse_raman(o),error("KSSOLV:Matgenlab:Cp2k:UnsupportedUpstream","Raman parsing is not implemented by the frozen pymatgen upstream.");v=[];end
  function v=read_pattern(o,patterns,varargin),text=fileread(o.filename);v=struct();n=fieldnames(patterns);for i=1:numel(n),v.(n{i})=regexp(text,patterns.(n{i}),"tokens");end,end
  function v=read_table_pattern(o,header,row,footer,varargin),text=fileread(o.filename);blocks=regexp(text,string(header)+"([\s\S]*?)"+string(footer),"tokens");v=cellfun(@(b)regexp(b{1},row,"tokens"),blocks,"UniformOutput",false);end
  function v=as_dict(o),v=struct("filename",o.filename,"data",o.data,"completed",o.completed,"final_energy",o.final_energy);end
 end
 methods(Access=private)
  function v=parseTensorFile(o,file,names),if strlength(file)==0,v=[];return,end;lines=splitlines(string(fileread(file)));v=[];for i=1:numel(lines),key=strtrim(lines(i));idx=find(names==key,1);if ~isempty(idx)&&i+3<=numel(lines),mat=[numbers(lines(i+1));numbers(lines(i+2));numbers(lines(i+3))];mat=mat(:,end-2:end);o.data.(char(key))={mat};v=mat;elseif startsWith(key,"delta_g")&&i+3<=numel(lines),mat=[numbers(lines(i+1));numbers(lines(i+2));numbers(lines(i+3))];mat=mat(:,end-2:end);o.data.delta_g={mat};end,end,end
 end
end
function f=chooseFile(args,files),if ~isempty(args)&&~isempty(args{1}),f=string(args{1});elseif ~isempty(files),f=files(1);else,f="";end,end
function v=numbers(s),m=regexp(char(s),'[-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?','match');v=str2double(m);end
function v=scalarToken(token),if isempty(token),v=[];else,v=str2double(token{1});end,end
function out=populationRows(rows,isMulliken),out=cell(1,numel(rows));for i=1:numel(rows),r=rows{i};if isMulliken,out{i}=struct("atom",str2double(r{1}),"element",string(r{2}),"kind",str2double(r{3}),"population",[str2double(r{4}),str2double(r{5})],"net_charge",str2double(r{6}),"spin_moment",str2double(r{7}));else,out{i}=struct("atom",str2double(r{1}),"element",string(r{2}),"kind",str2double(r{3}),"reference_charge",str2double(r{4}),"population",[str2double(r{5}),str2double(r{6})],"spin_moment",str2double(r{7}),"net_charge",str2double(r{8}));end,end,end
