classdef RemoteConfiguration
    %REMOTECONFIGURATION Versioned schema for a remote execution target.

    properties (Constant)
        FormatVersion = 2
        ExecutionModes = ["Standard", "Bridge", "Mirror", "Cloud"]
        CloudProviders = ["MathWorksCloudCenter", "AWS", "PrivateCloud"]
        ProfileSources = ["ManagedSlurm", "ExistingMatlabProfile"]
        ConnectionModes = ["SSH", "Direct"]
        AuthenticationModes = ["Agent", "IdentityFile", ...
            "Password", "Multifactor"]
        CodeDeploymentModes = ["ClusterInstalled", ...
            "AttachCurrentToolbox"]

    end

    methods (Static)
        function value = create(overrides)
            arguments
                overrides struct = struct()
            end
            overrides = upgradeLegacy(overrides);
            value = kssolv.services.remote.config.RemoteConfiguration.defaults();
            names = fieldnames(overrides);
            for index = 1:numel(names)
                value.(names{index}) = overrides.(names{index});
            end
            value = kssolv.services.remote.config.RemoteConfiguration.normalize(value);
            kssolv.services.remote.config.RemoteConfiguration.validate(value);
        end

        function value = defaults()
            value = struct( ...
                "Version", 2, ...
                "Id", kssolv.services.remote.config.RemoteConfiguration.newId(), ...
                "DisplayName", "New Remote Target", ...
                "Enabled", true, ...
                "ExecutionMode", "Standard", ...
                "CloudProvider", "MathWorksCloudCenter", ...
                "CloudResourceName", "", ...
                "CloudRegion", "", ...
                "ProfileSource", "ManagedSlurm", ...
                "ConnectionMode", "SSH", ...
                "Host", "", ...
                "Username", "", ...
                "AuthenticationMode", "Agent", ...
                "IdentityFile", "", ...
                "RememberTotpSecret", false, ...
                "EncryptedPassword", "", ...
                "EncryptedTotpSecret", "", ...
                "ExistingProfileName", "", ...
                "RemoteBridgeProfileName", "", ...
                "ManagedProfileName", "", ...
                "ClusterMatlabRoot", "", ...
                "RemoteJobStorageLocation", "", ...
                "PostLoginScript", "", ...
                "PostLoginCommandTemplate", "{command}", ...
                "PostLoginPromptRules", emptyPromptRules(), ...
                "HasSharedFilesystem", false, ...
                "RequiresOnlineLicensing", false, ...
                "LicenseNumber", "", ...
                "NumWorkers", 4, ...
                "PoolSize", 2, ...
                "Partition", "", ...
                "Account", "", ...
                "QoS", "", ...
                "Walltime", "01:00:00", ...
                "AdditionalSubmitArgs", "", ...
                "CodeDeploymentMode", "AttachCurrentToolbox", ...
                "RemoteKssolvRoot", "");
        end

        function value = normalize(value)
            arguments
                value struct
            end
            if ~isscalar(value)
                error("KSSOLV:Remote:ConfigurationNotScalar", ...
                    "A remote configuration must be a scalar structure.");
            end
            value = upgradeLegacy(value);
            defaults = kssolv.services.remote.config.RemoteConfiguration.defaults();
            names = fieldnames(defaults);
            normalized = defaults;
            for index = 1:numel(names)
                name = names{index};
                if isfield(value, name) && ~isempty(value.(name))
                    normalized.(name) = value.(name);
                end
            end

            stringFields = ["Id", "DisplayName", "ExecutionMode", ...
                "CloudProvider", "CloudResourceName", "CloudRegion", ...
                "ProfileSource", "ConnectionMode", "Host", "Username", ...
                "AuthenticationMode", "IdentityFile", ...
                "EncryptedPassword", "EncryptedTotpSecret", ...
                "ExistingProfileName", "RemoteBridgeProfileName", ...
                "ManagedProfileName", "ClusterMatlabRoot", ...
                "RemoteJobStorageLocation", "PostLoginScript", ...
                "PostLoginCommandTemplate", ...
                "LicenseNumber", "Partition", "Account", "QoS", ...
                "Walltime", "AdditionalSubmitArgs", ...
                "CodeDeploymentMode", "RemoteKssolvRoot"];
            for name = stringFields
                item = string(normalized.(name));
                if ~isscalar(item)
                    item = item(1);
                end
                normalized.(name) = strip(item);
            end
            normalized.Version = 2;
            normalized.Enabled = logical(normalized.Enabled);
            normalized.HasSharedFilesystem = ...
                logical(normalized.HasSharedFilesystem);
            normalized.RequiresOnlineLicensing = ...
                logical(normalized.RequiresOnlineLicensing);
            normalized.RememberTotpSecret = ...
                logical(normalized.RememberTotpSecret);
            normalized.NumWorkers = double(normalized.NumWorkers);
            normalized.PoolSize = double(normalized.PoolSize);
            normalized.PostLoginPromptRules = normalizePromptRules( ...
                normalized.PostLoginPromptRules);

            if strlength(normalized.ManagedProfileName) == 0
                normalized.ManagedProfileName = "KSSOLV-Slurm-" + ...
                    extractBefore(normalized.Id, min(13, ...
                    strlength(normalized.Id) + 1));
            end

            value = normalized;
        end

        function validate(value)
            rejectSecretFields(value);
            value = kssolv.services.remote.config.RemoteConfiguration.normalize(value);
            mustBeNonemptyScalar(value.Id, "Id");
            mustBeNonemptyScalar(value.DisplayName, "DisplayName");
            mustBeMember(value.ExecutionMode, ...
                kssolv.services.remote.config.RemoteConfiguration.ExecutionModes);
            mustBeMember(value.ProfileSource, ...
                kssolv.services.remote.config.RemoteConfiguration.ProfileSources);
            mustBeMember(value.ConnectionMode, ...
                kssolv.services.remote.config.RemoteConfiguration.ConnectionModes);
            mustBeMember(value.AuthenticationMode, ...
                kssolv.services.remote.config.RemoteConfiguration.AuthenticationModes);
            mustBeMember(value.CodeDeploymentMode, ...
                kssolv.services.remote.config.RemoteConfiguration.CodeDeploymentModes);
            mustBeMember(value.CloudProvider, ...
                kssolv.services.remote.config.RemoteConfiguration.CloudProviders);

            routed = any(value.ExecutionMode == ...
                ["Standard", "Bridge", "Mirror"]);
            if routed
                mustBeNonemptyScalar(value.PostLoginCommandTemplate, ...
                    "PostLoginCommandTemplate");
                if count(value.PostLoginCommandTemplate, "{command}") ~= 1
                    invalid("PostLoginCommandTemplate", ...
                        "must contain {command} exactly once");
                end
                validatePromptRules(value.PostLoginPromptRules);
            elseif strlength(value.PostLoginScript) > 0
                invalid("PostLoginScript", ...
                    "is not supported by Cloud mode");
            elseif value.PostLoginCommandTemplate ~= "{command}" || ...
                    ~isempty(value.PostLoginPromptRules)
                invalid("PostLoginCommandTemplate", ...
                    "is not supported by Cloud mode");
            end

            switch value.ExecutionMode
                case "Standard"
                    validateProfileTarget(value, true);
                case {"Bridge", "Mirror"}
                    if value.ConnectionMode ~= "SSH"
                        invalid("ConnectionMode", ...
                            "must be SSH for Bridge and Mirror modes");
                    end
                    validateSshTarget(value);
                    mustBeNonemptyScalar(value.ClusterMatlabRoot, ...
                        "ClusterMatlabRoot");
                    if value.ExecutionMode == "Bridge"
                        mustBeNonemptyScalar(value.RemoteBridgeProfileName, ...
                            "RemoteBridgeProfileName");
                    end
                case "Cloud"
                    if value.ProfileSource ~= "ExistingMatlabProfile"
                        invalid("ProfileSource", ...
                            "must be ExistingMatlabProfile for Cloud mode");
                    end
                    mustBeNonemptyScalar(value.ExistingProfileName, ...
                        "ExistingProfileName");
            end

            if value.AuthenticationMode == "IdentityFile" && routed && ...
                    value.ConnectionMode == "SSH"
                mustBeNonemptyScalar(value.IdentityFile, "IdentityFile");
            end
            if value.CodeDeploymentMode == "ClusterInstalled"
                mustBeNonemptyScalar(value.RemoteKssolvRoot, ...
                    "RemoteKssolvRoot");
            end
            validateWorkerCounts(value);
            if strlength(value.Walltime) > 0 && ...
                    isempty(regexp(char(value.Walltime), ...
                    '^([0-9]+-)?[0-9]{1,2}:[0-9]{2}:[0-9]{2}$', 'once'))
                invalid("Walltime", ...
                    "must use [days-]hours:minutes:seconds format");
            end

            function validateProfileTarget(item, requireRoot)
                if item.ProfileSource == "ExistingMatlabProfile"
                    mustBeNonemptyScalar(item.ExistingProfileName, ...
                        "ExistingProfileName");
                    if strlength(item.PostLoginScript) > 0 || ...
                            item.PostLoginCommandTemplate ~= "{command}" || ...
                            ~isempty(item.PostLoginPromptRules)
                        if item.ConnectionMode ~= "SSH"
                            invalid("ConnectionMode", ...
                                "must be SSH when Standard mode uses a " + ...
                                "post-login command template");
                        end
                        validateSshTarget(item);
                    end
                    return
                end
                mustBeNonemptyScalar(item.ManagedProfileName, ...
                    "ManagedProfileName");
                if item.ConnectionMode == "SSH"
                    validateSshTarget(item);
                end
                if requireRoot
                    mustBeNonemptyScalar(item.ClusterMatlabRoot, ...
                        "ClusterMatlabRoot");
                end
            end

            function validateSshTarget(item)
                mustBeNonemptyScalar(item.Host, "Host");
                mustBeNonemptyScalar(item.Username, "Username");
                mustBeNonemptyScalar(item.RemoteJobStorageLocation, ...
                    "RemoteJobStorageLocation");
            end

            function mustBeNonemptyScalar(item, name)
                if ~isscalar(string(item)) || ...
                        strlength(strip(string(item))) == 0
                    invalid(name, "must be a nonempty scalar string");
                end
            end

            function invalid(name, detail)
                error("KSSOLV:Remote:InvalidConfiguration", ...
                    "Remote configuration field %s %s.", name, detail);
            end
        end

        function value = sanitized(value)
            rejectSecretFields(value);
            value = kssolv.services.remote.config.RemoteConfiguration.normalize(value);
            kssolv.services.remote.config.RemoteConfiguration.validate(value);
        end

        function value = withoutCredentials(value)
            value = kssolv.services.remote.config.RemoteConfiguration. ...
                sanitized(value);
            value = rmfield(value, ["RememberTotpSecret", ...
                "EncryptedPassword", "EncryptedTotpSecret"]);
        end

        function id = newId()
            id = string(matlab.lang.internal.uuid);
        end
    end
end

function value = upgradeLegacy(value)
if ~isstruct(value) || ~isscalar(value)
    return
end
legacyModeOverride = isfield(value, "SubmissionMode") && ...
    string(value.SubmissionMode) == "RemoteMatlabBridge" && ...
    (~isfield(value, "ExecutionMode") || ...
    strlength(string(value.ExecutionMode)) == 0 || ...
    string(value.ExecutionMode) == "Standard");
if ~isfield(value, "ExecutionMode") || ...
        strlength(string(value.ExecutionMode)) == 0 || legacyModeOverride
    mode = "Standard";
    if isfield(value, "SubmissionMode") && ...
            string(value.SubmissionMode) == "RemoteMatlabBridge"
        mode = "Bridge";
        if isfield(value, "RemoteBridgeExecutionMode") && ...
                string(value.RemoteBridgeExecutionMode) == "StandaloneMatlab"
            mode = "Mirror";
        end
    end
    value.ExecutionMode = mode;
end
legacyCommandOverride = isfield(value, "RemoteCommandTemplate") && ...
    string(value.RemoteCommandTemplate) ~= "{command}" && ...
    (~isfield(value, "PostLoginCommandTemplate") || ...
    string(value.PostLoginCommandTemplate) == "{command}");
if ((~isfield(value, "PostLoginCommandTemplate") || ...
        strlength(string(value.PostLoginCommandTemplate)) == 0) && ...
        isfield(value, "RemoteCommandTemplate")) || legacyCommandOverride
    value.PostLoginCommandTemplate = value.RemoteCommandTemplate;
end
if (~isfield(value, "PostLoginPromptRules") || ...
        isempty(value.PostLoginPromptRules)) && ...
        isfield(value, "RemotePromptPattern") && ...
        strlength(string(value.RemotePromptPattern)) > 0
    label = "Elevation credential";
    if isfield(value, "RemoteCredentialLabel") && ...
            strlength(string(value.RemoteCredentialLabel)) > 0
        label = string(value.RemoteCredentialLabel);
    end
    value.PostLoginPromptRules = struct( ...
        "Pattern", string(value.RemotePromptPattern), ...
        "CredentialLabel", label);
end
end

function rules = emptyPromptRules()
rules = repmat(struct("Pattern", "", "CredentialLabel", ""), 0, 1);
end

function rules = normalizePromptRules(value)
rules = emptyPromptRules();
if isempty(value)
    return
end
if iscell(value)
    value = [value{:}];
end
if ~isstruct(value)
    error("KSSOLV:Remote:InvalidConfiguration", ...
        "PostLoginPromptRules must be a structure array.");
end
for index = 1:numel(value)
    pattern = "";
    label = "";
    if isfield(value, "Pattern")
        pattern = strip(string(value(index).Pattern));
    end
    if isfield(value, "CredentialLabel")
        label = strip(string(value(index).CredentialLabel));
    end
    if ~isscalar(pattern) || ~isscalar(label)
        error("KSSOLV:Remote:InvalidConfiguration", ...
            "Each post-login prompt rule must use scalar strings.");
    end
    rules(end + 1, 1) = struct( ...
        "Pattern", pattern, "CredentialLabel", label); %#ok<AGROW>
end
end

function validatePromptRules(rules)
for index = 1:numel(rules)
    if strlength(rules(index).Pattern) == 0 || ...
            strlength(rules(index).CredentialLabel) == 0
        error("KSSOLV:Remote:InvalidConfiguration", ...
            "Each post-login prompt rule requires Pattern and " + ...
            "CredentialLabel.");
    end
    try
        regexp("", char(rules(index).Pattern), "once");
    catch exception
        error("KSSOLV:Remote:InvalidConfiguration", ...
            "Post-login prompt rule %d is not a valid regular " + ...
            "expression: %s", index, exception.message);
    end
end
end

function rejectSecretFields(value)
secretNames = ["Password", "OTP", "TOTP", "TotpSeed", ...
    "TwoFactorKey", "PrivateKey", "Credential", "Secret"];
suppliedNames = string(fieldnames(value));
if any(ismember(lower(suppliedNames), lower(secretNames)))
    error("KSSOLV:Remote:SecretInConfiguration", ...
        "Remote configurations must not contain secrets.");
end
end

function validateWorkerCounts(value)
if ~isfinite(value.NumWorkers) || value.NumWorkers < 1 || ...
        fix(value.NumWorkers) ~= value.NumWorkers
    error("KSSOLV:Remote:InvalidConfiguration", ...
        "Remote configuration field NumWorkers must be a positive integer.");
end
if ~isfinite(value.PoolSize) || value.PoolSize < 0 || ...
        fix(value.PoolSize) ~= value.PoolSize || ...
        value.PoolSize > value.NumWorkers
    error("KSSOLV:Remote:InvalidConfiguration", ...
        "Remote configuration field PoolSize must be an integer " + ...
        "between 0 and NumWorkers.");
end
end
