classdef CommandExecutor
    %COMMANDEXECUTOR Validate and execute a modeling command transaction.

    methods (Static)
        function result = execute(model, commandId, parameters)
            arguments
                model
                commandId {mustBeTextScalar}
                parameters (1,1) struct = struct()
            end
            commandId = string(commandId);
            if ~kssolv.modeling.CommandExecutor.supports(commandId)
                error("KSSOLV:Modeling:NotImplemented", ...
                    "The modeling command '%s' is not implemented yet.", ...
                    commandId);
            end
            kssolv.modeling.contracts.CommandCapability.validateModel( ...
                commandId, model);

            workingCopy = model.copy();
            if kssolv.modeling.AtomicEditorCommands.supports(commandId)
                result = kssolv.modeling.AtomicEditorCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.chemistry. ...
                    MoleculeChemistryCommands.supports(commandId)
                result = kssolv.modeling.chemistry. ...
                    MoleculeChemistryCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.geometry. ...
                    MolecularGeometryCommands.supports(commandId)
                result = kssolv.modeling.geometry. ...
                    MolecularGeometryCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.fragments. ...
                    FragmentCommands.supports(commandId)
                result = kssolv.modeling.fragments.FragmentCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.polymers.PolymerCommands.supports(commandId)
                result = kssolv.modeling.polymers.PolymerCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.packing.PackingCommands.supports(commandId)
                result = kssolv.modeling.packing.PackingCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.CrystalBuilderCommands.supports(commandId)
                result = kssolv.modeling.CrystalBuilderCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.LatticeEditorCommands.supports(commandId)
                result = kssolv.modeling.LatticeEditorCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.SupercellCommands.supports(commandId)
                result = kssolv.modeling.SupercellCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.DefectCommands.supports(commandId)
                result = kssolv.modeling.DefectCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.SurfaceCommands.supports(commandId)
                result = kssolv.modeling.SurfaceCommands.execute( ...
                    workingCopy, commandId, parameters);
            elseif kssolv.modeling.NanostructureCommands.supports(commandId)
                result = kssolv.modeling.NanostructureCommands.execute( ...
                    workingCopy, commandId, parameters);
            else
                result = kssolv.modeling.SymmetryCommands.execute( ...
                    workingCopy, commandId, parameters);
            end
            result.commandId = commandId;
        end

        function value = supports(commandId)
            commandId = string(commandId);
            value = ...
                kssolv.modeling.AtomicEditorCommands.supports(commandId) || ...
                kssolv.modeling.chemistry. ...
                    MoleculeChemistryCommands.supports(commandId) || ...
                kssolv.modeling.geometry. ...
                    MolecularGeometryCommands.supports(commandId) || ...
                kssolv.modeling.fragments. ...
                    FragmentCommands.supports(commandId) || ...
                kssolv.modeling.polymers.PolymerCommands.supports(commandId) || ...
                kssolv.modeling.packing.PackingCommands.supports(commandId) || ...
                kssolv.modeling.CrystalBuilderCommands.supports(commandId) || ...
                kssolv.modeling.LatticeEditorCommands.supports(commandId) || ...
                kssolv.modeling.SupercellCommands.supports(commandId) || ...
                kssolv.modeling.DefectCommands.supports(commandId) || ...
                kssolv.modeling.SurfaceCommands.supports(commandId) || ...
                kssolv.modeling.NanostructureCommands.supports(commandId) || ...
                kssolv.modeling.SymmetryCommands.supports(commandId);
        end

        function [value, reason] = supportsForModel(commandId, model)
            if ~kssolv.modeling.CommandExecutor.supports(commandId)
                value = false;
                reason = sprintf( ...
                    "The modeling command '%s' is not implemented.", ...
                    string(commandId));
                return
            end
            [value, reason] = ...
                kssolv.modeling.contracts.CommandCapability. ...
                supportsModel(commandId, model);
        end

        function ids = supportedCommandIds()
            ids = [
                kssolv.modeling.AtomicEditorCommands.commandIds()
                kssolv.modeling.chemistry.MoleculeChemistryCommands.commandIds()
                kssolv.modeling.geometry.MolecularGeometryCommands.commandIds()
                kssolv.modeling.fragments.FragmentCommands.commandIds()
                kssolv.modeling.polymers.PolymerCommands.commandIds()
                kssolv.modeling.packing.PackingCommands.commandIds()
                kssolv.modeling.CrystalBuilderCommands.commandIds()
                kssolv.modeling.LatticeEditorCommands.commandIds()
                kssolv.modeling.SupercellCommands.commandIds()
                kssolv.modeling.DefectCommands.commandIds()
                kssolv.modeling.SurfaceCommands.commandIds()
                kssolv.modeling.NanostructureCommands.commandIds()
                kssolv.modeling.SymmetryCommands.commandIds()
                ];
        end
    end
end
