classdef CrystalBuilderCommands
    %CRYSTALBUILDERCOMMANDS Space-group construction and defect enumeration.
    methods (Static)
        function ids=commandIds()
            ids=["build_from_spacegroup";"make_p1"; ...
                "enumerate_point_defects"];
        end
        function value=supports(id)
            value=any(kssolv.modeling.CrystalBuilderCommands.commandIds()==string(id));
        end
        function result=execute(model,id,p)
            import kssolv.modeling.ParameterUtils
            id=string(id);
            switch id
                case "build_from_spacegroup"
                    lattice=double(ParameterUtils.get(p,"lattice",eye(3)*5));
                    if isequal(size(lattice),[1,3]), lattice=diag(lattice); end
                    species=ParameterUtils.get(p,"species","Si");
                    if ischar(species) || (isstring(species)&&isscalar(species))
                        species=split(strtrim(string(species)));
                    end
                    coordinates=double(ParameterUtils.get(p, ...
                        "fractionalCoordinates",[0,0,0]));
                    coordinates=reshape(coordinates,[],3);
                    if numel(species) ~= size(coordinates, 1)
                        error("KSSOLV:Modeling:CrystalBuilderShape", ...
                            "Species and asymmetric coordinates must have equal row counts.");
                    end
                    occupancies=reshape(double(ParameterUtils.get(p, ...
                        "occupancies",ones(1,numel(species)))),1,[]);
                    if numel(occupancies) ~= numel(species) || ...
                            any(~isfinite(occupancies)) || ...
                            any(occupancies <= 0 | occupancies > 1)
                        error("KSSOLV:Modeling:CrystalBuilderOccupancy", ...
                            "Occupancies must contain one value in (0, 1] per asymmetric site.");
                    end
                    sourceSpecies=reshape(string(species),1,[]);
                    expandedSpecies=cell(1,numel(sourceSpecies));
                    for siteIndex=1:numel(sourceSpecies)
                        if occupancies(siteIndex)==1
                            expandedSpecies{siteIndex}=char(sourceSpecies(siteIndex));
                        else
                            mapping=struct();
                            mapping.(char(sourceSpecies(siteIndex)))= ...
                                occupancies(siteIndex);
                            expandedSpecies{siteIndex}= ...
                                kssolv.analysis.matgenlab.core.Composition(mapping);
                        end
                    end
                    declared=string(ParameterUtils.get( ...
                        p,"spaceGroup","Pm-3m"));
                    model=kssolv.analysis.matgenlab.core.Structure. ...
                        from_spacegroup(declared,lattice,expandedSpecies,coordinates);
                    tolerance=double(ParameterUtils.get(p, ...
                        "collisionTolerance",0.1));
                    if ~isscalar(tolerance) || ~isfinite(tolerance) || tolerance<=0
                        error("KSSOLV:Modeling:CrystalBuilderTolerance", ...
                            "Collision tolerance must be a finite positive scalar.");
                    end
                    if model.num_sites>1
                        distances=model.distance_matrix;
                        distances(1:model.num_sites+1:end)=Inf;
                        minimumDistance=min(distances,[],"all");
                        if minimumDistance<tolerance
                            [first,second]=find(distances<tolerance,1);
                            error("KSSOLV:Modeling:CrystalBuilderCollision", ...
                                "Expanded sites %d and %d overlap at %.6g angstrom " + ...
                                "(tolerance %.6g angstrom).",first,second, ...
                                minimumDistance,tolerance);
                        end
                    else
                        minimumDistance=Inf;
                    end
                    analyzer=kssolv.analysis.matgenlab.symmetry.analyzer. ...
                        SpacegroupAnalyzer(model,1e-3,5);
                    dataset=analyzer.get_symmetry_dataset();
                    representatives=unique(dataset.equivalent_atoms,"stable");
                    equivalentTable=repmat(struct( ...
                        "representative",0,"species","", ...
                        "fractional",zeros(1,3),"wyckoff","", ...
                        "multiplicity",0,"siteSymmetry","", ...
                        "occupancy",0),1,numel(representatives));
                    for rowIndex=1:numel(representatives)
                        representative=representatives(rowIndex);
                        site=find(dataset.equivalent_atoms==representative,1);
                        equivalentTable(rowIndex)=struct( ...
                            "representative",site, ...
                            "species",string(model(site).species_string), ...
                            "fractional",reshape(model(site).frac_coords,1,3), ...
                            "wyckoff",dataset.wyckoffs(site), ...
                            "multiplicity",sum(dataset.equivalent_atoms==representative), ...
                            "siteSymmetry",dataset.site_symmetry_symbols(site), ...
                            "occupancy",double(model(site).species.num_atoms));
                    end
                    asymmetricTable=repmat(struct("species","", ...
                        "fractional",zeros(1,3),"occupancy",1), ...
                        1,numel(sourceSpecies));
                    for rowIndex=1:numel(sourceSpecies)
                        asymmetricTable(rowIndex)=struct( ...
                            "species",sourceSpecies(rowIndex), ...
                            "fractional",coordinates(rowIndex,:), ...
                            "occupancy",occupancies(rowIndex));
                    end
                    properties=model.structure_properties;
                    properties.symmetry=struct("schemaVersion",1, ...
                        "declaredSpaceGroup",declared, ...
                        "detectedSpaceGroup",dataset.international, ...
                        "detectedNumber",dataset.number, ...
                        "mode","preserve","asymmetricSites",asymmetricTable);
                    model=model.copy([],false,properties);
                    analysis=struct("asymmetricSites",asymmetricTable, ...
                        "equivalentSites",equivalentTable, ...
                        "declaredSpaceGroup",declared, ...
                        "detectedSpaceGroup",dataset.international, ...
                        "detectedNumber",dataset.number, ...
                        "minimumDistance",minimumDistance, ...
                        "collisionTolerance",tolerance);
                    result=changed(model, ...
                        "Crystal generated from asymmetric sites.",analysis);
                case "make_p1"
                    properties=model.structure_properties;
                    properties.symmetry=struct("schemaVersion",1, ...
                        "declaredSpaceGroup","P1","expandedSites",model.num_sites);
                    model=model.copy([],false,properties);
                    result=changed(model,"Explicit P1 model created.");
                case "enumerate_point_defects"
                    analyzer=kssolv.analysis.matgenlab.symmetry.analyzer. ...
                        SpacegroupAnalyzer(model,double(ParameterUtils.get( ...
                        p,"symprec",.01)),double(ParameterUtils.get( ...
                        p,"angleTolerance",5)));
                    dataset=analyzer.get_symmetry_dataset();
                    selected=ParameterUtils.get(p,"indices",1:model.num_sites);
                    selected=reshape(double(selected),1,[]);
                    representatives=unique(dataset.equivalent_atoms(selected),"stable");
                    kind=lower(string(ParameterUtils.get(p,"defectType","vacancy")));
                    variants=cell(1,numel(representatives));
                    degeneracy=zeros(1,numel(representatives));
                    sites=zeros(1,numel(representatives));
                    netCharges=zeros(1,numel(representatives));
                    minimumContacts=zeros(1,numel(representatives));
                    labels=strings(1,numel(representatives));
                    for index=1:numel(representatives)
                        representative=representatives(index);
                        site=find(dataset.equivalent_atoms==representative,1);
                        sites(index)=site;
                        degeneracy(index)=sum(dataset.equivalent_atoms==representative);
                        parameters=struct("defectType",kind,"indices",site);
                        if kind=="substitution"
                            parameters.species=string(ParameterUtils.get(p,"species","H"));
                        end
                        variants{index}=kssolv.modeling.DefectCommands. ...
                            execute(model,"create_point_defects",parameters).model;
                        sourceCharge=siteReferenceCharge(model(site));
                        if kind=="vacancy"
                            netCharges(index)=-sourceCharge;
                        elseif kind=="substitution"
                            replacementCharge=double(ParameterUtils.get( ...
                                p,"replacementCharge",0));
                            if ~isscalar(replacementCharge) || ...
                                    ~isfinite(replacementCharge)
                                error("KSSOLV:Modeling:DefectCharge", ...
                                    "Replacement charge must be a finite scalar.");
                            end
                            netCharges(index)=replacementCharge-sourceCharge;
                        else
                            netCharges(index)=0;
                        end
                        if variants{index}.num_sites>1
                            distances=variants{index}.distance_matrix;
                            distances(1:variants{index}.num_sites+1:end)=Inf;
                            minimumContacts(index)=min(distances,[],"all");
                        else
                            minimumContacts(index)=Inf;
                        end
                        labels(index)=sprintf("%s site %d (degeneracy %d)", ...
                            kind,site,degeneracy(index));
                    end
                    data=struct("variants",{variants},"siteIndices",sites, ...
                        "degeneracies",degeneracy,"defectType",kind, ...
                        "spaceGroup",dataset.number,"indexBase",1, ...
                        "netCharges",netCharges, ...
                        "minimumContacts",minimumContacts, ...
                        "labels",labels, ...
                        "chargeModel","oxidation_state_or_neutral_reference");
                    result=struct("model",model,"changed",false, ...
                        "message",sprintf("%d symmetry-unique defects enumerated.", ...
                        numel(variants)),"data",data, ...
                        "models",{variants},"labels",labels);
            end
        end
    end
end

function value=siteReferenceCharge(site)
value=0;
try
    specie=site.specie;
    if isprop(specie,"oxi_state") && ~isempty(specie.oxi_state) && ...
            isfinite(double(specie.oxi_state))
        value=double(specie.oxi_state);
    end
catch
    % Disordered or elemental sites use the documented neutral reference.
end
end

function value=changed(model,message,analysis)
if nargin<3, analysis=struct(); end
value=struct("model",model,"changed",true,"message",string(message), ...
    "analysis",analysis);
end
