classdef NanostructureCommands
    %NANOSTRUCTURECOMMANDS Dispatch native nanostructure builders.

    methods (Static)
        function ids = commandIds()
            ids = [
                "roll_nanotube"
                "cut_nanoribbon"
                "cut_nanowire"
                "quantum_dot_void"
                ];
        end

        function value = supports(commandId)
            value = any( ...
                kssolv.modeling.NanostructureCommands.commandIds() == ...
                string(commandId));
        end

        function result = execute(model, commandId, parameters)
            import kssolv.modeling.ParameterUtils
            commandId = string(commandId);
            vacuum = double(ParameterUtils.get( ...
                parameters, "vacuum", 8));
            maximumAtoms = double(ParameterUtils.get( ...
                parameters, "maximumAtoms", 100000));
            switch commandId
                case "roll_nanotube"
                    chiral = ParameterUtils.vector( ...
                        parameters, "chiralIndices", 2, [6, 0]);
                    lengthValue = double(ParameterUtils.get( ...
                        parameters, "length", 1));
                    model = ...
                        kssolv.modeling.builders.NanotubeBuilder.build( ...
                        model, chiral, length = lengthValue, ...
                        vacuum = vacuum, maximumAtoms = maximumAtoms);
                    message = "Nanotube created.";
                case "cut_nanoribbon"
                    width = double(ParameterUtils.get( ...
                        parameters, "width", 4));
                    lengthValue = double(ParameterUtils.get( ...
                        parameters, "length", 1));
                    edgeType = string(ParameterUtils.get( ...
                        parameters, "edgeType", "zigzag"));
                    model = ...
                        kssolv.modeling.builders.NanoribbonBuilder.build( ...
                        model, width = width, length = lengthValue, ...
                        edgeType = edgeType, vacuum = vacuum, ...
                        maximumAtoms = maximumAtoms);
                    message = "Nanoribbon created.";
                case "cut_nanowire"
                    direction = ParameterUtils.vector( ...
                        parameters, "direction", 3, [0, 0, 1]);
                    radius = double(ParameterUtils.get( ...
                        parameters, "radius", 5));
                    lengthValue = double(ParameterUtils.get( ...
                        parameters, "length", 1));
                    model = ...
                        kssolv.modeling.builders.NanowireBuilder.build( ...
                        model, direction, radius, length = lengthValue, ...
                        vacuum = vacuum, maximumAtoms = maximumAtoms);
                    message = "Nanowire created.";
                case "quantum_dot_void"
                    radius = double(ParameterUtils.get( ...
                        parameters, "radius", 5));
                    mode = string(ParameterUtils.get( ...
                        parameters, "mode", "dot"));
                    model = ...
                        kssolv.modeling.builders. ...
                        QuantumDotVoidBuilder.build( ...
                        model, radius, mode, vacuum = vacuum, ...
                        maximumAtoms = maximumAtoms);
                    message = "Nanoscale region created.";
                otherwise
                    error("KSSOLV:Modeling:NanostructureCommand", ...
                        "Unsupported Nanostructures command '%s'.", ...
                        commandId);
            end
            result = struct( ...
                "model", model, "changed", true, ...
                "message", string(message));
        end
    end
end
