classdef SupercellCommands
    %SUPERCELLCOMMANDS Cell-wide model transformations.

    methods (Static)
        function ids = commandIds()
            ids = [
                "build_supercell"
                "redefine_lattice"
                "orthogonalize_cell"
                "strain_structure"
                "perturb_structure"
                ];
        end

        function value = supports(commandId)
            value = any(kssolv.modeling.SupercellCommands.commandIds() == ...
                string(commandId));
        end

        function result = execute(model, commandId, parameters)
            import kssolv.modeling.ParameterUtils
            commandId = string(commandId);
            switch commandId
                case "build_supercell"
                    scaling = ParameterUtils.get( ...
                        parameters, "scalingMatrix", [2, 2, 2]);
                    model = model.make_supercell(scaling, true, true);
                case "redefine_lattice"
                    matrix = ParameterUtils.matrix(parameters, "matrix", ...
                        3, 3, model.lattice.matrix);
                    lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                        matrix, model.pbc);
                    cartesian = model.cart_coords;
                    model = model.set_lattice_preserve_fractional(lattice);
                    for index = 1:model.num_sites
                        model = model.replace( ...
                            index, [], cartesian(index, :), ...
                            coords_are_cartesian = true);
                    end
                case "orthogonalize_cell"
                    minLength = double(ParameterUtils.get( ...
                        parameters, "minimumLength", ...
                        min(model.lattice.lengths)));
                    maxLength = double(ParameterUtils.get( ...
                        parameters, "maximumLength", ...
                        max(model.lattice.lengths) * 4));
                    maxAtoms = double(ParameterUtils.get( ...
                        parameters, "maximumAtoms", 5000));
                    angleTolerance = double(ParameterUtils.get( ...
                        parameters, "angleTolerance", 0.1));
                    if ~isscalar(minLength) || ~isfinite(minLength) || ...
                            minLength <= 0 || ...
                            ~isscalar(maxLength) || ...
                            ~isfinite(maxLength) || ...
                            maxLength <= minLength
                        error("KSSOLV:Modeling:OrthogonalCellLengths", ...
                            "Maximum length must be finite and greater " + ...
                            "than the positive minimum length.");
                    end
                    if ~isscalar(angleTolerance) || ...
                            ~isfinite(angleTolerance) || ...
                            angleTolerance <= 0 || angleTolerance >= 10
                        error("KSSOLV:Modeling:OrthogonalCellAngle", ...
                            "Angle tolerance must be between 0 and 10 degrees.");
                    end
                    transformation = ...
                        kssolv.analysis.matgenlab.transformations. ...
                        CubicSupercellTransformation( ...
                        model.num_sites, maxAtoms, minLength, ...
                        maxLength, false, true, true, ...
                        angleTolerance, 0.1);
                    try
                        model = transformation.apply_transformation(model);
                    catch exception
                        known = startsWith(exception.identifier, ...
                            "KSSOLV:Matgenlab:CubicSupercell:");
                        if ~known
                            rethrow(exception)
                        end
                        error("KSSOLV:Modeling:OrthogonalCellNotFound", ...
                            "No integer supercell satisfying the requested " + ...
                            "90-degree, length and atom-count constraints " + ...
                            "was found. Increase Maximum cell length or " + ...
                            "Maximum atom count, relax Angle tolerance, or " + ...
                            "use a crystallographically compatible cell. " + ...
                            "Underlying reason: %s", exception.message);
                    end
                case "strain_structure"
                    model = model.apply_strain( ...
                        ParameterUtils.get(parameters, "strain", 0));
                case "perturb_structure"
                    distance = double(ParameterUtils.get( ...
                        parameters, "distance", 0.1));
                    minimum = double(ParameterUtils.get( ...
                        parameters, "minimumDistance", 0));
                    seed = ParameterUtils.get(parameters, "seed", 0);
                    model = model.perturb(distance, minimum, seed);
                otherwise
                    error("KSSOLV:Modeling:SupercellCommand", ...
                        "Unsupported Supercell & Lattice command '%s'.", ...
                        commandId);
            end
            result = struct( ...
                "model", model, "changed", true, ...
                "message", "Structure updated.");
        end
    end
end
