classdef SurfaceCommands
    %SURFACECOMMANDS Slab, vacuum and adsorption-site operations.

    methods (Static)
        function ids = commandIds()
            ids = [
                "build_slab"
                "add_vacuum"
                "insert_structure"
                "stack_heterostructure"
                "twist_moire"
                "interpolate_neb"
                "find_adsorption_sites"
                "locate_adsorbate"
                "place_adsorbate"
                "passivate_surface"
                "add_solvent_layer"
                ];
        end

        function value = supports(commandId)
            value = any(kssolv.modeling.SurfaceCommands.commandIds() == ...
                string(commandId));
        end

        function result = execute(model, commandId, parameters)
            import kssolv.modeling.ParameterUtils
            commandId = string(commandId);
            switch commandId
                case "build_slab"
                    miller = ParameterUtils.vector( ...
                        parameters, "millerIndex", 3, [0, 0, 1]);
                    slabSize = double(ParameterUtils.get( ...
                        parameters, "slabSize", 10));
                    vacuumSize = double(ParameterUtils.get( ...
                        parameters, "vacuumSize", 15));
                    center = ParameterUtils.logical( ...
                        parameters, "centerSlab", true);
                    primitive = ParameterUtils.logical( ...
                        parameters, "primitive", true);
                    generator = kssolv.analysis.matgenlab.core. ...
                        SlabGenerator(model, miller, slabSize, vacuumSize, ...
                        "center_slab", center, "primitive", primitive);
                    slabs = generator.get_slabs();
                    if isempty(slabs), slabs = {generator.get_slab()}; end
                    terminationIndex = double(ParameterUtils.get( ...
                        parameters, "terminationIndex", 1));
                    if ~isscalar(terminationIndex) || ...
                            terminationIndex ~= fix(terminationIndex) || ...
                            terminationIndex < 1 || ...
                            terminationIndex > numel(slabs)
                        error("KSSOLV:Modeling:SlabTermination", ...
                            "Termination index must be between 1 and %d.", ...
                            numel(slabs));
                    end
                    candidates = repmat(struct("index",0,"shift",0, ...
                        "formula","","atomCount",0,"surfaceArea",0, ...
                        "brokenBonds",0),1,numel(slabs));
                    for slabIndex = 1:numel(slabs)
                        slab = slabs{slabIndex};
                        area = norm(cross(slab.lattice.matrix(1,:), ...
                            slab.lattice.matrix(2,:)));
                        candidates(slabIndex) = struct( ...
                            "index", slabIndex, "shift", slab.shift, ...
                            "formula", string(slab.reduced_formula), ...
                            "atomCount", slab.num_sites, ...
                            "surfaceArea", area, ...
                            "brokenBonds", double(slab.energy));
                    end
                    model = annotateSurfaceLayers(slabs{terminationIndex}, ...
                        miller, terminationIndex, numel(slabs));
                    analysis = struct("terminations", candidates, ...
                        "selectedTermination", terminationIndex, ...
                        "millerIndex", reshape(miller,1,3), ...
                        "slabSize", slabSize, "vacuumSize", vacuumSize);
                    result = changed(model, "Surface slab created.", analysis);
                case "add_vacuum"
                    amount = double(ParameterUtils.get( ...
                        parameters, "amount", 10));
                    model = kssolv.modeling.SurfaceCommands. ...
                        addVacuum(model, amount);
                    result = changed(model, "Vacuum added.");
                case "insert_structure"
                    other = ParameterUtils.get( ...
                        parameters, "otherModel", []);
                    translation = ParameterUtils.vector( ...
                        parameters, "translation", 3, [0, 0, 0]);
                    minimumDistance = double(ParameterUtils.get( ...
                        parameters, "minimumDistance", 0.5));
                    model = ...
                        kssolv.modeling.builders. ...
                        InsertStructureBuilder.build( ...
                        model, other, translation = translation, ...
                        minimumDistance = minimumDistance);
                    result = changed(model, "Structure inserted.");
                case "stack_heterostructure"
                    other = ParameterUtils.get( ...
                        parameters, "otherModel", []);
                    gap = double(ParameterUtils.get( ...
                        parameters, "gap", 3.35));
                    vacuum = double(ParameterUtils.get( ...
                        parameters, "vacuum", 15));
                    maximumStrain = double(ParameterUtils.get( ...
                        parameters, "maximumStrain", 0.03));
                    maximumRepeat = double(ParameterUtils.get( ...
                        parameters, "maximumRepeat", 6));
                    sortMode = string(ParameterUtils.get( ...
                        parameters, "sortMode", "strain"));
                    maximumRotation=double(ParameterUtils.get( ...
                        parameters,"maximumRotation",30));
                    candidates = kssolv.modeling.builders. ...
                        InterfaceCandidateBuilder.enumerate( ...
                        model, other, maximumRepeat=maximumRepeat, ...
                        sortMode=sortMode,maximumRotation=maximumRotation);
                    candidateIndex = double(ParameterUtils.get( ...
                        parameters, "candidateIndex", 1));
                    if ~isscalar(candidateIndex) || ...
                            candidateIndex ~= fix(candidateIndex) || ...
                            candidateIndex < 1 || ...
                            candidateIndex > numel(candidates)
                        error("KSSOLV:Modeling:InterfaceCandidate", ...
                            "Interface candidate index must be between 1 and %d.", ...
                            numel(candidates));
                    end
                    selected = candidates(candidateIndex);
                    bottomModel=model*selected.bottomTransform;
                    topModel=other*selected.topTransform;
                    model = ...
                        kssolv.modeling.builders. ...
                        HeterostructureBuilder.build( ...
                        bottomModel, topModel, gap = gap, vacuum = vacuum, ...
                        maximumStrain = maximumStrain);
                    analysis = struct("candidates", candidates, ...
                        "selectedCandidate", candidateIndex, ...
                        "sortMode", sortMode);
                    result = changed(model, ...
                        "Heterostructure stacked.", analysis);
                case "twist_moire"
                    other = ParameterUtils.get( ...
                        parameters, "otherModel", []);
                    angle = double(ParameterUtils.get( ...
                        parameters, "angleDegrees", 21.786789));
                    gap = double(ParameterUtils.get( ...
                        parameters, "gap", 3.35));
                    vacuum = double(ParameterUtils.get( ...
                        parameters, "vacuum", 15));
                    maximumStrain = double(ParameterUtils.get( ...
                        parameters, "maximumStrain", 0.03));
                    maximumAtoms = double(ParameterUtils.get( ...
                        parameters, "maximumAtoms", 100000));
                    maximumIndex = double(ParameterUtils.get( ...
                        parameters, "maximumIndex", 60));
                    model = ...
                        kssolv.modeling.builders.MoireBuilder.build( ...
                        model, other, angle, gap = gap, ...
                        vacuum = vacuum, ...
                        maximumStrain = maximumStrain, ...
                        maximumAtoms = maximumAtoms, ...
                        maximumIndex = maximumIndex);
                    result = changed( ...
                        model, "Commensurate moire superlattice created.");
                case "interpolate_neb"
                    ending = ParameterUtils.get( ...
                        parameters, "endModel", []);
                    imageCount = double(ParameterUtils.get( ...
                        parameters, "intermediateCount", 5));
                    maximumSteps = double(ParameterUtils.get( ...
                        parameters, "maximumSteps", 200));
                    forceTolerance = double(ParameterUtils.get( ...
                        parameters, "forceTolerance", 0.1));
                    [images, diagnostics] = ...
                        kssolv.modeling.builders. ...
                        IDPPInterpolator.interpolate( ...
                        model, ending, imageCount, ...
                        maximumSteps = maximumSteps, ...
                        forceTolerance = forceTolerance);
                    labels = "NEB image " + ...
                        compose("%02d", 0:numel(images) - 1);
                    result = struct( ...
                        "model", model, "changed", false, ...
                        "message", idppMessage( ...
                        numel(images), diagnostics), ...
                        "data", diagnostics, ...
                        "models", {images}, "labels", labels);
                case "find_adsorption_sites"
                    distance = double(ParameterUtils.get( ...
                        parameters, "distance", 2));
                    finder = ...
                        kssolv.analysis.matgenlab.core. ...
                        AdsorbateSiteFinder(model);
                    sites = finder.find_adsorption_sites(distance);
                    count = sum(structfun(@(values) ...
                        size(values, 1), sites));
                    names = string(fieldnames(sites));
                    names = names(names ~= "all");
                    counts = arrayfun(@(name) ...
                        size(sites.(name), 1), names);
                    breakdown = join( ...
                        names + "=" + string(counts), ", ");
                    result = struct( ...
                        "model", model, "changed", false, ...
                        "message", sprintf( ...
                        "Found %d adsorption sites (%s).", ...
                        count, breakdown), "data", sites);
                case "locate_adsorbate"
                    adsorbate = ParameterUtils.get( ...
                        parameters, "adsorbateModel", []);
                    siteTypes = string(ParameterUtils.get( ...
                        parameters, "siteTypes", ...
                        ["ontop","bridge","hollow"]));
                    if isscalar(siteTypes)
                        siteTypes = split(strtrim(siteTypes));
                    end
                    heights = double(ParameterUtils.get( ...
                        parameters, "heights", [1.8,2.1,2.4]));
                    rotationStep = double(ParameterUtils.get( ...
                        parameters, "rotationStep", 30));
                    anchorAtom = double(ParameterUtils.get( ...
                        parameters, "anchorAtom", 1));
                    orientationAtom = double(ParameterUtils.get( ...
                        parameters, "orientationAtom", 0));
                    minimumDistance = double(ParameterUtils.get( ...
                        parameters, "minimumDistance", .6));
                    maximumCandidates = double(ParameterUtils.get( ...
                        parameters, "maximumCandidates", 200));
                    seed = double(ParameterUtils.get(parameters, "seed", 0));
                    scoringModel = string(ParameterUtils.get(parameters, ...
                        "scoringModel", ...
                        kssolv.modeling.adsorption. ...
                        AdsorptionScoringModel.GeometryId));
                    scoringFunction = ParameterUtils.get(parameters, ...
                        "scoringFunction", []);
                    scoringContract = ParameterUtils.get(parameters, ...
                        "scoringContract", struct());
                    analysis = kssolv.modeling.adsorption. ...
                        AdsorptionLocator.search(model, adsorbate, ...
                        SiteTypes = siteTypes, Heights = heights, ...
                        RotationStep = rotationStep, ...
                        AnchorAtom = anchorAtom, ...
                        OrientationAtom = orientationAtom, ...
                        MinimumDistance = minimumDistance, ...
                        MaximumCandidates = maximumCandidates, Seed = seed, ...
                        ScoringModel = scoringModel, ...
                        ScoringFunction = scoringFunction, ...
                        ScoringContract = scoringContract);
                    if analysis.isEnergyModel
                        summary = sprintf( ...
                            "Generated %d rigid candidates using %s (%s).", ...
                            analysis.candidateCount, analysis.scoringModel, ...
                            analysis.energyUnit);
                    else
                        summary = sprintf( ...
                            "Generated %d rigid geometry candidates; " + ...
                            "scores are not adsorption energies.", ...
                            analysis.candidateCount);
                    end
                    result = struct("model", model, "changed", false, ...
                        "message", summary, ...
                        "analysis", analysis, "data", analysis.candidates);
                case "place_adsorbate"
                    if isfield(parameters, "adsorbateCoordinates")
                        anchorSites = double(ParameterUtils.get( ...
                            parameters, "anchorSites", zeros(1, 0)));
                        species = ParameterUtils.get( ...
                            parameters, "adsorbateSpecies", strings(1, 0));
                        coordinates = double(ParameterUtils.get( ...
                            parameters, "adsorbateCoordinates", zeros(0, 3)));
                        bonds = double(ParameterUtils.get( ...
                            parameters, "adsorbateBonds", zeros(0, 3)));
                        anchorAtoms = double(ParameterUtils.get( ...
                            parameters, "anchorAtomIndices", 1));
                        name = string(ParameterUtils.get( ...
                            parameters, "adsorbateName", "Adsorbate"));
                        minimumDistance = double(ParameterUtils.get( ...
                            parameters, "minimumDistance", .35));
                        model = kssolv.modeling.builders. ...
                            AdsorbatePlacementBuilder.buildInteractive( ...
                            model, anchorSites, species, coordinates, bonds, ...
                            anchorAtomIndices = anchorAtoms, name = name, ...
                            minimumDistance = minimumDistance);
                        result = changed(model, ...
                            "Interactive " + name + " adsorbate placed.");
                    else
                        adsorbate=ParameterUtils.get(parameters,"adsorbateModel",[]);
                        siteType=string(ParameterUtils.get(parameters,"siteType","ontop"));
                        siteIndex=double(ParameterUtils.get(parameters,"siteIndex",1));
                        height=double(ParameterUtils.get(parameters,"height",2));
                        anchorAtom=double(ParameterUtils.get(parameters,"anchorAtom",1));
                        orientationAtom=double(ParameterUtils.get( ...
                            parameters,"orientationAtom",0));
                        direction=ParameterUtils.vector(parameters,"direction",3,[0,0,1]);
                        minimumDistance=double(ParameterUtils.get( ...
                            parameters,"minimumDistance",.5));
                        model=kssolv.modeling.builders.AdsorbatePlacementBuilder. ...
                            build(model,adsorbate,siteType=siteType, ...
                            siteIndex=siteIndex,height=height,anchorAtom=anchorAtom, ...
                            orientationAtom=orientationAtom,direction=direction, ...
                            minimumDistance=minimumDistance);
                        result=changed(model,"Adsorbate placed.");
                    end
                case "passivate_surface"
                    species = string(ParameterUtils.get( ...
                        parameters, "species", "H"));
                    bondLength = double(ParameterUtils.get( ...
                        parameters, "bondLength", 1.1));
                    side = string(ParameterUtils.get( ...
                        parameters, "side", "both"));
                    surfaceThickness = double(ParameterUtils.get( ...
                        parameters, "surfaceThickness", 1.5));
                    targetCoordination = double(ParameterUtils.get( ...
                        parameters, "targetCoordination", 0));
                    minimumDistance = double(ParameterUtils.get( ...
                        parameters, "minimumDistance", 0.6));
                    model = ...
                        kssolv.modeling.builders.PassivationBuilder.build( ...
                        model, species, bondLength = bondLength, ...
                        side = side, ...
                        surfaceThickness = surfaceThickness, ...
                        targetCoordination = targetCoordination, ...
                        minimumDistance = minimumDistance);
                    result = changed(model, "Surface passivated.");
                case "add_solvent_layer"
                    solvent = ParameterUtils.get( ...
                        parameters, "solventModel", []);
                    moleculeCount = double(ParameterUtils.get( ...
                        parameters, "moleculeCount", 20));
                    layerThickness = double(ParameterUtils.get( ...
                        parameters, "layerThickness", 10));
                    clearance = double(ParameterUtils.get( ...
                        parameters, "clearance", 2));
                    vacuum = double(ParameterUtils.get( ...
                        parameters, "vacuum", 5));
                    tolerance = double(ParameterUtils.get( ...
                        parameters, "tolerance", 2));
                    seed = double(ParameterUtils.get( ...
                        parameters, "seed", 1));
                    timeout = double(ParameterUtils.get( ...
                        parameters, "timeout", 60));
                    executor = ParameterUtils.get( ...
                        parameters, "executor", []);
                    model = ...
                        kssolv.modeling.builders.SolventLayerBuilder.build( ...
                        model, solvent, moleculeCount, ...
                        layerThickness = layerThickness, ...
                        clearance = clearance, vacuum = vacuum, ...
                        tolerance = tolerance, seed = seed, ...
                        timeout = timeout, executor = executor);
                    result = changed(model, "Solvent layer packed.");
                otherwise
                    error("KSSOLV:Modeling:SurfaceCommand", ...
                        "Unsupported Surfaces & Interfaces command '%s'.", ...
                        commandId);
            end

            function value = changed(updatedModel, message, analysis)
                if nargin < 3, analysis = struct(); end
                value = struct( ...
                    "model", updatedModel, "changed", true, ...
                    "message", string(message), "analysis", analysis);
            end

            function message = idppMessage(count, diagnostics)
                if diagnostics.converged
                    status = "converged";
                else
                    status = "did not converge";
                end
                message = sprintf( ...
                    "Generated %d IDPP path images; %s after %d steps " + ...
                    "(maximum force %.4g).", ...
                    count, status, diagnostics.iterations, ...
                    diagnostics.maximum_force);
            end
        end
    end

    methods (Static, Access = private)
        function model = addVacuum(model, amount)
            if ~isscalar(amount) || ~isfinite(amount) || amount <= 0
                error("KSSOLV:Modeling:VacuumAmount", ...
                    "Vacuum amount must be a positive finite scalar.");
            end
            oldMatrix = model.lattice.matrix;
            oldLength = norm(oldMatrix(3, :));
            direction = oldMatrix(3, :) / oldLength;
            cartesian = model.cart_coords;
            projections = cartesian * direction.';
            newMatrix = oldMatrix;
            newMatrix(3, :) = direction * (oldLength + amount);
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                newMatrix, model.pbc);
            model = model.set_lattice_preserve_fractional(lattice);
            shift = (norm(newMatrix(3, :)) - ...
                (max(projections) - min(projections))) / 2 - ...
                min(projections);
            shifted = cartesian + shift * direction;
            for index = 1:model.num_sites
                model = model.replace(index, [], shifted(index, :), ...
                    coords_are_cartesian = true);
            end
        end
    end
end

function model = annotateSurfaceLayers(model, miller, termination, count)
normal = cross(model.lattice.matrix(1,:), model.lattice.matrix(2,:));
normal = normal / norm(normal);
heights = model.cart_coords * normal.';
[ordered, order] = sort(heights);
layers = zeros(model.num_sites, 1);
layer = 0;
last = -Inf;
for index = 1:numel(order)
    if ordered(index) - last > 1e-3
        layer = layer + 1;
        last = ordered(index);
    end
    layers(order(index)) = layer;
end
sides = repmat("middle", model.num_sites, 1);
sides(layers == 1) = "bottom";
sides(layers == layer) = "top";
model = model.add_site_property("surface_layer", num2cell(layers.'));
model = model.add_site_property("surface_side", cellstr(sides.'));
model.properties.surface = struct("schemaVersion",1, ...
    "millerIndex",reshape(double(miller),1,3), ...
    "terminationIndex",termination,"terminationCount",count, ...
    "layerCount",layer);
end
