classdef SurfaceCommands
    %SURFACECOMMANDS Slab, vacuum and adsorption-site operations.

    methods (Static)
        function ids = commandIds()
            ids = [
                "build_slab"
                "add_vacuum"
                "insert_structure"
                "stack_heterostructure"
                "twist_moire"
                "interpolate_neb"
                "find_adsorption_sites"
                "passivate_surface"
                "add_solvent_layer"
                ];
        end

        function value = supports(commandId)
            value = any(kssolv.modeling.SurfaceCommands.commandIds() == ...
                string(commandId));
        end

        function result = execute(model, commandId, parameters)
            import kssolv.modeling.ParameterUtils
            commandId = string(commandId);
            switch commandId
                case "build_slab"
                    miller = ParameterUtils.vector( ...
                        parameters, "millerIndex", 3, [0, 0, 1]);
                    slabSize = double(ParameterUtils.get( ...
                        parameters, "slabSize", 10));
                    vacuumSize = double(ParameterUtils.get( ...
                        parameters, "vacuumSize", 15));
                    center = ParameterUtils.logical( ...
                        parameters, "centerSlab", true);
                    primitive = ParameterUtils.logical( ...
                        parameters, "primitive", true);
                    transformation = ...
                        kssolv.analysis.matgenlab.transformations. ...
                        SlabTransformation(miller, slabSize, vacuumSize, ...
                        false, center, false, primitive);
                    model = transformation.apply_transformation(model);
                    result = changed(model, "Surface slab created.");
                case "add_vacuum"
                    amount = double(ParameterUtils.get( ...
                        parameters, "amount", 10));
                    model = kssolv.modeling.SurfaceCommands. ...
                        addVacuum(model, amount);
                    result = changed(model, "Vacuum added.");
                case "insert_structure"
                    other = ParameterUtils.get( ...
                        parameters, "otherModel", []);
                    translation = ParameterUtils.vector( ...
                        parameters, "translation", 3, [0, 0, 0]);
                    minimumDistance = double(ParameterUtils.get( ...
                        parameters, "minimumDistance", 0.5));
                    model = ...
                        kssolv.modeling.builders. ...
                        InsertStructureBuilder.build( ...
                        model, other, translation = translation, ...
                        minimumDistance = minimumDistance);
                    result = changed(model, "Structure inserted.");
                case "stack_heterostructure"
                    other = ParameterUtils.get( ...
                        parameters, "otherModel", []);
                    gap = double(ParameterUtils.get( ...
                        parameters, "gap", 3.35));
                    vacuum = double(ParameterUtils.get( ...
                        parameters, "vacuum", 15));
                    maximumStrain = double(ParameterUtils.get( ...
                        parameters, "maximumStrain", 0.03));
                    model = ...
                        kssolv.modeling.builders. ...
                        HeterostructureBuilder.build( ...
                        model, other, gap = gap, vacuum = vacuum, ...
                        maximumStrain = maximumStrain);
                    result = changed(model, "Heterostructure stacked.");
                case "twist_moire"
                    other = ParameterUtils.get( ...
                        parameters, "otherModel", []);
                    angle = double(ParameterUtils.get( ...
                        parameters, "angleDegrees", 21.786789));
                    gap = double(ParameterUtils.get( ...
                        parameters, "gap", 3.35));
                    vacuum = double(ParameterUtils.get( ...
                        parameters, "vacuum", 15));
                    maximumStrain = double(ParameterUtils.get( ...
                        parameters, "maximumStrain", 0.03));
                    maximumAtoms = double(ParameterUtils.get( ...
                        parameters, "maximumAtoms", 100000));
                    maximumIndex = double(ParameterUtils.get( ...
                        parameters, "maximumIndex", 60));
                    model = ...
                        kssolv.modeling.builders.MoireBuilder.build( ...
                        model, other, angle, gap = gap, ...
                        vacuum = vacuum, ...
                        maximumStrain = maximumStrain, ...
                        maximumAtoms = maximumAtoms, ...
                        maximumIndex = maximumIndex);
                    result = changed( ...
                        model, "Commensurate moire superlattice created.");
                case "interpolate_neb"
                    ending = ParameterUtils.get( ...
                        parameters, "endModel", []);
                    imageCount = double(ParameterUtils.get( ...
                        parameters, "intermediateCount", 5));
                    maximumSteps = double(ParameterUtils.get( ...
                        parameters, "maximumSteps", 200));
                    forceTolerance = double(ParameterUtils.get( ...
                        parameters, "forceTolerance", 0.1));
                    [images, diagnostics] = ...
                        kssolv.modeling.builders. ...
                        IDPPInterpolator.interpolate( ...
                        model, ending, imageCount, ...
                        maximumSteps = maximumSteps, ...
                        forceTolerance = forceTolerance);
                    labels = "NEB image " + ...
                        compose("%02d", 0:numel(images) - 1);
                    result = struct( ...
                        "model", model, "changed", false, ...
                        "message", idppMessage( ...
                        numel(images), diagnostics), ...
                        "data", diagnostics, ...
                        "models", {images}, "labels", labels);
                case "find_adsorption_sites"
                    distance = double(ParameterUtils.get( ...
                        parameters, "distance", 2));
                    finder = ...
                        kssolv.analysis.matgenlab.core. ...
                        AdsorbateSiteFinder(model);
                    sites = finder.find_adsorption_sites(distance);
                    count = sum(structfun(@(values) ...
                        size(values, 1), sites));
                    names = string(fieldnames(sites));
                    names = names(names ~= "all");
                    counts = arrayfun(@(name) ...
                        size(sites.(name), 1), names);
                    breakdown = join( ...
                        names + "=" + string(counts), ", ");
                    result = struct( ...
                        "model", model, "changed", false, ...
                        "message", sprintf( ...
                        "Found %d adsorption sites (%s).", ...
                        count, breakdown), "data", sites);
                case "passivate_surface"
                    species = string(ParameterUtils.get( ...
                        parameters, "species", "H"));
                    bondLength = double(ParameterUtils.get( ...
                        parameters, "bondLength", 1.1));
                    side = string(ParameterUtils.get( ...
                        parameters, "side", "both"));
                    surfaceThickness = double(ParameterUtils.get( ...
                        parameters, "surfaceThickness", 1.5));
                    targetCoordination = double(ParameterUtils.get( ...
                        parameters, "targetCoordination", 0));
                    minimumDistance = double(ParameterUtils.get( ...
                        parameters, "minimumDistance", 0.6));
                    model = ...
                        kssolv.modeling.builders.PassivationBuilder.build( ...
                        model, species, bondLength = bondLength, ...
                        side = side, ...
                        surfaceThickness = surfaceThickness, ...
                        targetCoordination = targetCoordination, ...
                        minimumDistance = minimumDistance);
                    result = changed(model, "Surface passivated.");
                case "add_solvent_layer"
                    solvent = ParameterUtils.get( ...
                        parameters, "solventModel", []);
                    moleculeCount = double(ParameterUtils.get( ...
                        parameters, "moleculeCount", 20));
                    layerThickness = double(ParameterUtils.get( ...
                        parameters, "layerThickness", 10));
                    clearance = double(ParameterUtils.get( ...
                        parameters, "clearance", 2));
                    vacuum = double(ParameterUtils.get( ...
                        parameters, "vacuum", 5));
                    tolerance = double(ParameterUtils.get( ...
                        parameters, "tolerance", 2));
                    seed = double(ParameterUtils.get( ...
                        parameters, "seed", 1));
                    timeout = double(ParameterUtils.get( ...
                        parameters, "timeout", 60));
                    executor = ParameterUtils.get( ...
                        parameters, "executor", []);
                    model = ...
                        kssolv.modeling.builders.SolventLayerBuilder.build( ...
                        model, solvent, moleculeCount, ...
                        layerThickness = layerThickness, ...
                        clearance = clearance, vacuum = vacuum, ...
                        tolerance = tolerance, seed = seed, ...
                        timeout = timeout, executor = executor);
                    result = changed(model, "Solvent layer packed.");
                otherwise
                    error("KSSOLV:Modeling:SurfaceCommand", ...
                        "Unsupported Surfaces & Interfaces command '%s'.", ...
                        commandId);
            end

            function value = changed(updatedModel, message)
                value = struct( ...
                    "model", updatedModel, "changed", true, ...
                    "message", string(message));
            end

            function message = idppMessage(count, diagnostics)
                if diagnostics.converged
                    status = "converged";
                else
                    status = "did not converge";
                end
                message = sprintf( ...
                    "Generated %d IDPP path images; %s after %d steps " + ...
                    "(maximum force %.4g).", ...
                    count, status, diagnostics.iterations, ...
                    diagnostics.maximum_force);
            end
        end
    end

    methods (Static, Access = private)
        function model = addVacuum(model, amount)
            if ~isscalar(amount) || ~isfinite(amount) || amount <= 0
                error("KSSOLV:Modeling:VacuumAmount", ...
                    "Vacuum amount must be a positive finite scalar.");
            end
            oldMatrix = model.lattice.matrix;
            oldLength = norm(oldMatrix(3, :));
            direction = oldMatrix(3, :) / oldLength;
            cartesian = model.cart_coords;
            projections = cartesian * direction.';
            newMatrix = oldMatrix;
            newMatrix(3, :) = direction * (oldLength + amount);
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                newMatrix, model.pbc);
            model = model.set_lattice_preserve_fractional(lattice);
            shift = (norm(newMatrix(3, :)) - ...
                (max(projections) - min(projections))) / 2 - ...
                min(projections);
            shifted = cartesian + shift * direction;
            for index = 1:model.num_sites
                model = model.replace(index, [], shifted(index, :), ...
                    coords_are_cartesian = true);
            end
        end
    end
end
