classdef SymmetryEditPlanner
    %SYMMETRYEDITPLANNER Estimate and enforce symmetry-aware site edits.

    methods (Static)
        function [parameters, plan] = prepare(model, parameters)
            plan = struct.empty;
            if ~isa(model, ...
                    "kssolv.analysis.matgenlab.core.IStructure") || ...
                    ~isfield(parameters, "symmetryMode")
                return
            end
            mode = lower(strtrim(string(parameters.symmetryMode)));
            if ~isscalar(mode) || ~any(mode == ["preserve", "break"])
                error("KSSOLV:Modeling:SymmetryMode", ...
                    "Symmetry mode must be preserve or break.");
            end
            indices = kssolv.modeling.ParameterUtils.indices( ...
                parameters, model.num_sites, []);
            if isempty(indices)
                error("KSSOLV:Modeling:SymmetrySelection", ...
                    "A symmetry-aware edit requires selected sites.");
            end
            analyzer = kssolv.analysis.matgenlab.symmetry.analyzer. ...
                SpacegroupAnalyzer(model, 0.01, 5);
            dataset = analyzer.get_symmetry_dataset();
            affected = zeros(1, 0);
            for index = indices
                representative = dataset.equivalent_atoms(index);
                affected = [affected, ... %#ok<AGROW>
                    find(dataset.equivalent_atoms == representative)];
            end
            affected = unique(affected, "stable");
            plan = struct( ...
                "mode", mode, ...
                "selectedIndices", reshape(indices, 1, []), ...
                "affectedIndices", reshape(affected, 1, []), ...
                "selectedCount", numel(indices), ...
                "affectedCount", numel(affected), ...
                "originalSpaceGroup", dataset.international, ...
                "originalNumber", dataset.number, ...
                "resultSpaceGroup", "", ...
                "resultNumber", 0);
            if mode == "preserve"
                parameters.indices = affected;
            end
        end

        function [model, plan] = finalize(model, plan)
            if isempty(plan), return, end
            try
                analyzer = kssolv.analysis.matgenlab.symmetry.analyzer. ...
                    SpacegroupAnalyzer(model, 0.01, 5);
                dataset = analyzer.get_symmetry_dataset();
                plan.resultSpaceGroup = dataset.international;
                plan.resultNumber = dataset.number;
            catch exception
                if plan.mode == "preserve"
                    error("KSSOLV:Modeling:SymmetryPreservation", ...
                        "The edit cannot preserve the source symmetry: %s", ...
                        exception.message);
                end
                plan.resultSpaceGroup = "undetermined";
                plan.resultNumber = 0;
            end
            if plan.mode == "preserve" && ...
                    plan.resultNumber ~= plan.originalNumber
                error("KSSOLV:Modeling:SymmetryPreservation", ...
                    "The proposed edit changes space group %s (#%d) to " + ...
                    "%s (#%d). Choose break symmetry to apply it.", ...
                    plan.originalSpaceGroup, plan.originalNumber, ...
                    plan.resultSpaceGroup, plan.resultNumber);
            end
            properties = model.structure_properties;
            properties.symmetryEdit = struct( ...
                "schemaVersion", 1, "mode", plan.mode, ...
                "selectedCount", plan.selectedCount, ...
                "affectedCount", plan.affectedCount, ...
                "originalSpaceGroup", plan.originalSpaceGroup, ...
                "resultSpaceGroup", plan.resultSpaceGroup);
            model = model.copy([], false, properties);
        end
    end
end
