function input = gs_input(structure, pseudos, varargin)
options = parseFactory(varargin{:});
multi = kssolv.analysis.matgenlab.io.abinit.ebands_input(structure,pseudos, ...
    "kppa",options.kppa,"ndivsm",0,"ecut",options.ecut, ...
    "pawecutdg",options.pawecutdg,"scf_nband",options.scf_nband, ...
    "accuracy",options.accuracy,"spin_mode",options.spin_mode, ...
    "smearing",options.smearing,"charge",options.charge, ...
    "scf_algorithm",options.scf_algorithm);
input = multi(1);
end
function o=parseFactory(varargin)
o=struct("kppa",[],"ecut",[],"pawecutdg",[],"scf_nband",[],"accuracy","normal","spin_mode","polarized","smearing","fermi_dirac:0.1 eV","charge",0,"scf_algorithm",[]);
for i=1:2:numel(varargin),o.(char(string(varargin{i})))=varargin{i+1};end
end
