classdef VolumetricData < ...
        kssolv.analysis.matgenlab.io.vasp.VolumetricData
    %VOLUMETRICDATA Common volumetric-data API shared by simulation formats.

    methods
        function obj = VolumetricData(structure, data, options)
            arguments
                structure
                data (1,1) struct
                options.distance_matrix = struct()
                options.data_aug (1,1) struct = struct()
                options.grid_origin (1,3) double = [0, 0, 0]
                options.voxel_vectors double = zeros(0, 3)
                options.grid_periodic (1,3) logical = [true, true, true]
                options.grid_sampling (1,1) string = "cell-periodic"
                options.channel_labels (1,1) struct = struct()
            end
            obj@kssolv.analysis.matgenlab.io.vasp.VolumetricData( ...
                structure, data, ...
                distance_matrix = options.distance_matrix, ...
                data_aug = options.data_aug, ...
                grid_origin = options.grid_origin, ...
                voxel_vectors = options.voxel_vectors, ...
                grid_periodic = options.grid_periodic, ...
                grid_sampling = options.grid_sampling, ...
                channel_labels = options.channel_labels);
        end

        function output = copy(obj)
            output = ...
                kssolv.analysis.matgenlab.io.common.VolumetricData( ...
                    obj.structure, obj.data, data_aug = obj.data_aug, ...
                    grid_origin = obj.grid_origin, ...
                    voxel_vectors = obj.voxel_vectors, ...
                    grid_periodic = obj.grid_periodic, ...
                    grid_sampling = obj.grid_sampling, ...
                    channel_labels = obj.channel_labels);
            output.name = obj.name;
        end
    end

    methods (Static)
        function obj = from_hdf5(filename, varargin)
            base = kssolv.analysis.matgenlab.io.vasp.VolumetricData. ...
                from_hdf5(filename, varargin{:});
            obj = ...
                kssolv.analysis.matgenlab.io.common.VolumetricData( ...
                    base.structure, base.data, data_aug = base.data_aug, ...
                    grid_origin = base.grid_origin, ...
                    voxel_vectors = base.voxel_vectors, ...
                    grid_periodic = base.grid_periodic, ...
                    grid_sampling = base.grid_sampling, ...
                    channel_labels = base.channel_labels);
            obj.name = base.name;
        end

        function obj = from_cube(filename)
            base = kssolv.analysis.matgenlab.io.vasp.VolumetricData. ...
                from_cube(filename);
            obj = ...
                kssolv.analysis.matgenlab.io.common.VolumetricData( ...
                    base.structure, base.data, data_aug = base.data_aug, ...
                    grid_origin = base.grid_origin, ...
                    voxel_vectors = base.voxel_vectors, ...
                    grid_periodic = base.grid_periodic, ...
                    grid_sampling = base.grid_sampling, ...
                    channel_labels = base.channel_labels);
            obj.name = base.name;
        end
    end
end
