classdef AdsorbatePlacementBuilder
    %ADSORBATEPLACEMENTBUILDER Place and orient a finite guest on a slab.
    methods (Static)
        function output=build(host,adsorbate,options)
            arguments
                host
                adsorbate
                options.siteType {mustBeTextScalar}="ontop"
                options.siteIndex (1,1) double {mustBeInteger,mustBePositive}=1
                options.height (1,1) double {mustBePositive}=2
                options.anchorAtom (1,1) double {mustBeInteger,mustBePositive}=1
                options.orientationAtom (1,1) double {mustBeInteger,mustBeNonnegative}=0
                options.direction (1,3) double=[0,0,1]
                options.minimumDistance (1,1) double {mustBeNonnegative}=.5
            end
            kssolv.modeling.builders.BuilderUtils.requireStructure(host);
            if ~(isa(adsorbate,"kssolv.analysis.matgenlab.core.IMolecule") || ...
                    isa(adsorbate,"kssolv.analysis.matgenlab.core.IStructure"))
                error("KSSOLV:Modeling:AdsorbateType", ...
                    "Adsorbate must be a molecule or structure.");
            end
            if options.anchorAtom>adsorbate.num_sites || ...
                    options.orientationAtom>adsorbate.num_sites
                error("KSSOLV:Modeling:AdsorbateAnchor", ...
                    "Adsorbate anchor/orientation atom is outside the model.");
            end
            finder=kssolv.analysis.matgenlab.core.AdsorbateSiteFinder(host);
            sites=finder.find_adsorption_sites(0);
            siteType=lower(string(options.siteType));
            if ~isfield(sites,siteType) || isempty(sites.(siteType))
                error("KSSOLV:Modeling:AdsorptionSiteType", ...
                    "No adsorption sites of type '%s' are available.",siteType);
            end
            candidates=sites.(siteType);
            if options.siteIndex>size(candidates,1)
                error("KSSOLV:Modeling:AdsorptionSiteIndex", ...
                    "Adsorption site index exceeds the %s candidate count.",siteType);
            end
            normal=host.lattice.matrix(3,:); normal=normal/norm(normal);
            direction=options.direction/norm(options.direction);
            coordinates=adsorbate.cart_coords;
            anchor=coordinates(options.anchorAtom,:);
            if options.orientationAtom>0 && ...
                    options.orientationAtom~=options.anchorAtom
                source=coordinates(options.orientationAtom,:)-anchor;
                coordinates=(coordinates-anchor)*align(source,direction).'+anchor;
            end
            target=candidates(options.siteIndex,:)+options.height*normal;
            coordinates=coordinates+(target-coordinates(options.anchorAtom,:));
            guest=kssolv.analysis.matgenlab.core.Structure(host.lattice, ...
                adsorbate.species_and_occu,coordinates,coords_are_cartesian=true, ...
                site_properties=adsorbate.site_properties,skip_checks=true);
            output=kssolv.modeling.builders.InsertStructureBuilder.build( ...
                host,guest,minimumDistance=options.minimumDistance,wrap=true);
            properties=output.structure_properties;
            properties.adsorbate=struct( ...
                "schemaVersion",2, ...
                "placementMode","catalog-site", ...
                "name",string(adsorbate.formula), ...
                "species",siteSymbols(adsorbate), ...
                "coordinates",coordinates, ...
                "bonds",topologyBonds(adsorbate), ...
                "anchorAtomIndices",options.anchorAtom, ...
                "guestFormula",adsorbate.formula, ...
                "siteDescriptor",struct( ...
                    "type",siteType, ...
                    "candidateIndex",options.siteIndex, ...
                    "coordinates",candidates(options.siteIndex,:), ...
                    "offset",options.height), ...
                "orientationDescriptor",struct( ...
                    "referenceAtomIndex",options.orientationAtom, ...
                    "direction",direction));
            output=output.copy([],false,properties);
        end

        function output = buildInteractive( ...
                host, anchorSites, species, coordinates, bonds, options)
            %BUILDINTERACTIVE Commit any directly manipulated adsorbate.
            arguments
                host
                anchorSites double
                species
                coordinates double
                bonds double = zeros(0, 3)
                options.anchorAtomIndices double = 1
                options.name {mustBeTextScalar} = "Adsorbate"
                options.minimumDistance (1,1) double ...
                    {mustBeNonnegative} = .35
            end
            kssolv.modeling.builders.BuilderUtils.requireStructure(host);
            anchorSites = reshape(double(anchorSites), 1, []);
            anchorAtoms = reshape(double(options.anchorAtomIndices), 1, []);
            species = reshape(string(species), 1, []);
            coordinates = double(coordinates);
            bonds = double(bonds);
            if isempty(bonds), bonds = zeros(0, 3); end
            if isempty(anchorSites) || numel(anchorSites) ~= numel(anchorAtoms) || ...
                    any(anchorSites ~= fix(anchorSites)) || ...
                    any(anchorSites < 1) || any(anchorSites > host.num_sites)
                error("KSSOLV:Modeling:AdsorbateAnchor", ...
                    "Interactive host anchors must reference existing atoms.");
            end
            if isempty(species) || any(species == "") || ...
                    ~isequal(size(coordinates), [numel(species), 3]) || ...
                    any(~isfinite(coordinates), "all")
                error("KSSOLV:Modeling:AdsorbateCoordinates", ...
                    "Interactive adsorbate species and finite N-by-3 coordinates are required.");
            end
            if any(anchorAtoms ~= fix(anchorAtoms)) || ...
                    any(anchorAtoms < 1) || any(anchorAtoms > numel(species))
                error("KSSOLV:Modeling:AdsorbateGuestAnchor", ...
                    "Interactive guest anchors must reference adsorbate atoms.");
            end
            bonds = validateBonds(bonds, numel(species));
            hostDistances = vecnorm( ...
                coordinates(anchorAtoms, :) - host.cart_coords(anchorSites, :), ...
                2, 2);
            if any(hostDistances < options.minimumDistance)
                error("KSSOLV:Modeling:AdsorbateBondLength", ...
                    "Every sketched host-adsorbate distance must be at least %.4g angstrom.", ...
                    options.minimumDistance);
            end
            if ~isempty(bonds)
                internalDistances = vecnorm( ...
                    coordinates(bonds(:,1), :) - coordinates(bonds(:,2), :), ...
                    2, 2);
                if any(internalDistances < options.minimumDistance)
                    error("KSSOLV:Modeling:AdsorbateBondLength", ...
                        "Every sketched internal bond must be at least %.4g angstrom.", ...
                        options.minimumDistance);
                end
            end
            labels = species + "_ads" + string(1:numel(species));
            guest = kssolv.analysis.matgenlab.core.Structure( ...
                host.lattice, cellstr(species), coordinates, ...
                coords_are_cartesian = true, labels = labels, ...
                skip_checks = true);
            output = kssolv.modeling.builders.InsertStructureBuilder.build( ...
                host, guest, minimumDistance = options.minimumDistance, ...
                wrap = false);
            properties = output.structure_properties;
            properties.adsorbate = struct( ...
                "schemaVersion", 2, "placementMode", "direct-manipulation", ...
                "name", string(options.name), "species", species, ...
                "coordinates", coordinates, "bonds", bonds, ...
                "anchorAtomIndices", anchorAtoms, ...
                "hostAnchorSites", anchorSites, ...
                "hostAnchorLabels", string(host.labels(anchorSites)), ...
                "hostBondLengths", reshape(hostDistances, 1, []), ...
                "guestFormula", guest.formula);
            output = output.copy([], false, properties);
        end
    end
end

function bonds = topologyBonds(model)
bonds = zeros(0, 3);
if isfield(model.properties, "topology") && ...
        isfield(model.properties.topology, "bonds")
    bonds = double(model.properties.topology.bonds);
end
end

function species = siteSymbols(model)
species = strings(1, model.num_sites);
for index = 1:model.num_sites
    species(index) = string(model(index).specie.symbol);
end
end

function bonds = validateBonds(bonds, count)
if size(bonds, 2) ~= 3 || any(~isfinite(bonds), "all") || ...
        any(bonds(:,1:2) ~= fix(bonds(:,1:2)), "all") || ...
        any(bonds(:,1:2) < 1, "all") || any(bonds(:,1:2) > count, "all") || ...
        any(bonds(:,1) == bonds(:,2)) || ...
        any(~ismember(bonds(:,3), [1, 1.5, 2, 3]))
    error("KSSOLV:Modeling:AdsorbateTopology", ...
        "Interactive adsorbate bonds must be valid [i,j,order] rows.");
end
if size(unique(sort(bonds(:,1:2), 2), "rows"), 1) ~= size(bonds, 1)
    error("KSSOLV:Modeling:AdsorbateTopology", ...
        "Interactive adsorbate bonds cannot contain duplicate atom pairs.");
end
end

function rotation=align(source,target)
source=source/norm(source); target=target/norm(target);
crossValue=cross(source,target); sine=norm(crossValue); cosine=dot(source,target);
if sine<1e-12
    if cosine>0, rotation=eye(3); return, end
    axis=null(source).'; axis=axis(1,:); crossValue=axis; sine=1; cosine=-1;
end
axis=crossValue/sine;
skew=[0,-axis(3),axis(2);axis(3),0,-axis(1);-axis(2),axis(1),0];
rotation=eye(3)+skew*sine+skew^2*(1-cosine);
end
