classdef HeterostructureBuilder
    %HETEROSTRUCTUREBUILDER Stack two commensurate 2-D cells.

    methods (Static)
        function output = build(bottom, top, options)
            arguments
                bottom
                top
                options.gap (1,1) double = 3.35
                options.vacuum (1,1) double = 15
                options.maximumStrain (1,1) double = 0.03
            end
            import kssolv.modeling.builders.BuilderUtils
            BuilderUtils.requireTwoDimensional(bottom);
            BuilderUtils.requireTwoDimensional(top);
            gap = BuilderUtils.positiveScalar( ...
                options.gap, "Interlayer gap");
            vacuum = BuilderUtils.positiveScalar( ...
                options.vacuum, "Vacuum");
            maximumStrain = double(options.maximumStrain);
            if ~isscalar(maximumStrain) || ~isfinite(maximumStrain) || ...
                    maximumStrain < 0
                error("KSSOLV:Modeling:HeterostructureStrain", ...
                    "Maximum strain must be a finite nonnegative scalar.");
            end

            bottomPlane = bottom.lattice.matrix(1:2, :);
            topPlane = top.lattice.matrix(1:2, :);
            strain = BuilderUtils.inPlanePrincipalStrain( ...
                bottomPlane, topPlane);
            if strain > maximumStrain
                error("KSSOLV:Modeling:HeterostructureMismatch", ...
                    "In-plane cell mismatch %.4g exceeds the limit %.4g.", ...
                    strain, maximumStrain);
            end
            normal = cross(bottomPlane(1, :), bottomPlane(2, :));
            normal = normal / norm(normal);
            bottomNormal = bottom.cart_coords * normal.';
            topNormalVector = cross(topPlane(1, :), topPlane(2, :));
            topNormalVector = topNormalVector / norm(topNormalVector);
            topNormal = top.cart_coords * topNormalVector.';
            bottomHeight = max(bottomNormal) - min(bottomNormal);
            topHeight = max(topNormal) - min(topNormal);
            height = bottomHeight + gap + topHeight + vacuum;
            bottomZ = bottomNormal - min(bottomNormal) + vacuum / 2;
            topZ = topNormal - min(topNormal) + ...
                vacuum / 2 + bottomHeight + gap;
            bottomCartesian = ...
                bottom.frac_coords(:, 1:2) * bottomPlane + ...
                bottomZ * normal;
            topCartesian = ...
                top.frac_coords(:, 1:2) * bottomPlane + ...
                topZ * normal;
            latticeMatrix = [
                bottomPlane
                normal * height
                ];
            properties = BuilderUtils.combineProperties( ...
                bottom.site_properties, top.site_properties, ...
                bottom.num_sites, top.num_sites);
            properties.modeling_layer = [
                repmat({1}, 1, bottom.num_sites), ...
                repmat({2}, 1, top.num_sites)
                ];
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                latticeMatrix, [true, true, false]);
            output = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, ...
                [bottom.species_and_occu, top.species_and_occu], ...
                [bottomCartesian; topCartesian], ...
                coords_are_cartesian = true, ...
                site_properties = properties, ...
                labels = [bottom.labels, top.labels], ...
                properties = bottom.structure_properties, ...
                skip_checks = true);
            output.properties.heterostructure = struct( ...
                "gap", gap, "vacuum", vacuum, ...
                "principal_strain", strain, ...
                "metric_mismatch", strain, ...
                "top_formula", top.formula);
        end
    end
end
