classdef InsertStructureBuilder
    %INSERTSTRUCTUREBUILDER Insert a guest model into a host periodic cell.

    methods (Static)
        function output = build(host, guest, options)
            arguments
                host
                guest
                options.translation (1,3) double = [0, 0, 0]
                options.minimumDistance (1,1) double = 0.5
                options.wrap (1,1) logical = true
            end
            import kssolv.modeling.builders.BuilderUtils
            BuilderUtils.requireStructure(host);
            BuilderUtils.requireStructure(guest);
            minimumDistance = double(options.minimumDistance);
            if ~isscalar(minimumDistance) || ...
                    ~isfinite(minimumDistance) || minimumDistance < 0
                error("KSSOLV:Modeling:InsertMinimumDistance", ...
                    "Minimum distance must be a finite nonnegative scalar.");
            end
            coordinates = guest.cart_coords + options.translation;
            fractional = host.lattice.get_fractional_coords(coordinates);
            if options.wrap
                fractional(:, host.pbc) = ...
                    mod(fractional(:, host.pbc), 1);
                coordinates = host.lattice. ...
                    get_cartesian_coords(fractional);
            end
            if minimumDistance > 0
                crossDistances = host.lattice.get_all_distances( ...
                    host.frac_coords, fractional);
                guestDistances = host.lattice.get_all_distances( ...
                    fractional, fractional);
                guestDistances(1:size(guestDistances, 1) + 1:end) = Inf;
                if any(crossDistances(:) < minimumDistance) || ...
                        any(guestDistances(:) < minimumDistance)
                    error("KSSOLV:Modeling:InsertCollision", ...
                        "Insertion creates a pair closer than %.4g angstrom.", ...
                        minimumDistance);
                end
            end
            species = [host.species_and_occu, guest.species_and_occu];
            properties = BuilderUtils.combineProperties( ...
                host.site_properties, guest.site_properties, ...
                host.num_sites, guest.num_sites);
            properties.modeling_origin = [
                repmat({"host"}, 1, host.num_sites), ...
                repmat({"guest"}, 1, guest.num_sites)
                ];
            output = kssolv.analysis.matgenlab.core.Structure( ...
                host.lattice, species, ...
                [host.cart_coords; coordinates], ...
                coords_are_cartesian = true, ...
                site_properties = properties, ...
                labels = [host.labels, guest.labels], ...
                properties = host.structure_properties, ...
                skip_checks = true);
            output.properties.inserted_structure = struct( ...
                "translation", options.translation, ...
                "guest_formula", guest.formula);
        end
    end
end
