classdef NanowireBuilder
    %NANOWIREBUILDER Cut a cylindrical, one-dimensionally periodic wire.

    methods (Static)
        function wire = build(parent, direction, radius, options)
            arguments
                parent
                direction (1,3) double
                radius (1,1) double
                options.length (1,1) double = 1
                options.vacuum (1,1) double = 8
                options.maximumAtoms (1,1) double = 100000
            end
            import kssolv.modeling.builders.BuilderUtils
            BuilderUtils.requireStructure(parent);
            radius = BuilderUtils.positiveScalar(radius, "Wire radius");
            lengthValue = BuilderUtils.positiveInteger( ...
                options.length, "Wire length");
            vacuum = BuilderUtils.positiveScalar( ...
                options.vacuum, "Vacuum");
            maximumAtoms = BuilderUtils.positiveInteger( ...
                options.maximumAtoms, "Maximum atom count");
            if any(direction ~= fix(direction)) || all(direction == 0)
                error("KSSOLV:Modeling:NanowireDirection", ...
                    "Wire direction must contain three integers.");
            end
            [first, second] = BuilderUtils.transverseIntegerBasis( ...
                parent.lattice, direction, 6);
            axisVector = direction * parent.lattice.matrix;
            firstVector = first * parent.lattice.matrix;
            secondVector = second * parent.lattice.matrix;
            firstPerpendicular = firstVector - ...
                dot(firstVector, axisVector) / dot(axisVector, axisVector) * ...
                axisVector;
            secondPerpendicular = secondVector - ...
                dot(secondVector, axisVector) / dot(axisVector, axisVector) * ...
                axisVector;
            firstScale = max(1, ceil(2 * radius / ...
                norm(firstPerpendicular)) + 2);
            secondScale = max(1, ceil(2 * radius / ...
                norm(secondPerpendicular)) + 2);
            transform = [
                firstScale * first
                secondScale * second
                lengthValue * direction
                ];
            predicted = abs(round(det(transform))) * parent.num_sites;
            if predicted > maximumAtoms
                error("KSSOLV:Modeling:NanowireAtomLimit", ...
                    "The nanowire parent supercell would contain %d atoms " + ...
                    "(limit %d).", predicted, maximumAtoms);
            end
            supercell = parent * transform;
            [firstUnit, secondUnit, axisUnit] = BuilderUtils.frame( ...
                supercell.lattice.matrix(3, :), ...
                supercell.lattice.matrix(1, :));
            positions = supercell.cart_coords;
            projected = [
                positions * firstUnit.', ...
                positions * secondUnit.', ...
                positions * axisUnit.'
                ];
            center = [
                (min(projected(:, 1)) + max(projected(:, 1))) / 2, ...
                (min(projected(:, 2)) + max(projected(:, 2))) / 2
                ];
            radialDistance = hypot( ...
                projected(:, 1) - center(1), ...
                projected(:, 2) - center(2));
            indices = find(radialDistance <= radius + 1e-8).';
            if isempty(indices)
                error("KSSOLV:Modeling:NanowireEmpty", ...
                    "No sites fall inside the requested wire radius.");
            end
            selected = projected(indices, :);
            selected(:, 1) = selected(:, 1) - ...
                min(selected(:, 1)) + vacuum;
            selected(:, 2) = selected(:, 2) - ...
                min(selected(:, 2)) + vacuum;
            axisLength = norm(supercell.lattice.matrix(3, :));
            selected(:, 3) = mod(selected(:, 3), axisLength);
            lattice = diag([
                max(selected(:, 1)) - min(selected(:, 1)) + 2 * vacuum, ...
                max(selected(:, 2)) - min(selected(:, 2)) + 2 * vacuum, ...
                axisLength
                ]);
            wire = BuilderUtils.fromCartesian( ...
                supercell, lattice, selected, indices, ...
                [false, false, true]);
            wire.properties.nanowire = struct( ...
                "direction", direction, "radius", radius, ...
                "length", lengthValue);
        end
    end
end
