classdef SolventLayerBuilder
    %SOLVENTLAYERBUILDER Pack an explicit molecular layer above a slab.

    methods (Static)
        function output = build(host, solvent, moleculeCount, options)
            arguments
                host
                solvent
                moleculeCount (1,1) double
                options.layerThickness (1,1) double = 10
                options.clearance (1,1) double = 2
                options.vacuum (1,1) double = 5
                options.tolerance (1,1) double = 2
                options.seed (1,1) double = 1
                options.timeout (1,1) double = 60
                options.executor = []
            end
            import kssolv.modeling.builders.BuilderUtils
            BuilderUtils.requireStructure(host);
            moleculeCount = BuilderUtils.positiveInteger( ...
                moleculeCount, "Solvent molecule count");
            thickness = BuilderUtils.positiveScalar( ...
                options.layerThickness, "Solvent layer thickness");
            clearance = BuilderUtils.positiveScalar( ...
                options.clearance, "Surface clearance");
            vacuum = BuilderUtils.positiveScalar( ...
                options.vacuum, "Vacuum thickness");
            tolerance = BuilderUtils.positiveScalar( ...
                options.tolerance, "Packmol tolerance");
            timeout = BuilderUtils.positiveScalar( ...
                options.timeout, "Packmol timeout");
            if options.seed ~= fix(options.seed) || ~isfinite(options.seed)
                error("KSSOLV:Modeling:PackmolSeed", ...
                    "Packmol seed must be a finite integer.");
            end
            solventMolecule = ...
                kssolv.modeling.builders.SolventLayerBuilder. ...
                asMolecule(solvent);
            executor = options.executor;
            if isempty(executor)
                executor = @kssolv.analysis.packmol.native_executor;
            end
            if ~isa(executor, "function_handle")
                error("KSSOLV:Modeling:PackmolExecutorType", ...
                    "Packmol executor must be a MATLAB function handle.");
            end

            [frame, localHost, box, latticeMatrix] = ...
                kssolv.modeling.builders.SolventLayerBuilder. ...
                packingFrame(host, thickness, clearance, vacuum);
            hostMolecule = ...
                kssolv.analysis.matgenlab.core.Molecule( ...
                host.species_and_occu, localHost);
            descriptors = { ...
                struct("name", "surface", "number", 1, ...
                    "coords", hostMolecule, ...
                    "constraints", {{"fixed 0 0 0 0 0 0"}}), ...
                struct("name", "solvent", "number", moleculeCount, ...
                    "coords", solventMolecule, ...
                    "constraints", {{"inside box " + ...
                    join(string(box), " ")}})};
            generator = ...
                kssolv.analysis.matgenlab.io.packmol.PackmolBoxGen( ...
                tolerance = tolerance, seed = options.seed, ...
                executor = executor);
            inputSet = generator.get_input_set(descriptors);
            folder = string(tempname);
            [success, message] = mkdir(folder);
            if ~success
                error("KSSOLV:Modeling:PackmolTemporaryDirectory", ...
                    "Unable to create Packmol directory: %s", message);
            end
            cleanup = onCleanup(@() ...
                kssolv.modeling.builders.SolventLayerBuilder. ...
                removeTemporaryFolder(folder));
            inputSet.write_input(folder);
            inputSet.run(folder, timeout, executor);
            outputPath = fullfile(folder, inputSet.outputfile);
            if ~isfile(outputPath)
                error("KSSOLV:Modeling:PackmolOutput", ...
                    "Packmol did not create '%s'.", inputSet.outputfile);
            end
            packed = ...
                kssolv.analysis.matgenlab.core.Molecule. ...
                from_file(outputPath);
            expected = host.num_sites + ...
                moleculeCount * solventMolecule.num_sites;
            if packed.num_sites ~= expected
                error("KSSOLV:Modeling:PackmolOutputCount", ...
                    "Packmol returned %d atoms; expected %d.", ...
                    packed.num_sites, expected);
            end
            solventCoordinates = ...
                packed.cart_coords(host.num_sites + 1:end, :) * frame;
            solventSpecies = ...
                packed.species_and_occu(host.num_sites + 1:end);
            solventCount = size(solventCoordinates, 1);
            hostCoordinates = localHost * frame;
            properties = BuilderUtils.combineProperties( ...
                host.site_properties, struct(), ...
                host.num_sites, solventCount);
            properties.modeling_origin = [
                repmat({"surface"}, 1, host.num_sites), ...
                repmat({"solvent"}, 1, solventCount)];
            moleculeIds = repelem(1:moleculeCount, ...
                solventMolecule.num_sites);
            properties.solvent_molecule = [
                repmat({[]}, 1, host.num_sites), num2cell(moleculeIds)];
            output = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice( ...
                latticeMatrix, [true, true, false]), ...
                [host.species_and_occu, solventSpecies], ...
                [hostCoordinates; solventCoordinates], ...
                coords_are_cartesian = true, ...
                site_properties = properties, ...
                labels = [host.labels, ...
                    packed.labels(host.num_sites + 1:end)], ...
                properties = host.structure_properties, ...
                skip_checks = true);
            output.properties.solvent_layer = struct( ...
                "method", "native MATLAB Packmol", ...
                "molecule_count", moleculeCount, ...
                "layer_thickness", thickness, ...
                "clearance", clearance, "tolerance", tolerance, ...
                "seed", options.seed);
            clear cleanup
        end
    end

    methods (Static, Access = private)
        function molecule = asMolecule(value)
            if isa(value, ...
                    "kssolv.analysis.matgenlab.core.IMolecule")
                molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                    value.species_and_occu, value.cart_coords, ...
                    site_properties = value.site_properties, ...
                    labels = value.labels, ...
                    properties = value.properties);
            elseif isa(value, ...
                    "kssolv.analysis.matgenlab.core.IStructure")
                molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                    value.species_and_occu, value.cart_coords, ...
                    site_properties = value.site_properties, ...
                    labels = value.labels, ...
                    properties = value.structure_properties);
            else
                error("KSSOLV:Modeling:SolventModel", ...
                    "Solvent must be a matgenlab molecule or structure.");
            end
            molecule = molecule.get_centered_molecule();
        end

        function [frame, local, box, latticeMatrix] = ...
                packingFrame(host, thickness, clearance, vacuum)
            first = host.lattice.matrix(1, :);
            secondVector = host.lattice.matrix(2, :);
            normal = cross(first, secondVector);
            if norm(normal) <= 1e-12
                error("KSSOLV:Modeling:SolventLayerNormal", ...
                    "The first two lattice vectors do not define a surface.");
            end
            normal = normal / norm(normal);
            firstUnit = first / norm(first);
            secondUnit = cross(normal, firstUnit);
            frame = [firstUnit; secondUnit; normal];
            local = host.cart_coords * frame.';
            a = norm(first);
            b = secondVector * frame.';
            if b(2) <= 1e-10
                error("KSSOLV:Modeling:SolventLayerCell", ...
                    "The in-plane cell has no usable packing area.");
            end
            xLower = max(0, b(1));
            xUpper = min(a, a + b(1));
            if xUpper - xLower <= 2 * optionsTolerance()
                error("KSSOLV:Modeling:SolventLayerCell", ...
                    "The oblique in-plane cell has no sufficiently large " + ...
                    "inscribed Packmol box.");
            end
            minimumZ = min(local(:, 3));
            shift = vacuum / 2 - minimumZ;
            local(:, 3) = local(:, 3) + shift;
            surfaceTop = max(local(:, 3));
            box = [xLower, 0, surfaceTop + clearance, ...
                xUpper, b(2), surfaceTop + clearance + thickness];
            cellHeight = (max(local(:, 3)) - min(local(:, 3))) + ...
                vacuum + clearance + thickness;
            latticeMatrix = [first; secondVector; normal * cellHeight];
        end

        function removeTemporaryFolder(folder)
            if isfolder(folder)
                rmdir(folder, "s");
            end
        end
    end
end

function value = optionsTolerance()
value = 1e-6;
end
