function buildInstaller(runtimeDelivery)
%BUILDINSTALLER 编译 KSSOLV Toolbox 为独立应用程序，并生成安装包

% 开发者：杨柳
% 版权 2025-2026 合肥瀚海量子科技有限公司

arguments
    runtimeDelivery {mustBeMember(runtimeDelivery, ["web", "installer", "none"])} = "web"
end

% 编译仅支持使用公开 OpenAI-compatible API 的 4.9.0 及以上版本。
if ~kssolv.services.llm.isLLMWithMATLABAddonAvailable
    error('KSSOLV:Deployment:UnsupportedLLMAddon', ...
        'Before compiling, install and enable %s version %s or later.', ...
        kssolv.services.llm.Addon.Name, ...
        kssolv.services.llm.Addon.MinimumVersion);
end

% 设定代码依赖自动推断无法正确判断的、必须要包含的文件夹
toolboxFolder = fileparts(mfilename('fullpath'));
[dialogFrameworkFiles, dialogFrameworkCleanup] = stageDialogFrameworkFiles(toolboxFolder);
additionalFiles = [dialogFrameworkFiles(:).', ...
    string(fullfile(toolboxFolder, "ks.ks")), ...
    string(fullfile(toolboxFolder, "+kssolv", "+ui")), ...
    string(fullfile(toolboxFolder, "+kssolv", "+settings")), ...
    string(fullfile(toolboxFolder, "+kssolv", "+services")), ...
    string(fullfile(toolboxFolder, "+kssolv", "+analysis", "+seekpath", "+data")), ...
    getMatgenlabRuntimeData(), ...
    getKssolvRuntimeFiles()];

% 包含第三方 Add-Ons
addOnRuntimeFiles = getRequiredLLMAddonRuntimeFiles();
additionalFiles = [additionalFiles addOnRuntimeFiles];

% 设置编译属性
buildOptions = compiler.build.StandaloneApplicationOptions(fullfile(toolboxFolder, "kssolvStart.m"));
buildOptions.AdditionalFiles = additionalFiles;
buildOptions.AutoDetectDataFiles = true;
buildOptions.OutputDir = fullfile(toolboxFolder, 'Release', 'StandaloneDesktopApp', 'build');
buildOptions.ObfuscateArchive = false;
buildOptions.Verbose = true;
buildOptions.EmbedArchive = true;
buildOptions.ExecutableIcon = fullfile(KSSOLV_Toolbox.UIResourcesDirectory, "icons", "companyLOGO.png");
buildOptions.ExecutableName = "KSSOLV_Toolbox";
buildOptions.ExecutableVersion = KSSOLV_Toolbox.Version;
buildOptions.TreatInputsAsNumeric = false;

% 编译独立应用程序
if ispc
    buildOptions.ExecutableSplashScreen = fullfile(KSSOLV_Toolbox.UIResourcesDirectory, "icons", "companyLOGO.png");
    buildResult = compiler.build.standaloneWindowsApplication(buildOptions);
else
    buildResult = compiler.build.standaloneApplication(buildOptions);
end

% 下载 MATLAB Runtime
compiler.runtime.download;

% 设置打包属性
packageOptions = compiler.package.InstallerOptions(buildResult);
packageOptions.ApplicationName = KSSOLV_Toolbox.Name;
packageOptions.AuthorName = KSSOLV_Toolbox.Author;
packageOptions.AuthorEmail = KSSOLV_Toolbox.AuthorEmail;
packageOptions.AuthorCompany = KSSOLV_Toolbox.AuthorCompany;
packageOptions.Description = KSSOLV_Toolbox.Description;
packageOptions.Summary = KSSOLV_Toolbox.Summary;

packageOptions.Verbose = true;
packageOptions.Version = KSSOLV_Toolbox.Version;
packageOptions.RuntimeDelivery = runtimeDelivery;
packageOptions.OutputDir = fullfile(toolboxFolder, 'Release', 'StandaloneDesktopApp');
packageOptions.InstallerIcon = fullfile(KSSOLV_Toolbox.UIResourcesDirectory, "icons", "companyLOGO.png");
packageOptions.InstallerSplash = fullfile(KSSOLV_Toolbox.UIResourcesDirectory, "icons", "companyLOGO.png");
packageOptions.InstallerName = sprintf('KSSOLV_Toolbox_V%s', KSSOLV_Toolbox.Version);

% 删除旧的安装包
filesToDelete = dir(fullfile(packageOptions.OutputDir, [packageOptions.InstallerName, '.*']));
for k = 1:length(filesToDelete)
    fullFilePath = fullfile(filesToDelete(k).folder, filesToDelete(k).name);
    try
        if filesToDelete(k).isdir
            rmdir(fullFilePath, 's');
        else
            delete(fullFilePath);
        end
    catch ME
    end
end

% 生成独立应用程序安装包
compiler.package.installer(buildResult, "Options", packageOptions);
delete(dialogFrameworkCleanup)
end

function runtimeFiles = getRequiredLLMAddonRuntimeFiles()
installedAddOns = matlab.internal.addons.registry.getInstalledAddOnsMetadata;
addOnIndex = strcmp(string({installedAddOns.name}), ...
    kssolv.services.llm.Addon.Name);
if isfield(installedAddOns, 'version')
    supportedVersion = arrayfun(@(addon) ...
        kssolv.services.llm.Addon.isVersionSupported( ...
        string(addon.version)), installedAddOns);
    supportedVersion = reshape(supportedVersion, size(addOnIndex));
    addOnIndex = addOnIndex & supportedVersion;
end
if ~any(addOnIndex)
    error('KSSOLV:Deployment:LLMAddonFilesNotFound', ...
        'Unable to locate the supported LLM Add-On files for packaging.');
end

addOn = installedAddOns(find(addOnIndex, 1, 'last'));
runtimeFiles = getAddOnRuntimeFiles(string(addOn.registrationRoot));
end

function [runtimeFiles, cleanup] = stageDialogFrameworkFiles(toolboxFolder)
% 编译器无法推断仅作为父类使用的 controllib 包类，也会过滤直接加入的 MATLAB 自带源码。
% 因此先按原包层级暂存未修改的原生对话框框架，再将其加入运行时资源。
sourceDirectory = fullfile(matlabroot, "toolbox", "shared", ...
    "controllib", "graphics", "+controllib", "+ui", "+internal", ...
    "+dialog");
if ~isfolder(sourceDirectory)
    error('KSSOLV:Deployment:DialogFrameworkNotFound', ...
        'Unable to locate the MATLAB dialog framework: %s', ...
        sourceDirectory);
end

stagingRoot = fullfile(toolboxFolder, "+controllib");
if isfolder(stagingRoot)
    error('KSSOLV:Deployment:DialogFrameworkStageConflict', ...
        'The dialog framework staging directory already exists: %s', ...
        stagingRoot);
end
destinationDirectory = fullfile(stagingRoot, "+ui", ...
    "+internal", "+dialog");
[created, detail] = mkdir(fileparts(destinationDirectory));
if ~created
    error('KSSOLV:Deployment:DialogFrameworkStageFailed', ...
        'Unable to create the dialog framework staging directory: %s', ...
        detail);
end
[copied, detail] = copyfile(sourceDirectory, destinationDirectory);
if ~copied
    rmdir(stagingRoot, 's');
    error('KSSOLV:Deployment:DialogFrameworkStageFailed', ...
        'Unable to stage the dialog framework: %s', detail);
end

runtimeFiles = string(stagingRoot);
cleanup = onCleanup(@() removeStagingDirectory(stagingRoot));
end

function removeStagingDirectory(stagingRoot)
% 删除编译期间创建的对话框框架暂存目录。
if isfolder(stagingRoot)
    rmdir(stagingRoot, 's');
end
end

function runtimeFiles = getKssolvRuntimeFiles()
% 包含动态恢复的 KSSOLV 类、示例和赝势数据，同时排除测试代码。
kssolvHome = fullfile(fileparts(mfilename("fullpath")), ...
    "+kssolv", "+core", "kssolv-3o");
sourceDirectory = string(fullfile(kssolvHome, "src"));
entries = dir(fullfile(sourceDirectory, "**", "*.m"));
runtimeFiles = string(fullfile({entries.folder}, {entries.name}));
relativeFiles = extractAfter(runtimeFiles, sourceDirectory + filesep);
isTest = startsWith(relativeFiles, ...
    fullfile("+geometryoptimization", "test") + filesep) | ...
    startsWith(relativeFiles, ...
    fullfile("quantum_simulator", "+kssolv", ...
    "+simulator", "+tests") + filesep);
runtimeFiles = [runtimeFiles(~isTest), ...
    string(fullfile(kssolvHome, ["+example", "ppdata"]))];
runtimeFiles = reshape(runtimeFiles, 1, []);
end

function runtimeFiles = getMatgenlabRuntimeData()
% 仅包含通过 mfilename 派生路径动态加载的资源。
toolboxFolder = fileparts(mfilename('fullpath'));
matgenlabHome = string(fullfile(toolboxFolder, ...
    "+kssolv", "+analysis", "+matgenlab"));
resourcePatterns = [ ...
    fullfile(matgenlabHome, "+core", "+data", "*.json"), ...
    fullfile(matgenlabHome, "+analysis", "+data", "*.json"), ...
    fullfile(matgenlabHome, "+analysis", "+data", "*.csv"), ...
    fullfile(matgenlabHome, "+analysis", "+compatibility", ...
    "data", "*.yaml"), ...
    fullfile(matgenlabHome, "+analysis", "+compatibility", ...
    "data", "*.json"), ...
    fullfile(matgenlabHome, "+analysis", "+chemenv", ...
    "+coordination_environments", ...
    "+coordination_geometries_files", "*.json"), ...
    fullfile(matgenlabHome, "+analysis", "+prototypes", ...
    "data", "*.json.gz"), ...
    fullfile(matgenlabHome, "+command_line", "+gulp_caller", ...
    "+data", "*.lib"), ...
    fullfile(matgenlabHome, "+io", "+lammps", ...
    "templates", "*.template"), ...
    fullfile(matgenlabHome, "+io", "+lobster", "+future", ...
    "lobster_basis", "*.yaml"), ...
    fullfile(matgenlabHome, "+io", "+vasp", ...
    "+sets_data", "*.json")];

runtimeFiles = strings(1, 0);
for pattern = resourcePatterns
    entries = dir(pattern);
    if isempty(entries)
        warning('KSSOLV:Deployment:OptionalMatgenlabRuntimeDataNotFound', ...
            'No optional Matgenlab runtime resources matched: %s', ...
            pattern);
        continue
    end
    runtimeFiles = [runtimeFiles, ...
        string(fullfile({entries.folder}, {entries.name}))]; %#ok<AGROW>
end

requiredFiles = [ ...
    fullfile(matgenlabHome, "+analysis", "+chemenv", ...
    "+coordination_environments", ...
    "+coordination_geometries_files", "allcg.txt"), ...
    fullfile(matgenlabHome, "+analysis", "+solar", "am1.5G.dat"), ...
    fullfile(matgenlabHome, "+command_line", "+gulp_caller", ...
    "+data", "OxideTersoffPotentials"), ...
    fullfile(matgenlabHome, "+io", "+vasp", "incar_parameters.json"), ...
    fullfile(matgenlabHome, "+io", "+vasp", ...
    "potcar-summary-stats.json.bz2"), ...
    fullfile(matgenlabHome, "+symmetry", "+maggroups", ...
    "magnetic_space_groups.mat"), ...
    fullfile(matgenlabHome, "+vis", "ElementColorSchemes.json")];
missingFiles = requiredFiles(~isfile(requiredFiles));
if ~isempty(missingFiles)
    error('KSSOLV:Deployment:MatgenlabRuntimeDataNotFound', ...
        'Required Matgenlab runtime resources were not found:\n%s', ...
        char(join(missingFiles, newline)));
end
runtimeFiles = reshape(unique([runtimeFiles, requiredFiles], "stable"), ...
    1, []);
end

function runtimeFiles = getAddOnRuntimeFiles(addOnPath)
% 收集 Add-On 运行文件，排除测试、示例、文档和仓库开发内容。
entries = dir(fullfile(addOnPath, "**", "*"));
entries = entries(~[entries.isdir]);
allFiles = string(fullfile({entries.folder}, {entries.name}));

excludedDirectories = fullfile(addOnPath, [ ...
    "tests", ...
    "examples", ...
    "doc", ...
    ".git", ...
    ".github", ...
    ".githooks"]);
excludedFiles = fullfile(addOnPath, [ ...
    ".gitattributes", ...
    ".gitignore", ...
    "CONTRIBUTING.md", ...
    "DEVELOPMENT.md", ...
    "SECURITY.md"]);

isExcluded = ismember(allFiles, excludedFiles);
for directory = excludedDirectories
    isExcluded = isExcluded | ...
        startsWith(allFiles, directory + string(filesep));
end
runtimeFiles = allFiles(~isExcluded);
runtimeFiles = reshape(runtimeFiles, 1, []);

if isempty(runtimeFiles)
    error('KSSOLV:Deployment:LLMAddonFilesNotFound', ...
        'No deployable LLM Add-On files were found in: %s', addOnPath);
end
end
