classdef WorkflowSnapshotBuilder
    %WORKFLOWSNAPSHOTBUILDER Freeze a workflow into transferable data.

    properties (Constant)
        FormatVersion = 1
    end

    methods (Static)
        function snapshot = build(workflow, workflowName, projectIdentity)
            arguments
                workflow kssolv.services.workflow.WorkflowGraph
                workflowName (1, 1) string = "Default"
                projectIdentity (1, 1) string = ""
            end
            sortedNodeIds = ...
                kssolv.services.workflow.codegeneration.CodeGenerator. ...
                topologicalSort(workflow);
            emptyTask = struct("NodeId", "", "ClassName", "", ...
                "Identifier", "", "Options", struct());
            remoteTasks = repmat(emptyTask, 0, 1);
            localNodeIds = strings(0, 1);
            remoteNodeIds = strings(0, 1);
            unsupportedTasks = strings(0, 1);

            for index = 1:numel(sortedNodeIds)
                nodeId = string(sortedNodeIds{index});
                node = workflow.Nodes(char(nodeId));
                task = node.task;
                if kssolv.services.remote.execution.ExecutionTaskRegistry. ...
                        supports(task)
                    parents = string(workflow.getParents(char(nodeId)));
                    if any(ismember(parents, localNodeIds))
                        error("KSSOLV:Remote:LocalToRemoteDependency", ...
                            "Remote task %s depends on a local-only task. " + ...
                            "Reorder or split the workflow.", nodeId);
                    end
                    remoteTasks(end + 1, 1) = struct( ...
                        "NodeId", nodeId, ...
                        "ClassName", string(class(task)), ...
                        "Identifier", string(task.IDENTIFIER), ...
                        "Options", task.getExecutionOptions()); %#ok<AGROW>
                    remoteNodeIds(end + 1, 1) = nodeId; %#ok<AGROW>
                    if kssolv.services.remote.execution.ExecutionTaskRegistry. ...
                            requiresLocalPresentation(task)
                        localNodeIds(end + 1, 1) = nodeId; %#ok<AGROW>
                    end
                else
                    if task.module ~= ...
                            kssolv.services.workflow.module.ModuleType.Visualization
                        unsupportedTasks(end + 1, 1) = nodeId + ...
                            " (" + string(class(task)) + ")"; %#ok<AGROW>
                    end
                    localNodeIds(end + 1, 1) = nodeId; %#ok<AGROW>
                end
            end
            if ~isempty(unsupportedTasks)
                error("KSSOLV:Remote:UnsupportedWorkflowTask", ...
                    "The following tasks cannot execute remotely: %s", ...
                    strjoin(unsupportedTasks, ", "));
            end
            snapshot = struct( ...
                "Version", kssolv.services.remote.execution. ...
                    WorkflowSnapshotBuilder.FormatVersion, ...
                "WorkflowName", workflowName, ...
                "ProjectIdentity", projectIdentity, ...
                "ToolboxVersion", string(KSSOLV_Toolbox.Version), ...
                "MatlabRelease", string(version("-release")), ...
                "CreatedAt", string(datetime("now", "TimeZone", "UTC", ...
                    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")), ...
                "RemoteTasks", remoteTasks, ...
                "RemoteNodeIds", remoteNodeIds, ...
                "LocalNodeIds", unique(localNodeIds, "stable"));
            kssolv.services.remote.execution.WorkflowSnapshotBuilder.validate(snapshot);
        end

        function validate(snapshot)
            required = ["Version", "WorkflowName", "ProjectIdentity", ...
                "ToolboxVersion", "MatlabRelease", "CreatedAt", ...
                "RemoteTasks", "RemoteNodeIds", "LocalNodeIds"];
            if ~isstruct(snapshot) || ~isscalar(snapshot) || ...
                    ~all(isfield(snapshot, required)) || ...
                    double(snapshot.Version) ~= ...
                    kssolv.services.remote.execution.WorkflowSnapshotBuilder.FormatVersion
                error("KSSOLV:Remote:InvalidWorkflowSnapshot", ...
                    "The remote workflow snapshot is invalid.");
            end
            for index = 1:numel(snapshot.RemoteTasks)
                task = snapshot.RemoteTasks(index);
                if ~all(isfield(task, ...
                        ["NodeId", "ClassName", "Identifier", "Options"]))
                    error("KSSOLV:Remote:InvalidWorkflowTaskSnapshot", ...
                        "A remote workflow task snapshot is invalid.");
                end
                if ~any(string(task.ClassName) == ...
                        kssolv.services.remote.execution.ExecutionTaskRegistry. ...
                        headlessTaskClasses())
                    error("KSSOLV:Remote:UnsupportedHeadlessTask", ...
                        "Task class %s is not registered for remote use.", ...
                        task.ClassName);
                end
            end
        end
    end
end
