classdef GruneisenTest < matlab.unittest.TestCase
    methods (Test)
        function parameterNumericsMatchFrozenOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.phonon.GruneisenParameter
            qpoints=[0,0,0;0.5,0,0];
            frequencies=[1,2;3,4];
            gruneisen=[1,2;3,4];
            multiplicities=[2,3];
            structure=Structure(Lattice.cubic(4),{"Si"},[0,0,0]);
            actual=GruneisenParameter( ...
                qpoints,gruneisen,frequencies, ...
                multiplicities,structure,[]);
            ndarray=@(value)struct("matgenlab_ndarray",value);
            request=struct( ...
                "module","pymatgen.phonon.gruneisen", ...
                "symbol","GruneisenParameter", ...
                "construct",struct("args",{{ ...
                    ndarray(qpoints),ndarray(gruneisen), ...
                    ndarray(frequencies),ndarray(multiplicities), ...
                    structure.as_dict()}}), ...
                "operations",{{ ...
                    struct("kind","call","name","average_gruneisen", ...
                        "args",{{300}}), ...
                    struct("kind","call","name","average_gruneisen", ...
                        "args",{{300,false}}), ...
                    struct("kind","call","name","average_gruneisen", ...
                        "args",{{300,true,"acoustic"}}), ...
                    struct("kind","get","name","debye_temp_limit"), ...
                    struct("kind","get","name","acoustic_debye_temp"), ...
                    struct("kind","call", ...
                        "name","thermal_conductivity_slack", ...
                        "kwargs",struct("theta_d",300)), ...
                    struct("kind","call", ...
                        "name","thermal_conductivity_slack", ...
                        "kwargs",struct("theta_d",300,"t",500)), ...
                    struct("kind","get","name","phdos"), ...
                    struct("kind","call","name","as_dict")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            testCase.verifyEqual(actual.average_gruneisen(300), ...
                reference.results{1},AbsTol=2e-14);
            testCase.verifyEqual(actual.average_gruneisen(300,false), ...
                reference.results{2},AbsTol=2e-14);
            testCase.verifyEqual(actual.average_gruneisen( ...
                300,true,"acoustic"),reference.results{3},AbsTol=2e-14);
            testCase.verifyEqual(actual.debye_temp_limit, ...
                reference.results{4},AbsTol=3e-12);
            testCase.verifyEqual(actual.acoustic_debye_temp, ...
                reference.results{5},AbsTol=3e-12);
            testCase.verifyEqual(actual.thermal_conductivity_slack( ...
                true,[],300),reference.results{6},AbsTol=2e-13);
            testCase.verifyEqual(actual.thermal_conductivity_slack( ...
                true,[],300,500),reference.results{7},AbsTol=2e-13);
            phononDos=actual.phdos;
            expectedDos=reference.results{8};
            testCase.verifyEqual(phononDos.frequencies, ...
                expectedDos.frequencies,AbsTol=2e-14);
            testCase.verifyEqual(phononDos.densities, ...
                expectedDos.densities,AbsTol=5e-13);
            testCase.verifyEqual(actual.tdos.dos(:),phononDos.densities(:));
            testCase.verifyGreaterThan(actual.debye_temp_phonopy(),0);
            restored=GruneisenParameter.from_dict(actual.as_dict());
            testCase.verifyEqual(restored.gruneisen,actual.gruneisen);
            testCase.verifyEqual(restored.structure.formula, ...
                actual.structure.formula);
            wire=reference.results{9};
            testCase.verifyEqual(actual.as_dict().x_class,string(wire.x_class));
        end

        function bandStructuresRoundTripAndLineMetadata(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.phonon.GruneisenPhononBandStructure
            import kssolv.analysis.matgenlab.phonon.GruneisenPhononBandStructureSymmLine
            qpoints=[0,0,0;0.5,0,0];
            frequencies=[1,2;3,4];
            gruneisen=[0.1,0.2;0.3,0.4];
            lattice=Lattice.cubic(1);
            bands=GruneisenPhononBandStructure( ...
                qpoints,frequencies,gruneisen,lattice);
            restored=GruneisenPhononBandStructure. ...
                from_dict(bands.as_dict());
            testCase.verifyEqual(restored.bands,frequencies);
            testCase.verifyEqual(restored.gruneisen,gruneisen);
            labels=containers.Map( ...
                {'G','X'},{[0,0,0],[0.5,0,0]});
            line=GruneisenPhononBandStructureSymmLine( ...
                qpoints,frequencies,gruneisen,lattice,[],labels);
            testCase.verifyEqual(line.distance,[0,0]);
            testCase.verifyEqual(numel(line.branches),2);
            testCase.verifyEqual(line.branches{1}.start_index,1);
            testCase.verifyEqual(line.branches{2}.end_index,2);
            restoredLine=GruneisenPhononBandStructureSymmLine. ...
                from_dict(line.as_dict());
            testCase.verifyEqual(restoredLine.gruneisen,gruneisen);
            testCase.verifyEqual(restoredLine.distance,line.distance);
            testCase.verifyEqual( ...
                restoredLine.as_dict().x_class, ...
                "GruneisenPhononBandStructureSymmLine");
        end
    end
end
