classdef PhononDosTest < matlab.unittest.TestCase
    methods (Test)
        function thermodynamicsMatchFrozenOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            frequencies=linspace(-0.2,12,401);
            densities=3*exp(-((frequencies-4)/1.3).^2)+ ...
                2*exp(-((frequencies-8)/1.8).^2);
            dos=kssolv.analysis.matgenlab.phonon. ...
                PhononDos(frequencies,densities);
            request=struct( ...
                "module","pymatgen.phonon.dos", ...
                "symbol","PhononDos", ...
                "construct",struct("args",{{frequencies,densities}}), ...
                "operations",{{ ...
                struct("kind","call","name","get_smeared_densities", ...
                    "args",{{0.08}}), ...
                struct("kind","call","name","get_interpolated_value", ...
                    "args",{{3.14159}}), ...
                struct("kind","get","name","ind_zero_freq"), ...
                struct("kind","call","name","cv","args",{{300}}), ...
                struct("kind","call","name","entropy","args",{{300}}), ...
                struct("kind","call","name","internal_energy", ...
                    "args",{{300}}), ...
                struct("kind","call","name","helmholtz_free_energy", ...
                    "args",{{300}}), ...
                struct("kind","call","name","zero_point_energy"), ...
                struct("kind","call","name","get_last_peak")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            testCase.verifyEqual(dos.get_smeared_densities(0.08), ...
                reference.results{1},AbsTol=2e-13);
            testCase.verifyEqual(dos.get_interpolated_value(3.14159), ...
                reference.results{2},AbsTol=2e-14);
            testCase.verifyEqual(dos.ind_zero_freq, ...
                reference.results{3}+1);
            testCase.verifyEqual(dos.cv(300), ...
                reference.results{4},RelTol=2e-14);
            testCase.verifyEqual(dos.entropy(300), ...
                reference.results{5},RelTol=2e-14);
            testCase.verifyEqual(dos.internal_energy(300), ...
                reference.results{6},RelTol=2e-14);
            testCase.verifyEqual(dos.helmholtz_free_energy(300), ...
                reference.results{7},RelTol=2e-14);
            testCase.verifyEqual(dos.zero_point_energy(), ...
                reference.results{8},RelTol=2e-14);
            testCase.verifyEqual(dos.get_last_peak(), ...
                reference.results{9},AbsTol=0.04);
        end

        function fingerprintAndMetrics(testCase)
            frequencies=linspace(-1,10,300);
            first=kssolv.analysis.matgenlab.phonon.PhononDos( ...
                frequencies,exp(-(frequencies-4).^2));
            second=kssolv.analysis.matgenlab.phonon.PhononDos( ...
                frequencies,exp(-(frequencies-4.2).^2));
            fp1=first.get_dos_fp(true,0,10,64,true);
            fp2=second.get_dos_fp(true,0,10,64,true);
            similarity=kssolv.analysis.matgenlab.phonon. ...
                PhononDos.get_dos_fp_similarity(fp1,fp2);
            testCase.verifyGreaterThan(similarity,0.9);
            testCase.verifyLessThan(similarity,1);
            testCase.verifyEqual(first.mae(first),0);
            testCase.verifyEqual(first.r2_score(first),1);
            testCase.verifyEqual(first+second,second+first);
            dictionary=kssolv.analysis.matgenlab.phonon. ...
                PhononDos.fp_to_dict(fp1);
            testCase.verifyTrue(isfield(dictionary,"n64"));
            testCase.verifyEqual(size(dictionary.n64),[64,2]);
            restored=kssolv.analysis.matgenlab.phonon. ...
                PhononDos.from_dict(first.as_dict());
            testCase.verifyTrue(restored==first);
        end

        function completeDosProjectionRoundTrip(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.phonon.*
            structure=Structure(Lattice.cubic(4), ...
                {"Na","Cl"},[0,0,0;0.5,0.5,0.5]);
            frequencies=(0.1:0.1:1).';
            total=PhononDos(frequencies,3*ones(10,1));
            complete=CompletePhononDos( ...
                structure,total,{ones(10,1),2*ones(10,1)});
            testCase.verifyEqual(complete.get_site_dos(2).densities, ...
                2*ones(10,1));
            elements=complete.get_element_dos();
            testCase.verifyEqual(elements("Na").densities,ones(10,1));
            restored=CompletePhononDos.from_dict(complete.as_dict());
            testCase.verifyEqual(restored.pdos,complete.pdos);
            testCase.verifyTrue(restored.structure==structure);
        end
    end
end
