classdef PhononBandStructureTest < matlab.unittest.TestCase
    methods (Test)
        function helpersAndBaseOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.phonon.*
            testCase.verifyEqual(get_reasonable_repetitions(3),[3,3,3]);
            testCase.verifyEqual(get_reasonable_repetitions(20),[2,2,1]);
            displacements=reshape(1:18,3,2,3);
            testCase.verifyEqual( ...
                eigenvectors_from_displacements(displacements,[1,4]), ...
                displacements.*reshape([1,2],1,2,1));
            testCase.verifyEqual(estimate_band_connection( ...
                eye(3),eye(3),[1,2,3]),[1,2,3]);

            lattice=Lattice(2*pi*eye(3));
            qpoints=[0,0,0;0.25,0,0;0.5,0,0];
            bands=[-0.02,0.1,0.2;0,0.5,0.7;1,1.2,1.5];
            object=PhononBandStructure(qpoints,bands,lattice);
            request=struct( ...
                "module","pymatgen.phonon.bandstructure", ...
                "symbol","PhononBandStructure", ...
                "construct",struct("args",{{ ...
                qpoints,bands,lattice.as_dict()}}), ...
                "operations",{{ ...
                struct("kind","call","name","get_gamma_point"), ...
                struct("kind","call","name","min_freq"), ...
                struct("kind","call","name","max_freq"), ...
                struct("kind","call","name","width"), ...
                struct("kind","call","name","width","args",{{true}}), ...
                struct("kind","call","name","has_imaginary_freq"), ...
                struct("kind","call","name", ...
                    "has_imaginary_gamma_freq"), ...
                struct("kind","get","name","has_nac"), ...
                struct("kind","get","name","has_eigendisplacements"), ...
                struct("kind","call","name","asr_breaking")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            gamma=object.get_gamma_point();
            testCase.verifyEqual(gamma.frac_coords, ...
                reshape(reference.results{1}.fcoords,1,3));
            [minimumPoint,minimum]=object.min_freq();
            testCase.verifyEqual(minimumPoint.frac_coords, ...
                reshape(reference.results{2}{1}.fcoords,1,3));
            testCase.verifyEqual(minimum,reference.results{2}{2});
            [maximumPoint,maximum]=object.max_freq();
            testCase.verifyEqual(maximumPoint.frac_coords, ...
                reshape(reference.results{3}{1}.fcoords,1,3));
            testCase.verifyEqual(maximum,reference.results{3}{2});
            testCase.verifyEqual(object.width(),reference.results{4});
            testCase.verifyEqual(object.width(true),reference.results{5});
            testCase.verifyEqual(object.has_imaginary_freq(), ...
                reference.results{6});
            testCase.verifyEqual(object.has_imaginary_gamma_freq(), ...
                reference.results{7});
            testCase.verifyEqual(object.has_nac,reference.results{8});
            testCase.verifyEqual(object.has_eigendisplacements, ...
                reference.results{9});
            testCase.verifyEqual(object.asr_breaking(), ...
                reference.results{10});
        end

        function nacAndSymmetryLineRoundTrip(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.phonon.*
            lattice=Lattice(2*pi*eye(3));
            qpoints=[0,0,0;0.25,0,0;0.5,0,0; ...
                0.5,0,0;0.5,0.25,0;0.5,0.5,0];
            bands=repmat((1:3)',1,6);
            labels=struct("G",[0,0,0],"X",[0.5,0,0], ...
                "M",[0.5,0.5,0]);
            line=PhononBandStructureSymmLine( ...
                qpoints,bands,lattice,false,[],labels);
            testCase.verifyEqual(numel(line.branches),2);
            testCase.verifyEqual(line.get_equivalent_qpoints(3),[3,4]);
            restored=PhononBandStructureSymmLine.from_dict( ...
                line.as_dict());
            testCase.verifyTrue(restored==line);

            generic=PhononBandStructure( ...
                qpoints,bands,lattice,{[1,0,0],(4:6)'}, ...
                [],{[1,0,0],ones(3,1)},labels);
            testCase.verifyTrue(generic.has_nac);
            testCase.verifyEqual( ...
                generic.get_nac_frequencies_along_dir([2,0,0]), ...
                (4:6)');
            testCase.verifyEqual( ...
                generic.get_nac_eigendisplacements_along_dir([2,0,0]), ...
                ones(3,1));
            roundTrip=PhononBandStructure.from_dict(generic.as_dict());
            testCase.verifyEqual( ...
                roundTrip.get_nac_frequencies_along_dir([1,0,0]), ...
                (4:6)');
        end

        function websiteBranchesAndBandReorder(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.phonon.*
            lattice=Lattice(2*pi*eye(3));
            qpoints=[0,0,0;0.25,0,0;0.5,0,0; ...
                0.5,0,0;0.5,0.25,0;0.5,0.5,0];
            bands=repmat((1:3)',1,6);
            labels=struct("G",[0,0,0],"X",[0.5,0,0], ...
                "M",[0.5,0.5,0]);
            structure=Structure(Lattice.cubic(4),{"Si"},[0,0,0]);
            eigen=zeros(3,6,1,3);
            for point=1:6
                eigen(:,point,1,:)=reshape(eye(3),3,1,1,3);
            end
            line=PhononBandStructureSymmLine( ...
                qpoints,bands,lattice,false,eigen,labels,false,structure);

            branch=line.get_branch(3);
            testCase.verifyEqual(numel(branch),2);
            testCase.verifyEqual([branch{1}.index,branch{2}.index],[3,4]);
            payload=line.as_phononwebsite();
            testCase.verifyEqual(payload.natoms,1);
            testCase.verifyEqual(size(payload.qpoints),[6,3]);
            testCase.verifyEqual(size(payload.eigenvalues),[6,3]);

            filename=string(tempname)+".json";
            cleanup=onCleanup(@()deleteIfPresent(filename));
            line.write_phononwebsite(filename);
            written=jsondecode(fileread(filename));
            testCase.verifyEqual(written.natoms,1);
            reordered=line.band_reorder();
            testCase.verifyEqual(reordered.bands,bands);
            clear cleanup
        end
    end
end

function deleteIfPresent(filename)
if isfile(filename),delete(filename);end
end
