classdef ThermalDisplacementMatricesTest < matlab.unittest.TestCase
    methods (Test)
        function tensorConversionsMatchFrozenOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.phonon.ThermalDisplacementMatrices
            structure=Structure(Lattice.from_parameters( ...
                4,5,6,80,95,105),{"Na","Cl"}, ...
                [0,0,0;0.3,0.4,0.5]);
            reduced=[0.01,0.02,0.03,0.001,0.002,0.003; ...
                0.04,0.05,0.06,0.004,0.005,0.006];
            object=ThermalDisplacementMatrices( ...
                reduced,structure,300);
            request=struct( ...
                "module","pymatgen.phonon.thermal_displacements", ...
                "symbol","ThermalDisplacementMatrices", ...
                "construct",struct("args",{{ ...
                    reduced,structure.as_dict(),300}}), ...
                "operations",{{ ...
                struct("kind","get","name","Ustar"), ...
                struct("kind","get","name","Ucif"), ...
                struct("kind","get","name","B"), ...
                struct("kind","get","name","beta"), ...
                struct("kind","get","name","U1U2U3"), ...
                struct("kind","get","name","ratio_prolate")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            testCase.verifyEqual(object.Ustar,reference.results{1}, ...
                AbsTol=2e-15);
            testCase.verifyEqual(object.Ucif,reference.results{2}, ...
                AbsTol=2e-15);
            testCase.verifyEqual(object.B,reference.results{3}, ...
                AbsTol=2e-13);
            for index=1:2
                testCase.verifyEqual(object.beta{index}, ...
                    squeeze(reference.results{4}(index,:,:)),AbsTol=2e-14);
            end
            expectedEigen=reference.results{5};
            for index=1:2
                testCase.verifyEqual(sort(object.U1U2U3{index}), ...
                    sort(expectedEigen(index,:).'),AbsTol=2e-14);
            end
            testCase.verifyEqual(object.ratio_prolate, ...
                reference.results{6},AbsTol=2e-13);
            testCase.verifyEqual( ...
                ThermalDisplacementMatrices.get_reduced_matrix( ...
                ThermalDisplacementMatrices.get_full_matrix(reduced)), ...
                reduced);
        end

        function ucifSitePropertiesAndDirectionality(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.phonon.ThermalDisplacementMatrices
            structure=Structure(Lattice.cubic(4),{"Na","Cl"}, ...
                [0,0,0;0.5,0.5,0.5]);
            cif=[0.01,0.02,0.03,0,0,0; ...
                0.04,0.05,0.06,0.001,0.002,0.003];
            first=ThermalDisplacementMatrices.from_Ucif( ...
                cif,structure,300);
            testCase.verifyEqual(first.Ucif, ...
                ThermalDisplacementMatrices.get_full_matrix(cif), ...
                AbsTol=2e-15);
            decorated=first.to_structure_with_site_properties_Ucif();
            restored=ThermalDisplacementMatrices. ...
                from_structure_with_site_properties_Ucif(decorated,300);
            testCase.verifyEqual(restored.Ucif,first.Ucif,AbsTol=2e-15);
            result=first.compute_directionality_quality_criterion(first);
            testCase.verifyEqual([result.angle],[0,0],AbsTol=1e-12);
            expectedRatio=cellfun(@(values)max(values)/min(values), ...
                first.U1U2U3);
            testCase.verifyEqual(first.ratio_prolate,expectedRatio);
            mson=ThermalDisplacementMatrices.from_dict(first.as_dict());
            testCase.verifyEqual(mson.Ucif,first.Ucif,AbsTol=2e-15);

            cifFile=string(tempname)+".cif";
            vestaFile=string(tempname)+".vesta";
            cleanup=onCleanup(@()deleteIfPresent(cifFile,vestaFile));
            first.write_cif(cifFile);
            reparsed=ThermalDisplacementMatrices.from_cif_P1(cifFile);
            testCase.verifyEqual(numel(reparsed),1);
            testCase.verifyEqual(reparsed{1}.Ucif,first.Ucif,AbsTol=1e-12);
            first.visualize_directionality_quality_criterion( ...
                first,vestaFile,0);
            testCase.verifyTrue(isfile(vestaFile));
            testCase.verifyTrue(contains(fileread(vestaFile),"VECTR"));
            clear cleanup
        end
    end
end

function deleteIfPresent(varargin)
for index=1:nargin
    if isfile(varargin{index}),delete(varargin{index});end
end
end
