classdef AnalysisResultPresenter
    %ANALYSISRESULTPRESENTER Show modeling analysis results graphically.

    methods (Static)
        function present(commandId, model, result, titleText, varargin)
            commandId = string(commandId);
            switch commandId
                case "find_adsorption_sites"
                    kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                        plotAdsorptionSites(model, result, titleText);
                case "locate_adsorbate"
                    kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                        showAdsorptionCandidates( ...
                        model, result, titleText, varargin{:});
                case "wigner_seitz_cell"
                    kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                        plotWignerSeitz( ...
                        model, result, titleText, varargin{:});
                case "build_from_spacegroup"
                    kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                        showCrystalBuilder(result, titleText);
                case "enumerate_point_defects"
                    kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                        showDefectCandidates(result, titleText);
                case "build_slab"
                    kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                        showSurfaceBuilder(result, titleText);
                case "stack_heterostructure"
                    kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                        showInterfaceCandidates(result, titleText);
                otherwise
                    if isempty(varargin)
                        msgbox(result.message, titleText, "help", "modal");
                    else
                        uialert(varargin{1}, result.message, titleText, ...
                            "Icon", "info");
                    end
            end
        end

        function [asymmetric, equivalent] = crystalBuilderTables(result)
            analysis = result.analysis;
            source = analysis.asymmetricSites;
            asymmetric = table( ...
                reshape(string({source.species}), [], 1), ...
                reshape([source.occupancy], [], 1), ...
                reshape([source.fractional], 3, []).', ...
                'VariableNames', {'Species', 'Occupancy', 'Fractional'});
            sites = analysis.equivalentSites;
            equivalent = table( ...
                reshape([sites.representative], [], 1), ...
                reshape(string({sites.species}), [], 1), ...
                reshape(string({sites.wyckoff}), [], 1), ...
                reshape([sites.multiplicity], [], 1), ...
                reshape(string({sites.siteSymmetry}), [], 1), ...
                reshape([sites.occupancy], [], 1), ...
                reshape([sites.fractional], 3, []).', ...
                'VariableNames', {'Representative', 'Species', 'Wyckoff', ...
                'Multiplicity', 'SiteSymmetry', 'Occupancy', 'Fractional'});
        end

        function candidates = defectCandidateTable(result)
            data = result.data;
            candidates = table( ...
                reshape(data.siteIndices, [], 1), ...
                reshape(data.degeneracies, [], 1), ...
                reshape(data.netCharges, [], 1), ...
                reshape(data.minimumContacts, [], 1), ...
                reshape(string(data.labels), [], 1), ...
                'VariableNames', {'Site', 'Degeneracy', 'NetCharge', ...
                'MinimumContact', 'Label'});
        end

        function candidates = surfaceTerminationTable(result)
            items = result.analysis.terminations;
            candidates = table( ...
                reshape([items.index], [], 1), ...
                reshape([items.shift], [], 1), ...
                reshape(string({items.formula}), [], 1), ...
                reshape([items.atomCount], [], 1), ...
                reshape([items.surfaceArea], [], 1), ...
                reshape([items.brokenBonds], [], 1), ...
                'VariableNames', {'Index', 'Shift', 'Formula', ...
                'AtomCount', 'SurfaceArea', 'BrokenBonds'});
        end

        function candidates = interfaceCandidateTable(result)
            items = result.analysis.candidates;
            bottom=arrayfun(@(item)string(mat2str( ...
                item.bottomTransform(1:2,1:2))),items).';
            top=arrayfun(@(item)string(mat2str( ...
                item.topTransform(1:2,1:2))),items).';
            candidates = table( ...
                reshape([items.index], [], 1), ...
                bottom, top, ...
                reshape([items.area], [], 1), ...
                reshape([items.strain], [], 1), ...
                reshape([items.rotationDegrees], [], 1), ...
                reshape([items.atomCount], [], 1), ...
                'VariableNames', {'Index', 'BottomRepeat', 'TopRepeat', ...
                'Area', 'Strain', 'RotationDegrees', 'AtomCount'});
        end

        function candidates = adsorptionCandidateTable(result)
            items = result.analysis.candidates;
            candidates = table( ...
                reshape([items.rank], [], 1), ...
                reshape(string({items.siteType}), [], 1), ...
                reshape([items.siteIndex], [], 1), ...
                reshape([items.height], [], 1), ...
                reshape([items.rotationDegrees], [], 1), ...
                reshape([items.score], [], 1), ...
                reshape([items.minimumContact], [], 1), ...
                'VariableNames', {'Rank', 'SiteType', 'SiteIndex', ...
                'Height', 'RotationDegrees', 'Score', ...
                'MinimumContact'});
        end
    end

    methods (Static, Access = private)
        function showAdsorptionCandidates(host, result, titleText, varargin)
            candidates = ...
                kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                adsorptionCandidateTable(result);
            display = [];
            adsorbate = [];
            if numel(varargin) >= 2, display = varargin{2}; end
            if numel(varargin) >= 3, adsorbate = varargin{3}; end
            interactive = ~isempty(display) && isvalid(display) && ...
                ~isempty(adsorbate);
            selectedIndex = 1;
            if interactive, baseRevision = display.getRevision();
            else, baseRevision = 0;
            end
            figureHandle = uifigure("Name", string(titleText) + ...
                " — " + localized("AdsorptionLocatorResults"), ...
                "Position", [100, 100, 880, 461], "Visible", "off");
            layout = uigridlayout(figureHandle, [4, 1], ...
                "RowHeight", {"1x", 22, 54, 34}, ...
                "Padding", [14, 6, 14, 14], "RowSpacing", 7);
            candidateData = table2cell(candidates);
            candidateData(:, 2) = cellstr(candidates.SiteType);
            candidateTable = uitable(layout, ...
                "Data", candidateData, ...
                "RowName", {});
            if result.analysis.isEnergyModel
                scoreHeading = sprintf("%s (%s)", ...
                    localized("AdsorptionEnergyScore"), ...
                    result.analysis.energyUnit);
                modelNotice = sprintf( ...
                    localized("AdsorptionEnergyModelInfo"), ...
                    result.analysis.scoringModel);
                if result.analysis.scoringModel == ...
                        kssolv.modeling.adsorption.UffSurfaceScorer.Id
                    scoreHeading = sprintf("%s (%s)", ...
                        localized("UffInteractionEnergyScore"), ...
                        result.analysis.energyUnit);
                    modelNotice = localized("UffSurfaceModelNotice");
                end
                noticeColor = [.12,.38,.25];
            else
                scoreHeading = localized("AdsorptionGeometricScore");
                modelNotice = localized("AdsorptionNonEnergyWarning");
                noticeColor = [.68,.24,.05];
            end
            candidateTable.ColumnName = { ...
                localized("AdsorptionRank"), ...
                localized("AdsorptionSiteType"), ...
                localized("AdsorptionSiteIndex"), ...
                localized("AdsorptionHeight"), ...
                localized("AdsorptionRotation"), ...
                scoreHeading, ...
                localized("AdsorptionMinimumContact")};
            candidateTable.ColumnWidth = ...
                {55, 120, 90, 105, 115, 175, 170};
            candidateTable.CellSelectionCallback = @selectCandidate;
            uilabel(layout, "Text", sprintf( ...
                localized("AdsorptionCandidateSummary"), ...
                result.analysis.candidateCount, ...
                result.analysis.scoringModel), "FontAngle", "italic");
            warning = uilabel(layout, "Text", modelNotice, ...
                "FontWeight", "bold", "FontColor", noticeColor, ...
                "WordWrap", "on");
            warning.Layout.Row = 3;
            actions = uigridlayout(layout, [1, 4], ...
                "ColumnWidth", {"1x", 100, 100, 100}, ...
                "Padding", [0, 0, 0, 0], "ColumnSpacing", 8);
            previewButton = uibutton(actions, "Text", ...
                localized("PreviewCandidate"), ...
                "Enable", matlab.lang.OnOffSwitchState(interactive), ...
                "ButtonPushedFcn", @previewCandidate);
            previewButton.Layout.Column = 2;
            previewButton.Tag = "AdsorptionCandidatePreview";
            applyButton = uibutton(actions, "Text", ...
                localized("ApplyCandidate"), ...
                "Enable", matlab.lang.OnOffSwitchState(interactive), ...
                "ButtonPushedFcn", @applyCandidate);
            applyButton.Layout.Column = 3;
            applyButton.Tag = "AdsorptionCandidateApply";
            closeButton = uibutton(actions, "Text", localized("Close"), ...
                "ButtonPushedFcn", @closeWindow);
            closeButton.Layout.Column = 4;
            closeButton.Tag = "AdsorptionCandidateClose";
            figureHandle.CloseRequestFcn = @closeWindow;
            kssolv.ui.util.DialogWindow.showCentered(figureHandle);

            function selectCandidate(~, event)
                if ~isempty(event.Indices)
                    selectedIndex = event.Indices(1, 1);
                end
            end

            function model = selectedModel()
                item = result.analysis.candidates(selectedIndex);
                model = kssolv.modeling.adsorption.AdsorptionLocator. ...
                    applyCandidate(host, adsorbate, item);
            end

            function previewCandidate(~, ~)
                runSafely(@()display.showModelingCandidatePreview( ...
                    selectedModel(), baseRevision));
            end

            function applyCandidate(~, ~)
                runSafely(@commitAndClose);
            end

            function commitAndClose()
                item = result.analysis.candidates(selectedIndex);
                description = sprintf("Apply adsorption candidate %d", ...
                    item.rank);
                display.commitModelingCandidate( ...
                    selectedModel(), baseRevision, description);
                closeWindow([], []);
            end

            function runSafely(operation)
                try
                    operation();
                catch exception
                    uialert(figureHandle, exception.message, ...
                        localized("AdsorptionCandidateError"), ...
                        "Icon", "error");
                end
            end

            function closeWindow(~, ~)
                if interactive && isvalid(display)
                    display.clearModelingPreview();
                end
                if isvalid(figureHandle)
                    figureHandle.CloseRequestFcn = [];
                    delete(figureHandle);
                end
            end
        end

        function showInterfaceCandidates(result, titleText)
            candidates = ...
                kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                interfaceCandidateTable(result);
            figureHandle = uifigure("Name", string(titleText) + " — " + ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:InterfaceCandidates"), ...
                "Position", [100, 100, 860, 380], "Visible", "off");
            layout = uigridlayout(figureHandle, [2, 1], ...
                "RowHeight", {"1x", 24}, ...
                "Padding", [14, 14, 14, 14], "RowSpacing", 8);
            uitable(layout, "Data", candidates, "RowName", {});
            uilabel(layout, "Text", sprintf("%s %d; %s: %s", ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:SelectedInterfaceCandidate"), ...
                result.analysis.selectedCandidate, ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:CandidateSort"), ...
                result.analysis.sortMode), "FontAngle", "italic");
            kssolv.ui.util.DialogWindow.showCentered(figureHandle);
        end

        function showSurfaceBuilder(result, titleText)
            candidates = ...
                kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                surfaceTerminationTable(result);
            figureHandle = uifigure("Name", string(titleText) + " — " + ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:SurfaceTerminations"), ...
                "Position", [100, 100, 760, 360], "Visible", "off");
            layout = uigridlayout(figureHandle, [2, 1], ...
                "RowHeight", {"1x", 24}, ...
                "Padding", [14, 14, 14, 14], "RowSpacing", 8);
            uitable(layout, "Data", candidates, "RowName", {});
            uilabel(layout, "Text", sprintf( ...
                "%s %d; hkl [%s]", ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:SelectedTermination"), ...
                result.analysis.selectedTermination, ...
                join(string(result.analysis.millerIndex), " ")), ...
                "FontAngle", "italic");
            kssolv.ui.util.DialogWindow.showCentered(figureHandle);
        end

        function showDefectCandidates(result, titleText)
            candidates = ...
                kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                defectCandidateTable(result);
            figureHandle = uifigure("Name", string(titleText) + " — " + ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:DefectCandidates"), ...
                "Position", [100, 100, 760, 360], "Visible", "off");
            layout = uigridlayout(figureHandle, [2, 1], ...
                "RowHeight", {"1x", 24}, ...
                "Padding", [14, 14, 14, 14], "RowSpacing", 8);
            uitable(layout, "Data", candidates, "RowName", {});
            uilabel(layout, "Text", result.message, "FontAngle", "italic");
            kssolv.ui.util.DialogWindow.showCentered(figureHandle);
        end

        function showCrystalBuilder(result, titleText)
            [asymmetric, equivalent] = ...
                kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                crystalBuilderTables(result);
            figureHandle = uifigure( ...
                "Name", string(titleText) + " — " + ...
                kssolv.ui.util.Localizer.message( ...
                    "KSSOLV:modeling:CrystalBuilderResults"), ...
                "Position", [100, 100, 820, 520], "Visible", "off");
            layout = uigridlayout(figureHandle, [5, 1], ...
                "RowHeight", {22, 120, 22, "1x", 22}, ...
                "Padding", [14, 14, 14, 14], "RowSpacing", 7);
            uilabel(layout, "Text", ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:AsymmetricSites"), ...
                "FontWeight", "bold");
            uitable(layout, "Data", asymmetric, "RowName", {});
            uilabel(layout, "Text", ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:EquivalentSites"), ...
                "FontWeight", "bold");
            uitable(layout, "Data", equivalent, "RowName", {});
            summary = uilabel(layout, "Text", sprintf( ...
                "%s → %s (#%d); min. contact %.5g Å", ...
                analysisText(result, "declaredSpaceGroup"), ...
                analysisText(result, "detectedSpaceGroup"), ...
                result.analysis.detectedNumber, ...
                result.analysis.minimumDistance));
            summary.FontAngle = "italic";
            kssolv.ui.util.DialogWindow.showCentered(figureHandle);
        end

        function plotAdsorptionSites(model, result, titleText)
            figureHandle = figure( ...
                "Name", titleText, "NumberTitle", "off", ...
                "Color", "white");
            axesHandle = axes(figureHandle);
            kssolv.analysis.matgenlab.core.plot_slab( ...
                model, axesHandle, .8, 3, 1.5, true, .2, false);
            sites = result.data;
            if isfield(sites, "all") && ~isempty(sites.all)
                operation = ...
                    kssolv.analysis.matgenlab.core.get_rot(model);
                coordinates = operation.operate(sites.all);
                hold(axesHandle, "on");
                plot(axesHandle, coordinates(:, 1), coordinates(:, 2), ...
                    "kx", "MarkerSize", 10, "LineWidth", 1.5, ...
                    "LineStyle", "none");
                hold(axesHandle, "off");
            end
            title(axesHandle, result.message, ...
                "Interpreter", "none");
        end

        function plotWignerSeitz(model, result, titleText, varargin)
            appContainer = [];
            if ~isempty(varargin)
                appContainer = varargin{1};
            end
            embedInDocument = ~isempty(appContainer) && ...
                isvalid(appContainer);
            figureHandle = figure( ...
                "Name", titleText, "NumberTitle", "off", ...
                "Color", "white", ...
                "Visible", matlab.lang.OnOffSwitchState( ...
                ~embedInDocument));
            axesHandle = axes(figureHandle);
            view(axesHandle, 3);
            axis(axesHandle, "equal");
            grid(axesHandle, "on");
            kssolv.analysis.matgenlab.electronic_structure. ...
                plot_wigner_seitz(model.lattice, axesHandle);
            xlabel(axesHandle, "x (angstrom)");
            ylabel(axesHandle, "y (angstrom)");
            zlabel(axesHandle, "z (angstrom)");
            title(axesHandle, result.message, ...
                "Interpreter", "none");
            if embedInDocument
                documentTag = "ModelingWignerSeitzCell";
                existing = appContainer.getDocument( ...
                    "Plot", documentTag);
                if ~isempty(existing)
                    existing.close();
                end
                dataPlot = ...
                    kssolv.ui.components.figuredocument.DataPlot( ...
                    figureHandle, documentTag);
                dataPlot.Display(char(titleText), false);
                if isvalid(figureHandle)
                    delete(figureHandle);
                end
            end
        end
    end
end

function value = localized(key)
value = kssolv.ui.util.Localizer.message("KSSOLV:modeling:" + key);
end

function value = analysisText(result, name)
value = string(result.analysis.(name));
end
