classdef ParameterSchema
    %PARAMETERSCHEMA Input definitions for interactive modeling commands.

    methods (Static)
        function fields = forCommand(commandId, display)
            commandId = string(commandId);
            isMolecule = ...
                kssolv.modeling.contracts.CommandCapability.modelKind( ...
                display.getModel()) == "molecule";
            selected = display.getSelectedSiteIndices();
            if isempty(selected)
                selectedText = "1";
            else
                selectedText = join(string(selected), " ");
            end
            otherStructure = ...
                kssolv.ui.features.modeling.ModelInputResolver. ...
                suggestOther(display);

            switch commandId
                case "add_atom"
                    fields = field( ...
                        "species", "Element/species", "H", "text");
                    if ~isMolecule
                        fields(end + 1) = field("cartesian", ...
                            "Cartesian coordinates (true/false)", ...
                            "false", "logical");
                    end
                    fields(end + 1) = field("coordinates", ...
                        "Coordinates (x y z)", "0 0 0", "numeric");
                case "center_atoms"
                    fields = indicesField(selectedText);
                    if isMolecule
                        fields(end + 1) = field("center", ...
                            "Cartesian center (angstrom)", ...
                            "0 0 0", "numeric");
                    else
                        fields(end + 1) = field("center", ...
                            "Fractional center", ...
                            "0.5 0.5 0.5", "numeric");
                    end
                case "delete_atoms"
                    fields = indicesField(selectedText);
                case "merge_atoms"
                    fields = [
                        field("tolerance", "Merge tolerance (angstrom)", ...
                            "0.01", "numeric")
                        field("mode", "Mode (delete/sum/average)", ...
                            "delete", "text")
                        ];
                case "fix_atoms"
                    fields = indicesField(selectedText);
                    properties = display.getModel().site_properties;
                    if ~isMolecule && isfield(properties, "surface_layer")
                        fields(end + 1) = field("bottomLayerCount", ...
                            "Fix bottom geometric layers (0 uses selection)", ...
                            "1", "numeric");
                    end
                case "mirror_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("normal", "Plane normal", "1 0 0", "numeric")
                        field("point", "Point on plane (angstrom)", ...
                            "0 0 0", "numeric")
                        ];
                case "move_atoms"
                    fields = indicesField(selectedText);
                    if ~isMolecule
                        fields(end + 1) = field("cartesian", ...
                            "Cartesian coordinates (true/false)", ...
                            "true", "logical");
                    end
                    fields(end + 1) = field("coordinates", ...
                        "New coordinates", "0 0 0", "numeric");
                case {"perturb_atoms", "perturb_structure"}
                    fields = [
                        field("distance", "Maximum displacement (angstrom)", ...
                            "0.1", "numeric")
                        field("minimumDistance", ...
                            "Minimum displacement (angstrom)", "0", "numeric")
                        field("seed", "Random seed", "0", "numeric")
                        ];
                case "sort_atoms"
                    fields = field("reverse", "Reverse order (true/false)", ...
                        "false", "logical");
                case "rotate_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("angleDegrees", "Angle (degrees)", ...
                            "90", "numeric")
                        field("axis", "Rotation axis", "0 0 1", "numeric")
                        field("anchor", "Anchor (angstrom)", ...
                            "0 0 0", "numeric")
                        ];
                case "substitute_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("species", "Replacement species", "Si", "text")
                        ];
                case "translate_atoms"
                    fields = indicesField(selectedText);
                    if ~isMolecule
                        fields(end + 1) = field("fractional", ...
                            "Fractional vector (true/false)", ...
                            "false", "logical");
                    end
                    fields(end + 1) = field("vector", ...
                        "Translation vector", "0 0 1", "numeric");
                case "sketch_atom"
                    connectToDefault = "0";
                    idealLengthDefault = "false";
                    if isscalar(selected)
                        connectToDefault = string(selected);
                        idealLengthDefault = "true";
                    end
                    fields = [
                        field("species", "Element", "C", "text")
                        field("useIdealBondLength", ...
                            "Use force-field ideal bond length", ...
                            idealLengthDefault, "logical")
                        field("coordinates", "Cartesian coordinates (angstrom)", ...
                            "0 0 0", "numeric")
                        field("connectTo", "Connect to atom (0 = none)", ...
                            connectToDefault, "numeric")
                        field("bondOrder", "Bond order (1/1.5/2/3)", ...
                            "1", "numeric")
                        field("formalCharge", "Formal charge", "0", "numeric")
                        field("hybridization", ...
                            "Hybridization (auto/sp/sp2/sp3)", "auto", "text")
                        field("aromatic", "Aromatic atom (true/false)", ...
                            "false", "logical")
                        ];
                case {"add_bond", "delete_bond", "set_bond_order"}
                    fields = indicesField(selectedText);
                    if commandId ~= "delete_bond"
                        fields(end + 1) = field("bondOrder", ...
                            "Bond order (1/1.5/2/3)", "1", "numeric");
                    end
                case "sketch_ring"
                    fields = [
                        field("ringSize", "Ring size (3-8)", "6", "numeric")
                        field("species", "Ring element", "C", "text")
                        field("center", "Ring center (angstrom)", ...
                            "0 0 0", "numeric")
                        field("normal", "Ring plane normal", "0 0 1", "numeric")
                        field("bondLength", "Side length (angstrom)", ...
                            "1.4", "numeric")
                        field("aromatic", "Aromatic ring (true/false)", ...
                            "true", "logical")
                        field("attachTo", "Attach to atom (0 = none)", ...
                            "0", "numeric")
                        ];
                case "set_atom_chemistry"
                    fields = [
                        indicesField(selectedText)
                        field("species", "Element (unchanged = keep)", ...
                            "unchanged", "text")
                        field("formalCharge", "Formal charge", "0", "numeric")
                        field("hybridization", ...
                            "Hybridization (auto/sp/sp2/sp3)", "auto", "text")
                        field("aromatic", "Aromatic atom (true/false)", ...
                            "false", "logical")
                        ];
                case {"add_hydrogens", "remove_hydrogens", ...
                        "diagnose_molecule", "align_geometry"}
                    fields = indicesField(selectedText);
                    if commandId == "align_geometry"
                        fields(end + 1) = field("mode", ...
                            "Mode (principal_axis/plane_normal)", ...
                            "principal_axis", "text");
                        fields(end + 1) = field("target", ...
                            "Target vector", "1 0 0", "numeric");
                    end
                case "measure_geometry"
                    fields = indicesField(selectedText);
                case {"set_distance", "set_angle", "set_dihedral"}
                    fields = [
                        indicesField(selectedText)
                        field("value", "Target value (angstrom or degree)", ...
                            "1.5", "numeric")
                        field("scope", "Move scope (atom/subtree/fragment)", ...
                            "subtree", "text")
                        ];
                case "clean_geometry"
                    fields = field("iterations", ...
                        "Rule-based clean iterations", "4", "numeric");
                case "optimize_geometry"
                    fields = [
                        field("maximumIterations", ...
                            "Maximum optimization iterations", "200", ...
                            "numeric")
                        field("forceTolerance", ...
                            "Maximum-force convergence tolerance", ...
                            "0.001", "numeric")
                        field("fixedIndices", ...
                            "Fixed atom indices (optional)", "", ...
                            "optionalNumeric")
                        ];
                case "attach_fragment"
                    fields = [
                        indicesField(selectedText)
                        field("fragmentName", "Fragment name", ...
                            "Methyl", "text")
                        field("portId", ...
                            "Connection port (blank = primary)", "", ...
                            "optionalText")
                        field("fragmentIndex", "Connection head", "1", "numeric")
                        field("bondOrder", "Bond order", "1", "numeric")
                        ];
                case "save_user_fragment"
                    fields = [
                        field("fragmentName", "User fragment name", ...
                            "User Fragment", "text")
                        field("overwrite", "Overwrite existing (true/false)", ...
                            "false", "logical")
                        ];
                case "build_homopolymer"
                    fields = [
                        field("repeatUnit", "Repeat unit (PE/PP/PS/PEO/PPO)", ...
                            "PE", "text")
                        field("repeatCount", "Repeat count", "20", "numeric")
                        field("tacticity", ...
                            "Tacticity (atactic/isotactic/syndiotactic)", ...
                            "atactic", "text")
                        field("seed", "Random seed", "1", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        polymerArchitectureFields()
                        ];
                case "build_block_copolymer"
                    fields = [
                        field("blockKinds", "Block repeat units", ...
                            "PEO PPO PEO", "text")
                        field("blockLengths", "Block lengths", ...
                            "5 10 5", "numeric")
                        field("tacticity", ...
                            "Tacticity (atactic/isotactic/syndiotactic)", ...
                            "atactic", "text")
                        field("seed", "Random seed", "1", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        field("superunitCount", ...
                            "Repeat complete block superunit", "1", "numeric")
                        polymerArchitectureFields()
                        ];
                case "build_random_copolymer"
                    fields = [
                        field("monomerKinds", "Monomer repeat units", ...
                            "PE PP", "text")
                        field("fractions", "Mole fractions", ".5 .5", "numeric")
                        field("repeatCount", "Repeat count", "20", "numeric")
                        field("exactComposition", "Use exact composition", ...
                            "true", "logical")
                        field("tacticity", ...
                            "Tacticity (atactic/isotactic/syndiotactic)", ...
                            "atactic", "text")
                        field("seed", "Random seed", "1", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        field("reactivityRatios", ...
                            "Terminal-model reactivity ratios", "1 1", "numeric")
                        polymerArchitectureFields()
                        ];
                case "build_branched_polymer"
                    fields = [
                        field("repeatUnit", "Backbone repeat unit", "PE", "text")
                        field("repeatCount", "Repeat count", "20", "numeric")
                        field("branchFragment", "Branch fragment", ...
                            "Methyl", "text")
                        field("branchInterval", "Branch interval", "4", "numeric")
                        field("tacticity", ...
                            "Tacticity (atactic/isotactic/syndiotactic)", ...
                            "atactic", "text")
                        field("seed", "Random seed", "1", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        field("densityRamp", ...
                            "Density ramp stages (optional)", "", ...
                            "optionalNumeric")
                        field("batchSize", "Molecules per packing batch", ...
                            "100", "numeric")
                        ];
                case "build_dendrimer"
                    fields = [
                        field("generations", "Dendrimer generations", ...
                            "2", "numeric")
                        field("coreFunctionality", "Core functionality", ...
                            "3", "numeric")
                        field("branchingFactor", "Branching factor", ...
                            "2", "numeric")
                        field("element", "Skeleton element", "C", "text")
                        field("bondLength", "Skeleton bond length", ...
                            "1.54", "numeric")
                        field("seed", "Geometry seed", "1", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case {"pack_into_existing_box", ...
                        "pack_around_nanoparticle"}
                    fields = [
                        field("componentStructureName", ...
                            "Molecule to pack", otherStructure, "text")
                        field("moleculeCount", "Molecule count", ...
                            "20", "numeric")
                        field("tolerance", "Minimum contact (angstrom)", ...
                            "1.2", "numeric")
                        field("seed", "Random seed", "1", "numeric")
                        field("batchSize", "Molecules per packing batch", ...
                            "100", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                    if commandId=="pack_around_nanoparticle"
                        fields(end+1)=field("clearance", ...
                            "Nanoparticle clearance (angstrom)", ...
                            "1.2", "numeric");
                    end
                case "save_user_repeat_unit"
                    fields = [
                        field("repeatUnitName", "User repeat-unit name", ...
                            "User Repeat Unit", "text")
                        field("headIndex", "Head atom index", "1", "numeric")
                        field("tailIndex", "Tail atom index", "2", "numeric")
                        field("leavingIndices", ...
                            "Leaving atom indices (optional)", "", ...
                            "optionalNumeric")
                        field("overwrite", "Overwrite existing (true/false)", ...
                            "false", "logical")
                        ];
                case {"construct_amorphous", "build_confined_layer"}
                    fields = [
                        field("moleculeCount", "Molecule count", "20", "numeric")
                        field("density", "Target density (g/cm^3)", "1", "numeric")
                        field("tolerance", "Minimum contact (angstrom)", ...
                            "1.2", "numeric")
                        field("seed", "Random seed", "1", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        field("densityRamp", ...
                            "Density ramp stages (optional)", "", ...
                            "optionalNumeric")
                        field("batchSize", "Molecules per packing batch", ...
                            "100", "numeric")
                        ];
                    if commandId == "build_confined_layer"
                        fields(end+1) = field("confinementAxis", ...
                            "Confinement axis (1/2/3)", "3", "numeric");
                        fields(end+1) = field("region", ...
                            "Allowed region [lower upper] (fraction or angstrom)", ...
                            ".1 .9", "numeric");
                    end
                case "pack_mixture"
                    fields = [
                        field("mixtureStructureName", ...
                            "Second project molecule", otherStructure, "text")
                        field("counts", "Component molecule counts", ...
                            "10 10", "numeric")
                        field("compositionMode", ...
                            "Composition mode (count/mole_fraction/mass_fraction)", ...
                            "count", "text")
                        field("totalMolecules", ...
                            "Total molecules for fraction modes", "20", "numeric")
                        field("density", "Target density (g/cm^3)", "1", "numeric")
                        field("tolerance", "Minimum contact (angstrom)", ...
                            "1.2", "numeric")
                        field("seed", "Random seed", "1", "numeric")
                        field("atomLimit", "Maximum atom count", ...
                            "100000", "numeric")
                        field("densityRamp", ...
                            "Density ramp stages (optional)", "", ...
                            "optionalNumeric")
                        field("batchSize", "Molecules per packing batch", ...
                            "100", "numeric")
                        ];
                case {"apply_strain", "strain_structure"}
                    fields = field("strain", ...
                        "Strain (scalar or ex ey ez)", ...
                        "0.01", "numeric");
                case {"edit_lattice", "redefine_lattice"}
                    matrixText = ...
                        kssolv.ui.features.modeling.ParameterSchema.matrixText( ...
                        display.getModel().lattice.matrix);
                    fields = field("matrix", ...
                        "Lattice rows; separate rows with semicolons", ...
                        matrixText, "numeric");
                    if commandId == "edit_lattice"
                        fields(end + 1) = field( ...
                            "preserveCartesian", ...
                            "Preserve Cartesian positions (true/false)", ...
                            "false", "logical");
                    end
                case "mirror_lattice"
                    fields = field("axisIndex", ...
                        "Lattice-vector index (1, 2 or 3)", "1", "numeric");
                case "rotate_lattice"
                    fields = [
                        field("angleDegrees", "Angle (degrees)", ...
                            "90", "numeric")
                        field("axis", "Rotation axis", "0 0 1", "numeric")
                        ];
                case "swap_axes"
                    fields = field("order", "New axis order", ...
                        "2 1 3", "numeric");
                case "build_supercell"
                    fields = field("scalingMatrix", ...
                        "Scale (nx ny nz or 3x3 matrix)", ...
                        "2 2 2", "numeric");
                case "orthogonalize_cell"
                    lengths = display.getModel().lattice.lengths;
                    fields = [
                        field("minimumLength", ...
                            "Minimum cell length (angstrom)", ...
                            compose("%.6g", min(lengths)), "numeric")
                        field("maximumLength", ...
                            "Maximum cell length (angstrom)", ...
                            compose("%.6g", max(lengths) * 4), "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "5000", "numeric")
                        field("angleTolerance", ...
                            "90-degree tolerance (degrees)", ...
                            "0.1", "numeric")
                        ];
                case "create_point_defects"
                    fields = [
                        field("defectType", ...
                            "Type (vacancy/substitution/interstitial/antisite)", ...
                            "vacancy", "text")
                        indicesField(selectedText)
                        field("species", ...
                            "Species (substitution/interstitial)", ...
                            "H", "text")
                        field("cartesian", ...
                            "Interstitial coordinates are Cartesian", ...
                            "false", "logical")
                        field("coordinates", ...
                            "Interstitial coordinates", ...
                            "0.5 0.5 0.5", "numeric")
                        ];
                case "enumerate_point_defects"
                    fields = [
                        field("defectType", ...
                            "Type (vacancy/substitution)", "vacancy", "text")
                        indicesField(selectedText)
                        field("species", "Substitution species", "H", "text")
                        field("replacementCharge", ...
                            "Substitution reference charge", "0", "numeric")
                        symmetryFields()
                        ];
                case "generate_sqs_model"
                    fields = [
                        field("scaling", ...
                            "Supercell scaling (integer or nx ny nz)", ...
                            "1", "numeric")
                        field("searchTime", ...
                            "Search budget (seconds)", "60", "numeric")
                        ];
                case "build_slab"
                    fields = [
                        field("millerIndex", "Miller index (h k l)", ...
                            "0 0 1", "numeric")
                        field("slabSize", ...
                            "Minimum slab thickness (angstrom)", ...
                            "10", "numeric")
                        field("vacuumSize", ...
                            "Minimum vacuum thickness (angstrom)", ...
                            "15", "numeric")
                        field("centerSlab", "Center slab (true/false)", ...
                            "true", "logical")
                        field("primitive", ...
                            "Reduce surface cell (true/false)", ...
                            "true", "logical")
                        field("terminationIndex", ...
                            "Termination candidate index", "1", "numeric")
                        ];
                case "add_vacuum"
                    fields = field("amount", ...
                        "Additional vacuum (angstrom)", ...
                        "10", "numeric");
                case "find_adsorption_sites"
                    fields = field("distance", ...
                        "Adsorbate height (angstrom)", ...
                        "2", "numeric");
                case "locate_adsorbate"
                    fields = [
                        field("adsorbateStructureName", ...
                            "Project adsorbate(s), comma-separated for mixture", ...
                            otherStructure, "text")
                        field("scoringModel", ...
                            "Scoring model", ...
                            kssolv.modeling.adsorption. ...
                            AdsorptionScoringModel.GeometryId, "text")
                        field("siteTypes", ...
                            "Site types (ontop bridge hollow)", ...
                            "ontop bridge hollow", "text")
                        field("heights", ...
                            "Candidate heights (angstrom)", ...
                            "1.8 2.1 2.4", "numeric")
                        field("rotationStep", ...
                            "Rotation step (degrees)", "30", "numeric")
                        field("anchorAtom", "Anchor atom index", "1", "numeric")
                        field("orientationAtom", ...
                            "Orientation atom index (0 = keep)", "0", "numeric")
                        field("minimumDistance", ...
                            "Minimum interatomic distance (angstrom)", ...
                            "0.6", "numeric")
                        field("maximumCandidates", ...
                            "Maximum retained candidates", "200", "numeric")
                        field("seed", "Deterministic seed", "0", "numeric")
                        ];
                case "place_adsorbate"
                    fields=[
                        field("adsorbateStructureName", ...
                            "Project adsorbate(s), comma-separated for mixture", ...
                            otherStructure,"text")
                        field("siteType","Site type (ontop/bridge/hollow)", ...
                            "ontop","text")
                        field("siteIndex","Site candidate index","1","numeric")
                        field("height","Anchor height (angstrom)","2","numeric")
                        field("anchorAtom","Anchor atom index","1","numeric")
                        field("orientationAtom", ...
                            "Orientation atom index (0 = keep)","0","numeric")
                        field("direction","Target orientation vector","0 0 1","numeric")
                        field("minimumDistance", ...
                            "Minimum interatomic distance (angstrom)","0.5","numeric")
                        ];
                case "passivate_surface"
                    fields = [
                        field("species", "Passivant species", ...
                            "H", "text")
                        field("bondLength", ...
                            "Passivant bond length (angstrom)", ...
                            "1.1", "numeric")
                        field("side", ...
                            "Surface side (top/bottom/both)", ...
                            "both", "text")
                        field("surfaceThickness", ...
                            "Surface detection depth (angstrom)", ...
                            "1.5", "numeric")
                        field("targetCoordination", ...
                            "Target coordination (0 = infer)", ...
                            "0", "numeric")
                        field("minimumDistance", ...
                            "Minimum placement distance (angstrom)", ...
                            "0.6", "numeric")
                        ];
                case "add_solvent_layer"
                    fields = [
                        field("solventStructureName", ...
                            "Project solvent molecule/structure", ...
                            otherStructure, "text")
                        field("moleculeCount", ...
                            "Number of solvent molecules", ...
                            "20", "numeric")
                        field("layerThickness", ...
                            "Solvent layer thickness (angstrom)", ...
                            "10", "numeric")
                        field("clearance", ...
                            "Surface clearance (angstrom)", ...
                            "2", "numeric")
                        field("vacuum", ...
                            "Remaining vacuum (angstrom)", ...
                            "5", "numeric")
                        field("tolerance", ...
                            "Packmol tolerance (angstrom)", ...
                            "2", "numeric")
                        field("seed", "Packmol random seed", ...
                            "1", "numeric")
                        field("timeout", ...
                            "Packmol timeout (seconds)", ...
                            "60", "numeric")
                        ];
                case "insert_structure"
                    fields = [
                        field("otherStructureName", ...
                            "Project structure to insert", ...
                            otherStructure, "text")
                        field("translation", ...
                            "Cartesian translation (angstrom)", ...
                            "0 0 0", "numeric")
                        field("minimumDistance", ...
                            "Minimum interatomic distance (angstrom)", ...
                            "0.5", "numeric")
                        ];
                case "stack_heterostructure"
                    fields = [
                        field("otherStructureName", ...
                            "Project top-layer structure", ...
                            otherStructure, "text")
                        field("gap", "Interlayer gap (angstrom)", ...
                            "3.35", "numeric")
                        field("vacuum", "Total vacuum (angstrom)", ...
                            "15", "numeric")
                        field("maximumStrain", ...
                            "Maximum in-plane strain", ...
                            "0.03", "numeric")
                        field("maximumRepeat", ...
                            "Maximum in-plane repeat", "6", "numeric")
                        field("maximumRotation", ...
                            "Maximum rotation search (degrees)", ...
                            "30", "numeric")
                        field("sortMode", ...
                            "Candidate sort (strain/area/atom_count)", ...
                            "strain", "text")
                        field("candidateIndex", ...
                            "Interface candidate index", "1", "numeric")
                        ];
                case "twist_moire"
                    fields = [
                        field("otherStructureName", ...
                            "Project top-layer structure", ...
                            otherStructure, "text")
                        field("angleDegrees", ...
                            "Target twist angle (degrees)", ...
                            "21.786789", "numeric")
                        field("gap", "Interlayer gap (angstrom)", ...
                            "3.35", "numeric")
                        field("vacuum", "Total vacuum (angstrom)", ...
                            "15", "numeric")
                        field("maximumStrain", ...
                            "Maximum in-plane strain", ...
                            "0.03", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        field("maximumIndex", ...
                            "Maximum coincidence index", ...
                            "60", "numeric")
                        ];
                case "interpolate_neb"
                    fields = [
                        field("endStructureName", ...
                            "Project endpoint structure", ...
                            otherStructure, "text")
                        field("intermediateCount", ...
                            "Intermediate image count", ...
                            "5", "numeric")
                        field("maximumSteps", ...
                            "Maximum IDPP optimization steps", ...
                            "200", "numeric")
                        field("forceTolerance", ...
                            "IDPP force tolerance", ...
                            "0.1", "numeric")
                        ];
                case "roll_nanotube"
                    fields = [
                        field("chiralIndices", ...
                            "Chiral indices (n m)", "6 0", "numeric")
                        field("length", "Axial repetitions", ...
                            "1", "numeric")
                        field("vacuum", "Transverse vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case "cut_nanoribbon"
                    fields = [
                        field("width", "Ribbon width repetitions", ...
                            "4", "numeric")
                        field("length", "Axial repetitions", ...
                            "1", "numeric")
                        field("edgeType", ...
                            "Edge type (zigzag/armchair)", ...
                            "zigzag", "text")
                        field("vacuum", "Transverse vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case "cut_nanowire"
                    fields = [
                        field("direction", "Periodic direction (u v w)", ...
                            "0 0 1", "numeric")
                        field("radius", "Wire radius (angstrom)", ...
                            "5", "numeric")
                        field("length", "Axial repetitions", ...
                            "1", "numeric")
                        field("vacuum", "Transverse vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case "quantum_dot_void"
                    fields = [
                        field("mode", "Mode (dot/void)", ...
                            "dot", "text")
                        field("radius", "Radius (angstrom)", ...
                            "5", "numeric")
                        field("vacuum", "Dot vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case {"find_symmetry", "primitive_cell", ...
                        "conventional_cell"}
                    fields = symmetryFields();
                case "build_from_spacegroup"
                    fields = [
                        field("spaceGroup", "Space-group symbol/number", ...
                            "Pm-3m", "text")
                        field("lattice", ...
                            "Lattice rows; separate rows with semicolons", ...
                            "5 0 0; 0 5 0; 0 0 5", "numeric")
                        field("species", "Asymmetric-site species", ...
                            "Si", "text")
                        field("fractionalCoordinates", ...
                            "Asymmetric fractional coordinates", ...
                            "0 0 0", "numeric")
                        field("occupancies", ...
                            "Asymmetric-site occupancies", ...
                            "1", "numeric")
                        field("collisionTolerance", ...
                            "Expanded-site collision tolerance (angstrom)", ...
                            "0.1", "numeric")
                        ];
                case "make_p1"
                    fields = struct.empty;
                case "wigner_seitz_cell"
                    fields = struct.empty;
                otherwise
                    fields = struct.empty;
            end

            if ~isMolecule && any(commandId == [ ...
                    "center_atoms", "delete_atoms", "fix_atoms", ...
                    "mirror_atoms", "move_atoms", "rotate_atoms", ...
                    "substitute_atoms", "translate_atoms"])
                fields(end + 1) = field("symmetryMode", ...
                    "Symmetry choice (preserve/break)", ...
                    "preserve", "text");
            end

            function value = field(name, label, defaultValue, kind)
                value = struct( ...
                    "name", string(name), ...
                    "label", string(label), ...
                    "defaultValue", string(defaultValue), ...
                    "kind", string(kind));
            end

            function values = polymerArchitectureFields()
                values = [
                    field("chainCount", "Independent chain count", ...
                        "1", "numeric")
                    field("headGroup", "Head end group (none or fragment)", ...
                        "none", "text")
                    field("tailGroup", "Tail end group (none or fragment)", ...
                        "none", "text")
                    field("conformation", ...
                        "Initial conformation (extended/zigzag/random_coil)", ...
                        "extended", "text")
                    field("headTailMode", ...
                        "Head-tail mode (regular/alternating/random)", ...
                        "regular", "text")
                    ];
            end

            function value = indicesField(defaultValue)
                value = field("indices", ...
                    "Site indices (MATLAB 1-based)", ...
                    defaultValue, "numeric");
            end

            function value = symmetryFields()
                value = [
                    field("symprec", "Symmetry tolerance (angstrom)", ...
                        "0.01", "numeric")
                    field("angleTolerance", "Angle tolerance (degrees)", ...
                        "5", "numeric")
                    ];
            end
        end
    end

    methods (Static, Access = private)
        function text = matrixText(matrix)
            rows = strings(1, size(matrix, 1));
            for index = 1:size(matrix, 1)
                rows(index) = join(compose("%.10g", matrix(index, :)), " ");
            end
            text = join(rows, "; ");
        end
    end
end
