classdef ParameterSchema
    %PARAMETERSCHEMA Input definitions for interactive modeling commands.

    methods (Static)
        function fields = forCommand(commandId, display)
            commandId = string(commandId);
            selected = display.getSelectedSiteIndices();
            if isempty(selected)
                selectedText = "1";
            else
                selectedText = join(string(selected), " ");
            end
            otherStructure = ...
                kssolv.ui.features.modeling.ModelInputResolver. ...
                suggestOther(display);

            switch commandId
                case "add_atom"
                    fields = [
                        field("species", "Element/species", "H", "text")
                        field("cartesian", "Cartesian coordinates (true/false)", ...
                            "false", "logical")
                        field("coordinates", "Coordinates (x y z)", ...
                            "0 0 0", "numeric")
                        ];
                case "center_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("center", "Fractional center", ...
                            "0.5 0.5 0.5", "numeric")
                        ];
                case "delete_atoms"
                    fields = indicesField(selectedText);
                case "merge_atoms"
                    fields = [
                        field("tolerance", "Merge tolerance (angstrom)", ...
                            "0.01", "numeric")
                        field("mode", "Mode (delete/sum/average)", ...
                            "delete", "text")
                        ];
                case "fix_atoms"
                    fields = indicesField(selectedText);
                case "mirror_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("normal", "Plane normal", "1 0 0", "numeric")
                        field("point", "Point on plane (angstrom)", ...
                            "0 0 0", "numeric")
                        ];
                case "move_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("cartesian", "Cartesian coordinates (true/false)", ...
                            "true", "logical")
                        field("coordinates", "New coordinates", ...
                            "0 0 0", "numeric")
                        ];
                case {"perturb_atoms", "perturb_structure"}
                    fields = [
                        field("distance", "Maximum displacement (angstrom)", ...
                            "0.1", "numeric")
                        field("minimumDistance", ...
                            "Minimum displacement (angstrom)", "0", "numeric")
                        field("seed", "Random seed", "0", "numeric")
                        ];
                case "sort_atoms"
                    fields = field("reverse", "Reverse order (true/false)", ...
                        "false", "logical");
                case "rotate_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("angleDegrees", "Angle (degrees)", ...
                            "90", "numeric")
                        field("axis", "Rotation axis", "0 0 1", "numeric")
                        field("anchor", "Anchor (angstrom)", ...
                            "0 0 0", "numeric")
                        ];
                case "substitute_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("species", "Replacement species", "Si", "text")
                        ];
                case "translate_atoms"
                    fields = [
                        indicesField(selectedText)
                        field("fractional", ...
                            "Fractional vector (true/false)", ...
                            "false", "logical")
                        field("vector", "Translation vector", ...
                            "0 0 1", "numeric")
                        ];
                case {"apply_strain", "strain_structure"}
                    fields = field("strain", ...
                        "Strain (scalar or ex ey ez)", ...
                        "0.01", "numeric");
                case {"edit_lattice", "redefine_lattice"}
                    matrixText = ...
                        kssolv.ui.features.modeling.ParameterSchema.matrixText( ...
                        display.getModel().lattice.matrix);
                    fields = field("matrix", ...
                        "Lattice rows; separate rows with semicolons", ...
                        matrixText, "numeric");
                    if commandId == "edit_lattice"
                        fields(end + 1) = field( ...
                            "preserveCartesian", ...
                            "Preserve Cartesian positions (true/false)", ...
                            "false", "logical");
                    end
                case "mirror_lattice"
                    fields = field("axisIndex", ...
                        "Lattice-vector index (1, 2 or 3)", "1", "numeric");
                case "rotate_lattice"
                    fields = [
                        field("angleDegrees", "Angle (degrees)", ...
                            "90", "numeric")
                        field("axis", "Rotation axis", "0 0 1", "numeric")
                        ];
                case "swap_axes"
                    fields = field("order", "New axis order", ...
                        "2 1 3", "numeric");
                case "build_supercell"
                    fields = field("scalingMatrix", ...
                        "Scale (nx ny nz or 3x3 matrix)", ...
                        "2 2 2", "numeric");
                case "orthogonalize_cell"
                    lengths = display.getModel().lattice.lengths;
                    fields = [
                        field("minimumLength", ...
                            "Minimum cell length (angstrom)", ...
                            compose("%.6g", min(lengths)), "numeric")
                        field("maximumLength", ...
                            "Maximum cell length (angstrom)", ...
                            compose("%.6g", max(lengths) * 4), "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "5000", "numeric")
                        field("angleTolerance", ...
                            "90-degree tolerance (degrees)", ...
                            "0.1", "numeric")
                        ];
                case "create_point_defects"
                    fields = [
                        field("defectType", ...
                            "Type (vacancy/substitution/interstitial/antisite)", ...
                            "vacancy", "text")
                        indicesField(selectedText)
                        field("species", ...
                            "Species (substitution/interstitial)", ...
                            "H", "text")
                        field("cartesian", ...
                            "Interstitial coordinates are Cartesian", ...
                            "false", "logical")
                        field("coordinates", ...
                            "Interstitial coordinates", ...
                            "0.5 0.5 0.5", "numeric")
                        ];
                case "generate_sqs_model"
                    fields = [
                        field("scaling", ...
                            "Supercell scaling (integer or nx ny nz)", ...
                            "1", "numeric")
                        field("searchTime", ...
                            "Search budget (seconds)", "60", "numeric")
                        ];
                case "build_slab"
                    fields = [
                        field("millerIndex", "Miller index (h k l)", ...
                            "0 0 1", "numeric")
                        field("slabSize", ...
                            "Minimum slab thickness (angstrom)", ...
                            "10", "numeric")
                        field("vacuumSize", ...
                            "Minimum vacuum thickness (angstrom)", ...
                            "15", "numeric")
                        field("centerSlab", "Center slab (true/false)", ...
                            "true", "logical")
                        field("primitive", ...
                            "Reduce surface cell (true/false)", ...
                            "true", "logical")
                        ];
                case "add_vacuum"
                    fields = field("amount", ...
                        "Additional vacuum (angstrom)", ...
                        "10", "numeric");
                case "find_adsorption_sites"
                    fields = field("distance", ...
                        "Adsorbate height (angstrom)", ...
                        "2", "numeric");
                case "passivate_surface"
                    fields = [
                        field("species", "Passivant species", ...
                            "H", "text")
                        field("bondLength", ...
                            "Passivant bond length (angstrom)", ...
                            "1.1", "numeric")
                        field("side", ...
                            "Surface side (top/bottom/both)", ...
                            "both", "text")
                        field("surfaceThickness", ...
                            "Surface detection depth (angstrom)", ...
                            "1.5", "numeric")
                        field("targetCoordination", ...
                            "Target coordination (0 = infer)", ...
                            "0", "numeric")
                        field("minimumDistance", ...
                            "Minimum placement distance (angstrom)", ...
                            "0.6", "numeric")
                        ];
                case "add_solvent_layer"
                    fields = [
                        field("solventStructureName", ...
                            "Project solvent molecule/structure", ...
                            otherStructure, "text")
                        field("moleculeCount", ...
                            "Number of solvent molecules", ...
                            "20", "numeric")
                        field("layerThickness", ...
                            "Solvent layer thickness (angstrom)", ...
                            "10", "numeric")
                        field("clearance", ...
                            "Surface clearance (angstrom)", ...
                            "2", "numeric")
                        field("vacuum", ...
                            "Remaining vacuum (angstrom)", ...
                            "5", "numeric")
                        field("tolerance", ...
                            "Packmol tolerance (angstrom)", ...
                            "2", "numeric")
                        field("seed", "Packmol random seed", ...
                            "1", "numeric")
                        field("timeout", ...
                            "Packmol timeout (seconds)", ...
                            "60", "numeric")
                        ];
                case "insert_structure"
                    fields = [
                        field("otherStructureName", ...
                            "Project structure to insert", ...
                            otherStructure, "text")
                        field("translation", ...
                            "Cartesian translation (angstrom)", ...
                            "0 0 0", "numeric")
                        field("minimumDistance", ...
                            "Minimum interatomic distance (angstrom)", ...
                            "0.5", "numeric")
                        ];
                case "stack_heterostructure"
                    fields = [
                        field("otherStructureName", ...
                            "Project top-layer structure", ...
                            otherStructure, "text")
                        field("gap", "Interlayer gap (angstrom)", ...
                            "3.35", "numeric")
                        field("vacuum", "Total vacuum (angstrom)", ...
                            "15", "numeric")
                        field("maximumStrain", ...
                            "Maximum in-plane strain", ...
                            "0.03", "numeric")
                        ];
                case "twist_moire"
                    fields = [
                        field("otherStructureName", ...
                            "Project top-layer structure", ...
                            otherStructure, "text")
                        field("angleDegrees", ...
                            "Target twist angle (degrees)", ...
                            "21.786789", "numeric")
                        field("gap", "Interlayer gap (angstrom)", ...
                            "3.35", "numeric")
                        field("vacuum", "Total vacuum (angstrom)", ...
                            "15", "numeric")
                        field("maximumStrain", ...
                            "Maximum in-plane strain", ...
                            "0.03", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        field("maximumIndex", ...
                            "Maximum coincidence index", ...
                            "60", "numeric")
                        ];
                case "interpolate_neb"
                    fields = [
                        field("endStructureName", ...
                            "Project endpoint structure", ...
                            otherStructure, "text")
                        field("intermediateCount", ...
                            "Intermediate image count", ...
                            "5", "numeric")
                        field("maximumSteps", ...
                            "Maximum IDPP optimization steps", ...
                            "200", "numeric")
                        field("forceTolerance", ...
                            "IDPP force tolerance", ...
                            "0.1", "numeric")
                        ];
                case "roll_nanotube"
                    fields = [
                        field("chiralIndices", ...
                            "Chiral indices (n m)", "6 0", "numeric")
                        field("length", "Axial repetitions", ...
                            "1", "numeric")
                        field("vacuum", "Transverse vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case "cut_nanoribbon"
                    fields = [
                        field("width", "Ribbon width repetitions", ...
                            "4", "numeric")
                        field("length", "Axial repetitions", ...
                            "1", "numeric")
                        field("edgeType", ...
                            "Edge type (zigzag/armchair)", ...
                            "zigzag", "text")
                        field("vacuum", "Transverse vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case "cut_nanowire"
                    fields = [
                        field("direction", "Periodic direction (u v w)", ...
                            "0 0 1", "numeric")
                        field("radius", "Wire radius (angstrom)", ...
                            "5", "numeric")
                        field("length", "Axial repetitions", ...
                            "1", "numeric")
                        field("vacuum", "Transverse vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case "quantum_dot_void"
                    fields = [
                        field("mode", "Mode (dot/void)", ...
                            "dot", "text")
                        field("radius", "Radius (angstrom)", ...
                            "5", "numeric")
                        field("vacuum", "Dot vacuum (angstrom)", ...
                            "8", "numeric")
                        field("maximumAtoms", "Maximum atom count", ...
                            "100000", "numeric")
                        ];
                case {"find_symmetry", "primitive_cell", ...
                        "conventional_cell"}
                    fields = symmetryFields();
                case "wigner_seitz_cell"
                    fields = struct.empty;
                otherwise
                    fields = struct.empty;
            end

            function value = field(name, label, defaultValue, kind)
                value = struct( ...
                    "name", string(name), ...
                    "label", string(label), ...
                    "defaultValue", string(defaultValue), ...
                    "kind", string(kind));
            end

            function value = indicesField(defaultValue)
                value = field("indices", ...
                    "Site indices (MATLAB 1-based)", ...
                    defaultValue, "numeric");
            end

            function value = symmetryFields()
                value = [
                    field("symprec", "Symmetry tolerance (angstrom)", ...
                        "0.01", "numeric")
                    field("angleTolerance", "Angle tolerance (degrees)", ...
                        "5", "numeric")
                    ];
            end
        end
    end

    methods (Static, Access = private)
        function text = matrixText(matrix)
            rows = strings(1, size(matrix, 1));
            for index = 1:size(matrix, 1)
                rows(index) = join(compose("%.10g", matrix(index, :)), " ");
            end
            text = join(rows, "; ");
        end
    end
end
