classdef AdfInventoryTest < matlab.unittest.TestCase
    properties
        fixtureRoot
    end
    methods (TestMethodSetup)
        function locateFixtures(testCase)
            testCase.fixtureRoot=fullfile(pwd,"+kssolv","+analysis", ...
                "+matgenlab","+test","+io","+fixtures","+adf");
        end
    end
    methods (Test)
        function keyOperationsAndSerialization(testCase)
            Key=@(varargin) ...
                kssolv.analysis.matgenlab.io.adf.AdfKey(varargin{:});
            unrestricted=Key("unrestricted");
            testCase.verifyTrue(unrestricted.is_block_key());
            testCase.verifyEqual(unrestricted.key,"UNRESTRICTED");
            testCase.verifyEqual(strtrim(string(unrestricted)), ...
                "UNRESTRICTED");

            charge=Key("charge",{-1,0});
            charge=charge.add_option(2);
            testCase.verifyTrue(charge.has_option(-1));
            charge=charge.remove_option(0);
            testCase.verifyEqual(cell2mat(charge.options),[0,2]);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.adf.AdfKey. ...
                from_dict(charge.as_dict()),charge);

            step=kssolv.analysis.matgenlab.io.adf.AdfKey. ...
                from_str("step rad=0.15 angle=10.0");
            testCase.verifyEqual(step.options{1}{2},.15,AbsTol=1e-14);
            step=step.add_option({"length",.1});
            testCase.verifyTrue(step.has_option("length"));
            step=step.remove_option("rad");
            testCase.verifyFalse(step.has_option("rad"));
            testCase.verifyError(@()step.add_option(3), ...
                "KSSOLV:Matgenlab:ADF:OptionType");

            geometry=kssolv.analysis.matgenlab.io.adf.AdfKey. ...
                from_str("GEOMETRY"+newline+"optim all"+newline+ ...
                "iterations 100"+newline+"END"+newline);
            testCase.verifyTrue(geometry.has_subkey("optim"));
            geometry=geometry.remove_subkey("optim");
            testCase.verifyFalse(geometry.has_subkey("optim"));
            testCase.verifyEqual(geometry.subkeys{1}.options{1},100);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.adf.AdfKey.from_str( ...
                "ZLMFIT"+newline+"AtomDepQuality"+newline+ ...
                "subend"+newline+"END"), ...
                "KSSOLV:Matgenlab:ADF:NestedParse");
        end

        function nestedAndAtomFormattingMatch(testCase)
            Key=@(varargin) ...
                kssolv.analysis.matgenlab.io.adf.AdfKey(varargin{:});
            quality=Key("AtomDepQuality",[], ...
                {Key("10",{"good"}),Key("12",{"normal"})});
            zlm=Key("zlmfit",[],{quality});
            expected="ZLMFIT"+newline+"AtomDepQuality"+newline+ ...
                "10 good"+newline+"12 normal"+newline+ ...
                "subend"+newline+"END"+newline;
            testCase.verifyEqual(string(zlm),expected);

            atoms=Key("atoms");
            atoms=atoms.add_subkey(Key("O", ...
                {-0.90293455,.66591421,0}));
            atoms=atoms.add_subkey(Key("H", ...
                {.05706545,.66591421,0}));
            atoms=atoms.add_subkey(Key("H", ...
                {-1.22338913,1.57085004,0}));
            expected="ATOMS"+newline+ ...
                "O      -0.90293455        0.66591421        0.00000000"+newline+ ...
                "H       0.05706545        0.66591421        0.00000000"+newline+ ...
                "H      -1.22338913        1.57085004        0.00000000"+newline+ ...
                "END"+newline;
            testCase.verifyEqual(string(atoms),expected);
        end

        function taskDefaultsAndSerializationMatch(testCase)
            task=kssolv.analysis.matgenlab.io.adf.AdfTask();
            expected="TITLE ADF_RUN"+newline+newline+ ...
                "UNITS"+newline+"length angstrom"+newline+ ...
                "angle degree"+newline+"END"+newline+newline+ ...
                "XC"+newline+"GGA PBE"+newline+"END"+newline+newline+ ...
                "BASIS"+newline+"type DZ"+newline+"core small"+newline+ ...
                "END"+newline+newline+"SCF"+newline+"iterations 300"+ ...
                newline+"END"+newline+newline+"GEOMETRY SinglePoint"+ ...
                newline+"END"+newline+newline;
            testCase.verifyEqual(string(task),expected);
            rebuilt=kssolv.analysis.matgenlab.io.adf.AdfTask. ...
                from_dict(task.as_dict());
            testCase.verifyEqual(string(rebuilt),string(task));
            testCase.verifyEqual(string( ...
                kssolv.analysis.matgenlab.io.adf.AdfTask. ...
                get_default_geo()), ...
                "GEOMETRY SinglePoint"+newline+"END"+newline);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.adf.AdfTask("gradient"), ...
                "KSSOLV:Matgenlab:ADF:Input");
        end

        function inputMatchesOfficialFixture(testCase)
            [species,coordinates]=atomsFromInput(fullfile( ...
                testCase.fixtureRoot,"RhB18_adf.inp"));
            molecule=kssolv.analysis.matgenlab.core.Molecule( ...
                species,coordinates,charge=-1,spin_multiplicity=3);
            Key=@(text) ...
                kssolv.analysis.matgenlab.io.adf.AdfKey.from_str(text);
            basis=Key("BASIS"+newline+"type TZP"+newline+ ...
                "core small"+newline+"END");
            xc=Key("XC"+newline+"Hybrid PBE0"+newline+"END");
            units=Key("UNITS"+newline+"length angstrom"+newline+"END");
            geo={Key("optim all"),Key("iterations 300"), ...
                Key("step rad=0.15 angle=10.0"),Key("hessupd BFGS")};
            scf=Key("SCF"+newline+"iterations 300"+newline+ ...
                "converge 1.0e-7 1.0e-7"+newline+"mixing 0.2"+newline+ ...
                "lshift 0.0"+newline+ ...
                "diis n=100 ok=0.0001 cyc=100 cx=5.0 cxx=10.0"+ ...
                newline+"END");
            others={Key("SYMMETRY"),Key("RELATIVISTIC scalar zora"), ...
                Key("INTEGRATION 6.0 6.0 6.0"), ...
                Key("SAVE TAPE21"),Key("A1FIT 10.0")};
            task=kssolv.analysis.matgenlab.io.adf.AdfTask( ...
                "optimize",basis,xc,"RhB18",units,geo,scf,others);
            output=string(tempname);cleanup=onCleanup(@()deleteIfExists(output));
            kssolv.analysis.matgenlab.io.adf.AdfInput(task). ...
                write_file(molecule,output);
            testCase.verifyEqual(fileread(output),fileread(fullfile( ...
                testCase.fixtureRoot,"RhB18_adf.inp")));
            clear cleanup
        end

        function officialOutputsMatchFrozenValues(testCase)
            Output=@(kind)kssolv.analysis.matgenlab.io.adf.AdfOutput( ...
                fullfile(testCase.fixtureRoot,kind,"adf.out"));
            singlePoint=Output("sp");
            testCase.verifyEqual(string(singlePoint.run_type),"SinglePoint");
            testCase.verifyEqual(singlePoint.final_energy, ...
                -.74399276,AbsTol=1e-12);
            testCase.verifyEqual(singlePoint.final_structure.num_sites,4);

            analytical=Output("analytical_freq");
            testCase.verifyEqual(analytical.final_energy, ...
                -.54340325,AbsTol=1e-12);
            testCase.verifyEqual(numel(analytical.energies),4);
            testCase.verifyEqual(numel(analytical.structures),4);
            testCase.verifyEqual(analytical.frequencies([1,3]), ...
                [1553.931,3793.086],AbsTol=1e-9);
            testCase.verifyEqual(analytical.normal_modes{1}([3,7,8,9]), ...
                [.071,0,-.426,-.562],AbsTol=1e-12);

            numerical=Output("numerical_freq");
            testCase.verifyEqual(string(numerical.freq_type),"Numerical");
            testCase.verifyEqual(numerical.final_structure.num_sites,4);
            testCase.verifyEqual(numerical.frequencies([1,4,5,6]), ...
                [938.21,3426.64,3559.35,3559.35],AbsTol=1e-9);
            testCase.verifyEqual(numerical.normal_modes{2}([1,4,8,10]), ...
                [.067,-.536,0,-.536],AbsTol=1e-12);
        end

        function errorsArePublicTypes(testCase)
            input=kssolv.analysis.matgenlab.io.adf. ...
                AdfInputError("input");
            output=kssolv.analysis.matgenlab.io.adf. ...
                AdfOutputError("output");
            testCase.verifyEqual(input.identifier, ...
                'KSSOLV:Matgenlab:ADF:Input');
            testCase.verifyEqual(output.identifier, ...
                'KSSOLV:Matgenlab:ADF:Output');
        end
    end
end

function [species,coordinates]=atomsFromInput(filename)
lines=splitlines(string(fileread(filename)));
start=find(strip(lines)=="ATOMS cartesian",1)+1;
finish=start+find(strip(lines(start:end))=="END",1)-2;
species=cell(1,finish-start+1);
coordinates=zeros(finish-start+1,3);
for line=start:finish
    fields=split(strip(lines(line)));
    species{line-start+1}=char(fields(1));
    coordinates(line-start+1,:)=str2double(fields(2:4));
end
end

function deleteIfExists(filename)
if isfile(filename),delete(filename);end
end
