classdef AseInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function structureRoundTripPreservesAllMappedProperties(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice( ...
                eye(3) * 4, [true, true, false]), ...
                {"Fe", "O"}, [0, 0, 0; .5, .5, .5], ...
                site_properties = struct( ...
                "magmom", [2, 0], "final_magmom", [1, 0.1], ...
                "charge", [.2, -.2], "final_charge", [.1, -.1], ...
                "tags", [3, 4], "prop", [5, 6], ...
                "selective_dynamics", ...
                {{[true, false, true], [false, false, false]}}), ...
                properties = struct("test", "hi"));
            atoms = kssolv.analysis.matgenlab.io.ase. ...
                AseAtomsAdaptor.get_atoms(structure);
            testCase.verifyClass(atoms, ...
                "kssolv.analysis.matgenlab.io.ase.MSONAtoms");
            testCase.verifyEqual(atoms.pbc, [true, true, false]);
            testCase.verifyEqual(atoms.arrays.initial_magmoms, [2, 0]);
            testCase.verifyEqual(atoms.calc.results.charges, [.1, -.1]);
            restored = kssolv.analysis.matgenlab.io.ase. ...
                AseAtomsAdaptor.get_structure(atoms);
            testCase.verifyEqual(restored.frac_coords, ...
                structure.frac_coords, AbsTol = 1e-14);
            testCase.verifyEqual(restored.lattice.pbc, ...
                structure.lattice.pbc);
            testCase.verifyEqual(restored.site_properties.magmom, ...
                {2, 0});
            testCase.verifyEqual(restored.site_properties.final_charge, ...
                {.1, -.1});
            testCase.verifyEqual(restored.site_properties. ...
                selective_dynamics, ...
                {[true, false, true], [false, false, false]});
            testCase.verifyEqual(restored.structure_properties.test, "hi");
        end

        function moleculeRoundTripPreservesGlobalState(testCase)
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                {"C", "H"}, [0, 0, 0; 1, 0, 0], ...
                charge = -1, spin_multiplicity = 3, ...
                site_properties = struct("prop", [1, 2]), ...
                properties = struct("source", "offline"));
            atoms = kssolv.analysis.matgenlab.io.ase. ...
                AseAtomsAdaptor.get_atoms(molecule, false);
            testCase.verifyTrue(isstruct(atoms));
            restored = kssolv.analysis.matgenlab.io.ase. ...
                AseAtomsAdaptor.get_molecule(atoms);
            testCase.verifyEqual(restored.charge, -1);
            testCase.verifyEqual(restored.spin_multiplicity, 3);
            testCase.verifyEqual(restored.cart_coords, ...
                molecule.cart_coords, AbsTol = 1e-14);
            testCase.verifyEqual(restored.molecule_properties.source, ...
                "offline");
        end

        function oxidationAndMsonRoundTrip(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 3, {"Li", "O"}, [0, 0, 0; .5, .5, .5]);
            structure = structure.add_oxidation_state_by_site([1, -2]);
            atoms = kssolv.analysis.matgenlab.io.ase. ...
                AseAtomsAdaptor.get_atoms(structure);
            encoded = atoms.as_dict();
            restoredAtoms = kssolv.analysis.matgenlab.io.ase. ...
                MSONAtoms.from_dict(encoded);
            testCase.verifyTrue(restoredAtoms == atoms);
            restored = kssolv.analysis.matgenlab.io.ase. ...
                AseAtomsAdaptor.get_structure(restoredAtoms);
            testCase.verifyEqual(restored.species{1}.oxi_state, 1);
            testCase.verifyEqual(restored.species{2}.oxi_state, -2);
        end

        function disorderedStructureIsRejected(testCase)
            mixed = struct("Li", .5, "Na", .5);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3), {mixed}, [0, 0, 0]);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.ase. ...
                AseAtomsAdaptor.get_atoms(structure), ...
                "KSSOLV:Matgenlab:ASE:Disordered");
        end
    end
end
