classdef ExcitingInputTest < matlab.unittest.TestCase
    methods (Test)
        function officialFileParsesLikeFrozenPymatgen(testCase)
            input = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput. ...
                from_file(excitingFixture("input_exciting1.xml"));
            testCase.verifyEqual(input.structure.lattice.matrix, ...
                [0, 2.81, 2.81; 2.81, 0, 2.81; ...
                2.81, 2.81, 0], AbsTol = 1e-8);
            testCase.verifyEqual(input.structure.frac_coords, ...
                [0, 0, 0; 0.5, 0.5, 0.5], AbsTol = 1e-12);
            testCase.verifyEqual(cellfun(@(site) site.specie.symbol, ...
                input.structure.sites), ["Na", "Cl"]);
            testCase.verifyEqual(input.title, "Na4 Cl4");
            testCase.verifyEqual(input.lockxyz, false(2, 3));
        end

        function unchangedWriterRoundTripsStructure(testCase)
            structure = rocksalt();
            input = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput( ...
                    structure);
            text = input.write_string("unchanged");
            testCase.verifyThat(text, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                    "xsi:noNamespaceSchemaLocation"));
            testCase.verifyThat(text, ...
                matlab.unittest.constraints.ContainsSubstring( ...
                    "<species speciesfile=""Na.xml"">"));
            restored = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput. ...
                from_str(text);
            testCase.verifyEqual(restored.structure.lattice.matrix, ...
                structure.lattice.matrix, AbsTol = 1e-8);
            testCase.verifyEqual(restored.structure.frac_coords, ...
                structure.frac_coords, AbsTol = 1e-8);
            registered = ...
                kssolv.analysis.matgenlab.core.Structure.from_str( ...
                    text, "exciting");
            testCase.verifyEqual(registered.frac_coords, ...
                structure.frac_coords, AbsTol = 1e-8);
            element = input.write_etree("unchanged");
            testCase.verifyEqual(string(element.getTagName()), "input");
            path = string(tempname) + ".xml.gz";
            cleanup = onCleanup(@() deleteIfPresent(path));
            input.write_file("unchanged", path);
            restored = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput. ...
                from_file(path);
            testCase.verifyEqual(restored.structure.frac_coords, ...
                structure.frac_coords, AbsTol = 1e-8);
            clear cleanup
        end

        function lockAndCartesianSemantics(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {"Si", "O"}, [0, 0, 0; 0.25, 0.5, 0.75]);
            locks = [true, false, true; false, true, false];
            input = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput( ...
                    structure, "locked", locks);
            testCase.verifyEqual(input.lockxyz, locks);
            input.lockxyz = ~locks;
            testCase.verifyEqual(input.lockxyz, ~locks);
            text = input.write_string("unchanged", "cartesian", true);
            restored = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput. ...
                from_str(text);
            testCase.verifyEqual(restored.structure.cart_coords, ...
                structure.cart_coords, AbsTol = 1e-7);
        end

        function nestedParametersMatchOfficialFixture(testCase)
            lattice = ...
                kssolv.analysis.matgenlab.core.Lattice. ...
                from_parameters(3.84, 3.84, 3.84, 120, 90, 60);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"Si", "Si"}, ...
                [0, 0, 0; 0.75, 0.5, 0.75]);
            input = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput( ...
                    structure);
            grst = struct("do", "fromscratch", "ngridk", "8 8 8", ...
                "xctype", "GGA_PBE_SOL", "gmaxvr", "14.0");
            xs = struct("xstype", "BSE", "ngridk", "4 4 4", ...
                "ngridq", "4 4 4", "nempty", "30", "gqmax", "3.0", ...
                "broad", "0.07", "tevout", "true", ...
                "energywindow", struct("intv", "0.0 1.0", ...
                "points", "1200"), ...
                "screening", struct("screentype", "full", ...
                "nempty", "100"), ...
                "BSE", struct("bsetype", "singlet", ...
                "nstlbse", "1 5 1 4"));
            actual = input.write_string( ...
                "unchanged", "grst", grst, "xs", xs);
            expected = string(fileread( ...
                excitingFixture("input_exciting2.xml")));
            actual = regexprep(actual, ...
                'scale="[^"]+"', 'scale="VALUE"');
            expected = regexprep(expected, ...
                'scale="[^"]+"', 'scale="VALUE"');
            testCase.verifyEqual(split(strtrim(actual)), ...
                split(strtrim(expected)));
        end

        function primitiveBandPathMatchesFrozenOracle(testCase)
            structure = ...
                kssolv.analysis.matgenlab.core.Structure.from_file( ...
                    excitingFixture("CsI3Pb.cif"));
            input = ...
                kssolv.analysis.matgenlab.io.exciting.ExcitingInput( ...
                    structure);
            text = input.write_string( ...
                "primitive", "bandstr", true);
            labels = regexp(text, 'label="([^"]+)"', ...
                "tokens");
            labels = string(cellfun(@(entry) entry{1}, ...
                labels, UniformOutput = false));
            expected = ["GAMMA", "X", "S", "Y", "GAMMA", "Z", ...
                "U", "R", "T", "Z", "Y", "T", "U", "X", "S", "R"];
            testCase.verifyEqual(labels, expected);
            testCase.verifyError(@() input.write_string( ...
                "conventional", "bandstr", true), ...
                "KSSOLV:Matgenlab:ExcitingInput:BandCell");
        end
    end
end

function structure = rocksalt()
structure = kssolv.analysis.matgenlab.core.Structure( ...
    kssolv.analysis.matgenlab.core.Lattice.cubic(5.62), ...
    {"Na", "Na", "Na", "Na", "Cl", "Cl", "Cl", "Cl"}, ...
    [0, 0, 0; 0.5, 0.5, 0; 0.5, 0, 0.5; 0, 0.5, 0.5; ...
    0.5, 0, 0; 0, 0.5, 0; 0, 0, 0.5; 0.5, 0.5, 0.5]);
end

function path = excitingFixture(name)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "+exciting", name);
end

function deleteIfPresent(path)
if isfile(path), delete(path); end
end
