classdef FiestaTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 oracle tests for pymatgen.io.fiesta.

    methods (Test)
        function frozenInventorySurfaceIsImplemented(testCase)
            ledger = readtable(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", ...
                "compatibility_ledger.csv"), TextType = "string", ...
                Delimiter = ",");
            rows = ledger(ledger.module == "pymatgen.io.fiesta", :);
            testCase.verifyEqual(height(rows), 28);
            testCase.verifyTrue(all(rows.status == "implemented"), ...
                join(rows.api_id(rows.status ~= "implemented"), newline));

            package = "kssolv.analysis.matgenlab.io.fiesta.";
            expected = struct( ...
                "Nwchem2Fiesta", ...
                    ["run", "as_dict", "from_dict"], ...
                "FiestaRun", ...
                    ["run", "bse_run", "as_dict", "from_dict"], ...
                "BasisSetReader", ...
                    ["set_n_nlmo", "infos_on_basis_set"], ...
                "FiestaInput", ...
                    ["set_auxiliary_basis_set", "set_gw_options", ...
                    "make_full_bse_densities_folder", ...
                    "set_bse_options", "dump_bse_data_in_gw_run", ...
                    "dump_tddft_data_in_gw_run", "write_file", ...
                    "as_dict", "from_dict", "from_str", "from_file"], ...
                "FiestaOutput", strings(1, 0), ...
                "BSEOutput", strings(1, 0));
            classes = fieldnames(expected);
            for index = 1:numel(classes)
                metadata = meta.class.fromName( ...
                    package + classes{index});
                testCase.verifyNotEmpty(metadata, classes{index});
                methods = metadataNames(metadata.MethodList);
                testCase.verifyTrue(all(ismember( ...
                    expected.(classes{index}), methods)), ...
                    classes{index});
            end
            metadata = meta.class.fromName(package + "FiestaInput");
            properties = metadataNames(metadata.PropertyList);
            testCase.verifyTrue(all(ismember( ...
                ["infos_on_system", "molecule"], properties)));
        end

        function fiestaInputExactFrozenTextAndRoundTrip(testCase)
            input = methaneInput();
            testCase.verifyEqual(string(input), frozenCellInput());
            testCase.verifyEqual(input.infos_on_system, ...
                frozenSystemInfo());
            restored = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                from_str(string(input));
            testCase.verifyEqual(string(restored), string(input));
            testCase.verifyEqual(restored.GW_options.nc_corr, "10");
            testCase.verifyEqual(restored.cohsex_options.eigMethod, "C");
            testCase.verifyEqual(restored.molecule.cart_coords, ...
                input.molecule.cart_coords, AbsTol = 1e-15);

            scaledText = replace(string(input), ...
                "# scaling factor" + newline + "    1.000", ...
                "# scaling factor" + newline + "    2.000");
            scaled = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                from_str(scaledText);
            testCase.verifyEqual(scaled.molecule.cart_coords, ...
                input.molecule.cart_coords, AbsTol = 1e-15);
        end

        function fiestaInputDefaultsAndMutatorsMatchOracle(testCase)
            input = methaneInput();
            input.set_gw_options();
            testCase.verifyEqual(input.GW_options, ...
                struct("nc_corr", 10, "nit_gw", 5, "nv_corr", 10));
            testCase.verifyEqual(input.correlation_grid, ...
                struct("dE_grid", .5, "n_grid", 6));
            input.set_bse_options();
            testCase.verifyEqual(input.bse_tddft_options.npsi_bse, 10);
            testCase.verifyEqual(input.bse_tddft_options.nit_bse, 200);
            input.dump_bse_data_in_gw_run(false);
            testCase.verifyEqual(input.bse_tddft_options.do_bse, 0);
            testCase.verifyEqual(input.bse_tddft_options.do_tddft, 0);
            input.dump_tddft_data_in_gw_run(false);
            testCase.verifyEqual(input.bse_tddft_options.do_bse, "0");
            testCase.verifyEqual(input.bse_tddft_options.do_tddft, "0");
            input.dump_tddft_data_in_gw_run();
            testCase.verifyEqual(input.bse_tddft_options.do_tddft, "1");
        end

        function fiestaSystemInfoAlternateBranchesMatchOracle(testCase)
            input = methaneInput();
            exc = input.Exc_DFT_option;
            exc.rdVxcpsi = "0";
            input.Exc_DFT_option = exc;
            cohsex = input.cohsex_options;
            cohsex.eigMethod = "HF";
            cohsex.nv_cohsex = "2";
            cohsex.nc_cohsex = "3";
            cohsex.nit_cohsex = "4";
            input.cohsex_options = cohsex;
            dumps = input.bse_tddft_options;
            dumps.do_bse = "0";
            dumps.do_tddft = "1";
            input.bse_tddft_options = dumps;
            info = input.infos_on_system;
            testCase.verifyTrue(contains(info, ...
                "' Exchange and correlation energy re-computed'"));
            testCase.verifyTrue(contains(info, ...
                "' Correcting  2 valence bands and  3 conduction bands at HF level'"));
            testCase.verifyTrue(contains(info, ...
                "' Performing   4 diagonal HF iterations'"));
            testCase.verifyFalse(contains(info, ...
                "Dumping data for BSE treatment"));
            testCase.verifyTrue(contains(info, ...
                "' Dumping data for TD-DFT treatment'"));
        end

        function fiestaInputDictionaryUsesFrozenKeysAndError(testCase)
            input = methaneInput();
            value = input.as_dict();
            testCase.verifyEqual(fieldnames(value), ...
                {'mol'; 'correlation_grid'; 'Exc_DFT_option'; ...
                'COHSEX_options'; 'GW_options'; 'BSE_TDDFT_options'});
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                from_dict(value), ...
                "KSSOLV:Matgenlab:Fiesta:FrozenFromDictKey");
            value.geometry_options = value.COHSEX_options;
            value.symmetry_options = value.GW_options;
            value.memory_options = value.BSE_TDDFT_options;
            restored = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                from_dict(value);
            testCase.verifyEqual(string(restored), string(input));
            decoded = jsondecode(input.toJSON());
            testCase.verifyEqual(string(decoded.GW_options.nc_corr), "10");
        end

        function fiestaInputFilesCompressionAndParseErrors(testCase)
            input = methaneInput();
            paths = [string(tempname) + ".cell.in", ...
                string(tempname) + ".cell.in.gz"];
            cleanup = onCleanup(@() deleteFiles(paths));
            for path = paths
                input.write_file(path);
                restored = ...
                    kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                    from_file(path);
                testCase.verifyEqual(string(restored), string(input));
            end
            unsupported = string(tempname) + ".xz";
            testCase.verifyError(@() input.write_file(unsupported), ...
                "KSSOLV:Matgenlab:Fiesta:CompressionUnsupported");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                from_str("not a cell.in"), ...
                "KSSOLV:Matgenlab:Fiesta:Parse");
            clear cleanup
        end

        function auxiliaryBasisAndDensityFolderSemantics(testCase)
            input = methaneInput();
            destination = string(tempname);
            mkdir(destination);
            cleanup = onCleanup(@() removeTree(destination));
            input.set_auxiliary_basis_set(destination, ...
                fiestaFixture(""));
            testCase.verifyEqual(strtrim(string(fileread( ...
                fullfile(destination, "C2.ion")))), ...
                "C auxiliary oracle");
            testCase.verifyEqual(strtrim(string(fileread( ...
                fullfile(destination, "H2.ion")))), ...
                "H auxiliary oracle");

            root = string(tempname);
            mkdir(root);
            rootCleanup = onCleanup(@() removeTree(root));
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                make_full_bse_densities_folder(root), ...
                "makedirs FULL_BSE_Densities folder");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                make_full_bse_densities_folder(root), ...
                "KSSOLV:Matgenlab:Fiesta:FileExists");

            fileRoot = string(tempname);
            mkdir(fileRoot);
            fileCleanup = onCleanup(@() removeTree(fileRoot));
            writeText(fullfile(fileRoot, "FULL_BSE_Densities"), "x");
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                make_full_bse_densities_folder(fileRoot), ...
                "FULL_BSE_Densities folder already exists");
            clear cleanup rootCleanup fileCleanup
        end

        function basisSetReaderMatchesFrozenMutationBug(testCase)
            reader = ...
                kssolv.analysis.matgenlab.io.fiesta.BasisSetReader( ...
                fiestaFixture("synthetic_basis.ion"));
            testCase.verifyEqual(reader.data("n_nlmo"), "4");
            testCase.verifyFalse(isKey(reader.data, "lmax"));
            testCase.verifyEqual(reader.data("0_1_2"), ...
                {'1.0', '0.5'; '2.0', '-0.2'});
            testCase.verifyError(@() reader.infos_on_basis_set(), ...
                "KSSOLV:Matgenlab:Fiesta:BasisHeaderDiscarded");
            testCase.verifyError(@() reader.set_n_nlmo(), ...
                "KSSOLV:Matgenlab:Fiesta:BasisHeaderDiscarded");
        end

        function officialFiestaOutputMatchesFrozenOracle(testCase)
            output = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaOutput( ...
                fiestaFixture("log_fiesta"));
            testCase.verifyEqual(numel(output.data), 3);
            testCase.verifyEqual(numel(output.data{1}.keys()), 11);
            testCase.verifyEqual(numel(output.data{2}.keys()), 11);
            testCase.verifyEqual(numel(output.data{3}.keys()), 13);
            gaps = output.data{1}("Gaps");
            testCase.verifyEqual(gaps.Egap_KS, "6.9992");
            testCase.verifyEqual(gaps.Egap_QP_Linear, "10.4135");
            testCase.verifyEqual(gaps.Egap_QP_SCF, "9.3011");
            homo = output.data{1}("HOMO");
            testCase.verifyEqual(homo, struct("band", "HOMO", ...
                "eKS", "-7.3029", "eXX", "-15.9483", ...
                "eQP_old", "-7.7188", "z", "0.87", ...
                "sigma_c_Linear", "-0.4587", ...
                "eQP_Linear", "-9.5142", ...
                "sigma_c_SCF", "0.3900", ...
                "eQP_SCF", "-8.9264"));
            testCase.verifyEqual( ...
                output.data{2}("Gaps").Egap_QP_Linear, "10.6398");
            testCase.verifyEqual( ...
                output.data{1}("LUMO+1").sigma_c_SCF, "-2.6453");
            testCase.verifyEqual( ...
                output.data{3}("Gaps").Egap_QP_Linear, "10.7401");
            testCase.verifyEqual(output.data{3}("total_time"), ...
                "172.732740000000");
            testCase.verifyTrue(output.data{3}("end_normally"));
        end

        function bseOutputMatchesFrozenSyntheticOracle(testCase)
            output = kssolv.analysis.matgenlab.io.fiesta.BSEOutput( ...
                fiestaFixture("synthetic_bse.log"));
            testCase.verifyEqual(output.exiton("1"), ...
                struct("bse_eig", "1.234", ...
                "osc_strength", "-0.005"));
            testCase.verifyEqual(output.exiton("12"), ...
                struct("bse_eig", "4.500", ...
                "osc_strength", "0.600"));
            testCase.verifyEqual(output.exiton("total_time"), "12.50");
            testCase.verifyTrue(output.exiton("end_normally"));
        end

        function nwchemRunnerRequiresAndUsesExplicitExecutor(testCase)
            folder = string(tempname);
            mkdir(folder);
            cleanup = onCleanup(@() removeTree(folder));
            runner = ...
                kssolv.analysis.matgenlab.io.fiesta.Nwchem2Fiesta( ...
                folder, "methane", "convert.log");
            testCase.verifyError(@() runner.run(), ...
                "KSSOLV:Matgenlab:Fiesta:ExecutorRequired");
            runner.executor = @nwchemExecutor;
            runner.run();
            testCase.verifyEqual(string(fileread( ...
                fullfile(folder, "convert.log"))), "converted");
            value = runner.as_dict();
            testCase.verifyEqual(fieldnames(value), ...
                {'x_module'; 'x_class'; 'filename'; 'folder'});
            restored = ...
                kssolv.analysis.matgenlab.io.fiesta.Nwchem2Fiesta. ...
                from_dict(value);
            testCase.verifyEqual(restored.log_file, "log_n2f");
            decoded = kssolv.analysis.matgenlab.util.decode( ...
                runner.toJSON());
            testCase.verifyClass(decoded, ...
                "kssolv.analysis.matgenlab.io.fiesta.Nwchem2Fiesta");
            clear cleanup
        end

        function fiestaRunnerGwBseMSONAndErrors(testCase)
            folder = string(tempname);
            mkdir(folder);
            cleanup = onCleanup(@() removeTree(folder));
            gw = kssolv.analysis.matgenlab.io.fiesta.FiestaRun( ...
                folder, [2, 2, 2], "gw.log", @runnerExecutor);
            gw.run();
            testCase.verifyEqual(gw.mpi_procs, 8);
            testCase.verifyEqual(string(fileread( ...
                fullfile(folder, "gw.log"))), ...
                "mpirun|-n,8,fiesta,2,2,2");
            bse = kssolv.analysis.matgenlab.io.fiesta.FiestaRun( ...
                folder, [2, 2], "bse.log", @runnerExecutor);
            testCase.verifyError(@() bse.bse_run(), ...
                "KSSOLV:Matgenlab:Fiesta:MPIProcsUnset");
            bse.run();
            testCase.verifyEqual(bse.mpi_procs, 4);
            testCase.verifyEqual(string(fileread( ...
                fullfile(folder, "bse.log"))), ...
                "mpirun|-n,4,bse,2,2");
            restored = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaRun. ...
                from_dict(gw.as_dict());
            testCase.verifyEqual(restored.grid, [2, 2, 2]);
            decoded = kssolv.analysis.matgenlab.util.decode(gw.toJSON());
            testCase.verifyClass(decoded, ...
                "kssolv.analysis.matgenlab.io.fiesta.FiestaRun");

            invalid = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaRun( ...
                folder, 2, "bad.log", @runnerExecutor);
            testCase.verifyError(@() invalid.run(), ...
                "KSSOLV:Matgenlab:Fiesta:GridSize");
            failed = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaRun( ...
                folder, [1, 1, 1], "bad.log", @failedExecutor);
            testCase.verifyError(@() failed.run(), ...
                "KSSOLV:Matgenlab:Fiesta:ExecutorFailed");
            clear cleanup
        end
    end
end

function input = methaneInput()
coordinates = [0, 0, 0; 0, 0, 1.089; ...
    1.026719, 0, -.363; -.51336, -.889165, -.363; ...
    -.51336, .889165, -.363];
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    {"C", "H", "H", "H", "H"}, coordinates);
input = kssolv.analysis.matgenlab.io.fiesta.FiestaInput(molecule);
end

function value = frozenCellInput()
value = strjoin([ ...
    "# number of atoms and species", "   5    2", ...
    "# number of valence bands", "    5", ...
    "# number of points and spacing in eV for correlation grid", ...
    "    14    0.500", ...
    "# relire=1 ou recalculer=0 Exc DFT", "    1", ...
    "# number of COHSEX corrected occp and unoccp bands: C=COHSEX  H=HF", ...
    "    0    0   C", ...
    "# number of COHSEX iter, scf on wfns, mixing coeff; V=RI-V  I=RI-D", ...
    "    0   V       0       0.500", ...
    "# number of GW corrected occp and unoccp bands", ...
    "   10   10", "# number of GW iterations", "    3", ...
    "# dumping for BSE and TDDFT", "    1    0", ...
    "# number of occp. and virtual bands of BSE: nocore and up to 40 eVs", ...
    "    21   382", ...
    "# number of excitations needed and number of iterations", ...
    "    1   50", "# list of symbols in order", "C", "H", ...
    "# scaling factor", "    1.000", ...
    "# atoms x,y,z cartesian .. will be multiplied by scale", ...
    " 0.0 0.0 0.0 1", " 0.0 0.0 1.089 2", ...
    " 1.026719 0.0 -0.363 2", ...
    " -0.51336 -0.889165 -0.363 2", ...
    " -0.51336 0.889165 -0.363 2"], newline) + ...
    newline + "            ";
end

function value = frozenSystemInfo()
value = "['=========================================', " + ...
    "'Reading infos on system:', '', " + ...
    "' Number of atoms = 5.0 ; number of species = 2', " + ...
    "' Number of valence bands = 5', " + ...
    "' Sigma grid specs: n_grid = 14 ;  dE_grid = 0.500 (eV)', " + ...
    "' Exchange and correlation energy read from Vxcpsi.mat', " + ...
    "' Correcting  0 valence bands and  0 conduction bands at COHSEX level', " + ...
    "' Performing   0 diagonal COHSEX iterations', " + ...
    "' Using resolution of identity : V', " + ...
    "' Correcting  10 valence bands and 10 conduction bands at GW level', " + ...
    "' Performing   3 GW iterations', " + ...
    "' Dumping data for BSE treatment', '', " + ...
    "' Atoms in cell cartesian A:', ' 0.0 0.0 0.0 1', " + ...
    "' 0.0 0.0 1.089 2', ' 1.026719 0.0 -0.363 2', " + ...
    "' -0.51336 -0.889165 -0.363 2', " + ...
    "' -0.51336 0.889165 -0.363 2', " + ...
    "'=========================================']";
end

function path = fiestaFixture(name)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "+fiesta", name);
end

function output = nwchemExecutor(program, commandArguments, ~)
assert(program == "NWCHEM2FIESTA");
assert(isequal(commandArguments, ...
    ["methane.nw", "methane.nwout", "methane.movecs"]));
output = struct("stdout", "converted", "status", 0);
end

function output = runnerExecutor(program, commandArguments, ~)
output = program + "|" + strjoin(commandArguments, ",");
end

function output = failedExecutor(~, ~, ~)
output = struct("stdout", "failed", "status", 7);
end

function writeText(path, value)
[identifier, message] = fopen(path, "w", "n", "UTF-8");
assert(identifier >= 0, message);
cleanup = onCleanup(@() fclose(identifier));
fwrite(identifier, char(string(value)), "char");
clear cleanup
end

function deleteFiles(paths)
for path = string(paths)
    if isfile(path), delete(path); end
end
end

function removeTree(path)
if isfolder(path), rmdir(path, "s"); end
end

function names = metadataNames(values)
if iscell(values), values = [values{:}]; end
names = string({values.Name});
end
