classdef GaussianInventoryTest < matlab.unittest.TestCase
    %GAUSSIANINVENTORYTEST Frozen pymatgen-core Gaussian parity.

    properties
        fixtureRoot
        oracle
        methane
    end

    methods (TestMethodSetup)
        function prepare(testCase)
            testCase.fixtureRoot=fullfile(pwd,"+kssolv","+analysis", ...
                "+matgenlab","+test","+io","+fixtures","+gaussian");
            testCase.oracle=jsondecode(fileread(fullfile(pwd,"dev", ...
                "matgenlab","oracles","gaussian_2026.7.24.json")));
            coordinates=[0,0,0;0,0,1.089;1.026719,0,-.363; ...
                -.51336,-.889165,-.363;-.51336,.889165,-.363];
            testCase.methane=kssolv.analysis.matgenlab.core.Molecule( ...
                {"C","H","H","H","H"},coordinates);
        end
    end

    methods (Test)
        function frozenInventoryHasAllTwentyTwoApis(testCase)
            inputMeta=meta.class.fromName( ...
                "kssolv.analysis.matgenlab.io.GaussianInput");
            outputMeta=meta.class.fromName( ...
                "kssolv.analysis.matgenlab.io.GaussianOutput");
            testCase.verifyNotEmpty(inputMeta);
            testCase.verifyNotEmpty(outputMeta);
            inputMethods=string({inputMeta.MethodList.Name});
            outputMethods=string({outputMeta.MethodList.Name});
            testCase.verifyTrue(all(ismember( ...
                ["from_str","from_file","get_zmatrix", ...
                "get_cart_coords","to_str","write_file", ...
                "as_dict","from_dict"],inputMethods)));
            testCase.verifyTrue(all(ismember( ...
                ["as_dict","read_scan","get_scan_plot", ...
                "save_scan_plot","read_excitation_energies", ...
                "get_spectre_plot","save_spectre_plot","to_input"], ...
                outputMethods)));
            testCase.verifyNotEmpty(which( ...
                "kssolv.analysis.matgenlab.io.read_route_line"));
            inventory=readtable(fullfile(pwd,"dev","matgenlab", ...
                "inventory","api.csv"),TextType="string");
            rows=inventory.module=="pymatgen.io.gaussian";
            testCase.verifyEqual(nnz(rows),22);
            testCase.verifyTrue(all(inventory.source(rows)=="pymatgen-core"));
            testCase.verifyEqual(string(testCase.oracle.provenance.tag), ...
                "v2026.7.24");
        end

        function routeAndInputSerializationMatchOracle(testCase)
            route=containers.Map({'SP','SCF'},{'','Tight'});
            inputParameters=containers.Map({'EPS'},{12});
            input=kssolv.analysis.matgenlab.io.GaussianInput( ...
                testCase.methane,[],[],"","HF","6-31G(d)", ...
                route,inputParameters);
            expected=testCase.oracle.methane_input;
            testCase.verifyEqual(input.molecule,testCase.methane);
            testCase.verifyEqual(input.get_zmatrix(), ...
                string(expected.zmatrix));
            testCase.verifyEqual(input.get_cart_coords(), ...
                string(expected.cartesian));
            testCase.verifyEqual(input.to_str(false), ...
                string(expected.text_zmatrix));
            testCase.verifyEqual(input.to_str(true), ...
                string(expected.text_cartesian));

            for index=1:numel(testCase.oracle.route_cases)
                item=testCase.oracle.route_cases(index);
                [functional,basis,parameters,dieze]= ...
                    kssolv.analysis.matgenlab.io.read_route_line( ...
                    item.input);
                testCase.verifyEqual(string(functional), ...
                    optionalString(item.functional));
                testCase.verifyEqual(string(basis), ...
                    optionalString(item.basis_set));
                testCase.verifyEqual(string(dieze), ...
                    optionalString(item.dieze_tag));
                testCase.verifyEqual(double(parameters.Count), ...
                    numel(fieldnames(item.parameters)));
            end
        end

        function officialInputsRoundTripWriteAndErrors(testCase)
            cysteine=kssolv.analysis.matgenlab.io.GaussianInput. ...
                from_file(fullfile(testCase.fixtureRoot,"l-cysteine.inp"));
            expected=testCase.oracle.l_cysteine;
            testCase.verifyEqual(cysteine.molecule.formula, ...
                string(expected.formula));
            testCase.verifyEqual(string(cysteine.functional), ...
                string(expected.functional));
            testCase.verifyEqual(string(cysteine.basis_set), ...
                string(expected.basis_set));
            testCase.verifyEqual(double( ...
                cysteine.route_parameters.Count),3);
            testCase.verifyTrue(isa(cysteine.route_parameters("opt"), ...
                "containers.Map"));
            testCase.verifyTrue(isKey( ...
                cysteine.route_parameters("opt"),"Z-Matrix"));

            methyl=kssolv.analysis.matgenlab.io.GaussianInput. ...
                from_file(fullfile(testCase.fixtureRoot, ...
                "MethylPyrrolidine_drawn.gjf"));
            testCase.verifyEqual(methyl.molecule.formula,"H11 C5 N1");
            testCase.verifyEqual(string( ...
                methyl.route_parameters("geom")),"connectivity");
            rebuilt=kssolv.analysis.matgenlab.io.GaussianInput. ...
                from_dict(cysteine.as_dict());
            testCase.verifyEqual(rebuilt.molecule.cart_coords, ...
                cysteine.molecule.cart_coords,AbsTol=2e-10);

            temporary=tempname+".gjf";
            cleanup=onCleanup(@()deleteIfExists(temporary));
            cysteine.write_file(temporary,true);
            reparsed=kssolv.analysis.matgenlab.io.GaussianInput. ...
                from_file(temporary);
            testCase.verifyEqual(reparsed.molecule.cart_coords, ...
                cysteine.molecule.cart_coords,AbsTol=1e-6);
            clear cleanup

            charged=kssolv.analysis.matgenlab.core.Molecule( ...
                testCase.methane.species,testCase.methane.cart_coords, ...
                "charge",-1);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.GaussianInput( ...
                charged,[],1), ...
                "KSSOLV:Matgenlab:GaussianInput:ChargeSpin");
        end

        function methaneOutputAndConversionMatchOracle(testCase)
            output=kssolv.analysis.matgenlab.io.GaussianOutput( ...
                fullfile(testCase.fixtureRoot,"methane.log"));
            expected=testCase.oracle.methane_output;
            testCase.verifyTrue(output.properly_terminated);
            testCase.verifyEqual(output.energies, ...
                reshape(expected.energies,1,[]),AbsTol=1e-12);
            testCase.verifyEqual(output.final_energy, ...
                expected.energies(end),AbsTol=1e-12);
            testCase.verifyEqual(numel(output.structures), ...
                expected.structure_count);
            testCase.verifyEqual(output.final_structure.cart_coords, ...
                expected.final_coords,AbsTol=1e-12);
            testCase.verifyEqual(output.cart_forces{1}(6), ...
                expected.force_samples(1),AbsTol=1e-14);
            testCase.verifyEqual(output.cart_forces{3}(end), ...
                expected.force_samples(3),AbsTol=1e-14);
            testCase.verifyEqual(output.eigenvalues.up(end), ...
                expected.eigen_last,AbsTol=1e-12);
            testCase.verifyEqual(output.resumes{1},expected.resume);
            dictionary=output.as_dict();
            testCase.verifyEqual(dictionary.output.final_energy, ...
                output.final_energy);
            input=output.to_input();
            testCase.verifyEqual(input.functional,"hf");
            testCase.verifyEqual(input.basis_set,"3-21G");
            testCase.verifyEqual(input.molecule.cart_coords, ...
                output.final_structure.cart_coords);
        end

        function frequenciesHessianBondOrdersAndPopMatchOracle(testCase)
            coupled=kssolv.analysis.matgenlab.io.GaussianOutput( ...
                fullfile(testCase.fixtureRoot,"CH2O_CO2.log"));
            expected=testCase.oracle.frequencies;
            testCase.verifyEqual(cellfun(@numel,coupled.frequencies), ...
                reshape(expected.group_lengths,1,[]));
            testCase.verifyEqual(coupled.frequencies{1}(1).frequency, ...
                expected.first.frequency,AbsTol=1e-12);
            testCase.verifyEqual(coupled.frequencies{1}(1).symmetry, ...
                string(expected.first.symmetry));
            testCase.verifyEqual(coupled.frequencies{1}(2).mode, ...
                reshape(expected.mode_2.mode,1,[]),AbsTol=1e-12);
            testCase.verifyEqual(coupled.frequencies{2}(4).mode, ...
                reshape(expected.mode_last.mode,1,[]),AbsTol=1e-12);

            vibration=kssolv.analysis.matgenlab.io.GaussianOutput( ...
                fullfile(testCase.fixtureRoot,"H2O_gau_vib.out"));
            testCase.verifyEqual(vibration.hessian(1,1), ...
                testCase.oracle.h2o_vib.hessian_first,AbsTol=1e-12);
            testCase.verifyEqual(vibration.hessian(9,:), ...
                reshape(testCase.oracle.h2o_vib.hessian_last_row,1,[]), ...
                AbsTol=1e-12);
            testCase.verifyEqual(vibration.bond_orders(1,2),.7582, ...
                AbsTol=1e-12);
            testCase.verifyEqual(vibration.bond_orders(2,3),.0002, ...
                AbsTol=1e-12);

            population=kssolv.analysis.matgenlab.io.GaussianOutput( ...
                fullfile(testCase.fixtureRoot,"H2O_gau.out"));
            testCase.verifyEqual(population.eigenvalues.down, ...
                reshape(testCase.oracle.h2o_mo.down_eigenvalues,1,[]), ...
                AbsTol=1e-12);
            testCase.verifyEqual(population.eigenvectors.up(:,6), ...
                testCase.oracle.h2o_mo.eigenvector_col6,AbsTol=1e-12);
            testCase.verifyEqual(population.atom_basis_labels{1}, ...
                reshape(cellstr(string( ...
                testCase.oracle.h2o_mo.atom_basis_labels{1})),1,[]));
            testCase.verifyEqual( ...
                population.molecular_orbital.down{6}{1}("1S"),-.08771, ...
                AbsTol=1e-12);
        end

        function scansAndPlotsMatchOracle(testCase)
            output=kssolv.analysis.matgenlab.io.GaussianOutput( ...
                fullfile(testCase.fixtureRoot,"so2_scan.log"));
            scan=output.read_scan();
            testCase.verifyEqual(scan.energies, ...
                reshape(testCase.oracle.scan.energies,1,[]), ...
                AbsTol=1e-12);
            testCase.verifyEqual(scan.coords("DSO"), ...
                reshape(testCase.oracle.scan.coords.DSO,1,[]), ...
                AbsTol=1e-12);
            axesHandle=output.get_scan_plot("DSO");
            testCase.addTeardown(@()delete(ancestor(axesHandle,"figure")));
            testCase.verifyEqual(axesHandle.UserData.x,scan.coords("DSO"));
            temporary=tempname+".png";
            cleanup=onCleanup(@()deleteIfExists(temporary));
            output.save_scan_plot(temporary,"png","DSO");
            testCase.verifyTrue(isfile(temporary));
            clear cleanup
        end

        function excitationsAndSpectrumMatchOracle(testCase)
            output=kssolv.analysis.matgenlab.io.GaussianOutput( ...
                fullfile(testCase.fixtureRoot,"so2_td.log"));
            transitions=output.read_excitation_energies();
            testCase.verifyEqual(transitions, ...
                testCase.oracle.td.transitions,AbsTol=1e-12);
            [spectrum,axesHandle]=output.get_spectre_plot();
            testCase.addTeardown(@()delete(ancestor(axesHandle,"figure")));
            expected=testCase.oracle.td.spectrum;
            indices=[1,floor(numel(spectrum.energies)/2)+1, ...
                numel(spectrum.energies)];
            testCase.verifyEqual(numel(spectrum.energies), ...
                expected.energy_count);
            testCase.verifyEqual(spectrum.energies(indices), ...
                reshape(expected.energy_samples,1,[]),AbsTol=1e-12);
            testCase.verifyEqual(spectrum.xas(indices), ...
                reshape(expected.xas_samples,1,[]),AbsTol=1e-12);
            temporary=tempname+".png";
            cleanup=onCleanup(@()deleteIfExists(temporary));
            output.save_spectre_plot(temporary,"png");
            testCase.verifyTrue(isfile(temporary));
            clear cleanup
        end

        function registryRoutesInputsAndOutputs(testCase)
            registry=kssolv.analysis.matgenlab.io. ...
                FormatRegistryStore.molecules(true);
            inputFormat=registry("gaussian");
            testCase.verifyTrue(all([~isempty(inputFormat.read_str), ...
                ~isempty(inputFormat.read_file), ...
                ~isempty(inputFormat.write_str), ...
                ~isempty(inputFormat.write_file)]));
            molecule=inputFormat.read_file(fullfile( ...
                testCase.fixtureRoot,"l-cysteine.inp"));
            testCase.verifyEqual(molecule.formula,"H7 C3 S1 N1 O2");
            outputFormat=registry("gaussian-out");
            molecule=outputFormat.read_file(fullfile( ...
                testCase.fixtureRoot,"methane.log"));
            testCase.verifyEqual(molecule.formula,"H4 C1");
        end

        function invalidOutputInputsHaveStableErrors(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.GaussianOutput( ...
                tempname+".log"), ...
                "KSSOLV:Matgenlab:GaussianOutput:MissingFile");
            output=kssolv.analysis.matgenlab.io.GaussianOutput( ...
                fullfile(testCase.fixtureRoot,"methane.log"));
            testCase.verifyError(@()output.get_spectre_plot(), ...
                "KSSOLV:Matgenlab:GaussianOutput:NoExcitations");
            testCase.verifyError(@()output.get_scan_plot(), ...
                "KSSOLV:Matgenlab:GaussianOutput:NoScan");
        end
    end
end

function value=optionalString(input)
if isempty(input),value=missing;else,value=string(input);end
end

function deleteIfExists(path)
if isfile(path),delete(path);end
end
