classdef IcetInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function explicitBackendAndConstructorSemantics(testCase)
            kssolv.analysis.matgenlab.io.icet.IcetSQS.set_backend([]);
            structure = testCase.disorderedStructure();
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.icet.IcetSQS( ...
                structure, 2, 1, struct("x2", 5)), ...
                "KSSOLV:Matgenlab:IcetSQS:BackendRequired");
            backend = testCase.backend();
            sqs = kssolv.analysis.matgenlab.io.icet.IcetSQS( ...
                structure, 2, 2, struct("x2", 5, "x3", 3), ...
                "enumeration", struct("include_smaller_cells", false), ...
                backend = backend);
            testCase.verifyEqual(sqs.sqs_method, "enumeration");
            testCase.verifyEqual(sqs.cutoffs_list, [5, 3]);
            testCase.verifyEqual(sort(string(fieldnames(sqs.composition))), ...
                ["A"; "B"]);
            testCase.verifyEqual(sqs.sqs_vector, 0.5);
            root = fileparts(fileparts(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath")))))));
            oracle = jsondecode(fileread(fullfile(root, "dev", ...
                "matgenlab", "oracles", "icet_2026.7.24.json")));
            testCase.verifyEqual(sqs.cutoffs_list, ...
                reshape(oracle.cutoffs_list, 1, []));
            testCase.verifyEqual(sqs.composition.A("Mg"), ...
                oracle.composition.A.Mg);
            testCase.verifyEqual(sqs.composition.A("Al"), ...
                oracle.composition.A.Al);
            testCase.verifyEqual(sqs.composition.B("O"), ...
                oracle.composition.B.O);
            testCase.verifyEqual(sqs.sqs_kwargs.tol, ...
                oracle.sqs_kwargs.tol);
        end

        function enumerationObjectiveAndRun(testCase)
            sqs = kssolv.analysis.matgenlab.io.icet.IcetSQS( ...
                testCase.disorderedStructure(), 2, 2, ...
                struct("x2", 5), "enumeration", ...
                struct("tol", 1e-5), backend = testCase.backend());
            cluster = testCase.createSpace([], [], []);
            candidates = sqs.enumerate_sqs_structures(cluster);
            testCase.verifyNumElements(candidates, 2);
            scores = sort(cellfun(@(entry) entry.objective_function, ...
                candidates));
            testCase.verifyEqual(scores, [0, 0.25], "AbsTol", 1e-14);
            result = sqs.run();
            testCase.verifyClass(result, ...
                "kssolv.analysis.matgenlab.command_line.mcsqs_caller.Sqs");
            testCase.verifyEqual(result.objective_function, 0, ...
                "AbsTol", 1e-14);
            testCase.verifyEqual(result.bestsqs.num_sites, 4);
            testCase.verifyNumElements(result.allsqs, 2);
        end

        function monteCarloInstances(testCase)
            kwargs = struct("n_steps", 5, "random_seed", 19);
            sqs = kssolv.analysis.matgenlab.io.icet.IcetSQS( ...
                testCase.disorderedStructure(), 2, 3, ...
                struct("x2", 5), "monte_carlo", kwargs, ...
                backend = testCase.backend());
            candidates = sqs.monte_carlo_sqs_structures();
            testCase.verifyNumElements(candidates, 3);
            testCase.verifyTrue(all(cellfun(@(entry) ...
                entry.structure.num_sites == 4, candidates)));
            objective = sqs.get_icet_sqs_obj( ...
                candidates{1}.structure, []);
            testCase.verifyEqual(objective, 0, "AbsTol", 1e-14);
        end

        function invalidMethodAndBackendContract(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.icet.IcetSQS( ...
                testCase.disorderedStructure(), 2, 1, ...
                struct("x2", 5), "invalid", struct(), ...
                backend = testCase.backend()), ...
                "KSSOLV:Matgenlab:IcetSQS:UnknownMethod");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.icet.IcetSQS( ...
                testCase.disorderedStructure(), 2, 1, ...
                struct("x2", 5), backend = struct()), ...
                "KSSOLV:Matgenlab:IcetSQS:BackendContract");
        end
    end
    methods (Static, Access = private)
        function structure = disorderedStructure()
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                3 .* eye(3));
            species = {struct("Mg", 0.5, "Al", 0.5), "O"};
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, species, [0, 0, 0; 0.5, 0.5, 0.5]);
        end

        function value = backend()
            value = struct( ...
                "create_cluster_space", ...
                @kssolv.analysis.matgenlab.test.io. ...
                IcetInventoryTest.createSpace, ...
                "validate_concentrations", ...
                @(composition, cluster) 0.5, ...
                "get_sqs_cluster_vector", @(cluster, target) target, ...
                "get_cluster_vector", ...
                @kssolv.analysis.matgenlab.test.io. ...
                IcetInventoryTest.clusterVector, ...
                "compare_cluster_vectors", ...
                @(vector, target, cluster, options) abs(vector - target), ...
                "enumerate_structures", ...
                @kssolv.analysis.matgenlab.test.io. ...
                IcetInventoryTest.enumerate, ...
                "generate_sqs", ...
                @kssolv.analysis.matgenlab.test.io. ...
                IcetInventoryTest.generate, ...
                "describe_cluster_space", @(cluster) "fake cluster space");
        end

        function value = createSpace(atoms, cutoffs, symbols)
            value = struct("primitive_structure", atoms, ...
                "cutoffs", cutoffs, "chemical_symbols", {symbols});
        end

        function value = clusterVector(~, atoms)
            if isa(atoms, "kssolv.analysis.matgenlab.core.IStructure")
                symbols = string(cellfun(@(species) char(species.symbol), ...
                    atoms.species, "UniformOutput", false));
            else
                symbols = string(atoms.symbols);
            end
            value = nnz(symbols == "Mg") / numel(symbols);
        end

        function structures = enumerate(~, sizes, ~, ~)
            structures = {};
            for scale = sizes
                structures{end + 1} = ...
                    kssolv.analysis.matgenlab.test.io. ...
                    IcetInventoryTest.orderedCandidate( ...
                    scale, 2); %#ok<AGROW>
                structures{end + 1} = ...
                    kssolv.analysis.matgenlab.test.io. ...
                    IcetInventoryTest.orderedCandidate( ...
                    scale, 1); %#ok<AGROW>
                structures{end + 1} = ...
                    kssolv.analysis.matgenlab.test.io. ...
                    IcetInventoryTest.orderedCandidate( ...
                    scale, 3); %#ok<AGROW>
            end
        end

        function structure = generate(~, scaling, ~, ~)
            structure = kssolv.analysis.matgenlab.test.io. ...
                IcetInventoryTest.orderedCandidate(scaling, scaling);
        end

        function structure = orderedCandidate(scaling, magnesium)
            count = 2 * scaling;
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                diag([3 * scaling, 3, 3]));
            symbols = [repmat({"Mg"}, 1, magnesium), ...
                repmat({"Al"}, 1, count - magnesium)];
            coordinates = zeros(count, 3);
            coordinates(:, 1) = (0:(count - 1)) ./ count;
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, symbols, coordinates);
        end
    end
end
