classdef JDFTXOracleParityTest < matlab.unittest.TestCase
    %JDFTXORACLEPARITYTEST Frozen Python-oracle numerical parity checks.
    methods (Test)
        function infileParity(testCase)
            testCase.assumeTrue(oracleAvailable());
            path = fullfile(jdftxFixtureRoot(), ...
                "test_jdftx_in_files", "input-simple1.in");
            reference = oracle("pymatgen.io.jdftx.inputs", ...
                "JDFTXInfile", "from_file", {path}, ...
                [indexOperation("elec-cutoff"), indexOperation("ion"), ...
                indexOperation("lattice")]);
            value = kssolv.analysis.matgenlab.io.jdftx.JDFTXInfile. ...
                from_file(path);
            testCase.verifyEqual(value.get("elec-cutoff"), ...
                [reference.results{1}.Ecut, ...
                reference.results{1}.EcutRho], AbsTol=1e-12);
            testCase.verifyEqual(numel(value.get("ion")), ...
                numel(reference.results{2}));
            testCase.verifyEqual(value.get("lattice"), ...
                dictLattice(reference.results{3}), AbsTol=1e-12);
        end

        function singlePointOutfileParity(testCase)
            testCase.assumeTrue(oracleAvailable());
            path = fullfile(jdftxFixtureRoot(), ...
                "test_jdftx_out_files", "example_sp.out");
            names = ["nspin", "broadening", "pwcut", "rhocut", ...
                "fftgrid", "kgrid", "efermi", "egap", "total_electrons", ...
                "nbands", "lattice", "atom_coords", "ecomponents"];
            reference = oracle("pymatgen.io.jdftx.outputs", ...
                "JDFTXOutfile", "from_file", {path}, ...
                getOperations(names));
            value = kssolv.analysis.matgenlab.io.jdftx.JDFTXOutfile. ...
                from_file(path);
            for idx = 1:10
                expected = reference.results{idx};
                actual = value.(names(idx));
                if isnumeric(actual) && isvector(actual) && ...
                        isnumeric(expected)
                    expected = reshape(expected, size(actual));
                end
                testCase.verifyEqual(actual, expected, AbsTol=1e-9);
            end
            testCase.verifyEqual(value.lattice, ...
                reference.results{11}, AbsTol=1e-10);
            testCase.verifyEqual(value.atom_coords, ...
                reference.results{12}, AbsTol=1e-9);
            testCase.verifyEqual(value.ecomponents.F, ...
                reference.results{13}.F, AbsTol=1e-8);
        end

        function optimizationOutfileParity(testCase)
            testCase.assumeTrue(oracleAvailable());
            root = fullfile(jdftxFixtureRoot(), "test_jdftx_out_files");
            for name = ["example_latmin.out", "example_ionmin.out"]
                path = fullfile(root, name);
                fields = ["nspin", "efermi", "egap", "is_metal", ...
                    "total_electrons", "nbands", "nat", "t_s", ...
                    "geom_opt_type", "converged"];
                reference = oracle("pymatgen.io.jdftx.outputs", ...
                    "JDFTXOutfile", "from_file", {path}, ...
                    getOperations(fields));
                value = kssolv.analysis.matgenlab.io.jdftx. ...
                    JDFTXOutfile.from_file(path);
                for idx = 1:numel(fields)
                    actual = value.(fields(idx));
                    expected = reference.results{idx};
                    if isstring(actual)
                        expected = string(expected);
                    end
                    testCase.verifyEqual(actual, expected, AbsTol=1e-8);
                end
            end
        end

        function bandDumpParity(testCase)
            testCase.assumeTrue(oracleAvailable());
            path = fullfile(jdftxFixtureRoot(), ...
                "test_jdftx_calc_dirs", "N2");
            request = struct("module", "pymatgen.io.jdftx.outputs", ...
                "symbol", "JDFTXOutputs", ...
                "construct", struct("method", "from_calc_dir", ...
                "args", {{path}}, "kwargs", ...
                struct("store_vars", {{ ...
                "bandProjections", "eigenvals", "kpts"}})), ...
                "operations", [getOperation("bandProjections"), ...
                getOperation("eigenvals"), getOperation("kpts"), ...
                getOperation("orb_label_list")]);
            reference = kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            value = kssolv.analysis.matgenlab.io.jdftx.JDFTXOutputs. ...
                from_calc_dir(path, store_vars = ...
                {"bandProjections", "eigenvals", "kpts"});
            complex_data = reference.results{1}.matgenlab_complex;
            expected = complex(complex_data.real, complex_data.imag);
            testCase.verifyEqual(value.bandProjections, ...
                single(expected), AbsTol=1e-7);
            testCase.verifyEqual(value.eigenvals, ...
                reference.results{2}, AbsTol=1e-9);
            testCase.verifyEqual(value.kpts, ...
                reference.results{3}, AbsTol=1e-12);
            testCase.verifyEqual(value.orb_label_list, ...
                string(reference.results{4}));
        end
    end
end

function response = oracle(module, symbol, method, args, operations)
request = struct("module", module, "symbol", symbol, ...
    "construct", struct("method", method, "args", {args}), ...
    "operations", operations);
response = kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
    execute(request);
end

function values = getOperations(names)
values = repmat(getOperation(""), 1, numel(names));
for idx = 1:numel(names)
    values(idx) = getOperation(names(idx));
end
end

function value = getOperation(name)
value = struct("kind", "get", "name", name);
end

function value = indexOperation(key)
value = struct("kind", "index", "key", key);
end

function value = oracleAvailable()
value = kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable();
end

function lattice = dictLattice(value)
lattice = zeros(3);
for row = 0:2
    for column = 0:2
        lattice(row + 1, column + 1) = ...
            value.("R" + row + column);
    end
end
end

function root = jdftxFixtureRoot()
root = fullfile(KSSOLV_Toolbox.RootDirectory, "+kssolv", "+analysis", ...
    "+matgenlab", "+test", "+io", "+fixtures", "+jdftx");
end
