classdef LMTOTest < matlab.unittest.TestCase
    methods (Test)
        function ctrlStructureMatchesOfficialPoscar(testCase)
            ctrl = kssolv.analysis.matgenlab.io.lmto.LMTOCtrl. ...
                from_file(lmtoFixture("CTRL.BiSe"));
            poscar = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_file(lmtoFixture("POSCAR.BiSe"));
            matcher = ...
                kssolv.analysis.matgenlab.core.StructureMatcher();
            testCase.verifyTrue(matcher.fit( ...
                ctrl.structure, poscar.structure));
            registryRoundTrip = ...
                kssolv.analysis.matgenlab.core.Structure.from_str( ...
                    ctrl.get_str(), "lmto");
            testCase.verifyTrue(matcher.fit( ...
                registryRoundTrip, ctrl.structure));
            testCase.verifyEqual(ctrl.header, "Bi6Se6, hexagonal");
            reconstructed = ...
                kssolv.analysis.matgenlab.io.lmto.LMTOCtrl. ...
                from_dict(ctrl.as_dict());
            testCase.verifyTrue(reconstructed == ctrl);
        end

        function ctrlReadWriteRoundTrip(testCase)
            ctrl = kssolv.analysis.matgenlab.io.lmto.LMTOCtrl. ...
                from_file(lmtoFixture("CTRL.BiSe"));
            text = ctrl.get_str();
            restored = ...
                kssolv.analysis.matgenlab.io.lmto.LMTOCtrl. ...
                from_str(text);
            matcher = ...
                kssolv.analysis.matgenlab.core.StructureMatcher();
            testCase.verifyTrue(matcher.fit( ...
                restored.structure, ctrl.structure));
            path = string(tempname) + ".gz";
            cleanup = onCleanup(@() deleteIfPresent(path));
            ctrl.write_file(path, "sigfigs", 8);
            restored = ...
                kssolv.analysis.matgenlab.io.lmto.LMTOCtrl. ...
                from_file(path);
            testCase.verifyTrue(matcher.fit( ...
                restored.structure, ctrl.structure));
            clear cleanup
        end

        function coplAttributesMatchFrozenOracle(testCase)
            bise = kssolv.analysis.matgenlab.io.lmto.LMTOCopl( ...
                lmtoFixture("COPL.BiSe"));
            iron = kssolv.analysis.matgenlab.io.lmto.LMTOCopl( ...
                lmtoFixture("COPL"));
            testCase.verifyFalse(bise.is_spin_polarized);
            testCase.verifyTrue(iron.is_spin_polarized);
            testCase.verifyEqual(numel(bise.energies), 801);
            testCase.verifyEqual(numel(iron.energies), 801);
            testCase.verifyEqual(double(bise.cohp_data.Count), 7);
            testCase.verifyEqual(double(iron.cohp_data.Count), 8);
            testCase.verifyEqual(bise.efermi, -0.17223, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(iron.efermi, -0.085683, ...
                AbsTol = 1e-12);
            record = bise.cohp_data("Bi1-Se7");
            testCase.verifyEqual(record.length, 2.882);
            testCase.verifyEqual(record.sites, [0, 6]);
            expectedLabels = ["Fe1-Fe1", compose("Fe1-Fe1-%d", 1:7)];
            testCase.verifyEqual(sort(string(iron.cohp_data.keys)), ...
                sort(expectedLabels));
        end

        function coplElectronVoltConversionMatchesOracle(testCase)
            rydberg = kssolv.analysis.matgenlab.io.lmto.LMTOCopl( ...
                lmtoFixture("COPL.BiSe"));
            electronVolt = ...
                kssolv.analysis.matgenlab.io.lmto.LMTOCopl( ...
                lmtoFixture("COPL.BiSe"), true);
            testCase.verifyEqual(electronVolt.efermi, ...
                -2.3433, AbsTol = 1e-12);
            conversion = ...
                kssolv.analysis.matgenlab.core.Ry_to_eV();
            expected = arrayfun(@(value) ...
                kssolv.analysis.matgenlab.util. ...
                round_to_sigfigs(value * conversion, 5), ...
                rydberg.energies);
            testCase.verifyEqual(electronVolt.energies, ...
                expected, AbsTol = 1e-12);
            source = rydberg.cohp_data("Bi1-Se7").ICOHP.up;
            expected = arrayfun(@(value) ...
                kssolv.analysis.matgenlab.util. ...
                round_to_sigfigs(value * conversion, 5), source);
            testCase.verifyEqual( ...
                electronVolt.cohp_data("Bi1-Se7").ICOHP.up, ...
                expected, AbsTol = 1e-12);
        end
    end
end

function path = lmtoFixture(name)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "+lmto", name);
end

function deleteIfPresent(path)
if isfile(path), delete(path); end
end
