classdef MultiwfnTest < matlab.unittest.TestCase
    methods (Test)
        function individualCriticalPointsMatchFrozenOracle(testCase)
            [name, descriptor] = parseFixture("cp_just_atom.txt");
            testCase.verifyEqual(name, "2_N");
            testCase.verifyEqual(descriptor.cp_num, 102);
            testCase.verifyEqual(descriptor.element, "N");
            testCase.verifyEqual(descriptor.number, "2");
            testCase.verifyEqual(descriptor.pos_ang, ...
                [1.626104042116, -1.859508691395, ...
                -0.405402516863], AbsTol = 1e-12);
            testCase.verifyEqual(descriptor.density_total, ...
                183.1401128, AbsTol = 1e-9);

            [name, descriptor] = parseFixture("cp_unknown_atom.txt");
            testCase.verifyEqual(name, "142_Unknown");
            testCase.verifyEqual(descriptor.number, "Unknown");
            testCase.verifyEqual(descriptor.density_alpha, ...
                8.066360869, AbsTol = 1e-10);
            testCase.verifyEqual(descriptor.spin_density, 0);

            [name, descriptor] = parseFixture("cp_just_bond.txt");
            testCase.verifyEqual(name, "121_bond");
            testCase.verifyEqual(descriptor.Lagrangian_K, ...
                426.4263555, AbsTol = 1e-9);
            testCase.verifyEqual(descriptor.lap_e_density, ...
                1278.89597, AbsTol = 1e-8);

            [name, descriptor] = parseFixture("cp_just_ring.txt");
            testCase.verifyEqual(name, "123_ring");
            testCase.verifyEqual(descriptor.e_loc_func, ...
                0.4201012445, AbsTol = 1e-10);
            testCase.verifyEqual(descriptor.esp_total, ...
                96.1572999, AbsTol = 1e-8);

            [name, descriptor] = parseFixture("cp_just_cage.txt");
            testCase.verifyEqual(name, "56_cage");
            testCase.verifyEqual(descriptor.grad_norm, ...
                7.920799975e-18, AbsTol = 1e-28);
            testCase.verifyEqual(descriptor.eig_hess, ...
                0.0158312412724, AbsTol = 1e-12);

            [name, descriptor] = parseFixture("cp_fake_type.txt");
            testCase.verifyEmpty(name);
            testCase.verifyEmpty(fieldnames(descriptor));
        end

        function allCriticalPointsParseAndSeparate(testCase)
            descriptors = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                get_qtaim_descs(multiwfnFixture("CPprop_all.txt"));
            testCase.verifyEqual(double(descriptors.Count), 181);
            numbers = zeros(1, descriptors.Count);
            keys = descriptors.keys;
            for index = 1:numel(keys)
                value = descriptors(keys{index});
                numbers(index) = value.cp_num;
            end
            testCase.verifyEqual(sort(numbers), 1:181);
            organized = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                separate_cps_by_type(descriptors);
            testCase.verifyEqual(double(organized.atom.Count), 56);
            testCase.verifyEqual(double(organized.bond.Count), 90);
            testCase.verifyEqual(double(organized.ring.Count), 28);
            testCase.verifyEqual(double(organized.cage.Count), 3);
        end

        function atomMatchingUsesNameThenDistance(testCase)
            molecule = moleculeFixture();
            normal = separatedFixture("CPprop_all.txt");
            fudged = separatedFixture("CPprop_fudged_nuclei.txt");
            [name, descriptor] = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                match_atom_cp(molecule, 1, normal.atom);
            testCase.verifyEqual(name, "1_Sm");
            testCase.verifyEqual(descriptor.element, "Sm");
            [name, ~] = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                match_atom_cp(molecule, 1, fudged.atom);
            testCase.verifyEqual(name, "78_Sm");
            [name, descriptor] = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                match_atom_cp(molecule, 56, fudged.atom);
            testCase.verifyEmpty(name);
            testCase.verifyEmpty(fieldnames(descriptor));
            [mapping, missing] = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                map_atoms_cps(molecule, fudged.atom);
            testCase.verifyEqual(double(mapping.Count), 56);
            testCase.verifyEqual(mapping(1).element, "Sm");
            testCase.verifyEqual(missing, 56);
        end

        function topologyLinkingMatchesFrozenOracle(testCase)
            molecule = moleculeFixture();
            organized = separatedFixture("CPprop_all.txt");
            modified = ...
                kssolv.analysis.matgenlab.io.multiwfn.add_atoms( ...
                molecule, organized, ...
                bond_atom_criterion = "distance");
            testCase.verifyEqual( ...
                sort(modified.bond("1_bond").atom_inds), [4, 15]);
            testCase.verifyEqual( ...
                sort(modified.ring("13_ring").atom_inds), ...
                [36, 37, 38, 39, 40, 41, 43, 47]);
            testCase.verifyEqual( ...
                sort(string(modified.ring( ...
                "13_ring").bond_names)), ...
                sort(["11_bond", "23_bond", "27_bond", ...
                "28_bond", "3_bond", "5_bond", "8_bond"]));
            testCase.verifyEqual( ...
                sort(modified.cage("67_cage").atom_inds), ...
                [1, 21, 23, 24, 25, 26, 28, 51, 52, 53, 56]);
            testCase.verifyEqual( ...
                sort(string(modified.cage( ...
                "67_cage").ring_names)), ...
                sort(["62_ring", "66_ring", "70_ring"]));

            [mapped, ~] = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                map_atoms_cps(molecule, organized.atom);
            organized.atom = mapped;
            qtaim = ...
                kssolv.analysis.matgenlab.io.multiwfn.add_atoms( ...
                molecule, organized, ...
                bond_atom_criterion = "qtaim");
            testCase.verifyEqual(double(qtaim.bond.Count), 63);
            testCase.verifyEqual(qtaim.bond("9_bond").atom_inds, ...
                [3, 44]);
            combined = ...
                kssolv.analysis.matgenlab.io.multiwfn.add_atoms( ...
                molecule, organized);
            testCase.verifyEqual(double(combined.bond.Count), 90);
            testCase.verifyEqual(combined.bond("9_bond").atom_inds, ...
                [3, 44]);
        end

        function endToEndProcessingMatchesOracle(testCase)
            molecule = moleculeFixture();
            descriptors = ...
                kssolv.analysis.matgenlab.io.multiwfn. ...
                process_multiwfn_qtaim(molecule, ...
                multiwfnFixture("CPprop_all.txt"));
            testCase.verifyEqual(double(descriptors.atom.Count), 56);
            testCase.verifyEqual(double(descriptors.bond.Count), 90);
            testCase.verifyEqual(double(descriptors.ring.Count), 28);
            testCase.verifyEqual(double(descriptors.cage.Count), 3);
            testCase.verifyEqual( ...
                descriptors.bond("1_bond").atom_inds, [4, 15]);
        end
    end
end

function [name, descriptor] = parseFixture(filename)
lines = splitlines(string(fileread(multiwfnFixture(filename))));
[name, descriptor] = ...
    kssolv.analysis.matgenlab.io.multiwfn.parse_cp(lines);
end

function organized = separatedFixture(filename)
descriptors = kssolv.analysis.matgenlab.io.multiwfn. ...
    get_qtaim_descs(multiwfnFixture(filename));
organized = kssolv.analysis.matgenlab.io.multiwfn. ...
    separate_cps_by_type(descriptors);
end

function molecule = moleculeFixture()
molecule = kssolv.analysis.matgenlab.core.Molecule.from_file( ...
    multiwfnFixture("mol_all.xyz"));
end

function path = multiwfnFixture(name)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "multiwfn", name);
end
