classdef NwchemInventoryTest < matlab.unittest.TestCase
    properties
        fixtureRoot
        methane
    end
    methods (TestMethodSetup)
        function prepare(testCase)
            testCase.fixtureRoot=fullfile(pwd,"+kssolv","+analysis", ...
                "+matgenlab","+test","+io","+fixtures","+nwchem");
            coordinates=[0,0,0;0,0,1.089;1.026719,0,-.363; ...
                -.51336,-.889165,-.363;-.51336,.889165,-.363];
            testCase.methane=kssolv.analysis.matgenlab.core.Molecule( ...
                {"C","H","H","H","H"},coordinates);
        end
    end
    methods (Test)
        function taskFactoriesAndMsonMatch(testCase)
            task=kssolv.analysis.matgenlab.io.nwchem.NwTask. ...
                from_molecule(testCase.methane,"dft", ...
                "basis_set",struct("C","6-311++G**", ...
                "H","6-31++G**"), ...
                "theory_directives",struct("xc","b3lyp"));
            expected="title ""H4C1 dft optimize"""+newline+ ...
                "charge 0"+newline+"basis cartesian"+newline+ ...
                " C library ""6-311++G**"""+newline+ ...
                " H library ""6-31++G**"""+newline+"end"+newline+ ...
                "dft"+newline+" xc b3lyp"+newline+"end"+newline+ ...
                "task dft optimize";
            testCase.verifyEqual(string(task),expected);
            testCase.verifyEqual(string( ...
                kssolv.analysis.matgenlab.io.nwchem.NwTask. ...
                from_dict(task.as_dict())),string(task));

            dft=kssolv.analysis.matgenlab.io.nwchem.NwTask. ...
                dft_task(testCase.methane,"charge",1, ...
                "operation","energy");
            testCase.verifyEqual(dft.spin_multiplicity,2);
            testCase.verifyEqual(dft.theory_directives.mult,2);
            cosmo=kssolv.analysis.matgenlab.io.nwchem.NwTask. ...
                dft_task(testCase.methane,"operation","energy", ...
                "basis_set","6-311++G**", ...
                "alternate_directives", ...
                struct("cosmo",struct("dielec",78)));
            testCase.verifyTrue(contains(string(cosmo), ...
                "cosmo"+newline+" dielec 78.0"+newline+"end"));
            esp=kssolv.analysis.matgenlab.io.nwchem.NwTask. ...
                esp_task(testCase.methane,"operation","", ...
                "basis_set","6-311++G**");
            testCase.verifyEqual(esp.theory,"esp");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.nwchem.NwTask( ...
                0,1,struct(),"cartesian",[],"bad"), ...
                "KSSOLV:Matgenlab:NWChem:Input");
        end

        function inputRoundTripAndOfficialFileMatch(testCase)
            first=kssolv.analysis.matgenlab.io.nwchem.NwTask. ...
                dft_task(testCase.methane,"operation","optimize", ...
                "basis_set","6-31++G*");
            second=kssolv.analysis.matgenlab.io.nwchem.NwTask. ...
                dft_task(testCase.methane,"operation","freq", ...
                "basis_set","6-31++G*");
            input=kssolv.analysis.matgenlab.io.nwchem.NwInput( ...
                testCase.methane,{first,second},[], ...
                ["units","angstroms","noautoz"],"c1", ...
                "total 1000 mb");
            text=string(input);
            testCase.verifyTrue(startsWith(text, ...
                "memory total 1000 mb"+newline+ ...
                "geometry units angstroms noautoz"+newline+ ...
                " symmetry c1"));
            parsed=kssolv.analysis.matgenlab.io.nwchem.NwInput. ...
                from_str(text);
            testCase.verifyEqual(parsed.geometry_options, ...
                ["units","angstroms","noautoz"]);
            testCase.verifyEqual(parsed.symmetry_options,"c1");
            rebuilt=kssolv.analysis.matgenlab.io.nwchem.NwInput. ...
                from_dict(input.as_dict());
            testCase.verifyEqual(string(rebuilt),text);
            temporary=string(tempname);
            cleanup=onCleanup(@()deleteIfExists(temporary));
            input.write_file(temporary);
            testCase.verifyEqual(fileread(temporary),char(text));
            clear cleanup

            official=kssolv.analysis.matgenlab.io.nwchem.NwInput. ...
                from_file(fullfile(testCase.fixtureRoot,"ch4.nw"));
            testCase.verifyEqual(numel(official.tasks),5);
            testCase.verifyEqual(official.tasks{1}.theory,"dft");
            testCase.verifyEqual(official.memory_options, ...
                "total 1000 mb stack 400 mb");
            testCase.verifyEqual(official.tasks{1}.basis_set.C,"6-31++G*");
            testCase.verifyEqual(official.tasks{end}.basis_set.C, ...
                "6-311++G**");
            testCase.verifyEqual(official.molecule.num_sites,5);
        end

        function officialEnergiesForcesAndHessianMatch(testCase)
            output=kssolv.analysis.matgenlab.io.nwchem.NwOutput( ...
                fullfile(testCase.fixtureRoot,"CH4.nwout"));
            testCase.verifyEqual(length(output),5);
            testCase.verifyEqual(output(1).charge,0);
            testCase.verifyEqual(output(5).charge,-1);
            testCase.verifyEqual(output(1).energies(end), ...
                -1102.6224491715582,AbsTol=1e-2);
            testCase.verifyEqual(output(3).energies(end), ...
                -1102.9986291578023,AbsTol=1e-3);
            testCase.verifyEqual(output(1).forces{1}(4), ...
                -.001991,AbsTol=1e-12);
            hessian=output(2).hessian;
            testCase.verifyEqual(hessian(1,1),46.0187,AbsTol=1e-10);
            testCase.verifyEqual(hessian(2,3),-1.14030e-8,AbsTol=1e-14);
            testCase.verifyEqual(hessian(3,4),26.0819,AbsTol=1e-10);
            testCase.verifyEqual(hessian(7,7),145.055,AbsTol=1e-10);
            testCase.verifyEqual(hessian(12,15),13.5078,AbsTol=1e-10);
            testCase.verifyEqual( ...
                output(5).basis_set.C.description,"6-311++G**");
        end

        function cosmoErrorsAndFrequencyModesMatch(testCase)
            cosmo=kssolv.analysis.matgenlab.io.nwchem.NwOutput( ...
                fullfile(testCase.fixtureRoot,"N2O4.nwout"));
            energy=cosmo(6).energies{1};
            testCase.verifyEqual(energy.cosmo_scf, ...
                -11156.354030653656,AbsTol=1e-3);
            testCase.verifyEqual(energy.gas_phase, ...
                -11153.374133394364,AbsTol=1e-3);
            testCase.verifyEqual(energy.sol_phase, ...
                -11156.353632962995,AbsTol=1e-2);
            testCase.verifyEqual(cosmo(1).forces{1}(5), ...
                .011948,AbsTol=1e-12);
            testCase.verifyEqual(numel(cosmo(1).forces),4);

            errorFiles={"H4C3O3_1.nwout","CH3CH2O.nwout", ...
                "C1N1Cl1_1.nwout", ...
                "anthrachinon_wfs_16_ethyl.nwout"};
            expected={"Bad convergence","Bad convergence", ...
                "autoz error","Geometry optimization failed"};
            for index=1:numel(errorFiles)
                output=kssolv.analysis.matgenlab.io.nwchem.NwOutput( ...
                    fullfile(testCase.fixtureRoot,errorFiles{index}));
                testCase.verifyTrue(output(end).has_error);
                testCase.verifyEqual(string(output(end).errors{1}), ...
                    string(expected{index}));
            end

            modes=kssolv.analysis.matgenlab.io.nwchem.NwOutput( ...
                fullfile(testCase.fixtureRoot, ...
                "anthrachinon_wfs_15_carboxyl.nwout"));
            job=modes(2);
            testCase.verifyEqual(job.frequencies{1,1},-70.47, ...
                AbsTol=1e-12);
            testCase.verifyEqual(size(job.frequencies{1,2},1),27);
            testCase.verifyEqual(job.frequencies{end,1},3696.74, ...
                AbsTol=1e-12);
            testCase.verifyEqual(job.frequencies{end,2}(end,:), ...
                [.20498,-.94542,-.00073],AbsTol=1e-12);
            testCase.verifyEqual(job.normal_frequencies{2,1}, ...
                -70.72,AbsTol=1e-12);
            testCase.verifyEqual(job.normal_frequencies{4,1}, ...
                -61.92,AbsTol=1e-12);
            testCase.verifyEqual( ...
                job.normal_frequencies{2,2}(end,:), ...
                [.00056,.00042,.06781],AbsTol=1e-12);
        end

        function tddftAndSpectrumMatch(testCase)
            output=kssolv.analysis.matgenlab.io.nwchem.NwOutput( ...
                fullfile(testCase.fixtureRoot,"phen_tddft.log"));
            roots=output.parse_tddft();
            testCase.verifyEqual(numel(roots.singlet),20);
            testCase.verifyEqual(roots.singlet{1}.energy, ...
                3.9291,AbsTol=1e-12);
            testCase.verifyEqual(roots.singlet{1}.osc_strength,0);
            testCase.verifyEqual(roots.singlet{2}.osc_strength, ...
                .00177,AbsTol=1e-12);
            spectrum=output.get_excitation_spectrum();
            testCase.verifyEqual(length(spectrum),2000);
            testCase.verifyEqual(spectrum.x(1),1.9291,AbsTol=1e-12);
            testCase.verifyEqual(spectrum.y(1),0,AbsTol=1e-15);
            testCase.verifyEqual(spectrum.y(1001), ...
                .0007423569947114812,AbsTol=1e-15);
        end

        function errorTypeIsPublic(testCase)
            value=kssolv.analysis.matgenlab.io.nwchem. ...
                NwInputError("bad");
            testCase.verifyEqual(value.identifier, ...
                'KSSOLV:Matgenlab:NWChem:Input');
        end
    end
end

function deleteIfExists(filename)
if isfile(filename),delete(filename);end
end
