classdef OptimadeInventoryTest < matlab.unittest.TestCase
    properties
        structure
        oracle
    end

    methods (TestMethodSetup)
        function prepare(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                diag([2, 3, 4]), [true, false, true]);
            species = {"Fe", "P", "O", "O", "O", "O"};
            coords = [0, 0, 0; .5, .5, .5; .25, .25, .25; ...
                .75, .25, .25; .25, .75, .25; .25, .25, .75];
            testCase.structure = kssolv.analysis.matgenlab.core. ...
                Structure(lattice, species, coords);
            testCase.oracle = jsondecode(fileread(fullfile(pwd, "dev", ...
                "matgenlab", "oracles", ...
                "io_optimade_2026.7.24.json")));
        end
    end

    methods (Test)
        function serializationMatchesFrozenOracle(testCase)
            resource = kssolv.analysis.matgenlab.io.optimade. ...
                OptimadeStructureAdapter.get_optimade_structure( ...
                testCase.structure);
            attributes = resource.attributes;
            expected = testCase.oracle;
            testCase.verifyEqual(attributes.nsites, expected.nsites);
            testCase.verifyEqual(attributes.nelements, expected.nelements);
            testCase.verifyEqual(attributes.nperiodic_dimensions, ...
                expected.nperiodic_dimensions);
            testCase.verifyEqual(attributes.dimension_types, ...
                reshape(expected.dimension_types, 1, []));
            testCase.verifyEqual(attributes.elements, ...
                reshape(string(expected.elements), 1, []));
            testCase.verifyEqual(attributes.species_at_sites, ...
                reshape(string(expected.species_at_sites), 1, []));
            testCase.verifyEqual(attributes.elements_ratios, ...
                reshape(expected.elements_ratios, 1, []), AbsTol = 1e-15);
            testCase.verifyEqual(attributes.chemical_formula_anonymous, ...
                string(expected.chemical_formula_anonymous));
            testCase.verifyEqual(attributes.chemical_formula_reduced, ...
                string(expected.chemical_formula_reduced));
            testCase.verifyEqual(attributes.chemical_formula_descriptive, ...
                string(expected.chemical_formula_descriptive));
        end

        function resourceRoundTripPreservesGeometryAndMetadata(testCase)
            resource = kssolv.analysis.matgenlab.io.optimade. ...
                OptimadeStructureAdapter.get_optimade_structure( ...
                testCase.structure);
            resource.id = "offline-test-id";
            resource.attributes.x_custom_band_gap = 2.2;
            restored = kssolv.analysis.matgenlab.io.optimade. ...
                OptimadeStructureAdapter.get_structure(resource);
            testCase.verifyEqual(restored.lattice.matrix, ...
                testCase.structure.lattice.matrix, AbsTol = 1e-14);
            testCase.verifyEqual(restored.lattice.pbc, [true, false, true]);
            testCase.verifyEqual(restored.frac_coords, ...
                testCase.structure.frac_coords, AbsTol = 1e-14);
            testCase.verifyEqual(restored.structure_properties.optimade_id, ...
                "offline-test-id");
            testCase.verifyEqual(restored.structure_properties. ...
                optimade_attributes.x_custom_band_gap, 2.2);
        end

        function attributesAndJsonInputsAreAccepted(testCase)
            resource = kssolv.analysis.matgenlab.io.optimade. ...
                OptimadeStructureAdapter.get_optimade_structure( ...
                testCase.structure);
            fromAttributes = kssolv.analysis.matgenlab.io.optimade. ...
                OptimadeStructureAdapter.get_structure(resource.attributes);
            fromJson = kssolv.analysis.matgenlab.io.optimade. ...
                OptimadeStructureAdapter.get_structure(jsonencode(resource));
            testCase.verifyEqual(fromAttributes.frac_coords, ...
                testCase.structure.frac_coords, AbsTol = 1e-14);
            testCase.verifyEqual(fromJson.frac_coords, ...
                testCase.structure.frac_coords, AbsTol = 1e-14);
        end

        function malformedInputsAreRejected(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.optimade. ...
                OptimadeStructureAdapter.get_structure("{bad json"), ...
                "KSSOLV:Matgenlab:Optimade:JSON");
        end
    end
end
