classdef PackmolInventoryTest < matlab.unittest.TestCase
    properties
        fixtureFolder
        oracle
    end

    methods (TestMethodSetup)
        function prepare(testCase)
            testCase.fixtureFolder = fullfile(pwd, "+kssolv", ...
                "+analysis", "+matgenlab", "+test", "+io", ...
                "+fixtures", "+packmol");
            testCase.oracle = jsondecode(fileread(fullfile(pwd, "dev", ...
                "matgenlab", "oracles", ...
                "packmol_2026.7.24.json")));
        end
    end

    methods (Test)
        function defaultGenerationMatchesFrozenOracle(testCase)
            inputSet = kssolv.analysis.matgenlab.io.packmol. ...
                PackmolBoxGen().get_input_set(defaultMolecules());
            expected = testCase.oracle.default;
            testCase.verifyClass(inputSet, ...
                "kssolv.analysis.matgenlab.io.packmol.PackmolSet");
            testCase.verifyEqual(inputSet.keys(), ...
                reshape(cellstr(string(expected.keys)), 1, []));
            testCase.verifyEqual(string(inputSet("packmol.inp")), ...
                string(expected.inputs.packmol_inp));
            testCase.verifyEqual(string(inputSet("packmol_water.xyz")), ...
                string(expected.inputs.packmol_water_xyz));
            testCase.verifyEqual(string(inputSet( ...
                "packmol_ethanol.xyz")), ...
                string(expected.inputs.packmol_ethanol_xyz));
            testCase.verifyEqual(inputSet.seed, expected.seed);
            testCase.verifyEqual(inputSet.tolerance, ...
                expected.tolerance);
            testCase.verifyEqual(inputSet.outputfile, ...
                string(expected.outputfile));
        end

        function explicitBoxAndControlsMatchFrozenOracle(testCase)
            generator = kssolv.analysis.matgenlab.io.packmol. ...
                PackmolBoxGen(seed = -1, ...
                control_params = struct("maxit", 0, ...
                "movebadrandom", [1, 2, 3]), ...
                inputfile = "input.in", ...
                outputfile = "output with spaces.xyz", ...
                stdoutfile = "stdout.txt");
            inputSet = generator.get_input_set( ...
                defaultMolecules(), [0, 0, 0, 20, 21, 22]);
            expected = testCase.oracle.explicit_box;
            testCase.verifyEqual(string(inputSet("input.in")), ...
                string(expected.inputs.input_in));
            testCase.verifyEqual(inputSet.inputfile, "input.in");
            testCase.verifyEqual(inputSet.outputfile, ...
                "output with spaces.xyz");
            testCase.verifyEqual(inputSet.stdoutfile, "stdout.txt");
            testCase.verifyEqual(inputSet.seed, -1);
        end

        function officialPathFixturesMatchFrozenOracle(testCase)
            molecules = { ...
                struct("name", "EMC", "number", 10, "coords", ...
                fullfile(testCase.fixtureFolder, ...
                "subdir with spaces", "EMC.xyz")), ...
                struct("name", "LiTFSi", "number", 20, "coords", ...
                fullfile(testCase.fixtureFolder, "LiTFSi.xyz"))};
            inputSet = kssolv.analysis.matgenlab.io.packmol. ...
                PackmolBoxGen().get_input_set(molecules);
            expected = testCase.oracle.from_paths;
            testCase.verifyEqual(string(inputSet("packmol.inp")), ...
                string(expected.inputs.packmol_inp));
            testCase.verifyEqual(string(inputSet("packmol_EMC.xyz")), ...
                string(expected.inputs.packmol_EMC_xyz));
            testCase.verifyEqual(string(inputSet( ...
                "packmol_LiTFSi.xyz")), ...
                string(expected.inputs.packmol_LiTFSi_xyz));
        end

        function constraintsAndAtomIndicesMatchFrozenOracle(testCase)
            molecule = defaultMolecules();
            water = molecule{1}.coords;
            item = struct("name", "water", "number", 5, ...
                "coords", water, ...
                "constraints", {{"inside sphere 0 0 0 10"}}, ...
                "atoms_constraints", {{ ...
                struct("indices", 2, "constraints", ...
                {{"inside sphere 0 0 0 5"}}), ...
                struct("indices", [0, 1], "constraints", ...
                {{"outside sphere 0 0 0 5.5"}})}});
            generator = kssolv.analysis.matgenlab.io.packmol. ...
                PackmolBoxGen(inputfile = "input.in", ...
                outputfile = "output.xyz", ...
                stdoutfile = "stdout.txt", ...
                control_params = struct("precision", 0.001));
            inputSet = generator.get_input_set({item});
            testCase.verifyEqual(string(inputSet("input.in")), ...
                string(testCase.oracle.constrained.inputs.input_in));
        end

        function invalidSpecificationsAreRejected(testCase)
            molecules = defaultMolecules();
            duplicate = molecules;
            duplicate{2}.name = "water";
            testCase.verifyError(@() makeSet(duplicate), ...
                "KSSOLV:Matgenlab:Packmol:DuplicateNames");

            mixed = molecules;
            mixed{2}.constraints = {"inside sphere 1 2 3 4"};
            testCase.verifyError(@() makeSet(mixed), ...
                "KSSOLV:Matgenlab:Packmol:MixedConstraints");

            atomOnly = molecules;
            atomOnly{1}.atoms_constraints = {struct( ...
                "indices", [0, 2], "constraints", ...
                {{"outside sphere 1 2 3 4"}})};
            testCase.verifyError(@() makeSet(atomOnly), ...
                "KSSOLV:Matgenlab:Packmol:" + ...
                "AtomConstraintsRequireIndividual");

            invalid = molecules;
            invalid{1}.constraints = {"outsdie sphere 1 2 3 4"};
            invalid{2}.constraints = {"inside sphere 1 2 3 4"};
            testCase.verifyError(@() makeSet(invalid), ...
                "KSSOLV:Matgenlab:Packmol:Constraint");

            boxed = molecules;
            boxed{1}.constraints = {"outside sphere 1 2 3 4"};
            boxed{2}.constraints = {"inside sphere 1 2 3 4"};
            testCase.verifyError(@() makeSet(boxed, ...
                [0, 0, 0, 5, 5, 5]), ...
                "KSSOLV:Matgenlab:Packmol:BoxAndConstraints");

            badAtom = boxed;
            badAtom{1}.atoms_constraints = {struct( ...
                "indices", [0, 2], "constraints", ...
                {{"outsdie sphere 1 2 3 4"}})};
            testCase.verifyError(@() makeSet(badAtom), ...
                "KSSOLV:Matgenlab:Packmol:AtomConstraint");
            testCase.verifyError(@() makeSet({struct( ...
                "name", "bad", "number", 1, "coords", 42)}), ...
                "KSSOLV:Matgenlab:Packmol:MoleculeType");
        end

        function injectedExecutionAndFailuresAreStable(testCase)
            inputSet = kssolv.analysis.matgenlab.io.packmol. ...
                PackmolBoxGen().get_input_set(defaultMolecules());
            folder = string(tempname);
            cleanup = onCleanup(@() removeFolder(folder));
            inputSet.write_input(folder);
            inputSet.run(folder, 12, @successfulExecutor);
            testCase.verifyEqual(string(fileread(fullfile( ...
                folder, "packmol.stdout"))), "PACKMOL success" + newline);
            testCase.verifyError(@() inputSet.run(folder), ...
                "KSSOLV:Matgenlab:Packmol:ExecutorRequired");
            testCase.verifyError(@() inputSet.run( ...
                folder, 1, @(~) struct("timed_out", true)), ...
                "KSSOLV:Matgenlab:Packmol:Timeout");
            testCase.verifyError(@() inputSet.run( ...
                folder, 30, @(~) struct("status", 173, ...
                "stderr", "STOP 173", "stdout", "")), ...
                "KSSOLV:Matgenlab:Packmol:ExecutionFailed");
            testCase.verifyError(@() inputSet.run( ...
                folder, 30, @(~) "ERROR Could not open file."), ...
                "KSSOLV:Matgenlab:Packmol:PathSpaces");
            testCase.verifyError(@() inputSet.run( ...
                folder, 30, @(~) "header ERROR no solution"), ...
                "KSSOLV:Matgenlab:Packmol:PackingFailed");
            clear cleanup
        end

        function fromDirectoryHasStableUnsupportedBoundary(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.packmol.PackmolSet. ...
                from_directory("."), ...
                "KSSOLV:Matgenlab:Packmol:FromDirectory");
        end
    end
end

function inputSet = makeSet(molecules, box)
if nargin < 2, box = []; end
inputSet = kssolv.analysis.matgenlab.io.packmol. ...
    PackmolBoxGen().get_input_set(molecules, box);
end

function result = successfulExecutor(request)
assert(request.command == "packmol");
assert(request.timeout == 12);
assert(request.stdin_path == "packmol.inp");
assert(contains(request.stdin, "structure packmol_water.xyz"));
result = struct("status", 0, "stdout", "PACKMOL success" + newline, ...
    "stderr", "");
end

function molecules = defaultMolecules()
ethanolCoordinates = [ ...
    0.00720, -0.56870, 0.00000; ...
    -1.28540, 0.24990, 0.00000; ...
    1.13040, 0.31470, 0.00000; ...
    0.03920, -1.19720, 0.89000; ...
    0.03920, -1.19720, -0.89000; ...
    -1.31750, 0.87840, 0.89000; ...
    -1.31750, 0.87840, -0.89000; ...
    -2.14220, -0.42390, -0.00000; ...
    1.98570, -0.13650, -0.00000];
ethanol = kssolv.analysis.matgenlab.core.Molecule( ...
    ["C", "C", "O", "H", "H", "H", "H", "H", "H"], ...
    ethanolCoordinates);
water = kssolv.analysis.matgenlab.core.Molecule( ...
    ["H", "H", "O"], [9.626, 6.787, 12.673; ...
    9.626, 8.420, 12.673; 10.203, 7.604, 12.673]);
molecules = { ...
    struct("name", "water", "number", 10, "coords", water), ...
    struct("name", "ethanol", "number", 20, "coords", ethanol)};
end

function removeFolder(folder)
if isfolder(folder), rmdir(folder, "s"); end
end
