classdef PhonopyIOTest < matlab.unittest.TestCase
    methods (Test)
        function officialBandAndDosFixtures(testCase)
            root=officialFixtureRoot(testCase);
            import kssolv.analysis.matgenlab.io.phonopy.*
            band=get_ph_bs_symm_line( ...
                fullfile(root,"io","phonopy","NaCl_band.yaml"),true);
            testCase.verifyEqual(size(band.bands),[6,204]);
            testCase.verifyEqual(size(band.eigendisplacements),[6,204,2,3]);
            testCase.verifyEqual(band.bands(2,11), ...
                0.7753555184,AbsTol=2e-10);
            testCase.verifyEqual(band.bands(6,101), ...
                5.2548379776,AbsTol=1e-12);
            testCase.verifyEqual(squeeze( ...
                band.eigendisplacements(4,51,1,:)).', ...
                [0,0.141665685328555+0.040983392623596i, ...
                -0.141665685328555-0.040983392623596i], ...
                AbsTol=1e-13);
            testCase.verifyTrue(band.has_nac);
            nac=band.get_nac_frequencies_along_dir([1,1,0]);
            testCase.verifyEqual(nac(4),4.6084532143,AbsTol=1e-12);
            dos=get_ph_dos( ...
                fullfile(root,"io","phonopy","NaCl_total_dos.dat"));
            testCase.verifyEqual(dos.densities(16), ...
                0.0001665998,AbsTol=1e-15);
            testCase.verifyEqual(dos.get_interpolated_value(3), ...
                1.2915532670115628,AbsTol=1e-14);
            complete=get_complete_ph_dos( ...
                fullfile(root,"io","phonopy","NaCl_partial_dos.dat"), ...
                fullfile(root,"io","phonopy","NaCl_phonopy.yaml"));
            testCase.verifyEqual(complete.pdos{1}(31), ...
                0.008058208,AbsTol=1e-15);
            testCase.verifyEqual(complete.pdos{2}(31), ...
                0.0119040783,AbsTol=1e-15);
        end

        function structureConversionAndEigenvector(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.io.phonopy.*
            structure=Structure(Lattice.cubic(4), ...
                {"Na","Cl"},[0,0,0;0.5,0.5,0.5], ...
                site_properties=struct("magmom",[1,-1]));
            atoms=get_phonopy_structure(structure);
            restored=get_pmg_structure(atoms);
            testCase.verifyEqual(restored.frac_coords, ...
                structure.frac_coords,AbsTol=1e-15);
            testCase.verifyEqual(restored.lattice.matrix, ...
                structure.lattice.matrix,AbsTol=1e-15);
            value=eigvec_to_eigdispl([1,2i,3], ...
                [0.5,0,0],[0.25,0,0],4);
            expected=exp(2i*pi*0.125)/2*[1,2i,3];
            testCase.verifyEqual(value,expected,AbsTol=1e-15);
        end

        function forceConstantWorkflows(testCase)
            root=officialFixtureRoot(testCase);
            import kssolv.analysis.matgenlab.io.phonopy.*
            structure=kssolv.analysis.matgenlab.core.Structure. ...
                from_file(fullfile(root,"io","phonopy","POSCAR-NaCl"), ...
                "poscar");
            forceConstants=read_force_constants( ...
                fullfile(root,"io","phonopy","FORCE_CONSTANTS"));
            mesh=get_phonon_band_structure_from_fc( ...
                structure,eye(3)*2,forceConstants,10);
            testCase.verifyEqual(mesh.nb_bands,8);
            testCase.verifyEqual(mesh.nb_qpoints,8);
            testCase.verifyEqual(mesh.bands(3,11), ...
                3.887125285018674,AbsTol=2e-13);
            line=get_phonon_band_structure_symm_line_from_fc( ...
                structure,eye(3)*2,forceConstants,5);
            testCase.verifyEqual(line.nb_bands,24);
            testCase.verifyEqual(line.nb_qpoints,48);
            testCase.verifyEqual(line.bands(3,11), ...
                2.869229797603161,AbsTol=2e-13);
            dos=get_phonon_dos_from_fc( ...
                structure,eye(3)*2,forceConstants,10);
            testCase.verifyEqual(numel(dos.frequencies),201);
            testCase.verifyEqual(dos.structure.num_sites,8);
        end

        function officialDisplacements(testCase)
            root=officialFixtureRoot(testCase);
            import kssolv.analysis.matgenlab.io.phonopy.*
            structure=kssolv.analysis.matgenlab.core.Structure. ...
                from_file(fullfile(root,"io","phonopy","POSCAR-unitcell"), ...
                "poscar");
            structures=get_displaced_structures( ...
                structure,0.01,diag([2,1,2]));
            testCase.verifyEqual(numel(structures),49);
            testCase.verifyEqual(structures{1}.num_sites,128);
            testCase.verifyEqual(structures{5}.frac_coords(1,:), ...
                [0.10872682,0.21783039,0.12595286],AbsTol=1e-7);
            testCase.verifyEqual(structures{end}.frac_coords(10,:), ...
                [0.89127318,0.78130015,0.37404715],AbsTol=1e-7);
            filename=string(tempname)+".yaml";
            cleanup=onCleanup(@()deleteIfPresent(filename));
            get_displaced_structures( ...
                structure,0.01,diag([2,1,2]),filename);
            testCase.verifyTrue(isfile(filename));
            clear cleanup
        end

        function gruneisenAndThermalFixtures(testCase)
            root=officialFixtureRoot(testCase);
            import kssolv.analysis.matgenlab.io.phonopy.*
            gruneisenRoot=fullfile(root,"phonon","gruneisen");
            parameter=get_gruneisenparameter( ...
                fullfile(gruneisenRoot,"gruneisen_mesh_Si.yaml"),[], ...
                fullfile(gruneisenRoot,"eq","POSCAR_Si"));
            testCase.verifyEqual(parameter.frequencies(1,1), ...
                0.2523831291,AbsTol=1e-12);
            testCase.verifyEqual(parameter.gruneisen(1,1), ...
                -0.1190736091,AbsTol=1e-12);
            fitted=get_gruneisen_ph_bs_symm_line( ...
                fullfile(gruneisenRoot,"gruneisen_band_Si.yaml"),[], ...
                fullfile(gruneisenRoot,"eq","POSCAR_Si"),[],true);
            raw=get_gruneisen_ph_bs_symm_line( ...
                fullfile(gruneisenRoot,"gruneisen_band_Si.yaml"),[], ...
                fullfile(gruneisenRoot,"eq","POSCAR_Si"),[],false);
            testCase.verifyNotEqual(fitted.gruneisen(1,1), ...
                raw.gruneisen(1,1));
            testCase.verifyEqual(fitted.gruneisen(1,1), ...
                0.19513149849201247,AbsTol=1e-6);
            thermalRoot=fullfile(root,"phonon", ...
                "thermal_displacement_matrices");
            matrices=get_thermal_displacement_matrices( ...
                fullfile(thermalRoot,"thermal_displacement_matrices.yaml"), ...
                fullfile(thermalRoot,"POSCAR"));
            testCase.verifyEqual(numel(matrices),31);
            testCase.verifyEqual( ...
                matrices{1}.thermal_displacement_matrix_cart(1,:), ...
                [0.00516,0.00613,0.00415,-0.00011,-0.00158,-0.00081], ...
                AbsTol=1e-15);
            testCase.verifyEqual(matrices{end}.temperature,300);
        end
    end
end

function root=officialFixtureRoot(testCase)
root="/tmp/matgenlab-plan.tMNeV8/pymatgen-core-2026.7.24/test-files";
testCase.assumeTrue(isfolder(root), ...
    "Frozen pymatgen-core fixture tree is unavailable.");
end

function deleteIfPresent(filename)
if isfile(filename),delete(filename);end
end
