classdef PWmatOutputsTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 oracle tests for io.pwmat.outputs.

    methods (Test)
        function frozenInventorySurfaceIsImplemented(testCase)
            ledger = readtable(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", ...
                "compatibility_ledger.csv"), TextType = "string", ...
                Delimiter = ",");
            rows = ledger(ledger.module == ...
                "pymatgen.io.pwmat.outputs", :);
            testCase.verifyEqual(height(rows), 20);
            testCase.verifyTrue(all(rows.status == "implemented"), ...
                join(rows.api_id(rows.status ~= "implemented"), newline));

            package = "kssolv.analysis.matgenlab.io.pwmat.";
            expectedProperties = struct( ...
                "Movement", ["atom_configs", "e_tots", "atom_forces", ...
                    "e_atoms", "virials"], ...
                "OutFermi", "e_fermi", ...
                "Report", ["spin", "n_kpoints", "n_bands", ...
                    "eigenvalues", "kpoints", "kpoints_weight", "hsps"], ...
                "DosSpin", ["labels", "dos"]);
            classes = fieldnames(expectedProperties);
            for index = 1:numel(classes)
                metadata = meta.class.fromName( ...
                    package + classes{index});
                testCase.verifyNotEmpty(metadata, classes{index});
                properties = metadataNames(metadata.PropertyList);
                testCase.verifyTrue(all(ismember( ...
                    expectedProperties.(classes{index}), properties)));
            end
            metadata = meta.class.fromName(package + "DosSpin");
            testCase.verifyTrue(ismember("get_partial_dos", ...
                metadataNames(metadata.MethodList)));
        end

        function officialMovementMatchesFrozenOracle(testCase)
            movement = ...
                kssolv.analysis.matgenlab.io.pwmat.Movement( ...
                pwmatInputFixture("MOVEMENT.lzma"));
            testCase.verifyEqual(movement.n_ionic_steps, 1);
            testCase.verifyEqual(movement.chunk_sizes, 382);
            testCase.verifyEqual(movement.chunk_starts, 0);
            testCase.verifyEqual(numel(movement.ionic_steps), 1);
            testCase.verifyEqual(fieldnames(movement.ionic_steps{1}), ...
                {'atom_config'; 'e_tot'; 'atom_forces'; ...
                'atom_energies'; 'virial'});
            testCase.verifyEqual(movement.e_tots, ...
                -357677.2281, AbsTol = 1e-8);
            testCase.verifySize(movement.atom_forces, [1, 72, 3]);
            testCase.verifyEqual( ...
                squeeze(movement.atom_forces(1, 1, :)).', ...
                [0.018471657903432, 0.012960423864921, ...
                -0.049977022608987], AbsTol = 1e-15);
            testCase.verifyEmpty(movement.e_atoms);
            testCase.verifySize(movement.virials, [1, 3, 3]);
            testCase.verifyEqual(squeeze(movement.virials(1, :, :)), ...
                [734.547, -0.240455, -0.24418; ...
                -0.240469, 734.396, -0.246855; ...
                -0.244205, -0.246843, 734.414], AbsTol = 1e-12);
            testCase.verifyClass(movement.atom_configs{1}, ...
                "kssolv.analysis.matgenlab.core.Structure");
            testCase.verifyEqual( ...
                movement.atom_configs{1}.num_sites, 72);
            testCase.verifyEqual(movement.atom_configs{1}.lattice.matrix, ...
                [10.863786, 0, 0; 0, 10.863786, 0; ...
                0, 0, 7.242524], AbsTol = 1e-12);
        end

        function movementMultiStepAliasingAndSkipMatchUpstream(testCase)
            text = ...
                kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                read_text(pwmatInputFixture("MOVEMENT.lzma"));
            second = regexprep(text, ...
                '-0\.3576772281E\+06', '-0.1230000000E+03', "once");
            path = string(tempname) + ".MOVEMENT";
            cleanup = onCleanup(@() deleteFiles(path));
            kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                write_text(path, text + second);

            movement = ...
                kssolv.analysis.matgenlab.io.pwmat.Movement(path);
            testCase.verifyEqual(movement.n_ionic_steps, 2);
            testCase.verifyEqual(movement.chunk_sizes, [382, 382]);
            testCase.verifyEqual(movement.chunk_starts, [0, 382]);
            testCase.verifyEqual(movement.e_tots, [-123, -123]);

            selected = ...
                kssolv.analysis.matgenlab.io.pwmat.Movement(path, 2, 1);
            testCase.verifyEqual(selected.n_ionic_steps, 2);
            testCase.verifyEqual(numel(selected.ionic_steps), 1);
            testCase.verifyEqual(selected.e_tots, -123);
            zeroOffset = ...
                kssolv.analysis.matgenlab.io.pwmat.Movement(path, 2, 0);
            testCase.verifyEqual(numel(zeroOffset.ionic_steps), 2);
            testCase.verifyEqual(zeroOffset.e_tots, [-123, -123]);
            clear cleanup
        end

        function movementMSONAndMissingSeparatorError(testCase)
            movement = ...
                kssolv.analysis.matgenlab.io.pwmat.Movement( ...
                pwmatInputFixture("MOVEMENT.lzma"));
            value = movement.asDict();
            testCase.verifyEqual(value.x_module, ...
                "pymatgen.io.pwmat.outputs");
            restored = kssolv.analysis.matgenlab.util.decode( ...
                movement.toJSON());
            testCase.verifyClass(restored, ...
                "kssolv.analysis.matgenlab.io.pwmat.Movement");
            testCase.verifyEqual(restored.e_tots, movement.e_tots);

            path = string(tempname) + ".MOVEMENT";
            cleanup = onCleanup(@() deleteFiles(path));
            kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                write_text(path, "1 atoms" + newline);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.pwmat.Movement(path), ...
                "KSSOLV:Matgenlab:PWmat:MovementChunks");
            clear cleanup
        end

        function outFermiPlainGzipMSONAndErrors(testCase)
            path = pwmatOutputFixture("OUT.FERMI");
            output = ...
                kssolv.analysis.matgenlab.io.pwmat.OutFermi(path);
            testCase.verifyEqual(output.e_fermi, -2.359, ...
                AbsTol = 1e-15);
            gzipPath = string(tempname) + ".OUT.FERMI.gz";
            cleanup = onCleanup(@() deleteFiles(gzipPath));
            kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                write_text(gzipPath, fileread(path));
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.OutFermi( ...
                gzipPath).e_fermi, -2.359);
            restored = kssolv.analysis.matgenlab.util.decode( ...
                output.toJSON());
            testCase.verifyClass(restored, ...
                "kssolv.analysis.matgenlab.io.pwmat.OutFermi");
            badPath = string(tempname) + ".OUT.FERMI";
            badCleanup = onCleanup(@() deleteFiles(badPath));
            kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                write_text(badPath, "bad");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.pwmat.OutFermi(badPath), ...
                "KSSOLV:Matgenlab:PWmat:OutFermi");
            clear cleanup badCleanup
        end

        function officialReportMatchesFrozenOracle(testCase)
            report = ...
                kssolv.analysis.matgenlab.io.pwmat.Report( ...
                pwmatOutputFixture("REPORT"));
            testCase.verifyEqual(report.spin, 1);
            testCase.verifyEqual(report.n_kpoints, 1);
            testCase.verifyEqual(report.n_bands, 10);
            testCase.verifySize(report.eigenvalues, [1, 1, 10]);
            testCase.verifyEqual(reshape(report.eigenvalues, 1, []), ...
                [6.604678, 6.907668, 6.991905, 7.074478, ...
                7.130352, 7.423136, 7.505018, 7.698112, ...
                7.988332, 8.097967], AbsTol = 1e-12);
            testCase.verifyEqual(report.kpoints, [0, 0, 0]);
            testCase.verifyEqual(report.kpoints_weight, 1);
            testCase.verifyEmpty(report.hsps.keys());
            restored = kssolv.analysis.matgenlab.util.decode( ...
                report.toJSON());
            testCase.verifyClass(restored, ...
                "kssolv.analysis.matgenlab.io.pwmat.Report");
            testCase.verifyEqual(restored.eigenvalues, ...
                report.eigenvalues);
        end

        function spinPolarizedReportAndHSPsMatchFrozenOracle(testCase)
            report = ...
                kssolv.analysis.matgenlab.io.pwmat.Report( ...
                pwmatOutputFixture("REPORT.synthetic"));
            testCase.verifyEqual(report.spin, 2);
            testCase.verifyEqual(report.n_kpoints, 2);
            testCase.verifyEqual(report.n_bands, 6);
            testCase.verifyEqual(reshape(report.eigenvalues(1, 1, :), ...
                1, []), 1:6);
            testCase.verifyEqual(reshape(report.eigenvalues(1, 2, :), ...
                1, []), 7:12);
            testCase.verifyEqual(reshape(report.eigenvalues(2, 1, :), ...
                1, []), 13:18);
            testCase.verifyEqual(reshape(report.eigenvalues(2, 2, :), ...
                1, []), 19:24);
            testCase.verifyEqual(report.kpoints, ...
                [0, 0, 0; .5, 0, 0]);
            testCase.verifyEqual(report.kpoints_weight, [.5, .5]);
            testCase.verifyEqual(report.hsps("G"), [0, 0, 0]);
            testCase.verifyEqual(report.hsps("X"), [.5, 0, 0]);
        end

        function reportMissingHeaderHasStableError(testCase)
            path = string(tempname) + ".REPORT";
            cleanup = onCleanup(@() deleteFiles(path));
            kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                write_text(path, "NUM_KPT = 1" + newline);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.pwmat.Report(path), ...
                "KSSOLV:Matgenlab:PWmat:ReportHeader");
            clear cleanup
        end

        function officialDosSpinMatchesFrozenOracle(testCase)
            dos = kssolv.analysis.matgenlab.io.pwmat.DosSpin( ...
                pwmatOutputFixture("DOS.spinup_projected"));
            expectedLabels = ["Energy", "Total", "Cr-3S", "Cr-3Pz", ...
                "Cr-3Px", "Cr-3Py", "Cr-4S", "Cr-3Dz2", ...
                "Cr-3Dxz", "Cr-3Dyz", "Cr-3D(x^2-y^2)", ...
                "Cr-3Dxy", "I-4Dz2", "I-4Dxz", "I-4Dyz", ...
                "I-4D(x^2-y^2)", "I-4Dxy", "I-5S", ...
                "I-5Pz", "I-5Px", "I-5Py"];
            testCase.verifyEqual(dos.labels, expectedLabels);
            testCase.verifySize(dos.dos, [20, 21]);
            testCase.verifyEqual(dos.dos(1, :), ...
                [-1.3461, zeros(1, 20)], AbsTol = 1e-15);
            testCase.verifyEqual(dos.dos(end, :), ...
                [-.93765, 2.6331, 3.3024e-9, 1.0313e-7, ...
                3.8272e-7, 3.8138e-7, .00099164, .0034258, ...
                .576, .44439, .39186, .31456, 5.6428e-8, ...
                8.1113e-7, 8.9247e-7, 4.3818e-7, 3.785e-7, ...
                .0022301, .03783, .47422, .38761], ...
                AbsTol = 1e-15);
            testCase.verifyEqual(dos.get_partial_dos("total").', ...
                [0, 0, 0, .34071, 3.144, 12.168, 20.942, ...
                21.697, 22.704, 23.745, 19.62, 10.324, 4.4444, ...
                3.6435, 3.3347, 5.8741, 10.835, 10.815, ...
                5.6892, 2.6331], AbsTol = 1e-12);
            testCase.verifyError(@() dos.get_partial_dos("missing"), ...
                "KSSOLV:Matgenlab:PWmat:PartialDos");
            restored = kssolv.analysis.matgenlab.util.decode( ...
                dos.toJSON());
            testCase.verifyClass(restored, ...
                "kssolv.analysis.matgenlab.io.pwmat.DosSpin");
            testCase.verifyEqual(restored.dos, dos.dos);
        end

        function dosColumnMismatchHasStableError(testCase)
            path = string(tempname) + ".DOS";
            cleanup = onCleanup(@() deleteFiles(path));
            kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                write_text(path, "# Energy Total" + newline + "0.0");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.pwmat.DosSpin(path), ...
                "KSSOLV:Matgenlab:PWmat:DosColumns");
            clear cleanup
        end
    end
end

function path = pwmatInputFixture(name)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "+pwmat", "+inputs", name);
end

function path = pwmatOutputFixture(name)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "+pwmat", "+outputs", name);
end

function deleteFiles(paths)
for path = string(paths)
    if isfile(path), delete(path); end
end
end

function names = metadataNames(values)
if iscell(values), values = [values{:}]; end
names = string({values.Name});
end
