classdef PWmatInputsTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 oracle tests for io.pwmat.inputs.

    methods (Test)
        function frozenInventorySurfaceIsImplemented(testCase)
            ledger = readtable(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", ...
                "compatibility_ledger.csv"), TextType = "string", ...
                Delimiter = ",");
            rows = ledger(ledger.module == ...
                "pymatgen.io.pwmat.inputs", :);
            testCase.verifyEqual(height(rows), 41);
            testCase.verifyTrue(all(rows.status == "implemented"), ...
                join(rows.api_id(rows.status ~= "implemented"), newline));

            package = "kssolv.analysis.matgenlab.io.pwmat.";
            classes = ["LineLocator", "ListLocator", ...
                "ACExtractorBase", "ACExtractor", "ACstrExtractor", ...
                "AtomConfig", "GenKpt", "HighSymmetryPoint"];
            for name = classes
                testCase.verifyNotEmpty(meta.class.fromName(package + name));
            end
            expected = struct( ...
                "LineLocator", "locate_all_lines", ...
                "ListLocator", "locate_all_lines", ...
                "ACExtractorBase", ["get_n_atoms", "get_lattice", ...
                    "get_types", "get_coords", "get_magmoms"], ...
                "ACExtractor", ["get_n_atoms", "get_lattice", ...
                    "get_types", "get_coords", "get_magmoms"], ...
                "ACstrExtractor", ["get_n_atoms", "get_lattice", ...
                    "get_types", "get_coords", "get_magmoms", ...
                    "get_e_tot", "get_atom_energies", ...
                    "get_atom_forces", "get_virial"], ...
                "AtomConfig", ["from_str", "from_file", "from_dict", ...
                    "get_str", "write_file", "as_dict"], ...
                "GenKpt", ["from_structure", "get_str", "write_file"], ...
                "HighSymmetryPoint", ...
                    ["from_structure", "get_str", "write_file"]);
            names = fieldnames(expected);
            for index = 1:numel(names)
                metadata = meta.class.fromName(package + names{index});
                actual = metadataNames(metadata.MethodList);
                testCase.verifyTrue(all(ismember(expected.(names{index}), ...
                    actual)), names{index});
            end
        end

        function locatorsMatchCompressedOfficialOracle(testCase)
            movement = pwmatFixture("MOVEMENT.lzma");
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.LineLocator. ...
                locate_all_lines(movement, "force"), ...
                [1, 163]);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.LineLocator. ...
                locate_all_lines(movement, "FORCE", "AVERAGE"), ...
                163);
            values = ["Average Force=  0.12342E+01", "Force"];
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.ListLocator. ...
                locate_all_lines(values, "force"), [0, 1]);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.ListLocator. ...
                locate_all_lines(values, "FORCE", "average"), 1);
        end

        function extractorsMatchOfficialAtomConfig(testCase)
            path = pwmatFixture("atom.config");
            fileExtractor = ...
                kssolv.analysis.matgenlab.io.pwmat.ACExtractor(path);
            stringExtractor = ...
                kssolv.analysis.matgenlab.io.pwmat.ACstrExtractor( ...
                    fileread(path));
            expectedLattice = [3.503757564, 6.068685680, 0, ...
                -7.007514370, 0, 0, 0, 0, 23.14769057];
            expectedTypes = [53, 53, 53, 53, 53, 53, 24, 24];
            expectedCoordinates = [ ...
                .530070000, .419221000, .432258081, ...
                .248070000, .137072000, .567991460, ...
                .889151000, .419221000, .567741919, ...
                .889002000, .137072000, .432008540, ...
                .530365000, .778199000, .567801995, ...
                .247834000, .778199000, .432198005, ...
                .555714000, .111428000, .500000000, ...
                .222799000, .445598000, .500000000];
            testCase.verifyEqual(fileExtractor.n_atoms, 8);
            testCase.verifyEqual(fileExtractor.lattice, expectedLattice, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(fileExtractor.types, expectedTypes);
            testCase.verifyEqual(fileExtractor.coords, ...
                expectedCoordinates, AbsTol = 1e-12);
            testCase.verifyEqual(fileExtractor.magmoms, zeros(1, 8));
            testCase.verifyEqual(stringExtractor.get_n_atoms(), ...
                fileExtractor.get_n_atoms());
            testCase.verifyEqual(stringExtractor.get_lattice(), ...
                fileExtractor.get_lattice());
            testCase.verifyEqual(stringExtractor.get_types(), ...
                fileExtractor.get_types());
            testCase.verifyEqual(stringExtractor.get_coords(), ...
                fileExtractor.get_coords());
            testCase.verifyEqual(stringExtractor.get_magmoms(), ...
                fileExtractor.get_magmoms());
        end

        function movementFieldsMatchFrozenPythonOracle(testCase)
            text = ...
                kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                read_text(pwmatFixture("MOVEMENT.lzma"));
            extractor = ...
                kssolv.analysis.matgenlab.io.pwmat.ACstrExtractor(text);
            testCase.verifyEqual(extractor.get_n_atoms(), 72);
            testCase.verifyEqual(extractor.get_lattice(), ...
                [10.863786, 0, 0, 0, 10.863786, 0, ...
                0, 0, 7.242524], AbsTol = 1e-12);
            testCase.verifyEqual(extractor.get_e_tot(), ...
                -357677.2281, AbsTol = 1e-8);
            energies = extractor.get_atom_energies();
            testCase.verifyEqual(energies([1:3, end]), ...
                [166.1493442, 166.1535578, 166.1553266, ...
                166.152081], AbsTol = 1e-10);
            forces = extractor.get_atom_forces();
            testCase.verifyEqual(forces(1:3), ...
                [0.018471657903432, 0.012960423864921, ...
                -0.049977022608987], AbsTol = 1e-15);
            testCase.verifyEqual(extractor.get_virial(), ...
                [734.547, -0.240455, -0.24418, ...
                -0.240469, 734.396, -0.246855, ...
                -0.244205, -0.246843, 734.414], ...
                AbsTol = 1e-12);
        end

        function optionalMovementFieldsUseUpstreamEmptySemantics(testCase)
            extractor = ...
                kssolv.analysis.matgenlab.io.pwmat.ACstrExtractor( ...
                    fileread(pwmatFixture("atom.config")));
            testCase.verifyEmpty(extractor.get_atom_energies());
            testCase.verifyEmpty(extractor.get_virial());
            testCase.verifyError(@() extractor.get_e_tot(), ...
                "KSSOLV:Matgenlab:PWmat:Energy");
            testCase.verifyError(@() extractor.get_atom_forces(), ...
                "KSSOLV:Matgenlab:PWmat:Force");
        end

        function atomConfigExactTextAndMSONRoundTrip(testCase)
            atomConfig = ...
                kssolv.analysis.matgenlab.io.pwmat.AtomConfig. ...
                from_file(pwmatFixture("atom.config"), true);
            testCase.verifyEqual(atomConfig.true_names, "Cr2I6");
            testCase.verifyEqual(atomConfig.get_str(), ...
                frozenAtomConfigText());
            testCase.verifyEqual(string(atomConfig), atomConfig.get_str());
            testCase.verifyEqual(string(atomConfig.as_dict().x_module), ...
                "pymatgen.io.pwmat.inputs");
            restored = kssolv.analysis.matgenlab.util.decode( ...
                atomConfig.toJSON());
            testCase.verifyClass(restored, ...
                "kssolv.analysis.matgenlab.io.pwmat.AtomConfig");
            testCase.verifyEqual(restored.structure.lattice.matrix, ...
                atomConfig.structure.lattice.matrix, AbsTol = 1e-12);
            testCase.verifyEqual(restored.get_str(), atomConfig.get_str());
        end

        function atomConfigPlainGzipAndLzmaRoundTrip(testCase)
            atomConfig = ...
                kssolv.analysis.matgenlab.io.pwmat.AtomConfig. ...
                from_file(pwmatFixture("atom.config"), true);
            extensions = [".config", ".config.gz", ".config.z", ...
                ".config.bz2", ".config.xz", ".config.lzma"];
            paths = strings(size(extensions));
            cleanup = onCleanup(@() deleteAll(paths));
            for index = 1:numel(extensions)
                paths(index) = string(tempname) + extensions(index);
                atomConfig.write_file(paths(index));
                restored = ...
                    kssolv.analysis.matgenlab.io.pwmat.AtomConfig. ...
                    from_file(paths(index), true);
                testCase.verifyEqual(restored.get_str(), ...
                    atomConfig.get_str());
            end
            clear cleanup
        end

        function registeredStructurePWmatRoundTrip(testCase)
            structure = ...
                kssolv.analysis.matgenlab.core.Structure.from_file( ...
                    pwmatFixture("atom.config"));
            testCase.verifyEqual(structure.composition.reduced_formula, ...
                "CrI3");
            text = structure.to("", "pwmat");
            restored = ...
                kssolv.analysis.matgenlab.core.Structure.from_str( ...
                    text, "pwmat");
            testCase.verifyEqual(restored.lattice.matrix, ...
                structure.lattice.matrix, AbsTol = 5e-7);
            testCase.verifyEqual(restored.frac_coords, ...
                structure.frac_coords, AbsTol = 5e-7);
        end

        function atomConfigErrorsAreDeterministic(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.pwmat.ACstrExtractor("bad"), ...
                "KSSOLV:Matgenlab:PWmat:AtomCount");
            extractor = ...
                kssolv.analysis.matgenlab.io.pwmat.ACstrExtractor( ...
                    "1" + newline + "Position" + newline + ...
                    "14 0 0 0 1 1 1" + newline);
            testCase.verifyError(@() extractor.get_lattice(), ...
                "KSSOLV:Matgenlab:PWmat:MissingSection");
        end

        function atomConfigOrderingAndNegativeLatticeMatchUpstream(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                [-3, 0, 0; 0, 3, 0; 0, 0, 3], ...
                {"Cl", "Na"}, [0, 0, 0; .5, .5, .5]);
            atomConfig = ...
                kssolv.analysis.matgenlab.io.pwmat.AtomConfig( ...
                    structure, true);
            testCase.verifyEqual(atomConfig.true_names, "Na1Cl1");
            lines = splitlines(atomConfig.get_str());
            testCase.verifyEqual( ...
                sscanf(char(lines(3)), "%f").', [3, 0, 0]);

            ionic = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3), { ...
                kssolv.analysis.matgenlab.core.Species("O", -2), ...
                kssolv.analysis.matgenlab.core.Species("Fe", 2)}, ...
                [0, 0, 0; .5, .5, .5]);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.AtomConfig( ...
                ionic).true_names, "Fe2+1O2-1");
        end

        function genKptMatchesOfficialFrozenOracle(testCase)
            atomConfig = ...
                kssolv.analysis.matgenlab.io.pwmat.AtomConfig. ...
                from_file(pwmatFixture("atom.config"));
            generated = ...
                kssolv.analysis.matgenlab.io.pwmat.GenKpt. ...
                from_structure(atomConfig.structure, 2, .01);
            testCase.verifyEqual(generated.density, ...
                .06283185307179587, AbsTol = 1e-15);
            testCase.verifyEqual(generated.reciprocal_lattice, ...
                [0, 1.0353453183259256, 0; ...
                -.8966353795974571, .5176727151594053, 0; ...
                0, 0, .27143897090635705], AbsTol = 1e-14);
            testCase.verifyEqual(string(generated.kpath.path{1}), ...
                ["GAMMA", "M", "K", "GAMMA"]);
            testCase.verifyEqual(generated.get_str(), frozenGenKptText());
            path = string(tempname) + ".gen.kpt.lzma";
            cleanup = onCleanup(@() deleteAll(path));
            generated.write_file(path);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                read_text(path), generated.get_str());
            restored = generated.from_dict(generated.asDict());
            testCase.verifyEqual(restored.get_str(), generated.get_str());
            restored = kssolv.analysis.matgenlab.util.decode( ...
                generated.toJSON());
            testCase.verifyEqual(restored.get_str(), generated.get_str());

            onePoint = struct("GAMMA", [0, 0, 0]);
            arbitraryDensity = ...
                kssolv.analysis.matgenlab.io.pwmat.GenKpt( ...
                eye(3), onePoint, {{"GAMMA"}}, (1 / 3) * 2 * pi);
            testCase.verifyTrue(startsWith(arbitraryDensity.get_str(), ...
                "Generated by pymatgen. density=0.3333333333333333,"));
            clear cleanup
        end

        function highSymmetryPointMatchesOfficialFrozenOracle(testCase)
            atomConfig = ...
                kssolv.analysis.matgenlab.io.pwmat.AtomConfig. ...
                from_file(pwmatFixture("atom.config"));
            points = ...
                kssolv.analysis.matgenlab.io.pwmat.HighSymmetryPoint. ...
                from_structure(atomConfig.structure, 2, .01);
            testCase.verifyEqual(fieldnames(points.kpath), ...
                {'kpoints'; 'path'});
            testCase.verifyEqual(numel(points.kpath.path), 1);
            testCase.verifyEqual(points.get_str(), ...
                frozenHighSymmetryText());
            path = string(tempname) + ".HIGH_SYMMETRY_POINTS.lzma";
            cleanup = onCleanup(@() deleteAll(path));
            points.write_file(path);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                read_text(path), points.get_str());
            restored = points.from_dict(points.asDict());
            testCase.verifyEqual(restored.get_str(), points.get_str());
            restored = kssolv.analysis.matgenlab.util.decode( ...
                points.toJSON());
            testCase.verifyEqual(restored.get_str(), points.get_str());
            clear cleanup
        end

        function disconnectedPathIndexSemanticsMatchUpstream(testCase)
            points = struct("GAMMA", [0, 0, 0], "X", [1, 0, 0], ...
                "Y", [0, 1, 0], "Z", [0, 1, 1]);
            paths = {{"GAMMA", "X"}, {"Y", "Z"}};
            high = ...
                kssolv.analysis.matgenlab.io.pwmat.HighSymmetryPoint( ...
                    2 * pi * eye(3), points, paths, 2 * pi);
            testCase.verifyEqual(high.get_str(), strjoin([ ...
                "Label       Index       Coordinate", ...
                "G               1         0.000000", ...
                "X               3         1.000000", ...
                "Y               4         1.000000", ...
                "Z               6         2.000000"], newline) + newline);
        end
    end
end

function path = pwmatFixture(name)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "+pwmat", "+inputs", name);
end

function value = frozenAtomConfigText()
value = strjoin([ ...
    sprintf("\t8 atoms"), ...
    "Lattice vector", ...
    "       3.503758       6.068686       0.000000", ...
    "      -7.007514       0.000000       0.000000", ...
    "       0.000000       0.000000      23.147691", ...
    "Position, move_x, move_y, move_z", ...
    "  53       0.530070       0.419221       0.432258   1   1   1", ...
    "  53       0.248070       0.137072       0.567991   1   1   1", ...
    "  53       0.889151       0.419221       0.567742   1   1   1", ...
    "  53       0.889002       0.137072       0.432009   1   1   1", ...
    "  53       0.530365       0.778199       0.567802   1   1   1", ...
    "  53       0.247834       0.778199       0.432198   1   1   1", ...
    "  24       0.555714       0.111428       0.500000   1   1   1", ...
    "  24       0.222799       0.445598       0.500000   1   1   1", ...
    "MAGNETIC", ...
    "  53       0.000000", "  53       0.000000", ...
    "  53       0.000000", "  53       0.000000", ...
    "  53       0.000000", "  53       0.000000", ...
    "  24       0.000000", "  24       0.000000"], newline) + newline;
end

function value = frozenGenKptText()
value = strjoin([ ...
    "Generated by pymatgen. density=0.01, fractional coordinates in reciprocal lattice.", ...
    "9.0", ...
    sprintf("        0.000000\t    0.000000\t    0.000000\tGAMMA"), ...
    sprintf("        0.500000\t    0.000000\t    0.000000\tM"), ...
    "5.0", ...
    sprintf("        0.500000\t    0.000000\t    0.000000\tM"), ...
    sprintf("        0.333333\t    0.333333\t    0.000000\tK"), ...
    "10.0", ...
    sprintf("        0.333333\t    0.333333\t    0.000000\tK"), ...
    sprintf("        0.000000\t    0.000000\t    0.000000\tGAMMA")], ...
    newline) + newline;
end

function value = frozenHighSymmetryText()
value = strjoin([ ...
    "Label       Index       Coordinate", ...
    "G               1         0.000000", ...
    "M              11         0.082390", ...
    "K              17         0.129958", ...
    "G              28         0.225094"], newline) + newline;
end

function names = metadataNames(values)
if iscell(values), values = [values{:}]; end
names = string({values.Name});
end

function deleteAll(paths)
for path = string(paths)
    if strlength(path) > 0 && isfile(path), delete(path); end
end
end
