classdef PwscfInventoryTest < matlab.unittest.TestCase
    properties
        fixture
        oracle
        structure
        pseudo
    end

    methods (TestMethodSetup)
        function prepare(testCase)
            testCase.fixture = fullfile(pwd, "+kssolv", "+analysis", ...
                "+matgenlab", "+test", "+io", "+fixtures", ...
                "+pwscf", "Si.pwscf.out");
            testCase.oracle = jsondecode(fileread(fullfile(pwd, "dev", ...
                "matgenlab", "oracles", "pwscf_2026.7.24.json")));
            testCase.structure = kssolv.analysis.matgenlab.core.Structure( ...
                [2.9, .1, 1.5; .9, 2.7, 1.5; .1, .1, 3.3], ...
                {"O", "Li", "Li"}, ...
                [0, 0, 0; .75, .75, .75; .25, .25, .25]);
            testCase.pseudo = containers.Map({'Li', 'O'}, ...
                {'Li.UPF', 'O.UPF'});
        end
    end

    methods (Test)
        function automaticInputMatchesFrozenOracle(testCase)
            input = kssolv.analysis.matgenlab.io.pwscf.PWInput( ...
                testCase.structure, testCase.pseudo, ...
                struct("calculation", "scf", "pseudo_dir", "./"), ...
                struct("ecutwfc", 50));
            testCase.verifyEqual(string(input), ...
                string(testCase.oracle.automatic_input));
            testCase.verifyEqual(char(input), ...
                char(testCase.oracle.automatic_input));
        end

        function crystalKpointsAndFormattingMatch(testCase)
            input = kssolv.analysis.matgenlab.io.pwscf.PWInput( ...
                testCase.structure, testCase.pseudo, [], [], [], [], [], ...
                "crystal_b", [0, 0, 0; 0, .5, .5; .5, .5, .5], ...
                [], struct("coord_decimals", 8, ...
                "kpoints_crystal_b_indent", 2, ...
                "kpoints_grid_decimals", 5));
            testCase.verifyEqual(string(input), ...
                string(testCase.oracle.crystal_b_input));
            parsed = kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                from_str(string(input));
            testCase.verifyEqual(string(parsed), string(input));
            testCase.verifyEqual(parsed.kpoints_grid, ...
                [0, 0, 0; 0, .5, .5; .5, .5, .5]);
        end

        function dictionariesFilesAndGzipRoundTrip(testCase)
            input = kssolv.analysis.matgenlab.io.pwscf.PWInput( ...
                testCase.structure, testCase.pseudo, ...
                struct("calculation", "scf"), ...
                struct("ecutwfc", 50), struct("conv_thr", 5.3e-5), ...
                struct(), struct(), "automatic", [4, 4, 4], [1, 1, 1]);
            restored = kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                from_dict(input.as_dict());
            testCase.verifyEqual(string(restored), string(input));

            filename = string(tempname);
            cleanup = onCleanup(@() deleteIfExists(filename));
            input.write_file(filename);
            fromFile = kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                from_file(filename);
            testCase.verifyEqual(string(fromFile), string(input));
            archive = gzip(filename, fileparts(filename));
            gzipPath = string(archive{1});
            gzipCleanup = onCleanup(@() deleteIfExists(gzipPath));
            fromGzip = kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                from_file(gzipPath);
            testCase.verifyEqual(string(fromGzip), string(input));
            clear gzipCleanup cleanup
        end

        function procValMatchesFrozenOracle(testCase)
            oracleValues = testCase.oracle.proc_val;
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                proc_val("degauss", "7.3498618000d-03"), ...
                oracleValues.degauss, AbsTol = 1e-15);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                proc_val("nat", "2"), oracleValues.nat);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                proc_val("nosym", ".TRUE."), oracleValues.nosym);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.pwscf.PWInput. ...
                proc_val("smearing", "'cold'"), ...
                string(oracleValues.smearing));
        end

        function pseudoValidationUsesTypedInputError(testCase)
            incomplete = containers.Map({'Li'}, {'Li.UPF'});
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.pwscf.PWInput( ...
                testCase.structure, incomplete), ...
                "KSSOLV:Matgenlab:PWSCF:Input");
            properties = struct("pseudo", ...
                {{"O.UPF", "Li.UPF", "Li.UPF"}});
            propertyStructure = ...
                kssolv.analysis.matgenlab.core.Structure( ...
                testCase.structure.lattice, {"O", "Li", "Li"}, ...
                testCase.structure.frac_coords, ...
                site_properties = properties);
            input = kssolv.analysis.matgenlab.io.pwscf.PWInput( ...
                propertyStructure);
            testCase.verifyTrue(contains(string(input), "O1"));
            testCase.verifyTrue(contains(string(input), "Li2"));
        end

        function officialOutputPropertiesMatchFrozenOracle(testCase)
            output = kssolv.analysis.matgenlab.io.pwscf.PWOutput( ...
                testCase.fixture);
            expected = testCase.oracle.output;
            testCase.verifyEqual(output.final_energy, ...
                expected.final_energy, AbsTol = 1e-12);
            testCase.verifyEqual(output.lattice_type, ...
                expected.lattice_type);
            for index = 1:6
                testCase.verifyEqual(output.get_celldm(index), ...
                    expected.celldm(index), AbsTol = 1e-12);
            end
            testCase.verifyEqual(output.data.energies, ...
                reshape(expected.energies, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual(output.data.nkpts, expected.nkpts);
        end

        function genericPatternReaderSupportsControls(testCase)
            output = kssolv.analysis.matgenlab.io.pwscf.PWOutput( ...
                testCase.fixture);
            matches = output.read_pattern( ...
                struct("iteration", "iteration #\s+(\d+)"), ...
                true, true, @str2double);
            testCase.verifyEqual(matches.iteration{1}, 5);
            testCase.verifyEqual(output.data.iteration{1}, 5);
        end
    end
end

function deleteIfExists(filename)
if isfile(filename), delete(filename); end
end
