classdef RegistryTest < matlab.unittest.TestCase
    methods (Test)
        function registerLookupAndUnregisterAreCaseInsensitive(testCase)
            format=kssolv.analysis.matgenlab.io.StructureFormat( ...
                "TestFmt-RoundTrip","patterns",{"*.testfmt"}, ...
                "read_str",@readTestStructure);
            kssolv.analysis.matgenlab.io.register_structure_format(format);
            cleanup=onCleanup(@()kssolv.analysis.matgenlab.io. ...
                unregister_structure_format("TestFmt-RoundTrip"));
            byName=kssolv.analysis.matgenlab.io. ...
                get_structure_format("name","TESTFMT-ROUNDTRIP");
            byFile=kssolv.analysis.matgenlab.io. ...
                get_structure_format("filename","x.testfmt");
            testCase.verifyTrue(byName==format);
            testCase.verifyTrue(byFile==format);
            names=cellfun(@(value)value.name, ...
                kssolv.analysis.matgenlab.io.list_structure_formats());
            testCase.verifyTrue(any(names=="testfmt-roundtrip"));
            kssolv.analysis.matgenlab.io. ...
                unregister_structure_format("TESTFMT-ROUNDTRIP");
            names=cellfun(@(value)value.name, ...
                kssolv.analysis.matgenlab.io.list_structure_formats());
            testCase.verifyFalse(any(names=="testfmt-roundtrip"));
            clear cleanup

            moleculeFormat=kssolv.analysis.matgenlab.io.MoleculeFormat( ...
                "mol-test","patterns",{"*.moltest"});
            kssolv.analysis.matgenlab.io. ...
                register_molecule_format(moleculeFormat);
            moleculeCleanup=onCleanup(@() ...
                kssolv.analysis.matgenlab.io. ...
                unregister_molecule_format("mol-test"));
            testCase.verifyTrue(kssolv.analysis.matgenlab.io. ...
                get_molecule_format("filename","x.moltest")== ...
                moleculeFormat);
            clear moleculeCleanup
        end

        function builtinNameAndFilenameDispatchMatchesOfficial(testCase)
            structureCases={ ...
                "foo.cif","cif";"foo.mcif","cif"; ...
                "POSCAR","poscar";"CONTCAR","poscar"; ...
                "foo.vasp","poscar";"CHGCAR","chgcar"; ...
                "LOCPOT","chgcar";"vasprun.xml","vasprun"; ...
                "foo.cssr","cssr";"foo.json","json"; ...
                "foo.yaml","yaml";"foo.yml","yaml"; ...
                "foo.xsf","xsf";"foo.res","res"; ...
                "rndstr.in","mcsqs";"CTRL.foo","lmto"; ...
                "foo.config","pwmat";"foo.pwmat","pwmat"};
            for index=1:size(structureCases,1)
                actual=kssolv.analysis.matgenlab.io. ...
                    get_structure_format("filename", ...
                    structureCases{index,1});
                testCase.verifyEqual(actual.name, ...
                    structureCases{index,2});
            end
            moleculeCases={ ...
                "foo.xyz","xyz";"foo.gjf","gaussian"; ...
                "foo.g09","gaussian";"foo.out","gaussian-out"; ...
                "foo.json","json";"foo.yaml","yaml"};
            for index=1:size(moleculeCases,1)
                actual=kssolv.analysis.matgenlab.io. ...
                    get_molecule_format("filename", ...
                    moleculeCases{index,1});
                testCase.verifyEqual(actual.name,moleculeCases{index,2});
            end
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io. ...
                get_structure_format("name","badformat"), ...
                "KSSOLV:Matgenlab:Registry:InvalidStructureFormat");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.get_structure_format(), ...
                "KSSOLV:Matgenlab:Registry:Lookup");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io. ...
                get_molecule_format("filename","x.unknown"), ...
                "KSSOLV:Matgenlab:Registry:MoleculeExtension");
        end

        function keywordFilteringMatchesFunctionSignature(testCase)
            lastwarn("");
            filtered=kssolv.analysis.matgenlab.io.filter_kwargs( ...
                @(a,b)a+b,struct("a",1,"bogus",2));
            [~,warningId]=lastwarn;
            testCase.verifyEqual(filtered,struct("a",1));
            testCase.verifyEqual(warningId, ...
                'KSSOLV:Matgenlab:Registry:UnsupportedKeywords');
            passthrough=struct("a",1,"b",2);
            actual=kssolv.analysis.matgenlab.io.filter_kwargs( ...
                @acceptVarargin,passthrough);
            testCase.verifyEqual(actual,passthrough);
        end

        function publicStructureAndMoleculeUseRegistryOverrides(testCase)
            original=kssolv.analysis.matgenlab.io. ...
                get_structure_format("name","cif");
            replacement=kssolv.analysis.matgenlab.io.StructureFormat( ...
                "cif","patterns",{"*.cif*"}, ...
                "read_str",@readTestStructure, ...
                "write_str",original.write_str);
            kssolv.analysis.matgenlab.io. ...
                register_structure_format(replacement);
            cleanup=onCleanup(@()kssolv.analysis.matgenlab.io. ...
                register_structure_format(original));
            structure=kssolv.analysis.matgenlab.core.Structure. ...
                from_str("ignored","cif");
            testCase.verifyEqual(structure.formula,"Si1");
            clear cleanup

            simple=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
                ["Si","Si"],[0,0,0;.5,.5,.5]);
            for format=["cif","poscar","json","yaml"]
                text=simple.to("",format);
                restored=kssolv.analysis.matgenlab.core.Structure. ...
                    from_str(text,format);
                testCase.verifyEqual(restored.formula,simple.formula);
            end
            molecule=kssolv.analysis.matgenlab.core.Molecule( ...
                ["C","O"],[0,0,0;1.1,0,0]);
            for format=["xyz","json","yaml"]
                text=molecule.to("",format);
                restored=kssolv.analysis.matgenlab.core.Molecule. ...
                    from_str(text,format);
                testCase.verifyEqual(restored.formula,molecule.formula);
            end
        end
    end
end

function structure=readTestStructure(varargin)
assert(iscell(varargin));
structure=kssolv.analysis.matgenlab.core.Structure( ...
    kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
    "Si",[0,0,0]);
end

function varargout=acceptVarargin(varargin)
assert(iscell(varargin));
varargout=cell(1,nargout);
end
