classdef ResFrozenOracleTest < matlab.unittest.TestCase
    %RESFROZENORACLETEST Static parity oracle for pymatgen.io.res.

    methods (Test)
        function frozenInventoryHasAllFortySevenApis(testCase)
            package = "kssolv.analysis.matgenlab.io.res.";
            classes = ["AirssTITL", "ResCELL", "Ion", "ResSFAC", ...
                "Res", "ResParseError", "ResError", "ResParser", ...
                "ResWriter", "ResProvider", "AirssProvider", "ResIO"];
            writer = ["string", "write"];
            base = ["from_str", "from_file", "rems", "lattice", ...
                "sites", "structure"];
            airss = ["from_str", "from_file", "get_run_start_info", ...
                "get_castep_version", "get_func_rel_disp", ...
                "get_cut_grid_gmax_fsbc", ...
                "get_mpgrid_offset_nkpts_spacing", ...
                "get_airss_version", "get_pspots", "seed", "pressure", ...
                "volume", "energy", "integrated_spin_density", ...
                "integrated_absolute_spin_density", ...
                "spacegroup_label", "appearances", "entry", "as_dict"];
            conversions = ["structure_from_str", "structure_from_file", ...
                "structure_to_str", "structure_to_file", ...
                "entry_from_str", "entry_from_file", "entry_to_str", ...
                "entry_to_file"];
            testCase.verifyEqual(numel(classes) + numel(writer) + ...
                numel(base) + numel(airss) + numel(conversions), 47);
            for name = classes
                testCase.verifyNotEmpty(meta.class.fromName(package + name));
            end
            testCase.verifyMembers(package + "ResWriter", writer);
            testCase.verifyMembers(package + "ResProvider", base);
            testCase.verifyMembers(package + "AirssProvider", airss);
            testCase.verifyMembers(package + "ResIO", conversions);
        end

        function recordsMatchFrozenFormatting(testCase)
            title = kssolv.analysis.matgenlab.io.res.AirssTITL( ...
                "seed", 1.234, 2.34567, -3.456789, 4, 5, "P1", 6);
            testCase.verifyEqual(string(title), ...
                "TITL seed 1.23 2.3457 -3.45679 4.000000 " + ...
                "5.000000 (P1) n - 6");
            cellRecord = kssolv.analysis.matgenlab.io.res.ResCELL( ...
                1, 2, 3, 4, 90, 100, 110);
            testCase.verifyEqual(string(cellRecord), ...
                "CELL 1.00000 2.00000 3.00000 4.00000 " + ...
                "90.00000 100.00000 110.00000");
            plain = kssolv.analysis.matgenlab.io.res.Ion( ...
                "C", 1, [0.1, 0.2, 0.3], 0.5);
            magnetic = kssolv.analysis.matgenlab.io.res.Ion( ...
                "Co", 2, [-0.1, 0, 1.1], 1, -1.4);
            testCase.verifyEqual(string(plain), ...
                "C      1  0.10000000 0.20000000 0.30000000 0.500000");
            testCase.verifyEqual(string(magnetic), ...
                "Co     2  -0.10000000 0.00000000 1.10000000 " + ...
                "1.000000 -1.40");
            sfac = kssolv.analysis.matgenlab.io.res.ResSFAC( ...
                ["C", "Co"], {plain, magnetic});
            testCase.verifyTrue(endsWith(string(sfac), "END" + newline));
            parsed = kssolv.analysis.matgenlab.io.res.Res( ...
                title, "note", cellRecord, sfac);
            restored = kssolv.analysis.matgenlab.io.res.Res. ...
                from_dict(parsed.as_dict());
            testCase.verifyEqual(string(restored), string(parsed));
        end

        function officialAirssFixtureMatchesOracle(testCase)
            oracle = testCase.oracle().coc;
            provider = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_file(testCase.fixture("coc-115925-9326-14.res"), ...
                "strict");
            testCase.verifyEqual(provider.seed, string(oracle.seed));
            testCase.verifyEqual(provider.pressure, oracle.pressure, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(provider.volume, oracle.volume, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(provider.energy, oracle.energy, ...
                AbsTol = 1e-10);
            testCase.verifyEqual(provider.integrated_spin_density, ...
                oracle.integrated_spin_density);
            testCase.verifyEqual( ...
                provider.integrated_absolute_spin_density, ...
                oracle.integrated_absolute_spin_density);
            testCase.verifyEqual(provider.spacegroup_label, ...
                string(oracle.spacegroup_label));
            testCase.verifyEqual(provider.appearances, oracle.appearances);
            testCase.verifyEqual(numel(provider.rems), oracle.rem_count);
            testCase.verifyEqual(provider.lattice.lengths, ...
                reshape(oracle.lengths, 1, []), AbsTol = 1e-10);
            testCase.verifyEqual(provider.lattice.angles, ...
                reshape(oracle.angles, 1, []), AbsTol = 1e-10);
            testCase.verifyEqual(provider.structure.num_sites, ...
                oracle.site_count);
            testCase.verifyEqual(provider.structure.frac_coords(1, :), ...
                reshape(oracle.first_frac_coords, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(provider.structure.frac_coords(end, :), ...
                reshape(oracle.last_frac_coords, 1, []), ...
                AbsTol = 1e-12);
            species = cellfun(@(site) string(site.specie), ...
                provider.sites);
            testCase.verifyEqual(species, reshape(string(oracle.species), ...
                1, []));
        end

        function airssMetadataMatchesOracle(testCase)
            oracle = testCase.oracle().coc;
            provider = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_file(testCase.fixture("coc-115925-9326-14.res"), ...
                "strict");
            run = provider.get_run_start_info();
            testCase.verifyEqual(string(run{1}, "yyyy-MM-dd"), ...
                string(oracle.run_date));
            testCase.verifyEqual(run{2}, string(oracle.run_path));
            testCase.verifyEqual(provider.get_castep_version(), ...
                string(oracle.castep_version));
            functional = provider.get_func_rel_disp();
            testCase.verifyEqual(string(functional), ...
                [string(oracle.functional), string(oracle.relativity), ...
                string(oracle.dispersion)]);
            cutoff = provider.get_cut_grid_gmax_fsbc();
            testCase.verifyEqual([cutoff{1:3}], ...
                reshape(oracle.cut_grid_gmax, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual(cutoff{4}, string(oracle.fsbc));
            grid = provider.get_mpgrid_offset_nkpts_spacing();
            testCase.verifyEqual(grid{1}, reshape(oracle.mp_grid, 1, []));
            testCase.verifyEqual(grid{2}, reshape(oracle.mp_offset, 1, []));
            testCase.verifyEqual(grid{3}, oracle.nkpts);
            testCase.verifyEqual(grid{4}, oracle.spacing, AbsTol = 1e-12);
            airss = provider.get_airss_version();
            testCase.verifyEqual(airss{1}, string(oracle.airss_version));
            testCase.verifyEqual(string(airss{2}, "yyyy-MM-dd"), ...
                string(oracle.airss_date));
            potentials = provider.get_pspots();
            testCase.verifyEqual(potentials.Co, string(oracle.pspots.Co));
            testCase.verifyEqual(potentials.C, string(oracle.pspots.C));
        end

        function spinFixturePreservesLastColumn(testCase)
            oracle = testCase.oracle().spins;
            provider = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_file(testCase.fixture("spins-in-last-col.res"));
            testCase.verifyEqual(provider.seed, string(oracle.seed));
            testCase.verifyEqual(provider.structure.num_sites, ...
                oracle.site_count);
            moments = cellfun(@(site) site.site_properties.magmom, ...
                provider.sites);
            testCase.verifyEqual(moments, ...
                reshape(oracle.magmoms, 1, []), AbsTol = 1e-12);
            sfac = kssolv.analysis.matgenlab.io.res.ResWriter. ...
                sfac_from_sites(provider.sites);
            testCase.verifyEqual(sfac.species, ...
                reshape(string(oracle.sfac_species), 1, []));
            testCase.verifyTrue(endsWith(string(sfac), "END" + newline));
        end

        function writerAndResIOAreReversible(testCase)
            source = string(fileread( ...
                testCase.fixture("coc-115925-9326-14.res")));
            provider = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_str(source);
            structureText = ...
                kssolv.analysis.matgenlab.io.res.ResIO. ...
                structure_to_str(provider.structure);
            testCase.verifyTrue(startsWith(structureText, ...
                "TITL" + newline + "CELL 1.00000"));
            testCase.verifyTrue(endsWith(structureText, newline));
            structure = kssolv.analysis.matgenlab.io.res.ResIO. ...
                structure_from_str(structureText);
            testCase.verifyEqual(structure.frac_coords, ...
                provider.structure.frac_coords, AbsTol = 5e-9);

            entry = provider.entry;
            first = kssolv.analysis.matgenlab.io.res.ResIO. ...
                entry_to_str(entry);
            secondEntry = kssolv.analysis.matgenlab.io.res.ResIO. ...
                entry_from_str(first);
            second = kssolv.analysis.matgenlab.io.res.ResIO. ...
                entry_to_str(secondEntry);
            testCase.verifyEqual(second, first);
            testCase.verifyEqual(secondEntry.energy, entry.energy);
            testCase.verifyTrue(endsWith(first, newline));
        end

        function fileAndGzipIOAreEquivalent(testCase)
            provider = kssolv.analysis.matgenlab.io.res.ResProvider. ...
                from_file(testCase.fixture("coc-115925-9326-14.res"));
            plain = string(tempname) + ".res";
            compressed = string(tempname) + ".res.gz";
            entryFile = string(tempname) + "-entry.res";
            cleanup = onCleanup(@() testCase.removeFiles( ...
                [plain, compressed, entryFile]));
            kssolv.analysis.matgenlab.io.res.ResIO. ...
                structure_to_file(provider.structure, plain);
            kssolv.analysis.matgenlab.io.res.ResIO. ...
                structure_to_file(provider.structure, compressed);
            first = kssolv.analysis.matgenlab.io.res.ResIO. ...
                structure_from_file(plain);
            second = kssolv.analysis.matgenlab.io.res.ResIO. ...
                structure_from_file(compressed);
            testCase.verifyEqual(first.frac_coords, second.frac_coords, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(first.lattice.matrix, ...
                second.lattice.matrix, AbsTol = 1e-12);
            airss = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_file(testCase.fixture("coc-115925-9326-14.res"));
            kssolv.analysis.matgenlab.io.res.ResIO. ...
                entry_to_file(airss.entry, entryFile);
            restoredEntry = kssolv.analysis.matgenlab.io.res.ResIO. ...
                entry_from_file(entryFile);
            testCase.verifyEqual(restoredEntry.energy, airss.energy);
            clear cleanup
        end

        function msonRoundTripsBothProviders(testCase)
            provider = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_file(testCase.fixture("coc-115925-9326-14.res"), ...
                "strict");
            verbose = provider.as_dict(true);
            testCase.verifyEqual(sort(string(fieldnames(verbose))), ...
                sort(["x_module"; "x_class"; "res"; "parse_rems"]));
            restored = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_dict(verbose);
            testCase.verifyEqual(restored.as_dict(true), verbose);
            decoded = jsondecode(char(provider.toJSON()));
            jsonRestored = ...
                kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_dict(decoded);
            testCase.verifyEqual(jsonRestored.seed, provider.seed);
            testCase.verifyEqual(jsonRestored.structure.frac_coords, ...
                provider.structure.frac_coords, AbsTol = 1e-12);
            compact = provider.as_dict(false);
            testCase.verifyEqual(numel(fieldnames(compact)), 10);
            testCase.verifyEqual(compact.seed, provider.seed);
            base = kssolv.analysis.matgenlab.io.res.ResProvider. ...
                from_file(testCase.fixture("coc-115925-9326-14.res"));
            baseRoundTrip = ...
                kssolv.analysis.matgenlab.io.res.ResProvider. ...
                from_dict(base.as_dict());
            testCase.verifyEqual(baseRoundTrip.structure.frac_coords, ...
                base.structure.frac_coords, AbsTol = 1e-12);
        end

        function malformedAndStrictErrorsMatchContract(testCase)
            parser = kssolv.analysis.matgenlab.io.res.ResParser();
            testCase.verifyEqual(parser.line, 0);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.res.ResParser. ...
                parse_str("TITL" + newline + ...
                "CELL 1 2 3" + newline + "SFAC C" + newline + "END"), ...
                "KSSOLV:Matgenlab:ResParseError");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.res.ResParser. ...
                parse_str("CELL 1 1 1 1 90 90 90" + newline + ...
                "SFAC C" + newline + "C 1 0 0 0 1"), ...
                "KSSOLV:Matgenlab:ResParseError");
            bare = "TITL seed 0 1 -1 0 0" + newline + ...
                "CELL 1 1 1 1 90 90 90" + newline + ...
                "LATT -1" + newline + "SFAC H" + newline + ...
                "H 1 0 0 0 1" + newline + "END" + newline;
            gentle = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_str(bare);
            testCase.verifyEmpty(gentle.get_castep_version());
            strict = kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_str(bare, "strict");
            testCase.verifyError(@() strict.get_castep_version(), ...
                "KSSOLV:Matgenlab:ResParseError");
            noTitle = erase(bare, "TITL seed 0 1 -1 0 0" + newline);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_str(noTitle), "KSSOLV:Matgenlab:ResError");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.res.AirssProvider. ...
                from_str(bare, "invalid"), ...
                "KSSOLV:Matgenlab:AirssProvider:ParseMode");
        end
    end

    methods (Static, Access = private)
        function verifyMembers(className, expected)
            metadata = meta.class.fromName(className);
            available = [string({metadata.MethodList.Name}), ...
                string({metadata.PropertyList.Name})];
            if ~all(ismember(expected, available))
                error("KSSOLV:Matgenlab:ResTest:Inventory", ...
                    "Missing members in %s: %s", className, ...
                    strjoin(expected(~ismember(expected, available)), ", "));
            end
        end

        function value = fixture(name)
            here = fileparts(mfilename("fullpath"));
            value = fullfile(here, "+fixtures", "+res", name);
        end

        function value = oracle()
            value = jsondecode(fileread( ...
                kssolv.analysis.matgenlab.test.io. ...
                ResFrozenOracleTest.fixture("res_oracle.json")));
        end

        function removeFiles(files)
            for file = files
                if isfile(file), delete(file); end
            end
        end
    end
end
