classdef VaspOpticsInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function frozenNumericalFunctions(testCase)
            root = fileparts(fileparts(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath")))))));
            oracle = jsondecode(fileread(fullfile(root, "dev", ...
                "matgenlab", "oracles", ...
                "vasp_optics_2026.7.24.json")));
            testCase.verifyEqual(oracle.index_base, 1);
            x = reshape(oracle.x, 1, []);
            for order = 0:3
                field = "x" + order;
                actual = kssolv.analysis.matgenlab.io.vasp.optics. ...
                    delta_methfessel_paxton(x, order);
                testCase.verifyEqual(actual, ...
                    reshape(oracle.delta_mp.(field), 1, []), ...
                    "AbsTol", 2e-14);
                actual = kssolv.analysis.matgenlab.io.vasp.optics. ...
                    step_methfessel_paxton(x, order);
                testCase.verifyEqual(actual, ...
                    reshape(oracle.step_mp.(field), 1, []), ...
                    "AbsTol", 2e-14);
            end
            orders = [-1, 0, 1, 3];
            fields = ["x_1", "x0", "x1", "x3"];
            for index = 1:numel(orders)
                actual = kssolv.analysis.matgenlab.io.vasp.optics. ...
                    delta_func(x, orders(index));
                testCase.verifyEqual(actual, ...
                    reshape(oracle.delta.(fields(index)), 1, []), ...
                    "AbsTol", 2e-14);
                actual = kssolv.analysis.matgenlab.io.vasp.optics. ...
                    step_func(x, orders(index));
                testCase.verifyEqual(actual, ...
                    reshape(oracle.step.(fields(index)), 1, []), ...
                    "AbsTol", 2e-14);
            end
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.vasp.optics.get_delta( ...
                0.85, 0.2, 12, 0.1, 2), ...
                reshape(oracle.get_delta, 1, []), "AbsTol", 2e-14);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.vasp.optics.get_step( ...
                0.85, 0.2, 12, 0.1, 2), ...
                reshape(oracle.get_step, 1, []), "AbsTol", 2e-14);
            expected = complex( ...
                reshape(oracle.kramers_kronig.real, 1, []), ...
                reshape(oracle.kramers_kronig.imag, 1, []));
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.vasp.optics. ...
                kramers_kronig([0, 0.3, 1.2, 0.4, 0.1], ...
                5, 0.2, -0.1), expected, "AbsTol", 2e-14);
        end

        function errorSemantics(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.optics. ...
                delta_func(0, -2), ...
                "KSSOLV:Matgenlab:Optics:UnsupportedSmearing");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.optics. ...
                step_func(0, -2), ...
                "KSSOLV:Matgenlab:Optics:UnsupportedSmearing");
        end

        function officialVaspFixture(testCase)
            fixture = fullfile(fileparts(mfilename("fullpath")), ...
                "+fixtures", "+vasp_optics", "reproduce_eps");
            calculator = kssolv.analysis.matgenlab.io.vasp.optics. ...
                DielectricFunctionCalculator.from_directory(fixture);
            vrun = kssolv.analysis.matgenlab.io.vasp.Vasprun( ...
                fullfile(fixture, "vasprun.xml"));
            [grid, epsilon] = calculator.get_epsilon(1, 1);
            testCase.verifyEqual(grid(1), 0, "AbsTol", 1e-14);
            testCase.verifyEqual(grid(end), 59.3802, "AbsTol", 1e-9);
            testCase.verifyNumElements(grid, 3000);
            reference = vrun.dielectric;
            realReference = reference{2}(:, 1).';
            relative = max(abs(realReference - real(epsilon))) / ...
                max(abs(real(epsilon)));
            testCase.verifyLessThan(relative, 0.01);
            zeroMask = zeros(size(calculator.cder));
            [~, zeroEpsilon] = calculator.get_epsilon(1, 1, ...
                mask = zeroMask);
            testCase.verifyLessThan(max(abs(imag(zeroEpsilon))), 1e-10);
            [~, offDiagonal] = calculator.get_epsilon(1, 2);
            testCase.verifyLessThan(max(abs(offDiagonal)), 0.1);
            [xValue, yValue, labels] = calculator. ...
                plot_weighted_transition_data(1, 1, ...
                mask = ones(size(calculator.cder)), min_val = 0.001);
            testCase.verifyNumElements(yValue, numel(xValue));
            testCase.verifyNumElements(labels, numel(xValue));
            testCase.verifyNotEmpty(xValue);
            serialized = calculator.as_dict();
            testCase.verifyEqual(serialized.x_class, ...
                "DielectricFunctionCalculator");
        end
    end
end
