classdef VaspInputsFrozenOracleTest < matlab.unittest.TestCase
    % Static pymatgen-core 2026.7.24 parity for VASP input objects.

    methods (Test)
        function officialIncarMatchesOracle(testCase)
            [folder, oracle] = testCase.fixture();
            incar = kssolv.analysis.matgenlab.io.vasp.Incar. ...
                from_file(fullfile(folder, "INCAR"));
            testCase.verifyEqual(incar.get_str(sort_keys = true), ...
                string(oracle.incar.sorted));
            testCase.verifyEqual(incar.get_str( ...
                sort_keys = true, pretty = true), ...
                string(oracle.incar.pretty));
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.vasp.Incar. ...
                proc_val("LREAL", "Auto"), ...
                string(oracle.incar.proc.LREAL));
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.vasp.Incar. ...
                proc_val("MAGMOM", "2*5.0 1*-1.0"), ...
                double(oracle.incar.proc.MAGMOM).');
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.vasp.Incar. ...
                proc_val("LATTICE_CONSTRAINTS", "T F T"), ...
                logical(oracle.incar.proc.LATTICE_CONSTRAINTS).');
            restored = kssolv.analysis.matgenlab.io.vasp.Incar. ...
                from_dict(incar.as_dict());
            testCase.verifyEqual(restored, incar);
        end

        function officialPoscarMatchesOracle(testCase)
            [folder, oracle] = testCase.fixture();
            poscar = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_file(fullfile(folder, "POSCAR"), ...
                check_for_potcar = false);
            testCase.verifyEqual(poscar.site_symbols, ...
                string(oracle.poscar.site_symbols).');
            testCase.verifyEqual(poscar.natoms, ...
                double(oracle.poscar.natoms).');
            testCase.verifyEqual(poscar.get_str( ...
                significant_figures = 12), ...
                string(oracle.poscar.str12));
            testCase.verifyEqual(poscar.get_str( ...
                significant_figures = 4), ...
                string(oracle.poscar.str4));
            testCase.verifyEqual(poscar.get_str( ...
                direct = false, significant_figures = 12), ...
                string(oracle.poscar.cart12));
            restored = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_dict(poscar.as_dict());
            testCase.verifyEqual(restored.get_str( ...
                significant_figures = 12), ...
                string(oracle.poscar.str12));
        end

        function allOfficialKpointsFilesMatchOracle(testCase)
            [folder, oracle] = testCase.fixture();
            names = ["KPOINTS","KPOINTS_auto","KPOINTS_band", ...
                "KPOINTS_cartesian","KPOINTS_explicit", ...
                "KPOINTS_explicit_tet","KPOINTS_gamma"];
            for name = names
                points = kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    from_file(fullfile(folder, name));
                reference = oracle.kpoints.(char(name));
                testCase.verifyEqual(string(points), ...
                    string(reference.string), ...
                    "KPOINTS text differs for " + name);
                restored = kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    from_dict(points.as_dict());
                testCase.verifyEqual(restored, points);
            end
        end

        function constructorFamilyMatchesOracle(testCase)
            [folder, oracle] = testCase.fixture();
            structure = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_file(fullfile(folder, "POSCAR"), ...
                check_for_potcar = false).structure;
            previous = warning("off", ...
                "KSSOLV:Matgenlab:Kpoints:KspacingPreferred");
            cleanup = onCleanup(@() warning(previous));
            pathData = struct();
            pathData.kpoints = struct("G",[0,0,0], ...
                "X",[0.5,0,0],"L",[0.5,0.5,0.5]);
            pathData.path = {{"G","X","L"}};
            ibz = struct("kpath", pathData);
            constructors = {
                "default", kssolv.analysis.matgenlab.io.vasp.Kpoints()
                "positional", kssolv.analysis.matgenlab.io.vasp.Kpoints( ...
                    "positional",0,"Monkhorst",[4,6,8],[0.5,0.5,0.5])
                "automatic", kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    automatic(25)
                "gamma", kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    gamma_automatic([3,5,7],[0.5,0,0])
                "monkhorst", kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    monkhorst_automatic([4,6,8])
                "density", kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    automatic_density(structure,1000)
                "gamma_density", ...
                    kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    automatic_gamma_density(structure,1000)
                "density_vol", ...
                    kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    automatic_density_by_vol(structure,64)
                "density_lengths", ...
                    kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    automatic_density_by_lengths(structure,[20,30,40])
                "linemode", ...
                    kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                    automatic_linemode(20,ibz)
                };
            for index = 1:size(constructors, 1)
                name = constructors{index, 1};
                points = constructors{index, 2};
                testCase.verifyEqual(string(points), ...
                    string(oracle.kpoint_constructors.(name).string), ...
                    "Constructor output differs for " + name);
            end
            clear cleanup
        end

        function syntheticPotcarMetadataMatchesOracle(testCase)
            [~, oracle] = testCase.fixture();
            previous = warning("off", ...
                "KSSOLV:Matgenlab:UnknownPotcarWarning");
            cleanup = onCleanup(@() warning(previous));
            single = kssolv.analysis.matgenlab.io.vasp.PotcarSingle( ...
                testCase.syntheticPotcar());
            reference = oracle.potcar_single;
            testCase.verifyEqual(single.header, string(reference.header));
            testCase.verifyEqual(single.element, string(reference.element));
            testCase.verifyEqual(single.atomic_no, ...
                double(reference.atomic_no));
            testCase.verifyEqual(single.nelectrons, ...
                double(reference.nelectrons));
            testCase.verifyEqual(single.symbol, string(reference.symbol));
            testCase.verifyEqual(single.potential_type, ...
                string(reference.potential_type));
            testCase.verifyEqual(single.functional, ...
                string(reference.functional));
            testCase.verifyEqual(single.functional_class, ...
                string(reference.functional_class));
            testCase.verifyEqual(single.is_valid, reference.is_valid);
            expected = reference.electron_configuration;
            actual = single.electron_configuration;
            testCase.verifyEqual(size(actual, 1), numel(expected));
            for index = 1:size(actual, 1)
                testCase.verifyEqual(actual{index, 1}, ...
                    double(expected{index}{1}));
                testCase.verifyEqual(string(actual{index, 2}), ...
                    string(expected{index}{2}));
                testCase.verifyEqual(actual{index, 3}, ...
                    double(expected{index}{3}), AbsTol = 1e-12);
            end
            copy = single.copy();
            testCase.verifyEqual(copy.data, single.data);
            clear cleanup
        end

        function vaspInputSerializationAndSpecBoundary(testCase)
            [folder, oracle] = testCase.fixture();
            incar = kssolv.analysis.matgenlab.io.vasp.Incar. ...
                from_file(fullfile(folder, "INCAR"));
            poscar = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_file(fullfile(folder, "POSCAR"), ...
                check_for_potcar = false);
            points = kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                gamma_automatic([3,5,7],[0.5,0,0]);
            inputs = kssolv.analysis.matgenlab.io.vasp.VaspInput( ...
                incar, points, poscar, "Fe", potcar_spec = true);
            testCase.verifyEqual(inputs.keys(), ...
                string(oracle.vasp_input.keys).');
            restored = kssolv.analysis.matgenlab.io.vasp.VaspInput. ...
                from_dict(inputs.as_dict());
            testCase.verifyEqual(restored.keys(), inputs.keys());
            testCase.verifyEqual(restored.incar, inputs.incar);
            testCase.verifyEqual(restored.kpoints, inputs.kpoints);
            testCase.verifyEqual(string(restored.potcar), "Fe");
        end

        function invalidInputsHaveStableErrors(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.Kpoints( ...
                "bad",1,"Reciprocal",[0,0,0]), ...
                "KSSOLV:Matgenlab:Kpoints:ExplicitMetadata");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.Kpoints( ...
                comment = "x", unknown = 1), ...
                "KSSOLV:Matgenlab:Kpoints:Option");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                automatic_density_by_lengths( ...
                kssolv.analysis.matgenlab.core.Structure( ...
                eye(3),{"H"},[0,0,0]), [1,2]), ...
                "KSSOLV:Matgenlab:Kpoints:LengthDensities");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.KpointsSupportedModes. ...
                from_str("invalid"), ...
                "KSSOLV:Matgenlab:Kpoints:InvalidMode");
        end

        function potcarCollectionIoAndAuthorizationBoundary(testCase)
            previousWarning = warning("off", ...
                "KSSOLV:Matgenlab:UnknownPotcarWarning");
            warningCleanup = onCleanup(@() warning(previousWarning));
            raw = testCase.syntheticPotcar();
            collection = kssolv.analysis.matgenlab.io.vasp.Potcar. ...
                from_str(raw + raw);
            folder = string(tempname);
            mkdir(folder);
            folderCleanup = onCleanup(@() rmdir(folder, "s"));
            filename = fullfile(folder, "POTCAR");
            collection.write_file(filename);
            restored = kssolv.analysis.matgenlab.io.vasp.Potcar. ...
                from_file(filename);
            testCase.verifyEqual(restored.symbols, ["Fe","Fe"]);
            specFile = fullfile(folder, "POTCAR.spec.json.gz");
            collection.write_potcar_spec(specFile);
            testCase.verifyTrue(isfile(specFile));
            testCase.verifyEqual(numel(collection.spec), 2);
            singleFile = fullfile(folder, "POTCAR.Fe");
            collection(1).write_file(singleFile);
            singleRestored = ...
                kssolv.analysis.matgenlab.io.vasp.PotcarSingle. ...
                from_file(singleFile);
            testCase.verifyEqual(singleRestored.symbol, "Fe");
            [functions, symbols] = collection(1).identify_potcar();
            testCase.verifyEmpty(functions);
            testCase.verifyEmpty(symbols);
            stats = collection(1).summary_stats;
            testCase.verifyTrue( ...
                kssolv.analysis.matgenlab.io.vasp.PotcarSingle. ...
                compare_potcar_stats(stats, stats));
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.Potcar. ...
                from_spec(collection.spec), ...
                "KSSOLV:Matgenlab:Potcar:SpecMismatch");

            previousDirectory = getenv("PMG_VASP_PSP_DIR");
            directoryCleanup = onCleanup(@() setenv( ...
                "PMG_VASP_PSP_DIR", previousDirectory));
            setenv("PMG_VASP_PSP_DIR", "");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp.Potcar. ...
                from_dict(collection.as_dict()), ...
                "KSSOLV:Matgenlab:PmgVaspPspDirError");
            clear directoryCleanup folderCleanup warningCleanup
        end

        function vaspInputOptionalFilesCopyAndRun(testCase)
            [folder, ~] = testCase.fixture();
            incar = kssolv.analysis.matgenlab.io.vasp.Incar. ...
                from_file(fullfile(folder, "INCAR"));
            poscar = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_file(fullfile(folder, "POSCAR"), ...
                check_for_potcar = false);
            points = kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                gamma_automatic();
            inputs = kssolv.analysis.matgenlab.io.vasp.VaspInput( ...
                incar, points, poscar, "Si", potcar_spec = true, ...
                README = "optional");
            testCase.verifyEqual(inputs.get("README"), "optional");
            shallow = inputs.copy(false);
            deep = inputs.copy(true);
            testCase.verifyEqual(shallow.get("README"), "optional");
            testCase.verifyEqual(deep.get("README"), "optional");
            runFolder = string(tempname);
            cleanup = onCleanup(@() rmdir(runFolder, "s"));
            inputs.run_vasp(run_dir = runFolder, ...
                vasp_cmd = ["/bin/sh","-c","echo native-run"], ...
                output_file = "vasp.out", err_file = "vasp.err");
            testCase.verifySubstring(string(fileread( ...
                fullfile(runFolder, "vasp.out"))), "native-run");
            clear cleanup
        end

        function reexportedTypesAndWarningCategories(testCase)
            orbital = kssolv.analysis.matgenlab.electronic_structure. ...
                Orbital.dyz;
            testCase.verifyEqual(double(orbital), 5);
            testCase.verifyEqual(string(orbital), "dyz");
            description = kssolv.analysis.matgenlab.io.vasp. ...
                OrbitalDescription(2, -3.8, 23, 2.3);
            values = double(description);
            testCase.verifyEqual(values(1:4), [2,-3.8,23,2.3], ...
                AbsTol = 1e-12);
            classes = {
                kssolv.analysis.matgenlab.io.vasp. ...
                    BadPoscarWarning.identifier, ...
                    "KSSOLV:Matgenlab:BadPoscarWarning"
                kssolv.analysis.matgenlab.io.vasp. ...
                    BadIncarWarning.identifier, ...
                    "KSSOLV:Matgenlab:BadIncarWarning"
                kssolv.analysis.matgenlab.io.vasp. ...
                    UnknownPotcarWarning.identifier, ...
                    "KSSOLV:Matgenlab:UnknownPotcarWarning"
                kssolv.analysis.matgenlab.io.vasp. ...
                    PmgVaspPspDirError.identifier, ...
                    "KSSOLV:Matgenlab:PmgVaspPspDirError"
                };
            for index = 1:size(classes, 1)
                testCase.verifyEqual(classes{index, 1}, ...
                    classes{index, 2});
            end
        end
    end

    methods (Static, Access = private)
        function [folder, oracle] = fixture()
            folder = fullfile(fileparts(mfilename("fullpath")), ...
                "+fixtures", "+vasp_inputs");
            oracle = jsondecode(fileread(fullfile(folder, ...
                "oracle_inputs_2026_7_24.json")));
        end

        function text = syntheticPotcar()
            text = strjoin([
                "PAW_PBE Fe 01Jan2000"
                "parameters from PSCTR are:"
                "VRHFIN = Fe: 3d4s;"
                "LEXCH = PE;"
                "TITEL = PAW_PBE Fe 01Jan2000;"
                "LULTRA = F;"
                "LPAW = T;"
                "POMASS = 55.0;"
                "ZVAL = 8;"
                "ENMAX = 300.0;"
                "Atomic configuration"
                "2 entries"
                "n l j E occ."
                "3 2 2.5 -4.0 7.0"
                "4 0 0.5 -3.0 1.0"
                "Description"
                "2 -4.0 23 2.3"
                "Error from kinetic energy argument (eV)"
                "END of PSCTR-controll parameters"
                "Local Part"
                "1.0 2.0 True"
                "End of Dataset"
                ], newline) + newline;
        end
    end
end
