classdef VaspOutputsFrozenOracleTest < matlab.unittest.TestCase
    % Frozen pymatgen-core 2026.7.24 parity for VASP output readers.

    methods (Test)
        function vasprunFamilyMatchesOracle(testCase)
            [folder, oracle] = testCase.fixture();
            run = kssolv.analysis.matgenlab.io.vasp.Vasprun( ...
                fullfile(folder, "vasprun.Al.xml.gz"), ...
                parse_potcar_file = false);
            expected = oracle.vasprun_al;
            testCase.verifyEqual(run.final_energy, ...
                expected.final_energy, AbsTol = 1e-10);
            testCase.verifyEqual(run.run_type, string(expected.run_type));
            testCase.verifyEqual(run.converged_electronic, ...
                expected.converged_electronic);
            testCase.verifyEqual(run.converged_ionic, ...
                expected.converged_ionic);
            testCase.verifyEqual(run.converged, expected.converged);
            testCase.verifyEqual(run.is_spin, expected.is_spin);
            testCase.verifyEqual(run.is_hubbard, expected.is_hubbard);
            testCase.verifyEmpty(fieldnames(run.hubbards));
            testCase.verifyEqual(run.md_n_steps, expected.md_n_steps);
            testCase.verifyEqual(run.nionic_steps, expected.nionic_steps);
            testCase.verifyEqual(run.efermi, ...
                expected.efermi, AbsTol = 1e-10);
            testCase.verifyEqual(numel(run.structures), ...
                expected.structure_count);
            testCase.verifyEqual(run.final_structure.volume, ...
                expected.final_volume, AbsTol = 1e-10);
            testCase.verifyEqual(size(run.actual_kpoints, 1), ...
                expected.actual_kpoints);

            properties = run.eigenvalue_band_properties;
            testCase.verifyEqual(cell2mat(properties(1:3)), ...
                [expected.band_properties{1:3}], AbsTol = 1e-10);
            testCase.verifyEqual(properties{4}, ...
                expected.band_properties{4});
            testCase.verifyEqual(run.calculate_efermi(), ...
                expected.efermi, AbsTol = 1e-10);

            entry = run.get_computed_entry();
            testCase.verifyEqual(entry.energy, ...
                expected.final_energy, AbsTol = 1e-10);
            scalarEntry = run.get_computed_entry(inc_structure = false);
            testCase.verifyEqual(scalarEntry.energy, entry.energy);
            trajectory = run.get_trajectory();
            testCase.verifyEqual(length(trajectory), ...
                expected.trajectory_count);
            testCase.verifyEqual(trajectory(1).volume, ...
                expected.trajectory_first_volume, AbsTol = 1e-10);
            bands = run.get_band_structure();
            testCase.verifyEqual(numel(bands.kpoints), ...
                expected.actual_kpoints);
            testCase.verifyEqual(bands.efermi, expected.efermi);
            testCase.verifyNotEmpty(run.complete_dos);
            testCase.verifyNotEmpty(run.complete_dos_normalized);
            testCase.verifyEmpty(run.get_potcars(false));
            run.update_potcar_spec(false);
            run.update_charge_from_potcar(false);
            dictionary = run.as_dict();
            testCase.verifyTrue(isfield(dictionary, "input"));
            testCase.verifyTrue(isfield(dictionary, "output"));

            previous = warning("off", ...
                "KSSOLV:Matgenlab:Vasprun:DeprecatedSpelling");
            cleanup = onCleanup(@() warning(previous));
            run.projected_magnetisation = [];
            testCase.verifyEmpty(run.projected_magnetisation);
            clear cleanup

            compact = kssolv.analysis.matgenlab.io.vasp.BSVasprun( ...
                fullfile(folder, "vasprun.Al.xml.gz"), false, false);
            compactDictionary = compact.as_dict();
            testCase.verifyTrue(compactDictionary.has_vasp_completed);
        end

        function dielectricAndPropertyContainersMatchOracle(testCase)
            [folder, oracle] = testCase.fixture();
            run = kssolv.analysis.matgenlab.io.vasp.Vasprun( ...
                fullfile(folder, "vasprun.dielectric.xml.gz"), ...
                parse_potcar_file = false);
            expected = oracle.vasprun_dielectric;
            dielectric = run.dielectric;
            testCase.verifyEqual(numel(dielectric{1}), ...
                expected.point_count);
            testCase.verifyEqual(dielectric{1}(1), ...
                expected.first_energy, AbsTol = 1e-12);
            testCase.verifyEqual(dielectric{2}(1, :), ...
                double(expected.first_real).', AbsTol = 1e-12);
            testCase.verifyEqual(dielectric{3}(1, :), ...
                double(expected.first_imag).', AbsTol = 1e-12);
            absorption = run.optical_absorption_coeff;
            testCase.verifyEqual(absorption(1), ...
                expected.first_absorption, AbsTol = 1e-12);
            testCase.verifyEqual(numel(absorption), expected.point_count);

            options = kssolv.analysis.matgenlab.io.vasp.KpointOptProps();
            options.projected_magnetisation = ones(2);
            testCase.verifyEqual(options.projected_magnetisation, ones(2));
            gap = kssolv.analysis.matgenlab.io.vasp.BandgapProps( ...
                vbm = 1, cbm = 2, efermi = 1.5);
            testCase.verifyEqual(gap.as_dict().cbm, 2);
            testCase.verifyClass( ...
                kssolv.analysis.matgenlab.io.vasp.VaspParseError(), ...
                "kssolv.analysis.matgenlab.io.vasp.VaspParseError");
            testCase.verifyClass( ...
                kssolv.analysis.matgenlab.io.vasp. ...
                UnconvergedVASPWarning(), ...
                "kssolv.analysis.matgenlab.io.vasp." + ...
                "UnconvergedVASPWarning");
        end

        function outcarReadersMatchOfficialFixtures(testCase)
            [folder, oracle] = testCase.fixture();
            outcar = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR.Al"));
            expected = oracle.outcar_al;
            testCase.verifyEqual(outcar.efermi, ...
                expected.efermi, AbsTol = 1e-12);
            testCase.verifyEqual(outcar.final_energy, ...
                expected.final_energy, AbsTol = 1e-12);
            testCase.verifyEqual(outcar.nelect, expected.nelect);
            testCase.verifyEqual(outcar.total_mag, ...
                expected.total_mag, AbsTol = 1e-14);
            testCase.verifyEqual(numel(outcar.charge), ...
                expected.charge_count);
            testCase.verifyEqual(outcar.run_stats.cores, expected.cores);
            testCase.verifyNotEmpty(outcar.as_dict());
            outcar.read_pattern(struct("fermi", ...
                'E-fermi\s*:\s*([-+0-9.Ee]+)'), true, true, @str2double);
            testCase.verifyNotEmpty(outcar.data.fermi);
            table = outcar.read_table_pattern( ...
                "\(the norm of the test charge is\s+[\.\-\d]+\)", ...
                "((?:\s+\d+\s*[\.\-\d]+)+)", "\s+E-fermi :", ...
                @string, "", true, false);
            testCase.verifyNotEmpty(table);
            outcar.read_electrostatic_potential();
            testCase.verifyNotEmpty(outcar.electrostatic_potential);
            outcar.read_neb();
            outcar.read_igpar();

            optics = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR.LOPTICS"));
            optics.read_freq_dielectric();
            testCase.verifyEqual(optics.dielectric_energies(1), ...
                0, AbsTol = 1e-12);
            testCase.verifyEqual(optics.dielectric_energies(end), ...
                39.826101, AbsTol = 1e-6);
            testCase.verifyEqual( ...
                real(optics.dielectric_tensor_function(1, 1, 1)), ...
                8.969388, AbsTol = 1e-6);

            response = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR.lepsilon.gz"));
            response.read_internal_strain_tensor();
            response.read_lepsilon();
            response.read_lepsilon_ionic();
            response.read_piezo_tensor();
            testCase.verifyEqual(response.dielectric_tensor(1, 1), ...
                3.716432, AbsTol = 1e-6);
            testCase.verifyEqual(response.piezo_tensor(1, 1), ...
                0.52799, AbsTol = 1e-5);
            testCase.verifyNotEmpty(response.read_avg_core_poten());

            polar = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR.BaTiO3.polar"));
            polar.read_lcalcpol();
            polar.read_pseudo_zval();
            testCase.verifyEqual(polar.p_ion, ...
                [0, 0, -5.56684], AbsTol = 1e-5);
            testCase.verifyEqual(polar.zval_dict.Ba, 10);

            elastic = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR.total_tensor.Li2O.gz"));
            elastic.read_elastic_tensor();
            testCase.verifyEqual(elastic.elastic_tensor(1, 1), ...
                1986.3391, AbsTol = 1e-4);
            core = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR.icorelevel"));
            states = core.read_core_state_eigen();
            testCase.verifyEqual(states{5}.x3d(end), ...
                -31.4522, AbsTol = 1e-4);
            contact = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR_fc"));
            contact.read_fermi_contact_shift();
            testCase.verifyNotEmpty(contact.data.fermi_contact_shift);
            vacuum = kssolv.analysis.matgenlab.io.vasp.Outcar( ...
                fullfile(folder, "OUTCAR.vacuum_potentials.gz"));
            vacuum.read_vacuum_potentials();
            testCase.verifyEqual(vacuum.data.vacuum_potential_upper, ...
                1.778, AbsTol = 1e-3);

            outcar.read_corrections();
            outcar.read_chemical_shielding();
            outcar.read_cs_g0_contribution();
            outcar.read_cs_core_contribution();
            outcar.read_nmr_efg();
            testCase.verifyEmpty(outcar.read_nmr_efg_tensor());
            outcar.read_onsite_density_matrices();
            testCase.verifyError(@() outcar. ...
                read_cs_raw_symmetrized_tensors(), ...
                "KSSOLV:Matgenlab:Outcar:NmrTensor");
        end

        function volumetricReadersAndWritersRoundTrip(testCase)
            [folder, oracle] = testCase.fixture();
            expected = oracle.volumetric;
            charge = kssolv.analysis.matgenlab.io.vasp.Chgcar. ...
                from_file(fullfile(folder, "CHGCAR.nospin.gz"));
            testCase.verifyEqual(charge.dim, ...
                double(expected.chgcar_dim).');
            testCase.verifyEqual(charge.data.total(1), ...
                expected.chgcar_first, AbsTol = 1e-12);
            testCase.verifyEmpty(charge.net_magnetization);
            [poscar, data, augmentation] = ...
                kssolv.analysis.matgenlab.io.vasp.VolumetricData. ...
                parse_file(fullfile(folder, "CHGCAR.nospin.gz"));
            testCase.verifyEqual(data.total, charge.data.total);
            testCase.verifyNotEmpty(poscar);
            testCase.verifyTrue(isfield(augmentation, "total"));

            potential = kssolv.analysis.matgenlab.io.vasp.Locpot. ...
                from_file(fullfile(folder, "LOCPOT.gz"));
            testCase.verifyEqual(potential.dim, ...
                double(expected.locpot_dim).');
            testCase.verifyEqual(potential.data.total(1), ...
                expected.locpot_first, AbsTol = 1e-12);
            testCase.verifyEqual(sum(potential.get_average_along_axis(1)), ...
                -217.05226954, AbsTol = 1e-8);
            axisGrid = potential.get_axis_grid(1);
            testCase.verifyEqual(axisGrid(end), 2.87629, AbsTol = 1e-2);

            elf = kssolv.analysis.matgenlab.io.vasp.Elfcar. ...
                from_file(fullfile(folder, "ELFCAR.gz"));
            testCase.verifyEqual(elf.dim, double(expected.elfcar_dim).');
            testCase.verifyEqual(elf.data.total(1), ...
                expected.elfcar_total_first, AbsTol = 1e-12);
            testCase.verifyEqual(elf.data.diff(1), ...
                expected.elfcar_diff_first, AbsTol = 1e-12);
            alpha = elf.get_alpha();
            testCase.verifyEqual(alpha.data.total(1), ...
                expected.elfcar_alpha_first, AbsTol = 1e-10);

            copy = potential.copy();
            testCase.verifyClass(copy, class(potential));
            combined = charge + charge;
            testCase.verifyEqual(combined.data.total, ...
                2 * charge.data.total, AbsTol = 1e-12);
            difference = combined - charge;
            testCase.verifyEqual(difference.data.total, ...
                charge.data.total, AbsTol = 1e-12);
            testCase.verifyEqual(charge.value_at(0, 0, 0), ...
                charge.data.total(1));
            testCase.verifySize(charge.linear_slice( ...
                [0, 0, 0], [0.5, 0.5, 0.5], 5), [5, 1]);

            temporary = string(tempname);
            mkdir(temporary);
            cleanup = onCleanup(@() rmdir(temporary, "s"));
            output = fullfile(temporary, "CHGCAR");
            charge.write_file(output);
            restored = kssolv.analysis.matgenlab.io.vasp.Chgcar. ...
                from_file(output);
            testCase.verifyEqual(restored.data.total, ...
                charge.data.total, AbsTol = 1e-12);
            clear cleanup
        end

        function compactOutputFormatsMatchOracle(testCase)
            [folder, oracle] = testCase.fixture();
            oszicar = kssolv.analysis.matgenlab.io.vasp.Oszicar( ...
                fullfile(folder, "OSZICAR"));
            expected = oracle.oszicar;
            testCase.verifyEqual(numel(oszicar.ionic_steps), ...
                expected.ionic_steps);
            testCase.verifyEqual(numel(oszicar.electronic_steps), ...
                expected.electronic_steps);
            testCase.verifyEqual(oszicar.final_energy, ...
                expected.final_energy, AbsTol = 1e-8);
            testCase.verifyEqual(oszicar.all_energies{end}, ...
                double(expected.last_all_energies).', AbsTol = 1e-9);
            testCase.verifyNotEmpty(oszicar.as_dict());

            matrix = kssolv.analysis.matgenlab.io.vasp.Dynmat( ...
                fullfile(folder, "DYNMAT"));
            expected = oracle.dynmat;
            testCase.verifyEqual(matrix.nspecs, expected.nspecs);
            testCase.verifyEqual(matrix.natoms, expected.natoms);
            testCase.verifyEqual(matrix.ndisps, expected.ndisps);
            testCase.verifyEqual(matrix.masses, ...
                double(expected.masses).');
            testCase.verifyEqual(matrix.get_phonon_frequencies(), ...
                double(expected.frequencies), AbsTol = 1e-10);

            eigen = kssolv.analysis.matgenlab.io.vasp.Eigenval( ...
                fullfile(folder, "EIGENVAL.gz"));
            expected = oracle.eigenval;
            testCase.verifyEqual([eigen.nelect, eigen.nkpt, ...
                eigen.nbands, eigen.ispin], ...
                [expected.nelect, expected.nkpt, ...
                expected.nbands, expected.ispin]);
            properties = eigen.eigenvalue_band_properties;
            testCase.verifyEqual(cell2mat(properties(1:3)), ...
                [expected.band_properties{1:3}], AbsTol = 1e-10);
            testCase.verifyEqual(properties{4}, ...
                expected.band_properties{4});

            spinEigen = kssolv.analysis.matgenlab.io.vasp.Eigenval( ...
                fullfile(folder, "EIGENVAL.ispin2.gz"));
            expected = oracle.eigenval_ispin2;
            testCase.verifyEqual([spinEigen.nelect, spinEigen.nkpt, ...
                spinEigen.nbands, spinEigen.ispin], ...
                [expected.nelect, expected.nkpt, ...
                expected.nbands, expected.ispin]);
        end

        function procarAndTrajectoryMatchOracle(testCase)
            [folder, oracle] = testCase.fixture();
            projection = kssolv.analysis.matgenlab.io.vasp.Procar( ...
                fullfile(folder, "PROCAR.simple"));
            expected = oracle.procar;
            testCase.verifyEqual([projection.nkpoints, ...
                projection.nbands, projection.nions, projection.nspins], ...
                [expected.nkpoints, expected.nbands, ...
                expected.nions, expected.nspins]);
            testCase.verifyEqual(projection.orbitals, ...
                string(expected.orbitals).');
            occupation = projection.get_occupation(1, "s");
            testCase.verifyEqual([occupation.up, occupation.down], ...
                double(expected.occupation_s_atom1).', AbsTol = 1e-12);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3), {"Li", "Li", "O"}, ...
                [0, 0, 0; 0.25, 0.25, 0.25; 0.5, 0.5, 0.5]);
            elementProjection = projection. ...
                get_projection_on_elements(structure);
            testCase.verifyTrue(isfield(elementProjection.up{1, 1}, "Li"));
            reread = projection.read(fullfile(folder, "PROCAR.simple"));
            testCase.verifyEqual(reread.nkpoints, projection.nkpoints);

            trajectory = kssolv.analysis.matgenlab.io.vasp.Xdatcar( ...
                fullfile(folder, "XDATCAR_traj_combine_test_2"));
            expected = oracle.xdatcar;
            testCase.verifyEqual(length(trajectory), ...
                expected.structure_count);
            testCase.verifyEqual(trajectory.site_symbols, ...
                string(expected.site_symbols).');
            testCase.verifyEqual(trajectory.natoms, ...
                double(expected.natoms).');
            testCase.verifyEqual(trajectory.comment, ...
                string(expected.comment));
            testCase.verifyEqual(trajectory.structures{1}.volume, ...
                expected.first_volume, AbsTol = 1e-10);
            testCase.verifyNotEmpty(trajectory.get_str(1, 3));
            shortened = kssolv.analysis.matgenlab.io.vasp.Xdatcar( ...
                fullfile(folder, "XDATCAR_traj_combine_test_2"), 1, 3);
            testCase.verifyEqual(length(shortened), 2);
            shortened.concatenate( ...
                fullfile(folder, "XDATCAR_traj_combine_test_2"), 1, 2);
            testCase.verifyEqual(length(shortened), 3);
            temporary = string(tempname);
            cleanup = onCleanup(@() testCase.deleteIfPresent(temporary));
            shortened.write_file(temporary);
            testCase.verifyTrue(isfile(temporary));
            clear cleanup
        end

        function waveReadersMatchOracle(testCase)
            [folder, oracle] = testCase.fixture();
            overlap = kssolv.analysis.matgenlab.io.vasp.WSWQ. ...
                from_file(fullfile(folder, "WSWQ.gz"));
            expected = oracle.wswq;
            testCase.verifyEqual([overlap.nspin, overlap.nkpoints, ...
                overlap.nbands], [expected.nspin, ...
                expected.nkpoints, expected.nbands]);
            testCase.verifyEqual(real(overlap.data(1)), ...
                expected.first_real, AbsTol = 1e-12);
            testCase.verifyEqual(imag(overlap.data(1)), ...
                expected.first_imag, AbsTol = 1e-12);

            derivative = kssolv.analysis.matgenlab.io.vasp.Waveder. ...
                from_binary(fullfile(folder, "WAVEDER"), "float64");
            expected = oracle.waveder;
            testCase.verifyEqual([derivative.nspin, ...
                derivative.nkpoints, derivative.nbands], ...
                [expected.nspin, expected.nkpoints, expected.nbands]);
            first = derivative. ...
                get_orbital_derivative_between_states(1, 1, 1, 1, 1);
            testCase.verifyEqual(real(first), ...
                expected.first_real_float64, AbsTol = 1e-114);
            testCase.verifyEqual(imag(first), ...
                expected.first_imag_float64, AbsTol = 1e-114);
            testCase.verifyEqual(real(derivative.cder(1)), real(first));
            testCase.verifyEqual(imag(derivative.cder(1)), imag(first));
            formatted = ...
                kssolv.analysis.matgenlab.io.vasp.Waveder. ...
                from_formatted(fullfile(folder, "WAVEDERF.Si.gz"));
            testCase.verifyEqual([formatted.nspin, formatted.nkpoints, ...
                formatted.nbands], [1, 47, 32]);

            wave = kssolv.analysis.matgenlab.io.vasp.Wavecar( ...
                fullfile(folder, "WAVECAR.N2"));
            expected = oracle.wavecar;
            testCase.verifyEqual([wave.spin, wave.nk, wave.nb], ...
                [expected.spin, expected.nk, expected.nb]);
            testCase.verifyEqual(wave.ng, double(expected.ng).');
            testCase.verifyEqual(wave.encut, expected.encut);
            testCase.verifyEqual(wave.efermi, ...
                expected.efermi, AbsTol = 1e-12);
            value = wave.evaluate_wavefunc(1, 1, [0, 0, 0]);
            testCase.verifyEqual(real(value), ...
                expected.wavefunc_first_real, AbsTol = 1e-12);
            testCase.verifyEqual(imag(value), ...
                expected.wavefunc_first_imag, AbsTol = 1e-12);
            mesh = wave.fft_mesh(1, 6);
            testCase.verifyEqual(max(abs(mesh), [], "all"), ...
                expected.band6_mesh_max, AbsTol = 1e-12);
            poscar = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_file(fullfile(folder, "POSCAR"), ...
                check_for_potcar = false);
            partial = wave.get_parchg(poscar, 1, 1, ...
                spin = 1, phase = false, scale = 1);
            testCase.verifyTrue(isfield(partial.data, "total"));
            temporary = string(tempname);
            mkdir(temporary);
            cleanup = onCleanup(@() rmdir(temporary, "s"));
            wave.write_unks(temporary);
            testCase.verifyTrue(isfile(fullfile(temporary, "UNK00001.1")));
            clear cleanup
        end

        function hdf5OutputReadersAndBoundaries(testCase)
            [folder, oracle] = testCase.fixture();
            output = kssolv.analysis.matgenlab.io.vasp.Vaspout( ...
                fullfile(folder, ...
                "vaspout.line_mode_band_structure.h5.gz"), ...
                store_potcar = false);
            expected = oracle.vaspout;
            testCase.verifyEqual(output.final_energy, ...
                expected.final_energy, AbsTol = 1e-10);
            testCase.verifyEqual(output.kpoints.num_kpts, ...
                expected.num_kpoints);
            testCase.verifyEqual(numel(output.ionic_steps), ...
                expected.ionic_steps);
            testCase.verifyEqual(output.is_spin, expected.is_spin);
            testCase.verifyEqual(output.is_hubbard, expected.is_hubbard);
            temporary = string(tempname) + ".h5";
            cleanup = onCleanup(@() testCase.deleteIfPresent(temporary));
            output.remove_potcar_and_write_file(temporary);
            scrubbed = kssolv.analysis.matgenlab.io.vasp.Vaspout( ...
                temporary, store_potcar = false);
            testCase.verifyEqual(scrubbed.final_energy, ...
                output.final_energy, AbsTol = 1e-10);
            clear cleanup

            wave = kssolv.analysis.matgenlab.io.vasp.Vaspwave( ...
                fullfile(folder, "vaspwave.h5"));
            coefficients = wave.get_band_coeffs(1, 1, 1);
            testCase.verifyNotEmpty(coefficients);
            testCase.verifyNotEmpty(wave.fft_mesh(1, 1));
            testCase.verifyNotEmpty(wave.evaluate_wavefunc( ...
                1, 1, [0, 0, 0]));
            testCase.verifyClass(wave.get_chgcar(), ...
                "kssolv.analysis.matgenlab.io.vasp.Chgcar");
            testCase.verifyClass(wave.get_locpot(), ...
                "kssolv.analysis.matgenlab.io.vasp.Locpot");
            poscar = kssolv.analysis.matgenlab.io.vasp.Poscar. ...
                from_file(fullfile(folder, "POSCAR"), ...
                check_for_potcar = false);
            testCase.verifyClass(wave.get_parchg( ...
                poscar, 1, 1, scale = 1), ...
                "kssolv.analysis.matgenlab.io.vasp.Chgcar");
            unkFolder = string(tempname);
            mkdir(unkFolder);
            unkCleanup = onCleanup(@() rmdir(unkFolder, "s"));
            wave.write_unks(unkFolder);
            testCase.verifyTrue(isfile(fullfile( ...
                unkFolder, "UNK00001.1")));
            clear unkCleanup

            missing = string(tempname);
            mkdir(missing);
            missingCleanup = onCleanup(@() rmdir(missing, "s"));
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.vasp. ...
                get_band_structure_from_vasp_multiple_branches(missing), ...
                "KSSOLV:Matgenlab:VaspParseError");
            copyfile(fullfile(folder, "vasprun.Al.xml.gz"), ...
                fullfile(missing, "vasprun.xml.gz"));
            reconstructed = kssolv.analysis.matgenlab.io.vasp. ...
                get_band_structure_from_vasp_multiple_branches(missing);
            testCase.verifyEqual(numel(reconstructed.kpoints), 84);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.vasp. ...
                get_adjusted_fermi_level(1, 2, ...
                output.get_band_structure()), 1);
            clear missingCleanup
        end
    end

    methods (Static, Access = private)
        function [folder, oracle] = fixture()
            folder = fullfile(fileparts(mfilename("fullpath")), ...
                "+fixtures", "+vasp_outputs");
            oracle = jsondecode(fileread(fullfile( ...
                folder, "frozen_oracle_2026_7_24.json")));
        end

        function deleteIfPresent(filename)
            if isfile(filename)
                delete(filename);
            end
        end
    end
end
