classdef XcrysdenTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 oracle tests for io.xcrysden.

    methods (Test)
        function frozenInventorySurfaceIsImplemented(testCase)
            ledger = readtable(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", ...
                "compatibility_ledger.csv"), TextType = "string", ...
                Delimiter = ",");
            rows = ledger(ledger.module == "pymatgen.io.xcrysden", :);
            testCase.verifyEqual(height(rows), 23);
            testCase.verifyTrue(all(rows.status == "implemented"), ...
                join(rows.api_id(rows.status ~= "implemented"), newline));

            package = "kssolv.analysis.matgenlab.io.xcrysden.";
            expected = struct( ...
                "XSFBand", ["shape", "ndim"], ...
                "XSFGrid", ["shape", "ndim"], ...
                "XSF", "lattice", ...
                "AnimatedXSF", strings(1, 0));
            classes = fieldnames(expected);
            for index = 1:numel(classes)
                metadata = meta.class.fromName(package + classes{index});
                testCase.verifyNotEmpty(metadata);
                properties = metadataNames(metadata.PropertyList);
                testCase.verifyTrue(all(ismember( ...
                    expected.(classes{index}), properties)));
            end
            methods = metadataNames(meta.class.fromName( ...
                package + "XSF").MethodList);
            testCase.verifyTrue(all(ismember(["to_str", ...
                "structure_properties", "write_file", "from_file", ...
                "from_str", "parse_file"], methods)));
        end

        function gridAndBandMSONMatchFrozenOracle(testCase)
            grid = kssolv.analysis.matgenlab.io.xcrysden.XSFGrid( ...
                ones(1, 2, 3), eye(2, 3), zeros(1, 3), ...
                comment = "rho", labels = "grid/rho");
            testCase.verifyEqual(grid.shape, [1, 2, 3]);
            testCase.verifyEqual(grid.ndim, 2);
            decoded = kssolv.analysis.matgenlab.util.decode( ...
                grid.toJSON());
            testCase.verifyClass(decoded, ...
                "kssolv.analysis.matgenlab.io.xcrysden.XSFGrid");
            testCase.verifyEqual(decoded.data, grid.data);
            testCase.verifyEqual(decoded.labels, "grid/rho");

            band = kssolv.analysis.matgenlab.io.xcrysden.XSFBand( ...
                ones(1, 2, 2, 2), eye(3), zeros(1, 3), ...
                comment = "fermi surface", labels = "grid/1");
            testCase.verifyEqual(band.shape, [1, 2, 2, 2]);
            testCase.verifyEqual(band.ndim, 3);
            decoded = kssolv.analysis.matgenlab.util.decode( ...
                band.toJSON());
            testCase.verifyClass(decoded, ...
                "kssolv.analysis.matgenlab.io.xcrysden.XSFBand");
            testCase.verifyEqual(decoded.comment, "fermi surface");

            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.xcrysden.XSFGrid( ...
                ones(2, 2, 3), eye(2, 3), zeros(1, 3), ...
                labels = "only one"), ...
                "KSSOLV:Matgenlab:XSFGrid:LabelCount");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.xcrysden.XSFBand( ...
                ones(2, 2, 2, 2), eye(3), zeros(1, 3), ...
                labels = "only one"), ...
                "KSSOLV:Matgenlab:XSFBand:LabelCount");
        end

        function officialStructureFixturesMatchOracle(testCase)
            xsf = fixtureXSF("crystal_primvec_primcoord.xsf");
            testCase.verifyEqual(xsf.kind, "crystal");
            testCase.verifyEqual(xsf.ndim, 3);
            testCase.verifyEqual(xsf.comment, ...
                "# Primitive lattice vectors in Angstrom");
            testCase.verifyEqual(xsf.structure.num_sites, 2);
            testCase.verifyEqual(xsf.structure.cart_coords, ...
                [0, 0, 0; 1.5, 1.5, 1.5], AbsTol = 1e-14);
            testCase.verifyEqual(xsf.lattice.matrix, 3 * eye(3));

            forced = fixtureXSF("crystal_primcoord_forces.xsf");
            testCase.verifyEqual(string(forced.structure.species{1}), "O");
            testCase.verifyEqual(string(forced.structure.species{2}), "H");
            testCase.verifyEqual(forced.forces, ...
                [0.1, 0, 0; 0, 0.2, 0], AbsTol = 1e-14);

            conventional = fixtureXSF("crystal_convvec.xsf");
            testCase.verifyEqual(conventional.conventional_lattice, ...
                4 * eye(3));
        end

        function officialGridAndBandFixturesMatchOracle(testCase)
            xsf2 = fixtureXSF("datagrid_2d.xsf");
            grid2 = xsf2.grids("density_2d");
            testCase.verifyEqual(grid2.shape, [1, 2, 3]);
            testCase.verifyEqual(grid2.ndim, 2);
            testCase.verifyEqual(grid2.data, ...
                reshape([0, 1, 2, 3, 4, 5], [1, 2, 3]));
            testCase.verifyEqual(grid2.lattice, ...
                [2, 0, 0; 0, 2, 0]);
            testCase.verifyEqual(grid2.labels, "grid/density");

            xsf3 = fixtureXSF("datagrid_3d.xsf");
            grid3 = xsf3.grids("density_3d");
            testCase.verifyEqual(grid3.shape, [1, 2, 2, 2]);
            testCase.verifyEqual(grid3.data, ...
                reshape(0:7, [1, 2, 2, 2]));

            bxsf = fixtureXSF("bandgrid_3d.bxsf");
            band = bxsf.bands("band_energies");
            oracle = zeros(1, 2, 2, 2);
            oracle(1, :, :, :) = cat(3, ...
                [4.8, 5.2; 5.3, 4.7], ...
                [5.1, 4.9; 5.4, 5.0]);
            testCase.verifyEqual(bxsf.fermi_energy, 5);
            testCase.verifyEqual(band.data, oracle, AbsTol = 1e-14);
            testCase.verifyEqual(band.labels, "1");
        end

        function fullWriterRoundtripAndProperties(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                [3, 0, 0; 0, 3, 0; 0, 0, 3], ...
                {"Si", "Si"}, [0, 0, 0; 1.5, 1.5, 1.5], ...
                coords_are_cartesian = true);
            xsf = kssolv.analysis.matgenlab.io.xcrysden.XSF( ...
                structure, forces = [0.1, 0.2, 0.3; 0.4, 0.5, 0.6]);
            xsf.grids("density") = ...
                kssolv.analysis.matgenlab.io.xcrysden.XSFGrid( ...
                reshape(0:5, [1, 2, 3]), eye(2, 3), zeros(1, 3), ...
                labels = "grid/rho");
            xsf.bands("bands") = ...
                kssolv.analysis.matgenlab.io.xcrysden.XSFBand( ...
                reshape(0:7, [1, 2, 2, 2]), eye(3), zeros(1, 3), ...
                labels = "band_1");
            xsf.fermi_energy = 5;
            parsed = kssolv.analysis.matgenlab.io.xcrysden.XSF. ...
                from_str(xsf.to_str());
            testCase.verifyEqual(parsed.forces, xsf.forces);
            testCase.verifyEqual(parsed.grids("density").data, ...
                xsf.grids("density").data);
            testCase.verifyEqual(parsed.bands("bands").data, ...
                xsf.bands("bands").data);
            extras = parsed.structure_properties();
            testCase.verifyTrue(extras.isKey("grids/density/rho"));
            testCase.verifyTrue(extras.isKey("bands/bands/band_1"));
            testCase.verifyEqual(extras("bands/fermi_energy"), 5);
        end

        function moleculeAndAtomSymbolModesMatchOracle(testCase)
            xsf = fixtureXSF("molecule_atoms.xsf");
            testCase.verifyEqual(xsf.kind, "molecule");
            testCase.verifyEqual(xsf.ndim, 0);
            testCase.verifyEmpty(xsf.lattice);
            testCase.verifyClass(xsf.structure, ...
                "kssolv.analysis.matgenlab.core.Molecule");
            testCase.verifyEqual(xsf.structure.cart_coords, ...
                [0, 0, 0; 0.757, 0.586, 0; -0.757, 0.586, 0], ...
                AbsTol = 1e-14);

            numbered = fixtureXSF("crystal_primcoord_forces.xsf");
            text = numbered.to_str(false);
            testCase.verifyTrue(contains(text, newline + "8 "));
            parsed = kssolv.analysis.matgenlab.io.xcrysden.XSF.from_str(text);
            testCase.verifyEqual(string(parsed.structure.species{1}), "O");
        end

        function exactWriterTextMatchesFrozenOracle(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3), {"H"}, [0, 0, 0]);
            xsf = kssolv.analysis.matgenlab.io.xcrysden.XSF(structure);
            expected = join(["CRYSTAL"; ...
                "# Primitive lattice vectors in Angstrom"; "PRIMVEC"; ...
                " 1.00000000000000 0.00000000000000 0.00000000000000"; ...
                " 0.00000000000000 1.00000000000000 0.00000000000000"; ...
                " 0.00000000000000 0.00000000000000 1.00000000000000"; ...
                "# Cartesian coordinates in Angstrom."; "PRIMCOORD"; ...
                " 1 1"; ...
                "H     0.00000000000000     0.00000000000000     0.00000000000000"], ...
                newline);
            testCase.verifyEqual(xsf.to_str(), expected);
        end

        function fileCompressionAndStreamParsingWork(testCase)
            source = xcrysdenFixture("crystal_primvec_primcoord.xsf");
            xsf = kssolv.analysis.matgenlab.io.xcrysden.XSF.from_file(source);
            gzipPath = string(tempname) + ".xsf.gz";
            cleanup = onCleanup(@() deleteIfPresent(gzipPath));
            xsf.write_file(gzipPath);
            parsed = kssolv.analysis.matgenlab.io.xcrysden.XSF. ...
                from_file(gzipPath);
            testCase.verifyEqual(parsed.structure.cart_coords, ...
                xsf.structure.cart_coords);

            identifier = fopen(source, "rb");
            fileCleanup = onCleanup(@() fclose(identifier));
            streamed = kssolv.analysis.matgenlab.io.xcrysden.XSF. ...
                parse_file(identifier);
            testCase.verifyEqual(streamed.kind, "crystal");
            clear fileCleanup
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.xcrysden.XSF. ...
                parse_file("CRYSTAL"), ...
                "KSSOLV:Matgenlab:XSF:BinaryStream");
        end

        function writerValidationMatchesUpstream(testCase)
            empty = kssolv.analysis.matgenlab.io.xcrysden.XSF();
            testCase.verifyError(@() empty.to_str(), ...
                "KSSOLV:Matgenlab:XSF:MissingStructure");
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3), {"H"}, [0, 0, 0]);
            badForces = kssolv.analysis.matgenlab.io.xcrysden.XSF( ...
                structure, forces = ones(2, 3));
            testCase.verifyError(@() badForces.to_str(), ...
                "KSSOLV:Matgenlab:XSF:ForceShape");
            missingFermi = ...
                kssolv.analysis.matgenlab.io.xcrysden.XSF(structure);
            missingFermi.bands("b") = ...
                kssolv.analysis.matgenlab.io.xcrysden.XSFBand( ...
                ones(1, 2, 2, 2), eye(3), zeros(1, 3));
            testCase.verifyError(@() missingFermi.to_str(), ...
                "KSSOLV:Matgenlab:XSF:MissingFermi");
        end

        function parserStructuralErrorsMatchUpstream(testCase)
            verifyXsfError(testCase, "ANIMSTEPS 2", ...
                "KSSOLV:Matgenlab:XSF:Animated", "ANIMSTEPS keyword");
            verifyXsfError(testCase, "ATOMS" + newline + ...
                "H 0 0 0", "KSSOLV:Matgenlab:XSF:AtomsKind", ...
                "ATOMS is only valid");
            verifyXsfError(testCase, "CRYSTAL" + newline + ...
                "PRIMCOORD" + newline + "1 1" + newline + "H 0 0 0", ...
                "KSSOLV:Matgenlab:XSF:PrimcoordBeforePrimvec", ...
                "before PRIMVEC");
            verifyXsfError(testCase, "CONVCOORD", ...
                "KSSOLV:Matgenlab:XSF:Convcoord", ...
                "CONVCOORD section is not allowed");
            verifyXsfError(testCase, "END_INFO", ...
                "KSSOLV:Matgenlab:XSF:InfoEnd", ...
                "without a preceding BEGIN_INFO");
            verifyXsfError(testCase, "CRYSTAL" + newline + "PRIMVEC" + ...
                newline + "1 0 0" + newline + "0 1 0" + newline + ...
                "0 0 1" + newline + "PRIMCOORD" + newline + "1 1" + ...
                newline + "H 0 0", ...
                "KSSOLV:Matgenlab:XSF:PrimcoordFields", ...
                "4 fields or 7 fields");
        end

        function parserBlockErrorsMatchUpstream(testCase)
            verifyXsfError(testCase, "END_BLOCK_DATAGRID_3D", ...
                "KSSOLV:Matgenlab:XSF:DatagridEnd", ...
                "without a matching BEGIN_BLOCK_DATAGRID");
            verifyXsfError(testCase, "END_BLOCK_BANDGRID_3D", ...
                "KSSOLV:Matgenlab:XSF:BandgridEnd", ...
                "without a matching BEGIN_BLOCK_BANDGRID");
            verifyXsfError(testCase, "BEGIN_DATAGRID_3D_density", ...
                "KSSOLV:Matgenlab:XSF:DatagridBegin", ...
                "without a matching BEGIN_BLOCK_DATAGRID");
            verifyXsfError(testCase, "BEGIN_BANDGRID_3D_band", ...
                "KSSOLV:Matgenlab:XSF:BandgridBegin", ...
                "without a matching BEGIN_BLOCK_BANDGRID");

            truncated = join(["BEGIN_BLOCK_DATAGRID_3D"; "rho"; ...
                "BEGIN_DATAGRID_3D_rho"; "2 2 2"; "0 0 0"; ...
                "1 0 0"; "0 1 0"; "0 0 1"; "0 1 2 3 4 5 6"; ...
                "END_DATAGRID_3D"], newline);
            verifyXsfError(testCase, truncated, ...
                "KSSOLV:Matgenlab:XSF:ValueCount", ...
                "Expected 8 grid values but parsed 7");

            noFermi = join(["BEGIN_BLOCK_BANDGRID_3D"; "bands"; ...
                "BEGIN_BANDGRID_3D_band"; "1"; "1 1 1"; "0 0 0"; ...
                "1 0 0"; "0 1 0"; "0 0 1"; "BAND: 1"; "0"; ...
                "END_BANDGRID_3D"], newline);
            verifyXsfError(testCase, noFermi, ...
                "KSSOLV:Matgenlab:XSF:BandgridFermi", ...
                "missing required Fermi energy");
        end

        function animatedOfficialFixturesBecomeTrajectories(testCase)
            fixed = ...
                kssolv.analysis.matgenlab.io.xcrysden.AnimatedXSF. ...
                from_file(xcrysdenFixture("axsf_fixed_cell.axsf"));
            testCase.verifyEqual(length(fixed), 2);
            testCase.verifyEqual(fixed(2).structure.cart_coords(1, :), ...
                [0.05, 0, 0], AbsTol = 1e-14);
            trajectory = fixed.as_trajectory();
            testCase.verifyEqual(length(trajectory), 2);
            testCase.verifyTrue(trajectory.constant_lattice);

            variable = ...
                kssolv.analysis.matgenlab.io.xcrysden.AnimatedXSF. ...
                from_file(xcrysdenFixture("axsf_variable_cell.axsf"));
            trajectory = variable.as_trajectory();
            testCase.verifyFalse(trajectory.constant_lattice);
            testCase.verifyEqual(variable(2).lattice.matrix, ...
                3.1 * eye(3), AbsTol = 1e-14);

            identifier = fopen(xcrysdenFixture( ...
                "axsf_fixed_cell.axsf"), "rb");
            cleanup = onCleanup(@() fclose(identifier));
            streamed = ...
                kssolv.analysis.matgenlab.io.xcrysden.AnimatedXSF. ...
                parse_file(identifier);
            testCase.verifyEqual(length(streamed), 2);
            clear cleanup
        end

        function animatedValidationIsDeterministic(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.xcrysden.AnimatedXSF. ...
                from_str("CRYSTAL"), ...
                "KSSOLV:Matgenlab:AnimatedXSF:Header");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.xcrysden.AnimatedXSF. ...
                from_str("ANIMSTEPS 2" + newline + "CRYSTAL" + ...
                newline + "PRIMVEC" + newline + "1 0 0" + newline + ...
                "0 1 0" + newline + "0 0 1" + newline + ...
                "PRIMCOORD 1" + newline + "1 1" + newline + "H 0 0 0"), ...
                "KSSOLV:Matgenlab:AnimatedXSF:FrameCountMismatch");
            empty = ...
                kssolv.analysis.matgenlab.io.xcrysden.AnimatedXSF();
            testCase.verifyError(@() empty.as_trajectory(), ...
                "KSSOLV:Matgenlab:AnimatedXSF:Empty");
        end
    end
end

function path = xcrysdenFixture(name)
path = fullfile(KSSOLV_Toolbox.RootDirectory, "+kssolv", "+analysis", ...
    "+matgenlab", "+test", "+io", "+fixtures", "+xcrysden", name);
end

function value = fixtureXSF(name)
value = kssolv.analysis.matgenlab.io.xcrysden.XSF. ...
    from_file(xcrysdenFixture(name));
end

function verifyXsfError(testCase, text, identifier, fragment)
try
    kssolv.analysis.matgenlab.io.xcrysden.XSF.from_str(text);
    testCase.verifyFail("Expected XSF parsing to fail.");
catch exception
    testCase.verifyEqual(string(exception.identifier), string(identifier));
    testCase.verifyTrue(contains(string(exception.message), fragment), ...
        exception.message);
end
end

function deleteIfPresent(path)
if isfile(path), delete(path); end
end

function names = metadataNames(items)
if iscell(items), names = string(cellfun(@(item) item.Name, ...
        items, "UniformOutput", false));
else, names = string({items.Name});
end
end
