classdef XtbTest < matlab.unittest.TestCase
    methods (Test)
        function constraintTemplateMatchesOfficialFixture(testCase)
            fixture = xtbFixture("sample_CREST_output");
            molecule = ...
                kssolv.analysis.matgenlab.core.Molecule.from_file( ...
                    fullfile(fixture, "crest_in.xyz"));
            constraints = struct("atoms", [8, 1, 2], ...
                "force_constant", 0.5);
            actual = kssolv.analysis.matgenlab.io.xtb.CRESTInput. ...
                constrains_template(molecule, "crest_in.xyz", constraints);
            expected = strtrim(fileread(fullfile( ...
                xtbFixture("expected_output"), ...
                "expected_constrains.txt")));
            testCase.verifyEqual(actual, string(expected));
        end

        function inputWriterUsesWorkingDirectory(testCase)
            molecule = ...
                kssolv.analysis.matgenlab.core.Molecule( ...
                    ["C", "O"], [-9.5782, 0.62415, 0; ...
                    -7.58274, 0.5127, 0]);
            folder = string(tempname);
            cleanup = onCleanup(@() removeFolder(folder));
            input = kssolv.analysis.matgenlab.io.xtb.CRESTInput( ...
                molecule, working_dir = folder, ...
                constraints = struct("atoms", 1, ...
                "force_constant", 0.5));
            input.write_input_files();
            testCase.verifyTrue(isfile(fullfile(folder, "crest_in.xyz")));
            testCase.verifyTrue(isfile(fullfile(folder, ".constrains")));
            restored = ...
                kssolv.analysis.matgenlab.core.Molecule.from_file( ...
                    fullfile(folder, "crest_in.xyz"));
            testCase.verifyEqual(restored.cart_coords, ...
                molecule.cart_coords, AbsTol = 1e-6);
            testCase.verifyThat(fileread(fullfile(folder, ".constrains")), ...
                matlab.unittest.constraints.ContainsSubstring( ...
                    "atoms: 2-2"));
            clear cleanup
        end

        function officialOutputMatchesFrozenPymatgen(testCase)
            fixture = xtbFixture("sample_CREST_output");
            output = kssolv.analysis.matgenlab.io.xtb.CRESTOutput( ...
                "crest_out.out", fixture);
            testCase.verifyTrue(output.properly_terminated);
            testCase.verifyEqual(output.cmd_options.g, "H2O");
            testCase.verifyEqual(output.cmd_options.c, "2");
            testCase.verifyEqual(cellfun(@(group) size(group, 1), ...
                output.sorted_structures_energies), [9, 18]);
            testCase.verifyEqual(string( ...
                output.sorted_structures_energies{1}(:, 2)), ...
                repmat("-13.66580", 9, 1));
            testCase.verifyEqual(string( ...
                output.sorted_structures_energies{2}(:, 2)), ...
                repmat("-13.66479", 18, 1));
            testCase.verifyEqual(output.input_structure.charge, 0);
            testCase.verifyEqual( ...
                output.lowest_energy_structure.charge, 2);
            expected = ...
                kssolv.analysis.matgenlab.core.Molecule.from_file( ...
                    fullfile(xtbFixture("expected_output"), ...
                    "expected_crest_best.xyz"));
            testCase.verifyEqual( ...
                output.lowest_energy_structure.cart_coords, ...
                expected.cart_coords, AbsTol = 1e-6);
        end
    end
end

function path = xtbFixture(folder)
path = fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures", "+xtb", folder);
end

function removeFolder(path)
if isfolder(path), rmdir(path, "s"); end
end
