classdef ZeoppInventoryTest < matlab.unittest.TestCase
    properties
        fixtureFolder
        oracle
    end

    methods (TestMethodSetup)
        function prepare(testCase)
            testCase.fixtureFolder = fullfile(pwd, "+kssolv", ...
                "+analysis", "+matgenlab", "+test", "+io", ...
                "+fixtures", "+zeopp");
            testCase.oracle = jsondecode(fileread(fullfile(pwd, "dev", ...
                "matgenlab", "oracles", "zeopp_2026.7.24.json")));
        end
    end

    methods (Test)
        function zeoCssrMatchesFrozenOracle(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice. ...
                from_parameters(5.1, 6.2, 7.3, 81, 92, 103);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, ["Si", "O"], ...
                [0.1, 0.2, 0.3; 0.75, 0.5, 0.25], ...
                site_properties = struct("charge", [1.25, -0.5]));
            cssr = kssolv.analysis.matgenlab.io.zeopp.ZeoCssr(structure);
            testCase.verifyEqual(string(cssr), ...
                string(testCase.oracle.synthetic_cssr));
            restored = kssolv.analysis.matgenlab.io.zeopp. ...
                ZeoCssr.from_str(string(cssr));
            testCase.verifyEqual(restored.structure.frac_coords, ...
                testCase.oracle.synthetic_cssr_frac_coords, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(cell2mat( ...
                restored.structure.site_properties.charge), ...
                [1.25, -0.5], AbsTol = 1e-12);
        end

        function officialCssrFilesAndCompressionParse(testCase)
            filename = fullfile(testCase.fixtureFolder, "EDI.cssr");
            cssr = kssolv.analysis.matgenlab.io.zeopp. ...
                ZeoCssr.from_file(filename);
            expected = testCase.oracle.official_cssr;
            testCase.verifyEqual(cssr.structure.num_sites, ...
                expected.num_sites);
            testCase.verifyEqual(cssr.structure.lattice.lengths, ...
                reshape(expected.lengths, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual(cssr.structure.lattice.angles, ...
                reshape(expected.angles, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual(cssr.structure.frac_coords(1, :), ...
                reshape(expected.first_frac_coord, 1, []), ...
                AbsTol = 1e-12);
            decorated = kssolv.analysis.matgenlab.io.zeopp. ...
                ZeoCssr.from_file(fullfile(testCase.fixtureFolder, ...
                "EDI_oxistate_decorated.cssr"));
            testCase.verifyEqual(decorated.structure.num_sites, 15);
            testCase.verifyEqual( ...
                decorated.structure.get_site(1).specie.oxi_state, -2);

            folder = string(tempname);
            mkdir(folder);
            cleanup = onCleanup(@() removeFolder(folder));
            copyfile(filename, fullfile(folder, "EDI.cssr"));
            gzip(fullfile(folder, "EDI.cssr"), folder);
            compressed = kssolv.analysis.matgenlab.io.zeopp. ...
                ZeoCssr.from_file(fullfile(folder, "EDI.cssr.gz"));
            testCase.verifyEqual(compressed.structure.frac_coords, ...
                cssr.structure.frac_coords, AbsTol = 1e-12);
            clear cleanup
        end

        function voronoiXyzMatchesFrozenOracle(testCase)
            coordinates = [0, 0, 0; 0, 0, 1.089; ...
                1.026719, 0, -0.363; ...
                -0.513360, -0.889165, -0.363; ...
                -0.513360, 0.889165, -0.363];
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                ["C", "H", "H", "H", "H"], coordinates, ...
                site_properties = struct( ...
                "voronoi_radius", [0.4, 0.2, 0.2, 0.2, 0.2]));
            xyz = kssolv.analysis.matgenlab.io.zeopp. ...
                ZeoVoronoiXYZ(molecule);
            testCase.verifyEqual(string(xyz), ...
                string(testCase.oracle.methane_xyz));

            official = kssolv.analysis.matgenlab.io.zeopp. ...
                ZeoVoronoiXYZ.from_file(fullfile( ...
                testCase.fixtureFolder, "EDI_voro.xyz"));
            expected = testCase.oracle.official_voronoi_xyz;
            testCase.verifyEqual(official.molecule.num_sites, ...
                expected.num_sites);
            testCase.verifyEqual(official.molecule.formula, ...
                string(expected.formula));
            testCase.verifyEqual(official.molecule.cart_coords(1, :), ...
                reshape(expected.first_cart_coord, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(official.molecule.get_site(1). ...
                site_properties.voronoi_radius, expected.first_radius);
            testCase.verifyEqual(official.molecule.cart_coords(end, :), ...
                reshape(expected.last_cart_coord, 1, []), ...
                AbsTol = 1e-12);
        end

        function injectedVoronoiBackendConvertsCoordinates(testCase)
            structure = simpleStructure();
            frozen = testCase.oracle.backend_fixture;
            backend = struct("get_voronoi_nodes", ...
                @(cssr, radii, probe) normalResult( ...
                cssr, radii, probe, frozen));
            radii = struct("Si", 1.1);
            [nodes, edges, faces] = ...
                kssolv.analysis.matgenlab.io.zeopp. ...
                get_voronoi_nodes(structure, radii, 0.25, backend);
            testCase.verifyEqual(nodes.cart_coords, ...
                [1, 2, 3; 0.25, 0.75, 9.5], AbsTol = 1e-12);
            testCase.verifyEqual(cell2mat( ...
                nodes.site_properties.voronoi_radius), ...
                [0.4, 0.8], AbsTol = 1e-12);
            testCase.verifyEqual(edges.cart_coords, ...
                [1, 2, 3; 0.25, 0.75, 9.5], AbsTol = 1e-12);
            testCase.verifyEqual(faces.cart_coords, [4, 5, 6], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(cell2mat( ...
                edges.site_properties.voronoi_radius), [0, 0]);
        end

        function highAccuracyBackendConvertsNodes(testCase)
            structure = simpleStructure();
            frozen = testCase.oracle.backend_fixture;
            backend = struct("get_high_accuracy_voronoi_nodes", ...
                @(cssr, radii, probe) highResult( ...
                cssr, radii, probe, frozen));
            nodes = kssolv.analysis.matgenlab.io.zeopp. ...
                get_high_accuracy_voronoi_nodes( ...
                structure, struct("Si", 1.1), 0.2, backend);
            testCase.verifyEqual(nodes.cart_coords, ...
                [1, 2, 3; 0.25, 0.75, 9.5], AbsTol = 1e-12);
            testCase.verifyEqual(cell2mat( ...
                nodes.site_properties.voronoi_radius), [0.4, 0.8]);
        end

        function freeSphereBackendSupportsTextAndStruct(testCase)
            structure = simpleStructure();
            line = string(testCase.oracle.backend_fixture.free_sphere_line);
            textBackend = struct("get_free_sphere_params", ...
                @(cssr, radii, probe) freeSphereLine( ...
                cssr, radii, probe, line));
            result = kssolv.analysis.matgenlab.io.zeopp. ...
                get_free_sphere_params(structure, [], 0.1, textBackend);
            testCase.verifyEqual(result.inc_sph_max_dia, 2.58251);
            testCase.verifyEqual(result.free_sph_max_dia, 1.29452);
            testCase.verifyEqual( ...
                result.inc_sph_along_free_sph_path_max_dia, 2.58251);
            direct = struct( ...
                "inc_sph_max_dia", 4, ...
                "free_sph_max_dia", 3, ...
                "inc_sph_along_free_sph_path_max_dia", 2);
            structBackend = struct("get_free_sphere_params", ...
                @(varargin) direct);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.io.zeopp. ...
                get_free_sphere_params(structure, [], 0.1, ...
                structBackend), direct);
        end

        function missingAndInvalidBackendsAreStable(testCase)
            structure = simpleStructure();
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.zeopp. ...
                get_voronoi_nodes(structure), ...
                "KSSOLV:Matgenlab:ZeoPP:BackendRequired");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.zeopp. ...
                get_high_accuracy_voronoi_nodes( ...
                structure, struct(), 0.1), ...
                "KSSOLV:Matgenlab:ZeoPP:BackendRequired");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.zeopp. ...
                get_free_sphere_params(structure), ...
                "KSSOLV:Matgenlab:ZeoPP:BackendRequired");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.zeopp. ...
                get_voronoi_nodes(structure, [], -1, struct()), ...
                "KSSOLV:Matgenlab:ZeoPP:ProbeRadius");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.io.zeopp. ...
                get_voronoi_nodes(structure, [], 0.1, struct()), ...
                "KSSOLV:Matgenlab:ZeoPP:BackendContract");
        end
    end
end

function structure = simpleStructure()
structure = kssolv.analysis.matgenlab.core.Structure( ...
    10 * eye(3), "Si", [0.1, 0.2, 0.3]);
end

function result = normalResult(cssr, radii, probe, frozen)
assert(contains(cssr, "1 Si 0.3000 0.1000 0.2000"));
assert(radii.Si == 1.1);
assert(probe == 0.25);
result = struct("voronoi_xyz", frozen.voronoi_xyz, ...
    "edge_centers", frozen.edge_centers, ...
    "face_centers", frozen.face_centers);
end

function result = highResult(cssr, radii, probe, frozen)
assert(contains(cssr, "1 Si 0.3000 0.1000 0.2000"));
assert(radii.Si == 1.1);
assert(probe == 0.2);
result = frozen.voronoi_xyz;
end

function result = freeSphereLine(cssr, radii, probe, line)
assert(contains(cssr, "1 Si 0.3000 0.1000 0.2000"));
assert(isempty(radii));
assert(probe == 0.1);
result = line;
end

function removeFolder(folder)
if isfolder(folder)
    rmdir(folder, "s");
end
end
