classdef AdvancedTransformationsInventoryTest < matlab.unittest.TestCase
    %ADVANCEDTRANSFORMATIONSINVENTORYTEST Frozen advanced API parity tests.

    methods (Test)
        function frozenInventoryHasAllFortySevenApis(testCase)
            package = "kssolv.analysis.matgenlab.transformations.";
            classes = ["ChargeBalanceTransformation", ...
                "SuperTransformation", ...
                "MultipleSubstitutionTransformation", ...
                "EnumerateStructureTransformation", ...
                "SubstitutionPredictorTransformation", ...
                "MagOrderParameterConstraint", ...
                "MagOrderingTransformation", "DopingTransformation", ...
                "SlabTransformation", ...
                "DisorderOrderedTransformation", ...
                "GrainBoundaryTransformation", ...
                "CubicSupercellTransformation", ...
                "AddAdsorbateTransformation", ...
                "SubstituteSurfaceSiteTransformation", ...
                "SQSTransformation", ...
                "MonteCarloRattleTransformation"];
            specifications = {
                "ChargeBalanceTransformation", "apply_transformation"
                "SuperTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "MultipleSubstitutionTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "EnumerateStructureTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "SubstitutionPredictorTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "MagOrderParameterConstraint", "satisfies_constraint"
                "MagOrderingTransformation", ...
                    ["determine_min_cell", "apply_transformation", ...
                    "is_one_to_many"]
                "DopingTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "SlabTransformation", "apply_transformation"
                "DisorderOrderedTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "GrainBoundaryTransformation", "apply_transformation"
                "CubicSupercellTransformation", ...
                    ["apply_transformation", "check_exceptions", ...
                    "check_constraints", "get_possible_supercell"]
                "AddAdsorbateTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "SubstituteSurfaceSiteTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "SQSTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "MonteCarloRattleTransformation", "apply_transformation"
                };
            memberCount = sum(cellfun(@numel, specifications(:, 2)));
            testCase.verifyEqual(numel(classes) + memberCount + 1, 47);
            for name = classes
                testCase.verifyNotEmpty(meta.class.fromName(package + name));
            end
            for index = 1:size(specifications, 1)
                testCase.verifyMembers(package + specifications{index, 1}, ...
                    string(specifications{index, 2}));
            end
            testCase.verifyNotEmpty(which(package + "find_codopant"));
            oracle = testCase.oracle();
            testCase.verifyEqual(oracle.metadata.api_count, 47);
            testCase.verifyEqual(string(oracle.metadata.tag), "v2026.7.24");
        end

        function balanceCompositionAndSuperTransformsMatchOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            charged = testCase.chargedStructure();
            balanced = ChargeBalanceTransformation("Li+"). ...
                apply_transformation(charged);
            testCase.verifyEqual(balanced.formula, ...
                string(oracle.charge_balance.formula));
            testCase.verifyEqual(balanced.charge, 0, AbsTol = 1e-12);
            testCase.verifyEqual(balanced.frac_coords, ...
                oracle.charge_balance.frac_coords, AbsTol = 1e-12);

            combined = SuperTransformation({ ...
                SubstitutionTransformation({"Li+", "Na+"}), ...
                SubstitutionTransformation({"Li+", "K+"})});
            testCase.verifyTrue(combined.is_one_to_many);
            testCase.verifyError(@()combined.apply_transformation(charged), ...
                "KSSOLV:Matgenlab:SuperTransformation:RankedOnly");
            outputs = combined.apply_transformation(charged, true);
            testCase.verifyEqual(numel(outputs), ...
                oracle.super_transformation.count);
            testCase.verifyEqual(cellfun(@(item)item.structure.formula, ...
                outputs), string(oracle.super_transformation.formulas).');

            multiple = MultipleSubstitutionTransformation( ...
                "Li+", .5, {1, ["Na", "K"]});
            small = testCase.smallChargedStructure();
            outputs = multiple.apply_transformation(small, true);
            testCase.verifyTrue(multiple.is_one_to_many);
            testCase.verifyEqual(numel(outputs), ...
                oracle.multiple_substitution.count);
            testCase.verifyEqual(cellfun(@(item)item.structure.formula, ...
                outputs), string(oracle.multiple_substitution.formulas).');
        end

        function magneticConstraintsAndCodopantsMatchOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            site = testCase.smallChargedStructure();
            site = site(1);
            testCase.verifyEqual(MagOrderParameterConstraint(.5). ...
                satisfies_constraint(site), oracle.constraints.default);
            testCase.verifyEqual(MagOrderParameterConstraint(.5, "Li+"). ...
                satisfies_constraint(site), ...
                oracle.constraints.species_true);
            testCase.verifyEqual(MagOrderParameterConstraint(.5, "Fe2+"). ...
                satisfies_constraint(site), ...
                oracle.constraints.species_false);
            testCase.verifyError(@()MagOrderParameterConstraint(1.1), ...
                "KSSOLV:Matgenlab:MagOrderConstraint:Parameter");
            testCase.verifyError(@()MagOrderParameterConstraint( ...
                .5, [], [], 4), ...
                "KSSOLV:Matgenlab:MagOrderConstraint:PropertyName");

            testCase.verifyEqual(string(find_codopant( ...
                Species("Fe", 2), 1)), ...
                string(oracle.find_codopant.Fe2_to_1));
            testCase.verifyEqual(string(find_codopant( ...
                Species("Fe", 2), 3)), ...
                string(oracle.find_codopant.Fe2_to_3));
            testCase.verifyError(@()find_codopant( ...
                Species("Fe", 2), 99), ...
                "KSSOLV:Matgenlab:FindCodopant:NoSpecies");

            up = Species("Fe", 0, "spin", 1);
            down = Species("Fe", 0, "spin", -1);
            one = Structure(Lattice.cubic(4), ...
                {{up, .5; down, .5}}, [0, 0, 0]);
            two = Structure(Lattice.cubic(4), ...
                {{up, .5; down, .5}, {up, .5; down, .5}}, ...
                [0, 0, 0; .5, .5, .5]);
            testCase.verifyEqual( ...
                MagOrderingTransformation.determine_min_cell(one), 2);
            testCase.verifyEqual( ...
                MagOrderingTransformation.determine_min_cell(two), ...
                oracle.determine_min_cell);
        end

        function enumerationPredictionAndDopingAreNative(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            mixed = {{"Li+", .5; "Na+", .5}, ...
                {"Li+", .5; "Na+", .5}};
            disordered = Structure(Lattice.cubic(4), mixed, ...
                [0, 0, 0; .5, .5, .5]);
            enumerator = EnumerateStructureTransformation( ...
                1, 1, .1, false, .001, true, [], "nsites");
            ranked = enumerator.apply_transformation(disordered, 10);
            testCase.verifyNotEmpty(ranked);
            testCase.verifyTrue(all(cellfun( ...
                @(item)item.structure.is_ordered, ranked)));
            testCase.verifyTrue(enumerator.is_one_to_many);
            testCase.verifyError(@()EnumerateStructureTransformation( ...
                1, 2, .1, false, .001, true, 4), ...
                "KSSOLV:Matgenlab:EnumerateStructure:CellLimits");
            m3gnet = EnumerateStructureTransformation( ...
                1, 1, .1, false, .001, true, [], "m3gnet_relax");
            testCase.verifyError(@()m3gnet.apply_transformation( ...
                disordered, 2), ...
                "KSSOLV:Matgenlab:EnumerateStructure:M3GNet");

            table = {"O2-", "O2-", 1.0; "S2-", "S2-", 1.3; ...
                "Li1+", "Li1+", 1.0; "Na1+", "Na1+", 1.0; ...
                "Li1+", "Na1+", .4; "O2-", "S2-", .9};
            structure = Structure(Lattice.cubic(4), ...
                {"Li+", "Li+", "O2-"}, ...
                [0, 0, 0; .5, .5, 0; .25, .25, .25]);
            predictor = SubstitutionPredictorTransformation( ...
                1e-3, true, "lambda_table", table, "alpha", -5);
            testCase.verifyError(@()predictor.apply_transformation( ...
                structure), ...
                "KSSOLV:Matgenlab:SubstitutionPredictor:RankedOnly");
            predictions = predictor.apply_transformation(structure, 10);
            testCase.verifyNotEmpty(predictions);
            testCase.verifyEqual( ...
                predictions{1}.structure.volume, structure.volume, ...
                AbsTol = 1e-12);

            lithium = Structure(Lattice.cubic(4), {"Li+"}, [0, 0, 0]);
            doping = DopingTransformation("Na+", Inf, 4);
            doped = doping.apply_transformation(lithium, 1);
            testCase.verifyNumElements(doped, 1);
            testCase.verifyEqual(doped{1}.structure.formula, "Na1");
            testCase.verifyTrue(doping.is_one_to_many);
        end

        function slabDisorderGrainAndCubicSemantics(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            bulk = Structure.from_spacegroup( ...
                "Fm-3m", Lattice.cubic(3), {"Fe"}, [0, 0, 0]);
            slab = SlabTransformation([1, 1, 1], 10, 10). ...
                apply_transformation(bulk);
            testCase.verifyEqual(slab.lattice.matrix, ...
                oracle.slab_fcc111.lattice, AbsTol = 1e-10);
            testCase.verifyEqual(slab.frac_coords, ...
                oracle.slab_fcc111.frac_coords, AbsTol = 1e-9);

            ordered = Structure(Lattice.hexagonal(3.5, 5), ...
                {"Ba", "Ni", "O", "O", "O"}, ...
                [0, 0, 0; 0, 0, .5; .333, .667, .2; ...
                .667, .333, .8; 0, 0, .1]);
            disorderer = DisorderOrderedTransformation();
            disordered = disorderer.apply_transformation(ordered);
            testCase.verifyFalse(disordered.is_ordered);
            testCase.verifyEqual(disordered.formula, ...
                string(oracle.disorder_ordered.formula));
            testCase.verifyTrue(disorderer.is_one_to_many);
            testCase.verifyError(@()disorderer.apply_transformation( ...
                disordered), ...
                "KSSOLV:Matgenlab:DisorderOrdered:Input");

            iron = Structure(Lattice.cubic(4), {"Fe"}, [0, 0, 0]);
            cubic = CubicSupercellTransformation(1, 100, 7, [], true);
            supercell = cubic.apply_transformation(iron);
            testCase.verifyEqual(cubic.transformation_matrix, ...
                oracle.cubic_diagonal.transformation_matrix);
            testCase.verifyEqual(supercell.num_sites, ...
                oracle.cubic_diagonal.num_sites);
            testCase.verifyTrue(cubic.check_constraints( ...
                repmat([7, 0, 0], 6, 1), 8, supercell));
            [vectors, atoms, possible, matrix] = ...
                cubic.get_possible_supercell( ...
                iron.lattice.matrix, iron, 8 * eye(3)); %#ok<ASGLU>
            testCase.verifyEqual(matrix, 2 * eye(3));
            testCase.verifyEqual(atoms, 8);
            testCase.verifyNumElements(vectors, 18);

            aluminium = Structure.from_spacegroup( ...
                "Fm-3m", Lattice.cubic(2.8575585), {"Al"}, [0, 0, 0]);
            boundary = GrainBoundaryTransformation( ...
                [1, 0, 0], 53.13010235415599, 1, 0, [], ...
                true, true, [0, -1, -3], 20, 1e-8, .6);
            first = boundary.apply_transformation(aluminium);
            second = boundary.apply_transformation(aluminium);
            frozenLattice = [-2.8575585, 0, 0; ...
                0, -8.5726755, 2.8575585; ...
                0, 5.715117, 17.145351];
            testCase.verifyEqual(first.lattice.matrix, ...
                frozenLattice, AbsTol = 1e-12);
            testCase.verifyEqual(first.num_sites, 76);
            testCase.verifyEqual(first.lattice.matrix, ...
                second.lattice.matrix, AbsTol = 1e-12);
            testCase.verifyEqual(first.frac_coords, ...
                second.frac_coords, AbsTol = 1e-12);
        end

        function surfaceSqsRattleAndOfficialFixtures(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            platinum = Structure(Lattice.cubic(5), {"Pt"}, [0, 0, 0]);
            slab = SlabTransformation([0, 0, 1], 20, 10). ...
                apply_transformation(platinum);
            molecule = Molecule({"C", "O"}, [0, 0, 0; 0, 0, 1.23]);
            adsorbate = AddAdsorbateTransformation(molecule);
            adsorbed = adsorbate.apply_transformation(slab);
            substitution = SubstituteSurfaceSiteTransformation("Au");
            substituted = substitution.apply_transformation(slab);
            testCase.verifyEqual(adsorbed.reduced_formula, ...
                string(oracle.adsorbate.reduced_formula));
            testCase.verifyEqual(substituted.reduced_formula, ...
                string(oracle.surface_substitution.reduced_formula));
            testCase.verifyTrue(adsorbate.is_one_to_many);
            testCase.verifyTrue(substitution.is_one_to_many);

            alloy = Structure(Lattice.cubic(4), ...
                {{"Ti", .5; "Zr", .5}}, [0, 0, 0]);
            firstSqs = SQSTransformation(2, [], 1, [], 2);
            secondSqs = SQSTransformation(2, [], 1, [], 2);
            first = firstSqs.apply_transformation(alloy, 1);
            second = secondSqs.apply_transformation(alloy, 1);
            testCase.verifyEqual(first{1}.structure, second{1}.structure);
            testCase.verifyTrue(firstSqs.is_one_to_many);
            testCase.verifyError(@()SQSTransformation(2). ...
                apply_transformation(alloy, true), ...
                "KSSOLV:Matgenlab:SQS:Instances");

            silicon = Structure(Lattice.cubic(5.4), ...
                {"Si", "Si"}, [0, 0, 0; .25, .25, .25]);
            rattleOne = MonteCarloRattleTransformation(.01, 2, 7);
            rattleTwo = MonteCarloRattleTransformation(.01, 2, 7);
            rattledOne = rattleOne.apply_transformation(silicon);
            rattledTwo = rattleTwo.apply_transformation(silicon);
            testCase.verifyEqual(rattledOne.frac_coords, ...
                rattledTwo.frac_coords, AbsTol = 1e-14);
            testCase.verifyNotEqual(rattledOne.frac_coords, ...
                silicon.frac_coords);

            magnetite = Structure.from_file(testCase.fixture("Fe3O4.cif"));
            layered = Structure.from_file( ...
                testCase.fixture("Li8Fe2NiCoO8.cif"));
            testCase.verifyEqual(magnetite.num_sites, 14);
            testCase.verifyEqual(magnetite.reduced_formula, "Fe3O4");
            testCase.verifyEqual(layered.num_sites, 20);
            testCase.verifyEqual(layered.reduced_formula, ...
                "Li8Fe2CoNiO8");
        end

        function everyAdvancedClassMsonRoundTrips(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            molecule = Molecule({"C", "O"}, [0, 0, 0; 0, 0, 1]);
            constraint = MagOrderParameterConstraint(.5, "Fe");
            objects = { ...
                ChargeBalanceTransformation("Li+")
                SuperTransformation({SubstitutionTransformation( ...
                    {"Li+", "Na+"})})
                MultipleSubstitutionTransformation( ...
                    "Li+", .5, {1, "Na"})
                EnumerateStructureTransformation()
                SubstitutionPredictorTransformation()
                constraint
                MagOrderingTransformation({"Fe", 5}, {constraint})
                DopingTransformation("Na+")
                SlabTransformation([0, 0, 1], 10, 10)
                DisorderOrderedTransformation()
                GrainBoundaryTransformation([1, 0, 0], 30)
                CubicSupercellTransformation()
                AddAdsorbateTransformation(molecule)
                SubstituteSurfaceSiteTransformation("Au")
                SQSTransformation(2)
                MonteCarloRattleTransformation(.01, 1, 7)
                };
            for index = 1:numel(objects)
                encoded = kssolv.analysis.matgenlab.util.encode( ...
                    objects{index});
                testCase.verifyFalse(contains(lower(encoded), "python"));
                restored = kssolv.analysis.matgenlab.util.decode(encoded);
                testCase.verifyClass(restored, class(objects{index}));
                testCase.verifyEqual( ...
                    kssolv.analysis.matgenlab.util.encode(restored), ...
                    encoded);
            end
        end
    end

    methods (Static, Access = private)
        function value = oracle()
            value = jsondecode(fileread(fullfile(pwd, "dev", ...
                "matgenlab", "oracles", ...
                "advanced_transformations_2026.7.24.json")));
        end

        function value = fixture(name)
            folder = fileparts(mfilename("fullpath"));
            value = fullfile(folder, "+fixtures", ...
                "advanced_transformations", name);
        end

        function value = chargedStructure()
            coordinates = [0,0,0; .375,.375,.375; .5,.5,.5; ...
                .875,.875,.875; .125,.125,.125; .25,.25,.25; ...
                .625,.625,.625; .75,.75,.75];
            value = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.test.transformations. ...
                AdvancedTransformationsInventoryTest.referenceLattice(), ...
                [repmat({"Li+"}, 1, 6), repmat({"O2-"}, 1, 2)], ...
                coordinates);
        end

        function value = smallChargedStructure()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.test.transformations. ...
                AdvancedTransformationsInventoryTest.referenceLattice(), ...
                {"Li+", "Li+", "O2-", "O2-"}, ...
                [0,0,0; .75,.75,.75; .5,.5,.5; .25,.25,.25]);
        end

        function value = referenceLattice()
            value = kssolv.analysis.matgenlab.core.Lattice( ...
                [3.8401979337,0,0; 1.9200989668,3.3257101909,0; ...
                0,-2.2171384943,3.1355090603]);
        end

        function verifyMembers(className, expected)
            metadata = meta.class.fromName(className);
            available = [string({metadata.MethodList.Name}), ...
                string({metadata.PropertyList.Name})];
            if ~all(ismember(expected, available))
                error("KSSOLV:Matgenlab:AdvancedTransformations:Inventory", ...
                    "Missing members in %s: %s", className, ...
                    strjoin(expected(~ismember(expected, available)), ", "));
            end
        end
    end
end
