classdef StandardTransformationsFrozenOracleTest < matlab.unittest.TestCase
    %STANDARDTRANSFORMATIONSFROZENORACLETEST Frozen pymatgen parity tests.

    methods (Test)
        function frozenInventoryHasAllFortyThreeApis(testCase)
            package = "kssolv.analysis.matgenlab.transformations.";
            classes = ["RotationTransformation", ...
                "OxidationStateDecorationTransformation", ...
                "AutoOxiStateDecorationTransformation", ...
                "OxidationStateRemovalTransformation", ...
                "SupercellTransformation", "SubstitutionTransformation", ...
                "RemoveSpeciesTransformation", ...
                "PartialRemoveSpecieTransformation", ...
                "OrderDisorderedStructureTransformation", ...
                "PrimitiveCellTransformation", ...
                "ConventionalCellTransformation", ...
                "PerturbStructureTransformation", ...
                "DeformStructureTransformation", ...
                "DiscretizeOccupanciesTransformation", ...
                "ChargedCellTransformation", ...
                "ScaleToRelaxedTransformation"];
            specifications = {
                "RotationTransformation", ...
                    ["apply_transformation", "inverse"]
                "OxidationStateDecorationTransformation", ...
                    "apply_transformation"
                "AutoOxiStateDecorationTransformation", ...
                    "apply_transformation"
                "OxidationStateRemovalTransformation", ...
                    "apply_transformation"
                "SupercellTransformation", ...
                    ["from_scaling_factors", "from_boundary_distance", ...
                    "apply_transformation", "inverse"]
                "SubstitutionTransformation", ...
                    ["apply_transformation", "inverse"]
                "RemoveSpeciesTransformation", "apply_transformation"
                "PartialRemoveSpecieTransformation", ...
                    ["apply_transformation", "is_one_to_many"]
                "OrderDisorderedStructureTransformation", ...
                    ["apply_transformation", "is_one_to_many", ...
                    "lowest_energy_structure"]
                "PrimitiveCellTransformation", "apply_transformation"
                "ConventionalCellTransformation", "apply_transformation"
                "PerturbStructureTransformation", "apply_transformation"
                "DeformStructureTransformation", ...
                    ["apply_transformation", "inverse"]
                "DiscretizeOccupanciesTransformation", ...
                    "apply_transformation"
                "ChargedCellTransformation", ...
                    ["apply_transformation", "inverse"]
                "ScaleToRelaxedTransformation", "apply_transformation"
                };
            memberCount = sum(cellfun(@numel, specifications(:, 2)));
            testCase.verifyEqual(numel(classes) + memberCount + 1, 43);
            for name = classes
                testCase.verifyNotEmpty(meta.class.fromName(package + name));
            end
            for index = 1:size(specifications, 1)
                testCase.verifyMembers(package + specifications{index, 1}, ...
                    string(specifications{index, 2}));
            end
            testCase.verifyNotEmpty(which(package + ...
                "get_randomly_manipulated_structures"));
        end

        function rotationAndDeformationMatchOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            lattice = testCase.referenceLattice();
            structure = Structure(lattice, {"Si", "Si"}, ...
                [0, 0, 0; 0.75, 0.5, 0.75]);
            rotation = RotationTransformation([0, 1, 0], 30);
            rotated = rotation.apply_transformation(structure);
            testCase.verifyEqual(rotated.lattice.matrix, ...
                oracle.rotation_matrix, AbsTol = 1e-12);
            restored = rotation.inverse.apply_transformation(rotated);
            testCase.verifyEqual(restored.lattice.matrix, ...
                structure.lattice.matrix, AbsTol = 1e-12);

            coordinates = [0,0,0; .375,.375,.375; .5,.5,.5; ...
                .875,.875,.875; .125,.125,.125; .25,.25,.25; ...
                .625,.625,.625; .75,.75,.75];
            charged = Structure(lattice, ...
                [repmat({"Li+"}, 1, 4), repmat({"O2-"}, 1, 4)], ...
                coordinates);
            deformation = DeformStructureTransformation( ...
                [1,0,0; 0,1,0; 0,.05,1]);
            deformed = deformation.apply_transformation(charged);
            testCase.verifyEqual(deformed.lattice.lengths, ...
                reshape(oracle.deformed_lengths, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(deformation.inverse. ...
                apply_transformation(deformed).lattice.matrix, ...
                charged.lattice.matrix, AbsTol = 1e-11);
        end

        function oxidationDecorationsMatchOfficialFixture(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            plain = Structure(testCase.referenceLattice(), ...
                {"Li", "Li", "O", "O"}, testCase.fourCoordinates());
            decorated = OxidationStateDecorationTransformation( ...
                struct("Li", 1, "O", -2)).apply_transformation(plain);
            labels = cellfun(@(site) site.species_string, decorated.sites);
            testCase.verifyEqual(labels, ...
                reshape(string(oracle.decorated_species), 1, []));
            removed = OxidationStateRemovalTransformation(). ...
                apply_transformation(decorated);
            labels = cellfun(@(site) site.species_string, removed.sites);
            testCase.verifyEqual(labels, ...
                reshape(string(oracle.undecorated_species), 1, []));

            lfp = Structure.from_file( ...
                testCase.fixture("POSCAR_LiFePO4"), "poscar");
            automatic = AutoOxiStateDecorationTransformation(). ...
                apply_transformation(lfp);
            expected = oracle.auto_oxidation_states;
            for index = 1:automatic.num_sites
                specie = automatic(index).specie;
                testCase.verifyEqual(specie.oxi_state, ...
                    expected.(char(specie.symbol)), AbsTol = 1e-12);
            end

            copper = Structure.from_spacegroup( ...
                "Fm-3m", Lattice.cubic(3.677), {"Cu"}, [0, 0, 0]);
            testCase.verifyError(@() ...
                AutoOxiStateDecorationTransformation(). ...
                apply_transformation(copper), ...
                "KSSOLV:Matgenlab:AutoOxiState:Failed");
            zero = AutoOxiStateDecorationTransformation( ...
                .1, 4, 100000, 1.015, true). ...
                apply_transformation(copper);
            testCase.verifyEqual(cellfun(@(site) ...
                site.specie.oxi_state, zero.sites), ...
                zeros(1, zero.num_sites));
        end

        function supercellFactoriesAndErrorsMatchOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            charged = testCase.chargedStructure();
            transformed = SupercellTransformation( ...
                [2,1,0; 0,2,0; 1,0,2]). ...
                apply_transformation(charged);
            testCase.verifyEqual(transformed.formula, ...
                string(oracle.super_formula));
            diagonal = SupercellTransformation. ...
                from_scaling_factors(2, 3, 4);
            testCase.verifyEqual(diagonal.scaling_matrix, diag([2, 3, 4]));
            cubic = Structure.from_spacegroup( ...
                "Pm-3m", 4 * eye(3), {"H"}, [0, 0, 0]);
            fixed = SupercellTransformation. ...
                from_boundary_distance(cubic, 9, false);
            rotated = SupercellTransformation. ...
                from_boundary_distance(cubic, 9, true);
            testCase.verifyEqual(fixed.scaling_matrix, ...
                oracle.boundary_no_rotation);
            testCase.verifyEqual(rotated.scaling_matrix, ...
                oracle.boundary_rotation);
            testCase.verifyEqual([fixed.apply_transformation(cubic).num_sites, ...
                rotated.apply_transformation(cubic).num_sites], ...
                reshape(oracle.boundary_counts, 1, []));
            testCase.verifyError(@() ...
                SupercellTransformation.from_boundary_distance( ...
                charged, 6, false, 10), ...
                "KSSOLV:Matgenlab:SupercellTransformation:MaxAtoms");
            testCase.verifyError(@() testCase.readInverse(fixed), ...
                "KSSOLV:Matgenlab:SupercellTransformation:Inverse");
        end

        function substitutionsAndRemovalMatchOracle(testCase)
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            charged = testCase.chargedStructure();
            substitution = SubstitutionTransformation({
                "Li+", "Na+"
                "O2-", {"S2-", .5; "Se2-", .5}
                });
            changed = substitution.apply_transformation(charged);
            testCase.verifyEqual(changed.formula, ...
                string(oracle.substitution_formula));
            simple = SubstitutionTransformation({
                "Li+", "Na+"
                "O2-", "S2-"
                });
            restored = simple.inverse.apply_transformation( ...
                simple.apply_transformation(charged));
            testCase.verifyEqual(restored.formula, charged.formula);
            removed = RemoveSpeciesTransformation("Li+"). ...
                apply_transformation(charged);
            testCase.verifyEqual(removed.formula, ...
                string(oracle.removed_formula));
            testCase.verifyError(@() testCase.readInverse(substitution), ...
                "KSSOLV:Matgenlab:SubstitutionTransformation:Inverse");
        end

        function orderingAndPartialRemovalMatchOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            six = Structure(Lattice.cubic(10), repmat({"Li+"}, 1, 6), ...
                [0,0,0; .75,.75,.75; .5,.5,.5; .25,.25,.25; ...
                .1,.1,.1; .3,.75,.3]);
            partial = PartialRemoveSpecieTransformation("Li+", .5);
            reduced = partial.apply_transformation(six);
            testCase.verifyTrue(partial.is_one_to_many);
            testCase.verifyEqual(reduced.num_sites, oracle.partial_count);
            testCase.verifyEqual(reduced.frac_coords, ...
                oracle.partial_coords, AbsTol = 1e-12);

            disordered = Structure(testCase.referenceLattice(), ...
                repmat({{"Si4+", .5; "O2-", .25; "P5+", .25}}, ...
                1, 4), testCase.fourCoordinates());
            ordering = OrderDisorderedStructureTransformation();
            ranked = ordering.apply_transformation(disordered, 50);
            testCase.verifyTrue(ordering.is_one_to_many);
            testCase.verifyEqual(numel(ranked), oracle.order_count);
            testCase.verifyEqual(ranked{1}.energy, ...
                oracle.order_energy, AbsTol = 1e-9);
            testCase.verifyEqual(ranked{1}.structure.formula, ...
                string(oracle.order_formula));
            testCase.verifyEqual(ordering.lowest_energy_structure, ...
                ranked{1}.structure);

            tooSmall = Structure(testCase.referenceLattice(), ...
                {{"X4+", .33; "O2-", .33; "P5+", .33}}, ...
                [.5, .5, .5]);
            testCase.verifyError(@() ordering. ...
                apply_transformation(tooSmall), ...
                "KSSOLV:Matgenlab:OrderDisordered:Occupancy");

            alloy = Structure.from_spacegroup("Fm-3m", ...
                Lattice.cubic(3.677), ...
                {{"Cu1+", .5; "Au2+", .5}}, [0, 0, 0]);
            symmetryAware = OrderDisorderedStructureTransformation( ...
                OrderDisorderedStructureTransformation.ALGO_FAST, ...
                true, true);
            alloyRanked = symmetryAware.apply_transformation(alloy, 10);
            testCase.verifyEqual(numel(alloyRanked), 6);
            testCase.verifyEqual(alloyRanked{1}.structure.formula, ...
                "Cu2 Au2");
            testCase.verifyTrue(all(cellfun(@(site) ...
                isa(site.specie, ...
                "kssolv.analysis.matgenlab.core.Element"), ...
                alloyRanked{1}.structure.sites)));
        end

        function primitiveAndConventionalCellsMatchOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            raw = jsondecode(fileread(testCase.fixture("TiO2_super.json")));
            supercell = Structure.from_dict(raw);
            primitive = PrimitiveCellTransformation(). ...
                apply_transformation(supercell);
            testCase.verifyEqual(primitive.formula, ...
                string(oracle.primitive_formula));
            testCase.verifyEqual(primitive.num_sites, ...
                oracle.primitive_count);
            conventional = ConventionalCellTransformation(). ...
                apply_transformation(testCase.chargedStructure());
            testCase.verifyEqual(conventional.lattice.matrix, ...
                oracle.conventional_matrix, AbsTol = 2e-8);
            testCase.verifyEqual(conventional.num_sites, ...
                oracle.conventional_count);
        end

        function perturbDiscretizeAndChargeMatchOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            base = testCase.chargedStructure();
            exact = PerturbStructureTransformation(.05). ...
                apply_transformation(base);
            distances = arrayfun(@(index) ...
                exact(index).distance(base(index)), 1:base.num_sites);
            testCase.verifyEqual(distances, ...
                .05 * ones(1, base.num_sites), AbsTol = 1e-12);
            ranged = PerturbStructureTransformation(.05, 0). ...
                apply_transformation(base);
            distances = arrayfun(@(index) ...
                ranged(index).distance(base(index)), 1:base.num_sites);
            testCase.verifyGreaterThanOrEqual(distances, 0);
            testCase.verifyLessThanOrEqual(distances, .05);

            disordered = Structure(Lattice.cubic(4), ...
                {{"Li", .19; "Na", .19; "K", .62}, {"O", 1}}, ...
                [0,0,0; .5,.5,.5]);
            discretized = DiscretizeOccupanciesTransformation(5, .5). ...
                apply_transformation(disordered);
            expected = oracle.discrete_occupancies;
            testCase.verifyEqual(discretized(1).species("Li"), expected.Li);
            testCase.verifyEqual(discretized(1).species("Na"), expected.Na);
            testCase.verifyEqual(discretized(1).species("K"), expected.K);
            testCase.verifyError(@() ...
                DiscretizeOccupanciesTransformation(5, .01). ...
                apply_transformation(disordered), ...
                "KSSOLV:Matgenlab:DiscretizeOccupancies:Tolerance");
            charged = ChargedCellTransformation(oracle.charge). ...
                apply_transformation(disordered);
            testCase.verifyEqual(charged.charge, oracle.charge);
            transformation = ChargedCellTransformation(3);
            testCase.verifyError(@() testCase.readInverse(transformation), ...
                "KSSOLV:Matgenlab:ChargedCellTransformation:Inverse");
        end

        function officialScaleToRelaxedFixtureMatchesOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            oracle = testCase.oracle();
            initial = Structure.from_file( ...
                testCase.fixture("Cu_slab_init.cif"));
            relaxed = Structure.from_file( ...
                testCase.fixture("Cu_slab_fin.cif"));
            gold = Structure.from_file(testCase.fixture("Au_slab_init.cif"));
            scaled = ScaleToRelaxedTransformation(initial, relaxed). ...
                apply_transformation(gold);
            testCase.verifyEqual([gold.volume, scaled.volume], ...
                reshape(oracle.scale_volume, 1, []), AbsTol = 1e-8);
            testCase.verifyEqual(scaled.lattice.matrix, ...
                oracle.scale_matrix, AbsTol = 2e-8);
            testCase.verifyEqual(scaled.num_sites, oracle.scale_count);
            testCase.verifyEqual(scaled.symbol_set, ...
                string(oracle.scale_species));
            explicit = ScaleToRelaxedTransformation( ...
                initial, relaxed, {"Cu", "Au"}). ...
                apply_transformation(gold);
            testCase.verifyEqual(explicit.lattice.matrix, ...
                scaled.lattice.matrix, AbsTol = 1e-12);
            testCase.verifyEqual(explicit.frac_coords, ...
                scaled.frac_coords, AbsTol = 1e-12);
        end

        function randomManipulationsAreSeededUniqueAndValid(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            structure = Structure(Lattice.cubic(4), ...
                {"Li", "Li", "Li", "Li"}, ...
                [0,0,0; .25,0,0; .5,0,0; .75,0,0]);
            manipulations = {{0, 2, 1:4, "Na"}};
            first = get_randomly_manipulated_structures( ...
                structure, manipulations, 7, 3);
            second = get_randomly_manipulated_structures( ...
                structure, manipulations, 7, 3);
            keys = strings(1, 3);
            for index = 1:3
                testCase.verifyEqual(first{index}.formula, "Na2 Li2");
                testCase.verifyEqual(first{index}, second{index});
                keys(index) = strjoin(cellfun(@(site) ...
                    site.species_string, first{index}.sites), ",");
            end
            testCase.verifyEqual(numel(unique(keys)), 3);
            testCase.verifyError(@() ...
                get_randomly_manipulated_structures( ...
                structure, {{0, 5, 1:4, "Na"}}, 7, 1), ...
                "KSSOLV:Matgenlab:RandomManipulation:Impossible");
        end

        function allTransformationsMsonRoundTrip(testCase)
            import kssolv.analysis.matgenlab.transformations.*
            structure = testCase.chargedStructure();
            objects = {
                RotationTransformation([0, 1, 0], 30)
                OxidationStateDecorationTransformation( ...
                    struct("Li", 1, "O", -2))
                AutoOxiStateDecorationTransformation()
                OxidationStateRemovalTransformation()
                SupercellTransformation([2,0,0; 0,1,0; 0,0,1])
                SubstitutionTransformation({"Li+", "Na+"})
                RemoveSpeciesTransformation("Li+")
                PartialRemoveSpecieTransformation("Li+", .5)
                OrderDisorderedStructureTransformation()
                PrimitiveCellTransformation()
                ConventionalCellTransformation()
                PerturbStructureTransformation(.02)
                DeformStructureTransformation(eye(3))
                DiscretizeOccupanciesTransformation()
                ChargedCellTransformation(2)
                ScaleToRelaxedTransformation(structure, structure)
                };
            for index = 1:numel(objects)
                encoded = kssolv.analysis.matgenlab.util.encode( ...
                    objects{index});
                testCase.verifyFalse(contains(lower(encoded), "python"));
                restored = kssolv.analysis.matgenlab.util.decode(encoded);
                testCase.verifyClass(restored, class(objects{index}));
            end
        end
    end

    methods (Static, Access = private)
        function value = oracle()
            value = jsondecode(fileread( ...
                kssolv.analysis.matgenlab.test.transformations. ...
                StandardTransformationsFrozenOracleTest. ...
                fixture("standard_transformations_oracle.json")));
        end

        function value = fixture(name)
            folder = fileparts(mfilename("fullpath"));
            value = fullfile(folder, "+fixtures", "+standard", name);
        end

        function value = referenceLattice()
            value = kssolv.analysis.matgenlab.core.Lattice( ...
                [3.8401979337,0,0; 1.9200989668,3.3257101909,0; ...
                0,-2.2171384943,3.1355090603]);
        end

        function value = fourCoordinates()
            value = [0,0,0; .75,.75,.75; .5,.5,.5; .25,.25,.25];
        end

        function value = chargedStructure()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.test.transformations. ...
                StandardTransformationsFrozenOracleTest. ...
                referenceLattice(), ...
                {"Li+", "Li+", "O2-", "O2-"}, ...
                kssolv.analysis.matgenlab.test.transformations. ...
                StandardTransformationsFrozenOracleTest. ...
                fourCoordinates());
        end

        function value = readInverse(transformation)
            value = transformation.inverse;
        end

        function verifyMembers(className, expected)
            metadata = meta.class.fromName(className);
            available = [string({metadata.MethodList.Name}), ...
                string({metadata.PropertyList.Name})];
            if ~all(ismember(expected, available))
                error("KSSOLV:Matgenlab:StandardTransformations:Inventory", ...
                    "Missing members in %s: %s", className, ...
                    strjoin(expected(~ismember(expected, available)), ", "));
            end
        end
    end
end
