classdef TransformationsOracleParityTest < matlab.unittest.TestCase
    methods (Test)
        function rotationAndSlabMatchFrozenOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                isAvailable(),"Pinned pymatgen reference is unavailable.");
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*

            structure=Structure(Lattice([3.8401979337,0,0; ...
                1.9200989668,3.3257101909,0; ...
                0,-2.2171384943,3.1355090603]), ...
                {"Si","Si"},[0,0,0;.75,.5,.75]);
            rotation=RotationTransformation([0,1,0],30);
            response=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(struct( ...
                "module","pymatgen.transformations.standard_transformations", ...
                "symbol","RotationTransformation", ...
                "construct",struct("args",{{[0,1,0],30}}), ...
                "operations",{{struct("kind","call", ...
                "name","apply_transformation", ...
                "args",{{structure.asDict()}})}}));
            reference=response.results;
            if iscell(reference),reference=reference{1};end
            actual=rotation.apply_transformation(structure);
            testCase.verifyEqual(actual.lattice.matrix, ...
                reference.lattice.matrix,AbsTol=1e-10);

            bulk=Structure.from_spacegroup( ...
                "Fm-3m",Lattice.cubic(3),{"Fe"},[0,0,0]);
            response=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(struct( ...
                "module","pymatgen.transformations.advanced_transformations", ...
                "symbol","SlabTransformation", ...
                "construct",struct("args",{{[1,1,1],10,10}}), ...
                "operations",{{struct("kind","call", ...
                "name","apply_transformation", ...
                "args",{{bulk.asDict()}})}}));
            reference=response.results;
            if iscell(reference),reference=reference{1};end
            actual=SlabTransformation([1,1,1],10,10). ...
                apply_transformation(bulk);
            oracleSites=reference.sites;
            oracleFractional=reshape([oracleSites.abc],3,[]).';
            testCase.verifyEqual(actual.lattice.matrix, ...
                reference.lattice.matrix,AbsTol=1e-10);
            testCase.verifyEqual(actual.frac_coords, ...
                oracleFractional,AbsTol=1e-10);
        end

        function sigmaFiveBoundaryMatchesFrozenOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                isAvailable(),"Pinned pymatgen reference is unavailable.");
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            bulk=Structure.from_spacegroup( ...
                "Fm-3m",Lattice.cubic(2.8575585),{"Al"},[0,0,0]);
            transformation=GrainBoundaryTransformation( ...
                [1,0,0],53.13010235415599,3,0,[],true,true, ...
                [0,-1,-3],20,1e-8,.6);
            actual=transformation.apply_transformation(bulk);
            kwargs=struct("rotation_axis",[1,0,0], ...
                "rotation_angle",53.13010235415599, ...
                "expand_times",3,"vacuum_thickness",0, ...
                "normal",true,"plane",[0,-1,-3],"rm_ratio",.6);
            response=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(struct( ...
                "module","pymatgen.transformations.advanced_transformations", ...
                "symbol","GrainBoundaryTransformation", ...
                "construct",struct("kwargs",kwargs), ...
                "operations",{{struct("kind","call", ...
                "name","apply_transformation","args",{{bulk.asDict()}})}}));
            reference=response.results;
            if iscell(reference),reference=reference{1};end
            referenceFractional=reshape([reference.sites.abc],3,[]).';
            testCase.verifyEqual(actual.num_sites,size(referenceFractional,1));
            testCase.verifyEqual(actual.lattice.matrix, ...
                reference.lattice.matrix,AbsTol=1e-12);
            % Site order is not part of Structure semantics. The lattice
            % basis itself is frozen above, so compare both directions of
            % the periodic coordinate-set distance without permitting an
            % additional origin shift.
            matrix=actual.lattice.matrix;
            worstReference=0;
            for site=1:size(referenceFractional,1)
                delta=actual.frac_coords-referenceFractional(site,:);
                delta=delta-round(delta);
                worstReference=max(worstReference, ...
                    min(vecnorm(delta*matrix,2,2)));
            end
            worstActual=0;
            for site=1:actual.num_sites
                delta=referenceFractional-actual.frac_coords(site,:);
                delta=delta-round(delta);
                worstActual=max(worstActual, ...
                    min(vecnorm(delta*matrix,2,2)));
            end
            testCase.verifyLessThan( ...
                max(worstReference,worstActual),1e-5);
        end
    end
end
