classdef TransformationsTest < matlab.unittest.TestCase
    methods (Test)
        function siteIndicesAreOneBased(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            structure=Structure(Lattice.cubic(4), ...
                {"Li+","O2-"},[0,0,0;.5,.5,.5]);
            moved=TranslateSitesTransformation(1,[.1,.2,.3]). ...
                apply_transformation(structure);
            testCase.verifyEqual(moved(1).frac_coords,[.1,.2,.3], ...
                AbsTol=1e-12);
            testCase.verifyError(@()TranslateSitesTransformation( ...
                0,[.1,.2,.3]).apply_transformation(structure), ...
                "KSSOLV:Matgenlab:Transformation:SiteIndex");
            replaced=ReplaceSiteSpeciesTransformation({1,"Na+"}). ...
                apply_transformation(structure);
            testCase.verifyEqual(replaced.formula,"Na1 O1");
        end

        function siteTransformationBoundaries(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            structure=Structure(Lattice.cubic(4), ...
                {"Li","O"},[0,0,0;.5,.5,.5]);

            inserted=InsertSitesTransformation( ...
                {"Na"},[.25,.25,.25]).apply_transformation(structure);
            testCase.verifyEqual(inserted.num_sites,3);
            testCase.verifyEqual(inserted.composition("Na"),1);
            removed=RemoveSitesTransformation(2). ...
                apply_transformation(structure);
            testCase.verifyEqual(removed.num_sites,1);
            testCase.verifyEqual(removed.formula,"Li1");

            translation=TranslateSitesTransformation(1,[.1,.2,.3]);
            moved=translation.apply_transformation(structure);
            restored=translation.inverse.apply_transformation(moved);
            testCase.verifyEqual(restored.frac_coords, ...
                structure.frac_coords,AbsTol=1e-12);
            wire=translation.as_dict();
            testCase.verifyEqual(wire.indices_to_move,1);
            testCase.verifyFalse(translation.is_one_to_many);
            testCase.verifyFalse(translation.use_multiprocessing);

            decorated=AddSitePropertyTransformation( ...
                struct("candidate_tag",[3,5])). ...
                apply_transformation(structure);
            testCase.verifyEqual( ...
                [decorated(1).site_properties.candidate_tag, ...
                decorated(2).site_properties.candidate_tag],[3,5]);

            partial=PartialRemoveSitesTransformation({1:2},.5);
            testCase.verifyTrue(partial.is_one_to_many);
            radial=RadialSiteDistortionTransformation(1,.1,false);
            testCase.verifyFalse(radial.is_one_to_many);
            testCase.verifyFalse(radial.use_multiprocessing);
        end

        function frozenStandardAndSiteFixtures(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            lattice=[3.8401979337,0,0;1.9200989668,3.3257101909,0; ...
                0,-2.2171384943,3.1355090603];
            coords=[0,0,0;.375,.375,.375;.5,.5,.5;.875,.875,.875; ...
                .125,.125,.125;.25,.25,.25;.625,.625,.625; ...
                .75,.75,.75];
            structure=Structure(Lattice(lattice), ...
                {"Li+","Li+","Li+","Li+","O2-","O2-","O2-","O2-"}, ...
                coords);
            removal=PartialRemoveSitesTransformation( ...
                {1:4,5:8},[.5,.5], ...
                PartialRemoveSitesTransformation.ALGO_COMPLETE);
            ranked=removal.apply_transformation(structure,12);
            testCase.verifyNumElements(ranked,12);
            testCase.verifyEqual(ranked{1}.structure.formula,"Li2 O2");

            molecule=Molecule([{"C"},repmat({"H"},1,12)], ...
                [0,0,0;1,0,0;0,1,0;0,0,1;-1,0,0;0,-1,0; ...
                0,0,-1;3,0,0;0,3,0;0,0,3;-3,0,0;0,-3,0;0,0,-3]);
            distorted=RadialSiteDistortionTransformation(1,1,true). ...
                apply_transformation(molecule);
            testCase.verifyEqual(distorted.cart_coords(2:7,:), ...
                2*molecule.cart_coords(2:7,:),AbsTol=1e-12);
        end

        function slabMatchesFrozenFcc111Fixture(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            bulk=Structure.from_spacegroup( ...
                "Fm-3m",Lattice.cubic(3),{"Fe"},[0,0,0]);
            slab=SlabTransformation([1,1,1],10,10). ...
                apply_transformation(bulk);
            expected=[1.5,0,-1.5;0,1.5,-1.5;0,0,36];
            testCase.verifyEqual(slab.lattice.matrix,expected,AbsTol=1e-10);
            testCase.verifyEqual(slab.num_sites,6);
            testCase.verifyEqual(slab.frac_coords(:,3),(0:5).'/12, ...
                AbsTol=1e-10);
        end

        function advancedRankAndSurfaceSemantics(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            platinum=Structure(Lattice.cubic(5),{"Pt"},[0,0,0]);
            slab=SlabTransformation([0,0,1],20,10). ...
                apply_transformation(platinum);
            adsorbate=Molecule({"C","O"},[0,0,0;0,0,1.23]);
            adsorbed=AddAdsorbateTransformation(adsorbate). ...
                apply_transformation(slab);
            substituted=SubstituteSurfaceSiteTransformation("Au"). ...
                apply_transformation(slab);
            testCase.verifyEqual(adsorbed.reduced_formula,"Pt4CO");
            testCase.verifyEqual(substituted.reduced_formula,"Pt3Au");

            disordered=Structure(Lattice.cubic(4), ...
                {{"Ti",.5;"Zr",.5}},[0,0,0]);
            sqs=SQSTransformation(2,[],1,[],2);
            ranked=sqs.apply_transformation(disordered,1);
            testCase.verifyNumElements(ranked,1);
            testCase.verifyTrue(ranked{1}.structure.is_ordered);
            testCase.verifyTrue(isfield(ranked{1},"objective_function"));
        end

        function msonRoundTripsNestedTransformations(testCase)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.transformations.*
            structure=Structure(Lattice.cubic(4),{"Li+"},[0,0,0]);
            molecule=Molecule({"C","O"},[0,0,0;0,0,1]);
            objects={ ...
                InsertSitesTransformation({"Na"},[.5,.5,.5]), ...
                ReplaceSiteSpeciesTransformation({1,"Na"}), ...
                SubstitutionTransformation({"Li+","Na+"}), ...
                SuperTransformation({ ...
                    SubstitutionTransformation({"Li+","Na+"})}), ...
                RotationTransformation([0,1,0],30), ...
                TranslateSitesTransformation(1,[.1,.2,.3]), ...
                PartialRemoveSitesTransformation({1},1), ...
                OrderDisorderedStructureTransformation(), ...
                EnumerateStructureTransformation(), ...
                MagOrderingTransformation({"Li+",1}), ...
                DopingTransformation("Na+"), ...
                SlabTransformation([0,0,1],10,10), ...
                GrainBoundaryTransformation([1,0,0],30), ...
                CubicSupercellTransformation(), ...
                AddAdsorbateTransformation(molecule), ...
                SubstituteSurfaceSiteTransformation("Au"), ...
                SQSTransformation(2), ...
                MonteCarloRattleTransformation(.1,1,7), ...
                ScaleToRelaxedTransformation(structure,structure)};
            for index=1:numel(objects)
                encoded=kssolv.analysis.matgenlab.util.encode(objects{index});
                decoded=kssolv.analysis.matgenlab.util.decode(encoded);
                testCase.verifyClass(decoded,class(objects{index}));
            end
        end
    end
end
