classdef PackmolTest < matlab.unittest.TestCase
    methods (Test)
        function movableEulerMatrixAndDerivativesMatchSource(testCase)
            angles = [0.31, -0.72, 1.17];
            [rotation, derivatives] = ...
                kssolv.analysis.packmol.eulerrmat(angles(1), ...
                angles(2), angles(3));
            expected = [ ...
                0.794449231021982, -0.015652542038795, -0.607128830855780; ...
                0.538474886639722,  0.480487825530672,  0.692225574487930; ...
                0.280882921849871, -0.876861703716459,  0.390151684308230];
            testCase.verifyEqual(rotation, expected, AbsTol = 5e-15);
            step = 1e-6;
            for axis = 1:3
                plus = angles;
                minus = angles;
                plus(axis) = plus(axis) + step;
                minus(axis) = minus(axis) - step;
                numerical = (kssolv.analysis.packmol.eulerrmat( ...
                    plus(1), plus(2), plus(3)) - ...
                    kssolv.analysis.packmol.eulerrmat( ...
                    minus(1), minus(2), minus(3))) / (2 * step);
                testCase.verifyEqual(derivatives(:, :, axis), ...
                    numerical, AbsTol = 2e-10);
            end
        end

        function everyConstraintGradientMatchesFiniteDifference(testCase)
            cases = { ...
                2, [0 0 0 3], [-.7 1 4]; ...
                3, [0 0 0 2 3 4], [-.7 1 5]; ...
                4, [0 0 0 2], [3 .2 .1]; ...
                5, [0 0 0 2 3 4 1], [3 .2 .1]; ...
                6, [0 0 0 3], [.8 1.2 1.4]; ...
                7, [0 0 0 2 3 4], [.8 1.2 1.4]; ...
                8, [0 0 0 2], [1 .2 .1]; ...
                9, [0 0 0 2 3 4 1], [1 .2 .1]; ...
                10, [1 2 3 4], [.1 .2 .3]; ...
                11, [1 2 3 0], [.1 .2 .3]; ...
                12, [0 0 0 0 0 1 2 1 4], [3 0 2]; ...
                13, [0 0 0 0 0 1 2 1 4], [1 0 2]; ...
                14, [0 0 2 3 1 4], [.5 .7 0]; ...
                15, [0 0 2 3 1 4], [.5 .7 5]};
            step = 1e-6;
            for i = 1:size(cases, 1)
                type = cases{i, 1};
                parameters = cases{i, 2};
                point = cases{i, 3};
                [~, analytical] = ...
                    kssolv.analysis.packmol.constraint_function( ...
                    type, parameters, point);
                numerical = zeros(1, 3);
                for axis = 1:3
                    plus = point;
                    minus = point;
                    plus(axis) = plus(axis) + step;
                    minus(axis) = minus(axis) - step;
                    numerical(axis) = ( ...
                        kssolv.analysis.packmol.constraint_function( ...
                            type, parameters, plus) - ...
                        kssolv.analysis.packmol.constraint_function( ...
                            type, parameters, minus)) / (2 * step);
                end
                if type == 9
                    % Upstream comprest omits scale2 for this objective
                    % while gwalls keeps it in the analytical gradient.
                    testCase.verifyEqual(analytical, 1e-2 * numerical, ...
                        "Outside-ellipsoid source behavior differs.", ...
                        AbsTol = 3e-8);
                else
                    testCase.verifyEqual(analytical, numerical, ...
                        sprintf( ...
                        "Constraint type %d gradient differs.", type), ...
                        AbsTol = 3e-8);
                end
            end
        end

        function sphericalPenaltyUsesUpstreamScale2(testCase)
            [objective, gradient] = ...
                kssolv.analysis.packmol.constraint_function( ...
                4, [0, 0, 0, 2], [3, 0, 0]);
            testCase.verifyEqual(objective, 0.25, AbsTol = 1e-15);
            testCase.verifyEqual(gradient, [0.6, 0, 0], ...
                AbsTol = 1e-15);
        end

        function rigidObjectiveGradientMatchesFiniteDifference(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "water.xyz"), ...
                "3" + newline + "water" + newline + ...
                "H -0.8 0 0" + newline + ...
                "H 0.8 0 0" + newline + ...
                "O 0 0 0" + newline);
            input = basicInput("water.xyz", 2, ...
                "inside box 0 0 0 10 10 10");
            config = kssolv.analysis.packmol.parse_input( ...
                input, WorkingDirectory = folder);
            system = kssolv.analysis.packmol.prepare_system(config);
            variables = zeros(12, 1);
            variables(1:3) = [5; 5; 5];
            variables(4:6) = [5.5; 5; 5];
            [~, analytical] = ...
                kssolv.analysis.packmol.evaluate(system, variables);
            numerical = centralDifference( ...
                @(value) kssolv.analysis.packmol.evaluate(system, value), ...
                variables);
            testCase.verifyEqual(analytical, numerical, AbsTol = 2e-7);
            clear cleanup
        end

        function fixedPdbOutputIsByteIdenticalToUpstreamOracle(testCase)
            [folder, cleanup] = fixtureFolder();
            water = [ ...
                "HEADER    water"; ...
                "COMPND"; ...
                "SOURCE"; ...
                "HETATM    1  H   HOH     1       9.626   6.787  12.673"; ...
                "HETATM    2  H   HOH     1       9.626   8.420  12.673"; ...
                "HETATM    3  O   HOH     1      10.203   7.604  12.673"; ...
                "CONECT    1    3"; ...
                "CONECT    2    3"; ...
                "CONECT    3    1    2"; ...
                "END"];
            writeText(fullfile(folder, "water.pdb"), ...
                join(water, newline) + newline);
            input = "tolerance 2.0" + newline + ...
                "filetype pdb" + newline + ...
                "output output.pdb" + newline + ...
                "writecrd output.crd" + newline + ...
                "structure water.pdb" + newline + ...
                " number 1" + newline + ...
                " fixed 0 0 0 45 45 45" + newline + ...
                "end structure" + newline;
            kssolv.analysis.packmol.packmol( ...
                input, WorkingDirectory = folder);
            expected = [ ...
                "HEADER "; ...
                pad("TITLE     Built with Packmol", 73); ...
                "REMARK   Packmol generated pdb file "; ...
                "REMARK   Home-Page: http://m3g.iqm.unicamp.br/packmol"; ...
                "REMARK"; ...
                pad("HETATM    1  H   HOH     1      10.406  -0.009  13.822", 80); ...
                pad("HETATM    2  H   HOH     1       9.676  -0.565  15.173", 80); ...
                pad("HETATM    3  O   HOH     1      10.200   0.190  14.780", 80); ...
                "CONECT    1    3"; ...
                "CONECT    2    3"; ...
                "CONECT    3    1    2"; ...
                "END"];
            actual = string(fileread(fullfile(folder, "output.pdb")));
            testCase.verifyEqual(actual, join(expected, newline) + newline);
            expectedCrd = [ ...
                "* TITLE  Built with Packmol                                             "; ...
                "* Packmol generated CHARMM CRD File"; ...
                "* Home-Page:"; ...
                "* http://m3g.iqm.unicamp.br/packmol"; ...
                "* "; ...
                "         3  EXT"; ...
                "         1         1  HOH       H               0.0000000000        0.0000000000        0.0000000000  HOH       1               0.0000000000"; ...
                "         2         1  HOH       H               0.0000000000        0.0000000000        0.0000000000  HOH       1               0.0000000000"; ...
                "         3         1  HOH       O               0.0000000000        0.0000000000        0.0000000000  HOH       1               0.0000000000"];
            actualCrd = string(fileread(fullfile(folder, "output.crd")));
            testCase.verifyEqual(actualCrd, ...
                join(expectedCrd, newline) + newline);
            clear cleanup
        end

        function xyzAndTinkerOutputsAreByteIdenticalToUpstream(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "dimer.xyz"), ...
                "2" + newline + "dimer" + newline + ...
                "H 1 2 3" + newline + "O 4 5 6" + newline);
            xyzInput = "tolerance 2" + newline + ...
                "filetype xyz" + newline + ...
                "output output.xyz" + newline + ...
                "structure dimer.xyz" + newline + ...
                " number 1" + newline + ...
                " fixed 0 0 0 0 0 0" + newline + ...
                "end structure" + newline;
            kssolv.analysis.packmol.packmol( ...
                xyzInput, WorkingDirectory = folder);
            xyzOracle = sprintf([ ...
                '%12d\n %-64s\n' ...
                '  %-3s    %14.6f  %14.6f  %14.6f\n' ...
                '  %-3s    %14.6f  %14.6f  %14.6f\n'], ...
                2, " Built with Packmol ", ...
                "H", 1, 2, 3, "O", 4, 5, 6);
            testCase.verifyEqual( ...
                string(fileread(fullfile(folder, "output.xyz"))), ...
                string(xyzOracle));

            writeText(fullfile(folder, "dimer.txyz"), ...
                "2 dimer" + newline + ...
                "1 H 1 2 3 11 2" + newline + ...
                "2 O 4 5 6 22 1" + newline);
            tinkerInput = "tolerance 2" + newline + ...
                "filetype tinker" + newline + ...
                "output output.txyz" + newline + ...
                "structure dimer.txyz" + newline + ...
                " number 1" + newline + ...
                " fixed 0 0 0 0 0 0" + newline + ...
                "end structure" + newline;
            kssolv.analysis.packmol.packmol( ...
                tinkerInput, WorkingDirectory = folder);
            tinkerOracle = sprintf([ ...
                '%6d  %-64s\n' ...
                '%7d  %-3s  %10.6f  %10.6f  %10.6f  %7d  %7d\n' ...
                '%7d  %-3s  %10.6f  %10.6f  %10.6f  %7d  %7d\n'], ...
                2, " Built with Packmol ", ...
                1, "H", 1, 2, 3, 11, 2, ...
                2, "O", 4, 5, 6, 22, 1);
            testCase.verifyEqual( ...
                string(fileread(fullfile(folder, "output.txyz"))), ...
                string(tinkerOracle));
            clear cleanup
        end

        function restartCheckPdbIsByteIdenticalToUpstream(testCase)
            [folder, cleanup] = fixtureFolder();
            template = [ ...
                "HETATM    1  H   MOL     1      -0.500   0.000   0.000  1.00  0.00           H  "; ...
                "HETATM    2  O   MOL     1       0.500   0.000   0.000  1.00  0.00           O  "; ...
                "CONECT    1    2"; ...
                "CONECT    1    2"; ...
                "CONECT    2    1"; ...
                "END"];
            writeText(fullfile(folder, "dimer.pdb"), ...
                join(template, newline) + newline);
            writeText(fullfile(folder, "restart.dat"), ...
                " 5 5 5 0 0 0" + newline + ...
                " 5.5 5 5 0 0 0" + newline);
            input = "tolerance 2" + newline + ...
                "filetype pdb" + newline + ...
                "output output.pdb" + newline + ...
                "check" + newline + ...
                "restart_from restart.dat" + newline + ...
                "structure dimer.pdb" + newline + ...
                " number 2" + newline + ...
                " inside box 0 0 0 40 40 40" + newline + ...
                "end structure" + newline;
            result = kssolv.analysis.packmol.packmol( ...
                input, WorkingDirectory = folder);
            testCase.verifyEqual(result.initial_objective, 45.25, ...
                AbsTol = 1e-14);
            oracle = [ ...
                "HEADER "; ...
                pad("TITLE     Built with Packmol", 73); ...
                "REMARK   Packmol generated pdb file "; ...
                "REMARK   Home-Page: http://m3g.iqm.unicamp.br/packmol"; ...
                "REMARK"; ...
                "HETATM    1  H   MOL A   1       4.500   5.000   5.000  1.00  0.00           H  "; ...
                "HETATM    2  O   MOL A   1       5.500   5.000   5.000  1.00  0.00           O  "; ...
                "HETATM    3  H   MOL A   2       5.000   5.000   5.000  1.00  0.00           H  "; ...
                "HETATM    4  O   MOL A   2       6.000   5.000   5.000  1.00  0.00           O  "; ...
                "CONECT    1    2"; ...
                "CONECT    1    2"; ...
                "CONECT    2    1"; ...
                "CONECT    3    4"; ...
                "CONECT    3    4"; ...
                "CONECT    4    3"; ...
                "END"];
            testCase.verifyEqual( ...
                string(fileread(fullfile(folder, "output.pdb"))), ...
                join(oracle, newline) + newline);
            clear cleanup
        end

        function nativePackingAndExecutorMeetRequestedTolerance(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "helium.xyz"), ...
                "1" + newline + "helium" + newline + ...
                "He 0 0 0" + newline);
            input = basicInput("helium.xyz", 4, ...
                "inside box 0 0 0 8 8 8");
            writeText(fullfile(folder, "packmol.inp"), input);
            request = struct( ...
                "working_directory", folder, ...
                "stdin_path", "packmol.inp");
            response = kssolv.analysis.packmol.native_executor(request);
            testCase.verifyEqual(response.status, 0);
            result = kssolv.analysis.packmol.packmol( ...
                input, WorkingDirectory = folder, WriteOutput = false);
            testCase.verifyTrue(result.success);
            coordinates = result.coordinates;
            for first = 1:3
                for second = first + 1:4
                    testCase.verifyGreaterThanOrEqual( ...
                        norm(coordinates(first, :) - ...
                        coordinates(second, :)), 2 - 1e-8);
                end
            end
            clear cleanup
        end

        function singleMovableMoleculeEscapesFixedSymmetricTrap(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "ion.xyz"), ...
                "1" + newline + "ion" + newline + "Na 0 0 0" + newline);
            input = "tolerance 2" + newline + ...
                "filetype xyz" + newline + ...
                "output output.xyz" + newline + ...
                "avoid_overlap no" + newline + ...
                "seed 17504" + newline + ...
                "structure ion.xyz" + newline + ...
                " number 1" + newline + ...
                " fixed 0 0 -1 0 0 0" + newline + ...
                "end structure" + newline + ...
                "structure ion.xyz" + newline + ...
                " number 1" + newline + ...
                " fixed 0 0 1 0 0 0" + newline + ...
                "end structure" + newline + ...
                "structure ion.xyz" + newline + ...
                " number 1" + newline + ...
                " inside box -1 -1 -2 1 1 3" + newline + ...
                "end structure" + newline;
            result = kssolv.analysis.packmol.packmol( ...
                input, WorkingDirectory = folder);
            testCase.verifyTrue(result.success);
            testCase.verifyLessThan( ...
                result.diagnostics.evaluation. ...
                maximum_distance_violation, 1e-2);
            testCase.verifyLessThan( ...
                result.diagnostics.evaluation. ...
                maximum_restraint_violation, 1e-2);
            clear cleanup
        end

        function impossibleRestraintsReturnUpstreamConvergenceCode(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "long.xyz"), ...
                "2" + newline + "long" + newline + ...
                "H -5 0 0" + newline + "H 5 0 0" + newline);
            input = "tolerance 2" + newline + ...
                "filetype xyz" + newline + ...
                "output output.xyz" + newline + ...
                "nloop0 2" + newline + ...
                "structure long.xyz" + newline + ...
                " number 1" + newline + ...
                " inside box 0 0 0 1 1 1" + newline + ...
                "end structure" + newline;
            result = kssolv.analysis.packmol.packmol( ...
                input, WorkingDirectory = folder, WriteOutput = false);
            testCase.verifyFalse(result.success);
            codes = kssolv.analysis.packmol.exit_codes();
            testCase.verifyEqual(result.status, codes.failed_to_converge);
            testCase.verifyEqual(result.diagnostics.optimizer.status, ...
                "restraint-only fitting failed");
            clear cleanup
        end

        function periodicPairObjectiveEqualsMinimumImageFormula(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "one.xyz"), ...
                "1" + newline + "one" + newline + "He 0 0 0" + newline);
            input = "tolerance 2" + newline + ...
                "filetype xyz" + newline + ...
                "output out.xyz" + newline + ...
                "pbc 0 0 0 10 10 10" + newline + ...
                "structure one.xyz" + newline + ...
                " number 2" + newline + ...
                "end structure" + newline;
            config = kssolv.analysis.packmol.parse_input( ...
                input, WorkingDirectory = folder);
            system = kssolv.analysis.packmol.prepare_system(config);
            variables = zeros(12, 1);
            variables(1:3) = [.2; 5; 5];
            variables(4:6) = [9.8; 5; 5];
            [objective, gradient, diagnostics] = ...
                kssolv.analysis.packmol.evaluate(system, variables);
            expected = ((.4)^2 - 2^2)^2;
            testCase.verifyEqual(objective, expected, AbsTol = 1e-12);
            testCase.verifyEqual(diagnostics.distance_objective, ...
                expected, AbsTol = 1e-12);
            testCase.verifyEqual(gradient(1), 4 * (.16 - 4) * .4, ...
                AbsTol = 1e-12);
            clear cleanup
        end

        function restartRoundTripPreservesEveryRigidVariable(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "one.xyz"), ...
                "1" + newline + "one" + newline + "He 0 0 0" + newline);
            input = "tolerance 2" + newline + ...
                "filetype xyz" + newline + ...
                "output out.xyz" + newline + ...
                "restart_to state.restart" + newline + ...
                "pbc 0 0 0 10 10 10" + newline + ...
                "structure one.xyz" + newline + ...
                " number 2" + newline + ...
                "end structure" + newline;
            config = kssolv.analysis.packmol.parse_input( ...
                input, WorkingDirectory = folder);
            system = kssolv.analysis.packmol.prepare_system(config);
            variables = (1:12).' / 7;
            kssolv.analysis.packmol.write_restarts(system, variables);
            config.settings.restart_from = "state.restart";
            config.settings.restart_to = "none";
            restartedSystem = ...
                kssolv.analysis.packmol.prepare_system(config);
            actual = kssolv.analysis.packmol.read_restart( ...
                restartedSystem, zeros(12, 1));
            testCase.verifyEqual(actual, variables, AbsTol = 1e-15);
            clear cleanup
        end

        function chkgradWritesAuditAndDoesNotWriteCoordinates(testCase)
            [folder, cleanup] = fixtureFolder();
            writeText(fullfile(folder, "one.xyz"), ...
                "1" + newline + "one" + newline + "He 0 0 0" + newline);
            input = "tolerance 2" + newline + ...
                "filetype xyz" + newline + ...
                "output should_not_exist.xyz" + newline + ...
                "chkgrad" + newline + ...
                "pbc 0 0 0 10 10 10" + newline + ...
                "structure one.xyz" + newline + ...
                " number 1" + newline + ...
                "end structure" + newline;
            result = kssolv.analysis.packmol.packmol( ...
                input, WorkingDirectory = folder, ...
                InitialPoint = [11; 5; 5; 0; 0; 0]);
            testCase.verifyTrue(result.success);
            testCase.verifyLessThan( ...
                result.diagnostics.gradient_check.maximum_error, 1e-6);
            testCase.verifyTrue(isfile(fullfile(folder, "chkgrad.log")));
            testCase.verifyFalse( ...
                isfile(fullfile(folder, "should_not_exist.xyz")));
            clear cleanup
        end

        function commandLineSignatureAcceptsEitherFlagOrder(testCase)
            [folder, cleanup] = fixtureFolder();
            structurePath = fullfile(folder, "one.xyz");
            inputPath = fullfile(folder, "input.inp");
            outputPath = fullfile(folder, "cli.xyz");
            writeText(structurePath, ...
                "1" + newline + "one" + newline + "He 1 2 3" + newline);
            writeText(inputPath, ...
                "tolerance 2" + newline + ...
                "filetype xyz" + newline + ...
                "output ignored.xyz" + newline + ...
                "structure " + structurePath + newline + ...
                " number 1" + newline + ...
                " fixed 0 0 0 0 0 0" + newline + ...
                "end structure" + newline);
            result = kssolv.analysis.packmol.main( ...
                ["-o", outputPath, "-i", inputPath]);
            testCase.verifyEqual(result.status, 0);
            testCase.verifyTrue(isfile(outputPath));
            codes = kssolv.analysis.packmol.exit_codes();
            testCase.verifyEqual([codes.success, codes.general_error, ...
                codes.input_error, codes.open_file, ...
                codes.failed_to_converge, codes.command_line_error], ...
                [0, 170, 171, 172, 173, 174]);
            clear cleanup
        end
    end
end

function value = basicInput(filename, number, constraint)
value = "tolerance 2" + newline + ...
    "filetype xyz" + newline + ...
    "output output.xyz" + newline + ...
    "seed 1" + newline + ...
    "maxit 20" + newline + ...
    "nloop 2" + newline + ...
    "structure " + filename + newline + ...
    " number " + number + newline + ...
    " " + constraint + newline + ...
    "end structure" + newline;
end

function gradient = centralDifference(fun, value)
step = 1e-6;
gradient = zeros(size(value));
for i = 1:numel(value)
    plus = value;
    minus = value;
    plus(i) = plus(i) + step;
    minus(i) = minus(i) - step;
    gradient(i) = (fun(plus) - fun(minus)) / (2 * step);
end
end

function [folder, cleanup] = fixtureFolder()
folder = string(tempname);
mkdir(folder);
cleanup = onCleanup(@() removeFolder(folder));
end

function writeText(path, value)
fileId = fopen(path, "w");
assert(fileId >= 0);
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", char(value));
clear cleanup
end

function removeFolder(folder)
if isfolder(folder)
    rmdir(folder, "s");
end
end
