%#ok<*ALIGN>
classdef DeltaCSMNbSetWeight < ...
        kssolv.analysis.matgenlab.analysis.chemenv.coordination_environments.NbSetWeight
    properties
        effective_csm_estimator struct
        weight_estimator struct
        delta_cn_weight_estimators=[]
        symmetry_measure_type (1,1) string="csm_wcs_ctwcc"
        effective_rf
        weight_rf
        max_effective_csm (1,1) double=8
    end
    methods
        function obj=DeltaCSMNbSetWeight(varargin)
            opts=parseOptions(varargin{:});
            obj.effective_csm_estimator=opts.effective_csm_estimator;
            obj.weight_estimator=opts.weight_estimator;
            obj.delta_cn_weight_estimators=opts.delta_cn_weight_estimators;
            obj.symmetry_measure_type=string(opts.symmetry_measure_type);
            obj.effective_rf=kssolv.analysis.matgenlab.analysis.chemenv. ...
                utils.CSMInfiniteRatioFunction( ...
                opts.effective_csm_estimator.("function"), ...
                opts.effective_csm_estimator.options);
            obj.weight_rf=kssolv.analysis.matgenlab.analysis.chemenv. ...
                utils.DeltaCSMRatioFunction( ...
                opts.weight_estimator.("function"), ...
                opts.weight_estimator.options);
            obj.max_effective_csm=opts.effective_csm_estimator.options.max_csm;
        end
        function value=weight(obj,nbSet,se,varargin)
            opts=parseNamed(struct(cn_map=[],additional_info=[]),varargin{:});
            base=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.get_effective_csm(nbSet, ...
                opts.cn_map,se,opts.additional_info,obj.symmetry_measure_type, ...
                obj.max_effective_csm,obj.effective_rf);
            value=1;maps=se.neighbors_sets{nbSet.isite};
            for cn=maps.keys
                if cn{1}<=opts.cn_map(1),continue,end
                sets=maps(cn{1});
                for ii=1:numel(sets)
                    other=kssolv.analysis.matgenlab.analysis.chemenv. ...
                        coordination_environments.get_effective_csm( ...
                        sets{ii},[cn{1},ii],se,opts.additional_info, ...
                        obj.symmetry_measure_type,obj.max_effective_csm, ...
                        obj.effective_rf);
                    value=min(value,obj.weight_rf.evaluate(other-base));
                end
            end
        end
        function value=as_dict(obj)
            value=struct(x_module="pymatgen.analysis.chemenv."+ ...
                "coordination_environments.chemenv_strategies", ...
                x_class="DeltaCSMNbSetWeight", ...
                effective_csm_estimator=obj.effective_csm_estimator, ...
                weight_estimator=obj.weight_estimator, ...
                delta_cn_weight_estimators=obj.delta_cn_weight_estimators, ...
                symmetry_measure_type=obj.symmetry_measure_type);
        end
    end
    methods (Static)
        function obj=delta_cn_specifics(varargin)
            opts=parseNamed(struct("delta_csm_mins",[], ...
                "delta_csm_maxs",[],"function","smootherstep", ...
                "symmetry_measure_type","csm_wcs_ctwcc", ...
                "effective_csm_estimator",struct( ...
                "function","power2_inverse_decreasing", ...
                options=struct(max_csm=8))),varargin{:});
            if isempty(opts.delta_csm_mins)
                mins=.25+(1:12)*.25;maxs=5+(1:12)*.25;
            else,mins=opts.delta_csm_mins;maxs=opts.delta_csm_maxs;end
            estimator=struct("function",opts.function,options=struct( ...
                delta_csm_min=mins(end),delta_csm_max=maxs(end)));
            obj=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.DeltaCSMNbSetWeight( ...
                "effective_csm_estimator",opts.effective_csm_estimator, ...
                "weight_estimator",estimator, ...
                "delta_cn_weight_estimators",[], ...
                "symmetry_measure_type",opts.symmetry_measure_type);
        end
        function obj=from_dict(value)
            obj=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.DeltaCSMNbSetWeight( ...
                "effective_csm_estimator",value.effective_csm_estimator, ...
                "weight_estimator",value.weight_estimator, ...
                "delta_cn_weight_estimators", ...
                value.delta_cn_weight_estimators, ...
                "symmetry_measure_type",value.symmetry_measure_type);
        end
    end
end
function opts=parseOptions(varargin)
opts=struct(effective_csm_estimator=struct( ...
    "function","power2_inverse_decreasing",options=struct(max_csm=8)), ...
    weight_estimator=struct("function","smootherstep", ...
    options=struct(delta_csm_min=.5,delta_csm_max=3)), ...
    delta_cn_weight_estimators=[],symmetry_measure_type="csm_wcs_ctwcc");
opts=parseNamed(opts,varargin{:});
end
function opts=parseNamed(opts,varargin)
names=fieldnames(opts);pos=1;
while pos<=numel(varargin)&&~(ischar(varargin{pos})||isstring(varargin{pos}))
    if ~isempty(varargin{pos}),opts.(names{pos})=varargin{pos};end;pos=pos+1;
end
for ii=pos:2:numel(varargin),opts.(char(string(varargin{ii})))=varargin{ii+1};end
end
