classdef MultiWeightsChemenvStrategy < ...
        kssolv.analysis.matgenlab.analysis.chemenv.coordination_environments.WeightedNbSetChemenvStrategy
    %MULTIWEIGHTSCHEMENVSTRATEGY Standard multi-weight ChemEnv strategy.
    properties
        dist_ang_area_weight=[]
        self_csm_weight=[]
        delta_csm_weight=[]
        cn_bias_weight=[]
        angle_weight=[]
        normalized_angle_distance_weight=[]
    end
    methods
        function obj=MultiWeightsChemenvStrategy(varargin)
            opts=parseOptions(varargin{:});weights={};
            names=["dist_ang_area_weight","self_csm_weight", ...
                "delta_csm_weight","cn_bias_weight","angle_weight", ...
                "normalized_angle_distance_weight"];
            for name=names
                if ~isempty(opts.(name)),weights{end+1}=opts.(name);end %#ok<AGROW>
            end
            if isempty(weights)
                weights={kssolv.analysis.matgenlab.analysis.chemenv. ...
                    coordination_environments.AngleNbSetWeight()};
            end
            obj@kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.WeightedNbSetChemenvStrategy( ...
                "structure_environments",opts.structure_environments, ...
                "additional_condition",opts.additional_condition, ...
                "symmetry_measure_type",opts.symmetry_measure_type, ...
                "nb_set_weights",weights, ...
                "ce_estimator",opts.ce_estimator);
            for name=names,obj.(name)=opts.(name);end
        end
        function value=as_dict(obj)
            value=struct(x_module="pymatgen.analysis.chemenv."+ ...
                "coordination_environments.chemenv_strategies", ...
                x_class="MultiWeightsChemenvStrategy", ...
                additional_condition=obj.additional_condition, ...
                symmetry_measure_type=obj.symmetry_measure_type, ...
                dist_ang_area_weight=encode(obj.dist_ang_area_weight), ...
                self_csm_weight=encode(obj.self_csm_weight), ...
                delta_csm_weight=encode(obj.delta_csm_weight), ...
                cn_bias_weight=encode(obj.cn_bias_weight), ...
                angle_weight=encode(obj.angle_weight), ...
                normalized_angle_distance_weight= ...
                encode(obj.normalized_angle_distance_weight), ...
                ce_estimator=obj.ce_estimator);
        end
    end
    methods (Static)
        function obj=stats_article_weights_parameters()
            selfWeight=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.SelfCSMNbSetWeight();
            surface=struct(type="standard_elliptic", ...
                distance_bounds=struct(lower=1.15,upper=2), ...
                angle_bounds=struct(lower=.05,upper=.75));
            area=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.DistanceAngleAreaNbSetWeight( ...
                "surface_definition",surface);
            delta=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.DeltaCSMNbSetWeight. ...
                delta_cn_specifics();
            obj=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.MultiWeightsChemenvStrategy( ...
                "dist_ang_area_weight",area,"self_csm_weight",selfWeight, ...
                "delta_csm_weight",delta);
        end
        function obj=from_dict(value)
            names=["dist_ang_area_weight","self_csm_weight", ...
                "delta_csm_weight","cn_bias_weight","angle_weight", ...
                "normalized_angle_distance_weight"];
            args={"additional_condition",value.additional_condition, ...
                "symmetry_measure_type",value.symmetry_measure_type, ...
                "ce_estimator",value.ce_estimator};
            for name=names
                raw=value.(name);
                if ~isNull(raw),args(end+1:end+2)={char(name),decode(raw)};end
            end
            obj=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.MultiWeightsChemenvStrategy(args{:});
        end
    end
end
function opts=parseOptions(varargin)
opts=struct(structure_environments=[],additional_condition=1, ...
    symmetry_measure_type="csm_wcs_ctwcc",dist_ang_area_weight=[], ...
    self_csm_weight=[],delta_csm_weight=[],cn_bias_weight=[], ...
    angle_weight=[],normalized_angle_distance_weight=[], ...
    ce_estimator=struct("function","power2_inverse_power2_decreasing", ...
    options=struct(max_csm=8)));
names=fieldnames(opts);pos=1;
while pos<=numel(varargin)&&~(ischar(varargin{pos})||isstring(varargin{pos}))
    if ~isempty(varargin{pos}),opts.(names{pos})=varargin{pos};end;pos=pos+1;
end
for ii=pos:2:numel(varargin),opts.(char(string(varargin{ii})))=varargin{ii+1};end
end
function value=encode(input)
if isempty(input),value=[];else,value=input.as_dict();end
end
function value=isNull(input)
value=isempty(input)||(isnumeric(input)&&isscalar(input)&&isnan(input));
end
function value=decode(data)
name=char(data.x_class);constructor=str2func("kssolv.analysis.matgenlab."+ ...
    "analysis.chemenv.coordination_environments."+name+".from_dict");
value=constructor(data);
end
