classdef SelfCSMNbSetWeight < ...
        kssolv.analysis.matgenlab.analysis.chemenv.coordination_environments.NbSetWeight
    properties
        effective_csm_estimator struct
        weight_estimator struct
        symmetry_measure_type (1,1) string="csm_wcs_ctwcc"
        effective_csm_estimator_rf
        weight_estimator_rf
        max_effective_csm (1,1) double=8
    end
    methods
        function obj=SelfCSMNbSetWeight(varargin)
            opts=parseOptions(varargin{:});
            obj.effective_csm_estimator=opts.effective_csm_estimator;
            obj.weight_estimator=opts.weight_estimator;
            obj.symmetry_measure_type=string(opts.symmetry_measure_type);
            obj.effective_csm_estimator_rf=kssolv.analysis.matgenlab. ...
                analysis.chemenv.utils.CSMInfiniteRatioFunction( ...
                opts.effective_csm_estimator.("function"), ...
                opts.effective_csm_estimator.options);
            obj.weight_estimator_rf=kssolv.analysis.matgenlab.analysis. ...
                chemenv.utils.CSMFiniteRatioFunction( ...
                opts.weight_estimator.("function"), ...
                opts.weight_estimator.options);
            obj.max_effective_csm=opts.effective_csm_estimator.options.max_csm;
        end
        function value=weight(obj,nbSet,se,varargin)
            opts=parseNamed(struct(cn_map=[],additional_info=[]),varargin{:});
            csm=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.get_effective_csm(nbSet, ...
                opts.cn_map,se,opts.additional_info,obj.symmetry_measure_type, ...
                obj.max_effective_csm,obj.effective_csm_estimator_rf);
            value=obj.weight_estimator_rf.evaluate(csm);
            kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.set_info(opts.additional_info, ...
                "self_csms_weights",nbSet.isite,opts.cn_map,value);
        end
        function value=as_dict(obj)
            value=struct(x_module="pymatgen.analysis.chemenv."+ ...
                "coordination_environments.chemenv_strategies", ...
                x_class="SelfCSMNbSetWeight", ...
                effective_csm_estimator=obj.effective_csm_estimator, ...
                weight_estimator=obj.weight_estimator, ...
                symmetry_measure_type=obj.symmetry_measure_type);
        end
    end
    methods (Static)
        function obj=from_dict(value)
            obj=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.SelfCSMNbSetWeight( ...
                value.effective_csm_estimator,value.weight_estimator, ...
                value.symmetry_measure_type);
        end
    end
end
function opts=parseOptions(varargin)
opts=struct(effective_csm_estimator=struct( ...
    "function","power2_inverse_decreasing", ...
    options=struct(max_csm=8)),weight_estimator=struct( ...
    "function","power2_decreasing_exp", ...
    options=struct(max_csm=8,alpha=1)), ...
    symmetry_measure_type="csm_wcs_ctwcc");
opts=parseNamed(opts,varargin{:});
end
function opts=parseNamed(opts,varargin)
names=fieldnames(opts);pos=1;
while pos<=numel(varargin)&&~(ischar(varargin{pos})||isstring(varargin{pos}))
    if ~isempty(varargin{pos}),opts.(names{pos})=varargin{pos};end;pos=pos+1;
end
for ii=pos:2:numel(varargin),opts.(char(string(varargin{ii})))=varargin{ii+1};end
end
