%#ok<*ALIGN>
classdef TargetedPenaltiedAbundanceChemenvStrategy < ...
        kssolv.analysis.matgenlab.analysis.chemenv.coordination_environments.SimpleAbundanceChemenvStrategy
    %TARGETEDPENALTIEDABUNDANCECHEMENVSTRATEGY Abundance with target bias.
    properties
        max_nabundant (1,1) double=5
        target_environments cell={"O:6"}
        target_penalty_type (1,1) string="max_csm"
        max_csm (1,1) double=5
    end
    methods
        function obj=TargetedPenaltiedAbundanceChemenvStrategy(varargin)
            opts=parseNamed(struct(structure_environments=[], ...
                truncate_dist_ang=true,additional_condition=1, ...
                max_nabundant=5,target_environments={{"O:6"}}, ...
                target_penalty_type="max_csm",max_csm=5, ...
                symmetry_measure_type="csm_wcs_ctwcc"),varargin{:});
            obj@kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.SimpleAbundanceChemenvStrategy( ...
                "structure_environments",opts.structure_environments, ...
                "additional_condition",opts.additional_condition, ...
                "symmetry_measure_type",opts.symmetry_measure_type);
            obj.max_nabundant=opts.max_nabundant;
            if iscell(opts.target_environments)
                obj.target_environments=reshape(opts.target_environments,1,[]);
            else,obj.target_environments=cellstr(string( ...
                    opts.target_environments));end
            obj.target_penalty_type=string(opts.target_penalty_type);
            obj.max_csm=opts.max_csm;
        end
        function value=get_site_coordination_environment( ...
                obj,site,varargin)
            value=get_site_coordination_environment@kssolv.analysis. ...
                matgenlab.analysis.chemenv.coordination_environments. ...
                SimpleAbundanceChemenvStrategy(obj,site,varargin{:});
        end
        function value=as_dict(obj)
            value=struct(x_module="pymatgen.analysis.chemenv."+ ...
                "coordination_environments.chemenv_strategies", ...
                x_class="TargetedPenaltiedAbundanceChemenvStrategy", ...
                additional_condition=obj.additional_condition, ...
                max_nabundant=obj.max_nabundant, ...
                target_environments={obj.target_environments}, ...
                target_penalty_type=obj.target_penalty_type, ...
                max_csm=obj.max_csm);
        end
    end
    methods (Static)
        function obj=from_dict(value)
            obj=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments. ...
                TargetedPenaltiedAbundanceChemenvStrategy( ...
                "additional_condition",value.additional_condition, ...
                "max_nabundant",value.max_nabundant, ...
                "target_environments",value.target_environments, ...
                "target_penalty_type",value.target_penalty_type, ...
                "max_csm",value.max_csm);
        end
    end
    methods (Access=protected)
        function value=getMap(obj,isite)
            entries=obj.structure_environments.voronoi.maps_and_surfaces( ...
                isite,"surface_calculation_type", ...
                obj.surface_calculation_type,"max_dist",2, ...
                "additional_conditions",obj.additional_condition);
            if isempty(entries)
                value=getMap@kssolv.analysis.matgenlab.analysis.chemenv. ...
                    coordination_environments. ...
                    SimpleAbundanceChemenvStrategy(obj,isite);
                return
            end
            surfaces=cellfun(@(x)x.surface,entries);
            [~,order]=sort(surfaces,"descend");
            registry=kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.AllCoordinationGeometries();
            targetCns=zeros(1,numel(obj.target_environments));
            for ii=1:numel(targetCns)
                targetCns(ii)=registry.get_geometry_from_mp_symbol( ...
                    obj.target_environments{ii}).coordination_number;
            end
            value=[];best=Inf;
            for kk=1:min(obj.max_nabundant,numel(order))
                entry=entries{order(kk)};map=entry.map;
                if ~ismember(map(1),targetCns),continue,end
                params=entry.parameters_indices;
                if ~any(cellfun(@(x)x(3)==obj.additional_condition,params))
                    continue
                end
                ce=obj.environmentForMap(isite,map);
                if isempty(ce),continue,end
                geometry=ce.minimum_geometry( ...
                    "symmetry_measure_type",obj.symmetry_measure_type);
                if isempty(geometry),continue,end
                data=geometry{2};metric=data.other_symmetry_measures. ...
                    (char(obj.symmetry_measure_type));
                if any(string(obj.target_environments)==string(geometry{1}))&& ...
                        metric<=obj.max_csm&&metric<best
                    value=map;best=metric;
                end
            end
            if isempty(value)
                value=getMap@kssolv.analysis.matgenlab.analysis.chemenv. ...
                    coordination_environments. ...
                    SimpleAbundanceChemenvStrategy(obj,isite);
            end
        end
    end
end
function opts=parseNamed(opts,varargin)
names=fieldnames(opts);pos=1;
while pos<=numel(varargin)&&~(ischar(varargin{pos})||isstring(varargin{pos}))
    if ~isempty(varargin{pos}),opts.(names{pos})=varargin{pos};end
    pos=pos+1;
end
for ii=pos:2:numel(varargin)
    opts.(char(string(varargin{ii})))=varargin{ii+1};
end
end
