classdef AdsorptionPredictiveBenchmark
    %ADSORPTIONPREDICTIVEBENCHMARK External predictive validation of scorers.
    %
    % This benchmark evaluates the unmodified production UFF surface scorer
    % against a frozen primary-literature dataset. It is intentionally scoped
    % to rigid graphitic physisorption and must not be used to claim accuracy
    % for chemisorption, polar surfaces, relaxation or adsorption enthalpies.

    properties (Constant)
        Id = "kssolv-rare-gas-graphite-benchmark-v1"
        Version = "1.0.0"
        EnergyMaeThresholdEv = 0.012
        DistanceMaeThresholdAngstrom = 0.10
    end

    methods (Static)
        function result = rareGasGraphite(options)
            arguments
                options.Heights double = 2.6:0.01:4.2
            end
            heights = reshape(double(options.Heights), 1, []);
            if isempty(heights) || any(~isfinite(heights)) || ...
                    any(heights <= 0) || any(diff(heights) <= 0)
                error("KSSOLV:Modeling:AdsorptionBenchmarkHeights", ...
                    "Benchmark heights must be finite, positive and increasing.");
            end
            reference = kssolv.modeling.adsorption. ...
                AdsorptionReferenceCatalog.rareGasGraphite();
            host = graphenePrimitiveCell();
            matrix = double(host.lattice.matrix);
            lateral = [1/3, 1/3, 0.5] * matrix;
            records = reference.records;
            entries = repmat(struct( ...
                "symbol", "", ...
                "referenceBindingEnergyEv", NaN, ...
                "predictedBindingEnergyEv", NaN, ...
                "absoluteEnergyErrorEv", NaN, ...
                "referenceDistanceAngstrom", NaN, ...
                "predictedDistanceAngstrom", NaN, ...
                "absoluteDistanceErrorAngstrom", NaN), 1, numel(records));
            for index = 1:numel(records)
                adsorbate = kssolv.analysis.matgenlab.core.Molecule( ...
                    records(index).symbol, [0, 0, 0], ...
                    charge_spin_check = false);
                energies = zeros(size(heights));
                for heightIndex = 1:numel(heights)
                    coordinates = lateral + [0, 0, heights(heightIndex)];
                    energies(heightIndex) = ...
                        kssolv.modeling.adsorption.UffSurfaceScorer. ...
                        evaluate(host, adsorbate, coordinates, struct());
                end
                [minimumEnergy, minimumIndex] = min(energies);
                predictedBinding = -minimumEnergy;
                predictedDistance = heights(minimumIndex);
                entries(index) = struct( ...
                    "symbol", records(index).symbol, ...
                    "referenceBindingEnergyEv", ...
                        records(index).bindingEnergyEv, ...
                    "predictedBindingEnergyEv", predictedBinding, ...
                    "absoluteEnergyErrorEv", abs(predictedBinding - ...
                        records(index).bindingEnergyEv), ...
                    "referenceDistanceAngstrom", ...
                        records(index).equilibriumDistanceAngstrom, ...
                    "predictedDistanceAngstrom", predictedDistance, ...
                    "absoluteDistanceErrorAngstrom", ...
                        abs(predictedDistance - ...
                        records(index).equilibriumDistanceAngstrom));
            end
            referenceEnergies = [entries.referenceBindingEnergyEv];
            predictedEnergies = [entries.predictedBindingEnergyEv];
            [~, referenceOrder] = sort(referenceEnergies, "ascend");
            [~, predictedOrder] = sort(predictedEnergies, "ascend");
            symbols = string({entries.symbol});
            rankingExact = isequal( ...
                symbols(referenceOrder), symbols(predictedOrder));
            energyMae = mean([entries.absoluteEnergyErrorEv]);
            distanceMae = mean( ...
                [entries.absoluteDistanceErrorAngstrom]);
            passed = rankingExact && ...
                energyMae <= kssolv.modeling.adsorption. ...
                    AdsorptionPredictiveBenchmark.EnergyMaeThresholdEv && ...
                distanceMae <= kssolv.modeling.adsorption. ...
                    AdsorptionPredictiveBenchmark. ...
                    DistanceMaeThresholdAngstrom;
            result = struct( ...
                "schemaVersion", 1, ...
                "id", kssolv.modeling.adsorption. ...
                    AdsorptionPredictiveBenchmark.Id, ...
                "version", kssolv.modeling.adsorption. ...
                    AdsorptionPredictiveBenchmark.Version, ...
                "scoringModel", ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.Id, ...
                "reference", rmfield(reference, "records"), ...
                "proxySurface", ...
                    "periodic single-layer graphene primitive cell", ...
                "lateralSite", "graphene hollow-site proxy", ...
                "heightGridAngstrom", heights, ...
                "entries", entries, ...
                "referenceOrder", symbols(referenceOrder), ...
                "predictedOrder", symbols(predictedOrder), ...
                "rankingExact", rankingExact, ...
                "energyMaeEv", energyMae, ...
                "energyMaeThresholdEv", ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionPredictiveBenchmark.EnergyMaeThresholdEv, ...
                "distanceMaeAngstrom", distanceMae, ...
                "distanceMaeThresholdAngstrom", ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionPredictiveBenchmark. ...
                    DistanceMaeThresholdAngstrom, ...
                "parameterFittedToReference", false, ...
                "validationScope", ...
                    "Rigid low-coverage graphitic rare-gas physisorption only", ...
                "limitations", [ ...
                    "Single-layer graphene proxy for graphitized carbon"; ...
                    "No substrate or adsorbate relaxation"; ...
                    "No electrostatics, charge transfer or bond formation"; ...
                    "Interaction potential minimum, not adsorption enthalpy"], ...
                "passed", passed);
        end
    end
end

function host = graphenePrimitiveCell()
a = 2.46;
lattice = kssolv.analysis.matgenlab.core.Lattice( ...
    [a, 0, 0; a/2, a*sqrt(3)/2, 0; 0, 0, 25], ...
    [true, true, false]);
host = kssolv.analysis.matgenlab.core.Structure( ...
    lattice, ["C", "C"], [0, 0, 0.5; 1/3, 2/3, 0.5]);
end
