classdef AdsorptionReferenceCatalog
    %ADSORPTIONREFERENCECATALOG Frozen external adsorption benchmarks.
    %
    % Reference values are factual data transcribed from primary literature.
    % They are kept separate from force-field parameters so production models
    % cannot silently tune themselves to their own acceptance oracle.

    properties (Constant)
        BoltzmannEvPerKelvin = 8.617333262145e-5
    end

    methods (Static)
        function dataset = rareGasGraphite()
            % Low-coverage rare-gas interaction with graphitized carbon
            % black P33(2700), inferred from experimental adsorption
            % isotherms by Rybolt and Pierotti, J. Chem. Phys. 70 (1979)
            % 4413-4419, DOI 10.1063/1.438015.
            symbols = ["Ne", "Ar", "Kr", "Xe"];
            distances = [3.07, 3.33, 3.36, 3.66];
            energiesKelvin = [384, 1113, 1467, 1928];
            records = repmat(struct( ...
                "symbol", "", ...
                "equilibriumDistanceAngstrom", NaN, ...
                "bindingEnergyKelvin", NaN, ...
                "bindingEnergyEv", NaN), 1, numel(symbols));
            for index = 1:numel(symbols)
                records(index) = struct( ...
                    "symbol", symbols(index), ...
                    "equilibriumDistanceAngstrom", distances(index), ...
                    "bindingEnergyKelvin", energiesKelvin(index), ...
                    "bindingEnergyEv", energiesKelvin(index) * ...
                        kssolv.modeling.adsorption. ...
                        AdsorptionReferenceCatalog.BoltzmannEvPerKelvin);
            end
            dataset = struct( ...
                "id", "rybolt-pierotti-rare-gas-graphite-1979", ...
                "version", 1, ...
                "system", "Ne/Ar/Kr/Xe on graphitic carbon at low coverage", ...
                "referenceSurface", ...
                    "graphitized carbon black P33(2700)", ...
                "observable", ...
                    "gas-solid interaction potential minimum", ...
                "source", ...
                    "Rybolt and Pierotti, J. Chem. Phys. 70 (1979) 4413-4419", ...
                "doi", "10.1063/1.438015", ...
                "dataOrigin", ...
                    "experimental low-coverage adsorption isotherms", ...
                "records", records);
        end
    end
end
