classdef AdsorptionScoringModel
    %ADSORPTIONSCORINGMODEL Validated contract for locator score plug-ins.
    %
    % The built-in model is intentionally geometric.  External force-field
    % or electronic-structure scorers may be injected, but an energy scorer
    % must declare its unit, source, version and validation reference before
    % the Locator is allowed to label the result as energy.

    properties (Constant)
        SchemaVersion = 2
        GeometryId = "kssolv-geometric-contact-v1"
    end

    methods (Static)
        function descriptor = resolve(identifier, evaluator, contract)
            arguments
                identifier {mustBeTextScalar} = ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionScoringModel.GeometryId
                evaluator = []
                contract (1,1) struct = struct()
            end
            identifier = string(identifier);
            if identifier == ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionScoringModel.GeometryId
                if ~isempty(evaluator) || ~isempty(fieldnames(contract))
                    error("KSSOLV:Modeling:AdsorptionScorerConflict", ...
                        "The built-in geometry scorer cannot be overridden.");
                end
                descriptor = struct( ...
                    "schemaVersion", ...
                        kssolv.modeling.adsorption. ...
                        AdsorptionScoringModel.SchemaVersion, ...
                    "id", identifier, ...
                    "isEnergyModel", false, "scoreUnit", "", ...
                    "source", "KSSOLV periodic contact geometry", ...
                    "version", "1", "validated", true, ...
                    "validationReference", ...
                        "built-in deterministic geometry regression", ...
                    "validationScope", ...
                        "Deterministic contact geometry and ordering", ...
                    "parameterCoverage", "Any finite atomic coordinates", ...
                    "physicalInterpretation", ...
                        "Dimensionless short-range contact score", ...
                    "limitations", ...
                        "Geometric contact score only; not adsorption energy", ...
                    "evaluator", []);
                return
            end
            if identifier == ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.Id
                if ~isempty(evaluator) || ~isempty(fieldnames(contract))
                    error("KSSOLV:Modeling:AdsorptionScorerConflict", ...
                        "The built-in UFF surface scorer cannot be overridden.");
                end
                descriptor = kssolv.modeling.adsorption. ...
                    UffSurfaceScorer.descriptor();
                return
            end
            if ~isa(evaluator, "function_handle")
                error("KSSOLV:Modeling:AdsorptionScorerFunction", ...
                    "A custom adsorption scorer requires a function handle.");
            end
            required = ["id", "isEnergyModel", "scoreUnit", "source", ...
                "version", "validated", "validationReference", "limitations"];
            if ~all(isfield(contract, required))
                error("KSSOLV:Modeling:AdsorptionScorerContract", ...
                    "The custom scorer contract is incomplete.");
            end
            descriptor = struct( ...
                "schemaVersion", ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionScoringModel.SchemaVersion, ...
                "id", string(contract.id), ...
                "isEnergyModel", logical(contract.isEnergyModel), ...
                "scoreUnit", string(contract.scoreUnit), ...
                "source", string(contract.source), ...
                "version", string(contract.version), ...
                "validated", logical(contract.validated), ...
                "validationReference", ...
                    string(contract.validationReference), ...
                "validationScope", optionalText(contract, ...
                    "validationScope", "Contract-declared validation"), ...
                "parameterCoverage", optionalText(contract, ...
                    "parameterCoverage", "Contract-declared inputs"), ...
                "physicalInterpretation", optionalText(contract, ...
                    "physicalInterpretation", "External scorer value"), ...
                "limitations", reshape(string(contract.limitations), 1, []), ...
                "evaluator", evaluator);
            validateDescriptor(descriptor, identifier);
        end

        function score = evaluate(descriptor, host, adsorbate, ...
                coordinates, context)
            if isempty(descriptor.evaluator)
                error("KSSOLV:Modeling:AdsorptionScorerBuiltIn", ...
                    "The built-in geometry score is evaluated by the Locator.");
            end
            score = descriptor.evaluator(host, adsorbate, coordinates, context);
            if ~(isnumeric(score) && isscalar(score) && isreal(score) && ...
                    isfinite(score))
                error("KSSOLV:Modeling:AdsorptionScorerResult", ...
                    "Adsorption scorer '%s' returned a non-finite scalar.", ...
                    descriptor.id);
            end
            score = double(score);
        end

        function metadata = publicMetadata(descriptor)
            metadata = rmfield(descriptor, "evaluator");
        end
    end
end

function value = optionalText(contract, name, fallback)
if isfield(contract, name) && string(contract.(name)) ~= ""
    value = string(contract.(name));
else
    value = string(fallback);
end
end

function validateDescriptor(descriptor, requestedIdentifier)
if descriptor.id == "" || descriptor.id ~= string(requestedIdentifier)
    error("KSSOLV:Modeling:AdsorptionScorerIdentifier", ...
        "The requested scorer identifier must match its contract id.");
end
if ~isscalar(descriptor.isEnergyModel) || ~isscalar(descriptor.validated)
    error("KSSOLV:Modeling:AdsorptionScorerContract", ...
        "Scorer energy and validation flags must be scalar logical values.");
end
if descriptor.source == "" || descriptor.version == "" || ...
        descriptor.validationReference == "" || ~descriptor.validated
    error("KSSOLV:Modeling:AdsorptionScorerValidation", ...
        "A custom scorer requires a nonempty source, version and validation reference.");
end
if descriptor.isEnergyModel && descriptor.scoreUnit == ""
    error("KSSOLV:Modeling:AdsorptionScorerEnergyUnit", ...
        "An energy scorer must declare its energy unit.");
end
if ~descriptor.isEnergyModel && descriptor.scoreUnit ~= ""
    error("KSSOLV:Modeling:AdsorptionScorerNonEnergyUnit", ...
        "A non-energy scorer must not declare an energy unit.");
end
end
