classdef AdsorptionLocator
    %ADSORPTIONLOCATOR Deterministic adsorbate candidate generator.
    %
    % The built-in score is deliberately a geometric contact score, not an
    % adsorption energy.  A future validated surface force field may replace
    % the scorer without changing candidate generation or result ordering.

    properties (Constant)
        SchemaVersion = 1
        GeometryScorer = kssolv.modeling.adsorption. ...
            AdsorptionScoringModel.GeometryId
    end

    methods (Static)
        function analysis = search(host, adsorbate, options)
            arguments
                host
                adsorbate
                options.SiteTypes string = ["ontop","bridge","hollow"]
                options.Heights double = [1.8, 2.1, 2.4]
                options.RotationStep (1,1) double {mustBePositive} = 30
                options.AnchorAtom (1,1) double ...
                    {mustBeInteger,mustBePositive} = 1
                options.OrientationAtom (1,1) double ...
                    {mustBeInteger,mustBeNonnegative} = 0
                options.MinimumDistance (1,1) double ...
                    {mustBeNonnegative} = .6
                options.MaximumCandidates (1,1) double ...
                    {mustBeInteger,mustBePositive} = 200
                options.Seed (1,1) double {mustBeInteger} = 0
                options.CancelFcn (1,1) function_handle = @()false
                options.ScoringModel {mustBeTextScalar} = ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionScoringModel.GeometryId
                options.ScoringFunction = []
                options.ScoringContract (1,1) struct = struct()
            end
            kssolv.modeling.builders.BuilderUtils.requireStructure(host);
            if ~(isa(adsorbate, ...
                    "kssolv.analysis.matgenlab.core.IMolecule") || ...
                    isa(adsorbate, ...
                    "kssolv.analysis.matgenlab.core.IStructure"))
                error("KSSOLV:Modeling:AdsorptionLocatorAdsorbate", ...
                    "Adsorption Locator requires a molecule or structure adsorbate.");
            end
            if options.AnchorAtom > adsorbate.num_sites || ...
                    options.OrientationAtom > adsorbate.num_sites
                error("KSSOLV:Modeling:AdsorptionLocatorAnchor", ...
                    "Adsorbate anchor/orientation indices are outside the model.");
            end
            heights = unique(reshape(double(options.Heights), 1, []), ...
                "stable");
            if isempty(heights) || any(~isfinite(heights)) || any(heights <= 0)
                error("KSSOLV:Modeling:AdsorptionLocatorHeights", ...
                    "Candidate heights must be finite positive values.");
            end
            if options.RotationStep > 360
                error("KSSOLV:Modeling:AdsorptionLocatorRotation", ...
                    "Rotation step must not exceed 360 degrees.");
            end
            siteTypes = lower(unique(reshape(options.SiteTypes, 1, []), ...
                "stable"));
            siteTypes = siteTypes(siteTypes ~= "" & siteTypes ~= "all");
            if isempty(siteTypes)
                error("KSSOLV:Modeling:AdsorptionLocatorSiteType", ...
                    "At least one explicit adsorption-site type is required.");
            end
            scorer = kssolv.modeling.adsorption. ...
                AdsorptionScoringModel.resolve( ...
                options.ScoringModel, options.ScoringFunction, ...
                options.ScoringContract);
            scorerMetadata = kssolv.modeling.adsorption. ...
                AdsorptionScoringModel.publicMetadata(scorer);

            finder = kssolv.analysis.matgenlab.core. ...
                AdsorbateSiteFinder(host);
            sites = finder.find_adsorption_sites(0);
            normal = host.lattice.matrix(3, :);
            normal = normal / norm(normal);
            hostFractional = double(host.frac_coords);
            local = adsorbate.cart_coords - ...
                adsorbate.cart_coords(options.AnchorAtom, :);
            if options.OrientationAtom > 0 && ...
                    options.OrientationAtom ~= options.AnchorAtom
                direction = local(options.OrientationAtom, :);
                if norm(direction) <= eps
                    error("KSSOLV:Modeling:AdsorptionLocatorOrientation", ...
                        "Anchor and orientation atoms cannot coincide.");
                end
                local = local * align(direction, normal).';
            end
            rotations = 0:options.RotationStep:360;
            rotations = rotations(rotations < 360 - 1e-10);
            siteCount = 0;
            for siteType = siteTypes
                field = char(siteType);
                if isfield(sites, field)
                    siteCount = siteCount + size(sites.(field), 1);
                end
            end
            maximumRecords = siteCount * numel(heights) * numel(rotations);
            records = repmat(emptyCandidate(), maximumRecords, 1);
            recordCount = 0;
            sequence = 0;
            cancelled = false;
            for siteType = siteTypes
                field = char(siteType);
                if ~isfield(sites, field) || isempty(sites.(field))
                    continue
                end
                positions = double(sites.(field));
                for siteIndex = 1:size(positions, 1)
                    for height = heights
                        target = positions(siteIndex, :) + height * normal;
                        for rotation = rotations
                            if options.CancelFcn()
                                cancelled = true;
                                break
                            end
                            sequence = sequence + 1;
                            matrix = axisRotation(normal, rotation);
                            coordinates = local * matrix.' + target;
                            [geometricValue, contact] = geometricScore( ...
                                host.lattice, hostFractional, coordinates, ...
                                options.MinimumDistance);
                            if isfinite(geometricValue)
                                context = struct( ...
                                    "sequence", sequence, ...
                                    "siteType", siteType, ...
                                    "siteIndex", siteIndex, ...
                                    "site", positions(siteIndex, :), ...
                                    "height", height, ...
                                    "rotationDegrees", rotation, ...
                                    "minimumContact", contact, ...
                                    "boundaryCondition", ...
                                        "periodic-minimum-image");
                                if isempty(scorer.evaluator)
                                    score = geometricValue;
                                else
                                    score = kssolv.modeling.adsorption. ...
                                        AdsorptionScoringModel.evaluate( ...
                                        scorer, host, adsorbate, ...
                                        coordinates, context);
                                end
                                recordCount = recordCount + 1;
                                item = emptyCandidate();
                                item.sequence = sequence;
                                item.siteType = siteType;
                                item.siteIndex = siteIndex;
                                item.site = positions(siteIndex, :);
                                item.height = height;
                                item.rotationDegrees = rotation;
                                item.score = score;
                                item.minimumContact = contact;
                                item.coordinates = coordinates;
                                item.scoringModel = scorer.id;
                                item.isEnergyModel = scorer.isEnergyModel;
                                item.scoreUnit = scorer.scoreUnit;
                                item.scoringContract = scorerMetadata;
                                records(recordCount, 1) = item;
                            end
                        end
                        if cancelled, break, end
                    end
                    if cancelled, break, end
                end
                if cancelled, break, end
            end
            records = records(1:recordCount);
            if isempty(records) && ~cancelled
                error("KSSOLV:Modeling:AdsorptionLocatorNoCandidates", ...
                    "No collision-free adsorption candidates were generated.");
            end
            if ~isempty(records)
                ordering = [[records.score].', ...
                    -[records.minimumContact].', [records.sequence].'];
                [~, order] = sortrows(ordering, [1, 2, 3]);
                records = records(order);
                records = records(1:min(numel(records), ...
                    options.MaximumCandidates));
                for index = 1:numel(records)
                    records(index).rank = index;
                    records(index).id = "candidate-" + string(index);
                end
            end
            limitations = [reshape(string(scorer.limitations), 1, []), ...
                "Host and adsorbate coordinates remain rigid during enumeration"];
            if isempty(scorer.evaluator)
                limitations = [limitations, ...
                    "No electronic, electrostatic, solvent, or surface-relaxation terms"];
            end
            analysis = struct( ...
                "schemaVersion", ...
                    kssolv.modeling.adsorption.AdsorptionLocator.SchemaVersion, ...
                "searchKind", "geometry-candidate-search", ...
                "samplingMode", "exhaustive", ...
                "scoringModel", scorer.id, ...
                "scoringContract", scorerMetadata, ...
                "isEnergyModel", scorer.isEnergyModel, ...
                "energyUnit", scorer.scoreUnit, ...
                "seed", options.Seed, ...
                "siteTypes", siteTypes, "heights", heights, ...
                "rotationStep", options.RotationStep, ...
                "minimumDistance", options.MinimumDistance, ...
                "boundaryCondition", "periodic-minimum-image", ...
                "candidateCount", numel(records), ...
                "cancelled", cancelled, "candidates", records, ...
                "limitations", limitations);
        end

        function output = applyCandidate(host, adsorbate, candidate, options)
            %APPLYCANDIDATE Materialize one ranked geometry without relaxation.
            arguments
                host
                adsorbate
                candidate (1,1) struct
                options.MinimumDistance (1,1) double ...
                    {mustBeNonnegative} = .35
            end
            kssolv.modeling.builders.BuilderUtils.requireStructure(host);
            if ~(isa(adsorbate, ...
                    "kssolv.analysis.matgenlab.core.IMolecule") || ...
                    isa(adsorbate, ...
                    "kssolv.analysis.matgenlab.core.IStructure"))
                error("KSSOLV:Modeling:AdsorptionLocatorAdsorbate", ...
                    "Applying a candidate requires its molecule or structure adsorbate.");
            end
            required = ["id", "rank", "siteType", "siteIndex", ...
                "site", "height", "rotationDegrees", "score", ...
                "minimumContact", "coordinates", "scoringModel", ...
                "isEnergyModel", "scoreUnit", "scoringContract"];
            if ~all(isfield(candidate, required)) || ...
                    ~isequal(size(candidate.coordinates), ...
                    [adsorbate.num_sites, 3]) || ...
                    any(~isfinite(candidate.coordinates), "all")
                error("KSSOLV:Modeling:AdsorptionLocatorCandidate", ...
                    "The adsorption candidate is incomplete or incompatible with the adsorbate.");
            end
            species = reshape(string(adsorbate.species), 1, []);
            labels = species + "_ads" + string(1:adsorbate.num_sites);
            guest = kssolv.analysis.matgenlab.core.Structure( ...
                host.lattice, adsorbate.species_and_occu, ...
                candidate.coordinates, coords_are_cartesian = true, ...
                labels = labels, site_properties = adsorbate.site_properties, ...
                skip_checks = true);
            output = kssolv.modeling.builders.InsertStructureBuilder.build( ...
                host, guest, minimumDistance = options.MinimumDistance, ...
                wrap = false);
            properties = output.structure_properties;
            properties.adsorptionCandidate = struct( ...
                "schemaVersion", 1, "candidateId", string(candidate.id), ...
                "rank", candidate.rank, "siteType", string(candidate.siteType), ...
                "siteIndex", candidate.siteIndex, "site", candidate.site, ...
                "height", candidate.height, ...
                "rotationDegrees", candidate.rotationDegrees, ...
                "score", candidate.score, ...
                "minimumContact", candidate.minimumContact, ...
                "scoringModel", string(candidate.scoringModel), ...
                "scoringContract", candidate.scoringContract, ...
                "isEnergyModel", logical(candidate.isEnergyModel), ...
                "energyUnit", string(candidate.scoreUnit), ...
                "guestFormula", adsorbate.formula, ...
                "coordinates", candidate.coordinates, ...
                "bonds", adsorbateBonds(adsorbate));
            output = output.copy([], false, properties);
        end
    end
end

function item = emptyCandidate()
item = struct("id", "", "rank", 0, "sequence", 0, ...
    "siteType", "", "siteIndex", 0, "site", zeros(1,3), ...
    "height", 0, "rotationDegrees", 0, "score", Inf, ...
    "minimumContact", 0, "coordinates", zeros(0,3), ...
    "scoringModel", "", "isEnergyModel", false, "scoreUnit", "", ...
    "scoringContract", struct());
end

function [score, minimumContact] = geometricScore( ...
        lattice, hostFractional, guestCartesian, cutoff)
guestFractional = guestCartesian / lattice.matrix;
[~, distancesSquared] = ...
    kssolv.analysis.matgenlab.util.pbc_shortest_vectors( ...
    lattice, hostFractional, guestFractional, [], true);
distances = sqrt(distancesSquared);
minimumContact = min(distances, [], "all");
if minimumContact < cutoff
    score = Inf;
    return
end
scale = max(cutoff, .5);
score = sum((scale ./ distances).^12, "all");
end

function rotation = align(source, target)
source = source / norm(source);
target = target / norm(target);
crossValue = cross(source, target);
sine = norm(crossValue);
cosine = dot(source, target);
if sine < 1e-12
    if cosine > 0, rotation = eye(3); return, end
    basis = null(source).';
    crossValue = basis(1, :);
    sine = 1;
    cosine = -1;
end
axis = crossValue / sine;
skew = [0,-axis(3),axis(2);axis(3),0,-axis(1); ...
    -axis(2),axis(1),0];
rotation = eye(3) + skew * sine + skew^2 * (1 - cosine);
end

function matrix = axisRotation(axis, degrees)
axis = axis / norm(axis);
skew = [0,-axis(3),axis(2);axis(3),0,-axis(1); ...
    -axis(2),axis(1),0];
radians = deg2rad(degrees);
matrix = eye(3) + sin(radians) * skew + ...
    (1 - cos(radians)) * skew^2;
end

function bonds = adsorbateBonds(adsorbate)
bonds = zeros(0, 3);
if isfield(adsorbate.properties, "topology") && ...
        isfield(adsorbate.properties.topology, "bonds")
    bonds = double(adsorbate.properties.topology.bonds);
end
end
