classdef UffSurfaceScorer
    %UFFSURFACESCORER Rigid periodic host-guest UFF van der Waals energy.
    %
    % The scorer evaluates only the cross interaction between a rigid host
    % and a rigid adsorbate. It uses the UFF 12-6 van der Waals expression,
    % geometric distance/well-depth combination rules, and element-level
    % x1/D1 parameters from Rappe et al., JACS 1992, 114, 10024-10035,
    % DOI 10.1021/ja00051a040. A C2 switching function makes the finite
    % periodic-image sum continuous at the implementation cutoff.
    %
    % This is an interaction potential energy, not a relaxed adsorption
    % enthalpy or an electronic-structure result. It intentionally omits
    % electrostatics, charge transfer, bonding, solvent and relaxation.

    properties (Constant)
        SchemaVersion = 1
        Id = "kssolv-uff-vdw-surface-v1"
        Version = "1.0.0"
        EnergyUnit = "eV"
        Cutoff = 12
        SwitchStart = 10
        KcalMolToEv = 0.0433641153087705
        SourceDoi = "10.1021/ja00051a040"
        ParameterSource = ...
            "UFF Table I; Rappe et al., JACS 1992, DOI 10.1021/ja00051a040"
    end

    methods (Static)
        function descriptor = descriptor()
            descriptor = struct( ...
                "schemaVersion", ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionScoringModel.SchemaVersion, ...
                "id", kssolv.modeling.adsorption.UffSurfaceScorer.Id, ...
                "isEnergyModel", true, ...
                "scoreUnit", ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.EnergyUnit, ...
                "source", ...
                    kssolv.modeling.adsorption. ...
                    UffSurfaceScorer.ParameterSource, ...
                "version", ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.Version, ...
                "validated", true, ...
                "validationReference", ...
                    "Analytic implementation oracles plus Rybolt and " + ...
                    "Pierotti rare-gas/graphite experiment, " + ...
                    "DOI 10.1063/1.438015", ...
                "validationScope", ...
                    "Equation/parameter implementation and deterministic " + ...
                    "ranking; predictive ranking and interaction-potential " + ...
                    "scale for rigid graphitic rare-gas physisorption only; " + ...
                    "not predictive adsorption-enthalpy accuracy", ...
                "predictiveBenchmarkId", ...
                    kssolv.modeling.adsorption. ...
                    AdsorptionPredictiveBenchmark.Id, ...
                "parameterCoverage", ...
                    "UFF elements H-Lr (atomic numbers 1-103)", ...
                "physicalInterpretation", ...
                    "Rigid periodic host-guest UFF van der Waals " + ...
                    "interaction potential energy", ...
                "limitations", [ ...
                    "Rigid host and adsorbate"; ...
                    "No electrostatics or charge equilibration"; ...
                    "No bond formation, charge transfer or surface relaxation"; ...
                    "No solvent, temperature or zero-point contribution"; ...
                    "Predictive comparison is limited to low-coverage " + ...
                        "rare-gas physisorption on graphitic carbon"; ...
                    "12 angstrom cutoff with a 10-12 angstrom C2 switch"], ...
                "evaluator", ...
                    @kssolv.modeling.adsorption.UffSurfaceScorer.evaluate);
        end

        function energy = evaluate(host, adsorbate, coordinates, ~)
            state = kssolv.modeling.adsorption.UffSurfaceScorer. ...
                interactionState(host, adsorbate, coordinates);
            energy = state.energy;
        end

        function state = interactionState(host, adsorbate, coordinates)
            arguments
                host
                adsorbate
                coordinates double
            end
            kssolv.modeling.builders.BuilderUtils.requireStructure(host);
            coordinates = double(coordinates);
            if ~isequal(size(coordinates), [adsorbate.num_sites, 3]) || ...
                    any(~isfinite(coordinates), "all")
                error("KSSOLV:Modeling:UffSurfaceCoordinates", ...
                    "Adsorbate coordinates must be a finite N-by-3 array.");
            end
            hostSymbols = reshape(string(host.species), 1, []);
            guestSymbols = reshape(string(adsorbate.species), 1, []);
            hostParameters = arrayfun(@(symbol) ...
                kssolv.modeling.adsorption.UffSurfaceScorer.parameter( ...
                symbol), hostSymbols);
            guestParameters = arrayfun(@(symbol) ...
                kssolv.modeling.adsorption.UffSurfaceScorer.parameter( ...
                symbol), guestSymbols);
            lattice = host.lattice;
            matrix = double(lattice.matrix);
            inverse = inv(matrix);
            hostFractional = double(host.frac_coords);
            guestFractional = coordinates / matrix;
            periodic = logical(lattice.pbc);
            cutoff = ...
                kssolv.modeling.adsorption.UffSurfaceScorer.Cutoff;
            energy = 0;
            pairCount = 0;
            minimumDistance = Inf;
            for hostIndex = 1:host.num_sites
                for guestIndex = 1:adsorbate.num_sites
                    delta = guestFractional(guestIndex, :) - ...
                        hostFractional(hostIndex, :);
                    translations = periodicTranslations( ...
                        delta, inverse, periodic, cutoff);
                    vectors = (delta - translations) * matrix;
                    distances = vecnorm(vectors, 2, 2);
                    active = distances < cutoff;
                    if any(distances <= 1e-8)
                        error("KSSOLV:Modeling:UffSurfaceOverlap", ...
                            "Host and adsorbate atoms overlap in a periodic image.");
                    end
                    distances = distances(active);
                    if isempty(distances), continue, end
                    pairCount = pairCount + numel(distances);
                    minimumDistance = min(minimumDistance, min(distances));
                    energy = energy + sum(pairEnergyFromParameters( ...
                        hostParameters(hostIndex), ...
                        guestParameters(guestIndex), distances));
                end
            end
            if ~isfinite(minimumDistance), minimumDistance = NaN; end
            descriptor = kssolv.modeling.adsorption. ...
                UffSurfaceScorer.descriptor();
            state = struct( ...
                "schemaVersion", ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.SchemaVersion, ...
                "scoringModel", ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.Id, ...
                "source", ...
                    kssolv.modeling.adsorption. ...
                    UffSurfaceScorer.ParameterSource, ...
                "energy", energy, ...
                "energyUnit", ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.EnergyUnit, ...
                "pairCount", pairCount, ...
                "minimumDistance", minimumDistance, ...
                "cutoff", cutoff, ...
                "switchStart", ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.SwitchStart, ...
                "boundaryCondition", "explicit-periodic-image-sum", ...
                "hostElements", unique(hostSymbols, "stable"), ...
                "adsorbateElements", unique(guestSymbols, "stable"), ...
                "limitations", descriptor.limitations);
        end

        function energy = pairEnergy(first, second, distance)
            arguments
                first
                second
                distance double {mustBePositive}
            end
            firstParameter = kssolv.modeling.adsorption. ...
                UffSurfaceScorer.parameter(first);
            secondParameter = kssolv.modeling.adsorption. ...
                UffSurfaceScorer.parameter(second);
            energy = pairEnergyFromParameters( ...
                firstParameter, secondParameter, double(distance));
        end

        function parameter = parameter(symbol)
            element = kssolv.analysis.matgenlab.core.get_el_sp(symbol);
            atomicNumber = double(element.Z);
            [symbols, distances, wellDepths] = parameterTable();
            if atomicNumber < 1 || atomicNumber > numel(symbols)
                error("KSSOLV:Modeling:UffSurfaceElement", ...
                    "UFF surface parameters are unavailable for element '%s'.", ...
                    string(element.symbol));
            end
            parameter = struct( ...
                "symbol", symbols(atomicNumber), ...
                "atomicNumber", atomicNumber, ...
                "x1", distances(atomicNumber), ...
                "x1Unit", "angstrom", ...
                "D1", wellDepths(atomicNumber), ...
                "D1Unit", "kcal/mol", ...
                "source", ...
                    kssolv.modeling.adsorption. ...
                    UffSurfaceScorer.ParameterSource, ...
                "fallback", false);
        end
    end
end

function translations = periodicTranslations( ...
        delta, inverse, periodic, cutoff)
ranges = cell(1, 3);
for axis = 1:3
    if periodic(axis)
        bound = ceil(cutoff * norm(inverse(:, axis))) + 1;
        center = round(delta(axis));
        ranges{axis} = (center - bound):(center + bound);
    else
        ranges{axis} = 0;
    end
end
[first, second, third] = ndgrid(ranges{1}, ranges{2}, ranges{3});
translations = [first(:), second(:), third(:)];
end

function energy = pairEnergyFromParameters(first, second, distance)
x = sqrt(first.x1 * second.x1);
depth = sqrt(first.D1 * second.D1);
ratio6 = (x ./ distance).^6;
energy = depth .* (ratio6.^2 - 2 * ratio6);
energy = energy .* smoothSwitch(distance) * ...
    kssolv.modeling.adsorption.UffSurfaceScorer.KcalMolToEv;
end

function value = smoothSwitch(distance)
start = kssolv.modeling.adsorption.UffSurfaceScorer.SwitchStart;
cutoff = kssolv.modeling.adsorption.UffSurfaceScorer.Cutoff;
value = ones(size(distance));
value(distance >= cutoff) = 0;
active = distance > start & distance < cutoff;
t = (distance(active) - start) / (cutoff - start);
value(active) = 1 - 10 * t.^3 + 15 * t.^4 - 6 * t.^5;
end

function [symbols, distances, wellDepths] = parameterTable()
persistent cachedSymbols cachedDistances cachedWellDepths
if isempty(cachedSymbols)
    [cachedSymbols, cachedDistances, cachedWellDepths] = ...
        buildParameterTable();
end
symbols = cachedSymbols;
distances = cachedDistances;
wellDepths = cachedWellDepths;
end

function [symbols, distances, wellDepths] = buildParameterTable()
% Element-level x1 and D1 values. UFF hybridization variants share these
% two non-bonded parameters, so one row per element is sufficient here.
symbols = [ ...
    "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", ...
    "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", ...
    "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", ...
    "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", ...
    "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", ...
    "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd", ...
    "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", ...
    "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", ...
    "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", ...
    "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", ...
    "Md", "No", "Lr"];
distances = [ ...
    2.886,2.362,2.451,2.745,4.083,3.851,3.660,3.500,3.364,3.243, ...
    2.983,3.021,4.499,4.295,4.147,4.035,3.947,3.868,3.812,3.399, ...
    3.295,3.175,3.144,3.023,2.961,2.912,2.872,2.834,3.495,2.763, ...
    4.383,4.280,4.230,4.205,4.189,4.141,4.114,3.641,3.345,3.124, ...
    3.165,3.052,2.998,2.963,2.929,2.899,3.148,2.848,4.463,4.392, ...
    4.420,4.470,4.500,4.404,4.517,3.703,3.522,3.556,3.606,3.575, ...
    3.547,3.520,3.493,3.368,3.451,3.428,3.409,3.391,3.374,3.355, ...
    3.640,3.141,3.170,3.069,2.954,3.120,2.840,2.754,3.293,2.705, ...
    4.347,4.297,4.370,4.709,4.750,4.765,4.900,3.677,3.478,3.396, ...
    3.424,3.395,3.424,3.424,3.381,3.326,3.339,3.313,3.299,3.286, ...
    3.274,3.248,3.236];
wellDepths = [ ...
    .044,.056,.025,.085,.180,.105,.069,.060,.050,.042, ...
    .030,.111,.505,.402,.305,.274,.227,.185,.035,.238, ...
    .019,.017,.016,.015,.013,.013,.014,.015,.005,.124, ...
    .415,.379,.309,.291,.251,.220,.040,.235,.072,.069, ...
    .059,.056,.048,.056,.053,.048,.036,.228,.599,.567, ...
    .449,.398,.339,.332,.045,.364,.017,.013,.010,.010, ...
    .009,.008,.008,.009,.007,.007,.007,.007,.006,.228, ...
    .041,.072,.081,.067,.066,.037,.073,.080,.039,.385, ...
    .680,.663,.518,.325,.284,.248,.050,.404,.033,.026, ...
    .022,.022,.019,.016,.014,.013,.013,.013,.012,.012, ...
    .011,.011,.011];
end
