function descriptors = process_multiwfn_qtaim( ...
        molecule, filename, options)
%PROCESS_MULTIW_FN_QTAIM Parse, organize, map, and link a CPprop calculation.
arguments
    molecule
    filename
    options.bond_atom_criterion string = "distance"
    options.max_distance_atom (1,1) double = 0.5
    options.dist_threshold_bond (1,1) double = 1.0
    options.dist_threshold_ring_cage (1,1) double = 3.0
    options.distance_margin (1,1) double = 0.5
end
unorganized = ...
    kssolv.analysis.matgenlab.io.multiwfn. ...
    get_qtaim_descs(filename);
descriptors = ...
    kssolv.analysis.matgenlab.io.multiwfn. ...
    separate_cps_by_type(unorganized);
[mapped, missing] = ...
    kssolv.analysis.matgenlab.io.multiwfn. ...
    map_atoms_cps(molecule, descriptors.atom, ...
    options.max_distance_atom);
if ~isempty(missing)
    warning("KSSOLV:Matgenlab:Multiwfn:MissingAtoms", ...
        "Some atoms were not mapped to atom CPs: %s", ...
        strjoin(string(missing), ", "));
end
descriptors.atom = mapped;
descriptors = kssolv.analysis.matgenlab.io.multiwfn.add_atoms( ...
    molecule, descriptors, ...
    bond_atom_criterion = options.bond_atom_criterion, ...
    dist_threshold_bond = options.dist_threshold_bond, ...
    dist_threshold_ring_cage = options.dist_threshold_ring_cage, ...
    distance_margin = options.distance_margin);
end
