function value = qtaim_conditionals()
%QTAIM_CONDITIONALS Multiwfn CP-property labels recognized by the parser.
value = struct( ...
    "cp_num", {{"----------------"}}, ...
    "ele_info", {{"Corresponding", "nucleus:"}}, ...
    "connected_bond_paths", {{"Connected", "atoms:"}}, ...
    "pos_ang", {{"Position", "(Angstrom):"}}, ...
    "density_total", {{"Density", "of", "all", "electrons:"}}, ...
    "density_alpha", {{"Density", "of", "Alpha", "electrons:"}}, ...
    "density_beta", {{"Density", "of", "Beta", "electrons:"}}, ...
    "spin_density", {{"Spin", "density", "of", "electrons:"}}, ...
    "lol", {{"Localized", "orbital", "locator"}}, ...
    "energy_density", {{"Energy", "density", "E(r)"}}, ...
    "Lagrangian_K", {{"Lagrangian", "kinetic", "energy"}}, ...
    "Hamiltonian_K", {{"Hamiltonian", "kinetic", "energy"}}, ...
    "lap_e_density", {{"Laplacian", "electron", "density:"}}, ...
    "e_loc_func", {{"Electron", "localization", "function"}}, ...
    "ave_loc_ion_E", {{"Average", "local", "ionization", "energy"}}, ...
    "delta_g_promolecular", {{"Delta-g", "promolecular"}}, ...
    "delta_g_hirsh", {{"Delta-g", "Hirshfeld"}}, ...
    "esp_nuc", {{"ESP", "nuclear", "charges:"}}, ...
    "esp_e", {{"ESP", "electrons:"}}, ...
    "esp_total", {{"Total", "ESP:"}}, ...
    "grad_norm", {{"Components", "gradient", "x/y/z"}}, ...
    "lap_norm", {{"Components", "Laplacian", "x/y/z"}}, ...
    "eig_hess", {{"Eigenvalues", "Hessian:"}}, ...
    "det_hessian", {{"Determinant", "Hessian:"}}, ...
    "ellip_e_dens", {{"Ellipticity", "electron", "density:"}}, ...
    "eta", {{"eta", "index:"}});
end
