classdef KpointsSupportedModes
    %KPOINTSSUPPORTEDMODES Names of VASP KPOINTS generation modes.

    properties (Constant)
        Automatic = "Automatic"
        Gamma = "Gamma"
        Monkhorst = "Monkhorst"
        Line_mode = "Line_mode"
        Cartesian = "Cartesian"
        Reciprocal = "Reciprocal"
    end

    methods (Static)
        function output = from_str(mode)
            mode = lower(strtrim(string(mode)));
            if strlength(mode) == 0
                error("KSSOLV:Matgenlab:Kpoints:InvalidMode", ...
                    "Invalid empty Kpoint mode.");
            end
            switch extractBefore(mode, 2)
                case "a", output = ...
                        kssolv.analysis.matgenlab.io.vasp. ...
                        KpointsSupportedModes.Automatic;
                case "g", output = ...
                        kssolv.analysis.matgenlab.io.vasp. ...
                        KpointsSupportedModes.Gamma;
                case "m", output = ...
                        kssolv.analysis.matgenlab.io.vasp. ...
                        KpointsSupportedModes.Monkhorst;
                case "l", output = ...
                        kssolv.analysis.matgenlab.io.vasp. ...
                        KpointsSupportedModes.Line_mode;
                case "c", output = ...
                        kssolv.analysis.matgenlab.io.vasp. ...
                        KpointsSupportedModes.Cartesian;
                case "r", output = ...
                        kssolv.analysis.matgenlab.io.vasp. ...
                        KpointsSupportedModes.Reciprocal;
                otherwise
                    error("KSSOLV:Matgenlab:Kpoints:InvalidMode", ...
                        "Invalid Kpoint mode='%s'.", mode);
            end
        end
    end
end
