classdef MITMDSet < kssolv.analysis.matgenlab.io.vasp.VaspInputSet
    %MITMDSET MIT molecular-dynamics calculation inputs.
    methods
        function obj = MITMDSet(structure, varargin)
            if nargin < 1, structure = []; end
            obj@kssolv.analysis.matgenlab.io.vasp.VaspInputSet( ...
                structure, "MITRelaxSet", varargin{:});
            obj.set_name = "MITMDSet";
            obj.extra_incar_updates = obj.md_updates(1e-6, "Low");
            obj.extra_kpoints_updates = ...
                kssolv.analysis.matgenlab.io.vasp.Kpoints. ...
                gamma_automatic([1,1,1]);
        end
    end
    methods (Access = protected)
        function updates = md_updates(obj, tolerance, precision)
            updates = struct("TEBEG",obj.start_temp,"TEEND",obj.end_temp, ...
                "NSW",obj.nsteps,"EDIFF_PER_ATOM",tolerance, ...
                "LSCALU",false,"LCHARG",false,"LPLANE",false, ...
                "LWAVE",true,"ISMEAR",0,"NELMIN",4,"LREAL",true, ...
                "BMIX",1,"MAXMIX",20,"NELM",500,"NSIM",4,"ISYM",0, ...
                "ISIF",0,"IBRION",0,"NBLOCK",1,"KBLOCK",100, ...
                "SMASS",0,"POTIM",obj.time_step,"PREC",precision, ...
                "ISPIN",1 + double(obj.spin_polarized),"LDAU",false, ...
                "ENCUT",[]);
        end
    end
end
