classdef MPAbsorptionSet < kssolv.analysis.matgenlab.io.vasp.VaspInputSet
    %MPABSORPTIONSET Optical absorption calculation inputs.
    methods
        function obj = MPAbsorptionSet(structure, varargin)
            if nargin < 1, structure = []; end
            obj@kssolv.analysis.matgenlab.io.vasp.VaspInputSet( ...
                structure, "MPAbsorptionSet", "force_gamma",true, ...
                "inherit_incar",true,"copy_wavecar",true, ...
                "mode","IPA","reciprocal_density",400, varargin{:});
            obj.extra_incar_updates = struct("ALGO","Exact", ...
                "EDIFF",1e-8,"IBRION",-1,"ICHARG",1,"ISMEAR",0, ...
                "SIGMA",0.01,"LWAVE",true,"LREAL",false,"NELM",100, ...
                "NSW",0,"LOPTICS",true,"CSHIFT",0.1, ...
                "NEDOS",obj.nedos);
            obj.extra_kpoints_updates = struct( ...
                "reciprocal_density",obj.reciprocal_density);
        end
    end
end
