classdef AdsorptionInventoryTest < matlab.unittest.TestCase
    %ADSORPTIONINVENTORYTEST Frozen pymatgen-core adsorption parity.

    properties
        oracle
    end

    methods (TestMethodSetup)
        function loadOracle(testCase)
            testCase.oracle=jsondecode(fileread(fullfile(pwd,"dev", ...
                "matgenlab","oracles","adsorption_2026.7.24.json")));
        end
    end

    methods (Test)
        function frozenInventoryHasAllTwentyOneApis(testCase)
            name="kssolv.analysis.matgenlab.core.AdsorbateSiteFinder";
            metadata=meta.class.fromName(name);
            testCase.verifyNotEmpty(metadata);
            expectedMethods=["from_bulk_and_miller", ...
                "find_surface_sites_by_height","assign_site_properties", ...
                "get_extended_surface_mesh","subsurface_sites", ...
                "find_adsorption_sites","symm_reduce","near_reduce", ...
                "ensemble_center","add_adsorbate", ...
                "assign_selective_dynamics", ...
                "generate_adsorption_structures", ...
                "adsorb_both_surfaces", ...
                "generate_substitution_structures"];
            actualMethods=string({metadata.MethodList.Name});
            testCase.verifyTrue(all(ismember(expectedMethods,actualMethods)));
            actualProperties=string({metadata.PropertyList.Name});
            testCase.verifyTrue(ismember("surface_sites",actualProperties));
            functions=["get_mi_vec","get_rot","put_coord_inside", ...
                "reorient_z","plot_slab"];
            for functionName=functions
                testCase.verifyNotEmpty(which( ...
                    "kssolv.analysis.matgenlab.core."+functionName));
            end
            inventory=readtable(fullfile(pwd,"dev","matgenlab", ...
                "inventory","api.csv"),TextType="string");
            rows=inventory.module=="pymatgen.core.adsorption";
            testCase.verifyEqual(nnz(rows),21);
            testCase.verifyTrue(all( ...
                inventory.source(rows)=="pymatgen-core"));
            testCase.verifyEqual(string(testCase.oracle.provenance.tag), ...
                "v2026.7.24");
        end

        function squareSurfaceAndAdsorptionMatchOracle(testCase)
            [structure,finder]=squareFinder();
            expected=testCase.oracle.square;
            testCase.verifyEqual(finder.mvec, ...
                reshape(expected.mvec,1,[]),AbsTol=1e-14);
            testCase.verifyEqual(siteCoordinates( ...
                finder.surface_sites,false),expected.surface_frac, ...
                AbsTol=1e-14);
            testCase.verifyEqual(siteCoordinates( ...
                finder.subsurface_sites(),false), ...
                expected.subsurface_frac,AbsTol=1e-14);
            mesh=finder.get_extended_surface_mesh();
            testCase.verifyEqual(mesh.num_sites,expected.mesh_num_sites);
            testCase.verifyEqual(mesh.lattice.matrix, ...
                expected.mesh_lattice,AbsTol=1e-13);
            adsorption=finder.find_adsorption_sites();
            testCase.verifyEqual(adsorption.ontop, ...
                expected.default.ontop,AbsTol=2e-12);
            testCase.verifyEqual(adsorption.bridge, ...
                expected.default.bridge,AbsTol=2e-12);
            testCase.verifyEqual(adsorption.hollow,zeros(0,3));
            testCase.verifyEqual(adsorption.all, ...
                expected.default.all,AbsTol=2e-12);
            testCase.verifyEqual(structure.site_properties,struct());
            testCase.verifyTrue(isfield( ...
                finder.slab.site_properties,"surface_properties"));
        end

        function subsurfaceAndReductionNumericsMatchOracle(testCase)
            [~,finder]=squareFinder();
            adsorption=finder.find_adsorption_sites(2,true,.01,.01, ...
                ["ontop","subsurface","bridge"]);
            expected=testCase.oracle.square.with_subsurface_sorted;
            testCase.verifyEqual(sortrows(adsorption.ontop), ...
                expected.ontop,AbsTol=2e-12);
            testCase.verifyEqual(sortrows(adsorption.subsurface), ...
                expected.subsurface,AbsTol=2e-12);
            testCase.verifyEqual(sortrows(adsorption.bridge), ...
                expected.bridge,AbsTol=2e-12);
            testCase.verifyEqual(sortrows(adsorption.all), ...
                expected.all,AbsTol=2e-12);
            coordinates=[0,0,9;3,0,9;1.5,1.5,9; ...
                1.5,1.5,9.000001];
            testCase.verifyEqual(sortrows( ...
                finder.near_reduce(coordinates,1e-4)), ...
                testCase.oracle.reductions.near_sorted,AbsTol=2e-12);
            testCase.verifyEqual(sortrows( ...
                finder.symm_reduce(coordinates,1e-4)), ...
                testCase.oracle.reductions.symm_sorted,AbsTol=2e-12);
        end

        function ensembleRotationWrappingAndReorientationMatch(testCase)
            [structure,~]=squareFinder();
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core. ...
                AdsorbateSiteFinder.ensemble_center( ...
                structure,[1,2],true), ...
                reshape(testCase.oracle.ensemble.cart,1,[]), ...
                AbsTol=1e-13);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core. ...
                AdsorbateSiteFinder.ensemble_center( ...
                structure,[1,2],false), ...
                reshape(testCase.oracle.ensemble.frac,1,[]), ...
                AbsTol=1e-13);
            lattice=kssolv.analysis.matgenlab.core.Lattice( ...
                [2,0,1;0,3,1;0,0,10]);
            tilted=kssolv.analysis.matgenlab.core.Structure( ...
                lattice,{"Ni"},[.2,.3,.4]);
            normal=kssolv.analysis.matgenlab.core.get_mi_vec(tilted);
            testCase.verifyEqual(normal, ...
                reshape(testCase.oracle.geometry.mi_vec,1,[]), ...
                AbsTol=7e-13);
            operation=kssolv.analysis.matgenlab.core.get_rot(tilted);
            testCase.verifyEqual(operation.rotation_matrix, ...
                testCase.oracle.geometry.rotation,AbsTol=7e-10);
            inside=kssolv.analysis.matgenlab.core. ...
                put_coord_inside(structure.lattice,[-1.5,3.3,16.5]);
            testCase.verifyEqual(inside, ...
                reshape(testCase.oracle.geometry.inside,1,[]), ...
                AbsTol=1e-13);
            reoriented=kssolv.analysis.matgenlab.core.reorient_z(tilted);
            testCase.verifyEqual(reoriented.lattice.matrix, ...
                testCase.oracle.geometry.reoriented_lattice, ...
                AbsTol=7e-10);
            testCase.verifyEqual(reoriented.cart_coords, ...
                testCase.oracle.geometry.reoriented_cart, ...
                AbsTol=7e-10);
        end

        function adsorbatePlacementAndGenerationMatchOracle(testCase)
            [~,finder]=squareFinder();
            molecule=kssolv.analysis.matgenlab.core.Molecule( ...
                {"C","O"},[0,0,0;0,0,1.23]);
            original=molecule.cart_coords;
            adsorbed=finder.add_adsorbate( ...
                molecule,[.2,.3,11],[2,2,1]);
            expected=testCase.oracle.add_adsorbate;
            testCase.verifyEqual(adsorbed.num_sites,expected.num_sites);
            testCase.verifyEqual(adsorbed.cart_coords(end-1:end,:), ...
                expected.last_cart,AbsTol=2e-12);
            testCase.verifyEqual(string(cellfun(@(site) ...
                site.species_string,adsorbed.sites(end-1:end), ...
                "UniformOutput",false)), ...
                reshape(string(expected.last_species),1,[]));
            testCase.verifyEqual(molecule.cart_coords,original);
            properties=adsorbed.site_properties.surface_properties;
            testCase.verifyEqual(string(properties(end-1:end)), ...
                reshape(string(expected.surface_properties),1,[]));

            generated=finder.generate_adsorption_structures( ...
                molecule,[2,2,1]);
            testCase.verifyEqual(numel(generated), ...
                testCase.oracle.generate.count);
            testCase.verifyEqual(cellfun(@(item)item.num_sites,generated), ...
                reshape(testCase.oracle.generate.num_sites,1,[]));
            anchors=cell2mat(cellfun(@(item)item.cart_coords(end-1,:), ...
                generated,"UniformOutput",false).');
            testCase.verifyEqual(anchors, ...
                testCase.oracle.generate.anchor_cart,AbsTol=2e-12);
            hollowOnly=finder.generate_adsorption_structures( ...
                molecule,[],5,true,true,struct( ...
                "positions","hollow"));
            testCase.verifyEmpty(hollowOnly);
        end

        function selectiveDynamicsBothSurfacesAndSubstitutionMatch(testCase)
            [structure,~]=squareFinder();
            finder=kssolv.analysis.matgenlab.core. ...
                AdsorbateSiteFinder(structure,true);
            dynamics=finder.slab.site_properties.selective_dynamics;
            dynamics=cell2mat(cellfun(@(value)reshape(value,1,3), ...
                dynamics,"UniformOutput",false).');
            testCase.verifyEqual(dynamics, ...
                testCase.oracle.selective_dynamics);

            [slab,slabFinder]=symmetricSlabFinder();
            oxygen=kssolv.analysis.matgenlab.core.Molecule( ...
                {"O"},[0,0,0]);
            both=slabFinder.adsorb_both_surfaces(oxygen,[1,1,1], ...
                5,true,true,struct("positions","ontop"));
            testCase.verifyEqual(numel(both), ...
                testCase.oracle.both_surfaces.count);
            testCase.verifyEqual(both{1}.num_sites, ...
                testCase.oracle.both_surfaces.num_sites);
            properties=both{1}.site_properties.surface_properties;
            adsorbate=find(string(properties)=="adsorbate");
            fractional=mod(both{1}.frac_coords(adsorbate,:),1);
            testCase.verifyEqual(sortrows(fractional), ...
                sortrows(testCase.oracle.both_surfaces. ...
                adsorbate_frac_modulo_one),AbsTol=7e-13);

            substituted=slabFinder.generate_substitution_structures( ...
                "Cu","Ni");
            testCase.verifyEqual(numel(substituted), ...
                testCase.oracle.substitution.count);
            species=string(cellfun(@(site)site.species_string, ...
                substituted{1}.sites,"UniformOutput",false));
            testCase.verifyEqual(species, ...
                reshape(string(testCase.oracle.substitution.species),1,[]));
            labels=string(substituted{1}.site_properties. ...
                surface_properties);
            testCase.verifyEqual(labels,reshape(string( ...
                testCase.oracle.substitution.properties),1,[]));
            testCase.verifyEqual(slab.num_sites,4);
        end

        function fromBulkMillerCoordinationMatchesFrozenCounts(testCase)
            bulk=kssolv.analysis.matgenlab.core.Structure. ...
                from_spacegroup("Fm-3m", ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3.5), ...
                {"Ni"},[0,0,0]);
            millers={[1,1,1],[1,0,0],[1,1,0]};
            names=["x111","x100","x110"];
            for index=1:numel(millers)
                threshold=.09;
                if names(index)=="x110",threshold=.1;end
                finder=kssolv.analysis.matgenlab.core. ...
                    AdsorbateSiteFinder.from_bulk_and_miller( ...
                    bulk,millers{index},8,10,[],true,false,threshold);
                adsorption=finder.find_adsorption_sites();
                expected=testCase.oracle.from_bulk.(names(index));
                testCase.verifyEqual(finder.slab.num_sites, ...
                    expected.slab_sites);
                testCase.verifyEqual(numel(finder.surface_sites), ...
                    expected.surface_sites);
                counts=[size(adsorption.ontop,1), ...
                    size(adsorption.bridge,1), ...
                    size(adsorption.hollow,1), ...
                    size(adsorption.all,1)];
                testCase.verifyEqual(counts, ...
                    reshape(expected.counts,1,[]));
                testCase.verifyEqual(norm(finder.mvec),1,AbsTol=1e-13);
                testCase.verifyTrue(isfield(finder.slab. ...
                    site_properties,"undercoords"));
            end
        end

        function officialAuFixtureMatchesCoordinatesExactly(testCase)
            path=fullfile(pwd,"+kssolv","+analysis","+matgenlab", ...
                "+test","+transformations","+fixtures","+standard", ...
                "Au_slab_init.cif");
            structure=kssolv.analysis.matgenlab.core.Structure. ...
                from_file(path);
            finder=kssolv.analysis.matgenlab.core. ...
                AdsorbateSiteFinder(structure);
            adsorption=finder.find_adsorption_sites();
            expected=testCase.oracle.official_Au_slab_init;
            testCase.verifyEqual(structure.num_sites,expected.num_sites);
            testCase.verifyEqual(structure.reduced_formula, ...
                string(expected.formula));
            testCase.verifyEqual(numel(finder.surface_sites), ...
                expected.surface_sites);
            counts=[size(adsorption.ontop,1), ...
                size(adsorption.bridge,1), ...
                size(adsorption.hollow,1), ...
                size(adsorption.all,1)];
            testCase.verifyEqual(counts,reshape(expected.counts,1,[]));
            testCase.verifyEqual(finder.mvec, ...
                reshape(expected.mvec,1,[]),AbsTol=7e-13);
            testCase.verifyEqual(sortrows(adsorption.all), ...
                expected.all_sorted,AbsTol=7e-12);
        end

        function plotSlabIsHeadlessAndDeterministic(testCase)
            [structure,~]=squareFinder();
            figureHandle=figure("Visible","off","Color","white");
            testCase.addTeardown(@()delete(figureHandle));
            axesHandle=axes(figureHandle);
            returned=kssolv.analysis.matgenlab.core.plot_slab( ...
                structure,axesHandle,.8,2,1.5,true,.2,true,false);
            testCase.verifyEqual(returned,axesHandle);
            testCase.verifyEqual(string(figureHandle.Visible),"off");
            testCase.verifyEqual(axesHandle.UserData.site_count,8);
            testCase.verifyEqual(size( ...
                axesHandle.UserData.adsorption_sites,1),3);
            testCase.verifyEqual(size( ...
                axesHandle.UserData.unit_cell_vertices),[2,2]);
            testCase.verifyGreaterThanOrEqual(numel(axesHandle.Children),18);
        end

        function invalidInputsHaveStableErrors(testCase)
            [structure,finder]=squareFinder();
            testCase.verifyError(@()finder.find_adsorption_sites( ...
                2,true,.01,.01,"invalid"), ...
                "KSSOLV:Matgenlab:Adsorption:Positions");
            testCase.verifyError(@()finder.get_extended_surface_mesh( ...
                [2,0,1]),"KSSOLV:Matgenlab:Adsorption:Repeat");
            testCase.verifyError(@()finder.near_reduce([1,2],.01), ...
                "KSSOLV:Matgenlab:Adsorption:Coordinates");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core.AdsorbateSiteFinder. ...
                ensemble_center(structure,0), ...
                "KSSOLV:Matgenlab:Adsorption:SiteIndices");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core.get_mi_vec(eye(3)), ...
                "KSSOLV:Matgenlab:Adsorption:Structure");
        end
    end
end

function [structure,finder]=squareFinder()
lattice=kssolv.analysis.matgenlab.core.Lattice( ...
    [3,0,0;0,3,0;0,0,15]);
structure=kssolv.analysis.matgenlab.core.Structure( ...
    lattice,{"Ni","Ni"},[0,0,.6;.5,.5,.4]);
finder=kssolv.analysis.matgenlab.core. ...
    AdsorbateSiteFinder(structure);
end

function [slab,finder]=symmetricSlabFinder()
lattice=kssolv.analysis.matgenlab.core.Lattice( ...
    [3,0,0;0,3,0;0,0,15]);
unitCell=kssolv.analysis.matgenlab.core.Structure( ...
    lattice,{"Ni"},[0,0,0]);
properties=struct("surface_properties", ...
    {{"surface","subsurface","subsurface","surface"}});
slab=kssolv.analysis.matgenlab.core.Slab( ...
    lattice,{"Ni","Ni","Ni","Ni"}, ...
    [0,0,.25;.5,.5,.35;.5,.5,.65;0,0,.75], ...
    [0,0,1],unitCell,0,eye(3), ...
    "site_properties",properties,"reorient_lattice",false);
finder=kssolv.analysis.matgenlab.core.AdsorbateSiteFinder(slab);
end

function coordinates=siteCoordinates(sites,cartesian)
coordinates=zeros(numel(sites),3);
for index=1:numel(sites)
    if cartesian,coordinates(index,:)=sites{index}.coords;
    else,coordinates(index,:)=sites{index}.frac_coords;end
end
coordinates=sortrows(coordinates);
end
