classdef BondValenceTest < matlab.unittest.TestCase
    methods (Test)
        function orderedAndUnorderedSumsAgreeWithOracle(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4.2), ...
                {"Li", "O"}, [0, 0, 0; 0.5, 0.5, 0.5]);
            neighbors = structure.get_neighbors(structure.get_site(1), 4);
            actual = kssolv.analysis.matgenlab.core.calculate_bv_sum( ...
                structure.get_site(1), neighbors);

            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.bond_valence", ...
                "symbol", "calculate_bv_sum", ...
                "operations", {{struct("kind", "call", "args", {{ ...
                    structure.get_site(1).as_dict(), ...
                    cellfun(@(item) item.as_dict(), neighbors, ...
                        "UniformOutput", false)}})}});
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            testCase.verifyEqual(actual, response.results(1), RelTol=1e-12);

            site = structure.get_site(1);
            site.species = kssolv.analysis.matgenlab.core.Composition( ...
                {"Li", 0.5; "Na", 0.5});
            unordered = kssolv.analysis.matgenlab.core. ...
                calculate_bv_sum_unordered(site, neighbors);
            request.symbol = "calculate_bv_sum_unordered";
            request.operations{1}.args{1} = site.as_dict();
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            testCase.verifyEqual(unordered, response.results(1), RelTol=1e-12);
        end

        function fractionalDecoration(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {{"Li", 0.5; "Na", 0.5}, "O"}, ...
                [0, 0, 0; 0.5, 0.5, 0.5], skip_checks=true);
            decorated = kssolv.analysis.matgenlab.core. ...
                add_oxidation_state_by_site_fraction( ...
                    structure, {[1, 1], -2});
            species = decorated.get_site(1).species.elements;
            testCase.verifyTrue(all(cellfun(@(item) item.oxi_state == 1, species)));
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core. ...
                add_oxidation_state_by_site_fraction(structure, {[1, 1]}), ...
                "KSSOLV:Matgenlab:BondValence:OxidationStateLength");
        end

        function analyzerMatchesFrozenOracle(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4.6), ...
                {"O", "Li", "Li"}, ...
                [0, 0, 0; 0.25, 0.25, 0.25; 0.75, 0.75, 0.75]);
            analyzer = kssolv.analysis.matgenlab.core.BVAnalyzer(0);
            actual = analyzer.get_valences(structure);
            testCase.verifyEqual(actual, [-2, 1, 1]);

            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.bond_valence", ...
                "symbol", "BVAnalyzer", ...
                "construct", struct("args", {{0}}), ...
                "operations", {{struct( ...
                    "kind", "call", "name", "get_valences", ...
                    "args", {{structure.as_dict()}})}});
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            testCase.verifyEqual(actual, reshape(response.results, 1, []));
            decorated = analyzer.get_oxi_state_decorated_structure(structure);
            testCase.verifyEqual(string(decorated.composition), "O2-1 Li+2");
        end

        function deterministicSpeciesOrdering(testCase)
            composition = kssolv.analysis.matgenlab.core.Composition( ...
                {"Ni3+", 0.2; "Ni4+", 0.2; "Cr3+", 0.15; ...
                "Zn2+", 0.34; "Cr4+", 0.11});
            [species, occupancies] = ...
                kssolv.analysis.matgenlab.core. ...
                get_z_ordered_elmap(composition);
            testCase.verifyEqual(string(cellfun(@string, species, ...
                "UniformOutput", false)), ...
                ["Zn2+", "Cr3+", "Cr4+", "Ni3+", "Ni4+"]);
            testCase.verifyEqual(sum(occupancies), 1, AbsTol=1e-12);
        end
    end
end
