classdef BondsTest < matlab.unittest.TestCase
    methods (Test)
        function databaseAndInterpolation(testCase)
            lengths = ...
                kssolv.analysis.matgenlab.core.obtain_all_bond_lengths("C", "C");
            testCase.verifyEqual(lengths(1), 1.54, "AbsTol", 1e-12);
            testCase.verifyEqual(lengths(2), 1.34, "AbsTol", 1e-12);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.get_bond_order( ...
                    "C", "C", 1.34), 2, "AbsTol", 1e-12);
            expected = 2 - (1.40 - 1.34) / (1.54 - 1.34);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.get_bond_order( ...
                    "C", "C", 1.40), expected, "AbsTol", 1e-12);
        end

        function covalentBond(testCase)
            first = kssolv.analysis.matgenlab.core.Site("C", [0, 0, 0]);
            second = kssolv.analysis.matgenlab.core.Site("C", [1.34, 0, 0]);
            bond = kssolv.analysis.matgenlab.core.CovalentBond(first, second);
            testCase.verifyEqual(bond.length, 1.34, "AbsTol", 1e-12);
            testCase.verifyEqual(bond.get_bond_order(), 2, "AbsTol", 1e-12);
            testCase.verifyTrue( ...
                kssolv.analysis.matgenlab.core.CovalentBond.is_bonded( ...
                    first, second));
        end

        function missingDataAndFallback(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core.obtain_all_bond_lengths( ...
                    "He", "He"), "KSSOLV:Matgenlab:Bonds:MissingData");
            lengths = ...
                kssolv.analysis.matgenlab.core.obtain_all_bond_lengths( ...
                    "He", "He", 2.0);
            testCase.verifyEqual(lengths(1), 2.0);
        end

        function atomicNumberLookupRegression(testCase)
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.Element.from_Z(1).symbol, "H");
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.Element.from_Z(8).symbol, "O");
        end

        function interpolationMatchesPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.bonds", ...
                "symbol", "get_bond_order", ...
                "operations", {{struct( ...
                    "kind", "call", ...
                    "args", {{'C', 'C', 1.40}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            actual = kssolv.analysis.matgenlab.core.get_bond_order( ...
                "C", "C", 1.40);
            testCase.verifyEqual(actual, reference.results(1), ...
                "AbsTol", 1e-12);
        end
    end
end
