classdef CandidateCoreParityTest < matlab.unittest.TestCase
    % Frozen pymatgen-core v2026.7.24 edge coverage for candidate APIs.

    methods (Test)
        function tensorConversionAndCollectionEdges(testCase)
            cubic = kssolv.analysis.matgenlab.core.Structure( ...
                3 * eye(3), {"Si"}, [0, 0, 0]);
            symmetric = kssolv.analysis.matgenlab.core.Tensor. ...
                from_voigt(diag(1:6));
            testCase.verifyTrue(symmetric.is_voigt_symmetric());
            asymmetric = kssolv.analysis.matgenlab.core.Tensor( ...
                reshape(1:81, 3, 3, 3, 3));
            testCase.verifyFalse(asymmetric.is_voigt_symmetric());
            testCase.verifyEqual(double(symmetric.convert_to_ieee(cubic)), ...
                double(symmetric.fit_to_structure(cubic)), AbsTol=1e-12);
            testCase.verifyEqual(double(symmetric.structure_transform( ...
                cubic, cubic)), double(symmetric), AbsTol=1e-12);

            collection = kssolv.analysis.matgenlab.core. ...
                TensorCollection.from_voigt({eye(6), 1:6});
            testCase.verifyEqual(collection.ranks, [4, 2]);
            testCase.verifyTrue(collection.is_voigt_symmetric());
            converted = collection.convert_to_ieee(cubic, false);
            testCase.verifyEqual(converted.ranks, collection.ranks);
            rotated = collection.rotate(eye(3));
            testCase.verifyEqual(double(rotated(1)), ...
                double(collection(1)), AbsTol=1e-14);
            operation = kssolv.analysis.matgenlab.core.SymmOp. ...
                from_rotation_and_translation(eye(3), [1, 2, 3]);
            transformed = collection.transform(operation);
            testCase.verifyEqual(double(transformed(2)), ...
                double(collection(2)), AbsTol=1e-14);
        end

        function magneticConstructors(testCase)
            base = kssolv.analysis.matgenlab.core.SymmOp. ...
                from_rotation_and_translation( ...
                diag([-1, -1, 1]), [0.5, 0, 0]);
            magnetic = kssolv.analysis.matgenlab.core.MagSymmOp. ...
                from_symmop(base, -1);
            testCase.verifyEqual(magnetic.rotation_matrix, ...
                base.rotation_matrix);
            testCase.verifyEqual(magnetic.translation_vector, ...
                base.translation_vector);
            testCase.verifyEqual(magnetic.time_reversal, -1);
            direct = kssolv.analysis.matgenlab.core.MagSymmOp. ...
                from_rotation_and_translation_and_time_reversal( ...
                base.rotation_matrix, base.translation_vector, ...
                time_reversal=-1);
            testCase.verifyEqual(direct.as_xyzt_str(), ...
                magnetic.as_xyzt_str());
        end

        function orderMatcherPermutationEdges(testCase)
            brute = kssolv.analysis.matgenlab.core. ...
                BruteForceOrderMatcher.permutations([8, 14, 14]);
            testCase.verifyEqual(brute, {[1, 2, 3], [1, 3, 2]});

            root = "+kssolv/+analysis/+matgenlab/+test/" + ...
                "+core/+fixtures/+molecule_matcher";
            target = kssolv.analysis.matgenlab.io.xyz.XYZ. ...
                from_file(fullfile(root, "Si2O_cluster.xyz")).molecule;
            source = kssolv.analysis.matgenlab.io.xyz.XYZ. ...
                from_file(fullfile(root, "Si2O_cluster_2.xyz")).molecule;
            hungarian = kssolv.analysis.matgenlab.core. ...
                HungarianOrderMatcher(target);
            permutations = hungarian.permutations( ...
                source.atomic_numbers, ...
                source.cart_coords - source.center_of_mass, ...
                cellfun(@(site) site.species.weight, source.sites), ...
                target.atomic_numbers, ...
                target.cart_coords - target.center_of_mass, ...
                cellfun(@(site) site.species.weight, target.sites));
            testCase.verifyNumElements(permutations, 2);
            genetic = kssolv.analysis.matgenlab.core. ...
                GeneticOrderMatcher(target, 0.5196152422706631);
            testCase.verifyNumElements(genetic.permutations(source), 3);
        end
    end
end
