classdef CoreSurfaceInventoryTest < matlab.unittest.TestCase
    properties
        oracle
    end

    methods (TestMethodSetup)
        function loadOracle(testCase)
            testCase.oracle=jsondecode(fileread(fullfile(pwd,"dev", ...
                "matgenlab","oracles","core_surface_2026.7.24.json")));
        end
    end

    methods (Test)
        function millerFamiliesAndPlaneFitMatch(testCase)
            cscl=makeCsCl();
            actual=kssolv.analysis.matgenlab.core. ...
                get_symmetrically_distinct_miller_indices(cscl,1);
            testCase.verifyEqual(cell2mat(actual.'), ...
                testCase.oracle.miller.cscl_distinct_1);
            actual=kssolv.analysis.matgenlab.core. ...
                get_symmetrically_distinct_miller_indices(cscl,2);
            testCase.verifyEqual(cell2mat(actual.'), ...
                testCase.oracle.miller.cscl_distinct_2);

            magnesium=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.from_parameters( ...
                3.2,3.2,5.13,90,90,120),{"Mg","Mg"}, ...
                [1/3,2/3,1/4;2/3,1/3,3/4]);
            first=kssolv.analysis.matgenlab.core. ...
                get_symmetrically_equivalent_miller_indices( ...
                magnesium,[1,0,0]);
            second=kssolv.analysis.matgenlab.core. ...
                get_symmetrically_equivalent_miller_indices( ...
                magnesium,[2,0,0]);
            testCase.verifyEqual(cell2mat(first.'), ...
                testCase.oracle.miller.mg_equivalent_100);
            testCase.verifyEqual(cell2mat(second.'), ...
                testCase.oracle.miller.mg_equivalent_200);
            testCase.verifyEqual(numel(second),2*numel(first));

            transformed=kssolv.analysis.matgenlab.core. ...
                hkl_transformation([.5,.5,0;-.5,.5,0;0,0,1], ...
                [1,1,0]);
            testCase.verifyEqual(transformed, ...
                reshape(testCase.oracle.miller.transformation,1,[]));
            sites=[.5,-1.5,3;.5,3,-1.5;2.5,1.5,-4];
            fitted=kssolv.analysis.matgenlab.core. ...
                miller_index_from_sites(eye(3),sites);
            testCase.verifyEqual(fitted, ...
                reshape(testCase.oracle.miller.cubic_sites,1,[]));
        end

        function slabGeneratorMatchesFullOracle(testCase)
            lattice=kssolv.analysis.matgenlab.core.Lattice.cubic(3);
            bulk=kssolv.analysis.matgenlab.core.Structure. ...
                from_spacegroup("Fm-3m",lattice,"Fe",[0,0,0]);
            generator=kssolv.analysis.matgenlab.core.SlabGenerator( ...
                bulk,[1,1,1],10,10,max_normal_search=1);
            slab=generator.get_slab();
            verifySlab(testCase,slab, ...
                testCase.oracle.fcc_111.primitive,2e-10);
            testCase.verifyEqual(slab.num_sites,6);
            testCase.verifyTrue(isfield( ...
                generator.oriented_unit_cell.site_properties, ...
                "bulk_wyckoff"));
            testCase.verifyTrue(isfield( ...
                generator.oriented_unit_cell.site_properties, ...
                "bulk_equivalent"));

            nonprimitive=kssolv.analysis.matgenlab.core.SlabGenerator( ...
                bulk,[1,1,1],10,10,primitive=false, ...
                max_normal_search=1).get_slab();
            verifySlab(testCase,nonprimitive, ...
                testCase.oracle.fcc_111.nonprimitive,2e-10);
            testCase.verifyEqual(nonprimitive.num_sites, ...
                4*slab.num_sites);

            roundtrip=kssolv.analysis.matgenlab.core.Slab.from_dict( ...
                slab.as_dict());
            testCase.verifyEqual(roundtrip.miller_index,[1,1,1]);
            testCase.verifyEqual(roundtrip.frac_coords,slab.frac_coords, ...
                AbsTol=2e-12);
            copied=slab.copy(struct("marker",1:slab.num_sites));
            marker=copied.site_properties.marker;
            if iscell(marker),marker=cell2mat(marker);end
            testCase.verifyEqual(marker,1:slab.num_sites);
            sorted=slab.get_sorted_structure();
            testCase.verifyEqual(sorted.num_sites,slab.num_sites);
            orthogonal=slab.get_orthogonal_c_slab();
            testCase.verifyEqual(orthogonal.lattice.angles(1:2), ...
                [90,90],AbsTol=2e-10);
        end

        function surfaceSitesSymmetricEditingAndAdsorption(testCase)
            ag=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4.06), ...
                {"Ag","Ag","Ag","Ag"}, ...
                [0,0,0;0,.5,.5;.5,0,.5;.5,.5,0]);
            generator=kssolv.analysis.matgenlab.core.SlabGenerator( ...
                ag,[3,1,0],10,10);
            slab=generator.get_slabs();
            slab=slab{1};
            [sites,tagged]=slab.get_surface_sites(true);
            expected=testCase.oracle.ag_310.("false");
            testCase.verifyEqual(numel(sites.top), ...
                expected.top_surface_sites);
            testCase.verifyEqual(numel(sites.bottom), ...
                expected.bottom_surface_sites);
            tags=tagged.site_properties.is_surf_site;
            if iscell(tags),tags=cell2mat(tags);end
            testCase.verifyEqual(sum(tags),8);
            testCase.verifyTrue(slab.is_symmetric());

            top=sites.top{1}{2};
            adsorbed=slab.add_adsorbate_atom(top,"H",1);
            testCase.verifyEqual(adsorbed.num_sites,slab.num_sites+1);
            testCase.verifyEqual(adsorbed.sites{top}.distance( ...
                adsorbed.sites{adsorbed.num_sites}),1,AbsTol=2e-10);

            point=slab.frac_coords(top,:)+[0,0,.05];
            symmetricPoint=slab.get_symmetric_site(point);
            edited=slab.symmetrically_add_atom("O",point);
            testCase.verifyEqual(edited.num_sites,slab.num_sites+2);
            testCase.verifyTrue(edited.is_symmetric());
            testCase.verifyGreaterThan( ...
                abs(point(3)-symmetricPoint(3)),1e-6);
            edited=edited.symmetrically_remove_atoms( ...
                edited.num_sites-1);
            testCase.verifyEqual(edited.num_sites,slab.num_sites);
            testCase.verifyTrue(edited.is_symmetric());
        end

        function taskerAndGeneratorMutationsMatch(testCase)
            bulk=makeMgO();
            generator=kssolv.analysis.matgenlab.core.SlabGenerator( ...
                bulk,[1,1,1],10,10,max_normal_search=1);
            slabs=generator.get_slabs();
            source=slabs{1};
            testCase.verifyFalse(source.is_symmetric());
            testCase.verifyTrue(source.is_polar());
            source=source.make_supercell([2,1,1]);
            corrected=source.get_tasker2_slabs();
            testCase.verifyEqual(numel(corrected), ...
                testCase.oracle.tasker.count);
            for index=1:numel(corrected)
                testCase.verifyTrue(corrected{index}.is_symmetric());
                testCase.verifyFalse(corrected{index}.is_polar());
            end

            symmetric=generator.get_slabs(symmetrize=true);
            testCase.verifyEqual(numel(symmetric),2);
            testCase.verifyTrue(all(cellfun(@(item) ...
                item.is_symmetric(),symmetric)));
            z=source.frac_coords(:,3);
            top=find(z>=max(z)-1e-6);
            moved=generator.move_to_other_side(source,top);
            testCase.verifyTrue(all(moved.frac_coords(top,3)< ...
                moved.center_of_mass(3)));
        end

        function bondFilteringAndGlobalGenerationMatch(testCase)
            cscl=makeCsCl();
            generator=kssolv.analysis.matgenlab.core.SlabGenerator( ...
                cscl,[0,0,1],10,10);
            testCase.verifyEqual(numel(generator.get_slabs()), ...
                testCase.oracle.counts.cscl_get_slabs);
            allSlabs=kssolv.analysis.matgenlab.core. ...
                generate_all_slabs(cscl,1,10,10);
            testCase.verifyEqual(numel(allSlabs), ...
                testCase.oracle.counts.cscl_all_index_1);
            bonds=containers.Map({'Cs|Cl'},{4});
            testCase.verifyEmpty(generator.get_slabs(bonds=bonds));
            testCase.verifyEqual(numel(kssolv.analysis.matgenlab.core. ...
                generate_all_slabs(cscl,1,10,10,bonds=bonds, ...
                max_broken_bonds=100)),3);

            iron=kssolv.analysis.matgenlab.core.Structure. ...
                from_spacegroup("Im-3m", ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(2.82), ...
                "Fe",[0,0,0]);
            reconstructed=kssolv.analysis.matgenlab.core. ...
                generate_all_slabs(iron,1,10,10, ...
                include_reconstructions=true);
            testCase.verifyEqual(numel(reconstructed), ...
                testCase.oracle.counts.fe_all_with_reconstruction);
        end

        function reconstructionArchiveMatches(testCase)
            nickel=kssolv.analysis.matgenlab.core.Structure. ...
                from_spacegroup("Fm-3m", ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3.51), ...
                "Ni",[0,0,0]);
            names=["fcc_110_missing_row_1x2", ...
                "fcc_111_adatom_t_1x1", ...
                "fcc_111_adatom_ft_1x1"];
            for name=names
                generator=kssolv.analysis.matgenlab.core. ...
                    ReconstructionGenerator(nickel,10,10,name);
                plain=generator.get_unreconstructed_slabs();
                rebuilt=generator.build_slabs();
                expected=testCase.oracle.reconstructions.(name);
                testCase.verifyEqual(plain{1}.num_sites, ...
                    expected.plain_sites);
                testCase.verifyEqual( ...
                    plain{1}.oriented_unit_cell.num_sites, ...
                    expected.plain_ouc_sites);
                testCase.verifyEqual(rebuilt{1}.num_sites, ...
                    expected.reconstructed_sites);
                testCase.verifyEqual( ...
                    rebuilt{1}.oriented_unit_cell.num_sites, ...
                    expected.reconstructed_ouc_sites);
                testCase.verifyEqual(string(rebuilt{1}.reconstruction), ...
                    string(expected.reconstruction));
                testCase.verifyEqual(rebuilt{1}.is_symmetric(), ...
                    expected.symmetric);
                if name=="fcc_110_missing_row_1x2"
                    testCase.verifyEqual(kssolv.analysis.matgenlab.core. ...
                        get_d(plain{1}),testCase.oracle.get_d, ...
                        AbsTol=2e-10);
                end
            end
            testCase.verifyError(@()kssolv.analysis.matgenlab.core. ...
                ReconstructionGenerator(nickel,10,10,"not_present"), ...
                "KSSOLV:Matgenlab:Surface:Reconstruction");
        end

        function centeringRegionsAndErrors(testCase)
            base=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(10), ...
                {"Li","Li"},[0,0,.92;0,0,.08]);
            centered=kssolv.analysis.matgenlab.core.center_slab(base);
            z=sort(centered.frac_coords(:,3));
            testCase.verifyEqual(z,[.42;.58],AbsTol=2e-12);

            slab=kssolv.analysis.matgenlab.core.Slab( ...
                centered.lattice,centered.species_and_occu, ...
                centered.frac_coords,[0,0,1],base,0,eye(3));
            regions=kssolv.analysis.matgenlab.core.get_slab_regions(slab);
            testCase.verifyEqual(regions,[.42,.58],AbsTol=2e-12);
            testCase.verifyError(@()kssolv.analysis.matgenlab.core. ...
                get_d(kssolv.analysis.matgenlab.core.Slab( ...
                base.lattice,"Li",[0,0,.5],[0,0,1],base,0,eye(3))), ...
                "KSSOLV:Matgenlab:Surface:NoLayer");
        end
    end
end

function structure=makeCsCl()
structure=kssolv.analysis.matgenlab.core.Structure.from_spacegroup( ...
    "Pm-3m",kssolv.analysis.matgenlab.core.Lattice.cubic(4.2), ...
    {"Cs","Cl"},[0,0,0;.5,.5,.5]);
end

function structure=makeMgO()
structure=kssolv.analysis.matgenlab.core.Structure( ...
    kssolv.analysis.matgenlab.core.Lattice.cubic(3.010), ...
    {"Mg","Mg","Mg","Mg","O","O","O","O"}, ...
    [0,0,0;0,.5,.5;.5,0,.5;.5,.5,0; ...
    .5,0,0;.5,.5,.5;0,0,.5;0,.5,0]);
structure=structure.add_oxidation_state_by_element( ...
    struct("Mg",2,"O",-6));
end

function verifySlab(testCase,actual,expected,tolerance)
testCase.verifyEqual(actual.num_sites,expected.num_sites);
testCase.verifyEqual(actual.lattice.matrix,expected.lattice, ...
    AbsTol=tolerance);
reference=kssolv.analysis.matgenlab.core.Structure( ...
    kssolv.analysis.matgenlab.core.Lattice(expected.lattice), ...
    cellstr(string(expected.species)),expected.frac_coords);
matcher=kssolv.analysis.matgenlab.core.StructureMatcher( ...
    .2,.3,5,false,false);
testCase.verifyTrue(matcher.fit(actual,reference));
testCase.verifyEqual(actual.miller_index, ...
    reshape(expected.miller_index,1,[]));
testCase.verifyEqual(actual.shift,expected.shift,AbsTol=tolerance);
testCase.verifyEqual(actual.scale_factor,expected.scale_factor, ...
    AbsTol=tolerance);
testCase.verifyEqual(actual.surface_area,expected.surface_area, ...
    AbsTol=tolerance);
testCase.verifyEqual(actual.normal,reshape(expected.normal,1,[]), ...
    AbsTol=tolerance);
testCase.verifyEqual(actual.center_of_mass(3), ...
    expected.center_of_mass(3),AbsTol=tolerance);
testCase.verifyEqual(actual.oriented_unit_cell.num_sites, ...
    expected.ouc_num_sites);
end
