classdef DopantPredictorTest < matlab.unittest.TestCase
    methods (Test)
        function substitutionSuggestionsMatchUpstreamFixture(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                [3.24, 0, 0; 0, 4.83, 0; 0, 0, 4.84]);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"O", "O", "O", "O", "Sn", "Sn"}, ...
                [0.5, 0.19, 0.80; 0.5, 0.80, 0.19; ...
                0, 0.30, 0.30; 0, 0.69, 0.69; ...
                0.5, 0.50, 0.50; 0, 0, 0]);
            structure = structure.add_oxidation_state_by_element( ...
                struct("Sn", 4, "O", -2));
            result = kssolv.analysis.matgenlab.core. ...
                get_dopants_from_substitution_probabilities(structure, 5);
            testCase.verifyEqual(numel(result.n_type), 5);
            testCase.verifyEqual(numel(result.p_type), 5);
            testCase.verifyEqual(string(result.n_type(1).dopant_species), "F-");
            testCase.verifyEqual(string(result.n_type(1).original_species), "O2-");
            testCase.verifyEqual(result.n_type(1).probability, ...
                0.06692682583342474, RelTol=1e-12);
            testCase.verifyEqual(string(result.p_type(1).dopant_species), "Co2+");
            testCase.verifyEqual(string(result.p_type(1).original_species), "Sn4+");
            testCase.verifyEqual(result.p_type(1).probability, ...
                0.023398867249112935, RelTol=1e-12);
        end

        function oxidationStatesAreRequired(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
                {"Na"}, [0, 0, 0]);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core. ...
                get_dopants_from_substitution_probabilities(structure), ...
                "KSSOLV:Matgenlab:DopantPredictor:MissingOxidationStates");
        end
    end
end
