classdef ElasticityKinematicsTest < matlab.unittest.TestCase
    methods (Test)
        function deformationAndStrainRoundTrip(testCase)
            deformation = kssolv.analysis.matgenlab.core.Deformation( ...
                [1.02, 0.03, 0; 0, 0.98, 0.01; 0, 0, 1.01]);
            strain = deformation.green_lagrange_strain;
            rebuilt = strain.get_deformation_matrix("upper");
            testCase.verifyEqual( ...
                double(rebuilt).' * double(rebuilt), ...
                2 * double(strain) + eye(3), AbsTol=1e-12);
            testCase.verifyTrue( ...
                kssolv.analysis.matgenlab.core.Deformation. ...
                from_index_amount([1, 2], 0.01).is_independent());
        end

        function stressPropertiesMatchFrozenOracle(testCase)
            matrix = [3, 1, 0; 1, -2, 0.5; 0, 0.5, 1];
            stress = kssolv.analysis.matgenlab.core.Stress(matrix);
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.elasticity.stress", ...
                "symbol", "Stress", ...
                "construct", struct("args", {{matrix}}), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "dev_principal_invariants"), ...
                    struct("kind", "get", "name", "von_mises"), ...
                    struct("kind", "get", "name", "mean_stress"), ...
                    struct("kind", "get", "name", "deviator_stress")}});
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            testCase.verifyEqual(stress.dev_principal_invariants, ...
                reshape(response.results{1}, 1, []), AbsTol=1e-12);
            testCase.verifyEqual(stress.von_mises, ...
                response.results{2}, AbsTol=1e-12);
            testCase.verifyEqual(stress.mean_stress, ...
                response.results{3}, AbsTol=1e-12);
            testCase.verifyEqual(double(stress.deviator_stress), ...
                response.results{4}, AbsTol=1e-12);
        end

        function deformedStructureSetCardinality(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
                {"Si"}, [0, 0, 0]);
            values = kssolv.analysis.matgenlab.core. ...
                DeformedStructureSet(structure);
            testCase.verifyEqual(length(values), 24);
            testCase.verifyNotEqual(values(1).volume, structure.volume);
        end
    end
end
