classdef ElasticityTest < matlab.unittest.TestCase
    % Frozen pymatgen-core v2026.7.24 elasticity parity tests.

    methods (Test)
        function secondOrderPropertiesAndCompliance(testCase)
            matrix = [ ...
                59.33,28.08,28.08,0,0,0
                28.08,59.31,28.07,0,0,0
                28.08,28.07,59.32,0,0,0
                0,0,0,26.35,0,0
                0,0,0,0,26.35,0
                0,0,0,0,0,26.35];
            tensor = kssolv.analysis.matgenlab.core. ...
                ElasticTensor.from_voigt(matrix);
            testCase.verifyEqual(tensor.k_voigt, ...
                38.491111111111, AbsTol=1e-11);
            testCase.verifyEqual(tensor.g_voigt, ...
                22.058666666667, AbsTol=1e-11);
            testCase.verifyEqual(tensor.k_reuss, ...
                38.491109451333, AbsTol=1e-11);
            testCase.verifyEqual(tensor.g_reuss, ...
                20.671466353068, AbsTol=1e-11);
            testCase.verifyEqual(tensor.y_mod, ...
                54087787667.161, AbsTol=0.01);
            testCase.verifyEqual(tensor.universal_anisotropy, ...
                0.33553509658699, AbsTol=1e-12);
            testCase.verifyEqual(tensor.homogeneous_poisson, ...
                0.26579965576473, AbsTol=1e-12);
            testCase.verifyEqual( ...
                tensor.directional_elastic_mod([1,1,1]), ...
                73.624444444444, AbsTol=1e-11);
            testCase.verifyEqual(tensor.directional_poisson_ratio( ...
                [1,0,0], [0,1,0]), 0.32138803886382, AbsTol=1e-12);
            testCase.verifyEqual( ...
                tensor.compliance_tensor.voigt * tensor.voigt, ...
                eye(6), AbsTol=1e-12);
        end

        function cubicExpansionAndLebedevQuadrature(testCase)
            copper = kssolv.analysis.matgenlab.core.Structure. ...
                from_spacegroup("Fm-3m", ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3.623), ...
                {"Cu"}, [0,0,0]);
            second = kssolv.analysis.matgenlab.core.Tensor. ...
                from_values_indices([167.8,113.5,74.5], ...
                [0,0;0,1;3,3], populate=true, structure=copper);
            third = kssolv.analysis.matgenlab.core.Tensor. ...
                from_values_indices([-1507,-965,-71,-7,-901,45], ...
                [0,0,0;0,0,1;0,1,2;0,3,3;0,5,5;3,4,5], ...
                populate=true, structure=copper);
            expansion = kssolv.analysis.matgenlab.core. ...
                ElasticTensorExpansion({second,third});
            ggt = double(expansion.get_ggt([1,0,0], [0,1,0]));
            testCase.verifyEqual(ggt, diag( ...
                [4.92080537,4.2852349,-0.7147651]), AbsTol=1e-8);
            tgt = double(expansion.get_tgt());
            testCase.verifyEqual(tgt, eye(3) * ...
                2.59631832058877, AbsTol=1e-12);
            testCase.verifyEqual(expansion.get_gruneisen_parameter(), ...
                2.59631832058877, AbsTol=1e-12);
            testCase.verifyEqual(expansion.get_heat_capacity( ...
                300, copper, [1,0,0], [0,1,0]), ...
                8.285799471733913, AbsTol=1e-12);
        end

        function highOrderStressEnergyAndInverse(testCase)
            second = kssolv.analysis.matgenlab.core. ...
                NthOrderElasticTensor.from_voigt(diag(100:105));
            thirdVoigt = zeros(6,6,6);
            thirdVoigt(1,1,1) = -400;
            third = kssolv.analysis.matgenlab.core. ...
                NthOrderElasticTensor.from_voigt(thirdVoigt);
            fourth = kssolv.analysis.matgenlab.core. ...
                NthOrderElasticTensor(zeros(repmat(3,1,8)));
            expansion = kssolv.analysis.matgenlab.core. ...
                ElasticTensorExpansion({second,third,fourth});
            strain = kssolv.analysis.matgenlab.core.Strain. ...
                from_voigt([0.03,0,0,0,0,0]);
            stress = expansion.calculate_stress(strain);
            rebuilt = expansion.get_strain_from_stress(stress);
            testCase.verifyEqual(double(rebuilt), double(strain), ...
                AbsTol=1e-12);
            testCase.verifyEqual(expansion.energy_density(strain), ...
                second.energy_density(strain) + ...
                third.energy_density(strain), AbsTol=1e-15);
            testCase.verifyEqual(expansion.order, 4);
        end

        function fittingPrimitives(testCase)
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.get_diff_coeff([0,1]), ...
                [-1,1], AbsTol=1e-14);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.get_diff_coeff( ...
                -4:4, 2), ...
                [-0.001785714285714,0.025396825396825, ...
                -0.2,1.6,-2.847222222222222,1.6,-0.2, ...
                0.025396825396825,-0.001785714285714], ...
                AbsTol=1e-12);
            [pseudo, absent] = ...
                kssolv.analysis.matgenlab.core.generate_pseudo(eye(6), 4);
            testCase.verifyEqual(size(pseudo{1}), [21,36]);
            testCase.verifyEqual(size(pseudo{2}), [56,36]);
            testCase.verifyEqual(size(pseudo{3}), [126,36]);
            testCase.verifyEqual(cellfun(@numel, absent), [0,20,90]);

            stiffness = diag([100,110,120,40,50,60]);
            amplitudes = [-0.02,-0.01,0,0.01,0.02];
            strains = {};
            stresses = {};
            for mode = 1:6
                for amount = amplitudes
                    vector = zeros(1,6);
                    vector(mode) = amount;
                    strains{end+1} = ...
                        kssolv.analysis.matgenlab.core.Strain. ...
                        from_voigt(vector); %#ok<AGROW>
                    stresses{end+1} = ...
                        kssolv.analysis.matgenlab.core.Stress. ...
                        from_voigt((stiffness * vector.').'); %#ok<AGROW>
                end
            end
            fitted = kssolv.analysis.matgenlab.core.diff_fit( ...
                strains, stresses, zeros(3), 2);
            testCase.verifyEqual(fitted{1}.voigt, stiffness, ...
                AbsTol=1e-10);
        end

        function stressStrainAndMsonRoundTrips(testCase)
            stress = kssolv.analysis.matgenlab.core.Stress( ...
                [0.51,2.29,2.42;2.29,5.14,5.07;2.42,5.07,5.33]);
            testCase.verifyEqual(stress.mean_stress, 3.66, AbsTol=1e-14);
            testCase.verifyEqual(stress.von_mises, ...
                11.522538782751, AbsTol=1e-12);
            strain = kssolv.analysis.matgenlab.core.Strain. ...
                from_voigt([0,0.0002,0.0002,0.0004,0.02,0.02]);
            testCase.verifyEqual(strain.voigt, ...
                [0,0.0002,0.0002,0.0004,0.02,0.02], AbsTol=1e-15);
            deformation = strain.get_deformation_matrix();
            testCase.verifyEqual(double( ...
                deformation.green_lagrange_strain), ...
                double(strain), AbsTol=1e-12);

            objects = {deformation,strain,stress, ...
                kssolv.analysis.matgenlab.core.ElasticTensor. ...
                from_voigt(eye(6)), ...
                kssolv.analysis.matgenlab.core.ComplianceTensor. ...
                from_voigt(eye(6))};
            for index = 1:numel(objects)
                restored = kssolv.analysis.matgenlab.util.decode( ...
                    kssolv.analysis.matgenlab.util.encode(objects{index}));
                testCase.verifyClass(restored, class(objects{index}));
                testCase.verifyEqual(double(restored), ...
                    double(objects{index}), AbsTol=1e-15);
            end
        end
    end
end
