classdef EntriesInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function frozenEntryAndUncertaintyParity(testCase)
            % Frozen with pymatgen-core 2026.7.24.
            entry = kssolv.analysis.matgenlab.core.Entry("Fe6O9", -30);
            normalized = entry.normalize();
            testCase.verifyEqual(normalized.formula, "Fe2 O3");
            testCase.verifyEqual(normalized.energy, -10);
            testCase.verifyEqual(entry.normalize("atom").energy, -2);

            cases = { ...
                {}, NaN; ...
                {kssolv.analysis.matgenlab.core. ...
                ConstantEnergyAdjustment(0, "uncertainty", 0.2)}, NaN; ...
                {kssolv.analysis.matgenlab.core. ...
                ConstantEnergyAdjustment(1, "uncertainty", 0)}, NaN; ...
                {kssolv.analysis.matgenlab.core. ...
                ConstantEnergyAdjustment(1, "uncertainty", 0.2), ...
                kssolv.analysis.matgenlab.core. ...
                ConstantEnergyAdjustment(2, "uncertainty", 0.3)}, ...
                0.36055512754639896};
            for index = 1:size(cases, 1)
                computed = kssolv.analysis.matgenlab.core.ComputedEntry( ...
                    "Li", 0, "energy_adjustments", cases{index, 1});
                if isnan(cases{index, 2})
                    testCase.verifyTrue(isnan( ...
                        computed.correction_uncertainty));
                else
                    testCase.verifyEqual( ...
                        computed.correction_uncertainty, ...
                        cases{index, 2}, AbsTol = 1e-14);
                end
            end
        end

        function translatedStructuresAndComparatorGroup(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice.cubic(4);
            first = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"Li", "O"}, [0, 0, 0; 0.5, 0.5, 0.5]);
            translated = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"O", "Li"}, ...
                [0.75, 0.75, 0.75; 0.25, 0.25, 0.25]);
            entries = { ...
                kssolv.analysis.matgenlab.core. ...
                ComputedStructureEntry(first, -2), ...
                kssolv.analysis.matgenlab.core. ...
                ComputedStructureEntry(translated, -1)};
            groups = kssolv.analysis.matgenlab.core. ...
                group_entries_by_structure(entries, ...
                "primitive_cell", false);
            testCase.verifyNumElements(groups, 1);
            testCase.verifyNumElements(groups{1}, 2);
        end

        function entrySetCsvUsesPhaseDiagramEntries(testCase)
            entries = kssolv.analysis.matgenlab.core.EntrySet({ ...
                kssolv.analysis.matgenlab.analysis.PDEntry( ...
                "Li2O", -3, "name", "sample")});
            path = string(tempname) + ".csv";
            cleanup = onCleanup(@() deleteIfPresent(path));
            entries.to_csv(path, true);
            restored = ...
                kssolv.analysis.matgenlab.core.EntrySet.from_csv(path);
            testCase.verifyClass(restored.entries{1}, ...
                "kssolv.analysis.matgenlab.analysis.PDEntry");
            testCase.verifyEqual(restored.entries{1}.name, "sample");
            clear cleanup
        end
    end
end

function deleteIfPresent(path)
if isfile(path), delete(path); end
end
