classdef EntriesEnergyEwaldTest < matlab.unittest.TestCase
    % Frozen pymatgen-core v2026.7.24 entries/energy_models/ewald parity.

    methods (Test)
        function energyAdjustments(testCase)
            base=kssolv.analysis.matgenlab.core.EnergyAdjustment(10);
            testCase.verifyEqual(base.name,"Manual adjustment");
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.EnergyAdjustment. ...
                from_dict(base.as_dict()).as_dict(),base.as_dict());

            manual=kssolv.analysis.matgenlab.core.ManualEnergyAdjustment(10);
            testCase.verifyEqual(manual.explain, ...
                "Manual energy adjustment (10.000 eV)");
            constant=kssolv.analysis.matgenlab.core. ...
                ConstantEnergyAdjustment(8,"uncertainty",0);
            testCase.verifyEqual([constant.value,constant.uncertainty],[8,0]);
            composition=kssolv.analysis.matgenlab.core. ...
                CompositionEnergyAdjustment(2,2, ...
                "uncertainty_per_atom",0,"name","H");
            testCase.verifyEqual(composition.value,4);
            testCase.verifyEqual(composition.explain, ...
                "Composition-based energy adjustment (2.000 eV/atom x 2 atoms)");
            temperature=kssolv.analysis.matgenlab.core. ...
                TemperatureEnergyAdjustment(-.1,298,5, ...
                "uncertainty_per_deg",0,"name","entropy");
            testCase.verifyEqual(temperature.value,-149,AbsTol=1e-14);
            testCase.verifyEqual(temperature.explain, ...
                "Temperature-based energy adjustment (-0.1000 eV/K/atom x 298 K x 5 atoms)");
        end

        function computedEntryNormalizationAndMson(testCase)
            adjustments={ ...
                kssolv.analysis.matgenlab.core.ManualEnergyAdjustment(5), ...
                kssolv.analysis.matgenlab.core.ConstantEnergyAdjustment(5), ...
                kssolv.analysis.matgenlab.core.CompositionEnergyAdjustment( ...
                    1,5,"uncertainty_per_atom",0), ...
                kssolv.analysis.matgenlab.core.TemperatureEnergyAdjustment( ...
                    .005,100,10,"uncertainty_per_deg",0)};
            entry=kssolv.analysis.matgenlab.core.ComputedEntry( ...
                "Na5Cl5",6.9,"energy_adjustments",adjustments,"entry_id","id");
            testCase.verifyEqual(entry.correction,20);
            normalized=entry.normalize();
            testCase.verifyEqual(normalized.correction,4,AbsTol=1e-14);
            testCase.verifyEqual(cellfun(@(item)item.value, ...
                normalized.energy_adjustments),ones(1,4),AbsTol=1e-14);
            atom=entry.normalize("atom");
            testCase.verifyEqual(atom.energy*10,26.9,AbsTol=1e-13);
            restored=kssolv.analysis.matgenlab.util.decode( ...
                kssolv.analysis.matgenlab.util.encode(entry));
            testCase.verifyTrue(restored==entry);

            uncertain=kssolv.analysis.matgenlab.core.ComputedEntry( ...
                "Fe6O9",6.9,"energy_adjustments",{ ...
                kssolv.analysis.matgenlab.core.CompositionEnergyAdjustment( ...
                -.5,9,"uncertainty_per_atom",.1)});
            testCase.verifyEqual(uncertain.energy,2.4,AbsTol=1e-14);
            testCase.verifyEqual(uncertain.correction_uncertainty,.9,AbsTol=1e-14);
        end

        function structureEntryGroupingAndSet(testCase)
            lattice=kssolv.analysis.matgenlab.core.Lattice.cubic(4);
            first=kssolv.analysis.matgenlab.core.Structure( ...
                lattice,{"Li","O"},[0,0,0;.5,.5,.5]);
            second=kssolv.analysis.matgenlab.core.Structure( ...
                lattice,{"O","Li"},[.5,.5,.5;0,0,0]);
            e1=kssolv.analysis.matgenlab.core.ComputedStructureEntry(first,-2);
            e2=kssolv.analysis.matgenlab.core.ComputedStructureEntry(second,-1);
            groups=kssolv.analysis.matgenlab.core. ...
                group_entries_by_structure({e1,e2},"primitive_cell",false);
            testCase.verifyNumElements(groups,1);
            testCase.verifyNumElements(groups{1},2);
            restored=kssolv.analysis.matgenlab.util.decode( ...
                kssolv.analysis.matgenlab.util.encode(e1));
            testCase.verifyTrue(restored==e1);
            entries=kssolv.analysis.matgenlab.core.EntrySet({ ...
                kssolv.analysis.matgenlab.core.ComputedEntry("Li2O",-2), ...
                kssolv.analysis.matgenlab.core.ComputedEntry("Li2O",-1), ...
                kssolv.analysis.matgenlab.core.ComputedEntry("O2",-3)});
            testCase.verifyEqual(length(entries),3);
            testCase.verifyNumElements(entries.ground_states,2);
            testCase.verifyTrue(entries.is_ground_state(entries.entries{1}));
            testCase.verifyFalse(entries.is_ground_state(entries.entries{2}));
            testCase.verifyTrue(isfield(entries.as_dict(),"entries"));
            groundOnly=kssolv.analysis.matgenlab.core.EntrySet(entries.entries);
            groundOnly.remove_non_ground_states();
            testCase.verifyEqual(length(groundOnly),2);
            testCase.verifyEqual(entries.get_subset_in_chemsys({"O"}).chemsys,"O");
            compositionGroups=kssolv.analysis.matgenlab.core. ...
                group_entries_by_composition(entries.entries);
            testCase.verifyNumElements(compositionGroups,2);
            removed=entries.entries{2};entries.discard(removed);
            testCase.verifyEqual(length(entries),2);entries.add(removed);
            csvPath=string(tempname)+".csv";
            cleanup=onCleanup(@()deleteIfPresent(csvPath)); %#ok<NASGU>
            entries.to_csv(csvPath);
            csvRoundTrip=kssolv.analysis.matgenlab.core.EntrySet.from_csv(csvPath);
            testCase.verifyEqual(length(csvRoundTrip),3);
            function deleteIfPresent(path)
                if isfile(path),delete(path);end
            end
        end

        function energyModels(testCase)
            lattice=kssolv.analysis.matgenlab.core.Lattice( ...
                [3,0,0;1,3,0;0,-2,3]);
            occupancy=kssolv.analysis.matgenlab.core.Composition( ...
                {"Si4+",.5;"O2-",.25;"P5+",.25});
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                lattice,{occupancy,occupancy,occupancy,occupancy}, ...
                [0,0,0;.75,.75,.75;.5,.5,.5;.25,.25,.25]);
            ewald=kssolv.analysis.matgenlab.core.EwaldElectrostaticModel();
            testCase.verifyEqual(ewald.get_energy(structure), ...
                -264.66364858,AbsTol=1e-2);
            testCase.verifyClass( ...
                kssolv.analysis.matgenlab.core.EwaldElectrostaticModel. ...
                from_dict(ewald.as_dict()), ...
                "kssolv.analysis.matgenlab.core.EwaldElectrostaticModel");
            sites=kssolv.analysis.matgenlab.core.NsitesModel();
            testCase.verifyEqual(sites.get_energy(structure),4);
            testCase.verifyClass( ...
                kssolv.analysis.matgenlab.core.EnergyModel. ...
                from_dict(sites.as_dict()), ...
                "kssolv.analysis.matgenlab.core.NsitesModel");

            symmetric=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {"Cs","Cl"},[0,0,0;.5,.5,.5]);
            symmetry=kssolv.analysis.matgenlab.core.SymmetryModel();
            testCase.verifyEqual(symmetry.get_energy(symmetric),-221);

            spinUp=kssolv.analysis.matgenlab.core.Species("Fe",2,"spin",4);
            spinDown=kssolv.analysis.matgenlab.core.Species("Fe",2,"spin",-4);
            spins=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {spinUp,spinDown},[0,0,0;.5,.5,.5]);
            ising=kssolv.analysis.matgenlab.core.IsingModel(5,6);
            testCase.verifyEqual(ising.get_energy(spins), ...
                13.333333333333313,AbsTol=5e-14);
        end

        function ewaldMatricesForcesPartialAndSubstructure(testCase)
            structure=testCase.nacl();
            ewald=kssolv.analysis.matgenlab.core.EwaldSummation( ...
                structure,"compute_forces",true);
            expected=[.11085705337074589,-.3813548961470606, ...
                .5947062711700271,-5.409891115571493,-5.196539740548526];
            actual=[ewald.eta,ewald.real_space_energy, ...
                ewald.reciprocal_space_energy,ewald.point_energy, ...
                ewald.total_energy];
            testCase.verifyEqual(actual,expected,AbsTol=2e-12);
            testCase.verifyEqual(ewald.total_energy_matrix, ...
                [-2.48470320070622,-.113566669568044; ...
                -.113566669568044,-2.48470320070622],AbsTol=2e-12);
            testCase.verifyLessThan(max(abs(ewald.forces),[],"all"),2e-15);
            testCase.verifyEqual(ewald.compute_partial_energy(2), ...
                -2.48470320070622,AbsTol=2e-12);
            sub=kssolv.analysis.matgenlab.core.Structure( ...
                structure.lattice,{kssolv.analysis.matgenlab.core.Species("Na",1)}, ...
                [0,0,0]);
            testCase.verifyEqual(ewald.compute_sub_structure(sub), ...
                -2.48470320070622,AbsTol=2e-12);
            restored=kssolv.analysis.matgenlab.util.decode( ...
                kssolv.analysis.matgenlab.util.encode(ewald));
            testCase.verifyEqual(restored.total_energy_matrix, ...
                ewald.total_energy_matrix,AbsTol=0);
        end

        function officialEwaldFixture(testCase)
            fixture=fullfile(fileparts(mfilename("fullpath")),"POSCAR_ewald");
            poscar=kssolv.analysis.matgenlab.io.vasp.Poscar.from_file( ...
                fixture,"check_for_potcar",false);
            base=poscar.structure;oxidation=struct(Fe=2,P=5,O=-2);
            species=arrayfun(@(index) ...
                kssolv.analysis.matgenlab.core.Species( ...
                char(base(index).specie.symbol), ...
                oxidation.(char(base(index).specie.symbol))), ...
                1:base.num_sites,"UniformOutput",false);
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                base.lattice,species,base.frac_coords);
            ewald=kssolv.analysis.matgenlab.core.EwaldSummation( ...
                structure,"compute_forces",true);
            testCase.verifyEqual(ewald.real_space_energy, ...
                -502.235520540275,AbsTol=1e-9);
            testCase.verifyEqual(ewald.reciprocal_space_energy, ...
                6.15410742416884,AbsTol=1e-10);
            testCase.verifyEqual(ewald.point_energy, ...
                -620.226010208638,AbsTol=1e-10);
            testCase.verifyEqual(ewald.total_energy, ...
                -1122.998859425969,AbsTol=1e-9);
            testCase.verifyEqual(ewald.forces(1,1), ...
                -.198818604998084,AbsTol=1e-12);
            testCase.verifyEqual(sum(abs(ewald.forces),"all"), ...
                915.925392164915,AbsTol=1e-9);
        end

        function ewaldMinimizerOfficialFixture(testCase)
            matrix=[ ...
                -3,3,4,0,3,3,1,14,9,-4;1,-3,-3,12,-4,-1,5,11,1,12; ...
                14,7,13,15,13,5,-5,10,14,-2;9,13,4,1,3,-4,7,0,6,-4; ...
                4,-4,6,1,12,-4,-2,13,0,6;13,7,-4,12,-2,9,8,-5,3,1; ...
                8,1,10,-4,-2,4,13,12,-3,13;2,11,8,1,-1,5,-3,4,5,0; ...
                0,14,4,3,-1,-5,7,-1,-1,3;2,-2,10,1,6,-5,-3,12,0,13];
            manipulations={{.9,4,[1,2,3,4,8],"a"}, ...
                {-1,2,[5,6,7],"b"}};
            minimizer=kssolv.analysis.matgenlab.core.EwaldMinimizer( ...
                matrix,manipulations,50);
            testCase.verifyEqual(size(minimizer.output_lists,1),15);
            testCase.verifyEqual(minimizer.minimized_sum,111.63,AbsTol=1e-12);
            testCase.verifyEqual(size(minimizer.best_m_list,1),6);
        end

        function ewaldCandidateApiEdges(testCase)
            structure=testCase.nacl();
            ewald=kssolv.analysis.matgenlab.core.EwaldSummation( ...
                structure,"compute_forces",true);
            testCase.verifyEqual(sum(ewald.real_space_energy_matrix,"all"), ...
                ewald.real_space_energy,AbsTol=1e-14);
            testCase.verifyEqual( ...
                sum(ewald.reciprocal_space_energy_matrix,"all"), ...
                ewald.reciprocal_space_energy,AbsTol=1e-14);
            testCase.verifyEqual(sum(ewald.point_energy_matrix), ...
                ewald.point_energy,AbsTol=1e-14);
            testCase.verifyEqual(ewald.get_site_energy(1), ...
                -2.598269870274263,AbsTol=2e-12);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core.EwaldSummation( ...
                kssolv.analysis.matgenlab.core.Structure( ...
                structure.lattice,{"Na","Cl"},structure.frac_coords)), ...
                "KSSOLV:Matgenlab:Ewald:MissingCharge");

            charged=kssolv.analysis.matgenlab.core.Structure( ...
                structure.lattice,{"Na","Cl"},structure.frac_coords, ...
                site_properties=struct("charge",[1,-1]));
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core. ...
                compute_average_oxidation_state(charged(1)),1);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core. ...
                EwaldSummation(charged).total_energy, ...
                -5.196539740548526,AbsTol=2e-12);

            matrix=[1,2;3,4];
            manipulation={{.5,1,[0,1],"x"}};
            minimizer=kssolv.analysis.matgenlab.core.EwaldMinimizer( ...
                matrix,manipulation,2);
            testCase.verifyEqual(minimizer.output_lists(:,1), ...
                {4.5;6.75},AbsTol=1e-14);
            testCase.verifyEqual(minimizer.best_m_list,{1,"x"});
            testCase.verifyEqual(minimizer.best_case( ...
                matrix,{{.5,1,[0,1],"x"}},[0,1]),3.25,AbsTol=1e-14);
            testCase.verifyEqual(minimizer.get_next_index( ...
                matrix,{.5,1,[0,1],"x"},[0,1]),1);
            minimizer.add_m_list(3,{0,"manual"});
            testCase.verifyEqual(minimizer.minimized_sum,4.5);
            testCase.verifyEqual(minimizer.output_lists{1,1},3);
        end
    end

    methods (Static,Access=private)
        function structure=nacl()
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(5.64), ...
                {kssolv.analysis.matgenlab.core.Species("Na",1), ...
                kssolv.analysis.matgenlab.core.Species("Cl",-1)}, ...
                [0,0,0;.5,.5,.5]);
        end
    end
end
