classdef GraphsInventoryTest < matlab.unittest.TestCase
    % Frozen behavioral parity for pymatgen.core.graphs 2026.7.24.
    properties (Constant, Access=private)
        Core = "kssolv.analysis.matgenlab.core."
    end

    methods (Test)
        function structureFrozenOracle(testCase)
            oracle=testCase.oracle();
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.tetragonal(5,50), ...
                {"H"},[0,0,0]);
            graph=kssolv.analysis.matgenlab.core.StructureGraph. ...
                from_empty_graph(structure,"edge_weight_name","strength", ...
                "edge_weight_units","eV");
            graph.add_edge(1,1,"to_jimage",[1,0,0],"weight",1);
            graph.add_edge(1,1,"to_jimage",[0,1,0],"weight",3);

            testCase.verifyEqual(graph.graph.number_of_edges(), ...
                oracle.structure.edges);
            testCase.verifyEqual(graph.get_coordination_of_site(1), ...
                oracle.structure.coordination);
            connected=graph.get_connected_sites(1,[0,0,7]);
            testCase.verifyEqual(numel(connected),4);
            testCase.verifyTrue(all(cellfun(@(site) ...
                isa(site,"kssolv.analysis.matgenlab.core.ConnectedSite"), ...
                connected)));

            types=graph.types_and_weights_of_connections;
            testCase.verifyEqual(types("H-H"), ...
                transpose(oracle.structure.types.H_H));
            stats=graph.weight_statistics;
            testCase.verifyEqual(stats.all_weights, ...
                transpose(oracle.structure.stats.all_weights));
            testCase.verifyEqual(stats.min,oracle.structure.stats.min);
            testCase.verifyEqual(stats.max,oracle.structure.stats.max);
            testCase.verifyEqual(stats.mean,oracle.structure.stats.mean);
            testCase.verifyEqual(stats.variance, ...
                oracle.structure.stats.variance);
            testCase.verifyEqual(graph.types_of_coordination_environments(), ...
                cellstr(oracle.structure.environments));
            testCase.verifyEqual( ...
                graph.types_of_coordination_environments(true), ...
                cellstr(oracle.structure.anonymous));

            roundtrip=kssolv.analysis.matgenlab.core.StructureGraph. ...
                from_dict(graph.as_dict());
            testCase.verifyTrue(roundtrip==graph);
            testCase.verifyEqual(graph.diff(roundtrip).dist,0);
        end

        function reorderedStrictDiffAndAliases(testCase)
            lattice=kssolv.analysis.matgenlab.core.Lattice.cubic(4);
            first=kssolv.analysis.matgenlab.core.Structure( ...
                lattice,{"H","He"},[0,0,0;.5,.5,.5]);
            second=kssolv.analysis.matgenlab.core.Structure( ...
                lattice,{"He","H"},[.5,.5,.5;0,0,0]);
            firstGraph=kssolv.analysis.matgenlab.core.StructureGraph. ...
                with_edges(first,[1,2]);
            secondGraph=kssolv.analysis.matgenlab.core.StructureGraph. ...
                from_edges(second,[1,2]);
            testCase.verifyEqual(firstGraph.diff(secondGraph,true).dist,0);
            testCase.verifyTrue(firstGraph==secondGraph);
            testCase.verifyEqual(firstGraph.diff(secondGraph,false).dist,0);

            empty=kssolv.analysis.matgenlab.core.StructureGraph. ...
                with_empty_graph(first);
            testCase.verifyEqual(empty.name,"bonds");
            testCase.verifyEqual(length(empty),2);
        end

        function moleculeFrozenOracle(testCase)
            oracle=testCase.oracle();
            angles=transpose(0:5)*pi/3;
            molecule=kssolv.analysis.matgenlab.core.Molecule( ...
                repmat({"C"},1,6), ...
                [cos(angles),sin(angles),zeros(6,1)]);
            graph=kssolv.analysis.matgenlab.core.MoleculeGraph. ...
                from_edges(molecule,[1,2;2,3;3,4;4,5;5,6;6,1]);

            testCase.verifyEqual(graph.get_coordination_of_site(1), ...
                oracle.molecule.coordination);
            rings=graph.find_rings(1);
            testCase.verifyNumElements(rings,1);
            testCase.verifyEqual(sortrows(sort(rings{1},2)), ...
                sortrows(sort(oracle.molecule.ring,2)));

            fragments=graph.build_unique_fragments();
            testCase.verifyEqual(numel(fieldnames(fragments)), ...
                oracle.molecule.fragment_groups);
            testCase.verifyEqual(sum(structfun(@numel,fragments)), ...
                oracle.molecule.fragment_count);
            roundtrip=kssolv.analysis.matgenlab.core.MoleculeGraph. ...
                from_dict(graph.as_dict());
            testCase.verifyTrue(graph.isomorphic_to(roundtrip));
            testCase.verifyTrue(graph==roundtrip);

            split=graph.split_molecule_subgraphs([1,2;4,5]);
            testCase.verifyEqual(sort(cellfun(@length,split)),[3,3]);
        end

        function periodicMoleculeExtractionAndDot(testCase)
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(10), ...
                {"H","H"},[.95,0,0;.05,0,0]);
            graph=kssolv.analysis.matgenlab.core.StructureGraph. ...
                from_empty_graph(structure);
            graph.add_edge(1,2,"to_jimage",[1,0,0]);
            molecules=graph.get_subgraphs_as_molecules();
            testCase.verifyNumElements(molecules,1);
            testCase.verifyEqual(molecules{1}.formula,"H2");
            testCase.verifyEqual(vecnorm(diff(molecules{1}.cart_coords),2,2), ...
                1,AbsTol=1e-12);

            path=tempname()+".dot";
            cleanup=onCleanup(@()deleteIfPresent(path));
            graph.draw_graph_to_file(path,"hide_image_edges",false, ...
                "image_labels",true);
            testCase.verifyTrue(isfile(path));
            text=fileread(path);
            testCase.verifySubstring(text,"graph G");
            clear cleanup
        end

        function inventorySurfaceIsPresent(testCase)
            structureMethods=string(methods( ...
                "kssolv.analysis.matgenlab.core.StructureGraph"));
            expectedStructure=["from_empty_graph","with_empty_graph", ...
                "from_edges","with_edges","from_local_env_strategy", ...
                "with_local_env_strategy","add_edge","insert_node", ...
                "set_node_attributes","alter_edge","break_edge", ...
                "remove_nodes","substitute_group","get_connected_sites", ...
                "get_coordination_of_site","draw_graph_to_file", ...
                "types_of_coordination_environments","as_dict","from_dict", ...
                "sort","diff","get_subgraphs_as_molecules"];
            testCase.verifyTrue(all(ismember(expectedStructure, ...
                structureMethods)));

            moleculeMethods=string(methods( ...
                "kssolv.analysis.matgenlab.core.MoleculeGraph"));
            expectedMolecule=["from_empty_graph","with_empty_graph", ...
                "from_edges","with_edges","from_local_env_strategy", ...
                "with_local_env_strategy","add_edge","insert_node", ...
                "set_node_attributes","alter_edge","break_edge", ...
                "remove_nodes","get_disconnected_fragments", ...
                "split_molecule_subgraphs","build_unique_fragments", ...
                "substitute_group","replace_group","find_rings", ...
                "get_connected_sites","get_coordination_of_site", ...
                "draw_graph_to_file","as_dict","from_dict","sort", ...
                "isomorphic_to","diff"];
            testCase.verifyTrue(all(ismember(expectedMolecule, ...
                moleculeMethods)));
        end
    end

    methods (Static, Access=private)
        function value=oracle()
            root=fileparts(fileparts(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath")))))));
            path=fullfile(root,"dev","matgenlab","oracles", ...
                "core_graphs_2026.7.24.json");
            value=jsondecode(fileread(path));
        end
    end
end

function deleteIfPresent(path)
if isfile(path),delete(path);end
end
