classdef MolecularOrbitalsTest < matlab.unittest.TestCase
    methods (Test)
        function strontiumTitanate(testCase)
            object = ...
                kssolv.analysis.matgenlab.core.MolecularOrbitals("SrTiO3");
            testCase.verifyEqual(object.elec_neg, 2.49, "AbsTol", 1e-12);
            testCase.verifyEqual(string(object.band_edges.HOMO{1}), "O");
            testCase.verifyEqual(string(object.band_edges.HOMO{2}), "2p");
            testCase.verifyEqual(object.band_edges.HOMO{3}, ...
                -0.338381, "AbsTol", 1e-12);
            testCase.verifyEqual(string(object.band_edges.LUMO{1}), "Ti");
            testCase.verifyEqual(string(object.band_edges.LUMO{2}), "3d");
            testCase.verifyFalse(object.band_edges.metal);
        end

        function orbitalKeysMatchPymatgen(testCase)
            orbitals = ...
                kssolv.analysis.matgenlab.core.Element("O").atomic_orbitals;
            testCase.verifyTrue(isKey(orbitals, "1s"));
            testCase.verifyTrue(isKey(orbitals, "2p"));
        end

        function valuesMatchPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.molecular_orbitals", ...
                "symbol", "MolecularOrbitals", ...
                "construct", struct("args", {{'SrTiO3'}}), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "elec_neg"), ...
                    struct("kind", "get", "name", "band_edges")}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            actual = ...
                kssolv.analysis.matgenlab.core.MolecularOrbitals("SrTiO3");
            testCase.verifyEqual(actual.elec_neg, ...
                reference.results{1}, "AbsTol", 1e-12);
            expected = reference.results{2};
            testCase.verifyEqual(actual.band_edges.HOMO{3}, ...
                expected.HOMO{3}, "AbsTol", 1e-12);
            testCase.verifyEqual(actual.band_edges.LUMO{3}, ...
                expected.LUMO{3}, "AbsTol", 1e-12);
            testCase.verifyEqual(actual.band_edges.metal, expected.metal);
        end
    end
end
