classdef PeriodicTableParityTest < matlab.unittest.TestCase
    %PERIODICTABLEPARITYTEST Frozen pymatgen-core v2026.7.24 oracle values.

    methods (Test)
        function elementBaseSurfaceAndNumerics(testCase)
            import kssolv.analysis.matgenlab.core.Element
            import kssolv.analysis.matgenlab.core.ElementBase
            iron = ElementBase("Fe");
            testCase.verifyClass(iron, ...
                "kssolv.analysis.matgenlab.core.ElementBase");
            testCase.verifyEqual(iron.symbol, "Fe");
            actual = [iron.X, iron.atomic_radius, iron.atomic_mass, ...
                iron.ionization_energy, iron.electron_affinity, ...
                iron.average_ionic_radius, ...
                iron.average_cationic_radius, ...
                iron.average_anionic_radius, iron.number, ...
                iron.max_oxidation_state, iron.min_oxidation_state, ...
                iron.n_electrons, iron.valence, iron.row, iron.group, ...
                iron.iupac_ordering];
            expected = [1.83, 1.4, 55.845, 7.9024681, 0.15323635, ...
                0.8525, 0.8525, 0, 26, 6, -2, 26, 2, 6, 4, 8, 64];
            testCase.verifyEqual(actual, expected, AbsTol=1e-10);
            testCase.verifyTrue(isnan(iron.atomic_mass_number));
            testCase.verifyEqual(iron.electronic_structure, ...
                "[Ar].3d6.4s2");
            testCase.verifyEqual(iron.block, "d");
            testCase.verifyEqual(iron.oxidation_states, ...
                [-2, -1, 1, 2, 3, 4, 5, 6]);
            testCase.verifyEqual(iron.common_oxidation_states, [2, 3]);
            testCase.verifyEqual(iron.icsd_oxidation_states, [2, 3]);
            orbitals = iron.atomic_orbitals_eV;
            testCase.verifyEqual(orbitals("3d"), ...
                -8.028692300490327, AbsTol=3e-12);
            radii = iron.ionic_radii;
            testCase.verifyEqual(radii(2), 0.92);
            testCase.verifyEqual(radii(3), 0.785);
            testCase.verifyEqual(iron.full_electronic_structure, { ...
                1, "s", 2; 2, "s", 2; 2, "p", 6; ...
                3, "s", 2; 3, "p", 6; 4, "s", 2; 3, "d", 6});
            testCase.verifyEqual(iron.ground_state_term_symbol, "5D4.0");
            testCase.verifyNumElements(iron.term_symbols, 16);
            testCase.verifyEqual(iron.data.AtomicNo, 26);
            testCase.verifyEqual(Element.from_dict(iron.as_dict()), ...
                Element("Fe"));
        end

        function categoriesFactoriesAndPrinter(testCase)
            import kssolv.analysis.matgenlab.core.Element
            cases = { ...
                "He", "is_noble_gas"; ...
                "Fe", "is_transition_metal"; ...
                "Al", "is_post_transition_metal"; ...
                "Sc", "is_rare_earth"; ...
                "Li", "is_alkali"; ...
                "Ca", "is_alkaline"; ...
                "Cl", "is_halogen"; ...
                "O", "is_chalcogen"; ...
                "Nd", "is_lanthanoid"; ...
                "U", "is_actinoid"; ...
                "Tc", "is_radioactive"; ...
                "N", "is_quadrupolar"; ...
                "B", "is_metalloid"};
            for index = 1:size(cases, 1)
                element = Element(cases{index, 1});
                testCase.verifyTrue(element.(cases{index, 2}), ...
                    strjoin(string(cases(index, :)), ":"));
            end
            testCase.verifyTrue(Element("Fe").is_metal);
            testCase.verifyFalse(Element("He").is_metal);
            testCase.verifyEqual( ...
                Element("N").nmr_quadrupole_moment.N_14, 20.44);
            testCase.verifyEqual(Element.from_Z(26), Element("Fe"));
            testCase.verifyEqual(Element.from_name("iron"), Element("Fe"));
            testCase.verifyEqual( ...
                Element.from_row_and_group(4, 8), Element("Fe"));
            testCase.verifyEqual( ...
                Element.from_row_and_group(8, 3), Element("La"));
            testCase.verifyTrue(Element.is_valid_symbol("Fe"));
            testCase.verifyFalse(Element.is_valid_symbol("X"));
            table = Element.print_periodic_table(@(item) item.Z <= 2);
            rows = splitlines(table);
            testCase.verifyTrue(startsWith(rows(1), "H"));
            testCase.verifyTrue(contains(rows(1), "He"));
            testCase.verifyEqual(numel(rows), 10);
        end

        function speciesMethodsMatchFrozenOracle(testCase)
            import kssolv.analysis.matgenlab.core.Species
            lithium = Species.from_str("Li+");
            testCase.verifyEqual(lithium.element.symbol, "Li");
            testCase.verifyEqual(lithium.oxi_state, 1);
            testCase.verifyTrue(isnan(lithium.spin));
            testCase.verifyEqual(lithium.electronic_structure, "1s2");
            testCase.verifyEqual(lithium.full_electronic_structure, ...
                {1, "s", 2});
            testCase.verifyEqual(lithium.n_electrons, 2);
            testCase.verifyEqual(lithium.valence, [0, 2]);
            testCase.verifyEqual(lithium.ionic_radius, 0.9);
            testCase.verifyEqual(lithium.to_pretty_string(), "Li+");
            testCase.verifyEqual( ...
                Species.from_dict(lithium.as_dict()).to_pretty_string(), ...
                "Li+");

            iron = Species("Fe", 3, "spin", 5);
            testCase.verifyEqual(iron.get_nmr_quadrupole_moment(), 160);
            testCase.verifyEqual( ...
                iron.get_shannon_radius("VI", "High Spin"), 0.645);
            testCase.verifyEqual( ...
                iron.get_shannon_radius("VI", "Low Spin"), 0.55);
            testCase.verifyEqual( ...
                iron.get_crystal_field_spin("oct", "high"), 5);
            testCase.verifyEqual( ...
                iron.get_crystal_field_spin("oct", "low"), 1);
            testCase.verifyEqual(iron.to_pretty_string(), "Fe3+");
        end

        function dummyAliasesAndCoercion(testCase)
            import kssolv.analysis.matgenlab.core.*
            dummy = DummySpecies.from_str("X2-");
            testCase.verifyEqual(dummy.A, NaN);
            testCase.verifyEqual(dummy.oxi_state, -2);
            testCase.verifyEqual(dummy.X, 0);
            testCase.verifyEqual(dummy.symbol, "X");
            testCase.verifyEqual(string(dummy), "X2-");
            testCase.verifyEqual( ...
                string(DummySpecies.from_dict(dummy.as_dict())), "X2-");
            testCase.verifyClass(Specie("Fe", 2), ...
                "kssolv.analysis.matgenlab.core.Specie");
            testCase.verifyClass(DummySpecie("X"), ...
                "kssolv.analysis.matgenlab.core.DummySpecie");
            converted = {get_el_sp(26), get_el_sp("Fe"), ...
                get_el_sp("Fe2+"), get_el_sp("X2-")};
            expected = ["Element", "Element", "Species", "DummySpecies"];
            for index = 1:numel(converted)
                parts = split(string(class(converted{index})), ".");
                testCase.verifyEqual(parts(end), expected(index));
            end
        end

        function frozenApiSurfaceIsPresent(testCase)
            element = meta.class.fromName( ...
                "kssolv.analysis.matgenlab.core.ElementBase");
            properties = ["X", "atomic_radius", "atomic_mass", ...
                "atomic_mass_number", "atomic_orbitals_eV", "data", ...
                "ionization_energy", "electron_affinity", ...
                "electronic_structure", "average_ionic_radius", ...
                "average_cationic_radius", "average_anionic_radius", ...
                "ionic_radii", "number", "max_oxidation_state", ...
                "min_oxidation_state", "oxidation_states", ...
                "common_oxidation_states", "icsd_oxidation_states", ...
                "full_electronic_structure", "n_electrons", "valence", ...
                "term_symbols", "ground_state_term_symbol", "row", ...
                "group", "block", "is_noble_gas", ...
                "is_transition_metal", "is_post_transition_metal", ...
                "is_rare_earth", "is_metal", "is_metalloid", ...
                "is_alkali", "is_alkaline", "is_halogen", ...
                "is_chalcogen", "is_lanthanoid", "is_actinoid", ...
                "is_radioactive", "is_quadrupolar", ...
                "nmr_quadrupole_moment", "iupac_ordering"];
            testCase.verifyTrue(all(ismember(properties, ...
                string({element.PropertyList.Name}))));
            methods = ["from_Z", "from_name", "from_row_and_group", ...
                "is_valid_symbol", "as_dict", "from_dict", ...
                "print_periodic_table"];
            testCase.verifyTrue(all(ismember(methods, ...
                string({element.MethodList.Name}))));
        end
    end
end
