classdef PhysicalCoreParityTest < matlab.unittest.TestCase
    % Live differential checks against pymatgen-core v2026.7.24.

    methods (Test)
        function constantsAndUnits(testCase)
            testCase.requireOracle();
            constantRequest = struct( ...
                "module","pymatgen.core.constants", ...
                "symbol","value", ...
                "operations",{{struct( ...
                    "kind","call","args",{{"Bohr radius"}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(constantRequest);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.Constants. ...
                value("Bohr radius"), ...
                reference.results,RelTol=1e-15);

            unitRequest = struct( ...
                "module","pymatgen.core.units", ...
                "symbol","Unit", ...
                "construct",struct("args",{{"Ha bohr^-2"}}), ...
                "operations",{{struct( ...
                    "kind","call","name","get_conversion_factor", ...
                    "args",{{"J m^-2"}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(unitRequest);
            actual = kssolv.analysis.matgenlab.core.Unit( ...
                "Ha bohr^-2").get_conversion_factor("J m^-2");
            testCase.verifyEqual(actual,reference.results,RelTol=2e-15);
        end

        function spectrumSmearing(testCase)
            testCase.requireOracle();
            x = linspace(-2,2,11);
            y = zeros(1,11)+1e-20;
            y(6) = 1;
            operations = { ...
                struct("kind","call","name","smear","args",{{0.3}}, ...
                    "kwargs",struct("func","gaussian")), ...
                struct("kind","get","name","y")};
            request = struct( ...
                "module","pymatgen.core.spectrum", ...
                "symbol","Spectrum", ...
                "construct",struct("args",{{x,y}}), ...
                "operations",{operations});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            actual = kssolv.analysis.matgenlab.core.Spectrum(x,y);
            actual.smear(0.3);
            testCase.verifyEqual(actual.y,reference.results{2}, ...
                AbsTol=5e-15);

            operations{1}.kwargs.func = "lorentzian";
            request.operations = operations;
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            actual = kssolv.analysis.matgenlab.core.Spectrum(x,y);
            actual.smear(0.3,"lorentzian");
            testCase.verifyEqual(actual.y,reference.results{2}, ...
                AbsTol=5e-15);
        end

        function tensorVoigtProjectionAndRotation(testCase)
            testCase.requireOracle();
            voigt = [1,2,3,4,5,6];
            operations = { ...
                struct("kind","get","name","voigt"), ...
                struct("kind","call","name","project", ...
                    "args",{{[1,1,1]}}), ...
                struct("kind","get","name","principal_invariants"), ...
                struct("kind","call","name","rotate", ...
                    "args",{{[0,-1,0;1,0,0;0,0,1]}})};
            request = struct( ...
                "module","pymatgen.core.tensors", ...
                "symbol","SquareTensor", ...
                "construct",struct("method","from_voigt", ...
                    "args",{{voigt}}), ...
                "operations",{operations});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            actual = ...
                kssolv.analysis.matgenlab.core.SquareTensor. ...
                from_voigt(voigt);
            testCase.verifyEqual(actual.voigt, ...
                reshape(reference.results{1},1,[]),AbsTol=1e-14);
            testCase.verifyEqual(actual.project([1,1,1]), ...
                reference.results{2},AbsTol=1e-14);
            testCase.verifyEqual(actual.principal_invariants, ...
                reshape(reference.results{3},1,[]),AbsTol=1e-13);
            rotated = actual.rotate([0,-1,0;1,0,0;0,0,1]);
            testCase.verifyEqual(double(rotated),reference.results{4}, ...
                AbsTol=1e-14);
        end

        function tensorStructureFit(testCase)
            testCase.requireOracle();
            testCase.assumeTrue(spglibAvailable(), ...
                "The bundled spglib MEX is unavailable in this MATLAB runtime.");
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                3*eye(3),{"Si"},[0,0,0]);
            values = [1,2,3;2,4,5;3,5,6];
            request = struct( ...
                "module","pymatgen.core.tensors", ...
                "symbol","Tensor", ...
                "construct",struct("args",{{values}}), ...
                "operations",{{struct( ...
                    "kind","call","name","fit_to_structure", ...
                    "args",{{structure.as_dict()}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            actual = kssolv.analysis.matgenlab.core.Tensor(values);
            fitted = actual.fit_to_structure(structure);
            testCase.verifyEqual(double(fitted),squeeze(reference.results), ...
                AbsTol=1e-13);
        end
    end

    methods (Access = private)
        function requireOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable(), ...
                "Pinned pymatgen reference environment is unavailable.");
        end
    end
end

function available = spglibAvailable()
try
    kssolv.analysis.spglib.Spglib.getVersion();
    available = true;
catch
    available = false;
end
end
