classdef SiteParityTest < matlab.unittest.TestCase
    methods (Test)
        function siteMatchesPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.sites", ...
                "symbol", "Site", ...
                "construct", struct( ...
                    "args", {{struct("Fe", 0.5, "Mn", 0.5), ...
                    [0.25, 0.35, 0.45]}}), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "species_string"), ...
                    struct("kind", "get", "name", "is_ordered"), ...
                    struct("kind", "call", "name", "distance_from_point", ...
                        "args", {{[0, 0, 0]}}) ...
                    }});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            site = kssolv.analysis.matgenlab.core.Site( ...
                struct("Fe", 0.5, "Mn", 0.5), [0.25, 0.35, 0.45]);

            testCase.verifyEqual(site.species_string, ...
                string(reference.results{1}));
            testCase.verifyEqual(site.is_ordered, reference.results{2});
            testCase.verifyEqual(site.distance_from_point([0, 0, 0]), ...
                reference.results{3}, AbsTol = 1e-12);
        end

        function periodicSiteMatchesPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            lattice = struct( ...
                "x_module", "pymatgen.core.lattice", ...
                "x_class", "Lattice", ...
                "matrix", 10 * eye(3), ...
                "pbc", [true, true, true]);
            % Restore reserved MSON names in the request JSON explicitly.
            request = struct( ...
                "module", "pymatgen.core.sites", ...
                "symbol", "PeriodicSite", ...
                "construct", struct( ...
                    "args", {{"Fe", [0.25, 0.35, 0.45], lattice}}), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "coords"), ...
                    struct("kind", "call", ...
                        "name", "distance_and_image_from_frac_coords", ...
                        "args", {{[0, 0, 0]}}) ...
                    }});
            % PymatgenOracle uses jsonencode, so metadata-safe field names
            % need to be replaced before the runner sees the request.
            request.construct.args{3} = struct( ...
                "x_module", lattice.x_module, "x_class", lattice.x_class, ...
                "matrix", lattice.matrix, "pbc", lattice.pbc);
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);

            site = kssolv.analysis.matgenlab.core.PeriodicSite( ...
                "Fe", [0.25, 0.35, 0.45], ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(10));
            testCase.verifyEqual(site.coords, ...
                reshape(reference.results{1}, 1, 3), AbsTol = 1e-12);
            [distance, image] = ...
                site.distance_and_image_from_frac_coords([0, 0, 0]);
            testCase.verifyEqual(distance, reference.results{2}{1}, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(image, ...
                reshape(reference.results{2}{2}, 1, 3));
        end
    end
end
