classdef StructureAnalyzerTest < matlab.unittest.TestCase
    methods (Test)
        function officialVoronoiSpectrumAndCoordination(testCase)
            path="/tmp/matgenlab-plan.tMNeV8/pymatgen-2026.5.4/" + ...
                "test-files/io/vasp/outputs/XDATCAR.MD";
            testCase.assumeTrue(isfile(path), ...
                "Frozen XDATCAR fixture unavailable.");
            trajectory=kssolv.analysis.matgenlab.io.vasp.Xdatcar(path);
            analyzer=kssolv.analysis.matgenlab.core.VoronoiAnalyzer(4);
            testCase.verifyEqual( ...
                analyzer.analyze(trajectory.structures{2},6), ...
                [4,3,3,4,2,2,1,0]);
            ensemble=analyzer.analyze_structures( ...
                trajectory.structures,2,10);
            testCase.verifyTrue(any(strcmp(ensemble(:,1), ...
                '[1 3 4 7 1 0 0 0]') & cell2mat(ensemble(:,2))==3));
            coordination=kssolv.analysis.matgenlab.core. ...
                average_coordination_number(trajectory.structures,1);
            testCase.verifyEqual(coordination.Fe, ...
                4.771903318390836,AbsTol=1e-12);
        end

        function officialConnectivity(testCase)
            fixture=fullfile(fileparts(fileparts(mfilename("fullpath"))), ...
                "+fixtures","LiFePO4.json");
            structure=kssolv.analysis.matgenlab.core.Structure. ...
                from_dict(jsondecode(fileread(fixture)));
            connectivity=kssolv.analysis.matgenlab.core. ...
                VoronoiConnectivity(structure);
            array=connectivity.connectivity_array;
            center=(size(array,3)+1)/2;
            testCase.verifyEqual(reshape(array(16,1:4,center),1,[]), ...
                [0,1.96338392,0,.04594495],AbsTol=1e-8);
            testCase.verifyEqual( ...
                reshape(array(2,end-2:end,52),1,[]),zeros(1,3));
            site=connectivity.get_sitej(28,52);
            testCase.verifyEqual(site.specie.symbol,"O");
            testCase.verifyEqual(site.frac_coords, ...
                [-.29158,.74889,.95684],AbsTol=1e-8);
        end

        function bondLengthsAndPlot(testCase)
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(5), ...
                {'Li','O'},[0,0,0;.5,.5,.5]);
            lengths=kssolv.analysis.matgenlab.core. ...
                get_max_bond_lengths(structure);
            testCase.verifyEqual(lengths("Li|O"),1.81);
            axesHandle=kssolv.analysis.matgenlab.core. ...
                VoronoiAnalyzer.plot_vor_analysis( ...
                {'[0 6 0 8 0 0 0 0]',10;'[0 4 4 4 0 0 0 0]',2});
            cleanup=onCleanup(@()close(ancestor(axesHandle,"figure")));
            testCase.verifyClass(axesHandle,"matlab.graphics.axis.Axes");
            clear cleanup
        end
    end
end
