classdef StructureParityTest < matlab.unittest.TestCase
    methods (Test)
        function structureCoreValuesMatchPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            lattice = struct( ...
                "x_module", "pymatgen.core.lattice", ...
                "x_class", "Lattice", ...
                "matrix", 3 * eye(3), ...
                "pbc", [true, true, true]);
            request = struct( ...
                "module", "pymatgen.core.structure", ...
                "symbol", "Structure", ...
                "construct", struct("args", {{ ...
                    lattice, ["Na", "Cl"], [0, 0, 0; 0.5, 0.5, 0.5]}}), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "distance_matrix"), ...
                    struct("kind", "get", "name", "density"), ...
                    struct("kind", "get", "name", "formula") ...
                    }});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            actual = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
                ["Na", "Cl"], [0, 0, 0; 0.5, 0.5, 0.5]);

            testCase.verifyEqual(actual.distance_matrix, ...
                reference.results{1}, AbsTol = 1e-12);
            testCase.verifyEqual(actual.density, ...
                reference.results{2}, AbsTol = 1e-10);
            testCase.verifyEqual(actual.formula, string(reference.results{3}));
        end

        function moleculeCoreValuesMatchPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.structure", ...
                "symbol", "Molecule", ...
                "construct", struct("args", {{ ...
                    ["O", "H", "H"], ...
                    [0, 0, 0; 0.9572, 0, 0; -0.239, 0.927, 0]}}), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "center_of_mass"), ...
                    struct("kind", "get", "name", "nelectrons"), ...
                    struct("kind", "get", "name", "spin_multiplicity") ...
                    }});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            actual = kssolv.analysis.matgenlab.core.Molecule( ...
                ["O", "H", "H"], ...
                [0, 0, 0; 0.9572, 0, 0; -0.239, 0.927, 0]);

            testCase.verifyEqual(actual.center_of_mass, ...
                reshape(reference.results{1}, 1, 3), AbsTol = 1e-12);
            testCase.verifyEqual(actual.nelectrons, reference.results{2});
            testCase.verifyEqual(actual.spin_multiplicity, reference.results{3});
        end
    end
end
