classdef StructureMatcherTest < matlab.unittest.TestCase
    methods (Test)
        function linearAssignmentAndBoundary(testCase)
            costs=[ ...
                19,95,9,43,62,90,10,77,71,27; ...
                26,30,88,78,87,2,14,71,78,11; ...
                48,70,26,82,32,16,36,26,42,79; ...
                47,46,93,66,38,20,73,39,55,51; ...
                1,81,31,49,20,24,95,80,82,11; ...
                81,48,35,54,35,55,27,87,96,7; ...
                42,17,60,73,37,36,79,3,60,82; ...
                14,57,23,69,93,78,56,49,83,36; ...
                11,37,24,70,62,35,64,18,99,20; ...
                73,11,98,50,19,96,61,73,98,14];
            [solution,cost]=kssolv.analysis.matgenlab.core. ...
                get_linear_assignment_solution(costs);
            oracle=testCase.loadOracle();
            testCase.verifyEqual(cost, ...
                oracle.linear_assignment_min_costs(1));
            testCase.verifyEqual(numel(unique(solution)),10);
            booleanCosts=true(135);
            booleanCosts(1:136:end)=false;
            [solution,cost]=kssolv.analysis.matgenlab.core. ...
                get_linear_assignment_solution(booleanCosts);
            testCase.verifyEqual(solution,1:135);
            testCase.verifyEqual(cost,0);
            testCase.verifyError(@()kssolv.analysis.matgenlab.core. ...
                get_linear_assignment_solution(ones(3,2)), ...
                "KSSOLV:Matgenlab:LinearAssignment:Rectangular");
            testCase.verifyError(@()kssolv.analysis.matgenlab.core. ...
                get_linear_assignment_solution([0,NaN]), ...
                "KSSOLV:Matgenlab:LinearAssignment:NaN");
        end

        function comparatorSemanticsAndAbstractErrors(testCase)
            import kssolv.analysis.matgenlab.core.*
            iron2=Composition({Species("Fe",2),1});
            iron3=Composition({Species("Fe",3),1});
            testCase.verifyFalse(SpeciesComparator(). ...
                are_equal(iron2,iron3));
            testCase.verifyTrue(ElementComparator(). ...
                are_equal(iron2,iron3));
            spinUp=Composition({Species("Fe",2,"spin",4),1});
            spinDown=Composition({Species("Fe",2,"spin",-4),1});
            testCase.verifyTrue(SpinComparator(). ...
                are_equal(spinUp,spinDown));
            testCase.verifyFalse(SpinComparator(). ...
                are_equal(spinUp,spinUp));
            mixed=Composition(struct("Na",.6,"K",.4));
            anonymous=Composition(struct("Xa",.4,"Xb",.6));
            unequal=Composition(struct("Xa",.5,"Xb",.5));
            testCase.verifyTrue(OccupancyComparator(). ...
                are_equal(mixed,anonymous));
            testCase.verifyFalse(OccupancyComparator(). ...
                are_equal(mixed,unequal));
            testCase.verifyTrue(OrderDisorderElementComparator(). ...
                are_equal(Composition("Na"),Composition("NaCl")));
            testCase.verifyTrue(FrameworkComparator(). ...
                are_equal(iron2,Composition("O2")));
            testCase.verifyEqual(FrameworkComparator(). ...
                get_hash(Composition("O2")),1);
            abstract=AbstractComparator();
            testCase.verifyError(@()abstract.are_equal(iron2,iron3), ...
                "KSSOLV:Matgenlab:Comparator:Abstract");
            testCase.verifyError(@()abstract.get_hash(iron2), ...
                "KSSOLV:Matgenlab:Comparator:Abstract");
            invalid=struct("x_class","NotAComparator");
            testCase.verifyError(@()AbstractComparator.from_dict(invalid), ...
                "KSSOLV:Matgenlab:Comparator:Dictionary");
        end

        function comparatorsAndMsonRoundTrip(testCase)
            comparators = { ...
                kssolv.analysis.matgenlab.core.SpeciesComparator(), ...
                kssolv.analysis.matgenlab.core.ElementComparator(), ...
                kssolv.analysis.matgenlab.core.FrameworkComparator(), ...
                kssolv.analysis.matgenlab.core. ...
                    OrderDisorderElementComparator(), ...
                kssolv.analysis.matgenlab.core.OccupancyComparator(), ...
                kssolv.analysis.matgenlab.core.SpinComparator()};
            for index = 1:numel(comparators)
                restored = kssolv.analysis.matgenlab.core. ...
                    AbstractComparator.from_dict( ...
                    comparators{index}.as_dict());
                testCase.verifyClass(restored, class(comparators{index}));
            end

            matcher = kssolv.analysis.matgenlab.core.StructureMatcher( ...
                0.1, 0.2, 2, false, false, false, false, ...
                kssolv.analysis.matgenlab.core.FrameworkComparator(), ...
                "num_sites", strings(1, 0));
            restored = kssolv.analysis.matgenlab.core.StructureMatcher. ...
                from_dict(matcher.as_dict());
            testCase.verifyEqual(restored.as_dict(), matcher.as_dict());
        end

        function fitRmsGroupingAndAnonymousMapping(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice.cubic(4);
            first = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, ["Na", "Cl"], [0, 0, 0; .5, .5, .5]);
            shifted = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, ["Cl", "Na"], ...
                [.6, .5, .5; .1, 0, 0]);
            anonymous = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, ["K", "Br"], [0, 0, 0; .5, .5, .5]);
            matcher = kssolv.analysis.matgenlab.core.StructureMatcher();

            testCase.verifyTrue(matcher.fit(first, shifted));
            testCase.verifyEqual(matcher.get_rms_dist(first, shifted), ...
                [0, 0], AbsTol = 1e-12);
            testCase.verifyTrue(matcher.fit_anonymous(first, anonymous));
            [rmsd, mapping] = matcher.get_rms_anonymous( ...
                first, anonymous);
            testCase.verifyEqual(rmsd, 0, AbsTol = 1e-12);
            testCase.verifyNotEmpty(mapping);
            groups = matcher.group_structures( ...
                {first, shifted, anonymous});
            testCase.verifyEqual(cellfun(@numel, groups), [2, 1]);
        end

        function officialSupercellFixtureMatchesOracle(testCase)
            testCase.assumeTrue(isfolder(testCase.fixtureRoot()), ...
                "Official pymatgen structure_matcher fixtures unavailable.");
            primitive = testCase.loadStructure("Al3F9.json");
            distorted = testCase.loadStructure("Al3F9_distorted.json");
            noSupercell = ...
                kssolv.analysis.matgenlab.core.StructureMatcher( ...
                .2, .3, 5, true, true, false, false, [], ...
                "num_sites", strings(1, 0));
            testCase.verifyFalse(noSupercell.fit(primitive, distorted));

            matcher = kssolv.analysis.matgenlab.core.StructureMatcher( ...
                .2, .3, 5, true, true, true, false, [], ...
                "num_sites", strings(1, 0));
            testCase.verifyTrue(matcher.fit(primitive, distorted));
            testCase.verifyTrue(matcher.fit(distorted, primitive));
            oracle=testCase.loadOracle();
            testCase.verifyEqual( ...
                matcher.get_rms_dist(primitive, distorted), ...
                reshape(oracle.supercell_rms,1,[]), ...
                AbsTol = 1e-12);

            transformMatcher = ...
                kssolv.analysis.matgenlab.core.StructureMatcher( ...
                .2, .3, 5, false, true, true, false, [], ...
                "num_sites", strings(1, 0));
            [matrix, translation, mapping] = ...
                transformMatcher.get_transformation( ...
                distorted, primitive);
            testCase.verifyEqual(matrix,oracle.supercell_matrix);
            testCase.verifyEqual(translation, ...
                reshape(oracle.supercell_translation,1,[]), ...
                AbsTol = 1e-8);
            testCase.verifyEqual(mapping, ...
                reshape(oracle.supercell_mapping_matlab,1,[]));
            transformed = transformMatcher.get_s2_like_s1( ...
                distorted, primitive);
            testCase.verifyTrue( ...
                transformMatcher.fit(distorted, transformed));
        end

        function officialAnonymousFixtureMatchesOracle(testCase)
            testCase.assumeTrue(isfolder(testCase.fixtureRoot()), ...
                "Official pymatgen structure_matcher fixtures unavailable.");
            first = testCase.loadStructure("Na2Fe2PAsO4S4.json");
            second = testCase.loadStructure("Na2Fe2PNO4Se4.json");
            matcher = kssolv.analysis.matgenlab.core.StructureMatcher();
            mappings = matcher.get_all_anonymous_mappings( ...
                first, second, true, true);
            testCase.verifyNumElements(mappings, 2);
            distances = sort(cellfun(@(item) item{2}, mappings));
            oracle=testCase.loadOracle();
            testCase.verifyEqual(distances, ...
                reshape(oracle.anonymous_max_distances,1,[]), ...
                AbsTol = 1e-12);
            best = matcher. ...
                get_best_electronegativity_anonymous_mapping( ...
                first, second);
            testCase.verifyEqual(best.As, "N");
            testCase.verifyEqual(best.S, "Se");
        end

        function mappingAndTransformationUseMatlabIndices(testCase)
            lattice = ...
                kssolv.analysis.matgenlab.core.Lattice.orthorhombic( ...
                1, 2, 3);
            superset = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, ["Ag", "Si", "Si"], ...
                [.7, .4, .5; 0, 0, .1; 0, 0, .2]);
            subset = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, ["Si", "Ag"], ...
                [0, 0, .1; .7, .4, .5]);
            matcher = kssolv.analysis.matgenlab.core.StructureMatcher( ...
                .2, .3, 5, false, true, false, true);
            mapping = matcher.get_mapping(superset, subset);
            testCase.verifyEqual(mapping, [2, 1]);
            testCase.verifyGreaterThanOrEqual(mapping, ones(size(mapping)));
        end

        function combinedSubsetSupercellSizeModes(testCase)
            import kssolv.analysis.matgenlab.core.*
            primitiveLattice=Lattice.orthorhombic(10,20,30);
            primitive=Structure(primitiveLattice, ...
                {struct("Na",.5),struct("Cl",.5)}, ...
                [0,0,0;.5,.5,.5]);
            superLattice=Lattice.orthorhombic(20,20,30);
            supercell=Structure(superLattice,{"Na","Cl"}, ...
                [0,0,0;.75,.5,.5]);
            supercell=supercell*[-1,1,0;0,1,1;1,0,0];
            atoms=StructureMatcher(.2,.3,5,false,true,true,true, ...
                OrderDisorderElementComparator(),"num_atoms", ...
                strings(1,0));
            sites=StructureMatcher(.2,.3,5,false,true,true,true, ...
                OrderDisorderElementComparator(),"num_sites", ...
                strings(1,0));
            testCase.verifyTrue(atoms.fit(primitive,supercell));
            testCase.verifyFalse(sites.fit(primitive,supercell));
            testCase.verifyError(@()atoms.get_s2_like_s1( ...
                primitive,supercell), ...
                "KSSOLV:Matgenlab:StructureMatcher:TransformationOrder");
            transformed=atoms.get_s2_like_s1(supercell,primitive);
            testCase.verifyEqual(transformed.num_sites,4);
            testCase.verifyTrue(atoms.fit(supercell,transformed));
        end

        function ignoredSpeciesPrimitiveAndMinimax(testCase)
            import kssolv.analysis.matgenlab.core.*
            lattice=Lattice.orthorhombic(4,5,6);
            withLithium=Structure(lattice,{"Li","Fe","P","O"}, ...
                [.1,.1,.1;0,0,0;.5,0,0;0,.5,.5]);
            framework=Structure(lattice,{"Fe","P","O"}, ...
                [0,0,0;.5,0,0;0,.5,.5]);
            ignored=StructureMatcher(.2,.3,5,false,true,true,false, ...
                [],"num_sites","Li");
            testCase.verifyTrue(ignored.fit(withLithium,framework));
            testCase.verifyTrue(ignored.fit_anonymous( ...
                withLithium,framework));
            groups=ignored.group_structures({withLithium,framework});
            testCase.verifyNumElements(groups,1);
            doubled=withLithium*[2,0,0;0,1,0;0,0,1];
            restored=ignored.get_s2_like_s1( ...
                doubled,withLithium,true);
            testCase.verifyEqual(restored.reduced_formula,"LiFePO");
            testCase.verifyEqual(restored.num_sites,8);

            primitive=Structure(Lattice.cubic(4),{"Na","Cl"}, ...
                [0,0,0;.5,.5,.5]);
            supercell=primitive*[2,0,0;0,1,0;0,0,1];
            testCase.verifyTrue(StructureMatcher(). ...
                fit(primitive,supercell));

            minimax=StructureMatcher(.2,.301,1,false);
            longLattice=Lattice.orthorhombic(1,2,12);
            first=Structure(longLattice,{"Si","Si","Al"}, ...
                diag([.5,0,.5]));
            second=Structure(longLattice,{"Si","Si","Al"}, ...
                diag([.5,0,.6]));
            oracle=testCase.loadOracle();
            testCase.verifyEqual(minimax.get_rms_dist(first,second), ...
                reshape(oracle.rms_vs_minimax,1,[]),AbsTol=1e-12);
            testCase.verifyFalse(minimax.fit(first,second));
            testCase.verifyFalse(minimax.fit_anonymous(first,second));
        end

        function publicErrorBoundariesAndSiteOrder(testCase)
            import kssolv.analysis.matgenlab.core.*
            lattice=Lattice.cubic(3);
            first=Structure(lattice,{"Na","Cl"}, ...
                [0,0,0;.5,.5,.5]);
            second=Structure(lattice,{"Cl","Na"}, ...
                [.5,.5,.5;0,0,0]);
            ordered=SiteOrderedIStructure.from_sites(first);
            testCase.verifyEqual(ordered(1).species_string,"Na");
            testCase.verifyEqual(ordered(2).species_string,"Cl");
            primitiveMatcher=StructureMatcher();
            testCase.verifyError(@()primitiveMatcher. ...
                get_supercell_matrix(first,second), ...
                "KSSOLV:Matgenlab:StructureMatcher:PrimitiveOption");
            testCase.verifyError(@()primitiveMatcher. ...
                get_transformation(first,second), ...
                "KSSOLV:Matgenlab:StructureMatcher:PrimitiveOption");
            testCase.verifyError(@()primitiveMatcher. ...
                get_mapping(first,second), ...
                "KSSOLV:Matgenlab:StructureMatcher:MappingPrimitive");
            subsetMatcher=StructureMatcher(.2,.3,5,false,true, ...
                false,true);
            testCase.verifyError(@()subsetMatcher. ...
                get_mapping(first,first*[2,0,0;0,1,0;0,0,1]), ...
                "KSSOLV:Matgenlab:StructureMatcher:MappingSubset");
            groupingMatcher=StructureMatcher(.2,.3,5,false,true, ...
                false,true);
            testCase.verifyError(@()groupingMatcher. ...
                group_structures({first,second}), ...
                "KSSOLV:Matgenlab:StructureMatcher:SubsetGrouping");
        end
    end

    methods (Access = private)
        function structure = loadStructure(testCase, filename)
            value = jsondecode(fileread( ...
                fullfile(testCase.fixtureRoot(), filename)));
            structure = ...
                kssolv.analysis.matgenlab.core.Structure.from_dict(value);
        end

        function path = fixtureRoot(~)
            path = fullfile(fileparts(mfilename("fullpath")), ...
                "fixtures", "structure_matcher");
        end

        function value=loadOracle(~)
            root=fileparts(fileparts(fileparts(fileparts( ...
                fileparts(fileparts(mfilename("fullpath")))))));
            value=jsondecode(fileread(fullfile(root,"dev","matgenlab", ...
                "oracles","structure_matcher_2026.7.24.json")));
        end
    end
end
