classdef StructureInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function symmetricNeighborListMatchesFrozenPymatgen(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(1), ...
                {"Li"}, [0, 0, 0]);
            [center, point, offset, distance, symmetry, operations] = ...
                structure.get_symmetric_neighbor_list( ...
                1.01, "Pm-3m", true);
            % Frozen with pymatgen-core 2026.7.24.
            testCase.verifyEqual(center, ones(3, 1));
            testCase.verifyEqual(point, ones(3, 1));
            testCase.verifyEqual(sortrows(abs(offset)), sortrows(eye(3)));
            testCase.verifyEqual(distance, ones(3, 1), AbsTol = 1e-12);
            testCase.verifyEqual(symmetry, zeros(3, 1));
            testCase.verifyEqual(numel(operations), 3);
            testCase.verifyTrue(all(cellfun(@(operation) isa(operation, ...
                "kssolv.analysis.matgenlab.core.SymmOp"), operations)));
        end

        function sameCellOrderingAndExternalBoundary(testCase)
            disordered = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {{"Li", 0.5; "Na", 0.5}, ...
                {"Li", 0.5; "Na", 0.5}}, ...
                [0, 0, 0; 0.5, 0.5, 0.5]);
            values = disordered.get_orderings("enum", ...
                "deduplicate", false);
            testCase.verifyNumElements(values, 2);
            testCase.verifyTrue(all(cellfun(@(value) value.is_ordered, ...
                values)));
            supercellRequired = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {{"Li", 0.5; "Na", 0.5}}, [0, 0, 0]);
            testCase.verifyError(@() supercellRequired.get_orderings(), ...
                "KSSOLV:Matgenlab:External:EnumlibRequired");
            testCase.verifyError(@() disordered.get_orderings("sqs"), ...
                "KSSOLV:Matgenlab:External:McsqsRequired");
        end

        function matchAseAndCalculatorAdapters(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
                {"Si"}, [0, 0, 0]);
            testCase.verifyTrue(structure.matches(structure.copy()));
            atoms = structure.to_ase_atoms();
            roundTrip = kssolv.analysis.matgenlab.core.SiteCollection. ...
                from_ase_atoms(atoms);
            testCase.verifyTrue(structure.matches(roundTrip));
            result = structure.calculate( ...
                @(value) struct("sites", value.num_sites));
            testCase.verifyEqual(result.sites, 1);
            relaxed = structure.relax(@(value) value.scale_lattice(8));
            testCase.verifyEqual(relaxed.volume, 8, AbsTol = 1e-12);
            property = structure.calc_property("volume", ...
                @(value, name) struct(char(name), value.volume));
            testCase.verifyEqual(property.volume, 27, AbsTol = 1e-12);
            testCase.verifyError(@() structure.relax("FIRE"), ...
                "KSSOLV:Matgenlab:External:StructureRelaxer");
        end

        function functionalGroupSubstitution(testCase)
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                {"C", "H", "H", "H", "H"}, ...
                [0, 0, 0; 1, 0, 0; -1, 0, 0; ...
                0, 1, 0; 0, 0, 1]);
            substituted = molecule.substitute(2, "fluoro");
            testCase.verifyEqual(substituted.num_sites, 5);
            testCase.verifyEqual(substituted.composition("C"), 1);
            testCase.verifyEqual(substituted.composition("H"), 3);
            testCase.verifyEqual(substituted.composition("F"), 1);
            carbon = find(substituted.atomic_numbers == 6, 1);
            fluorine = find(substituted.atomic_numbers == 9, 1);
            expected = kssolv.analysis.matgenlab.core. ...
                get_bond_length("C", "F");
            testCase.verifyEqual( ...
                substituted.get_distance(carbon, fluorine), expected, ...
                AbsTol = 1e-10);
        end

        function magneticGroupFetcherAndTypedError(testCase)
            group = kssolv.analysis.matgenlab.symmetry.groups.SpaceGroup("P1");
            structure = kssolv.analysis.matgenlab.core.IStructure. ...
                from_magnetic_spacegroup(group, eye(3), {"Fe"}, ...
                [0, 0, 0], struct("magmom", 5));
            testCase.verifyEqual(structure.num_sites, 1);
            testCase.verifyClass(structure.site_properties.magmom{1}, ...
                "kssolv.analysis.matgenlab.electronic_structure.Magmom");
            fetched = kssolv.analysis.matgenlab.core.IStructure.from_id( ...
                "mock-1", "mock", "fetcher", @(~, ~) structure);
            testCase.verifyEqual(fetched, structure);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core.IStructure.from_id("mp-1"), ...
                "KSSOLV:Matgenlab:External:StructureFetcher");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.core.StructureError. ...
                throw("bad structure"), ...
                "KSSOLV:Matgenlab:StructureError");
        end

        function mutationAndDisorderEdgeCases(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice.cubic(3);
            disordered = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {{"Li", 0.5; "Na", 0.5}, "O"}, ...
                [0, 0, 0; 0.5, 0.5, 0.5], ...
                charge = 2, properties = struct("tag", 1), ...
                site_properties = struct("score", {{1, 2}}));
            copied = disordered.copy(struct("extra", {{3, 4}}));
            testCase.verifyEqual(copied.charge, 2);
            testCase.verifyTrue(isfield(copied.site_properties, "score"));
            testCase.verifyTrue(isfield(copied.site_properties, "extra"));
            sodiumOnly = disordered.remove_species("Li");
            testCase.verifyEqual(sodiumOnly.num_sites, 2);
            testCase.verifyEqual(sodiumOnly.composition("Na"), 0.5);
            subset = disordered.get_neighbor_list(10, ...
                sites = disordered.sites(1));
            testCase.verifyNotEmpty(subset);

            changed = disordered;
            changed.properties.label = "kept";
            testCase.verifyEqual(changed.properties.label, "kept");
            originalFractional = changed.frac_coords;
            changed.lattice = 2 * eye(3);
            testCase.verifyEqual(changed.frac_coords, originalFractional, ...
                AbsTol = 1e-12);
            strained = changed.apply_strain(diag([0.1, 0.2, 0.3]), false);
            testCase.verifyEqual(strained.lattice.lengths, ...
                [2.2, 2.4, 2.6], AbsTol = 1e-12);

            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                {{"Li", 0.5; "Na", 0.5}}, [0, 0, 0], ...
                charge_spin_check = false, ...
                properties = struct("name", "mixed"));
            testCase.verifyEqual(molecule.nelectrons, 7);
            testCase.verifyEqual(molecule.center_of_mass, [0, 0, 0]);
            molecule.properties.source = "native";
            testCase.verifyEqual(molecule.properties.source, "native");
            sodiumMolecule = molecule.remove_species("Li");
            testCase.verifyEqual(sodiumMolecule.composition("Na"), 0.5);
        end
    end
end
