classdef SubstitutionProbabilityTest < matlab.unittest.TestCase
    methods (Test)
        function customTableMatchesClosedForm(testCase)
            table = {"Na+", "K+", 1.25; "Na+", "Na+", 0.5; ...
                "K+", "K+", -0.25};
            model = kssolv.analysis.matgenlab.core. ...
                SubstitutionProbability(table, -5);
            testCase.verifyEqual(model.get_lambda("K+", "Na+"), 1.25);
            testCase.verifyEqual(model.get_lambda("Li+", "Na+"), -5);
            testCase.verifyEqual(model.prob("Na+", "K+"), ...
                exp(1.25) / model.Z, AbsTol=1e-15);
            testCase.verifyEqual(model.cond_prob_list( ...
                {"Na+", "K+"}, {"K+", "Na+"}), ...
                model.cond_prob("Na+", "K+") * ...
                model.cond_prob("K+", "Na+"), AbsTol=1e-15);
            testCase.verifyError(@() model.cond_prob_list({"Na+"}, ...
                {"Na+", "K+"}), ...
                "KSSOLV:Matgenlab:SubstitutionProbability:LengthMismatch");
        end

        function frozenDefaultMatchesPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable(), ...
                "Pinned pymatgen reference environment is unavailable.");
            model = kssolv.analysis.matgenlab.core.SubstitutionProbability();
            request = struct( ...
                "module", ...
                    "pymatgen.core.structure_prediction.substitution_probability", ...
                "symbol", "SubstitutionProbability", ...
                "construct", struct("args", {{}}), ...
                "operations", {{ ...
                    struct("kind", "call", "name", "get_lambda", ...
                        "args", {{"Na+", "K+"}}), ...
                    struct("kind", "call", "name", "prob", ...
                        "args", {{"Na+", "K+"}}), ...
                    struct("kind", "call", "name", "cond_prob", ...
                        "args", {{"Na+", "K+"}}), ...
                    struct("kind", "call", "name", "pair_corr", ...
                        "args", {{"Na+", "K+"}})}});
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            actual = [model.get_lambda("Na+", "K+"), ...
                model.prob("Na+", "K+"), model.cond_prob("Na+", "K+"), ...
                model.pair_corr("Na+", "K+")];
            testCase.verifyEqual(actual, reshape(response.results, 1, []), ...
                RelTol=1e-12, AbsTol=1e-15);
        end

        function predictorUsesProbabilityThreshold(testCase)
            table = {"Na+", "K+", 1.25; "Na+", "Na+", 0.5; ...
                "K+", "K+", -0.25};
            predictor = kssolv.analysis.matgenlab.core. ...
                SubstitutionPredictor(table, -5, 0);
            output = predictor.list_prediction({"Na+"});
            testCase.verifyEqual(numel(output), 2);
            testCase.verifyTrue(all([output.probability] > 0));
        end

        function msonRoundTrip(testCase)
            table = {"Na+", "K+", 1.25; "Na+", "Na+", 0.5};
            model = kssolv.analysis.matgenlab.core. ...
                SubstitutionProbability(table, -4);
            restored = kssolv.analysis.matgenlab.core. ...
                SubstitutionProbability.from_dict(model.as_dict());
            testCase.verifyEqual(restored.alpha, -4);
            testCase.verifyEqual(restored.get_lambda("Na+", "K+"), 1.25);
        end
    end
end
