classdef SurfaceInterfaceTest < matlab.unittest.TestCase
    methods (Test)
        function slabGeneratorMatchesFrozenOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            oracle=frozenOracle();
            bulk=Structure.from_spacegroup( ...
                "Fm-3m",Lattice.cubic(3),{"Fe"},[0,0,0]);
            actual=SlabGenerator(bulk,[1,1,1],10,10).get_slab();
            testCase.verifyClass(actual, ...
                "kssolv.analysis.matgenlab.core.Slab");
            testCase.verifyEqual(actual.lattice.matrix, ...
                oracle.slab.lattice,AbsTol=1e-12);
            testCase.verifyEqual(actual.frac_coords, ...
                oracle.slab.frac_coords,AbsTol=1e-12);
            testCase.verifyEqual(actual.surface_area, ...
                oracle.slab.surface_area,AbsTol=1e-12);
        end
        function interfaceFromSlabsMatchesFrozenOracle(testCase)
            import kssolv.analysis.matgenlab.core.*
            oracle=frozenOracle();
            lattice=Lattice([3,0,0;0,3,0;0,0,8]);
            substrate=Structure(lattice,{"Si","Si"}, ...
                [0,0,.2;.5,.5,.4]);
            film=Structure(lattice,{"O","O"},[0,0,.3;.5,.5,.5]);
            actual=Interface.from_slabs(substrate,film,gap=1.6, ...
                vacuum_over_film=4,center_slab=true);
            testCase.verifyEqual(actual.lattice.matrix, ...
                oracle.interface.lattice,AbsTol=1e-12);
            testCase.verifyEqual(actual.frac_coords, ...
                oracle.interface.frac_coords,AbsTol=1e-12);
            testCase.verifyEqual(actual.film_indices, ...
                transpose(oracle.interface.film_indices));
            testCase.verifyEqual(actual.substrate_indices, ...
                transpose(oracle.interface.substrate_indices));
        end
        function sigmaEnumerationsMatchOfficialFixtures(testCase)
            cubic=kssolv.analysis.matgenlab.core. ...
                GrainBoundaryGenerator.enum_sigma_cubic(50,[1,0,0]);
            hexagonal=kssolv.analysis.matgenlab.core. ...
                GrainBoundaryGenerator.enum_sigma_hex(50,[1,0,0],[8,3]);
            tetragonal=kssolv.analysis.matgenlab.core. ...
                GrainBoundaryGenerator.enum_sigma_tet(50,[1,0,0],[9,1]);
            orthorhombic=kssolv.analysis.matgenlab.core. ...
                GrainBoundaryGenerator.enum_sigma_ort( ...
                50,[1,0,0],[270,30,29]);
            rhombohedral=kssolv.analysis.matgenlab.core. ...
                GrainBoundaryGenerator.enum_sigma_rho( ...
                50,[1,0,0],[15,4]);
            testCase.verifyEqual(sort(cell2mat(keys(cubic))), ...
                [5,13,17,25,29,37,41]);
            testCase.verifyEqual(sort(cell2mat(keys(hexagonal))), ...
                [17,18,22,27,38,41]);
            testCase.verifyEqual(sort(cell2mat(keys(tetragonal))), ...
                [3,5,13,15,17,25,29,37,39,41]);
            testCase.verifyEqual(sort(cell2mat(keys(orthorhombic))), ...
                [3,5,13,15,17,25,29,37,39,41]);
            testCase.verifyEqual(sort(cell2mat(keys(rhombohedral))), ...
                [7,11,13,19,31,41,43,47]);
        end
        function sigmaFiveBoundaryCarriesCoreMetadata(testCase)
            import kssolv.analysis.matgenlab.core.*
            bulk=Structure.from_spacegroup( ...
                "Fm-3m",Lattice.cubic(2.8575585),{"Al"},[0,0,0]);
            generator=GrainBoundaryGenerator(bulk);
            boundary=generator.gb_from_parameters( ...
                [1,0,0],53.13010235415599,expand_times=3, ...
                normal=true,plane=[0,-1,-3],rm_ratio=.6);
            testCase.verifyClass(boundary, ...
                "kssolv.analysis.matgenlab.core.GrainBoundary");
            testCase.verifyEqual(boundary.sigma,5);
            testCase.verifyEqual(boundary.sigma_from_site_prop,5);
            testCase.verifyEqual( ...
                GrainBoundary.from_dict(boundary.as_dict()).sigma,5);
        end
    end
end

function value=frozenOracle()
root=fileparts(fileparts(fileparts(fileparts(fileparts( ...
    fileparts(mfilename("fullpath")))))));
value=jsondecode(fileread(fullfile(root,"dev","matgenlab","oracles", ...
    "surface_interface_2026.7.24.json")));
end
