classdef VolumePredictorTest < matlab.unittest.TestCase
    methods (Test)
        function referenceAtomicScalingMatchesOracle(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice.cubic(4);
            target = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"K", "Cl"}, [0, 0, 0; 0.5, 0.5, 0.5]);
            reference = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"Na", "Cl"}, [0, 0, 0; 0.5, 0.5, 0.5]);
            predictor = kssolv.analysis.matgenlab.core. ...
                RLSVolumePredictor(false, "atomic", false);
            actual = predictor.predict(target, reference);

            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", ...
                    "pymatgen.core.structure_prediction.volume_predictor", ...
                "symbol", "RLSVolumePredictor", ...
                "construct", struct("args", {{false, "atomic", false}}), ...
                "operations", {{struct("kind", "call", "name", "predict", ...
                    "args", {{target.as_dict(), reference.as_dict()}})}});
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            testCase.verifyEqual(actual, response.results(1), RelTol=1e-12);
        end

        function dataMinedScalingMatchesOracle(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice.cubic(5.6);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"Na", "Cl"}, [0, 0, 0; 0.5, 0.5, 0.5]);
            predictor = kssolv.analysis.matgenlab.core. ...
                DLSVolumePredictor(4, 0.5, 1.5);
            actual = predictor.predict(structure);

            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", ...
                    "pymatgen.core.structure_prediction.volume_predictor", ...
                "symbol", "DLSVolumePredictor", ...
                "construct", struct("args", {{4, 0.5, 1.5}}), ...
                "operations", {{struct("kind", "call", "name", "predict", ...
                    "args", {{structure.as_dict()}})}});
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            testCase.verifyEqual(actual, response.results(1), RelTol=1e-12);
            scaled = predictor.get_predicted_structure(structure);
            testCase.verifyEqual(scaled.volume, actual, RelTol=1e-12);
        end
    end
end
