classdef XcFuncTest < matlab.unittest.TestCase
    methods (Test)
        function libxcMetadata(testCase)
            pbe = kssolv.analysis.matgenlab.core.LibxcFunc("GGA_X_PBE");
            testCase.verifyEqual(pbe.value, 101);
            testCase.verifyEqual(pbe.kind, "EXCHANGE");
            testCase.verifyEqual(pbe.family, "GGA");
            testCase.verifyTrue(pbe.is_x_kind);
            testCase.verifyTrue(pbe.is_gga_family);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.LibxcFunc(101), pbe);
        end

        function aliasesAndAbinit(testCase)
            pbe = kssolv.analysis.matgenlab.core.XcFunc.from_name("PBE");
            testCase.verifyEqual(pbe.name, "PBE");
            testCase.verifyEqual(pbe.type, "GGA");
            testCase.verifyEqual(pbe.x.name, "GGA_X_PBE");
            testCase.verifyEqual(pbe.c.name, "GGA_C_PBE");
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.core.XcFunc.from_abinit_ixc(11), ...
                pbe);
            raw = kssolv.analysis.matgenlab.core.XcFunc.from_name( ...
                "LDA_XC_TETER93");
            testCase.verifyEqual(raw.name, "LDA_XC_TETER93");
        end

        function serializationRoundTrip(testCase)
            original = ...
                kssolv.analysis.matgenlab.core.XcFunc.from_name("BLYP");
            restored = ...
                kssolv.analysis.matgenlab.core.XcFunc.from_dict( ...
                    original.as_dict());
            testCase.verifyEqual(restored, original);
        end

        function matchesPymatgen(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.core.xcfunc", ...
                "symbol", "XcFunc", ...
                "construct", struct("method", "from_name", ...
                    "args", {{'PBE'}}), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "name"), ...
                    struct("kind", "get", "name", "type"), ...
                    struct("kind", "call", "name", "as_dict")}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);
            actual = ...
                kssolv.analysis.matgenlab.core.XcFunc.from_name("PBE");
            testCase.verifyEqual(actual.name, string(reference.results{1}));
            testCase.verifyEqual(actual.type, string(reference.results{2}));
            testCase.verifyEqual(actual.as_dict().x.name, ...
                string(reference.results{3}.x.name));
            testCase.verifyEqual(actual.as_dict().c.name, ...
                string(reference.results{3}.c.name));
        end
    end
end
