classdef CrystalSceneSerializer
    %CRYSTALSCENESERIALIZER Convert matgenlab values to uihtml-safe structs.
    methods (Static)
        function value = site(site, siteIndex, colorSchemes)
            [species, occupancies] = site.species.items();
            components = cell(1, numel(species));
            for index = 1:numel(species)
                components{index} = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer. ...
                    speciesComponent(species{index}, occupancies(index), ...
                    colorSchemes);
            end
            value = struct( ...
                "id", "site-" + string(siteIndex - 1), ...
                "siteIndex", siteIndex - 1, ...
                "label", string(site.label), ...
                "species", {components}, ...
                "fractional", reshape(double(site.frac_coords), 1, 3), ...
                "cartesian", reshape(double(site.coords), 1, 3), ...
                "magmom", ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.magmom(site));
        end

        function value = moleculeSite( ...
                site, siteIndex, colorSchemes, components)
            if nargin < 4
                [species, occupancies] = site.species.items();
                components = cell(1, numel(species));
                for index = 1:numel(species)
                    components{index} = ...
                        kssolv.ui.scene.atomic.CrystalSceneSerializer. ...
                        speciesComponent(species{index}, ...
                        occupancies(index), colorSchemes);
                end
            end
            value = struct( ...
                "id", "site-" + string(siteIndex - 1), ...
                "siteIndex", siteIndex - 1, ...
                "label", string(site.label), ...
                "species", {components}, ...
                "cartesian", reshape(double(site.coords), 1, 3));
        end

        function value = atom(siteIndex, image, position, visibility)
            image = round(reshape(double(image), 1, 3));
            imageText = join(string(image), ",");
            value = struct( ...
                "id", "site-" + string(siteIndex - 1) + "@" + imageText, ...
                "siteId", "site-" + string(siteIndex - 1), ...
                "siteIndex", siteIndex - 1, ...
                "imageOffset", image, ...
                "position", reshape(double(position), 1, 3), ...
                "visibility", string(visibility));
        end

        function value = relation(edge, relationIndex, structure)
            relativeImage = round(reshape(double(edge.to_jimage), 1, 3));
            start = structure(edge.from_index).coords;
            finish = structure.lattice.get_cartesian_coords( ...
                structure(edge.to_index).frac_coords + relativeImage);
            weight = edge.weight;
            if isempty(weight), weight = NaN; end
            value = struct( ...
                "id", "bond-relation-" + string(relationIndex - 1), ...
                "fromSiteIndex", edge.from_index - 1, ...
                "toSiteIndex", edge.to_index - 1, ...
                "relativeImage", relativeImage, ...
                "distance", norm(finish - start), ...
                "weight", double(weight));
        end

        function value = bond(relation, relationIndex, instanceIndex, ...
                fromImage, toImage, structure, visibility)
            fromImage = round(reshape(double(fromImage), 1, 3));
            toImage = round(reshape(double(toImage), 1, 3));
            fromSite = relation.fromSiteIndex + 1;
            toSite = relation.toSiteIndex + 1;
            start = structure.lattice.get_cartesian_coords( ...
                structure(fromSite).frac_coords + fromImage);
            finish = structure.lattice.get_cartesian_coords( ...
                structure(toSite).frac_coords + toImage);
            value = struct( ...
                "id", "bond-" + string(instanceIndex - 1), ...
                "relationId", "bond-relation-" + string(relationIndex - 1), ...
                "fromSiteIndex", fromSite - 1, ...
                "toSiteIndex", toSite - 1, ...
                "fromImage", fromImage, ...
                "toImage", toImage, ...
                "start", reshape(double(start), 1, 3), ...
                "end", reshape(double(finish), 1, 3), ...
                "distance", norm(finish - start), ...
                "visibility", string(visibility));
        end

        function value = polyhedron(identifier, centerIndex, center, ...
                vertices, colorValue, visibility)
            value = struct( ...
                "id", string(identifier), ...
                "centerSiteIndex", centerIndex - 1, ...
                "center", reshape(double(center), 1, 3), ...
                "vertices", double(vertices), ...
                "color", reshape(double(colorValue), 1, 3), ...
                "visibility", string(visibility));
        end

        function value = warning(code, message, severity, siteIndices)
            if nargin < 4, siteIndices = zeros(1, 0); end
            value = struct("code", string(code), ...
                "message", string(message), "severity", string(severity), ...
                "siteIndices", reshape(double(siteIndices), 1, []) - 1);
        end

        function value = transportScene(scene)
            %TRANSPORTSCENE Preserve scene arrays through jsonencode.
            %
            % MATLAB encodes a scalar struct as a JSON object, even when
            % that struct represents a one-element schema array. Wrapping
            % every top-level scene collection in a cell array keeps empty,
            % singleton, and multi-element payloads shape-stable for uihtml.
            value = scene;
            fields = ["sites", "atomInstances", "bondRelations", ...
                "bondInstances", "polyhedra"];
            for field = fields
                name = char(field);
                value.(name) = reshape(num2cell(scene.(name)), 1, []);
            end
            % Nested numeric singleton arrays have the same JSON ambiguity
            % as top-level singleton struct arrays. Keep the scientific
            % scene numeric, but make warning references shape-stable only
            % at the uihtml transport boundary.
            warnings=scene.warnings;
            for index=1:numel(warnings)
                warnings(index).siteIndices=num2cell(reshape( ...
                    double(warnings(index).siteIndices),1,[]));
            end
            value.warnings=reshape(num2cell(warnings),1,[]);
        end

        function value = modeling(scene, userFragments)
            %MODELING Serialize traceable interactive-modeling resources.
            arguments
                scene struct
                userFragments struct = struct([])
            end
            siteSymbols = strings(1, 0);
            for siteIndex = 1:numel(scene.sites)
                site = scene.sites(siteIndex);
                for speciesIndex = 1:numel(site.species)
                    if iscell(site.species)
                        species = site.species{speciesIndex};
                    else
                        species = site.species(speciesIndex);
                    end
                    siteSymbols(end + 1) = ...
                        string(species.symbol); %#ok<AGROW>
                end
            end
            constructionBonds = kssolv.modeling.forcefield. ...
                GeometryParameterProvider.constructionBonds(siteSymbols);
            value = struct( ...
                "adsorbateFragments", ...
                {reshape(num2cell(userFragments), 1, [])}, ...
                "constructionBonds", ...
                {reshape(num2cell(constructionBonds), 1, [])});
        end
    end

    methods (Static, Access = private)
        function value = speciesComponent(specie, occupancy, schemes)
            if isa(specie, "kssolv.analysis.matgenlab.core.Species")
                element = specie.element;
            else
                element = specie;
            end
            symbol = char(string(element.symbol));
            radius = element.atomic_radius;
            if isempty(radius) || ~isfinite(radius)
                radius = element.atomic_radius_calculated;
            end
            if isempty(radius) || ~isfinite(radius), radius = 0.8; end
            value = struct( ...
                "symbol", string(element.symbol), ...
                "occupancy", double(occupancy), ...
                "atomicNumber", double(element.Z), ...
                "colorVesta", ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer. ...
                    elementColor(schemes.VESTA, symbol), ...
                "colorJmol", ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer. ...
                    elementColor(schemes.Jmol, symbol), ...
                "atomicRadius", double(radius));
        end

        function value = elementColor(mapping, symbol)
            if isfield(mapping, symbol)
                value = reshape(double(mapping.(symbol)), 1, 3);
            else
                value = [190, 190, 190];
            end
        end

        function value = magmom(site)
            value = [0, 0, 0];
            if isfield(site.site_properties, "magmom")
                input = site.site_properties.magmom;
                if isscalar(input)
                    value = [0, 0, double(input)];
                elseif isnumeric(input) && numel(input) == 3
                    value = reshape(double(input), 1, 3);
                end
                return
            end
            if site.is_ordered && ...
                    isa(site.specie, ...
                    "kssolv.analysis.matgenlab.core.Species") && ...
                    isfinite(site.specie.spin)
                value = [0, 0, double(site.specie.spin)];
            end
        end
    end
end
