classdef MoleculeSceneBuilder
    %MOLECULESCENEBUILDER Compile a non-periodic matgenlab Molecule scene.
    methods (Static)
        function scene = build(molecule, options)
            arguments
                molecule (1,1) kssolv.analysis.matgenlab.core.IMolecule
                options.algorithm string = "Auto"
                options.includeConnectivity (1,1) logical = true
                options.requestId string = ""
            end
            started = tic;
            if molecule.num_sites > 64000
                error("KSSOLV:CrystalViewer:MoleculeLimit", ...
                    "Molecules above 64,000 atoms are not supported.");
            end
            requestId = string(options.requestId);
            if requestId == ""
                requestId = string(matlab.lang.internal.uuid);
            end
            warnings = warningArray();
            schemes = jsondecode(fileread(fullfile( ...
                KSSOLV_Toolbox.RootDirectory, "+kssolv", ...
                "+analysis", "+matgenlab", "+vis", ...
                "ElementColorSchemes.json")));

            siteCount = molecule.num_sites;
            sites = repmat(struct( ...
                "id", "", "siteIndex", 0, "label", "", ...
                "species", {cell(1, 0)}, ...
                "cartesian", zeros(1, 3)), 1, siteCount);
            atoms = repmat(struct( ...
                "id", "", "siteId", "", "siteIndex", 0, ...
                "imageOffset", zeros(1, 3), ...
                "position", zeros(1, 3), ...
                "visibility", ""), 1, siteCount);
            componentCache = containers.Map( ...
                "KeyType", "char", "ValueType", "any");
            coordinates = molecule.cart_coords;
            for index = 1:siteCount
                site = molecule(index);
                key = char(site.species_string);
                if isKey(componentCache, key)
                    serializedSite = ...
                        kssolv.ui.scene.atomic.CrystalSceneSerializer. ...
                        moleculeSite(site, index, schemes, ...
                        componentCache(key));
                else
                    serializedSite = ...
                        kssolv.ui.scene.atomic.CrystalSceneSerializer. ...
                        moleculeSite(site, index, schemes);
                    componentCache(key) = serializedSite.species;
                end
                sites(index) = serializedSite;
                atoms(index) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.atom( ...
                    index, [0, 0, 0], coordinates(index, :), "base");
            end

            relations = struct("id", {}, "fromSiteIndex", {}, ...
                "toSiteIndex", {}, "relativeImage", {}, "distance", {}, ...
                "weight", {}, "order", {}, "origin", {});
            bonds = struct("id", {}, "relationId", {}, ...
                "fromSiteIndex", {}, "toSiteIndex", {}, ...
                "fromImage", {}, "toImage", {}, "start", {}, "end", {}, ...
                "distance", {}, "visibility", {}, "order", {}, "origin", {});
            actualAlgorithm = "None";
            if options.includeConnectivity
                [graph, actualAlgorithm, graphWarnings] = ...
                    kssolv.ui.scene.atomic.MoleculeSceneBuilder. ...
                    buildGraph(molecule, options.algorithm);
                warnings = [warnings, graphWarnings];
                [relations, bonds] = ...
                    kssolv.ui.scene.atomic.MoleculeSceneBuilder. ...
                    graphScene(molecule, graph);
            else
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "CONNECTIVITY_DEFERRED", ...
                    "Atoms are available while molecular connectivity is computed.", ...
                    "info");
            end
            warnings = [warnings, ...
                kssolv.ui.scene.atomic.MoleculeSceneBuilder. ...
                diagnosticWarnings(molecule)];

            properties = molecule.properties;
            inputFormat = fieldText(properties, "input_format", "");
            frameIndex = fieldNumber(properties, "frame_index", 1);
            frameCount = fieldNumber(properties, "frame_count", 1);
            if frameCount > 1
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "MULTIFRAME_FIRST_FRAME", ...
                    "This input contains multiple frames; frame 1 is shown.", ...
                    "info");
            end
            matgenlabVersion = kssolv.analysis.matgenlab.version();
            scene = struct( ...
                "schemaVersion", "2.0", ...
                "kind", "molecule", ...
                "requestId", requestId, ...
                "molecule", struct( ...
                    "formula", ...
                        kssolv.ui.scene.atomic.MoleculeSceneBuilder. ...
                        structuralFormula(molecule), ...
                    "atomCount", molecule.num_sites, ...
                    "isOrdered", molecule.is_ordered, ...
                    "charge", double(molecule.charge), ...
                    "spinMultiplicity", double(molecule.spin_multiplicity), ...
                    "inputFormat", inputFormat, ...
                    "frameIndex", frameIndex, ...
                    "frameCount", frameCount), ...
                "sites", sites, ...
                "atomInstances", atoms, ...
                "bondRelations", relations, ...
                "bondInstances", bonds, ...
                "polyhedra", struct("id", {}, "centerSiteIndex", {}, ...
                    "center", {}, "vertices", {}, "color", {}, ...
                    "visibility", {}), ...
                "analysis", struct( ...
                    "algorithm", actualAlgorithm, ...
                    "parameters", struct( ...
                        "requestedAlgorithm", string(options.algorithm), ...
                        "includeConnectivity", options.includeConnectivity), ...
                    "source", "matgenlab", ...
                    "sourceVersion", "matgenlab-" + ...
                        string(matgenlabVersion.Version) + ...
                        "/pymatgen-" + ...
                        string(matgenlabVersion.PymatgenVersion), ...
                    "elapsedMilliseconds", toc(started) * 1000), ...
                "warnings", warnings);
            kssolv.ui.scene.atomic.CrystalSceneValidator.validate(scene);
        end
    end

    methods (Static, Access = private)
        function formula = structuralFormula(molecule)
            % reduced_formula applies elemental reference conventions (for
            % example, a one-atom O model becomes O2).  The viewer must show
            % the atoms actually present in the editable document instead.
            tokens = split(strtrim(string(molecule.formula)));
            tokens = regexprep(tokens, "(?<=[A-Za-z])1$", "");
            formula = join(tokens, "");
        end

        function [graph, algorithm, warnings] = ...
                buildGraph(molecule, requested)
            warnings = warningArray();
            requested = string(requested);
            topology = struct("bonds", zeros(0, 3), "origin", "none");
            properties = molecule.properties;
            if isfield(properties, "topology") && ...
                    isstruct(properties.topology)
                topology = properties.topology;
            end
            hasSource = isfield(topology, "bonds") && ...
                ~isempty(topology.bonds) && ...
                isfield(topology, "origin") && ...
                string(topology.origin) == "source";
            if requested == "Auto"
                if hasSource, requested = "Source";
                else, requested = "OpenBabelNN"; end
            end
            switch requested
                case "Source"
                    if ~hasSource
                        warnings(end + 1) = ...
                            kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                            "SOURCE_TOPOLOGY_UNAVAILABLE", ...
                            "The input has no explicit bond table; OpenBabelNN was used.", ...
                            "warning");
                    else
                        graph = kssolv.ui.scene.atomic.MoleculeSceneBuilder. ...
                            sourceGraph(molecule, topology.bonds);
                        algorithm = "Source";
                        return
                    end
                case "OpenBabelNN"
                otherwise
                    error("KSSOLV:CrystalViewer:MoleculeAlgorithm", ...
                        "Unsupported molecular bonding algorithm '%s'.", ...
                        requested);
            end
            [pairs, lengths, orders] = ...
                kssolv.analysis.matgenlab.core.OpenBabelNN(). ...
                get_bonds(molecule);
            graph = struct( ...
                "pairs", pairs, ...
                "lengths", lengths, ...
                "orders", orders, ...
                "origin", "OpenBabelNN");
            algorithm = "OpenBabelNN";
            if isfield(properties, "topology") && ...
                    isfield(properties.topology, "origin") && ...
                    string(properties.topology.origin) == "none"
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "BONDS_INFERRED", ...
                    "The input contains coordinates only; molecular bonds were inferred.", ...
                    "info");
            end
        end

        function graph = sourceGraph(molecule, bonds)
            graph = kssolv.analysis.matgenlab.core.MoleculeGraph. ...
                from_empty_graph(molecule, ...
                "edge_weight_name", "bond_order", ...
                "edge_weight_units", "");
            bonds = double(bonds);
            for index = 1:size(bonds, 1)
                first = bonds(index, 1);
                second = bonds(index, 2);
                order = bonds(index, 3);
                graph.add_edge(first, second, "weight", order, ...
                    "edge_properties", struct( ...
                    "origin", "source", ...
                    "bond_order", order, ...
                    "distance", molecule.get_distance(first, second)));
            end
        end

        function [relations, bonds] = graphScene(molecule, graph)
            if isstruct(graph) && isfield(graph, "pairs")
                edgeCount = size(graph.pairs, 1);
            else
                edgeCount = numel(graph.graph.edges);
            end
            relations = repmat(struct( ...
                "id", "", ...
                "fromSiteIndex", 0, ...
                "toSiteIndex", 0, ...
                "relativeImage", [0, 0, 0], ...
                "distance", 0, ...
                "weight", 0, ...
                "order", 0, ...
                "origin", ""), 1, edgeCount);
            bonds = repmat(struct( ...
                "id", "", ...
                "relationId", "", ...
                "fromSiteIndex", 0, ...
                "toSiteIndex", 0, ...
                "fromImage", [0, 0, 0], ...
                "toImage", [0, 0, 0], ...
                "start", [0, 0, 0], ...
                "end", [0, 0, 0], ...
                "distance", 0, ...
                "visibility", "", ...
                "order", 0, ...
                "origin", ""), 1, edgeCount);
            for index = 1:edgeCount
                if isstruct(graph) && isfield(graph, "pairs")
                    first = graph.pairs(index, 1);
                    second = graph.pairs(index, 2);
                    distance = graph.lengths(index);
                    order = graph.orders(index);
                    origin = string(graph.origin);
                else
                    edge = graph.graph.edges(index);
                    first = edge.from_index;
                    second = edge.to_index;
                    distance = molecule.get_distance(first, second);
                    order = edge.weight;
                    origin = "OpenBabelNN";
                    if isfield(edge.edge_properties, "origin")
                        origin = string(edge.edge_properties.origin);
                    end
                end
                if isempty(order) || ~isfinite(order), order = 1; end
                relationId = "bond-relation-" + string(index - 1);
                relations(index) = struct( ...
                    "id", relationId, ...
                    "fromSiteIndex", first - 1, ...
                    "toSiteIndex", second - 1, ...
                    "relativeImage", [0, 0, 0], ...
                    "distance", distance, ...
                    "weight", double(order), ...
                    "order", double(order), ...
                    "origin", origin);
                bonds(index) = struct( ...
                    "id", "bond-" + string(index - 1), ...
                    "relationId", relationId, ...
                    "fromSiteIndex", first - 1, ...
                    "toSiteIndex", second - 1, ...
                    "fromImage", [0, 0, 0], ...
                    "toImage", [0, 0, 0], ...
                    "start", reshape(double(molecule(first).coords), 1, 3), ...
                    "end", reshape(double(molecule(second).coords), 1, 3), ...
                    "distance", distance, ...
                    "visibility", "base", ...
                    "order", double(order), ...
                    "origin", origin);
            end
        end

        function warnings = diagnosticWarnings(molecule)
            warnings = warningArray();
            if molecule.num_sites > 500
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "MOLECULE_DIAGNOSTICS_DEFERRED", ...
                    "Real-time valence and collision diagnostics are " + ...
                    "deferred above 500 atoms; run Diagnose Molecule on demand.", ...
                    "info");
                return
            end
            try
                report = ...
                    kssolv.modeling.chemistry.MoleculeDiagnostics.inspect( ...
                    molecule);
            catch exception
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "MOLECULE_DIAGNOSTICS_UNAVAILABLE", ...
                    "Real-time molecular diagnostics are unavailable for " + ...
                    "this element combination; run Diagnose Molecule " + ...
                    "after supplying compatible bond data. (" + ...
                    string(exception.identifier) + ")", "warning");
                return
            end
            maximumDetails = 20;
            atomIssues = report.atomIssues;
            for index = 1:min(numel(atomIssues), maximumDetails)
                issue = atomIssues(index);
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    issue.code, issue.message, issue.severity, issue.siteIndex); %#ok<AGROW>
            end
            for index = 1:min(size(report.collisions, 1), maximumDetails)
                row = report.collisions(index, :);
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "ATOM_COLLISION", sprintf( ...
                    "Atoms %d and %d are only %.4g angstrom apart.", ...
                    row(1), row(2), row(3)), "error", row(1:2)); %#ok<AGROW>
            end
            for index = 1:min(size(report.abnormalBonds, 1), maximumDetails)
                row = report.abnormalBonds(index, :);
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "ABNORMAL_BOND_LENGTH", sprintf( ...
                    "Bond %d-%d is %.4g angstrom; rule estimate is %.4g.", ...
                    row(1), row(2), row(3), row(4)), ...
                    "warning", row(1:2)); %#ok<AGROW>
            end
            omitted = numel(atomIssues) + size(report.collisions, 1) + ...
                size(report.abnormalBonds, 1) - numel(warnings);
            if omitted > 0
                warnings(end + 1) = ...
                    kssolv.ui.scene.atomic.CrystalSceneSerializer.warning( ...
                    "MOLECULE_DIAGNOSTICS_SUMMARY", sprintf( ...
                    "%d additional molecular diagnostics are available " + ...
                    "from Diagnose Molecule.", omitted), "info");
            end
        end
    end
end

function value = warningArray()
value = struct("code", {}, "message", {}, "severity", {}, ...
    "siteIndices", {});
end

function value = fieldText(properties, name, fallback)
value = string(fallback);
if isfield(properties, name), value = string(properties.(name)); end
end

function value = fieldNumber(properties, name, fallback)
value = double(fallback);
if isfield(properties, name), value = double(properties.(name)); end
end
