function options = defaults()
%DEFAULTS Return the defaults used by m3g/packmol.
%
% The values mirror src/getinp.f90 at upstream commit 14e50c65.

options = struct( ...
    "seed", 1234567, ...
    "randominitialpoint", false, ...
    "check", false, ...
    "chkgrad", false, ...
    "discale", 1.1, ...
    "fbins", sqrt(3), ...
    "iprint1", 2, ...
    "iprint2", 2, ...
    "writeout", 10, ...
    "maxit", 20, ...
    "nloop", 0, ...
    "nloop0", 0, ...
    "movefrac", 0.05, ...
    "movebadrandom", false, ...
    "disable_movebad", false, ...
    "precision", 1.0e-2, ...
    "writebad", false, ...
    "sidemax", 1000, ...
    "avoid_overlap", true, ...
    "packall", false, ...
    "use_short_tol", false, ...
    "short_tol_dist", NaN, ...
    "short_tol_scale", 3, ...
    "add_amber_ter", false, ...
    "amber_ter_preserve", false, ...
    "add_box_sides", false, ...
    "add_box_sides_offset", 0, ...
    "crd", false, ...
    "crdfile", "", ...
    "hexadecimal_indices", false, ...
    "ignore_conect", false, ...
    "non_standard_conect", true, ...
    "filetype", "pdb", ...
    "output", "", ...
    "tolerance", NaN, ...
    "using_pbc", false, ...
    "pbc_min", zeros(1, 3), ...
    "pbc_max", zeros(1, 3), ...
    "restart_from", "none", ...
    "restart_to", "none");
end
