function [rotation, derivatives] = eulerrmat(beta, gamma, theta)
%EULERRMAT Packmol's movable-molecule Euler rotation matrix.
%
% beta rotates about y, gamma about z, and theta about x. This preserves
% src/polartocart.f90, including its historical angle convention.

cb = cos(beta); sb = sin(beta);
cg = cos(gamma); sg = sin(gamma);
ct = cos(theta); st = sin(theta);
rotation = [ ...
    -sb*sg*ct + cb*cg,  cb*sg*ct + sb*cg,  sg*st; ...
    -sb*cg*ct - cb*sg,  cb*cg*ct - sb*sg,  cg*st; ...
     sb*st,             -cb*st,             ct];
if nargout > 1
    derivatives = zeros(3, 3, 3);
    derivatives(:, :, 1) = [ ...
        -cb*sg*ct - sb*cg, -sb*sg*ct + cb*cg, 0; ...
        -cb*cg*ct + sb*sg, -sb*cg*ct - cb*sg, 0; ...
         cb*st,             sb*st,            0];
    derivatives(:, :, 2) = [ ...
        -sb*cg*ct - cb*sg,  cb*cg*ct - sb*sg,  cg*st; ...
         sb*sg*ct - cb*cg, -cb*sg*ct - sb*cg, -sg*st; ...
         0,                 0,                 0];
    derivatives(:, :, 3) = [ ...
         sb*sg*st, -cb*sg*st,  sg*ct; ...
         sb*cg*st, -cb*cg*st,  cg*ct; ...
         sb*ct,    -cb*ct,     -st];
end
end
