function codes = exit_codes()
%EXIT_CODES Return the public Packmol process exit-code constants.
codes = struct( ...
    "success", 0, ...
    "general_error", 170, ...
    "input_error", 171, ...
    "open_file", 172, ...
    "failed_to_converge", 173, ...
    "command_line_error", 174);
end
