function response = native_executor(request)
%NATIVE_EXECUTOR Adapt PackmolSet executor requests to native MATLAB.

required = ["working_directory", "stdin_path"];
for field = required
    if ~isfield(request, field)
        error("KSSOLV:Packmol:ExecutorRequest", ...
            "Executor request is missing '%s'.", field);
    end
end
try
    inputPath = fullfile(string(request.working_directory), ...
        string(request.stdin_path));
    result = kssolv.analysis.packmol.packmol( ...
        inputPath, WorkingDirectory = string(request.working_directory));
    response = struct( ...
        "status", result.status, ...
        "stdout", result.stdout, ...
        "stderr", result.stderr, ...
        "timed_out", false);
catch exception
    status = exceptionStatus(exception);
    response = struct( ...
        "status", status, ...
        "stdout", "", ...
        "stderr", string(getReport(exception, "extended", ...
            "hyperlinks", "off")), ...
        "timed_out", false);
end
end

function status = exceptionStatus(exception)
codes = kssolv.analysis.packmol.exit_codes();
identifier = string(exception.identifier);
if identifier == "KSSOLV:Packmol:CommandLine"
    status = codes.command_line_error;
elseif any(identifier == [ ...
        "KSSOLV:Packmol:OpenFile", ...
        "KSSOLV:Packmol:Output", ...
        "KSSOLV:Packmol:Restart", ...
        "KSSOLV:Packmol:GradientLog"])
    status = codes.open_file;
elseif startsWith(identifier, "KSSOLV:Packmol:")
    status = codes.input_error;
else
    status = codes.general_error;
end
end
