function [x, diagnostics] = optimize(system, x0, options)
%OPTIMIZE Run Packmol restraint fitting and all-molecule packing.
arguments
    system (1,1) struct
    x0 (:,1) double = kssolv.analysis.packmol.initial_point(system)
    options.MaxIterations (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end
if system.free_molecule_count == 0
    x = zeros(0, 1);
    [objective, ~, evaluation] = ...
        kssolv.analysis.packmol.evaluate(system, x);
    diagnostics = struct( ...
        "objective", objective, ...
        "evaluation", evaluation, ...
        "optimizer", struct("iterations", 0, ...
            "function_evaluations", 1, ...
            "first_order_optimality", 0, ...
            "status", "only fixed molecules", ...
            "objective_history", objective));
    return
end
settings = system.config.settings;
if options.MaxIterations > 0
    objective = @(variables) kssolv.analysis.packmol.evaluate( ...
        system, variables);
    [x, finalObjective, ~, optimizerOutput] = ...
        kssolv.analysis.packmol.gencan( ...
        objective, x0, system.lower_bounds, system.upper_bounds, ...
        MaxIterations = options.MaxIterations, ...
        MaxFunctionEvaluations = max(10 * options.MaxIterations, 20), ...
        OptimalityTolerance = 1e-6);
    [~, ~, evaluation] = kssolv.analysis.packmol.evaluate(system, x);
    diagnostics = struct( ...
        "objective", finalObjective, ...
        "evaluation", evaluation, ...
        "optimizer", optimizerOutput);
    return
end

x = x0;
history = zeros(0, 1);
totalIterations = 0;
totalEvaluations = 0;
lastStatus = "maximum Packmol loops reached";

% Packmol's initial phase fits each molecule type to its spatial
% restraints before atom-pair distances are introduced.
for structureIndex = 1:numel(system.structures)
    if system.structures(structureIndex).fixed
        continue
    end
    restraintFun = @(variables) kssolv.analysis.packmol.evaluate( ...
        system, variables, RestraintsOnly = true, ...
        ActiveStructures = structureIndex);
    [restraintValue, ~, restraintDiagnostics] = restraintFun(x);
    cycle = 0;
    while restraintDiagnostics.maximum_restraint_violation > ...
            settings.precision && ...
            cycle < system.structures(structureIndex).nloop0
        cycle = cycle + 1;
        [x, restraintValue, ~, localOutput] = ...
            kssolv.analysis.packmol.gencan( ...
            restraintFun, x, system.lower_bounds, system.upper_bounds, ...
            MaxIterations = settings.maxit, ...
            MaxFunctionEvaluations = max(10 * settings.maxit, 20));
        totalIterations = totalIterations + localOutput.iterations;
        totalEvaluations = totalEvaluations + ...
            localOutput.function_evaluations;
        [~, ~, restraintDiagnostics] = restraintFun(x);
        if restraintDiagnostics.maximum_restraint_violation > ...
                settings.precision && ~settings.disable_movebad
            [x, ~] = kssolv.analysis.packmol.move_bad( ...
                system, x, structureIndex, -cycle);
        end
    end
    history(end + 1, 1) = restraintValue; %#ok<AGROW>
    if restraintDiagnostics.maximum_restraint_violation > ...
            settings.precision
        [finalObjective, finalGradient, evaluation] = ...
            kssolv.analysis.packmol.evaluate(system, x);
        projectedGradient = x - min(max(x - finalGradient, ...
            system.lower_bounds), system.upper_bounds);
        optimizerOutput = struct( ...
            "iterations", totalIterations, ...
            "function_evaluations", totalEvaluations, ...
            "first_order_optimality", ...
            norm(projectedGradient, Inf), ...
            "status", "restraint-only fitting failed", ...
            "objective_history", history);
        diagnostics = struct( ...
            "objective", finalObjective, ...
            "evaluation", evaluation, ...
            "optimizer", optimizerOutput);
        return
    end
end

if settings.packall
    stages = {1:numel(system.structures)};
else
    stages = cell(numel(system.structures) + 1, 1);
    for i = 1:numel(system.structures)
        stages{i} = i;
    end
    stages{end} = 1:numel(system.structures);
end

bestX = x;
[bestObjective, ~] = kssolv.analysis.packmol.evaluate(system, x);
for stageIndex = 1:numel(stages)
    active = stages{stageIndex};
    if numel(active) == 1 && system.structures(active).fixed
        continue
    end
    if numel(active) == 1
        loopCount = system.structures(active).nloop;
    else
        loopCount = settings.nloop_all;
    end
    radiusScale = settings.discale;
    previous = Inf;
    for cycle = 0:loopCount
        [unscaledValue, ~, evaluation] = ...
            kssolv.analysis.packmol.evaluate( ...
            system, x, ActiveStructures = active);
        if evaluation.maximum_distance_violation < settings.precision && ...
                evaluation.maximum_restraint_violation < settings.precision
            lastStatus = "Packmol precision satisfied";
            break
        end
        improvement = 100;
        if isfinite(previous) && previous > 0
            improvement = max(-99.99, min(99.99, ...
                -100 * (unscaledValue - previous) / previous));
        end
        if cycle > 0 && ~settings.disable_movebad && ...
                radiusScale == 1 && improvement <= 10
            [x, ~] = kssolv.analysis.packmol.move_bad( ...
                system, x, active, cycle + 1000 * stageIndex);
        end
        scaledSystem = system;
        scaledSystem.radius = max(system.radius_initial, ...
            radiusScale * system.radius_initial);
        stageFun = @(variables) kssolv.analysis.packmol.evaluate( ...
            scaledSystem, variables, ActiveStructures = active);
        [x, ~, ~, localOutput] = ...
            kssolv.analysis.packmol.gencan( ...
            stageFun, x, system.lower_bounds, system.upper_bounds, ...
            MaxIterations = settings.maxit, ...
            MaxFunctionEvaluations = max(10 * settings.maxit, 20));
        totalIterations = totalIterations + localOutput.iterations;
        totalEvaluations = totalEvaluations + ...
            localOutput.function_evaluations;
        [currentObjective, ~, currentEvaluation] = ...
            kssolv.analysis.packmol.evaluate(system, x);
        history(end + 1, 1) = currentObjective; %#ok<AGROW>
        if currentObjective < bestObjective
            bestObjective = currentObjective;
            bestX = x;
        end
        if radiusScale > 1 && ...
                (improvement < 2 || ...
                 (currentEvaluation.maximum_distance_violation < ...
                  settings.precision && improvement < 10))
            radiusScale = max(0.9 * radiusScale, 1);
        end
        previous = unscaledValue;
    end
end
x = bestX;
[finalObjective, finalGradient, evaluation] = ...
    kssolv.analysis.packmol.evaluate(system, x);
projectedGradient = x - min(max(x - finalGradient, ...
    system.lower_bounds), system.upper_bounds);
optimizerOutput = struct( ...
    "iterations", totalIterations, ...
    "function_evaluations", totalEvaluations, ...
    "first_order_optimality", norm(projectedGradient, Inf), ...
    "status", lastStatus, ...
    "objective_history", history);
diagnostics = struct( ...
    "objective", finalObjective, ...
    "evaluation", evaluation, ...
    "optimizer", optimizerOutput);
end
