function result = packmol(input, options)
%PACKMOL Native MATLAB implementation of m3g/packmol.
%
% RESULT = kssolv.analysis.packmol.packmol(INPUT) accepts either Packmol
% input text or an input-file path. Structure paths are resolved against
% WorkingDirectory, exactly as the command-line program resolves them
% against its current directory.
arguments
    input {mustBeTextScalar}
    options.WorkingDirectory {mustBeTextScalar} = pwd
    options.Output {mustBeTextScalar} = ""
    options.WriteOutput (1,1) logical = true
    options.InitialPoint double = []
    options.MaxIterations (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end

started = tic;
config = kssolv.analysis.packmol.parse_input( ...
    input, WorkingDirectory = options.WorkingDirectory, ...
    Output = options.Output);
system = kssolv.analysis.packmol.prepare_system(config);
if isempty(options.InitialPoint)
    initialPoint = kssolv.analysis.packmol.initial_point(system);
else
    initialPoint = double(options.InitialPoint(:));
end
[initialObjective, ~, initialEvaluation] = ...
    kssolv.analysis.packmol.evaluate(system, initialPoint);
if config.settings.chkgrad
    variables = initialPoint;
    gradientCheck = kssolv.analysis.packmol.compare_gradient( ...
        system, variables);
    diagnostics = struct( ...
        "objective", initialObjective, ...
        "evaluation", initialEvaluation, ...
        "optimizer", struct("iterations", 0, ...
            "function_evaluations", 1 + 2 * numel(variables), ...
            "first_order_optimality", NaN, ...
            "status", "gradient check requested", ...
            "objective_history", initialObjective), ...
        "gradient_check", gradientCheck);
elseif config.settings.check
    variables = initialPoint;
    diagnostics = struct( ...
        "objective", initialObjective, ...
        "evaluation", initialEvaluation, ...
        "optimizer", struct("iterations", 0, ...
            "function_evaluations", 1, ...
            "first_order_optimality", NaN, ...
            "status", "check requested", ...
            "objective_history", initialObjective));
else
    [variables, diagnostics] = kssolv.analysis.packmol.optimize( ...
        system, initialPoint, MaxIterations = options.MaxIterations);
end
[coordinates, ~, ~] = ...
    kssolv.analysis.packmol.cartesian_coordinates(system, variables);
outputPath = string(config.settings.output);
if ~isAbsolutePath(outputPath)
    outputPath = fullfile(config.working_directory, outputPath);
end
if config.settings.chkgrad
    outputText = "";
elseif options.WriteOutput
    outputText = kssolv.analysis.packmol.write_output( ...
        system, variables, outputPath);
else
    outputText = kssolv.analysis.packmol.write_output( ...
        system, variables, "");
end
success = diagnostics.evaluation.maximum_distance_violation < ...
    config.settings.precision && ...
    diagnostics.evaluation.maximum_restraint_violation < ...
    config.settings.precision;
if config.settings.check || config.settings.chkgrad || ...
        system.free_molecule_count == 0
    success = true;
end
if config.settings.chkgrad
    stdout = string(sprintf([ ...
        '  Gradient comparison complete.\n' ...
        '  Maximum gradient error: %.12e at component %d.\n' ...
        '  Wrote gradient log: %s\n'], ...
        diagnostics.gradient_check.maximum_error, ...
        diagnostics.gradient_check.worst_component, ...
        fullfile(config.working_directory, "chkgrad.log")));
else
    stdout = statusText(success, diagnostics, outputPath, toc(started));
end
result = struct( ...
    "status", double(~success) * 173, ...
    "success", success, ...
    "stdout", stdout, ...
    "stderr", "", ...
    "timed_out", false, ...
    "config", config, ...
    "system", system, ...
    "initial_point", initialPoint, ...
    "variables", variables, ...
    "coordinates", coordinates, ...
    "output_path", outputPath, ...
    "output_text", outputText, ...
    "initial_objective", initialObjective, ...
    "diagnostics", diagnostics, ...
    "elapsed_time", toc(started));
end

function text = statusText(success, diagnostics, outputPath, elapsed)
if success
    heading = "Success!";
else
    heading = "ERROR: Packmol was unable to reach the requested precision.";
end
evaluation = diagnostics.evaluation;
text = string(sprintf([ ...
    '  %s\n' ...
    '  Final objective function value: %.12e\n' ...
    '  Maximum violation of target distance: %.12e\n' ...
    '  Maximum violation of the constraints: %.12e\n' ...
    '  Wrote output file: %s\n' ...
    '  Running time: %.6f seconds.\n'], ...
    heading, diagnostics.objective, ...
    evaluation.maximum_distance_violation, ...
    evaluation.maximum_restraint_violation, outputPath, elapsed));
end

function value = isAbsolutePath(path)
path = char(string(path));
if ispc
    value = ~isempty(regexp(path, "^[A-Za-z]:[\\/]", "once")) || ...
        startsWith(path, "\\");
else
    value = startsWith(path, "/");
end
end
