classdef EnvironmentNode < ...
        kssolv.analysis.matgenlab.analysis.chemenv.connectivity.AbstractEnvironmentNode
    %ENVIRONMENTNODE Concrete coordination-environment graph node.
    methods
        function obj=EnvironmentNode(centralSite,index,ceSymbol)
            obj@kssolv.analysis.matgenlab.analysis.chemenv. ...
                connectivity.AbstractEnvironmentNode(centralSite,index);
            obj.coordination_environment_value=string(ceSymbol);
        end
        function value=everything_equal(obj,other)
            value=everything_equal@kssolv.analysis.matgenlab.analysis. ...
                chemenv.connectivity.AbstractEnvironmentNode(obj,other)&& ...
                obj.coordination_environment==other.coordination_environment;
        end
        function value=as_dict(obj)
            value=struct(x_module="pymatgen.analysis.chemenv."+ ...
                "connectivity.environment_nodes",x_class="EnvironmentNode", ...
                central_site=obj.central_site.as_dict(), ...
                i_central_site=obj.isite-1, ...
                ce_symbol=obj.coordination_environment);
        end
    end
end
