classdef VolumeSceneValidator
    %VOLUMESCENEVALIDATOR Validate the MATLAB side of VolumeSceneSpec 1.0.

    methods (Static)
        function validate(scene)
            required = ["schemaVersion", "kind", "requestId", ...
                "source", "grid", "channels", "warnings", "transport"];
            for field = required
                if ~isfield(scene, field)
                    error("KSSOLV:UI:Volume:SceneField", ...
                        "Volume scene is missing required field '%s'.", ...
                        field);
                end
            end
            if string(scene.schemaVersion) ~= "1.0" || ...
                    string(scene.kind) ~= "volume"
                error("KSSOLV:UI:Volume:SceneVersion", ...
                    "Unsupported volume scene schema or kind.");
            end
            if strlength(string(scene.requestId)) == 0
                error("KSSOLV:UI:Volume:SceneRequest", ...
                    "Volume scene requestId cannot be empty.");
            end
            grid = scene.grid;
            dimensions = reshape(double(grid.dimensions), 1, []);
            if numel(dimensions) ~= 3
                error("KSSOLV:UI:Volume:SceneGrid", ...
                    "Grid dimensions must contain three entries.");
            end
            count = ...
                kssolv.services.fileparser.volume.VolumeLimits. ...
                validateDimensions(dimensions, numel(scene.channels));
            vectors = double(grid.voxelVectors);
            if ~isequal(size(vectors), [3, 3]) || ...
                    rank(vectors(1:grid.dimensionality, :)) < ...
                    grid.dimensionality
                error("KSSOLV:UI:Volume:SceneTransform", ...
                    "Volume voxel vectors do not span the declared grid.");
            end
            identifiers = string({scene.channels.id});
            if any(strlength(identifiers) == 0) || ...
                    numel(unique(identifiers)) ~= numel(identifiers)
                error("KSSOLV:UI:Volume:SceneChannels", ...
                    "Volume channel identifiers must be unique.");
            end
            for channel = scene.channels
                statistics = [channel.minimum, channel.maximum, ...
                    channel.mean, channel.standardDeviation];
                if any(~isfinite(statistics))
                    error("KSSOLV:UI:Volume:SceneStatistics", ...
                        "Channel '%s' contains invalid statistics.", ...
                        channel.id);
                end
                transport = channel.transport;
                bytesPerValue = 4;
                if string(transport.valueEncoding) == "float64-le"
                    bytesPerValue = 8;
                elseif string(transport.valueEncoding) == ...
                        "uint16-linear-le"
                    bytesPerValue = 2;
                    if ~isfield(transport, "scale") || ...
                            ~isfield(transport, "offset") || ...
                            ~isfinite(transport.scale) || ...
                            transport.scale <= 0 || ...
                            ~isfinite(transport.offset)
                        error("KSSOLV:UI:Volume:SceneQuantization", ...
                            ["Uint16 linear transport for channel '%s' " ...
                            "requires a positive scale and finite offset."], ...
                            channel.id);
                    end
                elseif string(transport.valueEncoding) ~= "float32-le"
                    error("KSSOLV:UI:Volume:SceneEncoding", ...
                        "Unsupported value encoding '%s'.", ...
                        transport.valueEncoding);
                end
                if transport.elementCount ~= count || ...
                        transport.byteLength ~= count * bytesPerValue
                    error("KSSOLV:UI:Volume:SceneByteLength", ...
                        "Channel '%s' transport size does not match grid.", ...
                        channel.id);
                end
                if ~isfield(transport, "crc32") || ...
                        ~isscalar(transport.crc32) || ...
                        ~isfinite(transport.crc32) || ...
                        transport.crc32 < 0 || ...
                        transport.crc32 > double(intmax("uint32")) || ...
                        fix(transport.crc32) ~= transport.crc32
                    error("KSSOLV:UI:Volume:SceneChecksum", ...
                        "Channel '%s' requires a valid CRC32 checksum.", ...
                        channel.id);
                end
            end
        end
    end
end
