classdef VolumeLodBuilder
    %VOLUMELODBUILDER Create a bounded preview grid for progressive display.

    methods (Static)
        function preview = previewDataset(dataset, maxVoxels)
            arguments
                dataset (1,1) kssolv.services.fileparser.VolumeDataset
                maxVoxels (1,1) double = 96^3
            end
            dimensions = dataset.dimensions;
            if prod(dimensions) <= maxVoxels
                preview = dataset;
                return
            end
            scale = (prod(dimensions) / maxVoxels) ^ (1 / 3);
            target = max(1, floor(dimensions / max(scale, 1)));
            target(1:dataset.dimensionality) = max(2, ...
                target(1:dataset.dimensionality));
            indices = cell(1, 3);
            for axis = 1:3
                indices{axis} = unique(round(linspace( ...
                    1, dimensions(axis), target(axis))));
            end
            target = cellfun(@numel, indices);
            channels = dataset.channels;
            for index = 1:numel(channels)
                values = channels(index).values( ...
                    indices{1}, indices{2}, indices{3});
                channels(index) = ...
                    kssolv.services.fileparser.volume. ...
                    VolumeStatistics.channel( ...
                    channels(index).id, channels(index).label, ...
                    channels(index).units, values, ...
                    channels(index).integral);
            end
            vectors = dataset.voxelVectors;
            for axis = 1:dataset.dimensionality
                if dataset.sampling == "point-inclusive"
                    factor = (dimensions(axis) - 1) / ...
                        max(target(axis) - 1, 1);
                else
                    factor = dimensions(axis) / target(axis);
                end
                vectors(axis, :) = vectors(axis, :) * factor;
            end
            source = dataset.source;
            source.preview = true;
            preview = kssolv.services.fileparser.VolumeDataset( ...
                source = source, ...
                structure = dataset.structure, ...
                dimensionality = dataset.dimensionality, ...
                dimensions = target, ...
                origin = dataset.origin, ...
                voxelVectors = vectors, ...
                periodic = dataset.periodic, ...
                sampling = dataset.sampling, ...
                channels = channels, ...
                warnings = [dataset.warnings, ...
                "Interactive preview; full-resolution data remains in MATLAB."]);
        end
    end
end
