classdef BatteryNumericTest < matlab.unittest.TestCase
    % Frozen from materialsproject/pymatgen-test-files master on 2026-07-27.
    methods (Test)
        function apiInventoryFrozen(testCase)
            root="kssolv.analysis.matgenlab.apps.battery.";
            classes=["AbstractVoltagePair","AbstractElectrode","BatteryAnalyzer", ...
                "InsertionElectrode","InsertionVoltagePair", ...
                "ConversionElectrode","ConversionVoltagePair", ...
                "VoltageProfilePlotter"];
            for name=classes,testCase.verifyNotEmpty(which(root+name));end
            testCase.verifyNotEmpty(which(root+"is_redox_active_intercalation"));
            verifyMembers(testCase,root+"AbstractVoltagePair",[], ...
                ["working_ion","framework","x_charge","x_discharge"]);
            verifyMembers(testCase,root+"AbstractElectrode", ...
                ["get_sub_electrodes","get_average_voltage", ...
                "get_capacity_grav","get_capacity_vol","get_specific_energy", ...
                "get_energy_density","get_summary_dict"], ...
                ["working_ion","framework","x_charge","x_discharge", ...
                "max_delta_volume","num_steps","max_voltage","min_voltage", ...
                "max_voltage_step","normalization_mass","normalization_volume"]);
            verifyMembers(testCase,root+"BatteryAnalyzer", ...
                ["get_max_capgrav","get_max_capvol","get_removals_int_oxid"], ...
                ["max_ion_removal","max_ion_insertion"]);
            verifyMembers(testCase,root+"InsertionElectrode", ...
                ["from_entries","get_stable_entries","get_unstable_entries", ...
                "get_all_entries","get_max_instability","get_min_instability", ...
                "get_max_muO2","get_min_muO2","get_sub_electrodes", ...
                "get_summary_dict","from_dict_legacy","as_dict_legacy"], ...
                ["fully_charged_entry","fully_discharged_entry"]);
            verifyMembers(testCase,root+"InsertionVoltagePair","from_entries",[]);
            verifyMembers(testCase,root+"ConversionElectrode", ...
                ["from_composition_and_pd","from_composition_and_entries", ...
                "get_sub_electrodes","is_super_electrode","get_summary_dict"], ...
                "initial_comp");
            verifyMembers(testCase,root+"ConversionVoltagePair","from_steps",[]);
            verifyMembers(testCase,root+"VoltageProfilePlotter", ...
                ["add_electrode","get_plot_data","get_plot", ...
                "get_plotly_figure","show","save"],[]);
        end

        function insertionOfficialFixtures(testCase)
            entries=loadFixture("LiTiO2_batt.json");
            lithium=kssolv.analysis.matgenlab.core.ComputedEntry( ...
                "Li",-1.90753119);
            electrode=kssolv.analysis.matgenlab.apps.battery. ...
                InsertionElectrode.from_entries(entries,lithium);
            testCase.verifyEqual(electrode.max_voltage,2.78583901,AbsTol=1e-8);
            testCase.verifyEqual(electrode.min_voltage,0.89702381,AbsTol=1e-8);
            testCase.verifyEqual(electrode.get_average_voltage(), ...
                1.84143141,AbsTol=1e-8);
            testCase.verifyEqual(electrode.get_capacity_grav(), ...
                308.74865045,AbsTol=2e-4);
            testCase.verifyEqual(electrode.get_capacity_vol(), ...
                1205.99391136,AbsTol=2e-4);
            testCase.verifyEqual(electrode.get_specific_energy(), ...
                electrode.get_capacity_grav()* ...
                electrode.get_average_voltage(),AbsTol=1e-10);
            testCase.verifyEqual(electrode.get_energy_density(), ...
                electrode.get_capacity_vol()* ...
                electrode.get_average_voltage(),AbsTol=1e-10);
            testCase.verifyEqual(numel(electrode.get_sub_electrodes(false,true)),3);
            testCase.verifyEqual(numel(electrode.get_sub_electrodes(true,true)),2);
            testCase.verifyEqual(numel(electrode.get_stable_entries()),3);
            testCase.verifyEqual(electrode.get_stable_entries(false), ...
                fliplr(electrode.get_stable_entries()));
            testCase.verifyEqual(numel(electrode.get_all_entries()), ...
                numel(electrode.get_stable_entries())+ ...
                numel(electrode.get_unstable_entries()));
            stable=electrode.get_stable_entries();
            testCase.verifyEqual(electrode.fully_charged_entry, ...
                stable{1});
            testCase.verifyEqual(electrode.fully_discharged_entry,stable{end});
            testCase.verifyGreaterThanOrEqual(electrode.max_delta_volume,0);
            testCase.verifyGreaterThan(electrode.normalization_mass,0);
            testCase.verifyGreaterThan(electrode.normalization_volume,0);
            pair=electrode.voltage_pairs{1};
            testCase.verifyEqual(pair.mAh,13400.7411749,AbsTol=1e-3);
            testCase.verifyEqual(pair.mass_charge,79.8658,AbsTol=1e-8);
            testCase.verifyEqual(pair.vol_charge,37.553684467,AbsTol=1e-9);
            testCase.verifyEqual(pair.x_discharge,0.5,AbsTol=1e-14);
            testCase.verifyEqual(pair.working_ion.symbol,"Li");
            testCase.verifyEqual(pair.framework.reduced_formula,"TiO2");
            restored=kssolv.analysis.matgenlab.apps.battery. ...
                InsertionElectrode.from_dict(electrode.as_dict());
            testCase.verifyEqual(restored.get_average_voltage(), ...
                electrode.get_average_voltage(),AbsTol=1e-14);
            legacy=kssolv.analysis.matgenlab.apps.battery. ...
                InsertionElectrode.from_dict_legacy( ...
                electrode.as_dict_legacy());
            testCase.verifyEqual(legacy.get_average_voltage(), ...
                electrode.get_average_voltage(),AbsTol=1e-14);
        end

        function insertionStabilityOfficialFixture(testCase)
            entries=loadFixture("MgVO_batt.json");
            magnesium=loadFixture("Mg_batt.json");
            electrode=kssolv.analysis.matgenlab.apps.battery. ...
                InsertionElectrode.from_entries(entries,magnesium);
            testCase.verifyEqual(electrode.get_average_voltage(), ...
                2.513767,AbsTol=1e-6);
            testCase.verifyEqual(electrode.get_capacity_grav(), ...
                281.845548242,AbsTol=2e-4);
            testCase.verifyEqual(electrode.get_max_instability(), ...
                0.7233711650000014,AbsTol=1e-13);
            testCase.verifyEqual(electrode.get_min_instability(), ...
                0.4913575099999994,AbsTol=1e-13);
            testCase.verifyEqual(electrode.get_max_muO2(), ...
                -4.93552791875,AbsTol=1e-12);
            testCase.verifyEqual(electrode.get_min_muO2(), ...
                -11.06599657,AbsTol=1e-12);
        end

        function insertionSummaryOfficialFixture(testCase)
            calcium=kssolv.analysis.matgenlab.core.ComputedEntry( ...
                "Ca",-1.99689568);
            electrode=kssolv.analysis.matgenlab.apps.battery. ...
                InsertionElectrode.from_entries( ...
                loadFixture("CaMoO2_batt.json"),calcium);
            data=electrode.get_summary_dict();
            testCase.verifyEqual(data.stability_charge, ...
                0.2346574583333325,AbsTol=1e-14);
            testCase.verifyEqual(data.stability_discharge, ...
                0.33379544031249786,AbsTol=1e-14);
            testCase.verifyEqual(data.framework_formula,"MoO2");
        end

        function conversionOfficialFixtures(testCase)
            formulas=["LiCoO2","FeF3","MnO2"];ions=["Li","Li","Mg"];
            expected=[2.26940307125,903.197529112,2903.35804724; ...
                3.06179925889,601.545087016,2132.20691151; ...
                1.71270276879017,790.914207003,3543.20200353];
            for index=1:numel(formulas)
                entries=loadFixture(formulas(index)+"_batt.json");
                electrode=kssolv.analysis.matgenlab.apps.battery. ...
                    ConversionElectrode.from_composition_and_entries( ...
                    formulas(index),entries,ions(index));
                diagram=kssolv.analysis.matgenlab.analysis.PhaseDiagram(entries);
                fromDiagram=kssolv.analysis.matgenlab.apps.battery. ...
                    ConversionElectrode.from_composition_and_pd( ...
                    formulas(index),diagram,ions(index));
                testCase.verifyEqual(fromDiagram.get_average_voltage(), ...
                    electrode.get_average_voltage(),AbsTol=1e-14);
                testCase.verifyEqual(electrode.get_average_voltage(), ...
                    expected(index,1),AbsTol=2e-10);
                testCase.verifyEqual(electrode.get_capacity_grav(), ...
                    expected(index,2),AbsTol=1e-3);
                testCase.verifyEqual(electrode.get_capacity_vol(), ...
                    expected(index,3),AbsTol=1e-3);
                testCase.verifyEqual(numel(electrode.get_sub_electrodes(true)), ...
                    electrode.num_steps);
                testCase.verifyEqual(numel(electrode.get_sub_electrodes(false)), ...
                    sum(1:electrode.num_steps));
                adjacent=electrode.get_sub_electrodes(true);
                testCase.verifyTrue(electrode.is_super_electrode(adjacent{1}));
                testCase.verifyEqual(electrode.initial_comp.reduced_formula, ...
                    formulas(index));
                summary=electrode.get_summary_dict();
                testCase.verifyEqual(numel(summary.reactions), ...
                    electrode.num_steps);
                restored=kssolv.analysis.matgenlab.apps.battery. ...
                    ConversionElectrode.from_dict(electrode.as_dict());
                testCase.verifyEqual(restored.get_average_voltage(), ...
                    electrode.get_average_voltage(),AbsTol=1e-14);
            end
        end

        function analyzerOfficialFixtures(testCase)
            previous=warning("off","all");cleanup=onCleanup(@()warning(previous));
            structure=loadCif("LiFePO4.cif", ...
                struct("Li",1,"Fe",2,"P",5,"O",-2));
            analyzer=kssolv.analysis.matgenlab.apps.battery. ...
                BatteryAnalyzer(structure,"Li");
            testCase.verifyGreaterThanOrEqual(analyzer.max_ion_removal,0);
            testCase.verifyGreaterThanOrEqual(analyzer.max_ion_insertion,0);
            testCase.verifyEqual(analyzer.get_max_capgrav(), ...
                169.89053,AbsTol=1e-3);
            testCase.verifyEqual(analyzer.get_max_capvol(), ...
                594.17518,AbsTol=1e-3);
            structure=loadCif("Li4Fe3Mn1(PO4)4.cif", ...
                struct("Li",1,"Fe",2,"Mn",2,"P",5,"O",-2));
            analyzer=kssolv.analysis.matgenlab.apps.battery. ...
                BatteryAnalyzer(structure,"Li");
            testCase.verifyEqual(analyzer.get_removals_int_oxid(),1:4);
            structure=loadCif("MgNiF6.cif", ...
                struct("Mg",2,"Ni",4,"F",-1));
            analyzer=kssolv.analysis.matgenlab.apps.battery. ...
                BatteryAnalyzer(structure,"F");
            testCase.verifyEqual(analyzer.get_removals_int_oxid(),[1,2]);
            testCase.verifyTrue(kssolv.analysis.matgenlab.apps.battery. ...
                is_redox_active_intercalation("Fe"));
            testCase.verifyFalse(kssolv.analysis.matgenlab.apps.battery. ...
                is_redox_active_intercalation("Li"));
            clear cleanup
        end
    end
end
function verifyMembers(testCase,className,methodNames,propertyNames)
availableMethods=string(methods(char(className)));
availableProperties=string(properties(char(className)));
for name=reshape(string(methodNames),1,[])
    testCase.verifyTrue(any(availableMethods==name), ...
        "Missing method "+className+"."+name);
end
for name=reshape(string(propertyNames),1,[])
    testCase.verifyTrue(any(availableProperties==name), ...
        "Missing property "+className+"."+name);
end
end
function value=loadFixture(name)
path=fullfile(fileparts(mfilename("fullpath")),"+fixtures",name);
value=kssolv.analysis.matgenlab.util.decode(fileread(path));
end
function structure=loadCif(name,oxidationStates)
path=fullfile(fileparts(mfilename("fullpath")),"+fixtures",name);
structure=kssolv.analysis.matgenlab.core.Structure.from_file(path);
structure=structure.add_oxidation_state_by_element(oxidationStates);
end
