classdef CrystalSceneBuilder
    %CRYSTALSCENEBUILDER Compile matgenlab structures for the WebGL viewer.
    methods (Static)
        function scene = fromString(content, format, options)
            arguments
                content string {mustBeScalarOrEmpty}
                format string {mustBeScalarOrEmpty}
                options.algorithm string = "CrystalNN"
                options.cell string = "input"
                options.repeat (1,3) double = [1, 1, 1]
                options.includeConnectivity (1,1) logical = true
                options.includePolyhedra (1,1) logical = true
                options.includeBoundaryAtoms (1,1) logical = true
                options.includeBondedOutside (1,1) logical = true
                options.boundaryTolerance (1,1) double = 0.05
                options.requestId string = ""
            end
            structure = kssolv.analysis.matgenlab.core.Structure. ...
                from_str(content, format);
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, algorithm = options.algorithm, ...
                cell = options.cell, repeat = options.repeat, ...
                includeConnectivity = options.includeConnectivity, ...
                includePolyhedra = options.includePolyhedra, ...
                includeBoundaryAtoms = options.includeBoundaryAtoms, ...
                includeBondedOutside = options.includeBondedOutside, ...
                boundaryTolerance = options.boundaryTolerance, ...
                requestId = options.requestId);
        end

        function scene = build(structure, options)
            arguments
                structure (1,1) kssolv.analysis.matgenlab.core.IStructure
                options.algorithm string = "CrystalNN"
                options.cell string = "input"
                options.repeat (1,3) double = [1, 1, 1]
                options.includeConnectivity (1,1) logical = true
                options.includePolyhedra (1,1) logical = true
                options.includeBoundaryAtoms (1,1) logical = true
                options.includeBondedOutside (1,1) logical = true
                options.boundaryTolerance (1,1) double = 0.05
                options.requestId string = ""
            end
            started = tic;
            repeat = round(options.repeat);
            if any(repeat < 1) || any(repeat > 8)
                error("KSSOLV:CrystalViewer:Repeat", ...
                    "Repeat values must be integers between 1 and 8.");
            end
            if options.boundaryTolerance < 0 || ...
                    options.boundaryTolerance >= 0.5
                error("KSSOLV:CrystalViewer:BoundaryTolerance", ...
                    "Boundary tolerance must be in the interval [0, 0.5).");
            end
            requestId = options.requestId;
            if strlength(requestId) == 0
                requestId = string(matlab.lang.internal.uuid);
            end
            structure = kssolv.ui.crystal.CrystalSceneBuilder. ...
                transformStructure(structure, options.cell);
            structure = structure.copy([], false);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                structure.lattice, structure.species_and_occu, ...
                structure.frac_coords, to_unit_cell = true, ...
                site_properties = structure.site_properties, ...
                labels = structure.labels, ...
                properties = structure.structure_properties, ...
                skip_checks = true);
            warnings = struct("code", {}, "message", {}, "severity", {});
            if structure.num_sites > 25600
                error("KSSOLV:CrystalViewer:StructureLimit", ...
                    "Structures above 25,600 sites are not supported.");
            end

            schemes = jsondecode(fileread(fullfile( ...
                fileparts(fileparts(fileparts(mfilename("fullpath")))), ...
                "+analysis", "+matgenlab", "+vis", ...
                "ElementColorSchemes.json")));
            sites = repmat( ...
                kssolv.ui.crystal.CrystalSceneSerializer. ...
                site(structure(1), 1, schemes), 1, structure.num_sites);
            for index = 1:structure.num_sites
                sites(index) = ...
                    kssolv.ui.crystal.CrystalSceneSerializer. ...
                    site(structure(index), index, schemes);
            end

            atomInstances = struct("id", {}, "siteId", {}, ...
                "siteIndex", {}, "imageOffset", {}, "position", {}, ...
                "visibility", {});
            atomKeys = strings(1, 0);
            for siteIndex = 1:structure.num_sites
                for a = 0:repeat(1)-1
                    for b = 0:repeat(2)-1
                        for c = 0:repeat(3)-1
                            image = [a, b, c];
                            visibility = "repeat";
                            if all(image == 0), visibility = "base"; end
                            [atomInstances, atomKeys] = ...
                                kssolv.ui.crystal.CrystalSceneBuilder.addAtom( ...
                                atomInstances, atomKeys, structure, ...
                                siteIndex, image, visibility);
                        end
                    end
                end
                if options.includeBoundaryAtoms
                    images = kssolv.ui.crystal.CrystalSceneBuilder. ...
                        boundaryImages(structure(siteIndex).frac_coords, ...
                        repeat, options.boundaryTolerance);
                    for imageIndex = 1:size(images, 1)
                        [atomInstances, atomKeys] = ...
                            kssolv.ui.crystal.CrystalSceneBuilder.addAtom( ...
                            atomInstances, atomKeys, structure, siteIndex, ...
                            images(imageIndex, :), "boundary");
                    end
                end
            end

            relations = struct("id", {}, "fromSiteIndex", {}, ...
                "toSiteIndex", {}, "relativeImage", {}, "distance", {}, ...
                "weight", {});
            bonds = struct("id", {}, "relationId", {}, ...
                "fromSiteIndex", {}, "toSiteIndex", {}, ...
                "fromImage", {}, "toImage", {}, "start", {}, "end", {}, ...
                "distance", {}, "visibility", {});
            polyhedra = struct("id", {}, "centerSiteIndex", {}, ...
                "center", {}, "vertices", {}, "color", {}, ...
                "visibility", {});
            actualAlgorithm = options.algorithm;
            if options.includeConnectivity
                [graph, actualAlgorithm, graphWarnings] = ...
                    kssolv.ui.crystal.CrystalSceneBuilder. ...
                    buildGraph(structure, options.algorithm);
                warnings = [warnings, graphWarnings];
                [relations, bonds, atomInstances, ~] = ...
                    kssolv.ui.crystal.CrystalSceneBuilder.buildBonds( ...
                    structure, graph, repeat, atomInstances, atomKeys, ...
                    options.includeBondedOutside);
                if options.includePolyhedra
                    polyhedra = ...
                        kssolv.ui.crystal.CrystalSceneBuilder. ...
                        buildPolyhedra(structure, graph, repeat, schemes);
                end
            else
                warnings(end + 1) = ...
                    kssolv.ui.crystal.CrystalSceneSerializer.warning( ...
                    "CONNECTIVITY_DEFERRED", ...
                    "Atoms are available while exact connectivity is computed.", ...
                    "info");
            end

            if numel(atomInstances) > 64000
                error("KSSOLV:CrystalViewer:AtomLimit", ...
                    "The expanded scene exceeds 64,000 atom instances.");
            end
            if numel(bonds) > 256000
                error("KSSOLV:CrystalViewer:BondLimit", ...
                    "The expanded scene exceeds 256,000 bond instances.");
            end
            parameters = struct( ...
                "cell", string(options.cell), ...
                "repeat", repeat, ...
                "boundaryTolerance", options.boundaryTolerance, ...
                "includeConnectivity", options.includeConnectivity, ...
                "includePolyhedra", options.includePolyhedra, ...
                "includeBoundaryAtoms", options.includeBoundaryAtoms, ...
                "includeBondedOutside", options.includeBondedOutside);
            matgenlabVersion = kssolv.analysis.matgenlab.version();
            scene = struct( ...
                "schemaVersion", "2.0", ...
                "kind", "crystal", ...
                "requestId", requestId, ...
                "structure", struct( ...
                    "formula", string(structure.reduced_formula), ...
                    "lattice", double(structure.lattice.matrix), ...
                    "periodic", logical(structure.pbc), ...
                    "repeat", repeat, ...
                    "siteCount", structure.num_sites, ...
                    "isOrdered", structure.is_ordered), ...
                "sites", sites, ...
                "atomInstances", atomInstances, ...
                "bondRelations", relations, ...
                "bondInstances", bonds, ...
                "polyhedra", polyhedra, ...
                "analysis", struct( ...
                    "algorithm", string(actualAlgorithm), ...
                    "parameters", parameters, ...
                    "source", "matgenlab", ...
                    "sourceVersion", "matgenlab-" + ...
                        string(matgenlabVersion.Version) + ...
                        "/pymatgen-" + ...
                        string(matgenlabVersion.PymatgenVersion), ...
                    "elapsedMilliseconds", toc(started) * 1000), ...
                "warnings", warnings);
            kssolv.ui.crystal.CrystalSceneValidator.validate(scene);
        end
    end

    methods (Static, Access = private)
        function structure = transformStructure(structure, cellType)
            switch lower(string(cellType))
                case "input"
                    structure = structure.copy();
                case "primitive"
                    analyzer = kssolv.analysis.matgenlab.symmetry. ...
                        analyzer.SpacegroupAnalyzer(structure);
                    structure = analyzer.get_primitive_standard_structure( ...
                        true, true);
                case "conventional"
                    analyzer = kssolv.analysis.matgenlab.symmetry. ...
                        analyzer.SpacegroupAnalyzer(structure);
                    structure = analyzer.get_conventional_standard_structure( ...
                        true, true);
                case "niggli"
                    structure = structure.get_reduced_structure("niggli");
                case "lll"
                    structure = structure.get_reduced_structure("lll");
                otherwise
                    error("KSSOLV:CrystalViewer:CellType", ...
                        "Unsupported unit-cell representation '%s'.", cellType);
            end
        end

        function [graph, algorithm, warnings] = ...
                buildGraph(structure, requestedAlgorithm)
            warnings = struct("code", {}, "message", {}, "severity", {});
            algorithm = string(requestedAlgorithm);
            strategy = ...
                kssolv.ui.crystal.CrystalSceneBuilder.strategy(algorithm);
            if ~structure.is_ordered
                warnings(end + 1) = ...
                    kssolv.ui.crystal.CrystalSceneSerializer.warning( ...
                    "DISORDERED_MAJORITY_CONNECTIVITY", ...
                    "Connectivity uses the highest-occupancy species at " + ...
                    "each disordered site; all occupancies remain visible.", ...
                    "warning");
            end
            try
                graph = strategy.get_bonded_structure( ...
                    structure, "weights", true, ...
                    "on_disorder", "take_max_species");
            catch exception
                if algorithm ~= "CrystalNN" || structure.is_ordered
                    rethrow(exception);
                end
                algorithm = "CutOffDictNN";
                strategy = kssolv.analysis.matgenlab.core.CutOffDictNN. ...
                    from_preset("vesta_2019");
                graph = strategy.get_bonded_structure( ...
                    structure, "weights", true, ...
                    "on_disorder", "take_max_species");
                warnings(end + 1) = ...
                    kssolv.ui.crystal.CrystalSceneSerializer.warning( ...
                    "DISORDERED_CONNECTIVITY_FALLBACK", ...
                    "CrystalNN could not resolve this disordered structure; " + ...
                    "VESTA cutoff connectivity is shown explicitly.", ...
                    "warning");
            end
        end

        function strategy = strategy(algorithm)
            switch string(algorithm)
                case "CrystalNN"
                    strategy = kssolv.analysis.matgenlab.core.CrystalNN();
                case "CutOffDictNN"
                    strategy = ...
                        kssolv.analysis.matgenlab.core.CutOffDictNN. ...
                        from_preset("vesta_2019");
                case "MinimumDistanceNN"
                    strategy = ...
                        kssolv.analysis.matgenlab.core.MinimumDistanceNN();
                case "JmolNN"
                    strategy = kssolv.analysis.matgenlab.core.JmolNN();
                case "MinimumOKeeffeNN"
                    strategy = ...
                        kssolv.analysis.matgenlab.core.MinimumOKeeffeNN();
                case "EconNN"
                    strategy = kssolv.analysis.matgenlab.core.EconNN();
                case "BrunnerNNReciprocal"
                    strategy = ...
                        kssolv.analysis.matgenlab.core.BrunnerNNReciprocal();
                otherwise
                    error("KSSOLV:CrystalViewer:Algorithm", ...
                        "Unsupported bonding algorithm '%s'.", algorithm);
            end
        end

        function [relations, bonds, atoms, atomKeys] = buildBonds( ...
                structure, graph, repeat, atoms, atomKeys, includeOutside)
            relations = struct("id", {}, "fromSiteIndex", {}, ...
                "toSiteIndex", {}, "relativeImage", {}, "distance", {}, ...
                "weight", {});
            bonds = struct("id", {}, "relationId", {}, ...
                "fromSiteIndex", {}, "toSiteIndex", {}, ...
                "fromImage", {}, "toImage", {}, "start", {}, "end", {}, ...
                "distance", {}, "visibility", {});
            edges = graph.graph.edges;
            for relationIndex = 1:numel(edges)
                relation = ...
                    kssolv.ui.crystal.CrystalSceneSerializer. ...
                    relation(edges(relationIndex), relationIndex, structure);
                relations(end + 1) = relation; %#ok<AGROW>
            end

            % Crystal Toolkit first determines a finite set of sites to draw:
            % the repeated cell, periodic boundary images, and (optionally)
            % exactly one graph hop outside that set.  Bonds are then emitted
            % only when both endpoints belong to that finite set.  Building
            % from the visible-site set avoids duplicate periodic bonds and
            % prevents relations from being expanded independently of atoms.
            if includeOutside
                seedCount = numel(atoms);
                incident = cell(1, structure.num_sites);
                for relationIndex = 1:numel(relations)
                    relation = relations(relationIndex);
                    fromSite = relation.fromSiteIndex + 1;
                    toSite = relation.toSiteIndex + 1;
                    incident{fromSite}(end + 1, :) = ...
                        [relationIndex, 1];
                    incident{toSite}(end + 1, :) = ...
                        [relationIndex, -1];
                end
                for atomIndex = 1:seedCount
                    atom = atoms(atomIndex);
                    siteIndex = atom.siteIndex + 1;
                    image = atom.imageOffset;
                    siteIncident = incident{siteIndex};
                    for incidentIndex = 1:size(siteIncident, 1)
                        relationIndex = siteIncident(incidentIndex, 1);
                        direction = siteIncident(incidentIndex, 2);
                        relation = relations(relationIndex);
                        if direction > 0
                            targetSite = relation.toSiteIndex + 1;
                            targetImage = image + relation.relativeImage;
                        else
                            targetSite = relation.fromSiteIndex + 1;
                            targetImage = image - relation.relativeImage;
                        end
                        if all(targetImage >= 0 & targetImage < repeat)
                            continue
                        end
                        [atoms, atomKeys] = ...
                            kssolv.ui.crystal.CrystalSceneBuilder.addAtom( ...
                            atoms, atomKeys, structure, targetSite, ...
                            targetImage, "bonded");
                    end
                end
            end

            bondKeys = strings(1, 0);
            siteIndices = [atoms.siteIndex];
            for relationIndex = 1:numel(relations)
                relation = relations(relationIndex);
                relative = relation.relativeImage;
                forwardAtoms = find(siteIndices == relation.fromSiteIndex);
                for atomIndex = forwardAtoms
                    source = atoms(atomIndex).imageOffset;
                    [bonds, bondKeys] = ...
                        kssolv.ui.crystal.CrystalSceneBuilder. ...
                        addVisibleBond(bonds, bondKeys, atoms, atomKeys, ...
                        relation, relationIndex, source, ...
                        source + relative, structure);
                end
                reverseAtoms = find(siteIndices == relation.toSiteIndex);
                for atomIndex = reverseAtoms
                    source = atoms(atomIndex).imageOffset;
                    [bonds, bondKeys] = ...
                        kssolv.ui.crystal.CrystalSceneBuilder. ...
                        addVisibleBond(bonds, bondKeys, atoms, atomKeys, ...
                        relation, relationIndex, source, ...
                        source - relative, structure, true);
                end
            end
        end

        function [bonds, bondKeys] = addVisibleBond( ...
                bonds, bondKeys, atoms, atomKeys, relation, relationIndex, ...
                fromImage, toImage, structure, reverse)
            if nargin < 10, reverse = false; end
            if reverse
                fromSite = relation.toSiteIndex + 1;
                toSite = relation.fromSiteIndex + 1;
                normalized = relation;
                normalized.fromSiteIndex = fromSite - 1;
                normalized.toSiteIndex = toSite - 1;
            else
                fromSite = relation.fromSiteIndex + 1;
                toSite = relation.toSiteIndex + 1;
                normalized = relation;
            end
            fromKey = string(fromSite) + "@" + ...
                join(string(fromImage), ",");
            toKey = string(toSite) + "@" + join(string(toImage), ",");
            fromAtomIndex = find(atomKeys == fromKey, 1);
            toAtomIndex = find(atomKeys == toKey, 1);
            if isempty(fromAtomIndex) || isempty(toAtomIndex), return, end
            geometryKey = kssolv.ui.crystal.CrystalSceneBuilder. ...
                bondGeometryKey(fromSite, fromImage, toSite, toImage);
            if any(bondKeys == geometryKey), return, end
            visibility = "base";
            if atoms(fromAtomIndex).visibility == "bonded" || ...
                    atoms(toAtomIndex).visibility == "bonded"
                visibility = "bonded";
            end
            instance = kssolv.ui.crystal.CrystalSceneSerializer.bond( ...
                normalized, relationIndex, numel(bonds) + 1, ...
                fromImage, toImage, structure, visibility);
            bonds(end + 1) = instance;
            bondKeys(end + 1) = geometryKey;
        end

        function value = bondGeometryKey(firstSite, firstImage, ...
                secondSite, secondImage)
            first = string(firstSite) + "@" + join(string(firstImage), ",");
            second = string(secondSite) + "@" + join(string(secondImage), ",");
            pair = sort([first, second]);
            value = pair(1) + "::" + pair(2);
        end

        function [atoms, keys] = addAtom( ...
                atoms, keys, structure, siteIndex, image, visibility)
            key = string(siteIndex) + "@" + join(string(image), ",");
            if any(keys == key), return, end
            position = structure.lattice.get_cartesian_coords( ...
                structure(siteIndex).frac_coords + image);
            atoms(end + 1) = ...
                kssolv.ui.crystal.CrystalSceneSerializer.atom( ...
                siteIndex, image, position, visibility);
            keys(end + 1) = key;
        end

        function images = boundaryImages(frac, repeat, tolerance)
            choices = cell(1, 3);
            for axis = 1:3
                choices{axis} = 0;
                if frac(axis) <= tolerance
                    choices{axis}(end + 1) = repeat(axis);
                elseif frac(axis) >= 1 - tolerance
                    choices{axis}(end + 1) = -1;
                end
            end
            images = zeros(0, 3);
            for a = choices{1}
                for b = choices{2}
                    for c = choices{3}
                        image = [a, b, c];
                        if any(image ~= 0)
                            images(end + 1, :) = image; %#ok<AGROW>
                        end
                    end
                end
            end
        end

        function polyhedra = buildPolyhedra( ...
                structure, graph, repeat, schemes)
            polyhedra = struct("id", {}, "centerSiteIndex", {}, ...
                "center", {}, "vertices", {}, "color", {}, ...
                "visibility", {});
            for siteIndex = 1:structure.num_sites
                if ~structure(siteIndex).is_ordered, continue, end
                connected = graph.get_connected_sites(siteIndex);
                if numel(connected) < 4, continue, end
                centerX = structure(siteIndex).specie.X;
                neighborX = cellfun(@(item) ...
                    item.site.species.average_electroneg, connected);
                finiteNeighbors = isfinite(neighborX);
                if isfinite(centerX) && ...
                        any(neighborX(finiteNeighbors) <= centerX)
                    continue
                end
                symbol = char(structure(siteIndex).specie.symbol);
                colorValue = [190, 190, 190];
                if isfield(schemes.VESTA, symbol)
                    colorValue = schemes.VESTA.(symbol);
                end
                for a = 0:repeat(1)-1
                    for b = 0:repeat(2)-1
                        for c = 0:repeat(3)-1
                            image = [a, b, c];
                            center = structure.lattice. ...
                                get_cartesian_coords( ...
                                structure(siteIndex).frac_coords + image);
                            % Crystal Toolkit includes the center in the
                            % convex-hull input.  It is normally internal for
                            % tetrahedral/octahedral sites, but is required for
                            % lower-symmetry pyramids where the center is a hull
                            % vertex.
                            vertices = zeros(numel(connected) + 1, 3);
                            vertices(1, :) = center;
                            outside = false;
                            for neighborIndex = 1:numel(connected)
                                neighbor = connected{neighborIndex};
                                neighborImage = image + neighbor.jimage;
                                vertices(neighborIndex + 1, :) = ...
                                    structure.lattice.get_cartesian_coords( ...
                                    structure(neighbor.index).frac_coords + ...
                                    neighborImage);
                                outside = outside || ...
                                    any(neighborImage < 0 | ...
                                    neighborImage >= repeat);
                            end
                            visibility = "base";
                            if outside, visibility = "bonded"; end
                            polyhedra(end + 1) = ...
                                kssolv.ui.crystal.CrystalSceneSerializer. ...
                                polyhedron( ...
                                "polyhedron-" + string(numel(polyhedra)), ...
                                siteIndex, center, unique(vertices, "rows"), ...
                                colorValue, visibility); %#ok<AGROW>
                        end
                    end
                end
            end
        end
    end
end
