classdef Header < handle
 %#ok<*AGROW,*CPROP>
 %HEADER FEFF structural header.
 properties,struct=[];source string="";comment string="None given";periodic=false;space_group=[];space_number=[];spacegroup_analyzer_settings struct=struct();end
 properties(Dependent),structure_symmetry;formula;end
 methods
  function obj=Header(structure,source,comment,varargin)
   if nargin==0,return,end;if nargin<2,source="";end;if nargin<3||strlength(string(comment))==0,comment="None given";end
   obj.struct=structure;obj.source=string(source);obj.comment=string(comment);
   if ~isempty(varargin)&&isstruct(varargin{1}),obj.spacegroup_analyzer_settings=varargin{1};end
   obj.periodic=isa(structure,"kssolv.analysis.matgenlab.core.Structure");
   if obj.periodic
    symprec=0.01;angle=5;if isfield(obj.spacegroup_analyzer_settings,"symprec"),symprec=obj.spacegroup_analyzer_settings.symprec;end;if isfield(obj.spacegroup_analyzer_settings,"angle_tolerance"),angle=obj.spacegroup_analyzer_settings.angle_tolerance;end
    analyzer=kssolv.analysis.matgenlab.symmetry.analyzer.SpacegroupAnalyzer(structure,symprec,angle);
    obj.space_group=analyzer.get_space_group_symbol();obj.space_number=analyzer.get_space_group_number();
   end
  end
  function v=get.structure_symmetry(obj),v={obj.space_group,obj.space_number};end
  function v=get.formula(obj),v=obj.struct.composition.formula;end
  function value=get_str(obj)
   lines=["* This FEFF.inp file generated by pymatgen";"TITLE comment: "+obj.comment;"TITLE Source:  "+obj.source; ...
    "TITLE Structure Summary:  "+obj.struct.composition.formula;"TITLE Reduced formula:  "+obj.struct.composition.reduced_formula];
   if obj.periodic
    abc=obj.struct.lattice.abc;angles=obj.struct.lattice.angles;
    lines(end+1)="TITLE space group: ("+string(obj.space_group)+"), space number:  ("+string(obj.space_number)+")";
    lines(end+1)=sprintf("TITLE abc:%10.6f %10.6f %10.6f",abc(1),abc(2),abc(3));
    lines(end+1)=sprintf("TITLE angles:%10.6f %10.6f %10.6f",angles(1),angles(2),angles(3));
   end
   lines(end+1)="TITLE sites: "+obj.struct.num_sites;
   for i=1:obj.struct.num_sites,site=obj.struct.sites{i};if obj.periodic,coords=site.frac_coords;else,coords=site.coords;end;lines(end+1)=sprintf("* %d %s %12.6f %12.6f %12.6f",i,site.species_string,coords(1),coords(2),coords(3));end
   value=char(join(lines,newline));
  end
  function value=char(obj),value=obj.get_str();end
  function value=string(obj),value=string(obj.get_str());end
  function value=write_file(obj,filename),if nargin<2,filename="HEADER";end;fid=fopen(filename,"w");if fid<0,error("KSSOLV:Matgenlab:Feff:Write","Cannot open output file.");end;c=onCleanup(@()fclose(fid));fprintf(fid,"%s\n",obj.get_str());value=string(filename);end
  function value=as_dict(obj),value=struct("x_module","pymatgen.io.feff.inputs","x_class","Header","struct",obj.struct.as_dict(),"source",obj.source,"comment",obj.comment,"space_group",obj.space_group,"space_number",obj.space_number,"periodic",obj.periodic,"spacegroup_analyzer_settings",obj.spacegroup_analyzer_settings);end
 end
 methods(Static)
  function obj=from_cif_file(filename,source,comment),if nargin<2,source="";end;if nargin<3,comment="";end;s=kssolv.analysis.matgenlab.core.Structure.from_file(filename);obj=kssolv.analysis.matgenlab.io.feff.Header(s,source,comment);end
  function obj=from_file(filename),obj=kssolv.analysis.matgenlab.io.feff.Header.from_str(kssolv.analysis.matgenlab.io.feff.Header.header_string_from_file(filename));end
  function value=header_string_from_file(filename),if nargin<1,filename="feff.inp";end;text=kssolv.analysis.matgenlab.io.feff.feff_read_text(filename);lines=splitlines(string(text));if isempty(lines),value="";return,end;if contains(lines(1),"pymatgen"),n=str2double(extractAfter(lines(9),":"));value=char(join(lines(1:min(numel(lines),n+9)),newline));else,keep=false(size(lines));for i=1:numel(lines),line=lines(i);if strlength(line)>0&&(startsWith(line,"*")||startsWith(line,"TITLE")),keep(i)=true;else,break,end,end;value=char(join(lines(keep),newline));end;end
  function obj=from_str(text)
   lines=splitlines(string(text));lines=lines(strlength(strtrim(lines))>0);if isempty(lines)||~contains(lines(1),"pymatgen"),error("KSSOLV:Matgenlab:Feff:Header","Header not generated by pymatgen.");end
   comment=strtrim(extractAfter(lines(2),"comment:"));source=strtrim(extractAfter(lines(3),"Source:"));n=str2double(strtrim(extractAfter(lines(9),":")));
   abc=sscanf(char(extractAfter(lines(7),":")),"%f").';angles=sscanf(char(extractAfter(lines(8),":")),"%f").';
   lattice=kssolv.analysis.matgenlab.core.Lattice.from_parameters(abc(1),abc(2),abc(3),angles(1),angles(2),angles(3));
   species=cell(1,n);coords=zeros(n,3);for i=1:n,t=split(strtrim(lines(9+i)));species{i}=char(t(3));coords(i,:)=str2double(t(4:6));end
   structure=kssolv.analysis.matgenlab.core.Structure(lattice,species,coords);obj=kssolv.analysis.matgenlab.io.feff.Header(structure,source,comment);
   sg=regexp(char(lines(6)),'space group:\s*\((.*?)\), space number:\s*\((\d+)\)','tokens','once');if ~isempty(sg),obj.space_group=string(sg{1});obj.space_number=str2double(sg{2});end
  end
  function obj=from_dict(d),if isfield(d.struct,"x_class")&&string(d.struct.x_class)=="Molecule",s=kssolv.analysis.matgenlab.core.Molecule.from_dict(d.struct);else,s=kssolv.analysis.matgenlab.core.Structure.from_dict(d.struct);end;obj=kssolv.analysis.matgenlab.io.feff.Header(s,d.source,d.comment,d.spacegroup_analyzer_settings);if isfield(d,"space_group"),obj.space_group=d.space_group;end;if isfield(d,"space_number"),obj.space_number=d.space_number;end;end
 end
end
