classdef MITAqueousCompatibility < kssolv.analysis.matgenlab.analysis.compatibility.CorrectionsList
    %MITAQUEOUSCOMPATIBILITY Frozen legacy MIT aqueous scheme.
    properties
        compat_type (1,1) string = "Advanced"
        correct_peroxide (1,1) logical = true
        check_potcar_hash (1,1) logical = false
    end
    methods
        function obj=MITAqueousCompatibility(varargin)
            options=struct(compat_type="Advanced",correct_peroxide=true, ...
                check_potcar_hash=false);
            options=kssolv.analysis.matgenlab.analysis.compatibility. ...
                internal.options(options,varargin);
            file=kssolv.analysis.matgenlab.analysis.compatibility.internal. ...
                config_path("MITCompatibility.yaml");
            corrections={ ...
                kssolv.analysis.matgenlab.analysis.compatibility. ...
                    PotcarCorrection("MIT","check_hash",options.check_potcar_hash), ...
                kssolv.analysis.matgenlab.analysis.compatibility.GasCorrection(file), ...
                kssolv.analysis.matgenlab.analysis.compatibility. ...
                    AnionCorrection(file,"correct_peroxide",options.correct_peroxide), ...
                kssolv.analysis.matgenlab.analysis.compatibility. ...
                    UCorrection(file,"MIT",options.compat_type), ...
                kssolv.analysis.matgenlab.analysis.compatibility.AqueousCorrection(file)};
            obj@kssolv.analysis.matgenlab.analysis.compatibility. ...
                CorrectionsList(corrections);
            obj.compat_type=string(options.compat_type);
            obj.correct_peroxide=options.correct_peroxide;
            obj.check_potcar_hash=options.check_potcar_hash;
        end
    end
end
