classdef ProvenanceTest < matlab.unittest.TestCase
    methods (Test)
        function authorsMatchOfficialAcceptedForms(testCase)
            structure=fixtureStructure("Fe");
            reference=fixtureReference();
            hulk=struct("name","Hulk","email","hulk@avengers.com");
            value=kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,hulk,{},reference);
            testCase.verifyEqual(value.authors{1}.name,"Hulk");
            value=kssolv.analysis.matgenlab.util.StructureNL( ...
                structure, ...
                "Captain America <captainamerica@avengers.com>",{}, ...
                reference);
            testCase.verifyEqual(value.authors{1}.email, ...
                "captainamerica@avengers.com");
            value=kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,{{"Thor","thor@avengers.com"}},{},reference);
            testCase.verifyEqual(value.authors{1}.name,"Thor");
            value=kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,"Iron Man <ironman@avengers.com>, " + ...
                "Black Widow <blackwidow@avengers.com>",{},reference);
            testCase.verifyEqual(numel(value.authors),2);
            testCase.verifyEqual(value.authors{2}.name,"Black Widow");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.Author. ...
                parse_author("missing email"), ...
                "KSSOLV:Matgenlab:Author:Format");
        end

        function referencesMatchOfficialValidation(testCase)
            structure=fixtureStructure("Fe");authors=fixtureAuthors();
            materialProject=['@misc{MaterialsProject,' newline ...
                'title={{Materials Project}},' newline ...
                'url={https://materialsproject.org}}'];
            unicode="@misc{Unicode_Title,title={{A 玫 is a rose}}}";
            combined=join([string(materialProject),unicode],newline);
            testCase.verifyTrue( ...
                kssolv.analysis.matgenlab.util.is_valid_bibtex( ...
                combined));
            kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},"");
            kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},combined);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},[]), ...
                "KSSOLV:Matgenlab:StructureNL:ReferenceType");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},"This is junk text"), ...
                "KSSOLV:Matgenlab:StructureNL:Reference");
            tooLong=['@misc{SuperLong,title={' ...
                repmat('REPEAT',1,4000) '}}'];
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},tooLong), ...
                "KSSOLV:Matgenlab:StructureNL:ReferenceSize");
        end

        function historyDataAndRemarksEnforceOfficialLimits(testCase)
            structure=fixtureStructure("Fe");authors=fixtureAuthors();
            node=kssolv.analysis.matgenlab.util.HistoryNode( ...
                "DB 1","www.db1URLgoeshere.com",struct("db1_id",12424));
            node2=struct("name","DB 2", ...
                "url","www.db2URLgoeshere.com", ...
                "description",struct("db2_id",12424));
            data=containers.Map({'_structure'},{fixtureStructure("Al")});
            value=kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},"","string format",data,{node,node2});
            testCase.verifyEqual(value.remarks,{'string format'});
            testCase.verifyEqual(value.history{2}.name,"DB 2");
            testCase.verifyTrue(value.data("_structure")== ...
                fixtureStructure("Al"));
            invalid=struct("name","DB 3","url","www.db3.com");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},"",{},struct(),{invalid}), ...
                "KSSOLV:Matgenlab:HistoryNode:Fields");
            tooMany=repmat({node},1,101);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},"",{},struct(),tooMany), ...
                "KSSOLV:Matgenlab:StructureNL:HistoryCount");
            badData=struct("bad_key",1);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},"",{},badData), ...
                "KSSOLV:Matgenlab:StructureNL:Namespace");
            longRemark=repmat('a',1,141);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,authors,{},"",longRemark), ...
                "KSSOLV:Matgenlab:StructureNL:RemarkSize");
        end

        function structureAndMoleculeMSONRoundTrips(testCase)
            structure=fixtureStructure("Fe");
            node=struct("name","DB","url","www.db.com", ...
                "description",struct("id",42));
            data=containers.Map({'_my_data'},{'string'});
            original=kssolv.analysis.matgenlab.util.StructureNL( ...
                structure,fixtureAuthors(),{"test_project"}, ...
                fixtureReference(),{"remark1"},data,{node}, ...
                "2026-07-27 00:00:00.000000+0000");
            direct=kssolv.analysis.matgenlab.util.StructureNL. ...
                from_dict(original.as_dict());
            testCase.verifyTrue(original==direct);
            encoded=kssolv.analysis.matgenlab.util.encode(original);
            testCase.verifySubstring(encoded,'"_my_data":"string"');
            decoded=kssolv.analysis.matgenlab.util.decode(encoded);
            testCase.verifyClass(decoded, ...
                "kssolv.analysis.matgenlab.util.StructureNL");
            testCase.verifyTrue(original==decoded);

            molecule=kssolv.analysis.matgenlab.core.Molecule( ...
                "He",[0,0,0]);
            molNL=kssolv.analysis.matgenlab.util.StructureNL( ...
                molecule,fixtureAuthors(),{},fixtureReference());
            restored=kssolv.analysis.matgenlab.util.StructureNL. ...
                from_dict(molNL.as_dict());
            testCase.verifyClass(restored.structure, ...
                "kssolv.analysis.matgenlab.core.Molecule");
            testCase.verifyTrue(molNL==restored);
        end

        function equalityAndFromStructuresMatchOfficialBehavior(testCase)
            first=fixtureStructure("Fe");second=fixtureStructure("Mn");
            authors="Test User <test@materialsproject.com>";
            values=kssolv.analysis.matgenlab.util.StructureNL. ...
                from_structures({first,second},authors,{}, ...
                "",{"unittest"});
            testCase.verifyEqual(numel(values),2);
            testCase.verifyEqual(values{1}.remarks,{'unittest'});
            testCase.verifyTrue(values{1}.authors{1}== ...
                kssolv.analysis.matgenlab.util.Author. ...
                parse_author(authors));
            timestamp="2026-07-27 00:00:00.000000+0000";
            same1=kssolv.analysis.matgenlab.util.StructureNL( ...
                first,fixtureAuthors(),{},"",{},struct(),{},timestamp);
            same2=kssolv.analysis.matgenlab.util.StructureNL( ...
                first,fixtureAuthors(),{},"",{},struct(),{},timestamp);
            changed=kssolv.analysis.matgenlab.util.StructureNL( ...
                second,fixtureAuthors(),{},"",{},struct(),{},timestamp);
            testCase.verifyTrue(same1==same2);
            testCase.verifyFalse(same1==changed);
        end
    end
end

function value=fixtureStructure(species)
value=kssolv.analysis.matgenlab.core.Structure( ...
    kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
    species,[0,0,0]);
end

function value=fixtureAuthors()
value=struct("name","Hulk","email","hulk@avengers.com");
end

function value=fixtureReference()
value="@article{Ong2013,title={{Python Materials Genomics}},year={2013}}";
end
