classdef StringUtilsTest < matlab.unittest.TestCase
    methods (Test)
        function stringifyModes(testCase)
            sub = kssolv.analysis.matgenlab.test.util.StringifyFixture("Fe8O12");
            testCase.verifyEqual(sub.to_latex_string(), "Fe$_{8}$O$_{12}$");
            testCase.verifyEqual(sub.to_html_string(), ...
                "Fe<sub>8</sub>O<sub>12</sub>");
            testCase.verifyEqual(sub.to_unicode_string(), "Fe₈O₁₂");
            sup = kssolv.analysis.matgenlab.test.util.StringifyFixture( ...
                "Fe2+", "SUPERSCRIPT");
            testCase.verifyEqual(sup.to_latex_string(), "Fe$^{2+}$");
            testCase.verifyEqual(sup.to_unicode_string(), "Fe²⁺");
        end

        function formulaFormatting(testCase)
            u = "kssolv.analysis.matgenlab.util.";
            testCase.verifyEqual(feval(u + "latexify", "Li3Fe2(PO4)3"), ...
                "Li$_{3}$Fe$_{2}$(PO$_{4}$)$_{3}$");
            testCase.verifyEqual(feval(u + "htmlify", "Li0.2Na0.8Cl"), ...
                "Li<sub>0.2</sub>Na<sub>0.8</sub>Cl");
            testCase.verifyEqual(feval(u + "unicodeify", "Li3Fe2(PO4)3"), ...
                "Li₃Fe₂(PO₄)₃");
            testCase.verifyEqual(feval(u + "unicodeify_species", "O2+"), "O²⁺");
            testCase.verifyEqual(feval(u + "latexify_spacegroup", "Fd-3m"), ...
                "Fd$\overline{3}$m");
            testCase.verifyEqual(feval(u + "unicodeify_spacegroup", "F-3m"), ...
                "F3̅m");
        end

        function coefficientAndChargeFormatting(testCase)
            u = "kssolv.analysis.matgenlab.util.";
            testCase.verifyEqual(feval(u + "formula_double_format", 1), "");
            testCase.verifyEqual(feval(u + "formula_double_format", 2.1), 2.1);
            testCase.verifyEqual(feval(u + "charge_string", 1), "[+1]");
            testCase.verifyEqual(feval(u + "charge_string", -1, false, false), "-");
            testCase.verifyEqual(feval(u + "charge_string", 0), "(aq)");
        end

        function transformationFormatting(testCase)
            u = "kssolv.analysis.matgenlab.util.";
            testCase.verifyEqual(feval(u + "transformation_to_string", eye(3)), ...
                "x,y,z");
            testCase.verifyEqual(feval(u + "transformation_to_string", ...
                eye(3), [0 0 0], ["a","b","c"]), "a,b,c");
            matrix = [-1/2 -2/3 -3/4; -5/6 -6/7 -7/8; ...
                -8/9 -9/10 -10/11];
            translation = [-11/12 -12/13 -13/14];
            expected = "-x/2-2y/3-3z/4-11/12," + ...
                "-5x/6-6y/7-7z/8-12/13," + ...
                "-8x/9-9y/10-10z/11-13/14";
            testCase.verifyEqual(feval(u + "transformation_to_string", ...
                matrix, translation), expected);
        end

        function delimitedString(testCase)
            actual = kssolv.analysis.matgenlab.util.str_delimited( ...
                {"a","b","c"; "d","e","f"; 1,2,3}, [], ",");
            testCase.verifyEqual(actual, "a,b,c" + newline + ...
                "d,e,f" + newline + "1,2,3");
        end

        function disorderedFormula(testCase)
            site = kssolv.analysis.matgenlab.core.Site( ...
                struct(Cu=.25, Au=.75), [0 0 0]);
            fixture = kssolv.analysis.matgenlab.test.util. ...
                DisorderedStructureFixture({site}, ...
                kssolv.analysis.matgenlab.core.Composition( ...
                struct(Cu=.25, Au=.75)));
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.util.disordered_formula(fixture), ...
                "CuxAu1-x x=0.25");
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.util.disordered_formula( ...
                fixture, ["x","y","z"], "LaTeX"), ...
                "Cu_{x}Au_{1-x} x=0.25");
        end
    end
end
