classdef UtilOracleParityTest < matlab.unittest.TestCase
    methods (TestMethodSetup)
        function requireFrozenOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                isAvailable(), ...
                "Set MATGENLAB_PYTHON to a frozen pymatgen-core environment.");
        end
    end

    methods (Test)
        function coordinateFunctionsMatch(testCase)
            oracle = @kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute;
            request = struct( ...
                module="pymatgen.util.coord", ...
                symbol="pbc_diff", ...
                operations={{struct(kind="call", args={{ ...
                [100.1 .2 .3], [123123.4 .5 502312.6]}})}});
            response = oracle(request);
            actual = kssolv.analysis.matgenlab.util.pbc_diff( ...
                [100.1 .2 .3], [123123.4 .5 502312.6]);
            expected = kssolv.analysis.matgenlab.test.util. ...
                UtilOracleParityTest.firstResult(response);
            expected = reshape(expected, size(actual));
            testCase.verifyEqual(actual, expected, AbsTol=1e-12);

            frac = [.3 .3 .5; .1 .1 .3; .9 .9 .8; .1 0 .5; .9 .7 0];
            request = struct( ...
                module="pymatgen.core.lattice", symbol="Lattice", ...
                construct=struct(method="from_parameters", ...
                args={{8, 8, 4, 90, 76, 58}}), ...
                operations={{struct(kind="call", name="get_all_distances", ...
                args={{frac(1:4, :), frac}})}});
            response = oracle(request);
            lattice = kssolv.analysis.matgenlab.core.Lattice.from_parameters( ...
                8, 8, 4, 90, 76, 58);
            vectors = kssolv.analysis.matgenlab.util.pbc_shortest_vectors( ...
                lattice, frac(1:4, :), frac);
            actual = sqrt(sum(vectors.^2, 3));
            expected = kssolv.analysis.matgenlab.test.util. ...
                UtilOracleParityTest.firstResult(response);
            expected = reshape(expected, size(actual));
            testCase.verifyEqual(actual, expected, AbsTol=1e-11);

            request = struct( ...
                module="pymatgen.util.coord", ...
                symbol="lattice_points_in_supercell", ...
                operations={{struct(kind="call", args={{ ...
                [1 3 5; -3 2 3; -5 3 1]}})}});
            response = oracle(request);
            actual = kssolv.analysis.matgenlab.util. ...
                lattice_points_in_supercell([1 3 5; -3 2 3; -5 3 1]);
            expected = kssolv.analysis.matgenlab.test.util. ...
                UtilOracleParityTest.firstResult(response);
            expected = reshape(expected, size(actual));
            testCase.verifyEqual(actual, expected, AbsTol=1e-12);
        end

        function numericalFunctionsMatch(testCase)
            oracle = @kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute;
            values = [424.2425, 2.3425356, 0.000042535636653, ...
                .23, 2.468e6, 0, -1.392156];
            for value = values
                for sig = 1:5
                    request = struct( ...
                        module="pymatgen.util.num", ...
                        symbol="round_to_sigfigs", ...
                        operations={{struct(kind="call", ...
                        args={{value, sig}})}});
                    response = oracle(request);
                    actual = kssolv.analysis.matgenlab.util. ...
                        round_to_sigfigs(value, sig);
                    expected = kssolv.analysis.matgenlab.test.util. ...
                        UtilOracleParityTest.firstResult(response);
                    testCase.verifyEqual(actual, expected, ...
                        RelTol=1e-14, AbsTol=1e-14);
                end
            end
        end

        function stringFunctionsMatch(testCase)
            oracle = @kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute;
            symbols = ["latexify", "htmlify", "unicodeify", ...
                "latexify_spacegroup", "unicodeify_spacegroup", ...
                "unicodeify_species"];
            inputs = ["Li3Fe2(PO4)3", "Li3Fe2(PO4)3", ...
                "Li3Fe2(PO4)3", "Fd-3m", "F-3m", "O2+"];
            for idx = 1:numel(symbols)
                request = struct( ...
                    module="pymatgen.util.string", ...
                    symbol=symbols(idx), ...
                    operations={{struct(kind="call", ...
                    args={{inputs(idx)}})}});
                response = oracle(request);
                actual = feval("kssolv.analysis.matgenlab.util." + ...
                    symbols(idx), inputs(idx));
                testCase.verifyEqual(actual, string(response.results{1}));
            end

            matrix = [-1/2 -2/3 -3/4; -5/6 -6/7 -7/8; ...
                -8/9 -9/10 -10/11];
            translation = [-11/12 -12/13 -13/14];
            request = struct(module="pymatgen.util.string", ...
                symbol="transformation_to_string", ...
                operations={{struct(kind="call", ...
                args={{matrix, translation}})}});
            response = oracle(request);
            actual = kssolv.analysis.matgenlab.util. ...
                transformation_to_string(matrix, translation);
            testCase.verifyEqual(actual, string(response.results{1}));
        end

        function simplexMatches(testCase)
            coords = [0 2; 3 1; 1 0];
            point = [.7 .5];
            request = struct(module="pymatgen.util.coord", symbol="Simplex", ...
                construct=struct(args={{coords}}), ...
                operations={{ ...
                struct(kind="get", name="volume"), ...
                struct(kind="call", name="bary_coords", args={{point}}), ...
                struct(kind="call", name="line_intersection", ...
                args={{point, [.5 .7]}})}});
            response = kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            simplex = kssolv.analysis.matgenlab.util.Simplex(coords);
            testCase.verifyEqual(simplex.volume, response.results{1}, ...
                AbsTol=1e-14);
            testCase.verifyEqual(simplex.bary_coords(point), ...
                reshape(response.results{2}, 1, []), AbsTol=1e-13);
            expected = squeeze(response.results{3});
            testCase.verifyEqual(simplex.line_intersection(point, [.5 .7]), ...
                expected, AbsTol=1e-12);
        end
    end

    methods (Static, Access = private)
        function value = firstResult(response)
            value = response.results;
            if iscell(value), value = value{1}; end
        end
    end
end
