function symbol=potcar_symbol(element,kind)
%POTCAR_SYMBOL Expected symbol in frozen MP/MIT VASP input sets.
element=string(element); symbol=element;
if upper(string(kind))=="MP"
    keys=["Ba","Be","Ca","Cr","Cs","Cu","Fe","Ga","Ge","Hf","In", ...
        "K","Li","Mg","Mn","Mo","Na","Nb","Ni","Os","Pb","Rb","Re", ...
        "Rh","Ru","Sc","Sn","Sr","Ta","Tc","Ti","Tl","V","W","Y","Zr"];
    vals=["Ba_sv","Be_sv","Ca_sv","Cr_pv","Cs_sv","Cu_pv","Fe_pv", ...
        "Ga_d","Ge_d","Hf_pv","In_d","K_sv","Li_sv","Mg_pv", ...
        "Mn_pv","Mo_pv","Na_pv","Nb_pv","Ni_pv","Os_pv","Pb_d", ...
        "Rb_sv","Re_pv","Rh_pv","Ru_pv","Sc_sv","Sn_d","Sr_sv", ...
        "Ta_pv","Tc_pv","Ti_pv","Tl_d","V_pv","W_pv","Y_sv","Zr_sv"];
else
    keys=["Ba","Ca","Cs","Dy","Er","Ho","K","Lu","Mo","Nb","Rb", ...
        "Ru","Sc","Sm","Sn","Sr","Tb"];
    vals=["Ba_sv","Ca_sv","Cs_sv","Dy_3","Er_3","Ho_3","K_sv", ...
        "Lu_3","Mo_pv","Nb_pv","Rb_pv","Ru_pv","Sc_sv","Sm_3", ...
        "Sn_d","Sr_sv","Tb_3"];
end
index=find(keys==element,1);
if ~isempty(index),symbol=vals(index);end
end
