classdef RemoteJobRecord
    %REMOTEJOBRECORD Schema for a persistent KSSOLV remote job.

    properties (Constant)
        FormatVersion = 2
        States = ["Created", "Preparing", "Authenticating", ...
            "Submitting", "Queued", "Running", "Finished", ...
            "Fetching", "Retrieved", "Failed", "Cancelling", ...
            "Cancelled", "ConnectionRequired", "Unknown"]
    end

    methods (Static)
        function value = create(configurationId, workflowName, projectIdentity)
            arguments
                configurationId (1, 1) string
                workflowName (1, 1) string = ""
                projectIdentity (1, 1) string = ""
            end
            nowText = string(datetime("now", "TimeZone", "UTC", ...
                "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
            value = struct( ...
                "Version", 2, ...
                "LocalJobId", ...
                    kssolv.services.remote.config.RemoteConfiguration.newId(), ...
                "ConfigurationId", strip(configurationId), ...
                "ExecutionMode", "Standard", ...
                "CloudProvider", "", ...
                "BackendProtocolVersion", 2, ...
                "ConfigurationSnapshot", struct(), ...
                "BridgeMatlabRelease", "", ...
                "MatlabProfileName", "", ...
                "MatlabJobId", NaN, ...
                "SchedulerJobIds", strings(0, 1), ...
                "WorkflowName", strip(workflowName), ...
                "ProjectIdentity", strip(projectIdentity), ...
                "BundlePath", "", ...
                "BundleContentHash", "", ...
                "RemoteToolboxRoot", "", ...
                "RemoteWorkspace", "", ...
                "SubmittedAt", "", ...
                "CreatedAt", nowText, ...
                "LastCheckedAt", nowText, ...
                "State", "Created", ...
                "ResultImported", false, ...
                "ErrorIdentifier", "", ...
                "ErrorSummary", "", ...
                "Diary", "");
        end

        function value = normalize(value)
            arguments
                value struct
            end
            if ~isscalar(value)
                error("KSSOLV:Remote:JobRecordNotScalar", ...
                    "A remote job record must be scalar.");
            end
            if (~isfield(value, "ExecutionMode") || ...
                    strlength(string(value.ExecutionMode)) == 0) && ...
                    isfield(value, "SubmissionMode") && ...
                    string(value.SubmissionMode) == "RemoteMatlabBridge"
                value.ExecutionMode = "Bridge";
            end
            defaults = kssolv.services.remote.job.RemoteJobRecord.create("", "", "");
            names = fieldnames(defaults);
            normalized = defaults;
            for index = 1:numel(names)
                name = names{index};
                if isfield(value, name) && ~isempty(value.(name))
                    normalized.(name) = value.(name);
                end
            end
            stringFields = ["LocalJobId", "ConfigurationId", ...
                "ExecutionMode", "CloudProvider", ...
                "BridgeMatlabRelease", ...
                "MatlabProfileName", "WorkflowName", ...
                "ProjectIdentity", "BundlePath", "BundleContentHash", ...
                "RemoteToolboxRoot", "RemoteWorkspace", ...
                "SubmittedAt", "CreatedAt", "LastCheckedAt", "State", ...
                "ErrorIdentifier", "ErrorSummary", "Diary"];
            for name = stringFields
                item = string(normalized.(name));
                if ~isscalar(item)
                    item = item(1);
                end
                normalized.(name) = item;
            end
            normalized.Version = 2;
            normalized.BackendProtocolVersion = ...
                double(normalized.BackendProtocolVersion);
            normalized.MatlabJobId = double(normalized.MatlabJobId);
            schedulerIds = normalized.SchedulerJobIds;
            if ischar(schedulerIds)
                schedulerIds = string(schedulerIds);
            else
                schedulerIds = string(schedulerIds(:));
            end
            normalized.SchedulerJobIds = schedulerIds;
            normalized.ResultImported = logical(normalized.ResultImported);
            if ~isempty(fieldnames(normalized.ConfigurationSnapshot))
                normalized.ConfigurationSnapshot = ...
                    kssolv.services.remote.config.RemoteConfiguration. ...
                    withoutCredentials( ...
                    normalized.ConfigurationSnapshot);
            end
            value = normalized;
        end

        function validate(value)
            value = kssolv.services.remote.job.RemoteJobRecord.normalize(value);
            if strlength(value.LocalJobId) == 0 || ...
                    strlength(value.ConfigurationId) == 0
                error("KSSOLV:Remote:InvalidJobRecord", ...
                    "A job record requires local and configuration IDs.");
            end
            if ~any(value.ExecutionMode == ...
                    kssolv.services.remote.config.RemoteConfiguration.ExecutionModes)
                error("KSSOLV:Remote:InvalidExecutionMode", ...
                    "Unsupported remote execution mode %s.", ...
                    value.ExecutionMode);
            end
            if ~any(value.State == ...
                    kssolv.services.remote.job.RemoteJobRecord.States)
                error("KSSOLV:Remote:InvalidJobState", ...
                    "Unsupported remote job state %s.", value.State);
            end
        end
    end
end
