classdef PackmolBoxGen < kssolv.analysis.matgenlab.io.InputGenerator
    %PACKMOLBOXGEN Generate PACKMOL inputs for rectangular boxes.
    %#ok<*AGROW>

    properties
        tolerance (1,1) double = 2
        seed (1,1) double = 1
        control_params = struct()
        inputfile (1,1) string = "packmol.inp"
        outputfile (1,1) string = "packmol_out.xyz"
        stdoutfile (1,1) string = "packmol.stdout"
        executor = []
    end

    methods
        function obj = PackmolBoxGen(options)
            arguments
                options.tolerance (1,1) double = 2
                options.seed (1,1) double = 1
                options.control_params = struct()
                options.inputfile (1,1) string = "packmol.inp"
                options.outputfile (1,1) string = "packmol_out.xyz"
                options.stdoutfile (1,1) string = "packmol.stdout"
                options.executor = []
            end
            obj.tolerance = options.tolerance;
            obj.seed = options.seed;
            obj.control_params = options.control_params;
            obj.inputfile = options.inputfile;
            obj.outputfile = options.outputfile;
            obj.stdoutfile = options.stdoutfile;
            obj.executor = options.executor;
            if ~isempty(obj.executor) && ~isa(obj.executor, "function_handle")
                error("KSSOLV:Matgenlab:Packmol:ExecutorType", ...
                    "executor must be a MATLAB function handle.");
            end
        end

        function inputSet = get_input_set(obj, molecules, box)
            if nargin < 3, box = []; end
            molecules = normalizeMolecules(molecules);
            names = strings(1, numel(molecules));
            for index = 1:numel(molecules)
                requireFields(molecules{index}, ["name", "number", "coords"]);
                names(index) = string(molecules{index}.name);
            end
            if numel(unique(names)) ~= numel(names)
                error("KSSOLV:Matgenlab:Packmol:DuplicateNames", ...
                    "Names of the molecules should all be different.");
            end

            descriptions = strings(1, numel(molecules));
            for index = 1:numel(molecules)
                descriptions(index) = pyScalar(molecules{index}.number) + ...
                    " " + names(index);
            end
            lines = ["# Packmol input generated by pymatgen." + newline; ...
                "# " + join(descriptions, " ")];
            if numel(descriptions) > 1
                lines(2) = "# " + join(descriptions, " + ");
            end
            controlLines = renderControlParams(obj.control_params);
            lines = [lines; controlLines; ...
                "seed " + pyScalar(obj.seed); ...
                "tolerance " + pyFloat(obj.tolerance) + newline; ...
                "filetype xyz" + newline];
            if contains(obj.outputfile, " ")
                lines(end + 1) = "output """ + obj.outputfile + """" + newline;
            else
                lines(end + 1) = "output " + obj.outputfile + newline;
            end

            hasConstraints = cellfun(@(item) ...
                hasNonemptyField(item, "constraints"), molecules);
            individualConstraints = all(hasConstraints);
            if ~individualConstraints && any(hasConstraints)
                error("KSSOLV:Matgenlab:Packmol:MixedConstraints", ...
                    "Either specify constraints for all molecules or " + ...
                    "for none of them.");
            end
            hasAtomConstraints = cellfun(@(item) ...
                hasNonemptyField(item, "atoms_constraints"), molecules);
            if any(hasAtomConstraints) && ~individualConstraints
                error("KSSOLV:Matgenlab:Packmol:AtomConstraintsRequireIndividual", ...
                    "You must use individual_constraints to use " + ...
                    "atoms_constraints.");
            end
            if individualConstraints
                validateConstraints(molecules);
            end

            boxList = "";
            if ~isempty(box)
                if individualConstraints
                    error("KSSOLV:Matgenlab:Packmol:BoxAndConstraints", ...
                        "Either specify individual constraints or box.");
                end
                boxList = join(arrayfun(@pyScalar, ...
                    reshape(box, 1, [])), " ");
            elseif ~individualConstraints
                netVolume = 0;
                for index = 1:numel(molecules)
                    molecule = loadMolecule(molecules{index}.coords);
                    spans = max(molecule.cart_coords, [], 1) - ...
                        min(molecule.cart_coords, [], 1);
                    lengthValue = max(spans) + obj.tolerance;
                    netVolume = netVolume + lengthValue ^ 3 * ...
                        double(molecules{index}.number);
                end
                boxLength = netVolume ^ (1 / 3);
                formatted = string(sprintf("%.1f", boxLength));
                boxList = "0.0 0.0 0.0 " + formatted + " " + ...
                    formatted + " " + formatted;
            end

            pairs = cell(0, 2);
            for index = 1:numel(molecules)
                item = molecules{index};
                molecule = loadMolecule(item.coords);
                filename = "packmol_" + string(item.name) + ".xyz";
                pairs(end + 1, :) = {char(filename), ...
                    char(molecule.to("", "xyz"))};
                if contains(filename, " ")
                    lines(end + 1) = "structure '" + filename + "'";
                else
                    lines(end + 1) = "structure " + filename;
                end
                lines(end + 1) = "  number " + pyScalar(item.number);
                if strlength(boxList) > 0
                    lines(end + 1) = "  inside box " + boxList;
                else
                    constraints = stringList(item.constraints);
                    for constraint = reshape(constraints, 1, [])
                        lines(end + 1) = "  " + strtrim(constraint);
                    end
                    if hasNonemptyField(item, "atoms_constraints")
                        atomGroups = normalizeMolecules( ...
                            item.atoms_constraints);
                        for groupIndex = 1:numel(atomGroups)
                            group = atomGroups{groupIndex};
                            requireFields(group, ["indices", "constraints"]);
                            indices = reshape(double(group.indices), 1, []) + 1;
                            lines(end + 1) = "  atoms " + join( ...
                                arrayfun(@pyScalar, indices), " ");
                            atomConstraints = stringList(group.constraints);
                            for constraint = reshape(atomConstraints, 1, [])
                                lines(end + 1) = ...
                                    "    " + strtrim(constraint);
                            end
                            lines(end + 1) = "  end atoms";
                        end
                    end
                end
                lines(end + 1) = "end structure" + newline + newline;
            end
            pairs(end + 1, :) = {char(obj.inputfile), ...
                char(join(lines, newline))};
            inputSet = ...
                kssolv.analysis.matgenlab.io.packmol.PackmolSet( ...
                    pairs, seed = obj.seed, inputfile = obj.inputfile, ...
                    outputfile = obj.outputfile, ...
                    stdoutfile = obj.stdoutfile, ...
                    control_params = obj.control_params, ...
                    tolerance = obj.tolerance, executor = obj.executor);
        end
    end
end

function molecules = normalizeMolecules(value)
if isempty(value)
    molecules = cell(1, 0);
elseif iscell(value)
    molecules = reshape(value, 1, []);
elseif isstruct(value)
    molecules = reshape(num2cell(value), 1, []);
else
    error("KSSOLV:Matgenlab:Packmol:MoleculesType", ...
        "molecules must be a struct array or cell array of structs.");
end
if ~all(cellfun(@isstruct, molecules))
    error("KSSOLV:Matgenlab:Packmol:MoleculesType", ...
        "Each molecule description must be a struct.");
end
end

function requireFields(value, names)
for name = reshape(string(names), 1, [])
    if ~isfield(value, name)
        error("KSSOLV:Matgenlab:Packmol:MissingField", ...
            "Molecule description requires field '%s'.", name);
    end
end
end

function result = hasNonemptyField(value, name)
result = isfield(value, name) && ~isempty(value.(name));
end

function molecule = loadMolecule(value)
if isa(value, "kssolv.analysis.matgenlab.core.Molecule")
    molecule = value;
elseif ischar(value) || (isstring(value) && isscalar(value))
    molecule = kssolv.analysis.matgenlab.core.Molecule. ...
        from_file(string(value));
else
    error("KSSOLV:Matgenlab:Packmol:MoleculeType", ...
        "Molecule is not provided in supported format.");
end
end

function lines = renderControlParams(parameters)
lines = strings(0, 1);
if isempty(parameters), return; end
if isa(parameters, "containers.Map")
    names = string(parameters.keys);
    getter = @(name) parameters(char(name));
elseif isstruct(parameters) && isscalar(parameters)
    names = string(fieldnames(parameters));
    getter = @(name) parameters.(char(name));
else
    error("KSSOLV:Matgenlab:Packmol:ControlParams", ...
        "control_params must be a scalar struct or containers.Map.");
end
for name = reshape(names, 1, [])
    value = getter(name);
    if iscell(value) || (numel(value) > 1 && ...
            (isnumeric(value) || isstring(value)))
        if iscell(value)
            rendered = cellfun(@pyScalar, reshape(value, 1, []));
        else
            rendered = arrayfun(@pyScalar, reshape(value, 1, []));
        end
        lines(end + 1, 1) = ...
            name + " " + join(rendered, " ");
    else
        lines(end + 1, 1) = ...
            name + " " + pyScalar(value);
    end
end
end

function validateConstraints(molecules)
valid = ["fixed", "inside cube", "outside cube", ...
    "inside box", "outside box", "inside sphere", ...
    "outside sphere", "inside ellipsoid", "outside ellipsoid", ...
    "above plane", "below plane", "inside cylinder", ...
    "outside cylinder", "constrain_rotation", "over xygauss", ...
    "below xygauss"];
for index = 1:numel(molecules)
    constraints = stringList(molecules{index}.constraints);
    for constraint = reshape(constraints, 1, [])
        if ~any(contains(constraint, valid))
            error("KSSOLV:Matgenlab:Packmol:Constraint", ...
                "Wrong packmol constraint: %s", constraint);
        end
    end
    if hasNonemptyField(molecules{index}, "atoms_constraints")
        groups = normalizeMolecules(molecules{index}.atoms_constraints);
        for groupIndex = 1:numel(groups)
            requireFields(groups{groupIndex}, ["indices", "constraints"]);
            constraints = stringList(groups{groupIndex}.constraints);
            for constraint = reshape(constraints, 1, [])
                if ~any(contains(constraint, valid))
                    error("KSSOLV:Matgenlab:Packmol:AtomConstraint", ...
                        "Wrong packmol constraint for specific atoms: %s", ...
                        constraint);
                end
            end
        end
    end
end
end

function values = stringList(value)
if isempty(value)
    values = strings(1, 0);
elseif iscell(value)
    values = reshape(string(value), 1, []);
else
    values = reshape(string(value), 1, []);
end
end

function value = pyScalar(input)
if iscell(input) && isscalar(input), input = input{1}; end
if islogical(input) && isscalar(input)
    if input, value = "True"; else, value = "False"; end
elseif isnumeric(input) && isscalar(input)
    value = string(input);
elseif ischar(input) || (isstring(input) && isscalar(input))
    value = string(input);
else
    error("KSSOLV:Matgenlab:Packmol:ParameterValue", ...
        "PACKMOL parameters must contain scalar values.");
end
end

function value = pyFloat(input)
value = string(sprintf("%.15g", double(input)));
if ~contains(lower(value), [".", "e", "nan", "inf"])
    value = value + ".0";
end
end
