function report = CrystalViewer(enforce)
%CRYSTALVIEWER Reproducible crystal scene-compiler performance gates.
if nargin < 1, enforce = true; end

grid = 0:9;
[a, b, c] = ndgrid(grid, grid, grid);
coordinates = [a(:), b(:), c(:)] / 10;
large = kssolv.analysis.matgenlab.core.Structure( ...
    kssolv.analysis.matgenlab.core.Lattice.cubic(30), ...
    repmat({"C"}, 1, size(coordinates, 1)), coordinates);

started = tic;
preview = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
    large, includeConnectivity = false, includePolyhedra = false, ...
    includeBoundaryAtoms = false);
atomsFirstMilliseconds = toc(started) * 1000;

root = fileparts(fileparts(fileparts( ...
    fileparts(fileparts(mfilename("fullpath"))))));
fixture = fullfile(root, "+kssolv", "+analysis", "+matgenlab", ...
    "+test", "+core", "+fixtures", "+local_env", "LiFePO4.json");
lifepo4 = kssolv.analysis.matgenlab.core.Structure.from_file(fixture);
lifepo4 = lifepo4.add_oxidation_state_by_guess();
options = struct("algorithm", "CrystalNN", "cell", "input", ...
    "repeat", [1, 1, 1]);
kssolv.ui.crystal.CrystalSceneCache.clear();
started = tic;
exact = kssolv.ui.crystal.CrystalSceneCache.build( ...
    lifepo4, options, "benchmark-exact");
exactMilliseconds = toc(started) * 1000;
started = tic;
cached = kssolv.ui.crystal.CrystalSceneCache.build( ...
    lifepo4, options, "benchmark-cached");
cachedMilliseconds = toc(started) * 1000;

[mx, my, mz] = ndgrid(0:19, 0:19, 0:11);
moleculeCoordinates = [mx(:), my(:), mz(:)] * 2.5;
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    repmat({"C"}, 1, size(moleculeCoordinates, 1)), ...
    moleculeCoordinates, charge_spin_check = false);
moleculeOptions = struct("algorithm", "OpenBabelNN");
kssolv.ui.crystal.MoleculeSceneCache.clear();
started = tic;
molecular = kssolv.ui.crystal.MoleculeSceneCache.build( ...
    molecule, moleculeOptions, "benchmark-molecule");
moleculeMilliseconds = toc(started) * 1000;
started = tic;
molecularCached = kssolv.ui.crystal.MoleculeSceneCache.build( ...
    molecule, moleculeOptions, "benchmark-molecule-cached");
moleculeCachedMilliseconds = toc(started) * 1000;

report = struct( ...
    "atomsFirstMilliseconds", atomsFirstMilliseconds, ...
    "atomsFirstInstances", numel(preview.atomInstances), ...
    "exactCrystalNNMilliseconds", exactMilliseconds, ...
    "cachedSceneMilliseconds", cachedMilliseconds, ...
    "exactRelations", numel(exact.bondRelations), ...
    "exactInstances", numel(exact.atomInstances), ...
    "moleculeAtoms", numel(molecular.atomInstances), ...
    "moleculeOpenBabelMilliseconds", moleculeMilliseconds, ...
    "moleculeCachedMilliseconds", moleculeCachedMilliseconds, ...
    "serializedBytes", strlength(string(jsonencode(exact))));
disp(struct2table(report, "AsArray", true));

if enforce
    assert(atomsFirstMilliseconds <= 1500, ...
        "KSSOLV:CrystalViewer:AtomsFirstSLO", ...
        "1,000-site atoms-first compilation exceeded 1.5 seconds.");
    assert(exactMilliseconds <= 8000, ...
        "KSSOLV:CrystalViewer:ExactSLO", ...
        "LiFePO4 CrystalNN scene compilation exceeded 8 seconds.");
    assert(cachedMilliseconds <= 500, ...
        "KSSOLV:CrystalViewer:CacheSLO", ...
        "Cached CrystalSceneSpec delivery exceeded 500 milliseconds.");
    assert(cached.analysis.parameters.cacheHit, ...
        "KSSOLV:CrystalViewer:CacheMiss", ...
        "The second identical scene request did not hit the cache.");
    assert(moleculeMilliseconds <= 3000, ...
        "KSSOLV:CrystalViewer:MoleculeSLO", ...
        "4,800-atom molecular scene compilation exceeded 3 seconds.");
    assert(moleculeCachedMilliseconds <= 500, ...
        "KSSOLV:CrystalViewer:MoleculeCacheSLO", ...
        "Cached MoleculeSceneSpec delivery exceeded 500 milliseconds.");
    assert(molecularCached.analysis.parameters.cacheHit, ...
        "KSSOLV:CrystalViewer:MoleculeCacheMiss", ...
        "The second identical molecular request did not hit the cache.");
end
end
