function report = ModelingDialogLayout(enforce, exportDirectory)
%MODELINGDIALOGLAYOUT Audit every schema-driven Modeling dialog in pixels.
arguments
    enforce (1,1) logical = true
    exportDirectory string = ""
end

maximumSymmetryError = 0.75;
if exportDirectory ~= "" && ~isfolder(exportDirectory)
    mkdir(exportDirectory);
end

app = matlab.ui.container.internal.AppContainer( ...
    struct("Title", "Modeling Dialog Layout Audit", ...
    "ToolstripEnabled", true));
kssolv.ui.util.DataStorage.setData("AppContainer", app);
cleanup = onCleanup(@()cleanupAudit(app)); %#ok<NASGU>
structure = kssolv.analysis.matgenlab.core.Structure( ...
    diag([4, 5, 6]), {"Si", "O"}, [0, 0, 0; .25, .25, .25]);
display = kssolv.ui.components.figuredocument.MoleculeDisplay(structure);
displayCleanup = onCleanup(@()deleteIfValid(display)); %#ok<NASGU>
localizer = kssolv.ui.util.Localizer.getInstance();
originalLocale = string(localizer.currentLocale);
localeCleanup = onCleanup(@() ...
    kssolv.ui.util.Localizer.setLocale(originalLocale)); %#ok<NASGU>

commandIds = kssolv.modeling.CommandCatalog.commandIds();
entries = repmat(struct( ...
    "locale", "", "commandId", "", "state", "", ...
    "figureHeight", 0, "bottomClearance", 0, ...
    "topClearance", 0, "symmetryError", 0, ...
    "buttonHeight", 0, "formHeight", 0, ...
    "helpExpanded", false, "statusVisible", false, ...
    "clipped", false), 0, 1);
for locale = ["zh_CN", "en_US"]
    kssolv.ui.util.Localizer.setLocale(locale);
    for index = 1:numel(commandIds)
        commandId = commandIds(index);
        commandInfo = kssolv.modeling.CommandCatalog.find(commandId);
        dialog = kssolv.ui.features.modeling.CommandDialog( ...
            commandInfo, display, struct());
        dialogCleanup = onCleanup(@()deleteIfValid(dialog));
        figureHandle = ancestor(dialog.Widgets.ApplyButton, "figure");
        figureHandle.Visible = "on";
        settleLayout(dialog.Widgets.ApplyButton);
        entries(end + 1) = measure( ... %#ok<AGROW>
            dialog, locale, commandId, "collapsed", ...
            exportDirectory);

        if isfield(dialog.Widgets, "HelpToggleButton")
            dialog.Widgets.HelpToggleButton.ButtonPushedFcn([], []);
            settleLayout(dialog.Widgets.ApplyButton);
            entries(end + 1) = measure( ... %#ok<AGROW>
                dialog, locale, commandId, "help-expanded", ...
                exportDirectory);
        end
        clear dialogCleanup
    end
end

bottomClearance = [entries.bottomClearance];
symmetryError = [entries.symmetryError];
report = struct( ...
    "maximumSymmetryErrorAllowed", maximumSymmetryError, ...
    "maximumSymmetryErrorMeasured", max(symmetryError), ...
    "minimumBottomClearance", min(bottomClearance), ...
    "maximumBottomClearance", max(bottomClearance), ...
    "dialogStateCount", numel(entries), ...
    "localeCount", numel(unique(string({entries.locale}))), ...
    "failedCount", sum(symmetryError > maximumSymmetryError | ...
        [entries.clipped]), ...
    "entries", entries);
disp(rmfield(report, "entries"));

if enforce
    failed = entries(symmetryError > maximumSymmetryError | ...
        [entries.clipped]);
    assert(isempty(failed), ...
        "KSSOLV:Modeling:DialogActionGutterSymmetry", ...
        "Modeling action-row top and bottom spacing must agree within " + ...
        "%g px. Failures: %s", maximumSymmetryError, ...
        failureText(failed));
end
end

function settleLayout(button)
drawnow;
% R2026b schedules managed-grid placement after the first paint. A short
% fixed compositor interval is more reliable than observing Position once:
% the default coordinates can look stable before the deferred pass runs.
pause(0.35);
drawnow;
started = tic;
while toc(started) < 2
    drawnow;
    position = getpixelposition(button, true);
    if abs(position(1) - 100) > 0.1 || ...
            abs(position(2) - 100) > 0.1 || ...
            abs(position(3) - 100) > 0.1
        return
    end
    pause(0.02);
end
error("KSSOLV:Modeling:DialogLayoutTimeout", ...
    "The Modeling dialog layout did not settle within two seconds.");
end

function entry = measure( ...
        dialog, locale, commandId, state, exportDirectory)
button = dialog.Widgets.ApplyButton;
figureHandle = ancestor(button, "figure");
position = getpixelposition(button, true);
topClearance = dialog.actionTopGap();
metrics = dialog.layoutAuditMetrics();
entry = struct( ...
    "locale", locale, ...
    "commandId", commandId, ...
    "state", state, ...
    "figureHeight", figureHandle.Position(4), ...
    "bottomClearance", position(2), ...
    "topClearance", topClearance, ...
    "symmetryError", abs(position(2) - topClearance), ...
    "buttonHeight", position(4), ...
    "formHeight", metrics.formHeight, ...
    "helpExpanded", metrics.helpExpanded, ...
    "statusVisible", metrics.statusVisible, ...
    "clipped", position(2) < 0);
if exportDirectory ~= ""
    path = fullfile(exportDirectory, ...
        locale + "--" + commandId + "--" + state + ".png");
    exportapp(figureHandle, path);
end
end

function text = failureText(entries)
if isempty(entries)
    text = "";
    return
end
labels = string({entries.locale}) + "/" + ...
    string({entries.commandId}) + " (" + ...
    string({entries.state}) + ": bottom " + ...
    compose("%.1f", [entries.bottomClearance]) + ...
    " px, top " + compose("%.1f", [entries.topClearance]) + " px)";
text = strjoin(labels, ", ");
end

function cleanupAudit(app)
kssolv.ui.util.DataStorage.removeData("AppContainer");
deleteIfValid(app);
end

function deleteIfValid(value)
if ~isempty(value) && isvalid(value), delete(value); end
end
