function amounts=element_amounts_from_wyckoffs( ...
        elements,elementWyckoffs,spgNum)
%ELEMENT_AMOUNTS_FROM_WYCKOFFS Expand AFLOW Wyckoff sections to site counts.
elements=reshape(string(elements),1,[]);
elementWyckoffs=reshape(string(elementWyckoffs),1,[]);
if numel(elements)~=numel(elementWyckoffs)
    error("KSSOLV:Matgenlab:Prototypes:ElementLength", ...
        "Chemical system and Wyckoff sections must have the same length.");
end
lookup=kssolv.analysis.matgenlab.analysis.prototypes.internal. ...
    load_data("multiplicities");
amounts=struct();
for index=1:numel(elements)
    normalized=kssolv.analysis.matgenlab.analysis.prototypes.internal. ...
        prefix_wyckoff_counts(elementWyckoffs(index));
    parsed=kssolv.analysis.matgenlab.analysis.prototypes. ...
        split_alpha_numeric(normalized);
    amounts.(char(elements(index)))= ...
        kssolv.analysis.matgenlab.analysis.prototypes. ...
        count_values_for_wyckoff(parsed.alpha,parsed.numeric,spgNum,lookup);
end
end
