classdef CrystalSceneBuilderTest < matlab.unittest.TestCase
    % Production contract tests for the MATLAB-to-WebGL crystal scene.
    methods (Test)
        function atomsFirstSceneIsSerializable(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {"Si"}, [0, 0, 0]);
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, "includeConnectivity", false, ...
                "requestId", "atoms-first");
            testCase.verifyEqual(scene.schemaVersion, "2.0");
            testCase.verifyEqual(scene.kind, "crystal");
            testCase.verifyEqual(scene.requestId, "atoms-first");
            testCase.verifyNumElements(scene.atomInstances, 8);
            testCase.verifyEmpty(scene.bondRelations);
            testCase.verifyEqual(scene.warnings(1).code, ...
                "CONNECTIVITY_DEFERRED");
            roundTrip = jsondecode(jsonencode(scene));
            testCase.verifyEqual(roundTrip.structure.siteCount, 1);
        end

        function crystalNNRelationsMatchStructureGraph(testCase)
            structures = testCase.crystalFixtures();
            strategy = kssolv.analysis.matgenlab.core.CrystalNN();
            for structureIndex = 1:numel(structures)
                structure = structures{structureIndex};
                graph = strategy.get_bonded_structure( ...
                    structure, "weights", true, ...
                    "on_disorder", "take_max_species");
                scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                    structure, "includePolyhedra", false);
                testCase.verifyNumElements( ...
                    scene.bondRelations, numel(graph.graph.edges));
                for edgeIndex = 1:numel(graph.graph.edges)
                    edge = graph.graph.edges(edgeIndex);
                    relation = scene.bondRelations(edgeIndex);
                    testCase.verifyEqual(relation.fromSiteIndex, ...
                        edge.from_index - 1);
                    testCase.verifyEqual(relation.toSiteIndex, ...
                        edge.to_index - 1);
                    testCase.verifyEqual(relation.relativeImage, ...
                        edge.to_jimage);
                    endpoint = structure.lattice.get_cartesian_coords( ...
                        structure(edge.to_index).frac_coords + ...
                        edge.to_jimage);
                    expected = norm(endpoint - ...
                        structure(edge.from_index).coords);
                    testCase.verifyEqual(relation.distance, expected, ...
                        AbsTol = 1e-10);
                end
            end
        end

        function elementSitesSupportConnectivityAndPolyhedra(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
                {"Na", "Cl"}, [0, 0, 0; .5, .5, .5]);
            testCase.verifyClass(structure(1).specie, ...
                "kssolv.analysis.matgenlab.core.Element");
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, includeConnectivity = true, ...
                includePolyhedra = true);
            testCase.verifyNotEmpty(scene.bondRelations);
            testCase.verifyNotEmpty(scene.bondInstances);
            testCase.verifyNotEmpty(scene.polyhedra);
        end

        function diamondGoldenPeriodicImages(testCase)
            structure = testCase.diamond();
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, "includePolyhedra", false);
            testCase.verifyNumElements(scene.bondRelations, 4);
            testCase.verifyEqual( ...
                vertcat(scene.bondRelations.relativeImage), ...
                [1, 1, 0; 0, 1, 1; 1, 0, 1; 1, 1, 1]);
            testCase.verifyEqual([scene.bondRelations.distance], ...
                [1.547360656085065, 1.547558722633813, ...
                1.548000322997382, 1.548993544208626], ...
                AbsTol = 1e-10);
        end

        function repeatBoundaryAndBondInstancesAreUnique(testCase)
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                testCase.diamond(), "algorithm", "CutOffDictNN", ...
                "repeat", [2, 1, 1], "includePolyhedra", false);
            atomKeys = string({scene.atomInstances.id});
            bondKeys = strings(1, numel(scene.bondInstances));
            for index = 1:numel(scene.bondInstances)
                bond = scene.bondInstances(index);
                first = string(bond.fromSiteIndex) + "@" + ...
                    join(string(bond.fromImage), ",");
                second = string(bond.toSiteIndex) + "@" + ...
                    join(string(bond.toImage), ",");
                pair = sort([first, second]);
                bondKeys(index) = pair(1) + "::" + pair(2);
            end
            testCase.verifyEqual(numel(unique(atomKeys)), numel(atomKeys));
            testCase.verifyEqual(numel(unique(bondKeys)), numel(bondKeys));
            testCase.verifyEqual(scene.structure.repeat, [2, 1, 1]);
            testCase.verifyTrue(any( ...
                string({scene.atomInstances.visibility}) == "bonded"));
        end

        function finiteVisibleSetOwnsEveryBondEndpoint(testCase)
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                testCase.diamond(), "algorithm", "CutOffDictNN", ...
                "repeat", [2, 2, 1], "includePolyhedra", false);
            atomKeys = string({scene.atomInstances.id});
            relationIds = string({scene.bondRelations.id});
            for bond = scene.bondInstances
                fromKey = "site-" + string(bond.fromSiteIndex) + "@" + ...
                    join(string(bond.fromImage), ",");
                toKey = "site-" + string(bond.toSiteIndex) + "@" + ...
                    join(string(bond.toImage), ",");
                testCase.verifyTrue(any(atomKeys == fromKey));
                testCase.verifyTrue(any(atomKeys == toKey));
                relationIndex = find( ...
                    relationIds == string(bond.relationId), 1);
                testCase.verifyNotEmpty(relationIndex);
                testCase.verifyEqual(bond.distance, ...
                    scene.bondRelations(relationIndex).distance, ...
                    AbsTol = 1e-10);
            end

            bondedAtoms = scene.atomInstances( ...
                string({scene.atomInstances.visibility}) == "bonded");
            for atom = bondedAtoms
                atomKey = string(atom.id);
                reachesSeed = false;
                for bond = scene.bondInstances
                    fromKey = "site-" + string(bond.fromSiteIndex) + "@" + ...
                        join(string(bond.fromImage), ",");
                    toKey = "site-" + string(bond.toSiteIndex) + "@" + ...
                        join(string(bond.toImage), ",");
                    if fromKey == atomKey
                        otherKey = toKey;
                    elseif toKey == atomKey
                        otherKey = fromKey;
                    else
                        continue
                    end
                    otherIndex = find(atomKeys == otherKey, 1);
                    reachesSeed = reachesSeed || ...
                        scene.atomInstances(otherIndex).visibility ~= "bonded";
                end
                testCase.verifyTrue(reachesSeed, ...
                    "A one-hop atom must remain connected to the seed set.");
            end
        end

        function polyhedronHullIncludesCoordinationCenter(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4.209), ...
                {"Cl1-", "Cs1+"}, [.5, .5, .5; 0, 0, 0]);
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, "includeBoundaryAtoms", false);
            testCase.verifyNotEmpty(scene.polyhedra);
            for polyhedron = scene.polyhedra
                testCase.verifyTrue(ismember( ...
                    polyhedron.center, polyhedron.vertices, "rows"));
            end
        end

        function partialOccupancyAndMagmomArePreserved(testCase)
            composition = kssolv.analysis.matgenlab.core.Composition( ...
                {"C", 0.6; "Si", 0.4});
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {composition}, [0, 0, 0], ...
                site_properties = struct("magmom", 2));
            scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, "includeConnectivity", false);
            testCase.verifyFalse(scene.structure.isOrdered);
            testCase.verifyNumElements(scene.sites(1).species, 2);
            components = [scene.sites(1).species{:}];
            testCase.verifyEqual([components.occupancy], [0.6, 0.4], ...
                AbsTol = 1e-12);
            testCase.verifyEqual(scene.sites(1).magmom, [0, 0, 2]);
        end

        function supportedAlgorithmsAndCellTransforms(testCase)
            structure = testCase.diamond();
            for algorithm = ["CrystalNN", "CutOffDictNN", "JmolNN", ...
                    "MinimumDistanceNN", "MinimumOKeeffeNN", "EconNN", ...
                    "BrunnerNNReciprocal"]
                scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                    structure, "algorithm", algorithm, ...
                    "includePolyhedra", false);
                testCase.verifyEqual(scene.analysis.algorithm, algorithm);
            end
            for cellType = ["input", "primitive", "conventional", ...
                    "niggli", "lll"]
                scene = kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                    structure, "cell", cellType, ...
                    "includeConnectivity", false);
                testCase.verifyEqual(scene.analysis.parameters.cell, cellType);
                testCase.verifyGreaterThan(scene.structure.siteCount, 0);
            end
        end

        function boundedCachePreservesScienceAndRefreshesRequest(testCase)
            kssolv.ui.crystal.CrystalSceneCache.clear();
            options = struct("algorithm", "CrystalNN", ...
                "cell", "input", "repeat", [1, 1, 1]);
            first = kssolv.ui.crystal.CrystalSceneCache.build( ...
                testCase.diamond(), options, "first");
            second = kssolv.ui.crystal.CrystalSceneCache.build( ...
                testCase.diamond(), options, "second");
            testCase.verifyFalse(first.analysis.parameters.cacheHit);
            testCase.verifyTrue(second.analysis.parameters.cacheHit);
            testCase.verifyEqual(second.requestId, "second");
            testCase.verifyEqual(second.bondRelations(:), ...
                first.bondRelations(:));
            kssolv.ui.crystal.CrystalSceneCache.clear();
        end

        function limitsAndInvalidOptionsFailExplicitly(testCase)
            structure = testCase.diamond();
            testCase.verifyError(@() ...
                kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, "repeat", [9, 1, 1]), ...
                "KSSOLV:CrystalViewer:Repeat");
            testCase.verifyError(@() ...
                kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, "algorithm", "GuessNN"), ...
                "KSSOLV:CrystalViewer:Algorithm");
            testCase.verifyError(@() ...
                kssolv.ui.crystal.CrystalSceneBuilder.build( ...
                structure, "cell", "unknown"), ...
                "KSSOLV:CrystalViewer:CellType");
        end
    end

    methods (Static, Access = private)
        function structures = crystalFixtures()
            diamond = ...
                kssolv.ui.test.CrystalSceneBuilderTest.diamond();
            nacl = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice( ...
                [3.485, 0, 2.012; 1.162, 3.286, 2.012; 0, 0, 4.025]), ...
                {"Na1+", "Cl1-"}, [0, 0, 0; 2.324, 1.643, 4.025], ...
                coords_are_cartesian = true);
            cscl = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4.209), ...
                {"Cl1-", "Cs1+"}, [.5, .5, .5; 0, 0, 0]);
            fixture = fullfile(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))), "+analysis", "+matgenlab", ...
                "+test", "+core", "+fixtures", "+local_env", ...
                "LiFePO4.json");
            lifepo4 = ...
                kssolv.analysis.matgenlab.core.Structure.from_file(fixture);
            lifepo4 = lifepo4.add_oxidation_state_by_guess();
            structures = {diamond, nacl, cscl, lifepo4};
        end

        function structure = diamond()
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                [2.189, 0, 1.264; .73, 2.064, 1.264; 0, 0, 2.528]);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"C0+", "C0+"}, ...
                [2.554, 1.806, 4.423; .365, .258, .632], ...
                coords_are_cartesian = true);
        end
    end
end
