classdef DeploymentCompatibilityTest < matlab.unittest.TestCase
    %DEPLOYMENTCOMPATIBILITYTEST Contracts exercised by the standalone app.

    methods (TestClassSetup)
        function configureKssolvPaths(~)
            addpath(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "+kssolv", "+core", "kssolv-3o"));
            KSSOLV.startup();
        end
    end

    methods (Test)
        function toolboxRestartRecreatesModelingSessionRegistry(testCase)
            previousProject = kssolv.ui.util.DataStorage.getData("Project");
            previousFilename = ...
                kssolv.ui.util.DataStorage.getData("ProjectFilename");
            cleanup = onCleanup(@()restoreToolboxState( ...
                previousProject, previousFilename));

            kssolv.ui.util.DataStorage.setData( ...
                "Project", kssolv.services.filemanager.Project());
            kssolv.ui.util.DataStorage.setData("ProjectFilename", "");
            first = kssolv.KSSOLVToolbox();
            firstRegistry = kssolv.ui.features.modeling. ...
                SessionRegistry.getInstance();
            testCase.verifyTrue(isvalid(firstRegistry));

            delete(first);
            testCase.verifyEmpty(kssolv.ui.util.DataStorage.getData( ...
                "ModelingSessionRegistry"));

            kssolv.ui.util.DataStorage.setData( ...
                "Project", kssolv.services.filemanager.Project());
            second = kssolv.KSSOLVToolbox();
            secondRegistry = kssolv.ui.features.modeling. ...
                SessionRegistry.getInstance();
            testCase.verifyTrue(isvalid(secondRegistry));
            testCase.verifyFalse(isequal(firstRegistry, secondRegistry));
            listener = addlistener(secondRegistry, ...
                "ActiveSessionChanged", @(~, ~)[]);
            testCase.verifyTrue(isvalid(listener));
            delete(listener);
            delete(second);
            clear cleanup

            function restoreToolboxState(project, filename)
                current = kssolv.ui.util.DataStorage.getData( ...
                    "KSSOLVToolbox");
                if ~isempty(current) && isvalid(current)
                    delete(current);
                end
                registry = kssolv.ui.util.DataStorage.getData( ...
                    "ModelingSessionRegistry");
                if ~isempty(registry) && isvalid(registry)
                    delete(registry);
                end
                if isempty(project)
                    kssolv.ui.util.DataStorage.removeData("Project");
                else
                    kssolv.ui.util.DataStorage.setData("Project", project);
                end
                if isempty(filename)
                    kssolv.ui.util.DataStorage.removeData( ...
                        "ProjectFilename");
                else
                    kssolv.ui.util.DataStorage.setData( ...
                        "ProjectFilename", filename);
                end
            end
        end

        function toolboxCloseSilencesModelingCallbacksBeforeTeardown(testCase)
            previousProject = kssolv.ui.util.DataStorage.getData("Project");
            previousFilename = ...
                kssolv.ui.util.DataStorage.getData("ProjectFilename");
            cleanup = onCleanup(@()restoreState( ...
                previousProject, previousFilename));

            kssolv.ui.util.DataStorage.setData( ...
                "Project", kssolv.services.filemanager.Project());
            kssolv.ui.util.DataStorage.setData("ProjectFilename", "");
            app = kssolv.KSSOLVToolbox();
            container = app.getAppContainer();
            registry = kssolv.ui.features.modeling. ...
                SessionRegistry.getInstance();
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 4, {"Si"}, [0, 0, 0]);
            display = ...
                kssolv.ui.components.figuredocument.MoleculeDisplay( ...
                structure);
            document = matlab.ui.internal.FigureDocument(struct( ...
                "Title", "Shutdown structure", ...
                "DocumentGroupTag", "Structure", ...
                "Tag", "shutdown-modeling-test"));
            container.add(document);
            registry.register(document, display);

            sessionNotifications = 0;
            activeNotifications = 0;
            sessionListener = addlistener(registry, ...
                "SessionCountChanged", @(~, ~)countSession());
            activeListener = addlistener(registry, ...
                "ActiveSessionChanged", @(~, ~)countActive());

            closeFcn = container.CanCloseFcn;
            testCase.verifyTrue(closeFcn(container));
            testCase.verifyEqual(registry.count(), 0);
            testCase.verifyEqual(sessionNotifications, 0);
            testCase.verifyEqual(activeNotifications, 0);

            % Destruction after close approval must not re-enter ModelingTab
            % through document or registry listeners.
            delete(document);
            drawnow
            testCase.verifyEqual(sessionNotifications, 0);
            testCase.verifyEqual(activeNotifications, 0);

            delete(sessionListener);
            delete(activeListener);
            delete(container);
            drawnow
            clear cleanup

            function countSession()
                sessionNotifications = sessionNotifications + 1;
            end

            function countActive()
                activeNotifications = activeNotifications + 1;
            end

            function restoreState(project, filename)
                current = kssolv.ui.util.DataStorage.getData( ...
                    "KSSOLVToolbox");
                if ~isempty(current) && isvalid(current)
                    delete(current);
                end
                currentRegistry = kssolv.ui.util.DataStorage.getData( ...
                    "ModelingSessionRegistry");
                if ~isempty(currentRegistry) && isvalid(currentRegistry)
                    delete(currentRegistry);
                end
                if isempty(project)
                    kssolv.ui.util.DataStorage.removeData("Project");
                else
                    kssolv.ui.util.DataStorage.setData("Project", project);
                end
                if isempty(filename)
                    kssolv.ui.util.DataStorage.removeData("ProjectFilename");
                else
                    kssolv.ui.util.DataStorage.setData( ...
                        "ProjectFilename", filename);
                end
            end
        end

        function helpMenuPlacesLogImmediatelyAfterUpdate(testCase)
            kssolv.ui.util.DataStorage.setData( ...
                "Project", kssolv.services.filemanager.Project());
            homeTab = kssolv.ui.components.tab.HomeTab();
            popup = homeTab.Widgets.ResourceSection.ResourceHelpButton.Popup;

            testCase.verifyEqual(popup.getChildByIndex(4), ...
                homeTab.Widgets.ResourceSection.CheckUpdateListItem);
            testCase.verifyEqual(popup.getChildByIndex(5), ...
                homeTab.Widgets.ResourceSection.OpenLogsListItem);
            testCase.verifyEqual( ...
                string(homeTab.Widgets.ResourceSection.OpenLogsListItem.Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:OpenLogsListItemLabel")));
        end

        function structureMenuUsesMaterialsProject(testCase)
            kssolv.ui.util.DataStorage.setData( ...
                "Project", kssolv.services.filemanager.Project());
            homeTab = kssolv.ui.components.tab.HomeTab();
            popup = homeTab.Widgets.ProjectSection. ...
                ProjectStructureButton.Popup;

            newStructureItem = popup.getChildByIndex(1);
            testCase.verifyClass(newStructureItem, ...
                "matlab.ui.internal.toolstrip.ListItemWithPopup");
            testCase.verifyEqual(string(newStructureItem.Text), string( ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:NewStructureListItemLabel")));
            newStructurePopup = newStructureItem.Popup;
            testCase.verifyEqual(string( ...
                newStructurePopup.getChildByIndex(1).Text), string( ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:" + ...
                "NewBlankCrystalStructureListItemLabel")));
            testCase.verifyEqual(string( ...
                newStructurePopup.getChildByIndex(2).Text), string( ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:" + ...
                "NewBlankMoleculeStructureListItemLabel")));

            testCase.verifyEqual(popup.getChildByIndex(3), ...
                homeTab.Widgets.ProjectSection. ...
                ImportStructureFromMaterialsProjectListItem);
            testCase.verifyEqual(string( ...
                popup.getChildByIndex(3).Text), string( ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:" + ...
                "ImportStructureFromMaterialsProjectListItemLabel")));
            testCase.verifyTrue(popup.getChildByIndex(3).Enabled);
            testCase.verifyFalse(popup.getChildByIndex(4).Enabled);
            testCase.verifyEqual(string(popup.getChildByIndex(4).Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:" + ...
                "ImportStructureFromMatlabListItemLabel")));
        end

        function materialsProjectDialogBuildsPeriodicSearchUI(testCase)
            dialog = ...
                kssolv.ui.components.dialog.MaterialsProjectDialog();
            cleanup = onCleanup(@() delete(dialog));

            testCase.verifyClass(dialog.widgets.ResultsTable, ...
                "matlab.ui.control.Table");
            testCase.verifyNumElements( ...
                dialog.widgets.ResultsTable.ColumnName, 11);
            testCase.verifyTrue(all( ...
                dialog.widgets.ResultsTable.ColumnSortable));
            testCase.verifyFalse(any(contains(string( ...
                dialog.widgets.ResultsTable.ColumnName), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectChemsysColumn")))));
            testCase.verifyClass(dialog.widgets.PageSizeDropDown, ...
                "matlab.ui.control.DropDown");
            testCase.verifyEqual(string( ...
                dialog.widgets.PageSizeDropDown.Items), ...
                ["10/page", "15/page", "20/page", "30/page"]);
            testCase.verifyEqual(dialog.widgets.PageSizeDropDown.Value, 10);
            dialog.widgets.PageSizeDropDown.Value = 15;
            dialog.widgets.PageSizeDropDown.ValueChangedFcn( ...
                dialog.widgets.PageSizeDropDown, []);
            testCase.verifyEqual(dialog.widgets.PageSizeDropDown.Value, 15);
            testCase.verifyEqual(string( ...
                dialog.widgets.ResultsTable.Tooltip), "");
            testCase.verifyClass(dialog.widgets.ExperimentalLegend, ...
                "matlab.ui.control.Label");
            testCase.verifyEqual(string( ...
                dialog.widgets.ExperimentalLegend.Text), string( ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectExperimentalLegend")));
            testCase.verifyClass(dialog.widgets.FirstPageButton, ...
                "matlab.ui.control.Button");
            testCase.verifyClass(dialog.widgets.LastPageButton, ...
                "matlab.ui.control.Button");
            testCase.verifyEqual( ...
                string(dialog.widgets.PageLabel.Text), ...
                string(sprintf(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectPageStatus"), 1, 1)));
            testCase.verifyEqual( ...
                string(dialog.widgets.NextPageButton.Enable), "off");
            drawnow;
            figure = ancestor(dialog.widgets.QueryField, 'figure');
            testCase.verifyEqual(figure.Position(3:4), [1020, 710]);
            testCase.verifyEqual( ...
                dialog.widgets.PeriodicTableGrid.RowHeight, ...
                repmat({36}, 1, 9));
            testCase.verifyEqual( ...
                dialog.widgets.PeriodicTableGrid.ColumnWidth(2:19), ...
                repmat({36}, 1, 18));
            testCase.verifyEqual( ...
                dialog.widgets.MainLayout.RowHeight{5}, 26);
            testCase.verifyEqual(dialog.widgets.MainLayout.RowSpacing, 2);
            testCase.verifyNumElements( ...
                fieldnames(dialog.widgets.ElementButtons), 118);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.C.BackgroundColor, ...
                [142, 159, 166] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.Li.BackgroundColor, ...
                [186, 208, 70] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.Be.BackgroundColor, ...
                [112, 202, 159] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.He.BackgroundColor, ...
                [145, 145, 205] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.F.BackgroundColor, ...
                [194, 161, 88] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.Bi.BackgroundColor, ...
                [222, 104, 104] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.Zn.BackgroundColor, ...
                [178, 178, 178] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.Sc.BackgroundColor, ...
                [136, 203, 254] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.La.BackgroundColor, ...
                [255, 235, 17] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                dialog.widgets.ElementButtons.Ac.BackgroundColor, ...
                [255, 188, 30] ./ 255, 'AbsTol', eps);
            testCase.verifyEqual( ...
                string(dialog.widgets.ElementButtons.La.Enable), "on");
            testCase.verifyEqual( ...
                string(dialog.widgets.ElementButtons.Pu.Enable), "on");
            testCase.verifyEqual( ...
                string(dialog.widgets.ElementButtons.Am.Enable), "off");
            testCase.verifyEqual( ...
                string(dialog.widgets.ElementButtons.Og.Enable), "off");
            disabled = ["Po", "At", "Rn", "Fr", "Ra", ...
                "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", ...
                "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", ...
                "Nh", "Fl", "Mc", "Lv", "Ts", "Og"];
            names = string(fieldnames(dialog.widgets.ElementButtons));
            disabledInDialog = strings(1, 0);
            for name = names.'
                if string(dialog.widgets.ElementButtons. ...
                        (name).Enable) == "off"
                    disabledInDialog(end + 1) = name; %#ok<AGROW>
                end
            end
            testCase.verifyEqual(sort(disabledInDialog), sort(disabled));
            testCase.verifyEqual( ...
                string(dialog.widgets.OnlyElementsButton.Tag), "only");
            testCase.verifyEqual( ...
                string(dialog.widgets.AtLeastElementsButton.Tag), ...
                "at-least");
            testCase.verifyEqual( ...
                string(dialog.widgets.FormulaButton.Tag), "formula");
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Editable), "off");
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Placeholder), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectElementsPlaceholder")));
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Tooltip), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectOnlyElementsTooltip")));
            testCase.verifyFalse(isfield( ...
                dialog.widgets, "SelectedElementsLabel"));
            testCase.verifyEqual( ...
                dialog.widgets.QueryField.ValueChangedFcn, ...
                dialog.widgets.SearchButton.ButtonPushedFcn);
            dialog.widgets.ElementButtons.C.Value = true;
            dialog.widgets.ElementButtons.C.ValueChangedFcn([], []);
            dialog.widgets.ElementButtons.N.Value = true;
            dialog.widgets.ElementButtons.N.ValueChangedFcn([], []);
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Value), "C-N");
            selectionChanged = dialog.widgets.SearchModeGroup. ...
                SelectionChangedFcn;
            dialog.widgets.SearchModeGroup.SelectedObject = ...
                dialog.widgets.FormulaButton;
            selectionChanged([], struct( ...
                "NewValue", dialog.widgets.FormulaButton));
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Editable), "on");
            testCase.verifyEqual(string(dialog.widgets.QueryField.Value), "");
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Placeholder), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectFormulaPlaceholder")));
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Tooltip), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectFormulaTooltip")));
            dialog.widgets.QueryField.Value = "mp-169";
            dialog.widgets.SearchModeGroup.SelectedObject = ...
                dialog.widgets.AtLeastElementsButton;
            selectionChanged([], struct( ...
                "NewValue", dialog.widgets.AtLeastElementsButton));
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Value), "C-N");
            testCase.verifyEqual( ...
                string(dialog.widgets.QueryField.Tooltip), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:MaterialsProjectAtLeastElementsTooltip")));
            dialog.widgets.SearchModeGroup.SelectedObject = ...
                dialog.widgets.OnlyElementsButton;
            selectionChanged([], struct( ...
                "NewValue", dialog.widgets.OnlyElementsButton));
            testCase.verifyEqual( ...
                string(dialog.widgets.ElementButtons.Am.Enable), "off");
            testCase.verifyFalse(isfield(dialog.widgets, "APIKeyField"));
            testCase.verifyFalse(isfield( ...
                dialog.widgets, "APIKeyVisibilityButton"));
            clear cleanup
        end

        function materialsProjectCredentialDoesNotUseBundledFallback(testCase)
            source = fileread(which( ...
                'kssolv.analysis.matgenlab.ext.matproj.MPRester'));
            testCase.verifyFalse(contains(source, 'BundledCredentials'));
            testCase.verifyFalse(isfile(fullfile( ...
                KSSOLV_Toolbox.RootDirectory, '+kssolv', '+settings', ...
                'data', 'materials-project-default.json')));
        end

        function settingsUsesMaskedEditFieldWithVisibilityToggle(testCase)
            dialog = kssolv.ui.components.dialog.SettingsDialog();
            cleanup = onCleanup(@() delete(dialog));
            metadata = metaclass(dialog);

            testCase.verifyTrue(any(strcmp( ...
                {metadata.SuperclassList.Name}, ...
                'controllib.ui.internal.dialog.AbstractDialog')));
            testCase.verifyClass(dialog.widgets.OpenAIAPIKeyText, ...
                'matlab.ui.control.EditField');
            testCase.verifyClass( ...
                dialog.widgets.OpenAIAPIKeyVisibilityButton, ...
                'matlab.ui.control.Button');

            editField = dialog.widgets.OpenAIAPIKeyText;
            editField.Value = 'sk-test-key';
            valueChangedCallback = editField.ValueChangedFcn;
            valueChangedCallback(editField, []);
            testCase.verifyEqual(editField.Value, 'sk-******');

            visibilityButton = ...
                dialog.widgets.OpenAIAPIKeyVisibilityButton;
            buttonPushedCallback = visibilityButton.ButtonPushedFcn;
            buttonPushedCallback(visibilityButton, []);
            testCase.verifyEqual(editField.Value, 'sk-test-key');
            buttonPushedCallback(visibilityButton, []);
            testCase.verifyEqual(editField.Value, 'sk-******');

            testCase.verifyEqual(string( ...
                dialog.widgets.MaterialsProjectTab.Title), ...
                "Materials Project");
            testCase.verifyClass( ...
                dialog.widgets.MaterialsProjectAPIKeyText, ...
                'matlab.ui.control.EditField');
            testCase.verifyClass( ...
                dialog.widgets.MaterialsProjectAPIPageButton, ...
                'matlab.ui.control.Button');

            materialsProjectKeyField = ...
                dialog.widgets.MaterialsProjectAPIKeyText;
            materialsProjectKeyField.Value = repmat('x', 1, 32);
            valueChangedCallback = ...
                materialsProjectKeyField.ValueChangedFcn;
            valueChangedCallback(materialsProjectKeyField, []);
            testCase.verifyEqual(materialsProjectKeyField.Value, ...
                repmat('*', 1, 32));

            materialsProjectVisibilityButton = dialog.widgets. ...
                MaterialsProjectAPIKeyVisibilityButton;
            buttonPushedCallback = ...
                materialsProjectVisibilityButton.ButtonPushedFcn;
            buttonPushedCallback(materialsProjectVisibilityButton, []);
            testCase.verifyEqual(materialsProjectKeyField.Value, ...
                repmat('x', 1, 32));
            clear cleanup
        end

        function settingsUsesEncryptedCredentialStore(testCase)
            source = fileread(which('kssolv.settings.Settings'));
            testCase.verifyTrue(contains(source, ...
                'kssolv.settings.EncryptedStore'));
            testCase.verifyTrue(contains(source, ...
                'writeMaterialsProjectAPIKey'));

            dialogSource = fileread(which( ...
                'kssolv.ui.components.dialog.SettingsDialog'));
            testCase.verifyTrue(contains(dialogSource, ...
                'https://next-gen.materialsproject.org/api'));
        end

    end
end
