classdef DeploymentCompatibilityTest < matlab.unittest.TestCase
    %DEPLOYMENTCOMPATIBILITYTEST Contracts exercised by the standalone app.

    methods (TestClassSetup)
        function configureKssolvPaths(~)
            addpath(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "+kssolv", "+core", "kssolv-3o"));
            KSSOLV.startup();
        end
    end

    methods (Test)
        function helpMenuPlacesLogImmediatelyAfterUpdate(testCase)
            kssolv.ui.util.DataStorage.setData( ...
                "Project", kssolv.services.filemanager.Project());
            homeTab = kssolv.ui.components.tab.HomeTab();
            popup = homeTab.Widgets.ResourceSection.ResourceHelpButton.Popup;

            testCase.verifyEqual(popup.getChildByIndex(4), ...
                homeTab.Widgets.ResourceSection.CheckUpdateListItem);
            testCase.verifyEqual(popup.getChildByIndex(5), ...
                homeTab.Widgets.ResourceSection.OpenLogsListItem);
            testCase.verifyEqual( ...
                string(homeTab.Widgets.ResourceSection.OpenLogsListItem.Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:OpenLogsListItemLabel")));
        end

        function structureMenuUsesMaterialsProject(testCase)
            kssolv.ui.util.DataStorage.setData( ...
                "Project", kssolv.services.filemanager.Project());
            homeTab = kssolv.ui.components.tab.HomeTab();
            popup = homeTab.Widgets.ProjectSection. ...
                ProjectStructureButton.Popup;

            testCase.verifyEqual(popup.getChildByIndex(3), ...
                homeTab.Widgets.ProjectSection. ...
                ImportStructureFromMaterialsProjectListItem);
            testCase.verifyEqual(string( ...
                popup.getChildByIndex(3).Text), string( ...
                kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:" + ...
                "ImportStructureFromMaterialsProjectListItemLabel")));
            testCase.verifyTrue(popup.getChildByIndex(3).Enabled);
            testCase.verifyFalse(popup.getChildByIndex(4).Enabled);
            testCase.verifyEqual(string(popup.getChildByIndex(4).Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:toolbox:" + ...
                "ImportStructureFromMatlabListItemLabel")));
        end

        function materialsProjectDialogBuildsPeriodicSearchUI(testCase)
            dialog = ...
                kssolv.ui.components.dialog.MaterialsProjectDialog();
            cleanup = onCleanup(@() delete(dialog));

            testCase.verifyClass(dialog.widgets.ResultsTable, ...
                "matlab.ui.control.Table");
            testCase.verifyNumElements( ...
                fieldnames(dialog.widgets.ElementButtons), 118);
            testCase.verifyEqual( ...
                string(dialog.widgets.OnlyElementsButton.Tag), "only");
            testCase.verifyEqual( ...
                string(dialog.widgets.AtLeastElementsButton.Tag), ...
                "at-least");
            testCase.verifyEqual( ...
                string(dialog.widgets.FormulaButton.Tag), "formula");
            clear cleanup
        end

        function bundledMaterialsProjectCredentialDecrypts(testCase)
            value = kssolv.settings.BundledCredentials. ...
                readMaterialsProjectAPIKey();
            testCase.verifyEqual(strlength(value), 32);

            digest = javaMethod( ...
                'getInstance', 'java.security.MessageDigest', 'SHA-256');
            bytes = uint8(unicode2native(char(value), 'UTF-8'));
            hashBytes = typecast(int8(digest.digest( ...
                typecast(bytes, 'int8'))), 'uint8');
            hash = lower(string(reshape(dec2hex(hashBytes, 2).', 1, [])));
            testCase.verifyEqual(hash, ...
                "a47b36c24ce68a3dceb64510533e6bb8" + ...
                "7264869b889cb59108f4d00b576e6aff");
        end

        function settingsUsesMaskedEditFieldWithVisibilityToggle(testCase)
            dialog = kssolv.ui.components.dialog.SettingsDialog();
            cleanup = onCleanup(@() delete(dialog));
            metadata = metaclass(dialog);

            testCase.verifyTrue(any(strcmp( ...
                {metadata.SuperclassList.Name}, ...
                'controllib.ui.internal.dialog.AbstractDialog')));
            testCase.verifyClass(dialog.widgets.OpenAIAPIKeyText, ...
                'matlab.ui.control.EditField');
            testCase.verifyClass( ...
                dialog.widgets.OpenAIAPIKeyVisibilityButton, ...
                'matlab.ui.control.Button');

            editField = dialog.widgets.OpenAIAPIKeyText;
            editField.Value = 'sk-test-key';
            valueChangedCallback = editField.ValueChangedFcn;
            valueChangedCallback(editField, []);
            testCase.verifyEqual(editField.Value, 'sk-******');

            visibilityButton = ...
                dialog.widgets.OpenAIAPIKeyVisibilityButton;
            buttonPushedCallback = visibilityButton.ButtonPushedFcn;
            buttonPushedCallback(visibilityButton, []);
            testCase.verifyEqual(editField.Value, 'sk-test-key');
            buttonPushedCallback(visibilityButton, []);
            testCase.verifyEqual(editField.Value, 'sk-******');

            testCase.verifyEqual(string( ...
                dialog.widgets.MaterialsProjectTab.Title), ...
                "Materials Project");
            testCase.verifyClass( ...
                dialog.widgets.MaterialsProjectAPIKeyText, ...
                'matlab.ui.control.EditField');
            testCase.verifyClass( ...
                dialog.widgets.MaterialsProjectAPIPageButton, ...
                'matlab.ui.control.Button');

            materialsProjectKeyField = ...
                dialog.widgets.MaterialsProjectAPIKeyText;
            materialsProjectKeyField.Value = repmat('x', 1, 32);
            valueChangedCallback = ...
                materialsProjectKeyField.ValueChangedFcn;
            valueChangedCallback(materialsProjectKeyField, []);
            testCase.verifyEqual(materialsProjectKeyField.Value, ...
                repmat('*', 1, 32));

            materialsProjectVisibilityButton = dialog.widgets. ...
                MaterialsProjectAPIKeyVisibilityButton;
            buttonPushedCallback = ...
                materialsProjectVisibilityButton.ButtonPushedFcn;
            buttonPushedCallback(materialsProjectVisibilityButton, []);
            testCase.verifyEqual(materialsProjectKeyField.Value, ...
                repmat('x', 1, 32));
            clear cleanup
        end

        function settingsUsesEncryptedCredentialStore(testCase)
            source = fileread(which('kssolv.settings.Settings'));
            testCase.verifyTrue(contains(source, ...
                'kssolv.settings.EncryptedStore'));
            testCase.verifyTrue(contains(source, ...
                'writeMaterialsProjectAPIKey'));

            dialogSource = fileread(which( ...
                'kssolv.ui.components.dialog.SettingsDialog'));
            testCase.verifyTrue(contains(dialogSource, ...
                'https://next-gen.materialsproject.org/api'));
        end

    end
end
