classdef ModelingCommandDialogTest < matlab.unittest.TestCase
    %MODELINGCOMMANDDIALOGTEST Schema-driven Modeling dialog contracts.

    methods (Test)
        function presentationCatalogCoversEveryCommand(testCase)
            testCase.verifyWarningFree(@() ...
                kssolv.ui.features.modeling.CommandPresentationCatalog.validate());
            commandIds = kssolv.modeling.CommandCatalog.commandIds();
            testCase.verifyEqual(numel( ...
                kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                iconNames()), numel(commandIds));
            for index = 1:numel(commandIds)
                commandId = commandIds(index);
                assetId = ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    iconName(commandId);
                verifyAsset(assetId, @(size) ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    icon(commandId, size));
            end
            categoryIds = ...
                kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                categoryIds();
            for index = 1:numel(categoryIds)
                categoryId = categoryIds(index);
                verifyAsset("category_" + categoryId, @(size) ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    categoryIcon(categoryId, size));
            end
            utilityIds = ...
                kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                utilityIds();
            for index = 1:numel(utilityIds)
                utilityId = utilityIds(index);
                verifyAsset("history_" + utilityId, @(size) ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    utilityIcon(utilityId, size));
            end

            function verifyAsset(assetId, iconFactory)
                masterPath = kssolv.ui.features.modeling. ...
                    CommandPresentationCatalog.sourceAssetPath( ...
                    assetId, 64);
                testCase.verifyTrue(isfile(masterPath));
                markup = string(fileread(masterPath));
                testCase.verifyTrue(contains(markup, 'width="64"'));
                testCase.verifyTrue(contains(markup, 'height="64"'));
                for size = [16, 24]
                    iconPath = kssolv.ui.features.modeling. ...
                        CommandPresentationCatalog.assetPath( ...
                        assetId, size);
                    testCase.verifyTrue(isfile(iconPath));
                    metadata = imfinfo(iconPath);
                    testCase.verifyEqual( ...
                        [metadata.Width, metadata.Height], [size, size]);
                    icon = iconFactory(size);
                    testCase.verifyClass(icon, ...
                        "matlab.ui.internal.toolstrip.Icon");
                    testCase.verifyTrue(startsWith( ...
                        string(icon.getIconClass()), ...
                        "data:image/svg+xml;base64,"));
                end
            end
        end

        function localesCoverCatalogAndSchema(testCase)
            localizer = kssolv.ui.util.Localizer.getInstance();
            originalLocale = string(localizer.currentLocale);
            cleanup = onCleanup(@() ...
                kssolv.ui.util.Localizer.setLocale(originalLocale));
            [app, display] = testCase.createDisplay();
            displayCleanup = onCleanup(@()testCase.cleanupDisplay(app));
            fixedKeys = [
                "ModelingTab", "History", "Undo", "Redo", ...
                "EditorsSection", "AtomicEditor", "LatticeEditor", ...
                "SupercellLattice", "DefectsAlloys", ...
                "Nanostructures", "SurfacesInterfaces", ...
                "SymmetryTools", "CreateSelectionGroup", ...
                "TransformGroup", "CleanupGroup", "EditGroup", ...
                "SupercellLatticeTooltip", "NanostructuresTooltip", ...
                "SymmetryToolsTooltip", "SymmetryAnalysisGroup", ...
                "SurfaceModeling", "SurfaceModelingTooltip", ...
                "InterfaceModeling", "InterfaceModelingTooltip", ...
                "SitesSpeciesGroup", "PositionTransformGroup", ...
                "ConstraintsOrderingGroup", "CellConstructionGroup", ...
                "StructureDeformationGroup", "OneDimensionalGroup", ...
                "ZeroDimensionalGroup", "SurfaceConstructionGroup", ...
                "SurfaceChemistryGroup", "InterfaceAssemblyGroup", ...
                "TransitionPathGroup", ...
                "QuickPresetsGroup", "DefectTypeGroup", ...
                "RegionModeGroup", "Supercell222", "Supercell333", ...
                "CustomParameters", "Vacancy", "Substitution", ...
                "Interstitial", "Antisite", "QuantumDot", ...
                "VacancyDescription", "SubstitutionDescription", ...
                "InterstitialDescription", "AntisiteDescription", ...
                "NanoVoid", "Enabled", "Reset", "Cancel", "Apply", ...
                "ValidationError", "NoAvailableStructures", ...
                "NoParametersRequired", ...
                "RunningCommand", "CompletedCommand"];
            commandIds = kssolv.modeling.CommandCatalog.commandIds();

            for locale = ["en_US", "zh_CN"]
                kssolv.ui.util.Localizer.setLocale(locale);
                for keyIndex = 1:numel(fixedKeys)
                    testCase.verifyNotEmpty( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:" + fixedKeys(keyIndex)));
                end
                for commandIndex = 1:numel(commandIds)
                    commandInfo = kssolv.modeling.CommandCatalog.find( ...
                        commandIds(commandIndex));
                    testCase.verifyNotEmpty( ...
                        kssolv.ui.util.Localizer.message( ...
                        commandInfo.labelKey));
                    testCase.verifyNotEmpty( ...
                        kssolv.ui.util.Localizer.message( ...
                        commandInfo.tooltipKey));
                    fields = ...
                        kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                        commandInfo.id, display);
                    for fieldIndex = 1:numel(fields)
                        key = "KSSOLV:modeling:Field_" + ...
                            fields(fieldIndex).name;
                        testCase.verifyNotEmpty( ...
                            kssolv.ui.util.Localizer.message(key));
                    end
                end
                if locale == "zh_CN"
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_species")), ...
                        "元素符号");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_indices")), ...
                        "原子序号（从 1 开始）");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:BuildSlab")), ...
                        "构建表面模型");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_slabSize")), ...
                        "表面模型最小厚度（Å）");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_intermediateCount")), ...
                        "NEB 中间构型数");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_maximumIndex")), ...
                        "最大周期匹配指数");
                    adsorptionFields = ...
                        kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                        "find_adsorption_sites", display);
                    adsorptionHeight = ...
                        kssolv.ui.features.modeling.ParameterPresentation.describe( ...
                        "find_adsorption_sites", ...
                        adsorptionFields( ...
                        [adsorptionFields.name] == "distance"));
                    testCase.verifyEqual(string( ...
                        adsorptionHeight.label), "吸附原子高度（Å）");
                    passivationFields = ...
                        kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                        "passivate_surface", display);
                    passivant = ...
                        kssolv.ui.features.modeling.ParameterPresentation.describe( ...
                        "passivate_surface", ...
                        passivationFields( ...
                        [passivationFields.name] == "species"));
                    testCase.verifyEqual(string(passivant.label), ...
                        "钝化元素");
                end
            end
            clear displayCleanup cleanup
        end

        function everyCommandDialogAcceptsItsDefaultForm(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            commandIds = kssolv.modeling.CommandCatalog.commandIds();

            for index = 1:numel(commandIds)
                commandId = commandIds(index);
                commandInfo = ...
                    kssolv.modeling.CommandCatalog.find(commandId);
                fields = ...
                    kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                    commandId, display);
                preset = testCase.referencePreset(fields);
                dialog = kssolv.ui.features.modeling.CommandDialog( ...
                    commandInfo, display, preset);
                dialogCleanup = onCleanup(@()deleteIfValid(dialog));

                callback = ...
                    dialog.Widgets.ApplyButton.ButtonPushedFcn;
                callback([], []);
                parameters = dialog.Parameters;
                cancelled = dialog.Cancelled;

                testCase.verifyFalse(cancelled, ...
                    "Default form did not apply for " + commandId);
                testCase.verifyClass(parameters, "struct");
                clear dialogCleanup
            end
            clear cleanup

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value)
                    delete(value);
                end
            end
        end

        function commandDialogSupportsAppContainerModalHost(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            commandInfo = ...
                kssolv.modeling.CommandCatalog.find("translate_atoms");
            dialog = kssolv.ui.features.modeling.CommandDialog( ...
                commandInfo, display, struct());
            dialogCleanup = onCleanup(@()deleteIfValid(dialog));
            dialogFigure = dialog.getWidget();
            testCase.verifyEqual( ...
                string(dialogFigure.WindowStyle), "modal");
            cancelCallback = dialog.Widgets.CancelButton.ButtonPushedFcn;
            closeTimer = timer( ...
                "StartDelay", 0.1, ...
                "TimerFcn", @(~, ~)cancelCallback([], []));
            timerCleanup = onCleanup(@()deleteTimer(closeTimer));

            start(closeTimer);
            [parameters, cancelled] = dialog.show(app);

            testCase.verifyTrue(cancelled);
            testCase.verifyEmpty(fieldnames(parameters));
            clear timerCleanup dialogCleanup cleanup

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value)
                    delete(value);
                end
            end

            function deleteTimer(value)
                if isvalid(value)
                    stop(value);
                    delete(value);
                end
            end
        end

        function defectAndQuantumPresetsControlVisibleFields(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));

            vacancy = testCase.createDialog( ...
                display, "create_point_defects", ...
                struct("defectType", "vacancy"));
            vacancyCleanup = onCleanup(@()delete(vacancy));
            testCase.verifyEqual( ...
                string(vacancy.Widgets.indices.Visible), "on");
            testCase.verifyEqual( ...
                string(vacancy.Widgets.species.Visible), "off");
            testCase.verifyEqual( ...
                string(vacancy.Widgets.coordinates.Visible), "off");
            clear vacancyCleanup

            interstitial = testCase.createDialog( ...
                display, "create_point_defects", ...
                struct("defectType", "interstitial"));
            interstitialCleanup = onCleanup(@()delete(interstitial));
            testCase.verifyEqual( ...
                string(interstitial.Widgets.indices.Visible), "off");
            testCase.verifyEqual( ...
                string(interstitial.Widgets.species.Visible), "on");
            testCase.verifyEqual( ...
                string(interstitial.Widgets.coordinates.Visible), "on");
            clear interstitialCleanup

            dot = testCase.createDialog( ...
                display, "quantum_dot_void", struct("mode", "dot"));
            dotCleanup = onCleanup(@()delete(dot));
            testCase.verifyEqual( ...
                string(dot.Widgets.vacuum.Visible), "on");
            clear dotCleanup

            void = testCase.createDialog( ...
                display, "quantum_dot_void", struct("mode", "void"));
            voidCleanup = onCleanup(@()delete(void));
            testCase.verifyEqual( ...
                string(void.Widgets.vacuum.Visible), "off");
            clear voidCleanup
            clear cleanup
        end

        function invalidSiteIndexIsRejectedInline(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            dialog = testCase.createDialog( ...
                display, "delete_atoms", struct("indices", 0));
            dialogCleanup = onCleanup(@()delete(dialog));
            callback = dialog.Widgets.ApplyButton.ButtonPushedFcn;

            testCase.verifyError(@()callback([], []), ...
                "KSSOLV:Modeling:ParameterRange");
            testCase.verifyEqual( ...
                string(dialog.Widgets.StatusLabel.Visible), "on");
            testCase.verifyTrue(dialog.Cancelled);
            clear dialogCleanup cleanup
        end

        function supercellDialogAcceptsGeneralIntegerMatrix(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            matrix = [1, -1, 0; 0, 1, -1; 1, 1, 1];
            dialog = testCase.createDialog( ...
                display, "build_supercell", ...
                struct("scalingMatrix", matrix));
            dialogCleanup = onCleanup(@()delete(dialog));
            callback = dialog.Widgets.ApplyButton.ButtonPushedFcn;
            callback([], []);

            testCase.verifyFalse(dialog.Cancelled);
            testCase.verifyEqual( ...
                dialog.Parameters.scalingMatrix, matrix);
            clear dialogCleanup cleanup
        end

        function supercellDialogRejectsSingularIntegerMatrix(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            matrix = [1, 0, 0; 0, 1, 0; 0, 0, 0];
            dialog = testCase.createDialog( ...
                display, "build_supercell", ...
                struct("scalingMatrix", matrix));
            dialogCleanup = onCleanup(@()delete(dialog));
            callback = dialog.Widgets.ApplyButton.ButtonPushedFcn;

            testCase.verifyError(@()callback([], []), ...
                "KSSOLV:Modeling:ScalingMatrix");
            testCase.verifyTrue(dialog.Cancelled);
            clear dialogCleanup cleanup
        end

        function projectStructureReferencesResolveToCopies(testCase)
            addpath(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "+kssolv", "+core", "kssolv-3o"));
            KSSOLV.startup();
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            project = kssolv.services.filemanager.Project();
            folder = project.findChildrenItem("Structure");
            reference = kssolv.services.filemanager.Structure( ...
                "Reference structure");
            reference.data = ...
                kssolv.services.fileparser.ModeledStructureData( ...
                display.getModel(), "Reference structure");
            folder.addChildrenItem(reference);
            kssolv.ui.util.DataStorage.setData("Project", project);
            projectCleanup = onCleanup(@() ...
                kssolv.ui.util.DataStorage.removeData("Project"));

            available = ...
                kssolv.ui.features.modeling.ModelInputResolver.available(display);
            testCase.verifyTrue(any(available == "Reference structure"));
            resolved = ...
                kssolv.ui.features.modeling.ModelInputResolver.resolve( ...
                "Reference structure");
            testCase.verifyEqual(resolved.frac_coords, ...
                display.getModel().frac_coords, AbsTol = 1e-12);
            testCase.verifyFalse(isequal(resolved, display.getModel()));

            cases = {
                "insert_structure", "otherStructureName", "otherModel"
                "stack_heterostructure", "otherStructureName", "otherModel"
                "twist_moire", "otherStructureName", "otherModel"
                "interpolate_neb", "endStructureName", "endModel"
                "add_solvent_layer", "solventStructureName", "solventModel"
                };
            for index = 1:size(cases, 1)
                parameters = struct();
                parameters.(cases{index, 2}) = "Reference structure";
                enriched = ...
                    kssolv.ui.features.modeling.ModelInputResolver.enrich( ...
                    cases{index, 1}, parameters);
                testCase.verifyTrue(isfield(enriched, cases{index, 3}));
                testCase.verifyClass(enriched.(cases{index, 3}), ...
                    "kssolv.analysis.matgenlab.core.Structure");
            end
            clear projectCleanup cleanup
        end
    end

    methods (Static, Access = private)
        function [app, display] = createDisplay()
            app = matlab.ui.container.internal.AppContainer( ...
                struct("Title", "Modeling Dialog Test", ...
                "ToolstripEnabled", true));
            kssolv.ui.util.DataStorage.setData("AppContainer", app);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                diag([4, 5, 6]), {"Si", "O"}, ...
                [0, 0, 0; .25, .25, .25]);
            display = ...
                kssolv.ui.components.figuredocument.MoleculeDisplay( ...
                structure);
        end

        function cleanupDisplay(app)
            close(findall(groot, "Type", "figure"));
            if ~isempty(app) && isvalid(app)
                delete(app);
            end
            kssolv.ui.util.DataStorage.removeData("AppContainer");
        end

        function preset = referencePreset(fields)
            preset = struct();
            for index = 1:numel(fields)
                name = string(fields(index).name);
                if endsWith(name, "StructureName")
                    preset.(char(name)) = "Reference structure";
                end
            end
        end

        function dialog = createDialog(display, commandId, preset)
            commandInfo = kssolv.modeling.CommandCatalog.find(commandId);
            dialog = kssolv.ui.features.modeling.CommandDialog( ...
                commandInfo, display, preset);
        end
    end
end
