classdef ModelingCommandDialogTest < matlab.unittest.TestCase
    %MODELINGCOMMANDDIALOGTEST Schema-driven Modeling dialog contracts.

    methods (Test)
        function presentationCatalogCoversEveryCommand(testCase)
            testCase.verifyWarningFree(@() ...
                kssolv.ui.features.modeling.CommandPresentationCatalog.validate());
            commandIds = kssolv.modeling.CommandCatalog.commandIds();
            testCase.verifyEqual(numel( ...
                kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                iconNames()), numel(commandIds));
            for index = 1:numel(commandIds)
                commandId = commandIds(index);
                assetId = ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    iconName(commandId);
                verifyAsset(assetId, @(size) ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    icon(commandId, size));
            end
            categoryIds = ...
                kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                categoryIds();
            for index = 1:numel(categoryIds)
                categoryId = categoryIds(index);
                verifyAsset("category_" + categoryId, @(size) ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    categoryIcon(categoryId, size));
            end
            utilityIds = ...
                kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                utilityIds();
            for index = 1:numel(utilityIds)
                utilityId = utilityIds(index);
                verifyAsset("history_" + utilityId, @(size) ...
                    kssolv.ui.features.modeling.CommandPresentationCatalog. ...
                    utilityIcon(utilityId, size));
            end

            function verifyAsset(assetId, iconFactory)
                masterPath = kssolv.ui.features.modeling. ...
                    CommandPresentationCatalog.sourceAssetPath( ...
                    assetId, 64);
                testCase.verifyTrue(isfile(masterPath));
                markup = string(fileread(masterPath));
                testCase.verifyTrue(contains(markup, 'width="64"'));
                testCase.verifyTrue(contains(markup, 'height="64"'));
                for size = [16, 24]
                    iconPath = kssolv.ui.features.modeling. ...
                        CommandPresentationCatalog.assetPath( ...
                        assetId, size);
                    testCase.verifyTrue(isfile(iconPath));
                    metadata = imfinfo(iconPath);
                    testCase.verifyEqual( ...
                        [metadata.Width, metadata.Height], [size, size]);
                    icon = iconFactory(size);
                    testCase.verifyClass(icon, ...
                        "matlab.ui.internal.toolstrip.Icon");
                    testCase.verifyTrue(startsWith( ...
                        string(icon.getIconClass()), ...
                        "data:image/svg+xml;base64,"));
                end
            end
        end

        function modelingIconsHaveUniqueSemanticMasters(testCase)
            commandIds = kssolv.ui.features.modeling. ...
                CommandPresentationCatalog.iconIds();
            iconNames = kssolv.ui.features.modeling. ...
                CommandPresentationCatalog.iconNames();
            testCase.verifyEqual(iconNames, commandIds, ...
                "Every command must own a distinct semantic icon asset.");
            assetIds = [
                commandIds
                "category_" + kssolv.ui.features.modeling. ...
                    CommandPresentationCatalog.categoryIds()
                "history_" + kssolv.ui.features.modeling. ...
                    CommandPresentationCatalog.utilityIds()
                ];
            markup = strings(size(assetIds));
            for index = 1:numel(assetIds)
                path = kssolv.ui.features.modeling. ...
                    CommandPresentationCatalog.sourceAssetPath( ...
                    assetIds(index), 64);
                markup(index) = string(fileread(path));
            end
            testCase.verifyEqual(numel(unique(markup)), numel(markup), ...
                "Modeling icons must not regress to shared placeholders.");
        end

        function localesCoverCatalogAndSchema(testCase)
            localizer = kssolv.ui.util.Localizer.getInstance();
            originalLocale = string(localizer.currentLocale);
            cleanup = onCleanup(@() ...
                kssolv.ui.util.Localizer.setLocale(originalLocale));
            [app, display] = testCase.createDisplay();
            displayCleanup = onCleanup(@()testCase.cleanupDisplay(app));
            fixedKeys = [
                "ModelingTab", "History", "Undo", "Redo", ...
                "EditorsSection", "AtomicEditor", "LatticeEditor", ...
                "SoftMatter", "PolymerBuilder", "AmorphousBuilder", ...
                "SupercellLattice", "DefectsAlloys", ...
                "Nanostructures", "SurfacesInterfaces", ...
                "SymmetryTools", "CreateSelectionGroup", ...
                "TransformGroup", "CleanupGroup", "EditGroup", ...
                "SupercellLatticeTooltip", "NanostructuresTooltip", ...
                "SymmetryToolsTooltip", "SymmetryAnalysisGroup", ...
                "PolymerBuilderTooltip", "AmorphousBuilderTooltip", ...
                "FragmentBrowser", "FragmentBrowserTooltip", ...
                "Search", "FragmentSearchPlaceholder", "NoFragments", ...
                "FragmentFormula", "FragmentTags", "FragmentPorts", ...
                "ConnectionHead", "ConnectionPort", ...
                "ImportFragmentLibrary", "ExportFragmentLibrary", ...
                "AttachSelectedFragment", ...
                "CrystalBuilderResults", "AsymmetricSites", ...
                "EquivalentSites", ...
                "DefectCandidates", ...
                "PolymerConstructionGroup", "PackingConstructionGroup", ...
                "CrystalConstructionGroup", ...
                "SurfaceModeling", "SurfaceModelingTooltip", ...
                "InterfaceModeling", "InterfaceModelingTooltip", ...
                "SitesSpeciesGroup", "PositionTransformGroup", ...
                "ConstraintsOrderingGroup", "CellConstructionGroup", ...
                "StructureDeformationGroup", "OneDimensionalGroup", ...
                "ZeroDimensionalGroup", "SurfaceConstructionGroup", ...
                "SurfaceChemistryGroup", "InterfaceAssemblyGroup", ...
                "TransitionPathGroup", ...
                "QuickPresetsGroup", "DefectTypeGroup", ...
                "PointDefectsGroup", "AlloyGroup", ...
                "DefectsAlloysTooltip", ...
                "RegionModeGroup", "Supercell222", "Supercell333", ...
                "CustomParameters", "Vacancy", "Substitution", ...
                "Interstitial", "Antisite", "QuantumDot", ...
                "VacancyDescription", "SubstitutionDescription", ...
                "InterstitialDescription", "AntisiteDescription", ...
                "NanoVoid", "Enabled", "Reset", "Preview", ...
                "PreviewTooltip", "PreviewActive", "Cancel", "Apply", ...
                "ChoiceFractionalCoordinates", ...
                "ChoiceCartesianCoordinates", ...
                "ChoiceToleranceVeryFine", "ChoiceToleranceFine", ...
                "ChoiceToleranceGood", "ChoiceToleranceCoarse", ...
                "ChoiceGeometricContactScore", ...
                "ChoiceUffVdwInteractionEnergy", ...
                "UffInteractionEnergyScore", ...
                "UffSurfaceModelNotice", ...
                "HelpInformation", ...
                "ValidationError", "NoAvailableStructures", ...
                "NoParametersRequired", ...
                "RunningCommand", "CompletedCommand"];
            commandIds = kssolv.modeling.CommandCatalog.commandIds();

            for locale = ["en_US", "zh_CN"]
                kssolv.ui.util.Localizer.setLocale(locale);
                for keyIndex = 1:numel(fixedKeys)
                    testCase.verifyNotEmpty( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:" + fixedKeys(keyIndex)));
                end
                for commandIndex = 1:numel(commandIds)
                    commandInfo = kssolv.modeling.CommandCatalog.find( ...
                        commandIds(commandIndex));
                    testCase.verifyNotEmpty( ...
                        kssolv.ui.util.Localizer.message( ...
                        commandInfo.labelKey));
                    testCase.verifyNotEmpty( ...
                        kssolv.ui.util.Localizer.message( ...
                        commandInfo.tooltipKey));
                    fields = ...
                        kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                        commandInfo.id, display);
                    for fieldIndex = 1:numel(fields)
                        key = "KSSOLV:modeling:Field_" + ...
                            fields(fieldIndex).name;
                        testCase.verifyNotEmpty( ...
                            kssolv.ui.util.Localizer.message(key));
                    end
                    help = ...
                        kssolv.ui.features.modeling.ParameterHelp.describe( ...
                        commandInfo.id);
                    if help.key ~= ""
                        testCase.verifyNotEmpty(help.title);
                        testCase.verifyNotEmpty(help.text);
                        if any(help.key == ...
                                kssolv.ui.features.modeling. ...
                                ParameterHelp.formulaTopics())
                            testCase.verifyNotEmpty(help.formula);
                            testCase.verifyNotEmpty(help.symbols);
                        else
                            testCase.verifyEqual(help.formula, "");
                            testCase.verifyEqual(help.symbols, "");
                        end
                    end
                end
                if locale == "zh_CN"
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_species")), ...
                        "元素符号");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_indices")), ...
                        "原子序号（从 1 开始）");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:BuildSlab")), ...
                        "构建表面模型");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_slabSize")), ...
                        "表面模型最小厚度（Å）");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_intermediateCount")), ...
                        "NEB 中间构型数");
                    testCase.verifyEqual(string( ...
                        kssolv.ui.util.Localizer.message( ...
                        "KSSOLV:modeling:Field_maximumIndex")), ...
                        "最大周期匹配指数");
                    adsorptionFields = ...
                        kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                        "find_adsorption_sites", display);
                    adsorptionHeight = ...
                        kssolv.ui.features.modeling.ParameterPresentation.describe( ...
                        "find_adsorption_sites", ...
                        adsorptionFields( ...
                        [adsorptionFields.name] == "distance"));
                    testCase.verifyEqual(string( ...
                        adsorptionHeight.label), "吸附原子高度（Å）");
                    passivationFields = ...
                        kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                        "passivate_surface", display);
                    passivant = ...
                        kssolv.ui.features.modeling.ParameterPresentation.describe( ...
                        "passivate_surface", ...
                        passivationFields( ...
                        [passivationFields.name] == "species"));
                    testCase.verifyEqual(string(passivant.label), ...
                        "钝化元素");
                end
            end
            clear displayCleanup cleanup
        end

        function everyCommandDialogAcceptsItsDefaultForm(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            commandIds = kssolv.modeling.CommandCatalog.commandIds();

            for index = 1:numel(commandIds)
                commandId = commandIds(index);
                commandInfo = ...
                    kssolv.modeling.CommandCatalog.find(commandId);
                fields = ...
                    kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                    commandId, display);
                preset = testCase.referencePreset(fields);
                dialog = kssolv.ui.features.modeling.CommandDialog( ...
                    commandInfo, display, preset);
                dialogCleanup = onCleanup(@()deleteIfValid(dialog));

                callback = ...
                    dialog.Widgets.ApplyButton.ButtonPushedFcn;
                callback([], []);
                parameters = dialog.Parameters;
                cancelled = dialog.Cancelled;

                testCase.verifyFalse(cancelled, ...
                    "Default form did not apply for " + commandId);
                testCase.verifyClass(parameters, "struct");
                clear dialogCleanup
            end
            clear cleanup

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value)
                    delete(value);
                end
            end
        end

        function commandDialogActionsKeepSymmetricVerticalGutters(testCase)
            initialTimerCount = numel(timerfindall);
            originalLocale = string(kssolv.ui.util.Localizer. ...
                getInstance().currentLocale);
            localeCleanup = onCleanup(@() ...
                kssolv.ui.util.Localizer.setLocale(originalLocale));
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            for locale = ["zh_CN", "en_US"]
                kssolv.ui.util.Localizer.setLocale(locale);
                dialog = testCase.createDialog( ...
                    display, "create_point_defects", struct());
                dialogCleanup = onCleanup(@()deleteIfValid(dialog));
                figureHandle = ancestor( ...
                    dialog.Widgets.ApplyButton, "figure");
                figureHandle.Visible = "on";
                drawnow;
                pause(0.35);
                assertSymmetry();

                dialog.Widgets.HelpToggleButton.ButtonPushedFcn([], []);
                assertStableSymmetry();

                dialog.Widgets.indices.Value = "invalid";
                dialog.Widgets.ApplyButton.ButtonPushedFcn([], []);
                testCase.verifyEqual( ...
                    string(dialog.Widgets.StatusLabel.Visible), "on");
                assertStableSymmetry();
                clear dialogCleanup
            end
            testCase.verifyEqual(numel(timerfindall), initialTimerCount, ...
                "Dialog layout must not use deferred correction timers.");
            clear cleanup localeCleanup

            function assertStableSymmetry()
                heightAfterCallback = figureHandle.Position(4);
                assertSymmetry();
                testCase.verifyEqual(figureHandle.Position(4), ...
                    heightAfterCallback, "AbsTol", 1.0, ...
                    "Dialog height must not change after it is painted.");
            end

            function assertSymmetry()
                drawnow;
                pause(1.0);
                drawnow;
                verifyCurrentGeometry();
            end

            function verifyCurrentGeometry()
                position = getpixelposition( ...
                    dialog.Widgets.ApplyButton, true);
                topClearance = dialog.actionTopGap();
                testCase.verifyEqual(position(2), topClearance, ...
                    "AbsTol", 0.75, ...
                    "The action row must have equal space above and below.");
                testCase.verifyGreaterThan(position(2), 0, ...
                    "The Modeling action row is clipped at the bottom.");
                testCase.verifyGreaterThan(position(4), 0, ...
                    "The Modeling action buttons are clipped.");
            end

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value), delete(value); end
            end
        end

        function commandDialogFirstVisibleFrameIsFinal(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            dialog = testCase.createDialog( ...
                display, "create_point_defects", struct());
            dialogCleanup = onCleanup(@()deleteIfValid(dialog));
            figureHandle = dialog.getWidget();
            visiblePositions = zeros(0, 4);
            sampler = timer("ExecutionMode", "singleShot", ...
                "StartDelay", 0.1, ...
                "TimerFcn", @(~, ~)sampleAndClose());
            timerCleanup = onCleanup(@()deleteTimers(sampler));
            start(sampler);
            [~, cancelled] = dialog.show();

            testCase.verifyTrue(cancelled);
            deleteTimers(sampler);
            testCase.verifyGreaterThanOrEqual( ...
                size(visiblePositions, 1), 5, ...
                "The visible dialog position was not sampled enough.");
            displacement = max(abs(visiblePositions - ...
                visiblePositions(1, :)), [], 2);
            testCase.verifyLessThanOrEqual(max(displacement), 1, ...
                "A visible dialog must never be repositioned.");
            clear timerCleanup dialogCleanup cleanup

            function sampleAndClose()
                for sampleIndex = 1:8
                    if string(figureHandle.Visible) == "on"
                        visiblePositions(end + 1, :) = ... %#ok<AGROW>
                            figureHandle.Position;
                    end
                    drawnow;
                    pause(0.05);
                end
                if isvalid(dialog)
                    dialog.Widgets.CancelButton.ButtonPushedFcn([], []);
                end
            end

            function deleteTimers(varargin)
                for value = [varargin{:}]
                    if ~isempty(value) && isvalid(value)
                        stop(value);
                        delete(value);
                    end
                end
            end

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value), delete(value); end
            end
        end

        function locatorOffersExplicitGeometryAndUffScoring(testCase)
            originalLocale = string(kssolv.ui.util.Localizer. ...
                getInstance().currentLocale);
            localeCleanup = onCleanup(@() ...
                kssolv.ui.util.Localizer.setLocale(originalLocale));
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            fields = kssolv.ui.features.modeling.ParameterSchema. ...
                forCommand("locate_adsorbate", display);
            scoringField = fields([fields.name] == "scoringModel");
            testCase.verifyNumElements(scoringField, 1);
            testCase.verifyEqual(string(scoringField.defaultValue), ...
                kssolv.modeling.adsorption. ...
                AdsorptionScoringModel.GeometryId);
            presentation = kssolv.ui.features.modeling. ...
                ParameterPresentation.describe( ...
                "locate_adsorbate", scoringField);
            testCase.verifyEqual(presentation.control, "enum");
            testCase.verifyEqual(presentation.choices, [ ...
                kssolv.modeling.adsorption. ...
                AdsorptionScoringModel.GeometryId; ...
                kssolv.modeling.adsorption.UffSurfaceScorer.Id]);
            dialog = testCase.createDialog(display, ...
                "locate_adsorbate", struct("scoringModel", ...
                kssolv.modeling.adsorption.UffSurfaceScorer.Id));
            dialogCleanup = onCleanup(@()delete(dialog));
            testCase.verifyClass(dialog.Widgets.scoringModel, ...
                "matlab.ui.control.DropDown");
            testCase.verifyEqual(string( ...
                dialog.Widgets.scoringModel.Value), ...
                kssolv.modeling.adsorption.UffSurfaceScorer.Id);
            for locale = ["en_US", "zh_CN"]
                kssolv.ui.util.Localizer.setLocale(locale);
                localized = kssolv.ui.features.modeling. ...
                    ParameterPresentation.describe( ...
                    "locate_adsorbate", scoringField);
                testCase.verifyTrue(all(strlength( ...
                    localized.choiceLabels) > 10));
            end
            clear dialogCleanup cleanup localeCleanup
        end

        function modelCommandPreviewIsSideEffectFreeAndCancelable(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            baseline = kssolv.modeling.provenance.CanonicalHash.of( ...
                display.getModel());
            dialog = testCase.createDialog(display, "translate_atoms", ...
                struct("indices", 1, "vector", [.2, 0, 0], ...
                "fractional", true));
            dialogCleanup = onCleanup(@()deleteIfValid(dialog));

            preview = dialog.Widgets.PreviewButton.ButtonPushedFcn;
            preview([], []);
            testCase.verifyTrue(display.isModelingPreviewActive());
            testCase.verifyEqual( ...
                kssolv.modeling.provenance.CanonicalHash.of( ...
                display.getModel()), baseline);
            cancel = dialog.Widgets.CancelButton.ButtonPushedFcn;
            cancel([], []);
            testCase.verifyFalse(display.isModelingPreviewActive());
            testCase.verifyEqual( ...
                kssolv.modeling.provenance.CanonicalHash.of( ...
                display.getModel()), baseline);
            clear dialogCleanup cleanup

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value), delete(value); end
            end
        end

        function fragmentBrowserSearchesAndReturnsConnectionPort(testCase)
            selectedName = "";
            selectedHead = 0;
            selectedPort = "";
            storePath = string(tempname) + ".json";
            browser = kssolv.ui.features.modeling.FragmentBrowser( ...
                @captureSelection, Visible = false, ...
                StorePath = storePath);
            cleanup = onCleanup(@()deleteIfValid(browser));

            testCase.verifyGreaterThanOrEqual(numel(browser.Entries), 6);
            browser.refresh("phenyl");
            testCase.verifyEqual(numel(browser.Entries), 1);
            testCase.verifyEqual(string(browser.Entries(1).name), "Phenyl");
            browser.select(1);
            browser.Widgets.Port.Value = "head";
            browser.attachSelected();
            testCase.verifyEqual(selectedName, "Phenyl");
            testCase.verifyEqual(selectedPort, "head");
            testCase.verifyEqual(selectedHead, 1);
            testCase.verifyEqual(string(browser.Widgets.Table.Data.Name), ...
                "Phenyl");
            clear cleanup

            function captureSelection(name, portId, head)
                selectedName = string(name);
                selectedPort = string(portId);
                selectedHead = double(head);
            end

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value), delete(value); end
            end
        end

        function verifiedRecoveryDraftCanBeRestoredAndDiscarded(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            tag = "Recovery-" + string(matlab.lang.internal.uuid);
            source = kssolv.ui.components.figuredocument.MoleculeDisplay( ...
                display.getModel(), "", tag);
            sourceCleanup = onCleanup(@()delete(source));
            translated = source.getModel();
            translated = translated.translate_sites(1, [.2, 0, 0], ...
                frac_coords = true);
            source.applyModel(translated, "Recovery fixture");
            testCase.verifyTrue(source.hasRecoveryDraft());

            reopened = kssolv.ui.components.figuredocument.MoleculeDisplay( ...
                display.getModel(), "", tag);
            reopenedCleanup = onCleanup(@()delete(reopened));
            testCase.verifyTrue(reopened.hasRecoveryDraft());
            snapshot = reopened.restoreRecoveryDraft();
            testCase.verifyEqual(reopened.getRevision(), snapshot.revision);
            testCase.verifyEqual( ...
                kssolv.modeling.provenance.CanonicalHash.of( ...
                reopened.getModel()), snapshot.modelHash);
            reopened.discardRecoveryDraft();
            testCase.verifyFalse(reopened.hasRecoveryDraft());
            clear reopenedCleanup sourceCleanup cleanup
        end

        function everyParameterDialogCanShowAndCancel(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            commandIds = kssolv.modeling.CommandCatalog.commandIds();
            commandIds(commandIds == "wigner_seitz_cell") = [];

            for index = 1:numel(commandIds)
                commandId = commandIds(index);
                commandInfo = ...
                    kssolv.modeling.CommandCatalog.find(commandId);
                fields = ...
                    kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                    commandId, display);
                preset = testCase.referencePreset(fields);
                dialog = kssolv.ui.features.modeling.CommandDialog( ...
                    commandInfo, display, preset);
                dialogCleanup = onCleanup(@()deleteIfValid(dialog));
                cancelCallback = ...
                    dialog.Widgets.CancelButton.ButtonPushedFcn;
                closeTimer = timer( ...
                    "StartDelay", 0.02, ...
                    "TimerFcn", @(~, ~)cancelCallback([], []));
                timerCleanup = onCleanup(@()deleteTimer(closeTimer));

                start(closeTimer);
                [parameters, cancelled] = dialog.show(app);

                testCase.verifyTrue(cancelled, ...
                    "Dialog did not cancel for " + commandId);
                testCase.verifyEmpty(fieldnames(parameters));
                clear timerCleanup dialogCleanup
            end
            clear cleanup

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value)
                    delete(value);
                end
            end

            function deleteTimer(value)
                if isvalid(value)
                    stop(value);
                    delete(value);
                end
            end
        end

        function commandDialogSupportsAppContainerModalHost(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            commandInfo = ...
                kssolv.modeling.CommandCatalog.find("translate_atoms");
            dialog = kssolv.ui.features.modeling.CommandDialog( ...
                commandInfo, display, struct());
            dialogCleanup = onCleanup(@()deleteIfValid(dialog));
            dialogFigure = dialog.getWidget();
            testCase.verifyEqual( ...
                string(dialogFigure.WindowStyle), "modal");
            cancelCallback = dialog.Widgets.CancelButton.ButtonPushedFcn;
            closeTimer = timer( ...
                "StartDelay", 0.1, ...
                "TimerFcn", @(~, ~)cancelCallback([], []));
            timerCleanup = onCleanup(@()deleteTimer(closeTimer));

            start(closeTimer);
            [parameters, cancelled] = dialog.show(app);

            testCase.verifyTrue(cancelled);
            testCase.verifyEmpty(fieldnames(parameters));
            clear timerCleanup dialogCleanup cleanup

            function deleteIfValid(value)
                if ~isempty(value) && isvalid(value)
                    delete(value);
                end
            end

            function deleteTimer(value)
                if isvalid(value)
                    stop(value);
                    delete(value);
                end
            end
        end

        function commandDialogsUseCompactContentSizedLayout(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));

            compact = testCase.createDialog( ...
                display, "build_supercell", struct());
            compactCleanup = onCleanup(@()delete(compact));
            compactPosition = compact.getWidget().Position;
            testCase.verifyEqual(compactPosition(3), 560);
            % R2026b macOS HiDPI reports an additional fitted-text allowance
            % while the dialog remains within the intended compact range.
            testCase.verifyLessThanOrEqual(compactPosition(4), 245);
            testCase.verifyEqual(string(compact.getWidget().Resize), "off");
            testCase.verifyEqual( ...
                compact.Widgets.ButtonLayout.RowHeight{1}, 0);
            testCase.verifyEqual( ...
                compact.Widgets.FormPanel.Parent.Padding(2), 16);
            testCase.verifyEqual( ...
                compact.Widgets.FormLayout.ColumnWidth, {'1x'});
            compactLabelAlignment = ...
                compact.Widgets.scalingMatrixLabel.HorizontalAlignment;
            testCase.verifyEqual( ...
                string(compactLabelAlignment), "left");

            detailed = testCase.createDialog( ...
                display, "add_solvent_layer", struct());
            detailedCleanup = onCleanup(@()delete(detailed));
            detailedPosition = detailed.getWidget().Position;
            testCase.verifyEqual(detailedPosition(3), 560);
            testCase.verifyGreaterThan( ...
                detailedPosition(4), compactPosition(4));

            medium = testCase.createDialog( ...
                display, "rotate_atoms", struct("indices", 1));
            mediumCleanup = onCleanup(@()delete(medium));
            actionBox = getpixelposition( ...
                medium.Widgets.ApplyButton, true);
            testCase.verifyGreaterThanOrEqual(actionBox(2), 1, ...
                "The fixed action row is clipped below the dialog.");
            testCase.verifyLessThanOrEqual( ...
                actionBox(2) + actionBox(4), ...
                medium.getWidget().Position(4), ...
                "The fixed action row extends beyond the dialog.");

            vacancy = testCase.createDialog( ...
                display, "create_point_defects", ...
                struct("defectType", "vacancy"));
            vacancyCleanup = onCleanup(@()delete(vacancy));
            vacancyPosition = vacancy.getWidget().Position;
            vacancyCenter = vacancyPosition(1:2) + ...
                vacancyPosition(3:4) / 2;
            vacancy.Widgets.defectType.Value = "interstitial";
            conditionCallback = ...
                vacancy.Widgets.defectType.ValueChangedFcn;
            conditionCallback([], []);
            interstitialPosition = vacancy.getWidget().Position;
            interstitialCenter = interstitialPosition(1:2) + ...
                interstitialPosition(3:4) / 2;
            testCase.verifyLessThan( ...
                vacancyPosition(4), interstitialPosition(4));
            testCase.verifyEqual( ...
                interstitialCenter, vacancyCenter, "AbsTol", 1e-12);

            clear vacancyCleanup mediumCleanup detailedCleanup ...
                compactCleanup cleanup
        end

        function logicalFieldsUseSelfLabeledCompactCheckboxes(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            dialog = testCase.createDialog( ...
                display, "sort_atoms", struct("reverse", true));
            dialogCleanup = onCleanup(@()delete(dialog));

            testCase.verifyClass( ...
                dialog.Widgets.reverse, "matlab.ui.control.CheckBox");
            testCase.verifyEqual( ...
                string(dialog.Widgets.reverse.Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:Field_reverse")));
            testCase.verifyNotEqual( ...
                string(dialog.Widgets.reverse.Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:Enabled")));
            testCase.verifyTrue( ...
                dialog.Widgets.reverse == dialog.Widgets.reverseLabel);
            testCase.verifyEqual( ...
                numel(dialog.Widgets.reverse.Parent.RowHeight), 1);
            testCase.verifyTrue(dialog.Widgets.reverse.Value);

            clear dialogCleanup cleanup
        end

        function technicalHelpIsInlineCollapsedAndLatexFormatted(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));

            mirror = testCase.createDialog( ...
                display, "mirror_atoms", struct());
            mirrorCleanup = onCleanup(@()delete(mirror));
            testCase.verifyTrue(isfield( ...
                mirror.Widgets, "HelpToggleButton"));
            testCase.verifyClass( ...
                mirror.Widgets.HelpToggleButton, ...
                "matlab.ui.control.Button");
            testCase.verifyEqual( ...
                string(mirror.Widgets.HelpPanel.Visible), "off");
            testCase.verifyEqual( ...
                mirror.Widgets.HelpLayout.RowHeight{2}, 0);
            testCase.verifyEqual( ...
                string(mirror.Widgets.HelpToggleButton.Text), "");
            testCase.verifyEqual( ...
                mirror.Widgets.HelpHeaderLayout.ColumnWidth, ...
                {26, 'fit', '1x'});
            testCase.verifyClass( ...
                mirror.Widgets.HelpInformationLabel, ...
                "matlab.ui.control.Label");
            testCase.verifyEqual( ...
                string(mirror.Widgets.HelpInformationLabel.Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:HelpInformation")));
            testCase.verifyFalse(isfield( ...
                mirror.Widgets, "normalHelpButton"));
            testCase.verifyEqual( ...
                mirror.Widgets.normal.Parent.ColumnWidth, {'1x'});
            testCase.verifyEqual( ...
                string(mirror.Widgets.HelpFormulaLabel.Interpreter), ...
                "latex");
            testCase.verifyTrue(contains( ...
                string(mirror.Widgets.HelpFormulaLabel.Text), "\hat"));
            testCase.verifyTrue(isfield( ...
                mirror.Widgets, "HelpSymbolsLabel"));
            testCase.verifyTrue(contains( ...
                string(mirror.Widgets.HelpSymbolsLabel.Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:modeling:HelpSymbols_MirrorAtoms"))));

            collapsedPosition = mirror.getWidget().Position;
            collapsedCenter = collapsedPosition(1:2) + ...
                collapsedPosition(3:4) / 2;
            mirror.Widgets.HelpToggleButton.ButtonPushedFcn([], []);
            expandedPosition = mirror.getWidget().Position;
            expandedCenter = expandedPosition(1:2) + ...
                expandedPosition(3:4) / 2;
            testCase.verifyEqual( ...
                string(mirror.Widgets.HelpPanel.Visible), "on");
            testCase.verifyGreaterThan( ...
                mirror.Widgets.HelpLayout.RowHeight{2}, 0);
            testCase.verifyGreaterThan( ...
                expandedPosition(4), collapsedPosition(4));
            testCase.verifyEqual( ...
                expandedCenter, collapsedCenter, "AbsTol", 1e-12);

            mirror.Widgets.HelpToggleButton.ButtonPushedFcn([], []);
            testCase.verifyEqual( ...
                string(mirror.Widgets.HelpPanel.Visible), "off");
            testCase.verifyEqual( ...
                mirror.getWidget().Position(4), collapsedPosition(4), ...
                "AbsTol", 1e-12);

            simple = testCase.createDialog( ...
                display, "delete_atoms", struct());
            simpleCleanup = onCleanup(@()delete(simple));
            testCase.verifyFalse(isfield( ...
                simple.Widgets, "HelpToggleButton"));
            testCase.verifyEqual( ...
                simple.Widgets.indices.Parent.ColumnWidth, {'1x'});

            lattice = testCase.createDialog( ...
                display, "edit_lattice", struct());
            latticeCleanup = onCleanup(@()delete(lattice));
            testCase.verifyTrue(isfield( ...
                lattice.Widgets, "HelpToggleButton"));
            testCase.verifyEqual( ...
                lattice.Widgets.preserveCartesian.Parent.ColumnWidth, ...
                {'1x'});

            clear latticeCleanup simpleCleanup mirrorCleanup cleanup
        end

        function commandDialogTextFollowsActiveLocale(testCase)
            localizer = kssolv.ui.util.Localizer.getInstance();
            originalLocale = string(localizer.currentLocale);
            localeCleanup = onCleanup(@() ...
                kssolv.ui.util.Localizer.setLocale(originalLocale));
            [app, display] = testCase.createDisplay();
            displayCleanup = onCleanup(@()testCase.cleanupDisplay(app));
            cases = {
                "en_US", "Mirror Atoms", "Help information", ...
                    "Mirror plane"
                "zh_CN", "镜像原子", "帮助信息", "镜像平面"
                };

            for index = 1:size(cases, 1)
                kssolv.ui.util.Localizer.setLocale(cases{index, 1});
                dialog = testCase.createDialog( ...
                    display, "mirror_atoms", struct());
                dialogCleanup = onCleanup(@()delete(dialog));

                testCase.verifyEqual( ...
                    string(dialog.Widgets.TitleLabel.Text), ...
                    cases{index, 2});
                testCase.verifyEqual( ...
                    string(dialog.Widgets.HelpInformationLabel.Text), ...
                    cases{index, 3});
                testCase.verifyEqual( ...
                    string(dialog.Widgets.HelpTitleLabel.Text), ...
                    cases{index, 4});
                clear dialogCleanup
            end

            clear displayCleanup localeCleanup
        end

        function coordinateSystemsUseDropdownsAndReturnLogicals(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));

            addAtom = testCase.createDialog( ...
                display, "add_atom", struct("cartesian", false));
            addAtomCleanup = onCleanup(@()delete(addAtom));
            testCase.verifyClass( ...
                addAtom.Widgets.cartesian, "matlab.ui.control.DropDown");
            testCase.verifyEqual( ...
                string(addAtom.Widgets.cartesian.ItemsData), ...
                ["fractional", "cartesian"]);
            testCase.verifyEqual( ...
                string(addAtom.Widgets.cartesian.Value), "fractional");
            addAtom.Widgets.cartesian.Value = "cartesian";
            addAtom.Widgets.ApplyButton.ButtonPushedFcn([], []);
            testCase.verifyTrue(addAtom.Parameters.cartesian);
            testCase.verifyClass(addAtom.Parameters.cartesian, "logical");
            clear addAtomCleanup

            translate = testCase.createDialog( ...
                display, "translate_atoms", struct("fractional", false));
            translateCleanup = onCleanup(@()delete(translate));
            testCase.verifyClass( ...
                translate.Widgets.fractional, ...
                "matlab.ui.control.DropDown");
            testCase.verifyEqual( ...
                string(translate.Widgets.fractional.Value), "cartesian");
            translate.Widgets.fractional.Value = "fractional";
            translate.Widgets.ApplyButton.ButtonPushedFcn([], []);
            testCase.verifyTrue(translate.Parameters.fractional);
            testCase.verifyClass(translate.Parameters.fractional, "logical");

            clear translateCleanup cleanup
        end

        function coordinateSystemPrecedesItsCoordinateInput(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            cases = {
                "add_atom", "cartesian", "coordinates"
                "move_atoms", "cartesian", "coordinates"
                "translate_atoms", "fractional", "vector"
                "create_point_defects", "cartesian", "coordinates"
                };

            for index = 1:size(cases, 1)
                fields = ...
                    kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                    cases{index, 1}, display);
                names = string({fields.name});
                coordinateSystemIndex = find( ...
                    names == cases{index, 2}, 1);
                coordinateInputIndex = find( ...
                    names == cases{index, 3}, 1);
                testCase.verifyLessThan( ...
                    coordinateSystemIndex, coordinateInputIndex, ...
                    "Coordinate system follows its input for " + ...
                    cases{index, 1});
            end

            clear cleanup
        end

        function symmetryToleranceUsesFourNumericLevels(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            expected = ["0.0001", "0.001", "0.01", "0.1"];

            for commandId = ["find_symmetry", "primitive_cell", ...
                    "conventional_cell"]
                fields = ...
                    kssolv.ui.features.modeling.ParameterSchema.forCommand( ...
                    commandId, display);
                symprec = fields([fields.name] == "symprec");
                presentation = ...
                    kssolv.ui.features.modeling.ParameterPresentation.describe( ...
                    commandId, symprec);
                testCase.verifyEqual(presentation.control, "numericEnum");
                testCase.verifyEqual(presentation.choices.', expected);
            end

            dialog = testCase.createDialog( ...
                display, "primitive_cell", struct("symprec", 0.001));
            dialogCleanup = onCleanup(@()delete(dialog));
            testCase.verifyClass( ...
                dialog.Widgets.symprec, "matlab.ui.control.DropDown");
            testCase.verifyEqual( ...
                string(dialog.Widgets.symprec.Value), "0.001");
            dialog.Widgets.ApplyButton.ButtonPushedFcn([], []);
            testCase.verifyEqual(dialog.Parameters.symprec, 0.001, ...
                "AbsTol", eps(0.001));
            testCase.verifyClass(dialog.Parameters.symprec, "double");

            clear dialogCleanup cleanup
        end

        function defectAndQuantumPresetsControlVisibleFields(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));

            vacancy = testCase.createDialog( ...
                display, "create_point_defects", ...
                struct("defectType", "vacancy"));
            vacancyCleanup = onCleanup(@()delete(vacancy));
            testCase.verifyEqual( ...
                string(vacancy.Widgets.indices.Visible), "on");
            testCase.verifyEqual( ...
                string(vacancy.Widgets.species.Visible), "off");
            testCase.verifyEqual( ...
                string(vacancy.Widgets.coordinates.Visible), "off");
            clear vacancyCleanup

            interstitial = testCase.createDialog( ...
                display, "create_point_defects", ...
                struct("defectType", "interstitial"));
            interstitialCleanup = onCleanup(@()delete(interstitial));
            testCase.verifyEqual( ...
                string(interstitial.Widgets.indices.Visible), "off");
            testCase.verifyEqual( ...
                string(interstitial.Widgets.species.Visible), "on");
            testCase.verifyEqual( ...
                string(interstitial.Widgets.coordinates.Visible), "on");
            clear interstitialCleanup

            dot = testCase.createDialog( ...
                display, "quantum_dot_void", struct("mode", "dot"));
            dotCleanup = onCleanup(@()delete(dot));
            testCase.verifyEqual( ...
                string(dot.Widgets.vacuum.Visible), "on");
            clear dotCleanup

            void = testCase.createDialog( ...
                display, "quantum_dot_void", struct("mode", "void"));
            voidCleanup = onCleanup(@()delete(void));
            testCase.verifyEqual( ...
                string(void.Widgets.vacuum.Visible), "off");
            clear voidCleanup
            clear cleanup
        end

        function sketchAtomDefaultsToForceFieldLengthForSelectedHost( ...
                testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            display.setSelectedSiteIndices(2);

            fields = kssolv.ui.features.modeling.ParameterSchema. ...
                forCommand("sketch_atom", display);
            connectTo = fields([fields.name] == "connectTo");
            ideal = fields([fields.name] == "useIdealBondLength");
            testCase.verifyEqual(connectTo.defaultValue, "2");
            testCase.verifyEqual(ideal.defaultValue, "true");

            dialog = testCase.createDialog(display, "sketch_atom", struct());
            dialogCleanup = onCleanup(@()delete(dialog));
            testCase.verifyTrue(dialog.Widgets.useIdealBondLength.Value);
            testCase.verifyEqual( ...
                string(dialog.Widgets.coordinates.Visible), "off");
            dialog.Widgets.useIdealBondLength.Value = false;
            dialog.Widgets.useIdealBondLength.ValueChangedFcn([], []);
            testCase.verifyEqual( ...
                string(dialog.Widgets.coordinates.Visible), "on");
            clear dialogCleanup cleanup
        end

        function invalidSiteIndexIsRejectedInline(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            dialog = testCase.createDialog( ...
                display, "delete_atoms", struct("indices", 0));
            dialogCleanup = onCleanup(@()delete(dialog));
            callback = dialog.Widgets.ApplyButton.ButtonPushedFcn;

            testCase.verifyError(@()callback([], []), ...
                "KSSOLV:Modeling:ParameterRange");
            testCase.verifyEqual( ...
                string(dialog.Widgets.StatusLabel.Visible), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.ButtonLayout.RowHeight{1}), "fit");
            testCase.verifyTrue(dialog.Cancelled);
            clear dialogCleanup cleanup
        end

        function supercellDialogAcceptsGeneralIntegerMatrix(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            matrix = [1, -1, 0; 0, 1, -1; 1, 1, 1];
            dialog = testCase.createDialog( ...
                display, "build_supercell", ...
                struct("scalingMatrix", matrix));
            dialogCleanup = onCleanup(@()delete(dialog));
            callback = dialog.Widgets.ApplyButton.ButtonPushedFcn;
            callback([], []);

            testCase.verifyFalse(dialog.Cancelled);
            testCase.verifyEqual( ...
                dialog.Parameters.scalingMatrix, matrix);
            clear dialogCleanup cleanup
        end

        function supercellDialogRejectsSingularIntegerMatrix(testCase)
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            matrix = [1, 0, 0; 0, 1, 0; 0, 0, 0];
            dialog = testCase.createDialog( ...
                display, "build_supercell", ...
                struct("scalingMatrix", matrix));
            dialogCleanup = onCleanup(@()delete(dialog));
            callback = dialog.Widgets.ApplyButton.ButtonPushedFcn;

            testCase.verifyError(@()callback([], []), ...
                "KSSOLV:Modeling:ScalingMatrix");
            testCase.verifyTrue(dialog.Cancelled);
            clear dialogCleanup cleanup
        end

        function projectStructureReferencesResolveToCopies(testCase)
            addpath(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "+kssolv", "+core", "kssolv-3o"));
            KSSOLV.startup();
            [app, display] = testCase.createDisplay();
            cleanup = onCleanup(@()testCase.cleanupDisplay(app));
            project = kssolv.services.filemanager.Project();
            folder = project.findChildrenItem("Structure");
            reference = kssolv.services.filemanager.Structure( ...
                "Reference structure");
            reference.data = ...
                kssolv.services.fileparser.ModeledStructureData( ...
                display.getModel(), "Reference structure");
            folder.addChildrenItem(reference);
            kssolv.ui.util.DataStorage.setData("Project", project);
            projectCleanup = onCleanup(@() ...
                kssolv.ui.util.DataStorage.removeData("Project"));

            available = ...
                kssolv.ui.features.modeling.ModelInputResolver.available(display);
            testCase.verifyTrue(any(available == "Reference structure"));
            resolved = ...
                kssolv.ui.features.modeling.ModelInputResolver.resolve( ...
                "Reference structure");
            testCase.verifyEqual(resolved.frac_coords, ...
                display.getModel().frac_coords, AbsTol = 1e-12);
            testCase.verifyFalse(isequal(resolved, display.getModel()));

            cases = {
                "insert_structure", "otherStructureName", "otherModel"
                "stack_heterostructure", "otherStructureName", "otherModel"
                "twist_moire", "otherStructureName", "otherModel"
                "interpolate_neb", "endStructureName", "endModel"
                "add_solvent_layer", "solventStructureName", "solventModel"
                };
            for index = 1:size(cases, 1)
                parameters = struct();
                parameters.(cases{index, 2}) = "Reference structure";
                enriched = ...
                    kssolv.ui.features.modeling.ModelInputResolver.enrich( ...
                    cases{index, 1}, parameters);
                testCase.verifyTrue(isfield(enriched, cases{index, 3}));
                testCase.verifyClass(enriched.(cases{index, 3}), ...
                    "kssolv.analysis.matgenlab.core.Structure");
            end
            clear projectCleanup cleanup
        end
    end

    methods (Static, Access = private)
        function [app, display] = createDisplay()
            app = matlab.ui.container.internal.AppContainer( ...
                struct("Title", "Modeling Dialog Test", ...
                "ToolstripEnabled", true));
            kssolv.ui.util.DataStorage.setData("AppContainer", app);
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                diag([4, 5, 6]), {"Si", "O"}, ...
                [0, 0, 0; .25, .25, .25]);
            display = ...
                kssolv.ui.components.figuredocument.MoleculeDisplay( ...
                structure);
        end

        function cleanupDisplay(app)
            close(findall(groot, "Type", "figure"));
            if ~isempty(app) && isvalid(app)
                delete(app);
            end
            kssolv.ui.util.DataStorage.removeData("AppContainer");
        end

        function preset = referencePreset(fields)
            preset = struct();
            for index = 1:numel(fields)
                name = string(fields(index).name);
                if endsWith(name, "StructureName")
                    preset.(char(name)) = "Reference structure";
                end
            end
        end

        function dialog = createDialog(display, commandId, preset)
            commandInfo = kssolv.modeling.CommandCatalog.find(commandId);
            dialog = kssolv.ui.features.modeling.CommandDialog( ...
                commandInfo, display, preset);
        end
    end
end
