classdef RemoteComputingUITest < matlab.unittest.TestCase
    %REMOTECOMPUTINGUITEST UI construction tests for remote computing.

    methods (Test)
        function clusterManagerBuildsAndAddsDraft(testCase)
            root = temporaryRoot(testCase);
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore(root);
            selectionStore = ...
                kssolv.services.remote.config.RemoteSelectionStore(root);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=configurationStore, ...
                SelectionStore=selectionStore, Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>

            testCase.verifyEqual(height(dialog.Widgets.Table.Data), 0);
            dialog.Widgets.Add.ButtonPushedFcn([], []);
            testCase.verifyEqual(height(dialog.Widgets.Table.Data), 1);
            testCase.verifyEqual(string( ...
                dialog.Widgets.Table.Data.Properties.VariableNames), ...
                ["Enabled", "Name", "Mode"]);
            testCase.verifyEqual(dialog.Widgets.Table.ColumnWidth, ...
                {48, 162, 85});
            testCase.verifyNumElements( ...
                dialog.Widgets.Table.ColumnName, 3);
            testCase.verifyNotEqual(string( ...
                dialog.Widgets.Host.Enable), "off");
            testCase.verifyFalse(isfield(dialog.Widgets, "Password"));
            tabs = string({dialog.Widgets.TabGroup.Children.Title});
            localizedTabs = isequal(sort(tabs), sort( ...
                ["连接", "计算"])) || ...
                isequal(sort(tabs), sort( ...
                ["Connection", "Compute"]));
            testCase.verifyTrue(localizedTabs);
            testCase.verifyEqual( ...
                dialog.Widgets.DisplayName.Parent.Parent, ...
                dialog.Widgets.ConnectionTab);
            testCase.verifyEqual( ...
                dialog.Widgets.ClusterMatlabRoot.Parent.Parent, ...
                dialog.Widgets.ComputeTab);
            testCase.verifyEqual( ...
                dialog.Widgets.PostLoginCommandTemplate.Parent.Parent, ...
                dialog.Widgets.ComputeTab);
            testCase.verifyEqual(string( ...
                dialog.Widgets.CancelResourceProbe.Enable), "off");
            testCase.verifyEqual( ...
                dialog.Widgets.ResourceProbe.Parent.Layout.Row, 22);
            testCase.verifyEqual( ...
                dialog.Widgets.ResourceProbeStatus.Layout.Row, 23);
            testCase.verifyTrue(any(string( ...
                dialog.Widgets.ResourceProbe.Text) == ...
                ["探测资源", "Probe Resources"]));
            testCase.verifyLessThan( ...
                dialog.Widgets.PostLoginPromptRules.Parent.Layout.Row, ...
                dialog.Widgets.PostLoginScript.Layout.Row);
        end

        function jobsDialogBuildsWithEmptyStore(testCase)
            root = temporaryRoot(testCase);
            manager = kssolv.services.remote.job.RemoteJobManager( ...
                kssolv.services.remote.config.RemoteConfigurationStore(root), ...
                kssolv.services.remote.job.RemoteJobStore(root));
            dialog = kssolv.ui.features.remote.RemoteJobsDialog( ...
                JobManager=manager, Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            drawnow;

            testCase.verifyEqual(height(dialog.Widgets.Table.Data), 0);
            testCase.verifyTrue(isvalid(dialog.Widgets.Refresh));
            testCase.verifyTrue(isvalid(dialog.Widgets.Fetch));
            testCase.verifyTrue(isvalid(dialog.Widgets.Delete));
            testCase.verifyEqual(string(dialog.Widgets.Delete.Enable), ...
                "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.Table.SelectionType), "row");
            testCase.verifyEqual(string( ...
                dialog.Widgets.Table.Multiselect), "on");
            testCase.verifyEqual(dialog.Widgets.Root.RowHeight{2}, 28);
            testCase.verifyEqual(dialog.Widgets.Root.RowSpacing, 12);
            testCase.verifyEqual(dialog.Widgets.Controls.Layout.Row, 2);
            testCase.verifyEqual(dialog.Widgets.Status.Parent, ...
                dialog.Widgets.Controls);
            padding = dialog.Widgets.Root.Padding;
            if isscalar(padding)
                bottomPadding = padding;
            else
                bottomPadding = padding(2);
            end
            testCase.verifyEqual(dialog.Widgets.Root.RowSpacing, ...
                bottomPadding);
        end

        function jobsDialogEnablesDeleteForSelection(testCase)
            root = temporaryRoot(testCase);
            configurationStore = kssolv.services.remote.config. ...
                RemoteConfigurationStore(root);
            jobStore = kssolv.services.remote.job.RemoteJobStore(root);
            configuration = bridgeConfiguration();
            configurationStore.upsert(configuration);
            record = kssolv.services.remote.job.RemoteJobRecord.create( ...
                configuration.Id, "Old remote job", "old-job");
            record.State = "Retrieved";
            jobStore.upsert(record);
            second = kssolv.services.remote.job.RemoteJobRecord.create( ...
                configuration.Id, "Another old job", "another-old-job");
            second.State = "Failed";
            jobStore.upsert(second);
            manager = kssolv.services.remote.job.RemoteJobManager( ...
                configurationStore, jobStore);
            dialog = kssolv.ui.features.remote.RemoteJobsDialog( ...
                JobManager=manager, Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            drawnow;

            testCase.verifyEqual(string(dialog.Widgets.Delete.Enable), ...
                "off");
            dialog.Widgets.Table.Selection = [1, 2];
            dialog.Widgets.Table.SelectionChangedFcn([], []);
            testCase.verifyEqual(string(dialog.Widgets.Delete.Enable), ...
                "on");
            dialog.Widgets.Table.Selection = [];
            dialog.Widgets.Table.SelectionChangedFcn([], []);
            testCase.verifyEqual(string(dialog.Widgets.Delete.Enable), ...
                "off");
        end

        function remoteRunReportsSubmissionPhases(testCase)
            root = temporaryRoot(testCase);
            configurationStore = kssolv.services.remote.config. ...
                RemoteConfigurationStore(root);
            selectionStore = kssolv.services.remote.config. ...
                RemoteSelectionStore(root);
            configuration = kssolv.services.remote.config. ...
                RemoteConfiguration.create(struct( ...
                "DisplayName", "Footer cluster", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "Processes"));
            configurationStore.upsert(configuration);
            selectionStore.set(configuration.Id);
            manager = kssolv.ui.test.FakeRemoteJobManager();
            recorder = kssolv.ui.test.RemoteStatusRecorder();

            [mode, record] = kssolv.ui.features.remote. ...
                RemoteRunController.execute( ...
                kssolv.services.workflow.WorkflowGraph({}), ...
                "Footer workflow", "project:footer", ...
                ConfigurationStore=configurationStore, ...
                SelectionStore=selectionStore, JobManager=manager, ...
                StatusReporter=@(text)recorder.report(text));

            testCase.verifyEqual(mode, "Remote");
            testCase.verifyEqual(record.LocalJobId, "footer-test-job");
            testCase.verifyNumElements(recorder.Messages, 3);
            testCase.verifyTrue(contains(recorder.Messages(1), ...
                "Footer workflow"));
            testCase.verifyTrue(contains(recorder.Messages(2), ...
                "Footer cluster"));
            testCase.verifyTrue(contains(recorder.Messages(3), ...
                "footer-test-job"));
        end

        function remoteRunReportsSubmissionFailure(testCase)
            root = temporaryRoot(testCase);
            configurationStore = kssolv.services.remote.config. ...
                RemoteConfigurationStore(root);
            selectionStore = kssolv.services.remote.config. ...
                RemoteSelectionStore(root);
            configuration = kssolv.services.remote.config. ...
                RemoteConfiguration.create(struct( ...
                "DisplayName", "Failing footer cluster", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "Processes"));
            configurationStore.upsert(configuration);
            selectionStore.set(configuration.Id);
            manager = kssolv.ui.test.FakeRemoteJobManager();
            manager.ShouldFail = true;
            recorder = kssolv.ui.test.RemoteStatusRecorder();
            callback = @()kssolv.ui.features.remote. ...
                RemoteRunController.execute( ...
                kssolv.services.workflow.WorkflowGraph({}), ...
                "Failing footer workflow", "project:footer", ...
                ConfigurationStore=configurationStore, ...
                SelectionStore=selectionStore, JobManager=manager, ...
                StatusReporter=@(text)recorder.report(text));

            testCase.verifyError(callback, ...
                "KSSOLV:Test:RemoteSubmissionFailure");
            testCase.verifyNumElements(recorder.Messages, 3);
            testCase.verifyTrue(contains(recorder.Messages(end), ...
                "simulated footer submission failure"));
        end

        function jobsDialogUsesCreationTimeForLegacyEmptySubmission(testCase)
            root = temporaryRoot(testCase);
            configurationStore = kssolv.services.remote.config. ...
                RemoteConfigurationStore(root);
            jobStore = kssolv.services.remote.job.RemoteJobStore(root);
            configuration = kssolv.services.remote.config. ...
                RemoteConfiguration.create(struct( ...
                "DisplayName", "Legacy submission time", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "Processes"));
            configurationStore.upsert(configuration);
            record = kssolv.services.remote.job.RemoteJobRecord.create( ...
                configuration.Id, "Legacy job");
            record.SubmittedAt = "";
            jobStore.upsert(record);
            manager = kssolv.services.remote.job.RemoteJobManager( ...
                configurationStore, jobStore);
            dialog = kssolv.ui.features.remote.RemoteJobsDialog( ...
                JobManager=manager, Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>

            testCase.verifyEqual( ...
                dialog.Widgets.Table.Data.Submitted(1), record.CreatedAt);
        end

        function footerAlignsRegionsAndKeepsButtonsFixed(testCase)
            root = temporaryRoot(testCase);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);
            drawnow;
            originalButtonHeights = [dialog.Widgets.Add.Position(4), ...
                dialog.Widgets.Save.Position(4), ...
                dialog.Widgets.Close.Position(4)];

            dialog.Widgets.Status.Text = repmat( ...
                "A deliberately long remote diagnostic message. ", 1, 20);
            drawnow;

            testCase.verifyEqual(dialog.Widgets.Root.RowHeight{2}, 28);
            testCase.verifyEqual(dialog.Widgets.Footer.RowHeight{1}, 28);
            testCase.verifyEqual(dialog.Widgets.LeftButtons.Layout.Row, 1);
            testCase.verifyEqual(dialog.Widgets.ActionButtons.Layout.Row, 1);
            testCase.verifyEqual(dialog.Widgets.Save.Layout.Row, 1);
            testCase.verifyEqual(dialog.Widgets.Close.Layout.Row, 1);
            testCase.verifyEqual(dialog.Widgets.Table.Layout.Row, 1);
            testCase.verifyEqual(dialog.Widgets.EditorPanel.Layout.Row, 1);
            testCase.verifyEqual(dialog.Widgets.Table.Position(2), ...
                dialog.Widgets.EditorPanel.Position(2), "AbsTol", 1);
            testCase.verifyEqual([dialog.Widgets.Add.Position(4), ...
                dialog.Widgets.Save.Position(4), ...
                dialog.Widgets.Close.Position(4)], ...
                originalButtonHeights, "AbsTol", 1);
            testCase.verifyEqual(string( ...
                dialog.Widgets.ConfigurationStatus.WordWrap), "off");
            testCase.verifyEqual( ...
                dialog.Widgets.ConfigurationStatus.Parent, ...
                dialog.Widgets.Footer);
            testCase.verifyEqual( ...
                dialog.Widgets.ConfigurationStatus.Layout.Column, 2);
        end

        function mirrorModeUsesSingleNodeFields(testCase)
            root = temporaryRoot(testCase);
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore(root);
            configurationStore.upsert(kssolv.services.remote.config. ...
                RemoteConfiguration.create(struct( ...
                "DisplayName", "Standalone", ...
                "ExecutionMode", "Mirror", ...
                "Host", "bridge.example.test", ...
                "Username", join(["test", "user"], "-"), ...
                "ClusterMatlabRoot", "/opt/MATLAB/R2024a", ...
                "RemoteJobStorageLocation", "/scratch/test", ...
                "PostLoginCommandTemplate", "ssh node7 -- {command}")));
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=configurationStore, ...
                SelectionStore= ...
                    kssolv.services.remote.config.RemoteSelectionStore(root), ...
                Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>

            testCase.verifyEqual(string(dialog.Widgets.ExecutionMode.Value), ...
                "Mirror");
            testCase.verifyEqual(string( ...
                dialog.Widgets.RemoteBridgeProfileName.Enable), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.RemoteBridgeProfileName.Visible), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PostLoginCommandTemplate.Enable), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PostLoginCommandTemplate.Visible), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PostLoginScript.Visible), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.ConnectionMode.Enable), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.ConnectionMode.Visible), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.CloudProvider.Visible), "off");
            testCase.verifyEqual(string(dialog.Widgets.Test.Visible), "on");
            testCase.verifyEqual( ...
                dialog.Widgets.Test.Parent.Parent.Parent, ...
                dialog.Widgets.ConnectionTab);
            testCase.verifyEqual( ...
                dialog.Widgets.ClusterMatlabRoot.Parent.Parent, ...
                dialog.Widgets.ComputeTab);
            testCase.verifyEqual( ...
                dialog.Widgets.Test.Parent.Layout.Row, 14);
            testCase.verifyEqual( ...
                dialog.Widgets.ResourceProbe.Parent.Parent.Parent, ...
                dialog.Widgets.ComputeTab);
        end

        function exposesFourMutuallyExclusiveModes(testCase)
            root = temporaryRoot(testCase);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);

            testCase.verifyEqual(string( ...
                dialog.Widgets.ExecutionMode.ItemsData), ...
                ["Standard", "Bridge", "Mirror", "Cloud"]);
            dialog.Widgets.ExecutionMode.Value = "Cloud";
            dialog.Widgets.ExecutionMode.ValueChangedFcn([], []);
            testCase.verifyEqual(string( ...
                dialog.Widgets.CloudProvider.Enable), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.CloudProvider.Visible), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PostLoginCommandTemplate.Enable), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PostLoginCommandTemplate.Visible), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PostLoginScript.Visible), "off");
            testCase.verifyEqual(string(dialog.Widgets.Host.Visible), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.ProfileSource.Visible), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.ProfileSource.Value), ...
                "ExistingMatlabProfile");
        end

        function modeSwitchShowsOnlyModeRelevantFields(testCase)
            root = temporaryRoot(testCase);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);

            setMode(dialog, "Standard");
            verifyVisibility(testCase, dialog, ...
                ["ProfileSource", "Partition", "ClusterMatlabRoot"], "on");
            verifyVisibility(testCase, dialog, ...
                ["CloudProvider", "RemoteBridgeProfileName", ...
                "ExistingProfileName"], "off");

            setMode(dialog, "Bridge");
            verifyVisibility(testCase, dialog, ...
                ["RemoteBridgeProfileName", "ClusterMatlabRoot", ...
                "PostLoginScript", "PostLoginCommandTemplate"], "on");
            verifyVisibility(testCase, dialog, ...
                ["CloudProvider", "ProfileSource", "ConnectionMode", ...
                "Partition", "ExistingProfileName"], "off");

            setMode(dialog, "Mirror");
            verifyVisibility(testCase, dialog, ...
                ["ConnectionDiscovery", "ClusterMatlabRoot", ...
                "PostLoginScript", "PostLoginCommandTemplate", ...
                "NumWorkers", "PoolSize"], ...
                "on");
            verifyVisibility(testCase, dialog, ...
                ["CloudProvider", "ProfileSource", "ConnectionMode", ...
                "RemoteBridgeProfileName", "Partition", ...
                "ExistingProfileName"], "off");

            setMode(dialog, "Cloud");
            verifyVisibility(testCase, dialog, ...
                ["CloudProvider", "CloudResourceName", "CloudRegion", ...
                "ExistingProfileName"], "on");
            verifyVisibility(testCase, dialog, ...
                ["Host", "AuthenticationMode", "ClusterMatlabRoot", ...
                "PostLoginCommandTemplate", "RemoteBridgeProfileName", ...
                "ProfileSource", "Partition"], "off");
        end

        function conditionalRowsAppearOnlyWhenSelected(testCase)
            root = temporaryRoot(testCase);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);

            testCase.verifyEqual(string( ...
                dialog.Widgets.IdentityFile.Visible), "off");
            dialog.Widgets.AuthenticationMode.Value = "IdentityFile";
            dialog.Widgets.AuthenticationMode.ValueChangedFcn([], []);
            testCase.verifyEqual(string( ...
                dialog.Widgets.IdentityFile.Visible), "on");

            testCase.verifyEqual(string( ...
                dialog.Widgets.LicenseNumber.Visible), "off");
            dialog.Widgets.RequiresOnlineLicensing.Value = true;
            dialog.Widgets.RequiresOnlineLicensing.ValueChangedFcn([], []);
            testCase.verifyEqual(string( ...
                dialog.Widgets.LicenseNumber.Visible), "on");

            testCase.verifyEqual(string( ...
                dialog.Widgets.RemoteKssolvRoot.Visible), "off");
            dialog.Widgets.CodeDeploymentMode.Value = "ClusterInstalled";
            dialog.Widgets.CodeDeploymentMode.ValueChangedFcn([], []);
            testCase.verifyEqual(string( ...
                dialog.Widgets.RemoteKssolvRoot.Visible), "on");

            helpNames = ["PostLoginCommandTemplateHelp", ...
                "PostLoginScriptHelp", "PostLoginPromptRulesHelp", ...
                "CodeDeploymentModeHelp"];
            verifyVisibility(testCase, dialog, helpNames, "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PostLoginScriptHelp.Text), "");
            testCase.verifyTrue(contains(string(dialog.Widgets. ...
                PostLoginScriptHelp.Tooltip), "module load"));
            testCase.verifyTrue(contains(string(dialog.Widgets. ...
                PostLoginCommandTemplateHelp.Tooltip), "{command}"));
            testCase.verifyTrue(contains(string(dialog.Widgets. ...
                PostLoginPromptRulesHelp.Tooltip), "(?i)password"));
            deploymentHelp = string(dialog.Widgets. ...
                CodeDeploymentModeHelp.Tooltip);
            testCase.verifyTrue(contains(deploymentHelp, ...
                "AttachCurrentToolbox"));
            testCase.verifyTrue(contains(deploymentHelp, ...
                "ClusterInstalled"));
        end

        function connectionAndComputeFieldsHaveHelpTooltips(testCase)
            root = temporaryRoot(testCase);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);

            connectionHelp = "PostLoginPromptRulesHelp";
            computeHelp = ["PostLoginCommandTemplateHelp", ...
                "ProfileSourceHelp", "CloudProviderHelp", ...
                "CloudResourceNameHelp", "CloudRegionHelp", ...
                "ExistingProfileNameHelp", ...
                "RemoteBridgeProfileNameHelp", ...
                "ClusterMatlabRootHelp", ...
                "RemoteJobStorageLocationHelp", ...
                "NumWorkersHelp", "PoolSizeHelp", ...
                "PartitionHelp", ...
                "AccountHelp", "QoSHelp", "WalltimeHelp", ...
                "AdditionalSubmitArgsHelp", ...
                "CodeDeploymentModeHelp", "RemoteKssolvRootHelp", ...
                "HasSharedFilesystemHelp", ...
                "RequiresOnlineLicensingHelp", "LicenseNumberHelp"];

            verifyHelpButtons(testCase, dialog, connectionHelp, ...
                dialog.Widgets.ConnectionTab);
            verifyHelpButtons(testCase, dialog, computeHelp, ...
                dialog.Widgets.ComputeTab);
            testCase.verifyTrue(contains(string(dialog.Widgets. ...
                RemoteJobStorageLocationHelp.Tooltip), "/scratch/"));
            testCase.verifyTrue(contains(string(dialog.Widgets. ...
                WalltimeHelp.Tooltip), "01:00:00"));
        end

        function optionalInputsAreMarkedInTheirLabels(testCase)
            root = temporaryRoot(testCase);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);

            optionalLabels = ["PostLoginScriptLabel", ...
                "CloudResourceNameLabel", "CloudRegionLabel", ...
                "ClusterMatlabRootLabel", ...
                "RemoteJobStorageLocationLabel", ...
                "NumWorkersLabel", "PoolSizeLabel", ...
                "PostLoginPromptRulesLabel", "PartitionLabel", ...
                "AccountLabel", "QoSLabel", "WalltimeLabel", ...
                "AdditionalSubmitArgsLabel", "LicenseNumberLabel"];
            for name = optionalLabels
                labelText = string(dialog.Widgets.(name).Text);
                testCase.verifyTrue(any(contains(labelText, ...
                    ["（可选）", "(optional)"])), ...
                    "Missing optional marker for " + name + ".");
                testCase.verifyFalse(any(contains(lower(labelText), ...
                    ["自动探测", "auto-detect"])), ...
                    "The label should only say optional for " + name + ".");
            end
        end

        function passwordCredentialsAreEnteredInline(testCase)
            root = temporaryRoot(testCase);
            cipher = kssolv.services.remote.security.LocalCredentialCipher( ...
                fullfile(root, "keys"));
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), ...
                CredentialCipher=cipher, Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);
            setMode(dialog, "Mirror");
            dialog.Widgets.AuthenticationMode.Value = "Password";
            dialog.Widgets.AuthenticationMode.ValueChangedFcn([], []);

            verifyVisibility(testCase, dialog, ...
                "PasswordInput", "on");
            verifyVisibility(testCase, dialog, ...
                ["RememberTotpSecret", "TotpSecretInput"], "off");
            setPasswordField(dialog.Widgets.PasswordInput, ...
                "test-password");
            dialog.Widgets.Host.Value = "mirror.example.test";
            dialog.Widgets.Username.Value = join(["test", "user"], "-");
            dialog.Widgets.ClusterMatlabRoot.Value = ...
                "/opt/MATLAB/R2024a";
            dialog.Widgets.RemoteJobStorageLocation.Value = "/scratch/test";
            dialog.Widgets.PostLoginScript.Value = { ...
                'source /etc/profile'; 'module load matlab'};

            saved = dialog.saveCurrent();

            testCase.verifyEqual(saved.AuthenticationMode, "Password");
            testCase.verifyFalse(saved.RememberTotpSecret);
            testCase.verifyEqual(saved.EncryptedTotpSecret, "");
            testCase.verifyEqual(saved.PostLoginScript, ...
                "source /etc/profile" + newline + "module load matlab");
            testCase.verifyEqual(cipher.decrypt( ...
                saved.EncryptedPassword), "test-password");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PasswordInput.Data.Value), "");
            persisted = string(fileread( ...
                dialog.ConfigurationStore.path()));
            testCase.verifyFalse(contains(persisted, "test-password"));
        end

        function standardPasswordCredentialIsEnteredInline(testCase)
            root = temporaryRoot(testCase);
            cipher = kssolv.services.remote.security.LocalCredentialCipher( ...
                fullfile(root, "keys"));
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), ...
                CredentialCipher=cipher, Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);
            setMode(dialog, "Standard");
            dialog.Widgets.ConnectionMode.Value = "SSH";
            dialog.Widgets.ConnectionMode.ValueChangedFcn([], []);
            dialog.Widgets.AuthenticationMode.Value = "Password";
            dialog.Widgets.AuthenticationMode.ValueChangedFcn([], []);

            verifyVisibility(testCase, dialog, "PasswordInput", "on");
            verifyVisibility(testCase, dialog, ...
                ["RememberTotpSecret", "TotpSecretInput"], "off");
            setPasswordField(dialog.Widgets.PasswordInput, ...
                "standard-test-password");
            dialog.Widgets.Host.Value = "standard.example.test";
            dialog.Widgets.Username.Value = "user";
            dialog.Widgets.ClusterMatlabRoot.Value = ...
                "/opt/MATLAB/R2026b";
            dialog.Widgets.RemoteJobStorageLocation.Value = ...
                "/scratch/user/kssolv";

            saved = dialog.saveCurrent();

            testCase.verifyEqual(saved.ExecutionMode, "Standard");
            testCase.verifyEqual(saved.AuthenticationMode, "Password");
            testCase.verifyEqual(cipher.decrypt( ...
                saved.EncryptedPassword), "standard-test-password");
            persisted = string(fileread( ...
                dialog.ConfigurationStore.path()));
            testCase.verifyFalse(contains(persisted, ...
                "standard-test-password"));
        end

        function storedMfaCredentialsEnableAutomaticMirrorLogin(testCase)
            root = temporaryRoot(testCase);
            cipher = kssolv.services.remote.security.LocalCredentialCipher( ...
                fullfile(root, "keys"));
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), ...
                CredentialCipher=cipher, ...
                Visible=false);
            cleanup = onCleanup(@()deleteIfValid(dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);
            setMode(dialog, "Mirror");
            dialog.Widgets.AuthenticationMode.Value = "Multifactor";
            dialog.Widgets.AuthenticationMode.ValueChangedFcn([], []);

            verifyVisibility(testCase, dialog, ...
                ["PasswordInput", "RememberTotpSecret"], "on");
            testCase.verifyClass(dialog.Widgets.PasswordInput, ...
                "matlab.ui.control.HTML");
            testCase.verifyTrue(endsWith(string( ...
                dialog.Widgets.PasswordInput.HTMLSource), ...
                "passwordField.html"));
            testCase.verifyEqual(string( ...
                dialog.Widgets.TotpSecretInput.Visible), "off");
            testCase.verifyEqual(string( ...
                dialog.Widgets.NumWorkers.Visible), "on");
            dialog.Widgets.RememberTotpSecret.Value = true;
            dialog.Widgets.RememberTotpSecret.ValueChangedFcn([], []);
            testCase.verifyEqual(string( ...
                dialog.Widgets.TotpSecretInput.Visible), "on");
            setPasswordField(dialog.Widgets.PasswordInput, ...
                "test-password");
            setPasswordField(dialog.Widgets.TotpSecretInput, ...
                "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ");
            testCase.verifyEqual(dialog.Widgets.Status.FontColor, ...
                [0.15, 0.45, 0.2]);

            dialog.Widgets.Host.Value = "mirror.example.test";
            dialog.Widgets.Username.Value = join(["test", "user"], "-");
            dialog.Widgets.ClusterMatlabRoot.Value = "/opt/MATLAB/R2024a";
            dialog.Widgets.RemoteJobStorageLocation.Value = "/scratch/test";

            saved = dialog.saveCurrent();
            testCase.verifyTrue(saved.RememberTotpSecret);
            testCase.verifyGreaterThan(strlength( ...
                saved.EncryptedPassword), 0);
            testCase.verifyGreaterThan(strlength( ...
                saved.EncryptedTotpSecret), 0);
            testCase.verifyEqual(cipher.decrypt( ...
                saved.EncryptedPassword), "test-password");
            testCase.verifyEqual(cipher.decrypt( ...
                saved.EncryptedTotpSecret), ...
                "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ");
            testCase.verifyEqual(string( ...
                dialog.Widgets.PasswordInput.Data.Value), "");
            testCase.verifyEqual(string( ...
                dialog.Widgets.TotpSecretInput.Data.Value), "");
            persisted = string(fileread( ...
                dialog.ConfigurationStore.path()));
            testCase.verifyTrue(contains(persisted, ...
                '"EncryptedPassword"'));
            testCase.verifyFalse(contains(persisted, ...
                "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"));
            testCase.verifyFalse(contains(persisted, "test-password"));

            savedWithBlankInputs = dialog.saveCurrent();
            testCase.verifyEqual(savedWithBlankInputs.EncryptedPassword, ...
                saved.EncryptedPassword);
            testCase.verifyEqual( ...
                savedWithBlankInputs.EncryptedTotpSecret, ...
                saved.EncryptedTotpSecret);
        end

        function homeRemoteMenuHasSelectionAndManagement(testCase)
            commandWindow = kssolv.ui.test.FakeRemoteCommandWindow();
            kssolv.ui.util.DataStorage.setData( ...
                "CommandWindow", commandWindow);
            testCase.addTeardown(@clearCommandWindowStorage);
            home = kssolv.ui.components.tab.HomeTab();
            popup = home.Widgets.EnvironmentSection. ...
                EnvironmentRemoteButton.Popup;

            testCase.verifyEqual(numel(popup.Children), 7);
            selection = popup.getChildByIndex(1);
            testCase.verifyClass(popup.getChildByIndex(2), ...
                "matlab.ui.internal.toolstrip.PopupListSeparator");
            testCase.verifyEqual(string( ...
                popup.getChildByIndex(3).Tag), ...
                "EnvironmentSection_ConfigureRemoteClusters");
            testCase.verifyEqual(string( ...
                popup.getChildByIndex(4).Tag), ...
                "EnvironmentSection_TestRemoteCluster");
            testCase.verifyEqual(string( ...
                popup.getChildByIndex(5).Tag), ...
                "EnvironmentSection_RemoteJobs");
            testCase.verifyClass(popup.getChildByIndex(6), ...
                "matlab.ui.internal.toolstrip.PopupListSeparator");
            remoteCommand = popup.getChildByIndex(7);
            testCase.verifyEqual(string(remoteCommand.Tag), ...
                "EnvironmentSection_RemoteCommandExecution");
            testCase.verifyFalse(remoteCommand.Value);
            remoteCommand.qeValueChanged();
            testCase.verifyTrue(remoteCommand.Value);
            testCase.verifyTrue(commandWindow.RemoteExecutionEnabled);
            remoteCommand.qeValueChanged();
            testCase.verifyFalse(remoteCommand.Value);
            testCase.verifyFalse(commandWindow.RemoteExecutionEnabled);
            itemCount = numel(selection.Popup.Children);
            testCase.verifyGreaterThanOrEqual(itemCount, 1);
            selectedCount = 0;
            for index = 1:itemCount
                selectedCount = selectedCount + double( ...
                    selection.Popup.getChildByIndex(index).Value);
            end
            testCase.verifyEqual(selectedCount, 1);
            testCase.verifyTrue(home.Widgets.EnvironmentSection. ...
                EnvironmentRemoteButton.Enabled);
        end

        function commandWindowReportsRemoteStatusToFooter(testCase)
            footer = kssolv.ui.components.others.FooterBar();
            testCase.addTeardown(@()delete(footer));
            commandWindow = ...
                kssolv.ui.components.databrowser.CommandWindow();
            testCase.addTeardown(@()delete(commandWindow));

            commandWindow.reportRemoteStatus("Connecting", "Test target");
            expected = sprintf(char(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:RemoteCommandConnecting")), ...
                "Test target");
            testCase.verifyEqual(string(footer.statusLabel.Text), ...
                string(expected));
            commandWindow.reportRemoteStatus("Finished", "");
            testCase.verifyEqual(string(footer.statusLabel.Text), ...
                string(kssolv.ui.util.Localizer.message( ...
                "KSSOLV:dialogs:RemoteCommandFinished")));
        end

        function commandWindowInputLayoutStaysAtBottom(testCase)
            path = fullfile(fileparts(which( ...
                "kssolv.ui.components.databrowser.CommandWindow")), ...
                "html", "index.html");
            source = string(fileread(path));

            testCase.verifyTrue(contains(source, ...
                "grid-template-rows: minmax(0, 1fr) auto"));
            testCase.verifyTrue(contains(source, ...
                "#input-container"));
            testCase.verifyTrue(contains(source, ...
                "position: relative"));
            testCase.verifyFalse(contains(source, ...
                "position: absolute;" + newline + ...
                "            bottom: 0;"));
        end

        function connectionTestPollsAndRestoresDialog(testCase)
            testCase.assumeTrue(any(string(parallel.listProfiles()) == ...
                "Processes"));
            root = temporaryRoot(testCase);
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore(root);
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                create(struct( ...
                "DisplayName", "UI smoke", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "Processes", ...
                "NumWorkers", 2, "PoolSize", 0));
            configurationStore.upsert(configuration);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=configurationStore, ...
                SelectionStore= ...
                    kssolv.services.remote.config.RemoteSelectionStore(root), ...
                Visible=false);
            cleanup = onCleanup(@()deleteDialog(dialog)); %#ok<NASGU>

            started = tic;
            dialog.Widgets.Test.ButtonPushedFcn([], []);
            submissionSeconds = toc(started);
            testCase.verifyLessThan(submissionSeconds, 8);
            testCase.verifyTrue(isvalid(dialog.Figure));
            testCase.verifyNotEmpty(dialog.ConnectionTestSession);

            deadline = tic;
            while ~any(dialog.ConnectionTestSession.State == ...
                    dialog.ConnectionTestSession.TerminalStates) && ...
                    toc(deadline) < 30
                drawnow;
                pause(0.05);
            end
            drawnow;

            testCase.verifyEqual(dialog.ConnectionTestSession.State, ...
                "Succeeded");
            testCase.verifyEqual(string(dialog.Widgets.Test.Enable), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.CancelTest.Enable), "off");
            testCase.verifyTrue(strlength(string( ...
                dialog.Widgets.ConnectionStatus.Text)) > 0);
            status = string(dialog.Widgets.ConnectionStatus.Text);
            testCase.verifyTrue(any(startsWith(status, ...
                ["连接测试通过。", "连接测试成功。", ...
                "Connection test passed.", ...
                "连接成功。资源探测完成。", ...
                "Connection succeeded. Resource discovery completed."])), ...
                "Actual status: " + status);
            testCase.verifyEqual( ...
                dialog.Widgets.TabGroup.SelectedTab, ...
                dialog.Widgets.ConnectionTab);
        end

        function resourceProbePollsPopulatesAndSelectsComputeTab(testCase)
            testCase.assumeTrue(any(string(parallel.listProfiles()) == ...
                "Processes"));
            root = temporaryRoot(testCase);
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore(root);
            configurationStore.upsert( ...
                kssolv.services.remote.config.RemoteConfiguration. ...
                create(struct( ...
                "DisplayName", "Resource probe UI smoke", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "Processes", ...
                "NumWorkers", 2, "PoolSize", 0)));
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=configurationStore, ...
                SelectionStore= ...
                    kssolv.services.remote.config.RemoteSelectionStore(root), ...
                Visible=false);
            cleanup = onCleanup(@()deleteDialog(dialog)); %#ok<NASGU>

            dialog.Widgets.ResourceProbe.ButtonPushedFcn([], []);
            testCase.verifyNotEmpty(dialog.ResourceProbeSession);
            deadline = tic;
            while ~any(dialog.ResourceProbeSession.State == ...
                    dialog.ResourceProbeSession.TerminalStates) && ...
                    toc(deadline) < 30
                drawnow;
                pause(0.05);
            end
            drawnow;

            testCase.verifyEqual(dialog.ResourceProbeSession.State, ...
                "Succeeded");
            testCase.verifyEqual(string( ...
                dialog.Widgets.ResourceProbe.Enable), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.CancelResourceProbe.Enable), "off");
            testCase.verifyGreaterThan(strlength(string( ...
                dialog.Widgets.ClusterMatlabRoot.Value)), 0);
            testCase.verifyTrue(strlength(string( ...
                dialog.Widgets.ResourceProbeStatus.Text)) > 0);
            testCase.verifyEqual( ...
                dialog.Widgets.TabGroup.SelectedTab, ...
                dialog.Widgets.ComputeTab);
        end

        function runningConnectionTestCanBeCancelled(testCase)
            testCase.assumeTrue(any(string(parallel.listProfiles()) == ...
                "Processes"));
            root = temporaryRoot(testCase);
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore(root);
            configurationStore.upsert( ...
                kssolv.services.remote.config.RemoteConfiguration. ...
                create(struct( ...
                "DisplayName", "Cancelable UI smoke", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "Processes", ...
                "NumWorkers", 2, "PoolSize", 0)));
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=configurationStore, ...
                SelectionStore= ...
                    kssolv.services.remote.config.RemoteSelectionStore(root), ...
                Visible=false);
            cleanup = onCleanup(@()deleteDialog(dialog)); %#ok<NASGU>

            dialog.Widgets.Test.ButtonPushedFcn([], []);
            testCase.verifyEqual(string( ...
                dialog.Widgets.CancelTest.Enable), "on");
            started = tic;
            dialog.Widgets.CancelTest.ButtonPushedFcn([], []);
            cancelSeconds = toc(started);

            testCase.verifyLessThan(cancelSeconds, 8);
            testCase.verifyEqual(dialog.ConnectionTestSession.State, ...
                "Cancelled");
            testCase.verifyEqual(string(dialog.Widgets.Test.Enable), "on");
            testCase.verifyEqual(string( ...
                dialog.Widgets.CancelTest.Enable), "off");
            status = string(dialog.Widgets.ConnectionStatus.Text);
            testCase.verifyTrue(any(startsWith(status, ...
                ["连接测试已取消。", ...
                "The connection test was cancelled."])));
        end

        function connectionValidationStatusStartsWithConclusion(testCase)
            root = temporaryRoot(testCase);
            dialog = kssolv.ui.features.remote. ...
                RemoteClusterManagerDialog( ...
                ConfigurationStore=kssolv.services.remote.config. ...
                    RemoteConfigurationStore(root), ...
                SelectionStore=kssolv.services.remote.config. ...
                    RemoteSelectionStore(root), Visible=false);
            cleanup = onCleanup(@()deleteDialog(dialog)); %#ok<NASGU>
            dialog.Widgets.Add.ButtonPushedFcn([], []);

            dialog.Widgets.Test.ButtonPushedFcn([], []);

            status = string(dialog.Widgets.ConnectionStatus.Text);
            testCase.verifyTrue(any(startsWith(status, ...
                ["尚未建立连接。", "Connection was not established."])));
            testCase.verifyEqual(dialog.Widgets.ConnectionStatus.Layout.Row, ...
                15);
            testCase.verifyEqual( ...
                dialog.Widgets.ConnectionStatus.Layout.Column, 2);
            testCase.verifyEqual( ...
                dialog.Widgets.ConnectionStatus.Parent, ...
                dialog.Widgets.Test.Parent.Parent);
            testCase.verifyGreaterThan(strlength(string( ...
                dialog.Widgets.ConfigurationStatus.Text)), 0);
        end

        function remoteEnvelopeImportsIntoProjectResults(testCase)
            project = kssolv.services.filemanager.Project();
            browser = kssolv.ui.test.RemoteProjectBrowserStub();
            kssolv.ui.util.DataStorage.setData("Project", project);
            kssolv.ui.util.DataStorage.setData("ProjectBrowser", browser);
            cleanup = onCleanup(@()clearProjectStorage()); %#ok<NASGU>
            workflow = kssolv.services.workflow.WorkflowGraph({});
            context = containers.Map("KeyType", "char", "ValueType", "any");
            context("energy") = -5.9666002670969;
            envelope = struct( ...
                "Context", context, ...
                "RemoteNodeIds", strings(0, 1), ...
                "LocalNodeIds", strings(0, 1), ...
                "WorkflowName", "Remote LiH");

            kssolv.services.workflow.codegeneration.CodeGenerator. ...
                completeRemoteExecution(workflow, envelope, ...
                ResultIdentity="remote-lih-import-test");
            kssolv.services.workflow.codegeneration.CodeGenerator. ...
                completeRemoteExecution(workflow, envelope, ...
                ResultIdentity="remote-lih-import-test");

            results = project.findChildrenItem("Results");
            datasets = results.findChildrenItem("Datasets");
            testCase.verifyEqual(numel(datasets.children), 1);
            testCase.verifyEqual(datasets.children{1}.data("energy"), ...
                -5.9666002670969);
            testCase.verifyEqual(browser.RefreshCount, 1);
            testCase.verifyEqual(browser.LastItem, datasets);
        end

        function jobsDialogFetchImportsMarksAndCleans(testCase)
            root = temporaryRoot(testCase);
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore(root);
            jobStore = kssolv.services.remote.job.RemoteJobStore(root);
            configuration = bridgeConfiguration();
            configurationStore.upsert(configuration);
            access = kssolv.services.remote.test.FakeRemoteAccess();
            bridge = kssolv.services.remote.bridge.RemoteMatlabBridge( ...
                kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access));
            manager = kssolv.services.remote.job.RemoteJobManager( ...
                configurationStore, jobStore, ...
                kssolv.services.remote.cluster.ClusterFactory( ...
                fullfile(root, "matlab-jobs")), bridge);

            project = kssolv.services.filemanager.Project();
            workflow = kssolv.services.filemanager.Workflow("Remote LiH");
            workflow.graph = kssolv.services.workflow.WorkflowGraph({});
            project.findChildrenItem("Workflow").addChildrenItem(workflow);
            browser = kssolv.ui.test.RemoteProjectBrowserStub();
            kssolv.ui.util.DataStorage.setData("Project", project);
            kssolv.ui.util.DataStorage.setData("ProjectBrowser", browser);
            storageCleanup = onCleanup(@()clearProjectStorage()); %#ok<NASGU>

            context = containers.Map("KeyType", "char", "ValueType", "any");
            context("energy") = -5.9666002670969;
            access.Outputs = {struct( ...
                "Context", context, ...
                "RemoteNodeIds", strings(0, 1), ...
                "LocalNodeIds", strings(0, 1), ...
                "WorkflowName", "Remote LiH")};
            record = kssolv.services.remote.job.RemoteJobRecord.create( ...
                configuration.Id, "Remote LiH", string(workflow.name));
            record.ExecutionMode = "Bridge";
            record.ConfigurationSnapshot = configuration;
            record.RemoteWorkspace = "/scratch/test/kssolv-bridge/" + ...
                record.LocalJobId;
            record.State = "Finished";
            record.BundlePath = fullfile(root, "bundle.zip");
            writelines("test bundle", record.BundlePath);
            jobStore.upsert(record);

            dialog = kssolv.ui.features.remote.RemoteJobsDialog( ...
                JobManager=manager, Visible=false);
            dialogCleanup = onCleanup(@()deleteIfValid( ...
                dialog.Figure)); %#ok<NASGU>
            dialog.Widgets.Table.Selection = [1, 1];
            dialog.Widgets.Fetch.ButtonPushedFcn([], []);

            imported = jobStore.get(record.LocalJobId);
            datasets = project.findChildrenItem("Datasets");
            testCase.verifyTrue(imported.ResultImported);
            testCase.verifyEqual(imported.State, "Retrieved");
            testCase.verifyEqual(imported.BundlePath, "");
            testCase.verifyFalse(isfile(fullfile(root, "bundle.zip")));
            testCase.verifyEqual(numel(datasets.children), 1);
            testCase.verifyEqual(datasets.children{1}.data("energy"), ...
                -5.9666002670969);
            testCase.verifyEqual(browser.RefreshCount, 1);
        end
    end
end

function root = temporaryRoot(testCase)
root = string(tempname);
mkdir(root);
testCase.addTeardown(@()removeFolder(root));
end

function removeFolder(path)
if isfolder(path)
    rmdir(path, "s");
end
end

function deleteIfValid(value)
if isvalid(value)
    delete(value);
end
end

function deleteDialog(dialog)
if isvalid(dialog)
    delete(dialog);
end
end

function clearProjectStorage()
kssolv.ui.util.DataStorage.removeData("Project");
kssolv.ui.util.DataStorage.removeData("ProjectBrowser");
end

function clearCommandWindowStorage()
kssolv.ui.util.DataStorage.removeData("CommandWindow");
end

function value = bridgeConfiguration()
value = kssolv.services.remote.config.RemoteConfiguration.create(struct( ...
    "DisplayName", "UI Bridge", ...
    "ExecutionMode", "Bridge", ...
    "Host", "bridge.example.test", ...
    "Username", join(["test", "user"], "-"), ...
    "AuthenticationMode", "Agent", ...
    "ClusterMatlabRoot", "/opt/MATLAB/R2024a", ...
    "RemoteJobStorageLocation", "/scratch/test", ...
    "RemoteBridgeProfileName", "remote-slurm", ...
    "CodeDeploymentMode", "ClusterInstalled", ...
    "RemoteKssolvRoot", "/shared/KSSOLV"));
end

function setMode(dialog, mode)
dialog.Widgets.ExecutionMode.Value = mode;
dialog.Widgets.ExecutionMode.ValueChangedFcn([], []);
end

function setPasswordField(field, value)
data = field.Data;
data.Value = string(value);
field.Data = data;
end

function verifyVisibility(testCase, dialog, names, expected)
for name = names
    testCase.verifyEqual(string(dialog.Widgets.(name).Visible), expected, ...
        "Unexpected visibility for " + name + ".");
end
end

function verifyHelpButtons(testCase, dialog, names, expectedTab)
for name = names
    testCase.verifyTrue(isfield(dialog.Widgets, name));
    button = dialog.Widgets.(name);
    testCase.verifyClass(button, "matlab.ui.control.Button");
    testCase.verifyEqual(string(button.Text), "");
    testCase.verifyGreaterThan(strlength(string(button.Tooltip)), 0);
    testCase.verifyEqual(button.Parent.Parent.Parent, expectedTab);
end
end
