classdef RemoteClusterManagerDialog < handle
    %REMOTECLUSTERMANAGERDIALOG Manage saved Slurm cluster definitions.

    properties (SetAccess = private)
        Figure
        Widgets struct = struct()
        ConfigurationStore
        SelectionStore
        CredentialCipher
        ConnectionTestSession = []
        ResourceProbeSession = []
    end

    properties (Access = private)
        Configurations struct
        SelectedIndex (1, 1) double = 0
        ConnectionTestTimer = []
        ResourceProbeTimer = []
        EditorGrids cell = {}
        EditorRowHeights cell = {}
        FieldRows struct = struct()
        FieldTabs struct = struct()
    end

    methods
        function this = RemoteClusterManagerDialog(options)
            arguments
                options.ConfigurationStore = ...
                    kssolv.services.remote.config.RemoteConfigurationStore()
                options.SelectionStore = ...
                    kssolv.services.remote.config.RemoteSelectionStore()
                options.CredentialCipher = ...
                    kssolv.services.remote.security.LocalCredentialCipher()
                options.Visible (1, 1) logical = true
            end
            this.ConfigurationStore = options.ConfigurationStore;
            this.SelectionStore = options.SelectionStore;
            this.CredentialCipher = options.CredentialCipher;
            this.buildUI();
            this.reload();
            if options.Visible
                kssolv.ui.util.DialogWindow.showCentered(this.Figure);
            else
                movegui(this.Figure, "center");
            end
        end

        function delete(this)
            this.stopConnectionTest(true);
            this.stopResourceProbe(true);
            this.clearCredentialInputs();
            if ~isempty(this.Figure) && isvalid(this.Figure)
                delete(this.Figure);
            end
        end

        function reload(this)
            this.Configurations = this.ConfigurationStore.list();
            this.refreshTable();
            if isempty(this.Configurations)
                this.SelectedIndex = 0;
                this.setEditorEnabled(false);
                return
            end
            this.selectIndex(min(max(this.SelectedIndex, 1), ...
                numel(this.Configurations)));
        end

        function configuration = saveCurrent(this)
            if this.SelectedIndex < 1 || ...
                    this.SelectedIndex > numel(this.Configurations)
                error("KSSOLV:Remote:UI:NoConfigurationSelected", ...
                    remoteMessage("RemoteNoConfigurationSelected"));
            end
            configuration = this.readEditor( ...
                this.Configurations(this.SelectedIndex));
            configuration = this.applyCredentialInputs(configuration);
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                create(configuration);
            this.validateCredentialSetup(configuration);
            this.ConfigurationStore.upsert(configuration);
            this.Configurations(this.SelectedIndex) = configuration;
            this.clearCredentialInputs();
            this.refreshTable();
            this.selectIndex(this.SelectedIndex);
            this.setConfigurationStatus( ...
                remoteMessage("RemoteConfigurationSaved"), false);
        end
    end

    methods (Access = private)
        function buildUI(this)
            this.Figure = uifigure( ...
                "Name", remoteMessage("RemoteClusterManagerTitle"), ...
                "Position", [100, 100, 1080, 690], ...
                "Visible", "off");
            this.Figure.CloseRequestFcn = @(~, ~) delete(this);
            root = uigridlayout(this.Figure, [2, 2], ...
                "RowHeight", {"1x", 28}, ...
                "ColumnWidth", {300, "1x"}, ...
                "Padding", 12, "ColumnSpacing", 12);

            configTable = uitable(root, "Data", table(), "RowName", [], ...
                "ColumnEditable", false, ...
                "ColumnWidth", {48, 162, 85}, ...
                "CellSelectionCallback", @(~, event) ...
                this.tableSelectionChanged(event));
            configTable.Layout.Row = 1;
            configTable.Layout.Column = 1;

            editorPanel = uipanel(root, ...
                "Title", remoteMessage("RemoteConfigurationEditor"));
            editorPanel.Layout.Row = 1;
            editorPanel.Layout.Column = 2;
            editorContainer = uigridlayout(editorPanel, [1, 1], ...
                "Padding", 0);
            tabGroup = uitabgroup(editorContainer);
            tabGroup.Layout.Row = 1;
            tabGroup.Layout.Column = 1;
            connectionTab = uitab(tabGroup, ...
                "Title", remoteMessage("RemoteConnectionTab"));
            computeTab = uitab(tabGroup, ...
                "Title", remoteMessage("RemoteComputeTab"));

            connectionHeights = repmat({28}, 1, 15);
            connectionHeights{12} = 145;
            connectionHeights{13} = 82;
            connectionHeights{15} = 70;
            connectionGrid = uigridlayout(connectionTab, [15, 2], ...
                "RowHeight", connectionHeights, ...
                "ColumnWidth", {245, "1x"}, ...
                "Scrollable", "on", "Padding", 10);
            computeHeights = repmat({28}, 1, 23);
            computeHeights{1} = 82;
            computeHeights{23} = 70;
            computeGrid = uigridlayout(computeTab, [23, 2], ...
                "RowHeight", computeHeights, ...
                "ColumnWidth", {245, "1x"}, ...
                "Scrollable", "on", "Padding", 10);

            displayName = addText(connectionGrid, 1, "RemoteDisplayName");
            enabled = addCheck(connectionGrid, 2, "RemoteEnabled");
            executionMode = addLocalizedDropDown(connectionGrid, 3, ...
                "RemoteExecutionMode", ...
                ["Standard", "Bridge", "Mirror", "Cloud"], ...
                ["RemoteModeStandard", "RemoteModeBridge", ...
                "RemoteModeMirror", "RemoteModeCloud"]);
            connectionMode = addDropDown(connectionGrid, 4, ...
                "RemoteConnectionMode", ["SSH", "Direct"]);
            host = addText(connectionGrid, 5, "RemoteHost");
            username = addText(connectionGrid, 6, "RemoteUsername");
            authenticationMode = addDropDown(connectionGrid, 7, ...
                "RemoteAuthenticationMode", ["Agent", "IdentityFile", ...
                "Password", "Multifactor"]);
            identityFile = addText(connectionGrid, 8, "RemoteIdentityFile");
            passwordInput = addPassword(connectionGrid, 9, ...
                "RemoteSshPassword", "RemoteStoredPasswordPlaceholder");
            rememberTotp = addCheck(connectionGrid, 10, ...
                "RemoteRememberTotpSecret");
            totpSecretInput = addPassword(connectionGrid, 11, ...
                "RemoteTotpSecret", "RemoteStoredTotpPlaceholder");
            [promptRules, addPrompt, removePrompt, promptRulesHelp, ...
                promptRulesLabel] = addPromptRules( ...
                connectionGrid, 12, "RemoteOptionalSuffix");
            [postLoginScript, postLoginScriptHelp, ...
                postLoginScriptLabel] = addTextArea( ...
                connectionGrid, 13, "RemotePostLoginScript", ...
                "RemotePostLoginScriptHelp", "RemoteOptionalSuffix");
            postLoginScript.Value = {''};
            [testButton, cancelTestButton] = addConnectionTestActions( ...
                connectionGrid, 14, @(~, ~) this.testConnection(), ...
                @(~, ~) this.cancelConnectionTest());
            connectionStatus = uilabel(connectionGrid, "Text", "", ...
                "WordWrap", "on", "VerticalAlignment", "top");
            connectionStatus.Layout.Row = 15;
            connectionStatus.Layout.Column = 2;

            [commandTemplate, commandTemplateHelp] = addTextArea( ...
                computeGrid, 1, "RemotePostLoginCommandTemplate", ...
                "RemotePostLoginCommandTemplateHelp");
            [profileSource, profileSourceHelp] = addDropDown( ...
                computeGrid, 2, ...
                "RemoteProfileSource", ["ManagedSlurm", ...
                "ExistingMatlabProfile"], "RemoteProfileSourceHelp");
            [cloudProvider, cloudProviderHelp] = addLocalizedDropDown( ...
                computeGrid, 3, ...
                "RemoteCloudProvider", ...
                ["MathWorksCloudCenter", "AWS", "PrivateCloud"], ...
                ["RemoteCloudCenterProvider", "RemoteAwsProvider", ...
                "RemotePrivateCloudProvider"], "RemoteCloudProviderHelp");
            [cloudResource, cloudResourceHelp, cloudResourceLabel] = ...
                addText( ...
                computeGrid, 4, "RemoteCloudResourceName", ...
                "RemoteCloudResourceNameHelp", "RemoteOptionalSuffix");
            [cloudRegion, cloudRegionHelp, cloudRegionLabel] = addText( ...
                computeGrid, 5, "RemoteCloudRegion", ...
                "RemoteCloudRegionHelp", "RemoteOptionalSuffix");
            [existingProfile, discoverProfiles, existingProfileHelp] = ...
                addTextWithButton( ...
                computeGrid, 6, "RemoteExistingProfile", ...
                "RemoteDiscoverProfiles", ...
                @(~, ~) this.discoverProfiles(), ...
                "RemoteExistingProfileHelp");
            [bridgeProfile, bridgeProfileHelp] = addText( ...
                computeGrid, 7, "RemoteBridgeProfile", ...
                "RemoteBridgeProfileHelp");
            [matlabRoot, matlabRootHelp, matlabRootLabel] = addText( ...
                computeGrid, 8, "RemoteMatlabRoot", ...
                "RemoteMatlabRootHelp", "RemoteOptionalSuffix");
            [remoteStorage, remoteStorageHelp, remoteStorageLabel] = ...
                addText( ...
                computeGrid, 9, "RemoteJobStorage", ...
                "RemoteJobStorageHelp", "RemoteOptionalSuffix");
            [workers, workersHelp, workersLabel] = addNumber( ...
                computeGrid, 10, "RemoteNumWorkers", 1, Inf, ...
                "RemoteNumWorkersHelp", "RemoteOptionalSuffix");
            [pool, poolHelp, poolLabel] = addNumber( ...
                computeGrid, 11, "RemotePoolSize", 0, Inf, ...
                "RemotePoolSizeHelp", "RemoteOptionalSuffix");

            [partition, partitionHelp, partitionLabel] = addText( ...
                computeGrid, 12, "RemotePartition", ...
                "RemotePartitionHelp", "RemoteOptionalSuffix");
            [account, accountHelp, accountLabel] = addText( ...
                computeGrid, 13, "RemoteAccount", ...
                "RemoteAccountHelp", "RemoteOptionalSuffix");
            [qos, qosHelp, qosLabel] = addText( ...
                computeGrid, 14, "RemoteQos", ...
                "RemoteQosHelp", "RemoteOptionalSuffix");
            [walltime, walltimeHelp, walltimeLabel] = addText( ...
                computeGrid, 15, "RemoteWalltime", ...
                "RemoteWalltimeHelp", "RemoteOptionalSuffix");
            [submitArgs, submitArgsHelp, submitArgsLabel] = addText( ...
                computeGrid, 16, "RemoteSubmitArguments", ...
                "RemoteSubmitArgumentsHelp", "RemoteOptionalSuffix");
            [deployment, deploymentHelp] = addDropDown(computeGrid, 17, ...
                "RemoteDeploymentMode", ["AttachCurrentToolbox", ...
                "ClusterInstalled"], "RemoteDeploymentModeHelp");
            [remoteRoot, remoteRootHelp] = addText( ...
                computeGrid, 18, "RemoteKssolvRoot", ...
                "RemoteKssolvRootHelp");
            [shared, sharedHelp] = addCheck(computeGrid, 19, ...
                "RemoteSharedFilesystem", ...
                "RemoteSharedFilesystemHelp");
            [online, onlineHelp] = addCheck(computeGrid, 20, ...
                "RemoteOnlineLicensing", "RemoteOnlineLicensingHelp");
            [licenseNumber, licenseNumberHelp, licenseNumberLabel] = ...
                addText( ...
                computeGrid, 21, "RemoteLicenseNumber", ...
                "RemoteLicenseNumberHelp", "RemoteOptionalSuffix");
            [resourceProbeButton, cancelResourceProbeButton] = ...
                addResourceProbeActions( ...
                computeGrid, 22, @(~, ~) this.probeResources(), ...
                @(~, ~) this.cancelResourceProbe());
            resourceProbeStatus = uilabel(computeGrid, "Text", "", ...
                "WordWrap", "on", "VerticalAlignment", "top");
            resourceProbeStatus.Layout.Row = 23;
            resourceProbeStatus.Layout.Column = 2;

            footer = uigridlayout(root, [1, 3], ...
                "RowHeight", {28}, ...
                "ColumnWidth", {300, "1x", "fit"}, ...
                "Padding", 0, "ColumnSpacing", 12);
            footer.Layout.Row = 2;
            footer.Layout.Column = [1, 2];
            leftButtons = uigridlayout(footer, [1, 3], ...
                "RowHeight", {28}, ...
                "ColumnWidth", {"1x", "1x", "1x"}, "Padding", 0);
            leftButtons.Layout.Row = 1;
            leftButtons.Layout.Column = 1;
            addButton = uibutton(leftButtons, ...
                "Text", remoteMessage("RemoteAdd"), ...
                "ButtonPushedFcn", @(~, ~) this.addConfiguration());
            duplicateButton = uibutton(leftButtons, ...
                "Text", remoteMessage("RemoteDuplicate"), ...
                "ButtonPushedFcn", @(~, ~) this.duplicateConfiguration());
            deleteButton = uibutton(leftButtons, ...
                "Text", remoteMessage("RemoteDelete"), ...
                "ButtonPushedFcn", @(~, ~) this.deleteConfiguration());
            configurationStatus = uilabel(footer, "Text", "", ...
                "WordWrap", "off", "VerticalAlignment", "center");
            configurationStatus.Layout.Row = 1;
            configurationStatus.Layout.Column = 2;
            actionButtons = uigridlayout(footer, [1, 2], ...
                "RowHeight", {28}, ...
                "ColumnWidth", {"fit", "fit"}, ...
                "Padding", 0, "ColumnSpacing", 8);
            actionButtons.Layout.Row = 1;
            actionButtons.Layout.Column = 3;
            saveButton = uibutton(actionButtons, ...
                "Text", remoteMessage("RemoteSave"), ...
                "ButtonPushedFcn", @(~, ~) this.saveClicked());
            saveButton.Layout.Row = 1;
            saveButton.Layout.Column = 1;
            closeButton = uibutton(actionButtons, ...
                "Text", remoteMessage("RemoteClose"), ...
                "ButtonPushedFcn", @(~, ~) delete(this));
            closeButton.Layout.Row = 1;
            closeButton.Layout.Column = 2;

            executionMode.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();
            cloudProvider.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();
            profileSource.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();
            connectionMode.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();
            authenticationMode.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();
            deployment.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();
            online.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();
            rememberTotp.ValueChangedFcn = @(~, ~) ...
                this.updateConditionalControls();

            this.Widgets = struct( ...
                "Table", configTable, "Add", addButton, ...
                "Duplicate", duplicateButton, "Delete", deleteButton, ...
                "TabGroup", tabGroup, ...
                "ConnectionTab", connectionTab, ...
                "ComputeTab", computeTab, ...
                "DisplayName", displayName, "Enabled", enabled, ...
                "ExecutionMode", executionMode, ...
                "CloudProvider", cloudProvider, ...
                "CloudProviderHelp", cloudProviderHelp, ...
                "CloudResourceName", cloudResource, ...
                "CloudResourceNameHelp", cloudResourceHelp, ...
                "CloudResourceNameLabel", cloudResourceLabel, ...
                "CloudRegion", cloudRegion, ...
                "CloudRegionHelp", cloudRegionHelp, ...
                "CloudRegionLabel", cloudRegionLabel, ...
                "ProfileSource", profileSource, ...
                "ProfileSourceHelp", profileSourceHelp, ...
                "ConnectionMode", connectionMode, "Host", host, ...
                "Username", username, ...
                "AuthenticationMode", authenticationMode, ...
                "IdentityFile", identityFile, ...
                "PasswordInput", passwordInput, ...
                "TotpSecretInput", totpSecretInput, ...
                "ExistingProfileName", existingProfile, ...
                "ExistingProfileNameHelp", existingProfileHelp, ...
                "DiscoverProfiles", discoverProfiles, ...
                "RemoteBridgeProfileName", bridgeProfile, ...
                "RemoteBridgeProfileNameHelp", bridgeProfileHelp, ...
                "PostLoginScript", postLoginScript, ...
                "PostLoginScriptHelp", postLoginScriptHelp, ...
                "PostLoginScriptLabel", postLoginScriptLabel, ...
                "ConnectionDiscovery", testButton, ...
                "ClusterMatlabRoot", matlabRoot, ...
                "ClusterMatlabRootHelp", matlabRootHelp, ...
                "ClusterMatlabRootLabel", matlabRootLabel, ...
                "RemoteJobStorageLocation", remoteStorage, ...
                "RemoteJobStorageLocationHelp", remoteStorageHelp, ...
                "RemoteJobStorageLocationLabel", remoteStorageLabel, ...
                "PostLoginCommandTemplate", commandTemplate, ...
                "PostLoginCommandTemplateHelp", commandTemplateHelp, ...
                "PostLoginPromptRules", promptRules, ...
                "PostLoginPromptRulesHelp", promptRulesHelp, ...
                "PostLoginPromptRulesLabel", promptRulesLabel, ...
                "AddPromptRule", addPrompt, ...
                "RemovePromptRule", removePrompt, ...
                "NumWorkers", workers, "NumWorkersHelp", workersHelp, ...
                "NumWorkersLabel", workersLabel, ...
                "PoolSize", pool, "PoolSizeHelp", poolHelp, ...
                "PoolSizeLabel", poolLabel, ...
                "Partition", partition, "PartitionHelp", partitionHelp, ...
                "PartitionLabel", partitionLabel, ...
                "Account", account, "AccountHelp", accountHelp, ...
                "AccountLabel", accountLabel, ...
                "QoS", qos, "QoSHelp", qosHelp, ...
                "QoSLabel", qosLabel, ...
                "Walltime", walltime, "WalltimeHelp", walltimeHelp, ...
                "WalltimeLabel", walltimeLabel, ...
                "AdditionalSubmitArgs", submitArgs, ...
                "AdditionalSubmitArgsHelp", submitArgsHelp, ...
                "AdditionalSubmitArgsLabel", submitArgsLabel, ...
                "CodeDeploymentMode", deployment, ...
                "CodeDeploymentModeHelp", deploymentHelp, ...
                "RemoteKssolvRoot", remoteRoot, ...
                "RemoteKssolvRootHelp", remoteRootHelp, ...
                "HasSharedFilesystem", shared, ...
                "HasSharedFilesystemHelp", sharedHelp, ...
                "RequiresOnlineLicensing", online, ...
                "RequiresOnlineLicensingHelp", onlineHelp, ...
                "LicenseNumber", licenseNumber, ...
                "LicenseNumberHelp", licenseNumberHelp, ...
                "LicenseNumberLabel", licenseNumberLabel, ...
                "RememberTotpSecret", rememberTotp, ...
                "Save", saveButton, "Test", testButton, ...
                "CancelTest", cancelTestButton, ...
                "ConnectionStatus", connectionStatus, ...
                "ResourceProbe", resourceProbeButton, ...
                "CancelResourceProbe", cancelResourceProbeButton, ...
                "ResourceProbeStatus", resourceProbeStatus, ...
                "Close", closeButton, ...
                "ConfigurationStatus", configurationStatus, ...
                "Status", configurationStatus, ...
                "Root", root, "Footer", footer, ...
                "LeftButtons", leftButtons, ...
                "EditorPanel", editorPanel, ...
                "ActionButtons", actionButtons);
            this.EditorGrids = {connectionGrid, computeGrid};
            this.EditorRowHeights = {connectionHeights, computeHeights};
            this.FieldRows = struct( ...
                "DisplayName", 1, "Enabled", 2, "ExecutionMode", 3, ...
                "ConnectionMode", 4, "Host", 5, "Username", 6, ...
                "AuthenticationMode", 7, "IdentityFile", 8, ...
                "PasswordInput", 9, "RememberTotpSecret", 10, ...
                "TotpSecretInput", 11, "PostLoginPromptRules", 12, ...
                "PostLoginScript", 13, ...
                "ConnectionDiscovery", 14, "ConnectionStatus", 15, ...
                "PostLoginCommandTemplate", 1, ...
                "ProfileSource", 2, "CloudProvider", 3, ...
                "CloudResourceName", 4, "CloudRegion", 5, ...
                "ExistingProfileName", 6, ...
                "RemoteBridgeProfileName", 7, ...
                "ClusterMatlabRoot", 8, ...
                "RemoteJobStorageLocation", 9, ...
                "NumWorkers", 10, "PoolSize", 11, ...
                "Partition", 12, "Account", 13, "QoS", 14, ...
                "Walltime", 15, "AdditionalSubmitArgs", 16, ...
                "CodeDeploymentMode", 17, "RemoteKssolvRoot", 18, ...
                "HasSharedFilesystem", 19, ...
                "RequiresOnlineLicensing", 20, "LicenseNumber", 21, ...
                "ResourceDiscovery", 22, "ResourceProbeStatus", 23);
            this.FieldTabs = struct( ...
                "DisplayName", 1, "Enabled", 1, "ExecutionMode", 1, ...
                "ConnectionMode", 1, "Host", 1, "Username", 1, ...
                "AuthenticationMode", 1, "IdentityFile", 1, ...
                "PasswordInput", 1, "RememberTotpSecret", 1, ...
                "TotpSecretInput", 1, "PostLoginScript", 1, ...
                "PostLoginPromptRules", 1, ...
                "ConnectionDiscovery", 1, "ConnectionStatus", 1, ...
                "PostLoginCommandTemplate", 2, ...
                "ProfileSource", 2, "CloudProvider", 2, ...
                "CloudResourceName", 2, "CloudRegion", 2, ...
                "ExistingProfileName", 2, ...
                "RemoteBridgeProfileName", 2, ...
                "ClusterMatlabRoot", 2, ...
                "RemoteJobStorageLocation", 2, ...
                "NumWorkers", 2, "PoolSize", 2, ...
                "Partition", 2, "Account", 2, "QoS", 2, ...
                "Walltime", 2, "AdditionalSubmitArgs", 2, ...
                "CodeDeploymentMode", 2, "RemoteKssolvRoot", 2, ...
                "HasSharedFilesystem", 2, ...
                "RequiresOnlineLicensing", 2, "LicenseNumber", 2, ...
                "ResourceDiscovery", 2, "ResourceProbeStatus", 2);
            this.updateFieldVisibility();
        end

        function refreshTable(this)
            configurations = this.Configurations;
            if isempty(configurations)
                data = table(false(0, 1), strings(0, 1), ...
                    strings(0, 1), ...
                    VariableNames=["Enabled", "Name", "Mode"]);
            else
                data = table(logical([configurations.Enabled]).', ...
                    string({configurations.DisplayName}).', ...
                    string({configurations.ExecutionMode}).', ...
                    VariableNames=["Enabled", "Name", "Mode"]);
            end
            this.Widgets.Table.Data = data;
            this.Widgets.Table.ColumnName = [ ...
                remoteMessage("RemoteEnabled")
                remoteMessage("RemoteDisplayName")
                remoteMessage("RemoteExecutionMode")];
        end

        function tableSelectionChanged(this, event)
            if isempty(event.Indices)
                return
            end
            this.selectIndex(event.Indices(1));
        end

        function selectIndex(this, index)
            if index < 1 || index > numel(this.Configurations)
                return
            end
            this.SelectedIndex = index;
            this.Widgets.Table.Selection = [index, 1];
            this.writeEditor(this.Configurations(index));
            this.setEditorEnabled(true);
            this.updateConditionalControls();
            this.setConnectionStatus("", false);
            this.setResourceProbeStatus("", false);
        end

        function writeEditor(this, value)
            this.clearCredentialInputs();
            this.Widgets.PostLoginScript.Value = ...
                cellstr(splitlines(string(value.PostLoginScript)));
            this.Widgets.PostLoginCommandTemplate.Value = ...
                cellstr(splitlines(string(value.PostLoginCommandTemplate)));
            rules = value.PostLoginPromptRules;
            if isempty(rules)
                this.Widgets.PostLoginPromptRules.Data = table( ...
                    strings(0, 1), strings(0, 1), ...
                    VariableNames=["Pattern", "CredentialLabel"]);
            else
                this.Widgets.PostLoginPromptRules.Data = table( ...
                    string({rules.Pattern}).', ...
                    string({rules.CredentialLabel}).', ...
                    VariableNames=["Pattern", "CredentialLabel"]);
            end
            names = fieldnames(this.Widgets);
            valueNames = fieldnames(value);
            for index = 1:numel(valueNames)
                name = valueNames{index};
                if any(string(name) == ...
                        ["PostLoginScript", "PostLoginCommandTemplate", ...
                        "PostLoginPromptRules"])
                    continue
                end
                if any(strcmp(names, name)) && ...
                        isprop(this.Widgets.(name), "Value")
                    this.Widgets.(name).Value = value.(name);
                end
            end
        end

        function value = readEditor(this, value)
            names = ["DisplayName", "Enabled", "ExecutionMode", ...
                "CloudProvider", "CloudResourceName", "CloudRegion", ...
                "ProfileSource", ...
                "ConnectionMode", "Host", "Username", ...
                "AuthenticationMode", "IdentityFile", ...
                "RememberTotpSecret", ...
                "ExistingProfileName", "RemoteBridgeProfileName", ...
                "ClusterMatlabRoot", ...
                "RemoteJobStorageLocation", "NumWorkers", "PoolSize", ...
                "Partition", "Account", "QoS", "Walltime", ...
                "AdditionalSubmitArgs", "CodeDeploymentMode", ...
                "RemoteKssolvRoot", "HasSharedFilesystem", ...
                "RequiresOnlineLicensing", "LicenseNumber"];
            for name = names
                value.(name) = this.Widgets.(name).Value;
            end
            value.PostLoginCommandTemplate = join(string( ...
                this.Widgets.PostLoginCommandTemplate.Value), newline);
            value.PostLoginScript = join(string( ...
                this.Widgets.PostLoginScript.Value), newline);
            value.PostLoginPromptRules = promptRulesFromTable( ...
                this.Widgets.PostLoginPromptRules.Data);
            if ~value.RememberTotpSecret
                value.EncryptedTotpSecret = "";
            end
            if ~any(value.AuthenticationMode == ...
                    ["Password", "Multifactor"])
                value.EncryptedPassword = "";
                value.EncryptedTotpSecret = "";
            elseif value.AuthenticationMode == "Password"
                value.RememberTotpSecret = false;
                value.EncryptedTotpSecret = "";
            end
        end

        function value = applyCredentialInputs(this, value)
            storedPassword = any(value.ExecutionMode == ...
                ["Standard", "Bridge", "Mirror"]) && ...
                value.ConnectionMode == "SSH" && ...
                any(value.AuthenticationMode == ...
                ["Password", "Multifactor"]);
            if ~storedPassword
                return
            end

            password = passwordValue(this.Widgets.PasswordInput);
            if strlength(password) > 0
                value.EncryptedPassword = ...
                    this.CredentialCipher.encrypt(password);
            end
            if value.AuthenticationMode == "Multifactor" && ...
                    value.RememberTotpSecret
                totpSecret = passwordValue( ...
                    this.Widgets.TotpSecretInput);
                if strlength(totpSecret) > 0
                    kssolv.services.remote.security.Totp.generate(totpSecret);
                    value.EncryptedTotpSecret = ...
                        this.CredentialCipher.encrypt(totpSecret);
                end
            else
                value.EncryptedTotpSecret = "";
            end
        end

        function clearCredentialInputs(this)
            names = ["PasswordInput", "TotpSecretInput"];
            for name = names
                if isfield(this.Widgets, name) && ...
                        isvalid(this.Widgets.(name))
                    setPasswordValue(this.Widgets.(name), "");
                end
            end
        end

        function addConfiguration(this)
            value = kssolv.services.remote.config.RemoteConfiguration.defaults();
            value.DisplayName = remoteMessage("RemoteNewConfiguration");
            this.Configurations(end + 1, 1) = value;
            this.refreshTable();
            this.selectIndex(numel(this.Configurations));
            this.setConfigurationStatus( ...
                remoteMessage("RemoteCompleteAndSave"), false);
        end

        function duplicateConfiguration(this)
            try
                saved = this.saveCurrent();
                duplicate = this.ConfigurationStore.duplicate(saved.Id);
                this.reload();
                ids = string({this.Configurations.Id});
                this.selectIndex(find(ids == duplicate.Id, 1));
            catch exception
                this.setConfigurationStatus(exception.message, true);
            end
        end

        function deleteConfiguration(this)
            if this.SelectedIndex < 1 || ...
                    this.SelectedIndex > numel(this.Configurations)
                return
            end
            value = this.Configurations(this.SelectedIndex);
            try
                referencedJobs = kssolv.services.remote.job.RemoteJobStore().list();
                if ~isempty(referencedJobs) && any( ...
                        string({referencedJobs.ConfigurationId}) == value.Id)
                    error("KSSOLV:Remote:UI:ConfigurationInUse", ...
                        remoteMessage("RemoteConfigurationInUse"));
                end
                if value.ExecutionMode == "Standard" && ...
                        value.ProfileSource == "ManagedSlurm" && ...
                        strlength(value.ManagedProfileName) > 0
                    kssolv.services.remote.cluster.ClusterFactory(). ...
                        removeManagedProfile(value);
                end
                this.ConfigurationStore.remove(value.Id);
                selected = this.SelectionStore.get(this.ConfigurationStore);
                if selected == value.Id
                    this.SelectionStore.set("");
                end
                this.SelectedIndex = max(1, this.SelectedIndex - 1);
                this.reload();
                this.setConfigurationStatus(remoteMessage( ...
                    "RemoteConfigurationDeleted"), false);
            catch exception
                this.setConfigurationStatus(exception.message, true);
            end
        end

        function saveClicked(this)
            try
                this.saveCurrent();
            catch exception
                this.setConfigurationStatus(exception.message, true);
            end
        end

        function testConnection(this)
            try
                if this.SelectedIndex < 1 || ...
                        this.SelectedIndex > numel(this.Configurations)
                    error("KSSOLV:Remote:UI:NoConfigurationSelected", ...
                        remoteMessage("RemoteNoConfigurationSelected"));
                end
                value = this.readEditor( ...
                    this.Configurations(this.SelectedIndex));
                value = this.applyCredentialInputs(value);
                mode = string(value.ExecutionMode);
                sshLogin = any(mode == ["Bridge", "Mirror"]) || ...
                    (mode == "Standard" && ...
                    string(value.ProfileSource) == "ManagedSlurm" && ...
                    string(value.ConnectionMode) == "SSH");
                if sshLogin
                    value = kssolv.services.remote.diagnostics. ...
                        RemoteLoginTest.prepareConfiguration(value);
                    this.validateCredentialSetup(value);
                    session = kssolv.services.remote.diagnostics. ...
                        RemoteLoginTestSession(value, ...
                        this.CredentialCipher.KeyRoot);
                else
                    value = kssolv.services.remote.config.RemoteConfiguration. ...
                        create(value);
                    this.validateCredentialSetup(value);
                    session = createConnectionTestSession(value, false);
                end
                this.setConnectionStatus( ...
                    remoteMessage("RemoteTestingConnection"), false);
                this.setConnectionTestRunning(true);
                drawnow;
                this.ConnectionTestSession = session;
                this.ConnectionTestSession.start();
                this.ConnectionTestTimer = timer( ...
                    "ExecutionMode", "fixedSpacing", ...
                    "Period", 0.25, ...
                    "BusyMode", "drop", ...
                    "TimerFcn", @(~, ~) this.pollConnectionTest());
                start(this.ConnectionTestTimer);
            catch exception
                this.stopConnectionTest(false);
                this.setConnectionTestRunning(false);
                this.setConnectionStatus(connectionStatusMessage( ...
                    exception.identifier, exception.message, true), true);
            end
        end

        function discoverProfiles(this)
            try
                mode = string(this.Widgets.ExecutionMode.Value);
                if mode == "Cloud"
                    backend = kssolv.services.remote.backend.CloudBackend();
                    profiles = backend.discoverProfiles( ...
                        string(this.Widgets.CloudProvider.Value));
                    profiles = profiles([profiles.Available]);
                    names = string({profiles.Name});
                else
                    names = string(parallel.listProfiles());
                end
                names = unique(names(strlength(names) > 0), "stable");
                if isempty(names)
                    this.setConfigurationStatus(remoteMessage( ...
                        "RemoteNoProfilesDiscovered"), true);
                    return
                end
                current = string(this.Widgets.ExistingProfileName.Value);
                initial = find(names == current, 1);
                if isempty(initial)
                    initial = 1;
                end
                [selection, accepted] = listdlg( ...
                    "PromptString", char(remoteMessage( ...
                    "RemoteChooseProfile")), ...
                    "ListString", cellstr(names), ...
                    "SelectionMode", "single", ...
                    "InitialValue", initial, ...
                    "Name", char(remoteMessage("RemoteDiscoverProfiles")));
                if accepted
                    this.Widgets.ExistingProfileName.Value = ...
                        names(selection);
                    this.setConfigurationStatus("", false);
                end
            catch exception
                this.setConfigurationStatus(exception.message, true);
            end
        end

        function pollConnectionTest(this)
            session = this.ConnectionTestSession;
            if isempty(session) || ~isvalid(session)
                return
            end
            state = session.poll();
            switch state
                case "Queued"
                    if isa(session, ...
                            "kssolv.services.remote.diagnostics.RemoteLoginTestSession")
                        key = "RemoteLoginTestQueued";
                    else
                        key = "RemoteConnectionTestQueued";
                    end
                    this.setConnectionStatus(connectionProgressMessage( ...
                        session, key), false);
                case "Running"
                    if isa(session, ...
                            "kssolv.services.remote.diagnostics.RemoteLoginTestSession")
                        key = "RemoteLoginTestRunning";
                    else
                        key = "RemoteConnectionTestRunning";
                    end
                    this.setConnectionStatus(connectionProgressMessage( ...
                        session, key), false);
                case "Succeeded"
                    if isa(session, ...
                            "kssolv.services.remote.diagnostics.RemoteLoginTestSession")
                        this.setConnectionStatus(sprintf( ...
                            remoteMessage("RemoteLoginTestSucceeded"), ...
                            session.Report.Hostname), false);
                    else
                        this.setConnectionStatus(sprintf( ...
                            remoteMessage("RemoteProfileConnectionSucceeded"), ...
                            session.Report.ProfileName, ...
                            session.Report.Connection.Hostname), false);
                    end
                    this.setConnectionTestRunning(false);
                    drawnow;
                    this.stopConnectionTest(false);
                case "Failed"
                    this.setConnectionStatus(connectionStatusMessage( ...
                        session.ErrorIdentifier, ...
                        session.ErrorSummary, false), true);
                    this.setConnectionTestRunning(false);
                    drawnow;
                    this.stopConnectionTest(false);
                case "Cancelled"
                    this.setConnectionStatus(remoteMessage( ...
                        "RemoteConnectionTestCancelled"), false);
                    this.setConnectionTestRunning(false);
                    drawnow;
                    this.stopConnectionTest(false);
            end
        end

        function probeResources(this)
            try
                if this.SelectedIndex < 1 || ...
                        this.SelectedIndex > numel(this.Configurations)
                    error("KSSOLV:Remote:UI:NoConfigurationSelected", ...
                        remoteMessage("RemoteNoConfigurationSelected"));
                end
                value = this.readEditor( ...
                    this.Configurations(this.SelectedIndex));
                value = this.applyCredentialInputs(value);
                mode = string(value.ExecutionMode);
                routedProbe = (mode == "Standard" && ...
                    string(value.ProfileSource) == "ManagedSlurm" && ...
                    string(value.ConnectionMode) == "SSH") || ...
                    any(mode == ["Bridge", "Mirror"]);
                if routedProbe
                    value = kssolv.services.remote.diagnostics. ...
                        RemoteEnvironmentProbe.prepareConfiguration(value);
                    this.validateCredentialSetup(value);
                    session = kssolv.services.remote.diagnostics. ...
                        RemoteEnvironmentProbeSession(value, ...
                        this.CredentialCipher.KeyRoot);
                else
                    value = kssolv.services.remote.config.RemoteConfiguration. ...
                        create(value);
                    this.validateCredentialSetup(value);
                    session = createConnectionTestSession(value, true);
                end
                this.setResourceProbeStatus( ...
                    remoteMessage("RemoteStartingResourceProbe"), false);
                this.setResourceProbeRunning(true);
                drawnow;
                this.ResourceProbeSession = session;
                this.ResourceProbeSession.start();
                this.ResourceProbeTimer = timer( ...
                    "ExecutionMode", "fixedSpacing", ...
                    "Period", 0.25, "BusyMode", "drop", ...
                    "TimerFcn", @(~, ~) this.pollResourceProbe());
                start(this.ResourceProbeTimer);
            catch exception
                this.stopResourceProbe(false);
                this.setResourceProbeRunning(false);
                this.setResourceProbeStatus(connectionStatusMessage( ...
                    exception.identifier, exception.message, true), true);
            end
        end

        function pollResourceProbe(this)
            session = this.ResourceProbeSession;
            if isempty(session) || ~isvalid(session)
                return
            end
            state = session.poll();
            switch state
                case "Queued"
                    this.setResourceProbeStatus(connectionProgressMessage( ...
                        session, "RemoteEnvironmentProbeQueued"), false);
                case "Running"
                    this.setResourceProbeStatus(connectionProgressMessage( ...
                        session, "RemoteEnvironmentProbeRunning"), false);
                case "Succeeded"
                    this.applyEnvironmentProbe(session.Report.Probe);
                    this.setResourceProbeRunning(false);
                    drawnow;
                    this.stopResourceProbe(false);
                case "Failed"
                    this.setResourceProbeStatus(connectionStatusMessage( ...
                        session.ErrorIdentifier, ...
                        session.ErrorSummary, false), true);
                    this.setResourceProbeRunning(false);
                    drawnow;
                    this.stopResourceProbe(false);
                case "Cancelled"
                    this.setResourceProbeStatus(remoteMessage( ...
                        "RemoteResourceProbeCancelled"), false);
                    this.setResourceProbeRunning(false);
                    drawnow;
                    this.stopResourceProbe(false);
            end
        end

        function cancelResourceProbe(this)
            if isempty(this.ResourceProbeSession) || ...
                    ~isvalid(this.ResourceProbeSession)
                return
            end
            this.setResourceProbeStatus(remoteMessage( ...
                "RemoteCancellingResourceProbe"), false);
            this.Widgets.CancelResourceProbe.Enable = "off";
            drawnow;
            this.ResourceProbeSession.cancel();
            this.pollResourceProbe();
        end

        function stopResourceProbe(this, cancelActive)
            arguments
                this
                cancelActive (1, 1) logical
            end
            if ~isempty(this.ResourceProbeTimer) && ...
                    isvalid(this.ResourceProbeTimer)
                stop(this.ResourceProbeTimer);
                delete(this.ResourceProbeTimer);
            end
            this.ResourceProbeTimer = [];
            if ~isempty(this.ResourceProbeSession) && ...
                    isvalid(this.ResourceProbeSession)
                if cancelActive && ~any( ...
                        this.ResourceProbeSession.State == ...
                        this.ResourceProbeSession.TerminalStates)
                    this.ResourceProbeSession.cancel();
                end
                this.ResourceProbeSession.cleanup();
            end
        end

        function cancelConnectionTest(this)
            if isempty(this.ConnectionTestSession) || ...
                    ~isvalid(this.ConnectionTestSession)
                return
            end
            this.setConnectionStatus(remoteMessage( ...
                "RemoteCancellingConnectionTest"), false);
            this.Widgets.CancelTest.Enable = "off";
            drawnow;
            this.ConnectionTestSession.cancel();
            this.pollConnectionTest();
        end

        function stopConnectionTest(this, cancelActive)
            arguments
                this
                cancelActive (1, 1) logical
            end
            if ~isempty(this.ConnectionTestTimer) && ...
                    isvalid(this.ConnectionTestTimer)
                stop(this.ConnectionTestTimer);
                delete(this.ConnectionTestTimer);
            end
            this.ConnectionTestTimer = [];
            if ~isempty(this.ConnectionTestSession) && ...
                    isvalid(this.ConnectionTestSession)
                if cancelActive && ~any( ...
                        this.ConnectionTestSession.State == ...
                        this.ConnectionTestSession.TerminalStates)
                    this.ConnectionTestSession.cancel();
                end
                this.ConnectionTestSession.cleanup();
            end
        end

        function setConnectionTestRunning(this, running)
            this.Widgets.Test.Enable = onOff(~running);
            this.Widgets.CancelTest.Enable = onOff(running);
            this.Widgets.ResourceProbe.Enable = onOff(~running);
            this.Widgets.Save.Enable = onOff(~running);
            this.Widgets.Add.Enable = onOff(~running);
            this.Widgets.Duplicate.Enable = onOff(~running);
            this.Widgets.Delete.Enable = onOff(~running);
        end

        function setResourceProbeRunning(this, running)
            this.Widgets.ResourceProbe.Enable = onOff(~running);
            this.Widgets.CancelResourceProbe.Enable = onOff(running);
            this.Widgets.Test.Enable = onOff(~running);
            this.Widgets.Save.Enable = onOff(~running);
            this.Widgets.Add.Enable = onOff(~running);
            this.Widgets.Duplicate.Enable = onOff(~running);
            this.Widgets.Delete.Enable = onOff(~running);
        end

        function applyEnvironmentProbe(this, probe)
            this.Widgets.ClusterMatlabRoot.Value = ...
                string(probe.ClusterMatlabRoot);
            if isfield(probe, "RemoteJobStorageLocation") && ...
                    strlength(string( ...
                    probe.RemoteJobStorageLocation)) > 0
                this.Widgets.RemoteJobStorageLocation.Value = ...
                    string(probe.RemoteJobStorageLocation);
            end
            if isfield(probe, "NumWorkers") && ...
                    isfinite(double(probe.NumWorkers)) && ...
                    double(probe.NumWorkers) >= 1
                this.Widgets.NumWorkers.Value = ...
                    floor(double(probe.NumWorkers));
            end
            if isfield(probe, "PoolSize") && ...
                    isfinite(double(probe.PoolSize)) && ...
                    double(probe.PoolSize) >= 0
                this.Widgets.PoolSize.Value = min( ...
                    floor(double(probe.PoolSize)), ...
                    this.Widgets.NumWorkers.Value);
            end
            this.Widgets.TabGroup.SelectedTab = ...
                this.Widgets.ComputeTab;
            this.setResourceProbeStatus(sprintf( ...
                remoteMessage("RemoteEnvironmentProbeSucceeded"), ...
                probe.Hostname, probe.MatlabRelease, ...
                probe.ClusterMatlabRoot, probe.NumWorkers, ...
                probe.PoolSize), false);
        end

        function updateConditionalControls(this)
            if this.SelectedIndex == 0
                return
            end
            mode = string(this.Widgets.ExecutionMode.Value);
            standard = mode == "Standard";
            bridge = mode == "Bridge";
            mirror = mode == "Mirror";
            cloud = mode == "Cloud";
            routed = standard || bridge || mirror;

            if bridge || mirror
                this.Widgets.ConnectionMode.Value = "SSH";
            elseif cloud
                this.Widgets.ProfileSource.Value = ...
                    "ExistingMatlabProfile";
                this.Widgets.ConnectionMode.Value = "Direct";
                this.Widgets.PostLoginScript.Value = {''};
                this.Widgets.PostLoginCommandTemplate.Value = ...
                    {'{command}'};
                this.Widgets.PostLoginPromptRules.Data = table( ...
                    strings(0, 1), strings(0, 1), ...
                    VariableNames=["Pattern", "CredentialLabel"]);
            end
            managed = this.Widgets.ProfileSource.Value == "ManagedSlurm";
            ssh = this.Widgets.ConnectionMode.Value == "SSH";
            identity = this.Widgets.AuthenticationMode.Value == ...
                "IdentityFile";
            automatedMfa = routed && ssh && ...
                this.Widgets.AuthenticationMode.Value == "Multifactor";
            storedPassword = routed && ssh && any( ...
                this.Widgets.AuthenticationMode.Value == ...
                ["Password", "Multifactor"]);
            rememberTotpSecret = automatedMfa && ...
                this.Widgets.RememberTotpSecret.Value;
            if ~storedPassword
                this.clearCredentialInputs();
            elseif ~rememberTotpSecret
                setPasswordValue(this.Widgets.TotpSecretInput, "");
            end
            installed = this.Widgets.CodeDeploymentMode.Value == ...
                "ClusterInstalled";
            onlineLicensing = this.Widgets.RequiresOnlineLicensing.Value;
            this.updateFieldVisibility();
            set(this.Widgets.CloudProvider, "Enable", onOff(cloud));
            set(this.Widgets.CloudResourceName, "Enable", onOff(cloud));
            set(this.Widgets.CloudRegion, "Enable", onOff(cloud));
            set(this.Widgets.ProfileSource, "Enable", onOff(standard));
            set(this.Widgets.ConnectionMode, "Enable", ...
                onOff(standard));
            set(this.Widgets.Host, "Enable", ...
                onOff(routed && ssh));
            set(this.Widgets.Username, "Enable", ...
                onOff(routed && ssh));
            set(this.Widgets.AuthenticationMode, "Enable", ...
                onOff(routed && ssh));
            set(this.Widgets.IdentityFile, "Enable", ...
                onOff(routed && ssh && identity));
            set(this.Widgets.RememberTotpSecret, "Enable", ...
                onOff(automatedMfa));
            setPasswordEnabled(this.Widgets.PasswordInput, storedPassword);
            setPasswordEnabled(this.Widgets.TotpSecretInput, ...
                rememberTotpSecret);
            set(this.Widgets.ExistingProfileName, "Enable", ...
                onOff(cloud || (standard && ~managed)));
            set(this.Widgets.DiscoverProfiles, "Enable", ...
                onOff(cloud || (standard && ~managed)));
            set(this.Widgets.RemoteBridgeProfileName, "Enable", ...
                onOff(bridge));
            set(this.Widgets.ClusterMatlabRoot, "Enable", ...
                onOff(bridge || mirror || (standard && managed)));
            set(this.Widgets.RemoteJobStorageLocation, "Enable", ...
                onOff(routed && ssh));
            set(this.Widgets.PostLoginScript, "Enable", onOff(routed));
            set(this.Widgets.PostLoginCommandTemplate, "Enable", ...
                onOff(routed));
            set(this.Widgets.PostLoginPromptRules, "Enable", ...
                onOff(routed));
            set(this.Widgets.AddPromptRule, "Enable", onOff(routed));
            set(this.Widgets.RemovePromptRule, "Enable", onOff(routed));
            directManaged = standard && managed;
            names = ["Partition", "Account", "QoS", "Walltime", ...
                "AdditionalSubmitArgs", "HasSharedFilesystem", ...
                "RequiresOnlineLicensing"];
            for name = names
                set(this.Widgets.(name), "Enable", onOff(directManaged));
            end
            set(this.Widgets.RemoteKssolvRoot, "Enable", onOff(installed));
            set(this.Widgets.LicenseNumber, "Enable", ...
                onOff(directManaged && onlineLicensing));
        end

        function updateFieldVisibility(this)
            mode = string(this.Widgets.ExecutionMode.Value);
            managed = this.Widgets.ProfileSource.Value == "ManagedSlurm";
            ssh = this.Widgets.ConnectionMode.Value == "SSH";
            identity = this.Widgets.AuthenticationMode.Value == ...
                "IdentityFile";
            installed = this.Widgets.CodeDeploymentMode.Value == ...
                "ClusterInstalled";
            onlineLicensing = this.Widgets.RequiresOnlineLicensing.Value;

            visibleFields = ["DisplayName", "Enabled", "ExecutionMode", ...
                "ConnectionDiscovery", "ConnectionStatus", ...
                "CodeDeploymentMode", "ResourceDiscovery", ...
                "ResourceProbeStatus"];
            switch mode
                case "Standard"
                    visibleFields = [visibleFields, "ProfileSource", ...
                        "ConnectionMode", "PostLoginScript", ...
                        "PostLoginCommandTemplate", ...
                        "PostLoginPromptRules", "NumWorkers", "PoolSize"];
                    if ssh
                        visibleFields = [visibleFields, "Host", "Username", ...
                            "AuthenticationMode", ...
                            "RemoteJobStorageLocation"];
                        if identity
                            visibleFields(end + 1) = "IdentityFile";
                        end
                    end
                    if managed
                        visibleFields = [visibleFields, ...
                            "ClusterMatlabRoot", "Partition", "Account", ...
                            "QoS", "Walltime", "AdditionalSubmitArgs", ...
                            "HasSharedFilesystem", ...
                            "RequiresOnlineLicensing"];
                        if onlineLicensing
                            visibleFields(end + 1) = "LicenseNumber";
                        end
                    else
                        visibleFields(end + 1) = "ExistingProfileName";
                    end
                case "Bridge"
                    visibleFields = [visibleFields, "Host", "Username", ...
                        "AuthenticationMode", ...
                        "RemoteBridgeProfileName", "ClusterMatlabRoot", ...
                        "RemoteJobStorageLocation", ...
                        "PostLoginScript", ...
                        "PostLoginCommandTemplate", ...
                        "PostLoginPromptRules", "NumWorkers", "PoolSize"];
                    if identity
                        visibleFields(end + 1) = "IdentityFile";
                    end
                case "Mirror"
                    visibleFields = [visibleFields, "Host", "Username", ...
                        "AuthenticationMode", "ClusterMatlabRoot", ...
                        "RemoteJobStorageLocation", ...
                        "PostLoginScript", ...
                        "PostLoginCommandTemplate", ...
                        "PostLoginPromptRules", "NumWorkers", "PoolSize"];
                    if identity
                        visibleFields(end + 1) = "IdentityFile";
                    end
                case "Cloud"
                    visibleFields = [visibleFields, "CloudProvider", ...
                        "CloudResourceName", "CloudRegion", ...
                        "ExistingProfileName", "NumWorkers", "PoolSize"];
            end
            storedPassword = any(mode == ...
                ["Standard", "Bridge", "Mirror"]) && ssh && ...
                any(this.Widgets.AuthenticationMode.Value == ...
                ["Password", "Multifactor"]);
            automatedMfa = storedPassword && ...
                this.Widgets.AuthenticationMode.Value == "Multifactor";
            if storedPassword
                visibleFields(end + 1) = "PasswordInput";
            end
            if automatedMfa
                visibleFields(end + 1) = "RememberTotpSecret";
                if this.Widgets.RememberTotpSecret.Value
                    visibleFields(end + 1) = "TotpSecretInput";
                end
            end
            if installed
                visibleFields(end + 1) = "RemoteKssolvRoot";
            end

            visibleRows = cellfun(@(heights)false(1, numel(heights)), ...
                this.EditorRowHeights, "UniformOutput", false);
            for name = unique(visibleFields, "stable")
                tab = this.FieldTabs.(name);
                visibleRows{tab}(this.FieldRows.(name)) = true;
            end
            for tab = 1:numel(this.EditorGrids)
                rowHeights = this.EditorRowHeights{tab};
                rowHeights(~visibleRows{tab}) = {0};
                grid = this.EditorGrids{tab};
                grid.RowHeight = rowHeights;
                children = grid.Children;
                for index = 1:numel(children)
                    row = children(index).Layout.Row;
                    setComponentTreeVisible(children(index), ...
                        all(visibleRows{tab}(row)));
                end
            end
        end

        function setEditorEnabled(this, enabled)
            names = fieldnames(this.Widgets);
            excluded = ["Table", "Add", "Close", "Status", ...
                "ConfigurationStatus", "ConnectionStatus", ...
                "ResourceProbeStatus", "CancelTest", ...
                "CancelResourceProbe"];
            for index = 1:numel(names)
                name = string(names{index});
                if ~any(name == excluded) && ...
                        isprop(this.Widgets.(name), "Enable")
                    this.Widgets.(name).Enable = onOff(enabled);
                end
            end
        end

        function setConfigurationStatus(this, text, isError)
            fullText = string(text);
            displayText = strip(join(splitlines(fullText), " "));
            this.Widgets.ConfigurationStatus.Text = displayText;
            this.Widgets.ConfigurationStatus.Tooltip = fullText;
            if isError
                this.Widgets.ConfigurationStatus.FontColor = ...
                    [0.75, 0.1, 0.1];
            else
                this.Widgets.ConfigurationStatus.FontColor = ...
                    [0.15, 0.45, 0.2];
            end
        end

        function setConnectionStatus(this, text, isError)
            this.Widgets.ConnectionStatus.Text = string(text);
            this.Widgets.ConnectionStatus.Tooltip = string(text);
            if isError
                this.Widgets.ConnectionStatus.FontColor = ...
                    [0.75, 0.1, 0.1];
            else
                this.Widgets.ConnectionStatus.FontColor = ...
                    [0.15, 0.45, 0.2];
            end
        end

        function setResourceProbeStatus(this, text, isError)
            this.Widgets.ResourceProbeStatus.Text = string(text);
            this.Widgets.ResourceProbeStatus.Tooltip = string(text);
            if isError
                this.Widgets.ResourceProbeStatus.FontColor = ...
                    [0.75, 0.1, 0.1];
            else
                this.Widgets.ResourceProbeStatus.FontColor = ...
                    [0.15, 0.45, 0.2];
            end
        end

        function validateCredentialSetup(this, configuration)
            if ~any(configuration.ExecutionMode == ...
                    ["Standard", "Bridge", "Mirror"]) || ...
                    configuration.ConnectionMode ~= "SSH" || ...
                    ~any(configuration.AuthenticationMode == ...
                    ["Password", "Multifactor"])
                return
            end
            if strlength(configuration.EncryptedPassword) == 0
                error("KSSOLV:Remote:UI:StoredPasswordRequired", ...
                    remoteMessage("RemoteStoredPasswordRequired"));
            end
            this.CredentialCipher.decrypt( ...
                configuration.EncryptedPassword);
            if configuration.AuthenticationMode == "Multifactor" && ...
                    configuration.RememberTotpSecret
                if strlength(configuration.EncryptedTotpSecret) == 0
                    error("KSSOLV:Remote:UI:StoredTotpRequired", ...
                        remoteMessage("RemoteStoredTotpRequired"));
                end
                secret = this.CredentialCipher.decrypt( ...
                    configuration.EncryptedTotpSecret);
                kssolv.services.remote.security.Totp.generate(secret);
            end
        end

    end
end

function [field, helpButton, label] = addText( ...
        parent, row, key, helpKey, qualifierKey)
if nargin < 4
    helpKey = "";
end
if nargin < 5
    qualifierKey = "";
end
[label, helpButton] = addLabel( ...
    parent, row, key, helpKey, qualifierKey);
field = uieditfield(parent, "text");
field.Layout.Row = row;
field.Layout.Column = 2;
end

function field = addPassword(parent, row, key, placeholderKey)
addLabel(parent, row, key);
field = uihtml(parent, "HTMLSource", fullfile( ...
    fileparts(mfilename("fullpath")), "passwordField.html"), ...
    "Data", struct("Value", "", "Enabled", true, ...
    "Placeholder", remoteMessage(placeholderKey)));
field.Tooltip = remoteMessage(placeholderKey);
field.Layout.Row = row;
field.Layout.Column = 2;
end

function value = passwordValue(field)
value = string(field.Data.Value);
end

function setPasswordValue(field, value)
data = field.Data;
data.Value = string(value);
field.Data = data;
end

function setPasswordEnabled(field, enabled)
data = field.Data;
data.Enabled = logical(enabled);
field.Data = data;
end

function [field, button, helpButton] = addTextWithButton( ...
        parent, row, key, buttonKey, callback, helpKey)
if nargin < 6
    helpKey = "";
end
[~, helpButton] = addLabel(parent, row, key, helpKey);
container = uigridlayout(parent, [1, 2], ...
    "ColumnWidth", {"1x", "fit"}, "Padding", 0);
container.Layout.Row = row;
container.Layout.Column = 2;
field = uieditfield(container, "text");
button = uibutton(container, "Text", remoteMessage(buttonKey), ...
    "ButtonPushedFcn", callback);
end

function [testButton, cancelButton] = addConnectionTestActions( ...
        parent, row, testCallback, cancelCallback)
addLabel(parent, row, "RemoteConnectionDiscovery");
container = uigridlayout(parent, [1, 2], ...
    "ColumnWidth", {"1x", "1x"}, "Padding", 0);
container.Layout.Row = row;
container.Layout.Column = 2;
testButton = uibutton(container, ...
    "Text", remoteMessage("RemoteTestConnection"), ...
    "ButtonPushedFcn", testCallback);
cancelButton = uibutton(container, ...
    "Text", remoteMessage("RemoteCancelConnectionTest"), ...
    "Enable", "off", "ButtonPushedFcn", cancelCallback);
end

function [probeButton, cancelButton] = addResourceProbeActions( ...
        parent, row, probeCallback, cancelCallback)
addLabel(parent, row, "RemoteResourceDiscovery");
container = uigridlayout(parent, [1, 2], ...
    "ColumnWidth", {"1x", "1x"}, "Padding", 0);
container.Layout.Row = row;
container.Layout.Column = 2;
probeButton = uibutton(container, ...
    "Text", remoteMessage("RemoteProbeResources"), ...
    "ButtonPushedFcn", probeCallback);
cancelButton = uibutton(container, ...
    "Text", remoteMessage("RemoteCancelResourceProbe"), ...
    "Enable", "off", "ButtonPushedFcn", cancelCallback);
end

function [field, helpButton, label] = addNumber( ...
        parent, row, key, lower, upper, helpKey, qualifierKey)
if nargin < 6
    helpKey = "";
end
if nargin < 7
    qualifierKey = "";
end
[label, helpButton] = addLabel( ...
    parent, row, key, helpKey, qualifierKey);
field = uispinner(parent, "Limits", [lower, upper], "Value", lower);
field.Layout.Row = row;
field.Layout.Column = 2;
end

function [field, helpButton] = addDropDown( ...
        parent, row, key, items, helpKey)
if nargin < 5
    helpKey = "";
end
[~, helpButton] = addLabel(parent, row, key, helpKey);
field = uidropdown(parent, "Items", cellstr(items), ...
    "ItemsData", cellstr(items));
field.Layout.Row = row;
field.Layout.Column = 2;
end

function [field, helpButton] = addLocalizedDropDown( ...
        parent, row, key, itemsData, itemKeys, helpKey)
if nargin < 6
    helpKey = "";
end
[~, helpButton] = addLabel(parent, row, key, helpKey);
items = arrayfun(@remoteMessage, itemKeys);
field = uidropdown(parent, "Items", cellstr(items), ...
    "ItemsData", cellstr(itemsData));
field.Layout.Row = row;
field.Layout.Column = 2;
end

function [field, helpButton, label] = addTextArea( ...
        parent, row, key, helpKey, qualifierKey)
if nargin < 5
    qualifierKey = "";
end
[label, helpButton] = addLabel( ...
    parent, row, key, helpKey, qualifierKey);
field = uitextarea(parent, "Value", {'{command}'});
field.Layout.Row = row;
field.Layout.Column = 2;
end

function [field, addButton, removeButton, helpButton, label] = ...
        addPromptRules(parent, row, qualifierKey)
if nargin < 3
    qualifierKey = "";
end
[label, helpButton] = addLabel(parent, row, ...
    "RemotePostLoginPromptRules", "RemotePostLoginPromptRulesHelp", ...
    qualifierKey);
container = uigridlayout(parent, [2, 2], ...
    "RowHeight", {"1x", 26}, "ColumnWidth", {"1x", "1x"}, ...
    "Padding", 0, "RowSpacing", 4);
container.Layout.Row = row;
container.Layout.Column = 2;
field = uitable(container, "Data", table( ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["Pattern", "CredentialLabel"]), ...
    "RowName", [], "ColumnEditable", [true, true], ...
    "ColumnName", [remoteMessage("RemotePromptPatternColumn"), ...
    remoteMessage("RemoteCredentialLabelColumn")]);
field.Layout.Row = 1;
field.Layout.Column = [1, 2];
addButton = uibutton(container, ...
    "Text", remoteMessage("RemoteAddPromptRule"), ...
    "ButtonPushedFcn", @(~, ~) addPromptRule(field));
addButton.Layout.Row = 2;
addButton.Layout.Column = 1;
removeButton = uibutton(container, ...
    "Text", remoteMessage("RemoteRemovePromptRule"), ...
    "ButtonPushedFcn", @(~, ~) removePromptRule(field));
removeButton.Layout.Row = 2;
removeButton.Layout.Column = 2;
end

function addPromptRule(field)
data = field.Data;
data(end + 1, :) = {"", ""};
field.Data = data;
end

function removePromptRule(field)
data = field.Data;
if height(data) > 0
    data(end, :) = [];
    field.Data = data;
end
end

function rules = promptRulesFromTable(data)
rules = repmat(struct("Pattern", "", "CredentialLabel", ""), 0, 1);
for index = 1:height(data)
    pattern = strip(string(data.Pattern(index)));
    label = strip(string(data.CredentialLabel(index)));
    if strlength(pattern) == 0 && strlength(label) == 0
        continue
    end
    rules(end + 1, 1) = struct( ...
        "Pattern", pattern, "CredentialLabel", label); %#ok<AGROW>
end
end

function [field, helpButton] = addCheck(parent, row, key, helpKey)
if nargin < 4
    helpKey = "";
end
[~, helpButton] = addLabel(parent, row, key, helpKey);
field = uicheckbox(parent, "Text", "");
field.Layout.Row = row;
field.Layout.Column = 2;
end

function [label, helpButton] = addLabel( ...
        parent, row, key, helpKey, qualifierKey)
if nargin < 4 || strlength(string(helpKey)) == 0
    if nargin < 5
        qualifierKey = "";
    end
    label = uilabel(parent, "Text", qualifiedLabel(key, qualifierKey));
    label.Layout.Row = row;
    label.Layout.Column = 1;
    helpButton = [];
    return
end
if nargin < 5
    qualifierKey = "";
end

container = uigridlayout(parent, [1, 2], ...
    "RowHeight", {24}, "ColumnWidth", {"1x", 24}, ...
    "Padding", 0, "ColumnSpacing", 4);
container.Layout.Row = row;
container.Layout.Column = 1;
label = uilabel(container, "Text", qualifiedLabel(key, qualifierKey));
label.Layout.Row = 1;
label.Layout.Column = 1;
helpText = remoteMessage(helpKey);
helpButton = uibutton(container, "Text", "", ...
    "BackgroundColor", "white", "Tooltip", helpText, ...
    "ButtonPushedFcn", @(~, ~) showFieldHelp(parent, helpText));
helpButton.IconAlignment = "center";
matlab.ui.control.internal.specifyIconID(helpButton, "help", 16);
helpButton.Layout.Row = 1;
helpButton.Layout.Column = 2;
end

function value = qualifiedLabel(key, qualifierKey)
value = remoteMessage(key);
if strlength(string(qualifierKey)) > 0
    value = value + remoteMessage(qualifierKey);
end
value = value + ":";
end

function showFieldHelp(parent, helpText)
figure = ancestor(parent, "figure");
uialert(figure, helpText, remoteMessage("RemoteHelpTitle"), ...
    "Icon", "info");
end

function setComponentTreeVisible(component, visible)
if isprop(component, "Visible")
    component.Visible = onOff(visible);
end
if ~isprop(component, "Children")
    return
end
children = component.Children;
for index = 1:numel(children)
    setComponentTreeVisible(children(index), visible);
end
end

function value = onOff(enabled)
if logical(enabled)
    value = "on";
else
    value = "off";
end
end

function value = remoteMessage(key)
value = string(kssolv.ui.util.Localizer.message( ...
    "KSSOLV:dialogs:" + string(key)));
end

function session = createConnectionTestSession(configuration, probeResources)
if nargin < 2 || logical(probeResources)
    purpose = "";
else
    purpose = "ConnectionOnly";
end
backend = kssolv.services.remote.backend.RemoteBackendFactory().create( ...
    configuration);
session = backend.testConnection(configuration, purpose);
end

function value = connectionProgressMessage(session, fallbackKey)
key = string(fallbackKey);
if isa(session, ...
        "kssolv.services.remote.diagnostics.RemoteEnvironmentProbeSession")
    switch string(session.Phase)
        case "Connecting"
            key = "RemoteEnvironmentConnecting";
        case "PostLoginAndDiscovery"
            key = "RemoteEnvironmentPostLoginAndDiscovery";
        case "Cancelling"
            key = "RemoteCancellingConnectionTest";
    end
elseif isa(session, ...
        "kssolv.services.remote.diagnostics.RemoteLoginTestSession")
    switch string(session.Phase)
        case "Connecting"
            key = "RemoteEnvironmentConnecting";
        case "PostLogin"
            key = "RemoteLoginPostLoginRunning";
        case "Cancelling"
            key = "RemoteCancellingConnectionTest";
    end
end
value = remoteMessage(key);
if isprop(session, "StartedAt") && ...
        ~isempty(session.StartedAt) && ~isnat(session.StartedAt)
    elapsed = max(0, floor(seconds(datetime("now") - ...
        session.StartedAt)));
    value = value + " " + sprintf( ...
        remoteMessage("RemoteConnectionElapsed"), elapsed);
end
end

function value = connectionStatusMessage(identifier, detail, beforeStart)
identifier = string(identifier);
detail = strip(string(detail));
combined = lower(identifier + " " + detail);
if beforeStart
    key = "RemoteConnectionNotStarted";
elseif contains(combined, lower( ...
        "KSSOLV:Remote:PostLoginScriptFailed"))
    key = "RemoteConnectionSucceededScriptFailed";
elseif any(contains(combined, lower( ...
        ["KSSOLV:Remote:EnvironmentProbeFailed", ...
        "KSSOLV:Remote:EnvironmentProbeInvalidOutput"])))
    key = "RemoteConnectionSucceededProbeFailed";
elseif contains(combined, lower( ...
        "KSSOLV:Remote:EnvironmentConnectionFailed"))
    key = "RemoteConnectionFailed";
else
    key = "RemoteConnectionFailed";
end
value = remoteMessage(key);
if strlength(detail) > 0
    value = value + " " + sprintf( ...
        remoteMessage("RemoteConnectionDiagnosticDetail"), detail);
end
end
