classdef CostTest < matlab.unittest.TestCase
    methods (Test)
        function officialDatabases(testCase)
            root = "/tmp/matgenlab-plan.tMNeV8/pymatgen-2026.5.4/" + ...
                "test-files/analysis/cost/";
            testCase.assumeTrue(isfile(root + "costdb_1.csv"), ...
                "Frozen cost fixture unavailable.");
            first = kssolv.analysis.matgenlab.analysis.CostAnalyzer( ...
                kssolv.analysis.matgenlab.analysis.CostDBCSV( ...
                root + "costdb_1.csv"));
            second = kssolv.analysis.matgenlab.analysis.CostAnalyzer( ...
                kssolv.analysis.matgenlab.analysis.CostDBCSV( ...
                root + "costdb_2.csv"));
            testCase.verifyEqual(first.get_cost_per_kg("Ag"), ...
                3, RelTol=1e-3);
            testCase.verifyEqual(first.get_cost_per_kg("O"), ...
                1, RelTol=1e-3);
            testCase.verifyEqual(first.get_cost_per_kg("AgO"), ...
                2.7416, RelTol=1e-3);
            testCase.verifyEqual(second.get_cost_per_kg("AgO"), ...
                1.5, RelTol=1e-3);
            testCase.verifyEqual(first.get_cost_per_mol("AgO"), ...
                0.3396, RelTol=1e-3);
            testCase.verifyEqual(second.get_cost_per_mol("AgO"), ...
                0.1858, RelTol=1e-3);
        end

        function builtinSanityAndReference(testCase)
            analyzer = kssolv.analysis.matgenlab.analysis.CostAnalyzer( ...
                kssolv.analysis.matgenlab.analysis.CostDBElements());
            testCase.verifyGreaterThan( ...
                analyzer.get_cost_per_kg("PtO"), ...
                analyzer.get_cost_per_kg("MgO"));
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.analysis.CostEntry( ...
                "Ag", 1, "silver", "not BibTeX"), ...
                "KSSOLV:Matgenlab:CostEntry:InvalidReference");
        end
    end
end
