classdef DimensionalityTest < matlab.unittest.TestCase
    methods (Test)
        function larsenRanksAndOrientations(testCase)
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3), ...
                {"C"},[0,0,0]);
            graph=kssolv.analysis.matgenlab.core.StructureGraph. ...
                from_empty_graph(structure);
            graph.add_edge(1,1,"to_jimage",[1,0,0]);
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_larsen(graph),1);
            component=kssolv.analysis.matgenlab.analysis. ...
                get_structure_components(graph,"inc_orientation",true, ...
                "inc_site_ids",true);
            testCase.verifyEqual(component.orientation,[1,0,0]);
            testCase.verifyEqual(component.site_ids,1);
            testCase.verifyEqual(component.structure_graph.graph. ...
                number_of_edges(),1);
            graph.add_edge(1,1,"to_jimage",[0,1,0]);
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                calculate_dimensionality_of_site(graph,1),2);
            graph.add_edge(1,1,"to_jimage",[0,0,1]);
            [dimension,vertices]=kssolv.analysis.matgenlab.analysis. ...
                calculate_dimensionality_of_site(graph,1,true);
            testCase.verifyEqual(dimension,3);
            testCase.verifySize(vertices,[4,3]);
        end

        function zeroDimensionalMoleculeConversion(testCase)
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(8), ...
                {"H","C","N"},[.1,.1,.1;.2,.1,.1;.3,.1,.1]);
            graph=kssolv.analysis.matgenlab.core.StructureGraph. ...
                from_empty_graph(structure);
            graph.add_edge(1,2,"to_jimage",[0,0,0]);
            graph.add_edge(2,3,"to_jimage",[0,0,0]);
            components=kssolv.analysis.matgenlab.analysis. ...
                get_structure_components(graph,"inc_molecule_graph",true);
            moleculeGraph=components.molecule_graph;
            testCase.verifyEqual(moleculeGraph.molecule.num_sites,3);
            testCase.verifyEqual(moleculeGraph.graph.number_of_edges(),2);
            connected=moleculeGraph.get_connected_sites(2);
            testCase.verifyEqual([connected{1}.index,connected{2}.index], ...
                [3,1]);
            graph.add_edge(1,1,"to_jimage",[1,0,0]);
            testCase.verifyError(@()kssolv.analysis.matgenlab.analysis. ...
                zero_d_graph_to_molecule_graph(graph,1:3), ...
                "KSSOLV:Matgenlab:Dimensionality:NotZeroD");
        end

        function cheonMatchesOfficialStructures(testCase)
            graphite=readFixture("Graphite.cif");
            lifepo=readFixture("LiFePO4.cif");
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_cheon(graphite),"2D");
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_cheon(lifepo),"intercalated ion");
            cscl=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4.209), ...
                {"Cl","Cs"},[.5,.5,.5;0,0,0]);
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_cheon(cscl,"standardize",false), ...
                "intercalated ion");
            radii=struct("Cs",3.7,"Cl",3);
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_cheon(cscl,"ldict",radii, ...
                "standardize",false),"3D");
        end

        function goraiAndClusterHelpersMatchOfficial(testCase)
            graphite=readFixture("Graphite.cif");
            lifepo=readFixture("LiFePO4.cif");
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_gorai(graphite),2);
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_gorai(lifepo),3);
            cscl=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4.209), ...
                {"Cl","Cs"},[.5,.5,.5;0,0,0]);
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_gorai(cscl,"standardize",false),1);
            bonds=containers.Map({'Cs|Cl'},{3.7});
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                get_dimensionality_gorai(cscl,"standardize",false, ...
                "bonds",bonds),3);
            adjacency=[0,1,0,0;1,0,0,0;0,0,0,1;0,0,1,0];
            dummy=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(10), ...
                {"H","H","H","H"}, ...
                [.1,.1,.1;.2,.1,.1;.7,.7,.7;.8,.7,.7]);
            [largest,smallest,clusters]= ...
                kssolv.analysis.matgenlab.analysis. ...
                find_clusters(dummy,adjacency);
            testCase.verifyEqual([largest,smallest],[2,2]);
            testCase.verifyEqual(clusters,{[1,2],[3,4]});
        end
    end
end

function structure=readFixture(name)
path=fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures","+dimensionality",name);
parser=kssolv.analysis.matgenlab.io.cif.CifParser(path);
structures=parser.parse_structures(primitive=false,on_error="raise");
structure=structures{1};
end
