classdef FragmenterInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function frozenOfficialFragmentCounts(testCase)
            [fixture, oracle] = testCase.fixtureAndOracle();
            small = kssolv.analysis.matgenlab.core.Molecule.from_file( ...
                fullfile(fixture, "PC_frag1.xyz"));
            smallEdges = [0, 2; 4, 2; 2, 1; 1, 3] + 1;
            smallFragments = ...
                kssolv.analysis.matgenlab.analysis.Fragmenter( ...
                small, smallEdges, 0);
            testCase.verifyEqual(smallFragments.total_unique_fragments, ...
                oracle.pc_frag1_depth0_total);

            pc = kssolv.analysis.matgenlab.core.Molecule.from_file( ...
                fullfile(fixture, "PC.xyz"));
            pcEdges = testCase.pcEdges();
            depthTwo = kssolv.analysis.matgenlab.analysis.Fragmenter( ...
                pc, pcEdges, 2, false, false, 0);
            testCase.verifyEqual(depthTwo.total_unique_fragments, ...
                oracle.pc_depth2_total);
            testCase.verifyEqual(testCase.mapCount( ...
                depthTwo.fragments_by_level("0")), ...
                oracle.pc_depth2_levels.x0);
            testCase.verifyEqual(testCase.mapCount( ...
                depthTwo.fragments_by_level("1")), ...
                oracle.pc_depth2_levels.x1);
            serialized = depthTwo.as_dict();
            testCase.verifyEqual(serialized.x_class, "Fragmenter");
        end

        function exhaustiveAndPreviousFragments(testCase)
            [fixture, oracle] = testCase.fixtureAndOracle();
            small = kssolv.analysis.matgenlab.core.Molecule.from_file( ...
                fullfile(fixture, "PC_frag1.xyz"));
            smallFragments = ...
                kssolv.analysis.matgenlab.analysis.Fragmenter( ...
                small, [0, 2; 4, 2; 2, 1; 1, 3] + 1, 0);
            pc = kssolv.analysis.matgenlab.core.Molecule.from_file( ...
                fullfile(fixture, "PC.xyz"));
            exhaustive = ...
                kssolv.analysis.matgenlab.analysis.Fragmenter( ...
                pc, testCase.pcEdges(), 0, false);
            testCase.verifyEqual(exhaustive.total_unique_fragments, ...
                oracle.pc_depth0_total);
            previous = ...
                kssolv.analysis.matgenlab.analysis.Fragmenter( ...
                pc, testCase.pcEdges(), 0, false, false, 10000, ...
                smallFragments.unique_frag_dict);
            testCase.verifyEqual(previous.new_unique_fragments, ...
                oracle.pc_with_previous_new);
            testCase.verifyEqual(previous.total_unique_fragments, ...
                oracle.pc_with_previous_total);
        end

        function nativeRingOpening(testCase)
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                {"C", "C", "C"}, ...
                [0, 0, 0; 1.4, 0, 0; 0.7, 1.2, 0]);
            graph = kssolv.analysis.matgenlab.core.MoleculeGraph. ...
                from_edges(molecule, [1, 2; 2, 3; 1, 3]);
            opened = kssolv.analysis.matgenlab.analysis.open_ring( ...
                graph, [1, 2], 20);
            testCase.verifyEqual(opened.graph.number_of_edges(), 2);
            testCase.verifyEqual(graph.graph.number_of_edges(), 3);
            fragmenter = kssolv.analysis.matgenlab.analysis.Fragmenter( ...
                molecule, [1, 2; 2, 3; 1, 3], 1, true);
            testCase.verifyTrue(fragmenter.open_rings);
            testCase.verifyEqual(fragmenter.opt_steps, 10000);
            testCase.verifyGreaterThan( ...
                fragmenter.total_unique_fragments, 0);
        end
    end
    methods (Static, Access = private)
        function [fixture, oracle] = fixtureAndOracle()
            fixture = fullfile(fileparts(mfilename("fullpath")), ...
                "+fixtures", "+fragmenter");
            root = fileparts(fileparts(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath")))))));
            oracle = jsondecode(fileread(fullfile(root, "dev", ...
                "matgenlab", "oracles", "fragmenter_2026.5.4.json")));
        end

        function value = pcEdges()
            value = [5, 10; 5, 12; 5, 11; 5, 3; 3, 7; 3, 4; ...
                3, 0; 4, 8; 4, 9; 4, 1; 6, 1; 6, 0; 6, 2] + 1;
        end

        function count = mapCount(value)
            count = 0;
            names = value.keys;
            for index = 1:numel(names)
                count = count + numel(value(names{index}));
            end
        end
    end
end
