classdef LobsterEnvInventoryTest < matlab.unittest.TestCase
    properties
        fixtures
        oracle
    end

    methods (TestMethodSetup)
        function prepare(testCase)
            testCase.fixtures = fullfile(pwd, "+kssolv", "+analysis", ...
                "+matgenlab", "+test", "+analysis", "+fixtures", ...
                "+lobster_env");
            testCase.oracle = jsondecode(fileread(fullfile(pwd, "dev", ...
                "matgenlab", "oracles", ...
                "lobster_env_2026.5.4.json")));
        end
    end

    methods (Test)
        function frozenNeighborConditionsMatch(testCase)
            for condition = 0:6
                value = make(testCase, "mp-190", ...
                    "additional_condition", condition);
                expected = testCase.oracle.mp190_counts.( ...
                    char("x" + string(condition)));
                testCase.verifyEqual(cellfun(@numel, value.sg_list), ...
                    reshape(expected, 1, []));
            end
            cases = { ...
                "all_005", {0, .05}; ...
                "anion_cation", {1, .15}; ...
                "different_elements", {2, .15}; ...
                "same_sign_005", {5, .05}; ...
                "same_sign_100", {5, 1}; ...
                "cation_cation_005", {6, .05}};
            for index = 1:size(cases, 1)
                settings = cases{index, 2};
                value = make(testCase, "mp-353", ...
                    "additional_condition", settings{1}, ...
                    "perc_strength_icohp", settings{2});
                expected = testCase.oracle.mp353_counts.(cases{index, 1});
                testCase.verifyEqual(cellfun(@numel, value.sg_list), ...
                    reshape(expected, 1, []));
            end
        end

        function flagsValencesAndErrorsMatch(testCase)
            value = make(testCase, "mp-353", ...
                "additional_condition", 1);
            testCase.verifyTrue(value.structures_allowed);
            testCase.verifyFalse(value.molecules_allowed);
            testCase.verifyEqual(value.valences, ...
                reshape(testCase.oracle.mp353_valences, 1, []));
            anions = value.anion_types;
            testCase.verifyEqual(string(anions{1}.symbol), "O");
            deprecatedAnions = value.get_anion_types();
            testCase.verifyEqual( ...
                string(deprecatedAnions{1}.symbol), "O");
            charged = make(testCase, "mp-353", ...
                "additional_condition", 1, ...
                "valences_from_charges", true, ...
                "charge_path", fixture(testCase, ...
                    "CHARGE.lobster.mp-353.gz"), ...
                "which_charge", "Loewdin");
            testCase.verifyEqual(charged.valences, ...
                reshape(testCase.oracle.mp353_loewdin, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyError(@() make(testCase, "mp-353", ...
                "additional_condition", 10), ...
                "KSSOLV:Matgenlab:LobsterNeighbors:Condition");
            testCase.verifyError(@() value.get_nn_info( ...
                value.structure, 1, "use_weights", true), ...
                "KSSOLV:Matgenlab:LobsterNeighbors:Weights");
        end

        function integratedNeighborInformationMatches(testCase)
            value = make(testCase, "mp-190", ...
                "additional_condition", 1, ...
                "perc_strength_icohp", .3, "noise_cutoff", 0);
            actual = value.get_info_icohps_to_neighbors("isites", 0);
            expected = testCase.oracle.mp190_site0_info;
            testCase.verifyEqual(actual.total_icohp, expected.total, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(actual.n_bonds, expected.n_bonds);
            testCase.verifyEqual(actual(1), actual.total_icohp);
            [actualLabels, order] = sort(actual.labels);
            [expectedLabels, expectedOrder] = ...
                sort(string(expected.labels));
            testCase.verifyEqual(actualLabels, ...
                reshape(expectedLabels, 1, []));
            expectedValues = reshape(expected.list, 1, []);
            testCase.verifyEqual(actual.list_icohps(order), ...
                expectedValues(expectedOrder), AbsTol = 1e-12);
            between = value.get_info_icohps_between_neighbors( ...
                "isites", 2);
            expectedBetween = testCase.oracle.mp190_between_site1;
            testCase.verifyEqual(between.total_icohp, ...
                expectedBetween.total, AbsTol = 1e-12);
            testCase.verifyEqual(between.n_bonds, ...
                expectedBetween.n_bonds);
            testCase.verifyEqual(between.labels, ...
                reshape(string(expectedBetween.labels), 1, []));
        end

        function lightEnvironmentsAndSerializationMatch(testCase)
            value = make(testCase, "mp-353", ...
                "additional_condition", 1);
            environments = value.get_light_structure_environment();
            for index = 1:value.structure.num_sites
                actual = environments.coordination_environments{index}{1};
                expected = testCase.oracle.mp353_lse(index);
                testCase.verifyEqual(string(actual.ce_symbol), ...
                    string(expected.symbol));
                testCase.verifyEqual(actual.csm, expected.csm, ...
                    AbsTol = 3e-14);
            end
            testCase.verifyTrue( ...
                environments.uniquely_determines_coordination_environments);
            serialized = environments.as_dict();
            testCase.verifyEqual(serialized.x_module, ...
                "pymatgen.analysis.lobster_env");
            testCase.verifyEqual(numel(serialized.all_nbs_sites), 16);
            selected = value.get_light_structure_environment( ...
                "only_indices", [1, 6]);
            testCase.verifyEmpty( ...
                selected.coordination_environments{2}{1}.ce_symbol);
        end

        function largeEnvironmentErrorModesMatch(testCase)
            value = make(testCase, "mp-1018096", ...
                "additional_condition", 0, ...
                "adapt_extremum_to_add_cond", true, ...
                "valences_from_charges", true, ...
                "charge_path", fixture(testCase, ...
                    "CHARGE.lobster.mp-1018096.gz"));
            testCase.verifyEqual(cellfun(@numel, value.sg_list), ...
                reshape(testCase.oracle.large_environment_counts, 1, []));
            testCase.verifyError(@() ...
                value.get_light_structure_environment( ...
                "on_error", "raise"), ...
                "KSSOLV:Matgenlab:LobsterNeighbors:LargeCN");
            warning("off", ...
                "KSSOLV:Matgenlab:LobsterNeighbors:LargeCN");
            cleanup = onCleanup(@() warning("on", ...
                "KSSOLV:Matgenlab:LobsterNeighbors:LargeCN"));
            ignored = value.get_light_structure_environment( ...
                "on_error", "ignore");
            testCase.verifyEqual(string(ignored. ...
                coordination_environments{1}{1}.ce_symbol), "18");
            clear cleanup
        end

        function additionalPopulationsAndCoopsMatch(testCase)
            value = kssolv.analysis.matgenlab.analysis. ...
                LobsterNeighbors.from_files( ...
                "structure_path", fixture(testCase, "CONTCAR.NaCl.gz"), ...
                "icoxxlist_path", fixture(testCase, ...
                    "ICOHPLIST.lobster.NaCl.gz"), ...
                "charge_path", fixture(testCase, ...
                    "CHARGE.lobster.NaCl.gz"), ...
                "valences_from_charges", true, ...
                "blist_sg1_path", fixture(testCase, ...
                    "ICOBILIST.lobster.NaCl.gz"), ...
                "blist_sg2_path", fixture(testCase, ...
                    "ICOOPLIST.lobster.NaCl.gz"), ...
                "add_additional_data_sg", true, ...
                "id_blist_sg1", "icobi", ...
                "id_blist_sg2", "icoop", ...
                "additional_condition", 1);
            edge = value.sg_list{1}{1}.edge_properties;
            testCase.verifyEqual(edge.bond_label, "21");
            testCase.verifyEqual(edge.ICOHP, -.59138, AbsTol = 1e-12);
            testCase.verifyEqual(edge.ICOBI, .08682, AbsTol = 1e-12);
            testCase.verifyEqual(edge.ICOOP, .03007, AbsTol = 1e-12);
            coop = kssolv.analysis.matgenlab.analysis. ...
                LobsterNeighbors.from_files( ...
                "structure_path", fixture(testCase, "CONTCAR.NaCl.gz"), ...
                "icoxxlist_path", fixture(testCase, ...
                    "ICOOPLIST.lobster.NaCl.gz"), ...
                "are_coops", true, "additional_condition", 1, ...
                "noise_cutoff", []);
            testCase.verifyEqual(numel(coop.sg_list{1}), 6);
        end

        function frozenCohpSumAndPlotMatch(testCase)
            value = make(testCase, "mp-190", ...
                "additional_condition", 1);
            [label, curve] = value.get_info_cohps_to_neighbors( ...
                "path_to_cohpcar", fixture(testCase, ...
                    "COHPCAR.lobster.mp-190.gz"), ...
                "isites", 0, "only_bonds_to", "O", ...
                "per_bond", false);
            expected = testCase.oracle.mp190_cohp;
            testCase.verifyEqual(label, string(expected.label));
            testCase.verifyEqual(numel(curve.energies), ...
                expected.energy_count);
            testCase.verifyEqual(curve.icohp.up(701), ...
                expected.icohp_up_700, AbsTol = 1e-12);
            testCase.verifyEqual(value.get_plot_label( ...
                {["Re1", "O2"], ["Re1", "O3"], ["Si1", "O4"]}, ...
                false), "2 x O-Re, 1 x O-Si");
            testCase.verifyWarning(@() ...
                kssolv.analysis.matgenlab.analysis.check_ICOHPs( ...
                [2, 2.001], [-1, -2], {[1, 0, 0], [-1, 0, 0]}), ...
                "KSSOLV:Matgenlab:LobsterNeighbors:AmbiguousICOHP");
        end
    end
end

function value = make(testCase, stem, varargin)
value = kssolv.analysis.matgenlab.analysis. ...
    LobsterNeighbors.from_files( ...
    "structure_path", fixture(testCase, "CONTCAR." + stem + ".gz"), ...
    "icoxxlist_path", fixture(testCase, ...
        "ICOHPLIST.lobster." + stem + ".gz"), varargin{:});
end

function value = fixture(testCase, name)
value = fullfile(testCase.fixtures, name);
end
