classdef PhaseDiagramTest < matlab.unittest.TestCase
    methods (Test)
        function officialFixtureHullAndDecomposition(testCase)
            path=phaseFixture("pd_entries_test.csv");
            testCase.assumeTrue(isfile(path),"Official phase-diagram fixture unavailable.");
            entries=kssolv.analysis.matgenlab.core.EntrySet.from_csv(path);
            pd=kssolv.analysis.matgenlab.analysis.PhaseDiagram(entries);
            testCase.verifyEqual(length(entries),490);
            testCase.verifyEqual(numel(pd.qhull_entries),143);
            testCase.verifyEqual(numel(pd.facets),12);
            testCase.verifyEqual(numel(pd.stable_entries),11);
            decomposition=pd.get_decomposition( ...
                kssolv.analysis.matgenlab.core.Composition("Li3Fe7O11"));
            formulas=cellfun(@(x)x.formula,decomposition(:,1));
            expected=containers.Map(["Fe2 O2","Li1 Fe1 O2","Fe6 O8"], ...
                [2/21,4/7,1/3]);
            for ii=1:numel(formulas)
                testCase.verifyEqual(decomposition{ii,2},expected(formulas(ii)),AbsTol=1e-12);
            end
            target=pd.stable_entries{find(cellfun(@(x) ...
                x.reduced_formula=="Li5FeO4",pd.stable_entries),1)};
            testCase.verifyEqual(pd.get_form_energy(target), ...
                -164.8117344866667,AbsTol=1e-8);
        end

        function grandCompoundAndMSON(testCase)
            path=phaseFixture("pd_entries_test.csv");
            testCase.assumeTrue(isfile(path));
            entries=kssolv.analysis.matgenlab.core.EntrySet.from_csv(path);
            grand=kssolv.analysis.matgenlab.analysis. ...
                GrandPotentialPhaseDiagram(entries,{"O",-5});
            testCase.verifyEqual(numel(grand.stable_entries),5);
            formulas=sort(cellfun(@(x)x.original_entry.reduced_formula,grand.stable_entries));
            testCase.verifyEqual(formulas,sort( ...
                ["Li5FeO4","Li2FeO3","LiFeO2","Fe2O3","Li2O2"]));
            compound=kssolv.analysis.matgenlab.analysis.CompoundPhaseDiagram( ...
                entries,{kssolv.analysis.matgenlab.core.Composition("Li2O"), ...
                kssolv.analysis.matgenlab.core.Composition("Fe2O3")});
            testCase.verifyEqual(numel(compound.stable_entries),4);
            restored=kssolv.analysis.matgenlab.analysis. ...
                CompoundPhaseDiagram.from_dict(compound.as_dict());
            testCase.verifyEqual(sort(cellfun(@(x)x.name,restored.stable_entries)), ...
                sort(cellfun(@(x)x.name,compound.stable_entries)));
        end

        function patchedAndReactionDiagram(testCase)
            path=phaseFixture("reaction_entries_test.csv");
            testCase.assumeTrue(isfile(path));
            entries=kssolv.analysis.matgenlab.core.EntrySet.from_csv(path);
            entries.add(kssolv.analysis.matgenlab.analysis.PDEntry("He",-1.23));
            patched=kssolv.analysis.matgenlab.analysis.PatchedPhaseDiagram(entries);
            full=kssolv.analysis.matgenlab.analysis.PhaseDiagram(entries);
            testCase.verifyEqual(length(patched),4);
            testCase.verifyEqual(numel(patched.stable_entries),numel(full.stable_entries));
            restored=kssolv.analysis.matgenlab.analysis. ...
                PatchedPhaseDiagram.from_dict(patched.as_dict());
            testCase.verifyEqual(length(restored),4);

            raw=entries.entries(~cellfun(@(x)x.reduced_formula=="He",entries.entries));
            first=raw{find(cellfun(@(x)x.reduced_formula=="VPO5",raw),1)};
            second=raw{find(cellfun(@(x)x.reduced_formula=="H4(CO)3",raw),1)};
            diagram=kssolv.analysis.matgenlab.analysis.ReactionDiagram( ...
                first,second,raw(3:end));
            testCase.verifyEqual(numel(diagram.rxn_entries),9);
            testCase.verifyClass(diagram.get_compound_pd(), ...
                "kssolv.analysis.matgenlab.analysis.CompoundPhaseDiagram");
        end

        function plotDataAndCoordinateUtilities(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            testCase.verifyEqual(triangular_coord([.5,.5]), ...
                [.75,sqrt(3)/4],AbsTol=1e-8);
            testCase.verifyEqual(tet_coord([.5,.5,.5]), ...
                [1,sqrt(3)/3,sqrt(6)/6],AbsTol=1e-8);
            path=phaseFixture("pd_entries_test.csv");
            testCase.assumeTrue(isfile(path));
            pd=PhaseDiagram(kssolv.analysis.matgenlab.core.EntrySet.from_csv(path));
            plotter=PDPlotter(pd,"backend","matplotlib");
            [lines,stable,unstable]=plotter.get_pd_plot_data();
            testCase.verifyNumElements(lines,22);
            testCase.verifyEqual(size(stable,1),11);
            testCase.verifyEqual(size(unstable,1),479);
            axesHandle=plotter.get_plot();
            testCase.verifyTrue(isgraphics(axesHandle,"axes"));
            close(axesHandle.Parent);
        end

        function chemicalPotentialGeometryUtilities(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            points=[-25,-6.5961471,-7.11535414; ...
                -25,-6.74159386,-6.96990738; ...
                -4.07706195,-6.74159386,-6.96990738; ...
                -3.93161519,-6.5961471,-7.11535414];
            scores=simple_pca(points,2);
            expected=[10.49782722,.10320265; ...
                10.4978342,-.10249014; ...
                -10.42510384,-.10320018; ...
                -10.57055758,.10248767];
            testCase.verifyEqual(scores,expected,AbsTol=1e-7);
            vertices=[3.30046498,.1707431; ...
                -.63480672,.21578376; ...
                -1.37717499,.13347465; ...
                -1.61148314,.0409329; ...
                -1.77880975,-.25825963; ...
                2.10180962,-.30267477];
            testCase.verifyEqual(get_centroid_2d(vertices), ...
                [-.00069433,-.00886174],AbsTol=1e-6);
            testCase.verifyEqual(get_2d_orthonormal_vector([1,1;2,2]), ...
                [.70710678,.70710678],AbsTol=1e-8);
            testCase.verifyEqual(get_2d_orthonormal_vector([-2,-5;-4,6]), ...
                [.98386991,.17888544],AbsTol=1e-8);
        end

        function officialChemicalPotentialDomains(testCase)
            path=phaseFixture("pd_entries_test.csv");
            testCase.assumeTrue(isfile(path));
            entries=kssolv.analysis.matgenlab.core.EntrySet.from_csv(path);
            diagram=kssolv.analysis.matgenlab.analysis.ChemicalPotentialDiagram( ...
                entries,"default_min_limit",-25,"formal_chempots",false);
            testCase.verifyEqual(size(diagram.hyperplanes,1),143);
            testCase.verifyEqual(size(diagram.domains,1),11);
            row=find(string(diagram.domains(:,1))=="FeO");
            actual=sortrows(round(diagram.domains{row,2},6));
            expected=sortrows([-25,-6.741594,-6.969907; ...
                -25,-6.596147,-7.115354; ...
                -4.077062,-6.741594,-6.969907; ...
                -3.931615,-6.596147,-7.115354]);
            testCase.verifyEqual(actual,expected,AbsTol=1e-6);
        end

        function interfacialAndGrandInterfacial(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            import kssolv.analysis.matgenlab.core.*
            entries={ComputedEntry("Li",0),ComputedEntry("Mn",0), ...
                ComputedEntry("O2",0),ComputedEntry("MnO2",-10), ...
                ComputedEntry("Mn2O4",-60),ComputedEntry("MnO3",20), ...
                ComputedEntry("Li2O",-10),ComputedEntry("Li2O2",-8), ...
                ComputedEntry("LiMnO2",-30)};
            pd=PhaseDiagram(entries);
            interfacial=InterfacialReactivity(Composition("O2"), ...
                Composition("Mn"),pd,"norm",false,"use_hull_energy",false);
            kinks=interfacial.get_kinks();
            testCase.verifyEqual([kinks.ratio],[0,.5,1],AbsTol=1e-8);
            testCase.verifyEqual([kinks.energy],[0,-15,0],AbsTol=1e-8);
            testCase.verifyEqual(interfacial.minimum,[.5,-15],AbsTol=1e-8);
            testCase.verifySize(interfacial.labels,[3,2]);
            testCase.verifyNotEmpty(interfacial.products);
            testCase.verifyEqual(height(interfacial.get_dataframe()),3);
            axesHandle=interfacial.plot();
            testCase.verifyTrue(isgraphics(axesHandle,"axes"));
            close(axesHandle.Parent);
            restored=InterfacialReactivity.from_dict(interfacial.as_dict());
            testCase.verifyEqual(restored.minimum,interfacial.minimum,AbsTol=1e-8);
            grand=GrandPotentialPhaseDiagram(entries,{"Li",-3});
            grandInterface=GrandPotentialInterfacialReactivity( ...
                Composition("Li2O"),Composition("Mn"),grand,pd, ...
                "norm",false,"include_no_mixing_energy",true, ...
                "use_hull_energy",false);
            testCase.verifyEqual(grandInterface.get_energy(2/3), ...
                -22/3,AbsTol=1e-8);
            testCase.verifyEqual(grandInterface.get_grand_potential( ...
                Composition("LiMnO2")),-27,AbsTol=1e-8);
            testCase.verifySize( ...
                grandInterface.get_no_mixing_energy(),[2,2]);
            restoredGrand=GrandPotentialInterfacialReactivity. ...
                from_dict(grandInterface.as_dict());
            testCase.verifyEqual(restoredGrand.get_energy(2/3), ...
                grandInterface.get_energy(2/3),AbsTol=1e-8);
            testCase.verifyEqual(InterfacialReactivity. ...
                get_chempot_correction("O",1000,1e-25),-3.8,AbsTol=.01);
        end

        function frozenPhaseDiagramOracle(testCase)
            testCase.assumeTrue(kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            entry=@(formula,energy)struct(x_module="pymatgen.analysis.phase_diagram", ...
                x_class="PDEntry",composition=formula,energy=energy);
            composition=struct("x_module","pymatgen.core.composition", ...
                "x_class","Composition","Li",1,"O",1);
            request=struct(module="pymatgen.analysis.phase_diagram", ...
                symbol="PhaseDiagram",construct=struct(args={{ ...
                {entry("Li",0),entry("O2",0),entry("Li2O",-5),entry("LiO2",-4)}}}), ...
                operations={{struct(kind="call",name="get_hull_energy_per_atom", ...
                args={{composition}}),struct(kind="call", ...
                name="get_transition_chempots",args={{struct( ...
                "x_module","pymatgen.core.periodic_table", ...
                "x_class","Element","element","Li")}})}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            entries={kssolv.analysis.matgenlab.analysis.PDEntry("Li",0), ...
                kssolv.analysis.matgenlab.analysis.PDEntry("O2",0), ...
                kssolv.analysis.matgenlab.analysis.PDEntry("Li2O",-5), ...
                kssolv.analysis.matgenlab.analysis.PDEntry("LiO2",-4)};
            pd=kssolv.analysis.matgenlab.analysis.PhaseDiagram(entries);
            testCase.verifyEqual(pd.get_hull_energy_per_atom( ...
                kssolv.analysis.matgenlab.core.Composition("LiO")), ...
                reference.results{1},AbsTol=1e-12);
            testCase.verifyEqual(pd.get_transition_chempots("Li"), ...
                reshape(reference.results{2},1,[]),AbsTol=1e-12);
        end

        function frozenChemicalPotentialOracle(testCase)
            testCase.assumeTrue(kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            import kssolv.analysis.matgenlab.analysis.*
            entries={PDEntry("Li",0),PDEntry("O2",0), ...
                PDEntry("Li2O",-5),PDEntry("LiO2",-4)};
            encoded=cellfun(@(entry)entry.as_dict(),entries, ...
                "UniformOutput",false);
            request=struct(module="pymatgen.analysis.chempot_diagram", ...
                symbol="ChemicalPotentialDiagram",construct=struct( ...
                args={{encoded}},kwargs=struct(default_min_limit=-10, ...
                formal_chempots=false)),operations={{struct( ...
                kind="get",name="hyperplanes")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            diagram=ChemicalPotentialDiagram(entries, ...
                "default_min_limit",-10,"formal_chempots",false);
            testCase.verifyEqual(sortrows(diagram.hyperplanes), ...
                sortrows(squeeze(reference.results)),AbsTol=1e-12);
        end

        function frozenInterfacialOracle(testCase)
            testCase.assumeTrue(interfaceOracleAvailable());
            import kssolv.analysis.matgenlab.analysis.*
            import kssolv.analysis.matgenlab.core.*
            entries={ComputedEntry("Li",0),ComputedEntry("Mn",0), ...
                ComputedEntry("O2",0),ComputedEntry("MnO2",-10), ...
                ComputedEntry("Mn2O4",-60),ComputedEntry("MnO3",20), ...
                ComputedEntry("Li2O",-10),ComputedEntry("Li2O2",-8), ...
                ComputedEntry("LiMnO2",-30)};
            pd=PhaseDiagram(entries);
            interfacial=InterfacialReactivity(Composition("O2"), ...
                Composition("Mn"),pd,"norm",false,"use_hull_energy",false);
            encoded=pd.as_dict();
            encoded=rmfield(encoded,"computed_data");
            c1=struct(x_module="pymatgen.core.composition", ...
                x_class="Composition",O=2);
            c2=struct(x_module="pymatgen.core.composition", ...
                x_class="Composition",Mn=1);
            request=struct(module="pymatgen.analysis.interface_reactions", ...
                symbol="InterfacialReactivity",construct=struct( ...
                args={{c1,c2,encoded}},kwargs=struct(norm=false, ...
                use_hull_energy=false)),operations={{ ...
                struct(kind="get",name="minimum"), ...
                struct(kind="call",name="get_critical_original_kink_ratio")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            testCase.verifyEqual(interfacial.minimum, ...
                reshape(reference.results{1},1,[]),AbsTol=1e-12);
            testCase.verifyEqual( ...
                interfacial.get_critical_original_kink_ratio(), ...
                reshape(reference.results{2},1,[]),AbsTol=1e-12);
        end
    end
end

function path=phaseFixture(name)
roots=[string(getenv("MATGENLAB_PYMATGEN_CORE")), ...
    "/tmp/matgenlab-pymatgen-core-v2026.7.24"];
path="";
for root=roots
    if strlength(root)==0,continue,end
    candidate=fullfile(root,"test-files","analysis",name);
    if isfile(candidate),path=candidate;return,end
end
end

function available=interfaceOracleAvailable()
python=kssolv.analysis.matgenlab.test.support.PymatgenOracle.python();
command=sprintf('"%s" -c "import pymatgen.analysis.interface_reactions"', ...
    python);
available=system(command)==0;
end
