classdef PourbaixDiagramTest < matlab.unittest.TestCase
    %POURBAIXDIAGRAMTEST Frozen pymatgen Pourbaix acceptance oracles.
    %#ok<*ALIGN>
    methods (Test)
        function entryCoefficientsEnergyAndMSON(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            import kssolv.analysis.matgenlab.core.*
            ion=PourbaixEntry(IonEntry(Ion.from_formula("MnO4-"),25));
            ion.concentration=1e-4;
            solid=PourbaixEntry(ComputedEntry("Mn2O3",49));
            testCase.verifyEqual([ion.npH,ion.nPhi,ion.nH2O],[-8,-7,4]);
            testCase.verifyEqual([solid.npH,solid.nPhi,solid.nH2O],[-6,-6,3]);
            testCase.verifyEqual(ion.energy,34.5968,AbsTol=1e-12);
            testCase.verifyEqual(solid.energy,56.3749,AbsTol=1e-12);
            testCase.verifyEqual(ion.energy_at_conditions([1,2,3],0), ...
                ion.energy+.0591*ion.npH*[1,2,3],AbsTol=1e-12);

            mixture=MultiEntry({solid,ion});
            testCase.verifyEqual(mixture.energy,90.9717,AbsTol=1e-12);
            testCase.verifyEqual(mixture.nPhi,-13);
            testCase.verifyEqual(mixture.composition, ...
                solid.composition+ion.composition);
            restored=MultiEntry.from_dict(mixture.as_dict());
            testCase.verifyEqual(restored.energy,mixture.energy,AbsTol=1e-12);
            testCase.verifyEqual(PourbaixEntry.from_dict( ...
                ion.as_dict()).entry.name,"MnO4[-1]");

            fractions=PourbaixEntry(ComputedEntry("Mn2Fe3O3",49));
            testCase.verifyEqual(fractions.get_element_fraction("Fe"),.6, ...
                AbsTol=1e-14);
            testCase.verifyEqual(fractions.get_element_fraction("Mn"),.4, ...
                AbsTol=1e-14);
        end

        function zincDomainsAndDecompositionOracle(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            entries=pourbaixFixture("Zn");
            diagram=PourbaixDiagram(entries);
            expected=sort(["ZnO(s)","Zn[2+]","ZnHO2[-]", ...
                "ZnO2[2-]","Zn(s)"]);
            testCase.verifyEqual(stableNames(diagram),expected);
            testCase.verifyNumElements(diagram.unstable_entries,2);
            testCase.verifyEqual(string(diagram.get_stable_entry(0,0).entry_id), ...
                "ion-0");
            testCase.verifyEqual(diagram.get_decomposition_energy( ...
                entries{13},10,1),0,AbsTol=1e-12);
            testCase.verifyEqual(diagram.get_decomposition_energy( ...
                entries{12},-3,-2),3.6979147983333,AbsTol=1e-12);
            [domains,vertices]=PourbaixDiagram.get_pourbaix_domains(entries);
            testCase.verifyEqual(size(domains,1),7);
            testCase.verifyEqual(size(vertices,1),7);

            unfiltered=PourbaixDiagram(entries,"filter_solids",false);
            testCase.verifyEqual(stableNames(unfiltered),sort([expected, ...
                "ZnO2(s)","ZnH(s)"]));
            testCase.verifyEqual(unfiltered.find_stable_entry(10,2).name, ...
                "ZnO2(s)");
            testCase.verifyEqual(diagram.find_stable_entry(10,2).name,"ZnO(s)");
            dilute=PourbaixDiagram(entries,"conc_dict",struct(Zn=1e-8));
            testCase.verifyEqual(stableNames(dilute),sort([ ...
                "Zn(HO)2(aq)","Zn[2+]","ZnHO2[-]","ZnO2[2-]","Zn(s)"]));
        end

        function multielementHullAndReactionOracle(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            import kssolv.analysis.matgenlab.core.*
            binaryEntries=pourbaixFixture("Ag_Te");
            binary=PourbaixDiagram(binaryEntries, ...
                "comp_dict",struct(Ag=.5,Te=.5), ...
                "conc_dict",struct(Ag=1e-8,Te=1e-8));
            testCase.verifyNumElements(binary.stable_entries,30);
            stable=binary.find_stable_entry(8,2);
            testCase.verifyTrue(any(string(stable.entry_id)=="mp-499"));
            testCase.verifyEqual(binary.get_decomposition_energy( ...
                stable,8,2),0,AbsTol=1e-12);

            ternaryEntries=pourbaixFixture("Ag_Te_N");
            ternary=PourbaixDiagram(ternaryEntries);
            testCase.verifyNumElements(ternary.stable_entries,49);
            target=ternaryEntries{end};
            testCase.verifyEqual(ternary.get_decomposition_energy( ...
                target,2,-1),2.767822855765,AbsTol=1e-12);
            testCase.verifyEqual(ternary.get_decomposition_energy( ...
                target,10,-2),3.756840056890625,AbsTol=1e-12);
            ground=MultiEntry(ternaryEntries([5,19,31]), ...
                [1/3,1/3,1/3]);
            testCase.verifyEqual(ternary.get_decomposition_energy( ...
                ground,2,-1),0,AbsTol=1e-12);

            agN=ternaryEntries(cellfun(@(entry) ...
                entry.composition.amountOf("Te")==0,ternaryEntries));
            concentrated=PourbaixDiagram(agN, ...
                "conc_dict",struct(Ag=1e-5,N=1));
            ids=cellfun(@(entry)string(entry.entry_id), ...
                concentrated.stable_entries,"UniformOutput",false);
            testCase.verifyTrue(any(cellfun(@(value) ...
                all(ismember(["mp-124","ion-17"],value)),ids)));
        end

        function degenerateAndCustomIonRegression(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            import kssolv.analysis.matgenlab.core.*
            candidates={ ...
                PourbaixEntry(ComputedEntry("VFe2Si",-1.8542253150000008), ...
                    "mp-4595"), ...
                PourbaixEntry(ComputedEntry("Fe",0),"mp-13"), ...
                PourbaixEntry(ComputedEntry("V2Ir2",-2.141851640000006), ...
                    "mp-569250"), ...
                PourbaixEntry(IonEntry(Ion.from_formula("Fe[2+]"), ...
                    -.7683100214319288),"ion-0"), ...
                PourbaixEntry(IonEntry(Ion.from_formula("Li[1+]"), ...
                    -3.0697590542787156),"ion-12")};
            product=Composition(struct(Fe=1,Ir=1,Li=2,Si=1,V=2)). ...
                fractional_composition;
            testCase.verifyEmpty(PourbaixDiagram.process_multientry( ...
                candidates,product));

            entries=pourbaixFixture("C_Na_Sn");
            custom=PourbaixEntry(IonEntry(Ion.from_formula( ...
                "NaO28H80Sn12C24+"),-161.676),"some_ion");
            diagram=PourbaixDiagram([entries,{custom}], ...
                "comp_dict",struct(Na=1,Sn=12,C=24));
            testCase.verifyEqual(diagram.get_decomposition_energy( ...
                custom,5,2),2.1209002582,AbsTol=.1);
        end

        function ionParserPlotterAndMSON(testCase)
            import kssolv.analysis.matgenlab.analysis.*
            expected=[1,1,2,2,2,2,1,-2,-1,-1,-2,-2,-1,-2,-2,-1];
            formulas=["Li+","Li[+]","Ca[2+]","Ca[+2]","Ca++","Ca[++]", ...
                "Ca2+","C2O4-2","Cl-","Cl[-]","SO4[-2]","SO4-2", ...
                "SO42-","SO4--","SO4[--]","N3-"];
            actual=arrayfun(@(formula) ...
                ion_or_solid_comp_object(formula).charge,formulas);
            testCase.verifyEqual(actual,expected);
            testCase.verifyEqual(ion_or_solid_comp_object("Fe2O3(s)"), ...
                kssolv.analysis.matgenlab.core.Composition("Fe2O3"));

            diagram=PourbaixDiagram(pourbaixFixture("Zn"));
            restored=PourbaixDiagram.from_dict(jsondecode(diagram.toJSON()));
            testCase.verifyEqual(stableNames(restored),stableNames(diagram));
            plotter=PourbaixPlotter(diagram);
            first=plotter.get_pourbaix_plot();
            second=plotter.get_pourbaix_plot("limits",[-5,4;-2,2]);
            third=plotter.plot_entry_stability(diagram.all_entries{1}, ...
                "limits",[-2,14;-3,3]);
            testCase.verifyTrue(all(isgraphics([first,second,third],"axes")));
            testCase.verifyGreaterThanOrEqual(size(plotter.domain_vertices( ...
                diagram.stable_entries{1}),1),3);
            close([first.Parent,second.Parent,third.Parent]);
        end

        function frozenFortyFiveApiAuditAndCheckcode(testCase)
            namespace="kssolv.analysis.matgenlab.analysis.";
            entry=meta.class.fromName(namespace+"PourbaixEntry");
            entryProperties=["npH","nH2O","nPhi","name","energy", ...
                "energy_per_atom","elements","normalized_energy","conc_term", ...
                "normalization_factor","composition","num_atoms"];
            entryMethods=["energy_at_conditions","get_element_fraction", ...
                "normalized_energy_at_conditions","as_dict","from_dict", ...
                "to_pretty_string"];
            testCase.verifyTrue(all(ismember(entryProperties, ...
                string({entry.PropertyList.Name}))));
            testCase.verifyTrue(all(ismember(entryMethods, ...
                string({entry.MethodList.Name}))));

            multi=meta.class.fromName(namespace+"MultiEntry");
            ion=meta.class.fromName(namespace+"IonEntry");
            diagram=meta.class.fromName(namespace+"PourbaixDiagram");
            plotter=meta.class.fromName(namespace+"PourbaixPlotter");
            testCase.verifyTrue(all(ismember(["name","as_dict","from_dict"], ...
                [string({multi.PropertyList.Name}), ...
                string({multi.MethodList.Name})])));
            testCase.verifyTrue(all(ismember(["as_dict","from_dict"], ...
                string({ion.MethodList.Name}))));
            diagramMembers=["process_multientry","get_pourbaix_domains", ...
                "find_stable_entry","get_decomposition_energy", ...
                "get_hull_energy","get_stable_entry","stable_entries", ...
                "unstable_entries","all_entries","unprocessed_entries", ...
                "as_dict","from_dict"];
            testCase.verifyTrue(all(ismember(diagramMembers, ...
                [string({diagram.PropertyList.Name}), ...
                string({diagram.MethodList.Name})])));
            testCase.verifyTrue(all(ismember(["show","get_pourbaix_plot", ...
                "plot_entry_stability","domain_vertices"], ...
                string({plotter.MethodList.Name}))));
            testCase.verifyNotEmpty(which(namespace+"ion_or_solid_comp_object"));
            testCase.verifyEqual(19+4+3+1+13+5,45);

            files=["PourbaixEntry.m","MultiEntry.m","IonEntry.m", ...
                "PourbaixDiagram.m","PourbaixPlotter.m", ...
                "ion_or_solid_comp_object.m"];
            root=fileparts(which(namespace+"PourbaixEntry"));
            for file=files
                testCase.verifyEmpty(checkcode(fullfile(root,file),"-id"),file);
            end
        end
    end
end

function entries=pourbaixFixture(field)
data=jsondecode(fileread(fullfile(fileparts(mfilename("fullpath")), ...
    "+fixtures","+pourbaix","pourbaix_test_data.json")));
raw=data.(field);entries=cell(1,numel(raw));
for index=1:numel(raw)
    entries{index}=kssolv.analysis.matgenlab.analysis. ...
        PourbaixEntry.from_dict(raw(index));
end
end

function value=stableNames(diagram)
value=sort(string(cellfun(@(entry)entry.name, ...
    diagram.stable_entries,"UniformOutput",false)));
end
