classdef SurfaceAnalysisInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function officialAdsorptionThermodynamicsMatch(testCase)
            [analyzers,adsorbate]=oxygenAnalyzers();
            cases={ ...
                "Ni",[1,0,0],3.999997719057772, ...
                    -5.974739886828379,0.016850001417724858, ...
                    -0.02032305430046445; ...
                "Ni",[1,1,1],3.9983696241768216, ...
                    -5.809246189180817,-0.015987252837530885, ...
                    -0.023467041742257062; ...
                "Pt",[1,1,1],4.0000020116831, ...
                    -4.508212135271725,0.008366102097000283, ...
                    -0.018253586607084236; ...
                "Rh",[1,0,0],4, ...
                    -5.440490009999996,0.05769410651804696, ...
                    -0.016907295048884708};
            for index=1:size(cases,1)
                analyzer=analyzers.(cases{index,1});
                group=facetGroup(analyzer,cases{index,2});
                clean=group.clean{1};ads=group.ads{1}{1};
                testCase.verifyEqual(ads.get_unit_primitive_area, ...
                    cases{index,3},AbsTol=2e-12);
                testCase.verifyEqual(ads.get_monolayer, ...
                    1/cases{index,3},AbsTol=2e-12);
                testCase.verifyEqual(ads.Nads_in_slab,1);
                testCase.verifyEqual(ads.Nsurfs_ads_in_slab,1);
                testCase.verifyEqual(ads.gibbs_binding_energy(), ...
                    cases{index,4},AbsTol=2e-12);
                testCase.verifyEqual(ads.gibbs_binding_energy(true), ...
                    cases{index,4},AbsTol=2e-12);
                expression=ads.surface_energy(analyzer.ucell_entry);
                testCase.verifyEqual(expression.constant, ...
                    cases{index,5},AbsTol=2e-12);
                testCase.verifyEqual(expression.coefficients.delu_O, ...
                    cases{index,6},AbsTol=2e-12);
                testCase.verifyEqual(clean.create_slab_label, ...
                    sprintf("(%d, %d, %d) %s1",cases{index,2}, ...
                    cases{index,1}));
                testCase.verifyEqual(ads.create_slab_label, ...
                    sprintf("(%d, %d, %d) %s1+O, 0.250 ML", ...
                    cases{index,2},cases{index,1}));
                testCase.verifyEqual(ads.cleaned_up_slab.composition. ...
                    reduced_composition, ...
                    clean.composition.reduced_composition);
                testCase.verifyEqual(ads.gibbs_binding_energy(), ...
                    (ads.energy-ads.get_unit_primitive_area*clean.energy)- ...
                    adsorbate.energy_per_atom,AbsTol=2e-12);
            end
        end

        function officialSurfaceStabilityMatches(testCase)
            [analyzers,~]=oxygenAnalyzers();
            expected=struct( ...
                "Ni_100",[.13827389280017743,.13827389280017743, ...
                    .03717305571818931,.016850001417724858], ...
                "Ni_111",[.11945397619021669,.11945397619021669, ...
                    .007479788904726177,-.015987252837530885], ...
                "Pt_111",[.09065803211215662,.09065803211215662, ...
                    .02661968870408452,.008366102097000283], ...
                "Rh_100",[.14967807632762642,.14967807632762642, ...
                    .07460140156693167,.05769410651804696]);
            names=fieldnames(expected);potentials=[-7,-6,-1,0];
            for index=1:numel(names)
                tokens=split(string(names{index}),"_");
                analyzer=analyzers.(tokens(1));
                hkl=double(char(tokens(2)))-double('0');
                for point=1:numel(potentials)
                    [entry,gamma]=analyzer.get_stable_entry_at_u( ...
                        hkl,"delu_dict", ...
                        struct("delu_O",potentials(point)));
                    testCase.verifyEqual(gamma, ...
                        expected.(names{index})(point),AbsTol=2e-12);
                    if point<=2
                        testCase.verifyFalse(contains(string(entry.label),"_O"));
                    else
                        testCase.verifyTrue(contains(string(entry.label),"_O"));
                    end
                end
            end
            ranges=analyzers.Rh.stable_u_range_dict( ...
                [-1,0],"delu_O","no_doped",false);
            testCase.verifyNotEmpty(ranges);
            testCase.verifyGreaterThan(numel(ranges(1).range),1);
            colors=analyzers.Ni.color_palette_dict();
            testCase.verifyEqual(numel(colors),4);
            variables=analyzers.Ni.set_all_variables(struct(),-2);
            testCase.verifyEqual(variables.delu_O,-2);
            testCase.verifyEqual(variables.constant,1);
        end

        function officialCuSurfaceAndWulffMatch(testCase)
            [plotter,entries]=entryAnalyzer( ...
                "Cu_entries.txt","Cu");
            testCase.verifyEqual(numel(entries),13);
            expected=[ ...
                1,0,0,.09160536592770563; ...
                1,1,0,.09795561781949647; ...
                1,1,1,.08231163450664702; ...
                2,1,0,.10066633799430091; ...
                2,1,1,.10211782288825644; ...
                2,2,1,.09267191947498676; ...
                3,1,0,.0998493240061542; ...
                3,1,1,.09662342231048937; ...
                3,2,0,.10135660324867501; ...
                3,2,1,.09892272009042058; ...
                3,2,2,.09084551325809342; ...
                3,3,1,.09498994685105133; ...
                3,3,2,.08985039953429563];
            energies=zeros(size(expected,1),1);
            for index=1:size(expected,1)
                group=facetGroup(plotter,expected(index,1:3));
                energies(index)=group.clean{1}.surface_energy( ...
                    plotter.ucell_entry);
            end
            testCase.verifyEqual(energies,expected(:,4),AbsTol=3e-12);
            [minimum,index]=min(energies); %#ok<ASGLU>
            testCase.verifyEqual(expected(index,1:3),[1,1,1]);
            shape=plotter.wulff_from_chempot();
            testCase.verifyEqual(shape.weighted_surface_energy, ...
                .08674904724380164,AbsTol=3e-12);
            testCase.verifyEqual(shape.volume, ...
                .0033091706085177745,AbsTol=3e-13);
            testCase.verifyEqual(shape.effective_radius, ...
                .09244359999153719,AbsTol=3e-12);
            stable=[3,1,0;3,1,1;2,1,0;2,2,1;1,0,0;1,1,1;3,3,1];
            for index=1:numel(shape.area_fraction_dict)
                item=shape.area_fraction_dict(index);
                if any(all(stable==item.miller,2))
                    testCase.verifyGreaterThan(item.value,0);
                else
                    testCase.verifyEqual(item.value,0,AbsTol=1e-13);
                end
            end
        end

        function nonStoichiometricAndSerializationMatch(testCase)
            [plotter,entries]=entryAnalyzer( ...
                "MgO_slab_entries.txt","MgO",{"Mg"});
            testCase.verifyEqual(numel(entries),2);
            for index=1:numel(entries)
                expression=entries{index}.surface_energy( ...
                    plotter.ucell_entry,plotter.ref_entries);
                testCase.verifyTrue(isfield(expression.coefficients,"delu_Mg"));
                testCase.verifyFalse(isfield(expression.coefficients,"delu_O"));
            end
            source=entries{1};
            restored=kssolv.analysis.matgenlab.analysis.SlabEntry. ...
                from_dict(source.as_dict());
            converted=kssolv.analysis.matgenlab.analysis.SlabEntry. ...
                from_computed_structure_entry(source,[1,1,1]);
            testCase.verifyEqual(restored.energy,source.energy);
            testCase.verifyEqual(restored.structure,source.structure);
            testCase.verifyEqual(converted.energy,source.energy);
            testCase.verifyEqual(converted.miller_index,[1,1,1]);
            grouped=kssolv.analysis.matgenlab.analysis. ...
                entry_dict_from_list(entries);
            testCase.verifyEqual(numel(grouped),1);
            expression=kssolv.analysis.matgenlab.analysis. ...
                SurfaceEnergyExpression(2,struct("delu_Mg",-.5));
            testCase.verifyEqual(kssolv.analysis.matgenlab.analysis. ...
                sub_chempots(expression,struct("delu_Mg",4)),0);
        end

        function officialWorkFunctionFilesMatch(testCase)
            directory=surfaceFixtureDirectory();
            analyzer=kssolv.analysis.matgenlab.analysis. ...
                WorkFunctionAnalyzer.from_files( ...
                fullfile(directory,"CONTCAR.relax1.gz"), ...
                fullfile(directory,"LOCPOT.gz"), ...
                fullfile(directory,"OUTCAR.relax1.gz"));
            testCase.verifyEqual(analyzer.work_function, ...
                3.1856951595332457,AbsTol=2e-13);
            testCase.verifyEqual(analyzer.vacuum_locpot, ...
                3.2459951595332455,AbsTol=2e-13);
            testCase.verifyEqual(analyzer.efermi,.0603,AbsTol=1e-15);
            testCase.verifyEqual(analyzer.ave_bulk_p, ...
                -13.040697221973561,AbsTol=2e-13);
            testCase.verifyEqual(analyzer.slab_regions, ...
                [.0289369999999991,.4710630000000009],AbsTol=2e-13);
            testCase.verifyTrue(analyzer.is_converged());
            shifted=kssolv.analysis.matgenlab.analysis. ...
                WorkFunctionAnalyzer.from_files( ...
                fullfile(directory,"CONTCAR.relax1.gz"), ...
                fullfile(directory,"LOCPOT.gz"), ...
                fullfile(directory,"OUTCAR.relax1.gz"),-.25,3.7);
            testCase.verifyEqual(shifted.ave_bulk_p, ...
                -13.078959473193354,AbsTol=2e-13);
            testCase.verifyEqual(shifted.slab_regions, ...
                [0,.2210630000000009;.7789369999999991,1], ...
                AbsTol=2e-13);
        end

        function officialNanoscaleStabilityMatches(testCase)
            [hcp,~]=entryAnalyzer("La_hcp_entries.txt","La_hcp");
            [fcc,~]=entryAnalyzer("La_fcc_entries.txt","La_fcc");
            stability=kssolv.analysis.matgenlab.analysis. ...
                NanoscaleStability({fcc,hcp});
            radius=stability.solve_equilibrium_point(hcp,fcc);
            testCase.verifyEqual(radius,3.0322452206447053,AbsTol=1e-3);
            hcpShape=hcp.wulff_from_chempot();
            fccShape=fcc.wulff_from_chempot();
            testCase.verifyEqual(hcpShape.weighted_surface_energy, ...
                .048256197490888775,AbsTol=1e-6);
            testCase.verifyEqual(fccShape.weighted_surface_energy, ...
                .046372640341005994,AbsTol=1e-6);
            testCase.verifyEqual(stability.scaled_wulff( ...
                hcpShape,10).effective_radius,10,AbsTol=3e-11);
            testCase.verifyEqual(stability.scaled_wulff( ...
                fccShape,10).effective_radius,10,AbsTol=3e-11);
            low=radius*10-10;high=radius*10+10;
            [hcpLow,rLow]=stability.wulff_gform_and_r( ...
                hcpShape,hcp.ucell_entry,low,from_sphere_area=true);
            [fccLow,~]=stability.wulff_gform_and_r( ...
                fccShape,fcc.ucell_entry,low,from_sphere_area=true);
            [hcpHigh,rHigh]=stability.wulff_gform_and_r( ...
                hcpShape,hcp.ucell_entry,high,from_sphere_area=true);
            [fccHigh,~]=stability.wulff_gform_and_r( ...
                fccShape,fcc.ucell_entry,high,from_sphere_area=true);
            testCase.verifyLessThan(fccLow,hcpLow);
            testCase.verifyGreaterThan(fccHigh,hcpHigh);
            testCase.verifyEqual(rLow,low/10,AbsTol=3e-12);
            testCase.verifyEqual(rHigh,high/10,AbsTol=3e-12);
        end

        function plottingApisReturnAxes(testCase)
            [analyzers,~]=oxygenAnalyzers();
            analyzer=analyzers.Ni;
            group=facetGroup(analyzer,[1,0,0]);
            axesHandles=gobjects(1,6);
            axesHandles(1)=analyzer.area_frac_vs_chempot_plot( ...
                "delu_O",[-7,-6],"increments",2);
            axesHandles(2)=analyzer.chempot_vs_gamma( ...
                "delu_O",[-7,0],"miller_index",[1,0,0], ...
                "no_doped",false);
            axesHandles(3)=analyzer.monolayer_vs_BE();
            axesHandles(4)=analyzer.BE_vs_clean_SE(struct("delu_O",0));
            axesHandles(5)=analyzer.surface_chempot_range_map( ...
                ["delu_O","delu_X"],[1,0,0],[-7,0;-1,1],"incr",3);
            axesHandles(6)=axes("Parent",figure("Visible","off"));
            analyzer.chempot_vs_gamma_plot_one(axesHandles(6), ...
                group.clean{1},"delu_O",[-7,0]);
            kssolv.analysis.matgenlab.analysis.SurfaceEnergyPlotter. ...
                chempot_plot_addons(axesHandles(6),[-7,0],"O");
            testCase.verifyTrue(all(isgraphics(axesHandles,"axes")));
            close(unique([axesHandles.Parent]));
        end
    end
end

function [analyzers,adsorbate]=oxygenAnalyzers()
cleanData=readJson("cs_entries_slabs.json");
adsData=readJson("cs_entries_o_ads.json");
adsorbate=kssolv.analysis.matgenlab.core.ComputedStructureEntry. ...
    from_dict(readJson("isolated_O_entry.txt"));
bulkData=readJson("ucell_entries.txt");
analyzers=struct();
for element=["Ni","Pt","Rh"]
    entries={};names=fieldnames(cleanData);
    for index=1:numel(names)
        name=names{index};
        if ~contains(name,element),continue,end
        hkl=parseTrailingHkl(name);
        cleanBase=kssolv.analysis.matgenlab.core. ...
            ComputedStructureEntry.from_dict(cleanData.(name));
        clean=kssolv.analysis.matgenlab.analysis.SlabEntry( ...
            cleanBase.structure,cleanBase.energy,hkl, ...
            label=name+"_clean");
        adsBase=kssolv.analysis.matgenlab.core. ...
            ComputedStructureEntry.from_dict(adsData.(name));
        ads=kssolv.analysis.matgenlab.analysis.SlabEntry( ...
            adsBase.structure,adsBase.energy,hkl,label=name+"_O", ...
            adsorbates={adsorbate},clean_entry=clean);
        entries=[entries,{clean,ads}]; %#ok<AGROW>
    end
    bulk=kssolv.analysis.matgenlab.core.ComputedStructureEntry. ...
        from_dict(bulkData.(element));
    analyzers.(element)=kssolv.analysis.matgenlab.analysis. ...
        SurfaceEnergyPlotter(entries,bulk);
end
end

function [analyzer,entries]=entryAnalyzer(filename,bulkName,refNames)
if nargin<3,refNames={};end
data=readJson(filename);names=fieldnames(data);entries=cell(1,numel(names));
for index=1:numel(names)
    base=kssolv.analysis.matgenlab.core.ComputedStructureEntry. ...
        from_dict(data.(names{index}));
    hkl=parseEntryHkl(names{index});
    entries{index}=kssolv.analysis.matgenlab.analysis.SlabEntry( ...
        base.structure,base.energy,hkl,label=names{index});
end
bulkData=readJson("ucell_entries.txt");
bulk=kssolv.analysis.matgenlab.core.ComputedStructureEntry. ...
    from_dict(bulkData.(bulkName));
references=cell(1,numel(refNames));
for index=1:numel(refNames)
    references{index}=kssolv.analysis.matgenlab.core. ...
        ComputedStructureEntry.from_dict(bulkData.(refNames{index}));
end
analyzer=kssolv.analysis.matgenlab.analysis.SurfaceEnergyPlotter( ...
    entries,bulk,references);
end

function hkl=parseEntryHkl(name)
if endsWith(name,"_2_12")
    hkl=[2,-1,2];
    return
end
token=regexp(name,'_([0-9])([0-9])([0-9])_shift','tokens','once');
if isempty(token)
    token=regexp(name,'_([0-9])([0-9])([0-9])$','tokens','once');
end
if isempty(token)
    error("KSSOLV:Matgenlab:Test:SurfaceFixture", ...
        "Cannot identify Miller index in '%s'.",name);
end
hkl=cellfun(@str2double,token);
end

function hkl=parseTrailingHkl(name)
token=regexp(name,'_([0-9])([0-9])([0-9])$','tokens','once');
hkl=cellfun(@str2double,token);
end

function group=facetGroup(analyzer,hkl)
index=find(arrayfun(@(x)isequal(x.hkl,reshape(hkl,1,3)), ...
    analyzer.all_slab_entries),1);
group=analyzer.all_slab_entries(index);
end

function value=readJson(name)
value=jsondecode(fileread(fullfile(surfaceFixtureDirectory(),name)));
end

function directory=surfaceFixtureDirectory()
root=fileparts(fileparts(mfilename("fullpath")));
directory=fullfile(root,"+fixtures","+analysis","surfaces");
end
