classdef TEMTest < matlab.unittest.TestCase
    methods (Test)
        function scalarAndGeometryOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            import kssolv.analysis.matgenlab.analysis.TEMCalculator
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            calculator = TEMCalculator();
            structure = Structure(Lattice.cubic(4.209), ...
                {"Cs","Cl"}, [0,0,0;0.5,0.5,0.5]);
            request = struct( ...
                "module", "pymatgen.analysis.diffraction.tem", ...
                "symbol", "TEMCalculator", ...
                "construct", struct("args", {{}}), ...
                "operations", {{ ...
                    struct("kind","call","name","wavelength_rel"), ...
                    struct("kind","call","name","generate_points", ...
                        "args",{{-1,1}}), ...
                    struct("kind","call","name","get_plot_coeffs", ...
                        "args",{{[1,1,0],[1,-1,0],[2,0,0]}}), ...
                    struct("kind","call","name", ...
                        "get_interplanar_angle", ...
                        "args",{{structure.as_dict(), ...
                        [0,0,-1],[0,-1,0]}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            testCase.verifyEqual(calculator.wavelength_rel(), ...
                reference.results{1}, AbsTol=2e-15);
            testCase.verifyEqual(TEMCalculator.generate_points(-1,1), ...
                reference.results{2});
            testCase.verifyEqual(TEMCalculator.get_plot_coeffs( ...
                [1,1,0],[1,-1,0],[2,0,0]), ...
                reshape(reference.results{3},1,[]),AbsTol=2e-15);
            testCase.verifyEqual(TEMCalculator.get_interplanar_angle( ...
                structure,[0,0,-1],[0,-1,0]), ...
                reference.results{4},AbsTol=2e-13);
        end

        function zoneAxisFilteringPreservesTupleLists(testCase)
            import kssolv.analysis.matgenlab.analysis.TEMCalculator
            calculator = TEMCalculator([], 200, [1, 0, 0]);
            points = calculator.zone_axis_filter( ...
                {[0, 2, 3], [1, 2, 3], [0, -1, 4]});
            testCase.verifyEqual(points, ...
                [0, 2, 3; 1, 2, 3; 0, -1, 4]);
            firstLaue = calculator.zone_axis_filter( ...
                {[0, 2, 3], [1, 2, 3], [0, -1, 4]}, 1);
            testCase.verifyEqual(firstLaue, ...
                [0, 2, 3; 1, 2, 3; 0, -1, 4]);
        end

        function officialScatteringValues(testCase)
            import kssolv.analysis.matgenlab.analysis.TEMCalculator
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            calculator = TEMCalculator();
            structure = Structure(Lattice.cubic(4.209), ...
                {"Cs","Cl"}, [0,0,0;0.5,0.5,0.5]);

            spacing = calculator.get_interplanar_spacings( ...
                structure, {[-10,3,0]});
            testCase.verifyEqual(spacing.value, ...
                4.209/sqrt(109), AbsTol=2e-15);
            angles = calculator.bragg_angles(spacing);
            sSquared = calculator.get_s2(angles);
            testCase.verifyEqual(sSquared.value, ...
                1.5381852947115047, RelTol=2e-14);
            xray = calculator.x_ray_factors(structure,angles);
            testCase.verifyEqual(xray.Cs.value, ...
                14.42250869579648,AbsTol=2e-12);
            testCase.verifyEqual(xray.Cl.value, ...
                2.7804915737999103,AbsTol=2e-12);

            spacing = calculator.get_interplanar_spacings( ...
                structure, {[2,1,3]});
            electron = calculator.electron_scattering_factors( ...
                structure, calculator.bragg_angles(spacing));
            testCase.verifyEqual(electron.Cs.value,2.848,RelTol=1e-3);
            testCase.verifyEqual(electron.Cl.value,1.1305,RelTol=1e-3);
        end

        function intensitiesPositionsAndPattern(testCase)
            import kssolv.analysis.matgenlab.analysis.TEMCalculator
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            calculator = TEMCalculator();
            structure = Structure(Lattice.cubic(4.209), ...
                {"Cs","Cl"}, [0,0,0;0.5,0.5,0.5]);
            spacing1 = calculator.get_interplanar_spacings( ...
                structure,{[2,1,0]});
            spacing2 = calculator.get_interplanar_spacings( ...
                structure,{[2,2,0]});
            intensity1 = calculator.cell_intensity( ...
                structure,calculator.bragg_angles(spacing1));
            intensity2 = calculator.cell_intensity( ...
                structure,calculator.bragg_angles(spacing2));
            testCase.verifyGreaterThan(intensity2.value,intensity1.value);

            points = TEMCalculator.generate_points(-2,2);
            first = calculator.get_first_point(structure,points);
            testCase.verifyEqual(first.value,4.209,AbsTol=2e-14);
            positions = calculator.get_positions(structure,points);
            origin = positions(all(vertcat(positions.hkl)==0,2));
            testCase.verifyEqual(origin.value,[0,0]);
            dots = calculator.tem_dots(structure,points);
            testCase.verifyTrue(all([dots.intensity] >= 0));
            testCase.verifyEqual(max([dots.intensity]),1,AbsTol=2e-15);

            pattern = calculator.get_pattern(structure);
            testCase.verifyClass(pattern,"table");
            testCase.verifyEqual(pattern.Properties.VariableNames, ...
                {'Position','hkl','Intensity_norm', ...
                'Film_radius','Interplanar_Spacing'});
            testCase.verifyEqual( ...
                pattern.Properties.UserData.PymatgenColumnNames, ...
                {'Position','(hkl)','Intensity (norm)', ...
                'Film radius','Interplanar Spacing'});
        end
    end
end
