classdef TopologicalSpillageTest < matlab.unittest.TestCase
    methods (Test)
        function helpers(testCase)
            testCase.verifyTrue( ...
                kssolv.analysis.matgenlab.analysis.topological. ...
                SOCSpillage.isclose(1, 1 + 1e-8));
            [basis, rankValue] = ...
                kssolv.analysis.matgenlab.analysis.topological. ...
                SOCSpillage.orth([1, 0; 1, 0; 0, 0]);
            testCase.verifyEqual(rankValue, 1);
            testCase.verifyEqual(basis' * basis, 1, AbsTol=1e-14);
        end

        function officialWavecarOracle(testCase)
            root = "/tmp/matgenlab-plan.tMNeV8/pymatgen-2026.5.4/" + ...
                "test-files/analysis/topological/";
            testCase.assumeTrue(isfile(root + "WAVECAR-NonSOC"), ...
                "Frozen WAVECAR fixtures unavailable.");
            spillage = ...
                kssolv.analysis.matgenlab.analysis.topological.SOCSpillage( ...
                root + "WAVECAR-NonSOC", root + "WAVECAR-SOC");
            testCase.verifyEqual(spillage.overlap_so_spinpol(), ...
                1.3634111271008775, AbsTol=1e-5);
        end
    end
end
