classdef TransitionStateTest < matlab.unittest.TestCase
    methods (Test)
        function officialNebDirectoryAndRoundTrip(testCase)
            root="/tmp/matgenlab-plan.tMNeV8/pymatgen-2026.5.4/" + ...
                "test-files/io/vasp/fixtures/neb_analysis/neb1/neb";
            testCase.assumeTrue(isfolder(root), ...
                "Frozen NEB fixture unavailable.");
            analysis=kssolv.analysis.matgenlab.analysis. ...
                NEBAnalysis.from_dir(root);
            testCase.verifyEqual(analysis.energies(1), ...
                -255.97992669000001,AbsTol=1e-12);
            testCase.verifyEqual(analysis.energies(4), ...
                -255.84261996000001,AbsTol=1e-12);
            [~,maxima]=analysis.get_extrema();
            testCase.verifyEqual(maxima(1,:), ...
                [.50023335723480078,325.20043063935128], ...
                AbsTol=1e-10);
            analysis=analysis.setup_spline([],true);
            [~,maxima]=analysis.get_extrema();
            testCase.verifyEqual(maxima(1,:), ...
                [.50023335723480078,325.20003984140203], ...
                AbsTol=1e-10);
            restored=kssolv.analysis.matgenlab.analysis. ...
                NEBAnalysis.from_dict(analysis.as_dict());
            testCase.verifyEqual(restored.r,analysis.r,AbsTol=1e-14);
            testCase.verifyEqual(restored.energies,analysis.energies);
        end

        function officialSerializedNebAndPlot(testCase)
            path="/tmp/matgenlab-plan.tMNeV8/pymatgen-2026.5.4/" + ...
                "test-files/io/vasp/fixtures/neb_analysis/neb2/" + ...
                "neb_analysis2.json";
            testCase.assumeTrue(isfile(path), ...
                "Frozen serialized NEB fixture unavailable.");
            analysis=kssolv.analysis.matgenlab.analysis. ...
                NEBAnalysis.from_dict(jsondecode(fileread(path)));
            [~,maxima]=analysis.get_extrema();
            testCase.verifyEqual(maxima(1,:), ...
                [.37255257367467326,562.40825334519991], ...
                AbsTol=1e-10);
            analysis=analysis.setup_spline([],true);
            [~,maxima]=analysis.get_extrema();
            testCase.verifyEqual(maxima(1,:), ...
                [.30371133723478794,528.46229631648691], ...
                AbsTol=1e-10);
            axesHandle=analysis.get_plot();
            cleanup=onCleanup(@()close(ancestor(axesHandle,"figure")));
            testCase.verifyClass(axesHandle,"matlab.graphics.axis.Axes");
            testCase.verifyEqual(axesHandle.XLabel.String, ...
                'Reaction Coordinate');
            testCase.verifyEqual(axesHandle.YLabel.String,'Energy (meV)');
            clear cleanup
        end
    end
end
