classdef WulffTest < matlab.unittest.TestCase
    methods (Test)
        function officialSurfaceSamplesMatchPymatgen(testCase)
            data=jsondecode(fileread(fullfile(fileparts(mfilename( ...
                "fullpath")),"+fixtures","wulff_surface_samples.json")));
            identifiers={"mp_101","mp_72","mp_8636"};
            lattices={ ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(3.8312), ...
                kssolv.analysis.matgenlab.core.Lattice. ...
                hexagonal(4.6,2.82), ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(2.992)};
            expected=[ ...
                2.4211051292145527,5.252679819228766, ...
                0.08446215185062898; ...
                1.9987444450694924,5.0173050155582475, ...
                0.03847329889939299; ...
                0.538339420684726,5.220805387340356,0];
            for item=1:numel(identifiers)
                sample=data.(identifiers{item});
                count=numel(sample.surfaces);
                width=numel(sample.surfaces(1).miller_index);
                millers=zeros(count,width);energies=zeros(1,count);
                for index=1:count
                    millers(index,:)= ...
                        sample.surfaces(index).miller_index;
                    energies(index)= ...
                        sample.surfaces(index).surface_energy;
                end
                shape=kssolv.analysis.matgenlab.analysis.WulffShape( ...
                    lattices{item},millers,energies);
                testCase.verifyEqual(shape.weighted_surface_energy, ...
                    expected(item,1),AbsTol=2e-12);
                testCase.verifyEqual(shape.shape_factor, ...
                    expected(item,2),AbsTol=2e-12);
                testCase.verifyEqual(shape.anisotropy, ...
                    expected(item,3),AbsTol=2e-12);
                testCase.verifyEqual(shape.surface_area, ...
                    sum([shape.miller_area_dict.value]),AbsTol=1e-12);
                testCase.verifyEqual(shape.total_surface_energy, ...
                    shape.weighted_surface_energy*shape.surface_area, ...
                    AbsTol=2e-11);
            end
        end

        function cubeAndHexPrismTopologyMatchesOfficial(testCase)
            cube=kssolv.analysis.matgenlab.analysis.WulffShape( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(1), ...
                [1,0,0],1);
            testCase.verifyEqual(cube.volume,8,AbsTol=1e-12);
            testCase.verifyEqual(cube.surface_area,24,AbsTol=1e-12);
            testCase.verifyEqual(cube.tot_corner_sites,8);
            testCase.verifyEqual(cube.tot_edges,12);
            prism=kssolv.analysis.matgenlab.analysis.WulffShape( ...
                kssolv.analysis.matgenlab.core.Lattice. ...
                hexagonal(2.63,5.21), ...
                [0,0,1;1,0,0],[0.35,0.53]);
            testCase.verifyEqual(prism.tot_corner_sites,12);
            testCase.verifyEqual(prism.tot_edges,18);
        end

        function utilityFormattingGeometryAndPlots(testCase)
            text=kssolv.analysis.matgenlab.analysis. ...
                hkl_tuple_to_str([1,-2,0]);
            testCase.verifyEqual(text,"($1\overline{2}0$)");
            area=kssolv.analysis.matgenlab.analysis.get_tri_area( ...
                [0,0,0;1,0,0;0,1,0]);
            testCase.verifyEqual(area,0.5,AbsTol=1e-14);
            shape=kssolv.analysis.matgenlab.analysis.WulffShape( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(1), ...
                [1,0,0],1);
            axesHandle=shape.get_plot();
            cleanup=onCleanup(@()close(axesHandle.Parent));
            testCase.verifyClass(axesHandle,"matlab.graphics.axis.Axes");
            testCase.verifyGreaterThanOrEqual(numel(axesHandle.Children),6);
            figureData=shape.get_plotly();
            testCase.verifyEqual(numel(figureData.data),6);
            testCase.verifyEqual(figureData.data{1}.type,"mesh3d");
            testCase.verifyEqual(shape.get_azimuth_elev([0,0,1]),0);
            [azimuth,elevation]=shape.get_azimuth_elev([1,1,1]);
            testCase.verifyEqual(azimuth,45,AbsTol=1e-12);
            testCase.verifyEqual(elevation, ...
                35.2643896827547,AbsTol=1e-12);
            clear cleanup
        end

        function completePublicInventoryAndErrors(testCase)
            facet=kssolv.analysis.matgenlab.analysis.WulffFacet( ...
                [1,0,0],2,[2,0,0],[.5,0,0],1,3,[1,0,0]);
            testCase.verifyEqual(facet.normal,[1,0,0]);
            testCase.verifyEqual(facet.e_surf,2);
            testCase.verifyEqual(facet.normal_pt,[2,0,0]);
            testCase.verifyEqual(facet.dual_pt,[.5,0,0]);
            testCase.verifyEqual(facet.index,1);
            testCase.verifyEqual(facet.m_ind_orig,3);
            testCase.verifyEqual(facet.miller,[1,0,0]);
            testCase.verifyEmpty(facet.points);
            testCase.verifyEmpty(facet.outer_lines);

            shape=kssolv.analysis.matgenlab.analysis.WulffShape( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(1), ...
                [1,0,0],1);
            testCase.verifyEqual(shape.volume,8,AbsTol=2e-14);
            testCase.verifyEqual(shape.surface_area,24,AbsTol=2e-14);
            testCase.verifyEqual(shape.weighted_surface_energy,1, ...
                AbsTol=2e-14);
            testCase.verifyEqual(shape.total_surface_energy,24, ...
                AbsTol=2e-14);
            testCase.verifyEqual(shape.anisotropy,0,AbsTol=2e-14);
            testCase.verifyEqual(shape.shape_factor,6,AbsTol=2e-14);
            testCase.verifyEqual(shape.effective_radius,(6/pi)^(1/3), ...
                AbsTol=2e-14);
            testCase.verifyEqual(shape.tot_corner_sites,8);
            testCase.verifyEqual(shape.tot_edges,12);
            testCase.verifyEqual(shape.miller_area_dict(1).miller, ...
                [1,0,0]);
            testCase.verifyEqual(shape.miller_area_dict(1).value,24, ...
                AbsTol=2e-14);
            testCase.verifyEqual(shape.miller_energy_dict(1).value,1);
            testCase.verifyEqual(shape.area_fraction_dict(1).value,1, ...
                AbsTol=2e-14);
            active=find(~cellfun(@(item)isempty(item.points), ...
                shape.facets),1);
            linePoints=shape.get_line_in_facet(shape.facets{active});
            testCase.verifyGreaterThanOrEqual(size(linePoints,1),4);

            cleanup=onCleanup(@()close(findall(groot,"Type","figure")));
            shape.show("axis_off",true);
            testCase.verifyNotEmpty(findall(groot,"Type","figure"));
            clear cleanup

            testCase.verifyError(@()kssolv.analysis.matgenlab.analysis. ...
                WulffShape(kssolv.analysis.matgenlab.core.Lattice. ...
                cubic(1),[1,0,0;1,1,0],1), ...
                "KSSOLV:Matgenlab:WulffShape:Size");
            testCase.verifyError(@()kssolv.analysis.matgenlab.analysis. ...
                WulffShape(kssolv.analysis.matgenlab.core.Lattice. ...
                cubic(1),[1,0,0],0), ...
                "KSSOLV:Matgenlab:WulffShape:Energy");
        end
    end
end
