function data = nbo_parser(filename)
%NBO_PARSER Parse all supported NBO analysis sections in a Q-Chem output.
text = kssolv.analysis.matgenlab.io.qchem.read_text(filename);
lines = splitlines(string(text));
data = struct( ...
    "natural_populations", ...
    {kssolv.analysis.matgenlab.io.qchem.parse_natural_populations(lines)}, ...
    "hybridization_character", ...
    {kssolv.analysis.matgenlab.io.qchem.parse_hybridization_character(lines)}, ...
    "hyperbonds", ...
    {kssolv.analysis.matgenlab.io.qchem.parse_hyperbonds(lines)}, ...
    "perturbation_energy", ...
    {kssolv.analysis.matgenlab.io.qchem.parse_perturbation_energy(lines)});
end
