function tables = parse_hyperbonds(lines)
%#ok<*AGROW>
%PARSE_HYPERBONDS Parse NBO three-center/four-electron hyperbond tables.
lines = string(lines(:));
headers = find(contains(lines, "3-Center, 4-Electron A:-B-:C Hyperbonds"));
tables = cell(1, numel(headers));
for tableIndex = 1:numel(headers)
    entries = struct([]);
    index = headers(tableIndex) + 2;
    while index <= numel(lines)
        line = char(lines(index));
        if any(contains(string(line), ["NATURAL BOND ORBITALS", ...
                "SECOND ORDER PERTURBATION THEORY", "Archival summary:"])), break; end
        if numel(line) >= 77 && ~isnan(str2double(strtrim(line(1:4))))
            entry = struct("hyperbond_index", str2double(strtrim(line(1:4))), ...
                "bond_atom_1_symbol", strtrim(line(6:8)), ...
                "bond_atom_1_index", str2double(strtrim(line(9:11))), ...
                "bond_atom_2_symbol", strtrim(line(14:15)), ...
                "bond_atom_2_index", str2double(strtrim(line(16:18))), ...
                "bond_atom_3_symbol", strtrim(line(21:22)), ...
                "bond_atom_3_index", str2double(strtrim(line(23:25))), ...
                "pctA_B", str2double(strtrim(line(28:31))), ...
                "pctB_C", str2double(strtrim(line(33:36))), ...
                "occ", str2double(strtrim(line(39:44))), ...
                "BD_A_B", str2double(strtrim(line(47:53))), ...
                "LP_C", str2double(strtrim(line(55:59))));
            entries(end + 1) = entry;
        end
        index = index + 1;
    end
    tables{tableIndex} = struct2table(entries);
end
end
