function tables = parse_perturbation_energy(lines)
%#ok<*AGROW>
%PARSE_PERTURBATION_ENERGY Parse NBO second-order donor/acceptor interactions.
lines = string(lines(:));
headers = find(contains(lines, ...
    "SECOND ORDER PERTURBATION THEORY ANALYSIS OF FOCK MATRIX IN NBO BASIS"));
tables = cell(1, numel(headers));
for tableIndex = 1:numel(headers)
    entries = struct([]);
    index = headers(tableIndex) + 1;
    while index <= numel(lines)
        line = char(lines(index));
        if contains(line, "NATURAL BOND ORBITALS"), break; end
        token = regexp(line, ...
            "^\s*(\d+)\.\s+(\S+)\s+(\d+)\s+(\S+)\s*(\d+)?(?:\s+(\S+)\s*(\d+)?)?\s+" + ...
            "(\d+)\.\s+(\S+)\s+(\d+)\s+(\S+)\s*(\d+)?(?:\s+(\S+)\s*(\d+)?)?\s+" + ...
            "(\*+|[-+\d.]+)\s+([-+\d.]+)\s+([-+\d.]+)", "tokens", "once");
        if ~isempty(token)
            energy = str2double(token{15});
            if contains(token{15}, "*"), energy = Inf; end
            entry = struct("donor_bond_index", str2double(token{1}), ...
                "donor_type", token{2}, "donor_orbital_index", str2double(token{3}), ...
                "donor_atom_1_symbol", token{4}, "donor_atom_1_number", str2double(token{5}), ...
                "acceptor_bond_index", str2double(token{8}), ...
                "acceptor_type", token{9}, "acceptor_orbital_index", str2double(token{10}), ...
                "acceptor_atom_1_symbol", token{11}, ...
                "acceptor_atom_1_number", str2double(token{12}), ...
                "perturbation_energy", energy, ...
                "energy_difference", str2double(token{16}), ...
                "fock_matrix_element", str2double(token{17}));
            entries(end + 1) = entry;
        end
        index = index + 1;
    end
    if isempty(entries), tables{tableIndex} = table();
    else, tables{tableIndex} = struct2table(entries); end
end
end
