classdef FiestaInput < kssolv.analysis.matgenlab.util.MSONable
    %FIESTAINPUT Representation of FIESTA's mandatory cell.in file.

    properties (Dependent)
        correlation_grid
        Exc_DFT_option
        cohsex_options
        GW_options
        bse_tddft_options
    end

    properties (Access = private)
        mol
        state (1,1) ...
            kssolv.analysis.matgenlab.io.fiesta.FiestaMutableState = ...
            kssolv.analysis.matgenlab.io.fiesta.FiestaMutableState()
    end

    properties (Dependent, SetAccess = private)
        infos_on_system
        molecule
    end

    methods
        function obj = FiestaInput(mol, correlationGrid, excDftOption, ...
                cohsexOptions, gwOptions, bseTddftOptions)
            obj.state = ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaMutableState();
            if nargin < 2 || emptyDictionary(correlationGrid)
                correlationGrid = struct( ...
                    "dE_grid", "0.500", "n_grid", "14");
            end
            if nargin < 3 || emptyDictionary(excDftOption)
                excDftOption = struct("rdVxcpsi", "1");
            end
            if nargin < 4 || emptyDictionary(cohsexOptions)
                cohsexOptions = struct("eigMethod", "C", ...
                    "mix_cohsex", "0.500", "nc_cohsex", "0", ...
                    "nit_cohsex", "0", "nv_cohsex", "0", ...
                    "resMethod", "V", "scf_cohsex_wf", "0");
            end
            if nargin < 5 || emptyDictionary(gwOptions)
                gwOptions = struct("nc_corr", "10", ...
                    "nit_gw", "3", "nv_corr", "10");
            end
            if nargin < 6 || emptyDictionary(bseTddftOptions)
                bseTddftOptions = struct("do_bse", "1", ...
                    "do_tddft", "0", "nc_bse", "382", ...
                    "nit_bse", "50", "npsi_bse", "1", ...
                    "nv_bse", "21");
            end
            obj.mol = mol;
            obj.correlation_grid = correlationGrid;
            obj.Exc_DFT_option = excDftOption;
            obj.cohsex_options = cohsexOptions;
            obj.GW_options = gwOptions;
            obj.bse_tddft_options = bseTddftOptions;
        end

        function value = get.correlation_grid(obj)
            value = obj.state.correlation_grid;
        end
        function obj = set.correlation_grid(obj, value)
            obj.state.correlation_grid = value;
        end
        function value = get.Exc_DFT_option(obj)
            value = obj.state.Exc_DFT_option;
        end
        function obj = set.Exc_DFT_option(obj, value)
            obj.state.Exc_DFT_option = value;
        end
        function value = get.cohsex_options(obj)
            value = obj.state.cohsex_options;
        end
        function obj = set.cohsex_options(obj, value)
            obj.state.cohsex_options = value;
        end
        function value = get.GW_options(obj)
            value = obj.state.GW_options;
        end
        function obj = set.GW_options(obj, value)
            obj.state.GW_options = value;
        end
        function value = get.bse_tddft_options(obj)
            value = obj.state.bse_tddft_options;
        end
        function obj = set.bse_tddft_options(obj, value)
            obj.state.bse_tddft_options = value;
        end

        function set_auxiliary_basis_set(obj, folder, auxiliaryFolder, ...
                auxiliaryBasisSetType)
            if nargin < 4, auxiliaryBasisSetType = "aug_cc_pvtz"; end
            listing = dir(auxiliaryFolder);
            listing = listing(~[listing.isdir]);
            for specie = reshape(string(obj.mol.symbol_set), 1, [])
                for index = 1:numel(listing)
                    name = string(listing(index).name);
                    if contains(upper(name), upper(specie) + "2") && ...
                            contains(lower(name), ...
                            lower(string(auxiliaryBasisSetType)))
                        source = string(fullfile( ...
                            listing(index).folder, listing(index).name));
                        destination = string(fullfile( ...
                            folder, specie + "2.ion"));
                        if source == destination
                            error("KSSOLV:Matgenlab:Fiesta:SameFile", ...
                                "Source and destination auxiliary basis " + ...
                                "files are identical.");
                        end
                        [status, message] = copyfile( ...
                            source, destination, "f");
                        if ~status
                            error("KSSOLV:Matgenlab:Fiesta:BasisCopy", ...
                                "%s", message);
                        end
                    end
                end
            end
        end

        function obj = set_gw_options(obj, nvBand, ncBand, nIteration, ...
                nGrid, dEGrid)
            if nargin < 2, nvBand = 10; end
            if nargin < 3, ncBand = 10; end
            if nargin < 4, nIteration = 5; end
            if nargin < 5, nGrid = 6; end
            if nargin < 6, dEGrid = .5; end
            options = obj.GW_options;
            options.nv_corr = nvBand;
            options.nc_corr = ncBand;
            options.nit_gw = nIteration;
            obj.GW_options = options;
            grid = obj.correlation_grid;
            grid.dE_grid = dEGrid;
            grid.n_grid = nGrid;
            obj.correlation_grid = grid;
        end

        function obj = set_bse_options(obj, nExcitations, nitBse)
            if nargin < 2, nExcitations = 10; end
            if nargin < 3, nitBse = 200; end
            options = obj.bse_tddft_options;
            options.npsi_bse = nExcitations;
            options.nit_bse = nitBse;
            obj.bse_tddft_options = options;
        end

        function obj = dump_bse_data_in_gw_run(obj, bseDump)
            if nargin < 2, bseDump = true; end
            options = obj.bse_tddft_options;
            options.do_bse = double(logical(bseDump));
            options.do_tddft = 0;
            obj.bse_tddft_options = options;
        end

        function obj = dump_tddft_data_in_gw_run(obj, tddftDump)
            if nargin < 2, tddftDump = true; end
            options = obj.bse_tddft_options;
            options.do_bse = "0";
            if tddftDump
                options.do_tddft = "1";
            else
                options.do_tddft = "0";
            end
            obj.bse_tddft_options = options;
        end

        function value = get.infos_on_system(obj)
            values = ["=========================================", ...
                "Reading infos on system:", "", ...
                " Number of atoms = " + pyFloat( ...
                obj.mol.composition.num_atoms) + ...
                " ; number of species = " + ...
                string(numel(obj.mol.symbol_set)), ...
                " Number of valence bands = " + ...
                string(fix(obj.mol.nelectrons / 2)), ...
                " Sigma grid specs: n_grid = " + ...
                optionText(obj.correlation_grid.n_grid) + ...
                " ;  dE_grid = " + ...
                optionText(obj.correlation_grid.dE_grid) + " (eV)"];
            rdVxcpsi = str2double(optionText( ...
                obj.Exc_DFT_option.rdVxcpsi));
            if rdVxcpsi == 1
                values(end + 1) = ...
                    " Exchange and correlation energy read from Vxcpsi.mat";
            elseif rdVxcpsi == 0
                values(end + 1) = ...
                    " Exchange and correlation energy re-computed";
            end
            if optionText(obj.cohsex_options.eigMethod) == "C"
                values(end + 1) = " Correcting  " + ...
                    optionText(obj.cohsex_options.nv_cohsex) + ...
                    " valence bands and  " + ...
                    optionText(obj.cohsex_options.nc_cohsex) + ...
                    " conduction bands at COHSEX level";
                values(end + 1) = " Performing   " + ...
                    optionText(obj.cohsex_options.nit_cohsex) + ...
                    " diagonal COHSEX iterations";
            elseif optionText(obj.cohsex_options.eigMethod) == "HF"
                values(end + 1) = " Correcting  " + ...
                    optionText(obj.cohsex_options.nv_cohsex) + ...
                    " valence bands and  " + ...
                    optionText(obj.cohsex_options.nc_cohsex) + ...
                    " conduction bands at HF level";
                values(end + 1) = " Performing   " + ...
                    optionText(obj.cohsex_options.nit_cohsex) + ...
                    " diagonal HF iterations";
            end
            values(end + 1) = " Using resolution of identity : " + ...
                optionText(obj.cohsex_options.resMethod);
            values(end + 1) = " Correcting  " + ...
                optionText(obj.GW_options.nv_corr) + ...
                " valence bands and " + ...
                optionText(obj.GW_options.nc_corr) + ...
                " conduction bands at GW level";
            values(end + 1) = " Performing   " + ...
                optionText(obj.GW_options.nit_gw) + " GW iterations";
            if str2double(optionText( ...
                    obj.bse_tddft_options.do_bse)) == 1
                values(end + 1) = " Dumping data for BSE treatment";
            end
            if str2double(optionText( ...
                    obj.bse_tddft_options.do_tddft)) == 1
                values(end + 1) = " Dumping data for TD-DFT treatment";
            end
            values = [values, "", " Atoms in cell cartesian A:"];
            symbols = reshape(string(obj.mol.symbol_set), 1, []);
            for index = 1:obj.mol.num_sites
                site = obj.mol(index);
                specieIndex = find(symbols == site.specie.symbol, 1);
                values(end + 1) = geometryLine( ...
                    site.coords, specieIndex); %#ok<AGROW>
            end
            values(end + 1) = "=========================================";
            value = pythonList(values);
        end

        function value = get.molecule(obj)
            value = obj.mol;
        end

        function value = string(obj)
            symbols = reshape(string(obj.mol.symbol_set), 1, []);
            geometry = strings(1, obj.mol.num_sites);
            for index = 1:obj.mol.num_sites
                site = obj.mol(index);
                specieIndex = find(symbols == site.specie.symbol, 1);
                geometry(index) = geometryLine(site.coords, specieIndex);
            end
            lines = [ ...
                "# number of atoms and species", ...
                "   " + string(fix(obj.mol.composition.num_atoms)) + ...
                "    " + string(numel(symbols)), ...
                "# number of valence bands", ...
                "    " + string(fix(obj.mol.nelectrons / 2)), ...
                "# number of points and spacing in eV for correlation grid", ...
                "    " + optionText(obj.correlation_grid.n_grid) + ...
                "    " + optionText(obj.correlation_grid.dE_grid), ...
                "# relire=1 ou recalculer=0 Exc DFT", ...
                "    " + optionText(obj.Exc_DFT_option.rdVxcpsi), ...
                "# number of COHSEX corrected occp and unoccp bands: C=COHSEX  H=HF", ...
                "    " + optionText(obj.cohsex_options.nv_cohsex) + ...
                "    " + optionText(obj.cohsex_options.nc_cohsex) + ...
                "   " + optionText(obj.cohsex_options.eigMethod), ...
                "# number of COHSEX iter, scf on wfns, mixing coeff; V=RI-V  I=RI-D", ...
                "    " + optionText(obj.cohsex_options.nit_cohsex) + ...
                "   " + optionText(obj.cohsex_options.resMethod) + ...
                "       " + ...
                optionText(obj.cohsex_options.scf_cohsex_wf) + ...
                "       " + optionText(obj.cohsex_options.mix_cohsex), ...
                "# number of GW corrected occp and unoccp bands", ...
                "   " + optionText(obj.GW_options.nv_corr) + ...
                "   " + optionText(obj.GW_options.nc_corr), ...
                "# number of GW iterations", ...
                "    " + optionText(obj.GW_options.nit_gw), ...
                "# dumping for BSE and TDDFT", ...
                "    " + optionText(obj.bse_tddft_options.do_bse) + ...
                "    " + optionText(obj.bse_tddft_options.do_tddft), ...
                "# number of occp. and virtual bands of BSE: nocore and up to 40 eVs", ...
                "    " + optionText(obj.bse_tddft_options.nv_bse) + ...
                "   " + optionText(obj.bse_tddft_options.nc_bse), ...
                "# number of excitations needed and number of iterations", ...
                "    " + optionText(obj.bse_tddft_options.npsi_bse) + ...
                "   " + optionText(obj.bse_tddft_options.nit_bse), ...
                "# list of symbols in order", symbols, ...
                "# scaling factor", "    1.000", ...
                "# atoms x,y,z cartesian .. will be multiplied by scale", ...
                geometry];
            value = strjoin(lines, newline) + newline + "            ";
        end

        function value = char(obj)
            value = char(string(obj));
        end

        function write_file(obj, filename)
            kssolv.analysis.matgenlab.io.fiesta.FiestaIOUtils. ...
                write_text(filename, string(obj));
        end

        function value = as_dict(obj)
            value = struct("mol", obj.mol.as_dict(), ...
                "correlation_grid", obj.correlation_grid, ...
                "Exc_DFT_option", obj.Exc_DFT_option, ...
                "COHSEX_options", obj.cohsex_options, ...
                "GW_options", obj.GW_options, ...
                "BSE_TDDFT_options", obj.bse_tddft_options);
        end

        function value = asDict(obj)
            value = obj.as_dict();
        end
    end

    methods (Static)
        function value = make_full_bse_densities_folder(folder)
            path = fullfile(folder, "FULL_BSE_Densities");
            if isfile(path)
                value = "FULL_BSE_Densities folder already exists";
                return
            elseif isfolder(path)
                error("KSSOLV:Matgenlab:Fiesta:FileExists", ...
                    "FULL_BSE_Densities already exists as a directory.");
            end
            [status, message] = mkdir(path);
            if ~status
                error("KSSOLV:Matgenlab:Fiesta:Mkdir", "%s", message);
            end
            value = "makedirs FULL_BSE_Densities folder";
        end

        function obj = from_dict(value)
            required = ["geometry_options", "symmetry_options", ...
                "memory_options"];
            for name = required
                if ~isfield(value, name)
                    error("KSSOLV:Matgenlab:Fiesta:FrozenFromDictKey", ...
                        "Frozen FiestaInput.from_dict expects key '%s'.", ...
                        name);
                end
            end
            molecule = value.mol;
            if ~isa(molecule, ...
                    "kssolv.analysis.matgenlab.core.Molecule")
                molecule = kssolv.analysis.matgenlab.core.Molecule. ...
                    from_dict(molecule);
            end
            obj = kssolv.analysis.matgenlab.io.fiesta.FiestaInput( ...
                molecule, value.correlation_grid, value.Exc_DFT_option, ...
                value.geometry_options, value.symmetry_options, ...
                value.memory_options);
        end

        function obj = fromDict(value)
            obj = kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                from_dict(value);
        end

        function obj = from_str(input)
            try
                lines = splitlines(strtrim(string(input)));
                atomTokens = split(strtrim(lines(2)));
                atomTokens(atomTokens == "") = [];
                nAtoms = str2double(atomTokens(1));
                nSpecies = str2double(atomTokens(2));
                correlation = tokensAt(lines, 6, 2);
                exc = tokensAt(lines, 8, 1);
                cohsexBands = tokensAt(lines, 10, 3);
                cohsexIteration = tokensAt(lines, 12, 4);
                gwBands = tokensAt(lines, 14, 2);
                gwIteration = tokensAt(lines, 16, 1);
                dumps = tokensAt(lines, 18, 2);
                bseBands = tokensAt(lines, 20, 2);
                bseIteration = tokensAt(lines, 22, 2);
                symbolStart = 24;
                symbols = strings(1, nSpecies);
                for index = 1:nSpecies
                    symbolTokens = tokensAt(lines, ...
                        symbolStart + index - 1, 1);
                    symbols(index) = symbolTokens(1);
                end
                scaleComment = symbolStart + nSpecies;
                geometryStart = scaleComment + 3;
                species = strings(1, nAtoms);
                coordinates = zeros(nAtoms, 3);
                for index = 1:nAtoms
                    geometryTokens = tokensAt(lines, ...
                        geometryStart + index - 1, 4);
                    coordinates(index, :) = ...
                        str2double(geometryTokens(1:3));
                    species(index) = symbols( ...
                        str2double(geometryTokens(4)));
                end
                if any(isnan(coordinates), "all")
                    error("KSSOLV:Matgenlab:Fiesta:Parse", ...
                        "Geometry contains a nonnumeric coordinate.");
                end
            catch exception
                if exception.identifier == ...
                        "KSSOLV:Matgenlab:Fiesta:Parse"
                    rethrow(exception)
                end
                wrapped = MException( ...
                    "KSSOLV:Matgenlab:Fiesta:Parse", ...
                    "Malformed Fiesta cell.in text.");
                wrapped = addCause(wrapped, exception);
                throw(wrapped)
            end
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                cellstr(species), coordinates);
            obj = kssolv.analysis.matgenlab.io.fiesta.FiestaInput( ...
                molecule, ...
                struct("n_grid", correlation(1), ...
                "dE_grid", correlation(2)), ...
                struct("rdVxcpsi", exc(1)), ...
                struct("nv_cohsex", cohsexBands(1), ...
                "nc_cohsex", cohsexBands(2), ...
                "eigMethod", cohsexBands(3), ...
                "nit_cohsex", cohsexIteration(1), ...
                "resMethod", cohsexIteration(2), ...
                "scf_cohsex_wf", cohsexIteration(3), ...
                "mix_cohsex", cohsexIteration(4)), ...
                struct("nv_corr", gwBands(1), ...
                "nc_corr", gwBands(2), ...
                "nit_gw", gwIteration(1)), ...
                struct("do_bse", dumps(1), ...
                "do_tddft", dumps(2), ...
                "nv_bse", bseBands(1), ...
                "nc_bse", bseBands(2), ...
                "npsi_bse", bseIteration(1), ...
                "nit_bse", bseIteration(2)));
        end

        function obj = from_file(filename)
            obj = kssolv.analysis.matgenlab.io.fiesta.FiestaInput. ...
                from_str( ...
                kssolv.analysis.matgenlab.io.fiesta.FiestaIOUtils. ...
                read_text(filename));
        end
    end
end

function value = emptyDictionary(input)
value = isempty(input) || (isstruct(input) && isempty(fieldnames(input)));
end

function value = optionText(input)
if isnumeric(input)
    if isscalar(input) && input == fix(input)
        value = string(sprintf("%.0f", input));
    else
        value = pyFloat(input);
    end
else
    value = string(input);
end
end

function value = pyFloat(input)
value = kssolv.analysis.matgenlab.io.fiesta.FiestaIOUtils. ...
    python_float(input);
end

function value = geometryLine(coordinates, specieIndex)
value = " " + pyFloat(coordinates(1)) + ...
    " " + pyFloat(coordinates(2)) + ...
    " " + pyFloat(coordinates(3)) + ...
    " " + string(specieIndex);
end

function value = pythonList(values)
values = replace(string(values), "\", "\\");
values = replace(values, "'", "\'");
value = "[" + strjoin("'" + values + "'", ", ") + "]";
end

function value = tokensAt(lines, index, count)
if index > numel(lines)
    error("KSSOLV:Matgenlab:Fiesta:Parse", ...
        "Expected data line %d.", index);
end
value = split(strtrim(lines(index)));
value(value == "") = [];
if numel(value) < count
    error("KSSOLV:Matgenlab:Fiesta:Parse", ...
        "Line %d contains fewer than %d fields.", index, count);
end
value = reshape(value(1:count), 1, []);
end
