classdef BaderCallerInventoryTest < matlab.unittest.TestCase
    % Frozen parity tests for pymatgen.command_line.bader_caller.

    methods (Test)
        function frozenInventoryHasAllElevenApis(testCase)
            package = "kssolv.analysis.matgenlab.command_line." + ...
                "bader_caller.";
            testCase.verifyNotEmpty(meta.class.fromName( ...
                package + "BaderAnalysis"));
            methodNames = string(methods(char( ...
                package + "BaderAnalysis")));
            testCase.verifyTrue(all(ismember([ ...
                "get_charge", "get_charge_transfer", ...
                "get_partial_charge", ...
                "get_charge_decorated_structure", ...
                "get_oxidation_state_decorated_structure", ...
                "get_decorated_structure", "from_path"], ...
                methodNames)));
            testCase.verifyNotEmpty(which( ...
                package + "bader_analysis_from_path"));
            testCase.verifyNotEmpty(which( ...
                package + "bader_analysis_from_objects"));

            inventory = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", "api.csv");
            rows = readtable(inventory, ...
                detectImportOptions(inventory, "TextType", "string"));
            selected = rows.module == ...
                "pymatgen.command_line.bader_caller";
            testCase.verifyEqual(sum(selected), 11);
            oracle = testCase.oracle();
            testCase.verifyEqual(oracle.metadata.api_count, 11);
            testCase.verifyEqual(string(oracle.metadata.tag), ...
                "v2026.7.24");
        end

        function officialAcfMatchesFrozenPythonOracle(testCase)
            import kssolv.analysis.matgenlab.command_line.bader_caller.*
            fixture = testCase.fixture("ACF.dat");
            cube = testCase.fixture("elec.cube.gz");
            nelects = [repmat(8, 1, 6), repmat(6, 1, 8)];
            analysis = BaderAnalysis("", "", "", cube, "", false, ...
                acf_text = fileread(fixture), nelects = nelects);
            expected = testCase.oracle();
            testCase.verifyEqual(numel(analysis.data), 14);
            names = ["x", "y", "z", "charge", ...
                "min_dist", "atomic_vol"];
            for index = 1:numel(analysis.data)
                for name = names
                    testCase.verifyEqual( ...
                        analysis.data(index).(name), ...
                        expected.data(index).(name), AbsTol = 1e-12);
                end
                testCase.verifyEqual( ...
                    analysis.get_charge_transfer(index), ...
                    expected.charge_transfer(index), AbsTol = 1e-12);
                testCase.verifyEqual( ...
                    analysis.get_partial_charge(index), ...
                    expected.partial_charge(index), AbsTol = 1e-12);
            end
            testCase.verifyEqual(analysis.nelectrons, ...
                expected.nelectrons);
            testCase.verifyEqual(analysis.vacuum_charge, ...
                expected.vacuum_charge);
            testCase.verifyEqual(analysis.vacuum_volume, ...
                expected.vacuum_volume);
            testCase.verifyEqual(analysis.get_charge(1), 6.6136782);
        end

        function decorationSemanticsMatchUpstream(testCase)
            import kssolv.analysis.matgenlab.command_line.bader_caller.*
            [chgcar, folder, cleanup] = ...
                testCase.temporaryChgcar(false); %#ok<ASGLU>
            path = fullfile(folder, "CHGCAR");
            chgcar.write_file(path);
            analysis = BaderAnalysis(path, "", "", "", "", false, ...
                acf_text = testCase.twoAtomAcf(), nelects = [1, 6]);

            charged = analysis.get_charge_decorated_structure();
            testCase.verifyEqual(cell2mat( ...
                charged.site_properties.charge), [-.8, -5.5]);

            oxidized = ...
                analysis.get_oxidation_state_decorated_structure();
            testCase.verifyEqual(oxidized(1).specie.oxi_state, .2, ...
                AbsTol = 1e-14);
            testCase.verifyEqual(oxidized(2).specie.oxi_state, .5, ...
                AbsTol = 1e-14);

            integrated = analysis.get_decorated_structure("potential");
            testCase.verifyEqual(cell2mat( ...
                integrated.site_properties.potential), [.8, 5.5]);
            averaged = analysis.get_decorated_structure( ...
                "potential", true);
            testCase.verifyEqual(cell2mat( ...
                averaged.site_properties.potential), [.08, .275], ...
                AbsTol = 1e-14);
            spin = analysis.get_decorated_structure("spin");
            testCase.verifyEqual(spin(1).specie.spin, .8);
            clear cleanup
        end

        function explicitExecutorBoundaryIsStable(testCase)
            import kssolv.analysis.matgenlab.command_line.bader_caller.*
            [chgcar, folder, cleanup] = ...
                testCase.temporaryChgcar(false); %#ok<ASGLU>
            path = fullfile(folder, "CHGCAR");
            chgcar.write_file(path);
            testCase.verifyError(@() BaderAnalysis(path), ...
                "KSSOLV:Matgenlab:Bader:ExecutorRequired");
            bad = @(~) struct("stdout", "failed", ...
                "stderr", "bad grid", "status", 9, ...
                "acf_text", testCase.twoAtomAcf());
            testCase.verifyError(@() BaderAnalysis(path, "", "", ...
                "", "/opt/bader", false, executor = bad), ...
                "KSSOLV:Matgenlab:Bader:Execution");

            density = struct("data", ones(2, 2, 2), ...
                "shift", [0, 1, -1], "dim", [2, 2, 2]);
            seen = struct();
            good = @capture;
            analysis = BaderAnalysis(path, "", "reference", "", ...
                "/opt/bader", true, executor = good);
            testCase.verifyEqual(analysis.version, 1.05);
            testCase.verifyTrue(analysis.reference_used);
            testCase.verifyEqual(numel(analysis.atomic_densities), 2);
            testCase.verifyEqual(seen.command, "/opt/bader");
            testCase.verifyEqual(seen.input_filename, string(path));
            testCase.verifyTrue(seen.parse_atomic_densities);
            summary = analysis.summary;
            testCase.verifyTrue(isfield(summary, "charge_densities"));
            clear cleanup

            function result = capture(request)
                seen = request;
                result = struct("stdout", "Bader version 1.05", ...
                    "stderr", "", "status", 0, ...
                    "acf_text", testCase.twoAtomAcf(), ...
                    "atomic_densities", {{density, density}});
            end
        end

        function fromPathUsesSuffixAndInjectedRunner(testCase)
            import kssolv.analysis.matgenlab.command_line.bader_caller.*
            [chgcar, folder, cleanup] = ...
                testCase.temporaryChgcar(false); %#ok<ASGLU>
            chgcar.write_file(fullfile(folder, "CHGCAR.relax"));
            chgcar.write_file(fullfile(folder, "CHGCAR.static"));
            runner = @(request) struct( ...
                "stdout", "Bader version 1.0", "stderr", "", ...
                "status", 0, "acf_text", testCase.twoAtomAcf(), ...
                "selected", request.input_filename);
            analysis = BaderAnalysis.from_path( ...
                folder, ".relax", "executor", runner);
            testCase.verifyEqual(analysis.version, 1);
            testCase.verifyEqual(analysis.summary.charge, [.8, 5.5]);
            summary = bader_analysis_from_path( ...
                folder, ".static", "executor", runner);
            testCase.verifyEqual(summary.atomic_volume, [10, 20]);
            clear cleanup
        end

        function objectWorkflowIncludesMagnetization(testCase)
            import kssolv.analysis.matgenlab.command_line.bader_caller.*
            [chgcar, ~, cleanup] = ...
                testCase.temporaryChgcar(true); %#ok<ASGLU>
            callCount = 0;
            runner = @execute;
            summary = bader_analysis_from_objects( ...
                chgcar, [], [], [], "executor", runner);
            testCase.verifyEqual(callCount, 2);
            testCase.verifyEqual(summary.charge, [.8, 5.5]);
            testCase.verifyEqual(summary.magmom, [.2, -.1]);
            testCase.verifyFalse(summary.reference_used);
            clear cleanup

            function result = execute(request)
                callCount = callCount + 1;
                if endsWith(request.input_filename, "CHGCAR_mag")
                    acf = testCase.twoAtomAcf([.2, -.1]);
                else
                    acf = testCase.twoAtomAcf();
                end
                result = struct("stdout", "Bader version 1.0", ...
                    "stderr", "", "status", 0, "acf_text", acf);
            end
        end

        function validationAndCubeInput(testCase)
            import kssolv.analysis.matgenlab.command_line.bader_caller.*
            testCase.verifyError(@() BaderAnalysis(), ...
                "KSSOLV:Matgenlab:Bader:InputRequired");
            testCase.verifyError(@() BaderAnalysis("a", "", "", "b"), ...
                "KSSOLV:Matgenlab:Bader:ConflictingInputs");
            analysis = BaderAnalysis("", "", "", ...
                testCase.fixture("elec.cube.gz"), "", false, ...
                acf_text = testCase.twoAtomAcf());
            testCase.verifyEqual(analysis.structure.num_sites, 9);
            testCase.verifyError(@() ...
                analysis.get_charge_transfer(1), ...
                "KSSOLV:Matgenlab:Bader:NoNelect");
            testCase.verifyEqual( ...
                analysis.get_charge_transfer(1, 1), -.2, ...
                AbsTol = 1e-14);
            testCase.verifyError(@() analysis.get_charge(3), ...
                "KSSOLV:Matgenlab:Bader:AtomIndex");
        end
    end

    methods (Static, Access = private)
        function value = fixture(name)
            value = fullfile(fileparts(mfilename("fullpath")), ...
                "+fixtures", "+bader", name);
        end

        function value = oracle()
            path = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "oracles", ...
                "bader_caller_2026.7.24.json");
            value = jsondecode(fileread(path));
        end

        function [chgcar, folder, cleanup] = temporaryChgcar(spin)
            import kssolv.analysis.matgenlab.core.*
            import kssolv.analysis.matgenlab.io.vasp.*
            structure = Structure(Lattice.cubic(4), ...
                {"Li", "O"}, [0, 0, 0; .5, .5, .5]);
            data = struct("total", reshape(1:8, 2, 2, 2));
            if spin
                data.diff = reshape(linspace(-1, 1, 8), 2, 2, 2);
            end
            chgcar = Chgcar(structure, data);
            folder = string(tempname);
            mkdir(folder);
            cleanup = onCleanup(@() rmdir(folder, "s"));
        end

        function text = twoAtomAcf(charges)
            if nargin < 1, charges = [.8, 5.5]; end
            format = join([ ...
                " # X Y Z CHARGE MIN DIST ATOMIC VOL\n" ...
                " -----------------------------------\n" ...
                " 1 0 0 0 %.8f 0.5 10\n" ...
                " 2 2 2 2 %.8f 0.7 20\n" ...
                " -----------------------------------\n" ...
                " VACUUM CHARGE: 0.01\n" ...
                " VACUUM VOLUME: 0.02\n" ...
                " NUMBER OF ELECTRONS: 6.3\n"], "");
            text = sprintf(char(format), charges(1), charges(2));
        end
    end
end
