classdef ChargemolCallerInventoryTest < matlab.unittest.TestCase
    % Frozen parity tests for pymatgen.command_line.chargemol_caller.

    methods (Test)
        function frozenInventoryHasAllSevenApis(testCase)
            package = "kssolv.analysis.matgenlab.command_line." + ...
                "chargemol_caller.";
            testCase.verifyNotEmpty(meta.class.fromName( ...
                package + "ChargemolAnalysis"));
            methodNames = string(methods(char(package + ...
                "ChargemolAnalysis")));
            testCase.verifyTrue(all(ismember([ ...
                "get_charge_transfer", "get_charge", ...
                "get_partial_charge", "get_bond_order", ...
                "get_property_decorated_structure"], methodNames)));
            propertyNames = string(properties(char(package + ...
                "ChargemolAnalysis")));
            testCase.verifyTrue(any(propertyNames == "summary"));

            inventory = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", "api.csv");
            rows = readtable(inventory, ...
                detectImportOptions(inventory, "TextType", "string"));
            testCase.verifyEqual(sum(rows.module == ...
                "pymatgen.command_line.chargemol_caller"), 7);
            oracle = testCase.oracle();
            testCase.verifyEqual(oracle.metadata.api_count, 7);
            testCase.verifyEqual(string(oracle.metadata.tag), ...
                "v2026.7.24");
        end

        function officialUnpolarizedOutputMatchesOracle(testCase)
            analysis = testCase.analysis("spin_unpolarized");
            expected = testCase.oracle().spin_unpolarized;
            testCase.verifyEqual(analysis.ddec_charges, ...
                reshape(expected.ddec_charges, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual(analysis.dipoles, ...
                expected.dipoles, AbsTol = 1e-12);
            testCase.verifyEqual(analysis.bond_order_sums, ...
                reshape(expected.bond_order_sums, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(analysis.ddec_rsquared_moments, ...
                reshape(expected.rsquared_moments, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(analysis.ddec_rcubed_moments, ...
                reshape(expected.rcubed_moments, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(analysis.ddec_rfourth_moments, ...
                reshape(expected.rfourth_moments, 1, []), ...
                AbsTol = 1e-12);
            testCase.verifyEqual(analysis.cm5_charges, ...
                reshape(expected.cm5_charges, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual(analysis.natoms, [1, 1]);
            testCase.verifyNotEmpty(analysis.structure);
            testCase.verifyEmpty(analysis.ddec_spin_moments);
        end

        function chargeAndBondConveniencesMatchUpstream(testCase)
            analysis = testCase.analysis("spin_unpolarized");
            testCase.verifyEqual(analysis.get_partial_charge(1), ...
                .8432, AbsTol = 1e-12);
            testCase.verifyEqual( ...
                analysis.get_partial_charge(1, "CM5"), ...
                .420172, AbsTol = 1e-12);
            testCase.verifyEqual(analysis.get_charge_transfer(1), ...
                -.8432, AbsTol = 1e-12);
            testCase.verifyEqual( ...
                analysis.get_charge_transfer(1, "cm5"), ...
                -.420172, AbsTol = 1e-12);
            testCase.verifyEqual(analysis.get_charge(1, 1), ...
                1 - .8432, AbsTol = 1e-12);
            testCase.verifyEqual(analysis.get_charge(1, 1, "cm5"), ...
                1 - .420172, AbsTol = 1e-12);
            testCase.verifyEqual(analysis.get_bond_order(1, 2), ...
                6 * .0882, AbsTol = 1e-12);
            testCase.verifyEqual(analysis.get_bond_order(2, 2), ...
                12 * .0306, AbsTol = 1e-12);

            first = analysis.bond_order_dict{1}.bonded_to(1);
            testCase.verifyEqual(first.index, 2);
            testCase.verifyEqual(first.direction, [-1, -1, 0]);
            testCase.verifyEqual(first.bond_order, .0882, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(first.spin_polarization, 0);
            testCase.verifyEqual(first.element.symbol, "Cl");
            testCase.verifyError(@() analysis.get_partial_charge(0), ...
                "KSSOLV:Matgenlab:Chargemol:AtomIndex");
            testCase.verifyError( ...
                @() analysis.get_partial_charge(1, "bad"), ...
                "KSSOLV:Matgenlab:Chargemol:ChargeType");
        end

        function summaryAndDecoratedStructureMatchUpstream(testCase)
            analysis = testCase.analysis("spin_unpolarized");
            summary = analysis.summary;
            testCase.verifyEqual(summary.ddec.partial_charges, ...
                analysis.ddec_charges);
            testCase.verifyEqual(summary.ddec.dipoles, ...
                analysis.dipoles);
            testCase.verifyEqual(summary.ddec.bond_order_sums, ...
                analysis.bond_order_sums);
            testCase.verifyEqual(summary.ddec.rsquared_moments, ...
                analysis.ddec_rsquared_moments);
            testCase.verifyEqual(summary.ddec.rcubed_moments, ...
                analysis.ddec_rcubed_moments);
            testCase.verifyEqual(summary.ddec.rfourth_moments, ...
                analysis.ddec_rfourth_moments);
            testCase.verifyFalse(isfield(summary.ddec, "spin_moments"));
            testCase.verifyEqual(summary.cm5.partial_charges, ...
                analysis.cm5_charges);

            decorated = analysis.get_property_decorated_structure();
            properties = decorated.site_properties;
            testCase.verifyEqual( ...
                cell2mat(properties.partial_charge_ddec6), ...
                analysis.ddec_charges);
            testCase.verifyEqual( ...
                vertcat(properties.dipole_ddec6{:}), ...
                analysis.dipoles);
            testCase.verifyEqual( ...
                cell2mat(properties.bond_order_sum_ddec6), ...
                analysis.bond_order_sums);
            testCase.verifyEqual( ...
                cell2mat(properties.partial_charge_cm5), ...
                analysis.cm5_charges);
        end

        function officialPolarizedOutputMatchesOracle(testCase)
            analysis = testCase.analysis("spin_polarized");
            expected = testCase.oracle().spin_polarized;
            testCase.verifyEqual(analysis.ddec_charges, ...
                reshape(expected.ddec_charges, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual(analysis.dipoles, ...
                expected.dipoles, AbsTol = 1e-12);
            testCase.verifyEqual(analysis.ddec_spin_moments, ...
                reshape(expected.spin_moments, 1, []), AbsTol = 1e-12);
            testCase.verifyEqual( ...
                analysis.bond_order_dict{1}. ...
                bonded_to(1).spin_polarization, .049, ...
                AbsTol = 1e-12);
            testCase.verifyEmpty(analysis.structure);
            testCase.verifyEmpty(analysis.natoms);
            testCase.verifyEmpty(analysis.cm5_charges);
            testCase.verifyEmpty(analysis.summary.cm5);
            testCase.verifyError( ...
                @() analysis.get_property_decorated_structure(), ...
                "KSSOLV:Matgenlab:Chargemol:MissingStructure");
        end

        function fileDiscoveryAndMissingOutputErrorsAreStable(testCase)
            import kssolv.analysis.matgenlab.command_line.chargemol_caller.ChargemolAnalysis
            folder = string(tempname);
            mkdir(folder);
            cleanup = onCleanup(@() rmdir(folder, "s"));
            fclose(fopen(fullfile(folder, "CHGCAR.relax"), "w"));
            fclose(fopen(fullfile(folder, "CHGCAR.static"), "w"));
            selected = ChargemolAnalysis.get_filepath(folder, "CHGCAR");
            testCase.verifyEqual(string(selected), ...
                string(fullfile(folder, "CHGCAR.static")));
            testCase.verifyEqual( ...
                ChargemolAnalysis.get_filepath(folder, "AECCAR0"), "");
            delete(fullfile(folder, "CHGCAR.relax"));
            delete(fullfile(folder, "CHGCAR.static"));
            testCase.verifyError(@() ChargemolAnalysis(folder, ...
                missing, false), ...
                "KSSOLV:Matgenlab:Chargemol:MissingOutput");
            clear cleanup;
        end

        function explicitExecutorBoundaryIsSafeAndInjectable(testCase)
            import kssolv.analysis.matgenlab.command_line.chargemol_caller.ChargemolAnalysis
            testCase.verifyError(@() ChargemolAnalysis("", ...
                missing, true), ...
                "KSSOLV:Matgenlab:Chargemol:ExecutorRequired");
            testCase.verifyError(@() ChargemolAnalysis("", ...
                missing, false, "", executor = 4), ...
                "KSSOLV:Matgenlab:Chargemol:ExecutorType");

            input = string(tempname);
            mkdir(input);
            cleanup = onCleanup(@() rmdir(input, "s"));
            source = testCase.fixture("spin_unpolarized");
            copyfile(fullfile(source, "CHGCAR.gz"), ...
                fullfile(input, "CHGCAR.gz"));
            copyfile(fullfile(source, "CHGCAR.gz"), ...
                fullfile(input, "AECCAR0.gz"));
            copyfile(fullfile(source, "CHGCAR.gz"), ...
                fullfile(input, "AECCAR2.gz"));
            potcar = testCase.fixture( ...
                fullfile("executor_inputs", "POTCAR_C2.gz"));
            copyfile(potcar, fullfile(input, "POTCAR.gz"));
            executor = @(request) testCase.fakeExecutor(request, source);
            analysis = ChargemolAnalysis(input, input, true, "", ...
                executor = executor);
            testCase.verifyEqual(analysis.ddec_charges, ...
                [.8432, -.8432], AbsTol = 1e-12);

            failed = @(~) struct("status", 9, "stderr", "bad", ...
                "stdout", "failed", "output_path", source);
            testCase.verifyError(@() ChargemolAnalysis(input, input, ...
                true, "", executor = failed), ...
                "KSSOLV:Matgenlab:Chargemol:Execution");
            clear cleanup;
        end
    end

    methods (Static, Access = private)
        function analysis = analysis(name)
            import kssolv.analysis.matgenlab.command_line.chargemol_caller.ChargemolAnalysis
            path = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "+kssolv", "+analysis", "+matgenlab", "+test", ...
                "+command_line", "+fixtures", "+chargemol", name);
            analysis = ChargemolAnalysis(path, missing, false);
        end

        function path = fixture(name)
            path = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "+kssolv", "+analysis", "+matgenlab", "+test", ...
                "+command_line", "+fixtures", "+chargemol", name);
        end

        function value = oracle()
            path = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "oracles", ...
                "chargemol_caller_2026.7.24.json");
            value = jsondecode(fileread(path));
        end

        function result = fakeExecutor(request, outputPath)
            if ~contains(request.job_control_text, "DDEC6") || ...
                    request.command ~= "chargemol"
                error("KSSOLV:Matgenlab:Chargemol:TestExecutor", ...
                    "Malformed injected Chargemol request.");
            end
            result = struct("status", 0, "stdout", "ok", ...
                "stderr", "", "output_path", outputPath);
        end
    end
end
