classdef Critic2CallerInventoryTest < matlab.unittest.TestCase
    % Frozen parity tests for pymatgen.command_line.critic2_caller.

    methods (Test)
        function frozenInventoryHasAllThirteenApis(testCase)
            package = "kssolv.analysis.matgenlab.command_line." + ...
                "critic2_caller.";
            classes = ["Critic2Caller", "CriticalPointType", ...
                "CriticalPoint", "Critic2Analysis"];
            for name = classes
                testCase.verifyNotEmpty(meta.class.fromName(package + name));
            end
            callerMethods = string(methods(char(package + ...
                "Critic2Caller")));
            testCase.verifyTrue(all(ismember( ...
                ["from_chgcar", "from_path"], callerMethods)));
            testCase.verifyNotEmpty(which(package + "get_filepath"));
            pointProperties = string(properties(char(package + ...
                "CriticalPoint")));
            testCase.verifyTrue(all(ismember( ...
                ["type", "laplacian", "ellipticity"], ...
                pointProperties)));
            analysisMethods = string(methods(char(package + ...
                "Critic2Analysis")));
            testCase.verifyTrue(all(ismember( ...
                ["structure_graph", "get_critical_point_for_site", ...
                "get_volume_and_charge_for_site"], analysisMethods)));

            inventory = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", "api.csv");
            rows = readtable(inventory, ...
                detectImportOptions(inventory, "TextType", "string"));
            selected = rows.module == ...
                "pymatgen.command_line.critic2_caller";
            testCase.verifyEqual(sum(selected), 13);
            oracle = testCase.oracle();
            testCase.verifyEqual(oracle.metadata.api_count, 13);
            testCase.verifyEqual(string(oracle.metadata.tag), "v2026.7.24");
        end

        function officialLegacyStdoutMatchesOracle(testCase)
            [analysis, oracle] = testCase.officialAnalysis("legacy", ...
                "MoS2_critic2_stdout.txt");
            testCase.verifyParsedAnalysis(analysis, oracle);
        end

        function officialNewStdoutFormatMatchesOracle(testCase)
            [analysis, oracle] = testCase.officialAnalysis("new_format", ...
                "MoS2_critic2_stdout_new_format.txt");
            testCase.verifyParsedAnalysis(analysis, oracle);
        end

        function graphMatchesOfficialTopologyAndFieldData(testCase)
            [analysis, oracle] = testCase.officialAnalysis("legacy", ...
                "MoS2_critic2_stdout.txt");
            graph = analysis.structure_graph();
            testCase.verifyEqual(graph.structure.num_sites, ...
                oracle.graph.site_count);
            testCase.verifyEqual(graph.graph.number_of_edges(), ...
                oracle.graph.edge_count);
            testCase.verifyEqual( ...
                graph.structure(4).species_string, ...
                string(oracle.graph.fourth_species));
            expected = sort([oracle.graph.edges.weight]);
            actual = sort([graph.graph.edges.weight]);
            testCase.verifyEqual(actual, expected, AbsTol = 3e-5);
            first = graph.graph.edges(1).edge_properties;
            testCase.verifyEqual(sort(string(fieldnames(first))), ...
                sort(["field"; "laplacian"; "ellipticity"; ...
                "frac_coords"]));

            nucleiOnly = analysis.structure_graph([]);
            testCase.verifyEqual(nucleiOnly.structure.num_sites, 3);
            testCase.verifyEqual(nucleiOnly.graph.number_of_edges(), 6);
            testCase.verifyEqual( ...
                analysis.get_critical_point_for_site(1).type, ...
                kssolv.analysis.matgenlab.command_line.critic2_caller. ...
                CriticalPointType.nucleus);
            testCase.verifyEmpty( ...
                analysis.get_volume_and_charge_for_site(1));
        end

        function cpreportAndYtNativeJsonPath(testCase)
            import kssolv.analysis.matgenlab.command_line.critic2_caller.*
            import kssolv.analysis.matgenlab.core.*
            structure = Structure(Lattice.cubic(4), ...
                {"Li", "O"}, [0, 0, 0; .5, .5, .5]);
            report = testCase.syntheticCpreport();
            yt = testCase.syntheticYt();
            analysis = Critic2Analysis(structure, "", "", report, yt, ...
                struct("Li", 1, "O", 6));
            testCase.verifyEqual(numel(analysis.critical_points), 3);
            testCase.verifyEqual(analysis.critical_points{3}.type, ...
                CriticalPointType.bond);
            testCase.verifyEqual(analysis.critical_points{3}.coords, ...
                [1, 1, 1] * 0.529177210903, AbsTol = 1e-14);
            testCase.verifyEqual(analysis.critical_points{3}.laplacian, 0);
            testCase.verifyEqual(analysis.critical_points{3}.ellipticity, 0);
            properties = analysis.structure.site_properties;
            testCase.verifyEqual(cell2mat(properties.bader_volume), [10, 20]);
            testCase.verifyEqual(cell2mat(properties.bader_charge), [.8, 5.5]);
            testCase.verifyEqual( ...
                cell2mat(properties.bader_charge_transfer), [-.2, -.5], ...
                AbsTol = 1e-14);
            testCase.verifyEqual( ...
                analysis.get_volume_and_charge_for_site(2), ...
                struct("volume", 20, "charge", 5.5));
            graph = analysis.structure_graph();
            testCase.verifyEqual(graph.graph.number_of_edges(), 1);
            testCase.verifyEqual(graph.get_coordination_of_site(1), 1);
        end

        function explicitExecutorBoundaryAndInputScript(testCase)
            import kssolv.analysis.matgenlab.command_line.critic2_caller.*
            testCase.verifyError(@() Critic2Caller("auto"), ...
                "KSSOLV:Matgenlab:Critic2:ExecutorRequired");
            [structure, stdout] = testCase.officialInput( ...
                "MoS2_critic2_stdout.txt");
            executor = @(request) struct( ...
                "stdout", stdout, "stderr", "", "status", 0, ...
                "request_command", request.command);
            caller = Critic2Caller.from_chgcar(structure, ...
                struct("fixture", true), [], struct("GRADEPS", .2), ...
                true, true, struct("Mo", 6, "S", 6), ...
                "executor", executor);
            testCase.verifyTrue(contains(caller.input_script, ...
                "load int.CHGCAR id chg_int zpsp Mo 6 S 6"));
            testCase.verifyTrue(contains(caller.input_script, ...
                "auto CPEPS 0.1 SEED WS SEED PAIR DIST 10 " + ...
                "GRADEPS 0.2 "));
            testCase.verifyTrue(contains(caller.input_script, ...
                "cpreport ../table.cml cell border graph"));
            testCase.verifyTrue(contains(caller.input_script, ...
                "yt JSON yt.json"));
            testCase.verifyClass(caller.output, ...
                "kssolv.analysis.matgenlab.command_line." + ...
                "critic2_caller.Critic2Analysis");
            failing = @(~) struct("stdout", "failure", ...
                "stderr", "bad", "status", 7);
            testCase.verifyError(@() Critic2Caller("auto", ...
                executor = failing), ...
                "KSSOLV:Matgenlab:Critic2:Execution");
        end

        function criticalPointSerializationAndFileSelection(testCase)
            import kssolv.analysis.matgenlab.command_line.critic2_caller.*
            point = CriticalPoint(4, "bond", [.1, .2, .3], ...
                "C2v", 2, .75, 1e-12, [1, 2, 3], ...
                diag([-3, -2, 7]));
            testCase.verifyEqual(point.laplacian, 2);
            testCase.verifyEqual(point.ellipticity, .5);
            restored = CriticalPoint.from_dict(point.as_dict());
            testCase.verifyEqual(string(restored.type), "bond");
            testCase.verifyEqual(restored.field_hessian, point.field_hessian);

            folder = string(tempname);
            mkdir(folder);
            cleanup = onCleanup(@() rmdir(folder, "s"));
            fclose(fopen(fullfile(folder, "CHGCAR.relax"), "w"));
            fclose(fopen(fullfile(folder, "CHGCAR.static"), "w"));
            selected = get_filepath("CHGCAR", "missing", folder, "");
            testCase.verifyTrue(endsWith(selected, "CHGCAR.static"));
            missing = get_filepath("POTCAR", "missing", folder, "");
            testCase.verifyEqual(missing, "");
            clear cleanup
        end

        function analysisSerializationRoundTrip(testCase)
            [analysis, ~] = testCase.officialAnalysis("legacy", ...
                "MoS2_critic2_stdout.txt");
            restored = kssolv.analysis.matgenlab.command_line. ...
                critic2_caller.Critic2Analysis.from_dict( ...
                analysis.as_dict());
            testCase.verifyEqual(numel(restored.critical_points), 6);
            testCase.verifyEqual(restored.edges{4}, analysis.edges{4});
            testCase.verifyEqual(restored.structure.frac_coords, ...
                analysis.structure.frac_coords, AbsTol = 1e-12);
        end
    end

    methods (Access = private)
        function [analysis, expected] = officialAnalysis( ...
                testCase, oracleField, filename)
            [structure, stdout] = testCase.officialInput(filename);
            analysis = kssolv.analysis.matgenlab.command_line. ...
                critic2_caller.Critic2Analysis(structure, stdout);
            oracle = testCase.oracle();
            expected = oracle.(oracleField);
        end

        function [structure, stdout] = officialInput(~, filename)
            folder = fullfile(fileparts(mfilename("fullpath")), ...
                "+fixtures", "+critic2");
            structure = kssolv.analysis.matgenlab.core.Structure. ...
                from_file(fullfile(folder, "MoS2.cif"));
            stdout = string(fileread(fullfile(folder, filename)));
        end

        function verifyParsedAnalysis(testCase, actual, expected)
            testCase.verifyEqual(numel(actual.critical_points), ...
                numel(expected.critical_points));
            testCase.verifyEqual(nnz(~cellfun(@isempty, actual.nodes)), ...
                numel(expected.nodes));
            testCase.verifyEqual(nnz(~cellfun(@isempty, actual.edges)), ...
                numel(expected.edges));
            for index = 1:numel(expected.critical_points)
                point = actual.critical_points{index};
                reference = expected.critical_points(index);
                testCase.verifyEqual(point.index, reference.index + 1);
                testCase.verifyEqual(string(point.type), ...
                    string(reference.type));
                testCase.verifyEqual(point.frac_coords, ...
                    reshape(reference.frac_coords, 1, 3), AbsTol = 1e-12);
                testCase.verifyEqual(point.field, reference.field, ...
                    RelTol = 2e-12);
                testCase.verifyEqual(point.field_hessian, ...
                    reference.field_hessian, RelTol = 2e-12);
                testCase.verifyEqual(point.laplacian, ...
                    reference.laplacian, RelTol = 2e-12);
                testCase.verifyEqual(point.ellipticity, ...
                    reference.ellipticity, AbsTol = 2e-12);
            end
            for index = 1:numel(expected.nodes)
                reference = expected.nodes(index);
                node = actual.nodes{reference.index + 1};
                testCase.verifyEqual(node.unique_idx, ...
                    reference.unique_idx + 1);
                testCase.verifyEqual(node.frac_coords, ...
                    reshape(reference.frac_coords, 1, 3), AbsTol = 1e-12);
            end
            for index = 1:numel(expected.edges)
                reference = expected.edges(index);
                edge = actual.edges{reference.index + 1};
                testCase.verifyEqual(edge.from_idx, ...
                    reference.from_idx + 1);
                testCase.verifyEqual(edge.to_idx, reference.to_idx + 1);
                testCase.verifyEqual(edge.from_lvec, ...
                    reshape(reference.from_lvec, 1, 3));
                testCase.verifyEqual(edge.to_lvec, ...
                    reshape(reference.to_lvec, 1, 3));
            end
        end

        function value = oracle(~)
            filename = fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "oracles", ...
                "critic2_caller_2026.7.24.json");
            value = jsondecode(fileread(filename));
        end

        function report = syntheticCpreport(~)
            common = struct("id", 0, "signature", -3, ...
                "is_nucleus", true, ...
                "fractional_coordinates", [0, 0, 0], ...
                "cartesian_coordinates", [0, 0, 0], ...
                "point_group", "Oh", "multiplicity", 1, ...
                "field", 1, "gradient", 0, "hessian", -eye(3));
            first = common;
            first.id = 1;
            second = common;
            second.id = 2;
            second.fractional_coordinates = [.5, .5, .5];
            second.cartesian_coordinates = [2, 2, 2];
            third = common;
            third.id = 3;
            third.signature = -1;
            third.is_nucleus = false;
            third.fractional_coordinates = [.25, .25, .25];
            third.cartesian_coordinates = [1, 1, 1];
            third.point_group = "C2v";
            third.field = .5;
            third.hessian = diag([-2, -2, 4]);
            attractors = [ ...
                struct("cell_id", 1, "lvec", [0, 0, 0]), ...
                struct("cell_id", 2, "lvec", [0, 0, 0])];
            cells = [ ...
                struct("id", 1, "nonequivalent_id", 1, ...
                "fractional_coordinates", [0, 0, 0], ...
                "attractors", []), ...
                struct("id", 2, "nonequivalent_id", 2, ...
                "fractional_coordinates", [.5, .5, .5], ...
                "attractors", []), ...
                struct("id", 3, "nonequivalent_id", 3, ...
                "fractional_coordinates", [.25, .25, .25], ...
                "attractors", attractors)];
            report = struct("units", "bohr", ...
                "critical_points", struct( ...
                "nonequivalent_cps", [first, second, third], ...
                "cell_cps", cells));
        end

        function yt = syntheticYt(~)
            properties = [ ...
                struct("id", 1, "label", "Volume"), ...
                struct("id", 2, "label", "$chg_int")];
            attractors = [ ...
                struct("id", 1, "integrals", [10, .8]), ...
                struct("id", 2, "integrals", [20, 5.5])];
            atoms = [ ...
                struct("nonequivalent_id", 1, ...
                "fractional_coordinates", [0, 0, 0]), ...
                struct("nonequivalent_id", 2, ...
                "fractional_coordinates", [.5, .5, .5])];
            yt = struct("integration", struct( ...
                "properties", properties, "attractors", attractors), ...
                "structure", struct("cell_atoms", atoms));
        end
    end
end
