classdef GulpCallerTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 oracle tests for gulp_caller.

    methods (Test)
        function frozenInventorySurfaceIsImplemented(testCase)
            ledger = readtable(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "dev", "matgenlab", "inventory", ...
                "compatibility_ledger.csv"), TextType = "string", ...
                Delimiter = ",");
            rows = ledger(ledger.module == ...
                "pymatgen.command_line.gulp_caller", :);
            testCase.verifyEqual(height(rows), 20);
            testCase.verifyTrue(all(rows.status == "implemented"), ...
                join(rows.api_id(rows.status ~= "implemented"), newline));
        end

        function keywordAndStructureTextMatchFrozenOracle(testCase)
            io = gulpIO();
            structure = mgO();
            testCase.verifyEqual(io.keyword_line("optimise", "conp"), ...
                "optimise conp" + newline);
            expected = join(["cell"; ...
                "4.212000 4.212000 4.212000 90.000000 90.000000 90.000000"; ...
                "frac"; "Mg core 0.0 0.0 0.0"; ...
                "O core 0.5 0.5 0.5"; "O shel 0.5 0.5 0.5"; ""], ...
                newline);
            testCase.verifyEqual(io.structure_lines( ...
                structure, symm_flg = false), expected);
            cartesian = io.structure_lines(structure, ...
                cell_flg = false, frac_flg = false, symm_flg = false);
            testCase.verifyEqual(cartesian, join(["cart"; ...
                "Mg core 0.0 0.0 0.0"; ...
                "O core 2.106 2.106 2.106"; ...
                "O shel 2.106 2.106 2.106"; ""], newline));
        end

        function potentialTablesAndDispatchAreFunctional(testCase)
            bush = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                BuckinghamPotential("bush");
            testCase.verifyTrue(bush.species_dict.isKey("Mg"));
            testCase.verifyEqual(bush.species_dict("Mg").oxi, 2);
            testCase.verifyEqual(bush.spring_dict("Li"), "");
            lewis = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                BuckinghamPotential("lewis");
            testCase.verifyTrue(lewis.species_dict.isKey("Sc_2+"));
            testCase.verifyTrue(lewis.species_dict.isKey("O_core"));
            tersoff = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                TersoffPotential();
            testCase.verifyTrue(tersoff.data.isKey("Mg(2)"));
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                BuckinghamPotential("invalid"), ...
                "KSSOLV:Matgenlab:GULP:PotentialFlag");

            values = containers.Map({'Mg', 'O'}, {2, -2});
            buckingham = gulpIO().specie_potential_lines( ...
                mgO(), "buckingham", valence_dict = values);
            testCase.verifyTrue(contains(buckingham, "Mg core"));
            testCase.verifyTrue(contains(buckingham, "O  shel"));
            testCase.verifyError(@() gulpIO().specie_potential_lines( ...
                mgO(), "unknown"), "KSSOLV:Matgenlab:GULP:Error");
        end

        function buckinghamAndTersoffInputsContainOracleSections(testCase)
            values = containers.Map({'Mg', 'O'}, {2, -2});
            buckingham = gulpIO().buckingham_input( ...
                mgO(), ["optimise", "conp"], valence_dict = values);
            testCase.verifyTrue(startsWith(buckingham, ...
                "optimise conp" + newline + "cell"));
            testCase.verifyTrue(contains(buckingham, "buckingham "));
            testCase.verifyTrue(contains(buckingham, "spring "));
            tersoff = gulpIO().tersoff_potential(mgO());
            testCase.verifyTrue(contains(tersoff, "Mg core 2"));
            testCase.verifyTrue(contains(tersoff, ...
                "Mg Mg 0.6000 10.0000"));
            testCase.verifyTrue(contains(tersoff, ...
                "O Mg 1.57554 1.953125 1.95627"));
        end

        function libraryResolutionAndErrorsAreSafe(testCase)
            path = string(tempname) + ".lib";
            cleanup = onCleanup(@() deleteIfPresent(path));
            identifier = fopen(path, "w");
            fwrite(identifier, "species" + newline);
            fclose(identifier);
            testCase.verifyEqual(gulpIO().library_line(path), ...
                "library " + path + newline);
            testCase.verifyError(@() gulpIO().library_line( ...
                "definitely_missing.lib"), ...
                "KSSOLV:Matgenlab:GULP:Error");
            clear cleanup
        end

        function outputParsersMatchOfficialFrozenOracle(testCase)
            output = fileread(gulpFixture("example21_excerpt.gout"));
            testCase.verifyEqual(gulpIO().get_energy(output), ...
                -169.06277218, AbsTol = 1e-12);
            relaxed = gulpIO().get_relaxed_structure(output);
            testCase.verifyEqual(relaxed.num_sites, 8);
            testCase.verifyEqual(relaxed.lattice.a, 4.212, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(relaxed.lattice.alpha, 90, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(relaxed.frac_coords(2, :), ...
                [0, 0.5, 0.5], AbsTol = 1e-14);
            testCase.verifyError(@() gulpIO().get_energy("no energy"), ...
                "KSSOLV:Matgenlab:GULP:Error");
            testCase.verifyError(@() ...
                gulpIO().get_relaxed_structure("no structure"), ...
                "KSSOLV:Matgenlab:GULP:NoStructure");
        end

        function callerRequiresExplicitExecutor(testCase)
            caller = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                GulpCaller("gulp");
            testCase.verifyError(@() caller.run("input"), ...
                "KSSOLV:Matgenlab:GULP:Error");
            caller = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                GulpCaller("gulp", executor = @successExecutor);
            testCase.verifyEqual(caller.run("input"), "ok" + newline);
            singleArgument = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                GulpCaller("gulp", executor = @(~) "single");
            testCase.verifyEqual(singleArgument.run("input"), ...
                "single" + newline);
        end

        function callerClassifiesExternalFailures(testCase)
            namespace = ...
                "kssolv.analysis.matgenlab.command_line.gulp_caller.";
            errorCaller = feval(namespace + "GulpCaller", "gulp", ...
                executor = @stderrExecutor);
            testCase.verifyError(@() errorCaller.run("input"), ...
                "KSSOLV:Matgenlab:GULP:Error");
            outputCaller = feval(namespace + "GulpCaller", "gulp", ...
                executor = @(~,~) "ERROR bad input");
            testCase.verifyError(@() outputCaller.run("input"), ...
                "KSSOLV:Matgenlab:GULP:Error");
            convergence = feval(namespace + "GulpCaller", "gulp", ...
                executor = @(~,~) ...
                "Conditions for a minimum have not been satisfied");
            testCase.verifyError(@() convergence.run("input"), ...
                "KSSOLV:Matgenlab:GULP:Convergence");
        end

        function globalBuckinghamWrappersUseInjectedExecutor(testCase)
            caller = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                GulpCaller("gulp", executor = @fixtureExecutor);
            values = containers.Map({'Mg', 'O'}, {2, -2});
            energy = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                get_energy_buckingham(mgO(), caller, ...
                valence_dict = values);
            testCase.verifyEqual(energy, -169.06277218, ...
                AbsTol = 1e-12);
            [energy, relaxed] = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                get_energy_relax_structure_buckingham( ...
                mgO(), caller, valence_dict = values);
            testCase.verifyEqual(energy, -169.06277218, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(relaxed.num_sites, 8);
        end

        function globalTersoffWrapperUsesInjectedExecutor(testCase)
            caller = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                GulpCaller("gulp", executor = @fixtureExecutor);
            energy = ...
                kssolv.analysis.matgenlab.command_line.gulp_caller. ...
                get_energy_tersoff(mgO(), caller);
            testCase.verifyEqual(energy, -169.06277218, ...
                AbsTol = 1e-12);
        end
    end
end

function io = gulpIO()
io = kssolv.analysis.matgenlab.command_line.gulp_caller.GulpIO();
end

function structure = mgO()
structure = kssolv.analysis.matgenlab.core.Structure( ...
    4.212 * eye(3), {"Mg", "O"}, [0, 0, 0; 0.5, 0.5, 0.5]);
end

function path = gulpFixture(name)
path = fullfile(KSSOLV_Toolbox.RootDirectory, "+kssolv", "+analysis", ...
    "+matgenlab", "+test", "+command_line", "+fixtures", "+gulp", name);
end

function result = successExecutor(~, ~)
result = "ok";
end

function result = stderrExecutor(~, ~)
result = struct("stdout", "", "stderr", "Error: failed", "status", 1);
end

function result = fixtureExecutor(~, ~)
result = string(fileread(gulpFixture("example21_excerpt.gout")));
end

function deleteIfPresent(path)
if isfile(path), delete(path); end
end
