classdef McsqsCallerInventoryTest < matlab.unittest.TestCase
    methods (TestMethodTeardown)
        function clearExecutor(~)
            kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                set_executor([]);
        end
    end

    methods (Test)
        function executorReceivesCompleteSearchContract(testCase)
            structure = disorderedStructure();
            kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                set_executor(@successfulExecutor);
            result = kssolv.analysis.matgenlab.command_line. ...
                mcsqs_caller.run_mcsqs(structure, [2, 6; 3, 4], ...
                [2, 1, 1], 0.01, "work", 4, 2, 3, 4, 0.6, 1e-4);
            testCase.verifyClass(result, ...
                "kssolv.analysis.matgenlab.command_line.mcsqs_caller.Sqs");
            testCase.verifyEqual(result.bestsqs, structure);
            testCase.verifyEqual(result.objective_function, "Perfect_match");
            testCase.verifyEqual(result.directory, "work");
            testCase.verifyEqual(result.clusters, [2, 6; 3, 4]);
            serialized = result.as_dict();
            testCase.verifyEqual(serialized.objective_function, ...
                "Perfect_match");
        end

        function orderedAndFractionalScalingAreRejected(testCase)
            ordered = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3), {"Si"}, [0, 0, 0]);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                run_mcsqs(ordered, [2, 3]), ...
                "KSSOLV:Matgenlab:Mcsqs:Ordered");
            kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                set_executor(@successfulExecutor);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                run_mcsqs(disorderedStructure(), [2, 3], 1.5), ...
                "KSSOLV:Matgenlab:Mcsqs:Scaling");
        end

        function missingAndInvalidExecutorsAreStable(testCase)
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                run_mcsqs(disorderedStructure(), [2, 3]), ...
                "KSSOLV:Matgenlab:Mcsqs:ExecutorRequired");
            kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                set_executor(@(~) struct());
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.command_line.mcsqs_caller. ...
                run_mcsqs(disorderedStructure(), [2, 3]), ...
                "KSSOLV:Matgenlab:Mcsqs:ExecutorResult");
        end
    end
end

function structure = disorderedStructure()
mixed = struct("Ti", 0.5, "Zr", 0.5);
structure = kssolv.analysis.matgenlab.core.Structure( ...
    eye(3) * 4, {mixed}, [0, 0, 0]);
end

function response = successfulExecutor(request)
assert(isequal(request.scaling, [2, 1, 1]));
assert(request.instances == 4);
assert(request.temperature == 2);
assert(request.wr == 3 && request.wn == 4);
assert(request.wd == 0.6 && request.tol == 1e-4);
response = struct("bestsqs", request.structure, ...
    "objective_function", "Perfect_match", "allsqs", {{}}, ...
    "clusters", request.clusters, "directory", request.directory);
end
