classdef PolymerCommands
    %POLYMERCOMMANDS Command adapters for deterministic polymer builders.
    methods (Static)
        function ids=commandIds()
            ids=["build_homopolymer";"build_block_copolymer"; ...
                "build_random_copolymer";"build_branched_polymer"; ...
                "build_dendrimer"; ...
                "save_user_repeat_unit"];
        end
        function value=supports(id)
            value=any(kssolv.modeling.polymers.PolymerCommands.commandIds()==string(id));
        end
        function estimate=estimate(id,p)
            %ESTIMATE Conservative pre-construction atom-count summary.
            import kssolv.modeling.ParameterUtils
            id=string(id);
            chainCount=double(ParameterUtils.get(p,"chainCount",1));
            switch id
                case "build_homopolymer"
                    unit=unitSize(ParameterUtils.get(p,"repeatUnit","PE"),p);
                    heavy=unit*double(ParameterUtils.get(p,"repeatCount",10));
                    heavy=heavy+endGroupSize(p);
                    upper=3*heavy*chainCount;
                case "build_block_copolymer"
                    kinds=parseKinds(ParameterUtils.get(p,"blockKinds", ...
                        ["PEO","PPO","PEO"]));
                    lengths=reshape(double(ParameterUtils.get( ...
                        p,"blockLengths",[5,10,5])),1,[]);
                    if numel(kinds)~=numel(lengths)
                        error("KSSOLV:Modeling:PolymerBlocks", ...
                            "Block kinds and lengths must align.");
                    end
                    sizes=arrayfun(@(kind)unitSize(kind,p),kinds);
                    heavy=sum(sizes.*lengths)*double(ParameterUtils.get( ...
                        p,"superunitCount",1))+endGroupSize(p);
                    upper=3*heavy*chainCount;
                case "build_random_copolymer"
                    kinds=parseKinds(ParameterUtils.get(p,"monomerKinds", ...
                        ["PE","PP"]));
                    sizes=arrayfun(@(kind)unitSize(kind,p),kinds);
                    heavy=max(sizes)*double(ParameterUtils.get( ...
                        p,"repeatCount",20))+endGroupSize(p);
                    upper=3*heavy*chainCount;
                case "build_branched_polymer"
                    count=double(ParameterUtils.get(p,"repeatCount",20));
                    interval=double(ParameterUtils.get(p,"branchInterval",4));
                    backbone=unitSize(ParameterUtils.get( ...
                        p,"repeatUnit","PE"),p)*count;
                    fragment=kssolv.modeling.fragments.FragmentLibrary.get( ...
                        string(ParameterUtils.get(p,"branchFragment","Methyl")));
                    heavy=backbone+floor(max(count-1,0)/interval)* ...
                        numel(fragment.species);
                    upper=3*heavy;
                case "build_dendrimer"
                    generations=double(ParameterUtils.get(p,"generations",2));
                    core=double(ParameterUtils.get(p,"coreFunctionality",3));
                    branching=double(ParameterUtils.get(p,"branchingFactor",2));
                    heavy=1+sum(core*branching.^(0:generations-1));
                    upper=4*heavy;
                otherwise
                    estimate=struct.empty; return
            end
            estimate=struct("estimatedAtoms",ceil(upper), ...
                "warning",upper>=10000);
        end
        function result=execute(model,id,p)
            import kssolv.modeling.ParameterUtils
            seed=double(ParameterUtils.get(p,"seed",1));
            tacticity=string(ParameterUtils.get(p,"tacticity","atactic"));
            atomLimit=double(ParameterUtils.get(p,"atomLimit",100000));
            storePath=string(ParameterUtils.get(p,"storePath",""));
            chainCount=double(ParameterUtils.get(p,"chainCount",1));
            headGroup=string(ParameterUtils.get(p,"headGroup","none"));
            tailGroup=string(ParameterUtils.get(p,"tailGroup","none"));
            conformation=string(ParameterUtils.get(p,"conformation","extended"));
            headTailMode=string(ParameterUtils.get(p,"headTailMode","regular"));
            switch string(id)
                case "build_homopolymer"
                    [model,info]=kssolv.modeling.polymers.PolymerBuilder. ...
                        homopolymer(string(ParameterUtils.get(p,"repeatUnit","PE")), ...
                        double(ParameterUtils.get(p,"repeatCount",10)), ...
                        seed=seed,tacticity=tacticity,atomLimit=atomLimit, ...
                        storePath=storePath,chainCount=chainCount, ...
                        headGroup=headGroup,tailGroup=tailGroup, ...
                        conformation=conformation,headTailMode=headTailMode);
                case "build_block_copolymer"
                    [model,info]=kssolv.modeling.polymers.PolymerBuilder.block( ...
                        parseKinds(ParameterUtils.get(p,"blockKinds",["PEO","PPO","PEO"])), ...
                        double(ParameterUtils.get(p,"blockLengths",[5,10,5])), ...
                        seed=seed,tacticity=tacticity,atomLimit=atomLimit, ...
                        storePath=storePath,chainCount=chainCount, ...
                        headGroup=headGroup,tailGroup=tailGroup, ...
                        conformation=conformation,headTailMode=headTailMode, ...
                        superunitCount=double(ParameterUtils.get( ...
                        p,"superunitCount",1)));
                case "build_random_copolymer"
                    [model,info]=kssolv.modeling.polymers.PolymerBuilder.random( ...
                        parseKinds(ParameterUtils.get(p,"monomerKinds",["PE","PP"])), ...
                        double(ParameterUtils.get(p,"repeatCount",20)), ...
                        double(ParameterUtils.get(p,"fractions",[.5,.5])), ...
                        seed=seed,exactComposition=ParameterUtils.logical( ...
                        p,"exactComposition",true),tacticity=tacticity, ...
                        atomLimit=atomLimit,storePath=storePath, ...
                        chainCount=chainCount,headGroup=headGroup, ...
                        tailGroup=tailGroup,conformation=conformation, ...
                        headTailMode=headTailMode, ...
                        reactivityRatios=double(ParameterUtils.get( ...
                        p,"reactivityRatios",[1,1])));
                case "build_branched_polymer"
                    [model,info]=kssolv.modeling.polymers.PolymerBuilder.branched( ...
                        string(ParameterUtils.get(p,"repeatUnit","PE")), ...
                        double(ParameterUtils.get(p,"repeatCount",20)), ...
                        double(ParameterUtils.get(p,"branchInterval",4)), ...
                        seed=seed,tacticity=tacticity,atomLimit=atomLimit, ...
                        storePath=storePath, ...
                        branchFragment=string(ParameterUtils.get( ...
                        p,"branchFragment","Methyl")));
                case "build_dendrimer"
                    [model,info]=kssolv.modeling.polymers.PolymerBuilder. ...
                        dendrimer(double(ParameterUtils.get(p,"generations",2)), ...
                        coreFunctionality=double(ParameterUtils.get( ...
                        p,"coreFunctionality",3)), ...
                        branchingFactor=double(ParameterUtils.get( ...
                        p,"branchingFactor",2)), ...
                        element=string(ParameterUtils.get(p,"element","C")), ...
                        bondLength=double(ParameterUtils.get( ...
                        p,"bondLength",1.54)),seed=seed,atomLimit=atomLimit);
                case "save_user_repeat_unit"
                    name=string(ParameterUtils.get(p, ...
                        "repeatUnitName","User Repeat Unit"));
                    head=double(ParameterUtils.get(p,"headIndex",1));
                    tail=double(ParameterUtils.get(p,"tailIndex",2));
                    leaving=double(ParameterUtils.get(p, ...
                        "leavingIndices",zeros(1,0)));
                    storePath=string(ParameterUtils.get(p,"storePath",""));
                    overwrite=ParameterUtils.logical(p,"overwrite",false);
                    kssolv.modeling.polymers.RepeatUnitLibrary.saveUser( ...
                        name,model,head,tail,leaving, ...
                        storePath=storePath,overwrite=overwrite);
                    info=struct("name",name,"head",head,"tail",tail, ...
                        "leavingAtoms",leaving,"storePath",storePath);
            end
            changed=string(id)~="save_user_repeat_unit";
            message="Polymer constructed (not equilibrated).";
            if ~changed, message="User repeat unit saved."; end
            result=struct("model",model,"changed",changed, ...
                "message",message, ...
                "analysis",info);
        end
    end
end

function values=parseKinds(input)
values=reshape(string(input),1,[]);
if isscalar(values), values=split(strtrim(values)); values=reshape(values,1,[]); end
end
function value=unitSize(kind,p)
storePath="";
if isstruct(p) && isfield(p,"storePath"), storePath=string(p.storePath); end
entry=kssolv.modeling.polymers.RepeatUnitLibrary.get( ...
    string(kind),storePath=storePath);
value=numel(entry.species);
end
function value=endGroupSize(p)
value=0;
for name=["headGroup","tailGroup"]
    if isstruct(p) && isfield(p,name) && ...
            lower(string(p.(name)))~="none"
        entry=kssolv.modeling.fragments.FragmentLibrary.get(string(p.(name)));
        value=value+numel(entry.species);
    end
end
end
