function result=get_gruneisenparameter(path,structure,structurePath)
%GET_GRUNEISENPARAMETER Read a phonopy Gruneisen mesh YAML.
if nargin<2,structure=[];end
if nargin<3,structurePath=[];end
data=kssolv.analysis.matgenlab.util.yaml_load(path);
if ~isempty(structurePath)&&isempty(structure)
    structure=kssolv.analysis.matgenlab.core.Structure. ...
        from_file(structurePath,"poscar");
else
    try
        structure=kssolv.analysis.matgenlab.io.phonopy. ...
            get_structure_from_dict(data);
    catch exception
        if isempty(structure)
            error("KSSOLV:Matgenlab:Phonopy:Structure", ...
                "Please provide a structure or structure path");
        end
        if ~strcmp(exception.identifier, ...
                "KSSOLV:Matgenlab:Phonopy:Structure")
            rethrow(exception);
        end
    end
end
phonons=kssolv.analysis.matgenlab.io.phonopy. ...
    phonopy_records(kssolv.analysis.matgenlab.io.phonopy. ...
    phonopy_field(data,"phonon"));
qpoints=zeros(numel(phonons),3);
multiplicities=ones(1,numel(phonons));
firstBands=kssolv.analysis.matgenlab.io.phonopy. ...
    phonopy_records(kssolv.analysis.matgenlab.io.phonopy. ...
    phonopy_field(phonons{1},"band"));
frequencies=zeros(numel(firstBands),numel(phonons));
gruneisen=zeros(size(frequencies));
for pointIndex=1:numel(phonons)
    point=phonons{pointIndex};
    qpoints(pointIndex,:)=reshape(double( ...
        kssolv.analysis.matgenlab.io.phonopy. ...
        phonopy_field(point,"q-position")),1,3);
    multiplicities(pointIndex)=double( ...
        kssolv.analysis.matgenlab.io.phonopy. ...
        phonopy_field(point,"multiplicity",1));
    bands=kssolv.analysis.matgenlab.io.phonopy. ...
        phonopy_records(kssolv.analysis.matgenlab.io.phonopy. ...
        phonopy_field(point,"band"));
    for bandIndex=1:numel(bands)
        frequencies(bandIndex,pointIndex)=double( ...
            kssolv.analysis.matgenlab.io.phonopy. ...
            phonopy_field(bands{bandIndex},"frequency"));
        if isfield(bands{bandIndex},"gruneisen")
            gruneisen(bandIndex,pointIndex)=double( ...
                bands{bandIndex}.gruneisen);
        end
    end
end
result=kssolv.analysis.matgenlab.phonon.GruneisenParameter( ...
    qpoints,gruneisen,frequencies,multiplicities,structure,[]);
end
