function dos=get_complete_ph_dos(partialDosPath,phonopyYamlPath)
%GET_COMPLETE_PH_DOS Read phonopy projected DOS and structure.
values=readmatrix(partialDosPath, ...
    FileType="text",CommentStyle="#");
values=values(all(isfinite(values),2),:).';
data=kssolv.analysis.matgenlab.util.yaml_load(phonopyYamlPath);
primitive=kssolv.analysis.matgenlab.io.phonopy. ...
    phonopy_field(data,"primitive_cell");
structure=kssolv.analysis.matgenlab.io.phonopy. ...
    get_structure_from_dict(primitive);
total=kssolv.analysis.matgenlab.phonon.PhononDos( ...
    values(1,:),sum(values(2:end,:),1));
dos=kssolv.analysis.matgenlab.phonon.CompletePhononDos( ...
    structure,total,values(2:end,:));
end
