function bands=get_phonon_band_structure_from_fc( ...
        structure,supercellMatrix,forceConstants,meshDensity,varargin)
%GET_PHONON_BAND_STRUCTURE_FROM_FC Uniform mesh bands from force constants.
if nargin<4||isempty(meshDensity),meshDensity=100;end
qpoints=kssolv.analysis.matgenlab.io.phonopy. ...
    phonopy_mesh_qpoints(structure,meshDensity);
frequencies=kssolv.analysis.matgenlab.io.phonopy. ...
    phonon_modes_from_fc( ...
    structure,supercellMatrix,forceConstants,qpoints);
bands=kssolv.analysis.matgenlab.phonon.PhononBandStructure( ...
    qpoints,frequencies,structure.lattice);
end
