function bands=get_phonon_band_structure_symm_line_from_fc( ...
        structure,supercellMatrix,forceConstants, ...
        lineDensity,symprec,varargin)
%GET_PHONON_BAND_STRUCTURE_SYMM_LINE_FROM_FC High-symmetry FC bands.
if nargin<4||isempty(lineDensity),lineDensity=20;end
if nargin<5||isempty(symprec),symprec=0.01;end
path=kssolv.analysis.matgenlab.symmetry.HighSymmKpath( ...
    structure,false,[],"setyawan_curtarolo",symprec);
[qpoints,labels]=path.get_kpoints(lineDensity,false);
frequencies=kssolv.analysis.matgenlab.io.phonopy. ...
    phonon_modes_from_fc( ...
    structure,supercellMatrix,forceConstants,qpoints);
labelMap=containers.Map("KeyType","char","ValueType","any");
for index=1:numel(labels)
    if strlength(labels(index))>0
        labelMap(char(labels(index)))=qpoints(index,:);
    end
end
bands=kssolv.analysis.matgenlab.phonon. ...
    PhononBandStructureSymmLine( ...
    qpoints,frequencies.',structure.lattice, ...
    false,[],labelMap,false,structure);
end
