classdef CubeVolumeAdapter
    %CUBEVOLUMEADAPTER Normalize Cube geometry and scalar channels.

    methods (Static)
        function datasets = read(filePath)
            volume = ...
                kssolv.analysis.matgenlab.io.common.VolumetricData. ...
                from_cube(filePath);
            names = string(fieldnames(volume.data));
            channels = repmat(emptyChannel(), 1, numel(names));
            voxelVolume = abs(det(volume.voxel_vectors));
            for index = 1:numel(names)
                name = names(index);
                values = double(volume.data.(name));
                integral = [];
                if voxelVolume > eps
                    integral = sum(values, "all") * voxelVolume;
                end
                displayLabel = name;
                if isfield(volume.channel_labels, name)
                    displayLabel = "Dataset " + ...
                        string(volume.channel_labels.(name));
                end
                channels(index) = ...
                    kssolv.services.fileparser.volume. ...
                    VolumeStatistics.channel(name, displayLabel, ...
                    "arbitrary", values, integral);
            end
            source = struct( ...
                "format", "cube", ...
                "name", sourceName(filePath), ...
                "path", string(filePath), ...
                "normalization", "source-values");
            dataset = kssolv.services.fileparser.VolumeDataset( ...
                source = source, ...
                structure = volume.structure, ...
                dimensionality = 3, ...
                dimensions = double(volume.dim), ...
                origin = volume.grid_origin, ...
                voxelVectors = volume.voxel_vectors, ...
                periodic = volume.grid_periodic, ...
                sampling = volume.grid_sampling, ...
                channels = channels);
            datasets = {dataset};
        end
    end
end

function value = sourceName(filePath)
[~, name, extension] = fileparts(string(filePath));
if any(lower(extension) == [".gz", ".bz2"])
    [~, name] = fileparts(name);
end
value = string(name);
end

function value = emptyChannel()
value = struct("id", "", "label", "", "units", "", ...
    "signed", false, "minimum", 0, "maximum", 0, "mean", 0, ...
    "standardDeviation", 0, "integral", [], "values", []);
end
