classdef VaspVolumeAdapter
    %VASPVOLUMEADAPTER Normalize CHGCAR/CHG grids to physical density.

    methods (Static)
        function datasets = read(filePath)
            volume = ...
                kssolv.analysis.matgenlab.io.vasp.Chgcar. ...
                from_file(filePath);
            dimensions = double(volume.dim);
            lattice = double(volume.structure.lattice.matrix);
            cellVolume = abs(det(lattice));
            if cellVolume <= eps
                error("KSSOLV:FileParser:VaspVolume:Cell", ...
                    "CHGCAR lattice has zero volume.");
            end
            names = string(fieldnames(volume.data));
            hasVectorMagnetization = all(isfield(volume.data, ...
                ["diff_x", "diff_y", "diff_z"]));
            hasCollinearDifference = isfield(volume.data, "diff") && ...
                ~hasVectorMagnetization;
            derivedChannelCount = 2 * double(hasCollinearDifference) + ...
                double(hasVectorMagnetization);
            channels = repmat(emptyChannel(), 1, ...
                numel(names) + derivedChannelCount);
            channelIndex = 0;
            for index = 1:numel(names)
                name = names(index);
                raw = double(volume.data.(name));
                density = raw / cellVolume;
                channelIndex = channelIndex + 1;
                channels(channelIndex) = ...
                    kssolv.services.fileparser.volume. ...
                    VolumeStatistics.channel(name, ...
                    label(name), "1/Angstrom^3", density, ...
                    mean(raw, "all"));
            end
            if hasCollinearDifference
                total = double(volume.data.total);
                difference = double(volume.data.diff);
                channelIndex = channelIndex + 1;
                channels(channelIndex) = ...
                    kssolv.services.fileparser.volume. ...
                    VolumeStatistics.channel("up", ...
                    "Spin-up charge density", "1/Angstrom^3", ...
                    0.5 * (total + difference) / cellVolume, ...
                    0.5 * mean(total + difference, "all"));
                channelIndex = channelIndex + 1;
                channels(channelIndex) = ...
                    kssolv.services.fileparser.volume. ...
                    VolumeStatistics.channel("down", ...
                    "Spin-down charge density", "1/Angstrom^3", ...
                    0.5 * (total - difference) / cellVolume, ...
                    0.5 * mean(total - difference, "all"));
            end
            if hasVectorMagnetization
                magnitude = sqrt( ...
                    double(volume.data.diff_x).^2 + ...
                    double(volume.data.diff_y).^2 + ...
                    double(volume.data.diff_z).^2);
                channelIndex = channelIndex + 1;
                channels(channelIndex) = ...
                    kssolv.services.fileparser.volume. ...
                    VolumeStatistics.channel( ...
                    "magnetization_magnitude", ...
                    "Magnetization magnitude", "1/Angstrom^3", ...
                    magnitude / cellVolume, ...
                    mean(magnitude, "all"));
            end
            source = struct( ...
                "format", "chgcar", ...
                "name", sourceName(filePath), ...
                "path", string(filePath), ...
                "normalization", "raw/cell-volume");
            dataset = kssolv.services.fileparser.VolumeDataset( ...
                source = source, ...
                structure = volume.structure, ...
                dimensionality = 3, ...
                dimensions = dimensions, ...
                origin = [0, 0, 0], ...
                voxelVectors = lattice ./ dimensions.', ...
                periodic = [true, true, true], ...
                sampling = "cell-periodic", ...
                channels = channels);
            datasets = {dataset};
        end
    end
end

function value = label(name)
switch string(name)
    case "total", value = "Total charge density";
    case "diff", value = "Magnetization density";
    case "diff_x", value = "Magnetization x";
    case "diff_y", value = "Magnetization y";
    case "diff_z", value = "Magnetization z";
    otherwise, value = string(name);
end
end

function value = sourceName(filePath)
[~, name, extension] = fileparts(string(filePath));
if any(lower(extension) == [".gz", ".bz2"])
    [~, name] = fileparts(name);
end
value = string(name);
end

function value = emptyChannel()
value = struct("id", "", "label", "", "units", "", ...
    "signed", false, "minimum", 0, "maximum", 0, "mean", 0, ...
    "standardDeviation", 0, "integral", [], "values", []);
end
