classdef VolumeStatistics
    %VOLUMESTATISTICS Construct canonical scalar channel metadata.

    methods (Static)
        function channel = channel(identifier, label, units, values, integral)
            arguments
                identifier {mustBeTextScalar}
                label {mustBeTextScalar}
                units {mustBeTextScalar}
                values {mustBeNumeric}
                integral = []
            end
            values = double(values);
            if any(~isfinite(values), "all")
                error("KSSOLV:FileParser:VolumeStatistics:Finite", ...
                    "Volume channel '%s' contains NaN or Inf.", identifier);
            end
            minimum = min(values, [], "all");
            maximum = max(values, [], "all");
            channel = struct( ...
                "id", string(identifier), ...
                "label", string(label), ...
                "units", string(units), ...
                "signed", minimum < 0, ...
                "minimum", minimum, ...
                "maximum", maximum, ...
                "mean", mean(values, "all"), ...
                "standardDeviation", std(values, 0, "all"), ...
                "integral", integral, ...
                "values", values);
        end
    end
end
