classdef VolumeLimits
    %VOLUMELIMITS Central allocation and transport limits for volume data.

    properties (Constant)
        MaxSourceBytes = 8 * 1024^3
        MaxVoxelCount = 256^3
        MaxChannelCount = 64
        MaxDecodedBytes = 2 * 1024^3
        % uihtml can silently discard larger custom-event payloads on some
        % MATLAB/CEF builds. Backpressure keeps the extra chunk count safe.
        DefaultChunkBytes = 32 * 1024
    end

    methods (Static)
        function validateSource(filePath)
            info = dir(filePath);
            if isempty(info)
                error("KSSOLV:FileParser:VolumeLimits:MissingSource", ...
                    "Cannot inspect volume source '%s'.", filePath);
            end
            if info.bytes > ...
                    kssolv.services.fileparser.volume.VolumeLimits. ...
                    MaxSourceBytes
                error("KSSOLV:FileParser:VolumeLimits:SourceBytes", ...
                    "Volume source is %.3g GiB; the limit is %.3g GiB.", ...
                    info.bytes / 1024^3, ...
                    kssolv.services.fileparser.volume.VolumeLimits. ...
                    MaxSourceBytes / 1024^3);
            end
        end

        function count = validateDimensions(dimensions, channelCount)
            arguments
                dimensions (1,3) double
                channelCount (1,1) double = 1
            end
            if any(~isfinite(dimensions)) || any(dimensions < 1) || ...
                    any(dimensions ~= fix(dimensions))
                error("KSSOLV:FileParser:VolumeLimits:Dimensions", ...
                    "Volume dimensions must be positive finite integers.");
            end
            if channelCount < 1 || channelCount ~= fix(channelCount) || ...
                    channelCount > ...
                    kssolv.services.fileparser.volume.VolumeLimits. ...
                    MaxChannelCount
                error("KSSOLV:FileParser:VolumeLimits:Channels", ...
                    "Volume channel count %g is outside the supported range.", ...
                    channelCount);
            end
            count = 1;
            for dimension = dimensions
                if count > flintmax / dimension
                    error("KSSOLV:FileParser:VolumeLimits:Overflow", ...
                        "Volume dimension product exceeds exact integer range.");
                end
                count = count * dimension;
            end
            if count > ...
                    kssolv.services.fileparser.volume.VolumeLimits. ...
                    MaxVoxelCount
                error("KSSOLV:FileParser:VolumeLimits:VoxelCount", ...
                    "Volume contains %.3g voxels; the limit is %.3g.", ...
                    count, ...
                    kssolv.services.fileparser.volume.VolumeLimits. ...
                    MaxVoxelCount);
            end
            decodedBytes = count * channelCount * 8;
            if decodedBytes > ...
                    kssolv.services.fileparser.volume.VolumeLimits. ...
                    MaxDecodedBytes
                error("KSSOLV:FileParser:VolumeLimits:DecodedBytes", ...
                    "Volume decoding requires approximately %.3g GiB; " + ...
                    "the limit is %.3g GiB. Reduce the grid or channels.", ...
                    decodedBytes / 1024^3, ...
                    kssolv.services.fileparser.volume.VolumeLimits. ...
                    MaxDecodedBytes / 1024^3);
            end
        end
    end
end
