classdef XSFVolumeAdapter
    %XSFVOLUMEADAPTER Normalize each XSF datagrid block as one dataset.

    methods (Static)
        function datasets = read(filePath)
            value = ...
                kssolv.analysis.matgenlab.io.xcrysden.XSF. ...
                from_file(filePath);
            keys = sort(string(value.grids.keys()));
            if isempty(keys)
                error("KSSOLV:FileParser:XSFVolume:MissingGrid", ...
                    "XSF file '%s' does not contain a scalar datagrid.", ...
                    filePath);
            end
            datasets = cell(1, numel(keys));
            for blockIndex = 1:numel(keys)
                blockName = keys(blockIndex);
                grid = value.grids(char(blockName));
                dimensions = size(grid.data);
                dimensions = dimensions(2:end);
                if numel(dimensions) < 3, dimensions(3) = 1; end
                dimensions = double(dimensions(1:3));
                dimensionality = grid.ndim;
                vectors = zeros(3, 3);
                vectors(1:dimensionality, :) = ...
                    double(grid.lattice(1:dimensionality, :)) ./ ...
                    max(dimensions(1:dimensionality).' - 1, 1);
                labels = grid.labels;
                if isempty(labels)
                    labels = "Grid " + string(1:size(grid.data, 1));
                end
                channels = repmat(emptyChannel(), 1, size(grid.data, 1));
                for channelIndex = 1:numel(channels)
                    values = reshape(grid.data(channelIndex, :, :, :), ...
                        dimensions);
                    identifier = matlab.lang.makeValidName( ...
                        lower(char(labels(channelIndex))));
                    channels(channelIndex) = ...
                        kssolv.services.fileparser.volume. ...
                        VolumeStatistics.channel(identifier, ...
                        labels(channelIndex), "arbitrary", values);
                end
                periodic = false(1, 3);
                periodic(1:dimensionality) = ~isempty(value.structure) && ...
                    isa(value.structure, ...
                    "kssolv.analysis.matgenlab.core.Structure");
                source = struct( ...
                    "format", "xsf", ...
                    "name", sourceName(filePath), ...
                    "path", string(filePath), ...
                    "dataset", blockName, ...
                    "normalization", "source-values");
                datasets{blockIndex} = ...
                    kssolv.services.fileparser.VolumeDataset( ...
                    source = source, ...
                    structure = value.structure, ...
                    dimensionality = dimensionality, ...
                    dimensions = dimensions, ...
                    origin = padOrigin(grid.origin), ...
                    voxelVectors = vectors, ...
                    periodic = periodic, ...
                    sampling = "point-inclusive", ...
                    channels = channels);
            end
        end
    end
end

function value = padOrigin(origin)
value = zeros(1, 3);
value(1:numel(origin)) = double(origin);
end

function value = sourceName(filePath)
[~, name, extension] = fileparts(string(filePath));
if any(lower(extension) == [".gz", ".bz2"])
    [~, name] = fileparts(name);
end
value = string(name);
end

function value = emptyChannel()
value = struct("id", "", "label", "", "units", "", ...
    "signed", false, "minimum", 0, "maximum", 0, "mean", 0, ...
    "standardDeviation", 0, "integral", [], "values", []);
end
