classdef BandStructureTest < matlab.unittest.TestCase
    methods (Test)
        function kpointRoundTrip(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.electronic_structure.Kpoint
            lattice = Lattice(2 * pi * eye(3));
            point = Kpoint([1.2, -0.1, 0.5], lattice, true, false, "X");
            testCase.verifyEqual(point.frac_coords, [0.2, 0.9, 0.5], ...
                AbsTol=1e-15);
            restored = Kpoint.from_dict(point.as_dict());
            testCase.verifyTrue(restored == point);
        end

        function bandEdgesAndGapOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.electronic_structure.*
            lattice = Lattice(2 * pi * eye(3));
            points = [0,0,0; 0.5,0,0; 0.5,0.5,0];
            bands = [-2,-1.5,-1; 1.2,1.0,1.4; 2,2.1,2.2];
            labels = struct("G", [0,0,0], "X", [0.5,0,0], ...
                "M", [0.5,0.5,0]);
            structure = BandStructure(points, struct("up", bands), ...
                lattice, 0, labels);
            request = struct( ...
                "module", "pymatgen.electronic_structure.bandstructure", ...
                "symbol", "BandStructure", ...
                "construct", struct("method", "from_dict", ...
                    "decode", false, "args", {{structure.as_dict()}}), ...
                "operations", {{ ...
                    struct("kind", "call", "name", "is_metal"), ...
                    struct("kind", "call", "name", "get_band_gap"), ...
                    struct("kind", "call", "name", ...
                        "get_direct_band_gap")}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            testCase.verifyEqual(structure.is_metal(), ...
                reference.results{1});
            gap = structure.get_band_gap();
            testCase.verifyEqual(gap.energy, ...
                reference.results{2}.energy, AbsTol=1e-15);
            testCase.verifyEqual(gap.direct, ...
                reference.results{2}.direct);
            testCase.verifyEqual(gap.transition, ...
                string(reference.results{2}.transition));
            testCase.verifyEqual(structure.get_direct_band_gap(), ...
                reference.results{3}, AbsTol=1e-15);
            testCase.verifyEqual(structure.get_vbm().kpoint_index, 3);
            testCase.verifyEqual(structure.get_cbm().kpoint_index, 2);
        end

        function symmetryLineBranchesAndScissor(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.electronic_structure.*
            lattice = Lattice(2 * pi * eye(3));
            points = [0,0,0; 0.25,0,0; 0.5,0,0; ...
                0.5,0,0; 0.5,0.25,0; 0.5,0.5,0];
            labels = struct("G", [0,0,0], "X", [0.5,0,0], ...
                "M", [0.5,0.5,0]);
            bands = [-ones(1,6); ones(1,6)];
            line = BandStructureSymmLine(points, ...
                struct("up", bands), lattice, 0, labels);
            testCase.verifyEqual(numel(line.branches), 2);
            testCase.verifyEqual(line.get_equivalent_kpoints(3), [3,4]);
            shifted = line.apply_scissor(3);
            testCase.verifyEqual(shifted.get_band_gap().energy, 3, ...
                AbsTol=1e-14);
        end

        function legacyProjectionDecoders(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.electronic_structure.*
            realLattice=Lattice.cubic(4);
            structure=Structure(realLattice,{"Si"},[0,0,0]);
            reciprocal=Lattice(2*pi*eye(3));
            entries=cell(2,2);
            entries{1,1}=struct("s",0.1,"py",0.2);
            entries{1,2}=struct("s",0.3,"py",0.4);
            entries{2,1}=struct("s",0.5,"py",0.6);
            entries{2,2}=struct("s",0.7,"py",0.8);
            legacy=struct( ...
                "x_class","BandStructure", ...
                "lattice_rec",reciprocal.as_dict(), ...
                "efermi",0, ...
                "kpoints",{{[0,0,0],[0.5,0,0]}}, ...
                "labels_dict",struct("G",[0,0,0],"X",[0.5,0,0]), ...
                "bands",struct("x1",[-1,-0.8;1,1.2]), ...
                "structure",structure.as_dict(), ...
                "projections",struct("x1",{{ ...
                    {entries{1,1},entries{1,2}}, ...
                    {entries{2,1},entries{2,2}}}}));
            restored=BandStructure.from_old_dict(legacy);
            testCase.verifyClass(restored, ...
                "kssolv.analysis.matgenlab.electronic_structure.BandStructure");
            testCase.verifyEqual(squeeze(restored.projections.up(2,2,:,:)), ...
                [0.7;0.8],AbsTol=1e-15);

            lobsterLegacy=legacy;
            lobsterLegacy.x_class="LobsterBandStructureSymmLine";
            lobsterLegacy.projections=struct("x1",{{ ...
                {[0.1;0.2],[0.3;0.4]}, ...
                {[0.5;0.6],[0.7;0.8]}}});
            lobster=LobsterBandStructureSymmLine.from_dict(lobsterLegacy);
            testCase.verifyClass(lobster, ...
                "kssolv.analysis.matgenlab.electronic_structure." + ...
                "LobsterBandStructureSymmLine");
            testCase.verifyEqual(squeeze(lobster.projections.up(2,2,:,:)), ...
                [0.7;0.8],AbsTol=1e-15);
        end
    end
end
