classdef CohpPlotterTest < matlab.unittest.TestCase
    methods (Test)
        function cohpNumericsMsonAndOracle(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            cohp=Cohp(0,[-2,-1,0,1], ...
                struct("up",[-.2,.2,-.1,.3],"down",[-.1,.1,-.05,.15]), ...
                "icohp",struct("up",[0,-.2,-.3,0],"down",[0,-.1,-.15,0]));
            testCase.verifyEqual(cohp.get_interpolated_value(-.5).up,.05,AbsTol=1e-14);
            testCase.verifyTrue(cohp.has_antibnd_states_below_efermi().up);
            restored=Cohp.from_dict(cohp.as_dict());
            testCase.verifyEqual(restored.cohp,cohp.cohp);
            lines=splitlines(string(char(Cohp(0,[-1,0], ...
                struct("up",[-1,0])))));
            testCase.verifyEqual(lines(2),"-1.00000 -1.00000");
            testCase.verifyEqual(lines(3),"0.00000 0.00000");

            testCase.assumeTrue(kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            request=struct(module="pymatgen.electronic_structure.cohp", ...
                symbol="Cohp",construct=struct(args={{0,[-2,-1,0,1], ...
                cohp.as_dict().COHP}},kwargs=struct(icohp=cohp.as_dict().ICOHP)), ...
                operations={{struct(kind="call",name="get_interpolated_value", ...
                args={{-.5}}),struct(kind="call", ...
                name="has_antibnd_states_below_efermi")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            first=oracleResult(reference.results,1);
            second=oracleResult(reference.results,2);
            testCase.verifyEqual(cohp.get_interpolated_value(-.5).up, ...
                first.x1,AbsTol=1e-14);
            testCase.verifyEqual(cohp.has_antibnd_states_below_efermi().up, ...
                second.x1);
        end

        function officialCompleteCohpFixtures(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            root=cohpFixtureRoot();testCase.assumeTrue(isfolder(root));
            lobster=CompleteCohp.from_dict(jsondecode(fileread( ...
                fullfile(root,"complete_cohp_lobster.json"))));
            testCase.verifyNumElements(lobster.energies,301);
            testCase.verifyEqual(lobster.efermi,9.75576,AbsTol=1e-12);
            testCase.verifyEqual(double(lobster.all_cohps.Count),2);
            testCase.verifyEqual(lobster.cohp.up(end),.0263,AbsTol=1e-12);
            testCase.verifyEqual(lobster.get_cohp_by_label("1").cohp.up(end), ...
                .01483,AbsTol=1e-12);
            testCase.verifyEqual(get_integrated_cohp_in_energy_range( ...
                lobster,"1"),-.29919,AbsTol=1e-8);
            restored=CompleteCohp.from_dict(lobster.as_dict());
            testCase.verifyEqual(double(restored.all_cohps.Count),2);

            lmto=CompleteCohp.from_dict(jsondecode(fileread( ...
                fullfile(root,"complete_cohp_lmto.json"))));
            testCase.verifyNumElements(lmto.energies,801);
            testCase.verifyEqual(lmto.efermi,-2.3433,AbsTol=1e-12);
            testCase.verifyEqual(double(lmto.all_cohps.Count),7);
            testCase.verifyEqual(get_integrated_cohp_in_energy_range( ...
                lmto,"Se7-Se8"),.049687373690246374,AbsTol=1e-9);
        end

        function nativeRawLobsterAndLmto(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            root=cohpFixtureRoot();testCase.assumeTrue(isfolder(root));
            warning("off","KSSOLV:Matgenlab:Poscar:DefaultNames");
            cleanup=onCleanup(@()warning("on","KSSOLV:Matgenlab:Poscar:DefaultNames"));
            lobster=CompleteCohp.from_file("LOBSTER", ...
                fullfile(root,"COHPCAR.lobster.gz"),fullfile(root,"POSCAR"));
            testCase.verifyNumElements(lobster.energies,301);
            testCase.verifyEqual(lobster.efermi,9.75576,AbsTol=1e-12);
            testCase.verifyEqual(double(lobster.all_cohps.Count),2);
            orbital=CompleteCohp.from_file("LOBSTER", ...
                fullfile(root,"COHPCAR.lobster.orbitalwise.gz"), ...
                fullfile(root,"POSCAR.orbitalwise"));
            testCase.verifyEqual(double(orbital.orb_res_cohp("2").Count),16);
            testCase.verifyClass(orbital.get_orbital_resolved_cohp( ...
                "2","4s-4px"), ...
                "kssolv.analysis.matgenlab.electronic_structure.Cohp");
            lmto=CompleteCohp.from_file("LMTO",fullfile(root,"COPL"), ...
                fullfile(root,"CTRL"));
            testCase.verifyNumElements(lmto.energies,801);
            testCase.verifyEqual(lmto.efermi,-1.1658,AbsTol=1e-5);
            testCase.verifyEqual(double(lmto.all_cohps.Count),8);

            multi=CompleteCohp.from_file("LOBSTER", ...
                fullfile(root,"COBICAR.lobster.GeTe_4center"), ...
                fullfile(root,"POSCAR.GeTe"), ...
                "are_multi_center_cobis",true);
            testCase.verifyEqual(double(multi.all_cohps.Count),13);
            testCase.verifyNumElements(multi.bonds("13").sites,4);
            spinMulti=CompleteCohp.from_file("LOBSTER", ...
                fullfile(root,"COBICAR.lobster.B2H6.spin"), ...
                fullfile(root,"POSCAR.B2H6"), ...
                "are_multi_center_cobis",true);
            lobsterAverage=CompleteCohp.from_file("LOBSTER", ...
                fullfile(root,"COBICAR.lobster.B2H6.spin.average.2"), ...
                fullfile(root,"POSCAR.B2H6"),"are_cobis",true);
            testCase.verifyEqual(spinMulti.cohp.up,lobsterAverage.cohp.up, ...
                AbsTol=1e-4);
            testCase.verifyEqual(spinMulti.cohp.down, ...
                lobsterAverage.cohp.down,AbsTol=1e-4);
            testCase.verifyEqual(spinMulti.icohp.up, ...
                lobsterAverage.icohp.up,AbsTol=1e-4);
            testCase.verifyEqual(spinMulti.icohp.down, ...
                lobsterAverage.icohp.down,AbsTol=1e-4);
            clear cleanup
        end

        function icohpValueAndCollection(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            value=IcohpValue("1","K1","F2",2.1,[-1,0,0],1, ...
                struct("up",-1.1,"down",-1));
            testCase.verifyEqual(value.summed_icohp,-2.1,AbsTol=1e-14);
            collection=IcohpCollection(["1","2"],["K1","K1"], ...
                ["F2","F3"],[2.1,3.2],{[-1,0,0],[0,0,0]},[1,1], ...
                {struct("up",-1.1,"down",-1), ...
                struct("up",-.2,"down",-.4)},true);
            testCase.verifyEqual(collection.get_icohp_by_label("1"),-2.1);
            testCase.verifyEqual(collection.get_summed_icohp_by_label_list( ...
                ["1","2"],2),-1.35,AbsTol=1e-14);
            testCase.verifyEqual(collection.extremum_icohpvalue(),-2.1);
            testCase.verifyEqual(double(collection.get_icohp_dict_by_bondlengths( ...
                2,2.5).Count),1);
            restored=IcohpCollection.from_dict(collection.as_dict());
            testCase.verifyEqual(restored.get_icohp_by_label("2"),-.6,AbsTol=1e-14);

            orbitalData={struct("x2s_6s",struct( ...
                "icohp",struct("x1",.0247,"x_1",.0247), ...
                "orbitals",{{{2,0},{6,0}}}))};
            orbitalCollection=IcohpCollection("1","O5","Ta2",1.99474, ...
                {[0,0,-1]},1,{struct("up",.29324,"down",.29324)}, ...
                true,"list_orb_icohp",orbitalData,"are_cobis",true);
            testCase.verifyEqual(orbitalCollection.get_icohp_by_label( ...
                "1",true,"up","2s-6s"),.0494,AbsTol=1e-14);
            orbitalRestored=IcohpCollection.from_dict( ...
                orbitalCollection.as_dict());
            testCase.verifyEqual(orbitalRestored.get_icohp_by_label( ...
                "1",false,"down","2s-6s"),.0247,AbsTol=1e-14);
        end

        function officialBandAndDosPlotData(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            root=electronicFixtureRoot();testCase.assumeTrue(isfolder(root));
            band=BandStructure.from_dict(jsondecode(fileread(fullfile(root, ...
                "bandstructure","CaO_2605_bandstructure.json"))));
            plotter=BSPlotter(band);data=plotter.bs_plot_data();
            testCase.verifyNumElements(data.distances,10);
            testCase.verifyNumElements(data.distances{1},16);
            testCase.verifyEqual(sum(cellfun(@numel,data.distances)),160);
            testCase.verifyEqual(plotter.get_ticks().label(6),"K");
            testCase.verifyEqual(plotter.get_ticks().distance(6), ...
                2.406607625322699,AbsTol=1e-12);
            joined=plotter.bs_plot_data(true,[],[],false);
            testCase.verifyNumElements(joined.distances,2);
            testCase.verifyNumElements(joined.distances{1},144);
            ax=plotter.get_plot();testCase.verifyTrue(isgraphics(ax,"axes"));
            close(ancestor(ax,"figure"));

            dos=kssolv.analysis.matgenlab.electronic_structure.CompleteDos. ...
                from_dict(jsondecode(fileread(fullfile(root,"dos", ...
                "complete_dos.json"))));
            dosPlotter=DosPlotter();dosPlotter.add_dos("total",dos);
            testCase.verifyEqual(double(dosPlotter.get_dos_dict().Count),1);
            ax=dosPlotter.get_plot([-5,5]);testCase.verifyTrue(isgraphics(ax,"axes"));
            close(ancestor(ax,"figure"));
        end

        function frozenPlotterOracle(testCase)
            testCase.assumeTrue(kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            root=electronicFixtureRoot();testCase.assumeTrue(isfolder(root));
            raw=jsondecode(fileread(fullfile(root,"bandstructure", ...
                "CaO_2605_bandstructure.json")));
            band=kssolv.analysis.matgenlab.electronic_structure. ...
                BandStructure.from_dict(raw);
            wire=band.as_dict();
            request=struct(module="pymatgen.electronic_structure.plotter", ...
                symbol="BSPlotter",construct=struct(args={{wire}}), ...
                operations={{struct(kind="call",name="get_ticks")}});
            reference=kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(request);
            plotter=kssolv.analysis.matgenlab.electronic_structure.BSPlotter(band);
            ticks=plotter.get_ticks();
            testCase.verifyEqual(ticks.distance, ...
                reshape(reference.results.distance,1,[]),AbsTol=1e-12);
            testCase.verifyEqual(ticks.label, ...
                reshape(string(reference.results.label),1,[]));
        end

        function projectedCohpAndReciprocalPlots(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            import kssolv.analysis.matgenlab.core.*
            root=electronicFixtureRoot();testCase.assumeTrue(isfolder(root));
            band=BandStructure.from_dict(jsondecode(fileread(fullfile(root, ...
                "bandstructure","Cu2O_361_bandstructure.json"))));
            projected=BSPlotterProjected(band);
            axesHandles=projected.get_projected_plots_dots( ...
                struct("Cu",["d","s"],"O","p"));
            testCase.verifyNumElements(axesHandles,4);
            testCase.verifyEqual(string(axesHandles(4).Visible),"off");
            close(ancestor(axesHandles(1),"figure"));
            summedAxes=projected.get_projected_plots_dots_patom_pmorb( ...
                struct("Cu",["dxy","s","px"],"O",["px","py","pz"]), ...
                struct("Cu",[3,5],"O",1),struct("Cu",[3,5]), ...
                struct("Cu",["dxy","px"]),true,[],false,[0,2],[],3);
            testCase.verifyNumElements(summedAxes,5);
            testCase.verifyEqual(string(summedAxes(1).Title.String),"Cu all s");
            close(ancestor(summedAxes(1),"figure"));

            cohp=Cohp(0,[-1,0,1],struct("up",[-1,0,1]), ...
                "icohp",struct("up",[-1,-1,0]));
            cp=CohpPlotter();cp.add_cohp("bond",cohp);
            ax=cp.get_plot();testCase.verifyTrue(isgraphics(ax,"axes"));
            close(ancestor(ax,"figure"));

            lattice=Lattice.cubic(1);
            testCase.verifyEqual(fold_point([.6,0,0],lattice), ...
                [-.4,0,0],AbsTol=1e-8);
            [fig,ax]=plot_wigner_seitz(lattice);
            testCase.verifyTrue(isgraphics(ax,"axes"));close(fig);
            [fig,ax]=plot_ellipsoid(eye(3),[0,0,0],lattice);
            testCase.verifyTrue(isgraphics(ax,"axes"));close(fig);
        end

        function boltztrapPlotAdapters(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            energies=linspace(-1,2,5);
            analyzer=struct(mu_steps=energies,gap=1,vol=10, ...
                doping=struct("n",[1e18,1e19],"p",[1e18,1e19]), ...
                mu_doping=mockMuDoping(),x_carrier_conc=struct("x300",1:5), ...
                dos=Dos(0,energies,ones(1,5)), ...
                get_seebeck=@mockTransport,get_conductivity=@mockTransport, ...
                get_power_factor=@mockTransport,get_zt=@mockTransport, ...
                get_average_eff_mass=@mockTransport, ...
                get_seebeck_eff_mass=@mockSpecial, ...
                get_complexity_factor=@mockSpecial, ...
                get_hall_carrier_concentration=@()struct("x300",1:5));
            plotter=BoltztrapPlotter(analyzer);
            handles={plotter.plot_seebeck_mu(300), ...
                plotter.plot_conductivity_temp(), ...
                plotter.plot_power_factor_dop(300), ...
                plotter.plot_seebeck_eff_mass_mu(300), ...
                plotter.plot_complexity_factor_mu(300), ...
                plotter.plot_dos(),plotter.plot_carriers(), ...
                plotter.plot_hall_carriers()};
            testCase.verifyTrue(all(cellfun(@(x)isgraphics(x,"axes"),handles)));
            cellfun(@(x)close(ancestor(x,"figure")),handles);
        end
    end
end

function root=electronicFixtureRoot()
base=string(getenv("MATGENLAB_PYMATGEN_CORE"));
if base=="",base="/tmp/matgenlab-pymatgen-core-v2026.7.24";end
root=fullfile(base,"test-files","electronic_structure");
end
function root=cohpFixtureRoot(),root=fullfile(electronicFixtureRoot(),"cohp");end
function value=mockMuDoping()
value=struct("n",struct("x300",[1,1.5]), ...
    "p",struct("x300",[-.5,-.2]));
end
function value=mockTransport(varargin)
if any(cellfun(@(x)islogical(x)&&~x,varargin))
    value=struct("x300",reshape(1:15,5,3));
else
    carrier=struct("x300",[1,2;2,3]);
    value=struct("n",carrier,"p",carrier);
end
end
function value=mockSpecial(varargin) %#ok<INUSD>
value=reshape(1:15,5,3);
end
function value=oracleResult(results,index)
if iscell(results),value=results{index};else,value=results(index);end
end
