classdef CompleteDosTest < matlab.unittest.TestCase
    methods (Test)
        function aggregationAndMoments(testCase)
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.electronic_structure.*
            structure = Structure(3 * eye(3), {"Fe", "O"}, ...
                [0,0,0; 0.5,0.5,0.5]);
            energies = -2:1:2;
            total = Dos(0, energies, struct("up", [3,4,0,4,3]));
            first = struct( ...
                "dxy", struct("up", [1,2,0,2,1]), ...
                "dz2", struct("up", [0,1,0,1,0]));
            second = struct("py", struct("up", [2,1,0,1,2]));
            complete = CompleteDos(structure, total, {first, second});
            testCase.verifyEqual( ...
                complete.get_site_dos(1).densities.up, ...
                [1,3,0,3,1]);
            spd = complete.get_spd_dos();
            testCase.verifyEqual(spd("d").densities.up, ...
                [1,3,0,3,1]);
            testCase.verifyEqual(spd("p").densities.up, ...
                [2,1,0,1,2]);
            testCase.verifyEqual( ...
                complete.get_band_center("d"), 0, AbsTol=1e-14);
            testCase.verifyEqual( ...
                complete.get_band_width("d"), ...
                1.1952286093343936, AbsTol=1e-14);
            resolved = complete.get_site_t2g_eg_resolved_dos(1);
            testCase.verifyEqual(resolved.t2g.densities.up, ...
                first.dxy.up);
            testCase.verifyEqual(resolved.e_g.densities.up, ...
                first.dz2.up);
        end

        function fingerprintAndSerialization(testCase)
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.electronic_structure.*
            structure = Structure(3 * eye(3), {"Si"}, [0,0,0]);
            energies = linspace(-3,3,301);
            density = exp(-energies.^2);
            total = Dos(0, energies, struct("up", density));
            complete = CompleteDos(structure, total, ...
                {struct("s", struct("up", density))});
            fingerprint = complete.get_dos_fp("s", true, -2, 2, 64);
            testCase.verifyEqual( ...
                sum(fingerprint.densities * fingerprint.bin_width), ...
                1, AbsTol=1e-14);
            testCase.verifyEqual(CompleteDos.get_dos_fp_similarity( ...
                fingerprint, fingerprint), 1, AbsTol=1e-14);
            restored = CompleteDos.from_dict(complete.as_dict());
            testCase.verifyEqual(restored.densities, complete.densities);
            testCase.verifyEqual( ...
                restored.pdos{1}.s.up, complete.pdos{1}.s.up);
        end

        function momentOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            energies = -2:0.25:2;
            density = exp(-(energies + 0.4).^2);
            expected = trapz(energies, energies .* density) / ...
                trapz(energies, density);
            testCase.verifyEqual(expected, -0.37795603999979593, ...
                AbsTol=2e-15);

            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.electronic_structure.*
            structure = Structure(3 * eye(3), {"Fe"}, [0,0,0]);
            total = Dos(0, energies, struct("up", density));
            complete = CompleteDos(structure, total, ...
                {struct("dxy", struct("up", density))});
            request = struct( ...
                "module", "pymatgen.electronic_structure.dos", ...
                "symbol", "CompleteDos", ...
                "construct", struct("method", "from_dict", ...
                    "decode", false, "args", {{complete.as_dict()}}), ...
                "operations", {{ ...
                    struct("kind", "call", "name", "get_band_center"), ...
                    struct("kind", "call", "name", "get_band_width"), ...
                    struct("kind", "call", "name", ...
                        "get_band_skewness")}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            testCase.verifyEqual(complete.get_band_center(), ...
                reference.results(1), AbsTol=2e-15);
            testCase.verifyEqual(complete.get_band_width(), ...
                reference.results(2), AbsTol=2e-15);
            testCase.verifyEqual(complete.get_band_skewness(), ...
                reference.results(3), AbsTol=2e-14);
        end
    end
end
