classdef DosTest < matlab.unittest.TestCase
    methods (Test)
        function densitiesInterpolationAndAddition(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            energies = -2:0.5:2;
            up = [2, 2, 1, 0, 0, 0, 1, 2, 2];
            down = up / 2;
            dos = Dos(0, energies, struct("up", up, "down", down));
            testCase.verifyEqual(dos.get_densities(), 1.5 * up);
            testCase.verifyEqual(dos.get_densities(Spin.down), down);
            interpolated = dos.get_interpolated_value(-1.25);
            testCase.verifyEqual(interpolated.up, 1.5);
            summed = dos + dos;
            testCase.verifyEqual(summed.densities.up, 2 * up);
        end

        function gapParity(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            energies = -2:0.25:2;
            density = abs(energies) >= 0.75;
            request = struct( ...
                "module", "pymatgen.electronic_structure.dos", ...
                "symbol", "Dos", ...
                "construct", struct("args", ...
                    {{0, energies, struct( ...
                    "matgenlab_spin_densities", ...
                    struct("up", double(density)))}}), ...
                "operations", {{ ...
                    struct("kind", "call", "name", ...
                        "get_interpolated_gap"), ...
                    struct("kind", "call", "name", ...
                        "get_interpolated_value", "args", {{-1.125}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            dos = kssolv.analysis.matgenlab.electronic_structure.Dos( ...
                0, energies, struct("up", double(density)));
            [gap, cbm, vbm] = dos.get_interpolated_gap();
            testCase.verifyEqual([gap, cbm, vbm], ...
                reshape(reference.results{1}, 1, 3), AbsTol=1e-14);
            actual = dos.get_interpolated_value(-1.125);
            testCase.verifyEqual(actual.up, ...
                reference.results{2}.x1, AbsTol=1e-14);
        end

        function fermiFunctionParity(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            energy = [-1, 0, 1];
            request = struct( ...
                "module", "pymatgen.electronic_structure.dos", ...
                "symbol", "f0", ...
                "operations", {{struct("kind", "call", ...
                    "args", {{struct("matgenlab_ndarray", energy), ...
                    0.2, 300}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            actual = kssolv.analysis.matgenlab.electronic_structure. ...
                f0(energy, 0.2, 300);
            testCase.verifyEqual(actual, ...
                reshape(reference.results, 1, []), AbsTol=2e-15);
        end

        function msonRoundTrip(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.Dos
            dos = Dos(1.2, [-1, 0, 1], ...
                struct("up", [1, 2, 3], "down", [3, 2, 1]));
            restored = Dos.from_dict(dos.as_dict());
            testCase.verifyEqual(restored.efermi, dos.efermi);
            testCase.verifyEqual(restored.energies, dos.energies);
            testCase.verifyEqual(restored.densities, dos.densities);
        end

        function fermiDosParity(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            import kssolv.analysis.matgenlab.core.Structure
            import kssolv.analysis.matgenlab.electronic_structure.*
            structure = Structure(3 * eye(3), {"Si"}, [0, 0, 0]);
            energies = -2:0.1:2;
            density = double(abs(energies) >= 0.5);
            dos = Dos(0, energies, struct("up", density));
            request = struct( ...
                "module", "pymatgen.electronic_structure.dos", ...
                "symbol", "FermiDos", ...
                "construct", struct("args", {{ ...
                    dos.as_dict(), structure.as_dict()}}), ...
                "operations", {{ ...
                    struct("kind", "call", "name", "get_e_h_concs", ...
                        "args", {{0.1, 300}}), ...
                    struct("kind", "call", "name", "get_doping", ...
                        "args", {{0.1, 300}})}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            actual = FermiDos(dos, structure);
            [electrons, holes] = actual.get_e_h_concs(0.1, 300);
            testCase.verifyEqual([electrons, holes], ...
                reshape(reference.results{1}, 1, 2), RelTol=5e-14);
            testCase.verifyEqual(actual.get_doping(0.1, 300), ...
                reference.results{2}, RelTol=5e-14);
        end
    end
end
