classdef ElectronicCoreTest < matlab.unittest.TestCase
    methods (Test)
        function spinAndOrbitals(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.*
            testCase.verifyEqual(double(Spin.up), 1);
            testCase.verifyEqual(double(Spin.down), -1);
            testCase.verifyEqual(string(Orbital.dyz), "dyz");
            testCase.verifyEqual(Orbital.dyz.orbital_type, OrbitalType.d);
            testCase.verifyEqual(double(Orbital.f3), 15);
        end

        function constructionAndTransforms(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.Magmom
            testCase.verifyEqual(double(Magmom(2)), 2, AbsTol=1e-14);
            moment = Magmom([1, 2, 3], [1, 1, 1]);
            testCase.verifyEqual(moment.saxis, ...
                sqrt(1/3) * [1, 1, 1], AbsTol=1e-14);
            transformed = Magmom.from_global_moment_and_saxis( ...
                [1, 2, 3], [1, 0, 0]);
            testCase.verifyEqual(transformed.moment, [-3, 2, 1], ...
                AbsTol=1e-14);
            testCase.verifyEqual(transformed.global_moment, [1, 2, 3], ...
                AbsTol=1e-14);
            testCase.verifyEqual(Magmom([1, 0, 0]).get_moment([1, 0, 0]), ...
                [0, 0, 1], AbsTol=1e-14);
        end

        function setsAndCollinearity(testCase)
            import kssolv.analysis.matgenlab.electronic_structure.Magmom
            testCase.verifyTrue(Magmom.are_collinear( ...
                [2, -2, 2]));
            testCase.verifyTrue(Magmom.are_collinear( ...
                [0, 0, 1; 0, 0, -1]));
            testCase.verifyFalse(Magmom.are_collinear( ...
                [0, 0, 1; 1, 2, 3]));
            [moments, axis] = Magmom.get_consistent_set_and_saxis( ...
                [0, 0, 0; 1, 1, 1; 2, 2, 2]);
            testCase.verifySize(moments, [3, 3]);
            testCase.verifyEqual(axis, sqrt(1/3) * [1, 1, 1], ...
                AbsTol=1e-14);
        end

        function crystalAxes(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.electronic_structure.Magmom
            lattice = Lattice.from_parameters(5, 10, 5, 90, 110, 90);
            moment = Magmom.from_moment_relative_to_crystal_axes( ...
                [1, 0, 2], lattice);
            testCase.verifyEqual(moment.moment, ...
                [0.939692620785908, 0, 1.65797985667433], ...
                AbsTol=2e-14);
            testCase.verifyEqual( ...
                moment.get_moment_relative_to_crystal_axes(lattice), ...
                [1, 0, 2], AbsTol=2e-14);
        end

        function frozenOracle(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable());
            request = struct( ...
                "module", "pymatgen.electronic_structure.core", ...
                "symbol", "Magmom", ...
                "construct", struct("args", {{[1, 2, 3]}}, ...
                    "kwargs", struct("saxis", [1, 1, 1])), ...
                "operations", {{ ...
                    struct("kind", "get", "name", "global_moment"), ...
                    struct("kind", "get", "name", "projection"), ...
                    struct("kind", "call", "name", "get_moment", ...
                        "kwargs", struct("saxis", [1, 0, 0]))}});
            reference = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle. ...
                execute(request);
            actual = ...
                kssolv.analysis.matgenlab.electronic_structure. ...
                Magmom([1, 2, 3], [1, 1, 1]);
            testCase.verifyEqual(actual.global_moment, ...
                reshape(reference.results{1}, 1, 3), AbsTol=2e-14);
            testCase.verifyEqual(actual.projection, ...
                reference.results{2}, AbsTol=2e-14);
            testCase.verifyEqual(actual.get_moment([1, 0, 0]), ...
                reshape(reference.results{3}, 1, 3), AbsTol=2e-14);
        end
    end
end
