classdef FeffAndEnvironmentCliInventoryTest < matlab.unittest.TestCase
    methods (Test)
        function crossSectionPlotData(testCase)
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                {"Fe", "O"}, [0, 0, 0; 1.7, 0, 0]);
            header = kssolv.analysis.matgenlab.io.feff.Header( ...
                molecule, "fixture", "CLI");
            tags = kssolv.analysis.matgenlab.io.feff.Tags( ...
                struct("XANES", [1, 2], "EDGE", "K"));
            raw = [(1:4).', zeros(4, 2), ...
                [2; 3; 5; 4], [1; 1.5; 2; 1.75], zeros(4, 1)];
            xmu = kssolv.analysis.matgenlab.io.feff.Xmu( ...
                header, tags, "Fe", raw);
            [axesHandle, data] = ...
                kssolv.analysis.matgenlab.cli. ...
                feff_plot_cross_section.main("unused", "unused", ...
                Xmu = xmu);
            cleanup = onCleanup(@()close(axesHandle.Parent));
            testCase.verifyEqual(data.energies, (1:4).');
            testCase.verifyEqual(data.scross, raw(:, 5));
            testCase.verifyEqual(data.across, raw(:, 4));
            testCase.verifyEqual(numel(axesHandle.Children), 2);
            oracle = testCase.oracle();
            expectedTitle = replace(string(oracle.cross_section.title), ...
                "FeO", data.formula);
            testCase.verifyEqual(string(axesHandle.Title.String), ...
                expectedTitle);
            testCase.verifyEqual(string(axesHandle.XLabel.String), ...
                string(oracle.cross_section.xlabel));
            testCase.verifyEqual(string(axesHandle.YLabel.String), ...
                string(oracle.cross_section.ylabel));
            clear cleanup
        end

        function dosSelectionAndHeadlessPlot(testCase)
            structure = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice(eye(3) .* 4), ...
                {"Fe", "O"}, [0, 0, 0; 0.5, 0.5, 0.5]);
            energies = [-1, 0, 1];
            total = kssolv.analysis.matgenlab.electronic_structure.Dos( ...
                0, energies, struct("up", [3, 4, 2]));
            pdos = {struct("s", struct("up", [1, 2, 1])), ...
                struct("s", struct("up", [2, 2, 1]))};
            complete = kssolv.analysis.matgenlab.electronic_structure. ...
                CompleteDos(structure, total, pdos);
            output = kssolv.analysis.matgenlab.io.feff.LDos( ...
                complete, struct());
            [axesHandle, allDos] = ...
                kssolv.analysis.matgenlab.cli.feff_plot_dos.main( ...
                "unused", "unused", site = true, element = true, ...
                orbital = true, LDos = output);
            cleanup = onCleanup(@()close(axesHandle.Parent));
            testCase.verifyTrue(isKey(allDos, "Total"));
            testCase.verifyTrue(isKey(allDos, "Site 0 Fe"));
            testCase.verifyTrue(isKey(allDos, "Site 1 O"));
            testCase.verifyTrue(isKey(allDos, "Fe"));
            testCase.verifyTrue(isKey(allDos, "O"));
            testCase.verifyTrue(isKey(allDos, "s"));
            oracle = testCase.oracle();
            testCase.verifyEqual(sort(string(allDos.keys)), ...
                sort(string(oracle.dos_keys)).');
            testCase.verifyEqual(string(axesHandle.Parent.Visible), "off");
            clear cleanup
        end

        function chemicalEnvironmentWorkflow(testCase)
            configuration = ...
                kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                ChemEnvConfig();
            callback = @(config, structure, strategy, valences) ...
                struct("config", config, "structure", structure, ...
                "strategy", strategy, "valences", valences);
            [status, result, transcript] = ...
                kssolv.analysis.matgenlab.cli.get_environment.main( ...
                configuration = configuration, structure = "fixture", ...
                compute_callback = callback, Print = false);
            testCase.verifyEqual(status, 0);
            testCase.verifyEqual(result.structure, "fixture");
            testCase.verifySubstring(transcript, ...
                "Chemical Environment package (ChemEnv)");
            testCase.verifySubstring(transcript, ...
                "Thank you for using the ChemEnv package");
            oracle = testCase.oracle();
            testCase.verifyEqual(status, oracle.environment_status);
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.get_environment.main( ...
                setup = true, configuration = configuration, ...
                compute_callback = callback, Print = false), ...
                "KSSOLV:Matgenlab:ChemEnvCLI:SetupCallbackRequired");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.get_environment.main( ...
                message_level = "LOUD", configuration = configuration, ...
                compute_callback = callback, Print = false), ...
                "KSSOLV:Matgenlab:ChemEnvCLI:MessageLevel");
        end
    end
    methods (Static, Access = private)
        function value = oracle()
            root = fileparts(fileparts(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath")))))));
            value = jsondecode(fileread(fullfile(root, "dev", ...
                "matgenlab", "oracles", ...
                "cli_feff_environment_2026.5.4.json")));
        end
    end
end
