classdef PmgAnalyzeInventoryTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 pmg-analyze compatibility tests.

    methods (Test)
        function detailedEnergyAndCacheMatchFrozenOutput(testCase)
            [work, cleanup, oracle] = testCase.preparedWork(); %#ok<ASGLU>
            cd(work);
            [output, status, result] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                get_energies("run", true, false, false, ...
                "energy_per_atom", "simple"));
            testCase.verifyEqual(status, oracle.energy.status);
            testCase.verifyEqual(output, string(oracle.energy.stdout));
            testCase.verifyTrue(isfile("vasp_data.gz"));
            testCase.verifyNumElements(result.rows, 1);
            testCase.verifyEqual(result.rows.formula, ...
                string(oracle.energy.formula));
            testCase.verifyEqual(result.rows.energy, ...
                oracle.energy.energy, AbsTol = 1e-10);
            testCase.verifyEqual(result.rows.energy_per_atom, ...
                oracle.energy.energy_per_atom, AbsTol = 1e-10);
            testCase.verifyEqual(result.rows.volume_change_percent, ...
                oracle.energy.volume_change_percent, AbsTol = 1e-12);

            [cachedOutput, cachedStatus, cached] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                get_energies("run", false, false, false, ...
                "filename", "simple"));
            testCase.verifyEqual(cachedStatus, oracle.cached.status);
            testCase.verifyEqual(cachedOutput, ...
                string(oracle.cached.stdout));
            testCase.verifyEqual(cached.rows.energy, ...
                oracle.energy.energy, AbsTol = 1e-10);
            clear cleanup
        end

        function quickEnergyMatchesFrozenOutput(testCase)
            [work, cleanup, oracle] = testCase.preparedWork(); %#ok<ASGLU>
            cd(work);
            [output, status, result] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                get_energies("quick", true, false, true, ...
                "energy_per_atom", "simple"));
            testCase.verifyEqual(status, oracle.quick.status);
            testCase.verifyEqual(output, string(oracle.quick.stdout));
            testCase.verifyTrue(result.quick);
            testCase.verifyEqual(result.rows.formula, ...
                string(oracle.quick.formula));
            testCase.verifyEqual(result.rows.energy, ...
                oracle.quick.energy, AbsTol = 1e-12);
            testCase.verifyEmpty(result.rows.volume_change_percent);
            clear cleanup
        end

        function magnetizationsMatchFrozenOutput(testCase)
            [work, cleanup, oracle] = testCase.preparedWork(); %#ok<ASGLU>
            cd(work);
            [selectedOutput, selectedStatus, selected] = ...
                testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                get_magnetizations("run", [0, 1]));
            testCase.verifyEqual(selectedStatus, ...
                oracle.magnetization_selected.status);
            testCase.verifyEqual(selectedOutput, ...
                string(oracle.magnetization_selected.stdout));
            testCase.verifyEqual(selected.rows.ion_indices, [0, 1]);
            testCase.verifyEqual(selected.rows.magnetizations, ...
                reshape(oracle.magnetization_selected.values, 1, []), ...
                AbsTol = 0);

            [allOutput, allStatus, allResult] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                get_magnetizations("run", []));
            testCase.verifyEqual(allStatus, ...
                oracle.magnetization_all.status);
            testCase.verifyEqual(allOutput, ...
                string(oracle.magnetization_all.stdout));
            testCase.verifyEqual(allResult.rows.magnetizations, ...
                reshape(oracle.magnetization_all.values, 1, []), ...
                AbsTol = 0);
            clear cleanup
        end

        function dispatcherUsesUpstreamPriorityAndRange(testCase)
            [work, cleanup, oracle] = testCase.preparedWork(); %#ok<ASGLU>
            cd(work);
            energyArgs = struct("directories", "run", ...
                "get_energies", false, "ion_list", [], ...
                "reanalyze", true, "verbose", false, "quick", false, ...
                "sort", "energy_per_atom", "format", "simple");
            [energyOutput, status, result] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                analyze(energyArgs));
            testCase.verifyEqual(status, 0);
            testCase.verifyEqual(energyOutput, ...
                string(oracle.energy.stdout));
            testCase.verifyEqual(result.rows.formula, ...
                string(oracle.energy.formula));

            magneticArgs = struct("directories", "run", ...
                "get_energies", false, "ion_list", "0-1");
            [magneticOutput, status] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                analyze(magneticArgs));
            testCase.verifyEqual(status, 0);
            testCase.verifyEqual(magneticOutput, ...
                string(oracle.magnetization_selected.stdout));

            energyArgs.get_energies = true;
            energyArgs.ion_list = "0-1";
            [priorityOutput, status] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                analyze(energyArgs));
            testCase.verifyEqual(status, 0);
            testCase.verifyEqual(priorityOutput, ...
                string(oracle.energy.stdout));
            clear cleanup
        end

        function nativeFormatsAndFailuresAreExplicit(testCase)
            [work, cleanup] = testCase.preparedWork(); %#ok<ASGLU>
            cd(work);
            rows = {"run/vasprun.xml.gz", "Li1H1", ...
                "-6.82078", "-3.41039", "0.00"};
            headers = ["Directory", "Formula", "Energy", ...
                "E/Atom", "% vol chg"];
            github = kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                tabulate_native(rows, headers, "github");
            testCase.verifyTrue(startsWith(github, "| Directory"));
            testCase.verifyTrue(contains(github, "| -6.82078 |"));
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                tabulate_native(rows, headers, "not-a-format"), ...
                "KSSOLV:Matgenlab:PmgAnalyze:TableFormat");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                get_energies("missing", false, false, false, ...
                "energy_per_atom", "simple"), ...
                "KSSOLV:Matgenlab:PmgAnalyze:Directory");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                get_magnetizations("run", -1), ...
                "KSSOLV:Matgenlab:PmgAnalyze:IonList");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                analyze(struct("directories", "run", ...
                "ion_list", "All", "get_energies", false)), ...
                "KSSOLV:Matgenlab:PmgAnalyze:AllIonList");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_analyze. ...
                analyze(struct("directories", "run", ...
                "ion_list", "invalid", "get_energies", false)), ...
                "KSSOLV:Matgenlab:PmgAnalyze:IonRange");
            clear cleanup
        end
    end

    methods (Static, Access = private)
        function [output, status, result] = capture(functionHandle) %#ok<INUSD>
            status = [];
            result = [];
            output = string(evalc( ...
                "[status, result] = functionHandle();"));
        end

        function [work, cleanup, oracle] = preparedWork()
            here = string(fileparts(mfilename("fullpath")));
            fixtures = fullfile(here, "+fixtures", "+pmg_analyze");
            quick = fullfile(here, "..", "+apps", "+borg", ...
                "+fixtures", "+simple_vasp");
            work = string(tempname);
            mkdir(work);
            mkdir(fullfile(work, "run"));
            mkdir(fullfile(work, "quick"));
            copyfile(fullfile(fixtures, "*"), fullfile(work, "run"));
            copyfile(fullfile(quick, "*"), fullfile(work, "quick"));
            previous = string(pwd);
            cleanup = onCleanup(@() restore(previous, work));
            repository = here;
            for index = 1:5
                repository = string(fileparts(repository));
            end
            oracle = jsondecode(fileread(fullfile(repository, ...
                "dev", "matgenlab", "oracles", ...
                "pmg_analyze_2026.5.4.json")));
        end
    end
end

function restore(previous, work)
cd(previous);
if isfolder(work), rmdir(work, "s"); end
end
