classdef PmgStructureInventoryTest < matlab.unittest.TestCase
    % Frozen pymatgen 2026.5.4 pmg-structure compatibility tests.

    methods (Test)
        function frozenSymmetryOutput(testCase)
            [fixtures, oracle] = testCase.fixtureData();
            args = struct("filenames", fullfile(fixtures, "Li2O.cif"), ...
                "symmetry", 0.1);
            [output, rows] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_symmetry(args));
            output = strrep(output, fixtures, "<FIXTURES>");
            testCase.verifyEqual(output, string(oracle.symmetry.stdout));
            testCase.verifyEqual(rows.international, ...
                string(oracle.symmetry.international));
            testCase.verifyEqual(rows.number, oracle.symmetry.number);
            testCase.verifyEqual(rows.hall, string(oracle.symmetry.hall));
        end

        function frozenLocalEnvironment(testCase)
            [fixtures, oracle] = testCase.fixtureData();
            args = struct("filenames", fullfile(fixtures, "Li2O.cif"), ...
                "localenv", "Li-O=3");
            [output, result] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_localenv(args));
            output = strrep(output, fixtures, "<FIXTURES>");
            testCase.verifyEqual(output, string(oracle.localenv.stdout));
            testCase.verifyNumElements(result.rows, 8);
            testCase.verifyEqual(result.rows(1).distances, ...
                reshape(oracle.localenv.first_site_distances, 1, []), ...
                "AbsTol", 2e-12);
            testCase.verifyEqual([result.rows.index], 0:7);
        end

        function frozenComparisonGrouping(testCase)
            [fixtures, oracle] = testCase.fixtureData();
            filenames = {fullfile(fixtures, "Li2O.cif"), ...
                fullfile(fixtures, "Li.cif")};
            args = struct("filenames", {filenames}, "group", "element");
            [elementOutput, elementGroups] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                compare_structures(args));
            elementOutput = strrep(elementOutput, fixtures, "<FIXTURES>");
            testCase.verifyEqual(elementOutput, ...
                string(oracle.element_group_stdout));
            testCase.verifyEqual(elementGroups{1}.formula, "Li8 O4");

            args.group = "species";
            [speciesOutput, speciesGroups] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                compare_structures(args));
            speciesOutput = strrep(speciesOutput, fixtures, "<FIXTURES>");
            testCase.verifyEqual(speciesOutput, ...
                string(oracle.species_group_stdout));
            testCase.verifyEqual(speciesGroups{1}.formula, "Li1");
        end

        function convertsFormatsAndPrimitiveByName(testCase)
            [fixtures, ~] = testCase.fixtureData();
            temporary = string(tempname);
            mkdir(temporary);
            cleanup = onCleanup(@() rmdir(temporary, "s"));
            input = fullfile(fixtures, "Li2O.cif");
            output = fullfile(temporary, "POSCAR_Li2O_test");
            args = struct("filenames", {{input, output}});
            result = kssolv.analysis.matgenlab.cli.pmg_structure. ...
                convert_fmt(args);
            testCase.verifyTrue(isfile(output));
            testCase.verifyEqual(result.format, "poscar");
            converted = kssolv.analysis.matgenlab.core.Structure. ...
                from_file(output, "poscar");
            testCase.verifyEqual(converted.formula, "Li8 O4");

            primitiveOutput = fullfile(temporary, "POSCAR_Li2O_prim");
            args.filenames = {input, primitiveOutput};
            primitive = kssolv.analysis.matgenlab.cli.pmg_structure. ...
                convert_fmt(args);
            testCase.verifyTrue(primitive.primitive);
            testCase.verifyLessThan( ...
                primitive.structure.num_sites, converted.num_sites);
            clear cleanup
        end

        function dispatcherPriorityAndNoop(testCase)
            [fixtures, oracle] = testCase.fixtureData();
            args = struct("filenames", fullfile(fixtures, "Li2O.cif"), ...
                "convert", false, "symmetry", 0.1, ...
                "group", "", "localenv", "");
            [output, rows] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_structures(args));
            output = strrep(output, fixtures, "<FIXTURES>");
            testCase.verifyEqual(output, ...
                string(oracle.dispatch_symmetry_stdout));
            testCase.verifyEqual(rows.number, 225);
            testCase.verifyEmpty( ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_structures(struct()));
        end

        function validatesBoundaryAndFailureCases(testCase)
            [fixtures, ~] = testCase.fixtureData();
            oneFile = {fullfile(fixtures, "Li2O.cif")};
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                compare_structures(struct( ...
                    "filenames", {oneFile}, "group", "species")), ...
                "KSSOLV:Matgenlab:PmgStructure:ComparisonCount");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_localenv(struct( ...
                    "filenames", oneFile{1}, "localenv", "Li-O")), ...
                "KSSOLV:Matgenlab:PmgStructure:LocalEnvironment");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_symmetry(struct( ...
                    "filenames", oneFile{1}, "symmetry", 0)), ...
                "KSSOLV:Matgenlab:PmgStructure:SymmetryTolerance");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                convert_fmt(struct("filenames", oneFile)), ...
                "KSSOLV:Matgenlab:PmgStructure:FilenameCount");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                compare_structures(struct("filenames", ...
                    {{oneFile{1}, fullfile(fixtures, "missing.cif")}}, ...
                    "group", "species")), ...
                "KSSOLV:Matgenlab:PmgStructure:FileConversion");

            lithium = fullfile(fixtures, "Li.cif");
            duplicateArgs = struct("filenames", lithium, ...
                "localenv", ["Li-Li=3", "Li-Li=-1"]);
            [~, duplicateResult] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_localenv(duplicateArgs));
            testCase.verifyNumElements(duplicateResult.rows, 1);
            testCase.verifyEmpty(duplicateResult.rows.distances);

            extraTokenArgs = struct("filenames", lithium, ...
                "localenv", "Li-Li=3=ignored");
            [~, extraTokenResult] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_localenv(extraTokenArgs));
            testCase.verifyNotEmpty(extraTokenResult.rows.distances);

            emptyArgs = struct("filenames", strings(1, 0), ...
                "symmetry", 0.1);
            [~, emptyRows] = testCase.capture(@() ...
                kssolv.analysis.matgenlab.cli.pmg_structure. ...
                analyze_symmetry(emptyArgs));
            testCase.verifyEmpty(emptyRows);
        end
    end

    methods (Static, Access = private)
        function [output, value] = capture(functionHandle) %#ok<STOUT,INUSD>
            output = evalc("value = functionHandle();");
        end

        function [fixtures, oracle] = fixtureData()
            here = fileparts(mfilename("fullpath"));
            fixtures = fullfile(here, "+fixtures");
            repository = here;
            for index = 1:5
                repository = fileparts(repository);
            end
            oraclePath = fullfile(repository, "dev", "matgenlab", ...
                "oracles", "pmg_structure_2026.5.4.json");
            oracle = jsondecode(fileread(oraclePath));
        end
    end
end
