function report = runModelingIconVisualAcceptance(outputDirectory)
%RUNMODELINGICONVISUALACCEPTANCE Generate repeatable icon contact sheets.

arguments
    outputDirectory string = ""
end
root = string(workingTreeRoot());
addpath(fullfile(root, "+kssolv", "+core", "kssolv-3o"));
KSSOLV.startup();
if outputDirectory == ""
    stamp = string(datetime("now", "TimeZone", "local", ...
        "Format", "yyyyMMdd-HHmmss"));
    outputDirectory = fullfile(root, "dev", "modeling", ...
        "acceptance", "reports", "modeling-icons-" + stamp);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

catalog = struct( ...
    "iconIds", @()kssolv.ui.features.modeling. ...
        CommandPresentationCatalog.iconIds(), ...
    "categoryIds", @()kssolv.ui.features.modeling. ...
        CommandPresentationCatalog.categoryIds(), ...
    "utilityIds", @()kssolv.ui.features.modeling. ...
        CommandPresentationCatalog.utilityIds(), ...
    "sourceAssetPath", @(id, pixelSize)kssolv.ui.features.modeling. ...
        CommandPresentationCatalog.sourceAssetPath(id, pixelSize), ...
    "assetPath", @(id, pixelSize)kssolv.ui.features.modeling. ...
        CommandPresentationCatalog.assetPath(id, pixelSize), ...
    "validate", @()kssolv.ui.features.modeling. ...
        CommandPresentationCatalog.validate());
assetIds = [catalog.iconIds(); ...
    "category_" + catalog.categoryIds(); ...
    "history_" + catalog.utilityIds()];
masterMarkup = strings(size(assetIds));
for index = 1:numel(assetIds)
    path = catalog.sourceAssetPath(assetIds(index), 64);
    masterMarkup(index) = string(fileread(path));
end
report = struct( ...
    "phase", "Modeling-icon-visual-QA", ...
    "matlabRelease", string(version("-release")), ...
    "platform", string(computer), ...
    "assetCount", numel(assetIds), ...
    "uniqueMasterCount", numel(unique(masterMarkup)), ...
    "sizes", [16, 24, 64], ...
    "contactSheets", strings(0, 1), ...
    "passed", false, "error", "", ...
    "outputDirectory", outputDirectory);

try
    catalog.validate();
    for pixelSize = report.sizes
        path = fullfile(outputDirectory, ...
            "modeling-icons-" + string(pixelSize) + "px.png");
        createContactSheet(catalog, assetIds, pixelSize, path);
        report.contactSheets(end + 1, 1) = string(path);
    end
    report.passed = report.assetCount == 89 && ...
        report.uniqueMasterCount == report.assetCount && ...
        all(isfile(report.contactSheets));
catch exception
    report.error = string(getReport(exception, "extended", ...
        "hyperlinks", "off"));
end
writeText(fullfile(outputDirectory, "report.json"), ...
    jsonencode(report, PrettyPrint = true));
if ~report.passed
    error("KSSOLV:Modeling:IconVisualAcceptance", "%s", report.error);
end
end

function createContactSheet(catalog, assetIds, pixelSize, outputPath)
columns = 10;
rows = ceil(numel(assetIds) / columns);
figureHandle = uifigure("Visible", "off", ...
    "Color", [0.965, 0.976, 0.992], ...
    "Position", [40, 40, 1800, 1180], ...
    "Name", "Modeling icons " + string(pixelSize) + " px");
cleanup = onCleanup(@()delete(figureHandle));
outer = uigridlayout(figureHandle, [2, 1], ...
    "RowHeight", {62, "1x"}, "Padding", [16, 12, 16, 16], ...
    "RowSpacing", 10);
header = uigridlayout(outer, [2, 1], ...
    "RowHeight", {28, 22}, "Padding", 0, "RowSpacing", 0);
title = uilabel(header, "Text", ...
    "KSSOLV Modeling icons · " + string(pixelSize) + " px source", ...
    "FontSize", 19, "FontWeight", "bold", ...
    "FontColor", [0.08, 0.20, 0.36]);
title.Layout.Row = 1;
subtitle = uilabel(header, "Text", ...
    string(numel(assetIds)) + ...
    " semantic assets · native source scaled uniformly for comparison", ...
    "FontSize", 11, "FontColor", [0.34, 0.39, 0.46]);
subtitle.Layout.Row = 2;
sheet = uigridlayout(outer, [rows, columns], ...
    "RowHeight", repmat({"1x"}, 1, rows), ...
    "ColumnWidth", repmat({"1x"}, 1, columns), ...
    "Padding", 0, "RowSpacing", 6, "ColumnSpacing", 6);

for index = 1:numel(assetIds)
    panel = uipanel(sheet, "BorderType", "line", ...
        "BorderColor", [0.82, 0.86, 0.91], ...
        "BackgroundColor", [1, 1, 1]);
    panel.Layout.Row = ceil(index / columns);
    panel.Layout.Column = mod(index - 1, columns) + 1;
    tile = uigridlayout(panel, [2, 1], ...
        "RowHeight", {72, "1x"}, "Padding", [7, 6, 7, 5], ...
        "RowSpacing", 3);
    if pixelSize == 64
        iconPath = catalog.sourceAssetPath(assetIds(index), 64);
    else
        iconPath = catalog.assetPath(assetIds(index), pixelSize);
    end
    image = uiimage(tile, "ImageSource", iconPath, ...
        "ScaleMethod", "fit");
    image.Layout.Row = 1;
    label = uilabel(tile, ...
        "Text", replace(assetIds(index), "_", " "), ...
        "HorizontalAlignment", "center", ...
        "VerticalAlignment", "top", "WordWrap", "on", ...
        "FontName", "Arial", "FontSize", 8.5, ...
        "FontColor", [0.22, 0.25, 0.30]);
    label.Layout.Row = 2;
end
drawnow;
exportapp(figureHandle, outputPath);
clear cleanup
end

function writeText(path, value)
file = fopen(path, "w", "n", "UTF-8");
if file < 0
    error("KSSOLV:Modeling:AcceptanceWrite", ...
        "Cannot write acceptance report: %s", path);
end
cleanup = onCleanup(@()fclose(file));
fwrite(file, char(value), "char");
clear cleanup
end
