function report = runP6AdsorptionLocatorAcceptance(outputDirectory)
%RUNP6ADSORPTIONLOCATORACCEPTANCE Production locator/scoring-model gate.

arguments
    outputDirectory string = ""
end
root = string(workingTreeRoot());
addpath(fullfile(root, "+kssolv", "+core", "kssolv-3o"));
KSSOLV.startup();
if outputDirectory == ""
    stamp = string(datetime("now", "TimeZone", "local", ...
        "Format", "yyyyMMdd-HHmmss"));
    outputDirectory = fullfile(root, "dev", "modeling", ...
        "acceptance", "reports", "p6-adsorption-locator-" + stamp);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

report = struct("phase", "P6-adsorption-locator", ...
    "matlabRelease", string(version("-release")), ...
    "platform", string(computer), "productionShell", false, ...
    "projectAdsorbateResolved", false, "candidateCount", 0, ...
    "deterministic", false, "sorted", false, ...
    "scoringModel", "", "isEnergyModel", true, ...
    "mixtureResolved", false, "mixtureCandidateCount", 0, ...
    "energyContractPassed", false, "energySorted", false, ...
    "energyResultWindowCaptured", false, ...
    "uffScoringModel", "", "uffCandidateCount", 0, ...
    "uffEnergyContractPassed", false, "uffDeterministic", false, ...
    "uffSorted", false, "uffAppliedMetadataPassed", false, ...
    "uffResultWindowCaptured", false, ...
    "uffParameterDialogCaptured", false, ...
    "scientificLabelPassed", false, "resultWindowCaptured", false, ...
    "previewPassed", false, "applyPassed", false, ...
    "undoRedoPassed", false, ...
    "passed", false, "error", "", "outputDirectory", outputDirectory);

existing = kssolv.ui.util.DataStorage.getData("KSSOLVToolbox");
if isa(existing, "kssolv.KSSOLVToolbox") && isvalid(existing)
    error("KSSOLV:Modeling:ProductionQARequiresCleanSession", ...
        "Close the existing KSSOLV application before production QA.");
end

toolbox = kssolv();
cleanup = onCleanup(@()cleanupScenario(toolbox));
try
    app = toolbox.getAppContainer();
    app.WindowBounds = [80, 80, 1200, 800];
    app.Visible = true;
    report.productionShell = true;

    project = kssolv.ui.util.DataStorage.getData("Project");
    folder = project.findChildrenItem("Structure");
    slabItem = folder.createBlankStructure(false);
    slabItem.label = "P6 Locator Slab";
    slab = slabFixture();
    slabItem.data = kssolv.services.fileparser.ModeledStructureData( ...
        slab, slabItem.label);
    slabItem.showMoleculeDisplay();
    display = kssolv.ui.features.modeling.SessionRegistry. ...
        getInstance().getCurrentDisplay();
    if isempty(display)
        error("KSSOLV:Modeling:ProductionQADisplay", ...
            "Production KSSOLV did not register the locator slab document.");
    end
    adsorbateItem = folder.createBlankMolecule(false);
    adsorbateItem.label = "P6 COOH Adsorbate";
    adsorbate = carboxyl();
    adsorbateItem.data = kssolv.services.fileparser.ModeledStructureData( ...
        adsorbate, adsorbateItem.label);
    waterItem = folder.createBlankMolecule(false);
    waterItem.label = "P6 H2O Co-adsorbate";
    waterItem.data = kssolv.services.fileparser.ModeledStructureData( ...
        water(), waterItem.label);
    drawnow;

    parameters = struct("adsorbateStructureName", adsorbateItem.label, ...
        "siteTypes", "ontop bridge hollow", ...
        "heights", [1.8,2.1,2.4], "rotationStep", 45, ...
        "anchorAtom", 1, "orientationAtom", 2, ...
        "minimumDistance", .55, "maximumCandidates", 60, "seed", 19);
    enriched = kssolv.ui.features.modeling.ModelInputResolver. ...
        enrich("locate_adsorbate", parameters);
    report.projectAdsorbateResolved = ...
        isa(enriched.adsorbateModel, ...
        "kssolv.analysis.matgenlab.core.IMolecule") && ...
        enriched.adsorbateModel.num_sites == adsorbate.num_sites;
    first = kssolv.modeling.CommandExecutor.execute( ...
        slab, "locate_adsorbate", enriched);
    second = kssolv.modeling.CommandExecutor.execute( ...
        slab, "locate_adsorbate", enriched);
    report.candidateCount = first.analysis.candidateCount;
    report.deterministic = isequal( ...
        first.analysis.candidates, second.analysis.candidates);
    report.sorted = issorted([first.analysis.candidates.score]);
    report.scoringModel = first.analysis.scoringModel;
    report.isEnergyModel = first.analysis.isEnergyModel;
    report.scientificLabelPassed = ...
        first.analysis.searchKind == "geometry-candidate-search" && ...
        ~first.analysis.isEnergyModel && first.analysis.energyUnit == "" && ...
        contains(first.message, "not adsorption energies");

    mixtureParameters = parameters;
    mixtureParameters.adsorbateStructureName = ...
        adsorbateItem.label + "," + waterItem.label;
    mixtureParameters.maximumCandidates = 12;
    mixture = kssolv.ui.features.modeling.ModelInputResolver. ...
        enrich("locate_adsorbate", mixtureParameters);
    report.mixtureResolved = ...
        mixture.adsorbateModel.num_sites == adsorbate.num_sites + 3 && ...
        mixture.adsorbateModel.properties. ...
        adsorbateAssembly.componentCount == 2;
    mixtureResult = kssolv.modeling.CommandExecutor.execute( ...
        slab, "locate_adsorbate", mixture);
    report.mixtureCandidateCount = mixtureResult.analysis.candidateCount;

    contract = energyContract();
    energyParameters = enriched;
    energyParameters.scoringModel = contract.id;
    energyParameters.scoringFunction = @frozenEnergyOracle;
    energyParameters.scoringContract = contract;
    energyParameters.heights = [1.8, 2.2];
    energyParameters.rotationStep = 90;
    energyParameters.maximumCandidates = 16;
    energyResult = kssolv.modeling.CommandExecutor.execute( ...
        slab, "locate_adsorbate", energyParameters);
    report.energyContractPassed = energyResult.analysis.isEnergyModel && ...
        energyResult.analysis.energyUnit == "eV" && ...
        energyResult.analysis.scoringContract.validated && ...
        energyResult.analysis.scoringModel == contract.id;
    report.energySorted = issorted([energyResult.analysis.candidates.score]);
    writetable(kssolv.ui.features.modeling.AnalysisResultPresenter. ...
        adsorptionCandidateTable(energyResult), ...
        fullfile(outputDirectory, "energy-candidates.csv"));

    uffParameters = enriched;
    uffParameters.scoringModel = ...
        kssolv.modeling.adsorption.UffSurfaceScorer.Id;
    uffParameters.heights = [1.8, 2.2, 2.6];
    uffParameters.rotationStep = 90;
    uffParameters.maximumCandidates = 24;
    uffResult = kssolv.modeling.CommandExecutor.execute( ...
        slab, "locate_adsorbate", uffParameters);
    repeatedUffResult = kssolv.modeling.CommandExecutor.execute( ...
        slab, "locate_adsorbate", uffParameters);
    report.uffScoringModel = uffResult.analysis.scoringModel;
    report.uffCandidateCount = uffResult.analysis.candidateCount;
    report.uffEnergyContractPassed = ...
        uffResult.analysis.isEnergyModel && ...
        uffResult.analysis.energyUnit == "eV" && ...
        uffResult.analysis.scoringContract.validated && ...
        contains(uffResult.analysis.scoringContract.source, ...
            "10.1021/ja00051a040") && ...
        contains(uffResult.analysis.scoringContract.validationScope, ...
            "not predictive adsorption-enthalpy accuracy");
    report.uffDeterministic = isequal( ...
        uffResult.analysis.candidates, ...
        repeatedUffResult.analysis.candidates);
    report.uffSorted = issorted([uffResult.analysis.candidates.score]);
    uffApplied = kssolv.modeling.adsorption.AdsorptionLocator. ...
        applyCandidate(slab, enriched.adsorbateModel, ...
        uffResult.analysis.candidates(1));
    appliedMetadata = uffApplied.structure_properties.adsorptionCandidate;
    report.uffAppliedMetadataPassed = ...
        appliedMetadata.isEnergyModel && ...
        appliedMetadata.energyUnit == "eV" && ...
        contains(appliedMetadata.scoringContract.source, ...
            "10.1021/ja00051a040") && ...
        appliedMetadata.scoringContract.validationReference == ...
        uffResult.analysis.scoringContract.validationReference;
    writetable(kssolv.ui.features.modeling.AnalysisResultPresenter. ...
        adsorptionCandidateTable(uffResult), ...
        fullfile(outputDirectory, "uff-vdw-candidates.csv"));
    commandInfo = kssolv.modeling.CommandCatalog.find("locate_adsorbate");
    uffDialog = kssolv.ui.features.modeling.CommandDialog( ...
        commandInfo, display, struct( ...
        "adsorbateStructureName", adsorbateItem.label, ...
        "scoringModel", ...
            kssolv.modeling.adsorption.UffSurfaceScorer.Id));
    dialogCleanup = onCleanup(@()deleteIfValid(uffDialog));
    dialogFigure = uffDialog.getWidget();
    dialogFigure.Visible = "on";
    drawnow;
    exportapp(dialogFigure, fullfile(outputDirectory, ...
        "production-uff-scoring-parameter-dialog.png"));
    report.uffParameterDialogCaptured = true;
    clear dialogCleanup

    tableData = kssolv.ui.features.modeling. ...
        AnalysisResultPresenter.adsorptionCandidateTable(first);
    writetable(tableData, fullfile(outputDirectory, "candidates.csv"));
    kssolv.ui.features.modeling.AnalysisResultPresenter.present( ...
        "locate_adsorbate", slab, first, "P6 Locator", ...
        app, display, enriched.adsorbateModel);
    drawnow;
    pause(.3);
    figures = findall(groot, "Type", "figure");
    names = strings(size(figures));
    for index = 1:numel(figures), names(index) = figures(index).Name; end
    locatorIndex = find(contains(names, "Adsorption Locator"), 1);
    if ~isempty(locatorIndex)
        resultFigure = figures(locatorIndex);
        exportapp(resultFigure, fullfile(outputDirectory, ...
            "production-locator-results.png"));
        report.resultWindowCaptured = true;
        initialSites = display.getModel().num_sites;
        previewButton = findall(resultFigure, ...
            "Tag", "AdsorptionCandidatePreview");
        applyButton = findall(resultFigure, ...
            "Tag", "AdsorptionCandidateApply");
        if isscalar(previewButton) && isscalar(applyButton)
            previewButton.ButtonPushedFcn(previewButton, []);
            drawnow;
            report.previewPassed = display.isModelingPreviewActive() && ...
                display.getModel().num_sites == initialSites;
            applyButton.ButtonPushedFcn(applyButton, []);
            drawnow;
            applied = display.getModel();
            report.applyPassed = applied.num_sites == ...
                initialSites + adsorbate.num_sites && ...
                isfield(applied.structure_properties, ...
                "adsorptionCandidate") && ...
                ~applied.structure_properties. ...
                adsorptionCandidate.isEnergyModel;
            display.undo();
            undoPassed = display.getModel().num_sites == initialSites;
            display.redo();
            report.undoRedoPassed = undoPassed && ...
                display.getModel().num_sites == ...
                initialSites + adsorbate.num_sites;
            writeText(fullfile(outputDirectory, ...
                "applied-candidate.cif"), display.getModel().to(fmt = "cif"));
        end
    end
    kssolv.ui.features.modeling.AnalysisResultPresenter.present( ...
        "locate_adsorbate", slab, energyResult, "P6 Energy Contract", ...
        app, display, enriched.adsorbateModel);
    drawnow;
    pause(.3);
    figures = findall(groot, "Type", "figure");
    names = strings(size(figures));
    for index = 1:numel(figures), names(index) = figures(index).Name; end
    energyIndex = find(contains(names, "P6 Energy Contract"), 1);
    if ~isempty(energyIndex)
        resultFigure = figures(energyIndex);
        exportapp(resultFigure, fullfile(outputDirectory, ...
            "production-energy-locator-results.png"));
        report.energyResultWindowCaptured = true;
        delete(resultFigure);
    end
    kssolv.ui.features.modeling.AnalysisResultPresenter.present( ...
        "locate_adsorbate", slab, uffResult, "P6 UFF Surface Energy", ...
        app, display, enriched.adsorbateModel);
    drawnow;
    pause(.3);
    figures = findall(groot, "Type", "figure");
    names = strings(size(figures));
    for index = 1:numel(figures), names(index) = figures(index).Name; end
    uffIndex = find(contains(names, "P6 UFF Surface Energy"), 1);
    if ~isempty(uffIndex)
        resultFigure = figures(uffIndex);
        exportapp(resultFigure, fullfile(outputDirectory, ...
            "production-uff-vdw-locator-results.png"));
        report.uffResultWindowCaptured = true;
        delete(resultFigure);
    end
    report.passed = report.productionShell && ...
        report.projectAdsorbateResolved && report.candidateCount > 0 && ...
        report.deterministic && report.sorted && ...
        report.mixtureResolved && report.mixtureCandidateCount > 0 && ...
        report.energyContractPassed && report.energySorted && ...
        report.energyResultWindowCaptured && ...
        report.uffCandidateCount > 0 && ...
        report.uffEnergyContractPassed && report.uffDeterministic && ...
        report.uffSorted && report.uffAppliedMetadataPassed && ...
        report.uffResultWindowCaptured && ...
        report.uffParameterDialogCaptured && ...
        report.scientificLabelPassed && report.resultWindowCaptured && ...
        report.previewPassed && report.applyPassed && report.undoRedoPassed;
catch exception
    report.error = string(getReport(exception, "extended", ...
        "hyperlinks", "off"));
end
writeText(fullfile(outputDirectory, "report.json"), ...
    jsonencode(report, PrettyPrint = true));
if ~report.passed
    error("KSSOLV:Modeling:P6AdsorptionLocator", "%s", report.error);
end
clear cleanup
end

function slab = slabFixture()
lattice = diag([6, 6, 18]);
fractional = [ ...
    .25,.25,.45; .75,.25,.45; .25,.75,.45; .75,.75,.45; ...
    .25,.25,.50; .75,.25,.50; .25,.75,.50; .75,.75,.50];
slab = kssolv.analysis.matgenlab.core.Structure( ...
    lattice, repmat("Cu", 1, size(fractional, 1)), fractional, ...
    labels = "Cu" + string(1:size(fractional, 1)));
end

function molecule = carboxyl()
properties = struct("topology", struct("bonds", ...
    [1,2,2;1,3,1;3,4,1], "origin", "source", "schemaVersion", 1));
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    ["C","O","O","H"], ...
    [0,0,0;1.23,0,0;-.65,1.12,0;-1.1,1.9,0], ...
    charge_spin_check = false, properties = properties);
end

function molecule = water()
properties = struct("topology", struct("bonds", ...
    [1,2,1;1,3,1], "origin", "source", "schemaVersion", 1));
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    ["O","H","H"], [0,0,0;.9572,0,0;-.239,.927,0], ...
    charge_spin_check = false, properties = properties);
end

function contract = energyContract()
contract = struct("id", "kssolv-p6-frozen-energy-oracle-v1", ...
    "isEnergyModel", true, "scoreUnit", "eV", ...
    "source", "P6 acceptance frozen analytic oracle", ...
    "version", "1", "validated", true, ...
    "validationReference", ...
        "runP6AdsorptionLocatorAcceptance/frozenEnergyOracle", ...
    "limitations", ...
        "Acceptance contract oracle only; no physical transferability");
end

function energy = frozenEnergyOracle(~, ~, ~, context)
energy = (context.height - 2.2)^2 + ...
    abs(context.rotationDegrees - 90) / 1000 + ...
    context.siteIndex / 1e5;
end

function cleanupScenario(toolbox)
figures = findall(groot, "Type", "figure");
for index = 1:numel(figures)
    if any(contains(string(figures(index).Name), ...
            ["P6 Locator", "P6 Energy Contract", ...
            "P6 UFF Surface Energy"]))
        delete(figures(index));
    end
end
if ~isempty(toolbox) && isvalid(toolbox), delete(toolbox); end
registry = kssolv.ui.util.DataStorage.getData("ModelingSessionRegistry");
if ~isempty(registry) && isvalid(registry), delete(registry); end
kssolv.ui.util.DataStorage.removeData("ModelingSessionRegistry");
kssolv.ui.util.DataStorage.removeData("Project");
kssolv.ui.util.DataStorage.removeData("ProjectFilename");
end

function writeText(path, value)
file = fopen(path, "w", "n", "UTF-8");
if file < 0
    error("KSSOLV:Modeling:AcceptanceWrite", ...
        "Cannot write acceptance report: %s", path);
end
cleanup = onCleanup(@()fclose(file));
fwrite(file, char(value), "char");
clear cleanup
end

function deleteIfValid(value)
if ~isempty(value) && isvalid(value), delete(value); end
end
