function report = runP6PredictiveAdsorptionAcceptance(outputDirectory)
%RUNP6PREDICTIVEADSORPTIONACCEPTANCE External graphitic physisorption gate.

arguments
    outputDirectory string = ""
end
root = string(workingTreeRoot());
addpath(fullfile(root, "+kssolv", "+core", "kssolv-3o"));
KSSOLV.startup();
if outputDirectory == ""
    stamp = string(datetime("now", "TimeZone", "local", ...
        "Format", "yyyyMMdd-HHmmss"));
    outputDirectory = fullfile(root, "dev", "modeling", ...
        "acceptance", "reports", ...
        "p6-predictive-adsorption-" + stamp);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

benchmark = kssolv.modeling.adsorption. ...
    AdsorptionPredictiveBenchmark.rareGasGraphite();
entries = benchmark.entries;
symbols = string({entries.symbol})';
referenceEnergy = [entries.referenceBindingEnergyEv]';
predictedEnergy = [entries.predictedBindingEnergyEv]';
energyError = [entries.absoluteEnergyErrorEv]';
referenceDistance = [entries.referenceDistanceAngstrom]';
predictedDistance = [entries.predictedDistanceAngstrom]';
distanceError = [entries.absoluteDistanceErrorAngstrom]';
results = table(symbols, referenceEnergy, predictedEnergy, energyError, ...
    referenceDistance, predictedDistance, distanceError, ...
    VariableNames = ["Adsorbate", "ReferenceBindingEnergyEv", ...
    "UffBindingEnergyEv", "AbsoluteEnergyErrorEv", ...
    "ReferenceDistanceAngstrom", "UffDistanceAngstrom", ...
    "AbsoluteDistanceErrorAngstrom"]);
writetable(results, fullfile(outputDirectory, ...
    "rare-gas-graphite-benchmark.csv"));

figureHandle = figure(Visible = "off", Color = "w", ...
    Position = [100, 100, 1080, 460]);
cleanup = onCleanup(@()deleteIfValid(figureHandle));
layout = tiledlayout(figureHandle, 1, 2, ...
    Padding = "compact", TileSpacing = "compact");
title(layout, "UFF graphitic physisorption vs primary experiment", ...
    FontWeight = "bold");
nexttile(layout);
bar([referenceEnergy, predictedEnergy]);
xticks(1:numel(symbols));
xticklabels(symbols);
ylabel("Binding interaction energy (eV)");
legend(["Rybolt–Pierotti experiment", "KSSOLV UFF"], ...
    Location = "northwest");
grid on;
nexttile(layout);
bar([referenceDistance, predictedDistance]);
xticks(1:numel(symbols));
xticklabels(symbols);
ylabel("Potential-minimum distance (Å)");
legend(["Rybolt–Pierotti experiment", "KSSOLV UFF"], ...
    Location = "northwest");
grid on;
exportgraphics(figureHandle, fullfile(outputDirectory, ...
    "rare-gas-graphite-benchmark.png"), Resolution = 180);

report = struct( ...
    "phase", "P6-predictive-adsorption", ...
    "generatedAtUtc", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
    "matlabRelease", string(version("-release")), ...
    "platform", string(computer), ...
    "benchmarkId", benchmark.id, ...
    "scoringModel", benchmark.scoringModel, ...
    "referenceDoi", benchmark.reference.doi, ...
    "parameterFittedToReference", ...
        benchmark.parameterFittedToReference, ...
    "referenceOrder", benchmark.referenceOrder, ...
    "predictedOrder", benchmark.predictedOrder, ...
    "rankingExact", benchmark.rankingExact, ...
    "energyMaeEv", benchmark.energyMaeEv, ...
    "energyMaeThresholdEv", benchmark.energyMaeThresholdEv, ...
    "distanceMaeAngstrom", benchmark.distanceMaeAngstrom, ...
    "distanceMaeThresholdAngstrom", ...
        benchmark.distanceMaeThresholdAngstrom, ...
    "validationScope", benchmark.validationScope, ...
    "limitations", benchmark.limitations, ...
    "passed", benchmark.passed, ...
    "outputDirectory", outputDirectory);
writeText(fullfile(outputDirectory, "report.json"), ...
    jsonencode(report, PrettyPrint = true));
writeReadme(fullfile(outputDirectory, "README.md"), report);
if ~report.passed
    error("KSSOLV:Modeling:PredictiveAdsorptionAcceptance", ...
        "UFF failed the frozen rare-gas/graphite predictive benchmark.");
end
clear cleanup
end

function writeReadme(path, report)
lines = [ ...
    "# P6 predictive adsorption benchmark";
    "";
    "- Scorer: `" + report.scoringModel + "`";
    "- Primary reference DOI: `" + report.referenceDoi + "`";
    "- Reference order: `" + strjoin(report.referenceOrder, " < ") + "`";
    "- Predicted order: `" + strjoin(report.predictedOrder, " < ") + "`";
    "- Energy MAE: `" + compose("%.6f", report.energyMaeEv) + ...
        " eV` (gate `" + compose("%.3f", ...
        report.energyMaeThresholdEv) + " eV`)";
    "- Distance MAE: `" + compose("%.4f", ...
        report.distanceMaeAngstrom) + " Å` (gate `" + ...
        compose("%.2f", report.distanceMaeThresholdAngstrom) + " Å`)";
    "- Parameters fitted to reference: **no**";
    "- Result: **pass**";
    "";
    "This closes predictive ranking only for rigid, low-coverage rare-gas " + ...
        "physisorption on graphitic carbon. It does not validate " + ...
        "chemisorption, polar surfaces, relaxation, adsorption enthalpy, " + ...
        "electrostatics or charge transfer."];
writeText(path, strjoin(lines, newline));
end

function writeText(path, value)
file = fopen(path, "w", "n", "UTF-8");
if file < 0
    error("KSSOLV:Modeling:AcceptanceWrite", ...
        "Cannot write acceptance report: %s", path);
end
cleanup = onCleanup(@()fclose(file));
fwrite(file, char(value), "char");
clear cleanup
end

function deleteIfValid(handle)
if ~isempty(handle) && isvalid(handle), delete(handle); end
end
