function report = runP5PointerEvidenceAcceptance(outputDirectory)
%RUNP5POINTEREVIDENCEACCEPTANCE Verify fail-closed physical P5 evidence.

arguments
    outputDirectory string = ""
end
root = string(workingTreeRoot());
if outputDirectory == ""
    stamp = string(datetime("now", "TimeZone", "local", ...
        "Format", "yyyyMMdd-HHmmss"));
    outputDirectory = fullfile(root, "dev", "modeling", ...
        "acceptance", "reports", "p5-pointer-evidence-" + stamp);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

evidenceDirectory = fullfile(root, "dev", "modeling", "acceptance", ...
    "reports", "p5-periodic-pointer-20260812-145945");
sourceReportPath = fullfile(evidenceDirectory, "report.json");
manifestPath = fullfile(root, "+kssolv", "+ui", "+components", ...
    "+figuredocument", "@MoleculeDisplay", "CrystalViewer", ...
    "build-manifest.json");
requiredImages = [ ...
    "01-live-periodic-distance.png"
    "02-measurement-editor-layout-fixed.png"
    "04-periodic-distance-edited-2p4.png"
    "05-periodic-distance-undo.png"
    "06-periodic-distance-redo.png"
    "07-periodic-angle-edited-112p25.png"
    "08-periodic-dihedral-edited-15-auto-remeasured.png"];

report = struct("phase", "P5-pointer-evidence", ...
    "evidenceDirectory", evidenceDirectory, ...
    "sourceReportPath", sourceReportPath, ...
    "runtimeSha256", "", "evidenceRuntimeSha256", "", ...
    "requiredImages", requiredImages, ...
    "missingImages", strings(0, 1), ...
    "distancePassed", false, "anglePassed", false, ...
    "dihedralPassed", false, "undoRedoPassed", false, ...
    "visualLayoutPassed", false, "runtimeMatched", false, ...
    "passed", false, "error", "", "outputDirectory", outputDirectory);
try
    if ~isfile(sourceReportPath)
        error("KSSOLV:Modeling:P5PointerReportMissing", ...
            "The P5 physical-pointer report is missing.");
    end
    source = jsondecode(fileread(sourceReportPath));
    manifest = jsondecode(fileread(manifestPath));
    report.runtimeSha256 = string(manifest.entrySha256);
    report.evidenceRuntimeSha256 = string(source.runtimeSha256);
    report.runtimeMatched = ...
        report.runtimeSha256 == report.evidenceRuntimeSha256;
    report.missingImages = requiredImages(~arrayfun( ...
        @(name)isfile(fullfile(evidenceDirectory, name)), requiredImages));
    report.distancePassed = logical(source.distance.passed) && ...
        abs(source.distance.remeasuredAngstrom - 2.4) < 1e-8;
    report.anglePassed = logical(source.angle.passed) && ...
        abs(source.angle.remeasuredDegrees - 112.25) < 1e-8;
    report.dihedralPassed = logical(source.dihedral.passed) && ...
        logical(source.dihedral.distinctSourceSites) && ...
        logical(source.dihedral.automaticPeriodicImageRemeasurement) && ...
        abs(source.dihedral.remeasuredDegrees - 15) < 1e-8;
    report.undoRedoPassed = ...
        abs(source.distance.undoAngstrom - 2.35126) < 1e-8 && ...
        abs(source.distance.redoAngstrom - 2.4) < 1e-8;
    report.visualLayoutPassed = logical(source.visualLayoutPassed);
    report.passed = logical(source.passed) && report.runtimeMatched && ...
        isempty(report.missingImages) && report.distancePassed && ...
        report.anglePassed && report.dihedralPassed && ...
        report.undoRedoPassed && report.visualLayoutPassed;
catch exception
    report.error = string(getReport(exception, "extended", ...
        "hyperlinks", "off"));
end

writeText(fullfile(outputDirectory, "report.json"), ...
    jsonencode(report, PrettyPrint = true));
if ~report.passed
    error("KSSOLV:Modeling:P5PointerEvidence", "%s", report.error);
end
end

function writeText(path, value)
file = fopen(path, "w", "n", "UTF-8");
if file < 0
    error("KSSOLV:Modeling:AcceptanceWrite", ...
        "Cannot write acceptance report: %s", path);
end
cleanup = onCleanup(@()fclose(file));
fwrite(file, char(value), "char");
clear cleanup
end
