function report = runP6GenericAdsorbateAcceptance(outputDirectory)
%RUNP6GENERICADSORBATEACCEPTANCE Production-shell generic adsorbate gate.

arguments
    outputDirectory string = ""
end
root = string(workingTreeRoot());
addpath(fullfile(root, "+kssolv", "+core", "kssolv-3o"));
KSSOLV.startup();
if outputDirectory == ""
    stamp = string(datetime("now", "TimeZone", "local", ...
        "Format", "yyyyMMdd-HHmmss"));
    outputDirectory = fullfile(root, "dev", "modeling", ...
        "acceptance", "reports", "p6-generic-adsorbate-" + stamp);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

report = struct("phase", "P6-generic-adsorbate", ...
    "matlabRelease", string(version("-release")), ...
    "platform", string(computer), "productionShell", false, ...
    "presetCount", 0, "presetsPassed", strings(0, 1), ...
    "carboxylTransactionPassed", false, ...
    "multiAnchorPassed", false, "undoRedoPassed", false, ...
    "metadataSchemaVersion", 0, "passed", false, "error", "", ...
    "outputDirectory", outputDirectory);

existing = kssolv.ui.util.DataStorage.getData("KSSOLVToolbox");
if isa(existing, "kssolv.KSSOLVToolbox") && isvalid(existing)
    error("KSSOLV:Modeling:ProductionQARequiresCleanSession", ...
        "Close the existing KSSOLV application before production QA.");
end

toolbox = kssolv();
cleanup = onCleanup(@()cleanupScenario(toolbox));
try
    app = toolbox.getAppContainer();
    app.WindowBounds = [80, 80, 1200, 800];
    app.Visible = true;
    report.productionShell = true;

    slab = slabFixture();
    project = kssolv.ui.util.DataStorage.getData("Project");
    folder = project.findChildrenItem("Structure");
    item = folder.createBlankStructure(false);
    item.label = "P6 Generic Adsorbate QA";
    item.data = kssolv.services.fileparser.ModeledStructureData( ...
        slab, item.label);
    item.showMoleculeDisplay();
    drawnow;
    display = kssolv.ui.features.modeling.SessionRegistry. ...
        getInstance().getCurrentDisplay();
    assert(~isempty(display));

    presets = adsorbatePresets();
    anchorSite = 5;
    anchor = slab.cart_coords(anchorSite, :);
    for index = 1:numel(presets)
        preset = presets{index};
        parameters = presetParameters(preset, anchorSite, anchor);
        result = kssolv.modeling.CommandExecutor.execute( ...
            slab, "place_adsorbate", parameters);
        metadata = result.model.structure_properties.adsorbate;
        assert(result.changed);
        assert(result.model.num_sites == slab.num_sites + ...
            numel(preset.species));
        assert(metadata.schemaVersion == 2);
        assert(metadata.name == preset.name);
        assert(isequal(metadata.species, preset.species));
        assert(isequal(metadata.bonds, preset.bonds));
        report.presetsPassed(end + 1, 1) = preset.id;
    end
    report.presetCount = numel(report.presetsPassed);

    carboxyl = presets{2};
    parameters = presetParameters(carboxyl, anchorSite, anchor);
    transaction = display.previewModelingCommand( ...
        "place_adsorbate", parameters);
    preview = transaction.preview();
    assert(preview.changed && preview.model.num_sites == slab.num_sites + 4);
    display.commitModelingTransaction(transaction, "place_adsorbate");
    committed = display.getModel();
    metadata = committed.structure_properties.adsorbate;
    report.metadataSchemaVersion = metadata.schemaVersion;
    report.carboxylTransactionPassed = metadata.name == "Carboxyl" && ...
        isequal(metadata.species, ["C", "O", "O", "H"]) && ...
        isequal(metadata.bonds, [1,2,2;1,3,1;3,4,1]);
    committedHash = kssolv.modeling.provenance.CanonicalHash.of(committed);
    display.undo();
    undoPassed = display.getModel().num_sites == slab.num_sites;
    display.redo();
    redoPassed = kssolv.modeling.provenance.CanonicalHash.of( ...
        display.getModel()) == committedHash;
    report.undoRedoPassed = undoPassed && redoPassed;

    multiCoordinates = [ ...
        slab.cart_coords(5, :) + [0,0,2]; ...
        mean(slab.cart_coords([5,6], :), 1) + [0,0,2]; ...
        slab.cart_coords(6, :) + [0,0,2]];
    multi = kssolv.modeling.CommandExecutor.execute(slab, ...
        "place_adsorbate", struct("anchorSites", [5,6], ...
        "adsorbateName", "Bidentate carboxylate", ...
        "adsorbateSpecies", ["O","C","O"], ...
        "adsorbateCoordinates", multiCoordinates, ...
        "adsorbateBonds", [1,2,1.5;2,3,1.5], ...
        "anchorAtomIndices", [1,3], "minimumDistance", .35));
    multiMetadata = multi.model.structure_properties.adsorbate;
    report.multiAnchorPassed = multi.model.num_sites == ...
        slab.num_sites + 3 && ...
        isequal(multiMetadata.hostAnchorSites, [5,6]) && ...
        isequal(multiMetadata.anchorAtomIndices, [1,3]) && ...
        all(abs(multiMetadata.hostBondLengths - 2) < 1e-12);

    drawnow;
    exportapp(display.Document.Figure, fullfile(outputDirectory, ...
        "production-carboxyl-transaction.png"));
    display.getModel().to(fullfile(outputDirectory, ...
        "cu-carboxyl.cif"), "cif");
    report.passed = report.productionShell && ...
        report.presetCount == numel(presets) && ...
        report.carboxylTransactionPassed && report.multiAnchorPassed && ...
        report.undoRedoPassed && report.metadataSchemaVersion == 2;
catch exception
    report.error = string(getReport(exception, "extended", ...
        "hyperlinks", "off"));
end
writeText(fullfile(outputDirectory, "report.json"), ...
    jsonencode(report, PrettyPrint = true));
if ~report.passed
    error("KSSOLV:Modeling:P6GenericAdsorbate", "%s", report.error);
end
clear cleanup
end

function parameters = presetParameters(preset, anchorSite, anchor)
parameters = struct("anchorSites", anchorSite, ...
    "adsorbateName", preset.name, ...
    "adsorbateSpecies", preset.species, ...
    "adsorbateCoordinates", preset.coordinates + anchor + [0,0,2], ...
    "adsorbateBonds", preset.bonds, ...
    "anchorAtomIndices", preset.anchorAtomIndex, ...
    "minimumDistance", .35);
end

function presets = adsorbatePresets()
presets = { ...
    preset("oxygen-hydrogen", "O-H fragment", ["O","H"], ...
        [0,0,0;0,0,.97], [1,2,1], 1), ...
    preset("carboxyl", "Carboxyl", ["C","O","O","H"], ...
        [0,0,0;1.23,0,0;-.65,1.12,0;-1.10,1.90,0], ...
        [1,2,2;1,3,1;3,4,1], 1), ...
    preset("amino", "Amino", ["N","H","H"], ...
        [0,0,0;.82,.52,0;-.82,.52,0], [1,2,1;1,3,1], 1), ...
    preset("methyl", "Methyl", ["C","H","H","H"], ...
        [0,0,0;.94,.33,0;-.47,.33,.81;-.47,.33,-.81], ...
        [1,2,1;1,3,1;1,4,1], 1), ...
    preset("carbon-monoxide", "Carbon monoxide", ["C","O"], ...
        [0,0,0;0,0,1.13], [1,2,3], 1), ...
    preset("carbon-dioxide", "Carbon dioxide", ["C","O","O"], ...
        [0,0,0;0,0,1.16;0,0,-1.16], [1,2,2;1,3,2], 1), ...
    preset("water", "Water", ["O","H","H"], ...
        [0,0,0;.76,.59,0;-.76,.59,0], [1,2,1;1,3,1], 1)};
end

function value = preset(id, name, species, coordinates, bonds, anchorAtomIndex)
value = struct("id", id, "name", name, "species", species, ...
    "coordinates", coordinates, "bonds", bonds, ...
    "anchorAtomIndex", anchorAtomIndex);
end

function slab = slabFixture()
lattice = diag([6, 6, 18]);
fractional = [ ...
    .25,.25,.45; .75,.25,.45; .25,.75,.45; .75,.75,.45; ...
    .25,.25,.50; .75,.25,.50; .25,.75,.50; .75,.75,.50];
slab = kssolv.analysis.matgenlab.core.Structure( ...
    lattice, repmat("Cu", 1, size(fractional, 1)), fractional, ...
    labels = "Cu" + string(1:size(fractional, 1)));
end

function cleanupScenario(toolbox)
if ~isempty(toolbox) && isvalid(toolbox), delete(toolbox); end
registry = kssolv.ui.util.DataStorage.getData("ModelingSessionRegistry");
if ~isempty(registry) && isvalid(registry), delete(registry); end
kssolv.ui.util.DataStorage.removeData("ModelingSessionRegistry");
kssolv.ui.util.DataStorage.removeData("Project");
kssolv.ui.util.DataStorage.removeData("ProjectFilename");
end

function writeText(path, value)
file = fopen(path, "w", "n", "UTF-8");
if file < 0
    error("KSSOLV:Modeling:AcceptanceWrite", ...
        "Cannot write acceptance report: %s", path);
end
cleanup = onCleanup(@()fclose(file));
fwrite(file, char(value), "char");
clear cleanup
end
