function report = runP4ForceFieldAcceptance(outputDirectory)
%RUNP4FORCEFIELDACCEPTANCE Production-shell energy minimization gate.

arguments
    outputDirectory string = ""
end
root = string(workingTreeRoot());
addpath(fullfile(root, "+kssolv", "+core", "kssolv-3o"));
KSSOLV.startup();
if outputDirectory == ""
    stamp = string(datetime("now", "TimeZone", "local", ...
        "Format", "yyyyMMdd-HHmmss"));
    outputDirectory = fullfile(root, "dev", "modeling", ...
        "acceptance", "reports", "p4-force-field-" + stamp);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

report = struct("phase", "P4-force-field", ...
    "matlabRelease", string(version("-release")), ...
    "platform", string(computer), "productionShell", false, ...
    "forceField", "", "initialEnergy", NaN, "finalEnergy", NaN, ...
    "maximumForce", NaN, "iterations", 0, "converged", false, ...
    "parameterSchemaVersion", NaN, "parameterSource", "", ...
    "fallbackByKind", struct(), "termCount", struct(), ...
    "gradientMaximumError", Inf, "torsionGradientMaximumError", Inf, ...
    "torsionTermCount", 0, "providerContractPassed", false, ...
    "parameterMetadataAuditable", false, ...
    "fixedAtomDisplacement", NaN, "topologyPreserved", false, ...
    "cleanIsNotMinimization", false, "undoRedoPassed", false, ...
    "passed", false, "error", "", "outputDirectory", outputDirectory);

existing = kssolv.ui.util.DataStorage.getData("KSSOLVToolbox");
if isa(existing, "kssolv.KSSOLVToolbox") && isvalid(existing)
    error("KSSOLV:Modeling:ProductionQARequiresCleanSession", ...
        "Close the existing KSSOLV application before production QA.");
end

toolbox = kssolv();
cleanup = onCleanup(@()cleanupScenario(toolbox));
try
    app = toolbox.getAppContainer();
    app.WindowBounds = [80, 80, 1200, 800];
    app.Visible = true;
    report.productionShell = true;

    molecule = moleculeFixture();
    originalCoordinates = molecule.cart_coords;
    originalTopology = molecule.properties.topology.bonds;
    molecule.to(fullfile(outputDirectory, ...
        "before-structure.mol"), "mol");
    state = kssolv.modeling.forcefield. ...
        MolecularMechanicsForceField.evaluate(molecule);
    kssolv.modeling.forcefield.ForceFieldProvider.validateState( ...
        state, molecule.num_sites);
    report.providerContractPassed = true;
    report.gradientMaximumError = max(abs(state.gradient - ...
        finiteDifference(molecule, molecule.cart_coords)), [], "all");
    torsionMolecule = torsionFixture();
    torsionState = kssolv.modeling.forcefield. ...
        MolecularMechanicsForceField.evaluate(torsionMolecule);
    report.torsionGradientMaximumError = max(abs( ...
        torsionState.gradient - finiteDifference( ...
        torsionMolecule, torsionMolecule.cart_coords)), [], "all");
    report.torsionTermCount = torsionState.termCount.torsion;
    fallback = kssolv.modeling.forcefield. ...
        GeometryParameterProvider.bond("Xe", "Xe", 1);
    report.parameterMetadataAuditable = fallback.fallback && ...
        fallback.source == "atomic-radius-fallback" && ...
        strlength(fallback.message) > 0;
    project = kssolv.ui.util.DataStorage.getData("Project");
    folder = project.findChildrenItem("Structure");
    item = folder.createBlankMolecule(false);
    item.label = "P4 Force-field QA";
    item.data = kssolv.services.fileparser.ModeledStructureData( ...
        molecule, item.label);
    item.showMoleculeDisplay();
    drawnow;
    display = kssolv.ui.features.modeling.SessionRegistry. ...
        getInstance().getCurrentDisplay();
    assert(~isempty(display));

    clean = display.previewModelingCommand("clean_geometry", ...
        struct("iterations", 2)).preview();
    report.cleanIsNotMinimization = ...
        ~clean.analysis.isEnergyMinimization;

    transaction = display.previewModelingCommand("optimize_geometry", ...
        struct("maximumIterations", 300, "forceTolerance", 1e-4, ...
        "fixedIndices", 1));
    preview = transaction.preview();
    analysis = preview.analysis;
    assert(preview.changed);
    report.forceField = analysis.forceField;
    report.parameterSchemaVersion = analysis.parameterSchemaVersion;
    report.parameterSource = analysis.parameterSource;
    report.fallbackByKind = analysis.fallbackByKind;
    report.termCount = analysis.termCount;
    report.initialEnergy = analysis.initialEnergy;
    report.finalEnergy = analysis.finalEnergy;
    report.maximumForce = analysis.maximumForce;
    report.iterations = analysis.iterations;
    report.converged = analysis.converged;
    report.fixedAtomDisplacement = norm( ...
        preview.model(1).coords - originalCoordinates(1, :));
    report.topologyPreserved = isequal( ...
        preview.model.properties.topology.bonds, originalTopology) && ...
        preview.model.formula == molecule.formula;

    display.commitModelingTransaction(transaction, "optimize_geometry");
    optimizedHash = kssolv.modeling.provenance.CanonicalHash.of( ...
        display.getModel());
    display.undo();
    undoPassed = isequal(display.getModel().cart_coords, ...
        molecule.cart_coords);
    display.redo();
    redoPassed = kssolv.modeling.provenance.CanonicalHash.of( ...
        display.getModel()) == optimizedHash;
    report.undoRedoPassed = undoPassed && redoPassed;

    drawnow;
    exportapp(display.Document.Figure, fullfile(outputDirectory, ...
        "production-force-field-result.png"));
    display.getModel().to(fullfile(outputDirectory, ...
        "after-structure.mol"), "mol");
    report.passed = report.productionShell && report.converged && ...
        report.finalEnergy < report.initialEnergy && ...
        report.maximumForce <= 1e-4 && ...
        report.fixedAtomDisplacement < 1e-10 && ...
        report.topologyPreserved && report.cleanIsNotMinimization && ...
        report.undoRedoPassed && report.parameterSchemaVersion == 2 && ...
        report.providerContractPassed && report.parameterMetadataAuditable && ...
        report.gradientMaximumError < 5e-5 && ...
        report.torsionGradientMaximumError < 3e-4 && ...
        report.torsionTermCount == 1;
catch exception
    report.error = string(getReport(exception, "extended", ...
        "hyperlinks", "off"));
end
writeText(fullfile(outputDirectory, "report.json"), ...
    jsonencode(report, PrettyPrint = true));
if ~report.passed
    error("KSSOLV:Modeling:P4ForceField", "%s", report.error);
end
clear cleanup
end

function molecule = moleculeFixture()
properties = struct("topology", struct("bonds", ...
    [1,2,1;1,3,1], "origin", "source", "schemaVersion", 1));
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    ["O","H","H"], ...
    [0,0,0;1.4,0,0;-0.1,1.3,0.2], ...
    charge_spin_check = false, properties = properties);
end

function molecule = torsionFixture()
properties = struct("topology", struct("bonds", ...
    [1,2,1;2,3,1;3,4,1], "origin", "source", "schemaVersion", 1));
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    ["C","C","C","C"], ...
    [0,0,0;1.53,0,0;2.1,1.35,0.1;3.2,1.7,1.0], ...
    charge_spin_check = false, properties = properties);
end

function gradient = finiteDifference(molecule, coordinates)
gradient = zeros(size(coordinates));
step = 1e-6;
for row = 1:size(coordinates, 1)
    for column = 1:3
        plus = coordinates;
        minus = coordinates;
        plus(row, column) = plus(row, column) + step;
        minus(row, column) = minus(row, column) - step;
        plusState = kssolv.modeling.forcefield. ...
            MolecularMechanicsForceField.evaluate(molecule, plus);
        minusState = kssolv.modeling.forcefield. ...
            MolecularMechanicsForceField.evaluate(molecule, minus);
        gradient(row, column) = ...
            (plusState.energy - minusState.energy) / (2 * step);
    end
end
end

function cleanupScenario(toolbox)
if ~isempty(toolbox) && isvalid(toolbox), delete(toolbox); end
registry = kssolv.ui.util.DataStorage.getData("ModelingSessionRegistry");
if ~isempty(registry) && isvalid(registry), delete(registry); end
kssolv.ui.util.DataStorage.removeData("ModelingSessionRegistry");
kssolv.ui.util.DataStorage.removeData("Project");
kssolv.ui.util.DataStorage.removeData("ProjectFilename");
end

function writeText(path, value)
file = fopen(path, "w", "n", "UTF-8");
if file < 0
    error("KSSOLV:Modeling:AcceptanceWrite", ...
        "Cannot write acceptance report: %s", path);
end
cleanup = onCleanup(@()fclose(file));
fwrite(file, char(value), "char");
clear cleanup
end
