function report = runP2ReferenceMoleculePointerEvidenceAcceptance(outputDirectory)
%RUNP2REFERENCEMOLECULEPOINTEREVIDENCEACCEPTANCE Verify fail-closed P2 evidence.

arguments
    outputDirectory string = ""
end
root = string(workingTreeRoot());
if outputDirectory == ""
    stamp = string(datetime("now", "TimeZone", "local", ...
        "Format", "yyyyMMdd-HHmmss"));
    outputDirectory = fullfile(root, "dev", "modeling", ...
        "acceptance", "reports", "p2-pointer-evidence-" + stamp);
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

evidenceDirectory = fullfile(root, "dev", "modeling", "acceptance", ...
    "reports", "p2-six-molecule-pointer-20260812-125404");
sourceReportPath = fullfile(evidenceDirectory, "report.json");
manifestPath = fullfile(root, "+kssolv", "+ui", "+components", ...
    "+figuredocument", "@MoleculeDisplay", "CrystalViewer", ...
    "build-manifest.json");
expected = [ ...
    molecule("water", "H2O", 3, 2, ...
        "01-water-h2o-3-atoms-2-bonds.png", ...
        "55b3e72623dc58c6a5a1c251716fe29dfc49996bd64a79bb23147e7634ec3758")
    molecule("ethanol", "H6C2O", 9, 8, ...
        "02-ethanol-h6c2o-9-atoms-8-bonds.png", ...
        "84869df05537573200db289a54c437458b727cde73bd9298bd20e64d2e691b64")
    molecule("formaldehyde", "H2CO", 4, 3, ...
        "03-formaldehyde-h2co-4-atoms-3-bonds.png", ...
        "146741521d5112b0c788e0f806bb9e3fb5e04aedfebf9466fa82a275f624f7cd")
    molecule("benzene", "H6C6", 12, 12, ...
        "04-benzene-h6c6-12-atoms-12-bonds.png", ...
        "da104e8ccaf5b28c9debf589409b8d42a953eb371c84acd5ebc5e46a686c4554")
    molecule("pyridine", "H5C5N", 11, 11, ...
        "05-pyridine-h5c5n-11-atoms-11-bonds.png", ...
        "8ec63cad27ecc1ae3a32b25106fccd88726138f50fd254127e333e5eb4233bea")
    molecule("benzamide", "H7C7NO", 16, 16, ...
        "06-benzamide-h7c7no-16-atoms-16-bonds.png", ...
        "1ea2fa54cc33eb1b5a0af58d93518894f37a1009685eb8228d8b6a4785f823e0")];

checks = repmat(struct("id", "", "formulaMatched", false, ...
    "countsMatched", false, "imagePresent", false, ...
    "imageHashMatched", false, "sourcePassed", false, ...
    "passed", false), numel(expected), 1);
report = struct("phase", "P2-pointer-evidence", ...
    "evidenceDirectory", evidenceDirectory, ...
    "sourceReportPath", sourceReportPath, ...
    "runtimeSha256", "", "evidenceRuntimeSha256", "", ...
    "runtimeMatched", false, "productionShell", false, ...
    "realPointerAndKeyboard", false, "moleculeCount", 0, ...
    "checks", checks, "passed", false, "error", "", ...
    "outputDirectory", outputDirectory);
try
    if ~isfile(sourceReportPath)
        error("KSSOLV:Modeling:P2PointerReportMissing", ...
            "The P2 real-pointer report is missing.");
    end
    source = jsondecode(fileread(sourceReportPath));
    manifest = jsondecode(fileread(manifestPath));
    report.runtimeSha256 = string(manifest.entrySha256);
    report.evidenceRuntimeSha256 = string(source.runtimeSha256);
    report.runtimeMatched = ...
        report.runtimeSha256 == report.evidenceRuntimeSha256;
    report.productionShell = logical(source.productionShell);
    report.realPointerAndKeyboard = logical(source.realPointerAndKeyboard);
    report.moleculeCount = double(source.moleculeCount);
    if numel(source.molecules) ~= numel(expected)
        error("KSSOLV:Modeling:P2PointerMoleculeCount", ...
            "Expected %d molecule evidence rows, got %d.", ...
            numel(expected), numel(source.molecules));
    end
    for index = 1:numel(expected)
        wanted = expected(index);
        matches = find(string({source.molecules.id}) == wanted.id);
        if numel(matches) ~= 1
            error("KSSOLV:Modeling:P2PointerMoleculeMissing", ...
                "Expected exactly one evidence row for %s.", wanted.id);
        end
        actual = source.molecules(matches);
        imagePath = fullfile(evidenceDirectory, wanted.image);
        imageInfo = dir(imagePath);
        imagePresent = isfile(imagePath) && ~isempty(imageInfo) && ...
            imageInfo.bytes > 10000;
        hashMatched = imagePresent && ...
            kssolv.ui.util.CrystalViewerRuntime.sha256(imagePath) == ...
            wanted.sha256 && string(actual.sha256) == wanted.sha256;
        checks(index) = struct( ...
            "id", wanted.id, ...
            "formulaMatched", string(actual.displayFormula) == wanted.formula, ...
            "countsMatched", double(actual.atomCount) == wanted.atoms && ...
                double(actual.bondCount) == wanted.bonds, ...
            "imagePresent", imagePresent, ...
            "imageHashMatched", hashMatched, ...
            "sourcePassed", logical(actual.passed), ...
            "passed", false);
        checks(index).passed = checks(index).formulaMatched && ...
            checks(index).countsMatched && checks(index).imagePresent && ...
            checks(index).imageHashMatched && checks(index).sourcePassed;
    end
    report.checks = checks;
    report.passed = logical(source.passed) && report.runtimeMatched && ...
        report.productionShell && report.realPointerAndKeyboard && ...
        report.moleculeCount == numel(expected) && all([checks.passed]);
catch exception
    report.error = string(getReport(exception, "extended", ...
        "hyperlinks", "off"));
end

writeText(fullfile(outputDirectory, "report.json"), ...
    jsonencode(report, PrettyPrint = true));
if ~report.passed
    error("KSSOLV:Modeling:P2PointerEvidence", "%s", report.error);
end
end

function value = molecule(id, formula, atoms, bonds, image, sha256)
value = struct("id", id, "formula", formula, "atoms", atoms, ...
    "bonds", bonds, "image", image, "sha256", sha256);
end

function writeText(path, value)
file = fopen(path, "w", "n", "UTF-8");
if file < 0
    error("KSSOLV:Modeling:AcceptanceWrite", ...
        "Cannot write acceptance report: %s", path);
end
cleanup = onCleanup(@()fclose(file));
fwrite(file, char(value), "char");
clear cleanup
end
