classdef LobsterLightStructureEnvironments < ...
        kssolv.analysis.matgenlab.analysis.chemenv. ...
        coordination_environments.LightStructureEnvironments
    %#ok<*AGROW>
    %LOBSTERLIGHTSTRUCTUREENVIRONMENTS Local environments from LOBSTER bonds.

    methods
        function obj = LobsterLightStructureEnvironments(strategy, varargin)
            if nargin == 0, strategy = []; end
            obj@kssolv.analysis.matgenlab.analysis.chemenv. ...
                coordination_environments.LightStructureEnvironments( ...
                strategy, varargin{:});
        end

        function value = as_dict(obj)
            sites = cell(1, numel(obj.all_nbs_sites));
            for index = 1:numel(sites)
                neighbor = obj.all_nbs_sites{index};
                sites{index} = struct("site", neighbor.site.as_dict(), ...
                    "index", neighbor.index - 1, ...
                    "image_cell", reshape(double(neighbor.image_cell), 1, 3));
            end
            sets = cell(size(obj.neighbors_sets));
            for siteIndex = 1:numel(sets)
                if isempty(obj.neighbors_sets{siteIndex})
                    sets{siteIndex} = [];
                else
                    sets{siteIndex} = cellfun(@(item) item.as_dict(), ...
                        obj.neighbors_sets{siteIndex}, ...
                        "UniformOutput", false);
                end
            end
            value = struct( ...
                "x_module", "pymatgen.analysis.lobster_env", ...
                "x_class", "LobsterLightStructureEnvironments", ...
                "strategy", obj.strategy, ...
                "structure", obj.structure.as_dict(), ...
                "coordination_environments", ...
                    {obj.coordination_environments}, ...
                "all_nbs_sites", {sites}, ...
                "neighbors_sets", {sets}, ...
                "valences", obj.valences);
        end
    end

    methods (Static)
        function obj = from_Lobster(listCeSymbol, listCsm, ...
                listPermutation, listNeighsite, listNeighisite, ...
                structure, valences)
            if nargin < 7, valences = []; end
            count = structure.num_sites;
            coordinationEnvironments = cell(1, count);
            neighborsSets = cell(1, count);
            allNeighbors = {};
            for siteIndex = 1:count
                symbol = itemAt(listCeSymbol, siteIndex);
                csm = itemAt(listCsm, siteIndex);
                permutation = itemAt(listPermutation, siteIndex);
                coordinationEnvironments{siteIndex} = {struct( ...
                    "ce_symbol", symbol, "ce_fraction", 1, ...
                    "csm", csm, "permutation", permutation)};
                indicesHere = [];
                sitesHere = itemAt(listNeighsite, siteIndex);
                siteIndices = itemAt(listNeighisite, siteIndex);
                if ~iscell(sitesHere), sitesHere = num2cell(sitesHere); end
                for neighborIndex = 1:numel(sitesHere)
                    neighborSite = sitesHere{neighborIndex};
                    originalIndex = siteIndices(neighborIndex);
                    difference = neighborSite.frac_coords - ...
                        structure(originalIndex).frac_coords;
                    image = round(difference);
                    if any(abs(difference - image) > 1e-7)
                        error("KSSOLV:Matgenlab:LobsterLSE:Image", ...
                            ['Differences between a site and its periodic ' ...
                            'image must be integral.']);
                    end
                    allNeighbors{end + 1} = struct( ...
                        "site", neighborSite, "index", originalIndex, ...
                        "image_cell", image);
                    indicesHere(end + 1) = numel(allNeighbors);
                end
                set = kssolv.analysis.matgenlab.analysis.chemenv. ...
                    coordination_environments. ...
                    LightStructureEnvironmentsNeighborsSet( ...
                    structure, siteIndex, allNeighbors, indicesHere);
                neighborsSets{siteIndex} = {set};
            end
            obj = kssolv.analysis.matgenlab.analysis. ...
                LobsterLightStructureEnvironments([], ...
                "coordination_environments", coordinationEnvironments, ...
                "all_nbs_sites", allNeighbors, ...
                "neighbors_sets", neighborsSets, ...
                "structure", structure, "valences", valences, ...
                "valences_origin", "user-defined");
        end
    end
end

function value = itemAt(input, index)
if iscell(input)
    value = input{index};
else
    value = input(index);
end
end
