classdef XRDCalculator < ...
        kssolv.analysis.matgenlab.analysis.AbstractDiffractionPatternCalculator
    %XRDCALCULATOR Calculate powder X-ray diffraction patterns.

    properties (Constant)
        AVAILABLE_RADIATION = [ ...
            "CuKa","CuKa2","CuKa1","CuKb1", ...
            "MoKa","MoKa2","MoKa1","MoKb1", ...
            "CrKa","CrKa2","CrKa1","CrKb1", ...
            "FeKa","FeKa2","FeKa1","FeKb1", ...
            "CoKa","CoKa2","CoKa1","CoKb1", ...
            "AgKa","AgKa2","AgKa1","AgKb1"]
    end

    properties (SetAccess = private)
        wavelength (1,1) double
        radiation (1,1) string = missing
        symprec (1,1) double = 0
        debye_waller_factors = struct()
    end

    methods
        function obj = XRDCalculator(wavelength, symprec, debyeWallerFactors)
            if nargin < 1 || isempty(wavelength), wavelength = "CuKa"; end
            if nargin < 2 || isempty(symprec), symprec = 0; end
            if nargin < 3 || isempty(debyeWallerFactors)
                debyeWallerFactors = struct();
            end
            if isnumeric(wavelength) && isscalar(wavelength)
                obj.wavelength = double(wavelength);
            elseif (ischar(wavelength) || ...
                    (isstring(wavelength) && isscalar(wavelength)))
                obj.radiation = string(wavelength);
                obj.wavelength = ...
                    kssolv.analysis.matgenlab.analysis.XRDCalculator. ...
                    radiationWavelength(obj.radiation);
            else
                error("KSSOLV:Matgenlab:XRDCalculator:WavelengthType", ...
                    "wavelength must be a numeric scalar or radiation name.");
            end
            if ~isfinite(obj.wavelength) || obj.wavelength <= 0
                error("KSSOLV:Matgenlab:XRDCalculator:Wavelength", ...
                    "wavelength must be a finite positive value.");
            end
            obj.symprec = double(symprec);
            obj.debye_waller_factors = debyeWallerFactors;
        end

        function pattern = get_pattern( ...
                obj, structure, scaled, two_theta_range)
            if nargin < 3 || isempty(scaled), scaled = true; end
            if nargin < 4, two_theta_range = [0, 90]; end
            pattern = ...
                kssolv.analysis.matgenlab.analysis. ...
                powder_diffraction_pattern( ...
                "xray", structure, obj.wavelength, obj.symprec, ...
                obj.debye_waller_factors, logical(scaled), ...
                two_theta_range);
        end
    end

    methods (Static, Access = private)
        function value = radiationWavelength(name)
            names = kssolv.analysis.matgenlab.analysis. ...
                XRDCalculator.AVAILABLE_RADIATION;
            values = [ ...
                1.54184,1.54439,1.54056,1.39222, ...
                0.71073,0.71359,0.70930,0.63229, ...
                2.29100,2.29361,2.28970,2.08487, ...
                1.93735,1.93998,1.93604,1.75661, ...
                1.79026,1.79285,1.78896,1.63079, ...
                0.560885,0.563813,0.559421,0.497082];
            index = find(names == string(name), 1);
            if isempty(index)
                error("KSSOLV:Matgenlab:XRDCalculator:Radiation", ...
                    "Unknown X-ray radiation '%s'.", name);
            end
            value = values(index);
        end
    end
end
