classdef OracleSmokeTest < matlab.unittest.TestCase
    methods (Test)
        function latticeReference(testCase)
            testCase.assumeTrue( ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.isAvailable(), ...
                "Pinned pymatgen reference environment is unavailable.");

            request = struct( ...
                "module", "pymatgen.core.lattice", ...
                "symbol", "Lattice", ...
                "construct", struct("method", "cubic", "args", {{3.0}}), ...
                "operations", {{struct("kind", "get", "name", "matrix")}});
            response = ...
                kssolv.analysis.matgenlab.test.support.PymatgenOracle.execute(request);

            testCase.verifyEqual(squeeze(response.results), 3 * eye(3), ...
                AbsTol = kssolv.analysis.matgenlab.internal.Tolerance.Lattice);
        end
    end
end
