function result = remoteConnectionSmoke()
%REMOTECONNECTIONSMOKE Minimal worker reachability check without discovery.
result = struct( ...
    "Hostname", string(java.net.InetAddress.getLocalHost.getHostName), ...
    "Result", 1 + 2, ...
    "Timestamp", datetime("now", "TimeZone", "UTC"));
end
