classdef RemoteEnvironmentProbe
    %REMOTEENVIRONMENTPROBE Discover a routed remote MATLAB installation.

    methods (Static)
        function configuration = prepareConfiguration(configuration)
            % Fill probe-only placeholders so connection transports can be
            % created before the editable configuration is complete.
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                normalize(configuration);
            standardSsh = configuration.ExecutionMode == "Standard" && ...
                configuration.ProfileSource == "ManagedSlurm" && ...
                configuration.ConnectionMode == "SSH";
            if ~standardSsh && ~any(configuration.ExecutionMode == ...
                    ["Bridge", "Mirror"])
                error("KSSOLV:Remote:EnvironmentProbeModeUnsupported", ...
                    "Environment discovery requires managed Standard SSH, " + ...
                    "Bridge, or Mirror mode.");
            end
            if strlength(configuration.Host) == 0
                error("KSSOLV:Remote:EnvironmentProbeHostRequired", ...
                    "Enter the SSH host before testing the connection.");
            end
            if strlength(configuration.Username) == 0
                error("KSSOLV:Remote:EnvironmentProbeUsernameRequired", ...
                    "Enter the SSH username before testing the connection.");
            end
            if strlength(configuration.ClusterMatlabRoot) == 0
                configuration.ClusterMatlabRoot = "/";
            end
            if strlength(configuration.RemoteJobStorageLocation) == 0
                configuration.RemoteJobStorageLocation = "/tmp";
            end
            if configuration.ExecutionMode == "Bridge" && ...
                    strlength(configuration.RemoteBridgeProfileName) == 0
                configuration.RemoteBridgeProfileName = "local";
            end
            if configuration.CodeDeploymentMode == "ClusterInstalled" && ...
                    strlength(configuration.RemoteKssolvRoot) == 0
                configuration.RemoteKssolvRoot = "/";
            end
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                sanitized(configuration);
        end

        function probe = run(configuration, credentialKeyRoot, progressPath)
            arguments
                configuration struct
                credentialKeyRoot (1, 1) string = fullfile( ...
                    prefdir, "KSSOLV", "remote", "credentials")
                progressPath (1, 1) string = ""
            end
            writePhase(progressPath, "Connecting");
            cipher = kssolv.services.remote.security.LocalCredentialCipher( ...
                credentialKeyRoot);
            configuration = kssolv.services.remote.diagnostics. ...
                RemoteEnvironmentProbe.prepareConfiguration(configuration);
            if configuration.ExecutionMode == "Standard"
                try
                    access = kssolv.services.remote.transport.SshRemoteAccess( ...
                        configuration, CredentialCipher=cipher);
                catch exception
                    connectionFailure(exception);
                end
                if strlength(configuration.PostLoginScript) > 0 || ...
                        configuration.PostLoginCommandTemplate ~= "{command}" || ...
                        ~isempty(configuration.PostLoginPromptRules)
                    access = kssolv.services.remote.transport.RemoteCommandAccess( ...
                        access, configuration);
                end
                probe = runWithAccess(configuration, access, progressPath);
            else
                factory = kssolv.services.remote.transport.RemoteAccessFactory( ...
                    CredentialCipher=cipher);
                probe = kssolv.services.remote.diagnostics.RemoteEnvironmentProbe. ...
                    runWithFactory(configuration, factory, progressPath);
            end
        end

        function probe = runWithFactory( ...
                configuration, accessFactory, progressPath)
            if nargin < 3
                progressPath = "";
            end
            configuration = kssolv.services.remote.diagnostics. ...
                RemoteEnvironmentProbe.prepareConfiguration(configuration);
            writePhase(progressPath, "Connecting");
            try
                access = accessFactory.create(configuration);
            catch exception
                connectionFailure(exception);
            end
            probe = runWithAccess(configuration, access, progressPath);
        end
    end
end

function probe = runWithAccess(configuration, access, progressPath)
if nargin < 3
    progressPath = "";
end
writePhase(progressPath, "Connecting");
connectionMarker = "KSSOLV_CONNECTION_OK";
connectionCommand = "printf '%s\n' " + shellQuote(connectionMarker);
try
    [status, output] = runLoginCommand(access, connectionCommand);
catch exception
    connectionFailure(exception);
end
if status ~= 0 || ~contains(string(output), connectionMarker)
    error("KSSOLV:Remote:EnvironmentConnectionFailed", ...
        "SSH connection check failed: %s", diagnosticText(output));
end

writePhase(progressPath, "PostLoginAndDiscovery");
scriptMarker = "KSSOLV_POST_LOGIN_SCRIPT_OK";
command = "printf '%s\n' " + shellQuote(scriptMarker) + "; " + ...
    discoveryCommand(configuration);
try
    [status, output] = access.runCommand(char(command));
catch exception
    if strlength(configuration.PostLoginScript) > 0
        error("KSSOLV:Remote:PostLoginScriptFailed", ...
            "The post-login script failed: %s", exception.message);
    end
    error("KSSOLV:Remote:EnvironmentProbeFailed", ...
        "Remote resource discovery failed: %s", exception.message);
end
if status ~= 0
    if strlength(configuration.PostLoginScript) > 0 && ...
            ~contains(string(output), scriptMarker)
        error("KSSOLV:Remote:PostLoginScriptFailed", ...
            "The post-login script returned an error: %s", ...
            diagnosticText(output));
    end
    error("KSSOLV:Remote:EnvironmentProbeFailed", ...
        "Remote resource discovery failed: %s", diagnosticText(output));
end
probe = parseOutput(string(output));
writePhase(progressPath, "Completed");
end

function [status, output] = runLoginCommand(access, command)
if ismethod(access, "runLoginCommand")
    [status, output] = access.runLoginCommand(char(command));
else
    [status, output] = access.runCommand(char(command));
end
end

function connectionFailure(exception)
error("KSSOLV:Remote:EnvironmentConnectionFailed", ...
    "Unable to establish the SSH connection: %s", exception.message);
end

function value = diagnosticText(output)
value = strip(string(output));
value = replace(value, ["KSSOLV_CONNECTION_OK", ...
    "KSSOLV_POST_LOGIN_SCRIPT_OK"], "");
value = strip(value);
if strlength(value) == 0
    value = "No additional diagnostic output was returned.";
end
end

function command = discoveryCommand(configuration)
profile = "local";
if configuration.ExecutionMode == "Bridge" && ...
        strlength(configuration.RemoteBridgeProfileName) > 0
    profile = configuration.RemoteBridgeProfileName;
end
profileLiteral = replace(profile, "'", "''");
matlabCode = ...
    "try;" + ...
    "fprintf('KSSOLV_DISCOVERY_ROOT=%s\n',matlabroot);" + ...
    "fprintf('KSSOLV_DISCOVERY_RELEASE=%s\n',version('-release'));" + ...
    "n=1;try;n=double(feature('numcores'));catch;end;" + ...
    "p=n;try;c=parcluster('" + profileLiteral + ...
    "');n=double(c.NumWorkers);p=n;" + ...
    "if isprop(c,'PreferredPoolNumWorkers');q=double(" + ...
    "c.PreferredPoolNumWorkers);if isfinite(q)&&q>0;p=q;end;end;catch;end;" + ...
    "n=max(1,floor(n));p=max(0,min(n,floor(p)));" + ...
    "fprintf('KSSOLV_DISCOVERY_WORKERS=%d\n',n);" + ...
    "fprintf('KSSOLV_DISCOVERY_POOL=%d\n',p);" + ...
    "catch ME;fprintf(2,'KSSOLV_DISCOVERY_ERROR=%s\n',ME.message);" + ...
    "exit(2);end";

candidates = "";
root = string(configuration.ClusterMatlabRoot);
if strlength(root) > 0 && root ~= "/"
    candidates = shellQuote(remoteJoin(root, "bin", "matlab")) + " ";
end
command = ...
    "matlab_executable=$(command -v matlab 2>/dev/null || true); " + ...
    "if test -z ""$matlab_executable""; then " + ...
    "for candidate in " + candidates + "; do " + ...
    "if test -x ""$candidate""; then matlab_executable=$candidate; " + ...
    "break; fi; done; fi; " + ...
    "if test -z ""$matlab_executable""; then " + ...
    "matlab_executable=$(find /usr/local/MATLAB /opt/MATLAB " + ...
    "/apps/MATLAB /shared/apps/MATLAB -path '*/bin/matlab' " + ...
    "-type f -perm -u+x 2>/dev/null | sort -r | head -n 1); fi; " + ...
    "if test -z ""$matlab_executable""; then " + ...
    "printf '%s\n' 'MATLAB executable was not found in PATH or common " + ...
    "installation directories.' >&2; exit 127; fi; " + ...
    "hostname_value=$(hostname 2>/dev/null || printf unknown); " + ...
    "effective_user=$(id -un 2>/dev/null || true); " + ...
    "effective_uid=$(id -u 2>/dev/null || printf 0); " + ...
    "passwd_home=''; " + ...
    "if test -n ""$effective_user"" && command -v getent " + ...
    ">/dev/null 2>&1; then passwd_home=$(getent passwd " + ...
    """$effective_user"" 2>/dev/null | awk -F: 'NR==1 {print $6}'); fi; " + ...
    "storage_path=''; " + ...
    "try_storage() { candidate=$1; test -n ""$candidate"" || " + ...
    "return 1; mkdir -p -- ""$candidate"" 2>/dev/null || return 1; " + ...
    "test -d ""$candidate"" && test -w ""$candidate"" || " + ...
    "return 1; probe_file=""$candidate/.kssolv-write-test-$$""; " + ...
    "(umask 077; : > ""$probe_file"") 2>/dev/null || return 1; " + ...
    "rm -f -- ""$probe_file""; storage_path=$candidate; return 0; }; " + ...
    "if test -n ""${SCRATCH:-}""; then try_storage " + ...
    """${SCRATCH%/}/.kssolv/remote-jobs"" || true; fi; " + ...
    "if test -z ""$storage_path"" && test -n ""$passwd_home""; " + ...
    "then try_storage ""${passwd_home%/}/.kssolv/remote-jobs"" || true; fi; " + ...
    "if test -z ""$storage_path"" && test -n ""${HOME:-}""; " + ...
    "then try_storage ""${HOME%/}/.kssolv/remote-jobs"" || true; fi; " + ...
    "if test -z ""$storage_path"" && test -n ""${TMPDIR:-}""; " + ...
    "then try_storage ""${TMPDIR%/}/kssolv-${effective_uid}/" + ...
    "remote-jobs"" || true; fi; " + ...
    "if test -z ""$storage_path""; then try_storage " + ...
    """/tmp/kssolv-${effective_uid}/remote-jobs"" || true; fi; " + ...
    "if test -z ""$storage_path""; then printf '%s\n' " + ...
    "'No writable remote job storage directory could be created for " + ...
    "the effective compute user.' >&2; exit 73; fi; " + ...
    "printf 'KSSOLV_DISCOVERY_HOST=%s\n' ""$hostname_value""; " + ...
    "printf 'KSSOLV_DISCOVERY_STORAGE=%s\n' ""$storage_path""; " + ...
    """$matlab_executable"" -batch " + shellQuote(matlabCode) + " 2>&1";
end

function probe = parseOutput(output)
root = marker(output, "ROOT");
release = marker(output, "RELEASE");
hostname = marker(output, "HOST");
storage = marker(output, "STORAGE");
workers = str2double(marker(output, "WORKERS"));
pool = str2double(marker(output, "POOL"));
if any(strlength([root, release, hostname, storage]) == 0) || ...
        any(~isfinite([workers, pool])) || workers < 1 || ...
        pool < 0 || pool > workers
    error("KSSOLV:Remote:EnvironmentProbeInvalidOutput", ...
        "Remote MATLAB discovery returned incomplete diagnostics: %s", ...
        strip(output));
end
probe = struct( ...
    "Hostname", hostname, ...
    "MatlabRelease", release, ...
    "ClusterMatlabRoot", root, ...
    "RemoteJobStorageLocation", storage, ...
    "NumWorkers", floor(workers), ...
    "PoolSize", floor(pool));
end

function value = marker(output, name)
expression = "(?m)^KSSOLV_DISCOVERY_" + name + "=([^\r\n]*)$";
match = regexp(char(output), char(expression), "tokens", "once");
if isempty(match)
    value = "";
else
    value = strip(string(match{1}));
end
end

function value = shellQuote(text)
singleQuoteEscape = "'" + """" + "'" + """" + "'";
value = "'" + replace(string(text), "'", singleQuoteEscape) + "'";
end

function value = remoteJoin(parts)
arguments (Repeating)
    parts (1, 1) string
end
value = join(strip(string([parts{:}]), "/"), "/");
if startsWith(parts{1}, "/")
    value = "/" + value;
end
end

function writePhase(path, phase)
if strlength(string(path)) == 0
    return
end
try
    writelines(string(phase), path);
catch
end
end
