classdef Prismatic
    %PRISMATIC Write STEM simulation extended-XYZ input.
    properties
        structure
        comment (1,1) string = "Generated by pymatgen"
    end
    methods
        function obj=Prismatic(structure,comment)
            obj.structure=structure;
            if nargin>=2,obj.comment=string(comment);end
        end
        function text=to_str(obj)
            lines=[obj.comment,join(string(obj.structure.lattice.lengths)," ")];
            for index=1:obj.structure.num_sites
                site=obj.structure(index);
                [species,occupancies]=site.species.items();
                thermalSigma=0;
                if isfield(site.site_properties,"thermal_sigma")
                    thermalSigma=site.site_properties.thermal_sigma;
                end
                for speciesIndex=1:numel(species)
                    coordinateText=strings(1,3);
                    for axis=1:3
                        coordinateText(axis)= ...
                            formatCoordinate(site.coords(axis));
                    end
                    lines(end+1)=string(species{speciesIndex}.Z)+" "+ ...
                        join(coordinateText," ")+" "+ ...
                        string(occupancies(speciesIndex))+" "+ ...
                        string(thermalSigma); %#ok<AGROW>
                end
            end
            lines(end+1)="-1";
            text=join(lines,newline);
        end
        function text=char(obj),text=char(obj.to_str());end
        function text=string(obj),text=obj.to_str();end
    end
end

function text=formatCoordinate(value)
text=string(sprintf("%.15g",value));
if ~contains(text,[".","e","E"]),text=text+".0";end
end
