classdef EncryptedStore
    %ENCRYPTEDSTORE 持久化经过加密的 KSSOLV 敏感配置。
    %
    % 每个用户首次保存密钥时生成独立的 RSA-3072 密钥对。每次写入使用
    % 随机 AES-256-GCM 数据密钥加密 API Key，再用 RSA-OAEP 包裹数据
    % 密钥。私钥和密文仅写入当前用户的 MATLAB 配置目录。
    %
    % 该方案用于避免 API Key 以明文形式保存在磁盘上。

    % 开发者：杨柳
    % 版权 2026 合肥瀚海量子科技有限公司

    properties (Constant, Access = private)
        FormatVersion = 1
        KeyPairFileName = 'keypair.json'
        OpenAIAPIKeyFileName = 'openai-api-key.json'
        RSAKeySize = 3072
        GCMNonceSize = 12
        AssociatedData = 'KSSOLV_OPENAI_API_KEY_V1'
    end

    methods (Static)
        function value = readOpenAIAPIKey()
            %READOPENAIAPIKEY 读取并解密已保存的 OpenAI API Key。
            value = "";
            encryptedFile = kssolv.settings.EncryptedStore.secretFile();
            if ~isfile(encryptedFile)
                return
            end

            try
                payload = kssolv.settings.EncryptedStore.readJSON( ...
                    encryptedFile);
                kssolv.settings.EncryptedStore.validateSecretPayload(payload);
                privateKey = ...
                    kssolv.settings.EncryptedStore.loadPrivateKey();
                aesKeyBytes = kssolv.settings.EncryptedStore.unwrapKey( ...
                    privateKey, ...
                    kssolv.settings.EncryptedStore.fromBase64( ...
                    payload.WrappedKey));
                plainBytes = kssolv.settings.EncryptedStore.decryptValue( ...
                    aesKeyBytes, ...
                    kssolv.settings.EncryptedStore.fromBase64(payload.Nonce), ...
                    kssolv.settings.EncryptedStore.fromBase64( ...
                    payload.Ciphertext));
                value = string(native2unicode(plainBytes(:).', 'UTF-8'));
            catch
                % 损坏或不可读的持久化数据按“未保存密钥”处理，允许用户
                % 在设置对话框中输入新密钥并覆盖。
                value = "";
            end
        end

        function writeOpenAIAPIKey(value)
            %WRITEOPENAIAPIKEY 加密并持久化 OpenAI API Key。
            value = string(value);
            if ~isscalar(value)
                error('KSSOLV:Settings:InvalidAPIKey', ...
                    'The API key must be a scalar string.');
            end
            if strlength(value) == 0
                kssolv.settings.EncryptedStore.removeOpenAIAPIKey();
                return
            end

            [~, publicKey] = ...
                kssolv.settings.EncryptedStore.loadOrCreateKeyPair();
            [aesKeyBytes, nonce, ciphertext] = ...
                kssolv.settings.EncryptedStore.encryptValue(value);
            wrappedKey = kssolv.settings.EncryptedStore.wrapKey( ...
                publicKey, aesKeyBytes);
            payload = struct( ...
                'Version', kssolv.settings.EncryptedStore.FormatVersion, ...
                'Algorithm', 'RSA-3072-OAEP-SHA256+AES-256-GCM', ...
                'WrappedKey', ...
                kssolv.settings.EncryptedStore.toBase64(wrappedKey), ...
                'Nonce', kssolv.settings.EncryptedStore.toBase64(nonce), ...
                'Ciphertext', ...
                kssolv.settings.EncryptedStore.toBase64(ciphertext));
            kssolv.settings.EncryptedStore.writeJSONAtomically( ...
                kssolv.settings.EncryptedStore.secretFile(), payload);
        end

        function removeOpenAIAPIKey()
            %REMOVEOPENAIAPIKEY 删除持久化的 API Key 密文。
            encryptedFile = kssolv.settings.EncryptedStore.secretFile();
            if isfile(encryptedFile)
                delete(encryptedFile);
            end
        end
    end

    methods (Static, Access = private)
        function folder = storageFolder()
            userFolders = split(string(userpath), pathsep);
            userFolders = strip(userFolders);
            userFolders(strlength(userFolders) == 0) = [];
            if isempty(userFolders)
                error('KSSOLV:Settings:UserPathUnavailable', ...
                    'MATLAB userpath is not configured.');
            end
            folder = fullfile(char(userFolders(1)), ...
                'KSSOLV_Toolbox', 'credentials');
            if ~isfolder(folder)
                [created, detail] = mkdir(folder);
                if ~created
                    error('KSSOLV:Settings:CredentialDirectoryCreateFailed', ...
                        'Unable to create the credential directory: %s', ...
                        detail);
                end
            end
            kssolv.settings.EncryptedStore.restrictPermissions( ...
                folder, 'rwx------');
        end

        function path = keyPairFile()
            path = fullfile( ...
                kssolv.settings.EncryptedStore.storageFolder(), ...
                kssolv.settings.EncryptedStore.KeyPairFileName);
        end

        function path = secretFile()
            path = fullfile( ...
                kssolv.settings.EncryptedStore.storageFolder(), ...
                kssolv.settings.EncryptedStore.OpenAIAPIKeyFileName);
        end

        function [privateKey, publicKey] = loadOrCreateKeyPair()
            try
                [privateKey, publicKey] = ...
                    kssolv.settings.EncryptedStore.loadKeyPair();
                return
            catch
                % 缺失或损坏的密钥对将在下一次保存时重新生成。
            end

            generator = javaMethod( ...
                'getInstance', 'java.security.KeyPairGenerator', 'RSA');
            generator.initialize( ...
                kssolv.settings.EncryptedStore.RSAKeySize);
            pair = generator.generateKeyPair();
            privateKey = pair.getPrivate();
            publicKey = pair.getPublic();
            payload = struct( ...
                'Version', kssolv.settings.EncryptedStore.FormatVersion, ...
                'Algorithm', 'RSA-3072', ...
                'PrivateKey', kssolv.settings.EncryptedStore.toBase64( ...
                kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                privateKey.getEncoded())), ...
                'PublicKey', kssolv.settings.EncryptedStore.toBase64( ...
                kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                publicKey.getEncoded())));
            kssolv.settings.EncryptedStore.writeJSONAtomically( ...
                kssolv.settings.EncryptedStore.keyPairFile(), payload);
        end

        function [privateKey, publicKey] = loadKeyPair()
            payload = kssolv.settings.EncryptedStore.readJSON( ...
                kssolv.settings.EncryptedStore.keyPairFile());
            requiredFields = {'Version', 'PrivateKey', 'PublicKey'};
            if ~isstruct(payload) || ~isscalar(payload) || ...
                    ~all(isfield(payload, requiredFields)) || ...
                    payload.Version ~= ...
                    kssolv.settings.EncryptedStore.FormatVersion
                error('KSSOLV:Settings:InvalidCredentialKeyPair', ...
                    'The stored credential key pair is invalid.');
            end

            factory = javaMethod( ...
                'getInstance', 'java.security.KeyFactory', 'RSA');
            privateSpec = javaObject( ...
                'java.security.spec.PKCS8EncodedKeySpec', ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                kssolv.settings.EncryptedStore.fromBase64( ...
                payload.PrivateKey)));
            publicSpec = javaObject( ...
                'java.security.spec.X509EncodedKeySpec', ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                kssolv.settings.EncryptedStore.fromBase64( ...
                payload.PublicKey)));
            privateKey = factory.generatePrivate(privateSpec);
            publicKey = factory.generatePublic(publicSpec);
        end

        function privateKey = loadPrivateKey()
            [privateKey, ~] = ...
                kssolv.settings.EncryptedStore.loadKeyPair();
        end

        function [aesKeyBytes, nonce, ciphertext] = encryptValue(value)
            keyGenerator = javaMethod( ...
                'getInstance', 'javax.crypto.KeyGenerator', 'AES');
            keyGenerator.init(256);
            aesKey = keyGenerator.generateKey();
            aesKeyBytes = ...
                kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                aesKey.getEncoded());

            random = javaObject('java.security.SecureRandom');
            nonce = kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                random.generateSeed( ...
                kssolv.settings.EncryptedStore.GCMNonceSize));
            cipher = javaMethod( ...
                'getInstance', 'javax.crypto.Cipher', 'AES/GCM/NoPadding');
            parameters = javaObject( ...
                'javax.crypto.spec.GCMParameterSpec', 128, ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes(nonce));
            cipher.init( ...
                kssolv.settings.EncryptedStore.cipherMode('ENCRYPT_MODE'), ...
                aesKey, parameters);
            cipher.updateAAD( ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                unicode2native( ...
                kssolv.settings.EncryptedStore.AssociatedData, 'UTF-8')));
            plainBytes = unicode2native(char(value), 'UTF-8');
            ciphertext = ...
                kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                cipher.doFinal( ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                plainBytes)));
        end

        function plainBytes = decryptValue(aesKeyBytes, nonce, ciphertext)
            aesKey = javaObject( ...
                'javax.crypto.spec.SecretKeySpec', ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes(aesKeyBytes), ...
                'AES');
            cipher = javaMethod( ...
                'getInstance', 'javax.crypto.Cipher', 'AES/GCM/NoPadding');
            parameters = javaObject( ...
                'javax.crypto.spec.GCMParameterSpec', 128, ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes(nonce));
            cipher.init( ...
                kssolv.settings.EncryptedStore.cipherMode('DECRYPT_MODE'), ...
                aesKey, parameters);
            cipher.updateAAD( ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                unicode2native( ...
                kssolv.settings.EncryptedStore.AssociatedData, 'UTF-8')));
            plainBytes = ...
                kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                cipher.doFinal( ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                ciphertext)));
        end

        function wrappedKey = wrapKey(publicKey, aesKeyBytes)
            cipher = kssolv.settings.EncryptedStore.rsaCipher();
            cipher.init( ...
                kssolv.settings.EncryptedStore.cipherMode('ENCRYPT_MODE'), ...
                publicKey);
            wrappedKey = ...
                kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                cipher.doFinal( ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                aesKeyBytes)));
        end

        function aesKeyBytes = unwrapKey(privateKey, wrappedKey)
            cipher = kssolv.settings.EncryptedStore.rsaCipher();
            cipher.init( ...
                kssolv.settings.EncryptedStore.cipherMode('DECRYPT_MODE'), ...
                privateKey);
            aesKeyBytes = ...
                kssolv.settings.EncryptedStore.javaBytesToBytes( ...
                cipher.doFinal( ...
                kssolv.settings.EncryptedStore.bytesToJavaBytes( ...
                wrappedKey)));
        end

        function cipher = rsaCipher()
            cipher = javaMethod('getInstance', 'javax.crypto.Cipher', ...
                'RSA/ECB/OAEPWithSHA-256AndMGF1Padding');
        end

        function mode = cipherMode(name)
            cipherClass = java.lang.Class.forName('javax.crypto.Cipher');
            mode = cipherClass.getField(name).get([]);
        end

        function validateSecretPayload(payload)
            requiredFields = { ...
                'Version', 'WrappedKey', 'Nonce', 'Ciphertext'};
            if ~isstruct(payload) || ~isscalar(payload) || ...
                    ~all(isfield(payload, requiredFields)) || ...
                    payload.Version ~= ...
                    kssolv.settings.EncryptedStore.FormatVersion
                error('KSSOLV:Settings:InvalidEncryptedCredential', ...
                    'The encrypted credential is invalid.');
            end
        end

        function payload = readJSON(path)
            text = fileread(path);
            payload = jsondecode(text);
        end

        function writeJSONAtomically(path, payload)
            folder = fileparts(path);
            temporaryFile = [tempname(folder) '.tmp'];
            cleanup = onCleanup(@() ...
                kssolv.settings.EncryptedStore.deleteIfExists(temporaryFile));
            data = unicode2native(jsonencode(payload), 'UTF-8');
            fileID = fopen(temporaryFile, 'wb');
            if fileID < 0
                error('KSSOLV:Settings:CredentialFileOpenFailed', ...
                    'Unable to open the credential file for writing.');
            end
            fileCleanup = onCleanup(@() fclose(fileID));
            written = fwrite(fileID, data, 'uint8');
            if written ~= numel(data)
                error('KSSOLV:Settings:CredentialFileWriteFailed', ...
                    'Unable to write the complete credential file.');
            end
            clear fileCleanup

            kssolv.settings.EncryptedStore.restrictPermissions( ...
                temporaryFile, 'rw-------');
            [moved, detail] = movefile(temporaryFile, path, 'f');
            if ~moved
                error('KSSOLV:Settings:CredentialFileMoveFailed', ...
                    'Unable to replace the credential file: %s', detail);
            end
            kssolv.settings.EncryptedStore.restrictPermissions( ...
                path, 'rw-------');
            clear cleanup
        end

        function restrictPermissions(path, permissions)
            if ~isunix
                % Windows 的用户配置目录继承当前账户的 ACL。
                return
            end
            permissionSet = javaMethod( ...
                'fromString', ...
                'java.nio.file.attribute.PosixFilePermissions', permissions);
            javaPath = javaObject('java.io.File', path).toPath();
            javaMethod('setPosixFilePermissions', ...
                'java.nio.file.Files', javaPath, permissionSet);
        end

        function encoded = toBase64(bytes)
            encoded = char(matlab.net.base64encode(uint8(bytes(:).')));
        end

        function bytes = fromBase64(encoded)
            bytes = uint8(matlab.net.base64decode(char(string(encoded))));
        end

        function bytes = javaBytesToBytes(javaBytes)
            bytes = typecast(int8(javaBytes), 'uint8');
        end

        function javaBytes = bytesToJavaBytes(bytes)
            javaBytes = typecast(uint8(bytes(:).'), 'int8');
        end

        function deleteIfExists(path)
            if isfile(path)
                delete(path);
            end
        end
    end
end
