classdef RemoteCommandExecutorTest < matlab.unittest.TestCase
    methods (Test)
        function persistentSessionRetainsWorkspaceAndProcess(testCase)
            testCase.assumeTrue(isunix);
            root = temporaryRoot(testCase);
            configuration = sshMatlabConfiguration(root);
            access = kssolv.services.remote.test.LocalRemoteAccess();
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access);
            executor = kssolv.services.remote.execution. ...
                RemoteCommandExecutor(factory);
            testCase.addTeardown(@()delete(executor));
            recorder = kssolv.services.remote.test. ...
                RemoteCommandPhaseRecorder();

            executor.execute( ...
                "remoteValue = 40; remotePid = feature('getpid');", ...
                configuration, StatusReporter= ...
                @(phase, detail)recorder.report(phase, detail));
            valueOutput = executor.execute( ...
                "fprintf('VALUE=%d\n', remoteValue + 2);", ...
                configuration, StatusReporter= ...
                @(phase, detail)recorder.report(phase, detail));
            processOutput = executor.execute( ...
                "fprintf('SAME_PID=%d\n', " + ...
                "feature('getpid') == remotePid);", configuration);

            testCase.verifyTrue(contains(valueOutput, "VALUE=42"));
            testCase.verifyTrue(contains(processOutput, "SAME_PID=1"));
            testCase.verifyEqual(executor.Session.Sequence, 3);
            testCase.verifyNumElements(factory.Configurations, 1);
            testCase.verifyEqual(recorder.Phases, [ ...
                "Connecting"; "Starting"; "Sending"; "Waiting"; ...
                "Finished"; "Sending"; "Waiting"; "Finished"]);
            testCase.verifyEqual(recorder.Details(1:2), ...
                repmat(configuration.DisplayName, 2, 1));
        end

        function closeSessionStopsProcessAndRemovesWorkspace(testCase)
            testCase.assumeTrue(isunix);
            root = temporaryRoot(testCase);
            configuration = sshMatlabConfiguration(root);
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory( ...
                kssolv.services.remote.test.LocalRemoteAccess());
            executor = kssolv.services.remote.execution. ...
                RemoteCommandExecutor(factory);
            testCase.addTeardown(@()delete(executor));
            executor.execute("sessionValue = 1;", configuration);
            workspace = executor.Session.RemoteWorkspace;
            ready = jsondecode(fileread(fullfile(workspace, "ready.json")));
            testCase.verifyTrue(isfolder(workspace));

            executor.closeSession();

            testCase.verifyFalse(isfolder(workspace));
            testCase.verifyEmpty(executor.Session);
            [aliveStatus, ~] = system(sprintf( ...
                "kill -0 %d 2>/dev/null", ready.ProcessId));
            testCase.verifyNotEqual(aliveStatus, 0);
        end

        function rejectsTargetWithoutDirectSshMatlabFields(testCase)
            configuration = kssolv.services.remote.config. ...
                RemoteConfiguration.create(struct( ...
                "DisplayName", "Profile only", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "Processes"));
            executor = kssolv.services.remote.execution. ...
                RemoteCommandExecutor(struct(), ...
                SessionFactory=@(~, ~)[]);

            testCase.verifyError(@()executor.execute( ...
                "disp(42)", configuration), ...
                "KSSOLV:Remote:MatlabSessionConfigurationIncomplete");
        end
    end
end

function root = temporaryRoot(testCase)
root = string(tempname);
mkdir(root);
testCase.addTeardown(@()removeFolder(root));
end

function removeFolder(path)
if isfolder(path)
    rmdir(path, "s");
end
end

function value = sshMatlabConfiguration(root)
value = kssolv.services.remote.config.RemoteConfiguration.create(struct( ...
    "DisplayName", "Persistent Command Window", ...
    "ExecutionMode", "Standard", ...
    "ProfileSource", "ExistingMatlabProfile", ...
    "ExistingProfileName", "Processes", ...
    "ConnectionMode", "SSH", ...
    "Host", "localhost", ...
    "Username", join(["test", "user"], "-"), ...
    "ClusterMatlabRoot", string(matlabroot), ...
    "RemoteJobStorageLocation", root));
end
