classdef RemoteConfigurationTest < matlab.unittest.TestCase
    properties
        StorageRoot string
        ConfigurationStore
        SelectionStore
    end

    methods (TestMethodSetup)
        function createStores(testCase)
            testCase.StorageRoot = string(tempname);
            mkdir(testCase.StorageRoot);
            testCase.addTeardown(@()removeFolder(testCase.StorageRoot));
            testCase.ConfigurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore( ...
                testCase.StorageRoot);
            testCase.SelectionStore = ...
                kssolv.services.remote.config.RemoteSelectionStore( ...
                testCase.StorageRoot);
        end
    end

    methods (Test)
        function defaultsPostLoginScriptToEmpty(testCase)
            configuration = kssolv.services.remote.config. ...
                RemoteConfiguration.defaults();

            testCase.verifyEqual(configuration.PostLoginScript, "");
        end

        function createAndRoundTripMultipleConfigurations(testCase)
            first = managedConfiguration("First");
            second = managedConfiguration("First");
            second.AuthenticationMode = "Multifactor";
            second.RememberTotpSecret = true;
            testCase.ConfigurationStore.save([first; second]);

            actual = testCase.ConfigurationStore.list();
            testCase.verifyNumElements(actual, 2);
            testCase.verifyEqual(string({actual.DisplayName}), ...
                ["First", "First"]);
            testCase.verifyNotEqual(actual(1).Id, actual(2).Id);
            testCase.verifyEqual(actual(2).AuthenticationMode, ...
                "Multifactor");
            testCase.verifyTrue(actual(2).RememberTotpSecret);
        end

        function currentSelectionPersistsAndFallsBack(testCase)
            configuration = managedConfiguration("Selected");
            testCase.ConfigurationStore.upsert(configuration);
            testCase.SelectionStore.set(configuration.Id);
            testCase.verifyEqual(testCase.SelectionStore.get( ...
                testCase.ConfigurationStore), configuration.Id);

            configuration.Enabled = false;
            testCase.ConfigurationStore.upsert(configuration);
            testCase.verifyEqual(testCase.SelectionStore.get( ...
                testCase.ConfigurationStore), "");
            testCase.verifyEqual(testCase.SelectionStore.get(), "");
        end

        function deletingSelectedConfigurationFallsBack(testCase)
            configuration = managedConfiguration("Deleted");
            testCase.ConfigurationStore.upsert(configuration);
            testCase.SelectionStore.set(configuration.Id);
            testCase.verifyTrue(testCase.ConfigurationStore.remove( ...
                configuration.Id));
            testCase.verifyEqual(testCase.SelectionStore.get( ...
                testCase.ConfigurationStore), "");
        end

        function duplicateGetsIndependentIdAndProfile(testCase)
            configuration = managedConfiguration("Source");
            testCase.ConfigurationStore.upsert(configuration);
            copy = testCase.ConfigurationStore.duplicate(configuration.Id);
            testCase.verifyNotEqual(copy.Id, configuration.Id);
            testCase.verifyNotEqual(copy.ManagedProfileName, ...
                configuration.ManagedProfileName);
            testCase.verifyEqual(copy.DisplayName, "Source Copy");
        end

        function rejectsSecretFields(testCase)
            configuration = managedConfiguration("Unsafe");
            configuration.Password = "not-a-real-password";
            testCase.verifyError(@() ...
                kssolv.services.remote.config.RemoteConfiguration.validate( ...
                configuration), "KSSOLV:Remote:SecretInConfiguration");
        end

        function persistedJsonContainsNoSecretFields(testCase)
            configuration = managedConfiguration("Safe");
            configuration.AuthenticationMode = "Multifactor";
            testCase.ConfigurationStore.upsert(configuration);
            text = string(fileread(testCase.ConfigurationStore.path()));
            testCase.verifyFalse(contains(lower(text), '"password"'));
            testCase.verifyFalse(contains(lower(text), '"otp"'));
            testCase.verifyFalse(contains(lower(text), 'totpseed'));
            testCase.verifyFalse(contains(lower(text), 'privatekey'));
        end

        function corruptedStoreFallsBackToEmpty(testCase)
            path = testCase.ConfigurationStore.path();
            fileId = fopen(path, "w");
            cleanup = onCleanup(@()fclose(fileId));
            fwrite(fileId, "{invalid", "char");
            clear cleanup
            testCase.verifyWarning(@()testCase.ConfigurationStore.list(), ...
                "KSSOLV:Remote:InvalidJsonFile");
            testCase.verifyEmpty(testCase.ConfigurationStore.list());
        end

        function rejectsInvalidPoolSize(testCase)
            configuration = managedConfiguration("Workers");
            configuration.NumWorkers = 2;
            configuration.PoolSize = 3;
            testCase.verifyError(@() ...
                kssolv.services.remote.config.RemoteConfiguration.validate( ...
                configuration), "KSSOLV:Remote:InvalidConfiguration");
        end

        function bridgeAllowsDifferentRemoteRelease(testCase)
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                create(struct( ...
                "DisplayName", "Older remote MATLAB", ...
                "SubmissionMode", "RemoteMatlabBridge", ...
                "Host", "cluster.example.test", ...
                "Username", join(["test", "user"], "-"), ...
                "AuthenticationMode", "Multifactor", ...
                "ClusterMatlabRoot", "/opt/MATLAB/R2024a", ...
                "RemoteJobStorageLocation", "/scratch/test", ...
                "RemoteBridgeProfileName", "r2024a-slurm"));
            testCase.verifyEqual(configuration.ExecutionMode, "Bridge");
            testCase.verifyEqual(configuration.ClusterMatlabRoot, ...
                "/opt/MATLAB/R2024a");
        end

        function bridgeRequiresSshAndRemoteProfile(testCase)
            value = kssolv.services.remote.config.RemoteConfiguration.defaults();
            value.DisplayName = "Invalid bridge";
            value.SubmissionMode = "RemoteMatlabBridge";
            value.ConnectionMode = "Direct";
            testCase.verifyError(@() ...
                kssolv.services.remote.config.RemoteConfiguration.validate(value), ...
                "KSSOLV:Remote:InvalidConfiguration");
        end

        function bridgeAcceptsTargetCommandAndPromptMetadata(testCase)
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                create(struct( ...
                "DisplayName", "Interactive bridge", ...
                "SubmissionMode", "RemoteMatlabBridge", ...
                "Host", "cluster.example.test", ...
                "Username", join(["test", "user"], "-"), ...
                "AuthenticationMode", "Multifactor", ...
                "ClusterMatlabRoot", "/opt/MATLAB/R2024a", ...
                "RemoteJobStorageLocation", "/scratch/test", ...
                "RemoteBridgeProfileName", "r2024a-slurm", ...
                "RemoteCommandTemplate", ...
                "sudo su -c ""ssh node7 -- {command}""", ...
                "RemotePromptPattern", "(?i)password:", ...
                "RemoteCredentialLabel", "Root credential"));
            testCase.verifyEqual(configuration.PostLoginCommandTemplate, ...
                "sudo su -c ""ssh node7 -- {command}""");
        end

        function targetCommandRequiresExactlyOnePlaceholder(testCase)
            value = kssolv.services.remote.config.RemoteConfiguration.defaults();
            value.DisplayName = "Invalid template";
            value.SubmissionMode = "RemoteMatlabBridge";
            value.Host = "cluster.example.test";
            value.Username = join(["test", "user"], "-");
            value.ClusterMatlabRoot = "/opt/MATLAB/R2024a";
            value.RemoteJobStorageLocation = "/scratch/test";
            value.RemoteBridgeProfileName = "r2024a-slurm";
            value.RemoteCommandTemplate = "ssh node7";
            testCase.verifyError(@() ...
                kssolv.services.remote.config.RemoteConfiguration.validate(value), ...
                "KSSOLV:Remote:InvalidConfiguration");
        end

        function standaloneBridgeDoesNotRequireClusterProfile(testCase)
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                create(struct( ...
                "DisplayName", "Standalone MATLAB", ...
                "SubmissionMode", "RemoteMatlabBridge", ...
                "RemoteBridgeExecutionMode", "StandaloneMatlab", ...
                "Host", "cluster.example.test", ...
                "Username", join(["test", "user"], "-"), ...
                "ClusterMatlabRoot", "/opt/MATLAB/R2024a", ...
                "RemoteJobStorageLocation", "/scratch/test", ...
                "RemoteBridgeProfileName", "", ...
                "RemoteCommandTemplate", "ssh node7 -- {command}"));
            testCase.verifyEqual(configuration.ExecutionMode, "Mirror");
            testCase.verifyEqual(configuration.RemoteBridgeProfileName, "");
        end

        function createsFourTopLevelExecutionModes(testCase)
            standard = managedConfiguration("Standard");
            bridge = routedConfiguration("Bridge");
            bridge.RemoteBridgeProfileName = "remote-slurm";
            bridge = kssolv.services.remote.config.RemoteConfiguration. ...
                create(bridge);
            mirror = kssolv.services.remote.config.RemoteConfiguration.create( ...
                routedConfiguration("Mirror"));
            cloud = kssolv.services.remote.config.RemoteConfiguration.create( ...
                struct("DisplayName", "Cloud", ...
                "ExecutionMode", "Cloud", ...
                "CloudProvider", "AWS", ...
                "ProfileSource", "ExistingMatlabProfile", ...
                "ExistingProfileName", "aws-profile"));

            testCase.verifyEqual([standard.ExecutionMode, ...
                bridge.ExecutionMode, mirror.ExecutionMode, ...
                cloud.ExecutionMode], ...
                ["Standard", "Bridge", "Mirror", "Cloud"]);
            testCase.verifyEqual(cloud.CloudProvider, "AWS");
        end

        function supportsOrderedPostLoginPromptRules(testCase)
            value = routedConfiguration("Mirror");
            value.PostLoginCommandTemplate = ...
                "sudo -S ssh node7 -- {command}";
            value.PostLoginPromptRules = [ ...
                struct("Pattern", "(?i)sudo password:", ...
                    "CredentialLabel", "Sudo credential")
                struct("Pattern", "(?i)node password:", ...
                    "CredentialLabel", "Node credential")];
            configuration = ...
                kssolv.services.remote.config.RemoteConfiguration.create(value);

            testCase.verifyNumElements( ...
                configuration.PostLoginPromptRules, 2);
            testCase.verifyEqual( ...
                configuration.PostLoginPromptRules(2).CredentialLabel, ...
                "Node credential");
        end

        function migratesLegacyConfigurationWithoutDeletingSource(testCase)
            legacy = routedConfiguration("Mirror");
            legacy = kssolv.services.remote.config.RemoteConfiguration.create(legacy);
            legacy.Version = 1;
            legacy.SubmissionMode = "RemoteMatlabBridge";
            legacy.RemoteBridgeExecutionMode = "StandaloneMatlab";
            legacy.RemoteCommandTemplate = "ssh node7 -- {command}";
            legacy = rmfield(legacy, {'ExecutionMode', 'CloudProvider', ...
                'CloudResourceName', 'CloudRegion', ...
                'PostLoginScript', 'PostLoginCommandTemplate', ...
                'PostLoginPromptRules'});
            legacyPath = fullfile(testCase.StorageRoot, ...
                "configurations-v1.json");
            kssolv.services.remote.internal.AtomicJsonFile.write( ...
                legacyPath, struct("Version", 1, ...
                "Configurations", legacy));

            migrated = testCase.ConfigurationStore.list();

            testCase.verifyEqual(migrated.ExecutionMode, "Mirror");
            testCase.verifyTrue(isfile(legacyPath));
            testCase.verifyTrue(isfile(testCase.ConfigurationStore.path()));
            persisted = string(fileread( ...
                testCase.ConfigurationStore.path()));
            testCase.verifyFalse(contains(persisted, '"SubmissionMode"'));
            testCase.verifyFalse(contains(persisted, ...
                '"RemoteBridgeExecutionMode"'));
        end
    end
end

function value = managedConfiguration(name)
placeholderUsername = join(["remote", "user"], "-");
value = kssolv.services.remote.config.RemoteConfiguration.create(struct( ...
    "DisplayName", name, ...
    "Host", "cluster.example.test", ...
    "Username", placeholderUsername, ...
    "ClusterMatlabRoot", "/opt/MATLAB/R2026b", ...
    "RemoteJobStorageLocation", "/scratch/tester/kssolv"));
end

function value = routedConfiguration(mode)
value = struct( ...
    "DisplayName", mode + " target", ...
    "ExecutionMode", mode, ...
    "ConnectionMode", "SSH", ...
    "Host", "cluster.example.test", ...
    "Username", join(["remote", "user"], "-"), ...
    "ClusterMatlabRoot", "/opt/MATLAB/R2024a", ...
    "RemoteJobStorageLocation", "/scratch/tester/kssolv", ...
    "RemoteBridgeProfileName", "", ...
    "PostLoginCommandTemplate", "ssh node7 -- {command}");
end

function removeFolder(path)
if isfolder(path)
    rmdir(path, "s");
end
end
