classdef RemoteEnvironmentProbeTest < matlab.unittest.TestCase
    methods (Test)
        function incompleteBridgeConfigurationCanBeProbed(testCase)
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                defaults();
            configuration.ExecutionMode = "Bridge";
            configuration.Host = "cluster.example.test";
            configuration.Username = "user";
            configuration.ClusterMatlabRoot = "";
            configuration.RemoteJobStorageLocation = "";
            configuration.RemoteBridgeProfileName = "";

            prepared = kssolv.services.remote.diagnostics.RemoteEnvironmentProbe. ...
                prepareConfiguration(configuration);

            testCase.verifyEqual(prepared.ClusterMatlabRoot, "/");
            testCase.verifyEqual(prepared.RemoteJobStorageLocation, "/tmp");
            testCase.verifyEqual(prepared.RemoteBridgeProfileName, "local");
        end

        function incompleteManagedStandardSshCanBeProbed(testCase)
            configuration = kssolv.services.remote.config.RemoteConfiguration. ...
                defaults();
            configuration.ExecutionMode = "Standard";
            configuration.ProfileSource = "ManagedSlurm";
            configuration.ConnectionMode = "SSH";
            configuration.Host = "cluster.example.test";
            configuration.Username = "user";
            configuration.ClusterMatlabRoot = "";
            configuration.RemoteJobStorageLocation = "";

            prepared = kssolv.services.remote.diagnostics.RemoteEnvironmentProbe. ...
                prepareConfiguration(configuration);

            testCase.verifyEqual(prepared.ClusterMatlabRoot, "/");
            testCase.verifyEqual(prepared.RemoteJobStorageLocation, "/tmp");
        end

        function parsesAndReturnsDiscoveredResources(testCase)
            output = join([ ...
                "login banner", ...
                "KSSOLV_DISCOVERY_HOST=node7", ...
                "KSSOLV_DISCOVERY_STORAGE=/scratch/user/.kssolv/remote-jobs", ...
                "KSSOLV_DISCOVERY_ROOT=/opt/MATLAB/R2024a", ...
                "KSSOLV_DISCOVERY_RELEASE=2024a", ...
                "KSSOLV_DISCOVERY_WORKERS=64", ...
                "KSSOLV_DISCOVERY_POOL=60"], newline);
            access = kssolv.services.remote.test. ...
                FakeEnvironmentProbeAccess(output);
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access);
            configuration = mirrorConfiguration();

            probe = kssolv.services.remote.diagnostics.RemoteEnvironmentProbe. ...
                runWithFactory(configuration, factory);

            testCase.verifyEqual(probe.Hostname, "node7");
            testCase.verifyEqual(probe.MatlabRelease, "2024a");
            testCase.verifyEqual(probe.ClusterMatlabRoot, ...
                "/opt/MATLAB/R2024a");
            testCase.verifyEqual(probe.RemoteJobStorageLocation, ...
                "/scratch/user/.kssolv/remote-jobs");
            testCase.verifyEqual(probe.NumWorkers, 64);
            testCase.verifyEqual(probe.PoolSize, 60);
            testCase.verifyTrue(contains(access.Command, ...
                "command -v matlab"));
            testCase.verifyTrue(contains(access.Command, "-batch"));
            testCase.verifyTrue(contains(access.Command, "id -un"));
            testCase.verifyTrue(contains(access.Command, "getent passwd"));
            testCase.verifyTrue(contains(access.Command, "mkdir -p"));
            testCase.verifyTrue(contains(access.Command, "test -w"));
            testCase.verifyTrue(contains(access.Command, ...
                ".kssolv-write-test-$$"));
            testCase.verifyTrue(contains(access.Command, ...
                "/tmp/kssolv-${effective_uid}/remote-jobs"));
            testCase.verifyTrue(contains(access.LoginCommand, ...
                "KSSOLV_CONNECTION_OK"));
        end

        function routesDiscoveryThroughFinalLoginTarget(testCase)
            output = join([ ...
                "KSSOLV_DISCOVERY_HOST=gpu6", ...
                "KSSOLV_DISCOVERY_STORAGE=/home/yliu7949/.kssolv/remote-jobs", ...
                "KSSOLV_DISCOVERY_ROOT=/opt/MATLAB/R2024a", ...
                "KSSOLV_DISCOVERY_RELEASE=2024a", ...
                "KSSOLV_DISCOVERY_WORKERS=32", ...
                "KSSOLV_DISCOVERY_POOL=24"], newline);
            delegate = kssolv.services.remote.test. ...
                FakeEnvironmentProbeAccess(output);
            configuration = mirrorConfiguration();
            configuration.PostLoginCommandTemplate = ...
                "sudo -n -- ssh -o BatchMode=yes gpu6 -- " + ...
                "su - yliu7949 -c {command}";
            access = kssolv.services.remote.transport.RemoteCommandAccess( ...
                delegate, configuration);
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access);

            probe = kssolv.services.remote.diagnostics.RemoteEnvironmentProbe. ...
                runWithFactory(configuration, factory);

            testCase.verifyEqual(probe.Hostname, "gpu6");
            testCase.verifyEqual(probe.ClusterMatlabRoot, ...
                "/opt/MATLAB/R2024a");
            testCase.verifyTrue(startsWith(delegate.Command, ...
                "sudo -n -- ssh -o BatchMode=yes gpu6 -- " + ...
                "su - yliu7949 -c "));
            testCase.verifyTrue(contains(delegate.Command, ...
                "command -v matlab"));
            testCase.verifyTrue(contains(delegate.Command, "-batch"));
            testCase.verifyFalse(contains(delegate.LoginCommand, "gpu6"));
        end

        function reportsDiscoveryPhaseToTheClient(testCase)
            output = join([ ...
                "KSSOLV_DISCOVERY_HOST=node7", ...
                "KSSOLV_DISCOVERY_STORAGE=/scratch/user/jobs", ...
                "KSSOLV_DISCOVERY_ROOT=/opt/MATLAB/R2024a", ...
                "KSSOLV_DISCOVERY_RELEASE=2024a", ...
                "KSSOLV_DISCOVERY_WORKERS=8", ...
                "KSSOLV_DISCOVERY_POOL=4"], newline);
            access = kssolv.services.remote.test. ...
                FakeEnvironmentProbeAccess(output);
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access);
            progressPath = string(tempname) + ".phase";
            cleanup = onCleanup(@()deleteIfPresent(progressPath)); %#ok<NASGU>

            kssolv.services.remote.diagnostics.RemoteEnvironmentProbe. ...
                runWithFactory(mirrorConfiguration(), factory, progressPath);

            testCase.verifyEqual(strip(string( ...
                fileread(progressPath))), "Completed");
        end

        function failedConnectionDoesNotRunScriptOrDiscovery(testCase)
            access = kssolv.services.remote.test. ...
                FakeEnvironmentProbeAccess("must not be returned");
            access.ConnectionStatus = 255;
            access.ConnectionOutput = "permission denied";
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access);

            testCase.verifyError(@()kssolv.services.remote.diagnostics. ...
                RemoteEnvironmentProbe.runWithFactory( ...
                mirrorConfiguration(), factory), ...
                "KSSOLV:Remote:EnvironmentConnectionFailed");
            testCase.verifyEqual(access.Command, "");
        end

        function failedPostLoginScriptStopsResourceDiscovery(testCase)
            delegate = kssolv.services.remote.test. ...
                FakeEnvironmentProbeAccess("module command failed");
            delegate.Status = 1;
            configuration = mirrorConfiguration();
            configuration.PostLoginScript = "module load missing-matlab";
            access = kssolv.services.remote.transport.RemoteCommandAccess( ...
                delegate, configuration);
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access);

            testCase.verifyError(@()kssolv.services.remote.diagnostics. ...
                RemoteEnvironmentProbe.runWithFactory( ...
                configuration, factory), ...
                "KSSOLV:Remote:PostLoginScriptFailed");
            testCase.verifyTrue(contains(delegate.Command, ...
                "module load missing-matlab"));
            testCase.verifyTrue(contains(delegate.Command, "set -e"));
        end

        function nonzeroRemoteStatusFails(testCase)
            access = kssolv.services.remote.test. ...
                FakeEnvironmentProbeAccess("no MATLAB");
            access.Status = 127;
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access);

            testCase.verifyError(@()kssolv.services.remote.diagnostics. ...
                RemoteEnvironmentProbe.runWithFactory( ...
                mirrorConfiguration(), factory), ...
                "KSSOLV:Remote:EnvironmentProbeFailed");
        end
    end
end

function deleteIfPresent(path)
if isfile(path)
    delete(path);
end
end

function value = mirrorConfiguration()
value = kssolv.services.remote.config.RemoteConfiguration.defaults();
value.ExecutionMode = "Mirror";
value.Host = "cluster.example.test";
value.Username = "user";
value.ClusterMatlabRoot = "/opt/MATLAB/R2024a";
value.RemoteJobStorageLocation = "/scratch/user";
end
