classdef RemoteMatlabBridgeTest < matlab.unittest.TestCase
    properties
        StorageRoot string
        Access
        AccessFactory
        Bridge
        Configuration
    end

    methods (TestMethodSetup)
        function createBridge(testCase)
            testCase.StorageRoot = string(tempname);
            mkdir(testCase.StorageRoot);
            testCase.addTeardown(@()removeFolder(testCase.StorageRoot));
            testCase.Access = ...
                kssolv.services.remote.test.FakeRemoteAccess();
            factory = kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(testCase.Access);
            testCase.AccessFactory = factory;
            testCase.Bridge = ...
                kssolv.services.remote.bridge.RemoteMatlabBridge(factory);
            testCase.Configuration = bridgeConfiguration();
        end
    end

    methods (Test)
        function submitsRefreshesAndFetchesNeutralWorkflow(testCase)
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore( ...
                testCase.StorageRoot);
            jobStore = kssolv.services.remote.job.RemoteJobStore( ...
                testCase.StorageRoot);
            configurationStore.upsert(testCase.Configuration);
            manager = kssolv.services.remote.job.RemoteJobManager( ...
                configurationStore, jobStore, ...
                kssolv.services.remote.cluster.ClusterFactory( ...
                fullfile(testCase.StorageRoot, "matlab-jobs")), ...
                testCase.Bridge);
            snapshot = kssolv.services.remote.test.smallLiHSnapshot();

            record = manager.submitWorkflow( ...
                testCase.Configuration.Id, snapshot);
            testCase.verifyEqual(record.ExecutionMode, "Bridge");
            testCase.verifyEqual(record.State, "Queued");
            testCase.verifyEqual(record.MatlabJobId, 42);
            testCase.verifyEqual(record.BridgeMatlabRelease, "2024a");
            testCase.verifyEqual(record.MatlabProfileName, "remote-slurm");
            testCase.verifyTrue(endsWith(record.RemoteWorkspace, ...
                "/kssolv-bridge/" + record.LocalJobId));
            testCase.verifyEqual(sort(testCase.Access.UploadedNames), ...
                sort(["request.json"; "snapshot.mat"]));
            testCase.verifyEqual(string( ...
                testCase.Access.UploadedRequest.Operation), "Workflow");
            testCase.verifyEqual(string( ...
                testCase.Access.UploadedRequest.ExecutionMode), ...
                "ParallelServer");
            testCase.verifyFalse(any(contains(lower(string(fieldnames( ...
                testCase.Access.UploadedRequest))), ...
                ["password", "otp", "totp", "privatekey"])));

            recoveredManager = kssolv.services.remote.job.RemoteJobManager( ...
                kssolv.services.remote.config.RemoteConfigurationStore( ...
                testCase.StorageRoot), ...
                kssolv.services.remote.job.RemoteJobStore( ...
                testCase.StorageRoot), ...
                kssolv.services.remote.cluster.ClusterFactory( ...
                fullfile(testCase.StorageRoot, "matlab-jobs")), ...
                testCase.Bridge);
            [outputs, fetched] = recoveredManager.fetch(record.LocalJobId);
            testCase.verifyEqual(fetched.State, "Retrieved");
            testCase.verifyEqual(outputs{1}.Context("energy"), -1.25);
            testCase.verifyTrue(any(contains(testCase.Access.Commands, ...
                "/opt/MATLAB/R2024a/bin/matlab")));
            testCase.verifyFalse(any(contains(testCase.Access.Commands, ...
                "R2026b")));
        end

        function cancelDispatchesToRemoteBridge(testCase)
            record = kssolv.services.remote.job.RemoteJobRecord.create( ...
                testCase.Configuration.Id);
            record.ExecutionMode = "Bridge";
            record.RemoteWorkspace = "/scratch/test/kssolv-bridge/id";
            record.State = "Running";
            cancelled = testCase.Bridge.cancel( ...
                testCase.Configuration, record);
            testCase.verifyEqual(cancelled.State, "Cancelled");
            testCase.verifyTrue(any(contains(testCase.Access.Commands, ...
                "cancel")));
        end

        function probeUsesRemoteProfileAndCanBeCleaned(testCase)
            testCase.Configuration.CodeDeploymentMode = ...
                "ClusterInstalled";
            [record, bundle] = testCase.Bridge.submitProbe( ...
                testCase.Configuration, testCase.StorageRoot);
            testCase.verifyEqual(bundle, "");
            testCase.verifyEqual(string( ...
                testCase.Access.UploadedRequest.Operation), "Probe");
            testCase.Bridge.cleanupRemote(testCase.Configuration, record);
            testCase.verifyEqual(testCase.Access.DeletedPaths(end), ...
                record.RemoteWorkspace);
        end

        function bridgeConnectionSessionReturnsWorkerProbe(testCase)
            testCase.Configuration.CodeDeploymentMode = ...
                "ClusterInstalled";
            testCase.Access.Outputs = {struct( ...
                "Hostname", "compute-01", ...
                "MatlabRelease", "2024a", ...
                "SlurmJobId", "1234", ...
                "WorkerName", "worker-1", ...
                "Result", 3)};
            session = kssolv.services.remote.diagnostics. ...
                RemoteBridgeConnectionTestSession( ...
                testCase.Configuration, testCase.Bridge);
            testCase.addTeardown(@()delete(session));
            session.start();
            state = session.poll();
            testCase.verifyEqual(state, "Succeeded");
            testCase.verifyEqual(session.Report.Probe.MatlabRelease, ...
                "2024a");
            testCase.verifyEqual(session.Report.Probe.Result, 3);
        end

        function bridgeConnectionRejectsWorkerReleaseMismatch(testCase)
            testCase.Configuration.CodeDeploymentMode = ...
                "ClusterInstalled";
            testCase.Access.Outputs = {struct( ...
                "Hostname", "compute-01", ...
                "MatlabRelease", "2025a", ...
                "SlurmJobId", "1234", ...
                "WorkerName", "worker-1", ...
                "Result", 3)};
            session = kssolv.services.remote.diagnostics. ...
                RemoteBridgeConnectionTestSession( ...
                testCase.Configuration, testCase.Bridge);
            testCase.addTeardown(@()delete(session));
            session.start();
            testCase.verifyEqual(session.poll(), "Failed");
            testCase.verifyEqual(session.ErrorIdentifier, ...
                "KSSOLV:Remote:BridgeServerReleaseMismatch");
        end

        function failedProbeRemovesLocalBundle(testCase)
            testCase.Configuration.CodeDeploymentMode = ...
                "AttachCurrentToolbox";
            testCase.Configuration.RemoteKssolvRoot = "";
            testCase.Access.FailOn = "submit";
            testCase.verifyError(@()testCase.Bridge.submitProbe( ...
                testCase.Configuration, testCase.StorageRoot), ...
                "KSSOLV:Remote:BridgeCommandFailed");
            testCase.verifyEmpty(dir(fullfile( ...
                testCase.StorageRoot, "*.zip")));
            testCase.verifyNumElements(testCase.Access.DeletedPaths, 1);
            testCase.verifyTrue(endsWith( ...
                testCase.Access.DeletedPaths(1), ...
                "/kssolv-bridge/" + ...
                testCase.Access.UploadedRequest.LocalJobId));
        end

        function attachCurrentToolboxReusesRemoteContentCache(testCase)
            configuration = testCase.Configuration;
            configuration.CodeDeploymentMode = "AttachCurrentToolbox";
            configuration.RemoteKssolvRoot = "";

            [first, firstBundle] = testCase.Bridge.submitProbe( ...
                configuration, testCase.StorageRoot);
            firstZipCount = nnz(endsWith( ...
                testCase.Access.UploadedNames, ".zip"));
            [second, secondBundle] = testCase.Bridge.submitProbe( ...
                configuration, testCase.StorageRoot);

            testCase.addTeardown(@()removeFile(firstBundle));
            testCase.addTeardown(@()removeFile(secondBundle));
            testCase.verifyEqual(firstZipCount, 1);
            testCase.verifyEqual(nnz(endsWith( ...
                testCase.Access.UploadedNames, ".zip")), 1);
            testCase.verifyEqual(first.BundleContentHash, ...
                second.BundleContentHash);
            testCase.verifyEqual(first.RemoteToolboxRoot, ...
                second.RemoteToolboxRoot);
            testCase.verifyTrue(contains(first.RemoteToolboxRoot, ...
                "/.kssolv-cache/toolbox/"));
            testCase.verifyEqual(string( ...
                testCase.Access.UploadedRequest.RemoteToolboxRoot), ...
                second.RemoteToolboxRoot);
        end

        function standaloneRequestOmitsRemoteProfile(testCase)
            testCase.Configuration.ExecutionMode = "Mirror";
            testCase.Configuration.RemoteBridgeProfileName = "";
            testCase.Configuration.CodeDeploymentMode = "ClusterInstalled";

            [record, bundle] = testCase.Bridge.submitProbe( ...
                testCase.Configuration, testCase.StorageRoot);

            testCase.verifyEqual(bundle, "");
            testCase.verifyEqual(string( ...
                testCase.Access.UploadedRequest.ExecutionMode), ...
                "StandaloneMatlab");
            testCase.verifyEqual(string( ...
                testCase.Access.UploadedRequest.ProfileName), "");
            testCase.verifyEqual(record.State, "Queued");
        end

        function routedSubmissionPreflightsFinalUserWorkspace(testCase)
            configuration = testCase.Configuration;
            configuration.CodeDeploymentMode = "ClusterInstalled";
            configuration.PostLoginCommandTemplate = ...
                "ssh node7 -- {command}";
            delegate = kssolv.services.remote.test.FakeRemoteAccess();
            access = kssolv.services.remote.transport.RemoteCommandAccess( ...
                delegate, configuration);
            bridge = kssolv.services.remote.bridge.RemoteMatlabBridge( ...
                kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(access));

            record = bridge.submitProbe(configuration, ...
                testCase.StorageRoot);
            refreshed = bridge.refresh(configuration, record);
            bridge.cancel(configuration, refreshed);

            testCase.verifyFalse(any(contains( ...
                delegate.LoginCommands, "mkdir -p")));
            testCase.verifyTrue(any(contains( ...
                delegate.Commands, "test -d")));
            testCase.verifyTrue(any(contains( ...
                delegate.Commands, "ssh node7 --")));
            routedCommands = delegate.Commands(contains( ...
                delegate.Commands, "ssh node7 --"));
            testCase.verifyGreaterThanOrEqual(numel(routedCommands), 4);
            bridge.cleanupRemote(configuration, record);

            hiddenDelegate = ...
                kssolv.services.remote.test.FakeRemoteAccess();
            hiddenDelegate.FailOn = "test -d";
            hiddenAccess = kssolv.services.remote.transport.RemoteCommandAccess( ...
                hiddenDelegate, configuration);
            hiddenBridge = kssolv.services.remote.bridge.RemoteMatlabBridge( ...
                kssolv.services.remote.test. ...
                FakeRemoteAccessFactory(hiddenAccess));
            testCase.verifyError(@()hiddenBridge.submitProbe( ...
                configuration, testCase.StorageRoot), ...
                "KSSOLV:Remote:WorkspaceCreateFailed");
        end

        function refreshRehydratesSavedCredentialsWithoutChangingSnapshot( ...
                testCase)
            configuration = testCase.Configuration;
            configuration.AuthenticationMode = "Password";
            configuration.EncryptedPassword = "saved-password-ciphertext";
            configuration.EncryptedTotpSecret = "";
            configurationStore = ...
                kssolv.services.remote.config.RemoteConfigurationStore( ...
                testCase.StorageRoot);
            configurationStore.upsert(configuration);
            jobStore = kssolv.services.remote.job.RemoteJobStore( ...
                testCase.StorageRoot);
            record = kssolv.services.remote.job.RemoteJobRecord.create( ...
                configuration.Id, "Credential recovery", "");
            record.ExecutionMode = "Bridge";
            record.RemoteWorkspace = "/scratch/test/kssolv-bridge/recovery";
            record.State = "Running";
            record.ConfigurationSnapshot = ...
                kssolv.services.remote.config.RemoteConfiguration. ...
                withoutCredentials(configuration);
            jobStore.upsert(record);
            manager = kssolv.services.remote.job.RemoteJobManager( ...
                configurationStore, jobStore, ...
                kssolv.services.remote.cluster.ClusterFactory( ...
                fullfile(testCase.StorageRoot, "matlab-jobs")), ...
                testCase.Bridge);

            refreshed = manager.refresh(record.LocalJobId);

            testCase.verifyEqual(refreshed.State, "Finished");
            used = testCase.AccessFactory.Configurations{end};
            testCase.verifyEqual(used.EncryptedPassword, ...
                configuration.EncryptedPassword);
            persisted = jobStore.get(record.LocalJobId);
            testCase.verifyFalse(isfield( ...
                persisted.ConfigurationSnapshot, "EncryptedPassword"));
        end
    end
end

function value = bridgeConfiguration()
value = kssolv.services.remote.config.RemoteConfiguration.create(struct( ...
    "DisplayName", "R2024a bridge", ...
    "ExecutionMode", "Bridge", ...
    "ConnectionMode", "SSH", ...
    "Host", "bridge.example.test", ...
    "Username", join(["test", "user"], "-"), ...
    "AuthenticationMode", "Multifactor", ...
    "ClusterMatlabRoot", "/opt/MATLAB/R2024a", ...
    "RemoteJobStorageLocation", "/scratch/test", ...
    "RemoteBridgeProfileName", "remote-slurm", ...
    "CodeDeploymentMode", "ClusterInstalled", ...
    "RemoteKssolvRoot", "/shared/KSSOLV", ...
    "NumWorkers", 4, ...
    "PoolSize", 2));
end

function removeFolder(path)
if isfolder(path)
    rmdir(path, "s");
end
end

function removeFile(path)
if strlength(string(path)) > 0 && isfile(path)
    delete(path);
end
end
