function snapshot = smallLiHSnapshot()
%SMALLLIHSNAPSHOT Deterministic two-atom LiH acceptance workload.

buildOptions = struct( ...
    "type", "Crystal", ...
    "pseudopotentialPpType", "default", ...
    "funct", "PBE", ...
    "ecut", 4, ...
    "smear", "gaussian", ...
    "temperature", 0, ...
    "nspin", 1, ...
    "autokpts", [1, 1, 1, 0, 0, 0], ...
    "extranbnd", 0, ...
    "lspinorb", false, ...
    "lsda", false, ...
    "noncolin", false, ...
    "domag", false, ...
    "structures", struct( ...
        "C", 7.5 * eye(3), ...
        "atomList", {{"Li", "H"}}, ...
        "xyzList", [0, 0, 0; 3.75, 3.75, 3.75], ...
        "name", "LiH primitive"));
scfOptions = struct( ...
    "eigmethod", "davidson_qe", ...
    "maxscfiter", 30, ...
    "force", false, ...
    "exxmethod", "default");
tasks = [ ...
    struct("NodeId", "build", ...
        "ClassName", ...
            "kssolv.services.workflow.module.computation.BuildMoleculeTask", ...
        "Identifier", "BuildMoleculeTask", "Options", buildOptions)
    struct("NodeId", "scf", ...
        "ClassName", ...
            "kssolv.services.workflow.module.computation.SCFTask", ...
        "Identifier", "SCFTask", "Options", scfOptions)];
snapshot = struct( ...
    "Version", 1, ...
    "WorkflowName", "LiH headless", ...
    "ProjectIdentity", "acceptance", ...
    "ToolboxVersion", string(KSSOLV_Toolbox.Version), ...
    "MatlabRelease", string(version("-release")), ...
    "CreatedAt", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")), ...
    "RemoteTasks", tasks, ...
    "RemoteNodeIds", ["build"; "scf"], ...
    "LocalNodeIds", strings(0, 1));
kssolv.services.remote.execution.WorkflowSnapshotBuilder.validate(snapshot);
end
