classdef FileDialogRegistry
    %FILEDIALOGREGISTRY Central file-dialog filters for imported data.

    methods (Static)
        function filters = structureFilters()
            filters = { ...
                ['*.cif;*.mcif;*.vasp;*.poscar;*.contcar;*.cssr;' ...
                '*.json;*.yaml;*.yml;*.xyz;*.pdb;*.mol;*.mol2;*.sdf;' ...
                '*.cml;*.config;*.pwmat;*.xsf;*.gz'], ...
                'Atomic structures and molecules'; ...
                '*.cif;*.mcif;*.cif.gz;*.mcif.gz', ...
                'Crystallographic Information Files'; ...
                '*.vasp;*.poscar;*.contcar;POSCAR*;CONTCAR*', ...
                'VASP structures'; ...
                '*.xyz;*.pdb;*.mol;*.mol2;*.sdf;*.cml', ...
                'Molecular structures'; ...
                '*.*', 'All files'};
        end

        function filters = volumeFilters()
            import kssolv.ui.util.Localizer.message
            filters = ...
                kssolv.services.fileparser.VolumeIO.fileFilters();
            keys = [ ...
                "VolumeFilterAllSupported", ...
                "VolumeFilterVasp", ...
                "VolumeFilterCube", ...
                "VolumeFilterXSF", ...
                "VolumeFilterAllFiles"];
            if size(filters, 1) ~= numel(keys)
                error("KSSOLV:FileParser:FileDialogRegistry:Filters", ...
                    "Volume filter labels and patterns are inconsistent.");
            end
            for index = 1:numel(keys)
                filters{index, 2} = message( ...
                    "KSSOLV:dialogs:" + keys(index));
            end
        end

        function [files, folder] = chooseMany( ...
                filters, title, preferenceKey)
            arguments
                filters cell
                title {mustBeTextScalar}
                preferenceKey {mustBeTextScalar} = ...
                    "LastImportFolder"
            end
            preferenceKey = string(preferenceKey);
            initialFolder = string(getpref( ...
                "KSSOLV", preferenceKey, pwd));
            if ~isfolder(initialFolder), initialFolder = string(pwd); end
            [files, folder] = uigetfile(filters, title, ...
                initialFolder, ...
                MultiSelect = "on");
            if isequal(files, 0) || isequal(folder, 0)
                files = {};
                folder = "";
            elseif ~iscell(files)
                files = {files};
            end
            if folder ~= ""
                setpref("KSSOLV", preferenceKey, folder);
            end
        end
    end
end
