classdef KPathTest < matlab.unittest.TestCase
    methods (Test)
        function setyawanCurtaroloOfficialNaCl(testCase)
            structure=readNaCl(testCase);
            path=kssolv.analysis.matgenlab.symmetry.kpath. ...
                KPathSetyawanCurtarolo(structure);
            testCase.verifyEqual(path.name,"FCC");
            testCase.verifyEqual(path.kpath.kpoints('K'), ...
                [3/8,3/8,3/4],AbsTol=1e-15);
            [points,labels]=path.get_kpoints(5,false);
            testCase.verifySize(points,[48,3]);
            testCase.verifyEqual(points(2,:), ...
                [1/12,0,1/12],AbsTol=1e-14);
            testCase.verifyEqual(points(end,:),[.5,0,.5], ...
                AbsTol=1e-14);
            testCase.verifyEqual(labels(1),"\Gamma");
        end

        function aCenteredConventionOracles(testCase)
            import kssolv.analysis.matgenlab.core.Lattice
            import kssolv.analysis.matgenlab.core.Structure
            structure=Structure.from_spacegroup(38, ...
                Lattice.orthorhombic(2,9,1),{'K','La','Ti'}, ...
                [.345,5,.77298;.1345,5.1,.77298;.7,.8,.9]);
            sc=kssolv.analysis.matgenlab.symmetry.kpath. ...
                KPathSetyawanCurtarolo(structure);
            testCase.verifyEqual(sc.name,"ORCC");
            testCase.verifyEqual(sc.kpath.kpoints('X'), ...
                [0.253086419753086,0.253086419753086,0], ...
                AbsTol=5e-15);
            hin=kssolv.analysis.matgenlab.symmetry.kpath. ...
                KPathSeek(structure);
            expected=["B_0","B_2","DELTA_0","F_0","GAMMA", ...
                "G_0","G_2","R","R_2","S","T","T_2","Y","Z","Z_2"];
            testCase.verifyEqual(sort(string(hin.kpath.kpoints.keys)), ...
                sort(expected));
            testCase.verifyEqual(hin.kpath.kpoints('DELTA_0'), ...
                [-0.253086419753086,0.253086419753086,0], ...
                AbsTol=5e-15);
            analyzer=kssolv.analysis.matgenlab.symmetry.analyzer. ...
                SpacegroupAnalyzer(structure);
            primitive=analyzer.get_primitive_standard_structure(false);
            lm=kssolv.analysis.matgenlab.symmetry.kpath. ...
                KPathLatimerMunro(primitive);
            expected=["a","b","c","d","d_{1}","e","f","q","q_{1}","Γ"];
            testCase.verifyEqual(sort(string(lm.kpath.kpoints.keys)), ...
                sort(expected));
            testCase.verifyEqual(lm.kpath.kpoints('d'), ...
                [0.253086419753086,0.253086419753086,0], ...
                AbsTol=5e-15);
            testCase.verifyEqual(lm.kpath.kpoints('q_{1}'), ...
                [-0.253086419753086,0.746913580246914,.5], ...
                AbsTol=5e-15);
        end

        function highSymmetryFacadeAndLabels(testCase)
            structure=readNaCl(testCase);
            path=kssolv.analysis.matgenlab.symmetry.HighSymmKpath( ...
                structure,false,[],"all");
            testCase.verifyEqual(path.path_type,"all");
            testCase.verifySize(path.path_lengths,[1,3]);
            testCase.verifyNotEmpty(path.label_index);
            testCase.verifyNotEmpty(path.equiv_labels);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.symmetry.kpath. ...
                KPathLatimerMunro.label_points(6),[1,1,1]);
            testCase.verifyEqual( ...
                kssolv.analysis.matgenlab.symmetry.kpath. ...
                KPathLatimerMunro.label_symbol(26),"\Gamma");

            reciprocal=kssolv.analysis.matgenlab.core.Lattice( ...
                2*pi*eye(3));
            coordinates=[0,0,0;.25,0,0;.5,0,0; ...
                .5,0,0;.5,.25,0;.5,.5,0];
            labels=struct("G",[0,0,0],"X",[.5,0,0], ...
                "M",[.5,.5,0]);
            line=kssolv.analysis.matgenlab.electronic_structure. ...
                BandStructureSymmLine(coordinates, ...
                struct("up",[-ones(1,6);ones(1,6)]), ...
                reciprocal,0,labels);
            continuous=kssolv.analysis.matgenlab.symmetry. ...
                HighSymmKpath.get_continuous_path(line);
            testCase.verifyClass(continuous, ...
                "kssolv.analysis.matgenlab.electronic_structure." + ...
                "BandStructureSymmLine");
            testCase.verifyEqual(numel(continuous.kpoints),12);
        end

        function allSetyawanPathFamiliesConstruct(testCase)
            structure=readNaCl(testCase);
            path=kssolv.analysis.matgenlab.symmetry.kpath. ...
                KPathSetyawanCurtarolo(structure);
            values={path.cubic(),path.fcc(),path.bcc(),path.tet(), ...
                path.bctet1(1,2),path.bctet2(3,2),path.orc(), ...
                path.orcf1(1,2,3),path.orcf2(2,3,4), ...
                path.orcf3(1,2,sqrt(4/3)),path.orci(1,2,3), ...
                path.orcc(1,2,3),path.hex(),path.rhl1(pi/3), ...
                path.rhl2(2*pi/3),path.mcl(2,3,pi/3), ...
                path.mclc1(1,2,3,pi/3), ...
                path.mclc2(1,2,3,pi/3), ...
                path.mclc3(1,2,3,pi/3), ...
                path.mclc4(1,2,3,pi/3), ...
                path.mclc5(1,2,3,pi/3),path.tria(),path.trib()};
            testCase.verifyEqual(numel(values),23);
            testCase.verifyTrue(all(cellfun(@(value) ...
                isa(value.kpoints,"containers.Map")&& ...
                ~isempty(value.path),values)));
        end
    end
end

function structure=readNaCl(testCase)
root=getenv("PYMATGEN_TEST_FILES");
if strlength(root)==0
    root="/tmp/matgenlab-plan.tMNeV8/" + ...
        "pymatgen-core-2026.7.24/test-files";
end
testCase.assumeTrue(isfolder(root), ...
    "Frozen pymatgen fixtures are not available.");
structure=kssolv.analysis.matgenlab.core.Structure.from_file( ...
    fullfile(root,"io","phonopy","POSCAR-NaCl"),"poscar");
end
