classdef MaggroupsInventoryTest < matlab.unittest.TestCase
    properties
        Oracle
    end

    methods (TestMethodSetup)
        function loadOracle(testCase)
            root = fileparts(fileparts(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath")))))));
            oraclePath = fullfile(root, "dev", "matgenlab", "oracles", ...
                "maggroups_2026.7.24.json");
            testCase.Oracle = jsondecode(fileread(oraclePath));
        end
    end

    methods (Test)
        function constructionAndOgLookupMatchUpstream(testCase)
            cls = @kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup;
            fromBnsLabel = cls("I_cmmm");
            fromBnsNumber = cls([71, 538]);
            fromOgLabel = kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup.from_og("C_Immm");
            fromOgNumber = kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup.from_og([65, 10, 554]);
            testCase.verifyEqual(fromBnsLabel, fromBnsNumber);
            testCase.verifyEqual(fromOgLabel, fromOgNumber);
            testCase.verifyEqual(fromBnsLabel, fromOgLabel);
            testCase.verifyEqual(cls(" I_c m m m "), fromBnsLabel);
            testCase.verifyEqual(fromBnsLabel.sg_symbol, ...
                string(testCase.Oracle.identity.bns_label));
            testCase.verifyEqual(fromOgNumber.sg_symbol, ...
                string(testCase.Oracle.identity.og_label));
            testCase.verifyEqual(cls(1).sg_symbol, "P1");
            testCase.verifyEqual(cls(1651).data.og_number(3), 1651);
        end

        function symbolsAndCrystalSystemsMatchOracle(testCase)
            cls = @kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup;
            for index = 1:numel(testCase.Oracle.symbols)
                reference = testCase.Oracle.symbols(index);
                group = cls(reshape(reference.label, 1, []));
                testCase.verifyEqual(group.sg_symbol, ...
                    string(reference.symbol));
            end
            references = testCase.Oracle.identity.crystal_systems;
            for index = 1:numel(references)
                group = cls(reshape(references(index).label, 1, []));
                testCase.verifyEqual(group.crystal_system, ...
                    string(references(index).system));
            end
        end

        function symmetryOperationsMatchFrozenMatrices(testCase)
            cls = @kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup;
            groups = {cls([62, 448]), cls([20, 37]), ...
                cls([2, 7], ...
                "c,1/4a+1/4b,-1/2a+1/2b;0,0,0")};
            for groupIndex = 1:numel(groups)
                group = groups{groupIndex};
                reference = testCase.Oracle.operations(groupIndex).values;
                testCase.verifyNumElements(group.symmetry_ops, ...
                    numel(reference));
                for operationIndex = 1:numel(reference)
                    operation = group.symmetry_ops{operationIndex};
                    testCase.verifyEqual(operation.rotation_matrix, ...
                        reference(operationIndex).rotation, ...
                        "AbsTol", 1e-12);
                    testCase.verifyEqual(operation.translation_vector, ...
                        reshape(reference(operationIndex).translation, 1, 3), ...
                        "AbsTol", 1e-12);
                    testCase.verifyEqual(operation.time_reversal, ...
                        reference(operationIndex).time_reversal);
                end
            end
        end

        function orbitAndMagmomsMatchUpstream(testCase)
            group = kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup("Pn'ma'");
            [points, moments] = group.get_orbit( ...
                [0.11, 0.22, 0.33], [1, 2, 3]);
            testCase.verifyEqual(points, testCase.Oracle.orbit.points, ...
                "AbsTol", 1e-12);
            actualMoments = cell2mat(cellfun(@(moment) ...
                moment.global_moment, moments, "UniformOutput", false).');
            testCase.verifyEqual(actualMoments, ...
                testCase.Oracle.orbit.magmoms, "AbsTol", 1e-12);
        end

        function conventionalLatticeCompatibilityMatches(testCase)
            lattices = struct( ...
                "cubic", kssolv.analysis.matgenlab.core.Lattice.cubic(1), ...
                "hexagonal", ...
                kssolv.analysis.matgenlab.core.Lattice.hexagonal(1, 2), ...
                "rhombohedral", ...
                kssolv.analysis.matgenlab.core.Lattice.rhombohedral(3, 80), ...
                "tetragonal", ...
                kssolv.analysis.matgenlab.core.Lattice.tetragonal(1, 2), ...
                "orthorhombic", ...
                kssolv.analysis.matgenlab.core.Lattice. ...
                orthorhombic(1, 2, 3));
            names = fieldnames(lattices);
            for index = 1:numel(testCase.Oracle.compatibility)
                reference = testCase.Oracle.compatibility(index);
                group = kssolv.analysis.matgenlab.symmetry.maggroups. ...
                    MagneticSpaceGroup(string(reference.label));
                for nameIndex = 1:numel(names)
                    name = names{nameIndex};
                    testCase.verifyEqual(group.is_compatible( ...
                        lattices.(name)), reference.values.(name));
                end
            end
        end

        function descriptionsMatchExactFrozenText(testCase)
            group = kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup([4, 11]);
            testCase.verifyEqual(string(group.data_str()), ...
                string(testCase.Oracle.data_str));
            testCase.verifyEqual(string(char(group)), ...
                string(testCase.Oracle.str));
            testCase.verifyEqual(string(group.dataStr(true)), ...
                string(testCase.Oracle.data_str));
        end

        function bundledDatabaseIsCompleteAndNative(testCase)
            packagePath = fileparts(which( ...
                "kssolv.analysis.matgenlab.symmetry.maggroups." + ...
                "MagneticSpaceGroup"));
            database = load(fullfile(packagePath, ...
                "magnetic_space_groups.mat"));
            testCase.verifySize(database.metadata, ...
                [testCase.Oracle.database.count, 6]);
            testCase.verifySize(database.labels, ...
                [testCase.Oracle.database.count, 2]);
            testCase.verifySize(database.blobs, ...
                [testCase.Oracle.database.count, 7]);
            testCase.verifyEqual(string(database.upstream_version), ...
                "pymatgen-core 2026.7.24");
        end

        function invalidLabelsRaiseTypedErrors(testCase)
            cls = @kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup;
            testCase.verifyError(@() cls("not-a-group"), ...
                "KSSOLV:Matgenlab:MagneticSpaceGroup:UnknownBnsLabel");
            testCase.verifyError(@() ...
                kssolv.analysis.matgenlab.symmetry.maggroups. ...
                MagneticSpaceGroup.from_og([999, 999, 999]), ...
                "KSSOLV:Matgenlab:MagneticSpaceGroup:UnknownOgLabel");
        end
    end
end
