classdef SettingsTest < matlab.unittest.TestCase
    methods (Test)
        function officialStringsAndMatricesRoundTrip(testCase)
            strings={ ...
                "a,b,c;0,0,0", ...
                "a-b,a+b,2c;0,0,1/2", ...
                "a/4+b/4-c/2,a/4-b/4,-a/2-b/2;0,0,0", ...
                "a,b,c;1/4,1/2,3/4"};
            matrices={eye(3), ...
                [1,1,0;-1,1,0;0,0,2], ...
                [.25,.25,-.5;.25,-.25,-.5;-.5,0,0], ...
                eye(3)};
            origins={[0,0,0],[0,0,.5],[0,0,0],[.25,.5,.75]};
            for index=1:numel(strings)
                value=kssolv.analysis.matgenlab.symmetry. ...
                    JonesFaithfulTransformation. ...
                    from_transformation_str(strings{index});
                testCase.verifyEqual(value.P,matrices{index}, ...
                    AbsTol=1e-14);
                testCase.verifyEqual(value.p,origins{index}, ...
                    AbsTol=1e-14);
                testCase.verifyEqual(value.transformation_string, ...
                    strings{index});
                direct=kssolv.analysis.matgenlab.symmetry. ...
                    JonesFaithfulTransformation( ...
                    matrices{index},origins{index});
                testCase.verifyTrue(value==direct);
                testCase.verifyTrue(value==value.inverse.inverse);
                testCase.verifyEqual( ...
                    value.inverse.inverse.transformation_string, ...
                    strings{index});
            end
            shifted=kssolv.analysis.matgenlab.symmetry. ...
                JonesFaithfulTransformation.from_origin_shift( ...
                "1/4,1/2,3/4");
            testCase.verifyEqual(shifted.p,[.25,.5,.75]);
        end

        function officialLatticeAndCoordinateTransforms(testCase)
            strings={ ...
                "a,b,c;0,0,0", ...
                "a-b,a+b,2c;0,0,1/2", ...
                "a/4+b/4-c/2,a/4-b/4,-a/2-b/2;0,0,0", ...
                "a,b,c;1/4,1/2,3/4"};
            expectedLattices={ ...
                [5,0,0;0,5,0;0,0,5], ...
                [5,5,0;-5,5,0;0,0,10], ...
                [1.25,1.25,-2.5;1.25,-1.25,-2.5;-2.5,0,0], ...
                [5,0,0;0,5,0;0,0,5]};
            expectedCoordinates={ ...
                [0,0,0;.5,.5,.5], ...
                [0,0,-.25;0,.5,0], ...
                [0,0,0;-1,0,-1.5], ...
                [-.25,-.5,-.75;.25,0,-.25]};
            lattice=kssolv.analysis.matgenlab.core.Lattice.cubic(5);
            coordinates=[0,0,0;.5,.5,.5];
            for index=1:numel(strings)
                value=kssolv.analysis.matgenlab.symmetry. ...
                    JonesFaithfulTransformation. ...
                    from_transformation_str(strings{index});
                transformed=value.transform_lattice(lattice);
                testCase.verifyEqual(transformed.matrix, ...
                    expectedLattices{index},AbsTol=1e-13);
                testCase.verifyEqual(value.transform_coords(coordinates), ...
                    expectedCoordinates{index},AbsTol=1e-13);
            end
        end

        function symmetryAndMagneticOperationsTransform(testCase)
            value=kssolv.analysis.matgenlab.symmetry. ...
                JonesFaithfulTransformation. ...
                from_transformation_str( ...
                "a-b,a+b,2c;0,0,1/2");
            operation=kssolv.analysis.matgenlab.core.SymmOp. ...
                from_xyz_str("-z,x,y");
            transformed=value.transform_symmop(operation);
            expected=kssolv.analysis.matgenlab.core.SymmOp. ...
                from_xyz_str( ...
                "-1/2x-1/2y-z+3/4," + ...
                "1/2x+1/2y-z+3/4," + ...
                "-1/2x+1/2y+3/4");
            testCase.verifyTrue(transformed==expected);
            magnetic=kssolv.analysis.matgenlab.core.MagSymmOp. ...
                fromRotationAndTranslationAndTimeReversal( ...
                operation.rotation_matrix, ...
                operation.translation_vector,-1,.01);
            transformedMagnetic=value.transform_symmop(magnetic);
            testCase.verifyClass(transformedMagnetic, ...
                "kssolv.analysis.matgenlab.core.MagSymmOp");
            testCase.verifyEqual(transformedMagnetic.time_reversal,-1);
            testCase.verifyEqual(transformedMagnetic.rotation_matrix, ...
                expected.rotation_matrix,AbsTol=1e-13);
            testCase.verifyEqual(transformedMagnetic.translation_vector, ...
                expected.translation_vector,AbsTol=1e-13);
        end

        function malformedOrNonlinearInputFailsClosed(testCase)
            factory=@(text)kssolv.analysis.matgenlab.symmetry. ...
                JonesFaithfulTransformation. ...
                from_transformation_str(text);
            testCase.verifyError(@()factory("a,b;0,0,0"), ...
                "KSSOLV:Matgenlab:JonesFaithful:Parse");
            testCase.verifyError(@()factory("a*b,b,c;0,0,0"), ...
                "KSSOLV:Matgenlab:JonesFaithful:Parse");
            testCase.verifyError(@()factory( ...
                "system('whoami'),b,c;0,0,0"), ...
                "KSSOLV:Matgenlab:JonesFaithful:Parse");
        end
    end
end
