classdef SiteSymmetriesTest < matlab.unittest.TestCase
    methods (Test)
        function officialPb2TiZrO6PointAndSharedCounts(testCase)
            fixture=fullfile(fileparts(mfilename("fullpath")), ...
                "+fixtures","Pb2TiZrO6.json");
            structure=kssolv.analysis.matgenlab.util.decode( ...
                fileread(fixture));
            pointOperations=kssolv.analysis.matgenlab.symmetry. ...
                get_site_symmetries(structure);
            testCase.verifyEqual(cellfun(@numel,pointOperations), ...
                [8,8,4,4,2,2,2,2,8,8]);
            for site=1:numel(pointOperations)
                testCase.verifyTrue(all(cellfun(@(operation) ...
                    all(abs(operation.translation_vector)<1e-12), ...
                    pointOperations{site})));
            end
            shared=kssolv.analysis.matgenlab.symmetry. ...
                get_shared_symmetry_operations( ...
                structure,pointOperations);
            expected=[ ...
                8,8,4,4,2,2,2,2,8,8; ...
                8,8,4,4,2,2,2,2,8,8; ...
                4,4,4,4,1,1,1,1,4,4; ...
                4,4,4,4,1,1,1,1,4,4; ...
                2,2,1,1,2,1,1,2,2,2; ...
                2,2,1,1,1,2,2,1,2,2; ...
                2,2,1,1,1,2,2,1,2,2; ...
                2,2,1,1,2,1,1,2,2,2; ...
                8,8,4,4,2,2,2,2,8,8; ...
                8,8,4,4,2,2,2,2,8,8];
            testCase.verifyEqual(cellfun(@numel,shared),expected);
            for first=1:structure.num_sites
                for second=1:structure.num_sites
                    rotations=cellfun(@(operation) ...
                        operation.rotation_matrix,shared{first,second}, ...
                        "UniformOutput",false);
                    testCase.verifyEqual(numel(rotations), ...
                        numel(unique(cellfun(@(rotation) ...
                        sprintf('%.8g,',rotation(:)),rotations, ...
                        "UniformOutput",false))));
                end
            end
        end

        function cubicSitesShareFullOctahedralGroup(testCase)
            structure=kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice.cubic(4), ...
                {"Cs","Cl"},[0,0,0;.5,.5,.5]);
            pointOperations=kssolv.analysis.matgenlab.symmetry. ...
                get_site_symmetries(structure,0.1);
            testCase.verifyEqual(cellfun(@numel,pointOperations),[48,48]);
            shared=kssolv.analysis.matgenlab.symmetry. ...
                get_shared_symmetry_operations( ...
                structure,pointOperations,0.1);
            testCase.verifyEqual(cellfun(@numel,shared), ...
                repmat(48,2,2));
        end
    end
end
