classdef AlchemyFiltersTest < matlab.unittest.TestCase
    % Official pymatgen alchemy/filter cases ported to MATLAB.

    methods (Test)
        function containsSpecieOfficialMatrix(testCase)
            import kssolv.analysis.matgenlab.alchemy.*
            import kssolv.analysis.matgenlab.core.*
            lattice = Lattice([3, 0, 0; 1, 3, 0; 0, -2, 3]);
            composition = Composition({ ...
                Species("Si", 4), 0.5; Species("O", -2), 0.25; ...
                Species("P", 5), 0.25});
            structure = Structure(lattice, ...
                {composition, composition, composition, composition}, ...
                [0, 0, 0; .75, .75, .75; .5, .5, .5; .25, .25, .25]);

            testCase.verifyFalse(ContainsSpecieFilter( ...
                {Species("Si", 5), Species("Mg", 2)}, true, false). ...
                test(structure));
            testCase.verifyTrue(ContainsSpecieFilter( ...
                {Species("Si", 5), Species("Mg", 2)}, false, false). ...
                test(structure));
            testCase.verifyTrue(ContainsSpecieFilter( ...
                {Species("Si", 4), Species("Mg", 2)}, true, false). ...
                test(structure));
            testCase.verifyFalse(ContainsSpecieFilter( ...
                {Species("Si", 5), Species("O", -2)}, true, true). ...
                test(structure));
            testCase.verifyTrue(ContainsSpecieFilter( ...
                {Species("Si", 5), Species("O", -2)}, false, true). ...
                test(structure));
            testCase.verifyFalse(ContainsSpecieFilter( ...
                {Species("Si", 4), Species("Mg", 2)}, false, true). ...
                test(structure));
            excluded = ContainsSpecieFilter({"Na"}, false, true, true);
            testCase.verifyTrue(excluded.test(structure));
        end

        function proximityUsesOfficialLi10GeP2S12Fixture(testCase)
            import kssolv.analysis.matgenlab.alchemy.*
            import kssolv.analysis.matgenlab.io.cif.*
            parser = CifParser.from_str(fileread(fixture("Li10GeP2S12.cif")));
            structures = parser.parse_structures(primitive = false, ...
                on_error = "raise");
            structure = structures{1};
            testCase.verifyTrue(SpecieProximityFilter( ...
                containers.Map("Li", 1)).test(structure));
            testCase.verifyFalse(SpecieProximityFilter( ...
                containers.Map("Li", 2)).test(structure));
            testCase.verifyTrue(SpecieProximityFilter( ...
                containers.Map("P", 1)).test(structure));
            testCase.verifyFalse(SpecieProximityFilter( ...
                containers.Map("P", 5)).test(structure));
        end

        function duplicateExistingChargeAndDistanceFilters(testCase)
            import kssolv.analysis.matgenlab.alchemy.*
            import kssolv.analysis.matgenlab.core.*
            base = Structure(Lattice.cubic(4), ...
                {"Li+", "O2-"}, [0, 0, 0; .5, .5, .5]);
            translated = Structure(Lattice.cubic(4), ...
                {"Li+", "O2-"}, [.25, .25, .25; .75, .75, .75]);
            different = Structure(Lattice.cubic(4), ...
                {"Na+", "O2-"}, [0, 0, 0; .5, .5, .5]);

            duplicate = RemoveDuplicatesFilter();
            testCase.verifyTrue(duplicate.test(base));
            testCase.verifyFalse(duplicate.test(base.copy()));
            testCase.verifyFalse(duplicate.test(translated));
            testCase.verifyTrue(duplicate.test(different));

            existing = RemoveExistingFilter({base, translated});
            testCase.verifyFalse(existing.test(base.copy()));
            testCase.verifyTrue(existing.test(different));
            testCase.verifyFalse(ChargeBalanceFilter().test(base));
            neutral = Structure(Lattice.cubic(4), ...
                {"Li+", "F-"}, [0, 0, 0; .5, .5, .5]);
            testCase.verifyTrue(ChargeBalanceFilter().test(neutral));
            testCase.verifyTrue(SpeciesMaxDistFilter( ...
                "Li+", "F-", 3.5).test(neutral));
            testCase.verifyFalse(SpeciesMaxDistFilter( ...
                "Li+", "F-", 3).test(neutral));
        end

        function allFilterMsonRoundTrips(testCase)
            import kssolv.analysis.matgenlab.alchemy.*
            import kssolv.analysis.matgenlab.core.*
            structure = Structure(Lattice.cubic(4), ...
                {"Li", "O"}, [0, 0, 0; .5, .5, .5]);
            filters = {ContainsSpecieFilter({"Li"}), ...
                SpecieProximityFilter(containers.Map("Li", 1)), ...
                RemoveDuplicatesFilter(), ...
                RemoveExistingFilter({structure}), ...
                ChargeBalanceFilter(), SpeciesMaxDistFilter("Li", "O", 3)};
            for index = 1:numel(filters)
                encoded = kssolv.analysis.matgenlab.util.encode(filters{index});
                decoded = kssolv.analysis.matgenlab.util.decode(encoded);
                testCase.verifyClass(decoded, class(filters{index}));
                testCase.verifyEqual( ...
                    jsondecode(kssolv.analysis.matgenlab.util.encode( ...
                    decoded.as_dict())), ...
                    jsondecode(kssolv.analysis.matgenlab.util.encode( ...
                    filters{index}.as_dict())));
            end
        end

        function containsResultMatchesFrozenOracle(testCase)
            testCase.assumeTrue(kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.isAvailable(), ...
                "Pinned pymatgen reference is unavailable.");
            import kssolv.analysis.matgenlab.alchemy.*
            import kssolv.analysis.matgenlab.core.*
            structure = Structure(Lattice.cubic(4), ...
                {"Li+", "O2-"}, [0, 0, 0; .5, .5, .5]);
            filter = ContainsSpecieFilter({"Li", "Na"}, false, false);
            response = kssolv.analysis.matgenlab.test.support. ...
                PymatgenOracle.execute(struct( ...
                "module", "pymatgen.alchemy.filters", ...
                "symbol", "ContainsSpecieFilter", ...
                "construct", struct("args", {{{"Li", "Na"}, false, false}}), ...
                "operations", {{struct("kind", "call", "name", "test", ...
                "args", {{structure.as_dict()}})}}));
            reference = response.results;
            if iscell(reference), reference = reference{1}; end
            testCase.verifyEqual(filter.test(structure), logical(reference));
        end
    end
end

function path = fixture(name)
path = fullfile(fileparts(mfilename("fullpath")), "+fixtures", name);
end
