classdef GenKpt < kssolv.analysis.matgenlab.util.MSONable
    %GENKPT PWmat line-mode gen.kpt representation.

    properties (SetAccess = private)
        reciprocal_lattice (3,3) double
        kpath (1,1) struct
        density (1,1) double
    end

    methods
        function obj = GenKpt(reciprocalLattice, kpoints, path, density)
            if nargin < 4, density = .01; end
            obj.reciprocal_lattice = double(reciprocalLattice);
            obj.kpath = struct("kpoints", normalizePoints(kpoints), ...
                "path", {normalizePath(path)});
            obj.density = double(density);
        end

        function value = get_str(obj)
            paths = obj.kpath.path;
            discontinuities = strings(max(0, numel(paths) - 1), 2);
            for index = 1:numel(paths) - 1
                discontinuities(index, :) = ...
                    [string(paths{index}{end}), ...
                    string(paths{index + 1}{1})];
            end
            flattened = [paths{:}];
            value = "Generated by pymatgen. density=" + ...
                pythonFloatText(obj.density / (2 * pi)) + ...
                ", fractional coordinates in reciprocal lattice." + ...
                newline;
            for index = 1:numel(flattened) - 1
                pair = string(flattened(index:index + 1));
                if any(all(discontinuities == pair, 2)), continue; end
                first = obj.kpath.kpoints(char(pair(1)));
                second = obj.kpath.kpoints(char(pair(2)));
                distance = norm((second - first) * ...
                    obj.reciprocal_lattice);
                value = value + sprintf("%.1f\n", ...
                    ceil(distance / obj.density));
                value = value + pointLine(first, pair(1));
                value = value + pointLine(second, pair(2));
            end
            value = string(value);
        end

        function write_file(obj, filename)
            kssolv.analysis.matgenlab.io.pwmat.PWmatIOUtils. ...
                write_text(filename, obj.get_str());
        end

        function value = asDict(obj)
            value = struct("x_module", "pymatgen.io.pwmat.inputs", ...
                "x_class", "GenKpt", ...
                "reciprocal_lattice", obj.reciprocal_lattice, ...
                "kpoints", obj.kpath.kpoints, ...
                "path", {obj.kpath.path}, "density", obj.density);
        end
    end

    methods (Static)
        function obj = from_structure(structure, dimension, density)
            if nargin < 3, density = .01; end
            pathObject = ...
                kssolv.analysis.matgenlab.symmetry.kpath.KPathSeek( ...
                structure);
            [points, paths] = canonicalizeLabels( ...
                pathObject.kpath.kpoints, pathObject.kpath.path);
            if dimension == 2
                filtered = containers.Map( ...
                    "KeyType", "char", "ValueType", "any");
                labels = points.keys();
                for index = 1:numel(labels)
                    coordinate = points(labels{index});
                    if coordinate(3) == 0
                        filtered(labels{index}) = coordinate;
                    end
                end
                filteredPaths = cell(1, 0);
                for index = 1:numel(paths)
                    segment = paths{index};
                    keep = cellfun(@(label) ...
                        isKey(filtered, char(label)), segment);
                    segment = segment(keep);
                    if numel(segment) > 1
                        filteredPaths{end + 1} = segment; %#ok<AGROW>
                    end
                end
                points = filtered;
                paths = filteredPaths;
            end
            obj = kssolv.analysis.matgenlab.io.pwmat.GenKpt( ...
                structure.lattice.reciprocal_lattice.matrix, ...
                points, paths, density * 2 * pi);
        end

        function obj = from_dict(value)
            obj = kssolv.analysis.matgenlab.io.pwmat.GenKpt( ...
                value.reciprocal_lattice, value.kpoints, ...
                value.path, value.density);
        end

        function obj = fromDict(value)
            obj = kssolv.analysis.matgenlab.io.pwmat.GenKpt. ...
                from_dict(value);
        end
    end
end

function value = pointLine(coordinate, label)
value = sprintf("    %12.6f\t%12.6f\t%12.6f\t%s\n", ...
    coordinate, label);
end

function value = normalizePoints(input)
if isa(input, "containers.Map")
    value = input;
    return
end
value = containers.Map("KeyType", "char", "ValueType", "any");
names = fieldnames(input);
for index = 1:numel(names)
    value(names{index}) = reshape(double(input.(names{index})), 1, 3);
end
end

function value = normalizePath(input)
if isempty(input), value = cell(1, 0); return; end
if isstring(input)
    if ismatrix(input) && size(input, 1) > 1
        value = arrayfun(@(row) cellstr(input(row, :)), ...
            1:size(input, 1), "UniformOutput", false);
    else
        value = {cellstr(reshape(input, 1, []))};
    end
elseif iscell(input) && ~isempty(input) && ...
        (ischar(input{1}) || isstring(input{1}))
    value = {cellstr(string(input))};
else
    value = cellfun(@(segment) ...
        cellstr(reshape(string(segment), 1, [])), input, ...
        "UniformOutput", false);
end
value = reshape(value, 1, []);
end

function [points, paths] = canonicalizeLabels(inputPoints, inputPaths)
% SeeK-path exposes plain HPKOT names (GAMMA, SIGMA, ...), whereas some
% native k-path backends use the corresponding TeX labels.
points = containers.Map("KeyType", "char", "ValueType", "any");
keys = inputPoints.keys();
for index = 1:numel(keys)
    points(char(canonicalLabel(keys{index}))) = inputPoints(keys{index});
end
paths = cellfun(@(segment) cellstr(arrayfun( ...
    @canonicalLabel, string(segment), "UniformOutput", false)), ...
    inputPaths, "UniformOutput", false);
paths = reshape(paths, 1, []);
end

function value = canonicalLabel(input)
value = string(input);
if startsWith(value, "\")
    value = upper(extractAfter(value, 1));
end
end

function value = pythonFloatText(input)
if isnan(input)
    value = "nan";
elseif isinf(input)
    if input < 0, value = "-inf"; else, value = "inf"; end
else
    javaText = string(javaMethod( ...
        "toString", "java.lang.Double", double(input)));
    match = regexp(javaText, ...
        '^([+-]?)(\d(?:\.\d+)?)[Ee]([+-]?\d+)$', ...
        "tokens", "once");
    if isempty(match)
        value = javaText;
        return
    end
    signText = string(match{1});
    mantissaParts = split(string(match{2}), ".");
    fraction = "";
    if numel(mantissaParts) > 1, fraction = mantissaParts(2); end
    if fraction == "0", fraction = ""; end
    digits = mantissaParts(1) + fraction;
    exponent = str2double(match{3});
    if exponent >= -4 && exponent < 16
        decimalPosition = 1 + exponent;
        if decimalPosition <= 0
            value = signText + "0." + ...
                string(repmat('0', 1, -decimalPosition)) + digits;
        elseif decimalPosition >= strlength(digits)
            value = signText + digits + ...
                string(repmat('0', 1, ...
                decimalPosition - strlength(digits))) + ".0";
        else
            value = signText + extractBefore(digits, ...
                decimalPosition + 1) + "." + ...
                extractAfter(digits, decimalPosition);
        end
    else
        mantissa = string(match{2});
        mantissa = erase(mantissa, regexpPattern('\.0$'));
        exponentSign = "+";
        if exponent < 0, exponentSign = "-"; end
        value = signText + mantissa + "e" + exponentSign + ...
            compose("%02d", abs(exponent));
    end
end
end
