classdef RatioFunction < kssolv.analysis.matgenlab.analysis.chemenv.utils.AbstractRatioFunction
    %RATIOFUNCTION General finite and infinite ratio functions.
    methods
        function obj=RatioFunction(varargin)
            obj@kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                AbstractRatioFunction(varargin{:});
        end
        function value=power2_decreasing_exp(obj,input)
            value=kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                power2_decreasing_exp(input,"edges",[0,obj.options.max], ...
                "alpha",obj.options.alpha);
        end
        function value=smootherstep(obj,input)
            value=kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                smootherstep(input,"edges",[obj.options.lower,obj.options.upper]);
        end
        function value=smoothstep(obj,input)
            value=kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                smoothstep(input,"edges",[obj.options.lower,obj.options.upper]);
        end
        function value=inverse_smootherstep(obj,input)
            value=kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                smootherstep(input,"edges",[obj.options.lower,obj.options.upper], ...
                "inverse",true);
        end
        function value=inverse_smoothstep(obj,input)
            value=kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                smoothstep(input,"edges",[obj.options.lower,obj.options.upper], ...
                "inverse",true);
        end
        function value=power2_inverse_decreasing(obj,input)
            value=kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                power2_inverse_decreasing(input,"edges",[0,obj.options.max]);
        end
        function value=power2_inverse_power2_decreasing(obj,input)
            value=kssolv.analysis.matgenlab.analysis.chemenv.utils. ...
                power2_inverse_power2_decreasing(input,"edges",[0,obj.options.max]);
        end
    end
    methods (Access=protected)
        function value=allowed_functions(~)
            value=struct(power2_decreasing_exp={{"max","alpha"}}, ...
                smoothstep={{"lower","upper"}}, ...
                smootherstep={{"lower","upper"}}, ...
                inverse_smoothstep={{"lower","upper"}}, ...
                inverse_smootherstep={{"lower","upper"}}, ...
                power2_inverse_decreasing={{"max"}}, ...
                power2_inverse_power2_decreasing={{"max"}});
        end
    end
end
