function values=cn_opt_params()
%CN_OPT_PARAMS Coordination-number-specific motif definitions.
values=struct();
values.cn2=struct( ...
    L_shaped={{"bent",struct(TA=.5,IGW_TA=15.15)}}, ...
    water_like={{"bent",struct(TA=.5802777777777778,IGW_TA=13.95)}}, ...
    bent_120_degrees={{"bent",struct(TA=2/3,IGW_TA=13.25)}}, ...
    bent_150_degrees={{"bent",struct(TA=5/6,IGW_TA=12.45)}}, ...
    linear={{"bent",struct(TA=1,IGW_TA=8.667)}});
values.cn3=struct( ...
    trigonal_planar={{"tri_plan_max"}}, ...
    trigonal_non_coplanar={{"tet_max",struct(TA=.6081734479693927, ...
        IGW_TA=18.33,fac_AA=1.5,exp_cos_AA=2)}}, ...
    T_shaped={{"T"}});
values.cn4=struct( ...
    square_co_planar={{"sq_plan_max"}},tetrahedral={{"tet_max"}}, ...
    rectangular_see_saw_like={{"see_saw_rect"}}, ...
    see_saw_like={{"tri_bipyr",struct(min_SPP=2.356194490192345, ...
        IGW_EP=15.75,IGW_SPP=12.75,fac_AA=1.5, ...
        exp_cos_AA=2,w_SPP=1)}},trigonal_pyramidal={{"tri_pyr"}});
values.cn5=struct(pentagonal_planar={{"pent_plan_max"}}, ...
    square_pyramidal={{"sq_pyr"}},trigonal_bipyramidal={{"tri_bipyr"}});
values.cn6=struct(hexagonal_planar={{"hex_plan_max"}}, ...
    octahedral={{"oct_max"}},pentagonal_pyramidal={{"pent_pyr"}});
values.cn7=struct(hexagonal_pyramidal={{"hex_pyr"}}, ...
    pentagonal_bipyramidal={{"pent_bipyr"}});
values.cn8=struct(body_centered_cubic={{"bcc"}}, ...
    hexagonal_bipyramidal={{"hex_bipyr"}});
values.cn12=struct(cuboctahedral={{"cuboct_max"}});
end
