function values=default_op_params()
%DEFAULT_OP_PARAMS Default parameter sets for local order parameters.
types=["cn","sgl_bd","bent","tri_plan","tri_plan_max","reg_tri", ...
    "sq_plan","sq_plan_max","pent_plan","pent_plan_max","sq","tet", ...
    "tet_max","tri_pyr","sq_pyr","sq_pyr_legacy","tri_bipyr", ...
    "sq_bipyr","oct","oct_legacy","pent_pyr","hex_pyr","pent_bipyr", ...
    "hex_bipyr","T","cuboct","cuboct_max","see_saw_rect","bcc","q2", ...
    "q4","q6","oct_max","hex_plan_max","sq_face_cap_trig_pris"];
order=kssolv.analysis.matgenlab.core.LocalStructOrderParams(cellstr(types));
values=struct();
for ii=1:numel(types)
    values.(char(types(ii)))=order.get_parameters(ii);
end
end
