function slabs=generate_all_slabs(structure,maxIndex,minSlabSize, ...
        minVacuumSize,varargin)
%GENERATE_ALL_SLABS Generate all reciprocal-symmetry-distinct surfaces.
options=struct("bonds",[],"tol",.1,"ftol",.1, ...
    "max_broken_bonds",0,"lll_reduce",false,"center_slab",false, ...
    "primitive",true,"max_normal_search",[],"symmetrize",false, ...
    "repair",false,"include_reconstructions",false, ...
    "in_unit_planes",false);
for index=1:2:numel(varargin)
    options.(char(string(varargin{index})))=varargin{index+1};
end
millers=kssolv.analysis.matgenlab.core. ...
    get_symmetrically_distinct_miller_indices(structure,maxIndex);
slabs={};
for index=1:numel(millers)
    generator=kssolv.analysis.matgenlab.core.SlabGenerator( ...
        structure,millers{index},minSlabSize,minVacuumSize, ...
        lll_reduce=options.lll_reduce,center_slab=options.center_slab, ...
        primitive=options.primitive, ...
        max_normal_search=options.max_normal_search, ...
        in_unit_planes=options.in_unit_planes);
    generated=generator.get_slabs(bonds=options.bonds,tol=options.tol, ...
        ftol=options.ftol,max_broken_bonds=options.max_broken_bonds, ...
        symmetrize=options.symmetrize,repair=options.repair);
    slabs=[slabs,generated]; %#ok<AGROW>
end
if options.include_reconstructions
    archivePath=fullfile(fileparts(mfilename("fullpath")),"+data", ...
        "reconstructions_archive.json");
    archive=jsondecode(fileread(archivePath));
    names=fieldnames(archive);
    symbol=kssolv.analysis.matgenlab.symmetry.analyzer. ...
        SpacegroupAnalyzer(structure).get_space_group_symbol();
    for index=1:numel(names)
        instructions=archive.(names{index});
        if isfield(instructions,"base_reconstruction")
            base=matlab.lang.makeValidName(char( ...
                instructions.base_reconstruction));
            instructions=archive.(base);
        end
        if ~isfield(instructions,"spacegroup")|| ...
                string(instructions.spacegroup.symbol)~=symbol || ...
                max(instructions.miller_index)>maxIndex
            continue
        end
        reconstruction=kssolv.analysis.matgenlab.core. ...
            ReconstructionGenerator(structure,minSlabSize, ...
            minVacuumSize,names{index},archive);
        slabs=[slabs,reconstruction.build_slabs()]; %#ok<AGROW>
    end
end
end
