function paths=generateModelingExamples(outputDirectory)
%GENERATEMODELINGEXAMPLES Build reopenable P3-P8 example projects.
arguments
    outputDirectory string=fullfile(KSSOLV_Toolbox.RootDirectory, ...
        "dev","modeling","examples")
end
dependency=fullfile(KSSOLV_Toolbox.RootDirectory, ...
    "+kssolv","+core","kssolv-3o");
addpath(dependency); evalc("KSSOLV.startup()");
if ~isfolder(outputDirectory), mkdir(outputDirectory); end

benzamide=blankMolecule();
benzamide=apply(benzamide,"sketch_ring",struct("ringSize",6, ...
    "species","C","center",[0,0,0],"normal",[0,0,1], ...
    "aromatic",true,"bondOrder",1.5));
benzamide=apply(benzamide,"sketch_atom",struct("species","C", ...
    "coordinates",[2.8,0,0],"connectTo",1,"bondOrder",1, ...
    "formalCharge",0,"hybridization","sp2","aromatic",false));
benzamide=apply(benzamide,"sketch_atom",struct("species","O", ...
    "coordinates",[4.03,0,0],"connectTo",7,"bondOrder",2, ...
    "formalCharge",0,"hybridization","sp2","aromatic",false));
benzamide=apply(benzamide,"sketch_atom",struct("species","N", ...
    "coordinates",[2.8,1.33,0],"connectTo",7,"bondOrder",1, ...
    "formalCharge",0,"hybridization","sp2","aromatic",false));
benzamide=apply(benzamide,"add_hydrogens",struct("indices",1:9));

blankCrystal=kssolv.analysis.matgenlab.core.Structure( ...
    eye(3)*10,cell(1,0),zeros(0,3));
platinum=apply(blankCrystal,"build_from_spacegroup",struct( ...
    "spaceGroup","Fm-3m","lattice",eye(3)*3.92, ...
    "species","Pt","fractionalCoordinates",[0,0,0]));
slab=apply(platinum,"build_slab",struct("millerIndex",[1,1,1], ...
    "slabSize",8,"vacuumSize",12,"centerSlab",true, ...
    "primitive",true));

polymer=kssolv.modeling.polymers.PolymerBuilder.block( ...
    ["PEO","PPO","PEO"],[5,10,5],seed=7, ...
    conformation="zigzag");
packed=kssolv.modeling.packing.PackingBuilder.pack( ...
    {polymer},4,density=.08,seed=17,tolerance=.5);

paths=[fullfile(outputDirectory,"01-benzamide-builder.ks"), ...
    fullfile(outputDirectory,"02-pt111-surface.ks"), ...
    fullfile(outputDirectory,"03-polymer-packing.ks")];
saveExample(paths(1),"Benzamide Builder",benzamide);
saveExample(paths(2),"Pt(111) Surface",slab);
saveExample(paths(3),"PEO-PPO-PEO Packing",packed);
end

function model=apply(model,id,parameters)
result=kssolv.modeling.CommandExecutor.execute(model,id,parameters);
model=result.model;
end

function value=blankMolecule()
value=kssolv.analysis.matgenlab.core.Molecule( ...
    strings(1,0),zeros(0,3),charge_spin_check=false, ...
    properties=struct("topology",struct("bonds",zeros(0,3), ...
    "origin","source","schemaVersion",1)));
end

function saveExample(path,label,model)
project=kssolv.services.filemanager.Project();
folder=project.findChildrenItem("Structure");
item=kssolv.services.filemanager.Structure(label);
item.description="KSSOLV Modeling schema v"+ ...
    KSSOLV_Toolbox.ModelingSchemaVersion+" example";
item.data=kssolv.services.fileparser.ModeledStructureData(model,label);
folder.addChildrenItem(item); project.saveToKsFile(path);
end
