classdef AdsorptionLocatorTest < matlab.unittest.TestCase
    methods (Test)
        function searchIsDeterministicAndExplicitlyNonEnergetic(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            adsorbate = oxygenHydrogenFragment();
            first = search(host, adsorbate, Seed = 41);
            second = search(host, adsorbate, Seed = 41);
            testCase.verifyGreaterThan(first.candidateCount, 0);
            testCase.verifyEqual(first.candidates, second.candidates);
            testCase.verifyEqual(first.searchKind, ...
                "geometry-candidate-search");
            testCase.verifyEqual(first.samplingMode, "exhaustive");
            testCase.verifyEqual(first.boundaryCondition, ...
                "periodic-minimum-image");
            testCase.verifyFalse(first.isEnergyModel);
            testCase.verifyEqual(first.energyUnit, "");
            testCase.verifyTrue(contains(first.limitations(1), ...
                "not adsorption energy"));
        end

        function scoreUsesPeriodicMinimumImage(testCase)
            host = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice( ...
                diag([4, 4, 12]), [true, true, false]), ...
                "Cu", [.02, .5, .5]);
            adsorbate = oxygenHydrogenFragment();
            first = search(host, adsorbate, SiteTypes = "ontop", ...
                Heights = 2, RotationStep = 360);
            translatedHost = kssolv.analysis.matgenlab.core.Structure( ...
                host.lattice, "Cu", [1.02, .5, .5]);
            second = search(translatedHost, adsorbate, ...
                SiteTypes = "ontop", Heights = 2, RotationStep = 360);
            testCase.verifyEqual(first.candidates(1).score, ...
                second.candidates(1).score, AbsTol = 1e-12);
            testCase.verifyEqual(first.candidates(1).minimumContact, ...
                second.candidates(1).minimumContact, AbsTol = 1e-12);
        end

        function arbitraryCarboxylUsesTheSameCandidatePipeline(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            adsorbate = carboxyl();
            result = search(host, adsorbate, ...
                SiteTypes = "ontop", Heights = [1.8, 2.2], ...
                RotationStep = 90, AnchorAtom = 1, ...
                OrientationAtom = 2, MaximumCandidates = 12);
            testCase.verifyGreaterThan(result.candidateCount, 0);
            testCase.verifyLessThanOrEqual(result.candidateCount, 12);
            testCase.verifyEqual(size(result.candidates(1).coordinates), ...
                [4, 3]);
            testCase.verifyEqual(result.candidates(1).rank, 1);
            testCase.verifyTrue(issorted([result.candidates.score]));
            testCase.verifyLessThan(max( ...
                [result.candidates.rotationDegrees]), 360);
        end

        function collisionFilterAndCancellationAreTransactional(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            adsorbate = oxygenHydrogenFragment();
            cancelled = search(host, adsorbate, CancelFcn = @()true);
            testCase.verifyTrue(cancelled.cancelled);
            testCase.verifyEmpty(cancelled.candidates);
            testCase.verifyEqual(host.num_sites, ...
                kssolv.modeling.test.ModelingFunctionalTestUtils. ...
                surfaceSlab().num_sites);
            testCase.verifyError(@()search(host, adsorbate, ...
                Heights = .1, MinimumDistance = 5), ...
                "KSSOLV:Modeling:AdsorptionLocatorNoCandidates");
        end

        function rankedCandidateCanBeAppliedWithoutMutatingInputs(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            adsorbate = carboxyl();
            originalHost = host.cart_coords;
            originalAdsorbate = adsorbate.cart_coords;
            result = search(host, adsorbate, SiteTypes = "ontop", ...
                Heights = 2.2, RotationStep = 90, ...
                AnchorAtom = 1, OrientationAtom = 2);
            output = kssolv.modeling.adsorption.AdsorptionLocator. ...
                applyCandidate(host, adsorbate, result.candidates(1));
            testCase.verifyEqual(output.num_sites, ...
                host.num_sites + adsorbate.num_sites);
            testCase.verifyEqual(host.cart_coords, originalHost);
            testCase.verifyEqual(adsorbate.cart_coords, originalAdsorbate);
            metadata = output.structure_properties.adsorptionCandidate;
            testCase.verifyEqual(metadata.candidateId, "candidate-1");
            testCase.verifyFalse(metadata.isEnergyModel);
            testCase.verifyEqual(metadata.bonds, [1,2,2;1,3,1;3,4,1]);
        end

        function validatedEnergyScorerUsesExplicitContract(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            adsorbate = carboxyl();
            contract = scorerContract(true);
            result = search(host, adsorbate, ...
                SiteTypes = "ontop", Heights = [1.8, 2.2], ...
                RotationStep = 90, AnchorAtom = 1, ...
                OrientationAtom = 2, ...
                ScoringModel = contract.id, ...
                ScoringFunction = @frozenEnergyOracle, ...
                ScoringContract = contract);
            testCase.verifyTrue(result.isEnergyModel);
            testCase.verifyEqual(result.energyUnit, "eV");
            testCase.verifyEqual(result.scoringModel, contract.id);
            testCase.verifyEqual(result.candidates(1).height, 2.2, ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                result.candidates(1).rotationDegrees, 90);
            testCase.verifyTrue(issorted([result.candidates.score]));
            applied = kssolv.modeling.adsorption.AdsorptionLocator. ...
                applyCandidate(host, adsorbate, result.candidates(1));
            metadata = applied.structure_properties.adsorptionCandidate;
            testCase.verifyTrue(metadata.isEnergyModel);
            testCase.verifyEqual(metadata.energyUnit, "eV");
            testCase.verifyEqual(metadata.score, result.candidates(1).score);
        end

        function energyScorerCannotBypassValidation(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            contract = scorerContract(true);
            contract.validated = false;
            testCase.verifyError(@()search(host, oxygenHydrogenFragment(), ...
                ScoringModel = contract.id, ...
                ScoringFunction = @frozenEnergyOracle, ...
                ScoringContract = contract), ...
                "KSSOLV:Modeling:AdsorptionScorerValidation");
        end

        function rigidMixtureUsesOneDisconnectedAdsorbatePipeline(testCase)
            mixture = kssolv.modeling.adsorption.AdsorbateAssembly. ...
                combine({oxygenHydrogenFragment(), carboxyl()});
            testCase.verifyEqual(mixture.num_sites, 6);
            testCase.verifyEqual( ...
                mixture.properties.topology.bonds, ...
                [1,2,1;3,4,2;3,5,1;5,6,1]);
            assembly = mixture.properties.adsorbateAssembly;
            testCase.verifyEqual(assembly.componentCount, 2);
            testCase.verifyFalse(assembly.hasIntercomponentBonds);
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            result = search(host, mixture, SiteTypes = "ontop", ...
                Heights = 2.4, RotationStep = 180, ...
                MaximumCandidates = 4);
            testCase.verifyGreaterThan(result.candidateCount, 0);
            testCase.verifyEqual( ...
                size(result.candidates(1).coordinates), [6, 3]);
        end

        function userFragmentCatalogPreservesAnchorAndOrientation(testCase)
            storePath = string(tempname) + ".json";
            cleanup = onCleanup(@()deleteIfPresent(storePath));
            port = struct("id", "oxygen-anchor", ...
                "label", "O anchor", "headIndices", 2, ...
                "leavingAtomIndices", zeros(1, 0), ...
                "defaultBondOrders", 1, "orientation", [1, 0, 0], ...
                "maxConnections", 1, "mode", "monodentate", ...
                "bondOverrides", zeros(0, 3));
            kssolv.modeling.fragments.FragmentLibrary.saveUser( ...
                "QA Custom COOH", carboxyl(), ports = port, ...
                storePath = storePath);
            payload = kssolv.modeling.adsorption. ...
                AdsorbateFragmentCatalog.userFragments( ...
                StorePath = storePath);
            testCase.verifyNumElements(payload, 1);
            testCase.verifyEqual(payload.id, ...
                "user-qa-custom-cooh-oxygen-anchor");
            testCase.verifyEqual(payload.anchorAtomIndex, 1);
            testCase.verifyEqual(payload.orientation, [1, 0, 0]);
            testCase.verifyEqual(payload.bonds, [0,1,2;0,2,1;2,3,1]);
            testCase.verifyEqual(payload.source, "user");
            clear cleanup
        end
    end
end

function result = search(host, adsorbate, options)
arguments
    host
    adsorbate
    options.SiteTypes string = ["ontop","bridge","hollow"]
    options.Heights double = [1.8,2.1,2.4]
    options.RotationStep double = 30
    options.AnchorAtom double = 1
    options.OrientationAtom double = 0
    options.MinimumDistance double = .6
    options.MaximumCandidates double = 200
    options.Seed double = 0
    options.CancelFcn function_handle = @()false
    options.ScoringModel string = ...
        kssolv.modeling.adsorption.AdsorptionScoringModel.GeometryId
    options.ScoringFunction = []
    options.ScoringContract struct = struct()
end
result = kssolv.modeling.adsorption.AdsorptionLocator.search( ...
    host, adsorbate, SiteTypes = options.SiteTypes, ...
    Heights = options.Heights, RotationStep = options.RotationStep, ...
    AnchorAtom = options.AnchorAtom, ...
    OrientationAtom = options.OrientationAtom, ...
    MinimumDistance = options.MinimumDistance, ...
    MaximumCandidates = options.MaximumCandidates, ...
    Seed = options.Seed, CancelFcn = options.CancelFcn, ...
    ScoringModel = options.ScoringModel, ...
    ScoringFunction = options.ScoringFunction, ...
    ScoringContract = options.ScoringContract);
end

function molecule = oxygenHydrogenFragment()
properties = struct("topology", struct("bonds", [1,2,1], ...
    "origin", "source", "schemaVersion", 1));
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    ["O","H"], [0,0,0;0,0,.97], ...
    charge_spin_check = false, properties = properties);
end

function molecule = carboxyl()
properties = struct("topology", struct("bonds", ...
    [1,2,2;1,3,1;3,4,1], "origin", "source", "schemaVersion", 1));
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    ["C","O","O","H"], ...
    [0,0,0;1.23,0,0;-.65,1.12,0;-1.1,1.9,0], ...
    charge_spin_check = false, properties = properties);
end

function contract = scorerContract(isEnergyModel)
contract = struct("id", "kssolv-test-frozen-energy-v1", ...
    "isEnergyModel", logical(isEnergyModel), "scoreUnit", "eV", ...
    "source", "Frozen P6 acceptance oracle", "version", "1", ...
    "validated", true, ...
    "validationReference", "AdsorptionLocatorTest/frozenEnergyOracle", ...
    "limitations", "Acceptance oracle only; no physical transferability");
end

function energy = frozenEnergyOracle(~, ~, ~, context)
energy = (context.height - 2.2)^2 + ...
    abs(context.rotationDegrees - 90) / 1000 + ...
    context.siteIndex / 1e5;
end

function deleteIfPresent(path)
if isfile(path), delete(path); end
end
