classdef AdvancedBuilderTest < matlab.unittest.TestCase
    %ADVANCEDBUILDERTEST Contracts for moire, IDPP and passivation.

    methods (Test)
        function commensurateMoireMatchesRequestedHexagonalAngle(testCase)
            layer = testCase.graphene();
            output = kssolv.modeling.builders.MoireBuilder.build( ...
                layer, layer, 21.786789, maximumIndex = 8);

            testCase.verifyEqual(output.num_sites, 28);
            testCase.verifyLessThan( ...
                output.properties.moire.angle_error_degrees, 1e-5);
            testCase.verifyLessThan( ...
                output.properties.moire.in_plane_strain, 1e-10);
            testCase.verifyEqual(output.pbc, [true, true, false]);
        end

        function idppKeepsEndpointsAndSeparatesLinearCollision(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                eye(3) * 10, [false, false, false]);
            initial = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"H", "H"}, ...
                [0.2, 0.5, 0.5; 0.8, 0.5, 0.5]);
            ending = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"H", "H"}, ...
                [0.8, 0.5, 0.5; 0.2, 0.5, 0.5]);
            [images, diagnostics] = ...
                kssolv.modeling.builders.IDPPInterpolator.interpolate( ...
                initial, ending, 5, maximumSteps = 300, ...
                forceTolerance = 0.05);

            testCase.verifyEqual(images{1}.cart_coords, ...
                initial.cart_coords, AbsTol = 1e-12);
            testCase.verifyEqual(images{end}.cart_coords, ...
                ending.cart_coords, AbsTol = 1e-12);
            testCase.verifyGreaterThan( ...
                norm(images{4}.cart_coords(1, :) - ...
                images{4}.cart_coords(2, :)), 0.5);
            testCase.verifyLessThan( ...
                diagnostics.final_energy, diagnostics.linear_path_energy);
        end

        function passivationAddsOnlyRequestedSurfaceAndPreservesInput(testCase)
            slab = testCase.simpleCubicSlab();
            original = slab.cart_coords;
            output = ...
                kssolv.modeling.builders.PassivationBuilder.build( ...
                slab, "H", side = "top", bondLength = 1.2, ...
                surfaceThickness = 0.2, targetCoordination = 14);

            testCase.verifyEqual(slab.cart_coords, original);
            testCase.verifyEqual(output.num_sites, slab.num_sites + 1);
            parent = output.site_properties.passivation_parent{end};
            testCase.verifyEqual(parent, 3);
            distance = norm(output.cart_coords(end, :) - ...
                slab.cart_coords(parent, :));
            testCase.verifyEqual(distance, 1.2, AbsTol = 1e-10);
            testCase.verifyGreaterThan( ...
                output.cart_coords(end, 3), slab.cart_coords(parent, 3));
        end

        function passivationRejectsInvalidSide(testCase)
            testCase.verifyError(@() ...
                kssolv.modeling.builders.PassivationBuilder.build( ...
                testCase.simpleCubicSlab(), "H", side = "middle"), ...
                "KSSOLV:Modeling:PassivationSide");
        end

        function solventLayerSupportsExplicitExecutorOverride(testCase)
            slab = testCase.simpleCubicSlab();
            solvent = ...
                kssolv.analysis.matgenlab.core.Molecule( ...
                "He", [0, 0, 0]);
            output = ...
                kssolv.modeling.builders.SolventLayerBuilder.build( ...
                slab, solvent, 2, executor = @fakePackmolExecutor, ...
                layerThickness = 5, clearance = 1, vacuum = 4);

            testCase.verifyEqual(output.num_sites, slab.num_sites + 2);
            testCase.verifyEqual(output.pbc, [true, true, false]);
            testCase.verifyEqual( ...
                output.properties.solvent_layer.molecule_count, 2);
            testCase.verifyEqual( ...
                output.site_properties.modeling_origin(end-1:end), ...
                {"solvent", "solvent"});
        end

        function solventLayerUsesNativePackmolByDefault(testCase)
            output = kssolv.modeling.builders.SolventLayerBuilder.build( ...
                testCase.simpleCubicSlab(), ...
                kssolv.analysis.matgenlab.core.Molecule( ...
                "He", [0, 0, 0]), 2, ...
                layerThickness = 5, clearance = 1, vacuum = 4);
            testCase.verifyEqual(output.num_sites, ...
                testCase.simpleCubicSlab().num_sites + 2);
            testCase.verifyEqual( ...
                output.properties.solvent_layer.method, ...
                "native MATLAB Packmol");
        end

        function modeledStructureDataSurvivesProjectSave(testCase)
            addpath(fullfile(KSSOLV_Toolbox.RootDirectory, ...
                "+kssolv", "+core", "kssolv-3o"));
            KSSOLV.startup();
            project = kssolv.services.filemanager.Project();
            folder = project.findChildrenItem("Structure");
            item = kssolv.services.filemanager.Structure( ...
                "Derived structure");
            item.data = ...
                kssolv.services.fileparser.ModeledStructureData( ...
                testCase.graphene(), "Derived structure");
            folder.addChildrenItem(item);
            filename = string(tempname) + ".ks";
            cleanup = onCleanup(@()deleteIfPresent(filename));

            project.saveToKsFile(filename);
            restored = ...
                kssolv.services.filemanager.Project.loadKsFile(filename);
            restoredItem = restored.findChildrenItem(item.name);
            testCase.verifyClass(restoredItem.data, ...
                "kssolv.services.fileparser.ModeledStructureData");
            testCase.verifyEqual( ...
                restoredItem.data.MatgenlabObject.frac_coords, ...
                item.data.MatgenlabObject.frac_coords, AbsTol = 1e-12);
            clear cleanup
        end
    end

    methods (Static, Access = private)
        function value = graphene()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice. ...
                hexagonal(2.46, 15), ...
                {"C", "C"}, [0, 0, .5; 1/3, 2/3, .5]);
        end

        function value = simpleCubicSlab()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                diag([2, 2, 12]), {"Si", "Si", "Si"}, ...
                [0, 0, 4/12; 0, 0, 6/12; 0, 0, 8/12]);
        end
    end
end

function result = fakePackmolExecutor(request)
assert(request.command == "packmol");
assert(contains(request.stdin, "fixed 0 0 0 0 0 0"));
assert(contains(request.stdin, "inside box"));
contents = sprintf([ ...
    '5\npacked by test\n' ...
    'Si 0 0 2\nSi 0 0 4\nSi 0 0 6\n' ...
    'He 0.5 0.5 8\nHe 1.0 1.0 9\n']);
fileId = fopen(fullfile(request.working_directory, ...
    request.outputfile), "w");
assert(fileId >= 0);
cleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, contents, "char");
clear cleanup
result = struct("status", 0, ...
    "stdout", "PACKMOL success" + newline, ...
    "stderr", "", "timed_out", false);
end

function deleteIfPresent(filename)
if isfile(filename)
    delete(filename);
end
end
