classdef CommandExecutorTest < matlab.unittest.TestCase
    %COMMANDEXECUTORTEST Production contracts for modeling transactions.

    methods (Test)
        function catalogMatchesAtomKitHierarchy(testCase)
            categories = kssolv.modeling.CommandCatalog.categories();
            testCase.verifyEqual(numel(categories), 10);
            testCase.verifyEqual( ...
                string({categories.id}), [
                "atomic_editor", "molecule_builder", ...
                "polymer_builder", "amorphous_builder", ...
                "lattice_editor", "supercell_lattice", ...
                "defects_alloys", "nanostructures", ...
                "surfaces_interfaces", "symmetry_tools"]);
            ids = kssolv.modeling.CommandCatalog.commandIds();
            testCase.verifyEqual(numel(ids), 75);
            testCase.verifyEqual(numel(unique(ids)), 75);
            supported = ...
                kssolv.modeling.CommandExecutor.supportedCommandIds();
            testCase.verifyEqual(sort(supported), sort(ids));
        end

        function commandExecutionDoesNotMutateInput(testCase)
            input = testCase.structure();
            originalCoordinates = input.cart_coords;
            result = kssolv.modeling.CommandExecutor.execute( ...
                input, "translate_atoms", ...
                struct("indices", 1, "vector", [1, 0, 0]));

            testCase.verifyEqual(input.cart_coords, originalCoordinates);
            testCase.verifyEqual( ...
                result.model.cart_coords(1, :), ...
                originalCoordinates(1, :) + [1, 0, 0], ...
                AbsTol = 1e-12);
        end

        function capabilitiesExposeMoleculeCommands(testCase)
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                ["O", "H", "H"], ...
                [0, 0, 0; 0.9572, 0, 0; -0.239, 0.927, 0]);
            moleculeCommands = [ ...
                "add_atom", "center_atoms", "delete_atoms", ...
                "mirror_atoms", "move_atoms", "perturb_atoms", ...
                "rotate_atoms", "substitute_atoms", "translate_atoms"];
            for commandId = moleculeCommands
                [supported, reason] = ...
                    kssolv.modeling.CommandExecutor.supportsForModel( ...
                    commandId, molecule);
                testCase.verifyTrue(supported, reason);
            end
            [supported, reason] = ...
                kssolv.modeling.CommandExecutor.supportsForModel( ...
                "build_supercell", molecule);
            testCase.verifyFalse(supported);
            testCase.verifyNotEmpty(reason);
        end

        function moleculeAtomicCommandsPreserveInputAndTopology(testCase)
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                ["O", "H", "H"], ...
                [0, 0, 0; 0.9572, 0, 0; -0.239, 0.927, 0]);
            molecule.properties.topology = struct( ...
                "bonds", [1, 2, 1; 1, 3, 1], "origin", "source");
            original = molecule.copy();

            moved = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "move_atoms", struct( ...
                "indices", 2, "coordinates", [1, 2, 3], ...
                "cartesian", true));
            testCase.verifyEqual(moved.model.cart_coords(2, :), [1, 2, 3]);
            testCase.verifyEqual(moved.model.properties.topology.bonds, ...
                [1, 2, 1; 1, 3, 1]);

            substituted = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "substitute_atoms", struct( ...
                "indices", 2, "species", "F"));
            testCase.verifyEqual( ...
                substituted.model(2).species_string, "F");
            testCase.verifyEqual( ...
                substituted.model.properties.topology.bonds, ...
                [1, 2, 1; 1, 3, 1]);

            translated = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "translate_atoms", struct( ...
                "indices", [2, 3], "vector", [0, 0, 1], ...
                "fractional", false));
            testCase.verifyEqual(translated.model.cart_coords(2:3, :), ...
                molecule.cart_coords(2:3, :) + [0, 0, 1], ...
                AbsTol = 1e-12);

            deleted = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "delete_atoms", struct("indices", 2));
            testCase.verifyEqual(deleted.model.num_sites, 2);
            testCase.verifyEqual( ...
                deleted.model.properties.topology.bonds, [1, 2, 1]);
            testCase.verifyEqual(molecule.cart_coords, original.cart_coords);
            testCase.verifyEqual(molecule.properties.topology.bonds, ...
                original.properties.topology.bonds);
        end

        function editTransactionRejectsStaleCommitAndCancelIsClean(testCase)
            input = testCase.structure();
            transaction = ...
                kssolv.modeling.contracts.EditTransaction( ...
                input, 4, "translate_atoms", struct( ...
                "indices", 1, "vector", [0.25, 0, 0], ...
                "fractional", true));
            preview = transaction.preview();
            testCase.verifyEqual(input.frac_coords(1, :), [0, 0, 0]);
            testCase.verifyEqual(preview.model.frac_coords(1, :), ...
                [0.25, 0, 0], AbsTol = 1e-12);
            testCase.verifyError(@()transaction.commit(5), ...
                "KSSOLV:Modeling:StaleTransaction");

            cancelled = ...
                kssolv.modeling.contracts.EditTransaction( ...
                input, 4, "delete_atoms", struct("indices", 1));
            cancelled.cancel();
            testCase.verifyEqual(cancelled.State, "cancelled");
            testCase.verifyError(@()cancelled.commit(4), ...
                "KSSOLV:Modeling:TransactionState");
            testCase.verifyEqual(input.num_sites, 2);
        end

        function capabilityDeclaresOnlyModelCommandsPreviewable(testCase)
            translated = kssolv.modeling.contracts.CommandCapability. ...
                forCommand("translate_atoms");
            measured = kssolv.modeling.contracts.CommandCapability. ...
                forCommand("measure_geometry");
            enumerated = kssolv.modeling.contracts.CommandCapability. ...
                forCommand("enumerate_point_defects");
            testCase.verifyTrue(translated.supportsPreview);
            testCase.verifyEqual(translated.resultKind, "model");
            testCase.verifyFalse(measured.supportsPreview);
            testCase.verifyEqual(measured.resultKind, "analysis");
            testCase.verifyFalse(enumerated.supportsPreview);
        end

        function moleculeTransformCommandsUseCartesianSemantics(testCase)
            molecule = kssolv.analysis.matgenlab.core.Molecule( ...
                ["H", "H"], [1, 0, 0; 2, 0, 0]);
            added = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "add_atom", struct( ...
                "species", "He", "coordinates", [3, 0, 0], ...
                "cartesian", true));
            testCase.verifyEqual(added.model.cart_coords(3, :), [3, 0, 0]);
            centered = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "center_atoms", struct( ...
                "indices", [1, 2], "center", [0, 0, 0]));
            testCase.verifyEqual(mean(centered.model.cart_coords, 1), ...
                [0, 0, 0], AbsTol = 1e-12);
            mirrored = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "mirror_atoms", struct( ...
                "indices", 1, "normal", [1, 0, 0], ...
                "point", [0, 0, 0]));
            testCase.verifyEqual(mirrored.model.cart_coords(1, :), ...
                [-1, 0, 0], AbsTol = 1e-12);
            rotated = kssolv.modeling.CommandExecutor.execute( ...
                molecule, "rotate_atoms", struct( ...
                "indices", [1, 2], "angleDegrees", 90, ...
                "axis", [0, 0, 1], "anchor", [0, 0, 0]));
            testCase.verifyEqual(rotated.model.cart_coords, ...
                [0, 1, 0; 0, 2, 0], AbsTol = 1e-12);
        end

        function atomicEditorCommandsValidateAndTransform(testCase)
            input = testCase.structure();
            added = kssolv.modeling.CommandExecutor.execute( ...
                input, "add_atom", struct( ...
                "species", "H", "coordinates", [.5, .5, .5]));
            testCase.verifyEqual(added.model.num_sites, 3);

            substituted = kssolv.modeling.CommandExecutor.execute( ...
                input, "substitute_atoms", struct( ...
                "indices", 1, "species", "C"));
            testCase.verifyEqual( ...
                substituted.model(1).species_string, "C");
            testCase.verifyEqual(substituted.model(1).label, "C");

            moved = kssolv.modeling.CommandExecutor.execute( ...
                input, "move_atoms", struct( ...
                "indices", 2, "coordinates", [2, 3, 4], ...
                "cartesian", true));
            testCase.verifyEqual(moved.model.cart_coords(2, :), ...
                [2, 3, 4], AbsTol = 1e-12);

            translated = kssolv.modeling.CommandExecutor.execute( ...
                input, "translate_atoms", struct( ...
                "indices", [1, 2], "vector", [.1, .2, .3], ...
                "fractional", true));
            testCase.verifyEqual(translated.model.frac_coords, ...
                input.frac_coords + [.1, .2, .3], AbsTol = 1e-12);

            deleted = kssolv.modeling.CommandExecutor.execute( ...
                input, "delete_atoms", struct("indices", 2));
            testCase.verifyEqual(deleted.model.num_sites, 1);

            emptied = kssolv.modeling.CommandExecutor.execute( ...
                input, "delete_atoms", struct("indices", [1, 2]));
            testCase.verifyEqual(emptied.model.num_sites, 0);
            testCase.verifyEqual(emptied.model.lattice.matrix, ...
                input.lattice.matrix, AbsTol = 1e-12);

            fixed = kssolv.modeling.CommandExecutor.execute( ...
                input, "fix_atoms", struct("indices", 2));
            testCase.verifyEqual( ...
                fixed.model(1).site_properties.selective_dynamics, ...
                [true, true, true]);
            testCase.verifyEqual( ...
                fixed.model(2).site_properties.selective_dynamics, ...
                [false, false, false]);

        end

        function latticeAndSupercellCommandsPreserveInvariants(testCase)
            input = testCase.structure();
            swapped = kssolv.modeling.CommandExecutor.execute( ...
                input, "swap_axes", struct("order", [2, 3, 1]));
            testCase.verifyEqual( ...
                swapped.model.lattice.matrix, ...
                input.lattice.matrix([2, 3, 1], :), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                swapped.model.cart_coords, input.cart_coords, ...
                AbsTol = 1e-12);

            supercell = kssolv.modeling.CommandExecutor.execute( ...
                input, "build_supercell", ...
                struct("scalingMatrix", [2, 1, 1]));
            testCase.verifyEqual(supercell.model.num_sites, 4);
            testCase.verifyEqual( ...
                supercell.model.volume, 2 * input.volume, ...
                AbsTol = 1e-10);
        end

        function symmetryCommandsReturnAnalysisOrModels(testCase)
            input = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 4, {"Si"}, [0, 0, 0]);
            analysis = kssolv.modeling.CommandExecutor.execute( ...
                input, "find_symmetry");
            testCase.verifyFalse(analysis.changed);
            testCase.verifyEqual(analysis.data.number, 221);

            primitive = kssolv.modeling.CommandExecutor.execute( ...
                input, "primitive_cell");
            testCase.verifyTrue(primitive.changed);
            testCase.verifyGreaterThan(primitive.model.num_sites, 0);
        end

        function defectAndSurfaceBuildersUseMatgenlabPrimitives(testCase)
            input = testCase.structure();
            vacancy = kssolv.modeling.CommandExecutor.execute( ...
                input, "create_point_defects", struct( ...
                "defectType", "vacancy", "indices", 2));
            testCase.verifyEqual(vacancy.model.num_sites, 1);

            slab = kssolv.modeling.CommandExecutor.execute( ...
                input, "build_slab", struct( ...
                "millerIndex", [0, 0, 1], ...
                "slabSize", 6, "vacuumSize", 8, ...
                "centerSlab", true, "primitive", false));
            vacuum = kssolv.modeling.CommandExecutor.execute( ...
                slab.model, "add_vacuum", struct("amount", 5));
            testCase.verifyGreaterThan( ...
                vacuum.model.lattice.c, slab.model.lattice.c);

            sites = kssolv.modeling.CommandExecutor.execute( ...
                slab.model, "find_adsorption_sites", ...
                struct("distance", 2));
            testCase.verifyFalse(sites.changed);
            testCase.verifyTrue(isstruct(sites.data));
        end

        function inProcessSqsOrdersDisorderedStructure(testCase)
            composition = ...
                kssolv.analysis.matgenlab.core.Composition( ...
                {"Si", .5; "Ge", .5});
            disordered = ...
                kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 4, {composition}, [0, 0, 0]);
            result = kssolv.modeling.CommandExecutor.execute( ...
                disordered, "generate_sqs_model", struct( ...
                "scaling", 2, "searchTime", 1));
            testCase.verifyEqual(result.model.num_sites, 2);
            testCase.verifyTrue(result.model.is_ordered);
        end

        function unsupportedCommandsFailExplicitly(testCase)
            testCase.verifyError(@() ...
                kssolv.modeling.CommandExecutor.execute( ...
                testCase.structure(), "not_a_modeling_command"), ...
                "KSSOLV:Modeling:NotImplemented");
        end
    end

    methods (Static, Access = private)
        function value = structure()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                diag([5, 6, 7]), {"Si", "O"}, ...
                [0, 0, 0; .25, .25, .25]);
        end
    end
end
