classdef CommandExecutorTest < matlab.unittest.TestCase
    %COMMANDEXECUTORTEST Production contracts for modeling transactions.

    methods (Test)
        function catalogMatchesAtomKitHierarchy(testCase)
            categories = kssolv.modeling.CommandCatalog.categories();
            testCase.verifyEqual(numel(categories), 7);
            testCase.verifyEqual( ...
                string({categories.id}), [
                "atomic_editor", "lattice_editor", "supercell_lattice", ...
                "defects_alloys", "nanostructures", ...
                "surfaces_interfaces", "symmetry_tools"]);
            ids = kssolv.modeling.CommandCatalog.commandIds();
            testCase.verifyEqual(numel(ids), 41);
            testCase.verifyEqual(numel(unique(ids)), 41);
            supported = ...
                kssolv.modeling.CommandExecutor.supportedCommandIds();
            testCase.verifyEqual(sort(supported), sort(ids));
        end

        function commandExecutionDoesNotMutateInput(testCase)
            input = testCase.structure();
            originalCoordinates = input.cart_coords;
            result = kssolv.modeling.CommandExecutor.execute( ...
                input, "translate_atoms", ...
                struct("indices", 1, "vector", [1, 0, 0]));

            testCase.verifyEqual(input.cart_coords, originalCoordinates);
            testCase.verifyEqual( ...
                result.model.cart_coords(1, :), ...
                originalCoordinates(1, :) + [1, 0, 0], ...
                AbsTol = 1e-12);
        end

        function atomicEditorCommandsValidateAndTransform(testCase)
            input = testCase.structure();
            added = kssolv.modeling.CommandExecutor.execute( ...
                input, "add_atom", struct( ...
                "species", "H", "coordinates", [.5, .5, .5]));
            testCase.verifyEqual(added.model.num_sites, 3);

            substituted = kssolv.modeling.CommandExecutor.execute( ...
                input, "substitute_atoms", struct( ...
                "indices", 1, "species", "C"));
            testCase.verifyEqual( ...
                substituted.model(1).species_string, "C");

            fixed = kssolv.modeling.CommandExecutor.execute( ...
                input, "fix_atoms", struct("indices", 2));
            testCase.verifyEqual( ...
                fixed.model(1).site_properties.selective_dynamics, ...
                [true, true, true]);
            testCase.verifyEqual( ...
                fixed.model(2).site_properties.selective_dynamics, ...
                [false, false, false]);

            testCase.verifyError(@() ...
                kssolv.modeling.CommandExecutor.execute( ...
                input, "delete_atoms", struct("indices", [1, 2])), ...
                "KSSOLV:Modeling:EmptyStructure");
        end

        function latticeAndSupercellCommandsPreserveInvariants(testCase)
            input = testCase.structure();
            swapped = kssolv.modeling.CommandExecutor.execute( ...
                input, "swap_axes", struct("order", [2, 3, 1]));
            testCase.verifyEqual( ...
                swapped.model.lattice.matrix, ...
                input.lattice.matrix([2, 3, 1], :), ...
                AbsTol = 1e-12);
            testCase.verifyEqual( ...
                swapped.model.cart_coords, input.cart_coords, ...
                AbsTol = 1e-12);

            supercell = kssolv.modeling.CommandExecutor.execute( ...
                input, "build_supercell", ...
                struct("scalingMatrix", [2, 1, 1]));
            testCase.verifyEqual(supercell.model.num_sites, 4);
            testCase.verifyEqual( ...
                supercell.model.volume, 2 * input.volume, ...
                AbsTol = 1e-10);
        end

        function symmetryCommandsReturnAnalysisOrModels(testCase)
            input = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 4, {"Si"}, [0, 0, 0]);
            analysis = kssolv.modeling.CommandExecutor.execute( ...
                input, "find_symmetry");
            testCase.verifyFalse(analysis.changed);
            testCase.verifyEqual(analysis.data.number, 221);

            primitive = kssolv.modeling.CommandExecutor.execute( ...
                input, "primitive_cell");
            testCase.verifyTrue(primitive.changed);
            testCase.verifyGreaterThan(primitive.model.num_sites, 0);
        end

        function defectAndSurfaceBuildersUseMatgenlabPrimitives(testCase)
            input = testCase.structure();
            vacancy = kssolv.modeling.CommandExecutor.execute( ...
                input, "create_point_defects", struct( ...
                "defectType", "vacancy", "indices", 2));
            testCase.verifyEqual(vacancy.model.num_sites, 1);

            slab = kssolv.modeling.CommandExecutor.execute( ...
                input, "build_slab", struct( ...
                "millerIndex", [0, 0, 1], ...
                "slabSize", 6, "vacuumSize", 8, ...
                "centerSlab", true, "primitive", false));
            vacuum = kssolv.modeling.CommandExecutor.execute( ...
                slab.model, "add_vacuum", struct("amount", 5));
            testCase.verifyGreaterThan( ...
                vacuum.model.lattice.c, slab.model.lattice.c);

            sites = kssolv.modeling.CommandExecutor.execute( ...
                slab.model, "find_adsorption_sites", ...
                struct("distance", 2));
            testCase.verifyFalse(sites.changed);
            testCase.verifyTrue(isstruct(sites.data));
        end

        function inProcessSqsOrdersDisorderedStructure(testCase)
            composition = ...
                kssolv.analysis.matgenlab.core.Composition( ...
                {"Si", .5; "Ge", .5});
            disordered = ...
                kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 4, {composition}, [0, 0, 0]);
            result = kssolv.modeling.CommandExecutor.execute( ...
                disordered, "generate_sqs_model", struct( ...
                "scaling", 2, "searchTime", 1));
            testCase.verifyEqual(result.model.num_sites, 2);
            testCase.verifyTrue(result.model.is_ordered);
        end

        function unsupportedCommandsFailExplicitly(testCase)
            testCase.verifyError(@() ...
                kssolv.modeling.CommandExecutor.execute( ...
                testCase.structure(), "not_a_modeling_command"), ...
                "KSSOLV:Modeling:NotImplemented");
        end
    end

    methods (Static, Access = private)
        function value = structure()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                diag([5, 6, 7]), {"Si", "O"}, ...
                [0, 0, 0; .25, .25, .25]);
        end
    end
end
