classdef CrystalConstructionFunctionalTest < matlab.unittest.TestCase
    methods (Test)
        function spaceGroupBuilderAndP1AreExplicit(testCase)
            input=kssolv.modeling.test.ModelingFunctionalTestUtils.simpleCubic();
            result=kssolv.modeling.CommandExecutor.execute(input, ...
                "build_from_spacegroup",struct("spaceGroup","Fm-3m", ...
                "lattice",eye(3)*3.61,"species","Cu", ...
                "fractionalCoordinates",[0,0,0]));
            testCase.verifyEqual(result.model.num_sites,4);
            analyzer=kssolv.analysis.matgenlab.symmetry.analyzer. ...
                SpacegroupAnalyzer(result.model,.001,5);
            testCase.verifyEqual(analyzer.get_space_group_number(),225);
            p1=kssolv.modeling.CommandExecutor.execute(result.model,"make_p1");
            testCase.verifyEqual(p1.model.num_sites,4);
            testCase.verifyEqual( ...
                p1.model.properties.symmetry.declaredSpaceGroup,"P1");
        end

        function pointDefectsAreSymmetryUniqueWithDegeneracy(testCase)
            input=kssolv.analysis.matgenlab.core.Structure.from_spacegroup( ...
                "Fm-3m",eye(3)*3.61,"Cu",[0,0,0]);
            result=kssolv.modeling.CommandExecutor.execute(input, ...
                "enumerate_point_defects",struct("defectType","vacancy"));
            testCase.verifyEqual(numel(result.data.variants),1);
            testCase.verifyEqual(result.data.degeneracies,4);
            testCase.verifyEqual(result.data.variants{1}.num_sites,3);
            testCase.verifyEqual(result.data.netCharges,0);
            testCase.verifyGreaterThan(result.data.minimumContacts,0);
            testCase.verifyNumElements(result.models,1);
            tableData=kssolv.ui.features.modeling. ...
                AnalysisResultPresenter.defectCandidateTable(result);
            testCase.verifyEqual(height(tableData),1);
            testCase.verifyEqual(tableData.Degeneracy,4);
        end

        function crystalBuilderReportsWyckoffOccupancyAndCollisions(testCase)
            input=kssolv.modeling.test.ModelingFunctionalTestUtils.simpleCubic();
            result=kssolv.modeling.CommandExecutor.execute(input, ...
                "build_from_spacegroup",struct("spaceGroup","Pm-3m", ...
                "lattice",eye(3)*4,"species","Si", ...
                "fractionalCoordinates",[0,0,0],"occupancies",0.5, ...
                "collisionTolerance",0.1));
            testCase.verifyFalse(result.model.is_ordered);
            testCase.verifyEqual(result.analysis.equivalentSites.wyckoff,"a");
            testCase.verifyEqual( ...
                result.analysis.equivalentSites.multiplicity,1);
            testCase.verifyEqual( ...
                result.analysis.equivalentSites.occupancy,0.5, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.model.properties.symmetry.mode,"preserve");
            [asymmetric,equivalent]= ...
                kssolv.ui.features.modeling.AnalysisResultPresenter. ...
                crystalBuilderTables(result);
            testCase.verifyEqual(height(asymmetric),1);
            testCase.verifyEqual(height(equivalent),1);
            testCase.verifyEqual(equivalent.Wyckoff,"a");
            testCase.verifyError(@()kssolv.modeling.CommandExecutor.execute( ...
                input,"build_from_spacegroup",struct("spaceGroup","P1", ...
                "lattice",eye(3)*4,"species","Si O", ...
                "fractionalCoordinates",[0,0,0;0,0,0])), ...
                "KSSOLV:Modeling:CrystalBuilderCollision");
        end

        function twentyCrystalBuilderCasesMatchFrozenOracle(testCase)
            path=fullfile(KSSOLV_Toolbox.RootDirectory,"dev","modeling", ...
                "acceptance","oracles","crystal-builder-v1.json");
            oracle=jsondecode(fileread(path));
            testCase.verifyEqual(numel(oracle.cases),20);
            input=kssolv.modeling.test.ModelingFunctionalTestUtils.simpleCubic();
            for index=1:numel(oracle.cases)
                item=oracle.cases(index);
                switch string(item.latticeKind)
                    case "triclinic"
                        lattice=kssolv.analysis.matgenlab.core.Lattice. ...
                            from_parameters(4.1,5.2,6.3,71,82,77);
                    case "monoclinic"
                        lattice=kssolv.analysis.matgenlab.core.Lattice. ...
                            monoclinic(4.1,5.2,6.3,105);
                    case "orthorhombic"
                        lattice=kssolv.analysis.matgenlab.core.Lattice. ...
                            orthorhombic(4.1,5.2,6.3);
                    case "tetragonal"
                        lattice=kssolv.analysis.matgenlab.core.Lattice. ...
                            tetragonal(4.1,6.3);
                    case "hexagonal"
                        lattice=kssolv.analysis.matgenlab.core.Lattice. ...
                            hexagonal(4.1,6.3);
                    case "cubic"
                        lattice=kssolv.analysis.matgenlab.core.Lattice. ...
                            cubic(5.1);
                end
                result=kssolv.modeling.CommandExecutor.execute(input, ...
                    "build_from_spacegroup",struct( ...
                    "spaceGroup",string(item.spaceGroup), ...
                    "lattice",lattice.matrix,"species","Si", ...
                    "fractionalCoordinates",[.137,.246,.359], ...
                    "collisionTolerance",1e-4));
                testCase.verifyEqual(result.model.num_sites, ...
                    item.atomCount,"Oracle case "+string(item.spaceGroup));
                testCase.verifyEqual(result.analysis.detectedNumber, ...
                    item.detectedNumber, ...
                    "Oracle case "+string(item.spaceGroup));
                testCase.verifyEqual( ...
                    kssolv.modeling.provenance.CanonicalHash.of(result.model), ...
                    string(item.hash), ...
                    "Oracle case "+string(item.spaceGroup));
            end
        end
    end
end
