classdef ModelingFunctionalTestUtils
    %MODELINGFUNCTIONALTESTUTILS Shared fixtures and structural assertions.

    methods (Static)
        function result = execute(testCase, model, commandId, parameters)
            if nargin < 4
                parameters = struct();
            end
            originalCoordinates = model.cart_coords;
            originalLattice = model.lattice.matrix;
            originalSpecies = model.species_and_occu;
            result = [];
            testCase.verifyWarningFree(@invoke);
            testCase.assertNotEmpty(result, ...
                "Command did not return a result.");
            testCase.verifyEqual(model.cart_coords, ...
                originalCoordinates, ...
                "Command mutated its input coordinates.", ...
                AbsTol = 1e-12);
            testCase.verifyEqual(model.lattice.matrix, ...
                originalLattice, ...
                "Command mutated its input lattice.", ...
                AbsTol = 1e-12);
            testCase.verifyEqual(model.species_and_occu, originalSpecies, ...
                "Command mutated its input species.");
            kssolv.modeling.test.ModelingFunctionalTestUtils. ...
                verifyStructure(testCase, result.model);

            function invoke()
                result = ...
                    kssolv.modeling.CommandExecutor.execute( ...
                    model, commandId, parameters);
            end
        end

        function verifyStructure(testCase, model)
            testCase.verifyTrue(isa(model, ...
                "kssolv.analysis.matgenlab.core.IStructure"), ...
                "Result must be a matgenlab periodic structure.");
            testCase.verifyGreaterThan(model.num_sites, 0);
            testCase.verifySize(model.cart_coords, [model.num_sites, 3]);
            testCase.verifyTrue(all(isfinite(model.cart_coords), "all"));
            testCase.verifyTrue(all(isfinite(model.lattice.matrix), "all"));
            testCase.verifyGreaterThan(abs(det(model.lattice.matrix)), 1e-10);
            testCase.verifySize(model.pbc, [1, 3]);
            names = fieldnames(model.site_properties);
            for index = 1:numel(names)
                values = model.site_properties.(names{index});
                if isvector(values)
                    count = numel(values);
                else
                    count = size(values, 1);
                end
                testCase.verifyEqual(count, model.num_sites, ...
                    "Site property '" + names{index} + ...
                    "' has the wrong number of values.");
            end
            if model.num_sites > 1
                distances = model.distance_matrix;
                distances(1:model.num_sites + 1:end) = Inf;
                testCase.verifyGreaterThan(min(distances, [], "all"), ...
                    1e-5, "Output contains coincident periodic sites.");
            end
        end

        function value = baseStructure()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                diag([5, 6, 7]), {"Si", "O"}, ...
                [0.10, 0.15, 0.20; 0.60, 0.65, 0.70]);
        end

        function value = duplicateStructure()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 8, {"Si", "Si", "O"}, ...
                [0.10, 0.10, 0.10; ...
                0.1001, 0.10, 0.10; 0.70, 0.70, 0.70]);
        end

        function value = graphene()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice. ...
                hexagonal(2.46, 15), ...
                {"C", "C"}, [0, 0, .5; 1/3, 2/3, .5]);
        end

        function value = simpleCubic()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 3, {"Si"}, [0, 0, 0]);
        end

        function value = simpleCubicSlab()
            value = kssolv.analysis.matgenlab.core.Structure( ...
                diag([2, 2, 12]), {"Si", "Si", "Si"}, ...
                [0, 0, 4/12; 0, 0, 6/12; 0, 0, 8/12]);
        end

        function value = surfaceSlab()
            transformation = ...
                kssolv.analysis.matgenlab.transformations. ...
                SlabTransformation([0, 0, 1], 6, 8, ...
                false, true, false, false);
            value = transformation.apply_transformation( ...
                kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.simpleCubic());
        end

        function [initial, ending] = nebEndpoints()
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                eye(3) * 10, [false, false, false]);
            initial = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"H", "H"}, ...
                [0.2, 0.5, 0.5; 0.8, 0.5, 0.5]);
            ending = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, {"H", "H"}, ...
                [0.8, 0.5, 0.5; 0.2, 0.5, 0.5]);
        end

        function result = fakePackmol(request)
            contents = sprintf([ ...
                '3\nfunctional Packmol adapter\n' ...
                'Si 1 1 2\nHe 0.5 0.5 6\nHe 1.5 1.5 7\n']);
            fileId = fopen(fullfile(request.working_directory, ...
                request.outputfile), "w");
            if fileId < 0
                error("KSSOLV:Test:PackmolOutput", ...
                    "Unable to create fake Packmol output.");
            end
            cleanup = onCleanup(@()fclose(fileId));
            fwrite(fileId, contents, "char");
            clear cleanup
            result = struct( ...
                "status", 0, ...
                "stdout", "PACKMOL success" + newline, ...
                "stderr", "", "timed_out", false);
        end
    end
end
