classdef MolecularMechanicsForceFieldTest < matlab.unittest.TestCase
    %MOLECULARMECHANICSFORCEFIELDTEST Energy, gradient, and optimizer gates.

    methods (Test)
        function analyticGradientMatchesFiniteDifference(testCase)
            molecule = testCase.molecule([0,0,0;1.9,0.2,0], [1,2,1]);
            coordinates = molecule.cart_coords;
            state = kssolv.modeling.forcefield. ...
                MolecularMechanicsForceField.evaluate(molecule, coordinates);
            numerical = testCase.finiteDifference(molecule, coordinates);
            testCase.verifyEqual(state.gradient, numerical, ...
                "AbsTol", 2e-5);
            testCase.verifyTrue(state.isEnergyModel);
            testCase.verifyEqual(state.parameterSet, ...
                "kssolv-generic-mm-v2");
            testCase.verifyEqual(state.parameterSchemaVersion, 2);
        end

        function angleAndRepulsionGradientsAreAnalytic(testCase)
            angled = testCase.molecule( ...
                [0,0,0;1.54,0,0;2.1,1.1,0.2], ...
                [1,2,1;2,3,1]);
            state = kssolv.modeling.forcefield. ...
                MolecularMechanicsForceField.evaluate(angled);
            numerical = testCase.finiteDifference( ...
                angled, angled.cart_coords);
            testCase.verifyEqual(state.gradient, numerical, ...
                "AbsTol", 3e-5);

            clashing = testCase.molecule([0,0,0;0.5,0.1,0], zeros(0,3));
            state = kssolv.modeling.forcefield. ...
                MolecularMechanicsForceField.evaluate(clashing);
            numerical = testCase.finiteDifference( ...
                clashing, clashing.cart_coords);
            testCase.verifyEqual(state.gradient, numerical, ...
                "AbsTol", 3e-5);
            testCase.verifyEqual(state.termCount.repulsion, 1);
        end

        function torsionGradientAndProvenanceAreReported(testCase)
            molecule = testCase.molecule( ...
                [0,0,0;1.53,0,0;2.1,1.35,0.1;3.2,1.7,1.0], ...
                [1,2,1;2,3,1;3,4,1]);
            state = kssolv.modeling.forcefield. ...
                MolecularMechanicsForceField.evaluate(molecule);
            numerical = testCase.finiteDifference( ...
                molecule, molecule.cart_coords);

            testCase.verifyEqual(state.gradient, numerical, ...
                "AbsTol", 3e-4);
            testCase.verifyEqual(state.termCount.torsion, 1);
            testCase.verifyGreaterThanOrEqual(state.termEnergy.torsion, 0);
            testCase.verifyEqual(state.parameterCount.atom, 4);
            testCase.verifyEqual(state.parameterCount.torsion, 1);
            testCase.verifyEqual(state.fallbackByKind.torsion, 0);
            testCase.verifyEqual(state.parameterSource, ...
                "kssolv-generic-mm-parameters-v2");
        end

        function optimizerLowersEnergyAndPreservesFixedAtoms(testCase)
            molecule = testCase.molecule([0,0,0;2.1,0,0], [1,2,1]);
            initial = molecule.cart_coords;
            [optimized, analysis] = kssolv.modeling.forcefield. ...
                GeometryOptimizer.optimize(molecule, ...
                MaximumIterations = 250, ForceTolerance = 1e-4, ...
                FixedIndices = 1);
            parameter = kssolv.modeling.forcefield. ...
                GeometryParameterProvider.bond("C", "C", 1);
            distance = norm(optimized(1).coords - optimized(2).coords);
            testCase.verifyLessThan(analysis.finalEnergy, ...
                analysis.initialEnergy);
            testCase.verifyTrue(analysis.converged, analysis.reason);
            testCase.verifyLessThanOrEqual(analysis.maximumForce, 1e-4);
            testCase.verifyEqual(optimized(1).coords, initial(1, :), ...
                "AbsTol", 1e-12);
            testCase.verifyEqual(distance, parameter.value, ...
                "AbsTol", 1e-6);
            testCase.verifyEqual(molecule.cart_coords, initial);
        end

        function commandReportsNonConvergenceWithoutClaimingSuccess(testCase)
            molecule = testCase.molecule([0,0,0;2.1,0,0], [1,2,1]);
            result = kssolv.modeling.CommandExecutor.execute(molecule, ...
                "optimize_geometry", struct("maximumIterations", 1, ...
                "forceTolerance", 1e-12, "fixedIndices", 1));
            testCase.verifyFalse(result.analysis.converged);
            testCase.verifyEqual(result.analysis.reason, ...
                "maximum-iterations");
            testCase.verifyTrue(result.analysis.isEnergyMinimization);
            testCase.verifyTrue(contains(result.message, ...
                "without convergence"));
        end

        function cancellationReturnsOriginalCoordinates(testCase)
            molecule = testCase.molecule([0,0,0;2.1,0,0], [1,2,1]);
            [cancelled, analysis] = kssolv.modeling.forcefield. ...
                GeometryOptimizer.optimize(molecule, ...
                CancelFcn = @()true);
            testCase.verifyEqual(cancelled.cart_coords, molecule.cart_coords, ...
                "AbsTol", 1e-12);
            testCase.verifyFalse(analysis.converged);
            testCase.verifyEqual(analysis.reason, "cancelled");
            testCase.verifyEqual(analysis.iterations, 0);
        end

        function optimizerAcceptsValidatedPluggableForceField(testCase)
            molecule = testCase.molecule( ...
                [1,0,0;2,0,0], zeros(0, 3));
            [optimized, analysis] = kssolv.modeling.forcefield. ...
                GeometryOptimizer.optimize(molecule, ...
                MaximumIterations = 100, ForceTolerance = 1e-4, ...
                FixedIndices = 1, ...
                ForceFieldEvaluator = @quadraticForceField);

            testCase.verifyTrue(analysis.converged, analysis.reason);
            testCase.verifyEqual(analysis.forceField, ...
                "qa-quadratic-energy-v1");
            testCase.verifyEqual(optimized(1).coords, [1,0,0], ...
                "AbsTol", 1e-12);
            testCase.verifyEqual(optimized(2).coords, [0,0,0], ...
                "AbsTol", 1e-4);
        end

        function providerRejectsIncompleteEvaluatorContract(testCase)
            molecule = testCase.molecule([0,0,0], zeros(0, 3));
            testCase.verifyError(@() ...
                kssolv.modeling.forcefield.ForceFieldProvider.evaluate( ...
                molecule, molecule.cart_coords, @(~,~)struct( ...
                "energy", 0, "gradient", zeros(1, 3))), ...
                "KSSOLV:Modeling:ForceFieldContract");
        end
    end

    methods (Access = private)
        function value = molecule(~, coordinates, bonds)
            properties = struct("topology", struct("bonds", bonds, ...
                "origin", "source", "schemaVersion", 1));
            value = kssolv.analysis.matgenlab.core.Molecule( ...
                repmat("C", 1, size(coordinates, 1)), coordinates, ...
                charge_spin_check = false, ...
                properties = properties);
        end


        function numerical = finiteDifference(~, molecule, coordinates)
            numerical = zeros(size(coordinates));
            step = 1e-6;
            for row = 1:size(coordinates, 1)
                for column = 1:3
                    plus = coordinates; minus = coordinates;
                    plus(row, column) = plus(row, column) + step;
                    minus(row, column) = minus(row, column) - step;
                    plusState = kssolv.modeling.forcefield. ...
                        MolecularMechanicsForceField.evaluate(molecule, plus);
                    minusState = kssolv.modeling.forcefield. ...
                        MolecularMechanicsForceField.evaluate(molecule, minus);
                    numerical(row, column) = ...
                        (plusState.energy - minusState.energy) / (2 * step);
                end
            end
        end
    end
end

function state = quadraticForceField(~, coordinates)
state = struct( ...
    "parameterSet", "qa-quadratic-energy-v1", ...
    "source", "frozen analytic QA oracle", ...
    "isEnergyModel", true, ...
    "energy", sum(coordinates.^2, "all"), ...
    "energyUnit", "kJ/mol", ...
    "gradient", 2 * coordinates, ...
    "gradientUnit", "kJ/(mol angstrom)", ...
    "fallbackCount", 0, ...
    "termEnergy", struct("quadratic", sum(coordinates.^2, "all")), ...
    "termCount", struct("quadratic", numel(coordinates)), ...
    "limitations", "QA oracle only");
end
