classdef NanoSurfaceFunctionalTest < matlab.unittest.TestCase
    %NANOSURFACEFUNCTIONALTEST Execute nano/surface/interface commands.

    properties (TestParameter)
        NanoCommand = { ...
            "roll_nanotube", "cut_nanoribbon", ...
            "cut_nanowire", "quantum_dot_void"}
        SurfaceCommand = { ...
            "build_slab", "add_vacuum", "insert_structure", ...
            "stack_heterostructure", "twist_moire", ...
            "interpolate_neb", "find_adsorption_sites", ...
            "locate_adsorbate", "place_adsorbate", ...
            "passivate_surface", "add_solvent_layer"}
    end

    methods (Test)
        function nanostructureCommandIsFunctional(testCase, NanoCommand)
            commandId = string(NanoCommand);
            [model, parameters] = testCase.nanoCase(commandId);
            result = ...
                kssolv.modeling.test.ModelingFunctionalTestUtils. ...
                execute(testCase, model, commandId, parameters);
            testCase.verifyTrue(result.changed);
            testCase.verifyNanoResult(commandId, model, result.model);
        end

        function surfaceBuilderEnumeratesTerminationsAndFixesLayers(testCase)
            bulk=kssolv.analysis.matgenlab.core.Structure. ...
                from_spacegroup("Fm-3m",eye(3)*3.92,"Pt",[0,0,0]);
            result=kssolv.modeling.CommandExecutor.execute(bulk, ...
                "build_slab",struct("millerIndex",[1,1,1], ...
                "slabSize",8,"vacuumSize",10,"centerSlab",true, ...
                "primitive",true,"terminationIndex",1));
            testCase.verifyGreaterThanOrEqual( ...
                numel(result.analysis.terminations),1);
            testCase.verifyEqual( ...
                result.model.properties.surface.terminationIndex,1);
            testCase.verifyTrue(isfield(result.model.site_properties, ...
                "surface_layer"));
            candidates=kssolv.ui.features.modeling. ...
                AnalysisResultPresenter.surfaceTerminationTable(result);
            testCase.verifyEqual(height(candidates), ...
                numel(result.analysis.terminations));
            fixed=kssolv.modeling.CommandExecutor.execute(result.model, ...
                "fix_atoms",struct("indices",1,"bottomLayerCount",1));
            layers=fixed.model.site_properties.surface_layer;
            if iscell(layers), layers=cell2mat(layers); end
            flags=fixed.model.site_properties.surface_fixed;
            if iscell(flags), flags=cell2mat(flags); end
            testCase.verifyEqual(logical(flags),double(layers)==1);
        end

        function interactiveAdsorbateProtocolAcceptsGenericCarboxyl(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            anchor = 1;
            carbon = host.cart_coords(anchor, :) + [0, 0, 2];
            coordinates = [carbon; carbon + [1.23,0,0]; ...
                carbon + [-.65,1.12,0]; carbon + [-1.1,1.9,0]];
            bonds = [1,2,2;1,3,1;3,4,1];
            result = kssolv.modeling.CommandExecutor.execute(host, ...
                "place_adsorbate", struct("anchorSites", anchor, ...
                "adsorbateName", "Carboxyl", ...
                "adsorbateSpecies", ["C","O","O","H"], ...
                "adsorbateCoordinates", coordinates, ...
                "adsorbateBonds", bonds, "anchorAtomIndices", 1, ...
                "minimumDistance", .35));
            testCase.verifyEqual(result.model.num_sites, host.num_sites + 4);
            metadata = result.model.structure_properties.adsorbate;
            testCase.verifyEqual(metadata.schemaVersion, 2);
            testCase.verifyEqual(metadata.name, "Carboxyl");
            testCase.verifyEqual(metadata.species, ["C","O","O","H"]);
            testCase.verifyEqual(metadata.bonds, bonds);
            testCase.verifyEqual(metadata.placementMode, "direct-manipulation");
            testCase.verifyEqual(metadata.hostAnchorSites, anchor);
            testCase.verifyEqual(metadata.anchorAtomIndices, 1);
            testCase.verifyEqual(metadata.hostBondLengths, 2, ...
                "AbsTol", 1e-12);
            testCase.verifyEqual(sort(string(fieldnames(metadata))), ...
                sort(["schemaVersion"; "placementMode"; "name"; ...
                "species"; "coordinates"; "bonds"; ...
                "anchorAtomIndices"; "hostAnchorSites"; ...
                "hostAnchorLabels"; "hostBondLengths"; "guestFormula"]));
        end

        function threeRequiredSlabsMatchFrozenOracle(testCase)
            path=fullfile(KSSOLV_Toolbox.RootDirectory,"dev","modeling", ...
                "acceptance","oracles","surface-builder-v1.json");
            oracle=jsondecode(fileread(path));
            testCase.verifyEqual(numel(oracle.cases),3);
            for index=1:numel(oracle.cases)
                item=oracle.cases(index);
                species=cellstr(string(item.species));
                if isscalar(species), species=species{1}; end
                bulk=kssolv.analysis.matgenlab.core.Structure. ...
                    from_prototype(string(item.prototype),species, ...
                    "a",item.a);
                result=kssolv.modeling.CommandExecutor.execute(bulk, ...
                    "build_slab",struct("millerIndex",item.miller, ...
                    "slabSize",item.slabSize, ...
                    "vacuumSize",item.vacuumSize, ...
                    "centerSlab",true,"primitive",true, ...
                    "terminationIndex",1));
                context="Oracle case "+string(item.name);
                testCase.verifyEqual(result.model.num_sites, ...
                    item.atomCount,context);
                testCase.verifyEqual(string(result.model.reduced_formula), ...
                    string(item.formula),context);
                testCase.verifyEqual(numel(result.analysis.terminations), ...
                    item.terminationCount,context);
                testCase.verifyEqual(result.model.lattice.c,item.c, ...
                    AbsTol=1e-10);
                testCase.verifyEqual( ...
                    kssolv.modeling.provenance.CanonicalHash.of(result.model), ...
                    string(item.hash),context);
            end
        end

        function surfaceCommandIsFunctional(testCase, SurfaceCommand)
            commandId = string(SurfaceCommand);
            [model, parameters] = testCase.surfaceCase(commandId);
            result = ...
                kssolv.modeling.test.ModelingFunctionalTestUtils. ...
                execute(testCase, model, commandId, parameters);
            testCase.verifySurfaceResult( ...
                commandId, model, result, parameters);
        end

        function genericOxygenHydrogenFragmentPreservesDraggedGeometry(testCase)
            model=kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            anchorSite=1;
            normal=model.lattice.matrix(3,:);
            normal=normal/norm(normal);
            oxygen=model.cart_coords(anchorSite,:)+2.05*normal;
            tangent=model.lattice.matrix(1,:);
            tangent=tangent/norm(tangent);
            direction=.8*normal+.6*tangent;
            direction=direction/norm(direction);
            hydrogen=oxygen+.96*direction;
            result=kssolv.modeling.CommandExecutor.execute(model, ...
                "place_adsorbate",struct("anchorSites",anchorSite, ...
                "adsorbateName","O-H fragment", ...
                "adsorbateSpecies",["O","H"], ...
                "adsorbateCoordinates",[oxygen;hydrogen], ...
                "adsorbateBonds",[1,2,1], ...
                "anchorAtomIndices",1, ...
                "minimumDistance",.1));
            testCase.verifyTrue(result.changed);
            testCase.verifyEqual(result.model.num_sites,model.num_sites+2);
            testCase.verifyEqual(result.model.cart_coords(end-1,:), ...
                oxygen,AbsTol=1e-12);
            testCase.verifyEqual(result.model.cart_coords(end,:), ...
                hydrogen,AbsTol=1e-12);
            metadata=result.model.properties.adsorbate;
            testCase.verifyEqual(metadata.schemaVersion,2);
            testCase.verifyEqual(metadata.placementMode,"direct-manipulation");
            testCase.verifyEqual(metadata.name,"O-H fragment");
            testCase.verifyEqual(metadata.species,["O","H"]);
            testCase.verifyEqual(metadata.bonds,[1,2,1]);
            testCase.verifyEqual(metadata.hostAnchorSites,anchorSite);
            testCase.verifyEqual(metadata.hostBondLengths,2.05, ...
                AbsTol=1e-12);
            testCase.verifyEqual(norm(metadata.coordinates(2,:) - ...
                metadata.coordinates(1,:)),.96, ...
                AbsTol=1e-12);
            testCase.verifyEqual(sort(string(fieldnames(metadata))), ...
                sort(["schemaVersion"; "placementMode"; "name"; ...
                "species"; "coordinates"; "bonds"; ...
                "anchorAtomIndices"; "hostAnchorSites"; ...
                "hostAnchorLabels"; "hostBondLengths"; "guestFormula"]));
        end

        function interfaceSearchEnumeratesAndAppliesRotation(testCase)
            bottom = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.graphene();
            rotated=kssolv.modeling.LatticeEditorCommands.execute( ...
                bottom,"rotate_lattice",struct("axis",[0,0,1], ...
                "angleDegrees",10));
            top=rotated.model;
            candidates = kssolv.modeling.builders. ...
                InterfaceCandidateBuilder.enumerate(bottom, top, ...
                maximumRepeat = 1, maximumCandidates = 1, ...
                maximumRotation = 15, rotationStep = 5);
            testCase.verifyEqual(abs(candidates.rotationDegrees),10, ...
                AbsTol=1e-10);
            result = kssolv.modeling.CommandExecutor.execute(bottom, ...
                "stack_heterostructure", struct("otherModel", top, ...
                "maximumRepeat", 1, "maximumRotation", 15, ...
                "rotationStep", 5, "candidateIndex", 1, ...
                "maximumStrain", .03));
            testCase.verifyEqual(abs( ...
                result.analysis.candidates(1).rotationDegrees),10, ...
                AbsTol=1e-10);
            testCase.verifyEqual(result.model.num_sites, 4);

            matched=kssolv.modeling.builders. ...
                InterfaceCandidateBuilder.enumerate(bottom,bottom, ...
                maximumRepeat=2,maximumCandidates=20, ...
                maximumRotation=30,sortMode="strain");
            nonDiagonal=find(arrayfun(@(item) ...
                item.bottomTransform(1,2)~=0 && isequal( ...
                item.bottomTransform,item.topTransform),matched),1);
            testCase.verifyNotEmpty(nonDiagonal);
            selected=matched(nonDiagonal);
            testCase.verifyEqual(selected.strain,0,AbsTol=1e-12);
            testCase.verifyEqual(selected.atomCount,8);
            matrixResult=kssolv.modeling.CommandExecutor.execute(bottom, ...
                "stack_heterostructure",struct("otherModel",bottom.copy(), ...
                "maximumRepeat",2,"candidateIndex",nonDiagonal, ...
                "maximumStrain",.03));
            testCase.verifyEqual(matrixResult.model.num_sites,8);
            testCase.verifyEqual( ...
                matrixResult.analysis.candidates(nonDiagonal). ...
                bottomTransform,selected.bottomTransform);
        end
    end

    methods (Static, Access = private)
        function [model, parameters] = nanoCase(commandId)
            switch commandId
                case "roll_nanotube"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.graphene();
                    parameters = struct( ...
                        "chiralIndices", [4, 0], ...
                        "length", 2, "vacuum", 6, ...
                        "maximumAtoms", 1000);
                case "cut_nanoribbon"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.graphene();
                    parameters = struct( ...
                        "width", 3, "length", 2, ...
                        "edgeType", "armchair", ...
                        "vacuum", 5, "maximumAtoms", 1000);
                case "cut_nanowire"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubic();
                    parameters = struct( ...
                        "direction", [0, 0, 1], "radius", 3, ...
                        "length", 2, "vacuum", 5, ...
                        "maximumAtoms", 1000);
                case "quantum_dot_void"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubic();
                    parameters = struct( ...
                        "mode", "dot", "radius", 3, ...
                        "vacuum", 5, "maximumAtoms", 1000);
            end
        end

        function [model, parameters] = surfaceCase(commandId)
            switch commandId
                case "build_slab"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubic();
                    parameters = struct( ...
                        "millerIndex", [0, 0, 1], ...
                        "slabSize", 6, "vacuumSize", 8, ...
                        "centerSlab", true, "primitive", false);
                case "add_vacuum"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.surfaceSlab();
                    parameters = struct("amount", 5);
                case "insert_structure"
                    model = kssolv.analysis.matgenlab.core.Structure( ...
                        eye(3) * 10, {"Si"}, [.1, .1, .1]);
                    guest = kssolv.analysis.matgenlab.core.Structure( ...
                        eye(3) * 10, {"He"}, [.7, .7, .7]);
                    parameters = struct( ...
                        "otherModel", guest, ...
                        "translation", [0, 0, 0], ...
                        "minimumDistance", .5);
                case {"stack_heterostructure", "twist_moire"}
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.graphene();
                    parameters = struct( ...
                        "otherModel", model.copy(), ...
                        "gap", 3.35, "vacuum", 12, ...
                        "maximumStrain", .03);
                    if commandId == "twist_moire"
                        parameters.angleDegrees = 21.786789;
                        parameters.maximumAtoms = 1000;
                        parameters.maximumIndex = 8;
                    end
                case "interpolate_neb"
                    [model, ending] = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.nebEndpoints();
                    parameters = struct( ...
                        "endModel", ending, ...
                        "intermediateCount", 5, ...
                        "maximumSteps", 300, ...
                        "forceTolerance", .05);
                case "find_adsorption_sites"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.surfaceSlab();
                    parameters = struct("distance", 2);
                case "locate_adsorbate"
                    model = kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.surfaceSlab();
                    adsorbate = kssolv.analysis.matgenlab.core.Molecule( ...
                        ["O","H"], [0,0,0;0,0,.97], ...
                        charge_spin_check = false);
                    parameters = struct("adsorbateModel", adsorbate, ...
                        "siteTypes", "ontop", "heights", [1.8,2.2], ...
                        "rotationStep", 90, "anchorAtom", 1, ...
                        "orientationAtom", 2, "minimumDistance", .4, ...
                        "maximumCandidates", 20, "seed", 7);
                case "place_adsorbate"
                    model=kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.surfaceSlab();
                    adsorbate=kssolv.analysis.matgenlab.core.Molecule( ...
                        ["O","H"],[0,0,0;0,0,1],charge_spin_check=false);
                    parameters=struct("adsorbateModel",adsorbate, ...
                        "siteType","ontop","siteIndex",1,"height",2, ...
                        "anchorAtom",1,"orientationAtom",2, ...
                        "direction",[0,0,1],"minimumDistance",.1);
                case "passivate_surface"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubicSlab();
                    parameters = struct( ...
                        "species", "H", "bondLength", 1.2, ...
                        "side", "top", "surfaceThickness", .2, ...
                        "targetCoordination", 14, ...
                        "minimumDistance", .6);
                case "add_solvent_layer"
                    model = kssolv.analysis.matgenlab.core.Structure( ...
                        diag([4, 4, 12]), {"Si"}, [.25, .25, .25]);
                    solvent = ...
                        kssolv.analysis.matgenlab.core.Molecule( ...
                        "He", [0, 0, 0]);
                    parameters = struct( ...
                        "solventModel", solvent, ...
                        "moleculeCount", 2, ...
                        "layerThickness", 5, "clearance", 1, ...
                        "vacuum", 4, "tolerance", 1.5, ...
                        "seed", 3, "timeout", 5, ...
                        "executor", ...
                        @kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.fakePackmol);
            end
        end

        function verifyNanoResult(commandId, input, output)
            switch commandId
                case "roll_nanotube"
                    assert(output.num_sites == 32);
                    assert(isequal(output.pbc, [false, false, true]));
                    radii = hypot( ...
                        output.cart_coords(:, 1) - output.lattice.a / 2, ...
                        output.cart_coords(:, 2) - output.lattice.b / 2);
                    assert(max(radii) - min(radii) < 1e-9);
                case "cut_nanoribbon"
                    assert(isequal(output.pbc, [false, true, false]));
                case "cut_nanowire"
                    assert(isequal(output.pbc, [false, false, true]));
                case "quantum_dot_void"
                    assert(~any(output.pbc));
                    assert(output.num_sites > input.num_sites);
            end
        end

        function verifySurfaceResult(commandId, input, result, parameters)
            switch commandId
                case "build_slab"
                    assert(result.changed);
                    assert(result.model.lattice.c > parameters.slabSize);
                case "add_vacuum"
                    assert(result.changed);
                    assert(result.model.lattice.c > input.lattice.c);
                case "insert_structure"
                    assert(result.model.num_sites == ...
                        input.num_sites + parameters.otherModel.num_sites);
                case "stack_heterostructure"
                    assert(result.model.num_sites == 4);
                    assert(isequal(result.model.pbc, [true, true, false]));
                    assert(issorted([result.analysis.candidates.strain]));
                    candidates=kssolv.ui.features.modeling. ...
                        AnalysisResultPresenter.interfaceCandidateTable(result);
                    assert(height(candidates)>=1);
                    assert(all(ismember(["Area","Strain", ...
                        "RotationDegrees","AtomCount"], ...
                        string(candidates.Properties.VariableNames))));
                case "twist_moire"
                    assert(result.model.num_sites == 28);
                    assert(result.model.properties.moire. ...
                        angle_error_degrees < 1e-5);
                case "interpolate_neb"
                    assert(~result.changed);
                    assert(numel(result.models) == 7);
                    assert(result.data.final_energy < ...
                        result.data.linear_path_energy);
                case "find_adsorption_sites"
                    assert(~result.changed);
                    assert(isstruct(result.data));
                    assert(sum(structfun(@(values) ...
                        size(values, 1), result.data)) > 0);
                case "locate_adsorbate"
                    assert(~result.changed);
                    assert(result.analysis.candidateCount > 0);
                    assert(~result.analysis.isEnergyModel);
                    candidates = kssolv.ui.features.modeling. ...
                        AnalysisResultPresenter.adsorptionCandidateTable(result);
                    assert(height(candidates) == ...
                        result.analysis.candidateCount);
                    assert(ismember("Score", ...
                        string(candidates.Properties.VariableNames)));
                case "place_adsorbate"
                    assert(result.changed);
                    assert(result.model.num_sites==input.num_sites+2);
                    metadata = result.model.properties.adsorbate;
                    assert(metadata.schemaVersion == 2);
                    assert(metadata.placementMode == "catalog-site");
                    assert(abs(metadata.siteDescriptor.offset-2)<1e-12);
                    assert(isequal(metadata.species, ["O", "H"]));
                    assert(isequal(sort(string(fieldnames(metadata))), ...
                        sort(["schemaVersion"; "placementMode"; "name"; ...
                        "species"; "coordinates"; "bonds"; ...
                        "anchorAtomIndices"; "guestFormula"; ...
                        "siteDescriptor"; "orientationDescriptor"])));
                case "passivate_surface"
                    assert(result.model.num_sites == input.num_sites + 1);
                    parent = result.model.site_properties. ...
                        passivation_parent{end};
                    assert(abs(norm(result.model.cart_coords(end, :) - ...
                        input.cart_coords(parent, :)) - ...
                        parameters.bondLength) < 1e-10);
                case "add_solvent_layer"
                    assert(result.model.num_sites == 3);
                    assert(isequal(result.model.pbc, ...
                        [true, true, false]));
            end
        end
    end
end
