classdef NanoSurfaceFunctionalTest < matlab.unittest.TestCase
    %NANOSURFACEFUNCTIONALTEST Execute nano/surface/interface commands.

    properties (TestParameter)
        NanoCommand = { ...
            "roll_nanotube", "cut_nanoribbon", ...
            "cut_nanowire", "quantum_dot_void"}
        SurfaceCommand = { ...
            "build_slab", "add_vacuum", "insert_structure", ...
            "stack_heterostructure", "twist_moire", ...
            "interpolate_neb", "find_adsorption_sites", ...
            "passivate_surface", "add_solvent_layer"}
    end

    methods (Test)
        function nanostructureCommandIsFunctional(testCase, NanoCommand)
            commandId = string(NanoCommand);
            [model, parameters] = testCase.nanoCase(commandId);
            result = ...
                kssolv.modeling.test.ModelingFunctionalTestUtils. ...
                execute(testCase, model, commandId, parameters);
            testCase.verifyTrue(result.changed);
            testCase.verifyNanoResult(commandId, model, result.model);
        end

        function surfaceCommandIsFunctional(testCase, SurfaceCommand)
            commandId = string(SurfaceCommand);
            [model, parameters] = testCase.surfaceCase(commandId);
            result = ...
                kssolv.modeling.test.ModelingFunctionalTestUtils. ...
                execute(testCase, model, commandId, parameters);
            testCase.verifySurfaceResult( ...
                commandId, model, result, parameters);
        end
    end

    methods (Static, Access = private)
        function [model, parameters] = nanoCase(commandId)
            switch commandId
                case "roll_nanotube"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.graphene();
                    parameters = struct( ...
                        "chiralIndices", [4, 0], ...
                        "length", 2, "vacuum", 6, ...
                        "maximumAtoms", 1000);
                case "cut_nanoribbon"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.graphene();
                    parameters = struct( ...
                        "width", 3, "length", 2, ...
                        "edgeType", "armchair", ...
                        "vacuum", 5, "maximumAtoms", 1000);
                case "cut_nanowire"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubic();
                    parameters = struct( ...
                        "direction", [0, 0, 1], "radius", 3, ...
                        "length", 2, "vacuum", 5, ...
                        "maximumAtoms", 1000);
                case "quantum_dot_void"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubic();
                    parameters = struct( ...
                        "mode", "dot", "radius", 3, ...
                        "vacuum", 5, "maximumAtoms", 1000);
            end
        end

        function [model, parameters] = surfaceCase(commandId)
            switch commandId
                case "build_slab"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubic();
                    parameters = struct( ...
                        "millerIndex", [0, 0, 1], ...
                        "slabSize", 6, "vacuumSize", 8, ...
                        "centerSlab", true, "primitive", false);
                case "add_vacuum"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.surfaceSlab();
                    parameters = struct("amount", 5);
                case "insert_structure"
                    model = kssolv.analysis.matgenlab.core.Structure( ...
                        eye(3) * 10, {"Si"}, [.1, .1, .1]);
                    guest = kssolv.analysis.matgenlab.core.Structure( ...
                        eye(3) * 10, {"He"}, [.7, .7, .7]);
                    parameters = struct( ...
                        "otherModel", guest, ...
                        "translation", [0, 0, 0], ...
                        "minimumDistance", .5);
                case {"stack_heterostructure", "twist_moire"}
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.graphene();
                    parameters = struct( ...
                        "otherModel", model.copy(), ...
                        "gap", 3.35, "vacuum", 12, ...
                        "maximumStrain", .03);
                    if commandId == "twist_moire"
                        parameters.angleDegrees = 21.786789;
                        parameters.maximumAtoms = 1000;
                        parameters.maximumIndex = 8;
                    end
                case "interpolate_neb"
                    [model, ending] = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.nebEndpoints();
                    parameters = struct( ...
                        "endModel", ending, ...
                        "intermediateCount", 5, ...
                        "maximumSteps", 300, ...
                        "forceTolerance", .05);
                case "find_adsorption_sites"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.surfaceSlab();
                    parameters = struct("distance", 2);
                case "passivate_surface"
                    model = ...
                        kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.simpleCubicSlab();
                    parameters = struct( ...
                        "species", "H", "bondLength", 1.2, ...
                        "side", "top", "surfaceThickness", .2, ...
                        "targetCoordination", 14, ...
                        "minimumDistance", .6);
                case "add_solvent_layer"
                    model = kssolv.analysis.matgenlab.core.Structure( ...
                        diag([4, 4, 12]), {"Si"}, [.25, .25, .25]);
                    solvent = ...
                        kssolv.analysis.matgenlab.core.Molecule( ...
                        "He", [0, 0, 0]);
                    parameters = struct( ...
                        "solventModel", solvent, ...
                        "moleculeCount", 2, ...
                        "layerThickness", 5, "clearance", 1, ...
                        "vacuum", 4, "tolerance", 1.5, ...
                        "seed", 3, "timeout", 5, ...
                        "executor", ...
                        @kssolv.modeling.test. ...
                        ModelingFunctionalTestUtils.fakePackmol);
            end
        end

        function verifyNanoResult(commandId, input, output)
            switch commandId
                case "roll_nanotube"
                    assert(output.num_sites == 32);
                    assert(isequal(output.pbc, [false, false, true]));
                    radii = hypot( ...
                        output.cart_coords(:, 1) - output.lattice.a / 2, ...
                        output.cart_coords(:, 2) - output.lattice.b / 2);
                    assert(max(radii) - min(radii) < 1e-9);
                case "cut_nanoribbon"
                    assert(isequal(output.pbc, [false, true, false]));
                case "cut_nanowire"
                    assert(isequal(output.pbc, [false, false, true]));
                case "quantum_dot_void"
                    assert(~any(output.pbc));
                    assert(output.num_sites > input.num_sites);
            end
        end

        function verifySurfaceResult(commandId, input, result, parameters)
            switch commandId
                case "build_slab"
                    assert(result.changed);
                    assert(result.model.lattice.c > parameters.slabSize);
                case "add_vacuum"
                    assert(result.changed);
                    assert(result.model.lattice.c > input.lattice.c);
                case "insert_structure"
                    assert(result.model.num_sites == ...
                        input.num_sites + parameters.otherModel.num_sites);
                case "stack_heterostructure"
                    assert(result.model.num_sites == 4);
                    assert(isequal(result.model.pbc, [true, true, false]));
                case "twist_moire"
                    assert(result.model.num_sites == 28);
                    assert(result.model.properties.moire. ...
                        angle_error_degrees < 1e-5);
                case "interpolate_neb"
                    assert(~result.changed);
                    assert(numel(result.models) == 7);
                    assert(result.data.final_energy < ...
                        result.data.linear_path_energy);
                case "find_adsorption_sites"
                    assert(~result.changed);
                    assert(isstruct(result.data));
                    assert(sum(structfun(@(values) ...
                        size(values, 1), result.data)) > 0);
                case "passivate_surface"
                    assert(result.model.num_sites == input.num_sites + 1);
                    parent = result.model.site_properties. ...
                        passivation_parent{end};
                    assert(abs(norm(result.model.cart_coords(end, :) - ...
                        input.cart_coords(parent, :)) - ...
                        parameters.bondLength) < 1e-10);
                case "add_solvent_layer"
                    assert(result.model.num_sites == 3);
                    assert(isequal(result.model.pbc, ...
                        [true, true, false]));
            end
        end
    end
end
