classdef PolymerPackingFunctionalTest < matlab.unittest.TestCase
    methods (Test)
        function builtInPolymersHaveExactCompositionAndState(testCase)
            base=blank();
            for kind=["PE","PP","PS","PEO"]
                result=kssolv.modeling.CommandExecutor.execute(base, ...
                    "build_homopolymer",struct("repeatUnit",kind, ...
                    "repeatCount",5,"seed",17));
                testCase.verifyEqual(result.analysis.repeatUnits,5);
                testCase.verifyEqual(result.analysis.actualCounts,5);
                testCase.verifyEqual(result.analysis.state, ...
                    "constructed_not_equilibrated");
                report=kssolv.modeling.chemistry.MoleculeDiagnostics. ...
                    inspect(result.model);
                testCase.verifyEmpty(report.collisions);
                testCase.verifyFalse(any(string({report.atomIssues.severity})=="error"));
            end
        end

        function userRepeatUnitStoresHeadsTailsAndLeavingAtoms(testCase)
            storePath=string(tempname)+" repeat unit's store.json";
            cleanup=onCleanup(@()deleteIfPresent(storePath)); %#ok<NASGU>
            unit=molecule(["C","C","H"], ...
                [0,0,0;1.5,0,0;2.5,0,0],[1,2,1;2,3,1]);
            saved=kssolv.modeling.CommandExecutor.execute(unit, ...
                "save_user_repeat_unit",struct( ...
                "repeatUnitName","USER_CC","headIndex",1, ...
                "tailIndex",2,"leavingIndices",3, ...
                "storePath",storePath));
            testCase.verifyFalse(saved.changed);
            entry=kssolv.modeling.polymers.RepeatUnitLibrary.get( ...
                "USER_CC",storePath=storePath);
            testCase.verifyEqual(entry.species,["C","C"]);
            testCase.verifyEqual(entry.head,1);
            testCase.verifyEqual(entry.tail,2);
            testCase.verifyEmpty(dir(storePath+".*.tmp"));
            polymer=kssolv.modeling.polymers.PolymerBuilder. ...
                homopolymer("USER_CC",4,storePath=storePath);
            testCase.verifyEqual(polymer.num_sites,26);
        end

        function blockRandomStereoAndBranchesAreReproducible(testCase)
            base=blank();
            block=execute(base,"build_block_copolymer",struct( ...
                "blockKinds","PEO PPO PEO","blockLengths",[3,4,3], ...
                "seed",8));
            testCase.verifyEqual(block.analysis.actualKinds,["PEO","PPO"]);
            testCase.verifyEqual(block.analysis.actualCounts,[6,4]);
            first=execute(base,"build_random_copolymer",struct( ...
                "monomerKinds","PE PP","fractions",[.3,.7], ...
                "repeatCount",20,"exactComposition",true,"seed",91, ...
                "tacticity","syndiotactic"));
            second=execute(base,"build_random_copolymer",struct( ...
                "monomerKinds","PE PP","fractions",[.3,.7], ...
                "repeatCount",20,"exactComposition",true,"seed",91, ...
                "tacticity","syndiotactic"));
            testCase.verifyEqual(first.analysis.actualCounts,[6,14]);
            testCase.verifyEqual(first.analysis.sequence,second.analysis.sequence);
            stereo=cellfun(@double,first.model.site_properties.stereo);
            repeat=cellfun(@double,first.model.site_properties.repeat_unit);
            signs=arrayfun(@(unit)stereo(find(repeat==unit,1)),1:20);
            testCase.verifyEqual(signs,(-1).^(0:19));
            branched=execute(base,"build_branched_polymer",struct( ...
                "repeatCount",10,"branchInterval",3,"seed",5));
            testCase.verifyEqual(branched.analysis.branchCount,3);
        end

        function architectureControlsHaveExactDeterministicSemantics(testCase)
            [multi,info]=kssolv.modeling.polymers.PolymerBuilder. ...
                homopolymer("PE",4,chainCount=3,headGroup="O-H fragment", ...
                tailGroup="Methyl",conformation="zigzag", ...
                headTailMode="alternating",addHydrogens=false);
            chainIds=cellfun(@double,multi.site_properties.chain_id);
            testCase.verifyEqual(unique(chainIds),1:3);
            testCase.verifyEqual(histcounts(chainIds,.5:1:3.5), ...
                repmat(multi.num_sites/3,1,3));
            testCase.verifyEqual(info.headTailFlipped,[false,true,false,true]);
            testCase.verifyEqual(info.conformation,"zigzag");
            testCase.verifyEqual(info.headGroup,"O-H fragment");
            testCase.verifyEqual(info.tailGroup,"Methyl");

            [block,blockInfo]=kssolv.modeling.polymers.PolymerBuilder. ...
                block(["PE","PP"],[2,1],superunitCount=3, ...
                addHydrogens=false);
            testCase.verifyEqual(blockInfo.repeatUnits,9);
            testCase.verifyEqual(blockInfo.sequence, ...
                repmat(["PE","PE","PP"],1,3));
            testCase.verifyGreaterThan(block.num_sites,0);

            [biased,biasedInfo]=kssolv.modeling.polymers.PolymerBuilder. ...
                random(["PE","PP"],200,[.5,.5],seed=29, ...
                exactComposition=false,reactivityRatios=[12,.08], ...
                addHydrogens=false);
            [repeated,repeatedInfo]=kssolv.modeling.polymers.PolymerBuilder. ...
                random(["PE","PP"],200,[.5,.5],seed=29, ...
                exactComposition=false,reactivityRatios=[12,.08], ...
                addHydrogens=false);
            testCase.verifyEqual(biasedInfo.sequence,repeatedInfo.sequence);
            testCase.verifyGreaterThan(biasedInfo.actualCounts(1),100);
            testCase.verifyEqual( ...
                kssolv.modeling.provenance.CanonicalHash.of(biased), ...
                kssolv.modeling.provenance.CanonicalHash.of(repeated));
        end

        function basicDendrimerHasExactGenerationTopology(testCase)
            [heavy,info]=kssolv.modeling.polymers.PolymerBuilder. ...
                dendrimer(2,coreFunctionality=3,branchingFactor=2, ...
                addHydrogens=false,seed=11);
            testCase.verifyEqual(info.generationCounts,[3,6]);
            testCase.verifyEqual(info.heavyAtomCount,10);
            testCase.verifyEqual(heavy.num_sites,10);
            bonds=kssolv.modeling.chemistry.MoleculeDiagnostics. ...
                topology(heavy);
            testCase.verifySize(bonds,[9,3]);
            generations=cellfun(@double,heavy.site_properties.generation);
            testCase.verifyEqual(histcounts(generations,-.5:1:2.5),[1,3,6]);
            built=execute(blank(),"build_dendrimer",struct( ...
                "generations",2,"coreFunctionality",3, ...
                "branchingFactor",2,"seed",11));
            testCase.verifyEqual(built.analysis.architecture,"basic_dendrimer");
            testCase.verifyEqual(built.model.num_sites,32);
        end

        function polymerPreflightEstimatesCoverEveryArchitecture(testCase)
            cases={
                "build_homopolymer",struct("repeatUnit","PE", ...
                    "repeatCount",10,"chainCount",2, ...
                    "headGroup","O-H fragment","tailGroup","Methyl")
                "build_block_copolymer",struct("blockKinds","PEO PPO", ...
                    "blockLengths",[2,3],"superunitCount",2)
                "build_random_copolymer",struct("monomerKinds","PE PP", ...
                    "repeatCount",12)
                "build_branched_polymer",struct("repeatUnit","PE", ...
                    "repeatCount",12,"branchInterval",3, ...
                    "branchFragment","Methyl")
                "build_dendrimer",struct("generations",3, ...
                    "coreFunctionality",3,"branchingFactor",2)
                };
            for row=1:size(cases,1)
                estimate=kssolv.modeling.polymers.PolymerCommands. ...
                    estimate(cases{row,1},cases{row,2});
                testCase.verifyGreaterThan(estimate.estimatedAtoms,0);
                testCase.verifyFalse(estimate.warning);
            end
            large=kssolv.modeling.polymers.PolymerCommands.estimate( ...
                "build_homopolymer",struct("repeatUnit","PE", ...
                "repeatCount",2000));
            testCase.verifyTrue(large.warning);
            testCase.verifyEmpty(kssolv.modeling.polymers.PolymerCommands. ...
                estimate("unknown",struct()));
            testCase.verifyError(@() ...
                kssolv.modeling.polymers.PolymerCommands.estimate( ...
                "build_block_copolymer",struct("blockKinds","PE PP", ...
                "blockLengths",2)),"KSSOLV:Modeling:PolymerBlocks");
        end

        function densityPackingHasCountsContactsSeedAndWorkflowState(testCase)
            water=molecule(["O","H","H"], ...
                [0,0,0;.9572,0,0;-.239,0.927,0],[1,2,1;1,3,1]);
            ethanol=molecule(["C","C","O"], ...
                [0,0,0;1.52,0,0;2.85,.3,0],[1,2,1;2,3,1]);
            [first,info]=kssolv.modeling.packing.PackingBuilder.pack( ...
                {water,ethanol},[20,10],density=.5,seed=22,tolerance=.65);
            [second,~]=kssolv.modeling.packing.PackingBuilder.pack( ...
                {water,ethanol},[20,10],density=.5,seed=22,tolerance=.65);
            testCase.verifyEqual(first.density,.5,AbsTol=5e-12);
            testCase.verifyEqual(info.counts,[20,10]);
            testCase.verifyEqual(info.state,"packed_not_equilibrated");
            testCase.verifyEqual( ...
                kssolv.modeling.provenance.CanonicalHash.of(first), ...
                kssolv.modeling.provenance.CanonicalHash.of(second));
            ids=cellfun(@double,first.site_properties.molecule_id);
            testCase.verifyGreaterThanOrEqual( ...
                minimumIntermolecularDistance(first.cart_coords,ids, ...
                info.boxLength),.65-1e-12);
        end

        function invalidPackingAndPreflightFailBeforeLargeAllocation(testCase)
            water=molecule(["O","H","H"], ...
                [0,0,0;.9572,0,0;-.239,0.927,0],[1,2,1;1,3,1]);
            testCase.verifyError(@() ...
                kssolv.modeling.packing.PackingBuilder.pack( ...
                {water},100,density=5,tolerance=2), ...
                "KSSOLV:Modeling:PackingInfeasible");
            testCase.verifyError(@() ...
                kssolv.modeling.polymers.PolymerBuilder.homopolymer( ...
                "PE",1000,atomLimit=10),"KSSOLV:Modeling:AtomLimit");
        end

        function compositionModesAndWorkflowTemplatesAreExplicit(testCase)
            water=molecule(["O","H","H"], ...
                [0,0,0;.9572,0,0;-.239,0.927,0],[1,2,1;1,3,1]);
            ethanol=molecule(["C","C","O"], ...
                [0,0,0;1.52,0,0;2.85,.3,0],[1,2,1;2,3,1]);
            mole=kssolv.modeling.packing.CompositionCalculator.counts( ...
                {water,ethanol},[.25,.75],"mole_fraction",20);
            testCase.verifyEqual(mole,[5,15]);
            mass=kssolv.modeling.packing.CompositionCalculator.counts( ...
                {water,ethanol},[.5,.5],"mass_fraction",100);
            testCase.verifyEqual(sum(mass),100);
            testCase.verifyGreaterThan(mass(1),mass(2));
            workflow=kssolv.modeling.packing.PackingWorkflowTemplate. ...
                create("density_ramp_npt");
            testCase.verifyEqual(workflow.inputState, ...
                "packed_not_equilibrated");
            testCase.verifyEqual(workflow.engine,"unassigned");
        end

        function ringPiercingFixtureHasZeroFalseNegatives(testCase)
            angles=(0:5).'*pi/3;
            ring=[cos(angles),sin(angles),zeros(6,1)];
            coordinates=[ring;0,0,-1;0,0,1];
            moleculeIds=[ones(1,6),2,2];
            ringBonds=[(1:6).',[2:6,1].',ones(6,1)];
            bonds=[ringBonds;7,8,1];
            hits=kssolv.modeling.packing.PackingDiagnostics. ...
                ringPiercings(coordinates,moleculeIds,bonds,{1:6});
            testCase.verifyNumElements(hits,1);
            safe=coordinates; safe(7:8,1)=2;
            testCase.verifyEmpty(kssolv.modeling.packing.PackingDiagnostics. ...
                ringPiercings(safe,moleculeIds,bonds,{1:6}));
        end

        function existingBoxExclusionRampAndBatchesAreExplicit(testCase)
            container=kssolv.analysis.matgenlab.core.Structure( ...
                diag([20,20,20]),{"Si"},[10,10,10], ...
                coords_are_cartesian=true, ...
                site_properties=struct("fixed",{{true}}));
            helium=molecule("He",[0,0,0],zeros(0,3));
            progress=zeros(0,2);
            [filled,info]=kssolv.modeling.packing.PackingBuilder.packInto( ...
                container,{helium},4,seed=7,tolerance=.4, ...
                exclusionCenter=[10,10,10],exclusionRadius=4, ...
                batchSize=2,progressFcn=@recordProgress);
            testCase.verifyEqual(filled.num_sites,5);
            testCase.verifyEqual(filled.lattice.matrix,diag([20,20,20]));
            testCase.verifyEqual(filled(1).specie.symbol,"Si");
            testCase.verifyTrue(filled.site_properties.fixed{1});
            testCase.verifyEqual(info.containerAtoms,1);
            testCase.verifyEqual(info.addedAtoms,4);
            testCase.verifyEqual(info.batchCount,2);
            testCase.verifyEqual(progress,[1,4;2,4;3,4;4,4]);
            testCase.verifyGreaterThanOrEqual(min(vecnorm( ...
                filled.cart_coords(2:end,:)-[10,10,10],2,2)),4);

            command=execute(container,"pack_into_existing_box",struct( ...
                "components",{{helium}},"counts",2,"tolerance",.4, ...
                "seed",9,"batchSize",1));
            testCase.verifyTrue(command.analysis.preservedExistingBox);
            testCase.verifyEqual(command.model.num_sites,3);

            [~,ramp]=kssolv.modeling.packing.PackingBuilder.pack( ...
                {helium},6,density=.2,tolerance=.1,seed=3, ...
                densityRamp=[.05,.1,.2],batchSize=2);
            testCase.verifyEqual(ramp.densityRamp,[.05,.1,.2]);
            testCase.verifyEqual(ramp.batchCount,3);
            testCase.verifyEqual(numel(ramp.densityStageVolumes),3);
            function recordProgress(done,total)
                progress(end+1,:)=[done,total]; %#ok<AGROW>
            end
        end

        function linkedRingFixtureIsReportedAsChainInterlock(testCase)
            angles=(0:11).'*2*pi/12;
            first=[cos(angles),sin(angles),zeros(12,1)];
            secondAngles=angles+pi/12;
            second=[.5*ones(12,1),.7*cos(secondAngles), ...
                .7*sin(secondAngles)];
            coordinates=[first;second];
            firstBonds=[(1:12).',[2:12,1].',ones(12,1)];
            secondBonds=[(13:24).',[14:24,13].',ones(12,1)];
            hits=kssolv.modeling.packing.PackingDiagnostics. ...
                chainInterlocks(coordinates,[ones(1,12),2*ones(1,12)], ...
                [firstBonds;secondBonds],{1:12,13:24});
            testCase.verifyNotEmpty(hits);
            testCase.verifyEqual(hits(1).molecules,[1,2]);
        end

        function packingCancellationLeavesNoPartialModel(testCase)
            water=molecule(["O","H","H"], ...
                [0,0,0;.9572,0,0;-.239,.927,0],[1,2,1;1,3,1]);
            calls=0; progress=0;
            testCase.verifyError(@() ...
                kssolv.modeling.packing.PackingBuilder.pack( ...
                {water},100,density=.1,tolerance=.1, ...
                cancelFcn=@cancelAfterFive,progressFcn=@countProgress), ...
                "KSSOLV:Modeling:PackingCancelled");
            testCase.verifyEqual(progress,5);
            function value=cancelAfterFive()
                calls=calls+1; value=calls>5;
            end
            function countProgress(~,~), progress=progress+1; end
        end
    end
end

function result=execute(model,id,p)
result=kssolv.modeling.CommandExecutor.execute(model,id,p);
end
function value=blank()
value=kssolv.analysis.matgenlab.core.Molecule( ...
    strings(1,0),zeros(0,3),charge_spin_check=false);
end
function value=molecule(species,coordinates,bonds)
value=kssolv.analysis.matgenlab.core.Molecule( ...
    cellstr(species),coordinates,charge_spin_check=false, ...
    properties=struct("topology",struct("bonds",bonds, ...
    "origin","source","schemaVersion",1)));
end
function value=minimumIntermolecularDistance(coordinates,ids,box)
value=Inf;
for first=1:size(coordinates,1)-1
    candidates=find(ids(first+1:end)~=ids(first))+first;
    if isempty(candidates), continue, end
    delta=abs(coordinates(candidates,:)-coordinates(first,:));
    delta=min(delta,box-delta);
    value=min(value,min(vecnorm(delta,2,2)));
end
end
function deleteIfPresent(path)
if isfile(path), delete(path); end
end
