classdef ScientificValidityTest < matlab.unittest.TestCase
    %SCIENTIFICVALIDITYTEST Quantitative checks for modeling algorithms.

    methods (Test)
        function quantumDotUsesTrueSupercellCenter(testCase)
            parent = ...
                kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.simpleCubic();
            output = ...
                kssolv.modeling.builders.QuantumDotVoidBuilder.build( ...
                parent, 3.1, "dot", vacuum = 5, maximumAtoms = 1000);
            testCase.verifyGreaterThan(output.num_sites, 1);
            testCase.verifyFalse(any(output.pbc));
            metadata = output.properties.nano_region;
            testCase.verifyEqual( ...
                metadata.source_center_cartesian, ...
                sum(metadata.source_supercell_lattice, 1) / 2, ...
                AbsTol = 1e-12);
            boundsCenter = ...
                (min(output.cart_coords, [], 1) + ...
                max(output.cart_coords, [], 1)) / 2;
            testCase.verifyEqual(boundsCenter, ...
                output.lattice.lengths / 2, AbsTol = 1e-12);
        end

        function nanotubeRadiusFollowsChiralVector(testCase)
            layer = ...
                kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.graphene();
            indices = [4, 2];
            output = kssolv.modeling.builders.NanotubeBuilder.build( ...
                layer, indices, vacuum = 6, maximumAtoms = 2000);
            chiral = indices * layer.lattice.matrix(1:2, :);
            expected = norm(chiral) / (2 * pi);
            testCase.verifyEqual( ...
                output.properties.nanotube.radius, ...
                expected, AbsTol = 1e-12);
            radii = hypot( ...
                output.cart_coords(:, 1) - output.lattice.a / 2, ...
                output.cart_coords(:, 2) - output.lattice.b / 2);
            testCase.verifyEqual(radii, ...
                repmat(expected, output.num_sites, 1), ...
                AbsTol = 1e-10);
        end

        function heterostructureLimitUsesPrincipalStrain(testCase)
            bottom = ...
                kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.graphene();
            top = bottom.copy();
            matrix = top.lattice.matrix;
            matrix(1:2, :) = matrix(1:2, :) * 1.02;
            top = kssolv.analysis.matgenlab.core.Structure( ...
                kssolv.analysis.matgenlab.core.Lattice( ...
                matrix, top.pbc), ...
                top.species_and_occu, top.frac_coords);
            output = ...
                kssolv.modeling.builders.HeterostructureBuilder.build( ...
                bottom, top, maximumStrain = .021);
            expected = abs(1 / 1.02 - 1);
            testCase.verifyEqual( ...
                output.properties.heterostructure.principal_strain, ...
                expected, AbsTol = 1e-12);
            testCase.verifyError(@() ...
                kssolv.modeling.builders.HeterostructureBuilder.build( ...
                bottom, top, maximumStrain = .019), ...
                "KSSOLV:Modeling:HeterostructureMismatch");
        end

        function smallSqsUsesExactEnumeration(testCase)
            model = testCase.disorderedBinary();
            transformation = ...
                kssolv.analysis.matgenlab.transformations. ...
                SQSTransformation(2, [], .1);
            output = transformation.apply_transformation(model);
            testCase.verifyTrue(output.is_ordered);
            testCase.verifyEqual( ...
                output.properties.sqs.search_mode, ...
                "exact-enumeration");
            testCase.verifyEqual( ...
                output.properties.sqs.configuration_count, 2);
        end

        function largeSqsUsesBoundedMonteCarlo(testCase)
            model = testCase.disorderedBinary();
            transformation = ...
                kssolv.analysis.matgenlab.transformations. ...
                SQSTransformation(20, [], .05);
            output = transformation.apply_transformation(model);
            testCase.verifyTrue(output.is_ordered);
            testCase.verifyEqual(output.num_sites, 20);
            testCase.verifyEqual( ...
                output.properties.sqs.search_mode, ...
                "bounded-monte-carlo");
            testCase.verifyEqual( ...
                output.properties.sqs.configuration_count, 184756);
            symbols = string(cellfun(@(site) ...
                site.species_string, output.sites, ...
                "UniformOutput", false));
            testCase.verifyEqual(sum(symbols == "Si"), 10);
            testCase.verifyEqual(sum(symbols == "Ge"), 10);
            testCase.verifyGreaterThanOrEqual( ...
                output.properties.sqs.objective_function, 0);
        end

        function idppConvergesAndKeepsEndpoints(testCase)
            [initial, ending] = ...
                kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.nebEndpoints();
            [images, diagnostics] = ...
                kssolv.modeling.builders.IDPPInterpolator.interpolate( ...
                initial, ending, 5, maximumSteps = 300, ...
                forceTolerance = .05);
            testCase.verifyTrue(diagnostics.converged);
            testCase.verifyLessThanOrEqual( ...
                diagnostics.maximum_force, .05);
            testCase.verifyLessThan( ...
                diagnostics.final_energy, ...
                diagnostics.linear_path_energy);
            testCase.verifyEqual(images{1}.cart_coords, ...
                initial.cart_coords, AbsTol = 1e-12);
            testCase.verifyEqual(images{end}.cart_coords, ...
                ending.cart_coords, AbsTol = 1e-12);
        end
    end

    methods (Static, Access = private)
        function model = disorderedBinary()
            composition = ...
                kssolv.analysis.matgenlab.core.Composition( ...
                {"Si", .5; "Ge", .5});
            model = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 4, {composition}, [0, 0, 0]);
        end
    end
end
