classdef SelectionSetStoreTest < matlab.unittest.TestCase
    methods (Test)
        function setsSurviveCopyMovementAndSiteRemoval(testCase)
            model = kssolv.analysis.matgenlab.core.Molecule( ...
                ["O", "H", "H"], ...
                [0, 0, 0; 0.9572, 0, 0; -0.239, 0.927, 0]);
            [model, saved] = ...
                kssolv.modeling.selection.SelectionSetStore.save( ...
                model, "Hydrogens", [2, 3]);
            testCase.verifyEqual(saved.name, "Hydrogens");
            copied = model.copy();
            copied = copied.translate_sites([2, 3], [0, 0, 1]);
            [indices, missing] = ...
                kssolv.modeling.selection.SelectionSetStore.resolve( ...
                copied, "Hydrogens");
            testCase.verifyEqual(indices, [2, 3]);
            testCase.verifyEmpty(missing);

            copied = copied.remove_sites(2);
            [indices, missing] = ...
                kssolv.modeling.selection.SelectionSetStore.resolve( ...
                copied, "Hydrogens");
            testCase.verifyEqual(indices, 2);
            testCase.verifyNumElements(missing, 1);
            listed = ...
                kssolv.modeling.selection.SelectionSetStore.list(copied);
            testCase.verifyEqual(listed.siteCount, 2);
            testCase.verifyEqual(listed.resolvedCount, 1);
            testCase.verifyEqual(listed.missingCount, 1);
        end

        function deterministicIdsRepairDuplicatesAfterExpansion(testCase)
            model = kssolv.analysis.matgenlab.core.Structure( ...
                eye(3) * 4, {"Si", "Si"}, ...
                [0, 0, 0; 0.5, 0.5, 0.5]);
            [first, ids] = ...
                kssolv.modeling.selection.SelectionSetStore. ...
                ensureSiteIds(model);
            testCase.verifyEqual(ids, ["site-00000001", "site-00000002"]);
            second = first.copy();
            [second, secondIds] = ...
                kssolv.modeling.selection.SelectionSetStore. ...
                ensureSiteIds(second);
            testCase.verifyEqual(secondIds, ids);
            testCase.verifyEqual(second.site_properties.kssolv_site_id, ...
                first.site_properties.kssolv_site_id);
        end

        function validatesNamesAndMissingSets(testCase)
            model = kssolv.analysis.matgenlab.core.Molecule( ...
                "He", [0, 0, 0]);
            testCase.verifyError(@() ...
                kssolv.modeling.selection.SelectionSetStore.save( ...
                model, "", 1), "KSSOLV:Modeling:SelectionSetName");
            testCase.verifyError(@() ...
                kssolv.modeling.selection.SelectionSetStore.resolve( ...
                model, "missing"), ...
                "KSSOLV:Modeling:SelectionSetMissing");
        end
    end
end
