classdef UffSurfaceScorerTest < matlab.unittest.TestCase
    methods (Test)
        function parameterTableCoversPublishedElements(testCase)
            for atomicNumber = 1:103
                element = kssolv.analysis.matgenlab.core.Element. ...
                    fromZ(atomicNumber);
                published = kssolv.modeling.adsorption. ...
                    UffSurfaceScorer.parameter(element);
                testCase.verifyEqual(published.atomicNumber, atomicNumber);
                testCase.verifyFalse(published.fallback);
                testCase.verifyGreaterThan(published.x1, 0);
                testCase.verifyGreaterThan(published.D1, 0);
            end
            testCase.verifyEqual(uffParameter("H").x1, 2.886, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(uffParameter("C").D1, .105, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(uffParameter("O").x1, 3.5, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(uffParameter("Mg").D1, .111, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(uffParameter("Si").x1, 4.295, ...
                AbsTol = 1e-12);
            testCase.verifyEqual(uffParameter("Pt").D1, .080, ...
                AbsTol = 1e-12);
            testCase.verifyError(@()uffParameter("Rf"), ...
                "KSSOLV:Modeling:UffSurfaceElement");
        end

        function pairMinimumMatchesIndependentEquation(testCase)
            distance = sqrt(3.851 * 2.754);
            expected = -sqrt(.105 * .080) * ...
                0.0433641153087705;
            actual = kssolv.modeling.adsorption. ...
                UffSurfaceScorer.pairEnergy("C", "Pt", distance);
            testCase.verifyEqual(actual, expected, AbsTol = 1e-14);
            testCase.verifyEqual( ...
                kssolv.modeling.adsorption.UffSurfaceScorer. ...
                pairEnergy("Pt", "C", distance), actual, ...
                AbsTol = 1e-14);
            testCase.verifyEqual( ...
                kssolv.modeling.adsorption.UffSurfaceScorer. ...
                pairEnergy("C", "Pt", 12), 0, AbsTol = 1e-15);
        end

        function rareGasGraphitePredictionMatchesPrimaryExperiment(testCase)
            dataset = kssolv.modeling.adsorption. ...
                AdsorptionReferenceCatalog.rareGasGraphite();
            testCase.verifyEqual(dataset.doi, "10.1063/1.438015");
            testCase.verifyEqual(string({dataset.records.symbol}), ...
                ["Ne", "Ar", "Kr", "Xe"]);
            testCase.verifyEqual( ...
                [dataset.records.equilibriumDistanceAngstrom], ...
                [3.07, 3.33, 3.36, 3.66], AbsTol = 1e-12);
            testCase.verifyEqual( ...
                [dataset.records.bindingEnergyKelvin], ...
                [384, 1113, 1467, 1928], AbsTol = 1e-12);

            result = kssolv.modeling.adsorption. ...
                AdsorptionPredictiveBenchmark.rareGasGraphite();
            testCase.verifyTrue(result.passed);
            testCase.verifyTrue(result.rankingExact);
            testCase.verifyEqual(result.referenceOrder, ...
                ["Ne", "Ar", "Kr", "Xe"]);
            testCase.verifyEqual(result.predictedOrder, ...
                result.referenceOrder);
            testCase.verifyFalse(result.parameterFittedToReference);
            testCase.verifyLessThanOrEqual(result.energyMaeEv, ...
                result.energyMaeThresholdEv);
            testCase.verifyLessThanOrEqual( ...
                result.distanceMaeAngstrom, ...
                result.distanceMaeThresholdAngstrom);
            testCase.verifyEqual( ...
                [result.entries.predictedBindingEnergyEv], ...
                [0.041431368, 0.102369450, ...
                0.118945568, 0.154738189], AbsTol = 5e-9);
            testCase.verifyEqual( ...
                [result.entries.predictedDistanceAngstrom], ...
                [3.12, 3.42, 3.54, 3.66], AbsTol = 1e-12);
        end

        function periodicImageSumMatchesIndependentOracle(testCase)
            lattice = kssolv.analysis.matgenlab.core.Lattice( ...
                [5,0,0;1,4.5,0;0,0,20], [true,true,false]);
            host = kssolv.analysis.matgenlab.core.Structure( ...
                lattice, "Pt", [.15,.20,.50]);
            adsorbate = oneAtom("H");
            guestFractional = [.72,.67,.62];
            coordinates = guestFractional * lattice.matrix;
            state = kssolv.modeling.adsorption.UffSurfaceScorer. ...
                interactionState(host, adsorbate, coordinates);
            [expected, expectedCount, expectedMinimum] = ...
                independentPtHOracle(host.frac_coords, ...
                guestFractional, lattice.matrix);
            testCase.verifyEqual(state.energy, expected, AbsTol = 1e-14);
            testCase.verifyEqual(state.pairCount, expectedCount);
            testCase.verifyEqual(state.minimumDistance, ...
                expectedMinimum, AbsTol = 1e-12);
            translated = coordinates + lattice.matrix(1, :);
            translatedState = kssolv.modeling.adsorption. ...
                UffSurfaceScorer.interactionState( ...
                host, adsorbate, translated);
            testCase.verifyEqual(translatedState.energy, state.energy, ...
                AbsTol = 1e-14);
            testCase.verifyEqual(translatedState.pairCount, state.pairCount);
        end

        function descriptorIsBuiltInAuditableAndNonOverrideable(testCase)
            descriptor = kssolv.modeling.adsorption. ...
                AdsorptionScoringModel.resolve( ...
                kssolv.modeling.adsorption.UffSurfaceScorer.Id, [], struct());
            testCase.verifyTrue(descriptor.isEnergyModel);
            testCase.verifyEqual(descriptor.scoreUnit, "eV");
            testCase.verifyTrue(descriptor.validated);
            testCase.verifySubstring(descriptor.source, ...
                "10.1021/ja00051a040");
            testCase.verifySubstring(descriptor.validationScope, ...
                "not predictive adsorption-enthalpy accuracy");
            testCase.verifySubstring(descriptor.validationReference, ...
                "10.1063/1.438015");
            testCase.verifyEqual(descriptor.predictiveBenchmarkId, ...
                kssolv.modeling.adsorption. ...
                AdsorptionPredictiveBenchmark.Id);
            testCase.verifySubstring(descriptor.physicalInterpretation, ...
                "van der Waals");
            testCase.verifyError(@() ...
                kssolv.modeling.adsorption.AdsorptionScoringModel.resolve( ...
                descriptor.id, @(varargin)0, struct()), ...
                "KSSOLV:Modeling:AdsorptionScorerConflict");
        end

        function locatorRanksWithBuiltInEnergyWithoutChangingDefault(testCase)
            host = kssolv.modeling.test. ...
                ModelingFunctionalTestUtils.surfaceSlab();
            adsorbate = oneAtom("O");
            geometry = kssolv.modeling.adsorption.AdsorptionLocator. ...
                search(host, adsorbate, SiteTypes = "ontop", ...
                Heights = [2.2, 3.0], RotationStep = 360);
            energy = kssolv.modeling.adsorption.AdsorptionLocator. ...
                search(host, adsorbate, SiteTypes = "ontop", ...
                Heights = [2.2, 3.0], RotationStep = 360, ...
                ScoringModel = ...
                    kssolv.modeling.adsorption.UffSurfaceScorer.Id);
            testCase.verifyFalse(geometry.isEnergyModel);
            testCase.verifyEqual(geometry.energyUnit, "");
            testCase.verifyTrue(energy.isEnergyModel);
            testCase.verifyEqual(energy.energyUnit, "eV");
            testCase.verifyEqual(energy.scoringModel, ...
                kssolv.modeling.adsorption.UffSurfaceScorer.Id);
            testCase.verifyTrue(issorted([energy.candidates.score]));
            testCase.verifyNotEqual([energy.candidates.score], ...
                [geometry.candidates.score]);
            testCase.verifySubstring( ...
                energy.scoringContract.physicalInterpretation, ...
                "interaction potential energy");
            testCase.verifyTrue(any(contains(energy.limitations, ...
                "No electrostatics")));
            applied = kssolv.modeling.adsorption.AdsorptionLocator. ...
                applyCandidate(host, adsorbate, energy.candidates(1));
            metadata = applied.structure_properties.adsorptionCandidate;
            testCase.verifyEqual(metadata.scoringContract.source, ...
                energy.scoringContract.source);
            testCase.verifyEqual( ...
                metadata.scoringContract.validationReference, ...
                energy.scoringContract.validationReference);
        end
    end
end

function value = uffParameter(symbol)
value = kssolv.modeling.adsorption.UffSurfaceScorer.parameter(symbol);
end

function molecule = oneAtom(symbol)
molecule = kssolv.analysis.matgenlab.core.Molecule( ...
    string(symbol), [0,0,0], charge_spin_check = false);
end

function [energy, count, minimumDistance] = independentPtHOracle( ...
        hostFractional, guestFractional, lattice)
x = sqrt(2.754 * 2.886);
depth = sqrt(.080 * .044);
conversion = 0.0433641153087705;
energy = 0;
count = 0;
minimumDistance = Inf;
for first = -4:4
    for second = -4:4
        translation = [first, second, 0];
        distance = norm((guestFractional - hostFractional - ...
            translation) * lattice);
        if distance >= 12, continue, end
        count = count + 1;
        minimumDistance = min(minimumDistance, distance);
        ratio6 = (x / distance)^6;
        switchValue = 1;
        if distance > 10
            t = (distance - 10) / 2;
            switchValue = 1 - 10*t^3 + 15*t^4 - 6*t^5;
        end
        energy = energy + depth * (ratio6^2 - 2*ratio6) * ...
            switchValue * conversion;
    end
end
end
